### ISSUE TITLE
Please complete the data for running self-test, or the link to download the data

### ISSUE THREAD

**Issue by gzygzy9211** [NVIDIA/DALI#10]
dali/image/jpeg_test.cc: 34
there are image files mentioned "420.jpg", "422.jpg", ...
Please complete these image files and ANY OTHER data for the self testing so we can ensure the functionality of DALI.

Thank you very much!

**Comment by JanuszL** [comment]
Hi,
Files mentioned there cannot be redistributed due to licensing. Some examples also uses training data sets that cannot be distributed with Dali.
We plan to create license free set of images so others could use it during own development.

**Comment by gzygzy9211** [comment]
So could you please make that happen as soon as possible as self-testing is CRITICAL? @JanuszL 

> We plan to create license free set of images so others could use it during own development.

**Comment by JanuszL** [comment]
Tracked internally in DALI-132

**Comment by JanuszL** [comment]
PR is created https://github.com/NVIDIA/DALI/pull/69

**Comment by JanuszL** [comment]
We have created a repo with the test data - https://github.com/NVIDIA/DALI_extra. We plan to gradually move all tests to it.

**Comment by JanuszL** [comment]
https://github.com/NVIDIA/DALI/pull/1056 should fulfill this request.
