### ISSUE TITLE
Can DALI help make CPU time overlapped by GPU time ?

### ISSUE THREAD

**Issue by Lausannen** [NVIDIA/DALI#1002]
Hi !  I tested my model running time. The result is shown in four parts. I use Pytorch .
Part 1 : Get batch from dataloader costed almost 4 sec
Part 2 : Transfer data from CPU to GPU costed 4 sec
Part 3 : Model forward costed 2-3 sec
Part 4 : Model backward costed 6-7 sec
I think Part 1-4 are executed sequentially. That means if Part 1 is runned in CPU, all GPUs will wait for this part. Can DALI help make Part 1 CPU time overlapped by Part 2-4 GPU time, which means GPU will always be busy. Thank you very much!!!

**Comment by klecki** [comment]
Hi. Yes, DALI can do the Part 1 and 2 asynchronously. It will use a worker threads to prepare queue of batches and return them for the framework when needed. It should be possible to overlap loading and transfer to GPU with your forward and backward pass.
