### ISSUE TITLE
Parallely perform pre-processing and data loading

### ISSUE THREAD

**Issue by ashwinRameshBabu** [NVIDIA/DALI#1016]
Hello all

I was building a DALI pipeline where it loads a video using VideoReader and apply transformation on the data such as crop, jitter, transpose etc. after which it is sent to the model.  I would like to see if there is a way where I can parallelize this process.  To be more clear, I would like to see if we can parallelize in such a way that when the transformation is applied on the data, the dataloader can simultaneously load the next set of frames. 

Thanks in advance

Ashwin

**Comment by a-sansanwal** [comment]
If I understand your question correctly, then this might be what you're looking for.

> prefetch_queue_depth (int, optional, default = 1) – Specifies the number of batches prefetched by the internal Loader. To be increased when pipeline processing is CPU stage-bound, trading memory consumption for better interleaving with the Loader thread.

**Comment by JanuszL** [comment]
Hi,
@a-sansanwal is right, DALI does prefetch in the background by the default. You can check [DALI pipeline API](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/api.html#nvidia.dali.pipeline.Pipeline). By default prefetch_queue_depth is set to 2 and DALI works in asynchronous mode. So when you are consuming one batch of data the second one should be prepared in the background.
One side note - currently DALI doesn't support jitter for sequences, but crop and transpose should work.

**Comment by ashwinRameshBabu** [comment]
Hello @JanuszL Thank you so much for your response.  I did look into how to parallelize the data transfers and the computation by increasing the prefetch_queue_depth.  I did not see any difference with higher prefetch_queue_depth.  I ran the code with the nvidia profiler and I observed the following, 

![stream](https://user-images.githubusercontent.com/15481902/60615121-437c3180-9d83-11e9-8434-720134a7c04c.png)

If you see in the picture, sream 14 and stream 16 waits for the data transfer(HtoD) to happen to further execute.  Please let me know where I am going wrong.  Also, if further clarification is required on the process.

**Comment by JanuszL** [comment]
Hi,
Can you provide the code you are actually running? Is there anything that consumes this data or it is only DALI pipeline?
Even when the pipeline is executed on the GPU it needs to be transferred there from the CPU first (I guess it may be the case here). In the case of the VideoReader, video data need to be moved to the GPU first and then processed, but you can do something in parallel. Also, outputs from DALI to native frameworks tensors are transferred in a blocking way - if the last operator is on the GPU then data is already in the GPU and transfer DtoD is fast, if your data is on CPU then HtoD happens and it is more time-consuming.
Yet another thing, if you just using `pipeline.run()` then DALI will launch execution and block until the results are ready. In https://github.com/NVIDIA/DALI/pull/1028 we improved documentation of that and made internal API public that allows you to launch the pipeline, do something and get the results.

**Comment by ashwinRameshBabu** [comment]
Hi @JanuszL  thanks for your quick response.  I am currently in building stage and currently there is **only** DALI pipeline.  Since my requirement was to parallelize the data transfers and and the rest of the computing that include DALI pre processing, i was checking on the profiler with just the DALI pipeline.  Any recommendation to parallelize these process is appriciated.

Thanks
Ashwin

**Comment by JanuszL** [comment]
The main goal is to parallelize data processing with the other activities. So even though you see computations serialized with data transfer on DALI side it doesn't mean that you cannot do anything in parallel. And this is the mail goal of DALI.
