### ISSUE TITLE
Can I use DALI on Nvidia TX2

### ISSUE THREAD

**Issue by KleinXin** [NVIDIA/DALI#1022]
thx

**Comment by JanuszL** [comment]
Hi,
Now DALI support for ARM platform is rather elementary. You can build the native part using [this guide](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/compilation.html#cross-compiling-dali-c-api-for-aarch64-linux-docker) but without python bindings. We tested it on Xavier platform and it passes the basic unit tests (you can also check [this GTC19 talk](https://developer.nvidia.com/gtc/2019/video/S9818/video) and [the blog post](https://devblogs.nvidia.com/drive-agx-accelerators-object-detection/)).
So feel free to experiment and we encourage you to contribute to DALI if you manage to solve some problem with launching DALI on Nvidia TX2.

**Comment by klecki** [comment]
Just FYI the resize kernels have some troubles working on Xavier (we suspect that using unified memory may be the cause and we are working to fix it).

**Comment by klecki** [comment]
Updating my previous message, #1026 fixes the issues with resampling on aarch64 platform, this change is available in weekly & nightly builds and will be part of upcoming 0.12 release.

**Comment by KleinXin** [comment]
@JanuszL & @klecki Thank you for your reply！
What is the fps of Resnet18 on TX2？
According to my test, it is about 50fps.

**Comment by JanuszL** [comment]
Hi,
We haven't checked the actual performance of TX2 with DALI. You can try to check https://devblogs.nvidia.com/jetpack-doubles-jetson-inference-perf/ or other Nvidia materials regarding TX2 performance.
