### ISSUE TITLE
make error of DALI while building jpeg_mem.cc.o

### ISSUE THREAD

**Issue by woshifzh** [NVIDIA/DALI#1027]
Hi, I have problems while building the project. Here's my cmake info:
-- DALI version: 0.12.0dev
-- Build configuration: Release
/home/xiaoju/tensorrt-server/env/cuda-9.0
nvJPEG found in /home/xiaoju/DALI/cuda-linux64-nvjpeg/include
-- Found OpenCV: /usr/local/include;/usr/local/include/opencv (found suitable version "3.4.6", minimum required is "3.0")
OpenCV libraries: opencv_core;opencv_imgproc;opencv_imgcodecs
-- Failed to find LLVM FileCheck
-- git Version: v1.4.0-505be96a
-- Version: 1.4.0
-- Performing Test HAVE_STD_REGEX -- success
-- Performing Test HAVE_GNU_POSIX_REGEX -- failed to compile
-- Performing Test HAVE_POSIX_REGEX -- success
-- Performing Test HAVE_STEADY_CLOCK -- success
Using libjpeg-turbo at /usr/lib64/libjpeg.so
-- pybind11 v2.2.4
-- Building WITHOUT LMDB support
-- Enabling TensorFlow TFRecord file format support
-- CUDA supported archs: 35;50;52;60;61;70
-- CUDA targeted archs: 35;50;52;60;61;70
-- Generated gencode flags:  -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_70,code=compute_70
-- Exclude libs 'libcudart_static.a:libnvjpeg_static.a:libnppicom_static.a:libnppicc_static.a:libnppig_static.a:libnppc_static.a:libculibos.a:libopencv_core.a:libopencv_imgproc.a:libopencv_highgui.a:libopencv_imgcodecs.a:liblibwebp.a:libittnotify.a:libpng.a:liblibtiff.a:liblibjasper.a:libIlmImf.a:liblibjpeg-turbo.a:libprotobuf.a:libsupc++.a:libstdc++.a:libstdc++_nonshared.a'
-- Adding dependencies to dali: '/home/xiaoju/tensorrt-server/env/cuda-9.0/lib64/libcudart_static.a;-lpthread;dl;/usr/lib64/librt.so;/home/xiaoju/DALI/cuda-linux64-nvjpeg/lib64/libnvjpeg_static.a;/home/xiaoju/tensorrt-server/env/cuda-9.0/lib64/libnppicom_static.a;/home/xiaoju/tensorrt-server/env/cuda-9.0/lib64/libnppicc_static.a;/home/xiaoju/tensorrt-server/env/cuda-9.0/lib64/libnppig_static.a;/home/xiaoju/tensorrt-server/env/cuda-9.0/lib64/libnppc_static.a;/home/xiaoju/tensorrt-server/env/cuda-9.0/lib64/libculibos.a;opencv_core;opencv_imgproc;opencv_imgcodecs;/usr/lib64/libjpeg.so;avformat;avformat;avcodec;avfilter;avutil;/usr/local/lib/libprotobuf.a'
-- Adding dependencies to dali_test.bin: 'dali'
-- Adding dependencies to dali_benchmark.bin: 'dali'
-- Installing sources for dali_tf: /home/xiaoju/DALI/dali/tensorflow/daliop.cc
-- Adding dependencies to backend_impl: 'dali'
-- Configuring done
-- Generating done
-- Build files have been written to: /home/xiaoju/DALI/build

And here's my make info with 'make VERBOSE=1':
/usr/bin/cmake3 -S/home/xiaoju/DALI -B/home/xiaoju/DALI/build --check-build-system CMakeFiles/Makefile.cmake 0
Re-run cmake file: Makefile older than: dali/CMakeFiles/dali.dir/pipeline/operators/reader/nvdecoder/dali_generated_imgproc.cu.o.depend
-- DALI version: 0.12.0dev
-- Build configuration: Release
/home/xiaoju/tensorrt-server/env/cuda-9.0
nvJPEG found in /home/xiaoju/DALI/cuda-linux64-nvjpeg/include
-- Found OpenCV: /usr/local/include;/usr/local/include/opencv (found suitable version "3.4.6", minimum required is "3.0")
OpenCV libraries: opencv_core;opencv_imgproc;opencv_imgcodecs
-- Failed to find LLVM FileCheck
-- git Version: v1.4.0-505be96a
-- Version: 1.4.0
-- Performing Test HAVE_STD_REGEX -- success
-- Performing Test HAVE_GNU_POSIX_REGEX -- failed to compile
-- Performing Test HAVE_POSIX_REGEX -- success
-- Performing Test HAVE_STEADY_CLOCK -- success
Using libjpeg-turbo at /usr/lib64/libjpeg.so
-- pybind11 v2.2.4
-- Building WITHOUT LMDB support
-- Enabling TensorFlow TFRecord file format support
-- CUDA supported archs: 35;50;52;60;61;70
-- CUDA targeted archs: 35;50;52;60;61;70
-- Generated gencode flags:  -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_70,code=compute_70
-- Exclude libs 'libcudart_static.a:libnvjpeg_static.a:libnppicom_static.a:libnppicc_static.a:libnppig_static.a:libnppc_static.a:libculibos.a:libopencv_core.a:libopencv_imgproc.a:libopencv_highgui.a:libopencv_imgcodecs.a:liblibwebp.a:libittnotify.a:libpng.a:liblibtiff.a:liblibjasper.a:libIlmImf.a:liblibjpeg-turbo.a:libprotobuf.a:libsupc++.a:libstdc++.a:libstdc++_nonshared.a'
-- Adding dependencies to dali: '/home/xiaoju/tensorrt-server/env/cuda-9.0/lib64/libcudart_static.a;-lpthread;dl;/usr/lib64/librt.so;/home/xiaoju/DALI/cuda-linux64-nvjpeg/lib64/libnvjpeg_static.a;/home/xiaoju/tensorrt-server/env/cuda-9.0/lib64/libnppicom_static.a;/home/xiaoju/tensorrt-server/env/cuda-9.0/lib64/libnppicc_static.a;/home/xiaoju/tensorrt-server/env/cuda-9.0/lib64/libnppig_static.a;/home/xiaoju/tensorrt-server/env/cuda-9.0/lib64/libnppc_static.a;/home/xiaoju/tensorrt-server/env/cuda-9.0/lib64/libculibos.a;opencv_core;opencv_imgproc;opencv_imgcodecs;/usr/lib64/libjpeg.so;avformat;avformat;avcodec;avfilter;avutil;/usr/local/lib/libprotobuf.a'
-- Adding dependencies to dali_test.bin: 'dali'
-- Adding dependencies to dali_benchmark.bin: 'dali'
-- Installing sources for dali_tf: /home/xiaoju/DALI/dali/tensorflow/daliop.cc
-- Adding dependencies to backend_impl: 'dali'
-- Configuring done
-- Generating done
-- Build files have been written to: /home/xiaoju/DALI/build
/usr/bin/cmake3 -E cmake_progress_start /home/xiaoju/DALI/build/CMakeFiles /home/xiaoju/DALI/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory `/home/xiaoju/DALI/build'
make -f dali/kernels/CMakeFiles/dali_kernels.dir/build.make dali/kernels/CMakeFiles/dali_kernels.dir/depend
make[2]: Entering directory `/home/xiaoju/DALI/build'
cd /home/xiaoju/DALI/build && /usr/bin/cmake3 -E cmake_depends "Unix Makefiles" /home/xiaoju/DALI /home/xiaoju/DALI/dali/kernels /home/xiaoju/DALI/build /home/xiaoju/DALI/build/dali/kernels /home/xiaoju/DALI/build/dali/kernels/CMakeFiles/dali_kernels.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/home/xiaoju/DALI/build'
make -f dali/kernels/CMakeFiles/dali_kernels.dir/build.make dali/kernels/CMakeFiles/dali_kernels.dir/build
make[2]: Entering directory `/home/xiaoju/DALI/build'
[  0%] Linking CXX static library libdali_kernels.a
cd /home/xiaoju/DALI/build/dali/kernels && /usr/bin/cmake3 -P CMakeFiles/dali_kernels.dir/cmake_clean_target.cmake
cd /home/xiaoju/DALI/build/dali/kernels && /usr/bin/cmake3 -E cmake_link_script CMakeFiles/dali_kernels.dir/link.txt --verbose=1
/bin/ar qc libdali_kernels.a  CMakeFiles/dali_kernels.dir/imgproc/resample/resampling_impl_cpu.cc.o CMakeFiles/dali_kernels.dir/imgproc/resample/resampling_setup.cc.o CMakeFiles/dali_kernels.dir/alloc.cc.o CMakeFiles/dali_kernels.dir/dummy.cc.o CMakeFiles/dali_kernels.dir/common/dali_kernels_generated_scatter_gather.cu.o CMakeFiles/dali_kernels.dir/imgproc/resample/dali_kernels_generated_resampling_batch.cu.o CMakeFiles/dali_kernels.dir/imgproc/resample/dali_kernels_generated_resampling_filters.cu.o
/bin/ranlib libdali_kernels.a
make[2]: Leaving directory `/home/xiaoju/DALI/build'
[  2%] Built target dali_kernels
make -f dali/core/CMakeFiles/dynlink_cuda.dir/build.make dali/core/CMakeFiles/dynlink_cuda.dir/depend
make[2]: Entering directory `/home/xiaoju/DALI/build'
cd /home/xiaoju/DALI/build && /usr/bin/cmake3 -E cmake_depends "Unix Makefiles" /home/xiaoju/DALI /home/xiaoju/DALI/dali/core /home/xiaoju/DALI/build /home/xiaoju/DALI/build/dali/core /home/xiaoju/DALI/build/dali/core/CMakeFiles/dynlink_cuda.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/home/xiaoju/DALI/build'
make -f dali/core/CMakeFiles/dynlink_cuda.dir/build.make dali/core/CMakeFiles/dynlink_cuda.dir/build
make[2]: Entering directory `/home/xiaoju/DALI/build'
make[2]: Nothing to be done for `dali/core/CMakeFiles/dynlink_cuda.dir/build'.
make[2]: Leaving directory `/home/xiaoju/DALI/build'
[  2%] Built target dynlink_cuda
make -f dali/core/CMakeFiles/dali_core.dir/build.make dali/core/CMakeFiles/dali_core.dir/depend
make[2]: Entering directory `/home/xiaoju/DALI/build'
cd /home/xiaoju/DALI/build && /usr/bin/cmake3 -E cmake_depends "Unix Makefiles" /home/xiaoju/DALI /home/xiaoju/DALI/dali/core /home/xiaoju/DALI/build /home/xiaoju/DALI/build/dali/core /home/xiaoju/DALI/build/dali/core/CMakeFiles/dali_core.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/home/xiaoju/DALI/build'
make -f dali/core/CMakeFiles/dali_core.dir/build.make dali/core/CMakeFiles/dali_core.dir/build
make[2]: Entering directory `/home/xiaoju/DALI/build'
make[2]: Nothing to be done for `dali/core/CMakeFiles/dali_core.dir/build'.
make[2]: Leaving directory `/home/xiaoju/DALI/build'
[  3%] Built target dali_core
make -f dali/CMakeFiles/dali_operators.dir/build.make dali/CMakeFiles/dali_operators.dir/depend
make[2]: Entering directory `/home/xiaoju/DALI/build'
cd /home/xiaoju/DALI/build && /usr/bin/cmake3 -E cmake_depends "Unix Makefiles" /home/xiaoju/DALI /home/xiaoju/DALI/dali /home/xiaoju/DALI/build /home/xiaoju/DALI/build/dali /home/xiaoju/DALI/build/dali/CMakeFiles/dali_operators.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/home/xiaoju/DALI/build'
make -f dali/CMakeFiles/dali_operators.dir/build.make dali/CMakeFiles/dali_operators.dir/build
make[2]: Entering directory `/home/xiaoju/DALI/build'
[  4%] Linking CXX static library ../lib/libdali_operators.a
cd /home/xiaoju/DALI/build/dali && /usr/bin/cmake3 -P CMakeFiles/dali_operators.dir/cmake_clean_target.cmake
cd /home/xiaoju/DALI/build/dali && /usr/bin/cmake3 -E cmake_link_script CMakeFiles/dali_operators.dir/link.txt --verbose=1
/bin/ar qc ../lib/libdali_operators.a  CMakeFiles/dali_operators.dir/pipeline/operators/color/color_twist.cc.o CMakeFiles/dali_operators.dir/pipeline/operators/color_space/color_space_conversion.cc.o CMakeFiles/dali_operators.dir/pipeline/operators/crop/bbox_crop.cc.o CMakeFiles/dali_operators.dir/pipeline/operators/crop/crop.cc.o CMakeFiles/dali_operators.dir/pipeline/operators/crop/crop_attr.cc.o CMakeFiles/dali_operators.dir/pipeline/operators/crop/random_crop_attr.cc.o CMakeFiles/dali_operators.dir/pipeline/operators/crop/slice.cc.o CMakeFiles/dali_operators.dir/pipeline/operators/crop/slice_base.cc.o CMakeFiles/dali_operators.dir/pipeline/operators/detection/box_encoder.cc.o CMakeFiles/dali_operators.dir/pipeline/operators/detection/random_crop.cc.o CMakeFiles/dali_operators.dir/pipeline/operators/displacement/displacement_filter.cc.o CMakeFiles/dali_operators.dir/pipeline/operators/displacement/jitter.cc.o CMakeFiles/dali_operators.dir/pipeline/operators/displacement/rotate.cc.o CMakeFiles/dali_operators.dir/pipeline/operators/displacement/sphere.cc.o CMakeFiles/dali_operators.dir/pipeline/operators/displacement/warpaffine.cc.o CMakeFiles/dali_operators.dir/pipeline/operators/displacement/water.cc.o CMakeFiles/dali_operators.dir/pipeline/operators/fused/crop_mirror_normalize.cc.o CMakeFiles/dali_operators.dir/pipeline/operators/fused/normalize_permute.cc.o CMakeFiles/dali_operators.dir/pipeline/operators/fused/resize_crop_mirror.cc.o CMakeFiles/dali_operators.dir/pipeline/operators/geometric/bb_flip.cc.o CMakeFiles/dali_operators.dir/pipeline/operators/geometric/flip.cc.o CMakeFiles/dali_operators.dir/pipeline/operators/optical_flow/turing_of/optical_flow_turing.cc.o CMakeFiles/dali_operators.dir/pipeline/operators/optical_flow/optical_flow.cc.o CMakeFiles/dali_operators.dir/pipeline/operators/paste/bbox_paste.cc.o CMakeFiles/dali_operators.dir/pipeline/operators/paste/paste.cc.o CMakeFiles/dali_operators.dir/pipeline/operators/resize/random_resized_crop.cc.o CMakeFiles/dali_operators.dir/pipeline/operators/resize/resize.cc.o CMakeFiles/dali_operators.dir/pipeline/operators/resize/resize_base.cc.o CMakeFiles/dali_operators.dir/pipeline/operators/sequence/element_extract.cc.o CMakeFiles/dali_operators.dir/pipeline/operators/support/random/coin_flip.cc.o CMakeFiles/dali_operators.dir/pipeline/operators/support/random/uniform.cc.o CMakeFiles/dali_operators.dir/pipeline/operators/transpose/cutt/cutt.cc.o CMakeFiles/dali_operators.dir/pipeline/operators/transpose/cutt/cuttGpuModel.cc.o CMakeFiles/dali_operators.dir/pipeline/operators/transpose/cutt/cuttplan.cc.o CMakeFiles/dali_operators.dir/pipeline/operators/transpose/transpose.cc.o CMakeFiles/dali_operators.dir/pipeline/operators/util/cast.cc.o CMakeFiles/dali_operators.dir/pipeline/operators/util/copy.cc.o CMakeFiles/dali_operators.dir/pipeline/operators/util/dummy_op.cc.o CMakeFiles/dali_operators.dir/pipeline/operators/util/dump_image.cc.o CMakeFiles/dali_operators.dir/pipeline/operators/util/external_source.cc.o CMakeFiles/dali_operators.dir/pipeline/operators/python_function/util/copy_with_stride.cc.o CMakeFiles/dali_operators.dir/pipeline/operators/color/dali_operators_generated_color_twist.cu.o CMakeFiles/dali_operators.dir/pipeline/operators/color_space/dali_operators_generated_color_space_conversion.cu.o CMakeFiles/dali_operators.dir/pipeline/operators/crop/dali_operators_generated_crop.cu.o CMakeFiles/dali_operators.dir/pipeline/operators/crop/dali_operators_generated_slice.cu.o CMakeFiles/dali_operators.dir/pipeline/operators/crop/dali_operators_generated_slice_base.cu.o CMakeFiles/dali_operators.dir/pipeline/operators/detection/dali_operators_generated_box_encoder.cu.o CMakeFiles/dali_operators.dir/pipeline/operators/displacement/dali_operators_generated_jitter.cu.o CMakeFiles/dali_operators.dir/pipeline/operators/displacement/dali_operators_generated_rotate.cu.o CMakeFiles/dali_operators.dir/pipeline/operators/displacement/dali_operators_generated_sphere.cu.o CMakeFiles/dali_operators.dir/pipeline/operators/displacement/dali_operators_generated_warpaffine.cu.o CMakeFiles/dali_operators.dir/pipeline/operators/displacement/dali_operators_generated_water.cu.o CMakeFiles/dali_operators.dir/pipeline/operators/fused/dali_operators_generated_crop_mirror_normalize.cu.o CMakeFiles/dali_operators.dir/pipeline/operators/fused/dali_operators_generated_normalize_permute.cu.o CMakeFiles/dali_operators.dir/pipeline/operators/geometric/dali_operators_generated_bb_flip.cu.o CMakeFiles/dali_operators.dir/pipeline/operators/geometric/dali_operators_generated_flip.cu.o CMakeFiles/dali_operators.dir/pipeline/operators/optical_flow/turing_of/dali_operators_generated_optical_flow_turing.cu.o CMakeFiles/dali_operators.dir/pipeline/operators/paste/dali_operators_generated_paste.cu.o CMakeFiles/dali_operators.dir/pipeline/operators/resize/dali_operators_generated_random_resized_crop.cu.o CMakeFiles/dali_operators.dir/pipeline/operators/resize/dali_operators_generated_resize.cu.o CMakeFiles/dali_operators.dir/pipeline/operators/sequence/dali_operators_generated_element_extract.cu.o CMakeFiles/dali_operators.dir/pipeline/operators/transpose/cutt/dali_operators_generated_CudaMemcpy.cu.o CMakeFiles/dali_operators.dir/pipeline/operators/transpose/cutt/dali_operators_generated_CudaUtils.cu.o CMakeFiles/dali_operators.dir/pipeline/operators/transpose/cutt/dali_operators_generated_cuttGpuModelKernel.cu.o CMakeFiles/dali_operators.dir/pipeline/operators/transpose/cutt/dali_operators_generated_cuttkernel.cu.o CMakeFiles/dali_operators.dir/pipeline/operators/transpose/dali_operators_generated_transpose.cu.o CMakeFiles/dali_operators.dir/pipeline/operators/util/dali_operators_generated_cast.cu.o CMakeFiles/dali_operators.dir/pipeline/operators/util/dali_operators_generated_copy.cu.o CMakeFiles/dali_operators.dir/pipeline/operators/util/dali_operators_generated_dummy_op.cu.o CMakeFiles/dali_operators.dir/pipeline/operators/util/dali_operators_generated_dump_image.cu.o CMakeFiles/dali_operators.dir/pipeline/operators/util/dali_operators_generated_external_source.cu.o CMakeFiles/dali_operators.dir/pipeline/operators/util/dali_operators_generated_make_contiguous.cu.o
/bin/ranlib ../lib/libdali_operators.a
make[2]: Leaving directory `/home/xiaoju/DALI/build'
[ 27%] Built target dali_operators
make -f dali/pipeline/operators/reader/parser/CMakeFiles/TF_PROTO.dir/build.make dali/pipeline/operators/reader/parser/CMakeFiles/TF_PROTO.dir/depend
make[2]: Entering directory `/home/xiaoju/DALI/build'
cd /home/xiaoju/DALI/build && /usr/bin/cmake3 -E cmake_depends "Unix Makefiles" /home/xiaoju/DALI /home/xiaoju/DALI/dali/pipeline/operators/reader/parser /home/xiaoju/DALI/build /home/xiaoju/DALI/build/dali/pipeline/operators/reader/parser /home/xiaoju/DALI/build/dali/pipeline/operators/reader/parser/CMakeFiles/TF_PROTO.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/home/xiaoju/DALI/build'
make -f dali/pipeline/operators/reader/parser/CMakeFiles/TF_PROTO.dir/build.make dali/pipeline/operators/reader/parser/CMakeFiles/TF_PROTO.dir/build
make[2]: Entering directory `/home/xiaoju/DALI/build'
make[2]: Nothing to be done for `dali/pipeline/operators/reader/parser/CMakeFiles/TF_PROTO.dir/build'.
make[2]: Leaving directory `/home/xiaoju/DALI/build'
[ 29%] Built target TF_PROTO
make -f dali/CMakeFiles/libdali.map.dir/build.make dali/CMakeFiles/libdali.map.dir/depend
make[2]: Entering directory `/home/xiaoju/DALI/build'
cd /home/xiaoju/DALI/build && /usr/bin/cmake3 -E cmake_depends "Unix Makefiles" /home/xiaoju/DALI /home/xiaoju/DALI/dali /home/xiaoju/DALI/build /home/xiaoju/DALI/build/dali /home/xiaoju/DALI/build/dali/CMakeFiles/libdali.map.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/home/xiaoju/DALI/build'
make -f dali/CMakeFiles/libdali.map.dir/build.make dali/CMakeFiles/libdali.map.dir/build
make[2]: Entering directory `/home/xiaoju/DALI/build'
make[2]: Nothing to be done for `dali/CMakeFiles/libdali.map.dir/build'.
make[2]: Leaving directory `/home/xiaoju/DALI/build'
[ 29%] Built target libdali.map
make -f dali/pipeline/CMakeFiles/DALI_PROTO.dir/build.make dali/pipeline/CMakeFiles/DALI_PROTO.dir/depend
make[2]: Entering directory `/home/xiaoju/DALI/build'
cd /home/xiaoju/DALI/build && /usr/bin/cmake3 -E cmake_depends "Unix Makefiles" /home/xiaoju/DALI /home/xiaoju/DALI/dali/pipeline /home/xiaoju/DALI/build /home/xiaoju/DALI/build/dali/pipeline /home/xiaoju/DALI/build/dali/pipeline/CMakeFiles/DALI_PROTO.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/home/xiaoju/DALI/build'
make -f dali/pipeline/CMakeFiles/DALI_PROTO.dir/build.make dali/pipeline/CMakeFiles/DALI_PROTO.dir/build
make[2]: Entering directory `/home/xiaoju/DALI/build'
make[2]: Nothing to be done for `dali/pipeline/CMakeFiles/DALI_PROTO.dir/build'.
make[2]: Leaving directory `/home/xiaoju/DALI/build'
[ 29%] Built target DALI_PROTO
make -f dali/CMakeFiles/dali.dir/build.make dali/CMakeFiles/dali.dir/depend
make[2]: Entering directory `/home/xiaoju/DALI/build'
cd /home/xiaoju/DALI/build && /usr/bin/cmake3 -E cmake_depends "Unix Makefiles" /home/xiaoju/DALI /home/xiaoju/DALI/dali /home/xiaoju/DALI/build /home/xiaoju/DALI/build/dali /home/xiaoju/DALI/build/dali/CMakeFiles/dali.dir/DependInfo.cmake --color=
make[2]: Leaving directory `/home/xiaoju/DALI/build'
make -f dali/CMakeFiles/dali.dir/build.make dali/CMakeFiles/dali.dir/build
make[2]: Entering directory `/home/xiaoju/DALI/build'
[ 29%] Building CXX object dali/CMakeFiles/dali.dir/image/jpeg_mem.cc.o
cd /home/xiaoju/DALI/build/dali && /home/xiaoju/tensorrt-server/env/gcc52/bin/g++  -DDALI_BUILD_PROTO3=1 -DDALI_USE_JPEG_TURBO -DDALI_USE_NVJPEG -DFFMPEG_ENABLED=1 -DHAVE_AVBSFCONTEXT=1 -DHAVE_AVSTREAM_CODECPAR=1 -DJPEG_TURBO_ENABLED=1 -DLMDB_ENABLED=0 -DNVDEC_ENABLED=1 -DNVJPEG_ENABLED=1 -DNVML_ENABLED=1 -DNVOF_ENABLED=1 -DPYTHON_ENABLED=1 -DTENSORFLOW_ENABLED=0 -Ddali_EXPORTS -I/home/xiaoju/DALI/build -I/home/xiaoju/DALI/include -I/home/xiaoju/DALI -I/home/xiaoju/tensorrt-server/env/cuda-9.0/include -I/usr/include/ffmpeg -I/home/xiaoju/DALI/third_party/boost/preprocessor/include -I/home/xiaoju/DALI/third_party/rapidjson/include -I/home/xiaoju/DALI/third_party/turing_of -isystem /home/xiaoju/DALI/cuda-linux64-nvjpeg/include -isystem /usr/local/include -isystem /usr/local/include/opencv -isystem /home/xiaoju/DALI/third_party/googletest/googletest/include -isystem /home/xiaoju/DALI/third_party/benchmark/include/benchmark  -Wall -Wno-unused-variable -Wno-unused-function -fno-strict-aliasing -fPIC -fvisibility=hidden -O2 -DNDEBUG -O2 -DDALI_DEBUG=0 -fPIC   -std=c++14 -o CMakeFiles/dali.dir/image/jpeg_mem.cc.o -c /home/xiaoju/DALI/dali/image/jpeg_mem.cc
/home/xiaoju/DALI/dali/image/jpeg_mem.cc: In function ‘dali::uint8* dali::jpeg::{anonymous}::UncompressLow(const void*, dali::jpeg::{anonymous}::FewerArgsForCompiler*)’:
/home/xiaoju/DALI/dali/image/jpeg_mem.cc:215:52: error: ‘jpeg_crop_scanline’ was not declared in this scope
     jpeg_crop_scanline(&cinfo, &crop_x, &crop_width);
                                                    ^
/home/xiaoju/DALI/dali/image/jpeg_mem.cc:218:65: error: ‘jpeg_skip_scanlines’ was not declared in this scope
     skipped_scanlines = jpeg_skip_scanlines(&cinfo, flags.crop_y);
                                                                 ^
/home/xiaoju/DALI/dali/image/jpeg_mem.cc:373:79: error: ‘jpeg_skip_scanlines’ was not declared in this scope
                         cinfo.output_height - flags.crop_y - flags.crop_height);
                                                                               ^
make[2]: *** [dali/CMakeFiles/dali.dir/image/jpeg_mem.cc.o] Error 1
make[2]: Leaving directory `/home/xiaoju/DALI/build'
make[1]: *** [dali/CMakeFiles/dali.dir/all] Error 2
make[1]: Leaving directory `/home/xiaoju/DALI/build'
make: *** [all] Error 2

**Comment by jantonguirao** [comment]
Hi @woshifzh,

`jpeg_skip_scanlines` is part of libjpeg-turbo. Which version of `libjpeg-turbo` do you have?
DALI requires libjpeg-turbo `1.5.x` (see https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/compilation.html)

**Comment by woshifzh** [comment]
> Hi @woshifzh,
> 
> `jpeg_skip_scanlines` is part of libjpeg-turbo. Which version of `libjpeg-turbo` do you have?
> DALI requires libjpeg-turbo `1.5.x` (see https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/compilation.html)

Thank you so much, that error's fixed
