### ISSUE TITLE
detection_pipeline boxes and labels not same

### ISSUE THREAD

**Issue by guanfuchen** [NVIDIA/DALI#1046]
I use the code [detection_pipeline](https://github.com/NVIDIA/DALI/blob/master/docs/examples/detection_pipeline.ipynb) for test, and I use dataiterator to get epoch data for looping the pipline, sometimes the boxes and labels N is not same? Is there some need for sync?

**Comment by awolant** [comment]
Hi, thanks for reporting the issue. There should be no need for any synchronization. Could you share some code sample, so I could reproduce it easily?

**Comment by guanfuchen** [comment]
I use the code wrongly, I get the change from TensorCPUList to array, and sometimes it can not work in the right size.
