### ISSUE TITLE
How to release the allocated GPU memory of a Pipeline object?

### ISSUE THREAD

**Issue by felixgwu** [NVIDIA/DALI#1048]
Hi, 

I am working with the VideoReader in DALI. Unfortunately, the it hasn't supported varied resolution yet (see this [issue](https://github.com/NVIDIA/DALI/issues/725)). One way to get around this is to create a series of Pipeline objects on the fly. However, after deleting a Pipeline object, the allocated GPU memory is not released. I wonder how I can free the allocated GPU memory.

Thanks in advance!

**Comment by JanuszL** [comment]
Hi,
What kind of indicator do you use to determine that memory has not been freed? Can you provide some simple reproduction script that shows that problem?

**Comment by felixgwu** [comment]
Hi @JanuszL, 
I really appreciate your quick response. The VideoReader is working correctly for me now. The GPU memory is released as I expected. I guess there might be some problem with my GPU.
I'm closing this issue. I'll reopen it if this happens and I can reproduce it.
