### ISSUE TITLE
detection_pipeline.ipynb some issue

### ISSUE THREAD

**Issue by guanfuchen** [NVIDIA/DALI#1049]
COCOReader and other Op return ltrb Bounding box, but draw the image using patches.Rectangle((bbox[0]*W,bbox[1]*H),bbox[2]*W,bbox[3]*H,linewidth=1,edgecolor=category_id_to_color[label[0]],facecolor='none'), here patches.Rectangle is xy, w, h, it is a mistake??

[detection_pipeline.ipynb](https://github.com/NVIDIA/DALI/blob/master/docs/examples/detection_pipeline.ipynb)

**Comment by JanuszL** [comment]
Hi,
Currently it is not possible other than create a new pipeline with different resize parameters. We have such feature on our ToDo list but it is a low priority one now., as it requires a sane way to pass parameters from the outside of the pipeline to the operators and sync it with the epoch boundary.
Tracked as DALI-947.

**Comment by awolant** [comment]
Hi, thanks for reporting this issue. You are correct. This was a mistake. Fixed in #1055

**Comment by awolant** [comment]
Merged, closing.
