### ISSUE TITLE
How can I change the resize and CropMirrorNormalize parameter when running?

### ISSUE THREAD

**Issue by guanfuchen** [NVIDIA/DALI#1050]
I see the source code, Greate Work!!! I want to know how can I change the resize and cropMiooroNormalize crop or resize size when running about 20 batch? like [YOLO code](https://github.com/TencentYoutuResearch/ObjectDetection-OneStageDet/blob/master/yolo/vedanet/engine/_voc_train.py#L164)

```
        if self.batch % self.resize_rate == 0:
            if self.batch + 200 >= self.max_batches:
                finish_flag = True
            else:
                finish_flag = False
            self.dataloader.change_input_dim(finish=finish_flag)
```
```
        self.resize = ops.Resize(
            device="cpu",
            resize_x=300,
            resize_y=300,
            min_filter=types.DALIInterpType.INTERP_TRIANGULAR)

        self.normalize = ops.CropMirrorNormalize(
            device="gpu",
            crop=(300, 300),
            mean=[0.485 * 255, 0.456 * 255, 0.406 * 255],
            std=[0.229 * 255, 0.224 * 255, 0.225 * 255],
            mirror=0,
            output_dtype=output_dtype,
            output_layout=types.NCHW,
            pad_output=False)
```

**Comment by JanuszL** [comment]
Hi,
Currently it is not possible other than create a new pipeline with different resize parameters. We have such feature on our ToDo list but it is a low priority one now., as it requires a sane way to pass parameters from the outside of the pipeline to the operators and sync it with the epoch boundary.
Tracked as DALI-947.

**Comment by guanfuchen** [comment]
Ok, I wish the feature can be used soon. And how can I do to help get the feature?

**Comment by guanfuchen** [comment]
I try the fixed size to train my detector, but it works worse than my origin multi-scale training version, the feature is important in object dtection. YOLO adding the multi-scale training is 1.4 AP more than the origin version. So how DALI-947 works? I want to try implement the feature to test.

**Comment by JanuszL** [comment]
`DALI-947` is the internal tracking number in our Jira project.
Answering your question about how to implement this - we don't have any implementation strategy yet. Problems to consider are:
- DALI is not really aware of the epoch - it just reads the stream of data and processes it batches after batch. Only readers are aware of shards of data and when to move to next one - it can be some indicator of the epoch, but still, it needs to be propagated over the pipeline or another mechanism should be developed in operators
- parameters to operators are provided either during construction or by the supported op. In this case, support op may provide some solution but operator need to be adjusted to accept resize parameters from it
- DALI executes asynchronously - so when you get data for the last batch of Nth epoch, one or more batches are processed by the pipeline, so you need to pass new parameters ahead of time to the pipeline (how is still the thing to figure out). Custom support op or when we unify support op with the remaining operators the ExternalSource may provide some solution
- one of the ideas is to provide those parameters during operator construction with the epoch numbers when they should be applied (but it sound like a limited solution)
So as you see there is a lot of open questions if you have any idea regarding any of those feel free to share.

**Comment by JanuszL** [comment]
Hi,
We had some discussion about it and the current plan is as follows:
1. rework current scalar argument to be dynamic one (can be supplied every iteration)
2. add something similar to `iter_setup` which is called by the pipeline each iterator, and the user has the ability to change values of scalar arguments
3. move operator initialization from constructors to separate method that could be safely called each iteration. It should fetch scalar arguments (in case the user changes its values from comparing to the last iteration) and setup operator again. In case values are unchanged old state could be reused to save setup time - still it needs to be decided how and if to do that case by case for each operator

I think the current work with the operators refactoring needs to be finished - kernels separated from the operators, then we can proceed with the rest starting from 3, through 1 and adding 2 at the end.

What do you think about this?

**Comment by bonlime** [comment]
Hi @JanuszL 
I also was interested in changing resize size during running. In the [article on fastai](https://www.fast.ai/2018/08/10/fastai-diu-imagenet/)  authors proposed a novel method for training and validation: rectangles. The idea is simple. They precalculated aspect ratio for all images, sorted them and then averaged with window size == batch size. Here is an example:
```
ar_before   = 0.73 0.8  0.66 0.43 0.91 0.97
ar_sorted   = 0.43 0.66 0.73 0.8  0.91 0.97
ar_averaged = 0.54 0.54 0.76 0.76 0.94 0.94
```
after that they used custom `batch_sampler` in pytorch to loop through indexes in this averaged ar list and resize the images in a batch to this mean aspect ratio. you could check their code [here](https://github.com/cybertronai/imagenet18_/blob/master/training/dataloader.py) 
I tried their code and it works but it's very slow. So I'm curious how to implement this using DALI. As far as I see custom `batch_sampler` could be implemented using ExternalSource input but would it be possible to somehow pass additional data from this external input such as target resize shape?

**Comment by awolant** [comment]
Hi, thanks for the question. If I understand what you are trying to do correctly, there is no easy way of doing this with DALI. I will dig into it a bit and get back to you on this.

**Comment by awolant** [comment]
As I said before, there is no easy way of doing this in DALI.
What you might try is to pass additional resize parameters (current aspect ratio) through the [ExternnalSource](https://github.com/NVIDIA/DALI/blob/master/docs/examples/external_input.ipynb) and then write custom resize, that would use them [(how to write custom op in DALI)](https://github.com/NVIDIA/DALI/blob/master/docs/examples/extend/create_a_custom_operator.ipynb)
It would probably be easier to start with writing custom operator using [python function](https://github.com/NVIDIA/DALI/blob/master/docs/examples/python_operator/python_operator.ipynb)

**Comment by bonlime** [comment]
@awolant  Thanks for the response. I'll try writing custom op as you suggested
