### ISSUE TITLE
build from source wrong?

### ISSUE THREAD

**Issue by guanfuchen** [NVIDIA/DALI#1058]
I build from the source code. When I use python. Assert on "v != nullptr" failed: Optional argument "use_batched_decode" is not defined for schema "ImageDecoder"

**Comment by guanfuchen** [comment]
And how can I build the whl file myself, I use the command "python setup.py bdist_wheel --universal" but the whl file installing using pip get the wrong "ImportError: libdali.so: cannot open shared object file: No such file or directory" error

**Comment by JanuszL** [comment]
Hi,
`use_batched_decode` was available only with the old version of nvJPEG, with the new one this option is not available.
If you want to build DALI without docker you need to issue bellow command after compiling it:
```
pip install --upgrade dali/python
```
Creating wheel using `python setup.py bdist_wheel --universal`, we have https://github.com/NVIDIA/DALI/blob/master/dali/python/bundle-wheel.sh which does bundle all necessary libs, hash their names and updates RPATHs. It is supported only in the docker image crafted by us. If you want to get python wheel please follow this guide https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/compilation.html#compiling-dali-from-source-using-docker-builder-recommended.

**Comment by chenguanfu511** [comment]
I can build the source code in the docker, but use the building whl file can not be used in other system.

**Comment by JanuszL** [comment]
Have you set the proper version of Python in the docker build? Maybe it differs compared to the one you have in the system?
What error message do you get?
