### ISSUE TITLE
How can I resize the image and crop on the fixed black image?

### ISSUE THREAD

**Issue by chenguanfu511** [NVIDIA/DALI#1072]
I use the detection pipeline, but I can just resize and crop the image to another image about two ratio size comparing the origin image, then resize to the fixed size. But I want to first create a fixed size image, and then resize and crop the origin image then to paste to the fixed size image. How can I complete using the DALI API. just like yolo [class RandomCropLetterbox(BaseMultiTransform):](https://github.com/TencentYoutuResearch/ObjectDetection-OneStageDet/blob/master/yolo/vedanet/data/transform/_preprocess.py#L250)

![image](https://user-images.githubusercontent.com/7610009/61168265-f6b40a00-a57d-11e9-9665-9461456dc181.png)

**Comment by awolant** [comment]
Thanks for the question. As far as I understand what you want to do, right now there is no easy way of doing it with DALI. It requires handling per sample size and arithmetic operations. We are looking into both of those features, since they came up before. I will keep you posted.
In the meantime, you may try to implement custom operator and reuse parts of `Resize` for it.

**Comment by JanuszL** [comment]
@chenguanfu511,

I think you should be able to do what you need using [the `peek_image_shape` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.peek_image_shape) or just [`shapes`](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.shapes) to get the image shape, then [math operations](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/math.html) and [reductions](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#module-nvidia.dali.fn.reductions) should allow you to compute parameters for [the `slice` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.slice) and [`resize](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.resize).
To obtain the result of your paste operation you can use [`pad` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.pad). If you want to paste no in the corner you can utilize `out_of_bounds_policy` policy in slice to provide the padding. If you provide the anchor equal to the padding on left, and the window that spans beyond the image size it will fill the region around the image in the way you want.
