### ISSUE TITLE
offical lmdb example raise error

### ISSUE THREAD

**Issue by RAYKALI** [NVIDIA/DALI#1076]
I am trying to run offical lmdb data example:
https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/dataloading_lmdb.html
I use caffe's convert_imageset to make first lmdb data  and run example raised RuntimeError:

DB has 60000 entries
Traceback (most recent call last):
  File "/home/jiangshan/mytrain/data_loader.py", line 42, in <module>
    pipe_out = pipe.run()
  File "/home/jiangshan/anaconda3/lib/python3.7/site-packages/nvidia/dali/pipeline.py", line 321, in run
    return self.outputs()
  File "/home/jiangshan/anaconda3/lib/python3.7/site-packages/nvidia/dali/pipeline.py", line 285, in outputs
    return self._outputs()
  File "/home/jiangshan/anaconda3/lib/python3.7/site-packages/nvidia/dali/pipeline.py", line 312, in _outputs
    return self._pipe.Outputs()
RuntimeError

I use caffe's offical 'create_mnist.sh' to create mnist lmdb then,raise the same error
pipe.build() run successfully :got print DB has 60000 entries
but pipe.run() got RuntimeError
i have no idea where went wrong

**Comment by JanuszL** [comment]
Hi,
Is that the whole error you see or there is something more there?
Could you check if pipeline consisting only from the LMDB reader doesn't work as well?

**Comment by RAYKALI** [comment]
@JanuszL   thank you

those are whole error 

/home/jiangshan/anaconda3/bin/python3.7 /home/jiangshan/mytrain/data_loader.py
DB has 60000 entries
Traceback (most recent call last):
  File "/home/jiangshan/mytrain/data_loader.py", line 44, in <module>
    pipe_out = pipe.run()
  File "/home/jiangshan/anaconda3/lib/python3.7/site-packages/nvidia/dali/pipeline.py", line 321, in run
    return self.outputs()
  File "/home/jiangshan/anaconda3/lib/python3.7/site-packages/nvidia/dali/pipeline.py", line 285, in outputs
    return self._outputs()
  File "/home/jiangshan/anaconda3/lib/python3.7/site-packages/nvidia/dali/pipeline.py", line 312, in _outputs
    return self._pipe.Outputs()
RuntimeError
Process finished with exit code 1


I have tried FileReader(folder) and MXNetReader(rec+idx) just now,both are ok!
I write read_lmdb.py to verify the caffe lmdb data that seems no problem
I think mninst only28*28 and exaple 

 self.cmnp = ops.CropMirrorNormalize(device = "gpu",
                                            output_dtype = types.FLOAT,
                                            crop = (224, 224),
                                            image_type = types.RGB,
                                            mean = [0., 0., 0.],
                                            std = [1., 1., 1.])
is inappropriate so I simplify to
self.decode = ops.nvJPEGDecoder(device = "mixed", output_type=types.GRAY)
also raise the same error...

here are the .py and lmdb-mnist-dataset
link：https://pan.baidu.com/s/12XpNzyQow_5PzhskA5Cqdg     pwd：v8hp

env: ubuntu18.04 cuda10.1 driver418.67 gpu:1x1050ti 
anaconda/python3.7  caffe:sudo apt install caffe-cuda     dali:pip install --extra-index-url https://developer.download.nvidia.com/compute/redist/cuda/10.0 nvidia-dali

**Comment by klecki** [comment]
Hi,
I am looking at the issue right now. I will try to reproduce on the mnist converted to LMDB.

**Comment by klecki** [comment]
@RAYKALI could you provide the .py files here? I cannot download them from the link you provided.

**Comment by RAYKALI** [comment]
@klecki 
https://onedrive.live.com/?authkey=%21AILxVGZKJ1bDdEs&id=10AF58D3931C9EFD%21759&cid=10AF58D3931C9EFD

**Comment by klecki** [comment]
Thanks, I think I was able to reproduce the problem. 
The MNIST dataset and the LMDB that you created using Caffe scripts is represented as row-major arrays of (28x28) pixels (without any encoding).

In the pipeline, from the example that you used, there is `nvJPEGDecoder` Op. `nvJPEGDecoder` Op treats input data from `CaffeReader` as encoded image data. It tries to detect what kind of format is used (jpeg, png, bmp, tiff or other) and fails because the input is just raw pixel data.

I was able to run it with `nvJPEGDecoder` commented out:

```
from nvidia.dali.pipeline import Pipeline
import nvidia.dali.ops as ops
import nvidia.dali.types as types

import numpy as np
from timeit import default_timer as timer
import numpy as np

db_folder = "mnist_train_lmdb"

class CaffePipeline(Pipeline):
    def __init__(self, batch_size, num_threads, device_id):
        super(CaffePipeline, self).__init__(batch_size,
                                         num_threads,
                                         device_id)
        self.input = ops.CaffeReader(path = db_folder)
        # self.decode = ops.nvJPEGDecoder(device = "mixed", output_type=types.GRAY)
        self.iter = 0

    def define_graph(self):
        self.jpegs, self.labels = self.input()
        # images = self.decode(self.jpegs)
        return (self.jpegs, self.labels)

    def iter_setup(self):
        pass

batch_size = 1
pipe = CaffePipeline(batch_size=batch_size, num_threads=1, device_id = 0)
pipe.build()
pipe_out = pipe.run()
print(pipe_out[0].as_array().shape)

> (1, 784)
```

The downside of it you would get a 1D buffer of length `784 = 28*28` as we assume that the readers return only encoded images as an array of bytes.

There was work done to allow to reshape the data (change the shape information from 1D buffer of 784 to 2D buffer of 28x28) but it got delayed: https://github.com/NVIDIA/DALI/pull/388 and we still do not support that feature.

If you use a LMDB with jpeg images inside like Imagenet LMDB https://github.com/intel/caffe/wiki/How-to-create-ImageNet-LMDB, the example should work without any modifications (the `nvJPEGDecoder` should be there to decode the images).

**Comment by RAYKALI** [comment]
@klecki Thanks a lot
I did't understand the function JPEGDecoder before.
The example you give me don't work either.
https://github.com/BVLC/caffe/blob/master/examples/imagenet/create_imagenet.sh
Because we need add additional args: Set --encoded=True and --encode_type='jpg or other types' for
caffe offical tools "convert_imageset"  which allows mnist and imagenet to work directly for nvjpegdecoder.

**Comment by JanuszL** [comment]
I think this example is more up to date https://github.com/intel/caffe/blob/master/examples/imagenet/create_imagenet.sh.
