### ISSUE TITLE
cannot install dali HTTPError 404

### ISSUE THREAD

**Issue by adrianstaniec** [NVIDIA/DALI#1078]
I used this command:
```
pip3 install --user --extra-index-url https://developer.download.nvidia.com/compute/redist/cuda/10.0 nvidia-dali
```

I get this error:
```
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/nvidia-dali/
```

Also:
specifically it doesn't show up here:
https://pypi.org/simple/

also here:
https://developer.download.nvidia.com/compute/redist/nvidia-dali/
0.7.0 is the newest (I was expecting 0.8.0)

**Comment by adrianstaniec** [comment]
I tried this #1065 didn't help

**Comment by awolant** [comment]
Thanks for reporting the issue. I will look into what happens there.
In the meantime, I think you can find .whl files you are looking for with [direct link](http://developer.download.nvidia.com/compute/redist/cuda/10.0/nvidia-dali/)

**Comment by awolant** [comment]
Since 0.8 release, we do not use [https://developer.download.nvidia.com/compute/redist/nvidia-dali/](https://developer.download.nvidia.com/compute/redist/nvidia-dali/), as we support two CUDA version.
We were never on [https://pypi.org/simple/](https://pypi.org/simple/)
Additionally to the link I provided before, you can look into releases page on the github [https://github.com/NVIDIA/DALI/releases](https://github.com/NVIDIA/DALI/releases)

**Comment by adrianstaniec** [comment]
#### 1. wheel file
Ok i managed to install nvidia-dali from the wheel file (from your [link](http://developer.download.nvidia.com/compute/redist/cuda/10.0/nvidia-dali/))
but now I have problem installing the nvidia-dali-tf-plugin (from similar [link](http://developer.download.nvidia.com/compute/redist/cuda/10.0/nvidia-dali-tf-plugin/)).
Somehow the plugin installation still looks into pypi.org/simple which gives 404.

```
 pip3 install nvidia_dali-0.8.0-680097-cp36-cp36m-manylinux1_x86_64.whl                                                                                                                    6s
Processing ./nvidia_dali-0.8.0-680097-cp36-cp36m-manylinux1_x86_64.whl
Collecting future (from nvidia-dali==0.8.0)
Installing collected packages: future, nvidia-dali
Successfully installed future-0.17.1 nvidia-dali-0.8.0
/tmp
 pip3 install nvidia-dali-tf-plugin-0.8.0.tar.gz                                                                                                                                           7s
Processing ./nvidia-dali-tf-plugin-0.8.0.tar.gz
Collecting nvidia-dali==0.8.0 (from nvidia-dali-tf-plugin==0.8.0)
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python3/dist-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 795, in get_page
    resp.raise_for_status()
  File "/usr/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/nvidia-dali/

               
```


#### 2.  Official way
Why the method mentioned in the official documentation [here](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/installation.html#installing-prebuilt-dali-packages) doesn't work anymore?
I used to work fine in the past

**Comment by JanuszL** [comment]
I see [some issue](https://github.com/pypa/pip/issues/4823) reported to pip that sound like one you faces. Can you check it?

**Comment by adrianstaniec** [comment]
As a workaround I unpacked `nvidia-dali-tf-plugin-0.8.0.tar.gz`
and removed nvidia-dali from `install_requires` argument from setup call in setup.py.
and than I coudl install the tf-plugin from new tar.gz file.

**But** anyway in the meantime something changed on the servers I guess,
I now **I can again just install with the command recommended by documentation**:
```
pip3 install --user --extra-index-url https://developer.download.nvidia.com/compute/redist/cuda/10.0 nvidia-dali
pip3 install --user --extra-index-url https://developer.download.nvidia.com/compute/redist/cuda/10.0 nvidia-dali-tf-plugin
```

**Comment by JanuszL** [comment]
Do you use any proxy? I think we haven't changed anything in our servers since then.

**Comment by tanguofu** [comment]
> I used this command:
> 
> ```
> pip3 install --user --extra-index-url https://developer.download.nvidia.com/compute/redist/cuda/10.0 nvidia-dali
> ```
> 
> I get this error:
> 
> ```
> requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/nvidia-dali/
> ```
> 
> Also:
> specifically it doesn't show up here:
> https://pypi.org/simple/
> 
> also here:
> https://developer.download.nvidia.com/compute/redist/nvidia-dali/
> 0.7.0 is the newest (I was expecting 0.8.0)

i aslo has this error, and reslove when i update the pip:
sudo -E python3 -m pip install -U pip
