### ISSUE TITLE
How to solve Optional argument "use_batched_decode" is not defined for schema "ImageDecoder"

### ISSUE THREAD

**Issue by cyang49** [NVIDIA/DALI#1080]
I built DALI from source. I cannot use Docker version. I see that the response #1058 mentioned that this is because of the nvjpeg version problem. The version installed on my system is `libnvjpeg.so.10.1.105`. 

How can I solve this problem? Do I need to install a newer version of nvjpeg? Please advise.

**Comment by JanuszL** [comment]
Hi,
As I have mentioned in #1058 `use_batched_decode` is no longer available as it was not providing performance advantage for batch sizes usually used during typical training. So you can stop using it without any performance hit.

**Comment by cyang49** [comment]
@JanuszL I did not write any application code that uses `use_batched_decode`. I dug a bit more and found that my nvjpeg doesn't include this function `nvjpegBufferPinnedCreate()`, and the build uses legacy api for the nvjpeg decoder which supplies this parameter. Is this expected behavior?

**Comment by JanuszL** [comment]
So it is a bug. Thank you for reporting it. In the meantime please update CUDA 10.1 to CUDA 10.1, update 1 - https://developer.nvidia.com/cuda-downloads, it should provide `libnvjpeg.so.10.1.168` and check if that works for you.

**Comment by cyang49** [comment]
@JanuszL I tested building DALI with `libnvjpeg.so.10.1.168`, and it does not produce this runtime error anymore. Thanks.

P.S. Since I don't have root and I copied `libnvjpeg.so.10.1.168` from elsewhere, I had to make some changes in the cmake scripts to let it find the correct `nvjpeg.h` and not use the default one supplied by the system. Specifically, `NVJPEG_INCLUDE_DIR` may need to be changed.

**Comment by ruiyuanlu** [comment]
@JanuszL Hi, I'm using CUDA 10.0 and met exactly same issue with DALI 0.13.0dev, and the version on my machine is `libnvjpeg.so.10.0.130`. I found no update for CUDA 10.0. So what can I do to avoid this issue?

**Comment by JanuszL** [comment]
Hi,
For CUDA 10 please use https://developer.nvidia.com/cuda-10.0-download-archive, when you select the download you can get full CUDA 10 binary as well as small `Patch 1` with nvJPEG update. Also, you can use the direct [link](https://developer.download.nvidia.com/compute/cuda/10.0/Prod/patches/1/cuda_10.0.130.1_linux.run).
