### ISSUE TITLE
Ability to split image?

### ISSUE THREAD

**Issue by atyshka** [NVIDIA/DALI#1084]
For performing inference with TensorRT, we must separate out the channels of an image so that instead of being rgb pixels they are 3 separate channels. This is possible in opencv with the split() method, but if I'd like to accelerate this with DALI, is there a way to perform such a split? I haven't found anything yet going through the docs.

**Comment by JanuszL** [comment]
Hi,
Do you mean to format change from NHWC to NCHW? DALI supports that in [Transpose](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html#nvidia.dali.ops.Transpose), [NormalizePermute](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html#nvidia.dali.ops.NormalizePermute) and [CropMirrorNormalize](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html#nvidia.dali.ops.CropMirrorNormalize). But if you are asking about having 3 separate tensor list at the output CNHW then this is not supported and some custom operator need to be prepared or other tool needs to be used to achieve that (like pyCuda).

**Comment by JanuszL** [comment]
Hi,
Now you can use [the `slice` operator]() to do that. Something like:
```
  c0= fn.slice(imgs, 0, 1, axes=[2])
  c1= fn.slice(imgs, 1, 1, axes=[2])
  c2= fn.slice(imgs, 2, 1, axes=[2])
```
should work.
