### ISSUE TITLE
Atomic operator

### ISSUE THREAD

**Issue by zheLim** [NVIDIA/DALI#1092]
Greetings, thanks for your excellent work. 
By the way, will it be better splitting operators to atomic operators? For example, CropMirrorNormalize split into crop, mirror and normalize. Some situation only require normalization operator but there has no such operator.

**Comment by JanuszL** [comment]
Hi,
I think there is no such need. If you use default arguments then the part you want to strip off (mirror or normalize) would be transparent. The idea behind having these operators fused is:
- it is a common pattern in the data pipeline
- if those operations are fused we saved memory round trips. If someone doesn't want to use all functionalities then he can use default arguments. If we make them separated then we will have load->crop->store->load->mirror->store->load->normalize->store, where each load/store cost you very much.
Could you tell which operation is not possible to express with the current API?

**Comment by haoxintong** [comment]
Hi, @JanuszL 
I have some trouble on image normalization with different size. `CropMirrorNormalize` and `NormalizePermute` require crop size or w/h which can not be provided in my situation. 
Now my workaround is, define this operation in network graph. But I think this should belong to data processing pipeline.

**Comment by zheLim** [comment]
Hi, @ @JanuszL 
I totally agree with your opinion. Fusing operators makes code run faster.
However, code readability is affected. For example, PyTorch do normalization by first converting image to range [0,1] and then subtract mean and divide std.
In order to use Dali to reproduce such process, two CropMirrorNormalize operators is required and both of them only performs normalize operation.

**Comment by zheLim** [comment]
@haoxintong I think you can just skip crop size parameter and only use normalization part of this function.

**Comment by JanuszL** [comment]
@haoxintong - the idea behind [NormalizePermute](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html#nvidia.dali.ops.NormalizePermute) it to just do normalization with optional permutation. In the next release `NormalizePermute` will be deprecated, and just calling `CropMirrorNormalize` without any crop arg should work. Could you check it with the nightly build?
@zheLim - I don't know if it is the best approach to have 1:1 representation PyTorch data transformation using DALI:
> PyTorch do normalization by first converting image to the range [0,1] and then subtract mean and divide std.
In case of DALI you can do this by one call to `CropMirrorNormalize` with mean and std multiplied by the range of processed data type, for example: 
```
mean=[0.485 * 255,0.456 * 255,0.406 * 255],
std=[0.229 * 255,0.224 * 255,0.225 * 255]
```
Will apply to mean subtraction, division by the mean and conversion to the range 0-1 with just one call.

**Comment by zheLim** [comment]
I see, thanks for your reply!
