### ISSUE TITLE
Question: Does DALI support 'mix' mode decode for PNG files on GPU?

### ISSUE THREAD

**Issue by ruiyuanlu** [NVIDIA/DALI#1093]
The cityscapes dataset has segmentation labels in png format, I'm wondering if dali support 'mix' mode decode for png files like what nvJPEG does for jpgs?

**Comment by JanuszL** [comment]
Hi,
Currently, we don't provide a GPU accelerated decoding for PNG format. Still, if you use nvJPEG it will handle it, silently falling back to CPU implementation.
As far as I know, PNG decoding doesn't parallelize well and there could be a very little gain by moving it to the GPU.
