### ISSUE TITLE
Does DALI support bi-linear resize op for now?

### ISSUE THREAD

**Issue by ruiyuanlu** [NVIDIA/DALI#1094]
Thx a lot for speed up the training procedure, I'm wondering if DALI support bi-linear resize op, since it is the pytorch default Resize options~.

**Comment by JanuszL** [comment]
Hi,
DALI supports [following interpolations](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/api.html#nvidia.dali.types.DALIInterpType).
`INTERP_LINEAR` basically means bilinear for 2D data - like images. Please also note that PyTorch, when the bilinear strategy is given, silently fails to triangular window sampling pattern when scaling down, while for upsizing it uses linear. DALI supports `INTERP_TRIANGULAR` as well.

**Comment by ruiyuanlu** [comment]
Thanks for the reply, I think that would be enough for re-implement a network.
