### ISSUE TITLE
Question: What if resize_shoter and resize_longer are both given?

### ISSUE THREAD

**Issue by ruiyuanlu** [NVIDIA/DALI#1095]
Hi, guys, I just read the doc about [Resize](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html?highlight=resize#resize), and I'm wondering the behavior if resize_shoter and resize_longer are both given in op.Resize.
The pytorch maskrcnn_benchmark use both [(min_size and max_size)](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/config/defaults.py#L43-L45) to resize images, so what if the upper bound and lower bound of size of images are give in DALI Resize?

**Comment by JanuszL** [comment]
Hi,
Is `max_size` in the thing you are asking for - https://docs.nvidia.com/deeplearning/sdk/dali-master-branch-user-guide/docs/supported_ops.html#nvidia.dali.ops.Resize.
It is available in the master branch, you can check it in the nightly/weekly build and it will be available in the next release.

**Comment by ZJU-lishuang** [comment]
Hi,may i ask you a question?
When you resize your image,how to deal with the bounding box?I find it is difficult to deal with the bounding box changes.

**Comment by ZJU-lishuang** [comment]
I find when I resize the image ,I can not resize the bounding box at the same time.I use the ops.COCOReader.

**Comment by JanuszL** [comment]
@ZJU-lishuang - you have a couple of options:
- write [own custom op in C/C++](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/extend/create_a_custom_operator.html) (slow to develop, fastest solution)
- write [own custom op in python](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/python_operator/python_operator.html) (faster to get, perf will be inferior)
- use bboxes in relative coordinates, see 'ratio' argument in [COCOReader](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html#nvidia.dali.ops.COCOReader). Then no matter what the pixel size your image have bboxes corners are still 0-1.

**Comment by JanuszL** [comment]
@ZJU-lishuang,

[This example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/image_processing/resize.html) shows `resize`  behavior.
You can check [this one](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/math/geometric_transforms.html) to see how to transform keypoints/bounding boxes.
