### ISSUE TITLE
Question: Is there any way to auto generate operator signature in python api?

### ISSUE THREAD

**Issue by haoxintong** [NVIDIA/DALI#1099]
Hi,
When building graph in pipe, there are 2 ways to get what operators supported in DALI, `ops.support_ops()` or check in document. Then if I want to know details of the operator, I also have two choices, `help()` and document.

This is inefficient and not user friendly, especially when the network condition is not well. So is there any way to get the signature of them directly in python code? An example is that in MXNet all operators in ndarray/symbol are auto generated when building python module in `setup.py`. 

As we could get that by `ops.support_ops()` and `help(...)`, just write them in `gen_op.py` then import to `ops.py`?

**Comment by JanuszL** [comment]
Hi,
I'm sorry, but I don't fully understand what you are asking for.
Do you want DALI to have all operators generated before DALI is imported and available in some 'jadajada.py` file? I think it may not work in all cases, as DALI supports plugins and operators could be dynamically added in the runtime and populate operator list. In the solution, you propose those operators won't be listed there.
If the network is not always available to you you can download docs page and use it offline.

**Comment by haoxintong** [comment]
Thanks for reply.

The basic idea of this question is:
1. Make IDE auto complete code when typing "Tab". :D
2. Jump to the operator signature instead of reading the docs in browser if not sure how to use it.  

So this is a feature giving users a fluent coding experience. Users can focus on the main screen and dont have to switch to another.

My understanding is that when we have finished DALI building, the basic operators are certain, which will not be changed when imported in python. For users new to DALI, we assume that they have clear requirements on the pipeline, (for example they want Reader->Crop->Norm->ToTensor already implemented in DALI), but they dont know if they are supported and how to use it.

In my experience of coding mxnet block, the only thing I should consider is the implement method.  Take "Short Time Fourier Transform" as an example, we have known the formula of stft: spilt signal into frames, apply window function, then compute fourier transform. So I found following operators help:
1. `nd.take`, getting the frames by provided indices
2. `nd.broadcast_mul`, applying the window
3. `nd.contrib.fft`, computing the transform

For this block, there is no need to look up in documents, just type possible key words, then IDE will give me the candidate list.

As you said it may not work in all cases, but most popular ops have been included in DALI, then put them into a "**.py" will be great at least for me. Should this be an external contribution? I am not sure if this is necessary for other users.

By the way, could you please provide some explaination of dynamically adding op/plugins, when should we use it and if there are some documents showing how to use.

**Comment by awolant** [comment]
With regards to the last question about the dynamically added ops, this functionality is intended for the situation, when existing DALI ops are not enough for your particular use case and you want to implement some custom augmentation on your own.
Example of how to do this you can find [here](https://github.com/NVIDIA/DALI/blob/master/docs/examples/extend/create_a_custom_operator.ipynb)

About the better IDE support, I think this would be a cool feature, but I'm not sure if there is an elegant way of doing this across multiple cases. Let me get back to you on this.

**Comment by haoxintong** [comment]
@awolant Thanks!
I have another problem of multi-scale images loading with MXNet plugin . When I change the input shape in the next batch, assert in `feed_ndarray` failed, DALI tensor has a new shape. Can I make it work using `DALIGenericIterator` or I have to implement my own mxnet plugin for this situation.

**Comment by JanuszL** [comment]
@haoxintong 
You can check[ nightly build](https://docs.nvidia.com/deeplearning/sdk/dali-master-branch-user-guide/docs/plugins/mxnet_plugin_api.html#nvidia.dali.plugin.mxnet.DALIClassificationIterator) and `dynamic_shape` argument in the MXNet iterator. This option should be available in the next release.

**Comment by klecki** [comment]
@haoxintong, recent DALI releases (1.32 and 1.33) added the signatures/type hints to DALI operator modules `nvidia.dali.fn`, `nvidia.dali.math` (with several overloads to cover regular usage as well as passing constant values or use less common API features), to the tensor types (`TensorListCPU/GPU` and `TensorCPU/GPU`), pipeline definition decorator (`@pipeline_def`), framework plugins for PyTorch and JAX - so it should cover most of typical user interactions with DALI code. We also provide the `__signature__` definition, so DALI APIs should now be fully visible in the popular IDEs as well as in runtime environments like Jupyter, accompanied by their docstrings.
