### ISSUE TITLE
Question: Read mask and keypoints from json support?

### ISSUE THREAD

**Issue by ruiyuanlu** [NVIDIA/DALI#1114]
Thanks for the great lib to accelerate training process about 3-5x. I'm wondering if DALI support read mask and keypoints from json annotations that used in segmentation and pose estimation? Especially COCO-like datasets.

Thanks~

**Comment by awolant** [comment]
Hi, thanks for the question and glad to hear you enjoy it and see good results. 
Currently, there is no native way of doing that in DALI. I can think of two ways of accomplishing it right now. First would be to convert this dataset to TFRecord and loading that. Another would be to experiment with [ExternalSource](https://github.com/NVIDIA/DALI/blob/master/docs/examples/external_input.ipynb)

**Comment by ruiyuanlu** [comment]
Actually, I'm willing to have a try to implement a native DALI reader in my spare time. But I'm new to cuda programming and any guidance would be very helpful.

**Comment by JanuszL** [comment]
@ruiyuanlu - if you just want to read key points then there is no need to program in CUDA as this code is executed on the CPU. Another story is if you want to process these key points - then for some heavy operations, GPU based operators may be useful.
Also, does your network accepts raw keypoints or you need to render a mask image from them?

**Comment by ruiyuanlu** [comment]
@JanuszL Actually, some coco images has some invalid annotations: empty boxes annotations, images with no annotations, and keypoints num < threshold annotations. These images cannot be used to train directly, for the lack of annotations. 

I think these images should be removed at loading time, or at least set a parameter to determine if DALI should load these images.

I tried to write a pipeline based on DALI and COCOAPI, but it is not easy to filter these images. DALI will load these not annotated images into a tensor just like the others, cannot be used to train directly.

The following code is the filter used in maskrcnn benchmark to filter out these invalid annotations:
```python

min_keypoints_per_image = 10


def _count_visible_keypoints(anno):
    return sum(sum(1 for v in ann["keypoints"][2::3] if v > 0) for ann in anno)


def _has_only_empty_bbox(anno):
    return all(any(o <= 1 for o in obj["bbox"][2:]) for obj in anno)


def has_valid_annotation(anno):
    # if it's empty, there is no annotation
    if len(anno) == 0:
        return False
    # if all boxes have close to zero area, there is no annotation
    if _has_only_empty_bbox(anno):
        return False
    # keypoints task have a slight different critera for considering
    # if an annotation is valid
    if "keypoints" not in anno[0]:
        return True
    # for keypoint detection tasks, only consider valid images those
    # containing at least min_keypoints_per_image
    if _count_visible_keypoints(anno) >= min_keypoints_per_image:
        return True
    return False
```

And the invalid images will be filtered out in the __init__:

```python
class COCODataset(torchvision.datasets.coco.CocoDetection):
    def __init__(
        self, ann_file, root, remove_images_without_annotations, transforms=None
    ):
        super(COCODataset, self).__init__(root, ann_file)
        # sort indices for reproducible results
        self.ids = sorted(self.ids)

        # filter images without detection annotations
        if remove_images_without_annotations:
            ids = []
            for img_id in self.ids:
                ann_ids = self.coco.getAnnIds(imgIds=img_id, iscrowd=None)
                anno = self.coco.loadAnns(ann_ids)
                if has_valid_annotation(anno):
                    ids.append(img_id)
            self.ids = ids

        self.json_category_id_to_contiguous_id = {
            v: i + 1 for i, v in enumerate(self.coco.getCatIds())
        }
        self.contiguous_category_id_to_json_id = {
            v: k for k, v in self.json_category_id_to_contiguous_id.items()
        }
        self.id_to_img_map = {k: v for k, v in enumerate(self.ids)}
        self._transforms = transforms
```

So I think a parameter might be add to control the filter behavior? And a filter might be implemented during DALI loading process?

**Comment by JanuszL** [comment]
Hi,
Have you tried `skip_empty` or `size_threshold` options of the [COCO reader](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html#cocoreader) for the bounding boxes? I think a similar thing could be added for the key points as well if I understand your ask correctly.

**Comment by ruiyuanlu** [comment]
@JanuszL Hi, thanks for the helpful responding, `skip_empty` and `size_threshold` are exactly what I need.
