### ISSUE TITLE
Issue loading video

### ISSUE THREAD

**Issue by Toraudonn** [NVIDIA/DALI#1115]
Hi, I'm trying to load videos but getting stuck with the error:
```
RuntimeError: [/opt/dali/dali/pipeline/operators/reader/video_reader_op.h:60] [/opt/dali/dali/pipeline/operators/reader/loader/video_loader.cc:222] Assert on "file.frame_base_.num == 1" failed: Variable frame rate videos are unsupported. Check failed for file: videos/0/prepared_0.mp4
```

- I'm following the newest video examples on github on jupyter notebook (`video_reader_label_example.ipynb`) with my own mp4 file.
- The video file was originally VFR (got `[VFR: 0.040284 (261/6218) min: 20 max: 21]` using `ffmpeg -i original.mp4 -vf vfrdet -f null -`)
- I converted the video file to CFR and h264 codec using: `ffmpeg -i original.mp4 -map v:0 -c:v libx264 -crf 18 -pix_fmt yuv420p -g 5 -profile:v high -r 29.97 -vsync 1 prepared.mp4`
- I checked that `[VFR: 0.000000 (0/6479)]`, which I think it means it's converted to CFR

Spec:
- `nvidia-dali-nightly==0.13.0.dev20190725`
- ubuntu 16.04
- cuda 9.0
- ffmpeg 4.1.3

**Comment by Toraudonn** [comment]
Just an update, it works fine on `nvidia-dali==0.12.0`.

**Comment by JanuszL** [comment]
Hi,
We added this check to detect if a video is vfr. It is rather a heuristic than strong evidence, as to be 100% sure if the video is vfr you need to go through the whole stream.
@awolant - maybe we can change this to a warning or add some reader option that will make this check optional?

**Comment by Toraudonn** [comment]
@JanuszL Thanks for the response!
On, `0.12.0`, even though it works, sometimes it hangs as stated in #1041 . Maybe my video wasn't fully converted into CFR.
Do you by chance know what is the best way of converting VFR videos to CFR using ffmpeg?

**Comment by JanuszL** [comment]
@Toraudonn - sorry, but I don't know how to do it properly. It is strange that it sometimes hangs in `0.12.0` - it should be deterministic. Maybe there is some issue not related to CFR vs VFR. Does it happen with all video samples you have or only this particular one?

**Comment by Toraudonn** [comment]
@JanuszL I was using 4K videos (30 frames) which were initially VFR and I converted them to CFR. I looked at various videos, but on `0.12.0` it seems that this occurs constantly with any video using `batch_size=8`, `sequence_length=2` and `initial_prefetch=2` (I was playing around with the parameters).

**Comment by JanuszL** [comment]
Could you provide simple reproduction script for DALI and for the creation of failing video (you can refer to some simple FFmpeg invocation that could create such video https://github.com/NVIDIA/DALI_extra/blob/master/db/video/README.rst)?

**Comment by JanuszL** [comment]
If it still doesn't work please reopen.
