### ISSUE TITLE
Random rotate without cropping side

### ISSUE THREAD

**Issue by zheLim** [NVIDIA/DALI#1118]
Hi, i would like to create random rotate/warpaffine operator without cropping side like [OpenCV Python : rotate image without cropping sides](https://stackoverflow.com/questions/43892506/opencv-python-rotate-image-without-cropping-sides/47248339).
Firstly I suppose it can be done using Paste+rotate. However, random parameter pass to rotate operator cannot be known. Thus I cannot do padding before rotate. Any suggestion on this problem?

**Comment by zheLim** [comment]
And I would like to know, how to do rotate for image and mask at the same time?

**Comment by zheLim** [comment]
BTW, It is not easy to do Mirror for image and mask and the same time. CropMirrorNorm output wrong mask. FastResizeCrop cannot be used, since mask require resize with inter_NN.

**Comment by mzient** [comment]
I'm currently reworking all warping operators (rotate, warp affine, etc). New rotate will enlarge canvas to accommodate whole image, while new warp affine will accept externally provided canvas size.

**Comment by zheLim** [comment]
@mzient Looking forward to your later commit!

**Comment by lxlee** [comment]
I have the same needs，is there any new solution now?

**Comment by JanuszL** [comment]
Hi,
Reworked WarpAffine operator is already available in the master branch and you can try is by installing the nightly build of DALI.
An example of how it works can be found https://docs.nvidia.com/deeplearning/sdk/dali-master-branch-user-guide/docs/examples/warp.html.
@mzient anything to add?

**Comment by mzient** [comment]
Regarding rotate: the new rotate automatically adjusts canvas size to fit the image. Just download the new version and you're set.
If you need more than just rotation, you can use WarpAffine, but that leaves you on your own with calculating the matrix elements and output sizes. I guess some solution can be hacked together with the combination of ExternalSource for base transform matrices and incorporating the input sizes with the newly-added arithmetic operators (see https://docs.nvidia.com/deeplearning/sdk/dali-master-branch-user-guide/docs/examples/expressions.html) and Shapes operator. If the images at the input to WarpAffine are of uniform size, you can simply calculate the sizes and matrices in python and just feed them to the pipeline through external source.

**Comment by JanuszL** [comment]
This change is available in [DALI 0.16.0](https://github.com/NVIDIA/DALI/releases/tag/v0.16.0).
