### ISSUE TITLE
How to write a DALI plugin?

### ISSUE THREAD

**Issue by shippingwang** [NVIDIA/DALI#1123]
How to write a plugin?

I wanna write a DALI plugin which can support another platform
Can anyone tell me how to start it?
I found Pytorch API  [here](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/plugins/pytorch_plugin_api.html#nvidia.dali.plugin.pytorch.DALIClassificationIterator)

Thanks for your great work.

**Comment by awolant** [comment]
Hi, thanks for the question. Could you specify a bit what you are trying to do?
In general, DALI supports custom operators via [plugin system](https://github.com/NVIDIA/DALI/blob/master/docs/examples/extend/create_a_custom_operator.ipynb)
