### ISSUE TITLE
Conda recipe for DALI

### ISSUE THREAD

**Issue by JanuszL** [NVIDIA/DALI#1125]
There is already community support for conda DALI build for Power - https://github.com/NVIDIA/DALI/pull/1124.
It would be good to add such recipe to DALI repository.

**Comment by aalugore** [comment]
Hello! Looks like we are moving forward with contributing our Conda recipe upstream. As previously mentioned we were able to get full functionality with DALI v0.9. However, with the move to v0.12, the TensorFlow Plugin is being built differently and thus requires some work. (mentioned here: https://github.com/NVIDIA/DALI/issues/954) Being that the plugin now needs to be built separately, we are interested in getting your feedback on whether it would make sense to have a separate recipe for just the TF plugin. We have been able to get our recipe working with v0.12 though we had to remove all of the plugin specific code. Thoughts?

**Comment by JanuszL** [comment]
@aalugore - difficult question. If the user uses TensorFlow build inside Conda environment then the old way of building DALI TensorFlow plugin on the fly will work (https://github.com/tensorflow/tensorflow/issues/29643). If he decided to install one from PIP then it will break due to C++ ABI incompatibility and prebuilding plugin using TensorFlow docker is required. In your specific case - Power architecture PIP  is not a problem (I doubt that there is any wheel prebuild), but in case of other people asking about Conda recipe, it could be a problem.
I would be more than happy to hear the opinion of other people as well, @jayfurmanek?
Regarding:
> Being that the plugin now needs to be built separately, we are interested in getting your feedback on whether it would make sense to have a separate recipe for just the TF plugin
I think we are not limited to the way it is now. We can rework it to restore the old way of building TensorFlow plugin for use cases like this one.

**Comment by jayfurmanek** [comment]
Mixing pip packages and conda packages that include native code should probably be avoided in just about any context, so I don't think that should limit us here. We can assume it will pair with a TensorFlow conda package sourced from either Anaconda or IBM - and indeed we can code the run time dependencies in the recipe so that is enforced. This enforcement will avoid any C++ ABI issues because in that case Tensorflow would be built with the same settings.

Looking at the plugin specifically, the conda build would not need the docker pieces or any of the other necessary complications that are needed for manylinux compliance. The Anaconda toolchain enforces that with a standard GCC version, ABI settings and an included glibc to build against. So if there was a way to restore the "old way" of building the plugin, even if only for the conda build, that would be ideal.

The conda build wouldn't replace the manylinux/pip builds, those would still be needed to work along with the community TensorFlow .whl files (there are community builds of TF for ppc64le, available btw - just not via pypi).

Our current recipe works with version `0.9` (which still had the old way of building the plugin). It works with `0.12` with a few small updates, but not for the plugin. Perhaps we start by pushing up what we have - knowing it won't work for the plugin, then work towards getting the plugin working in a mutually acceptable way. Sound like a plan?

**Comment by jayfurmanek** [comment]
Our recipe works for both ppc4le and x86_64 btw.

**Comment by JanuszL** [comment]
@jayfurmanek - "should probably be avoided" != "not possible" - I can imagine people doing that. Also on the TensorFlow site, you can read (for Conda case):
```
While we recommend the TensorFlow-provided pip package, a community-supported Anaconda package is available. 
```
So for ppc64le it is fine as you are providing builds for Conda, for x86_64 I have some reservations. But this is another topic.
Yes, please publish as a PR whatever you can so we can see how we can plugin into it.
As I understand correctly you want to have binary plugin for certain version of TensorFlow, not the source distribution - this introduces the need to rebuilding DALI whenever new TF version appears. I'm pretty new to conda but I see that there is some `post-link` step that can be added to conda package that could build TensorFlow plugin on the fly.

**Comment by jayfurmanek** [comment]
Hi @JanuszL,

We did a quick review of the recipe and compiled a list that would need decisions:
 - The aforementioned `USE_CXX11_ABI`  setting. The Anaconda toolchain has many pre-set parameters and setting this to 1 is among them. It's possible to set it to 0 to gain compatibility with things built with 0, but then the risk is incompatibility with the rest of anaconda. We're fine with whatever you decide here. It shouldn't hold us up.

- Anaconda provides a `cudatoolkit` package. IBM's WMLCE provides a `cudatoolkit` and `cudatoolkit-dev` package. Our recipe uses the `-dev` package for the cuda compilers.  We can change this to source the cuda compilers from the local system, if desired.

- Anaconda does not have a complete package for `jpeg-turbo` (they only have one for `jpeg`). We've built a recipe for `jpeg-turbo` and could include it as well, or we could change the dali recipe to source jpeg-turbo from the local system as well. (from `/usr/local/jpeg-turbo` or some such)

That should be it, other than the need for the old non-manylinux build method for the plugin.  BTW, your post-link idea is certainly interesting, but probably a too ambitious. Anaconda warns to only user the pre and post scripts for relatively simple things an behavior can change over time.

**Comment by JanuszL** [comment]
Hi @jayfurmanek ,

* I think setting USE_CXX11_ABI to 1 should do. @mzient @cliffwoolley do you think that there is anything we should be afraid of?
* > Anaconda provides a cudatoolkit package. IBM's WMLCE provides a cudatoolkit

I'm fine with both. Maybe we can leave it up to the user to decide via some option or variable?
* Regarding `jpeg-turbo` I think we can again provide use with a choice - use our recipe for `jpeg-turbo` or just provide a path to one in the system.

Regarding plugin - let us keep the prebuild one for now (for the simplicity). Please publish what you got with your recipe so we can see what is needed to restore the ability to build DALI TF pluging with it (I think it should be possible to handle all the stuff inside the conda recipe without touching much of the current code).

Feel free to publish a PR anytime so we can continue our discussion with the real code we can refer to.

**Comment by jayfurmanek** [comment]
>>I'm fine with both. Maybe we can leave it up to the user to decide via some option or variable?

Yeah, conda will pull the package from whatever channel is enabled, so there is choice built in. So for `cudatoolkit` we're fine. The change I was trying to highlight was for `cudatoolkit-dev` which is an additional package that WML CE provides that includes the nvcc compilers. (`cudatoolkit` is just the runtime).

We'll keep the plugin build the same, although maybe disabled as it won't work with the latest code

We'll include the `jpeg-turbo` recipe.

Looking at the CLA now. Hope to have this up soon.

**Comment by JanuszL** [comment]
Sure. I just wanted to have an option to switch to local CUDA SDK if needed, but by default relay on `cudatoolkit-dev`.
So waiting for your CLA.

**Comment by aalugore** [comment]
@JanuszL Here is our initial draft of a working conda recipe: https://github.com/NVIDIA/DALI/pull/1156
Any and all feedback welcome!

**Comment by jantonguirao** [comment]
The conda recipe was merged to master, so this issue can be closed. Thank you @aalugore & @jayfurmanek for your contribution!
