### ISSUE TITLE
How to feed the strings into dali.Pipeline ?

### ISSUE THREAD

**Issue by Beanocean** [NVIDIA/DALI#1130]
I want to get the filenames loaded during the training. If the `ExternalSource` is used, I need to use the `dali.Pipeline.feed_input()` in `dali.Pipeline.iter_setup()`. But the `layout` parameter of  [`dali.Pipeline.feed_input()`](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/api.html#nvidia.dali.pipeline.Pipeline.feed_input) only support [`dali.types.DALITensorLayout`](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/api.html#nvidia.dali.types.DALITensorLayout). How can I achieve my purpose?

**Comment by JanuszL** [comment]
@Beanocean - you can try to do is:
- have two `ExternalSource`, one with the data, other with file names
- convert filename string to a numpy array and feed the second `ExternalSource`
- at the output of the pipeline reverse the process
Another option is to create an array of all file names and just feed the second `ExternalSource` with the values of file name indexes. So no conversion is needed, just a lookup.

**Comment by Beanocean** [comment]
@JanuszL  Thanks a lot for your reply.

The second solution is a good workaround. But there are problems in the first one.

Before asking the question, I have tried to convert the string into a numpy array by using `np.array([filename], dtype=object)`, which finally returned the following error message:
```
  File "lib/python3.7/site-packages/nvidia/dali/pipeline.py", line 377, in _prefetch
    self._run_once()
  File "lib/python3.7/site-packages/nvidia/dali/pipeline.py", line 388, in _run_once
    self.iter_setup()
  File "semseg/dataset/dali.py", line 136, in iter_setup
    self.feed_input(self.path, path)
  File "lib/python3.7/site-packages/nvidia/dali/pipeline.py", line 255, in feed_input
    inp = Edge.TensorListCPU(data, layout)
RuntimeError: [/opt/dali/dali/util/pybind.h:150] Cannot create type for unknown format string: O
```
Maybe I need to convert the chars in the string to ascii code numbers, then use your first solution.

**Comment by JanuszL** [comment]
@Beanocean - yes, I was thinking about converting string to a numerical value, as DALI doesn't support nonnumerical numpy arrays.
