### ISSUE TITLE
decode test image url on gpu when inference time

### ISSUE THREAD

**Issue by xinedison** [NVIDIA/DALI#1132]
Hello, Dali developer，
      I want to use Dali to decode image content in gpu to speed up my model inference and reduced load pressure in cpu. But i can not find a easy way to load image url for inference.Current tutorial all assume we use dali to load data in filesystem, and speedup in training. So is there as simple method to load image data in url to inference in python with dali. 
 Thank you.

**Comment by awolant** [comment]
Hi, thanks for the question.
Right now there is no native support for this in DALI. One idea that comes to mind is writing something based on [ExternalSource](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/external_input.html), where you would obtain the image from the URL in python by hand and pass it to DALI pipeline.

**Comment by xinedison** [comment]
@awolant It works, Thanks for your reply.

**Comment by JanuszL** [comment]
@xinedison,

The best way would be to check [DALI TRITON backend](https://github.com/triton-inference-server/dali_backend/). It should make the inference with DALI much easier.
