### ISSUE TITLE
How can I pass a random number to functions?

### ISSUE THREAD

**Issue by tanglang96** [NVIDIA/DALI#1148]
How can I implement ops like 
`self.crop = ops.Crop(device=dali_device, crop_h=32, crop_w=32, crop_pos_x=random.random(), crop_pos_y=random.random())`

**Comment by awolant** [comment]
Hi @tanglang96 , thanks for the question.

You can do something like this:
```
# In pipeline __init__
self.uniform = ops.Uniform(range = (0., 1.))
self.crop = ops.Crop(device='gpu', crop_h=32, crop_w=32)

# In define_graph
image = self.crop(
    image,
    crop_pos_x = self.uniform(),
    crop_pos_y = self.uniform())
```

For more examples and information, you can refer to [Tensors as arguments and Random Number Generation](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/getting%20started.html#Tensors-as-arguments-and-Random-Number-Generation) section of our docs.

Let me know, if this works for you.

**Comment by tanglang96** [comment]
It actually works, thank you so much @awolant

**Comment by awolant** [comment]
You're welcome! Closing.
