### ISSUE TITLE
Any end-end CNN benchmark example available?

### ISSUE THREAD

**Issue by Zhaojp-Frank** [NVIDIA/DALI#115]
Looks GTC18's talk (http://on-demand.gputechconf.com/gtc/2018/presentation/s8906-fast-data-pipelines-for-deep-learning-training.pdf) expose some end-end CNN training benchmark using DALI e.g., MXNet, ResNet50, multiple GPU, and numbers look exciting!

However in current repo, though some test/benchmark named RN50, it is pre-processing only, not end-end training benchmark. So wondering any end-end CNN training examples available or in-plan to showcase apple-apple comparison? This would help users to better evaluate DALI and build their own end-end pipeline.

Take TensorFlow as example, end-end benchmark may based on TF official repo : https://github.com/tensorflow/benchmarks, completed support is ideal, but I think at least it shall support multi-GPU in single node case (PS in CPU, or PS in GPU), then AllReduce.

Thanks a lot.

**Comment by JanuszL** [comment]
Hi,
We are working to get this kind of official data which can be reproduce by other users.
Nevertheless thank you for your question, it stresses out how important is that for community.

**Comment by JanuszL** [comment]
Internally tracked as a DALI-199.

**Comment by Kh4L** [comment]
End-to-end trainings available in https://github.com/NVIDIA/DALI/tree/master/docs/examples , closing the issue
