### ISSUE TITLE
error about ffmpeg

### ISSUE THREAD

**Issue by QingyueMeng** [NVIDIA/DALI#1164]
Hi,

I compiled ffpmeg-3.4.2 as  instructions and then tried to build DALI,  but I got the following errors:

`[ 60%] Building CXX object dali/CMakeFiles/dali.dir/pipeline/operators/reader/loader/video_loader.cc.o
In file included from /home/ar/mengqingyue/packages/dali/dali/pipeline/operators/reader/loader/video_loader.cc:14:0:
/home/ar/mengqingyue/packages/dali/dali/pipeline/operators/reader/loader/video_loader.h:19:34: fatal error: libavformat/avformat.h: No such file or directory
compilation terminated.
make[2]: *** [dali/CMakeFiles/dali.dir/build.make:487: dali/CMakeFiles/dali.dir/pipeline/operators/reader/loader/video_loader.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:468: dali/CMakeFiles/dali.dir/all] Error 2
make: *** [Makefile:130: all] Error 2`
![image](https://user-images.githubusercontent.com/33691506/62992018-776b6c00-be84-11e9-9c4e-daa274759315.png)
The command I use is 

`cmake --prefix=/home/ar/mengqingyue/opt/NVIDIA-DALI -DNVJPEG_ROOT_DIR=/home/ar/mengqingyue/opt/cuda-linux64-nvjpeg -D JPEG_LIBRARY=/home/ar/mengqingyue/opt/JPEG-8c/lib -D JPEG_INCLUDE_DIR=/home/ar/mengqingyue/opt/JPEG-8c/include -D Protobuf_INCLUDE_DIR=/home/ar/.jumbo/include/ -D Protobuf_LIBRARY=/home/ar/.jumbo/lib/ -D JPEG_LIBRARY=/home/ar/mengqingyue/opt/libjpeg-turbo-1.5.3/lib  -D JPEG_INCLUDE_DIR=/home/ar/mengqingyue/opt/libjpeg-turbo-1.5.3/include -D FFMPEG_ROOT_DIR=/home/ar/mengqingyue/opt/FFmpeg-3.4.2 ..`

Does the ffmpeg linked error? What should I do?

**Comment by JanuszL** [comment]
Hi,
Could you run `make VERBOSE=1`, check the compilation command of the `video_loader.cc.o` file and see if the right include paths are there?
In my case I have `/usr/include/x86_64-linux-gnu/libavformat` and the compilation command has ` -I/usr/include/x86_64-linux-gnu`.

**Comment by JanuszL** [comment]
If you haven't solved your problem please reopen.
