### ISSUE TITLE
hi! there are some op or op_combine same as Random Erasing in DALI?

### ISSUE THREAD

**Issue by bigbrother33** [NVIDIA/DALI#1165]

**Comment by jantonguirao** [comment]
Hi @bigbrother33,

At this moment we don't have a random erase operator. We plan to introduce it at some point in the future, but we can't give you a date at this moment.

However, you can write your own custom operator for it and load it into DALI. Here is a tutorial on how to do that:
https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/extend/create_a_custom_operator.html
You might also find useful this thread https://github.com/NVIDIA/DALI/issues/410 where a user went through the process of creating a custom operator.

Alternatively, you could use our python operator to write custom python code as a DALI operator. You can find the documentation here:
https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/python_operator.html#

The Python operator is good for quick prototyping. If you want to maximize performance you should write a custom operator in C++.

**Comment by bigbrother33** [comment]
> Hi @bigbrother33,
> 
> At this moment we don't have a random erase operator. We plan to introduce it at some point in the future, but we can't give you a date at this moment.
> 
> However, you can write your own custom operator for it and load it into DALI. Here is a tutorial on how to do that:
> https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/extend/create_a_custom_operator.html
> You might also find useful this thread #410 where a user went through the process of creating a custom operator.
> 
> Alternatively, you could use our python operator to write custom python code as a DALI operator. You can find the documentation here:
> https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/python_operator.html#
> 
> The Python operator is good for quick prototyping. If you want to maximize performance you should write a custom operator in C++.

Thx for reply ! I have use PythonFunction to implement, just slow...

**Comment by JanuszL** [comment]
Hi,
You can use erase with random generator like in [this example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/erase.html).

**Comment by MatthewD1993** [comment]
@JanuszL @bigbrother33 is talking about random erasing, which means it should erase a random area at each run, but you are pointing to fixed erasing, is not expected answer...

**Comment by JanuszL** [comment]
Hi @MatthewD1993,

Have you read one of the last sections of the mentioned example:
![image](https://user-images.githubusercontent.com/39967756/123997468-b7805d00-d9d0-11eb-9f2e-1a6254a49f29.png)
?

**Comment by MatthewD1993** [comment]
@JanuszL My bad, didn't read it thoroughly. It's really helpful! Now I have another question, is it possible to fill random value to the erased area? As far as I know, in Pytorch it's able to do that? Thanks!

**Comment by jantonguirao** [comment]
@MatthewD1993 Currently it is not possible to pass random fill values. It'd be relatively simple to add support for that though.

**Comment by JanuszL** [comment]
> @MatthewD1993 Currently it is not possible to pass random fill values. It'd be relatively simple to add support for that though.

Let us add it to our ToDo list.
Also, this sounds like a perfect opportunity for an external contribution
I would start from [erase_utils.h](https://github.com/NVIDIA/DALI/blob/main/dali/operators/generic/erase/erase_utils.h) and [erase.cu)](https://github.com/NVIDIA/DALI/blob/main/dali/operators/generic/erase/erase.cu) and make sure that `fill_value` argument is obtained per each sample separately, not globally. Then you can use a random generator or external source to pass the value, the same way as anchors and shapes.
