### ISSUE TITLE
Using DALI in the intermediate part of Tensorflow graph

### ISSUE THREAD

**Issue by kmkolasinski** [NVIDIA/DALI#1171]
Hi,
Is there a possiblity to use tensorflow tensor as an input to DALI pipeline. I have already working file reading pipeline which uses tf.data.Datasets. I was wandering if there is a possibility to apply DALI augmentations to tensors instead of reading from files or tfrecords. For example I would like to achieve something like that:
```python

images, labels = dataset.make_one_shot_iterator().get_next()
# images a tensor of shape [batch_size, height, width, 3]
# labels - a tensor with e.g. class labels or bounding box annotations 

pipeline = SomeDALIPipeline(images, labels)
new_images, new_labels = pipeline.run()
model = NeuralNet()
predictions = model(new_images)
....
```
Thank you in advance.

**Comment by awolant** [comment]
Hi, thanks for the question.
I'm not sure if I understand correctly what you are trying to do, but maybe it would be possible to make something like this based on [ExternalSource](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/external_input.html), where you would pass the tensors obtained from the `tf.data.Dataset` to the DALI pipeline via `ExternalSource` mechanism and then run the pipeline to get the augmented data on the other end. I'm not sure how exactly this would fit within Tensorflow graph execution model. Maybe you need to wrap DALI pipeline `run` with [tf.py_function](https://www.tensorflow.org/api_docs/python/tf/py_function) or something. I don't know if anyone tried this already and if so, what the outcome was.
If you are working with Tensorflow your safest bet would be to use [DALI Tensorflow plugin](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/plugins/tensorflow_tutorials.html) whenever possible.
BTW. we are working on providing official integration with `tf.data.Dataset` API, but this work is still very much in progress.

**Comment by kmkolasinski** [comment]
Hi, thanks for the quick anwser. 
I think ExternalSource will not fit the tensorflow static graph mode which I use. However, tf.py_function would theoretically do the thing, but the problem is that Pipeline would be initialized at every batch inside `py_function`... I'm not sure if this is efficient way of doing augmentations in DALI. I will wait for the official integration with tf.data.Dataset.
