### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [NVIDIA/DALI#1172]
Would you like to wrap any pointer data members with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

Update candidates:
- [TensorC class](https://github.com/NVIDIA/DALI/blob/6cbd42fdc6b41cd1e05ab0ea25c064fa13944ead/dali/pipeline/operators/transpose/cutt/cuttplan.cc#L142)
- [testCounters() function](https://github.com/NVIDIA/DALI/blob/6cbd42fdc6b41cd1e05ab0ea25c064fa13944ead/dali/pipeline/operators/transpose/cutt/cuttGpuModel.cc#L1373)

**Comment by awolant** [comment]
Hi,
we would be happy to improve our code base in that regard, so if you are willing to contribute we would be happy to review and merge your PR.
The files you pointed out are actually a part of [cuTT](https://github.com/ap-hynninen/cutt) with some minor modifications, I think. AFAIK, cuTT is no longer actively maintained.

**Comment by awolant** [comment]
@elfring We discussed this today and you should know that in the long term we plan to replace cuTT with cuTensor.
Nevertheless, we welcome any contribution to improve the code base.

**Comment by JanuszL** [comment]
Hi,
The cuTT usage has been removed some time ago.
Closing as no longer relevant.
