### ISSUE TITLE
Failed to find any distributed training sampler in DALI

### ISSUE THREAD

**Issue by Kylin9511** [NVIDIA/DALI#1175]
Hi, I am new to DALI from [Apex]() aided PyTorch.

And for distributed training in Apex or latest PyTorch (or even horovod), a distributed training sampler is always included.  The DistributedDataParallel module usually works with `torch.utils.data.distributed.DistributedSampler`. This would ensure the dataset is evenly separated to all the GPUs without any omitting or overlap, making full use of the training data. Also, during validation the sample will make sure the result is stable.

However, I failed to find similar tools in DALI. The random_shuffle in `ops.FileReader` is not able to serve as a replacement, which is the case of [official PyTorch example of DALI](https://github.com/NVIDIA/DALI/blob/master/docs/examples/pytorch/resnet50/main.py).

May I ask if there exist any tool in DALI or any open-source plug-in supporting distributed training sampler for DALI pipeline?

**Comment by Kh4L** [comment]
Hi @Kylin9511 ,

Distributed training (and inference) is handled by the `Reader` ops in DALI and specifying the shard_id and num_shards for each DALI pipeline (take a look at the arguments [here](https://github.com/NVIDIA/DALI/blob/1900068003fd1f3f419e0ae97fa17e5e4b59a982/docs/examples/pytorch/resnet50/main.py#L83)).

The only thing you need to do is to create one (indentical) dali.Pipeline per GPU, with one exception: a different `shard_id` every time.

The dataset is sharded and evenly distributed to all the GPUs, which means that at each epoch, each GPU/DALI pipeline will see `dataset_size/num_shards` samples.

Examples:

- When using Horovod https://github.com/NVIDIA/DALI/blob/1900068003fd1f3f419e0ae97fa17e5e4b59a982/docs/examples/pytorch/resnet50/main.py#L83 , `num_shards` will be `args.world_size`, and each Pipeline will receive `args.local_rank` or `args.rank` if you're doing multi-node.

**Comment by Kylin9511** [comment]
@Kh4L Thank you! I didn't dig deep into the c++ source code of FileReader. In this case it will be very easy to use DALI for data parallel 👍🏻

I think you may describe the distributed sampling strategy that `ops.FileReader` uses briefly here (or in the document ?), for the future comming confuser.

And I have to say, DALI is really awesome~~
