### ISSUE TITLE
CPU/GPU data transfer

### ISSUE THREAD

**Issue by kometa-triatlon** [NVIDIA/DALI#1176]
How does the data transfer between CPU and GPU operators work?

If an operator is only CPU or GPU and has purely CPU or GPU inputs/outpus - it is quite trivial.
But what should I do if my custom GPU operator passes data to a CPU op?

For example, RandomBBoxCrop is purely CPU operator: https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html#randombboxcrop

Despite that, I can call `.gpu()` method that (I believe) copies the data to GPU memory if it is not there yet:

```
crop_begin, crop_size, boxes, labels = self.crop(boxes, labels)
...
return images.gpu(), boxes.gpu(), labels.gpu()
```

In the source code of RandomBBoxCrop I do not see any explicit CPU->GPU memory copy, so I assume it happens automatically.

But the reverse direction does not seem to work: I have a custom GPU operator, which must be connected to a CPU op, and this pipeline fails:

```
crop_begin, crop_size, boxes, labels = self.crop(boxes, labels)
images = self.slice(images, crop_begin, crop_size)
images, boxes, labels = self.patch_box_regions(images, boxes.gpu(), labels.gpu()) 
encoded_boxes, encoded_labels = self.box_encoder(boxes.cpu(), labels.cpu())
```

Here, `self.patch_box_regions` is a custom GPU op. The `self.box_encoder` is an instance of `BoxEncoder`. 

I got this error:
 > RuntimeError: [/opt/dali/dali/pipeline/pipeline.cc:241] Assert on "it->second.has_cpu" failed: cpu input requested by op exists only on gpu. (op: 'BoxEncoder', input: 'PatchBBoxRegions_id_22_output_1')

 - Should the `.cpu()` and `.gpu()` methods work out of the box, without any additional custom code?
 - What is the reason of the error? I have a feeling that pipeline can only follow CPU -> mixed -> GPU direction. So, when I try to insert GPU -> CPU -> GPU part, it fails. Is it correct?

**Comment by awolant** [comment]
Hi, thanks for the question.
Your feeling is correct. DALI does not support GPU->CPU direction. Right now the GPU ops are executed after the CPU ones, so that is the technical reason for this constraint.
In this particular case you can use GPU variant of `BoxEncoder`, I suppose.
Supporting GPU->CPU is on our radar, but will not be happening any time soon.

**Comment by kometa-triatlon** [comment]
Thank you for explaining. You definitely need a better error message then! ;)

**Comment by awolant** [comment]
I improved the error message, added info to our docs and removed the `.cpu()` method to avoid further confusion in #1181 
It's merged, so I'm closing the issue.

**Comment by shamoqianting** [comment]
so if only allow cpu->gpu， how do I check the result on GPU is correct or not ? or maybe I should ask how can I print out the data on gpu?

**Comment by JanuszL** [comment]
> so if only allow cpu->gpu， how do I check the result on GPU is correct or not ? or maybe I should ask how can I print out the data on gpu?

You can get the output from DALI and call `as_cpu()` on it, check[ this example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/getting%20started.html#Copying-tensors-to-GPU) and check the results outside the pipeline.

**Comment by shamoqianting** [comment]
> > so if only allow cpu->gpu， how do I check the result on GPU is correct or not ? or maybe I should ask how can I print out the data on gpu?
> 
> You can get the output from DALI and call `as_cpu()` on it, check[ this example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/getting%20started.html#Copying-tensors-to-GPU) and check the results outside the pipeline.

thank you very much for the reply.
Is there a same function in C++ api ? or is there any document I can refer to ?

**Comment by JanuszL** [comment]
If you are talking about pure C API, you can just use cudaMemCopy from Host to the Device, if you are using C++ structures you can always do:
```
TensorList<CPUBackend> t; // or Tensor<CPUBackend>
t.set_pinned(false);
t.Copy(out, s);
```
where `s` is a cuda stream and out a GPU memory returned from DALI.
