### ISSUE TITLE
Read video frames with specific height and width using VideoReader 

### ISSUE THREAD

**Issue by ptirupat** [NVIDIA/DALI#1183]
Hello,

Is there a way to read video frames with a specific height and width using VideoReader operation? I see that there is a parameter "scale" which is a float value and is the rescale factor for height and width. How do I specify different rescale factors for height and width? To compute these rescale factors, is there a way to get the original height and width of the video?

I have a video of resolution (410, 800) and I want to rescale it to (224, 224) while reading using VideoReader.

**Comment by JanuszL** [comment]
Hi,
Currently, there is no such functionality. Moreover "scale" doesn't work properly either. Long term you should be able to use a resize operator to rescale the frames you read to any size you want.
Adding to our ToDo list.

**Comment by awolant** [comment]
Hi @ptirupat,
recently we introduced [`VideoReaderResize`](https://docs.nvidia.com/deeplearning/dali/master-user-guide/docs/supported_ops.html?highlight=videoreaderresize#nvidia.dali.ops.VideoReaderResize) op that can resize videos. It supports all `Resize` parameters for videos.
It is available in our [nightly build](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/installation.html#nightly-builds).

**Comment by ptirupat** [comment]
Thank you for the update.
