### ISSUE TITLE
Incompatibility with TensorRT?

### ISSUE THREAD

**Issue by predrag12** [NVIDIA/DALI#1196]
Hi,

Can DALI tensor on GPU be passed directly to TensorRT device input buffer?

Looking at python wrapper of DALI, nvidia.dali.backend_impl.TensorGPU has function called copy_to_external, but it is not clear how to use it and point it to TensorRT input buffer which is of type pycuda._driver.DeviceAllocation obtained from cuda.mem_alloc(<nbytes>).

There are no TRT samples to exemplify GPU to GPU copy without intermediate copy to CPU and documentation is not directly addressing it, there is also a related issue https://github.com/NVIDIA/DALI/issues/17, but no updates since 2018. Any ideas if this is doable?

Thanks.

**Comment by awolant** [comment]
Hi, thanks for the question.
I've asked around about this internally.
Let me get back to you on this.

**Comment by predrag12** [comment]
Hi,
When one uses ctypes.c_void_p directly on the DALI tensor the results are not correct relative to copying back and forth to and from CPU memory.

# errors out in invalid parameter
pipeline.run()[0].copy_to_external(ctypes.c_void_p(int(device_mem)))

# no exception but image is incorrect, different from GPU->CPU->GPU
pipeline.run().at(0).copy_to_external(ctypes.c_void_p(int(device_mem)))

Thanks.

**Comment by predrag12** [comment]
Hi @awolant,

Any updates on the topic? Since this is inference and TRT rather than training, has this been done before, and is it expected to work with only client code refactoring, or would it require TRT plugin like with TensorFlow and PyTorch?

Thanks.

**Comment by awolant** [comment]
@predrag12 sorry for the delay.

I've checked the PyCuda-DALI interoperability and code below works for me:
```python
import pycuda.driver as cuda
import pycuda.autoinit
import numpy as np
import os
import nvidia.dali.ops as ops
import nvidia.dali.types as types
from nvidia.dali.pipeline import Pipeline
import ctypes

dali_extra_path = os.environ['DALI_EXTRA_PATH']
image_dir = os.path.join(dali_extra_path, 'db/single/jpeg')
BATCH_SIZE = 64
SIZE = 416

class DaliPipeline(Pipeline):
  def __init__(self, batch_size, num_threads, device_id):
    super(DaliPipeline, self).__init__(
      batch_size,
      num_threads,
      device_id,
      exec_async=True,
      exec_pipelined=True)

    self.input = ops.FileReader(
      file_root=image_dir)
    self.decode = ops.ImageDecoder(
      device="mixed", output_type=types.RGB)
    self.resize = ops.Resize(
      device="gpu",
      image_type=types.RGB,
      interp_type=types.INTERP_LINEAR,
      resize_x=SIZE,
      resize_y=SIZE)


  def define_graph(self):
    images, labels = self.input(name="Reader")
    images = self.decode(images)
    images = self.resize(images)
    return images


if __name__ == '__main__':
  pipes = DaliPipeline(batch_size=BATCH_SIZE, num_threads=4, device_id=0)
  pipes.build()

  size = SIZE*SIZE*3*BATCH_SIZE*4
  device_mem = cuda.mem_alloc(size)

  c_type_pointer = ctypes.c_void_p(int(device_mem))

  for i in range(20):
    dali_tensor = pipes.run()
    dali_tensor[0].copy_to_external(c_type_pointer)

    dali_out = dali_tensor[0].as_cpu().as_array()
    pycuda_out = np.empty_like(dali_out)
    cuda.memcpy_dtoh(pycuda_out, device_mem)
    print(np.array_equal(pycuda_out, dali_out))
```
On my machine `pycuda_out` and `dali_out` are always the same.

If I understand you correctly this is more or less what you wanted to do: copy GPU DALI output directly to PyCUDA device memory? 

Could you provide more complete reproduction of this issue?

**Comment by predrag12** [comment]
Hi @awolant,

Thanks for the sample code, copy_to_external works as expected. I may have missed in my original code the np size allocation on the way back from the device memory.

Thank you.
