### ISSUE TITLE
error loading DALI TF plugin for tf 1.14.0

### ISSUE THREAD

**Issue by chenghuige** [NVIDIA/DALI#1200]
1 import nvidia.dali.plugin.tf as dali_tf

/home/gezi/env/anaconda3/lib/python3.6/site-packages/nvidia/dali/plugin/tf.py in <module>()
     33     pass
     34 else:
---> 35   raise Exception('No matching DALI plugin found for installed TensorFlow version')
     36 
     37 _dali_tf = _dali_tf_module.dali

Exception: No matching DALI plugin found for installed TensorFlow version

----> 1 tf.load_op_library('/home/gezi/env/anaconda3/lib/python3.6/site-packages/nvidia/dali/plugin/libdali_tf_current.so')

/home/gezi/env/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py in load_op_library(library_filename)
     59     RuntimeError: when unable to load the library or get the python wrappers.
     60   """
---> 61   lib_handle = py_tf.TF_LoadLibrary(library_filename)
     62 
     63   op_list_str = py_tf.TF_GetOpList(lib_handle)

NotFoundError: /home/gezi/env/anaconda3/lib/python3.6/site-packages/nvidia/dali/plugin/libdali_tf_current.so: undefined symbol: _ZN10tensorflow14DataTypeStringENS_8DataTypeE

So if I want to use dali tf plugin, must I compile tensorflow-gpu from source ? Could I use the prebuilt tensorflow ?

**Comment by jantonguirao** [comment]
Hi @chenghuige,
There are some binary compatibility problems when you mix a tensorflow-gpu and DALI tensorflow plugin build with different compilers. DALI TF plugin already tries to prevent that by trying to provide a prebuilt version of DALI tensorflow plugin when it detects your current compiler doesn't match the one used to build tensorflow. We will need some more details to check whether we have a bug in the installation script.

Could you please share your:
- DALI installation steps and currently installed version number?
- TF installation steps and currently installed version number?
- Your compiler version (e.g. see `g++ --version`)

**Comment by chenghuige** [comment]
@jantonguirao  
1. dali installation 
pip list | grep dali
nvidia-dali                        0.12.0
nvidia-dali-tf-plugin              0.12.0
pip install --extra-index-url https://developer.download.nvidia.com/compute/redist/cuda/10.0 nvidia-dali-tf-plugin==0.12.0
2. tf installation 
pip install tensorflow-gpu==1.14.0
3. gcc -v
gcc 版本 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC)

**Comment by jantonguirao** [comment]
@chenghuige Thanks for the information.
One more thing that could help us investigate this issue. Could you please run the pip installation of nvidia-dali-tf-plugin with `--verbose` flag and attach the logs here?

**Comment by chenghuige** [comment]
@jantonguirao like below 
 Found link https://developer.download.nvidia.cn/compute/redist/cuda/10.0/nvidia-dali/nvidia_dali-0.12.0-819496-cp36-cp36m-manylinux1_x86_64.whl (from https://developer.download.nvidia.cn/compute/redist/cuda/10.0/nvidia-dali/), version: 0.12.0
  Using version 0.12.0 (newest of versions: 0.12.0)
  Created temporary directory: /tmp/pip-unpack-lijrrox5
  Looking up "https://developer.download.nvidia.cn/compute/redist/cuda/10.0/nvidia-dali/nvidia_dali-0.12.0-819496-cp36-cp36m-manylinux1_x86_64.whl" in the cache
  Ignoring unknown cache-control directive:
  Current age based on date: 678314
  Freshness lifetime from max-age: 604800
  https://developer.download.nvidia.cn:443 "GET /compute/redist/cuda/10.0/nvidia-dali/nvidia_dali-0.12.0-819496-cp36-cp36m-manylinux1_x86_64.whl HTTP/1.1" 304 0
  Using cached https://developer.download.nvidia.cn/compute/redist/cuda/10.0/nvidia-dali/nvidia_dali-0.12.0-819496-cp36-cp36m-manylinux1_x86_64.whl
  Downloading from URL https://developer.download.nvidia.cn/compute/redist/cuda/10.0/nvidia-dali/nvidia_dali-0.12.0-819496-cp36-cp36m-manylinux1_x86_64.whl (from https://developer.download.nvidia.cn/compute/redist/cuda/10.0/nvidia-dali/)
Requirement already satisfied: future in /search/odin/chenghuige/env/anaconda3/lib/python3.6/site-packages (from nvidia-dali==0.12.0->nvidia-dali-tf-plugin==0.12.0) (0.17.1)
tensorboard 1.14.0 has requirement setuptools>=41.0.0, but you'll have setuptools 39.1.0 which is incompatible.
jupyterlab-server 1.0.0 has requirement jsonschema>=3.0.1, but you'll have jsonschema 2.6.0 which is incompatible.
Installing collected packages: nvidia-dali, nvidia-dali-tf-plugin

  changing mode of /home/gezi/env/anaconda3/bin/rec2idx to 755

Successfully installed nvidia-dali-0.12.0 nvidia-dali-tf-plugin-0.12.0
Cleaning up...
You are using pip version 10.0.1, however version 19.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by jantonguirao** [comment]
It looks like the requirement was already satisfied so it didn't try to install again:
```
Requirement already satisfied: future in /search/odin/chenghuige/env/anaconda3/lib/python3.6/site-packages (from nvidia-dali==0.12.0->nvidia-dali-tf-plugin==0.12.0) (0.17.1)
```
Can you collect the logs from a clean install (remove the package first)?

**Comment by chenghuige** [comment]
@jantonguirao  below
Installing collected packages: nvidia-dali-tf-plugin
  Created temporary directory: /tmp/pip-record-aji_2j3d
  Running setup.py install for nvidia-dali-tf-plugin ...     Running command /home/gezi/env/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-0_yyhdfc/nvidia-dali-tf-plugin/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-aji_2j3d/install-record.txt --single-version-externally-managed --compile
    running install
    which: no g++-4.8 in (/home/gezi/env/anaconda3/condabin:/home/gezi/env/anaconda3/bin:/home/gezi/tools/bin:/home/gezi/tools/:/home/gezi/soft/py3env/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/ibutils/bin:/root/bin)
    <命令行>:0:0: 警告：“_GLIBCXX_USE_CXX11_ABI”重定义 [默认启用]
    <命令行>:0:0: 附注：这是先前定义的位置
    running build
    running install_egg_info
    running egg_info
    writing nvidia_dali_tf_plugin.egg-info/PKG-INFO
    writing dependency_links to nvidia_dali_tf_plugin.egg-info/dependency_links.txt
    writing requirements to nvidia_dali_tf_plugin.egg-info/requires.txt
    writing top-level names to nvidia_dali_tf_plugin.egg-info/top_level.txt
    reading manifest file 'nvidia_dali_tf_plugin.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.h'
    writing manifest file 'nvidia_dali_tf_plugin.egg-info/SOURCES.txt'
    Copying nvidia_dali_tf_plugin.egg-info to /home/gezi/env/anaconda3/lib/python3.6/site-packages/nvidia_dali_tf_plugin-0.12.0-py3.6.egg-info
    running install_scripts
    writing list of installed files to '/tmp/pip-record-aji_2j3d/install-record.txt'
done
  Removing source in /tmp/pip-install-0_yyhdfc/nvidia-dali-tf-plugin
Successfully installed nvidia-dali-tf-plugin-0.12.0
Cleaning up...

I tried to ln /usr/bin/g++ /usr/bin/g++4.8 and reinstall but still could not load dali tf plugin.

**Comment by jantonguirao** [comment]
@chenghuige We've submitted a patch that we believe will solve your issue. Could you please test our nightly build and let us know if it solves your problem?

1. Uninstall previously installed nvidia-dali and nvidia-dali-tf-plugin
2. Install nvidia-dali-nightly (here using cuda 10, you can change to cuda 9 path if that's what you have)
```
pip install --verbose --force-reinstall --extra-index-url https://developer.download.nvidia.com/compute/redist/nightly/cuda/10.0 nvidia-dali-nightly
```
2. Install nvidia-dali-tf-plugin-nightly
```
pip install --verbose --force-reinstall --extra-index-url https://developer.download.nvidia.com/compute/redist/nightly/cuda/10.0 nvidia-dali-tf-plugin-nightly
```

**Comment by chenghuige** [comment]
@jantonguirao , seems still could not load plugin for me
Using version 0.17.1 (newest of versions: 0.0.1, 0.0.2, 0.0.3, 0.1.0, 0.2.0, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.4.0, 0.4.1, 0.5.0, 0.5.1, 0.5.2, 0.6.0, 0.7.0, 0.8.0, 0.8.1, 0.8.2, 0.9.0, 0.10.0, 0.10.1, 0.10.2, 0.11.0, 0.11.1, 0.11.2, 0.11.3, 0.11.4, 0.12.0, 0.12.1, 0.12.2, 0.12.3, 0.12.4, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.14.2, 0.14.3, 0.15.0, 0.15.1, 0.15.2, 0.16.0, 0.17.0, 0.17.1)
  Using cached wheel link: file:///root/.cache/pip/wheels/0c/61/d2/d6b7317325828fbb39ee6ad559dbe4664d0896da4721bf379e/future-0.17.1-cp36-none-any.whl
Building wheels for collected packages: nvidia-dali-tf-plugin-nightly
  Created temporary directory: /tmp/pip-wheel-yuf2ok7l
  Running setup.py bdist_wheel for nvidia-dali-tf-plugin-nightly ...   Destination directory: /tmp/pip-wheel-yuf2ok7l
  Running command /home/gezi/env/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-32fi8ey7/nvidia-dali-tf-plugin-nightly/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-yuf2ok7l --python-tag cp36
  /home/gezi/env/anaconda3/lib/python3.6/site-packages/setuptools/dist.py:388: UserWarning: Normalizing '0.14.0dev.20190828' to '0.14.0.dev20190828'
    normalized_version,
  running bdist_wheel
  running build
  installing to build/bdist.linux-x86_64/wheel
  running install
  <命令行>:0:0: 警告：“_GLIBCXX_USE_CXX11_ABI”重定义 [默认启用]
  <命令行>:0:0: 附注：这是先前定义的位置
  running install_egg_info
  running egg_info
  writing nvidia_dali_tf_plugin_nightly.egg-info/PKG-INFO
  writing dependency_links to nvidia_dali_tf_plugin_nightly.egg-info/dependency_links.txt
  writing requirements to nvidia_dali_tf_plugin_nightly.egg-info/requires.txt
  writing top-level names to nvidia_dali_tf_plugin_nightly.egg-info/top_level.txt
  reading manifest file 'nvidia_dali_tf_plugin_nightly.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.h'
  writing manifest file 'nvidia_dali_tf_plugin_nightly.egg-info/SOURCES.txt'
  Copying nvidia_dali_tf_plugin_nightly.egg-info to build/bdist.linux-x86_64/wheel/nvidia_dali_tf_plugin_nightly-0.14.0.dev20190828-py3.6.egg-info
  running install_scripts
  creating build/bdist.linux-x86_64/wheel/nvidia_dali_tf_plugin_nightly-0.14.0.dev20190828.dist-info/WHEEL
  creating '/tmp/pip-wheel-yuf2ok7l/nvidia_dali_tf_plugin_nightly-0.14.0.dev20190828-cp36-none-any.whl' and adding '.' to it
  adding 'nvidia_dali_tf_plugin_nightly-0.14.0.dev20190828.dist-info/top_level.txt'
  adding 'nvidia_dali_tf_plugin_nightly-0.14.0.dev20190828.dist-info/WHEEL'
  adding 'nvidia_dali_tf_plugin_nightly-0.14.0.dev20190828.dist-info/METADATA'
  adding 'nvidia_dali_tf_plugin_nightly-0.14.0.dev20190828.dist-info/RECORD'
  removing build/bdist.linux-x86_64/wheel
done
  Stored in directory: /root/.cache/pip/wheels/a1/cc/61/fe6d331b275637145d3b3d06ba2ebf74d0f6c132494071bbdc
  Removing source in /tmp/pip-install-32fi8ey7/nvidia-dali-tf-plugin-nightly
Successfully built nvidia-dali-tf-plugin-nightly

**Comment by chenghuige** [comment]
@jantonguirao  could  it be my conda env ? I installed gcc 7 on this env

**Comment by jantonguirao** [comment]
@chenghuige Sorry for the late reply. There is a bit of logic in our `nvidia-dali-tf-plugin` installation script in order to determine whether to provide a prebuilt plugin or use the system's compiler. 
The following script will collect some info about your environment, in a similar way to what is done inside the installation script. Could you please run this script and paste the output here?
```
import subprocess
import os
import re
import sys
import platform

import os, fnmatch
def find(pattern, path):
    result = []
    for root, dirs, files in os.walk(path):
        for name in files:
            if fnmatch.fnmatch(name, pattern):
                result.append(os.path.join(root, name))
    return result

def get_module_path(module_name):
    module_path = ''
    for d in sys.path:
        possible_path = os.path.join(d, module_name)
        # skip current dir as this is plugin dir
        if os.path.isdir(possible_path) and len(d) != 0:
            module_path = possible_path
            break
    return module_path

def get_tf_compiler_version():
    tensorflow_path = get_module_path('tensorflow')
    tensorflow_libs = find('libtensorflow_framework*so*', tensorflow_path)
    if not tensorflow_libs:
        return ''
    lib = tensorflow_libs[0]
    cmd = 'strings -a ' + lib + ' | grep "GCC: ("'
    s = str(subprocess.check_output(cmd, shell=True))
    version = re.search("GCC:\s*\(.*\)\s*(\d+.\d+).\d+", s).group(1)
    return version

def get_tf_version():
    import pkg_resources
    s = pkg_resources.get_distribution("tensorflow-gpu").version
    version = re.search("(\d+.\d+).\d+", s).group(1)
    return version

def get_gpp_compiler():
    return os.environ.get('CXX') or 'g++'

def get_gpp_compiler_version():
    cmd = get_gpp_compiler() + ' --version | head -1 | grep "g++ ("'
    s = str(subprocess.check_output(cmd, shell=True).strip())
    version = re.search("g\+\+\s*\(.*\)\s*(\d+.\d+).\d+", s).group(1)
    return version

def which(program):
    try:
        return subprocess.check_output('which ' + program, shell=True).strip()
    except:
        return None

dali_lib_path = get_module_path('nvidia/dali')
print("DALI lib path:                        {}".format(dali_lib_path))
plugin_dest_dir = dali_lib_path + '/plugin'
print("DALI TF plugin destination directory: {}".format(plugin_dest_dir))
tf_version = get_tf_version()
print("TF version installed:                 {}".format(tf_version))
tf_compiler = get_tf_compiler_version()
print("g++ version used to compile TF:       {}".format(tf_compiler))
gpp_compiler = get_gpp_compiler()
default_gpp_version = get_gpp_compiler_version()
print("Using compiler:                      \"{}\", version {}".format(gpp_compiler, default_gpp_version))
is_tf_built_with_gpp_4_8 = tf_compiler == '4.8'
print("Is TF compiled with g++ 4.8?          {}".format(is_tf_built_with_gpp_4_8))
has_gpp_4_8 = which('g++-4.8') is not None
print("Is g++-4.8 present in the system?     {}".format(has_gpp_4_8))
is_compatible_with_prebuilt_bin = platform.system() == 'Linux' and platform.machine() == 'x86_64'
print("Platform system:                      {}".format(platform.system()))
print("Platform machine:                     {}".format(platform.machine()))

should_install_prebuilt = is_tf_built_with_gpp_4_8 and is_compatible_with_prebuilt_bin
print("Should install prebuilt plugin?       {}".format(should_install_prebuilt)
```

**Comment by jantonguirao** [comment]
@chenghuige 
We have updated the DALI TF installation logic. Could you check whether it helps for your environment by installing our nightly build? At the very least it should give you a more detailed error message.

Could you please run in your conda environment (you might have to uninstall previously installed DALI):
```
python -m pip install --extra-index-url https://developer.download.nvidia.com/compute/redist/nightly/cuda/10.0 nvidia-dali-nightly --force-reinstall --verbose
```
and then 
```
python -m pip install --extra-index-url https://developer.download.nvidia.com/compute/redist/nightly/cuda/10.0 nvidia-dali-tf-plugin-nightly --force-reinstall --verbose
```

It might happen that you get an error message if your compiler can't match the compiler used to build your tensorflow version. For example
```
    ImportError: Installation error:
     Conda C++ compiler version should be the same as the compiler used to build tensorflow (7.3 != 5.4).
     Try to run `conda install gxx_linux-64==5.4` or install an alternative compiler `g++-5.4` and install again
```

There are two ways you can workaround that:
1. Run `conda install gxx_linux-64==5.4` to match the compiler version used to build your tensorflow (I am using 5.4 because that is what I had)
2. If you have this compiler in the system you can provide a symlink to an alternative compiler:
`ln -s /usr/bin/g++ /usr/bin/g++-5.4` (Assuming that `/usr/bin/g++` is actuall g++ 5.4)

**Comment by chenghuige** [comment]
@jantonguirao Thanks! After conda install gxx 5.4, now I can load the plugin. Closing issue.
