### ISSUE TITLE
Does DALI support loading multiple LMDB files?

### ISSUE THREAD

**Issue by 00liujj** [NVIDIA/DALI#1208]
e.g. 

self.input = ops.CaffeReader(path = [db_folder1, db_folder2, db_folder3])

How about tfrecord or recordio files?

**Comment by awolant** [comment]
Hi, thanks for the question.
Currently DALI does not support something like this for LMDB.
For RecordIO and TFRecord you can pass multiple paths. Please look into [Data loading section](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/dataloading.html) of our examples. You can also look into our docs for [`MXNetReader`](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html?highlight=mxnet%20reader#nvidia.dali.ops.MXNetReader) and [`TFRecordReader`](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html?highlight=tfrecordreader#nvidia.dali.ops.TFRecordReader).

**Comment by 00liujj** [comment]
Thank you for your answer. I 've got a solution:  Use 2 CaffeReader in a pipeline, the graph has 4 outputs: image1, label1, image2, label2, then concat them in caffe.

**Comment by awolant** [comment]
Currently all operators within the pipeline must have the same batch size.
Alternatively, you could look into [`ExternalSource`](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/external_input.html) to write data loading from multiple files in python and pass it to DALI or [create custom C++ op](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/extend/create_a_custom_operator.html) to do this.
Lastly, if you are willing to extend existing `CaffeReader` and post a PR we would be happy to review and merge it.

**Comment by 00liujj** [comment]
Thank you, I'll try to extend that.

**Comment by JanuszL** [comment]
This change is available in [DALI 0.16.0](https://github.com/NVIDIA/DALI/releases/tag/v0.16.0).
