### ISSUE TITLE
 uses Dali to process images under multi GPU and uses multi GPU inference。

### ISSUE THREAD

**Issue by LCWdmlearning** [NVIDIA/DALI#121]
i try to uses Dali to process images under multi GPU and uses multi GPU inference。
code：

     class FileReadPipeline(Pipeline):
            def __init__(self, batch_size, num_threads, device_id,path,image_size):
                super(FileReadPipeline, self).__init__(batch_size, num_threads, device_id, seed=12)
                self.input = ops.FileReader(file_root=path, random_shuffle=True, initial_fill=21)
                self.decode = ops.nvJPEGDecoder(device="mixed", output_type=types.RGB)
                self.resize = ops.Resize(device="gpu", random_resize=True,
                                 resize_a=image_size, resize_b=image_size,
                                 image_type=types.RGB,
                                 interp_type=types.INTERP_LINEAR)
                self.cmn = ops.CropMirrorNormalize(device="gpu",
                                           output_dtype=types.FLOAT,
                                           crop=(227, 227),
                                           image_type=types.RGB,
                                           mean=[128., 128., 128.],
                                           std=[1., 1., 1.])
                self.uniform = ops.Uniform(range=(0.0, 1.0))

           def define_graph(self):
                jpegs, labels = self.input()
                images = self.decode(jpegs)
                resized_images = self.resize(images)
                output = self.cmn(resized_images, crop_pos_x=self.uniform(),
                          crop_pos_y=self.uniform())
                return (output, labels.gpu())

     def get_batch_dali(batch_size,image_size,path,gpu_count):
          pipes = [FileReadPipeline(batch_size=batch_size, num_threads=24, 
          device_id=device_id,path=path,image_size=image_size) for device_id in
               range(gpu_count)]
          serialized_pipes = [pipe.serialize() for pipe in pipes]
          del pipes
          daliop = dali_tf.DALIIterator()
          images = []
          labels = []
          for d in range(gpu_count):
              with tf.device('/gpu:%i' % d):
                  image, label = daliop(serialized_pipeline=serialized_pipes[d],
                                  batch_size=batch_size,
                                  height=image_size,
                                  width=image_size,
                                  device_id=d)
                  images.append(image)
                  labels.append(label)
        return [images, labels]
    def main_run():
        test_batch = get_batch_test_dali(BATCH_SIZE,IMAGE_SIZE,PATH,GPU_COUNT)
        for i in range(GPU_COUNT):
            with tf.device('/gpu:%d' % i):
                x = tf.placeholder(tf.float32, shape=[BATCH_SIZE, IMAGE_SIZE, IMAGE_SIZE, 3], name='x')
                model = alexnet.alexNet(x, str(i), dropoutPro, classNum, skip)
                softmax_arr.append(model)
                placeholder_arr.append(x)
        config = tf.ConfigProto()
        config.gpu_options.per_process_gpu_memory_fraction = 0.5
        with tf.Session(config=config) as sess:
             sess.run(tf.global_variables_initializer())
            threads = []
            for i in range(len(softmax_arr)):
                threads.append(threading.Thread(target=run_sess, args=(str(i), sess,test_batch, softmax_arr[i], placeholder_arr[i])))
            for t in threads:
                t.start()
            for t in threads:
                t.join()
            sess.close()
    main_run()
###################################
and i got some error:
     
InternalError: DALI label_tensor_shape = daliShapeAt(&pipe_handle_, 1) failed: [/opt/dali/dali/pipeline/workspace/workspace.h:123] Index 1 out of range [0, 1).
	 [[Node: Dali_1 = Dali[batch_size=16, device_id=1, height=227, num_threads=2, serialized_pipeline="\010\030\0...0\000@\001", width=227, _device="/job:localhost/replica:0/task:0/device:GPU:1"]()]]
	 [[Node: Dali_1/_27 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:1", send_device_incarnation=1, tensor_name="edge_20_Dali_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

#############
If I set the number of GPU to 1, it will be normal.

**Comment by wangguangyuan** [comment]
class ClassCommonPipeline(Pipeline):
    def __init__(self,
                 batch_size,
                 num_threads,
                 dali_device_id,
                 size=(224, 224),
                 crop_size=(224, 224),
                 seed=12,
                 mean=IMAGE_MEAN,
                 std=IMAGE_STD,
                 output_type=types.RGB,
                 channel_format=types.NHWC,
                 probability=0.5,
                 device='gpu',
                 decode_method='in_gpu'):

        super(ClassCommonPipeline, self).__init__(batch_size, num_threads, dali_device_id, seed=seed)

        assert (device == 'gpu' and decode_method == 'in_gpu') or (device == 'cpu' and decode_method == 'in_cpu')

        self.device = device
        self.decode_method = decode_method

        if decode_method == 'in_gpu':
            self.decode = ops.nvJPEGDecoder(device="mixed", output_type=output_type)
        else:
            self.decode = ops.HostDecoder(output_type=output_type)

        self.rrc = ops.RandomResizedCrop(device=device, size=size)

        self.cmnp = ops.CropMirrorNormalize(device=device,
                                            output_dtype=types.FLOAT,
                                            output_layout=channel_format,
                                            image_type=output_type,
                                            crop=crop_size,
                                            mean=mean,
                                            std=std)

        self.coin = ops.CoinFlip(probability=probability)
        # self.cast = ops.Cast(device=device, dtype=types.FLOAT16)

    def base_define_graph(self, inputs, labels):
        rng = self.coin()
        images = self.decode(inputs)
        images = self.rrc(images)
        images = self.cmnp(images, mirror=rng)
        # images = self.cast(images)
        if self.decode_method == 'in_gpu' and self.device == 'gpu':
            return images, labels.gpu()
        else:
            return images, labels


class ClassFileReadPipeline(ClassCommonPipeline):
    def __init__(self,
                 batch_size,
                 num_threads,
                 dali_device_id,
                 random_shuffle,
                 file_root='',
                 file_list='',
                 size=(224, 224),
                 crop_size=(224, 224),
                 seed=12,
                 mean=IMAGE_MEAN,
                 std=IMAGE_STD,
                 output_type=types.RGB,
                 channel_format=types.NHWC,
                 probability=0.5,
                 device='gpu',
                 decode_method='in_gpu',
                 initial_fill=4096):

        super(ClassFileReadPipeline, self).__init__(batch_size=batch_size,
                                                    num_threads=num_threads,
                                                    dali_device_id=dali_device_id,
                                                    size=size,
                                                    crop_size=crop_size,
                                                    seed=seed,
                                                    mean=mean,
                                                    std=std,
                                                    output_type=output_type,
                                                    channel_format=channel_format,
                                                    probability=probability,
                                                    device=device,
                                                    decode_method=decode_method)

        self.input = ops.FileReader(file_root=file_root, file_list=file_list,
                                    random_shuffle=random_shuffle, initial_fill=initial_fill)

    def define_graph(self):
        images, labels = self.input()
        return self.base_define_graph(images, labels)


def get_batch_images(pipe_name,
                     batch_size,
                     num_threads,
                     device_id,
                     random_shuffle,
                     dali_device_id,
                     shape,
                     file_root='',
                     file_list='',
                     size=(224, 224),
                     crop_size=(224, 224),
                     seed=12,
                     mean=IMAGE_MEAN,
                     std=IMAGE_STD,
                     output_type=types.RGB,
                     channel_format=types.NHWC,
                     probability=0.5,
                     device='gpu',
                     decode_method='in_gpu',
                     initial_fill=4096):

    pipes = pipe_name(batch_size=batch_size,
                      num_threads=num_threads,
                      dali_device_id=dali_device_id,
                      random_shuffle=random_shuffle,
                      file_root=file_root,
                      file_list=file_list,
                      size=size,
                      crop_size=crop_size,
                      seed=seed,
                      mean=mean,
                      std=std,
                      output_type=output_type,
                      channel_format=channel_format,
                      probability=probability,
                      device=device,
                      decode_method=decode_method,
                      initial_fill=initial_fill)

    print(pipes)
    serialized_pipes = pipes.serialize()

    daliop_t = dali_tf.DALIIterator()

    print('/gpu:%i' % device_id)
    with tf.device('/gpu:%i' % device_id):
        image, label = daliop_t(serialized_pipeline=serialized_pipes,
                                shape=shape,
                                image_type=tf.float32,
                                label_type=tf.int32,
                                num_threads=num_threads,
                                device_id=dali_device_id)

        return image, label

train_image, train_label = get_batch_images(pipe_name=ClassFileReadPipeline, batch_size=args.batch_size,
                                                    num_threads=2, device_id=0, random_shuffle=True,
                                                    dali_device_id=hvd.local_rank(),
                                                    shape=[args.batch_size, 3, 224, 224],
                                                    channel_format=types.NCHW, file_list='./test.txt',
                                                    seed=hvd.local_rank())

pu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.7)
    config = tf.ConfigProto(gpu_options=gpu_options)
    config.gpu_options.visible_device_list = str(hvd.local_rank())
    sess = tf.Session(config=config)

For tensoeflow, the device_id of tensorflow is different from the device_id of dali.

When you run a program with multiple processes, you need to assign a gpu to each process. Regardless of the real gpu id, the id of tensorflowd gpu is zero, and dali uses the id of the real gpu. So I provided two parameters, device_id and dali_device_id.

Not too sure if you are experiencing this problem, I hope I can give you some tips.

**Comment by JanuszL** [comment]
Internally tracked - DALI-204

**Comment by LCWdmlearning** [comment]
thanks,

**Comment by LCWdmlearning** [comment]
Thank you wangguangyuan and JanuszL,I still can't solve this problem.

**Comment by JanuszL** [comment]
@LCWdmlearning - I need to rework your example a bit to be able to launch it, it works fine for me. If it is not the case please provide a minimal example that crashes (no external dependency would be best), so we can easily reproduce your problem on our own.
```
from subprocess import call
import os.path
from nvidia.dali.pipeline import Pipeline
import nvidia.dali.ops as ops
import nvidia.dali.types as types
import nvidia.dali.tfrecord as tfrec
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import nvidia.dali.plugin.tf as dali_tf
from timeit import default_timer as timer
import threading

IMAGE_MEAN = [128., 128., 128.]
IMAGE_STD = [1., 1., 1.]
GPU_COUNT = 2
BATCH_SIZE = 12
IMAGE_SIZE = 227
PATH = 'XXX'

class FileReadPipeline(Pipeline):
    def __init__(self, batch_size, num_threads, path, device_id, num_gpus):
        super(FileReadPipeline, self).__init__(batch_size, num_threads, device_id, seed=12)
        self.input = ops.FileReader(file_root=path, random_shuffle=True, initial_fill=21, num_shards = num_gpus)

        self.decode = ops.nvJPEGDecoder(device = "mixed", output_type = types.RGB)
        self.resize = ops.Resize(device = "gpu",
                                 image_type = types.RGB,
                                 interp_type = types.INTERP_LINEAR)
        self.cmn = ops.CropMirrorNormalize(device = "gpu",
                                            output_dtype = types.FLOAT,
                                            crop = (224, 224),
                                            image_type = types.RGB,
                                            mean = [128., 128., 128.],
                                            std = [1., 1., 1.])
        self.res_uniform = ops.Uniform(range = (256.,480.))
        self.uniform = ops.Uniform(range = (0.0, 1.0))
        self.cast = ops.Cast(device = "gpu",
                             dtype = types.INT32)

    def define_graph(self):
        inputs, labels = self.input(name="Reader")
        images = self.decode(inputs)
        images = self.resize(images, resize_shorter = self.res_uniform())
        output = self.cmn(images, crop_pos_x = self.uniform(),
                          crop_pos_y = self.uniform())
        output = self.cast(output)
        return (output, labels.gpu())


def get_batch_dali(batch_size,image_size,path,gpu_count):
    pipes = [FileReadPipeline(batch_size=batch_size, num_threads=24, 
    device_id=device_id,path=path,num_gpus=gpu_count) for device_id in
        range(gpu_count)]
    serialized_pipes = [pipe.serialize() for pipe in pipes]
    del pipes
    daliop = dali_tf.DALIIterator()
    images = []
    labels = []
    for d in range(gpu_count):
        with tf.device('/gpu:%i' % d):
            image, label = daliop(serialized_pipeline=serialized_pipes[d],
                            shape = [BATCH_SIZE, 3, 224, 224],
                            image_type = tf.int32,
                            label_type = tf.float32,
                            device_id=d)
            images.append(image)
            labels.append(label)
    return [images, labels]

def main_run():
    test_batch = get_batch_dali(BATCH_SIZE,IMAGE_SIZE,PATH,GPU_COUNT)
    config = tf.ConfigProto()
    config.gpu_options.per_process_gpu_memory_fraction = 0.5
    with tf.Session(config=config) as sess:
        sess.run(tf.global_variables_initializer())
        threads = []
        for i in xrange(0,GPU_COUNT):
            print "GPU", i
            threads.append(threading.Thread(target=sess.run, args=[test_batch]))
        for t in threads:
            t.start()
        for t in threads:
            t.join()
        sess.close()
main_run()
```

**Comment by JanuszL** [comment]
If problem still persists please reopen.
