### ISSUE TITLE
NVIDIA OPTICAL FLOW SDK

### ISSUE THREAD

**Issue by ideaRunner** [NVIDIA/DALI#1216]
Since the Nvidia Optical Flow SDK 1.0 released at 10 Jan, 2019,
Should I assume that the optical flow API in DALI [pull 434](https://github.com/NVIDIA/DALI/pull/434) that pulled in 14 Jan and merged, already implement NVOF SDK?

**Comment by awolant** [comment]
Hi, thanks for the question.
Yes, for the capable devices DALI uses Nvidia Optical Flow SDK: https://github.com/NVIDIA/DALI/blob/master/dali/pipeline/operators/optical_flow/turing_of/optical_flow_turing.h

**Comment by ideaRunner** [comment]
Oh, Thanks!   It's awesome! !
It's very convenient for us who develop by Python.
BTW, as you mentioned about capable devices, is there a way to check whether it is uwsing Nvidia Optical Flow SDK?
My device is capable, I want to make sure that it's accelerated by NVOF.

**Comment by awolant** [comment]
We don't have any other implementation of optical flow available. If it works, it uses Nvidia Optical Flow SDK.

**Comment by ideaRunner** [comment]
I see, thank you again!
