### ISSUE TITLE
developer.download.nvidia.com not accessible, breaking installation

### ISSUE THREAD

**Issue by PerryXDeng** [NVIDIA/DALI#1218]
developer.download.nvidia.com returns status 404, making it impossible to install from https://developer.download.nvidia.com/compute/redist/cuda/10.0

Steps to reproduce: `pip3 install --extra-index-url https://developer.download.nvidia.com/compute/redist/cuda/10.0 nvidia-dali`

Note that I have no trouble resolving the developer.nvidia.com domain.

**Comment by awolant** [comment]
Hi, thanks for the question.
Exact link you provided worked for me on my machine. It's probably something with your environment. I suspect it might be [pip `--extra-index-url` issue](https://github.com/pypa/pip/issues/6428). Could you please show the output of the command?

**Comment by awolant** [comment]
As I suspected. Note the last line of this error:
> requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/nvidia-dali/

Your `pip` is looking for DALI on` pypi.org` not on `developer.download.nvidia.com` so the error occurs.
I stumbled upon this particular thing myself. Upgrading `pip` solved it for me.

**Comment by PerryXDeng** [comment]
> As I suspected. Note the last line of this error:
> 
> > requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/nvidia-dali/
> 
> Your `pip` is looking for DALI on` pypi.org` not on `developer.download.nvidia.com` so the error occurs.
> I stumbled upon this particular thing myself. Upgrading `pip` solved it for me.

Thanks that fixed the issue!
