### ISSUE TITLE
CUDA 10.1 Build

### ISSUE THREAD

**Issue by yaysummeriscoming** [NVIDIA/DALI#1225]
Is it possible to get prebuilt binaries for CUDA 10.1, in addition to 9 & 10?

**Comment by awolant** [comment]
Hi, thanks for the question.
For now, we do not plan to provide prebuild binaries for CUDA versions other than 9 and 10.
You should be able to build it yourself, if you want. Bare metal build from source is known to work with CUDA 10.1.
Our docker build is set up for 9 or 10, but it should be possible to modify/extend it to other CUDA versions. Our main reason for not doing that is maintenance/testing cost.

**Comment by yaysummeriscoming** [comment]
Ok thanks for your prompt reply.   I tested that prebuilt DALI for CUDA 10 works with my pytorch CUDA 10.1 install.  I'm assuming that building myself will improve performance, so when I get some free time I'll give that a go.
