### ISSUE TITLE
docs/examples/mxnet/demo doesn't use DALI

### ISSUE THREAD

**Issue by xcls1117** [NVIDIA/DALI#1228]
for mxnet demo in doc/examples/mxnet/demo, why I couldn't see DALI in data.py?
anyone can tell me if this demo use DALI or not?

**Comment by awolant** [comment]
Hi, thanks for the question.
For how to run this demo code with DALI you can look into our [MXNet ResNet example](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/mxnet/mxnet-resnet50.html).
If you are looking for more complete, ready to run example with DALI and MXNet look into [NVIDIA Deep Learning Examples](https://github.com/NVIDIA/DeepLearningExamples/tree/master/MxNet/Classification/RN50v1.5).

**Comment by xcls1117** [comment]
@awolant Thanks for your relpy. The second example really helps me a lot. 
Hope to see more MXNET examples,

**Comment by awolant** [comment]
Happy to help. Another thing you can look into is our [Gluon example](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/mxnet/gluon.html). I know that other examples are on the roadmap and will be coming in the future.
I'm closing this issue for now. If you have more questions or comments please do not hesitate to reopen or post a new one.
