### ISSUE TITLE
QUESTION:How to add noise in an image?How to blur an image?How to do log transformation or gamma transformation in an image?

### ISSUE THREAD

**Issue by ZJU-lishuang** [NVIDIA/DALI#1232]
Is there a easy way to achieve these operators,such as noise,blur or transform an image?

I see using PythonFunction ,making custom operator in C++ or doing it in DALIGenericIterator where outputs have been transformed as tensor are ok.

But I think it's a compromise.

So I want to know if there is an easy way to solve it.

**Comment by awolant** [comment]
Hi @ZJU-lishuang thanks for another question.
For now there is no easy way of doing that with DALI. We have arithmetic operations on our roadmap that will address some of those shortcomings in the following releases.
As you pointed out, for now the way to go would be to implement custom C++ ops.

**Comment by ZJU-lishuang** [comment]
Thank you！

**Comment by JanuszL** [comment]
@ZJU-lishuang  - some update. Now you can use [`NormalDistribution`](https://docs.nvidia.com/deeplearning/sdk/dali-master-branch-user-guide/docs/supported_ops.html#nvidia.dali.ops.NormalDistribution) operator to generate noise and use the [arithmetic operators`](https://docs.nvidia.com/deeplearning/sdk/dali-master-branch-user-guide/docs/supported_ops.html#arithmetic-expressions) to add it to your tensors.

**Comment by JanuszL** [comment]
Hi,
[Math operations](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/math.html) have been extended and supports `log` function, [the `gaussian_blur` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.gaussian_blur) is supported as well.
To add a noise you can use [random generators](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#module-nvidia.dali.fn.random) and just add their output to the image.
To apply fully custom gamma correction you can use [the `lookup_table` oeprator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.lookup_table).
