### ISSUE TITLE
CUDA driver api error "resource not mapped" using VideoReader

### ISSUE THREAD

**Issue by mikkeldenker** [NVIDIA/DALI#1235]
Hello!
I am trying to run the simple video pipeline located [here](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/video/video_reader_simple_example.html#Setting-up
)

However, when I run the code I get the following error message:
`terminate called after throwing an instance of 'std::runtime_error'
  what():  [/opt/anaconda/conda-bld/dali_1559892361674/work/dali/util/cuda_utils.h:80] CUDA driver api error "resource not mapped"`

The code is running on a ppc64le architecture in the PowerAI=1.6.1 docker container running ubuntu 18.04, and nvidia-smi is able to see the GPU. DALI is installed through conda.

I have also verified that the video files aren't corrupt, as I am able to load the frames into memory using OpenCV.

Any help would be very much appreciated!

Stacktrace:
`[frame 0]: /opt/anaconda3/lib/python3.6/site-packages/nvidia/dali/../../../../libdali.so(+0x95b14) [0x7fff252e5b14]
[frame 1]: /opt/anaconda3/lib/python3.6/site-packages/nvidia/dali/../../../../libdali.so(+0x17a9b4) [0x7fff253ca9b4]
[frame 2]: /opt/anaconda3/lib/python3.6/site-packages/nvidia/dali/../../../../libdali.so(+0x17bf0c) [0x7fff253cbf0c]
[frame 3]: /opt/anaconda3/lib/python3.6/site-packages/nvidia/dali/../../../../libdali.so(+0x180424) [0x7fff253d0424]
[frame 4]: /opt/anaconda3/lib/python3.6/site-packages/nvidia/dali/../../../../libdali.so(+0x16c75c) [0x7fff253bc75c]
[frame 5]: /opt/anaconda3/lib/python3.6/site-packages/nvidia/dali/../../../../libdali.so(+0x16d1b4) [0x7fff253bd1b4]
[frame 6]: /opt/anaconda3/lib/python3.6/site-packages/nvidia/dali/../../../../libdali.so(+0x1a0a20) [0x7fff253f0a20]
[frame 7]: /opt/anaconda3/lib/python3.6/site-packages/nvidia/dali/../../../../libdali.so(+0x1a240c) [0x7fff253f240c]
[frame 8]: /opt/anaconda3/lib/python3.6/site-packages/nvidia/dali/../../../../libdali.so(std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (dali::DataReader<dali::GPUBackend, dali::SequenceWrapper, dali::SequenceWrapper>::*)(
), dali::DataReader<dali::GPUBackend, dali::SequenceWrapper, dali::SequenceWrapper>*> > >::_M_run()+0x4c) [0x7fff253e510c]
[frame 9]: /opt/anaconda3/lib/libstdc++.so.6(+0xe1538) [0x7fff862e1538]
[frame 10]: /lib/powerpc64le-linux-gnu/libpthread.so.0(+0x885c) [0x7fff88e3885c]
[frame 11]: /lib/powerpc64le-linux-gnu/libc.so.6(clone+0x98) [0x7fff88d59028]`

**Comment by awolant** [comment]
Hi, thanks for the question.
Can you run other parts of DALI without issues? If so, this would isolate the problem to the video support.
For video processing DALI uses NVDEC, so I guess the next step would be to check it is working properly in your setup. 
Do you build DALI yourself from source?

**Comment by mikkeldenker** [comment]
Hi again,
I have successfully gotten an image pipeline to work using the nvJPEGDecoder, so I suspect the error has to do with NVDEC. I'll try and see if ffmpeg also has trouble using it.

I have installed DALI on my system using conda as documented [here](https://www.ibm.com/support/knowledgecenter/en/SS5SF7_1.6.1/navigation/wmlce_getstarted_DALI.html), so I haven't built it from source.

Thanks for the help and the quick reply!

**Comment by JanuszL** [comment]
Hi @mikkeldenker,

Can you check if the latest GPU driver and DALI release resolve the issue?

**Comment by mikkeldenker** [comment]
Hey @JanuszL 

Thanks for looking into this. Unfortunately I don't have access to the system anymore so I am unable to check if the issue is resolved. Hopefully someone else can verify the solution.

**Comment by JanuszL** [comment]
I will close it. If you face this again please reopen.
