### ISSUE TITLE
Question about how Loader works

### ISSUE THREAD

**Issue by FlyClover** [NVIDIA/DALI#1238]
We found the sample mechanism has changed recently in 0.13.0. Just want to make sure we understand how the loader works and it's working as designed. Suppose we have a indexed dataset of size 1000, number of shards is 1, and the initial_buffer_fill is also set to 1000. At the beginning of first epoch, the initial_buffer_fill will be filled with all the data. shards_ will contain one tuple (0, 1000). Then each ReadOne will randomly remove (suppose shuffle is true) one element from the initial_buffer_fill and inserts a new element from the dataset. The shards_ will contain two tuples where the first one indicates the current valid index and the second one indicates the next set of index. When one epoch finishes, the first tuple will be removed from shards_ and second tuple which is (1000, 2000) will serve as the index for reading from the initial_buffer_fill. 

Is this understanding correct? @JanuszL

**Comment by FlyClover** [comment]
Also it seems that stick_to_shard in loader.h is not set for TFRecordReader. Does it mean it's false by default? If so, then it means if I multiple GPUs, then all of them will start from the same index (https://github.com/NVIDIA/DALI/blob/master/dali/pipeline/operators/reader/loader/indexed_file_loader.h#L138)?

**Comment by mzient** [comment]
Hello,

Answering your second question:
AFAIK `stick_to_shard_` is false by default for all loaders - and, if set to True, affects TFRecordReader via IndexedFileLoader
This option was added for multi-node, not multi GPU - it was designed to increase data locality and help keep the data in file system cache when running on multiple nodes.
If this option is set to *false*, then when the reader has exhausted its shard, it will pull in data from the next shard. If this option is set to *true*, then the reader will just loop through the shard (with shuffling, if specified).

**Comment by FlyClover** [comment]
Hi @mzient thanks for the clarification. I thought sharding is for multi-gpu due to this notebook (https://github.com/NVIDIA/DALI/blob/master/docs/examples/multigpu.ipynb). It may need some clarification.

**Comment by awolant** [comment]
@FlyClover Sharding is for any setup with multiple GPUs. The notebook is correct in that regard. What @mzient meant was that the benefit of using it for better data locality is on multi node, I think.
If you have one system with multiple GPUs the whole dataset must be accessible to this system anyway.

**Comment by JanuszL** [comment]
@FlyClover - I think your understanding is correct. It is based on [TensorFlow behavior](tensorflow/core/kernels/data/shuffle_dataset_op.cc). The idea is to mark where in the sample buffer samples from each epoch are located. To get the actual index from `shards_`, index modulo size of the sample buffer is taken - https://github.com/NVIDIA/DALI/blob/master/dali/pipeline/operators/reader/loader/loader.h#L160.
You can also take a look into dali/test/python/test_operator_reader_shuffling.py to test on your own if all samples are provided at each epoch.

**Comment by FlyClover** [comment]
If the initial_buffer_fill is set to a size which is smaller than the size of dataset, is it equivalent to say that the dataset will be divided into `len(dataset) // len(initial_buffer_fill)` chunks and data is only shuffled within each chunk?

We're asking this because our training is very sensitive to the shuffling orders. We are seeing a significant preprocessing speed boost when switching to DALI but the final performance drops a little bit if we don't maintain a buffer as big as the dataset. So is it possible to do a reshuffling of indexes (https://github.com/NVIDIA/DALI/blob/master/dali/pipeline/operators/reader/loader/indexed_file_loader.h#L132) at end of each epoch?

**Comment by JanuszL** [comment]
@FlyClover - 
> If the initial_buffer_fill is set to a size which is smaller than the size of the dataset, is it equivalent to say that the dataset will be divided into len(dataset) // len(initial_buffer_fill) chunks and data is only shuffled within each chunk?

Not really. The first sample is selected from `0 - initial_buffer_fill` dataset indexes, then one sample is read from the dataset and the next one is selected from `1 - initial_buffer_fill` dataset indexes.
Indeed it is not fully random, but in case of FileReader and COCOReader you can use `shuffle_after_epoch` to globally shuffle data at the begging of each epoch (then prefetch buffer is not used). In the case of TFRecord, RecordIO and LMDB random access is slow and global shuffling is not possible - the only way it to set `initial_buffer_fill` to the dataset size.
