### ISSUE TITLE
Use for audio?

### ISSUE THREAD

**Issue by PCerles** [NVIDIA/DALI#1256]
Hi, is there any path towards using TFRecords containing audio in DALI? My TFRecords contain WAV files as encoded strings. Tried to write a PythonFunction to parse them but it can't operate on strings, so not sure how to directly work on the audio. Thanks!

**Comment by awolant** [comment]
Hi, thanks for the question.
Our [`TFRecordReader`](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/dataloading_tfrecord.html#Data-loading:-TensorFlow-TFRecord) supports `string` feature.
It's hard for me to say if this is compatible with your exact file format. Can you provide a sample of it?

**Comment by PCerles** [comment]
Yeah of course. Here is the error I'm getting:
```
pipe.build()
  File "/usr/local/lib/python3.6/dist-packages/nvidia/dali/pipeline.py", line 450, in run
    return self.outputs()
  File "/usr/local/lib/python3.6/dist-packages/nvidia/dali/pipeline.py", line 360, in outputs
    return self._outputs()
  File "/usr/local/lib/python3.6/dist-packages/nvidia/dali/pipeline.py", line 437, in _outputs
    return self._pipe.Outputs()
RuntimeError: Critical error in pipeline: Error in thread 0: [/opt/dali/dali/pipeline/operators/reader/parser/tfrecord_parser.h:92] Tensors of strings are not supported.
```

And here is the code:
```
class TFRecordPipeline(Pipeline, AudioParser):
    def __init__(self, batch_size, num_threads, device_id, rep_converter, tfrecord, tfrecord_idx):
        super(TFRecordPipeline, self).__init__(batch_size=batch_size,
                                         num_threads=num_threads,
                                         device_id=device_id)
        self.input = ops.TFRecordReader(path = tfrecord,
                                        index_path = tfrecord_idx,
                                        features = {"transcript" : tfrec.VarLenFeature((), tfrec.string, ""),
                                         'filename': tfrec.VarLenFeature((), tfrec.string, ""),
                                         'audio': tfrec.VarLenFeature((), tfrec.string, "")})
        self.iter = 0

    def parse_audio(self):
        fake_flac = io.BytesIO()
        fake_flac.write(audio_file)
        fake_flac.seek(0)
        audio_proc = load_audio(fake_flac) # loads flac into numpy
        return audio_proc

    def define_graph(self):
        inputs = self.input()
        audio_file = inputs['audio']
        return audio_file
```
I could provide a tfrecord sample if that would help further but hoping there might be something obvious in the code itself. Thanks!

**Comment by awolant** [comment]
You can provide the sample dataset, but from the error message above I assume that it contains tensors of strings. This is currently not supported by both the `TFRecordReader` and rest of the DALI. 
I don't know if this works for your use case, but a workaround is to use tensor of `chars` as an alternative.

**Comment by JanuszL** [comment]
Hi,
You can read any data from TF record and pass it to the [AudioDecoder operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.ops.AudioDecoder). It should work as in [this example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/audio_processing/audio_decoder.html).
