### ISSUE TITLE
Integrate Pipeline with Keras?

### ISSUE THREAD

**Issue by ben0it8** [NVIDIA/DALI#1260]
I wanted to ask if someone found a nice way to integrate DALI's Pipeline with Keras.

Cheers,
Oliver

**Comment by awolant** [comment]
Hi, thanks for the question.
I'm not aware of such an effort. 
We have support for TensorFlow `tf.data.Dataset` API with DALI on our roadmap and as far as I know, it is possible to easily use `tf.data.Dataset` with Keras. This is still work in progress, though.

**Comment by ben0it8** [comment]
Thanks for you answer. I look forward for the tf.data.Dataset support.

**Comment by JanuszL** [comment]
Hi,

DALI does support tf.data.Dataset API, you can check [this example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/frameworks/tensorflow/tensorflow-dataset-multigpu.html).
