### ISSUE TITLE
support for pointcloud data

### ISSUE THREAD

**Issue by turboxin** [NVIDIA/DALI#1265]
hi, I wonder do you plan to support pointcloud data in the near future?  
As @szalpal mentioned in [https://github.com/NVIDIA/DALI/pull/240#discussion_r228418017](url) : "I can easily imagine, that in the nearest future we'd have some other types of data to handle, like audio data, point cloud data, etc. "

**Comment by awolant** [comment]
Hi, thanks for the question.
Do you have any particular format in mind?
For example, we have [`TFRecordReader`](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html?highlight=tfrecordreader#nvidia.dali.ops.TFRecordReader) capable of reading general tensors from TFRecord files.
Another thing is the operators that you want to use?

**Comment by JanuszL** [comment]
Hi @turboxin ,

You can check [this](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/math/geometric_transforms.html#) example and see if that is what you need.
You can also check [Kaolin project](https://github.com/NVIDIAGameWorks/kaolin), maybe it is what you are looking for.
