### ISSUE TITLE
How to extract Optical Flow by specific indexes from frame sequence？

### ISSUE THREAD

**Issue by ideaRunner** [NVIDIA/DALI#1275]
```
class OFPipeline(Pipeline):
    def __init__(self, batch_size, num_threads, device_id):
        super(OFPipeline, self).__init__(batch_size, num_threads, device_id, seed=16)

        self.input = ops.VideoReader(device="gpu", filenames=video_filename, sequence_length=sequence_length)
        self.of_op = ops.OpticalFlow(device="gpu", output_format=4)

    def define_graph(self):
        seq = self.input(name="Reader")
        of = self.of_op(seq.gpu())
        return of
```

As the extraction of optical flow is time consumed and gpu utilized, what should I do to save time and gpu utilization if I don't need to extract optical flow from all frames in one sequence? 
Is there any way that I can point the index of frames that should be used to extract flow？

For example:

```
    def define_graph(self):
        seq = self.input(name="Reader")
        sample_seq = self.sample_op(seq)
        of = self.of_op(sample_seq.gpu())
        return of
```

**Comment by awolant** [comment]
Hi, thanks for the question.
Unfortunately, right now something like this is not supported.

You could try to write this operator yourself as a [custom plugin to DALI](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/extend/create_a_custom_operator.html).

If you are willing to contribute we would be happy to help.

**Comment by JanuszL** [comment]
Hi,

You can now extract only frames relevant to you and create a smaller sequence from it:
```
new_sequence = fn.stack(*fn.element_extract(sequence, element_map=[0,  4,  8, 13, 17]))
```

**Comment by JanuszL** [comment]
Also you can use [the `element_extract` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.sequence_rearrange):
```
new_sequence = fn.sequence_rearrange(sequence, new_order=[0,  4,  8, 13, 17])
```
