### ISSUE TITLE
How to use CoinFlip as input of PythonFunction? 

### ISSUE THREAD

**Issue by kingder** [NVIDIA/DALI#1283]
I wan't to use the CoinFlip output as the input of PythonFunction, but it throws:
```
RuntimeError: [/opt/dali/dali/pipeline/pipeline.cc:263] Assert on "!it->second.is_support" failed: Argument input can only be used as regular input by support ops. (op: 'PythonFunctionImpl', input: 'CoinFlip_id_2_output_0')
```
Is it possible?

**Comment by awolant** [comment]
Hi, thanks for the question.
Unfortunately, right now `PythonFunction` does not support support op inputs.
We are in the middle of reworking support ops to regular CPU ops (e.x. #1259 ). Then this limitation will disappear.

**Comment by kingder** [comment]
Thanks for the reply, look forward for the reworking.

I have one more question, I want make a custom GPU operator, inside which will call two builtin operators, like below:
my_own_operator(ws):
  1. call builtin OP1.
  2. call builtin OP2.

I know I could use InstantiateOperator with a spec to call builtin OP, but how to pass input of my_OP to OP1, and output of OP1 to input of OP2, and finally the output of OP2 to my_OP's output?

Thanks!

**Comment by awolant** [comment]
For detailed discussion on this topic you can look into #410

**Comment by awolant** [comment]
You can also look into #1312 for how to workaround this issue.

**Comment by mzient** [comment]
@kingder I'm happy to announce that latest master (after #1423) removes the distinction between `support` operators and `cpu` operators. You can now use support operators as outputs, python operator inputs, etc - and you can pass regular CPU operator outputs to named inputs.
