### ISSUE TITLE
Failed to import nvidia_dali without tfrecord (source and redist)

### ISSUE THREAD

**Issue by ccoulombe** [NVIDIA/DALI#1286]
Hi,

When building `v0.12` from source **without** TFRecord or using the pre-built wheel, importing DALI with `python -c "import nvidia.dali"` fails as it tries to find TFRecord: 
```
Traceback (most recent call last):
  File "/home/coulombc/.dali/lib/python3.7/site-packages/nvidia/dali/tfrecord.py", line 16, in <module>
    from nvidia.dali.backend_impl.tfrecord import *
ModuleNotFoundError: No module named 'nvidia.dali.backend_impl.tfrecord'; 'nvidia.dali.backend_impl' is not a package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/coulombc/.dali/lib/python3.7/site-packages/nvidia/dali/__init__.py", line 17, in <module>
    from . import ops
  File "/home/coulombc/.dali/lib/python3.7/site-packages/nvidia/dali/ops.py", line 21, in <module>
    from nvidia.dali.types import _type_name_convert_to_string, _type_convert_value, DALIDataType
  File "/home/coulombc/.dali/lib/python3.7/site-packages/nvidia/dali/types.py", line 18, in <module>
    from nvidia.dali import tfrecord as tfrec
  File "/home/coulombc/.dali/lib/python3.7/site-packages/nvidia/dali/tfrecord.py", line 18, in <module>
    raise RuntimeError('DALI was not compiled with TFRecord support.'
RuntimeError: DALI was not compiled with TFRecord support. Use BUILD_PROTO3=ON CMake option to enable TFRecord support
```

By commenting this line : 
https://github.com/NVIDIA/DALI/blob/0cc25332a94af37626055f8918f2ec1b5c891eee/dali/python/__init__.py.in#L20
and setting tfrecord to false with : https://github.com/NVIDIA/DALI/blob/0cc25332a94af37626055f8918f2ec1b5c891eee/dali/python/nvidia/dali/types.py#L21
```
from nvidia.dali.backend_impl.types import *    
_tfrecord_support = False
```

I can successfully import DALI.

**Comment by awolant** [comment]
Hi, thanks for reporting this issue.
We will look into this.
Could you provide your build commands for easier reproduction?

**Comment by ccoulombe** [comment]
In a virtual env. install DALI with
```
pip install --extra-index-url https://developer.download.nvidia.com/compute/redist/cuda/10.0 nvidia-dali
```

Or, when building from source, when a virtual env. is activated:
```
git clone --recursive https://github.com/NVIDIA/DALI --branch v0.13.0 dali
cd dali && mkdir build && cd build 
cmake .. && make -j 16 && cd dali/python
python setup.py install
```
then run `python -c "import nvidia.dali"`.

**Note** that TFRecord was not built since the CMake module failed to locate `protobuf/3.7.1`, I had to hint it to CMake with `-DCMAKE_PREFIX_PATH -DProtobuf_INCLUDE_DIRS -DProtobuf_LIBRARIES -DProtobuf_LIBRARY `.   I now build TFRecord.

**Note2** that I also had to fix the RUNPATH of the shared objects otherwise `libdali.so` is not found

**Comment by JanuszL** [comment]
The recommended way is to use [dockerized build environment](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/compilation.html).

**Comment by ccoulombe** [comment]
Good instructions and building from source should work in the first place, then alternatives like conda or docker could be recommended. Especially for HPC

**Comment by JanuszL** [comment]
> Good instructions and building from source should work in the first place, then alternatives like conda or docker could be recommended. Especially for HPC

Conda is a whole runtime environment. What I mean by the dockerized build environment, is to use docker to build a portable python wheel you can install in your host system. You don't need to use docker to run it.
