### ISSUE TITLE
I could not find the cutout operation

### ISSUE THREAD

**Issue by leoozy** [NVIDIA/DALI#1292]
Dears:
    Cutout operation is a very popular data augment method used in computer vision. Almost all the nas papers apply this method. But I could not find it in the doc. Could you help me ?

**Comment by awolant** [comment]
Hi,
thanks for the question. Unfortunately there is no native support for cutout in DALI right now, but it is definitely a desirable feature.
If you are willing to contribute we would be happy to help.

As a workaround you can try to write it as a [custom operator](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/extend/create_a_custom_operator.html#Create-a-custom-operator).

**Comment by JanuszL** [comment]
This should be possible with erase operator. Please check [this guide](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/erase.html).
