### ISSUE TITLE
freezing the graph KeyError Dali

### ISSUE THREAD

**Issue by adrianstaniec** [NVIDIA/DALI#1297]
I am trying to run [freeze_graph script](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/freeze_graph.py) on the model trained with DALI.
And I am getting this error:

```
Traceback (most recent call last):
  File "utils/freeze_graph.py", line 100, in <module>
    frozen_graph = freeze_graph(args.model_dir, args.output_node_names)
  File "utils/freeze_graph.py", line 57, in freeze_graph
    input_checkpoint + '.meta', clear_devices=clear_devices)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1449, in import_meta_graph
    **kwargs)[0]
  File "/usr/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1473, in _import_meta_graph_with_return_elements
    **kwargs))
  File "/usr/lib/python3.6/site-packages/tensorflow/python/framework/meta_graph.py", line 857, in import_scoped_meta_graph_with_return_elements
    return_elements=return_elements)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 400, in import_graph_def
    _RemoveDefaultAttrs(op_dict, producer_op_list, graph_def)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 160, in _RemoveDefaultAttrs
    op_def = op_dict[node.op]
KeyError: 'Dali'
```

**Comment by awolant** [comment]
Hi, thanks for reporting this issue.
Let me check it and get back to you. Could you provide some minimal reproduction to speed things up?

**Comment by anishagartia** [comment]
Hi, any resolution to this? I used the instruction [here](https://github.com/NVIDIA/DALI/issues/1078) to install Dal, which went through successfully. Yet I get the KeyError: 'Dali' error.

**Comment by JanuszL** [comment]
As @awolant said - if you provide some minimal repro it would speed things up.

**Comment by anishagartia** [comment]
[Dali_node.txt](https://github.com/NVIDIA/DALI/files/3811629/Dali_node.txt)

I can share the Dali node in the .pbtxt file.

**Comment by JanuszL** [comment]
I mean full end2end script to run to reproduce this error. How you run `freeze_graph script`, how DALI is plugged in and how to reproduce the exact error you get. The simple repro the better. You can refer to https://github.com/NVIDIA/DALI#reporting-problems-asking-questions.

**Comment by anishagartia** [comment]
Freeze graph wasn't working so I went back to Tensorboard. I see the same error here:

` Pip3 install https://developer.download.nvidia.com/compute/redist/cuda/10.0/nvidia-dali/nvidia_dali-0.15.0-947079-cp36-cp36m-manylinux1_x86_64.whl`
`wget https://developer.download.nvidia.com/compute/redist/cuda/10.0/nvidia-dali-tf-plugin/nvidia-dali-tf-plugin-0.15.0.tar.gz`
`tar-xvzf nvidia-dali-tf-plugin-0.15.0.tar.gz
`
Removed nvidia-dali from install_requires argument from setup call in setup.py.

`python3 setup.py`
`python3`
>>import tensorflow as tf
>> tf.train.import_meta_graph("./resnet50_mod/model.ckpt-14130.meta")
>>for n in tf.get_default_graph().as_graph_def().node:
         print(n)
>>with tf.Session() as sess:
      writer = tf.summary.FileWriter("./output/", sess.graph)
      writer.close()

**Comment by JanuszL** [comment]
Please reopen when you can share a repro.
