### ISSUE TITLE
question: how can I create multi-class segmentation mask as labels?

### ISSUE THREAD

**Issue by bamps53** [NVIDIA/DALI#1302]
My dataset has multi-class segmentation mask as run length encoding. How can I read this labels and encode/decode to mask?
That mean I want pipeline to return (images, masks). Could someone let me know how can I do that??

**Comment by awolant** [comment]
Hi, thanks for the question.
Could you provide more info about your use case? What is the structure and the format of the files?
For your masks you probably need custom reader, you can use [`ExternalSource`](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/external_input.html) for that purpose. Then, you can have two readers, one for masks and one for images.

**Comment by JanuszL** [comment]
Hi,

[The `coco` reader](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.readers.coco) supports run-length encoding. You can use it enabling `pixelwise_masks` option.
If it doesn't address your use case please reopen.
