### ISSUE TITLE
Doc typo

### ISSUE THREAD

**Issue by ShoufaChen** [NVIDIA/DALI#1311]
As mention in #1301 

The Docs about  [DALIClassificationIterator](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/plugins/pytorch_plugin_api.html) has a typo.

**Comment by awolant** [comment]
Hi, thanks for reporting this.
I will post a PR with the fix for it.

**Comment by awolant** [comment]
Fixed in #1314
