### ISSUE TITLE
How to enable LOG_LINE debug message ? 

### ISSUE THREAD

**Issue by xutianming** [NVIDIA/DALI#1313]
I was trying to add some debug message using `LOG_LINE` 
After compiling and building the wheel package, I reinstalled the wheel package and rerun my testing Python script. 
I didn't see any debug message from the stdout.

What is the recommended way of adding debug message ?

**Comment by xutianming** [comment]
Should I build the wheel with `CMAKE_BUILD_TYPE=DevDebug` ?

**Comment by xutianming** [comment]
```
#define LOG_LINE \
   if (1) \
   std::cout << __FILE__ << ":" << __LINE__ << ": "
```

We have to hard-code `if(0)` to `if(1)` for debugging.

**Comment by JanuszL** [comment]
Yes, we don't want it even in debug because it spews a lot of logs. But we can try to add CMake flag for that.

**Comment by JanuszL** [comment]
https://github.com/NVIDIA/DALI/pull/1319 should improve this
