### ISSUE TITLE
How to pass the data of dali on gpu directly to tensorflow through tf.placerholder()

### ISSUE THREAD

**Issue by wangguangyuan** [NVIDIA/DALI#135]
Is it possible to pass the data on the GPU output by dali directly to tensorflow via tensorflow's tf.placehoder(), avoiding the process of data from cpu->gpu->cpu->gpu.

**Comment by JanuszL** [comment]
Internally tracked DALI-208.

**Comment by wangguangyuan** [comment]
For the DALI ClassificationIterator, the data of dali on the gpu is directly passed to the pytorch directly through the pointer.
I plan to use only dali's FileReader to read images and nvJPEGDecoder to decode images. Then get the dali data through pipe.run and send it to tf.placeholder.
Then put the data Resize, Crop and other operations on the tensorflow to do.

**Comment by wangguangyuan** [comment]
I am very grateful to open source for such a good software, I wish dali becomes more powerful.

**Comment by ptrendx** [comment]
This is unfortunately not easy. MXNet and pyTorch have APIs to get the pointer of a NDArray/Tensor respectively, and so we can just copy the contents of our Tensor to their respective implementations. TensorFlow (AFAIK) does not have such API and to produce a TF Tensor one needs to produce it via the TF op. That is why TF integration of DALI is different than MXNet and pyTorch integration, which is unfortunate.

@wangguangyuan Would it work for you if for TensorLists that do not hold tensors with the same shape we gave an option to return it as 2 tensors: a tensor being basically the concatenated tensorlist, and a second tensor holding just shapes? So let's say a list of 2 tensors, one with shape `(X1,Y1,3)` and the other `(X2,Y2,3)` would give you tensor of shape `(X1*Y1+X2*Y2, 3)` (or even 1D `(X1*Y1*3+X2*Y2*3)`) holding data and a tensor of shape (2, 3) holding shapes?

**Comment by wangguangyuan** [comment]
@ptrendx,  thanks very much.
https://github.com/NVIDIA/DALI/issues/112

For the target detection task, the image is scaled by the short edge. At this time, the bounding box [x1, y1, x2, y2] we marked should also be scaled in the same scale so that the bounding box can correspond to the scaled image. Dali has a good implementation？
I didn't find a good solution, so I plan to use only dali's FileReader to read images and nvJPEGDecoder to decode images. After using the DALI TensorFlow plugin to get the Ops of TensorFlow, I can use the functions in TensorFlow to simultaneously enhance the data and the bounding box. But I found a problem in the process of doing it. One of the shape parameters of DALIIterator() needs to set the image size, but the image size I input is not fixed, which causes me to not call DALIIterator() correctly, and I can't get the Ops of TensorFlow.


For other tasks of deep learning, such as target detection. We generally want to do data enhancements on images, such as Reszie, Crop, Scale, etc. At the same time we have to ensure that our bounding boxes[x,y,width, height] or [left, right, bottom, top] should also be changed accordingly. So, I tried a lot of methods and found that I encountered some problems.

Because I see that dali doesn't seem to support that data and tags  Resize and Scale synchronously. I plan to use only dali's FileReader to read images and nvJPEGDecoder to decode images. After using the DALI TensorFlow plugin to get the OpsorFlow Ops, I can use the functions in TensorFlow to resize and scale the image and bounding box at the same time.But in the process I found a problem,你When I am using nvidia.dali.plugin.tf.DALIIterator() method to get the Tensorflow Op, nvidia.dali.plugin.tf.DALIIterator() needs to pass in the shape parameter, but we only use dali to read the image and decode it, no Resize and Crop do not fix the output image size, so I can't pass in the shape.
So I plan not to use nvidia.dali.plugin.tf.DALIIterator() method to get the Tensorflow Op,
Instead, the data is obtained through pipe.build and pipe.run(), and then sent to tensorflow via tf.placehoder(). In order to achieve faster speed, avoiding the process of data from cpu->gpu->cpu->gpu.
I tried a lot of methods and couldn't find the solution of dali on the target detection and segmentation tasks.


I am very sorry, my English is not very good, generally through google translation, may not describe the problem clearly, if not described clearly, I hope to tell me, I am changing.
I think this is a very important question, I want to describe him clearly.

**Comment by wangguangyuan** [comment]
for target detection batch_size=1

**Comment by saikiranvadhi** [comment]
@JanuszL has this been implemented yet? Can you please let me know if there is a timeline in place for this feature?

**Comment by JanuszL** [comment]
Hi,

The first step we have on our roadmap is to enable external input for DALI TensorFlow plugin (we still need to determine how flexible it would be and what is the performance implication). Then we can try to enable GPU data. If it would be done thanks to tf.placerholder or some other mechanism is the open question.
If you have a good idea of how it may work, we would be more than happy to see RFC or even PR with the necessary changes.

**Comment by JanuszL** [comment]
https://github.com/VoVAllen/tf-dlpack could be a solution you are looking for. We plan to provide the ability to output a DLPacked data from DALI.

**Comment by klecki** [comment]
Hi,
DALI has now support for tf.data.Dataset APIs with CPU and GPU placement supported, maybe this can help in this scenario? We also have operators that can apply corresponding augmentation to bounding boxes directly in DALI, so it may be no longer needed to process them further in TensorFlow.

tf.placeholder is not compatible with the eager mode (and the direction that TensorFlow is taking) and we do not have plans to support it.

**Comment by eedalong** [comment]
Great！So this is done by DLPacked data or use an external TF Allocator

**Comment by JanuszL** [comment]
Hi @eedalong,

I'm not sure if I understand your question. You are asking how DALI is integrated with TensorFlow or how an external input from TensorFlow can be feed to DALI?

**Comment by eedalong** [comment]
My Bad, I'am asking how DALI is integrated with TF. I am trying to integrate DALI with [mindspore](https://github.com/mindspore-ai) and my rough idea is that : DALI -> DLPack Tensor -> MindSpore Tensor. But I wander how you guys did to integrate DALI with TF.

**Comment by eedalong** [comment]
> My Bad, I'am asking how DALI is integrated with TF. I am trying to integrate DALI with [mindspore](https://github.com/mindspore-ai) and my rough idea is that : DALI -> DLPack Tensor -> MindSpore Tensor. But I wander how you guys did to integrate DALI with TF.

@JanuszL

**Comment by JanuszL** [comment]
We created a custom TF operator that wraps up DALI under the hood and used TF allocated memory we copy the DALI outputs to.
DALI itself doesn't support the DLPack interface as an output. However, we do support `__cuda_array_interface__` which you can leverage to create a DLPack Tensor. However, if you can create an empty Tensor in mindspopre and obtain its pointer you can do the same as we do with PyTorch for example. Please check [this file](https://github.com/NVIDIA/DALI/blob/main/dali/python/nvidia/dali/plugin/pytorch.py#L38) for a reference.

**Comment by JanuszL** [comment]
Please remember that DALI owns the memory, so you should not run the pipeline again as long as the memory is in use

**Comment by eedalong** [comment]
Oh, I see, appreciate that!
