### ISSUE TITLE
QUESTION: How to implement a custom sampler

### ISSUE THREAD

**Issue by shuten-douji** [NVIDIA/DALI#1356]
Thanks for your great work of DALI, it is really facinating and powerful. Still, I wish to ask that if it is possible to implement a samper that controls the sampling order in DALI, like the torch.utils.data.Sampler in Pytorch ： https://pytorch.org/docs/stable/data.html?highlight=sampler#torch.utils.data.Sampler. 

I need to sample the data in a manner that every minibatch contains n_class * n_per_class data, which samples from a selected "n_class" classes out of all classes, and each class contains "n_per_class" data. So I wish to know if it is possible to control the sample order of DALI pipeline. Thanks!

**Comment by awolant** [comment]
Hi, thanks for your interest in DALI.
Currently something like this is not supported out of the box. I have two ideas for a workaround.

1. You can use [`ExternalSource`](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/external_input.html) and read and decode your images in Python however you want.

2. You can use `file_list` parameter of [`FileReader`](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html#nvidia.dali.ops.FileReader). You can prepare the sample reading order for the entire training and `FileReader` will follow it. 

Let me know, how this works for you.

**Comment by shuten-douji** [comment]
Thanks for your advice, I will try as you suggested~

**Comment by WarBean** [comment]
@awolant Can I simply return a byte string in an ExternalInputIterator, so that the image decoding process can be done in DALI mixed mode?

**Comment by knsong** [comment]
@awolant How to implement a weighted sampler like [this](https://pytorch.org/docs/stable/data.html#torch.utils.data.WeightedRandomSampler) for pytorch?

**Comment by JanuszL** [comment]
@knsong - I believe the  [`ExternalSource`](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/external_input.html) is the best way to do so now.

**Comment by knsong** [comment]
> @knsong - I believe the [`ExternalSource`](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/external_input.html) is the best way to do so now.
Doesn't [ExternalSource](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/external_input.html) support input images of different sizes?
I will get such error when using ExternalSource reading images of different sizes:
```
/site-packages/nvidia/dali/pipeline.py", line 326, in feed_input
    inputs.append(Edge.TensorCPU(datum, layout))
RuntimeError: [/opt/dali/dali/pipeline/data/buffer.h:265] Assert on "!shares_data_" failed: Cannot reallocate Buffer if it is sharing data. Clear the status by `Reset()` first.
```

**Comment by JanuszL** [comment]
@knsong 

> Doesn't ExternalSource support input images of different sizes?
I will get such error when using ExternalSource reading images of different sizes:

Yes, this example shows that each image can have a different size.
What version of DALI do you use? I cannot match this error to code in the repository `RuntimeError: [/opt/dali/dali/pipeline/data/buffer.h:265] Assert on "!shares_data_" failed: Cannot reallocate Buffer if it is sharing data. Clear the status by `Reset()` first.` - it should appear in line [244](https://github.com/NVIDIA/DALI/blob/master/dali/pipeline/data/buffer.h#L244) not 265.
Can you provide some minimal reproduction using some dummy numpy array as a data source so we can debug this problem?

**Comment by knsong** [comment]
> @knsong
> 
> > Doesn't ExternalSource support input images of different sizes?
> > I will get such error when using ExternalSource reading images of different sizes:
> 
> Yes, this example shows that each image can have a different size.
> What version of DALI do you use? I cannot match this error to code in the repository `RuntimeError: [/opt/dali/dali/pipeline/data/buffer.h:265] Assert on "!shares_data_" failed: Cannot reallocate Buffer if it is sharing data. Clear the status by `Reset()` first.` - it should appear in line [244](https://github.com/NVIDIA/DALI/blob/master/dali/pipeline/data/buffer.h#L244) not 265.
> Can you provide some minimal reproduction using some dummy numpy array as a data source so we can debug this problem?

The DALI version I used is https://github.com/NVIDIA/DALI/tree/983b66d3b6a69389980c6593dee3e0997d90768c,
I roughly wrote the dataloader [here](https://gist.github.com/knsong/d1f443e5bbcfd07b8095271d33c6795e), which I think can describe the whole pipeline I used,  if there needs more information, I'd like to add more then.

**Comment by JanuszL** [comment]
With 0.17 and code you provided (with small bugfixes), data from DALI 'docs/examples/images`:
```
import math
import os
import nvidia.dali.ops as ops
import nvidia.dali.types as types
import nvidia.dali.tfrecord as tfrec
#from nvidia.dali.backend import oss
from nvidia.dali.pipeline import Pipeline
from nvidia.dali.plugin.pytorch import DALIGenericIterator, DALIClassificationIterator
from nvidia.dali.types import DALIDataType

class CommonPipeline(Pipeline):
    def __init__(self,
                 batch_size,
                 num_workers,
                 image_size=(256, 256),
                 crop_size=(224, 224),
                 image_mean=[0.485 * 255, 0.456 * 255, 0.406 * 255],
                 image_std=[0.229 * 255, 0.224 * 255, 0.225 * 255],
                 random_area=[0.08, 1.0],
                 random_aspect_ratio=[0.75, 1.333333],
                 train=True,
                 device_id=0,
                 shard_id=0,
                 seed=0,
                 decoder_device='mixed',
                 **kwargs):
        super(CommonPipeline, self).__init__(batch_size,
                                             num_workers,
                                             device_id,
                                             seed=seed + shard_id,
                                             **kwargs)
        self.train = train
        self.dali_device = 'gpu' if decoder_device == 'mixed' else 'cpu',
        self.decoder_device = decoder_device

        if train:
            device_memory_padding = 211025920 if decoder_device == 'mixed' else 0
            host_memory_padding = 140544512 if decoder_device == 'mixed' else 0
            self.decode = ops.ImageDecoderRandomCrop(
                device=decoder_device,
                output_type=types.RGB,
                device_memory_padding=device_memory_padding,
                host_memory_padding=host_memory_padding,
                random_area=random_area,
                random_aspect_ratio=random_aspect_ratio,
                num_attempts=100)
            self.coin = ops.CoinFlip(probability=0.5)
            self.resize = ops.Resize(
                                device='gpu' if decoder_device == 'mixed' else 'cpu',
                                resize_x=crop_size[1],
                                resize_y=crop_size[0],
                                interp_type=types.INTERP_TRIANGULAR)
        else:
            self.decode = ops.ImageDecoder(device=decoder_device,
                                           output_type=types.RGB)
            self.resize = ops.Resize(
                                device='gpu' if decoder_device == 'mixed' else 'cpu',
                                resize_x=image_size[1],
                                resize_y=image_size[0],
                                interp_type=types.INTERP_TRIANGULAR)

        assert isinstance(image_size, tuple) or isinstance(image_size, list)
        assert isinstance(crop_size, tuple) or isinstance(crop_size, list)
        assert len(image_size) == 2
        assert len(crop_size) == 2

        self.cnmp = ops.CropMirrorNormalize(
            device='gpu' if decoder_device == 'mixed' else 'cpu',
            output_dtype=types.FLOAT,
            output_layout=types.NCHW,
            crop_w=crop_size[1],
            crop_h=crop_size[0],
            image_type=types.RGB,
            mean=image_mean,
            std=image_std)
        self.augmentations = []

    def base_define_graph(self, inputs, targets):
        inputs = self.decode(inputs)
        for augment in self.augmentations:
            inputs = augment(inputs)
        inputs = self.resize(inputs)
        if self.dali_device == 'gpu':
            inputs = inputs.gpu()
            targets = targets.gpu()
        if self.train:
            inputs = self.cnmp(inputs, mirror=self.coin())
        else:
            inputs = self.cnmp(inputs)
        return inputs, targets

    def define_graph(self):
        raise NotImplementedError

    def add_augmentations(self, ops):
        """Add augmentation list
        Args:
            ops: list of DALI ops that will perform image augmentations on decoded image data.
        """
        self.augmentations + ops

class ExternalSourcePipeline(CommonPipeline):
    def __init__(self, sampler_iterator,
                 batch_size,
                 num_workers,
                 image_size=(256, 256),
                 crop_size=(224, 224),
                 image_mean=[0.485 * 255, 0.456 * 255, 0.406 * 255],
                 image_std=[0.229 * 255, 0.224 * 255, 0.225 * 255],
                 random_area=[0.08, 1.0],
                 random_aspect_ratio=[0.75, 1.333333],
                 train=True,
                 device_id=0,
                 shard_id=0,
                 seed=0,
                 decoder_device='mixed',
                 **kwargs):
        super(ExternalSourcePipeline, self).__init__(
                             batch_size, num_workers, image_size, crop_size,
                             image_mean, image_std, random_area,
                             random_aspect_ratio, train, device_id, shard_id,
                             seed, decoder_device, **kwargs)
        self.sampler_iterator = sampler_iterator
        self.input = ops.ExternalSource()
        self.input_label = ops.ExternalSource()

    def define_graph(self):
        self.jpegs = self.input()
        self.labels = self.input_label()
        return self.base_define_graph(self.jpegs, self.labels)

    def iter_setup(self):
        (images, labels) = next(self.sampler_iterator)
        self.feed_input(self.jpegs, images)
        self.feed_input(self.labels, labels)

    def reset_sampler_iterator(self, sampler_iterator):
        self.sampler_iterator = sampler_iterator

class ClassificationIterator(DALIGenericIterator):
    def __init__(self,
                 sampler,
                 pipelines,
                 size,
                 fill_last_batch=True,
                 last_batch_padded=False):
        super(ClassificationIterator, self).__init__(pipelines, ["data", "label"],
                                                         size, auto_reset = False,
                                                         fill_last_batch = fill_last_batch,
                                                         dynamic_shape = False,
                                                         last_batch_padded = last_batch_padded)
        self.sampler = sampler
   
    def __len__(self):
        return ceil(self._size / self.batch_size)

    def reset(self, epoch):
        self.sampler.set_epoch(epoch)
        for p in self._pipes:
            p.reset_sampler_iterator(iter(self.sampler))
        super(ClassificationIterator, self).reset()

def make_dataloader(sampler, pipeline, num_shards, train):
    pipeline.build()
    print('pipeline build successful')
    assert len(sampler) % num_shards == 0
    size = len(sampler) / num_shards
    print('pipeline size{}'.format(size))
    if train:
        return ClassificationIterator(sampler=sampler, pipelines=pipeline,
                                                   size=size,
                                                   fill_last_batch=True,
                                                   last_batch_padded=False)
    else:
        return ClassificationIterator(sampler=sampler, pipelines=pipeline,
                                                   size=size,
                                                   fill_last_batch=False,
                                                   last_batch_padded=True)
                                             
import os
import time
import random
import numpy as np
import copy 
from io import StringIO

class Sampler(object):
    def __init__(self, data_root, file_list, batch_size, delimiter=','):
        self.data_root = data_root 
        self.batch_size = batch_size
        lines = open(file_list).readlines()
        self.samples = [line.strip().split(delimiter) for line in lines if line is not '']

    def __iter__(self):
        batch = []
        labels = []
        for idx, sample in enumerate(self.samples):
            jpeg_filename, label = sample[0].split()
            f = open(self.data_root + jpeg_filename)
            batch.append(np.frombuffer(f.read(), dtype = np.uint8))
            labels.append(np.array([label], dtype = np.int32))
            if len(batch) == self.batch_size:
                yield (batch, labels)
                batch = []
                labels = []
        if len(batch) > 0:
            base_len = len(batch)
            for i in range(self.batch_size - base_len):
                img_obj = batch[i % base_len].copy()
                label_obj = labels[i % base_len].copy()
                batch.append(img_obj)
                labels.append(label_obj)
            yield (batch, labels)

    def __len__(self):
        return len(self.samples)
"""
file_list.txt:
  0.jpg 0\n
  1.jpg 1\n
  ...
Note the 'xxx.jpg's have different sizes.
"""
sampler = Sampler(data_root="images/", file_list="images/file_list.txt", batch_size=4, delimiter=',')  
pipeline = ExternalSourcePipeline(sampler_iterator=iter(sampler),
                                   batch_size=4,
                                   num_workers=2,
                                   image_size=(256, 256),
                                   crop_size=(224, 224),
                                   image_mean=[0.485 * 255, 0.456 * 255, 0.406 * 255],
                                   image_std=[0.229 * 255, 0.224 * 255, 0.225 * 255],
                                   random_area=[0.25, 1.0],
                                   random_aspect_ratio=[0.75, 1.333333],
                                   train=True,
                                   device_id=0,
                                   shard_id=1,
                                   decoder_device='mixed',
                                   prefetch_queue_depth=2,
                                   )
dataloader = make_dataloader(sampler, pipeline, 1, True)
for data in dataloader:
  image_data, label = data[0]["data"], data[0]["label"]
  print("ok")
```
It works fine (at least I don't see any crash). If it still doesn't in your case please provide something that requires only to issue `python run_repro.py` to be sure we are on the same page (as a source of test data you can use the content of 'docs/examples/images` or https://github.com/NVIDIA/DALI_extra

**Comment by knsong** [comment]
> With 0.17 and code you provided (with small bugfixes), data from DALI 'docs/examples/images`:
> 
> ```
> import math
> import os
> import nvidia.dali.ops as ops
> import nvidia.dali.types as types
> import nvidia.dali.tfrecord as tfrec
> #from nvidia.dali.backend import oss
> from nvidia.dali.pipeline import Pipeline
> from nvidia.dali.plugin.pytorch import DALIGenericIterator, DALIClassificationIterator
> from nvidia.dali.types import DALIDataType
> 
> class CommonPipeline(Pipeline):
>     def __init__(self,
>                  batch_size,
>                  num_workers,
>                  image_size=(256, 256),
>                  crop_size=(224, 224),
>                  image_mean=[0.485 * 255, 0.456 * 255, 0.406 * 255],
>                  image_std=[0.229 * 255, 0.224 * 255, 0.225 * 255],
>                  random_area=[0.08, 1.0],
>                  random_aspect_ratio=[0.75, 1.333333],
>                  train=True,
>                  device_id=0,
>                  shard_id=0,
>                  seed=0,
>                  decoder_device='mixed',
>                  **kwargs):
>         super(CommonPipeline, self).__init__(batch_size,
>                                              num_workers,
>                                              device_id,
>                                              seed=seed + shard_id,
>                                              **kwargs)
>         self.train = train
>         self.dali_device = 'gpu' if decoder_device == 'mixed' else 'cpu',
>         self.decoder_device = decoder_device
> 
>         if train:
>             device_memory_padding = 211025920 if decoder_device == 'mixed' else 0
>             host_memory_padding = 140544512 if decoder_device == 'mixed' else 0
>             self.decode = ops.ImageDecoderRandomCrop(
>                 device=decoder_device,
>                 output_type=types.RGB,
>                 device_memory_padding=device_memory_padding,
>                 host_memory_padding=host_memory_padding,
>                 random_area=random_area,
>                 random_aspect_ratio=random_aspect_ratio,
>                 num_attempts=100)
>             self.coin = ops.CoinFlip(probability=0.5)
>             self.resize = ops.Resize(
>                                 device='gpu' if decoder_device == 'mixed' else 'cpu',
>                                 resize_x=crop_size[1],
>                                 resize_y=crop_size[0],
>                                 interp_type=types.INTERP_TRIANGULAR)
>         else:
>             self.decode = ops.ImageDecoder(device=decoder_device,
>                                            output_type=types.RGB)
>             self.resize = ops.Resize(
>                                 device='gpu' if decoder_device == 'mixed' else 'cpu',
>                                 resize_x=image_size[1],
>                                 resize_y=image_size[0],
>                                 interp_type=types.INTERP_TRIANGULAR)
> 
>         assert isinstance(image_size, tuple) or isinstance(image_size, list)
>         assert isinstance(crop_size, tuple) or isinstance(crop_size, list)
>         assert len(image_size) == 2
>         assert len(crop_size) == 2
> 
>         self.cnmp = ops.CropMirrorNormalize(
>             device='gpu' if decoder_device == 'mixed' else 'cpu',
>             output_dtype=types.FLOAT,
>             output_layout=types.NCHW,
>             crop_w=crop_size[1],
>             crop_h=crop_size[0],
>             image_type=types.RGB,
>             mean=image_mean,
>             std=image_std)
>         self.augmentations = []
> 
>     def base_define_graph(self, inputs, targets):
>         inputs = self.decode(inputs)
>         for augment in self.augmentations:
>             inputs = augment(inputs)
>         inputs = self.resize(inputs)
>         if self.dali_device == 'gpu':
>             inputs = inputs.gpu()
>             targets = targets.gpu()
>         if self.train:
>             inputs = self.cnmp(inputs, mirror=self.coin())
>         else:
>             inputs = self.cnmp(inputs)
>         return inputs, targets
> 
>     def define_graph(self):
>         raise NotImplementedError
> 
>     def add_augmentations(self, ops):
>         """Add augmentation list
>         Args:
>             ops: list of DALI ops that will perform image augmentations on decoded image data.
>         """
>         self.augmentations + ops
> 
> class ExternalSourcePipeline(CommonPipeline):
>     def __init__(self, sampler_iterator,
>                  batch_size,
>                  num_workers,
>                  image_size=(256, 256),
>                  crop_size=(224, 224),
>                  image_mean=[0.485 * 255, 0.456 * 255, 0.406 * 255],
>                  image_std=[0.229 * 255, 0.224 * 255, 0.225 * 255],
>                  random_area=[0.08, 1.0],
>                  random_aspect_ratio=[0.75, 1.333333],
>                  train=True,
>                  device_id=0,
>                  shard_id=0,
>                  seed=0,
>                  decoder_device='mixed',
>                  **kwargs):
>         super(ExternalSourcePipeline, self).__init__(
>                              batch_size, num_workers, image_size, crop_size,
>                              image_mean, image_std, random_area,
>                              random_aspect_ratio, train, device_id, shard_id,
>                              seed, decoder_device, **kwargs)
>         self.sampler_iterator = sampler_iterator
>         self.input = ops.ExternalSource()
>         self.input_label = ops.ExternalSource()
> 
>     def define_graph(self):
>         self.jpegs = self.input()
>         self.labels = self.input_label()
>         return self.base_define_graph(self.jpegs, self.labels)
> 
>     def iter_setup(self):
>         (images, labels) = next(self.sampler_iterator)
>         self.feed_input(self.jpegs, images)
>         self.feed_input(self.labels, labels)
> 
>     def reset_sampler_iterator(self, sampler_iterator):
>         self.sampler_iterator = sampler_iterator
> 
> class ClassificationIterator(DALIGenericIterator):
>     def __init__(self,
>                  sampler,
>                  pipelines,
>                  size,
>                  fill_last_batch=True,
>                  last_batch_padded=False):
>         super(ClassificationIterator, self).__init__(pipelines, ["data", "label"],
>                                                          size, auto_reset = False,
>                                                          fill_last_batch = fill_last_batch,
>                                                          dynamic_shape = False,
>                                                          last_batch_padded = last_batch_padded)
>         self.sampler = sampler
>    
>     def __len__(self):
>         return ceil(self._size / self.batch_size)
> 
>     def reset(self, epoch):
>         self.sampler.set_epoch(epoch)
>         for p in self._pipes:
>             p.reset_sampler_iterator(iter(self.sampler))
>         super(ClassificationIterator, self).reset()
> 
> def make_dataloader(sampler, pipeline, num_shards, train):
>     pipeline.build()
>     print('pipeline build successful')
>     assert len(sampler) % num_shards == 0
>     size = len(sampler) / num_shards
>     print('pipeline size{}'.format(size))
>     if train:
>         return ClassificationIterator(sampler=sampler, pipelines=pipeline,
>                                                    size=size,
>                                                    fill_last_batch=True,
>                                                    last_batch_padded=False)
>     else:
>         return ClassificationIterator(sampler=sampler, pipelines=pipeline,
>                                                    size=size,
>                                                    fill_last_batch=False,
>                                                    last_batch_padded=True)
>                                              
> import os
> import time
> import random
> import numpy as np
> import copy 
> from io import StringIO
> 
> class Sampler(object):
>     def __init__(self, data_root, file_list, batch_size, delimiter=','):
>         self.data_root = data_root 
>         self.batch_size = batch_size
>         lines = open(file_list).readlines()
>         self.samples = [line.strip().split(delimiter) for line in lines if line is not '']
> 
>     def __iter__(self):
>         batch = []
>         labels = []
>         for idx, sample in enumerate(self.samples):
>             jpeg_filename, label = sample[0].split()
>             f = open(self.data_root + jpeg_filename)
>             batch.append(np.frombuffer(f.read(), dtype = np.uint8))
>             labels.append(np.array([label], dtype = np.int32))
>             if len(batch) == self.batch_size:
>                 yield (batch, labels)
>                 batch = []
>                 labels = []
>         if len(batch) > 0:
>             base_len = len(batch)
>             for i in range(self.batch_size - base_len):
>                 img_obj = batch[i % base_len].copy()
>                 label_obj = labels[i % base_len].copy()
>                 batch.append(img_obj)
>                 labels.append(label_obj)
>             yield (batch, labels)
> 
>     def __len__(self):
>         return len(self.samples)
> """
> file_list.txt:
>   0.jpg 0\n
>   1.jpg 1\n
>   ...
> Note the 'xxx.jpg's have different sizes.
> """
> sampler = Sampler(data_root="images/", file_list="images/file_list.txt", batch_size=4, delimiter=',')  
> pipeline = ExternalSourcePipeline(sampler_iterator=iter(sampler),
>                                    batch_size=4,
>                                    num_workers=2,
>                                    image_size=(256, 256),
>                                    crop_size=(224, 224),
>                                    image_mean=[0.485 * 255, 0.456 * 255, 0.406 * 255],
>                                    image_std=[0.229 * 255, 0.224 * 255, 0.225 * 255],
>                                    random_area=[0.25, 1.0],
>                                    random_aspect_ratio=[0.75, 1.333333],
>                                    train=True,
>                                    device_id=0,
>                                    shard_id=1,
>                                    decoder_device='mixed',
>                                    prefetch_queue_depth=2,
>                                    )
> dataloader = make_dataloader(sampler, pipeline, 1, True)
> for data in dataloader:
>   image_data, label = data[0]["data"], data[0]["label"]
>   print("ok")
> ```
> 
> It works fine (at least I don't see any crash). If it still doesn't in your case please provide something that requires only to issue `python run_repro.py` to be sure we are on the same page (as a source of test data you can use the content of 'docs/examples/images` or https://github.com/NVIDIA/DALI_extra

Yes, when running on 'docs/examples/images` I also never meet the crash, but I further find that when the image file **> 1MB**, it will definitely crash. You can run the code on this single image 
![bochum_000000_004032_leftImg8bit](https://user-images.githubusercontent.com/11374482/71722600-5cfe5300-2e64-11ea-85cc-0d2b757ed0eb.png) to reproduce that.

**Comment by JanuszL** [comment]
I have added the image you provided to the `docs/examples/images` it still works:
![obraz](https://user-images.githubusercontent.com/39967756/71753491-0e13e600-2e83-11ea-8d04-0752f36a54a9.png)
Please follow the [issue reporting guide](https://github.com/NVIDIA/DALI#reporting-problems-asking-questions) and provide a minimal, complete and verifiable repro. If it is just a zip with all files needed to reproduce the problem and the one script that can be just run it would be great.

**Comment by knsong** [comment]
> I have added the image you provided to the `docs/examples/images` it still works
> Please follow the [issue reporting guide](https://github.com/NVIDIA/DALI#reporting-problems-asking-questions) and provide a minimal, complete and verifiable repro. If it is just a zip with all files needed to reproduce the problem and the one script that can be just run it would be great.

Thank you. The problem has been solved.(not from DALI official code). But are there some best practices to improve the data loading performance?( When the file list is etremely large e.g. 2kw lines, the data loading performance will be much slower than pytorch weighted sampler.)

**Comment by JanuszL** [comment]
> The problem has been solved.(not from DALI official code)

So you mean that the problem was not related to DALI? Or you fixed the DALI code internally? If the second could you post a PR with changes so the rest of the community benefits your changes?

> But are there some best practices to improve the data loading performance?( When the file list is etremely large e.g. 2kw lines, the data loading performance will be much slower than pytorch weighted sampler.)

The ExternalSource approach is the most flexible but not the most performant.  To achieve the best performance you need to create a custom reader. I don't think if the current DALI approach to sampling could be easily extended and the best would be to provide some independent version with weights.
Now DALI uses internal buffer (the default size is 1024) which is filled with sequentially read samples from the data set (no matter if those are single files or samples form some container like TFRecord) and then the buffer is sampled randomly to form a batch. Samples are replaced with the new one from the reader. To support wights you need to allow sampling over the whole data set which is not supported in the current architecture. So the new approach needs to be developed on the side as an independent operator - it will work only for `FileReader` as random access to containerized data set is extremely slow and rather not recommended.

**Comment by knsong** [comment]
> So you mean that the problem was not related to DALI? Or you fixed the DALI code internally? If the second could you post a PR with changes so the rest of the community benefits your changes?

Yes, the problem was related to some internally changes for supporting reading tfrecord files stored in [OSS](https://github.com/aliyun/aliyun-oss-python-sdk). It would be great if the code is allowed by the company to be posted to the community, I think.

> The ExternalSource approach is the most flexible but not the most performant. To achieve the best performance you need to create a custom reader. I don't think if the current DALI approach to sampling could be easily extended and the best would be to provide some independent version with weights.
> Now DALI uses internal buffer (the default size is 1024) which is filled with sequentially read samples from the data set (no matter if those are single files or samples form some container like TFRecord) and then the buffer is sampled randomly to form a batch. Samples are replaced with the new one from the reader. To support wights you need to allow sampling over the whole data set which is not supported in the current architecture. So the new approach needs to be developed on the side as an independent operator - it will work only for `FileReader` as random access to containerized data set is extremely slow and rather not recommended.

Thanks for the information. By the way, will [nvidia.dali.ops.TFRecordReader](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html?highlight=tfrecordreader#nvidia.dali.ops.TFRecordReader) shuffle the tfrecord files(a.k.a the whole dataset) before it gets a shard(considering a distributed training)? and when an epoch finishes and the pipeline is reset, will the shuffling of the whole dataset be performed again(like behavior of [DistributedSampler](https://pytorch.org/docs/stable/_modules/torch/utils/data/distributed.html#DistributedSampler) in pytorch)? If doesn't, will DALI consider to support that?

**Comment by JanuszL** [comment]
> Yes, the problem was related to some internally changes for supporting reading tfrecord files stored in OSS. It would be great if the code is allowed by the company to be posted to the community, I think.

Can you ask for such permission? We already have a contribution from PaddlePaddle side.

> Thanks for the information. By the way, will nvidia.dali.ops.TFRecordReader shuffle the tfrecord files(a.k.a the whole dataset) before it gets a shard(considering a distributed training)? and when an epoch finishes and the pipeline is reset, will the shuffling of the whole dataset be performed again(like behavior of DistributedSampler in pytorch)? If doesn't, will DALI consider to support that?

Not really. What DALI theoretically can do is to shuffle file (if the TFRecord has more than one part) when sharding, but it due to performance reason I'm not much for shuffling the entries inside the TFRecord - because instead of the sequential access we would have a random one which is slow in such case. TFRecord is expected to be preshuffled, and then DALI relies on the shuffling inside the reading window. As far as I know, TensorFlow does the same.

**Comment by knsong** [comment]
> Can you ask for such permission? We already have a contribution from PaddlePaddle side.

I can ask for it and if it is ready, we will post it(which I'm really not sure though).

> Not really. What DALI theoretically can do is to shuffle file (if the TFRecord has more than one part) when sharding, but it due to performance reason I'm not much for shuffling the entries inside the TFRecord - because instead of the sequential access we would have a random one which is slow in such case. TFRecord is expected to be preshuffled, and then DALI relies on the shuffling inside the reading window. As far as I know, TensorFlow does the same.

With the shuffling the whole dataset I mean that shuffling the tfrecord files order before every epoch and then split them for each shard, which is a tradeoff between speed and shuffling effect.

**Comment by JanuszL** [comment]
> I can ask for it and if it is ready, we will post it(which I'm really not sure though).

I would very much appreciate it.

> With the shuffling the whole dataset I mean that shuffling the tfrecord files order(not the entries inside the tfrecord file) before every epoch and then split them for each shard, which is a tradeoff between speed and shuffling effect.

I would add it to our backlog.

**Comment by Crescentz** [comment]
> 感谢您为DALI所做的出色工作，它确实令人着迷且功能强大。不过，我还是想问一问，是否有可能在DALI中实现一个用于控制采样顺序的表示符，例如Pytorch中的torch.utils.data.Sampler：[https](https://pytorch.org/docs/stable/data.html?highlight=sampler#torch.utils.data.Sampler) ://pytorch.org/docs/stable/data.html [？highlight = sampler＃torch.utils.data.Sampler](https://pytorch.org/docs/stable/data.html?highlight=sampler#torch.utils.data.Sampler)。
> 
> 我需要以每个minibatch包含n_class * n_per_class数据的方式来采样数据，该数据是从所有类中选择的“ n_class”类中采样的，每个类都包含“ n_per_class”数据。因此，我想知道是否有可能控制DALI管道的采样顺序。谢谢！

Have you solved it? Can you share it

**Comment by Crescentz** [comment]
> Thanks for your great work of DALI, it is really facinating and powerful. Still, I wish to ask that if it is possible to implement a samper that controls the sampling order in DALI, like the torch.utils.data.Sampler in Pytorch ： https://pytorch.org/docs/stable/data.html?highlight=sampler#torch.utils.data.Sampler.
> 
> I need to sample the data in a manner that every minibatch contains n_class * n_per_class data, which samples from a selected "n_class" classes out of all classes, and each class contains "n_per_class" data. So I wish to know if it is possible to control the sample order of DALI pipeline. Thanks!

Excuse me, Have you solved it? Can you share your code
