### ISSUE TITLE
QUESTION:when I use ops.RandomBBoxCrop function,it will break.

### ISSUE THREAD

**Issue by ZJU-lishuang** [NVIDIA/DALI#1358]
The program will break when I use ops.RandomBBoxCrop function.
When I comment this function,it runs well.

![深度截图_选择区域_20191009162505](https://user-images.githubusercontent.com/26588466/66464349-640a0500-eab1-11e9-88df-e650543208bf.png)

Does this mean the annotation has something wrong?

**Comment by awolant** [comment]
Hi, thanks for another question.
I seems that one of your bounding boxes failed, because one of its coordinates is negative (note the error message).
This might indicate a problem with your input, as you pointer out.

**Comment by JanuszL** [comment]
@ZJU-lishuang - DALI currently validates if bboxes are inside the image and if not assertion is triggered.
Can you tell us if your dataset and network intentionally accept boxes that can cross the image boundary? We have discussed loose up this assertion but we would like to hear if this is what people want to have (in some cases it can easily find a mistake in the data set, but in the other, it may impose unnecessary constraints).

**Comment by ZJU-lishuang** [comment]
@JanuszL - In this case,I use COCOReader to read my data set.I`d like to find a mistake in the data set right now.My dataset unintentionally accept boxes that can cross the image boundary.

@awolant Thank you!
