### ISSUE TITLE
Error when adding tensors with and without gradiant （Pytorch）

### ISSUE THREAD

**Issue by gasvn** [NVIDIA/DALI#1370]
I use a commonly used trick to make the output binary while keeping the gradiant,
it's working on standard pytorch. 
```
y_hard = (y_soft>0.5).float()
ret = y_hard - y_soft.detach() + y_soft
```
But I get this error when using dali.
```
RuntimeError: Critical error in pipeline: std::bad_alloc
Current pipeline object is no longer valid.
```
How can I solve this problem?

**Comment by ZHUANGHP** [comment]
Last time I got this error is when the memory's running out. not sure about your case.

**Comment by JanuszL** [comment]
Hi @gasvn,

Could you provide a standalone repro code that would show this problem? Without it we cannot tell anything.

**Comment by JanuszL** [comment]
Please reopen when you can share a repro.
