### ISSUE TITLE
dataloading_tfrecord :failed: Got an unexpected argument "resize_shorter"

### ISSUE THREAD

**Issue by sosofun** [NVIDIA/DALI#139]
run dataloading_tfrecord example with multi GPU in docker ::

`
from nvidia.dali.pipeline import Pipeline
import nvidia.dali.ops as ops
import nvidia.dali.types as types
import nvidia.dali.tfrecord as tfrec
import numpy as np
import matplotlib.pyplot as plt

class TFRecordPipeline(Pipeline):
    def __init__(self, batch_size, num_threads, device_id):
        super(TFRecordPipeline, self).__init__(batch_size,
                                         num_threads,
                                         device_id)
        self.input = ops.TFRecordReader(path = tfrecord, 
                                        index_path = tfrecord_idx,
                                        features = {"image/encoded" : tfrec.FixedLenFeature((), tfrec.string, ""),
                                         'image/class/label':         tfrec.FixedLenFeature([1], tfrec.int64,  -1),
                                         'image/class/text':          tfrec.FixedLenFeature([ ], tfrec.string, ''),
                                         'image/object/bbox/xmin':    tfrec.VarLenFeature(tfrec.float32, 0.0),
                                         'image/object/bbox/ymin':    tfrec.VarLenFeature(tfrec.float32, 0.0),
                                         'image/object/bbox/xmax':    tfrec.VarLenFeature(tfrec.float32, 0.0),
                                         'image/object/bbox/ymax':    tfrec.VarLenFeature(tfrec.float32, 0.0)})
        self.decode = ops.nvJPEGDecoder(device = "mixed", output_type = types.RGB)
        self.resize = ops.Resize(device = "gpu", resize_shorter = 256.)
        self.cmnp = ops.CropMirrorNormalize(device = "gpu",
                                            output_dtype = types.FLOAT,
                                            crop = (224, 224),
                                            image_type = types.RGB,
                                            mean = [0., 0., 0.],
                                            std = [1., 1., 1.])
        self.uniform = ops.Uniform(range = (0.0, 1.0))
        self.iter = 0

    def define_graph(self):
        inputs = self.input()
        images = self.decode(inputs["image/encoded"])
        resized_images = self.resize(images)
        output = self.cmnp(resized_images, crop_pos_x = self.uniform(),
                           crop_pos_y = self.uniform())
        return (output, inputs["image/class/text"])

    def iter_setup(self):
        pass

batch_size = 16

pipe = TFRecordPipeline(batch_size=batch_size, num_threads=4, device_id = 0)
pipe.build()
`

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-18-241b87f6ccac> in <module>()
      2 
      3 pipe = TFRecordPipeline(batch_size=batch_size, num_threads=4, device_id = 0)
----> 4 pipe.build()

/usr/local/lib/python3.5/dist-packages/nvidia/dali/pipeline.py in build(self)
    122 
    123         if not self._prepared:
--> 124             self._prepare_graph()
    125 
    126         self._pipe.Build(self._names_and_devices)

/usr/local/lib/python3.5/dist-packages/nvidia/dali/pipeline.py in _prepare_graph(self)
     94             if source_op.id not in op_ids:
     95                 op_ids.add(source_op.id)
---> 96                 source_op.check_args()
     97                 ops.append(source_op)
     98             else:

/usr/local/lib/python3.5/dist-packages/nvidia/dali/ops.py in check_args(self)
     96 
     97     def check_args(self):
---> 98         self._op.schema.CheckArgs(self._spec)
     99 
    100     def generate_outputs(self):

RuntimeError: [/opt/dali/dali/pipeline/operators/op_schema.cc:51] Assert on "required_arguments.find(s) != required_arguments.end() || OptionalArgumentExists(s) || internal_arguments_.find(s) != internal_arguments_.end()" failed: Got an unexpected argument "resize_shorter"

**Comment by JanuszL** [comment]
Hi,
Looks like the same issue as #138.
Between DALI 0.1 and 0.2 there was a change in operators API. Examples you are running from master branch (new code) but DALI you have installed is probably 0.1.x. In such cases, I recommend using DALi build from sources corresponding to the same version as an example or use examples from version tagged with the number of the one you have installed.
Also we just released 0.2, please update DALI and try again. If that doesn't work please reopen.
