### ISSUE TITLE
how to return list of tensor for a single output?

### ISSUE THREAD

**Issue by kingder** [NVIDIA/DALI#1394]
I want to create a custom operator that return a list of tensors with different shape for a single output, is that possible, something like a TensorListCPU?

**Comment by mzient** [comment]
It's actually the default for DALI - tensors of the same shape are a special case. The only constraint is that all tensors must have the same number of dimensions.
You can look at an example here:
https://github.com/NVIDIA/DALI/blob/master/dali/test/plugins/dummy/dummy.h
`RunImpl(SampleWorkspace &ws)` in CPU operator produces just one sample in the batch - however, if you want to produce whole batch in one go, you can override
`RunImpl(HostWorkspace &ws)`. To access the whole batch, use `ws.InputRef` / `ws.OutputRef`. For GPU operators, these function return a reference to a `TensorList`, for CPU operators, while for CPU operators they return a reference to a `TensorVector`. The latter can be resized by providing a `TensorListShape<>` and individual tensors can be accessed using `operator[]`.

Also, if your data is of image/video kind, it's good to set layout for your output, according to the following key: H - height, W - width, D - depth, C - channels, for example:
`ws.OutputRef<CPUBackend>(0).SetLayout("HWC")`
This will make your tensors suitable for further processing by DALI builtin operators.

**Comment by kingder** [comment]
@mzient  Thanks for the detailed reply,  I know the for a batch, the shape can be different for each sample, so we get a TensorListCPU in Python side which consist of numpy arrays.
what I actually mean is for SampleWorkspace scenario (not HostWorkspace), can I return a TensorVector? and if I can, what do I expect in the Python side for a batch? TensorListCPU of TensorListCPU of numpy array?

**Comment by JanuszL** [comment]
Hi,
It is not possible to return a TensorVector as a sample. Can you provide some background what you want to achieve and what is your use case?

**Comment by JanuszL** [comment]
If you still need our assistance please reopen.
