### ISSUE TITLE
What is the way to Resize the output of VideoReader

### ISSUE THREAD

**Issue by kfhe00** [NVIDIA/DALI#1405]
Hi,
    recently I try to use VideoReader and Resize the output. And I got that:

> The layout "FHWC" does not match any of the allowed layouts for input 0. Valid layouts are:
> HWC
>     
   I want to know there is some way to resize the output of VideoReader. 
  Thanks.

**Comment by conraddd** [comment]
same issue here, is there any way to split batch of sequences into batch of frames so that all those non-sequence ops can be used in videos?

**Comment by JanuszL** [comment]
@conraddd - currently it is not possible. Also, DALI assumes that batch size is constant across the pipeline. Doing your way it would mean the transformation of a batch k size of n sequences into a batch k*x of single images.

**Comment by awolant** [comment]
Hi @kfhe00 ,
recently we introduced [`VideoReaderResize`](https://docs.nvidia.com/deeplearning/dali/master-user-guide/docs/supported_ops.html?highlight=videoreaderresize#nvidia.dali.ops.VideoReaderResize) op that can resize videos. It supports all `Resize` parameters for videos.
It is available in our [nightly build](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/installation.html#nightly-builds).

**Comment by JanuszL** [comment]
0.25 was released. The requested feature is implemented there.
