### ISSUE TITLE
Question about multi GPU without torch.utils.data.distributed

### ISSUE THREAD

**Issue by guvcolie** [NVIDIA/DALI#1409]
I am honoured to use DALI, great work! Now I encounter a problem, could you guide me?
Previously，I implement multi-GPU like this:
```
from torchvision import datasets
from torch.utils.data import DataLoader
trainset = datasets.ImageFolder(...)
trainloader = DataLoader(trainset, ...)
...
model = Model()
model = model.cuda()
model = torch.nn.DataParallel(model, device_ids=[x for x in range(len(gpu_ids))])
...
for index, data in enumerate(trainloader):
    image, label = data
    logits = model(image)
    # calc loss
```
As above, I just need to define **only one** dataloader for models in multi GPUs, Pytorch will separate the training data to each gpu automatically.
In DALI, however, according to the example https://github.com/NVIDIA/DALI/blob/master/docs/examples/pytorch/resnet50/main.py, I must use torch.utils.data.distributed and **define dataloader for each GPU**, that may be  incompatible with my current code framework.
So, if I still want to use torch.nn.DataParallel, how do I use DALI?  Thanks!

**Comment by awolant** [comment]
Hi, thanks a lot for your interest in DALI and your kind words.

As far as I know when you write code like in your example dataset produces one batch and then this batch is broken into as many peaces as you have GPUs in your parallel model and they are forwarded accordingly.

With DALI we want something different. The main idea is to move the data pipeline to the GPU. To keep the GPU load even between the devices you want to have pipeline on each of them and process only part of the batch. This is why we do it the way we do in our examples and run them with `python -m torch.distributed.launch`. DALI pipeline can handle sharding when proper parameters are passed. 


But from the API point of view, I don't think anything stops you from running one DALI pipeline, even on the CPU and use your old approach. You can have one pipeline without any sharding and use [`DALIClassificationIterator`](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/plugins/pytorch_plugin_api.html#nvidia.dali.plugin.pytorch.DALIClassificationIterator) as a replacement for `trainloader`. So it could look something like:


```python
model = Model()
model = model.cuda()
model = torch.nn.DataParallel(model, device_ids=[x for x in range(len(gpu_ids))])

pipeline = DaliPipeline(...)
pipeline.build()

trainloader = DALIClassificationIterator(
    pipeline,
    size=int(pipeline.epoch_size("Reader")))

...
for index, data in enumerate(trainloader):
    image = data[0]['data']
    label = data[0]['label'].squeeze().long()
    logits = model(image)
    # calc loss
```

This should work, but performance will be inferior.

**Comment by guvcolie** [comment]
Thank you for your timely feedback！
Actually，however， I want to use multi-GPUs with DALI and use my old approach to accelerate my training, can current DALI API meet my need ?
And, will the code that you write be faster than native dataloader of Pytorch?
Thanks!  : )

**Comment by awolant** [comment]
In theory you could run multiple DALI pipelines in one python process and distribute the results. I'm not sure how to integrate this with `torch.nn.DataParallel` though. It's safe to say that this would require some significant changes to your code as well.

It's hard to tell anything solid about the performance without knowing your exact use case, your GPU utilization and whether or not your model is IO bottlenecked. I think you can try to follow the approach from my code sample and see what happens. It should be relatively easy to do without any major changes to your code base.

**Comment by guvcolie** [comment]
Got it! Thank you very much! : ) 
I will try your code, and try to modify my code framework.

**Comment by JanuszL** [comment]
@guvcolie - one more thing to notice is that the distributed data parallel is the way we recommend as it allows you to train using more than one node as your data processing is distributed as well. DataParallel is limited to only one process per node which can cause a big overhead due to Python GIL, doesn't evely distribute work over all GPUs and the way how communication is performed it also inferior comparing to the distributed data parallel approach. You can check it [here ](https://discuss.pytorch.org/t/what-is-the-difference-between-dataparallel-and-distributeddataparallel/6108)or [here](https://datascience.stackexchange.com/questions/22191/what-is-the-difference-between-pytorchs-dataparallel-and-distributeddataparalle).

**Comment by guvcolie** [comment]
@JanuszL Thank you! I'll check it, and learn more about this!
