### ISSUE TITLE
easily install DALI 0.2 use pip?

### ISSUE THREAD

**Issue by sosofun** [NVIDIA/DALI#141]
i can't compiling DALI from source in the docker,   can i easily install DALI 0.2 by pip?  
because only DALI 0.1 install with the cmd:"pip install --extra-index-url https://developer.download.nvidia.com/compute/redist nvidia-dali". 

"
DALI and NGC
DALI is preinstalled in the NVIDIA GPU Cloud TensorFlow, PyTorch, and MXNet containers in versions 18.07 and later.
"
by the way , i pull the docker image TensorFlow 18.08 from  NVIDIA GPU Cloud , and find not preinstall in it .....

root@beaff37c96d6:/workspace# python
Python 3.5.2 (default, Nov 23 2017, 16:37:01)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from dali.pipeline import Pipeline
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'dali'

**Comment by JanuszL** [comment]
Hi,
It is strange that you gets 0.1 only, could you try to use direct link form https://github.com/NVIDIA/DALI/releases? We had some problems with caching in different regions but it should be solved.
Regarding availability 0.2 will be available in 18.09 container. In 18.08 DALI 0.1 is available, please try

    from nvidia.dali.pipeline import Pipeline

In the mean time we will recheck our server caches.

**Comment by JanuszL** [comment]
Tracked DALI-212

**Comment by sosofun** [comment]
@JanuszL ,thanks for reply the issue,   i am try to use   direct link form **https://github.com/NVIDIA/DALI/releases**  :
`root@bjlt-idc11:/code# pip install --extra-index-url https://developer.download.nvidia.com/compute/redist nvidia-dali==0.2.0
Looking in indexes: https://pypi.org/simple, https://developer.download.nvidia.com/compute/redist
Collecting nvidia-dali==0.2.0
  Could not find a version that satisfies the requirement nvidia-dali==0.2.0 (from versions: 0.1.0, 0.1.1, 0.1.2)
No matching distribution found for nvidia-dali==0.2.0
root@bjlt-idc11:/code#`

**Comment by sosofun** [comment]
have done!
use :
pip install https://developer.download.nvidia.com/compute/redist/nvidia-dali/nvidia_dali-0.2.0-34068-cp35-cp35m-manylinux1_x86_64.whl

**Comment by JanuszL** [comment]
0.3 is out and it seems to work fine. If issue reapers please reopen.
