### ISSUE TITLE
 CUDA error "invalid argument"

### ISSUE THREAD

**Issue by shdyn** [NVIDIA/DALI#1411]
hello. I met some problems in the docker. I want to use the DALI with glibc 2.12. Therefore, I use the DALI version 0.1.0. Other configurations include: cuda 9.0, centos 6.3, gcc 5.2.0, pytorch 1.3.0. Can you give me some suggestions how to solve this? Thanks.
 
dali_iter = DALIGenericIterator(pipes, ['data', 'label'], pipes[0].epoch_size("Reader"))
  File "/root/anaconda3/envs/pytorch1.3.0/lib/python3.6/site-packages/nvidia/dali/plugin/pytorch.py", line 72, in __init__
    self._first_batch = self.next()
  File "/root/anaconda3/envs/pytorch1.3.0/lib/python3.6/site-packages/nvidia/dali/plugin/pytorch.py", line 125, in __next__
    feed_ndarray(l_arr, pyt_labels[j])
  File "/root/anaconda3/envs/pytorch1.3.0/lib/python3.6/site-packages/nvidia/dali/plugin/pytorch.py", line 42, in feed_ndarray
    dali_tensor.copy_to_external(c_type_pointer)
RuntimeError: [/opt/dali/dali/plugin/copy.cu:40] CUDA error "invalid argument"

**Comment by awolant** [comment]
Hi, thanks for the question.
First question is why are you using DALI 0.1.0 for this?

This kind of error in this context usually stems from the invalid pointers to GPU memory, I think.

**Comment by shdyn** [comment]
Thanks for your reply.
The running experimental experiment only has glibc2.12 (cannot be changed).
I checked different versions of pre-built nvidia-dali. Only 0.1.0 version
supports glic2.12. Others are built on the glibc2.14.
If this error is in such a case, do you think it is related with the docker?
Thanks again.

**Comment by shdyn** [comment]
Correction: The running experimental environment only...

**Comment by awolant** [comment]
Oh, ok. I thought you are building DALI from source. 

Does the Pytorch code using the GPU work in your setup? If so, this might be some bug in this version of DALI, but it's hard to say. This is very old version.

Maybe you can try to build current DALI from source in your environment?

**Comment by JanuszL** [comment]
You can also try to build DALI on your own using manylinux2010 as a base image (this makes sure that glibc 2.12 is used). What you need to do is:
- remove https://github.com/NVIDIA/DALI/blob/master/docker/build.sh#L90L98
- change https://github.com/NVIDIA/DALI/blob/master/docker/build.sh#L72 to `export BASE_NAME=quay.io/pypa/manylinux2010_x86_64`

**Comment by shdyn** [comment]
Thank you guys. These are very useful information. I will try. If there is
any problem, I will come back to you.
