### ISSUE TITLE
Need some suggestion about how to decode from specific frame start index at every epoch?

### ISSUE THREAD

**Issue by kfhe00** [NVIDIA/DALI#1416]
Hi,
I am trying to modify VideoReader.
 I need batch_size = 1, and every epoch of my program would generator 32 specific frame start indexes. I want dali would decode the video from the 32 start indexes next time. 
But I find it's a little difficult, I want some suggestion about how to do that. 
Could you help me？ Thanks a lot.

**Comment by JanuszL** [comment]
Hi,
You may want to look into [preparation of allowed sequences](https://github.com/NVIDIA/DALI/blob/master/dali/operators/reader/loader/video_loader.h#L183) and [place where samples are selected to read](https://github.com/NVIDIA/DALI/blob/master/dali/operators/reader/loader/video_loader.cc#L596).
