### ISSUE TITLE
I met a problem when using DALI on P100.

### ISSUE THREAD

**Issue by PoonKinWang** [NVIDIA/DALI#1422]
A error was reported when I ran a pytorch code after importing nvidia.dali:

THCudaCheck FAIL file=/tmp/pip-req-build-58y_cjjl/aten/src/THC/THCGeneral.cpp line=50 error=3 : initialization error
...
torch._C._cuda_init()
RuntimeError: cuda runtime error (3) : initialization error at /tmp/pip-req-build-58y_cjjl/aten/src/THC/THCGeneral.cpp:50

Some info of the server: 
Linux version 4.4.0-131-generic (buildd@lgw01-amd64-015) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.10) )
4*P100
Driver Version: 418.40.04    
CUDA Version: 10.1  
pytorch1.2.0 cudatoolkit=10 
dali for CUDA 10.0

How can I solve with this problem? Thanks a lot

**Comment by awolant** [comment]
Hi, thanks for the question.
I assume that without importing DALI it works fine, right?
Could you provide some minimal reproduction of this issue. For now it's hard to say what happened. For example what is the exact order of importing modules?

One thing that comes to my mind is the current device status. There is a Pytorch API fo this (e.g. `torch.cuda.device()`). It would be good to make sure that you are trying to init the proper device.

**Comment by PoonKinWang** [comment]
> Hi, thanks for the question.
> I assume that without importing DALI it works fine, right?
> Could you provide some minimal reproduction of this issue. For now it's hard to say what happened. For example what is the exact order of importing modules?
> 
> One thing that comes to my mind is the current device status. There is a Pytorch API fo this (e.g. `torch.cuda.device()`). It would be good to make sure that you are trying to init the proper device.

Thanks for your advice, and I have tried to define which device to use. But, eventually, I found that when I used DALI in a subprocess the same error would occur. As far as I know, CUDA cannot be re-initialized, so that I didn't initialize CUDA twice (just initialzing it in subprocess). Therefore, I speculate that when import nvidia.dali, the mainprocess will initialize CUDA first, and the subprocess' initialization will become violative. If so, how can I use both of DALI and multiprocessing at the same time? Thanks in advance for your help.

**Comment by JanuszL** [comment]
Hi,
That is strange. Can you share some minimal reproduction as @awolant asked for? So we know how you want to use DALI and if you are not doing something that is an obvious no-go for us but we missed to properly document.

**Comment by PoonKinWang** [comment]
> Hi,
> That is strange. Can you share some minimal reproduction as @awolant asked for? So we know how you want to use DALI and if you are not doing something that is an obvious no-go for us but we missed to properly document.

Sorry, I thought the error just occuring with multiprocess. The demo is following.
`import multiprocessing
import datetime
import time

import torch
import nvidia.dali

def main(gpu_id):
    device = torch.device(gpu_id)
    torch.tensor(1).to(device)



if __name__ == '__main__':
    print("Program starts")
    gpu_id = 0
    while True:
        print(datetime.datetime.now())
        print("Training begins in "+str(gpu_id))
        
        child = multiprocessing.Process(target=main, args=(gpu_id,))
        child.start()
        child.join()
        print(datetime.datetime.now())
        print("Training stops")
        time.sleep(600)`

**Comment by JanuszL** [comment]
Thanks. Will check that.

**Comment by JanuszL** [comment]
It seems that torch doesn't like reinitialization in the forked process - https://pytorch.org/docs/stable/multiprocessing.html
And yes, when you import DALI cuda is initialized. What you can do is import DALI inside `main`.

**Comment by PoonKinWang** [comment]
What a plain but clear way! Just now I was watching where the source code can be modified to later initialization. Thanks for your help!
