### ISSUE TITLE
Installation error with TF plugin 0.15 and g++-4.8

### ISSUE THREAD

**Issue by ben0it8** [NVIDIA/DALI#1432]
Based on the image below, the prebuilt plugin should be available for this compiler version but still, I can't install it.

![image](https://user-images.githubusercontent.com/11842615/67934640-95658480-fbc8-11e9-8419-9c92063fcf99.png)

More info:
Ubuntu 18.04
Python 3.7
TF 2.0

**Comment by jantonguirao** [comment]
Hi @ben0it8,

This is a known problem with the combination of Python 3.7 and Tensorflow 2.0 (which we just started supportingi recently). 
Good news is that we already fixed it. It will be part of our next release, but for now you can just use our nightly builds instead:
```
pip install --extra-index-url https://developer.download.nvidia.com/compute/redist/nightly/cuda/10.0 nvidia-dali-nightly
pip install --extra-index-url https://developer.download.nvidia.com/compute/redist/nightly/cuda/10.0 nvidia-dali-tf-plugin-nightly
```

**Comment by ben0it8** [comment]
fantastic, thanks for the quick reply.

**Comment by JanuszL** [comment]
@ben0it8 - could you show the output from `nvidia-smi` command (GPU model, driver version)?
Has the resale version of DALI works for you (non-nightly)?

**Comment by ben0it8** [comment]
@JanuszL no, the non-nightly tf-plugin does not install. I've tried TF1.15 too -- same error.

![image](https://user-images.githubusercontent.com/11842615/67945473-3fe8a200-fbdf-11e9-87ce-45294a21f6a9.png)

**Comment by jantonguirao** [comment]
@ben0it8 I just tried the Dockerfile from your link and it works.

Are you running `nvidia-docker` (instead of `docker`)? You need that to have the CUDA runtime environment available (needed by DALI and tensorflow-gpu).

Regular docker (can't import):
```
$ docker run --rm test /bin/bash -c "python -c 'import nvidia.dali as dali; print(dali.__version__)'"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/srv/venv/lib/python3.7/site-packages/nvidia/dali/__init__.py", line 17, in <module>
    from . import ops
  File "/srv/venv/lib/python3.7/site-packages/nvidia/dali/ops.py", line 21, in <module>
    from nvidia.dali import backend as b
  File "/srv/venv/lib/python3.7/site-packages/nvidia/dali/backend.py", line 28, in <module>
    Init(OpSpec("CPUAllocator"), OpSpec("PinnedCPUAllocator"), OpSpec("GPUAllocator"))
RuntimeError: CUDA runtime API error cudaErrorInsufficientDriver (35):
CUDA driver version is insufficient for CUDA runtime version
```

nvidia-docker:
```
$ nvidia-docker run --rm test /bin/bash -c "python -c 'import nvidia.dali as dali; print(dali.__version__)'"
0.16.0dev.20191030
```

**Comment by ben0it8** [comment]
I was using `docker run ...--runtime=nvidia`, with `nvidia-docker` it works. thanks!
