### ISSUE TITLE
read lmdb without label

### ISSUE THREAD

**Issue by shawnthu** [NVIDIA/DALI#1433]
It seems that both CaffeReader and Caffe2Reader request that label must be provided, how can I read image from lmdb without label

**Comment by JanuszL** [comment]
Hi,
Yes, indeed we assume that label is present. Could you tell us what exact use case you have so the label is not there? What other kinds of data you have in your lmdb?

**Comment by shawnthu** [comment]
For example, in the region of Super Resolution (SR), the input is low resolution image, and the output is the corresponding high resolution counterpart, so generally two lmdbs are generated.

**Comment by JanuszL** [comment]
I have made https://github.com/NVIDIA/DALI/pull/1440 to support your case. Please check the nightly build when it is merged.

**Comment by shawnthu** [comment]
much thx
