### ISSUE TITLE
All pipeline crashed with illegal image type!!! Any solution to catch the exception?

### ISSUE THREAD

**Issue by donnyyou** [NVIDIA/DALI#1435]
When we use dali for images processing, all pipeline will crash due to some illegal image. I wonder how to catch the exception caused by this without all pipeline exiting.

**Comment by JanuszL** [comment]
Hi,
As DALI works in a separate set thread under the hood independently from the main Python one it is very hard or even impossible to do it in the way you are asking. Also, there is the question of what should happen with other images in the batch that are fine - how to put it back to the pool used to generate batches.
However, DALI reports which image exactly causes probelms so you can fix your dataset.
