### ISSUE TITLE
How to get the image size,e.g image_width and image_height?

### ISSUE THREAD

**Issue by uefall** [NVIDIA/DALI#1436]
Hi, thanks for this great work.

I have a problem with using custome pipeline,how could I get the decode images shape info,like image_w or image_h?

any help would be greatly appreciated

**Comment by JanuszL** [comment]
Hi,
If you want to get dimensions after decoding you can use [Shapes operator](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html#shapes). Before decoding it is not currently possible although we have code used internally that can [do this](https://github.com/NVIDIA/DALI/tree/master/dali/image) but you would need to wrap it up into the operator.

**Comment by uefall** [comment]
@JanuszL thanks for reply. 

what I need is raw resolution before decodeing, so is the PeekShape that could get the original image dimensions without decoding the image? 
I will have a try.

**Comment by JanuszL** [comment]
Yes, that is the one. It would be great if you can share your work with the rest of the community and issue a PR implementing this functionality in DALI. We would be more than happy to assist.

**Comment by mingqizhang** [comment]
> Yes, that is the one. It would be great if you can share your work with the rest of the community and issue a PR implementing this functionality in DALI. We would be more than happy to assist.

self.shape = ops.Shapes()
...
images = self.decoder(image)
shape = self.shape(images) 
The shape is not support index, so, could you tell me how to get the eight and width of images after decoder？

**Comment by mzient** [comment]
```python
from __future__ import division
import nvidia.dali as dali
from nvidia.dali import ops as ops
from nvidia.dali import types as types
import os.path

test_data_root = os.environ['DALI_EXTRA_PATH']
db_folder = os.path.join(test_data_root, 'db', 'lmdb')

class ExamplePipeline(dali.pipeline.Pipeline):
    def __init__(self, batch_size, num_threads, device_id, pipelined = True, exec_async = True):
        super(ExamplePipeline, self).__init__(
            batch_size, num_threads, device_id,
            seed = 12, exec_pipelined=pipelined, exec_async=exec_async)
        
        self.input = ops.CaffeReader(path = db_folder, random_shuffle = True)
        self.decode = ops.ImageDecoder(device = "cpu", output_type = types.RGB)
        self.shapes = ops.Shapes(device = "cpu")
        
    def define_graph(self):
        img_files, labels = self.input()
        images = self.decode(img_files)
        shapes = self.shapes(images)
        return [labels, images, shapes]
    
batch_size = 32
pipe = ExamplePipeline(batch_size=batch_size, num_threads=2, device_id = 0)
pipe.build()

output = pipe.run()
for i in range(len(output[2])):
    print(output[2].at(i))
```
This prints the following result:
```
[ 853 1280    3]
[ 853 1280    3]
[ 851 1280    3]
[1280  919    3]
[1024 1280    3]
[ 853 1280    3]
[ 853 1280    3]
[ 853 1280    3]
[ 988 1280    3]
[ 960 1280    3]
[ 911 1280    3]
[360 640   3]
[ 853 1280    3]
[1920 1280    3]
[ 853 1280    3]
[ 806 1280    3]
[ 968 1280    3]
[ 720 1280    3]
[ 825 1280    3]
[720 479   3]
[480 640   3]
[ 720 1280    3]
[ 853 1280    3]
[720 960   3]
[640 960   3]
[ 936 1280    3]
[279 960   3]
[ 849 1280    3]
[ 853 1280    3]
[427 640   3]
[ 825 1280    3]
[1920 1280    3]
```

**Comment by mingqizhang** [comment]
> ```python
> from __future__ import division
> import nvidia.dali as dali
> from nvidia.dali import ops as ops
> from nvidia.dali import types as types
> import os.path
> 
> test_data_root = os.environ['DALI_EXTRA_PATH']
> db_folder = os.path.join(test_data_root, 'db', 'lmdb')
> 
> class ExamplePipeline(dali.pipeline.Pipeline):
>     def __init__(self, batch_size, num_threads, device_id, pipelined = True, exec_async = True):
>         super(ExamplePipeline, self).__init__(
>             batch_size, num_threads, device_id,
>             seed = 12, exec_pipelined=pipelined, exec_async=exec_async)
>         
>         self.input = ops.CaffeReader(path = db_folder, random_shuffle = True)
>         self.decode = ops.ImageDecoder(device = "cpu", output_type = types.RGB)
>         self.shapes = ops.Shapes(device = "cpu")
>         
>     def define_graph(self):
>         img_files, labels = self.input()
>         images = self.decode(img_files)
>         shapes = self.shapes(images)
>         return [labels, images, shapes]
>     
> batch_size = 32
> pipe = ExamplePipeline(batch_size=batch_size, num_threads=2, device_id = 0)
> pipe.build()
> 
> output = pipe.run()
> for i in range(len(output[2])):
>     print(output[2].at(i))
> ```
> 
> This prints the following result:
> 
> ```
> [ 853 1280    3]
> [ 853 1280    3]
> [ 851 1280    3]
> [1280  919    3]
> [1024 1280    3]
> [ 853 1280    3]
> [ 853 1280    3]
> [ 853 1280    3]
> [ 988 1280    3]
> [ 960 1280    3]
> [ 911 1280    3]
> [360 640   3]
> [ 853 1280    3]
> [1920 1280    3]
> [ 853 1280    3]
> [ 806 1280    3]
> [ 968 1280    3]
> [ 720 1280    3]
> [ 825 1280    3]
> [720 479   3]
> [480 640   3]
> [ 720 1280    3]
> [ 853 1280    3]
> [720 960   3]
> [640 960   3]
> [ 936 1280    3]
> [279 960   3]
> [ 849 1280    3]
> [ 853 1280    3]
> [427 640   3]
> [ 825 1280    3]
> [1920 1280    3]
> ```

Thanks fot your reply. Actually, i want to get the height and width in the define_graph, so I can get the offset to do the paste.
For example, I have the image of 512x256,and then I will resize it to 256x128. Finally, I use paste operator to pad it to 256x256，like this
![0-0](https://user-images.githubusercontent.com/28778038/68856595-d8247200-071b-11ea-9df3-8be947f80be2.jpg)
Do you have any suggestions for me? Better  give the an example,thanks.

**Comment by mzient** [comment]
Actually, for that you don't need Shapes at all.
```python
        self.resize = ops.Resize(device = "gpu", resize_longer = 256)
        self.paste = ops.Paste(device = "gpu", paste_x = 0.5, paste_y = 0.5, ratio = 1, min_canvas_size = 256, fill_value = 0)
```
This does the trick. This only works for square images, but if you're good with square, then you're set.

**Comment by mingqizhang** [comment]
> Actually, for that you don't need Shapes at all.
> 
> ```python
>         self.resize = ops.Resize(device = "gpu", resize_longer = 256)
>         self.paste = ops.Paste(device = "gpu", paste_x = 0.5, paste_y = 0.5, ratio = 1, min_canvas_size = 256, fill_value = 0)
> ```
> 
> ...and in `define_graph`...
> 
> ```python
>     out_images = self.paste(self.resize(images))
> ```
> 
> This does the trick. This only works for square images, but if you're good with square, then you're set.

Thanks, that's what i want.

**Comment by 372046933** [comment]
@mingqizhang Do you have any ideas about rectangular images padding?

**Comment by JanuszL** [comment]
@372046933 - what exactly you need to do?

**Comment by 372046933** [comment]
@JanuszL . I want to make the following transformations to the image.

1. Resize (Can be done by `dali.ops.Resize`)
2. Normalize (Can be done by `dali.ops.CropMirrorNormalize`)
3. Pad zeros to image's right and bottom border. The  size of padding depends on the image size after step 1

I can't implement step 3 because image size (height & width) is not available at step 3. Only `max_size`, `resize_longer` or `resize_shorter` can be deduced after step 1.

**Comment by JanuszL** [comment]
@372046933 
> Pad zeros to image's right and bottom border. The size of padding depends on the image size after step 1

Have you checked `out_of_bounds_policy` from `CropMirrorNormalize`. If your output image size is fixed and you only need to determine the amount of padding then this should solve your problem.
If it is not your case, could you provide any examples of:
> The size of padding depends on the image size after step 1

**Comment by 372046933** [comment]
@JanuszL Thanks, I have checked `out_of_bounds_policy`, but the `crop` argument can not be determined at initialization phase. For example, if an image size is `640 * 320(W*H)`, and I want to make the width and height of the image to be a multiple of 128 after normalization. `dali.ops.Paste` only supports `uint8`

**Comment by JanuszL** [comment]
In that case, you can try to use slice with `out_of_bounds_policy` too. You can obtain the Image dimension using []PeekImageShape](https://docs.nvidia.com/deeplearning/dali/master-user-guide/docs/supported_ops.html#nvidia.dali.ops.PeekImageShape) operator (available in DALI nightly and weekly builds) and based on them calculate the necessary `Slice` parameters.

**Comment by mzient** [comment]
We have a Pad operator can do what you want:
```Python
import nvidia.dali as dali
import nvidia.dali.fn as fn
import numpy as np

def get_data():
    # prepare a dummy batch
    return [
      np.zeros([480, 600, 3], dtype=np.float32),
      np.zeros([300, 400, 3], dtype=np.float32)
    ]

pipe = dali.pipeline.Pipeline(batch_size=2, device_id=0, num_threads=1)
with pipe:
    # prepare some dummy data
    input = fn.external_source(source=get_data, layout="HWC")
    # shape=[0,0] will cause no padding other than that required by the alignment
    # axes=[0,1] will pad only first two axes, the channel dimension will remain unpadded
    padded = fn.pad(input, align=128, shape=[0,0], axes=[0,1])  # or axis_names="HW"
    pipe.set_outputs(padded)

pipe.build()
o = pipe.run()
print("Padding separately")
print(o[0].at(0).shape)
print(o[0].at(1).shape)


pipe2 = dali.pipeline.Pipeline(batch_size=2, device_id=0, num_threads=1)
with pipe2:
    # prepare some dummy data
    input = fn.external_source(source=get_data, layout="HWC")
    # Not specifying a shape will cause all images in the batch
    # to be padded to the size of the largest sample.
    # axes=[0,1] will pad only first two axes, the channel dimension will remain unpadded
    padded = fn.pad(input, align=128, axes=[0,1])  # or axis_names="HW"
    pipe2.set_outputs(padded)

pipe2.build()
o = pipe2.run()
print("Padding batch")
print(o[0].at(0).shape)
print(o[0].at(1).shape)
```

The result is:
```
Padding separately
(512, 640, 3)
(384, 512, 3)
Padding batch
(512, 640, 3)
(512, 640, 3)
```

Does that handle your use case?

**Comment by 372046933** [comment]
I see that `dali.ops.PeekImageShape` only supports CPU backend currently. But `Pad with align` seems great. I'll try that. Thanks very much.

**Comment by mzient** [comment]
You're most welcome. I'm glad I could be of help.
