### ISSUE TITLE
RuntimeError: Critical error in pipeline（Data loading:-TensorFlow TFRecord）

### ISSUE THREAD

**Issue by sosofun** [NVIDIA/DALI#144]
DALI 0.2 in docker,   GPU num: 8: 
code:  dataloading_tfrecord.ipynb 

```
from subprocess import call
import os.path

tfrecord = "/code/datasets/imagenet/valid.tfrecord"
tfrecord_idx = "idx_files/valid.idx"
tfrecord2idx_script = "tfrecord2idx"

if not os.path.exists("idx_files"):
    os.mkdir("idx_files")

if not os.path.isfile(tfrecord_idx):
    call([tfrecord2idx_script, tfrecord, tfrecord_idx])



from nvidia.dali.pipeline import Pipeline
import nvidia.dali.ops as ops
import nvidia.dali.types as types
import nvidia.dali.tfrecord as tfrec
import numpy as np
import matplotlib.pyplot as plt


class TFRecordPipeline(Pipeline):
    def __init__(self, batch_size, num_threads, device_id):
        super(TFRecordPipeline, self).__init__(batch_size,
                                         num_threads,
                                         device_id)
        self.input = ops.TFRecordReader(path = tfrecord, 
                                        index_path = tfrecord_idx,
                                        features = {"image/encoded" : tfrec.FixedLenFeature((), tfrec.string, ""),
                                         'image/class/label':         tfrec.FixedLenFeature([1], tfrec.int64,  -1),
                                         'image/class/text':          tfrec.FixedLenFeature([ ], tfrec.string, ''),
                                         'image/object/bbox/xmin':    tfrec.VarLenFeature(tfrec.float32, 0.0),
                                         'image/object/bbox/ymin':    tfrec.VarLenFeature(tfrec.float32, 0.0),
                                         'image/object/bbox/xmax':    tfrec.VarLenFeature(tfrec.float32, 0.0),
                                         'image/object/bbox/ymax':    tfrec.VarLenFeature(tfrec.float32, 0.0)})
        self.decode = ops.nvJPEGDecoder(device = "mixed", output_type = types.RGB)
        self.resize = ops.Resize(device = "gpu", resize_shorter = 256.)
        self.cmnp = ops.CropMirrorNormalize(device = "gpu",
                                            output_dtype = types.FLOAT,
                                            crop = (224, 224),
                                            image_type = types.RGB,
                                            mean = [0., 0., 0.],
                                            std = [1., 1., 1.])
        self.uniform = ops.Uniform(range = (0.0, 1.0))
        self.iter = 0

    def define_graph(self):
        inputs = self.input()
        images = self.decode(inputs["image/encoded"])
        resized_images = self.resize(images)
        output = self.cmnp(images, crop_pos_x = self.uniform(),
                           crop_pos_y = self.uniform())
        return (output, inputs["image/class/text"])

    def iter_setup(self):
        pass

batch_size = 16

pipe = TFRecordPipeline(batch_size=batch_size, num_threads=4, device_id = 0)
pipe.build()
```
----------------------------------
all rights, then  do the below code :

```
pipe_out = pipe.run()
```
-----------------------------------------

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-5-636c3db419af> in <module>()
----> 1 pipe_out = pipe.run()

/usr/local/lib/python3.5/dist-packages/nvidia/dali/pipeline.py in run(self)
    246         faster execution."""
    247         self._start_run()
--> 248         return self.outputs()
    249 
    250     def _start_run(self):

/usr/local/lib/python3.5/dist-packages/nvidia/dali/pipeline.py in outputs(self)
    237         if not self._built:
    238             raise RuntimeError("Pipeline must be built first.")
--> 239         return self._pipe.Outputs()
    240 
    241     def run(self):

RuntimeError: Critical error in pipeline: Error in thread 0: Caught unknown exception
Current pipeline object is no longer valid.

```

**Comment by JanuszL** [comment]
Hi,
It is very strange, could you look into a console where you launched your jupyter notebook process, some errors are reported there as well.
You can also copy-paste this example to plain python script and run it form the console - then we have all errors in one output.

**Comment by JanuszL** [comment]
Hi,
If this still doesn't work for you and you have more logs please reopen.

**Comment by ranjiewwen** [comment]
i meet this problem:

> File "/opt/conda/lib/python3.6/site-packages/nvidia/dali/plugin/pytorch.py", line 150, in __next__
    return self.__next__()
    return self.__next__()
  File "/opt/conda/lib/python3.6/site-packages/nvidia/dali/plugin/pytorch.py", line 150, in __next__
  File "/opt/conda/lib/python3.6/site-packages/nvidia/dali/plugin/pytorch.py", line 150, in __next__
    return self.__next__()
  File "/opt/conda/lib/python3.6/site-packages/nvidia/dali/plugin/pytorch.py", line 150, in __next__
    outputs.append(p.share_outputs())
  File "/opt/conda/lib/python3.6/site-packages/nvidia/dali/pipeline.py", line 402, in share_outputs
    outputs.append(p.share_outputs())
  File "/opt/conda/lib/python3.6/site-packages/nvidia/dali/pipeline.py", line 402, in share_outputs
    outputs.append(p.share_outputs())
    outputs.append(p.share_outputs())
  File "/opt/conda/lib/python3.6/site-packages/nvidia/dali/pipeline.py", line 402, in share_outputs
  File "/opt/conda/lib/python3.6/site-packages/nvidia/dali/pipeline.py", line 402, in share_outputs
    return self._pipe.ShareOutputs()
    return self._pipe.ShareOutputs()
RuntimeError: Critical error in pipeline: CUDA allocation failed
Current pipeline object is no longer valid.
    return self._pipe.ShareOutputs()
    return self._pipe.ShareOutputs()
RuntimeError: Critical error in pipeline: CUDA allocation failed
Current pipeline object is no longer valid.RuntimeError: Critical error in pipeline: CUDA allocation failed
Current pipeline object is no longer valid.
RuntimeError: Critical error in pipeline: CUDA allocation failed
Current pipeline object is no longer valid.  

and then i reduce the batchsize solve this .

**Comment by JanuszL** [comment]
`CUDA allocation failed` usually means that your are running out of memory.

**Comment by bonlime** [comment]
I met the same problem as @ranjiewwen. This issue helped me to solve it #21 
Long story short: TF allocates almost all memory and DALI fails to allocate required tensors with huge BS but does allocate with small BS which is very frustrating. Could you please update the docs for TF plugin to mention such behavior?

**Comment by JanuszL** [comment]
@awolant - could you update the TF plugin docs in the meantime as you work on TF dataset currently?
