### ISSUE TITLE
The speed of executing "PIPELINE" instance depending on whether running nvidia-smi -l in another terminal

### ISSUE THREAD

**Issue by yanmingcheng** [NVIDIA/DALI#1441]
Hi 
I have successfully coded and ran a Pipeline descendant class following the starter tutorials. However, I have noticed the code runs quite fast while nvidia-smi -l was running in another terminal of the same Linux machine (GPU with Volta architecture). In this case, gpustat showed that GPU was used. However, the code ran extremely slowly while no nvidia-smi was running. In this case, gpustat show no GPU was used. Just can't figure out what was going on. Please help!!!
Below is the test Python code:
#!/usr/bin/env python
import sys
from sys import platform

import os
import cv2
from time import time, sleep
import argparse
import numpy as np

############# nvidia DALI for GPU speed up
from nvidia.dali.pipeline import Pipeline
import nvidia.dali.ops as ops
import nvidia.dali.types as dali_types
from nvidia.dali.plugin.pytorch import DALIGenericIterator

class ExternalTransformIterator(object):
    def __init__(self, batch_size, dataset):
        self.batch_size = batch_size
        self.dataset = dataset

    def __iter__(self):
        self.i = 0
        self.n = self.dataset.shape[0]
        return self

    def __next__(self):
        self.i = self.n
        return (list(self.dataset), ) 

    next = __next__
    
class DaliTransforms(Pipeline):
    def __init__(self, dataset, height, width, batch_size, use_gpu=True, num_threads=1, device_id=0):
        t0=time()
        super(DaliTransforms, self).__init__(batch_size, num_threads, device_id)
        t1=time()
        self.use_gpu = use_gpu
        length = dataset.shape[0]
        self.data_iterator = iter(ExternalTransformIterator(dataset=dataset, batch_size=length))
        t2=time()
        self.input = ops.ExternalSource()
        t3=time()
        self.resize = ops.Resize(device=("gpu" if self.use_gpu else "cpu"), 
                                 image_type=dali_types.RGB,
                                 resize_y=height, resize_x=width, 
                                 interp_type=dali_types.INTERP_CUBIC 
                                 )
        t4=time()
        self.normalize = ops.CropMirrorNormalize(device=("gpu" if self.use_gpu else "cpu"),
                                                output_dtype=dali_types.FLOAT,
                                                image_type=dali_types.RGB,
                                                mean=[0.485 * 255, 0.456 * 255, 0.406 * 255], 
                                                std=[0.229 * 255, 0.224 * 255, 0.225 * 255], 
                                                output_layout=dali_types.NCHW)            
        t5 =time()
        self.begin_time = t5
        
    def define_graph(self):
        self.images = self.input()
        images = self.resize(self.images.gpu() if self.use_gpu else self.images)
        images = self.normalize(images)
        return (images,)

    def iter_setup(self):
        self.feed_input(self.images, self.data_iterator.next()[0])

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input_video_path", type=str, default="/tmp/demo.gif")
    parser.add_argument('--batchsize', default=5, type=int, help='batchsize')
    return parser.parse_args()

if __name__=="__main__":
    
    args = parse_args()

    
    video_frame_rate= 25
    chunksize = args.batchsize
    print("")
    print("Process video file:", args.input_video_path)
    vidcap = cv2.VideoCapture(args.input_video_path)
    input_images=[]
    cap_success=True
    duration = 0
    frameRate = 1.0 / video_frame_rate
    count=0
    #t_begin = time()
    while cap_success :
        duration = duration + frameRate
        vidcap.set(cv2.CAP_PROP_POS_MSEC, duration*1000)
        cap_success, img = vidcap.read()
        if cap_success :
            img_shape = img.shape
            img_dtype = str(img.dtype)
            input_images.append(img)
        count += 1
        if ((count%chunksize)==0) or not cap_success :
            dataset = np.array(input_images)
            t0=time()
            transforme_pipe = DaliTransforms(dataset=dataset, use_gpu=True,
                                             height=dataset.shape[1], width=dataset.shape[2], batch_size=dataset.shape[0])
            t1=time()
            transforme_pipe.build()
            t2=time()
            dataset_transformed = transforme_pipe.run()[0]
            t3=time()
            print(" dataset shape: %s, t1-t0=%.3f (%.3f) t2-t1=%.3f t3-t2=%.3f " % (str(dataset.shape), t1-t0, t1-transforme_pipe.begin_time, t2-t1, t3-t2))
            input_images=[]
    print("Done Process video file:", args.input_video_path, " with %d frames" % count)
    vidcap.release()

############# code end ###########

Thanks in advance

**Comment by JanuszL** [comment]
Hi,
Can you tell what do you mean by fast and slow? Can you provide some example timings?
Also, I see that you create `transforme_pipe` for every batch you process, while you should create the pipeline only once, and then just call `run` as many times as you need to process a batch.
[gpustat](https://github.com/wookayin/gpustat) seems to use [pynvml](https://github.com/fbcotter/py3nvml) ([here](https://github.com/wookayin/gpustat/blob/master/gpustat/core.py#L26))  - python bindings to nvml which is also used by nvidia-smi. So both should report the same values unless there is some problem with the interoperability which rather should be reported to gpustat authors.

**Comment by yanmingcheng** [comment]
Hi Januszl
Thanks for prompt response! What I mean "fast" is that with nvidia-smi -l running in another terminal the code can run as at least 10x fast as it runs without nvidia-smi. Below are the print out of time()s inserted in multiple places of the code.
Case 1: with nvidia-smi -l running in another terminal:
nvidia-docker run --rm -w /root --name YMC -e CUDA_VISIBLE_DEVICES=2 -v /cto-home/fyc002/AIServices/frictionless_shopping:/root  -it nvidia/dali-debug:0.0 python3 test_dali.py --batchsize 20

Process video file: /tmp/demo.gif
 dataset shape: (20, 240, 320, 3), t1-t0=0.000 (0.000) t2-t1=0.643 t3-t2=0.032
 dataset shape: (20, 240, 320, 3), t1-t0=0.012 (0.011) t2-t1=0.028 t3-t2=0.023
 dataset shape: (20, 240, 320, 3), t1-t0=0.007 (0.007) t2-t1=0.026 t3-t2=0.018
 dataset shape: (20, 240, 320, 3), t1-t0=0.019 (0.019) t2-t1=0.029 t3-t2=0.021
 dataset shape: (20, 240, 320, 3), t1-t0=0.014 (0.013) t2-t1=0.030 t3-t2=0.022
 dataset shape: (20, 240, 320, 3), t1-t0=0.018 (0.018) t2-t1=0.042 t3-t2=0.029
 dataset shape: (20, 240, 320, 3), t1-t0=0.014 (0.014) t2-t1=0.029 t3-t2=0.023
 dataset shape: (20, 240, 320, 3), t1-t0=0.017 (0.017) t2-t1=0.030 t3-t2=0.021
 dataset shape: (20, 240, 320, 3), t1-t0=0.012 (0.011) t2-t1=0.029 t3-t2=0.023
 dataset shape: (20, 240, 320, 3), t1-t0=0.017 (0.017) t2-t1=0.030 t3-t2=0.023
 dataset shape: (5, 240, 320, 3), t1-t0=0.012 (0.012) t2-t1=0.029 t3-t2=0.010
Done Process video file: /tmp/demo.gif  with 206 frames

Case 2: Without nvidia-smi running:
nvidia-docker run --rm -w /root --name YMC -e CUDA_VISIBLE_DEVICES=2 -v /cto-home/fyc002/AIServices/frictionless_shopping:/root  -it nvidia/dali-debug:0.0 python3 test_dali.py --batchsize 20

Process video file: /tmp/demo.gif
 dataset shape: (20, 240, 320, 3), t1-t0=0.000 (0.000) t2-t1=2.435 t3-t2=0.026
 dataset shape: (20, 240, 320, 3), t1-t0=0.796 (0.796) t2-t1=2.023 t3-t2=0.026
 dataset shape: (20, 240, 320, 3), t1-t0=0.766 (0.766) t2-t1=2.076 t3-t2=0.026
 dataset shape: (20, 240, 320, 3), t1-t0=0.796 (0.796) t2-t1=2.131 t3-t2=0.026
 dataset shape: (20, 240, 320, 3), t1-t0=0.810 (0.810) t2-t1=2.331 t3-t2=0.029
 dataset shape: (20, 240, 320, 3), t1-t0=0.770 (0.770) t2-t1=2.255 t3-t2=0.031
 dataset shape: (20, 240, 320, 3), t1-t0=0.796 (0.795) t2-t1=2.296 t3-t2=0.027
 dataset shape: (20, 240, 320, 3), t1-t0=0.737 (0.737) t2-t1=2.162 t3-t2=0.027
 dataset shape: (20, 240, 320, 3), t1-t0=0.778 (0.778) t2-t1=2.470 t3-t2=0.024
 dataset shape: (20, 240, 320, 3), t1-t0=0.789 (0.789) t2-t1=2.067 t3-t2=0.028
 dataset shape: (5, 240, 320, 3), t1-t0=0.758 (0.758) t2-t1=2.114 t3-t2=0.011
Done Process video file: /tmp/demo.gif  with 206 frames

The time differences in seconds for both t1-t0 (Pipeline __init__()) and t2-t1 (Pipeline build()) for Case 2 are significantly larger than Case 1. However, the t3-t2 (Pipeline run()) are similar for both cases.

My feeling was that there is a switch of controlling GPU allocation in Pipeline C/C++ code, which was on/off depending whether running nvidia-smi.

**Comment by JanuszL** [comment]
What is the most important for use it t3-t2 which indicates data processing time, t1-t0 and t2-t1 is about initialization and allocations, and as said before you should do it only once, not every iteration.
If you run nvidia-smi in the background it may behave the same way as the persistent mode in driver so that is why it affects the initialization time - 
https://docs.nvidia.com/deploy/driver-persistence/index.html
