### ISSUE TITLE
Recommended Model Visualizer?

### ISSUE THREAD

**Issue by meshaun9** [NVIDIA/DALI#1443]
Do you promote a recommended model Visualizer other than Tensorboard that can interpret the Dali TF plugin operations?

**Comment by JanuszL** [comment]
Hi,
Currently, we don't have such a recommendation.
Can you tell more about what exactly you want to visualize? The output from the DALI pipeline? Or how much the processing lasts in DALI?

**Comment by meshaun9** [comment]
I'd like to visualize the entire structure of the model to understand more of how the Dali TF operations are structured.

**Comment by anishagartia** [comment]
Can we use native TF to do this visualization? Right now I get an error that says Op not recognized: Dali.

**Comment by meshaun9** [comment]
I've tried Netron and I believe that based on it's dependency on Native TF it doesn't support the Dali TF operations and yes I get the same error you are getting.

**Comment by meshaun9** [comment]
I've also tried summarize graph and it's the same result that you're seeing.

**Comment by JanuszL** [comment]
DALI op in TF is just a custom op that wraps the DALI pipeline. DALI pipeline itself creates a set of native threads running in parallel to the training. I would be surprised if the TF can recognize it.
What TF schedules in the case of DALI is just an operation of copying data out from DALI to the TF tensors, while de rest id done asynchronously to the TF graph execution.
