### ISSUE TITLE
GPU kernel launches aren't always finished before result is returned

### ISSUE THREAD

**Issue by rbetz** [NVIDIA/DALI#1448]
DALI operators don't all seem to call `cudaDeviceSynchronize` or `cudaStreamSynchronize` after kernel launches, leading to incomplete results being returned even on pipelines where `exec_async=False`.

I am using DALI a little atypically, creating Pipelines that are callable and can be run on a single image. I'm not sure why I get this behavior in my implementation vs. one that more closely resembles the documentation.

The following GPU code produces incomplete results:
```
import numpy as np
import nvidia.dali.ops as ops
from nvidia.dali.pipeline import Pipeline
from PIL import image

class SimpleGPUPipeline(Pipeline):
    def __init__(self, batch_size, num_threads, device_id):
        super(SimpleGPUPipeline, self).__init__(batch_size, num_threads, device_id, seed=1,
                                                exec_pipelined=False, exec_async=False)
        self.input = ops.ExternalSource()
        self.labelinput = ops.ExternalSource()
        self.twist = ops.ColorTwist(device="gpu", hue=50)

    def define_graph(self):
        self.jpegs = self.input()
        self.label = self.labelinput()
        images = self.jpegs.gpu()
        images = self.twist(images)
        return images, self.label

    def __call__(self, image_path):
        # Open image and convert to NHWC
        img = np.array(Image.open(image_path))
        img_nhwc = np.moveaxis(img, [0,1,2], [1,2,0]) # NHWC
        img_nhwc = np.ascontiguousarray(img_nhwc)
        img_nhwc = img_nhwc.reshape(1, *img_nhwc.shape)

        # Feed to pipeline
        self.feed_input(self.jpegs, img_nhwc)
        self.feed_input(self.label, np.array([0]))
        imgt, _ = pipe.run()

        # Convert back to CWH on CPU
        imgc = imgt.as_cpu().at(0)
        imgc = np.moveaxis(imgc, [0,1,2], [2,0,1])

        return imgc

# Build pipeline
pipe = SimpleGPUPipeline(batch_size=1, num_threads=1, device_id=0)
pipe.build()

# Run pipeline on one image and show it
img_out = pipe("cat_pic.jpg")
plt.imshow(img_out)
```

Expected result (can be obtained with a CPU implementation of the above, omitting the conversion to HWC):
![image](https://user-images.githubusercontent.com/54285210/68335264-01486100-0091-11ea-89e2-d76a239db56d.png)

Actual result:
![image](https://user-images.githubusercontent.com/54285210/68335284-073e4200-0091-11ea-9e0b-215dc5598aa9.png)

I have some custom operators that had the same problem, and a call to `cudaDeviceSynchronize` following kernel launches fixes the issue. I noticed some DALI operators do synchronize but others (like ColorTwist) don't.

Running this pipeline with `exec_async=True, exec_pipelined=True` has the same issue.

A few questions:
- Is this a bug, or am I using the library incorrectly? I know the example is a bit contrived, running on a single image at a time. I do need the `ExternalSource` operator for my use-case rather than one of the provided loaders.
- How do DALI pipelines avoid this problem of operating on images before previous kernel launches are complete? I imagine all launches occur on the same stream and are serialized there, but what ensures the returned result is ready to go?
- Can I fix this by adding calls to `cudaStreamSynchronize` somewhere before the results are returned? Would each operator need this addition? I'm happy to assemble a pull request but want to make sure I understand what's going on.

**Comment by JanuszL** [comment]
Hi,
The recommended way of using `ExternalSource` is to call `feed_input` from the inside of `iter_setup` method. It is because DALI does prefetching and when you can run for the first time in the background DALI will run ahead `prefetch_queue_depth` times. `iter_setup` will be called the appropriate number of times as well so DALI have all necessary data to run the pipeline.
Have you checked if that works correctly for you?
Regarding synchronization kernels usually don't do that, and DALI synchronizes only when the outputs need to be obtained - `run` or `share_outputs`.
You may try to set `exec_pipelined` to `false`, `prefetch_queue_depth` to `1` (no prefetching) and see how it works in your case.

**Comment by JanuszL** [comment]
I have tried this code and ti works fine:
```
import numpy as np
import nvidia.dali.ops as ops
from nvidia.dali.pipeline import Pipeline
from PIL import Image
import matplotlib.pyplot as plt

class SimpleGPUPipeline(Pipeline):
    def __init__(self, batch_size, num_threads, device_id):
        super(SimpleGPUPipeline, self).__init__(batch_size, num_threads, device_id, seed=1,
                                                exec_pipelined=True, exec_async=True, prefetch_queue_depth=1)
        self.input = ops.ExternalSource()
        self.labelinput = ops.ExternalSource()
        self.twist = ops.ColorTwist(device="gpu", hue=10)

    def define_graph(self):
        self.jpegs = self.input()
        self.label = self.labelinput()
        images = self.jpegs.gpu()
        images = self.twist(images)
        return images, self.label
    
       
    def __call__(self, image_path):
        # Open image and convert to NHWC
        img = np.array(Image.open(image_path))
        img_nhwc = np.ascontiguousarray(img)
        img_nhwc = img_nhwc.reshape(1, *img_nhwc.shape)

        # Feed to pipeline
        self.feed_input(self.jpegs, img_nhwc)
        self.feed_input(self.label, np.array([0]))
        imgt, _ = pipe.run()

        imgc = imgt.as_cpu().at(0)

        return imgc


# Build pipeline
pipe = SimpleGPUPipeline(batch_size=1, num_threads=1, device_id=0)
pipe.build()

# Run pipeline on one image and show it
img_out = pipe("docs/examples/images/kitten/cat_10.jpg")
plt.imshow(img_out)
```

**Comment by JanuszL** [comment]
If it still doesn't work please reopen.
