### ISSUE TITLE
Is cuda10.1 supported now?

### ISSUE THREAD

**Issue by xuezu29** [NVIDIA/DALI#1454]
Is cuda10.1 supported now?

**Comment by cliffwoolley** [comment]
You can use the DALI builds made using CUDA 10.0 within an application otherwise built for CUDA 10.1.  This works fine (and is a tested as such).

**Comment by xuezu29** [comment]
That is great! thanks!

**Comment by JanuszL** [comment]
If you really need CUDA 10.1 builds you can easily create one on your own following [this guide](https://docs.nvidia.com/deeplearning/sdk/dali-master-branch-user-guide/docs/compilation.html#compiling-dali-from-source-using-docker-builder-recommended) :
- create docker file with the toolkit  - similar to https://github.com/NVIDIA/DALI/blob/master/docker/Dockerfile.cuda10.deps and name it Dockerfile.cuda101.deps 
- use https://github.com/NVIDIA/DALI/blob/master/docker/build.sh with CUDA_VERSION=.101 (this `dot` skips sanity check)

**Comment by huangh12** [comment]
Hi @cliffwoolley , my env is also CUDA10.1.  

After installing the DALI with the command
> pip install --extra-index-url https://developer.download.nvidia.com/compute/redist --upgrade nvidia-dali-cuda100

I can import Pipeline
```Python
from nvidia.dali.pipeline import Pipeline
```
But the pipeline_def cannot be found

>     from nvidia.dali import pipeline_def
> ImportError: cannot import name 'pipeline_def'

Do you know how to resolve it? 
Thank you.

**Comment by JanuszL** [comment]
@huangh12 - `pipeline_def` is part of the 1.0 release that should be released by the end of the month. In the meantime, you can try either [the nightly build](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/installation.html#nightly-and-weekly-release-channels), or use examples for [0.31 release](https://github.com/NVIDIA/DALI/tree/release_v0.31).

**Comment by huangh12** [comment]
Thank you so much for the prompt reply. Using the nightly build fix my problem.
