### ISSUE TITLE
Get the "same" scaled up Random Crop on a higher resolution image.

### ISSUE THREAD

**Issue by KevinMrc** [NVIDIA/DALI#1456]
Hello, I'm working on a Super-resolution problem:

I would like to apply a random crop to my lowres input image and get the same crop but scaled up on my highres output image. (I can't just use the resize function on the cropped highres images from DALI because my downscaled images were done in a specific way already)

Is there a way to do this or get the coordinates from the cropping maybe?

I searched the docs and the Video Super-Resolution example but I couldn't find an anwser, sorry if I missed it, I'm new to DALI.

Thank you very much for your help 👍

**Comment by JanuszL** [comment]
Hi,
You can use [slice operator](https://docs.nvidia.com/deeplearning/sdk/dali-master-branch-user-guide/docs/supported_ops.html#nvidia.dali.ops.Slice) and feed it with the data from the [ExternalSource operator](https://docs.nvidia.com/deeplearning/sdk/dali-master-branch-user-guide/docs/supported_ops.html#nvidia.dali.ops.ExternalSource) so you can define relative coordinates and the size of the cropping window. You can also do something like that to make sure that the same operation is executed on both your data streams:
```
[small_cropped, big_cropped] = self.slice([small, big], crop_anchor , crop_window)
```
@jantonguirao - have I missed anything?

**Comment by KevinMrc** [comment]
Thank you very much!

I found the same general idea in [the docs](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/decoder_examples.html#Image-Decoder-(Hybrid)-with-external-window-size-and-anchor) but using ImageDecoderSlice.

If I understand correctly it will work just like slice, but it has the advantage to use partial decoding instead of having to decode the entire image before slicing?

**Comment by JanuszL** [comment]
@KevinMrc,

> If I understand correctly it will work just like slice, but it has the advantage to use partial decoding instead of having to decode the entire image before slicing?

Yes, this is exactly what it is doing. Actually, it decodes more than just provided ROI (due to how JPEG format looks like) - it decodes from the start to the right, bottom corner of the image. But still, in most cases, it will provide you some additional performance benefits.
