### ISSUE TITLE
VideoReader track frame location

### ISSUE THREAD

**Issue by miguelrc1** [NVIDIA/DALI#1458]
Hello,

While VideoReader is a great option to decrease disk usage and have a I/O for video data, I was wondering if currently there is any way to track the location in the video of the frames that are being inputed at every iteration through VideoReader. I found that this increases the flexibility of this module. See below a use case for that.

Use case 1: Sound
* Videos generally include an additional signal: sound. If we want to use it in our modeling it's hard to do so using the current implementation of VideoReader.

Use case 2: Frame level task
* If the task in hand is the classification of video frames the location of the frames is needed to map those to their appropriate label.

**Comment by JanuszL** [comment]
Hi,
We are aware of this request. There is a long thread about it https://github.com/NVIDIA/DALI/issues/753 and @a-sansanwal will post some [PR with that functionality](https://github.com/NVIDIA/DALI/issues/753#issuecomment-552384488).

**Comment by JanuszL** [comment]
Can you check how https://github.com/NVIDIA/DALI/pull/1500 works for you with the latest nightly build?
