### ISSUE TITLE
Replacing Tensorflow's Estimator input function with Dali input function

### ISSUE THREAD

**Issue by piseabhijeet** [NVIDIA/DALI#1462]
Hi,
I am using Dali 0.15 with the TF-plugin.
I have a model which is based on the Estimator framework and uses a TF Dataset for passing data from the input_fn(). The input_fn() reads video frames and its corresponding labels from a TFRecord file.  I am facing few issues:

1. When using a DALI as a data loading library, i have to return images which are decoded and processed labels in the form of 'Edge Reference Object', however, i cannot combine the images and send a batch of images as 'Edge Reference Object' from the define_graph(). Is there any alternative to this?

2. When processing images/labels using tensor operations, I have to use dali-tf plugin to return images and labels as tensors, how is this pair from the daliop given as an input to the Estimator in Estimator framework? :

import nvidia.dali.plugin.tf as dali_tf
daliop = dali_tf.DALIIterator()
image = daliop(pipeline = pipe, shapes = [(1,360,640,3)], dtypes = [tf.uint8]) 

Here is the define_graph() function snapshot:

![define_graph()](https://user-images.githubusercontent.com/57705684/68750147-6e29a100-0625-11ea-88a9-3cbf65d22fd1.png)

Thanks,
Abhijeet

**Comment by JanuszL** [comment]
Hi,

1) It is assumed that each entry in TFRecord is a separate sample. If you stores consecutive frames from one sequence as a separate entry in the TFRecord DALI is not able to handle it properly. If it is possible I would recommend storing them as a separate feature in one entry instead of several entries. Of course, DALI would need some operator that would assemble a sequence from the list of tensors (frames), but it is more in line with our understanding of what a sample is inside given data containers.

2) Have you looked into https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/tensorflow/demo/README.html ?

@awolant - have I missed anything?

**Comment by piseabhijeet** [comment]
Hi,

Thank you for your response. I had assumed the same thing. Creating one tfrecord per example would not be a problem however multiple labels are to be passed as outputs from the define_graph() function as you see in the snapshot shared. Is there a way to combine these as well?

Thank you

**Comment by JanuszL** [comment]
Hi,
You can store labels as a vector of values as well - so you have multiple features with frame per entry and one vector of labels.
Please check [here](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html#nvidia.dali.ops.TFRecordReader) about  dali.tfrecord.FixedLenFeature and dali.tfrecord.VarLenFeature.

**Comment by piseabhijeet** [comment]
Hi,

Thank you for your response. I meant can labels in define_graph() be modified/encapsulated so that 
inputs['signals1'], inputs['signals2'], inputs['signals3'] ... inputs['labels1'], inputs['labels2']... in the screenshot above can be returned as a single entity/object from the define_graph() which has all multiple inputs and multiple labels information? 

Thank you

**Comment by JanuszL** [comment]
@piseabhijeet - not now. For that, you would need to develop custom operator that would assemble samples into a sequence. You can try to do it using [Python operator](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/python_operator/python_operator.html) or develop something faster [in C++](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/extend/create_a_custom_operator.html).

**Comment by piseabhijeet** [comment]
Hi Janusz,

Thank you for your prompt response once again.
I anticipated that. Also, when using a TF Estimator framework, i have to run the pipeline and convert the image, label pair to numpy arrays using '
![image](https://user-images.githubusercontent.com/57705684/68935259-58031880-07be-11ea-8d2f-51d89ff889fe.png)
' in dali_input_fn() which places the operations on CPU and then feeds the Estimator. Is there a better way of doing the same?
I need to test DALI's performance with tf.Data in my existing ML pipeline, hence the need.
I have referred to [https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/tensorflow/tensorflow-plugin-tutorial.html#Using-DALI-TensorFlow-plugin] but i do not want to run a separate session for fetching image, label pairs from daliop.

Thank you

**Comment by awolant** [comment]
Hi @piseabhijeet 

if I understand correctly, this above is what you are passing to `tf.Estimator` API as `input_fn`, right?

In that case, you can follow and modify example below:

```python
# Define train input fn
def train_data_fn():
     with tf.device('/gpu:0'):
         daliop = dali_tf.DALIIterator()
         images, labels = daliop(
             pipeline=pipe,
             shapes=shapes,
             dtypes=dtypes)
     return ({'images': images}, labels)

# Training like this:
model.train(input_fn=train_data_fn, steps=steps)
```

In my tests this code picked up the GPU instance of `daliop` and the buffers were allocated on the GPU. Remember about passing config similar to this:

```python
run_config = tf.estimator.RunConfig(
     device_fn=lambda op: '/gpu:0')
```

as the `config` to your estimator. This should ensure that everything lands on the GPU.

**Comment by piseabhijeet** [comment]
Hi Albert, 

Thank you for your response.
I will check the same and let you know.

Thank you

**Comment by piseabhijeet** [comment]
@awolant ,
Hi Albert,
So i tried the estimator thing and i managed to get the images and labels in a single tuple from define_graph()
![image](https://user-images.githubusercontent.com/57705684/69219927-e64e1480-0b99-11ea-9703-7b67de5a99e5.png)
So i tried running the input function:
![image](https://user-images.githubusercontent.com/57705684/69220038-1b5a6700-0b9a-11ea-88b6-888c5a1440fe.png)
But it gives a pipeline error.
So as you can see in shapes: the first one for images and second one for labels. When using images and labels as a single tuple from define_graph(), the shapes for images and labels would be different. How to overcome this?

Thank you

**Comment by JanuszL** [comment]
Hi,
The error you see is because you have run out of memory. The reason is that DALI creates one instance of ImageDecoder for every `i in range(FpsVideo*Seconds_Per_Label)`. We do it to separate the state of the operator for every input it process. In the case of the ImageDecoder that relays on nvJPEG, it needs to create a set of GPU and CPU buffers. Usually, the user has 1 or 2 ImageDecoders in their pipeline so it has not been a problem so far. To help in your case we would need to extract from the ImageDecoder a part that utilizes the most memory into one entity and leave only the state in the ImageDecoder. It is not a trivial change. I would put it into our backlog but I cannot promise any timeline when this going to be available.

**Comment by piseabhijeet** [comment]
@JanuszL 

Thank you for your response.
But when i do not include the label in define_graph() 'outputs'
![image](https://user-images.githubusercontent.com/57705684/69331171-53d17200-0c7a-11ea-849d-1283857ec05b.png)

and give only one shape for the images in the tuple
![image](https://user-images.githubusercontent.com/57705684/69331261-75caf480-0c7a-11ea-8224-65c11ad0e45d.png)

I am able to run the session fine. The labels are only (batch_size, 360) in size so i suppose it wouldn't take a lot of memory. Also I am using a 32GB GPU for running this pipeline.

Thank you

**Comment by JanuszL** [comment]
Indeed that is strange. Can you share some minimal repro I could run and see what is going on?

**Comment by piseabhijeet** [comment]
@JanuszL 


Here is the entire code: 
`
from nvidia.dali.pipeline import Pipeline
import nvidia.dali.ops as ops
import nvidia.dali.types as types
import nvidia.dali.tfrecord as tfrec
import numpy as np
import matplotlib.pyplot as plt

#step 1
#generate the index files for tfrecords
tf_record_files = [os.path.join(tfrecord, file) for file in os.listdir(tfrecord) if file.endswith('.tfrecords')]
idx_files = [os.path.join(idx_path, file) for file in os.listdir(idx_path) if file.endswith('.idx')]
idx_files.sort()
tf_record_files.sort()

class TFRecordPipeline(Pipeline):
    def __init__(self, batch_size, num_threads, device_id):
        super(TFRecordPipeline, self).__init__(batch_size,
                                         num_threads,
                                         device_id)
        self.feature_map = {}
        for idy in range(55):
            self.feature_map['frames' + str(idy)] = tfrec.FixedLenFeature((), tfrec.string, "")
        self.feature_map['label'] = tfrec.FixedLenFeature([360], tfrec.int64, 0)
        self.inputs = []
        self.input = ops.TFRecordReader(path = tf_record_files,
                                        index_path = idx_files, features = self.feature_map)
        self.decode = ops.ImageDecoder(device = "mixed", output_type = types.RGB)
        self.iter = 0

    def define_graph(self):
        inputs = self.input()
        outputs = []
        for i in range(55):
            images = self.decode(inputs["frames" + str(i)])
            outputs.append(images)
        labels = inputs['labels']
        outputs_tuple = tuple(outputs)
        return outputs

    def iter_setup(self):
        pass

batch_size = 5

pipe = TFRecordPipeline(batch_size=batch_size, num_threads=4, device_id = 0)
pipe.build()


#using the tf-plugin for compatibility with the estimator framework
import nvidia.dali.plugin.tf as dali_tf
shapes = [(5,55,360,640,3), (5,1,360)]
dtypes = [tf.float32, tf.float32]

def train_data_fn():
    daliop = dali_tf.DALIIterator()
    images = daliop(pipeline=pipe, shapes=shapes, dtypes=dtypes)
    return ({'images': images})
images_dict = train_data_fn()
sess = tf.Session()
sess.run(images_dict)
`


*Assumption: 1 tfrecord contains multiple frames (55, 360,640,3) from video sample and 1 label (1, 360) for all the 55 frames.
If batch size is 10 then shape of the input to model: (10, 55, 360, 640, 3) and label (10, 1, 360) or (10, 360)

**Comment by JanuszL** [comment]
@piseabhijeet - thanks, we will look into that.

**Comment by JanuszL** [comment]
With some fixes it works for me:
```
RAME_NUM = 55
class TFRecordPipeline(Pipeline):
    def __init__(self, batch_size, num_threads, device_id):
        super(TFRecordPipeline, self).__init__(batch_size,
                                         num_threads,
                                         device_id)
        self.feature_map = {}
        for idy in range(FRAME_NUM):
            self.feature_map['frames' + str(idy)] = tfrec.FixedLenFeature((), tfrec.string, "")
        self.feature_map['label'] = tfrec.FixedLenFeature([1], tfrec.int64,  -1)
        self.inputs = []
        self.input = ops.TFRecordReader(path = tf_record_files,
                                        index_path = idx_files, features = self.feature_map)
        self.decode = ops.ImageDecoder(device = "mixed", output_type = types.RGB)
        self.iter = 0

    def define_graph(self):
        inputs = self.input()
        outputs = []
        for i in range(FRAME_NUM):
            images = self.decode(inputs["frames" + str(i)])
            outputs.append(images)
        labels = inputs['label']
        outputs.append(labels.gpu())
        outputs_tuple = tuple(outputs)
        return outputs

    def iter_setup(self):
        pass

batch_size = 5

pipe = TFRecordPipeline(batch_size=batch_size, num_threads=4, device_id = 0)
pipe.build()


#using the tf-plugin for compatibility with the estimator framework
import nvidia.dali.plugin.tf as dali_tf
shapes = [(batch_size,853,1280,3) for _ in range(FRAME_NUM)] + [(5,1)]
dtypes = [tf.float32 for _ in range(FRAME_NUM)] + [tf.int64]

def train_data_fn():
    daliop = dali_tf.DALIIterator()
    images = daliop(pipeline=pipe, shapes=shapes, dtypes=dtypes)
    return ({'images': images})
images_dict = train_data_fn()

gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.333)
sess = tf.Session(config=tf.ConfigProto(gpu_options=gpu_options))
sess.run(images_dict)
```
I have changed the shapes and label types to one I artificially created but other than that it should work for you. I see that you pass (5,55,360,640,3), while it should be a shape per every output. Another thing is that you need to move labels to GPU as the reader is on the CPU.

**Comment by piseabhijeet** [comment]
Hi @JanuszL ,

Thank you for your prompt experimentation with this issue and the response. I shall try running the same with these inputs :)

**Comment by piseabhijeet** [comment]
Hi @JanuszL ,

What if i were to have one label for the entire frames in a single tfrecord?
As an example, the input to the model is (batch_size, no_of_frames, 853, 1280, 3) for features and (batch_size, 1, 360) for labels?

The example shared by you has 60 elements with each entity being different batch,
Thank you

**Comment by JanuszL** [comment]
As said before, currently you cannot have (batch_size, no_of_frames, 853, 1280, 3)  but (no_of_frames, batch_size, 853, 1280, 3) as each frame is a separate output from DALI. To make that happen you need to develop some operator that will assemble frames into a sequence. Regarding labels (batch_size, 1, 360)  should work fine without any additional change.

**Comment by piseabhijeet** [comment]
Thank you @JanuszL :)

**Comment by piseabhijeet** [comment]
Hi @JanuszL ,

So i got the Dali pipeline working for a single batch (1,no_of_frames,360,640,3) as of now instead of developing the custom operator to assemble the sequences.
When i compare the performance of Dali against the existing tf.Data workflow, the average no of examples processed by Dali is quite lower than the tf.Data for the same set of tfrecords.

Can you suggest a time profiling method for DALI to visualize on Tensorboard to analyze time taken for each operation in the TFRecordPipeline?

Thank you.

**Comment by JanuszL** [comment]
Hi,
Currently, we are not supporting Tensorboard. What you can do it to try to run Nvidia Profiler. In your particular use case, the main bottleneck is the fact that DALI creates number_of_frames of `ImageDecoder` instances which spawns own pool of threads and buffers. So it is very likely that those threads fight for the CPU time. We have a plan to rework `ImageDecoder` to have only one set of threads and buffer for the whole pipeline instance but no timeline is known when this functionality is available.

**Comment by piseabhijeet** [comment]
Hi @JanuszL ,
Thank you for your prompt response. The support helps (y)

**Comment by JanuszL** [comment]
@piseabhijeet -  I missed to write that it is the most likely cause base on my experience, still, I haven't profiled this code there could be a different bottleneck.

**Comment by piseabhijeet** [comment]
@JanuszL 
Thank you for highlighting the same (y)

**Comment by AshishSardana** [comment]
@piseabhijeet You can try using NSight Systems to profile the code and visualize to find the bottleneck.
An introductory video to profile the code is here - 
https://www.youtube.com/watch?v=m5He_FlhcRo&feature=youtu.be&t=1

**Comment by piseabhijeet** [comment]
@AshishSardana thank you for sharing the tool. It will be quite useful to me (y)
