### ISSUE TITLE
Can not use dali_tf.DALIIterator()

### ISSUE THREAD

**Issue by mingqizhang** [NVIDIA/DALI#1463]
I want to use dali for my segmentation project.
I follow the nvidia dali tutorials, now there's some problem for me.
my code as below:
`

    class ExternalSourcePipeline(Pipeline):
        def __init__(self, batch_size, num_threads, device, device_id):
            super(ExternalSourcePipeline, self).__init__(batch_size, 
                                                     num_threads, 
                                                     device_id) 
            self.input = ops.ExternalSource()
            self.input_mask = ops.ExternalSource()
            self.decode = ops.ImageDecoder(device = 'mixed', output_type = types.RGB)
            self.image_cmnp = ops.CropMirrorNormalize(device = device,
                                           output_dtype = types.FLOAT,
                                           output_layout = types.NHWC,
                                           image_type = types.RGB,
                                           mean = [0., 0., 0.],
                                           std = [1., 1., 1.])
        self.mask_cmnp = ops.CropMirrorNormalize(device = device,
                                           output_dtype = types.FLOAT,
                                           output_layout = types.NHWC,                                           
                                           image_type = types.GRAY,
                                           mean = [0., 0., 0.],
                                           std = [1., 1., 1.])
        self.augmentations["warpaffine"] = ops.WarpAffine(device = device,
                                                         matrix = [1.0, 0.0, 0.0, 0.0, 1.0, 0.0],
                                                         use_image_center = True,
                                                          interp_type = types.INTERP_LINEAR)
        self.augmentations["resize"] = ops.Resize(device = device, 
                                                 resize_longer = 256)
           
        self.cast = ops.Cast(device = device, dtype = types.UINT8)
        self.coin = ops.CoinFlip(probability=0.5)
        self.coin = ops.CoinFlip(probability=0.5)        
    def define_graph(self):
        rand = self.coin()
        self.jpegs = self.input()
        self.mask = self.input_mask()
        image, mask = self.decode([self.jpegs, self.mask])
        
        images, masks = self.augmentations["warpaffine"]([image, mask])
        images, masks = self.augmentations["resize"]([images, masks]) 
        
        images = self.image_cmnp(images, mirror = rand)
        masks = self.mask_cmnp(masks, mirror = rand)        
        images, masks = self.cast([images, masks])
        return (images, masks)
    
    def iter_setup(self):
        (images, masks) = iterator.next()
        self.feed_input(self.jpegs, images)
        self.feed_input(self.mask, masks)
`

the reslut is corret as below:
`
      
    pipe = ExternalSourcePipeline(batch_size=batch_size, num_threads=2, 
                                                           device="gpu",device_id=0)
    pipe.build()
    pipe_out = pipe.run()
    image_batch, mask_batch = pipe_out
    # image and mask have the same shape 
    show_image(image_batch.as_cpu())
    show_image(mask_batch.as_cpu())
`

But when I use tf, there's problem
`

    daliop = dali_tf.DALIIterator()
    pipe = ExternalSourcePipeline(batch_size=batch_size, 
                              num_threads=2, 
                              device="gpu",
                              device_id=0)

    with tf.device('/gpu:0'):
        images, masks = daliop(pipeline = pipe,
                          shapes = [(batch_size, 256, 256, 3), (batch_size, 256, 256, 3)],
                          dtypes = [tf.float32, tf.float32],
                          device_id=0)

    with tf.Session() as sess:
        images, masks = sess.run([images, masks])
`
error message:
RuntimeError: CHECK failed: IsInitialized(): Can't serialize message of type "dali_proto.PipelineDef" because it is missing required fields: op[0].name, op[1].name

So, how can I use dali in tf?

**Comment by JanuszL** [comment]
Hi,
The ExternalSource operator is not supported with tf.DALIIterator(). The reason is that DALI is executed as a TensorFlow node in such a case. To use ExternalSource `iter_setup` needs to be called to feed the ExternalSource, and that is not possible from the tf.DALIIterator().
Is there any particular reason why you need to use ExternalSource and cannot use any other reader available in DALI?

**Comment by mingqizhang** [comment]
In segmentation, my data are like
![0-0](https://user-images.githubusercontent.com/28778038/68860711-078bac80-0725-11ea-8b34-65a2947e7839.jpg)
![0-0_mask](https://user-images.githubusercontent.com/28778038/68860717-0a869d00-0725-11ea-8cbc-89002fd05415.jpg)
I need read these images and correspanding masks.The images and masks path are write in txt file like 
`

    1.jpg 1.png
    2.jpg 2.png
    3.jpg 3.png
    ...
` 
So could you please give an example to read these data, thanks a lot?

**Comment by JanuszL** [comment]
Hi,
You can have two FileReaders with the same seed and use a file list.
```
class ExternalSourcePipeline(Pipeline):
    def __init__(self, batch_size, num_threads, device, device_id):
        super(ExternalSourcePipeline, self).__init__(batch_size, 
                                                 num_threads, 
                                                 device_id) 
        self.input = ops.FileReader(file_root="xxx\data",file_list="data_list', seed=111,  random_shuffle=True)
        self.input_mask = ops.FileReader(file_root="xxx\masks",file_list="masks_list', seed=111, random_shuffle=True)

def define_graph(self):
    rand = self.coin()
    self.jpegs, _ = self.input()
    self.mask, __ = self.input_mask()
```
And file list could look like (as a label use some dummy value):
```
1.jpg 1
2.jpg 1
3.jpg 1
```

**Comment by mingqizhang** [comment]
Thanks for your reply.
Maybe I can use tfrecord to save my images and masks.
But , when I use ops.TFRecordReader, I have another problem. 


    from subprocess import call
    import os.path

    test_data_root = './tfrecord/'
    tfrecord = test_data_root + 'train.tfrecord'
    tfrecord_idx = test_data_root + "train.idx"
    tfrecord2idx_script = "tfrecord2idx"

    if not os.path.isfile(tfrecord_idx):
        call([tfrecord2idx_script, tfrecord, tfrecord_idx])

    class TFRecordPipeline(Pipeline):
        def __ini__(self, batch_size, num_threads, device_id):
            super(TFRecordPipeline, self).__init__(batch_size,
                                              num_threads,
                                              device_id)
            self.input = ops.TFRecordReader(path=tfrecord,
                                       index_path=tfrecord_idx,
                                       features={
                                           "image": tfrec.FixedLenFeature((), tfrec.string, ""),
                                           "mask": tfrec.FixedLenFeature((), tfrec.string, "")
                                       })
            self.decode = ops.ImageDecoder(device="mixed", output_type = types.RGB)
        
        def define_graph(self):
            inputs = self.input()
            images = self.decode(inputs["image"])
            masks = self.decode(inputs["mask"])
            return (images, masks)

    pipe = TFRecordPipeline(batch_size, 4, 0)
    pipe.build()

AttributeError: 'TFRecordPipeline' object has no attribute 'input'
How to solve this problem?

**Comment by JanuszL** [comment]
__ini__ -> __init__
