### ISSUE TITLE
AttributeError: module 'types' has no attribute 'RGB'

### ISSUE THREAD

**Issue by DecentMakeover** [NVIDIA/DALI#1470]

**Comment by JanuszL** [comment]
Hi,
Have you tried to run https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/augmentation_gallery.html?
What you get after issuing "pip show nvidia-dali"?

**Comment by JanuszL** [comment]
If it still doesn't work please reopen.
