### ISSUE TITLE
The data_dataloder will be empty, when I try to enumerate the dali_loader in the second time.

### ISSUE THREAD

**Issue by zhangchbin** [NVIDIA/DALI#1471]

**Comment by JanuszL** [comment]
Hi,
After each epoch you need to call [reset](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/plugins/pytorch_plugin_api.html#nvidia.dali.plugin.pytorch.DALIGenericIterator.reset) on the iterator or set the `auto_reset` to [true in it](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/plugins/pytorch_plugin_api.html#nvidia.dali.plugin.pytorch.DALIClassificationIterator).
