### ISSUE TITLE
Using Dali Pipeline on a GPU input

### ISSUE THREAD

**Issue by igolan89** [NVIDIA/DALI#1478]
Hi all,
I tried to figure out if there was a way, using Dali's Python API, to run the pipeline on data which is *already* located in the GPU.
The `feed_input` method of the pipeline seems to support only numpy arrays. It would be great to support GPU arrays such DLPacks.

**Comment by JanuszL** [comment]
Hi,
We know about that request but now we are pursuing other goals. If you want you can try to hack it on your own:
- utilize DLPack https://pytorch.org/docs/stable/dlpack.html and convert the tensor you have to it
- extend DALI's ExtrenalSource to unpack DLPacked data and handle data that is already at the GPU side.
- Python side needs to be adjusted to accept DLPack https://github.com/NVIDIA/DALI/blob/master/dali/python/nvidia/dali/pipeline.py#L311, the backend needs to have a dedicated code path similar to https://github.com/NVIDIA/DALI/blob/master/dali/python/backend_impl.cc#L742 for DLPack, and pipeline needs to be adjusted as well like https://github.com/NVIDIA/DALI/blob/master/dali/pipeline/pipeline.h#L141
- Then using something like https://github.com/NVIDIA/DALI/blob/master/dali/operators/python_function/dltensor_function.h#L37 DLPacked data needs to be transformed into DALI tensor internally inside ExternalSource https://github.com/NVIDIA/DALI/blob/master/dali/pipeline/operator/builtin/external_source.h#L144

We would be happy to review any code and provide a guidance if needed.

**Comment by uefall** [comment]
Hi @JanuszL 
I have a similar question that is can I reuse the DALI output of pipeline A as the input to feed pipeline B?
My purpose is to do a [decode] [detection] [classification] project, I have finished the first two step and now I need to crop object in original size decoded img according to my detection result, can I just return the decoded img and feed it to pipeline B as a ExternalSource?

another question is that with a batch of images ,could I input serveral crop positions for each image to crop out and resize norm to a new crop batch image?

thanks a lot.

**Comment by JanuszL** [comment]
Hi,
Yes, you can just pass the decoded image as the input to the ExternalSource as long as it is on the CPU. ExternalSource still doesn't support GPU inputs. However, the fastest solution would be probably to run the reader and the decoder in the second pipeline with the same seed as in the first one (reading and decoding would be probably faster than making this copy on the host but this is just my guess).
To input several crop positions - are you asking to provide different crop per each sample in the batch ([Slice operator](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html#nvidia.dali.ops.Slice) is the way), or you want to have several crops per each image (in that case you need to apply Slice operator multiple times and return the result as a separate output, still you need to know this number ahead - like what is the maximum number of objects you want to cut this way; another solution is to create some [custom operator](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/extend/create_a_custom_operator.html) that would produce a sequence of crops, but in this case, sequence length is common for the whole batch and you need to return the number of meaningful images in each sample).

**Comment by WANG-lp** [comment]
From [gpu_python_operator.ipynb](https://github.com/NVIDIA/DALI/blob/master/docs/examples/custom_operations/gpu_python_operator.ipynb), DALI is able to load DLPack from GPU memory. Am I right?

**Comment by JanuszL** [comment]
> From [gpu_python_operator.ipynb](https://github.com/NVIDIA/DALI/blob/master/docs/examples/custom_operations/gpu_python_operator.ipynb), DALI is able to load DLPack from GPU memory. Am I right?

You can write a GPU python function that uses DLPack and plug it to DALI. `ExternalSource` doesn't support DLPack yet, but GPU python function supports side effect and you can use some global state to pass values to it.

**Comment by JanuszL** [comment]
Hi,
https://github.com/NVIDIA/DALI/pull/2023 enabled support for GPU and CPU DLPack input to the ExternalSource.
It will be available in 0.24 or in nightly builds.

**Comment by JanuszL** [comment]
0.24 has been released. Please check if that works for you.
