### ISSUE TITLE
Protobuf_LIBRARY is not found

### ISSUE THREAD

**Issue by hubutui** [NVIDIA/DALI#1484]
`cmake` complains that `Protobuf_LIBRARY` is not found. I have to run with:
```shell
cmake \
    -DCMAKE_EXE_LINKER_FLAGS="$(pkg-config --libs protobuf)" \
    -DCMAKE_EXE_LINKER_FLAGS="$(pkg-config --libs protobuf)" \
    -DProtobuf_INCLUDE_DIR='/usr/include' \
    -DProtobuf_LIBRARY='/usr/lib' \
    ..
```
Any plan to fix this?

**Comment by JanuszL** [comment]
Hi,
We find protobuf using [this](https://github.com/NVIDIA/DALI/blob/master/cmake/modules/FindProtobuf.cmake) what is almost 1:1 copy of what [CMake provides](https://github.com/Kitware/CMake/blob/master/Modules/FindProtobuf.cmake) in the upstream.
It doesn't rely on pkg-config but on:
```
find_path(Protobuf_INCLUDE_DIR
    google/protobuf/service.h
    PATHS ${Protobuf_SRC_ROOT_FOLDER}/src
)

find_library(${name}_LIBRARY_RELEASE
  NAMES ${filename}
  PATHS ${Protobuf_SRC_ROOT_FOLDER}/vsprojects/${_PROTOBUF_ARCH_DIR}Release ${FIND_PATH_SELECTOR})
```
find_path and find_library have well-defined default search paths and this approach works in most of the cases.
If you have any PR that could improve the current process feel free to create on for DALI or even CMake itself.

**Comment by hubutui** [comment]
@JanuszL According to https://github.com/NVIDIA/DALI/blob/master/cmake/Dependencies.aarch64-linux.cmake#L62, you're using static libraries, any particular reason? I found the protobuf provided in ArchLinux have no `libprotobuf.a`.

**Comment by JanuszL** [comment]
DALI is distributed as a self-contained python wheel. We want to avoid external dependency as some users may not have the libprotobuf installed or have incompatible versions. Using the static one we get rid of this problem.

**Comment by hubutui** [comment]
Could we have an option to turn it on/off?

**Comment by JanuszL** [comment]
Here you go https://github.com/NVIDIA/DALI/blob/master/cmake/Dependencies.cmake#L92. Just `-DProtobuf_USE_STATIC_LIBS=NO` should do.

**Comment by hubutui** [comment]
@jantonguirao According to https://github.com/NVIDIA/DALI/blob/master/CMakeLists.txt#L77, it's for other platform, not aarch64-linux.

**Comment by JanuszL** [comment]
[ArchLinux](https://en.wikipedia.org/wiki/Arch_Linux) != [aarch64](https://en.wikipedia.org/?title=AArch64&redirect=no). If your ARM system doesn't have a static version of libprotobuf you can always fill a PR that makes DALI build more flexible on this platform.

**Comment by hubutui** [comment]
Oh, my mistake, I'll try with `-DProtobuf_USE_STATIC_LIBS=NO`.

**Comment by JanuszL** [comment]
If it still doesn't work please reopen.
