### ISSUE TITLE
how to quickly classify mp4 files?

### ISSUE THREAD

**Issue by PCerles** [NVIDIA/DALI#1488]
Hi, I'm working on a project to classify mp4 videos (between 10s and 30s) with a frame classifier. I want to sample a frame approximately every 1 second and feed it into a Tensorflow model. Right now, the fastest option is using ffmpeg:
`ffmpeg -flags2 fast -ss 0 -i in.mp4 -an  -vframes 30 -vf "fps=1,scale=224:224" -f image2 out/test_%09d.bmp`
And then running the BMPs through a tensorflow frozen graph. I have no control over the input video parameters. Is this something that might work faster through DALI?

**Comment by JanuszL** [comment]
Hi,
It should be doable as long as your videos have the same FPS. Then by setting sequence length (1 in your case), step and stride (number of frames that correspond to 1s) of the [VideoReader ](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html#nvidia.dali.ops.VideoReader)you should get what you want.
You can check out [this example](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/video/video_reader_label_example.html).
