### ISSUE TITLE
why the image readed from dali_tf.DALIIterator() are wrong?

### ISSUE THREAD

**Issue by MapleLeafInAutumn** [NVIDIA/DALI#149]
class TFRecordPipeline(Pipeline):
    def __init__(self,batch_size,num_threads,device_id,num_gpu=1):
        super(TFRecordPipeline,self).__init__(batch_size,
                                              num_threads,
                                              device_id)
        self.input = ops.TFRecordReader(wsi_tfrecord_train,
                                        wsi_index_train,
                                        random_shuffle=True,
                                        features={"image_raw":tfrec.FixedLenFeature((),tfrec.string,""),
                                                  "label":tfrec.FixedLenFeature([1],tfrec.int64,-1)})
        #self.decode = ops.HostDecoder(output_type=types.RGB)
        self.decode = ops.nvJPEGDecoder(device='mixed', output_type=types.RGB)
        #self.resize = ops.Resize(device="gpu",resize_shorter=256)
        self.cmn = ops.CropMirrorNormalize(device="gpu",
                                           output_dtype=types.FLOAT,
                                           crop=(227, 227),
                                           image_type=types.RGB,
                                           mean=[128., 128., 128.],
                                           std=[1., 1., 1.])

    def define_graph(self):
        inputs = self.input()
        images = inputs["image_raw"]
        labels = inputs["label"]
        decoded_images = self.decode(images)
        output = self.augmentations[0](decoded_images)
        #augemented_images = self.cmn(outputs, crop_pos_x=self.uniform(),
        #                                crop_pos_y=self.uniform())
        return output,labels.gpu()

def get_input():
    pipe = TFRecordPipeline(batch_size=batch_size, num_threads=1, device_id=0)
    serialized_pipe = pipe.serialize()
    dali_op = dali_tf.DALIIterator()
    images,labels = dali_op(serialized_pipe,batch_size=batch_size,width=128,height=128,device_id=0)
    return images,labels

def test_run():
    images,labels = get_input()
    sess = tf.Session()
    img = sess.run(images)
    plt.imshow(img[0].astype('uint8'))
    plt.show()

if __name__ == "__main__":
    test_run():

the original image is : 
![original](https://user-images.githubusercontent.com/39239249/45143501-12c47d80-b1ee-11e8-81c2-e403eba2ccff.jpg)

the output image is:
![output](https://user-images.githubusercontent.com/39239249/45143531-21ab3000-b1ee-11e8-8d03-200e5ef3c7d8.jpg)

**Comment by JanuszL** [comment]
Hi,
I have tested your code on Dali 0.2 release and it works good. My test code:
```
from __future__ import print_function
from nvidia.dali.pipeline import Pipeline
import nvidia.dali.ops as ops
import nvidia.dali.types as types
import nvidia.dali.tfrecord as tfrec
import glob
import nvidia.dali.plugin.tf as dali_tf
import tensorflow as tf
import matplotlib.pyplot as plt

BATCH_SIZE = 1
class TFRecordPipeline(Pipeline):
    def __init__(self,batch_size,num_threads,device_id,num_gpu=1):
        super(TFRecordPipeline,self).__init__(batch_size,
                                              num_threads,
                                              device_id)
        self.input = ops.FileReader(file_root = "XXXX")
        #self.decode = ops.HostDecoder(output_type=types.RGB)
        self.decode = ops.nvJPEGDecoder(device='mixed', output_type=types.RGB)
        #self.resize = ops.Resize(device="gpu",resize_shorter=256)
        self.cmn = ops.CropMirrorNormalize(device="gpu",
                                           output_dtype=types.FLOAT,
                                           crop=(227, 227),
                                           image_type=types.RGB,
                                           output_layout = types.NHWC,
                                           mean=[0., 0., 0.],
                                           std=[1., 1., 1.])
        self.uniform = ops.Uniform(range = (0.0, 1.0))

    def define_graph(self):
        images, labels = self.input()
        decoded_images = self.decode(images)
        image = self.cmn(decoded_images,
                          crop_pos_x = self.uniform(),
                          crop_pos_y = self.uniform())
        return (image, labels.gpu())

def get_input():
    pipe = TFRecordPipeline(batch_size=BATCH_SIZE, num_threads=1, device_id=0)
    serialized_pipe = pipe.serialize()
    dali_op = dali_tf.DALIIterator()
    images,labels = dali_op(serialized_pipe,
                            shape = [BATCH_SIZE, 227, 227, 3],
                            image_type = tf.float32,
                            label_type = tf.int64)
    return images, labels

from __future__ import division
import matplotlib.gridspec as gridspec
import matplotlib.pyplot as plt
%matplotlib inline

def test_run():
    images,labels = get_input()
    sess = tf.Session()
    img = sess.run(images)

    plt.imshow(img[0]/255.)
    plt.show()
    print ("OK")

if __name__ == "__main__":
    test_run()
```
I haven't used TFRecord as I got only access to file you posted here, but is output for other images looks reasonable. If it still doesn't work for you please provide or TFRecord or image itself which causes problems.

**Comment by ptrendx** [comment]
The default layout of the output of CropMirrorNormalize op is NCHW (which is the typical layout of input accepted by DL frameworks) and matplotlib expects HWC.
To visualize the output you would need to transpose the image. Alternatively, if output in NHWC format is what you want, please upgrade to DALI 0.2 which enables setting the full output shape in TF plugin instead of just width and height and add `output_layout=types.NHWC` argument to CropMirrorNormalize.

**Comment by JanuszL** [comment]
Closing. If issue is not solved please provide feedback and reopen.
