### ISSUE TITLE
Set output_layout N*C*H*W as output from Dali Pipeline

### ISSUE THREAD

**Issue by cristyioan2000** [NVIDIA/DALI#1490]
I want to reshape my image and bounding box output.
### This is my Piepeline:
```

class ExternalSourcePipeline(Pipeline):
    '''
        - Only GPU - 
        Support for:
            - Flip ( Image + BoundingBox)
            - ColorTwist [0.5 -> 1.50] range:
                - brightness
                - contrast
                - huse
                - saturation
    '''
    def __init__(self,batch_size,num_threads,device_id,external_data):
        super(ExternalSourcePipeline, self).__init__(batch_size,
                                                     seed=12,
                                                     device_id=0,
                                                     num_threads=2)
        self.image_input = ops.ExternalSource()
        self.input_bbox= ops.ExternalSource()
        self.decode = ops.ImageDecoder(device="mixed",output_type = types.RGB)
        self.cast = ops.Cast(device="gpu",dtype= types.INT32)
        self.castlbl = ops.Cast(device="gpu",dtype=types.FLOAT)
        self.flip = ops.Flip(device='gpu')
        self.bbflip = ops.BbFlip(device="gpu")
        self.color_twist = ops.ColorTwist(device="gpu")
        self.coin = ops.CoinFlip(probability=0.5)
        self.coin2 = ops.CoinFlip(probability =0.5)
        self.brightness_range = ops.Uniform(range=[0.5,1.50])
        self.contrast_range = ops.Uniform(range=[0.5,1.50])
        self.hue_range = ops.Uniform(range=[0.8,1.90])
        self.saturation_range = ops.Uniform(range=[0.5,1.50])
        self.external_data = external_data
        self.iterator = iter(self.external_data)

    def define_graph(self):
        #rng_1 = self.coin()
        rng_2 = self.coin2()
        brightness = self.brightness_range()
        contrast = self.contrast_range()
        hue = self.hue_range()
        saturation = self.saturation_range()

        self.jpegs = self.image_input()
        self.bounding_box = self.input_bbox()
        images = self.decode(self.jpegs)
        labels = self.castlbl(self.bounding_box.gpu())
        #labels = self.bboxencoder(labels)
        images = self.flip(images,horizontal=rng_2)
        images = self.color_twist(images,brightness=brightness,contrast=contrast,hue=hue,saturation=saturation)
        labels  = self.bbflip(labels ,horizontal=rng_2)
        output = self.cast(images)
        return(output,labels)
    def iter_setup(self):
        try:
            (images,labels) = self.iterator.next()
            self.feed_input(self.jpegs, images)
            self.feed_input(self.bounding_box, labels)
        except StopIteration:
            self.iterator = iter(self.external_data)
            raise StopIteration

```
If I copy to the cpu the output it has [W,H,C,N] format and I need [N,C,H,W]  format compatible with Pytorch. I need [N,C,H,W] format for images at the pieplene's output, also for the labels I need: [x,y,w,h,cls_id]. Do I need to use `Transpose` with `output_layout = 'CHW'` at the end of the graph of the pipeline ? What can I do for labels ?

**Comment by JanuszL** [comment]
Hi,
For the format conversion please use [crop operator](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html#cropmirrornormalize) without any cropping.
As for labels we don't provide any conversion operator between lrtb and xywh format, but [BbFlip operator ](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html#nvidia.dali.ops.BbFlip) support both thanks to `lrtb` switch. In the end, you may try to return bboxes and labels and use torch.cat to merge cls_ids with bboxes.

**Comment by cristyioan2000** [comment]
### For image format covnersion: 
```
self.format_conversion = CropMirrorNormalize(device="gpu",output_layout=types.NCHW)
# In the graph function
output = self.format_conversion(images)
```
It runs, but when I copy from GPU to CPU and check the shape with `image.shape` it's `WHC` format. My guess is that the shape, on the GPU after `CropMirrorNormalize`, is ` NCHW` and when i copy it to the CPU it's `WHC` but on the GPU it's `NCHW`, am I right ? 
### For the label conversion:
For the label conversion I need to copy from GPU to CPU and format my bboxes and `torch.cat` with cls_ids, and after the format is done on the CPU move it back to GPU and pass it to the neural network ?

**Comment by JanuszL** [comment]
You can keep the labels and bboxes on the CPU all the time. I though `torch.cat` should work for GPU tensors but I'm not 100% sure.

**Comment by cristyioan2000** [comment]
Where `bboxes`, `labels` are `nvidia.dali.backend_impl.TensorListGPU`

```
images,bboxes,labels = next(batch_iterator)
concat = torch.cat((bboxes,labels))
```

`TypeError: expected Tensor as element 0 in argument 0, but got nvidia.dali.backend_impl.TensorListGPU
`

I tried `torch.cat([gpu_tensor_1,gpu_tensor_2])` and it works, where `gpu_tensor_1` and `2` are cuda tensors.

I tried  `nvidia.dali.plugin.pytorch.feed_ndarray(dali_tensor, arr)` to copy from DALI tensor to Pytorch GPU Tensor so I can use torch.cat on GPU but I get this error:    
```
batch_iterator = DaliCustomIterator(nvidia_pipe)
images,bboxes,labels = next(batch_iterator)

bboxes_gpu_tensor = torch.Tensor([])
labels_gpu_tensor = torch.Tensor([])

bboxes_gpu_tensor.cuda()
labels_gpu_tensor.cuda()

feed_ndarray(dali_tensor=bboxes,arr=bboxes_gpu_tensor)
```
```
assert dali_tensor.shape() == list(arr.size()), \
AttributeError: 'nvidia.dali.backend_impl.TensorListGPU' object has no attribute 'shape'
```
Did i misused `feed_ndarray` ?

**Comment by JanuszL** [comment]
`feed_ndarray` expects that all elements are uniform in shape and can be represented as one big tensor.  bboxes and labels size differs sample to sample so it cannot be easily represented as one tensor (no matter if DALI or PyTorch).
`BoxEncoder` may be a valid solution as long as your network expects that kind of input.
Another thing that comes to my mind is you can call [`as_reshaped_tensor`](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/api.html#nvidia.dali.backend.TensorListGPU.as_reshaped_tensor) because your bboxes and labels are just 4xN and 1xN respectively tensors. So to use it first iterate over samples in to learn how many bboxes and labels you have in total, call `as_reshaped_tensor` with proper shapes and then `feed_ndarray` should work.

**Comment by cristyioan2000** [comment]
My network expects labels like this: `bbox[x,y,w,h,id]`, so using torch.cat or getting labels and bboxes together is a must.
I tried using [BoxEncoder](BoxEncoder):
`bboxes,labels = self.bbox_encoder(anchors=[bboxes,labels])`, where `bboxes,labels` are lists containing numpy arrays.
But it returns me this error:
`ValueError: Operator BoxEncoder expects [2, 2] inputs, but received 0`

And for your [as_reshaped_tensor](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html#nvidia.dali.ops.BoxEncoder) idea, I must find the N dimension in the 4xN and 1xN tensors and call `reshaped_tensor = as_reshaped_tensor(N)` and after that, `feed_ndarray(tensor_1,feed_ndarray)` ?

**Comment by cristyioan2000** [comment]
If I use `target = self.bbox_encoder(bboxes,labels)` I have no error in the graph, but it crashes on `.build`:
 ```
output = self.cast(images)
target = self.encode_labels(bboxes,labels)
return(output,target)
    Error: .format(type(output).__name__)
TypeError: Expected outputs of type EdgeReference. Received output type list
```

**Comment by JanuszL** [comment]
Hi,
You can check how to use `bbox_encoder` [here](https://github.com/NVIDIA/DALI/blob/master/docs/examples/pytorch/single_stage_detector/src/coco_pipeline.py).
Regarding `as_reshaped_tensor` you need to provide full shape, like `as_reshaped_tensor([4, N])`.
Regarding the last error you see does it come from `feed_input`?

**Comment by cristyioan2000** [comment]
Don't think so
```

Traceback (most recent call lasTraceback (most recent call last):
  File "/media/cfatu/HDD2/Nvidia_DALI/code/external_source.py", line 192, in <module>
    nvidia_pipe.build()
  File "/home/cfatu/anaconda3/envs/dali/lib/python3.7/site-packages/nvidia/dali/pipeline.py", line 311, in build
    self._prepare_graph()
Traceback (most recent call lasTraceback (most recent call last):
  File "/media/cfatu/HDD2/Nvidia_DALI/code/external_source.py", line 192, in <module>
    nvidia_pipe.bu```

  File "/home/cfatu/anaconda3/envs/dali/lib/python3.7/site-packages/nvidia/dali/pipeline.py", line 252, in _prepare_graph
    .format(type(output).__name__)
TypeError: Expected outputs of type EdgeReference. Received output type listt):
  File "/media/cfatu/HDD2/Nvidia_DALI/code/external_source.py", line 192, in <module>
    nvidia_pipe.build()
  File "/home/cfatu/anaconda3/envs/dali/lib/python3.7/site-packages/nvidia/dali/pipeline.py", line 311, in build
    self._prepare_graph()
  File "/home/cfatu/anaconda3/envs/dali/lib/python3.7/site-packages/nvidia/dali/pipeline.py", line 252, in _prepare_graph
    .format(type(output).__name__)
TypeError: Expected outputs of type EdgeReference. Received output type list
```

```

**Comment by cristyioan2000** [comment]
If I change the encoding in the graph with this:
 `bboxes,labels = self.encode_labels(bboxes,labels)`

 there is another crash message:
` RuntimeError: [/opt/dali/dali/pipeline/operators/op_schema.cc:60] Not all required arguments were specified for op "BoxEncoder". Please specify values for arguments: "anchors".`

**Comment by JanuszL** [comment]
Regarding the first crash:
```
return(output,target)
```
The whole output should be a single output from operator, tuple or list. In your case, it seems that `output` or `target` are lists themselves.
Ad `RuntimeError: [/opt/dali/dali/pipeline/operators/op_schema.cc:60] Not all required arguments were specified for op "BoxEncoder". Please specify values for arguments: "anchors".` you need to provide anchors to bbox_encoder. For COCO you can generate them [like this](https://github.com/NVIDIA/DALI/blob/master/docs/examples/pytorch/single_stage_detector/src/utils.py#L273).

**Comment by cristyioan2000** [comment]
I will do all the bbox and labels operations on CPU, after they exit the pipeline i will unpack them with `.at(index)`. For the images that are the output of the pipeline, they are `nvidia.dali.backend.GPU` objects, what I need to do so I can pass the images to Pytorch neural network without using a Dali Iterator, and keep them on GPU ?

**Comment by JanuszL** [comment]
If you want to keep images on the GPU and pass them to PyTorch please create empty GPU tensor with required shape and then call `[feed_ndarray`](https://github.com/NVIDIA/DALI/blob/master/dali/python/nvidia/dali/plugin/pytorch.py#L39) on it, like [here](https://github.com/NVIDIA/DALI/blob/master/dali/python/nvidia/dali/plugin/pytorch.py#L209).

**Comment by cristyioan2000** [comment]
I unpacked every item from the batch given from Dali pipeline and moved it on a list.
```
import torch
from coco_pipeline import *
class DaliCustomIterator(object):
    def __init__(self,pipeline = None,device = None,batch_size=None):
        self.pipeline = pipeline
        self.batch_size = batch_size
        ''' Building NvidiaPipeline '''
        self.tensor_list = []
        self.pipeline.build()
        #self.empty_tensor = torch.Tensor([])
    def _copy_to_tensor(self,dali_image_tensor):
        '''
            Create a tensor of image size
            Foreach dali object unpack it and copy the content to a gpu_tensor location
       '''

        for index in range(self.batch_size):
            tensor_shape = dali_image_tensor.at(index).shape()
            # Empty tensor to copy the dali data to
            self.tensor_list.append(torch.zeros(tensor_shape).cuda())
            feed_ndarray(dali_image_tensor.at(index),self.tensor_list[index])
    def __iter__(self):
        return self
    def __next__(self):
        output = self.pipeline.run()
        self._copy_to_tensor(dali_image_tensor=output[0])
        return output[0],output[1],output[2]
```
It seems to work, lastly, I need to make a batch with all the items from `self.tensor_list[index]` how can I do that ? Or is it better to make the batch while unpacking and store it directly to a tensor:             `feed_ndarray(dali_image_tensor.at(index),self.tensor_list[index])`

**Comment by JanuszL** [comment]
If you images are uniform across the batch you can do just:
```
dali_image_tensor = dali_image_tensor.as_tensor()
tensor_shape = dali_image_tensor.shape()
self.tensor_image = torch.zeros(tensor_shape).cuda()
feed_ndarray(dali_image_tensor, self.tensor_image)
```
If they are not uniform you cannot do a batch from all of them, as a batch is a [batch_size, w, h, c] tensor. If w, h or c differs sample to sample you cannot merge them together.

**Comment by cristyioan2000** [comment]
If the size of the image samples is different can I resize them(with an operator) or use `Paste `operator so I have `[w,h]` the same at each sample and merge them as a tensor ?  If yes, can I make a tensor with all my batch samples without iterating through the DALI tensor and feed it directly to the neural network with this line : `feed_ndarray(dali_image_tensor, self.tensor_image), return(tensor_image)` ?

**Comment by JanuszL** [comment]
I would recommend the resize. And yes, then one `feed_ndarray` call should suffice.
