### ISSUE TITLE
Error on BbFlip

### ISSUE THREAD

**Issue by alphinside** [NVIDIA/DALI#1501]
Hi guys, so I'm a bit confused on using Bbflip operation. My Pipeline looked like this 

`class DALIPipeline(Pipeline):
    def __init__(self,
                 base_iterator,
                 batch_size: int,
                 num_gpus: int = 1,
                 device_id: int = 0,
                 num_threads: int = 1,
                 shuffle: bool = True,
                 dali_transform: dict = None,
                 exec_async=True,
                 exec_pipelined=True
                 ):
        super(DALIPipeline, self).__init__(batch_size,
                                             num_threads,
                                             device_id,
                                             exec_async=exec_async,
                                             exec_pipelined=exec_pipelined,
                                             seed=12)
        self.input_dict = dict()
        self._external_input_iterator = ExternalInputIterator(base_iterator,
                                                              batch_size=batch_size,
                                                              device_id=device_id,
                                                              num_gpus=num_gpus,
                                                              shuffle=shuffle)
        self.data_keys = self._external_input_iterator.data_keys
        for key in self.data_keys:
            self.input_dict[key] = ops.ExternalSource()
        self.decode = ops.ImageDecoder(device="mixed", output_type=types.BGR)
        self.dali_transform = dali_transform
        self.iterator = iter(self._external_input_iterator)

    def define_graph(self):
        self.labels = dict()
        for key_idx, key in enumerate(self.data_keys):
            if key_idx == 0:
                self.jpegs = self.input_dict[key]()
            else:
                self.labels[key] = self.input_dict[key]()
        images = self.decode(self.jpegs)
        labels = self.labels
        if self.dali_transform:
            images, labels = self.dali_transform(images, labels)
        output = (images,)
        labels = tuple(labels[key] for key in labels.keys())
        return output+labels

    def iter_setup(self):
        try:
            data_tuple = self.iterator.next()
            for data_idx, data in enumerate(data_tuple):
                if data_idx == 0:
                    self.feed_input(self.jpegs, data)
                else:
                    self.feed_input(
                        self.labels[self.data_keys[data_idx]], data)
        except StopIteration:
            self.iterator = iter(self._external_input_iterator)
            raise StopIteration`

In short, I'm trying to make a kind of flexible iterator and pipeline for object detection and image classification. So i'm creating a dictionary with 'image' key to handle image data, and the other keys to handle any additional labels. To simplify process, I'm creating a new object class to handle the augmentation part as an object in self.dali_transform which looked like this :

`class GraphCompose(DALICompose):
    def __init__(self):
        self.brightness = ops.Brightness(device="gpu", brightness=.5)
        self.bbflip = ops.BbFlip(device='cpu', horizontal=1, ltrb=True)

    def __call__(self, images, labels):
        images = self.brightness(images)
        labels['bboxes'] = self.bbflip(labels['bboxes'])
        return images, labels`

however when I added bbflip it raise error like this : 
`Assert on "source != nullptr" failed: Input name 'BbFlip_id_5_output_0' is not marked as an external input.`
Any hint where do i did wrong? if I add only image augmentation it went fine

**Comment by JanuszL** [comment]
Hi,
I believe this line is a problem:
```
labels['bboxes'] = self.bbflip(labels['bboxes'])
```
Before calling that line `labels['bboxes']` houses the output (edge reference) from `self.input_dict[key]()`, and it is something you can call `feed_input` on. But when you can `self.bbflip(labels['bboxes'])`, and `labels['bboxes']` houses the output from `bblifp` and you are not allowed to call `feed_input` on this one. What I can suggest is to avoid overriding the output of `self.input_dict[key]()` by the output of any other operator.

**Comment by alphinside** [comment]
Ah I see thank you very much!! @JanuszL
