### ISSUE TITLE
Does Nvidia Dali support dynamic image size ? 

### ISSUE THREAD

**Issue by cristyioan2000** [NVIDIA/DALI#1505]
Hi,
1. I want to know if Nvidia Dali supports batches with images of different size (in a batch there are images with multiple dimensions Ex 520x300,240x180 etc. ).
2. Does COCO Iterator supports bounding boxes with dynamic shape ? I observed that the limitation of the most of the Iterators is the need for the Tensors to be dense, what can I use for that kind of bbox dynamic shape in a batch ? 
3. Is there a way to rescale an image to [416x240] and keeping aspect ratio and the bounding boxes ?

**Comment by JanuszL** [comment]
Hi,
1) Yes. It does. ImageNet is the best example of images of different sizes.
However, if you want to use a framework iterator at the output sizes needs to be unified so one tensor per batch can be created. If you want to have different sizes at the end then you cannot use framework iterator, and just use `pipeline.run()` and manually extract sample after sample.
2) Currently not. Still, there is some custom example available [here](https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/Detection/SSD/src/coco_pipeline.py#L117) how you can create own DALI iterator.
3) If you keep your bounding boxes in the relative coordinates (0-1), then any rescale is transparent.

**Comment by cristyioan2000** [comment]
I am sorry if I wasn't very clear with the question 2. I meant by dynamic shape different number of bounding boxes in each sample of the batch. Is the answer for this still no ?

**Comment by JanuszL** [comment]
> I am sorry if I wasn't very clear with the question 2. I meant by dynamic shape different number of bounding boxes in each sample of the batch. Is the answer for this still no ?

DALI framework iterators don't support that case. It is required that samples are uniform across the batch. Given examples is a try to make it possible for the COCO.
If you just call `pipeline.run()` then there is no limitation. But you need to access sample by sample.
