### ISSUE TITLE
Pad to square?

### ISSUE THREAD

**Issue by alphinside** [NVIDIA/DALI#1509]
Hi, any idea on how to pad image to square? the example on retinanet dali sadly didn't solve this

**Comment by alphinside** [comment]
Well actually min canvas size solved the pad to square problem, but the parameter doesn't exist in the BboxPaste operator so the bounding box is broken

**Comment by JanuszL** [comment]
Hi,

@alphinside - I don't think BboxPaste needs this parameter as it operates on the relative coordinates. So no matter what image size (in pixels) the Paste operator will produce the bounding boxes coordinates expressed as a value in the range (0-1) are still valid.

**Comment by JanuszL** [comment]
BTW - we plan to extend crop operators to support padding (when the image is smaller than the crop it should pad). If you want you can try to implement this on your own and issue a PR.
The other thing is to implement a crop operator for BBoxes and we don't have such a plan now.

**Comment by alphinside** [comment]
Actually relative coordinates rely on the actual width and height before padding, except if the padding is using the same ratio. However if we want to pad using minimum canvas, the ration information is lost because the aspect ratio is changing thus it will broke the bbox. I'll give some visualization later. Currently to make a way around of this, i capture the original size using ops.Shape before padding so it will maintain the original shape. Thank you very much for the information

**Comment by JanuszL** [comment]
@alphinside - I have checked code again and you are right. Sorry for the confusion.

**Comment by fengyuentau** [comment]
Hi, any updates on padding each image in a batch to its longer edge to make it square? I read this issue and the documentation of `ops.Pad` and `ops.Paste`. It seems DALI does not directly support this feature yet?

**Comment by JanuszL** [comment]
> Hi, any updates on padding each image in a batch to its longer edge to make it square? I read this issue and the documentation of `ops.Pad` and `ops.Paste`. It seems DALI does not directly support this feature yet?

Not yet, we plan to add a way to do that. We will get back to you once it is done.

**Comment by FlorentMeyer** [comment]
Looking forward such an `ops` too!

**Comment by jantonguirao** [comment]
@fengyuentau I am pleased to announce that you can now easily pad to a square. The functionality should be available in our next nightly build.

You can easily pad to a square with something like this in your pipeline (note that I am using the functional API, `dali.fn`):
```
shapes = fn.shapes(images, dtype=types.INT64)
h = fn.slice(in_shape, 0, 1, axes = [0])
w = fn.slice(in_shape, 1, 1, axes = [0])
side = math.max(h, w)
out_images = fn.pad(images, axis_names="HW", shape=fn.cat(side, side, axis=0))
``` 

@FlorentMeyer the issue was that Pad operator accepted fixed window dimensions, so you could not make the dimensions depend on your input. Now you can do that, as I show in the example above.
