### ISSUE TITLE
Question about random bboxcrop

### ISSUE THREAD

**Issue by alphinside** [NVIDIA/DALI#1512]
Hi, I have another question regarding randombboxcrop thresholds work. Does it calculate all nms of all bboxes compared to the prospective crop, or only bboxes in the edges of the crop only?

For example if I use threshold of 0.1 it will not crop if it didnt find any prospective crop which doesnt eliminate any of bboxes?

Thank you for the help

**Comment by JanuszL** [comment]
Hi,
You can check the [code](https://github.com/NVIDIA/DALI/blob/master/dali/operators/crop/bbox_crop.h#L198). So it does up to `num_attempts` to find a crop (randomly selected) where the aspect ratio is inside the provide boundaries, then IntersectionOverUnion for all bboxes for proposed crop is calculated and compared with the threshold (each bbox need to match the threshold), at the end bboxes which centroid is outside the crop area are removed.
If I understand correctly:
> For example if I use threshold of 0.1 it will not crop if it didnt find any prospective crop which doesnt eliminate any of bboxes?

It will not crop if IoU for the selected crop for any bbox doesn't meet the threshold.
Does that answer your question?

**Comment by alphinside** [comment]
Thank you very much @JanuszL
