### ISSUE TITLE
`source_info` of `tensor` lost

### ISSUE THREAD

**Issue by llhuii** [NVIDIA/DALI#1513]
When I ran the code below, It was expected to get right image name:
```cpp
pipe.AddOperator(
            OpSpec("FileReader")
                    .AddArg("file_root", "images")
                    .AddArg("file_list", "image_list.txt")
                    .AddOutput("images", "cpu")
                    .AddOutput("labels", "cpu"), "FileReader");
outputs = {{"images",              "cpu"},
                {"labels",        "cpu"}};
pipe.Outputs(&ws);
auto &image = ws.Output<CPUBackend>(0);
std::cout << "first image name " + image.GetSourceInfo(0);

```

I set breakpoint in FileReader `file_reader_op.h`source code, I could get the image name.

After diving into the code, the framework add a `MakeContiguous` operator.
So I added ` output.SetSourceInfo(i, input.GetSourceInfo());` into `make_contiguous.h`
```cpp
    if (ws->OutputIsType<CPUBackend>(0)) {
      auto &output = ws->Output<CPUBackend>(0);
      output.Resize(output_shape);
      output.SetLayout(layout);
      output.set_type(type);

      for (int i = 0; i < batch_size_; ++i) {
        auto &input = ws->Input<CPUBackend>(0, i);
        output.SetSourceInfo(i, input.GetSourceInfo());
```
It worked.
Same way to fix in `else branch of make_contiguous.h` if I changed the device of  `images` to `gpu`.

**Comment by JanuszL** [comment]
Hi,
`GetSourceInfo` was mostly developed with the decoder operator in mind to provide meaningful error messages when it fails with a hint which file caused it. We didn't extend it beyond this case as some operators may accept more than one input and produce only one output - then the question arises, which SourceInfo should be used in the output.
Still, we would be happy to review any PR with improvements to this functionality. The only thing I want to ask first is some thorough think through of this idea first, with consideration of all edge cases, and listing all of the pros and cons It would probably require extending Python API to allow extract this data from the pipeline output. If we limit this feature to the C++ code it may be not very useful after all.

**Comment by llhuii** [comment]
Hi
I think this issue may only apply the `MakeContiguous` operator which just accepts one input and one output, so it does not have the question that you said
```
We didn't extend it beyond this case as some operators may accept more than one input and produce only one output - then the question arises, which SourceInfo should be used in the output.
```


And `tensort.meta_`  has the fields `layout_` and `source_info_`, why does`MakeContiguous` copy `layout_` , but not `source_info_`?

**Comment by JanuszL** [comment]
Hi,
As I said, it was added to improve the decoder error message, so we didn't consider other use cases, including `MakeContiguous`. Still, feel free to add a PR that will extend `MakeContiguous`.

**Comment by JanuszL** [comment]
https://github.com/NVIDIA/DALI/pull/4518 should address this.
