### ISSUE TITLE
Does it support lighting augmentation?

### ISSUE THREAD

**Issue by Fangyh09** [NVIDIA/DALI#1526]
Hello, does it support lighting augmentation?

**Comment by JanuszL** [comment]
Hi,
If you are asking about something like [MXNet provides](https://github.com/apache/incubator-mxnet/blob/master/src/operator/image/image_random-inl.h#L1000) we don't have a dedicated operator like that. It should be easy to develop one, you can look into Hsv operator [here](https://github.com/NVIDIA/DALI/blob/master/dali/operators/color/hsv.h) and [here](https://github.com/NVIDIA/DALI/blob/master/dali/kernels/imgproc/pointwise/linear_transformation_cpu.h). In this case operator needs to prepare only the additive part of a linear transformation.
Another solution, that can be some workaround for you is to use arithmetic operators we just introduced [recently](https://docs.nvidia.com/deeplearning/sdk/dali-master-branch-user-guide/docs/examples/expressions.html?highlight=arithmetic), generate the transformation matrix on your own and load to DALI pipeline using [the ExternalSource operator](https://docs.nvidia.com/deeplearning/sdk/dali-master-branch-user-guide/docs/examples/external_input.html) and then just sum the target image with loaded coefficients (the only limitation is that you need the target image size to load appropriate coefficient matrix).

**Comment by Fangyh09** [comment]
Does rithmetic operators support GPU?

**Comment by JanuszL** [comment]
Yes. It does. It even accepts input at the GPU and CPU side in one expression execute it on the GPU.

**Comment by Fangyh09** [comment]
However, it seems the output is a list instead of an array.  So I have to iterate the list one by one?
My code:
```python
def depth_to_tensor(tensor):
    out_tensor = tensor / 255.0 * 10.0
    return out_tensor

# In my pipeline
self.depth_to_tensor = ops.DLTensorPythonFunction(function=depth_to_tensor, device=dali_device, num_outputs=1)
   
```
And it gave:
```
RuntimeError: Critical error in pipeline: DLTensorPythonFunction error: TypeError: unsupported operand type(s) for /: 'list' and 'float'
```

**Comment by Fangyh09** [comment]
I am sure that it is an array. I will try again.
Thanks for this amazing tool!

**Comment by JanuszL** [comment]
Hi,
We don't have a good example of how DLTensorPythonFunction works but you can check [its test](https://github.com/NVIDIA/DALI/blob/master/dali/test/python/test_dltensor_operator.py).
`simple_pytorch_op` operates on PyTorch tensors, `pytorch_adapter` obtains DLPacks and creates a PyTorch tensor from it. As a `function` to `DLTensorPythonFunction` is passed `lambda in1, in2: pytorch_adapter(fun, in1, in2)`, where fun is `simple_pytorch_op` or any other function.

**Comment by Fangyh09** [comment]
Hi, I have implemented it.
But it does not bring speed improvement.  What are the possible reasons?

**Comment by JanuszL** [comment]
Hi,
If you are using `DLTensorPythonFunction` then the performance is expected to be inferior as this code is called back in Python from the DALI pipeline. Another reason is that you are not a CPU bottlenecked. You can read more on how to asses that in our [RN50 case study blog post](https://devblogs.nvidia.com/case-study-resnet50-dali/) - you need to check the performance with the synthetic data pipeline, a dummy tensor in your case.

**Comment by JanuszL** [comment]
Hi @Fangyh09,

There are more ways to [support external operations now](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/custom_operations/index.html). You can use either CuPy or Numba GPU function to apply the desired transformation. Also thanks to enabling full asynchronously for the Python functions, the `DLTensorPythonFuncion` should impose less overhead on the whole pipeline.
