### ISSUE TITLE
Dose DALI's performance depend on network

### ISSUE THREAD

**Issue by PoonKinWang** [NVIDIA/DALI#1537]
My program run slower since the network was not available. Meanwhile, I only read image with DALI, the speed became lower, and the GPU-Util nearly reached 100%. So, I wonder that whether DALI would search efficient algorithms on network like the auto-tuner of cuDNN? If not, how to address this problem?

**Comment by JanuszL** [comment]
Hi,
Now DALI uses a statically predefined graph regarding the operations and the placement on the execution device (CPU or GPU).
What can be done to create a copy of each operator for CPU and GPU and then dynamically switch between different implementations according to the GPU utilization. The downside is that it may significantly increase memory consumption (DALI would keep buffers preallocated on both CPU and GPU).
Regarding heuristics, it is possible to make a few automatic tries to select the best placement of operators on the CPU and GPU but I'm not sure how accurate it would be in the long run. As performance varies depending on data it processes, for smaller images it may pay off to do more work on the CPU, for bigger ones on the GPU, and taking into account data shuffling it is hard to set something ahead that has the best performance through the whole training.
If you have any thoughts about this problem feel free to share.

**Comment by PoonKinWang** [comment]
> Hi,
> Now DALI uses a statically predefined graph regarding the operations and the placement on the execution device (CPU or GPU).
> What can be done to create a copy of each operator for CPU and GPU and then dynamically switch between different implementations according to the GPU utilization. The downside is that it may significantly increase memory consumption (DALI would keep buffers preallocated on both CPU and GPU).
> Regarding heuristics, it is possible to make a few automatic tries to select the best placement of operators on the CPU and GPU but I'm not sure how accurate it would be in the long run. As performance varies depending on data it processes, for smaller images it may pay off to do more work on the CPU, for bigger ones on the GPU, and taking into account data shuffling it is hard to set something ahead that has the best performance through the whole training.
> If you have any thoughts about this problem feel free to share.

Thanks for your reply. 
I used DALI to read imagenet (batch_size=256, num_threads=12, 2080ti), and it just taking up about 15% of the GPU-util. But now it takes up almost 100% of the GPU-util and performs very slow (the processing speed have decreased by 6 times). Can you give me some advises to find the cause?

**Comment by JanuszL** [comment]
> Thanks for your reply.
> I have to apologize for my careless. I have found the cause that one of the current leads of GPU is broken, because I noticed that the pwd was very low and the util was very high.

No problem, even if in your particular case it is a broken GPU, still the questions has its merits. If you or anyone else have any good idea how to tackle this challenge we would be more than happy to hear any suggestions.
