### ISSUE TITLE
Using as_reshaped tensor

### ISSUE THREAD

**Issue by cristyioan2000** [NVIDIA/DALI#1545]
Hi,
I am trying to use Nvidia DALI framework pipeline to train a neural network for detection. I have some problems with the labels, the labels consists of:  

### 1. bounding boxes 

Bounding boxes with the shape of `[4xN]`, where 4 represents the coords of the bounding box, `N` represents the number of bounding boxes in a image
### 2. Labels (int that describes which class it is)
The labels have a shape of `[1xN]`, where 1 is the class and `N` the number of labels found in a image

### The problem
The problem is that I can't collate the tensors because they are not dense. I want to stack them all in a single batch, so my shape of `bbox = [64x4xN]`, where 64 is the batch size. `label = [64x1xN]`.
How can I collate these 2 tensors in a `[64x5xN]` tensor ? where 5 is `[coords of bbox,label]`.
Or at least how can I concatenate a sample from the batch to have the bbox and label in one tensor `[1x5xN]` ?

I tried `output[1].as_reshaped_tensor([4,7])` and it yields this error: `RuntimeError: [/opt/dali/dali/pipeline/data/tensor.h:345] Assert on "product == volume(new_shape)" failed: Requested shape need to have the same volume as the tensor list.`
As I see the arguments for` as_reshaped_tensor()` is a list of the dimensions of every label in a batch and the column number, so if I have 443 labels in a batch my label `as_reshaped_tensor()` will look like this, `output[1].as_reshaped_tensor([443,1])` and it works. I did the same for bounding boxes and i used torch.cat to concatenate the tensors so my final tensor looks like this `[443,5]`.

**Comment by cristyioan2000** [comment]
``

**Comment by cristyioan2000** [comment]
One more question, how can I pass the integer that holds the labels count from the pipeline to the iterator ?

**Comment by JanuszL** [comment]
> As I see the arguments for as_reshaped_tensor() is a list of the dimensions of every label in a batch and the column number, so if I have 443 labels in a batch my label as_reshaped_tensor() will look like this, output[1].as_reshaped_tensor([443,1]) and it works. I did the same for bounding boxes and i used torch.cat to concatenate the tensors so my final tensor looks like this [443,5].

So I assume you managed to do what you originally wanted.

Regarding:
>One more question, how can I pass the integer that holds the labels count from the pipeline to the iterator 

I afraid you need to create a custom iterator to do that. Now it is not supported.

**Comment by cristyioan2000** [comment]
I am using a Custom Iterator already, it's unclear if I can send an integer(as an EdgeReference I guess) as an output from the ExternalPipeline and decode it to an integer ?

Another solution would be to add the number as a tensor to the label first row and decode it as an output.

**Comment by JanuszL** [comment]
`EdgeReference` is an entity existing inside the `define_graph` method which expresses an edge of the data processing graph. Iterator is a thing that runs the pipeline and obtains the output from it.
The number of labels can be easily obtained as a shape of Tensors returned by DALI so I don't think you need to pass any additional information from the inside of the graph. If you like to you can feed ExternalSource with that value perf each sample and then use it as any other output from DALI.

**Comment by cristyioan2000** [comment]
How can I get the shape of the DALI output ? 
`output[1]` are the bboxes and on `index = 2` there are the labels, but the problem is that `output[1], output[2]` are not dense tensors so I can use `as_tensor()`, how can I get the shape of them after they exit the pipeline ?

**Comment by cristyioan2000** [comment]
I should do `output[1].at(batch).shape()` for all samples of the batch and get the sum and use it for `as_reshaped_tensor()` ?

**Comment by JanuszL** [comment]
Yes, `output[1].at(batch).shape()` is the way.
