### ISSUE TITLE
nvidia.dali.ops' has no attribute 'nvJPEGDecoderSlice'

### ISSUE THREAD

**Issue by chowkamlee81** [NVIDIA/DALI#1550]
Iam getting an error like : nvidia.dali.ops' has no attribute 'nvJPEGDecoderSlice'

Kindly help

**Comment by Kh4L** [comment]
Hi @chowkamlee81 ,

`nvJPEGDecoder*` and `HostDecoder*` operators has been renamed in `ImageDecoder*` ones with a different `device` argument in [0.16](https://github.com/NVIDIA/DALI/releases/tag/v0.16.0).

In your case, please use [ImageDecoderSlice](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html#nvidia.dali.ops.ImageDecoderSlice) with `device=gpu`.

**Comment by JanuszL** [comment]
You can always see the supported operations inside our docs - https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html.

> In your case, please use ImageDecoderSlice with device=gpu.

You need to use "mixed" to be precise.

**Comment by chowkamlee81** [comment]
Thanks Got the changed APIs and it was working for the rest of modules.Closing the issue
