### ISSUE TITLE
Assert on "crop_arg_ndims >= 2 && crop_arg_ndims <= 3" failed: `crop` argument should have 2 or 3 elements depending on the input data shape

### ISSUE THREAD

**Issue by chowkamlee81** [NVIDIA/DALI#1564]
Kindly help for the issue:

Assert on "crop_arg_ndims >= 2 && crop_arg_ndims <= 3" failed: `crop` argument should have 2 or 3 elements depending on the input data shape

**Comment by awolant** [comment]
Hi, 
could you provide some more information on what you were trying to do? Some small reproduction would be very helpful, because right now it's hard to say what exactly happened.
Thanks.

**Comment by chowkamlee81** [comment]
i have used nvidia-retinanet examples. And i run inference code without using docker and iam using anaconda environment to debug.
But when irun infer i got the error "Assert on "crop_arg_ndims >= 2 && crop_arg_ndims <= 3" failed: crop argument should have 2 or 3 elements depending on the input data shape".

Also nvidia-retinanet member told they cant solve this issue. Kindly help

**Comment by chowkamlee81** [comment]
@awolant , kindly help

**Comment by jantonguirao** [comment]
@chowkamlee81 In order to help you, we will need a short snippet of code that we can use to reproduce your problem. Could  you please share your DALI pipeline?

**Comment by jantonguirao** [comment]
@chowkamlee81 I took a look at the `nvidia-retinanet` example and found that the usage `CropMirrorNormalize` is outdated for the latest version of DALI. You can solve this issue by replacing the line:
```
self.normalize = ops.CropMirrorNormalize(device='gpu', mean=mean, std=std, crop=padded_size, crop_pos_x=0, crop_pos_y=0)
```
with
```
self.normalize = ops.CropMirrorNormalize(device='gpu', mean=mean, std=std, crop=(padded_size, padded_size), crop_pos_x=0, crop_pos_y=0)
```

**Comment by chowkamlee81** [comment]
@jantonguirao thanks for your patience for having a look t the code of nvifia tetinanet. I will make those modification for the line u suggested and will update you

**Comment by chowkamlee81** [comment]
Thanks @jantonguirao , your function pick was exactly correct and it is working fine. Thanks you made my day today.
