### ISSUE TITLE
AttributeError: module 'nvidia.dali.ops' has no attribute 'NormalizePermute'

### ISSUE THREAD

**Issue by Moon-W** [NVIDIA/DALI#1580]
Traceback (most recent call last):
  File "test.py", line 32, in <module>
    frontalize(saved_model, datapath, 3)
  File "test.py", line 16, in frontalize
    test_pipe = ImagePipeline(datapath, image_size=128, random_shuffle=False, batch_size=mtest)
  File "/home/hanchao/Wu/frontalization/data.py", line 112, in __init__
    self.norm = ops.NormalizePermute(device="gpu", output_dtype=types.FLOAT,
AttributeError: module 'nvidia.dali.ops' has no attribute 'NormalizePermute'

I use cuda9.0 , nvida-dali=0.16.0, what should I do to fix it ?

**Comment by awolant** [comment]
Hi,
thanks for the question. 
This operator has been [deprecated](https://docs.nvidia.com/deeplearning/sdk/dali-archived/dali_0150_beta/dali-developer-guide/docs/supported_ops.html?highlight=normalizepermute#nvidia.dali.ops.NormalizePermute) for some time now and we removed it. You can use [`CropMirrorNormalize`](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html?highlight=cropmirrornormalize#nvidia.dali.ops.CropMirrorNormalize) instead.
