### ISSUE TITLE
no sequence length

### ISSUE THREAD

**Issue by Wegnery219** [NVIDIA/DALI#1588]
Assert on "HasArgument(name)" failed: Argument "sequence_length" is not supported by operator "VideoReader"

on Kaggle kernel, build from .whl Dali version is 0.6.0

anyone successfully load video on Kaggle kernel? can I see your kernel please?

**Comment by JanuszL** [comment]
Hi,
Please update DALI to the last release 0.16 and test again. The one you are using is almost 1 year old.

**Comment by Wegnery219** [comment]
> Hi,
> Please update DALI to the last release 0.16 and test again. The one you are using is almost 1 year old.

Thank you for your apply!I have another question, how the VideoReader get frames from a video?consequently or equally spaced?

**Comment by JanuszL** [comment]
Hi,
Sequences could be obtained randomly when `random_shuffle` is set to true. To control what frames are inside the sequence please use `sequence_length`, `step` and `stride`. So they are equally spaced in the sequence but the step can be configures between frames, and between senescence.

**Comment by Wegnery219** [comment]
> Hi,
> Sequences could be obtained randomly when `random_shuffle` is set to true. To control what frames are inside the sequence please use `sequence_length`, `step` and `stride`. So they are equally spaced in the sequence but the step can be configures between frames, and between senescence.

Thank you for your reply! I run help(ops.VideoReader) but i only get a param named step to define the interval between sequences, i didn't find a stride to define the interval in each sequence.By the way, i run your example successfully yesterday, but today i met a problem like "Critical error in pipeline: [/opt/dali/dali/util/cuda_utils.h:69] CUDA runtime api error "out of memory" Current pipeline object is no longer valid." I restart the kernel and still not working, what should I do?

**Comment by JanuszL** [comment]
> y the way, i run your example successfully yesterday, but today i met a problem like "Critical error in pipeline: [/opt/dali/dali/util/cuda_utils.h:69] CUDA runtime api error "out of memory" Current pipeline object is no longer valid."

Are you sure there is no process running in the background that uses GPU memory? You can run `nvidia-smi` to check how much memory you have left? Are you running DALI standalone or with some framework?

**Comment by Wegnery219** [comment]
It is with some framework. I have found the reason is my batch size is too big to load in gpu memory. Can I use more than one pipeline in my code?And how to clean the gpu memory the pipeline takes if I don't need that anymore?t 

And why i can't find the stride parameter in VideoReader?

Thank you a lot for your timely reply!

**Comment by JanuszL** [comment]
You can use more than 1 pipeline, if you want to free the memory used by it just issue `del old_pipeline`, as soon as the object is GC then all memory allocated by it should be freed.
Regarding the stride parameter it is very strange. Can you:
- provide the result after issuing `pip show nvidia-dali`?
- can you show the full content after issuing `help (nvidia.dali.ops.VideoReader)`?

**Comment by Wegnery219** [comment]
- The result after `pip show nvidia-dali`
Name: nvidia-dali
Version: 0.10.0
Summary: NVIDIA DALI for CUDA 9.0
- The full content after `help(nvidia.dali.ops.VideoReader)`
```
Help on class VideoReader in module nvidia.dali.ops:
class VideoReader(builtins.object)
 |  .. _VideoReader:
 |  
 |  This is a 'GPU' operator
 |  
 |  
 |  Load and decode H264 video codec with FFmpeg and NVDECODE, NVIDIA GPU's hardware-accelerated video decoding.
 |  The video codecs can be contained in most of container file formats. FFmpeg is used to parse video containers.
 |  Returns a batch of sequences of `sequence_length` frames of shape [N, F, H, W, C] (N being the batch size and F the
 |  number of frames).
 |  
 |  Parameters
 |  ----------
 |  `filenames` : str or list of str
 |                File names of the video files to load.
 |  `sequence_length` : int
 |                      Frames to load per sequence.
 |  `bytes_per_sample_hint` : int, optional, default = 0
 |                            Output size hint (bytes), per sample. The memory will be preallocated if it uses GPU or page-locked memory
 |  `channels` : int, optional, default = 3
 |               Number of channels.
 |  `dtype` : nvidia.dali.types.DALIDataType, optional, default = DALIDataType.UINT8
 |            The data type of the output frames (supports FLOAT and UINT8).
 |  `image_type` : nvidia.dali.types.DALIImageType, optional, default = DALIImageType.RGB
 |                 The color space of the output frames (supports RGB and YCbCr).
 |  `initial_fill` : int, optional, default = 1024
 |                   Size of the buffer used for shuffling.
 |  `lazy_init` : bool, optional, default = False
 |                If set to true, Loader will parse and prepare the dataset metadata only during the first `Run`
 |                instead of in the constructor.
 |  `normalized` : bool, optional, default = False
 |                 Get output as normalized data.
 |  `num_shards` : int, optional, default = 1
 |                 Partition the data into this many parts (used for multiGPU training).
 |  `prefetch_queue_depth` : int, optional, default = 1
 |                           Specifies the number of batches prefetched by the internal Loader. To be increased when pipeline
 |                           processing is CPU stage-bound, trading memory consumption for better interleaving with the Loader thread.
 |  `random_shuffle` : bool, optional, default = False
 |                     Whether to randomly shuffle data.
 |  `read_ahead` : bool, optional, default = False
 |                 Whether accessed data should be read ahead. In case of big files like LMDB,
 |                 RecordIO or TFRecord it will slow down first access but will decrease the time of all following
 |                 accesses.
 |  `scale` : float, optional, default = 1.0
 |            Rescaling factor of height and width.
 |  `seed` : int, optional, default = -1
 |           Random seed (If not provided it will be populated based on the global seed of the pipeline)
 |  `shard_id` : int, optional, default = 0
 |               Id of the part to read.
 |  `skip_cached_images` : bool, optional, default = False
 |                         If set to true, loading data will be skipped when the sample is present in the decoder cache.
 |                         In such case the output of the loader will be empty
 |  `step` : int, optional, default = -1
 |           Frame interval between each sequence (if `step` < 0, `step` is set to `sequence_length`).
 |  `stick_to_shard` : bool, optional, default = False
 |                     Whether reader should stick to given data shard instead of going through the whole dataset.
 |                     When decoder caching is used, it reduces significantly the amount of data to be cached, but could affect
 |                     accuracy in some cases
 |  `tensor_init_bytes` : int, optional, default = 1048576
 |                        Hint for how much memory to allocate per image.
 |  
 |  Methods defined here:
 |  
 |  __call__(self, *inputs, **kwargs)
 |  
 |  __init__(self, **kwargs)
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)
 |  
 |  device
 |  
 |  schema
 |  
 |  spec
```

**Comment by Wegnery219** [comment]
By the way, the VideoReader still doesn't support Resize operation?
what should I do if I really need to Resize the video use gpu?

I try to take the picture from the videoloader one by one, like the code:
```
resize = ops.Resize(device="gpu", resize_x=299, resize_y=299)
for i, inputs in enumerate(loader):
    resize(inputs[0]["data"])
``` 
but the error is `Expected inputs of type EdgeReference or list of EdgeReference. Received input type Tensor`

Any other solution to Video Resize?

**Comment by JanuszL** [comment]
Hi,
1) Please update DALI to the latest release. 0.10 is over half a year old. Stride should appear after the update.
2) We plan to enable support for sequences in resize, but we cannot commit to any date yet. DALI builds a graph, so
```
for i, inputs in enumerate(loader):
    resize(inputs[0]["data"])
```
won't work as the whole sequence is represented by the one edge so you cannot split it that way.

**Comment by Wegnery219** [comment]
hello again(TAT), what normalized do in VideoReader? After I set that to true, the whole image in a sequence changed to zero every pixel, my code is like this:`self.reader = ops.VideoReader(device="gpu", filenames=files, sequence_length=sequence_length, normalized=True,
                                     step=step, image_type=types.RGB, dtype=types.FLOAT)`

Where to get the DALI latest release wheel file?

**Comment by JanuszL** [comment]
> Where to get the DALI latest release wheel file?

You can check the [installation guide](https://docs.nvidia.com/deeplearning/sdk/dali-master-branch-user-guide/docs/installation.html#installing-prebuilt-dali-packages) , and issue `pip install --upgrade ...`.

> what normalized do in VideoReader

When set to true it is assumed that the video data output will be in [0-1.0] range, when set to false it will be [0, 256]. When you set the output type to UINT8 then your values will be rounded toward 0. If you want to set it to `True` use FLOAT as an output.

**Comment by Wegnery219** [comment]
I tried to use DALI in kaggle kernel and this is what i met with . Not sure ,if there is some enablement need to be done in Kaggle containers .
```
Assert on "cuvidInitChecked(0)" failed: Failed to load libnvcuvid.so, 
needed by the VideoReader operator. 
If you are running in a Docker container, please refer to https://github.com/NVIDIA/nvidia-docker/wiki/Usage
```

I got this insight on your project `docker run --runtime=nvidia --rm nvidia/cuda nvidia-smi`
but how to config that on a running docker?

**Comment by JanuszL** [comment]
Please try:
```
For a Dockerfile using the NVIDIA Video Codec SDK, you should use:

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,video,utility
```
from the mentioned link https://github.com/NVIDIA/nvidia-docker/wiki/Usage.

**Comment by Wegnery219** [comment]
It seems that I couldn't update the environment setting to support video on kaggle docker kernel. It depends on the kaggle official. But I have tried VideoReader locally, it's really fast and efficient. Thank you for your work!

**Comment by JanuszL** [comment]
You can build your own docker image using the kagel`s as a base and then just add the env variables or add following lines to docker run command:
```
-e "NVIDIA_DRIVER_CAPABILITIES=compute,utility,video"
```

**Comment by NicWickman** [comment]
Yes but we cannot modify the Kaggle docker kernel, correct? So we cannot use this pipeline for competition.

**Comment by JanuszL** [comment]
@NicWickman - if you cannot change Kaggle docker kernel to update DALI then there is nothing we can do, Still, you can check if `-e "NVIDIA_DRIVER_CAPABILITIES=compute,utility,video"` works for you.
