### ISSUE TITLE
How to split imagenet dataset into training and validation datasets?

### ISSUE THREAD

**Issue by colorjam** [NVIDIA/DALI#1607]
DALI load imagenet training dataset through `ops.FileReader` and iterate data through `Pipeline`. If I want to split the dataset into training and validation according to `val_size`, how can I do this inside `Pipeline` class? Do I need to use  `ExternalSource` operator?

**Comment by jantonguirao** [comment]
Hello @colorjam,
Typically, we split the data set into separate training and validation sets before you start. For example, in https://github.com/NVIDIA/DALI/blob/master/docs/examples/pytorch/resnet50/main.py you can see two different pipelines, one for training and one for validation, and each of the pipelines get a different data directory: '/data/imagenet/train-jpeg/' and '/data/imagenet/val-jpeg/' respectively.

**Comment by colorjam** [comment]
Thank you for the quick reply @jantonguirao , I have seen that, but I want to use images in '/data/imagenet/train-jpeg' to split additional validation dataset, such as in PyTorch, I can do this use `Sampler` as following:
```
        if valid_size is not None:
            if isinstance(valid_size, float):
                valid_size = int(valid_size * len(train_dataset))
            else:
                assert isinstance(valid_size, int), 'invalid valid_size: %s' % valid_size
            train_indexes, valid_indexes = self.random_sample_valid_set(
                [cls for _, cls in train_dataset.samples], valid_size, self.n_classes,
            )
            train_sampler = torch.utils.data.sampler.SubsetRandomSampler(train_indexes)
            valid_sampler = torch.utils.data.sampler.SubsetRandomSampler(valid_indexes)

            valid_dataset = datasets.ImageFolder(self.train_path, transforms.Compose([
                transforms.Resize(self.resize_value),
                transforms.CenterCrop(self.image_size),
                transforms.ToTensor(),
                self.normalize,
            ]))

            self.train = torch.utils.data.DataLoader(
                train_dataset, batch_size=train_batch_size, sampler=train_sampler,
                num_workers=n_worker, pin_memory=True,
            )
            self.valid = torch.utils.data.DataLoader(
                valid_dataset, batch_size=test_batch_size, sampler=valid_sampler,
                num_workers=n_worker, pin_memory=True,
            )
```

Can I do similar operation in DALI?

**Comment by jantonguirao** [comment]
@colorjam You could use the `file_list` argument of `FileReader` to provide a list of files for each of your sets, and use two instances of FileReader, one with each of those file lists. You can see some usage examples here: https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/getting%20started.html?highlight=file_list and the documentation for FileReader here: https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html#filereader

```
reader_train = ops.FileReader(file_root=/path/to/dataset, file_list=/path/to/file/list/train.txt)
reader_val = ops.FileReader(file_root=/path/to/dataset, file_list=/path/to/file/list/val.txt)
```
In this scenario, the two file lists are created before hand, and `reader_train` and `reader_val` have access to two different non-overlapping set of samples

**Comment by JanuszL** [comment]
@colorjam - you can also create these files online as a part of your script, traverse the folders, assemble a list of all files, the split into to train and val part and then create the file lists you will pass to `FileReader`.

**Comment by colorjam** [comment]
Thanks! I will give it a try.
