### ISSUE TITLE
For PyTorch: RuntimeError("Data list provided to feed_input needs to have batch_size length")

### ISSUE THREAD

**Issue by WhatAShot** [NVIDIA/DALI#1608]
I used DALI as pytorch data loader. I wrote a Pipleline of my own dataset, and define a function "iter_setup" in the class, by:
```
    def iter_setup(self):
        (images, labels) = self.iterator.next()
        self.feed_input(self.pngs, images)
        self.feed_input(self.labels, labels)
```
I use DALIClassificationIterator, and set fill_last_batch=True. However an error raised no matter I set last_batch_padded=True or False:
> RuntimeError("Data list provided to feed_input needs to have batch_size length")

It might be because that, the length of data might not match the batch_size in the last batch iteration in an epoch. I don't know how to fix it. Please give me some advice.

**Comment by JanuszL** [comment]
Hi.
the error you see is because the `images, labels` are in the wrong format. It should be either a list of batch size length of numpy arrays or numpy array with the first dimension equal to the batch size.
