### ISSUE TITLE
How to load video from tfrecord?

### ISSUE THREAD

**Issue by ghost** [NVIDIA/DALI#1613]
we has many video files and i pack them into one tfrecord file  with each video as a exmple. 
So how can i load the video from tfrecord?  i found that the videoreader only accept files.

**Comment by jantonguirao** [comment]
Hi @tanguofu. At this moment we do not have a stand-alone video decoder. 

It is in our plans to have a separate video decoder to enable use cases like yours. However, we can't give you an exact schedule right now. The only way you could use DALI to decode videos is to split your TFRecords into separate video files.
 
Thank you for your request, I hope it will help us prioritize this feature.

**Comment by JanuszL** [comment]
Providing more background to what @jantonguirao wrote, the main problem is that decoder is tightly coupled with the reader - reader seeks through the video stream in and gets feedback from the decoder how to seek (we need to find enclosing keyframes to be able to decode selected frames).
To provide separation you are asking for we need to read the whole video and pass it to decoder even if we want to decode only one frame (it increases memory occupation and requires to reread over and over the same sample if we want to decode different frames each iteration).
Could you also provide more description of how you want video decoder in such use case - you want to decode the whole video at once or keep the current behavior of extracting selected sequences from the longer video stream?

**Comment by JanuszL** [comment]
Hi,

You can now use [the `video decoder`](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.experimental.decoders.video.html) to decode the raw tensors with the videos, no matter if they are provided by an external source or TFRecord reader.
