### ISSUE TITLE
How to use multiple VideoReader, so I can read input/GT videos from different folders?

### ISSUE THREAD

**Issue by jiangsutx** [NVIDIA/DALI#1616]
Hi,
I am doing some training on video super-resolution.
So I prepared 2 folders, one for input low-resolution videos and one for high-resolution videos.

And I want to use DALI to loader these videos, and sample the same frame index and crop corresponding patches. 

After some research, I found DALI does support 2 `VideoReader` in one pipeline? Is it true?
Do you have suggestions for this situation?

Thank for your kindness.

**Comment by jantonguirao** [comment]
Hi @jiangsutx. I believe that there should be no problem having two instances of `VideoReader` reading files from two different directories in one pipeline. If you find any issues with that, please let us know

**Comment by JanuszL** [comment]
Please keep in mind that you need to have the same folder structure or provide the same `file_list`. If you want to have shuffling enable please set the same seed to both readers.

**Comment by jiangsutx** [comment]
Thanks for your reply.
Here I attached my code here.
```python
import os
import sys

from nvidia.dali.pipeline import Pipeline
from nvidia.dali.plugin import pytorch
import nvidia.dali.ops as ops
import nvidia.dali.types as types

class VideoReaderPipeline(Pipeline):
    def __init__(self, batch_size, sequence_length, num_threads, device_id, files, crop_size):
        super(VideoReaderPipeline, self).__init__(batch_size, num_threads, device_id, seed=12)
        self.reader = ops.VideoReader(device="gpu", filenames=files, sequence_length=sequence_length, normalized=False,
                                      random_shuffle=True, image_type=types.RGB, dtype=types.UINT8, initial_fill=16)
        self.reader2 = ops.VideoReader(device="gpu", filenames=files, sequence_length=sequence_length, normalized=False,
                                      random_shuffle=True, image_type=types.RGB, dtype=types.UINT8, initial_fill=16)
        self.crop = ops.Crop(device='gpu', crop=crop_size, output_dtype=types.FLOAT)
        self.uniform = ops.Uniform(range=(0.0, 1.0))
        self.transpose = ops.Transpose(device='gpu', perm=[3, 0, 1, 2])

    def define_graph(self):
        input = self.reader(name='Reader')
        cropped = self.crop(input, crop_pos_x=self.uniform(), crop_pos_y=self.uniform())
        output = self.transpose(cropped)
        input2 = self.reader2(name='Reader2')
        cropped2 = self.crop(input2, crop_pos_x=self.uniform(), crop_pos_y=self.uniform())
        output2 = self.transpose(cropped2)
        return output, output2



if __name__ == '__main__':
    file_root = '../../dataset/PCVSR4_triple/PCVSR4_4K_420'
    container_files = os.listdir(file_root)
    container_files = [file_root + '/' + f for f in container_files]
    print(container_files)
    pipeline = VideoReaderPipeline(batch_size=5, sequence_length=3, num_threads=1, device_id=0, files=container_files,
                                            crop_size=[200, 200])
    pipeline.build()

    pipe_out = pipeline.run()
    print(pipe_out[0], len(pipe_out[0]), pipe_out[1], len(pipe_out[1]))
```
This code runs smoothly if I use one `VideoReader`. When I add a new one, it produces error:
```
RuntimeError: Critical error in pipeline: CUDA allocation failed
Current pipeline object is no longer valid.
```
Did I write something wrong in that code please? 
Thank you for your time.

**Comment by JanuszL** [comment]
@jiangsutx - you may also try to play with `additional_decode_surfaces` parameter of the video reader and see if that reduces memory consumption in your case.

**Comment by JanuszL** [comment]
https://github.com/NVIDIA/DALI/pull/1669 could resolve your problem. Please check the nightly build that will follow when it is merged.

**Comment by JanuszL** [comment]
0.19 is out and should address this. Please reopen if it doesn't work.
