### ISSUE TITLE
How to efficiently use DALI on a custom MXNet model and training loop with multiple GPUs in 1 node?

### ISSUE THREAD

**Issue by miguelrc1** [NVIDIA/DALI#1622]
Hi, I have a question after going through the examples [here](https://docs.nvidia.com/deeplearning/sdk/dali-master-branch-user-guide/docs/examples/mxnet/mxnet-resnet50.html) and it's related code [here](https://github.com/NVIDIA/DALI/blob/master/docs/examples/mxnet/demo/common/fit.py).

My understanding is that DALI process all the augmentations in different GPUs, then aggregates the data in GPU 0 and down the algorithm we use something like `gluon.utils.split_and_load` to re-distribute it across GPUs. Since this seems quite inefficient my question is if I am doing something wrong or that's suppose to be the expected behaviour?

After instantiating, building the pipelines, and creating the DALIClassificationIterator I check the output and it's all in GPU:0.

In those examples a pre-build model is used (`mx.mod.Module`) which has a fit method that is then used for training with DALI pipelines.

**Comment by JanuszL** [comment]
Hi,
Indeed DALI does processing in each GPU separately. However, no step aggregates the data in GPU0 - you can check [MXNet DALI iterator code](https://github.com/NVIDIA/DALI/blob/master/dali/python/nvidia/dali/plugin/mxnet.py#L230) and see that for each pipeline it wraps, the corresponding NDArray is created for each GPU separately.
Still, the most recommended way to perform multi GPU training is using Horovod where each GPU runs in the separated process, and data from DALI is processed and training the same GPU - you can check example [here](https://github.com/NVIDIA/DeepLearningExamples/tree/master/MxNet/Classification/RN50v1.5).

> After instantiating, building the pipelines, and creating the DALIClassificationIterator I check the output and it's all in GPU:0.

Can you provide some code sample that reproduces you used to verify this?

**Comment by miguelrc1** [comment]
Hi @JanuszL, happy new year and thank you very much for the quick response. 

Thank you very much for pointing out the Resnet50 Horovod example. Will try to use the Horovod example. 

A side question, do you happen to have an example of how to use DALI + Horovod with PyTorch? I have only been able to find it with PyTorch DDP which to the best of my knowledge is slightly slower than hvd. Here I am having issues on how to adapt the data torch.utils.data.distributed.DistributedSampler wrapper to a DALI iterator as shown in [here](https://github.com/horovod/horovod/blob/master/docs/pytorch.rst) for a DataSet. 

Here is a sniped of the code I used:

```
N_CLASSES = len(list(TRAIN_FOLDER.iterdir()))
IMG_SIZE = (250,250)
N_GPUS = 4
BS = 8 * N_GPUS

class ImagePipeline_train(Pipeline):
    def __init__(self, batch_size, num_threads, device_id, image_dir, size, num_shards=1):
        super().__init__(batch_size, num_threads, device_id, seed=12)
        self.input = ops.FileReader(file_root=image_dir, random_shuffle=True, num_shards=num_shards, shard_id=device_id)
        self.decode = ops.ImageDecoder(device='cpu', output_type=types.RGB)
        self.normalize = ops.CropMirrorNormalize(device='gpu', crop=size, 
                                                 mean=[0.485, 0.456, 0.406], 
                                                 std=[0.229, 0.224, 0.225],
                                                output_layout=types.NHWC)  
        self.mirror = ops.CoinFlip()
        self.rotate = ops.Rotate(device='gpu', size=size)
        self.rng = ops.Uniform(range = (-10.0, 10.0))
        
        self.transpose = ops.Transpose(device='gpu', perm=[2,0,1]) #without batch dimension
        
    def define_graph(self):
        jpegs, labels = self.input()
        images = self.decode(jpegs)/256
        norm_images = self.normalize(images.gpu(), mirror=self.mirror())
        angle = self.rng()
        rotated_images = self.rotate(norm_images, angle=angle)
        out_images = self.transpose(rotated_images)
        return (out_images, labels.gpu())

train_pipes = [ImagePipeline_train(BS, num_threads=2, device_id=device_id, image_dir=IMAGE_DIR, size=IMG_SIZE, num_shards=N_GPUS) for device_id in range(N_GPUS)]

train_pipes[0].build()

train_dali_iter = DALIClassificationIterator(pipelines=train_pipes, 
                                data_name='images',
                                label_name='labels', 
                                size=size_train//BS,
                                auto_reset=True
                               )

# check device
next(train_dali_iter)[0].data
```

**Comment by JanuszL** [comment]
Hi,
We haven't tested horovod with PyTorch, you can check [PyTorch DDP examples here](https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/Classification/ConvNets).

Still, by the analogy to MXNet I believe your code with horovod should looks like:
```
class ImagePipeline_train(Pipeline):
    def __init__(self, batch_size, num_threads, device_id, image_dir, size, shard_id=1, num_shards=1):
        super().__init__(batch_size, num_threads, device_id, seed=12)
        self.input = ops.FileReader(file_root=image_dir, random_shuffle=True, num_shards=num_shards, shard_id=shard_id)
(...)

train_pipe = ImagePipeline_train(BS, num_threads=2, device_id=hvd.local_rank(), image_dir=IMAGE_DIR, size=IMG_SIZE, shard_id=hvd.rank(), num_shards=hvd.size())

train_pipe.build()

train_dali_iter = DALIClassificationIterator(pipelines=train_pipe, 
                                data_name='images',
                                label_name='labels', 
                                size=size_train//BS,
                                auto_reset=True
                               )

```

**Comment by miguelrc1** [comment]
Thank you @JanuszL !

Will try that analogy for DALI with hvd and PyTorch / hvd and MXNet and provide feedback on the former.

**Comment by Kh4L** [comment]
Hi @miguelrc1 ,

AFAIK, DDP is faster than Horovod (and easier to use) in PyTorch.
However, Horovod is the best when using TF or MXNet.

**Comment by miguelrc1** [comment]
Hi @Kh4L, thank you very much for jumping in. Do you have the link to the comparison between using both distributed frameworks I can refer to?

**Comment by JanuszL** [comment]
@miguelrc1 - I think the best place to ask is https://discuss.pytorch.org/.
