### ISSUE TITLE
maybe Transpose bug

### ISSUE THREAD

**Issue by tanglang96** [NVIDIA/DALI#1623]
Hi, I'm using ```ops.Transpose(perm=[2, 0, 1], device="gpu")``` to transpose img from ```HWC->CHW```, when I have 3 channels it works fine, but when I have 1 channel like ```32x32x1``` input shape, it reports an error
![bug](https://user-images.githubusercontent.com/28501635/71620881-2d9eda80-2c07-11ea-81ca-46c4f6b195bc.PNG)

**Comment by jantonguirao** [comment]
Hi @tanglang96. Could you please share the DALI version that you are using? I believe this is a bug we fixed few releases ago (around September)

**Comment by tanglang96** [comment]
Hi @jantonguirao , I'm using dali version==0.17

**Comment by tanglang96** [comment]
Hi @jantonguirao , I tried version 0.14, 0.15, 0.16 and 0.17 and they report the same error as above

**Comment by JanuszL** [comment]
@tanglang96 - I have found the bug. https://github.com/NVIDIA/DALI/pull/1624 should fix it. Please check the nightly build when this PR is merged.

**Comment by tanglang96** [comment]
@JanuszL Thanks for this.
