### ISSUE TITLE
Some problems about ImageDecoderSlice

### ISSUE THREAD

**Issue by 00liujj** [NVIDIA/DALI#1627]
The op `ImageDecoderSlice` accepts three parameters: (image, begin, size), what if the image is on GPU(e.g. the output of Paste), while (begin, size) are on CPU?

It's easy for users to implement boxes augmentations in CPU, while keep the image augmentations on GPU.

**Comment by JanuszL** [comment]
Hi,
It will work. Very similar example is [here](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/detection_pipeline.html). `Slice` runs on the GPU, while `crop_begin` and `crop_size` come from `prospective_crop` on the CPU.

**Comment by 00liujj** [comment]
@JanuszL  Thank you very much. It works!
