### ISSUE TITLE
More Example for Pytorch, please?

### ISSUE THREAD

**Issue by iqDF** [NVIDIA/DALI#1632]
Hi there I'm wondering if I can help/add some example on Pytorch DALI. Currently I'm using Dali for Video pipelining in my Deep Learning experiment, perhaps I can refactor them and make a simple tutorial here at NVIDIA DALI repo.

Some questions before we start. 

1. Does the example/tutorial has to be from staff/main contributors? I heard NVIDIA is pretty strict regarding knowledge sharing under its name.
2. If you're okay with me, I can perhaps send a simple notebook first and proceed from there. Is there any criteria on the tutorials? and what usually are the format? more towards article based?

Regards,
Daniel Kurniadi

**Comment by szalpal** [comment]
Hi @iqDF !
We're not *that* strict and we'd be happy to accept your use-case example. Feel free to post it as a PR and we'll take the conversation from there. We accept both notebooks and scripts, whatever suits you better. I'd encourage you to fit the format to the content. Whether you feel, that what you have is more a step-by-step tutorial or more towards an article, please do it this way.

In the case of notebooks, nice reference material for the tutorials are the ones that we already have:
[Spectogram tutorial](https://github.com/NVIDIA/DALI/blob/master/docs/examples/audio/spectrogram.ipynb)
[Audio decoder](https://github.com/NVIDIA/DALI/blob/master/docs/examples/audio_decoder.ipynb)

Please remember, that the contributions need to be compliant with the Apache2.0 license. We might ask you to provide license sources in case of material, that we're not 100% sure about the compliance.

Kind regards,
MS

**Comment by JanuszL** [comment]
@iqDF - regarding knowledge sharing, in this case, it is reviewed and accepted before it is done under NVIDIA name. So when we think that the example has the required level of quality we will accept it and make a part of the official documentation. As you can see we are doing our best to be approachable and as responsive as possible here so feel free to ask us for help if needed.
Regarding the legal side - please check https://github.com/NVIDIA/DALI/blob/master/CONTRIBUTING.md#sign-your-work.

**Comment by iqDF** [comment]
Sounds good to me. I'll try wrap up my work first on my upcoming deadlines and submit to you asap. 
@JanuszL. I'll make sure to follow the review procedure and comply to Apache2.0 License. Thanks !
