### ISSUE TITLE
Problem with nvjpeg version

### ISSUE THREAD

**Issue by wuzhi19931128** [NVIDIA/DALI#1633]
when I run make. I got this Information:

PEG_LIBRARY-NOTFOUND
CMake Error at /data1/cmake/data/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find NVJPEG: Found unsuitable version "", but required is at
  least "9.0" (found /data1/cuda-linux64-nvjpeg)

What should I do?update NVjpeg?
Thanks

**Comment by szalpal** [comment]
@wuzhi19931128 ,
From the context I assume, you want to build bare-metal DALI on your system. Am I right?
What CUDA version are you using here?

**Comment by wuzhi19931128** [comment]
Thanks。 I have cuda9.0 and my NVjpeg is decompression from cuda-linux64-nvjpeg-9.0-v0.2.0.tar。My Dali is latest version from github.

**Comment by wuzhi19931128** [comment]
I saw the same problem in NVIDA web: 
https://devtalk.nvidia.com/default/topic/1050253/other-libraries/issue-while-building-nvidia-dali-with-source/

AND I notice that the source of dali said:
nvJPEG 9.0 calls itself 0.1.x via API calls, and the header file doesn't tell you which
# version it is. There's not a super clean way to determine which CUDA's nvJPEG we have.

BUT what should I do to solve this problem?
Thank you for your reply.

**Comment by szalpal** [comment]
Seems to me, that nvJpeg is not found. For sure a solution would be to use CUDA 10.0+, since nvJpeg is shipped there. If you would like to have CUDA 9.0, you need to install nvJpeg separately.

By default, CMake will look for nvJpeg in `/usr/local/cuda/*`. In case your nvJpeg is somewhere else, you can point its location to cmake, e.g.: `cmake -D NVJPEG_ROOT_DIR=/home/me/nvjpeg ..`

If this does not help, please paste `cmake ..` output, so I can see more details.

**Comment by wuzhi19931128** [comment]
I can't use other way to install because I'm in Chain, so I can't download package form the source. 
I alreadly point NVjpeg location and cmake found it. The problem is cmake can't identify the version.
Here is the output of my cmake:


root@test-zywmp0v9i:/data1/DALI-master/DALI-master/build# cmake .. -DNVJPEG_INCLUDE_DIR=/data1/cuda-linux64-nvjpeg/
-- BUILD_PYTHON -- ON
-- BUILD_LMDB -- OFF
-- BUILD_JPEG_TURBO -- ON
-- BUILD_LIBTIFF -- ON
-- BUILD_NVJPEG -- ON
-- BUILD_NVOF -- ON
-- BUILD_NVDEC -- ON
-- BUILD_LIBSND -- ON
-- BUILD_NVML -- ON
-- BUILD_FFTS -- ON
-- BUILD_FFMPEG -- ON
-- DALI version: 0.18.0dev
-- DALI_extra version: d61722e9fa6df5379cba68941e3f94bff9814def
CMake Error: File /data1/DALI-master/DALI-master/dali/test/dali_test_info.h.in does not exist.
CMake Error at CMakeLists.txt:64 (configure_file):
  configure_file Problem configuring file


-- Build configuration: Release
strings: NVJPEG_LIBRARY-NOTFOUND：无此文件
CMake Error at /data1/cmake/data/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find NVJPEG: Found unsuitable version "", but required is at
  least "9.0" (found /data1/cuda-linux64-nvjpeg)
Call Stack (most recent call first):
  /data1/cmake/data/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:376 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindNVJPEG.cmake:30 (find_package_handle_standard_args)
  cmake/Dependencies.cmake:28 (find_package)
  CMakeLists.txt:86 (include)


-- Configuring incomplete, errors occurred!
See also "/data1/DALI-master/DALI-master/build/CMakeFiles/CMakeOutput.log".
See also "/data1/DALI-master/DALI-master/build/CMakeFiles/CMakeError.log".

**Comment by JanuszL** [comment]
DALI determines the nvJPEG version based on the library binary, not the header. How about providing NVJPEG_ROOT_DIR (where the `include` and `lib` dirs are) or NVJPEG_LIBRARY (where the lib itself is)?

**Comment by wuzhi19931128** [comment]
I update my cuda to 10.0 and keep NVjpeg in local dir . But DALI didn't send error massage.

**Comment by yiakwy-xpu-ml-framework-team** [comment]
Hi, if you are using NGC, make check the location here :

> /usr/local/cuda/targets/x86_64-linux/

or

> find / -name "**nvjpeg**" | grep *.so

this will show you where the library it is.
