### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by wuzhi19931128** [NVIDIA/DALI#1638]
Hi . I install DALI from source (bare metal) . Cmake is OK but make -j"$(nproc)" is error.

Here the massage:
root@test-zdm7qox8h:/data1/DALI/build# make -j"$(nproc)"
make[2]: *** No rule to make target '../dali/pipeline/Protobuf_PROTOC_EXECUTABLE-NOTFOUND', needed by 'dali/pipeline/dali.pb.cc'。 停止。
CMakeFiles/Makefile2:1443: recipe for target 'dali/pipeline/CMakeFiles/DALI_PROTO.dir/all' failed
make[1]: *** [dali/pipeline/CMakeFiles/DALI_PROTO.dir/all] Error 2
make[1]: *** 正在等待未完成的任务....
make[2]: *** No rule to make target '../dali/operators/reader/parser/Protobuf_PROTOC_EXECUTABLE-NOTFOUND', needed by 'dali/operators/reader/parser/caffe2.pb.cc'。 停止。
CMakeFiles/Makefile2:2311: recipe for target 'dali/operators/reader/parser/CMakeFiles/CAFFE2_PROTO.dir/all' failed
make[1]: *** [dali/operators/reader/parser/CMakeFiles/CAFFE2_PROTO.dir/all] Error 2
make[2]: *** No rule to make target '../dali/operators/reader/parser/Protobuf_PROTOC_EXECUTABLE-NOTFOUND', needed by 'dali/operators/reader/parser/caffe.pb.cc'。 停止。
CMakeFiles/Makefile2:2348: recipe for target 'dali/operators/reader/parser/CMakeFiles/CAFFE_PROTO.dir/all' failed
make[1]: *** [dali/operators/reader/parser/CMakeFiles/CAFFE_PROTO.dir/all] Error 2

So what should I do? Thanks very much.

**Comment by wuzhi19931128** [comment]
Here is my cmake file. Maybe it's useful
[cmake_log.txt](https://github.com/NVIDIA/DALI/files/4044501/cmake_log.txt)

**Comment by JanuszL** [comment]
It seems that "protoc" is not found. Can you check if it is installed as well?

**Comment by wuzhi19931128** [comment]
I follow the  docker example and update my protobuf . It works.Thansks
