### ISSUE TITLE
the training time is slow after using dali

### ISSUE THREAD

**Issue by Adorablepet** [NVIDIA/DALI#1639]
I wrote an iterator to support the PK sampler (P personal and K pictures as a batch).The preprocessing time is about 10 times faster than pytorch's dataloader with one epoch.I don’t know why the training time is slow, or because the proportion of pre-processing time in the training process is relatively small.Thanks.

**Comment by JanuszL** [comment]
Hi,

>  because the proportion of pre-processing time in the training process is relatively small

is the most likely reason. You check this by checking GPU utilization - if it is high then you cannot go any faster. If it is still low maybe there is some other inefficiency in your network implementation.
You can also test with the synthetic data source - some dummy input tensor created once just to check how fast is your training without any data processing overhead. You can read more about this kind of analysis in https://devblogs.nvidia.com/case-study-resnet50-dali/.

**Comment by JanuszL** [comment]
If it still doesn't work please reopen.

**Comment by Adorablepet** [comment]
ok
