### ISSUE TITLE
ops.VideoReader: Too Many Opened Files

### ISSUE THREAD

**Issue by BlackPepperAPI** [NVIDIA/DALI#1651]
First of all, let me say thanks in advance for any advise. Here is my situation:

### Description
I currently working with HMDB51 dataset which training split has 3,571 videos. I quickly ran into this problem where my remote machine only allows opening 1,024 files at once.

Here is the specification from `ulimit`:

```
$ ulimit -a

- open files                      (-n) 1024  
- pipe size            (512 bytes, -p) 8
....
- file locks                      (-x) unlimited 
```

### Issue/Error
Here is the error I got from running the Video Pipeline using `ops.VideoReader`
```
Traceback (most recent call last):
...

RuntimeError: [/opt/dali/dali/operators/reader/loader/video_loader.cc:223] Could not open file:
data/HMDB51/processed/fencing/Zorro_(Funny_Fight_Scene)_fencing_u_cm_np2_fr_bad_1.mp4

because of Too many open files

Stacktrace (38 entries): 
[frame 0]: /home/students/student3_17/.local/lib/python3.6/site-packages/nvidia/dali/libdali_operators.so(+0x2bea1e) [0x7fd43996e
a1e]
[frame 1]: /home/students/student3_17/.local/lib/python3.6/site-packages/nvidia/dali/libdali_operators.so(+0x8db3db) [0x7fd439f8$
3db]
... 
```

### Question

Now I'm aware that some people has posted ways to allow the Ubuntu 18.04 system to open more files at once, e.g. [tutorial here](https://www.robustperception.io/dealing-with-too-many-open-files). 

However, I'm currently not the admin of my remote machine so I can't change the content of `/etc/security/limit.conf`.

Therefore, I wonder if I can limit the number of files to be opened at once by `ops.VideoReader`, let say to 1,024 or less.

I used `file_list = <MY TRAIN SPLIT FILE>`. This is my configurations for the video reader.

```
# Define video reader pipeline
self.reader = ops.VideoReader(
                        device = "gpu",
			file_list = file_list,
			sequence_length = 16,
			normalized = False,
			random_shuffle = True,
			image_type = types.RGB,
			dtype = types.UINT8,
			step = -1,
			stride = 1,
			initial_fill = 1024)
```

Is there a way/configuration that I can use to limit the number of opened files at once for `ops.VideoReader`? I tried reading the docs but I didn't see the arguments that satisfy my needs as far as I understand.

Btw. each video files is 30 fps with duration from 11-30 seconds. Thank you, I really appreciate your kind help in this matter.

**Comment by JanuszL** [comment]
Hi,
It is not currently possible to extend the limit in DALI. DALI keeps all files open until the very end of the pipeline. However we are aware about this problem and it is in our backlog.
If you want you can try to hack DALI on your own.
https://github.com/NVIDIA/DALI/blob/master/dali/operators/reader/loader/video_loader.cc#L414 DALI opens a video if it has not been opened so far. What could be done is to make some kind of LRU bookkeeping and close the files inside `get_or_open_file` function that are above some safe threshold (100?) when we try open a new file.
@a-sansanwal - what do you think?

**Comment by BlackPepperAPI** [comment]
Ah understood. Let me see if I can contribute. 

I'm working with videos right now for DL application and I wonder if NVIDIA Dali have supported the following:

### Additional questions regarding features
1. Perhaps I also wonder if I can do some random sampling on the video frames. Say if my sequence length is 16 and sample one sequence per video. Then randomly sample start frame: `Uniform(0, video_length - sequence_length)`
2. Perform sort of segmentation just like in Temporal Segmentation Network: [paper](https://wanglimin.github.io/papers/WangXWQLTV_ECCV16.pdf)

**Comment by JanuszL** [comment]
> * Perhaps I also wonder if I can do some random sampling on the video frames. Say if my sequence length is 16 and sample one sequence per video. Then randomly sample start frame: `Uniform(0, video_length - sequence_length)`
> 
> * Perform sort of segmentation just like in Temporal Segmentation Network: [paper](https://wanglimin.github.io/papers/WangXWQLTV_ECCV16.pdf)

If you enabling shuffling in the reader you should get more or less what you want (as far as I understand your ask correctly). VideoReader will create a list of all possible sequences given the length, step and stride and then will create a batch formed from the randomly chosen ones.

**Comment by BlackPepperAPI** [comment]
I see... When is the scheduled next release for NVIDIA Dali with the opened-file-limit feature?

**Comment by JanuszL** [comment]
@BlackPepperAPI - we don't have any ETA for that feature now as we are pursuing other goals. Still, we would be more than happy to see any community contribution lifting that limitation.

**Comment by a-sansanwal** [comment]
Hi @JanuszL, There is no other way around this because its enforced by kernel.
This can be a good external contribution, if not I can implement it when I find some time.

**Comment by JanuszL** [comment]
It should be fixed in https://github.com/NVIDIA/DALI/pull/1659. Please check the nightly build that would follow the merge of it.

**Comment by JanuszL** [comment]
0.19 is out and should address this. Please reopen if it doesn't work.
