### ISSUE TITLE
[Question] Support  Random scaling, Random Crop, and Random Flip Operations for Video in NVIDIA DALI

### ISSUE THREAD

**Issue by BlackPepperAPI** [NVIDIA/DALI#1660]
I'm currently using NVIDIA Dali `0.17.0` nightly built for Python. I'm working with video and I'm keen to try out data augmentation on video frames such as:

 **Random Scaling** - Apply scale the aspect ratio to `height:width` a sequence of video frames, where aspect ratio  is chosen randomly from e.g. [0.8, 1.25] for frames in entire sequence

** Random Crop** - Apply random crop for `crop_size =(w, h)` for video frames at random point, but still within the original frame size.

**Random Horizontal Flip** - Apply Flip randomly with probability e.g. 0.5

I noted that those operations are supported already for Image. But how about for input videos from `ops.VideoReader()`. It would be nice if I can do some sort of:

```
# video pipeline definition
self.video_reader = ops.VideoReader(.....)
self.video_scale = ops.RandomlyScaleVideo(...)  # input NFCHW or NFHWC
self.video_random_crop = ops.RandomlyCropVideo(...)  # input NFCHW or NFHWC
self.video_horizontal_crop = ops/RandomlyFlip(...) # input NFCHW or NFHWC
...
```

### Issue

I tried using the available operations in NVIDIA DALI:
- `ops.Flip`
- `ops.RandomResizedCrop` with `random_aspect_ratio`

But it seems those operations only support image input `HWC` . The program I run output an error complaining mismatch for shape, and only expect output_layout `HWC`.

### Questions
So my questions are:
1. Can I used the available operations for video? Please do point me out if I can use those operations for video frames with `NFCHW` or `NFHWC` input. I notice some operations only support Image `HWC`?
2. If do, how do I specify to the operations that I'm inputing video frames, not single image.

**Comment by JanuszL** [comment]
Hi @BlackPepperAPI,
From the listed operators only `Flip` support video. You can check `Sequences` column in [DALI documentation](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html).
Long term we want to make as many operators as possible to support sequences, but I cannot provide you any timeline now. However, we would be more than happy to accept any commit that would extend the current functionality.

**Comment by BlackPepperAPI** [comment]
Ahh that's what `sequence` tick means... understood. Yes I'm actually keen on doing contribution to NVIDIA Dali. I'm thinking to do so after I finished my research deadline on February. 

As someone who are new to C++, where should I start?

**Comment by JanuszL** [comment]
@BlackPepperAPI - if you are new to C++ then starting up may not that easy as DALI is using quite advanced C++.
@mzient any suggestion?

**Comment by mzient** [comment]
@BlackPepperAPI If you're fine with just bilinear interpolation (without extra anti-aliasing when downscaling aggresively), you can use WarpAffine to achieve scaling.
While it doens't work with sequences natively, it does work with volumetric data. The trick would be to use the Reshape operator to reinterpret the data from "FHWC" to "DHWC". Then, you use a 3D transform (the D dimension being the frame) and reinterpret back to FHWC when you're done.
It's still quite hacky (and slower than a native 2D sequence operator would be) and you'd probably need to use PythonFunction (which limits performance dramatically) to get the transform matrices and output sizes right - unless you know the input video sizes up front, then you can use ExternalSource to provide the matrices and shapes.

**Comment by kiyoon** [comment]
You can combine `Crop` and `Uniform` operator to perform random crop. I found this in the superresolution example.

**Comment by JanuszL** [comment]
The question is if this only about `Crop` or `RandomResizedCrop`, first is possible, the other one is not.

**Comment by kiyoon** [comment]
But how do you do random flip?
I tried something like
```python
flipped = self.flip(cropped, horizontal=(self.uniform() > 0.5))
```

But it didn't work.

**Comment by JanuszL** [comment]
Please try:
```
def __init__(...)
   self.coin = ops.CoinFlip(probability=0.5)
   (...)
def define_graph(self): 
  flipped = self.flip(cropped, horizontal=self.coin)
```

**Comment by JanuszL** [comment]
RandomResizedCrop have just been enabled - https://github.com/NVIDIA/DALI/pull/2430.
Please check the nightly build that follows it to see how it works.

**Comment by JanuszL** [comment]
Hi,
Now you can:
- randomly crop videos using slice and random generators
- random flip using flip and coin flip
- random scale using resize and random generators for a scale
