### ISSUE TITLE
how to use DALI with the model.fit in MXNET?

### ISSUE THREAD

**Issue by EaglesKK** [NVIDIA/DALI#1663]
I was following the example of [MXNet with DALI - ResNet 50 example](https://github.com/NVIDIA/DALI/blob/master/docs/examples/mxnet/mxnet-resnet50.ipynb), while I was using [model.fit()](https://mxnet.apache.org/api/python/docs/api/mxnet/model/index.html#mxnet.model.FeedForward.fit) to train the model, it threw an error liking this "TypeError: X must be DataIter, NDArray or numpy.ndarray"
following is the code
model.fit(
    X = dali_train_iter,
    eval_data = dali_val_iter,
    eval_metric=metrics,
    batch_end_callback=batchEndCBs,
    epoch_end_callback=epochEndCBs
)

Looking forward to your reply, thanks

**Comment by JanuszL** [comment]
Hi @EaglesKK,
Could you provide the code sample that throws that error?
In the DALI example, you are referring to we are using DALIClassificationIterator from nvidia.dali.plugin.mxnet to wrap the pipeline, and it returns NDArray as the output, so I'm a bit surprised by the error you get.

**Comment by EaglesKK** [comment]
Thanks to your reply @JanuszL,
I was using the exact [ResNet 50 pipeline](https://github.com/NVIDIA/DALI/blob/master/docs/examples/mxnet/mxnet-resnet50.ipynb) until
`from nvidia.dali.plugin.mxnet import DALIClassificationIterator
dali_train_iter = DALIClassificationIterator(trainpipes, trainpipes[0].epoch_size("Reader"))
dali_val_iter = DALIClassificationIterator(valpipes, valpipes[0].epoch_size("Reader"))`
 
then I compile my own model 
`# compile the model
model = mx.model.FeedForward(
    ctx=[mx.gpu(0), mx.gpu(1), mx.gpu(2), mx.gpu(3)],
    symbol=model,
    initializer=mx.initializer.Xavier(),
    arg_params=argParams,
    aux_params=auxParams,
    optimizer=opt,
    num_epoch=90,
    begin_epoch=args['start_epoch']
)
# train the network
model.fit(
    X = dali_train_iter,
    eval_data = dali_val_iter,
    eval_metric=metrics,
    batch_end_callback=batchEndCBs,
    epoch_end_callback=epochEndCBs
)` 
at the part of model.fit it threw the error
"TypeError: X must be DataIter, NDArray or numpy.ndarray"

**Comment by JanuszL** [comment]
I don't know MXNet that well, but shouldn't you do something like:
```
model.fit(
train_data = dali_train_iter,
eval_data = dali_val_iter,
eval_metric=metrics,
batch_end_callback=batchEndCBs,
epoch_end_callback=epochEndCBs
)
```
@Kh4L ?

**Comment by JanuszL** [comment]
> nvidia.dali.plugin.mxnet to wrap the pipeline, and it returns NDArray as the output, so I'm a bit surprised by the error you get.

Correction, DALI returns `mx.io.DataBatch` that wraps up `NDArray`.

**Comment by EaglesKK** [comment]
Thanks for your reply @JanuszL ,
The `X`  here is the training data and is described as follows:
```
Parameters
X (DataIter, or numpy.ndarray/NDArray) – Training data. If X is a DataIter, the name or (if name not available) the position of its outputs should match the corresponding variable names defined in the symbolic graph.
```
I am sorry, this is my first time using DALI, I don't really understand what do you mean by " DALI returns `mx.io.DataBatch` that wraps up `NDArray`"

**Comment by Kh4L** [comment]
Hi @EaglesKK ,

`Model.fit` is deprecated and you should be using `Module.fit`.

Please take a look at https://github.com/NVIDIA/DALI/blob/5b9f9d72056239bcc7df9daa1626a9fe34af7e43/docs/examples/mxnet/demo/common/fit.py#L198

to adapt the compilation of the model to the `mx.mod.Module` interface.

**Comment by Kh4L** [comment]
Then you will be able to use https://mxnet.apache.org/api/python/docs/api/module/index.html#mxnet.module.BaseModule.fit instead of https://mxnet.apache.org/api/python/docs/api/mxnet/model/index.html#mxnet.model.FeedForward.fit

**Comment by JanuszL** [comment]
@EaglesKK  I have made a fix https://github.com/NVIDIA/DALI/pull/1669, which makes the MXNet `DALIGenericIterator` inherit from `mxnet.io.DataIter`. Still to use it with `Model.fit` you need to wrap `DALIGenericIterator` and convert a list it returns to single `mx.io.DataBatch`, like in test added https://github.com/NVIDIA/DALI/pull/1669 (not the most beautiful solution but works).

**Comment by EaglesKK** [comment]
Hi @Kh4L, 
I tried your method, it's working now,  and I also tried @JanuszL 's method, it works too. Thanks a lot to both of you.
But there is one thing, my purpose in using DALI is to make GPUs have a higher utilization rate compared to `ImageRecordIter`, while I didn't see much difference. Do you have any suggestions about this?

**Comment by EaglesKK** [comment]
I think the speed problem is from my own settings, now it is working much faster than before.
Thanks for your help again!

**Comment by JanuszL** [comment]
@EaglesKK - I'm glad it works faster after all. Keep in mind that if the CPU is not the bottleneck then DALI won't help much. You can read about in one of our [blog posts](https://devblogs.nvidia.com/case-study-resnet50-dali/). The best approach to verify this is to check GPU utilization and create some dummy loader returning some constant tensor you can check how fast you can train without any data processing overhead.

**Comment by EaglesKK** [comment]
@JanuszL - Got it, really thanks a lot and have a nice day.
