### ISSUE TITLE
Knowing which part is loaded by VideoReader

### ISSUE THREAD

**Issue by kiyoon** [NVIDIA/DALI#1665]
Hi,

Is there any way to figure out which video sequence I'm getting from the VideoReader?
In other words, is it possible to know which video file is read, and which frames in the video files are read?

I have a model that uses another feature of the video and I need to know what exactly happened to the video so that I can load the correct feature.

Thank you in advance.

**Comment by JanuszL** [comment]
Hi,
It will be possible in 0.18 or if you are inpatient you can test the latest nightly build. Please check the latest [`VideoReader` documentation](https://docs.nvidia.com/deeplearning/sdk/dali-master-branch-user-guide/docs/supported_ops.html#nvidia.dali.ops.VideoReader).
Now you can provide a `file_list` in the format "file_name label frame_start frame_end" so you can assign a unique label to each file or even part of a file, and if you enable `enable_frame_num` then the reader will return the exact frame numbers as well.
In the above way, you should be able to achieve what you are asking for.

**Comment by kiyoon** [comment]
> Now you can provide a `file_list` in the format "file_name label frame_start frame_end" so you can assign a unique label to each file or even part of a file, and if you enable `enable_frame_num` then the reader will return the exact frame numbers as well.
> In the above way, you should be able to achieve what you are asking for.

Oh, that's pretty cool. Thank you!

I read the documentation and I understand that now I can get the frame numbers from the reader. However, is it possible to get a filename or file id so that we know which files are loaded?

The only way I can think of is to use "label" to represent "id" and I get the labels by myself in post. Is there any better way for example directly accessing the pipeline data and figure that out?

**Comment by JanuszL** [comment]
@kiyoon - the only way is to treat the label as a file id.
> "label" to represent "id" and I get the labels by myself in post

Keep in mind that it is possible to assign a label to even part of the video (only selected range of frames), so one file could have more than one label. Could you tell me what exactly you would need to do in post to map ids to labels?

**Comment by kiyoon** [comment]
> Keep in mind that it is possible to assign a label to even part of the video (only selected range of frames), so one file could have more than one label. Could you tell me what exactly you would need to do in post to map ids to labels?

I have a model that needs separate feature as an input. There's an object feature for each video but it changes based on how the video is cut and cropped, because the scene might not contain some objects after cutting. If I know how the frames and resolution are cut, I can generate the right feature (i.e. discard objects out of the scene) from the feature I have.

So I'm okay with having random frame cut, as long as it returns the frame. 

One thing I'm not sure from the documentation is, does `enable_frame_num` return the start frame num (counted from zero)?

I think I made it work. Thanks a lot for your help.

```python
import sys
import copy
from glob import glob
import math
import os

from nvidia.dali.pipeline import Pipeline
from nvidia.dali.plugin import pytorch
import nvidia.dali.ops as ops
import nvidia.dali.types as types

import argparse

parser = argparse.ArgumentParser()
parser.add_argument('--file_list', type=str, default='file_list.txt',
                    help='DALI file_list for VideoReader')
parser.add_argument('--frames', type=int, default = 3,
                    help='num frames in input sequence')
parser.add_argument('--crop_size', type=int, nargs='+', default=[224, 224],
                    help='[height, width] for input crop')
parser.add_argument('--batchsize', type=int, default=1,
                    help='per rank batch size')

args = parser.parse_args()


class VideoReaderPipeline(Pipeline):
    def __init__(self, batch_size, sequence_length, num_threads, device_id, file_list, crop_size):
        super(VideoReaderPipeline, self).__init__(batch_size, num_threads, device_id, seed=12)
        self.reader = ops.VideoReader(device="gpu", file_list=file_list, sequence_length=sequence_length, normalized=False,
                                     random_shuffle=True, image_type=types.RGB, dtype=types.UINT8, initial_fill=16, enable_frame_num=True)
        self.crop = ops.Crop(device="gpu", crop=crop_size, output_dtype=types.FLOAT)
        self.uniform = ops.Uniform(range=(0.0, 1.0))
        self.transpose = ops.Transpose(device="gpu", perm=[3, 0, 1, 2])

    def define_graph(self):
        input = self.reader(name="Reader")
        crop_pos_x = self.uniform()
        crop_pos_y = self.uniform()
        cropped = self.crop(input[0], crop_pos_x=crop_pos_x, crop_pos_y=crop_pos_y)
        output = self.transpose(cropped)
        return output, input[1], input[2], crop_pos_x, crop_pos_y

class DALILoader():
    def __init__(self, batch_size, file_list, sequence_length, crop_size):
        self.pipeline = VideoReaderPipeline(batch_size=batch_size,
                                            sequence_length=sequence_length,
                                            num_threads=2,
                                            device_id=0,
                                            file_list=file_list,
                                            crop_size=crop_size)
        self.pipeline.build()

        self.epoch_size = self.pipeline.epoch_size("Reader")
        self.dali_iterator = pytorch.DALIGenericIterator(self.pipeline,
                                                         ["data", "label", "frame_num", "crop_pos_x", "crop_pos_y"],
                                                         self.epoch_size,
                                                         auto_reset=True)
    def __len__(self):
        return int(self.epoch_size)
    def __iter__(self):
        return self.dali_iterator.__iter__()
    def __next__(self):
        return self.dali_iterator.__next__()


if __name__ == "__main__":
    loader = DALILoader(args.batchsize,
                args.file_list,
                args.frames,
                args.crop_size)
    batches = len(loader)

    batch = next(loader)
    print(batch[0]['data'].shape)
    print(batch[0]['label'])
    print(batch[0]['frame_num'])
    print(batch[0]['crop_pos_x'])
    print(batch[0]['crop_pos_y'])
```



You mean

**Comment by JanuszL** [comment]
> One thing I'm not sure from the documentation is, does enable_frame_num return the start frame num (counted from zero)?

It should.
