### ISSUE TITLE
AttributeError: module 'nvidia.dali.ops' has no attribute 'nvJPEGDecoder'

### ISSUE THREAD

**Issue by redaghanem** [NVIDIA/DALI#1674]

**Comment by JanuszL** [comment]
Hi @redaghanem,
Can you provide a bit more details? What version of DALI do you use? How have you obtained it?
You can also familiarize yourself with the issue-reporting [guide](https://github.com/NVIDIA/DALI#reporting-problems-asking-questions).

**Comment by redaghanem** [comment]
Thanks for reply 

I am trying to run this code

https://github.com/scaleway/frontalization

**Comment by JanuszL** [comment]
Still, it is unclear how you have installed DALI.

**Comment by szalpal** [comment]
@redaghanem ,
You're using nvJPEGDecoder operator, which was deprecated and is removed. You should use [ImageDecoder](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html#nvidia.dali.ops.ImageDecoder) instead.
[This page](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html#) gives you supported operations and details about ImageDecoder

Regards,
szalpal
