### ISSUE TITLE
Return images with different sizes from TF plugin

### ISSUE THREAD

**Issue by milkpot** [NVIDIA/DALI#1690]
I want to return images with different sizes from the pipeline.
Similar to #1676, but with TensorFlow.

TensorFlow Dataset API can return a tensor of unknown shape. For example (TF 2.x eager mode):
```
import tensorflow as tf

def generator():
    for file in ['dog.jpg', 'eagle.jpg', 'person.jpg']:
        data = tf.io.read_file(file)
        image = tf.io.decode_jpeg(data)
        yield image

ds = tf.data.Dataset.from_generator(generator, tf.uint8, [None, None, 3])
for image in ds:
    print(image.shape)
```

Result:
```
(576, 768, 3)
(512, 773, 3)
(424, 640, 3)
```

I cannot do it with DALI:
```
import tensorflow as tf
import nvidia.dali.ops
import nvidia.dali.pipeline
import nvidia.dali.plugin.tf

class MyPipeline(nvidia.dali.pipeline.Pipeline):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.reader = nvidia.dali.ops.FileReader(file_root='.', file_list='filelist.txt')
        self.decoder = nvidia.dali.ops.ImageDecoder(device='mixed')

    def define_graph(self):
        data, label = self.reader()
        image = self.decoder(data)
        return image

pipe = MyPipeline(batch_size=1)
ds = nvidia.dali.plugin.tf.DALIDataset(pipe, batch_size=1, shapes=((1, None, None, 3),), dtypes=(tf.uint8,))
for image, in ds:
    print(image.shape)
```

Result:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 663, in _next_internal
    return self._element_spec._from_compatible_tensor_list(ret)  # pylint: disable=protected-access
AttributeError: 'tuple' object has no attribute '_from_compatible_tensor_list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dali.py", line 19, in <module>
    for image, in ds:
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 630, in __next__
    return self.next()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 674, in next
    return self._next_internal()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 665, in _next_internal
    return structure.from_compatible_tensor_list(self._element_spec, ret)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/data/util/structure.py", line 228, in from_compatible_tensor_list
    element_spec, tensor_list)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/data/util/structure.py", line 203, in _from_tensor_list_helper
    flat_ret.append(decode_fn(component_spec, value))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/data/util/structure.py", line 227, in <lambda>
    lambda spec, value: spec._from_compatible_tensor_list(value),
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/tensor_spec.py", line 177, in _from_compatible_tensor_list
    tensor_list[0].set_shape(self._shape)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 1088, in set_shape
    (self.shape, shape))
ValueError: Tensor's shape () is not compatible with supplied shape (1, None, None, 3)
Segmentation fault (core dumped)
```

For now, I recreate the pipeline everytime I want to change the output size. (I also need to rewrite filelist.txt so that only images for that size are loaded.) It's wasteful...

**Comment by JanuszL** [comment]
Hi,
Currently `nvidia.dali.plugin.tf.DALIDataset` doesn't support shape wildcards in that way. Now you can provide only either full shape or no shape at all.
If you are interested in that particular feature to feel free to dive deep into code and post a PR.
By skimming the code you need deal with shape inference https://github.com/NVIDIA/DALI/blob/master/dali_tf_plugin/dali_dataset_op.cc#L359 but I'm not sure if this only it.
@awolant - any more suggestions?

**Comment by klecki** [comment]
Hi,
we're adding more flexible support for shapes in TF Dataset with #1723. It should land soon in master branch.
The goal here is to allow specifying placeholders for shapes with `None` and match the output of DALI with the shape requested by user by optionally skipping 1-sized dimensions (only from the Pipeline output side), so it matches the Dataset shape in unambiguous way.
It should also allow for automatic shape propagation in some cases.

It also aligns the API with TF's from_generator: https://www.tensorflow.org/api_docs/python/tf/data/Dataset#from_generator

Similar approach to shape will be probably added to TF DALI Op.

**Comment by milkpot** [comment]
I just found that this feature has been added to nightly build and it works well.
It's very helpful.
Thank you so much!

**Comment by klecki** [comment]
Glad that it works, I was intending to write here that it is merged (so as you noticed it's available in the nightly) and will also be a part of 0.20.0 release.
