### ISSUE TITLE
how to parse  `TensorProto` in tfrecord ?

### ISSUE THREAD

**Issue by zhen8838** [NVIDIA/DALI#1696]
I first converted the audio signal into a mel spectrum and made it into a tfrecord form, but it could not save it as a jpg, so I used `tf.io.serialize_tensor()`, and used `tf.io.parse_tensor()` when loading , Is there a function with the same function in DALI?

If not, is there a better way to store or load data?

Thanks

**Comment by JanuszL** [comment]
Hi,
What DALI is tested against is https://www.tensorflow.org/api_docs/python/tf/train/Feature, but it can work with your approach as well, feel free to test. If the way you are using stores the shape and raw data then DALI should be able to consume it.

**Comment by zhen8838** [comment]
Thank you. I can read the string saved in tfrecord, but I lack a function to parse the string to the sensor like imagedecoder. 

I use the function provided by tensorflow to read. The code is as follows:
```python
def TensorDecoder(strings):
    return tf.io.parse_tensor(strings, tf.float32)


class TFRecordPipeline(Pipeline):
    def __init__(self, batch_size, num_threads, device_id):
        super(TFRecordPipeline, self).__init__(batch_size,
                                               num_threads,
                                               device_id, exec_async=False, exec_pipelined=False)
        self.input = ops.TFRecordReader(
            path=tfrecord,
            index_path=tfrecord_idx,
            features={
                'mel_raw': tfrec.FixedLenFeature([], tfrec.string, ''),
                'label': tfrec.VarLenFeature(tfrec.int64, 0),
            }, device='cpu')

        self.decode = ops.PythonFunction(TensorDecoder, 1)

    def define_graph(self):
        inputs = self.input()
        mel = self.decode(inputs['mel_raw'])
        return (img, inputs['label'])

    def iter_setup(self):
        pass


pipe = TFRecordPipeline(8, 4, 0)
pipe.build()
mel, label = pipe.run()
mel.at(0).shape
mel.at(1).shape
label.at(0)
```

Get the error message as:
```sh

from subprocess import call...
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/Documents/K210_Yolo_framework/devlop/dev_dali_tfrecord.py in 
     36 
     37 pipe = TFRecordPipeline(8, 4, 0)
---> 38 pipe.build()
     39 mel, label = pipe.run()
     40 mel.at(0).shape

~/miniconda3/lib/python3.7/site-packages/nvidia/dali/pipeline.py in build(self)
    312 
    313         if not self._prepared:
--> 314             self._prepare_graph()
    315 
    316         self._pipe.Build(self._names_and_devices)

~/miniconda3/lib/python3.7/site-packages/nvidia/dali/pipeline.py in _prepare_graph(self)
    254 
    255         for output in outputs:
--> 256             Edge._validate_edge_reference(output)
    257 
    258         # Backtrack to construct the graph

~/miniconda3/lib/python3.7/site-packages/nvidia/dali/check_edge.py in _validate_edge_reference(edge)
     18         raise TypeError(("Expected outputs of type compatible with \"EdgeReference\"."
     19                 " Received output type with name \"{}\" that does not match.")
---> 20                 .format(type(edge).__name__))
     21     for attr in ["name", "device", "source"]:
     22       if not hasattr(edge, attr):

TypeError: Expected outputs of type compatible with "EdgeReference". Received output type with name "TensorListGPU" that does not match.
```

**Comment by zhen8838** [comment]
By the way, in the [reading example of tfrecord](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/detection_pipeline.html#COCO-Reader-with-augmentations), how to convert the bbox data of tfrecord to bboxes in dali?

I see that COCOreader can read bboxes directly. Is there a function to convert `l, t, r, b`tensor to bboxes?

**Comment by JanuszL** [comment]
Hi,
Regarding the first question try to use `VarLenFeature` and just return inputs['mel_raw'] without any decoding - unless you encoded your spectrogram as JPEG (or any other) images.
Regarding the second one, TFrecord usually stores each coordinate for BBoxs as a separate entry - one entry for l, one for t, one for r and one for b, while dali expects one, K-lenght entry of [l, t, r, b] (K is the number of entries).
Some DALI bbox operators support this absolute coordinates (and there is a switch to select which format is provided) while another only relative (like bbox crop). Currently, there is no conversion function for that, still, if you think it is needed you can make a PR with that functionality.

**Comment by zhen8838** [comment]
Thank you very much for your answer
