### ISSUE TITLE
Adjusting batch size doesn't affect dataloader length

### ISSUE THREAD

**Issue by syb0rg** [NVIDIA/DALI#1717]
I have the following code defined:

```
class VideoPipe(Pipeline):
    def __init__(self, batch_size, num_threads, device_id, data, shuffle):
        super(VideoPipe, self).__init__(batch_size, num_threads, device_id, seed=16)
        self.input = ops.VideoReader(device="gpu", 
                                     filenames=data, 
                                     sequence_length=32,
                                     stride=8,
                                     shard_id=0, 
                                     num_shards=1,
                                     random_shuffle=shuffle, 
                                     initial_fill=1,
                                     image_type=types.RGB)
        self.crop = ops.CropMirrorNormalize(device="gpu", 
                                            crop=[0, 1024, 1024], 
                                            mean=[0.485 * 255,0.456 * 255,0.406 * 255],
                                            std=[0.229 * 255,0.224 * 255,0.225 * 255],
                                            mirror=0,
                                            output_layout="CFHW",
                                            output_dtype=types.FLOAT16)
        self.rand_spatial = ops.Uniform(range=(0.0, 1.0))
        self.rand_temporal = ops.Uniform(range=(0.0, 0.0))


    def define_graph(self):
        frames = self.input(name="Reader")
        output = self.crop(frames, 
                           crop_pos_z=self.rand_temporal(), 
                           crop_pos_x=self.rand_spatial(), 
                           crop_pos_y=self.rand_spatial())
        return output

class VideoLoader():
    def __init__(self, batch_size, file_list):
        self.pipe = VideoPipe(batch_size=batch_size, num_threads=2, device_id=0, data=file_list, shuffle=False)
        self.pipe.build()
        self.epoch_size = self.pipe.epoch_size("Reader")
        self.dali_iterator = pytorch.DALIGenericIterator([self.pipe],
                                                         ["frames"],
                                                         self.epoch_size,
                                                         auto_reset=True)
        
    def __len__(self):
        return int(self.epoch_size)
    
    
    def __iter__(self):
        return self.dali_iterator.__iter__()
```

If I define `train_files` as a list of 400 10 second long videos at 30 FPS and I run `dl = VideoLoader(batch_size=8, train_files)`, no matter what the batch size was set to `len(dl)` will return 400 and always remain the same.  Why is this?  If I define the batch size as 8 as in this example I would expect the length of the data loader to be 50.

**Comment by JanuszL** [comment]
Hi,
```
def __len__(self):
        return int(self.epoch_size)
```
And `len` return the `self.epoch_size` which is the number of samples within the epoch - 400, not the number of iterations.
If you want to get number of iterations you can:
```
math(self.epoch_size / self._num_gpus * self.batch_size)
```

**Comment by syb0rg** [comment]
Gotcha, I figured it was something like that but wanted to confirm.  Thanks!

**Comment by tian1327** [comment]
> Hi,
> 
> ```
> def __len__(self):
>         return int(self.epoch_size)
> ```
> 
> And `len` return the `self.epoch_size` which is the number of samples within the epoch - 400, not the number of iterations. If you want to get number of iterations you can:
> 
> ```
> math(self.epoch_size / self._num_gpus * self.batch_size)
> ```

Shouldn't this be `return int(self.epoch_size / (self._num_gpus * self.batch_size))` ? Thanks

**Comment by JanuszL** [comment]
Hi @tian1327,

Yes, you are correct. However, you don't have to do this calculation manually anymore. The framework iterator, like DALIClassificationIterator from PyTorch, can do it properly and you can just call `len(it)` on it.

**Comment by tian1327** [comment]
@JanuszL Great to know! Thanks! 
Would you be able to point me to the C code or python code in the repo for the `DALIClassificationIterator` class?

**Comment by JanuszL** [comment]
Hi @tian1327,

Please check [https://github.com/NVIDIA/DALI/blob/main/dali/python/nvidia/dali/plugin/pytorch.py](pytorch.py) and [https://github.com/NVIDIA/DALI/blob/main/dali/python/nvidia/dali/plugin/base_iterator.py](base_iterator.py).
