### ISSUE TITLE
Question about data shuffling behavior for TFRecord

### ISSUE THREAD

**Issue by YunseokJANG** [NVIDIA/DALI#1725]
Hi, I have a quick question related to [this issue](https://github.com/NVIDIA/DALI/issues/1268).

If my understanding is correct, TFRecordReader shuffles data based on the 'prefetch_queue_depth' and 'random_shuffle' parameter. In other words, I guess it will do local shuffling, and it is fair then you provide only one TFRecord data since sequential read is the major benefit of using TFRecord.

However, when there is multiple TFRecord with multiple processes (multi-GPU, APEX setting for instance), then there will be two choices: 
- each process chooses **different** TFRecord files (perform random shuffle based on the seed) and performs local shuffling.
- every process grabs the **same** TFRecord by following the list in order and performs local shuffling. 

I guess the second option can be detoured if we shuffle the list before we feed it to the pipeline. But I am not sure which is the way DALI is currently doing. So, I wrote this question to make it clear.
(By the way, If you choose the second one by default, then is it for saving the disk cache? 
Also, is there any best practice example code for the multi-TFRecord case that I can refer to?)

**Comment by JanuszL** [comment]
Hi,
When you provide more than one TFRecord file DALI still threats it just as one entity, each GPU (shard) takes a part of it that could be a subpart of one of this files, or two parts of consecutive ones, then it performs the sequential read and shuffling inside the prefetch buffer. After each epoch (unless you set `stick_to_shard` to true) each GPU moves to the next shard., If you have 2 equally big files and 3 GPUs, 1st uses part of 1st file, 2nd part of 1st and 2nd file, 3rd GPU uses only a part of 2nd file.

**Comment by YunseokJANG** [comment]
Oh, I see.  

In such cases, I guess I need to provide 'num_shards' and 'shard_id' to the TFRecordReader correctly, per each process, so that each process knows where to start. 

And, for the multiple files case, although the list of TFRecord files will be considered as one huge TFRecord file, it will be faster than providing one huge file because it does not need to hold the entire file for each process, especially in multiprocessing case.

I think I am clear. Thanks for your fast response, and please let me know if I miss some key points. 
(Please feel free to close if my understanding is correct ;) )

**Comment by JanuszL** [comment]
> In such cases, I guess I need to provide 'num_shards' and 'shard_id' to the TFRecordReader correctly, per each process, so that each process knows where to start. (in APEX, world_size, and local_rank respectively.)

You need to do that no matter how many TFRecordReader you provides because each GPU/process needs to know where to start.

> And, for the multiple files case, although the list of TFRecord files will be considered as one huge TFRecord file, it will be faster to provide a list of multiple TFRecord files than providing one huge file because it does not need to hold the entire file per each process, especially in multiprocessing case.

We haven't done such a test, usually, you already have multiple TFRecord files so this is what DALI needs to handle to work with existing data. My educated guess is that it should not matter, even if DALI keeps multiple files open (mmaped) their content is not in the memory unless you access it.

**Comment by YunseokJANG** [comment]
Got it. Thanks for your super-fast clarification ;) 

(Closing this issue)
