### ISSUE TITLE
Question: How to use RandomBBoxCrop properly？

### ISSUE THREAD

**Issue by mchl0203** [NVIDIA/DALI#1726]
I want to generate face samples according to the marked bounding box. The format of anno_file like 'img_path x1 x2 w h'.
my code like this:
```
class ExternalSourcePipeline(Pipeline):
    def __init__(self, batch_size, num_threads, device_id, external_data):
         ...
         self.rand_crop = ops.RandomBBoxCrop(
            device="cpu",
            thresholds=[0.6, 0.7],
            ltrb=False,
            allow_no_crop=False,
            num_attempts=100)
    def define_graph(self):
        self.images = self.input()
        self.bboxes = self.input_bboxes()
        self.labels = self.input_label()

        images = self.decode(self.images)
        crop_begin, crop_size, bboxes, labels = self.rand_crop(self.bboxes, self.labels)
        crop_images = self.slice(images, crop_begin, crop_size)

        return (images, bboxes, labels, crop_size, crop_images)
```
The output bboxes value is always unchanged. And if I set allow_no_crop to True, process will break.

how to use it, Or is there a combination of other operators that can return a bbox that is greater than a certain iou threshold according to the marked bounding box?
And how to set the threshold in the image below, or the threshold is 0?
Looking forward to your reply, thanks!
![image](https://user-images.githubusercontent.com/8417221/74099243-6ada7e80-4b5c-11ea-8476-9b45c1357a5d.png)

**Comment by JanuszL** [comment]
Hi,
Please check the documentation of [RandomBBoxCrop operator](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html?highlight=ssdrandomcrop#nvidia.dali.ops.RandomBBoxCrop) and example usage in [SSD network](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/pytorch/single_stage_detector/pytorch_ssd.html).
This operator is designed for SSD where you want to crop an image in such a way that certain properties of bboxes describing it are preserved. I think it may be something else that you are looking for - filtering out bboxes that have a certain IoU with given the marked bounding box.
In such a case, you can try to write a custom, [python operator](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/python_operator/python_operator.html) - slow but flexible, or write a custom [C++ plugin](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/extend/create_a_custom_operator.html) which implements that operation.
