### ISSUE TITLE
Better handling of corrupt videos

### ISSUE THREAD

**Issue by syb0rg** [NVIDIA/DALI#1727]
Let's say I have [a corrupt video](https://github.com/NVIDIA/DALI/files/4177870/corrupt.mp4.zip) in a folder of valid MP4 files, and I pass this example `videos.csv` to `ops.VideoReader`:

```
/home/ubuntu/data/test_videos/dbtbbhakdv.mp4 0
/home/ubuntu/data/test_videos/azsmewqghg.mp4 1
/home/ubuntu/data/test_videos/corrupt.mp4 1
```

It will currently throw an exception:

```
[/opt/dali/dali/operators/reader/loader/video_loader.cc:223] Could not open file /home/ubuntu/data/test_videos/corrupt.mp4 because of Invalid data found when processing input
```

Is there a way I could more gracefully handle these corrupt files?  Either by skipping them and perhaps returning a list of corrupted filenames or by some other means?

**Comment by JanuszL** [comment]
Hi,

In general, it is not possible as readers are separated from the decoders, and when one sample in the batch is corrupted there is no way for the decoder to ask the reader (or any operator to ask the previous one) to provide one more sample to replace the faulty one.
In the case of VideoReder reader and the decoder are coupled so in theory, it is possible, but there is a different important aspect to handle shading. If you have 4 samples (2 good, 2 bad) and 2 GPUs, DALI happen to shard in the way that 1st GPU gets all good, and 2nd all bad then when 2nd GPU will ask for the next, good sample will get the same as 1st GPU killing any sharing as shards will overlaps and decrease (kill randomness).
Those are my quick thought, although if you see any good solution to address this feel free to share or propose a PR.

**Comment by syb0rg** [comment]
How difficult would it be to have the reader check for a corrupt file and then just skip it?  This could then be controlled by a boolean parameter.

**Comment by JanuszL** [comment]
As said. There is more than that, what needs to be considered is sharding which happens before any file is accessed, and you need to take into account not only multi-GPU environment but also a mutlti-node one.
As DALI is open source we would be more than happy to review and accept any PR that would introduce such functionality.

**Comment by syb0rg** [comment]
Closing for now, as filtering can be done beforehand to create a "clean" files list to mitigate.

In a distributed model there is a manager and the subsequent workers.  Either the managing task can handle the corrupt videos before distributing the workload, or the individual workers could handle the corrupt videos.  There are pros and cons to both, some pointed out in your comments above.

**Comment by JanuszL** [comment]
I glad you managed to work this problem around.
