### ISSUE TITLE
Multi-GPU reading in super-resolution example

### ISSUE THREAD

**Issue by kiyoon** [NVIDIA/DALI#1743]
Hi, I appreciate your awesome work and support.
I have a question about the supperresolution example.

In NVVL example, they seem to use multi-gpu reading.
```python
devide_id=args.rank % 8
```
https://github.com/NVIDIA/nvvl/blob/a94c7493ec9f309cc54acf81a66c62a068a06962/examples/pytorch_superres/dataloading/dataloaders.py#L122-L133

However, in the DALI example, device_id is always set to zero, which means only the master process will be reading the data (am I right?)
https://github.com/NVIDIA/DALI/blob/6d532d49328979325fa3ae8b5d58be95bab2364f/docs/examples/use_cases/video_superres/dataloading/dataloaders.py#L32-L41

Is there any reason that this been changed?

**Comment by JanuszL** [comment]
Hi,
The example in DALI is just a showcase. If you want to have 100% alignment with nvvl example you need:
- change this hardcoded `0` to the actual device id
- set in the VideoReader operator `shard_id` and `num_shards` to the actual values
@Kh4L - have I missed anything?

**Comment by kiyoon** [comment]
Thanks for your kind answer.
I should be able to reproduce it comparing with the NVVL example.
If I manage to do it, I'll share my solution here.

**Comment by kiyoon** [comment]
Hi,

Why does DALI always return a list of length 1?
For example, you always need to access to the 0-th element of the input data.
https://github.com/NVIDIA/DALI/blob/e10a36556b7d900c78119611cba4c86dacbc7de5/docs/examples/video/superres_pytorch/main.py#L147

I thought it was something to do with multiprocessing, but changing the shard_id only changes what part of the data you'll read and it will still have a length of 1. Is it just safe to always access to the 0-th element or should I be careful of the case where the list size is longer than 1?

**Comment by kiyoon** [comment]
@JanuszL Also, increasing the `num_shards` argument doesn't change the `pipeline.epoch_size`. How do I get the size of the shard, not the size of the whole epoch?

**Comment by JanuszL** [comment]
> Why does DALI always return a list of length 1?
> For example, you always need to access to the 0-th element of the input data.

This `0` is the index of available GPU. DALIIterator can have more than one pipeline inside (for more than 1 GPU). For 1 GPU data is always available at index 0.
`pipeline.epoch_size` is the global size of the epoch. You need to scale it down by dividing by the number of shards.

Regarding the formula if you use `pad_last_batch` parameter of the reader then the formula is:
```
math.ceil(self.epoch_size / num_shards)
```
If not then the shard sizes won't be equal and are calculated as a:
```
int(self.epoch_size * (shard_id + 1) / shard_num) - int(self.epoch_size * shard_id / shard_num)
```

**Comment by kiyoon** [comment]
I distribute the data over multiple processes so it is 1 GPU data per process, therefore I should be able to access at index 0.

Also, then the shard is distributed as evenly as possible. I thought it is the same size except for the last shard.

Thank you!
