### ISSUE TITLE
Sample-level control with TFRecordReader op

### ISSUE THREAD

**Issue by ben0it8** [NVIDIA/DALI#1744]
Assume I a TFRecord dataset of 6 samples in 2 record files, for which I have a table where I store the byte positions and lengths in the corresponding index files:

|   | byte_pos | byte_len | index_file | record_file |
|---|----------|----------|------------|-------------|
| 1 | 0        | 100      | idx-1.idx  | data-1.rec  |
| 2 | 100      | 200      | idx-1.idx  | data-1.rec  |
| 3 | 200      | 300      | idx-1.idx  | data-1.rec  |
| 4 | 300      | 400      | idx-1.idx  | data-1.rec  |
| 5 | 0        | 100      | idx-2.idx  | data-2.rec  |
| 6 | 100      | 200      | idx-2.idx  | data-2.rec  |

Now, lets say I only want to read certain samples from a record file, e.g. sample 2 and 3 from record file #1 and sample 6 from record file #2. 
I can just re-write the corresponding index files and try to pass them to TFRecordReader, but reading fails, I reckon for the bytes not being contiuous.

Based on [the TFRecord docs](https://www.tensorflow.org/tutorials/load_data/tfrecord#tfrecords_format_details) I'm afraid this is not possible, but I wanted to check with you.
Do you have any workaround in mind that would allow me to have a sample-level control over what's being read **after** the records are written? 

Cheers,
Oliver

**Comment by JanuszL** [comment]
Hi,
Yes. It doesn't work now, https://github.com/NVIDIA/DALI/pull/1747 should enable this.
Please check the nightly after it is merged.

**Comment by ben0it8** [comment]
Amazing, thanks Janusz, I'll try it with the nightly! :+1:
