### ISSUE TITLE
test_plugin_manager.py fails on Linux RHEL 7.7 x86 and PowerPC

### ISSUE THREAD

**Issue by npanpaliya** [NVIDIA/DALI#1748]
We built conda package of DALI 0.13, 0.17 and 0.18 for Linux x86 and ppc64le architecture. When test_plugin_manager.py is run with any of these dali versions, it fails with below error -

```
(testdalinew) [builder@b606c8864fb8 DALI]$ nosetests dali/test/python/test_plugin_manager.py 
.F....
======================================================================
FAIL: test_load_existing_but_not_a_library (test_plugin_manager.TestLoadedPlugin)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/builder/DALI/dali/test/python/test_plugin_manager.py", line 83, in test_load_existing_but_not_a_library
    plugin_manager.load_library( test_bin_dir + "/dali_test.bin" )
AssertionError: RuntimeError not raised

----------------------------------------------------------------------
Ran 6 tests in 0.843s

FAILED (failures=1)
```

dlopen call is expected to fail with executable and the test expects that it should raise a RuntimeError, but it is not throwing any error. 
I checked the other test binaries that are being generated in the same directory like `dali_core_test.bin` or `dali_benchmark.bin`. The test fails with all the built test binaries (i.e. dlopen is able to load all of them successfully). 
I don't see any existing issue on this test which makes me assume that it has been passing so far for all. Not sure what different are we doing and the reason behind the failure.

Please help us to get this problem resolved.

**Comment by JanuszL** [comment]
I double-checked that. It seems that this test fails for my local Ubuntu-based build, but binaries compiled with manylinux docker image (the one we are using for the official builds) works as expected. I have fixed that in https://github.com/NVIDIA/DALI/pull/1749.

**Comment by npanpaliya** [comment]
Thank you @JanuszL .

**Comment by npanpaliya** [comment]
@JanuszL - Could you please take a look at https://github.com/NVIDIA/DALI/issues/1750 one too?

**Comment by npanpaliya** [comment]
This issue is not just on Power. It's also seen on x86.

**Comment by JanuszL** [comment]
> This issue is not just on Power. It's also seen on x86.

 This tag is rather to track customer than the actual architecture.

**Comment by JanuszL** [comment]
DALI 0.20 is out. and should include a fix for this bug. Closing.
