### ISSUE TITLE
Feature for sampling rate of indexes for TFRecord

### ISSUE THREAD

**Issue by kkihara** [NVIDIA/DALI#1754]
Hi, I am trying to dynamically control the random sample rate of indices. For instance, if I had a index file representing 4 data points, I would want to control this by inputting a sample rate array of size 4 ([0.1, 0.2, 0.3, 0.4]). In addition, after each batch or certain iteration, I would want to be able to change the sample rate array.

The use case would be for online hard example mining, but it may also be useful for other use cases as well. Could this be a possible addition?

Thanks

**Comment by JanuszL** [comment]
Hi,
It is not possible now in a straightforward way. The only solution that comes to my mind is to create an index file with 10 indices - 1 of 1st, 2 of 2nd, 3 of 3rd and 4 of 4rd. Then you would have the desired sampling rate in the prefetch buffer used for sampling (this would also require https://github.com/NVIDIA/DALI/pull/1747 to be merged first). However, I don't have any idea how to change that in the runtime.
I agree that TFRecord reader is not that flexible but I think it is not possible to make it in the way that any need, similar to yours, could be met, as it basically requires to program logic in some language. The most flexible way would be to use the ExternalSource and then feed the data in any way you like.

**Comment by kkihara** [comment]
Thanks for the response. I realized I could do what I wanted within the minibatch. [ExternalSource](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html#nvidia.dali.ops.ExternalSource) seems to be a good option for the original ask though.
