### ISSUE TITLE
Access to GPU Tensor pointer in TensorGPUList

### ISSUE THREAD

**Issue by mnicely** [NVIDIA/DALI#1765]
Is it possible to retrieve a pointer to each individual TensorGPU in a TensorGPUList? Similar to **.at()** for TensorCPUList. My understanding is that data in allocated using _cudaMalloc_. I need the pointer so I can do a copy to a _cudaMallocPitch_ location and then process an image with custom cuda kernels.

**Comment by JanuszL** [comment]
For TensorListCPU you can extract each tensor using `[idx]` notation and treat is a NumPy array which should return underlying pointer in the [following way](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.ctypes.html).
The easiest would be probably to implement 2DLpack for tensors and TensorList and hide the pointer itself into that @banasraf?
If not we can add `c_ptr` attribute that would return a raw pointer to TensorList or Tensor, @mzient?

**Comment by mzient** [comment]
If all that's needed is a pointer, then I don't know if DLPack is not too big a gun. We won't hurt to have both, though - I think that `c_ptr` sounds enough like "danger! you're  on your own here", whereas might seem safer than it is (or we'd have to use managed DLPack, which may be an overkill in this case).

**Comment by banasraf** [comment]
Also, DLPack Tensors are not meant to be handled from python level. It's not possible (easy) to retrieve a data pointer from DLPack Tensor in python. Although, if you want to pass it to C++, DLPack has a handful of useful information, like device id, shape and stride. 

Also I don't see any problem with implementing both `c_ptr` and `as_dlpack`. It shouldn't require much effort.

**Comment by JanuszL** [comment]
> Also, DLPack Tensors are not meant to be handled from python level. It's not possible (easy) to retrieve a data pointer from DLPack Tensor in python. Although, if you want to pass it to C++, DLPack has a handful of useful information, like device id, shape and stride.

I think this is an example how to do it https://github.com/dmlc/dlpack/blob/master/apps/from_numpy/main.py.

**Comment by JanuszL** [comment]
It is available in 0.20.
