### ISSUE TITLE
Use (12 + device_id) as the seed for pipes

### ISSUE THREAD

**Issue by alexbrowngh** [NVIDIA/DALI#1774]
I came across the examples and found that most of them use `12 + device_id` as the seed for pipes.  For example, `super(HybridTrainPipe, self).__init__(batch_size, num_threads, device_id, seed=12 + device_id)`. Because training involves shuffling the data and we use the sharding technique for using multiple GPUs, will this lead to the result that different GPUs use the same image?

If `12 + device_id` is correct, should we use `12 + rank` as the seed, instead of `12 + local_rank`, when using multiple nodes?

**Comment by JanuszL** [comment]
Hi,
This is just an example, but you can use any seed you like. If you leave it empty the system time would be used.
In some rare cases, when the data set is not divisible by the shard number it may happen than some sample could be picked up in the same epoch by different GPUs, but the chance is low and is not affected i  any predictible way by the seed value.

**Comment by alexbrowngh** [comment]
@JanuszL Thanks for your reply. I know the seed 12 is just an example, but I wonder how this will influence the shards. For example, we have 2 GPUs (GPU1 and GPU2) and 4 Images (Image 1,2,3,4). Because we use data shuffling for the images (for training), GPU 1 may see the image order 4,3,2,1, and GPU 2 may see the image order 1,2,3,4. The GPU 1 then takes the shard 1, which is image 4,3. The GPU 2 then takes the shard 2, which is image 3,4. In this case, all the GPUs process the same images and half of the dataset is not used.

I wonder whether
1) this is the case when we use different seeds for different GPUs?
2) if yes, whether this can be solved by setting the same seed?

**Comment by JanuszL** [comment]
@alexbrowngh - it is not the case. Sharing is deterministic. If the data set has samples 1,2,3,4 - then GPU0 gets 1,2 and GPU1 3,4 in the first epoch. For separate files, there is deterministic preshuffling (seed is hardcoded and the same for all DALI instances) so GPU0 won't get all images with label 0 and GPU1 with label 1, for containers like TFRecord or RecordIO DALI expects that they are preshuffled already. Then when reading DALI uses a prefetch buffer of default size 1024 which is filled by the sequential reading, then it is randomly sampled to form a batch (seed matter in this case). Still, shards don't overlap. So there is a strong guarantee that GPU0 will first use all samples 1....N/2, and GPU1 N/2+1....N first. If they run out of it (in case of an odd number of samples in this particular example) then some sample at the shard boundary may be picked up by both GPUs in the same epoch. To prevent this you can ask the reader to pad missing samples, instead of crossing the shard boundary.

**Comment by alexbrowngh** [comment]
@JanuszL I see. The conclusion is that all the GPUs will use the same hardcoded seed for data shuffling, which is independent of the seed I give to the __init__ function, and no matter it is the case of multiple GPUs or multiple instances (i.e., machines). Do I understand it correctly?

**Comment by JanuszL** [comment]
> The conclusion is that all the GPUs will use the same hardcoded seed for data shuffling, which is independent of the seed I give to the init function, and no matter it is the case of multiple GPUs or multiple instances (i.e., machines). Do I understand it correctly

The opposite:-)
Let me give you some examples. You have a list of separate files with labels:
`[A:0, B:0, C:0, D:1, E:1, F:1]`
FileReader does deterministic file shuffling first so every DALI instance sees the same order:
`[E:1, B:0, D:1, A:0, C:0, F:1]`
Then shards are made (the division is virtual, just every GPU starts with a different starting index in the data set:
```
GPU0 [[E:1, B:0, D:1] -> start_idx = 0
GPU1 [A:0, C:0, F:1] -> start_idx = 3
```
Then each GPU reads shards sequentially to fill the internal buffer which is randomly sampled - now seed is taken into account. When the epoch ends each GPU move to the next shard.
When you are using data set containers like TFRecord, RecordIO or LMDB the data inside is already preshuffled `[E:1, B:0, D:1, A:0, C:0, F:1]` as random access to this containers is slow.

**Comment by alexbrowngh** [comment]
Awesome! Currently, I use
`self.input = ops.FileReader(file_root=data_dir, shard_id=rank, num_shards=world_size, shuffle_after_epoch=True)`.

Two quick follow-up questions:
- Since I set shuffle_after_epoch to True, is the data shuffling behavior deterministic in all the epochs? Or just the first epoch?
- I use multiple GPUs on multiple machines. Is the deterministic behavior on data shuffling guaranteed even on different machines?

**Comment by JanuszL** [comment]
> * Since I set shuffle_after_epoch to True, is the data shuffling behavior deterministic in all the epochs? Or just the first epoch?
> 
> * I use multiple GPUs on multiple machines. Is the deterministic behavior on data shuffling guaranteed even on different machines?

Yes, all epoch. Yes, all GPUs instances. If not then it wouldn't work.
In this case, after each epoch, its number is added to the hard-coded seed used for shuffling the dataset - https://github.com/NVIDIA/DALI/blob/cb77222a4c820863705094dd99019ed4576db52c/dali/operators/reader/loader/file_loader.h#L128 (it is the same across all DALI instances).
