### ISSUE TITLE
【Question】pytorch distributed

### ISSUE THREAD

**Issue by wuzhi19931128** [NVIDIA/DALI#1776]
Hi, I have a question about distributed train process if DALI in pytorch. And I read most answers in issues and Here is my understanding. But I don't konw whether it's right.

In my case ,I have a server with 8 GPU.  Like everyone else, the word_size is 1 so it will not use apex DDP in resnet50 example file . But actually DALI use 8 GPU in data process but model just forward in 1 GPU,Am I right?  So we don't need to care about things like torch.utils.data.distributed.DistributedSampler and DALI have done it automatic.

Then there is a question. If I use DDP(model) or DataParallel(model) , will model trained in 8GPUs?
Or it will damage the performance?

Thanks if you can answer it.

**Comment by JanuszL** [comment]
Hi,
The word size should be equal to the number of GPUs - 8 in your case.
It would be better to ask on PyTorch forum, but I think DDP is a recommended way to train in multi GPU environment, even on single node as it has better load balancing.
Still you can use DALI in DP scenario as well, you need to create a list of pipelines and pass it to one DLIIterator.
Regarding the distributed sampler DALI does all the job - all it needs is shard id and the number of shards. Then each DALI instance pick the right shard and comparing to distributed sampler no other communication between DALI instances is needed.

**Comment by wuzhi19931128** [comment]
Hi ,I found more examples in DeepLearingExamples and it works , Thank you .

**Comment by December-boy** [comment]
@wuzhi19931128 Hi, could you share the example, Thank you.

**Comment by JanuszL** [comment]
@December-boy - please check https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch.
