### ISSUE TITLE
Can I install older version pre-built DALI？

### ISSUE THREAD

**Issue by KleinXin** [NVIDIA/DALI#1777]
It seems this link does not work any more

pip install --extra-index-url https://developer.download.nvidia.com/compute/redist/cuda/10.0 nvidia-dali==0.13.0

**Comment by JanuszL** [comment]
Hi,
What error do you get and what system so you have (architecture, python version, OS)?
We had a similar issue with the python 3.8  user - python 3.8 is not yet supported, if this is your case please use 3.7 at most.

**Comment by KleinXin** [comment]
> Hi,
> What error do you get and what system so you have (architecture, python version, OS)?
> We had a similar issue with the python 3.8 user - python 3.8 is not yet supported, if this is your case please use 3.7 at most.

Thank you for you reply!
It seems something wrong with my proxy.
Just wait a moment and I will close this issue if it's the problem of my proxy
By the way, I am using python 3.6.10

**Comment by JanuszL** [comment]
How about the direct link https://developer.download.nvidia.com/compute/redist/cuda/10.0/nvidia-dali/?

**Comment by KleinXin** [comment]
> How about the direct link https://developer.download.nvidia.com/compute/redist/cuda/10.0/nvidia-dali/?

Now I am sure it is the problem of my proxy.
The link for version 0.13.0 works fine.
Thank you very much!
