### ISSUE TITLE
Do the ops (ops.Resize, ops.Rotate ...) only support unit8 type?

### ISSUE THREAD

**Issue by Zzlongjuanfeng** [NVIDIA/DALI#1780]
When I using Resize/Rotate ops to augment input data with a type of int16/int32. I get an error like
`RuntimeError: Critical error in pipeline: [/opt/dali/dali/operators/resize/resize.cu:43] Assert on "IsType<uint8>(input.type())" failed: Expected input data as uint8.`
1. Do the ops only support uint8 input data now?
2. How could I use DALI loading and augmenting int32 images?

**Comment by JanuszL** [comment]
Hi,
Currently, those ops only support uint8, but the code is more generic and lifting that limitation should not be that difficult. @mzient - what do you think?

**Comment by mzient** [comment]
1. Resize is only uint8. WarpAffine and Rotate handle uint8, int16, int32 and float (no uint16 and no uint32). Lifting the constraint should not pose a big problem.
2. Currently we can only load int8 although int16 is on the horizon; int32 is rather uncommon and was never paid much attention. What do you need it for?

**Comment by Zzlongjuanfeng** [comment]
Thanks for replying.
I am using DALI to load an RGB and GRAY image pair, where RGB is uint8 and GRAY is int16.  So int16 is enough for me. Could you lift the constraint of uint8?
Besides, the (RBG, GRAY) pair should have the same augmentation on [Resize, Crop]. Does DALI support that?

**Comment by JanuszL** [comment]
Hi,
It is a valid and useful request, and we would be more than happy to accept any PR enabling this.
Regarding crop and resize if you provide the same arguments to both transformations (for images and masks then it should work (keep in mind that having an interpolation for image resize if fine, but for the mask, you probably want to apply the nearest neighbor strategy).

**Comment by Zzlongjuanfeng** [comment]
Hi,
Recently, I tried to lift the uint8 constraint in Resize operation. What I did is comment this line `DALI_ENFORCE(IsType<uint8>(input.type()), "Expected input data as uint8.");` in resize.cu and resize.cc.
And I get a new error, that is `RuntimeError: Critical error in pipeline: [/opt/dali/dali/pipeline/data/buffer.h:114] Assert on "type_.id() == TypeTable::GetTypeID<T>()" failed: Calling type does not match buffer data type: uint8 v. int16`
It seems that the input is still constrained to be uint8.
How could I lift this constraint properly?

**Comment by JanuszL** [comment]
Hi,
The enforce you have removed it to warn that the variant is not implemented. Removing it won't help. What you need to do is to extend the implementation by other data types. For example, [resize_base.cc](https://github.com/NVIDIA/DALI/blob/master/dali/operators/image/resize/resize_base.cc#L91) uses uint8 all around, so you need to change the actual implementation.

**Comment by JanuszL** [comment]
Hi,
Resize now supports `uint8, int16, uint16 and float` types.
Please check if that works for you.
