### ISSUE TITLE
Label augmentation methods

### ISSUE THREAD

**Issue by HayashiRS** [NVIDIA/DALI#1781]
I am attempting to convert the image-label augmentation algorithm we use to DALI in order to overcome the CPU bottleneck through augmentation processing, but ran into a brick wall of sorts.

While DALI works remarkably for loading images and applying augmentations to them, for the semantic segmentation work I do, it is necessary to apply the exact same augmentations to the label, where the label is expressed as a list of coordinates that bound the polygons.

I have tried passing in the arguments for the transformation as labels of sorts, but doing so in the __init__ method of the pipeline appears to simply use the very first argument and apply it to the whole dataset, since the initialization occurs only when the pipeline is instantiated, but there doesn't seem to be a way to pass in arguments within the define_graph method.

I have also tried setting the argument as a random function and trying to output the result of the random function together with the image (so that the resultant arguments can be used to subsequently transform the coordinates), but received: 

> TypeError: Expected outputs of type compatible with "EdgeReference". Received output type with name "float" that does not match.

That leaves the only working possibilities I can think of as:
1. Generate a uint8 black-white image mask from the coordinates and pass this into DALI as a tuple together with the image, but this essentially doubles the amount of processing required and wipes out any speed gain from DALI.
2. Write a custom ops Function to process the coordinates with within the pipeline, but this requires C++ knowledge I don't have.

Are there any other workarounds to doing this, or is it not possible to speed up semantic segmentation tasks with DALI out-of-the-box at the moment?

**Comment by JanuszL** [comment]
Hi,
DALI doesn't support any transformation for polygons. One solution is to render mask as an image and process them in the same way as data you segment - in that case, you need to render them offline or write a custom operator for that.
Either way, to make it performant you need to develop some operators in C++. In the meantime you can also experiment with python operators - it won't be fast but at least you can check the approach and the correctness.
If anyone would like to contribute such functionality we would be more than happy to review such PR.

**Comment by HayashiRS** [comment]
Thanks for the answer thus far.

May I check if there is any way of outputting the value of the argument (or the random seed used to generate it) used by an ops function as well, or is it not possible to convert it into the expected EdgeReference output type?

**Comment by JanuszL** [comment]
If I understand correctly your question, yes you can output the values from any random generator as a normal DALI pipeline output. Or you are asking about obtaining some internal state from any operator?

**Comment by JanuszL** [comment]
Hi @HayashiRS,

[This example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/math/geometric_transforms.html#) shows how to transform points together with the image.
