### ISSUE TITLE
When using a GPU, the result of the flip operation is incorrect.

### ISSUE THREAD

**Issue by hongdayu** [NVIDIA/DALI#1790]
When using a GPU, the result of the flip operation is incorrect.
Test also failed！！！
tests/test_op_flip.py::test_flip_daliCpu_vs_pyCpu PASSED                 [ 20%]
tests/test_op_flip.py::test_flip_cpu_vs_gpu FAILED                       [ 40%]
tests/test_op_flip.py::test_flip_vs_numpy_horizontal FAILED              [ 60%]
tests/test_op_flip.py::test_flip_vs_numpy_vertical FAILED                [ 80%]
tests/test_op_flip.py::test_flip_vs_numpy_rotate FAILED                  [100%]WARNING: Failed to

**Comment by JanuszL** [comment]
Hi @hongdayu,
Could you tell me more about what you are testing and how your tests look like?
Please follow [this guideline](https://github.com/NVIDIA/DALI#reporting-problems-asking-questions) when reporting an issue.

**Comment by JanuszL** [comment]
Please reopen when you can share a repro.
