### ISSUE TITLE
How to  exactly restore  the reader shuffle queue ?

### ISSUE THREAD

**Issue by ghost** [NVIDIA/DALI#1791]
As there is shuffle queue that read sample into CPU mem and async cp to GPU. 
Because some crash will happen during train step， and we expect save the queue state to a ckpt， after another  train process restart， the ckpt can be load and train  step continue with last shuffer queue read index。

As shuffle is very  necessary for model precision ，  the samples dataset  is very large to one  billion images,  it is inefficiency shuffle offline.

**Comment by JanuszL** [comment]
Hi,
Currently, it is not possible to dump and restore the shuffling queue state.
What you can do now it to use the same seed to the reader, and just run the data pipeline up to the checkpoint without feeding data to the network, it won't be as fast as a plain seek but still, you would save training time.
It should be possible to ask the reader to run dry for N iterations to restore the state from the N'th iteration, and we would be more than happy to accept any PR introducing such change.

**Comment by JanuszL** [comment]
Hi @florischabert,

Now you can save and restore DALI execution state thanks to [checkpointing](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/advanced_topics_checkpointing.html.
