### ISSUE TITLE
ops.Transpose maybe have a bug

### ISSUE THREAD

**Issue by AaronStuart** [NVIDIA/DALI#1802]
Hi, 
`b = ops.Transpose(perm = [2, 0, 1])(a)`, a have a shape of `[H, W, 1]`, but `a[:, :, 0]` is not equal to `b[0, :, :]`, is this a bug?
My dali version is 0.18

**Comment by JanuszL** [comment]
Hi,
It is indeed a bug. We will look into this.
Thank you for reporting.

**Comment by klecki** [comment]
Hi, should be fixed in  #1817. I will let you know when it lands in the nightly channel.

**Comment by klecki** [comment]
#1817 was merged and should be available in our nightly and weekly channels: https://docs.nvidia.com/deeplearning/sdk/dali-master-branch-user-guide/docs/installation.html#nightly-and-weekly-release-channels
