### ISSUE TITLE
what does the device_memory_padding and host_memory_padding mean?

### ISSUE THREAD

**Issue by irexyc** [NVIDIA/DALI#1818]
HI,

I read the nvJPEG Library Guide and the DALI document, but can't figure out the does that two functions mean.

Could someone please explain how to get the number in this code https://github.com/makslevental/atlas_sr/blob/606f1f2c2cee8a9490fdab8f65461d77cbd878f0/data_utils/dali.py#L43

**Comment by JanuszL** [comment]
Hi,
It translates to https://docs.nvidia.com/cuda/archive/10.1/nvjpeg/index.html#nvjpeg-set-device-mem-padding. nvJPEG needs to host and device buffers for decoding. As any GPU memory allocation is time-consuming by setting these values it is possible to preallocate nvJPEG internal buffers so no additional reallocation would happen during its operation. Values present there should more or less guarantee that for used dataset internal buffer would suffice and no reallocation should happen in the middle. These values need to be selected empirically.Link to CUDA dynamically

**Comment by irexyc** [comment]
Hi, JanuszL
Thanks for your reply, but I am still quite understand. 

According to the [cuda sample code ](https://github.com/NVIDIA/CUDALibrarySamples/blob/aa0e50fcefa026ebf11990eb659cf43d3e50e34d/nvJPEG/nvJPEG-Decoder/nvjpegDecoder.cpp#L157)，everytime before to decode some jpeg images, it use `cudaMalloc` to allocate memory and after decoding, it use `cudaFree` to free the cuda memory. I know one can use user define `nvjpegPinnedAllocator_t` or `nvjpegDevAllocator_t` to construct memory pool like cnmem to reduce memory allocation. 

So, what is the padding there used for? I searched the google but find nothing.

**Comment by JanuszL** [comment]
Hi.,
The buffer you allocate is only for output, but there are internal buffers allocated by nvJPEG used for intermediate results - like decoded coefficients. You don't have control over that buffer, so what you can do is ask nvjPEG to preallocate them using this `padding` option or provide custom allocators and try cnmem.

**Comment by irexyc** [comment]
Thanks you very much, I get the point.

And I have one last question about it. Is there a formula to calculate the padding to my own dataset?

**Comment by JanuszL** [comment]
I don't think there is anything explicit - it depends on chroma subsampling and the size of raw data after Huffman coefficients decoding but I don't exactly know how to connect these two.
The easiest would be to write a simple custom decoding app using nvJPEG with a custom memory allocation and see what is the maximum allocation value for host and device memory for your data set (I would start with extending  [cuda sample code ](https://github.com/NVIDIA/CUDALibrarySamples/blob/aa0e50fcefa026ebf11990eb659cf43d3e50e34d/nvJPEG/nvJPEG-Decoder/nvjpegDecoder.cpp#L157)).
These parameters are mostly for fine-tuning. For normal usage, it is not that critical to have them set (unless you are aiming to squeeze last GPU cycles).
