### ISSUE TITLE
How to use ops.PythonFunction to preprocess input data?

### ISSUE THREAD

**Issue by Approximetal** [NVIDIA/DALI#1824]
My model is based on [Tacotron2](https://github.com/NVIDIA/tacotron2), I'm trying to use DALI to solve my CPU bound issue. But it seems there is no function avilable in ops library, so I tried to use `ops.PythonFunction`, but I got this error`RuntimeError: PythonFunction can be used only in pipelines with 'exec_async' and 'exec_pipelined' set to False.` 
Also I saw the [document](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html?highlight=torchpythonfunction#nvidia.dali.ops.PythonFunction) said "For now, this operator can be used only in pipelines with exec_async=False and exec_pipelined=False specified. Due to inferior performance, it is intended mostly for prototyping and debugging." Is that means even I can use PythonFunction, it won't enhance the performance?
I would like to ask how can I preprocess data as [TextMelCollate](https://github.com/NVIDIA/tacotron2/blob/91ae5b57b0ff33cc17425f86e54354eb76d2b6b1/data_utils.py#L67) does in DALI Pipline? Or any other methed I can use to solve CPU bound? 
(P.S. I can't change hardware devices nor occupy RAM as disc)
Thank you!

**Comment by JanuszL** [comment]
Hi,
You can still develop your [custom operator](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/custom_operations/custom_operator/create_a_custom_operator.html).

**Comment by JanuszL** [comment]
Hi @Approximetal,

Now the python function can be executed asynchronously in the pipeline mode.
