### ISSUE TITLE
Using or adapting image operators for videos

### ISSUE THREAD

**Issue by rdevon** [NVIDIA/DALI#1825]
Working with Dali for augmentation, it appears that most operators are incompatible with video, re https://github.com/NVIDIA/DALI/issues/1247. This includes other useful operators such as colorjitter, normalize crop etc. These operators would be useful for video, particularly because on-the-fly video preprocessing can be especially taxing for CPU, and researchers might want similar sorts of preprocessing pipelines as ImageNet.

So the question is: are there simple, straightforward guidelines for adapting existing image operators for video or for expanding said operators for using video?

**Comment by rdevon** [comment]
For instance, it would be useful to be able to combine ideas from:
https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/video/video_reader_simple_example.html
with
https://github.com/NVIDIA/DALI/blob/2a5e14c6946334b2459de6d4c01a21b1f56f3953/docs/examples/pytorch/main.py

**Comment by JanuszL** [comment]
Hi,
That is true, not many operators yet support video. We plan to change that but it is hard to tell when the support would be extended. The first operator on our ToDo list is Resize.
Although much of the currently available operators are going to be reused for the video, still some custom code paths for handling sequences needs to be developed.

**Comment by rdevon** [comment]
So I noticed that there's a PythonFunction operator, so I was curious if one could use said operator to loop through a sequence of images from a VideoReader, applying image-valid operators to each image (or if this is even a good idea).

Other things that one can do, if one is fine with using the same color jitter parameters across a sequence, is to reshape the temporal dimension into one of the spatial ones. But this requires the ability to perform this manipulation in addition to the color jitter operator.

**Comment by JanuszL** [comment]
> So I noticed that there's a PythonFunction operator, so I was curious if one could use said operator to loop through a sequence of images from a VideoReader, applying image-valid operators to each image (or if this is even a good idea).

It is possible, and but the Python operator is mostly meant for prototyping and debugging, and its permanence is not that great.

> Other things that one can do, if one is fine with using the same color jitter parameters across a sequence, is to reshape the temporal dimension into one of the spatial ones. But this requires the ability to perform this manipulation in addition to the color jitter operator.

I don't think it is doable now.

To sum up, if you want to see how that works try the Python operator. To get the best performance you need to develop custom, native operator or extend the existing one.

**Comment by JanuszL** [comment]
Most DALI operators support video now, [even temporal operations are supported](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/sequence_processing/video/video_processing_per_frame_arguments.html).
