### ISSUE TITLE
make error when creating custom ops

### ISSUE THREAD

**Issue by h-bo** [NVIDIA/DALI#1827]
fatal error: dali/pipeline/operators/operator.h: No such file or directory
 #include "dali/pipeline/operators/operator.h"
                                              ^
compilation terminated.

environment:
>>> from __future__ import print_function
>>> import nvidia.dali.sysconfig as sysconfig
>>> print(sysconfig.get_include_dir())
*/lib/python3.7/site-packages/nvidia/dali/include
>>> print(sysconfig.get_lib_dir())
*/lib/python3.7/site-packages/nvidia/dali
>>> print(sysconfig.get_compile_flags())
*/lib/python3.7/site-packages/nvidia/dali/include', '-D_GLIBCXX_USE_CXX11_ABI=0']
>>> print(sysconfig.get_link_flags())
['-L*/lib/python3.7/site-packages/nvidia/dali', '-ldali']

Thanks for any help

**Comment by JanuszL** [comment]
HI,
I think your include should be:
`#include "dali/pipeline/operators/operator.h`

**Comment by h-bo** [comment]
> HI,
> I think your include should be:
> `#include "dali/pipeline/operators/operator.h`

Hi
That's same as what I write?

**Comment by JanuszL** [comment]
Sorry, typo `operators` -> `operator`.

**Comment by h-bo** [comment]
That's right
