### ISSUE TITLE
Pipeline SetExternalInput with void * Support

### ISSUE THREAD

**Issue by kurff** [NVIDIA/DALI#1830]
Pipeline adds external input only support data structure: TensorList<CPUBackend> and vector<Tensor<CPUBackend>>. Can it support data with pointer (void *) which make DALI more flexible?

**Comment by JanuszL** [comment]
Hi,
From python level, you can create a numpy array from this void pointer [like this](https://stackoverflow.com/questions/39376892/creating-a-numpy-array-directly-from-array-interface) or [this](https://github.com/NVIDIA/DALI/blob/master/dali/test/python/test_utils.py#L246L259) and then DALI will automatically convert it to TensorList (zero-copy).  From the native code side, you can create an empty TensorList or vector<Tensor>, and call `SetExternalInput` like in [this test](https://github.com/NVIDIA/DALI/blob/master/dali/benchmark/decoder_bench.cc#L43L58).

**Comment by kurff** [comment]
It solved my problem.
Thanks!
