### ISSUE TITLE
failed to build dali from source due to link error

### ISSUE THREAD

**Issue by hubutui** [NVIDIA/DALI#1843]
I'm trying to build dali 0.20.0 from source in ArchLinux, but got this error:
```
/usr/bin/ld: /usr/lib/libopencv_imgcodecs.so.4.2.0: undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()@GLIBCXX_3.4.26
```
this symbol is found in `/usr/lib/libstdc++.so`, not sure why ld want it from `/usr/lib/libopencv_imgcodecs.so.4.2.0`. For complete build log, check [here](https://build.archlinuxcn.org/~imlonghao/log/python-nvidia-dali/2020-03-28T01%3A17%3A01.html).
Step to build:
```
git clone https://github.com/NVIDIA/DALI.git
cd DALI
git submodule update --init --recursive
mkdir build && cd build
cmake \
    -DBUILD_LMDB:BOOL=ON \
    -DCMAKE_BUILD_TYPE:String=Release \
    -DCMAKE_INSTALL_PREFIX:PATH=/usr \
    -DCMAKE_SKIP_RPATH:BOOL=ON \
    -DProtobuf_USE_STATIC_LIBS:BOOL=OFF \
    ..
make
```
The default C/CXX compiler is gcc 9. However, I also try with gcc 8, but with no luck. Here is the build log: [dali-gcc8.txt](https://github.com/NVIDIA/DALI/files/4397199/dali-gcc8.txt)

**Comment by JanuszL** [comment]
Hi,

`/usr/bin/ld: /usr/lib/libopencv_imgcodecs.so.4.2.0: undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()@GLIBCXX_3.4.26` sounds like a problem with your installation of OpenCV. Can you try to build it from sources? The minimal, static OpenCV version DALI uses in prebuild binaries is build like [this](https://github.com/NVIDIA/DALI/blob/master/docker/Dockerfile.deps#L77L90).

**Comment by hubutui** [comment]
The default configuration of opencv from ArchLinux repo, https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/opencv#n45.
```
  cmake ../$pkgname-$pkgver \
    -DWITH_OPENCL=ON \
    -DWITH_OPENGL=ON \
    -DWITH_TBB=ON \
    -DWITH_QT=ON \
    -DBUILD_WITH_DEBUG_INFO=OFF \
    -DBUILD_TESTS=OFF \
    -DBUILD_PERF_TESTS=OFF \
    -DBUILD_EXAMPLES=ON \
    -DINSTALL_C_EXAMPLES=ON \
    -DINSTALL_PYTHON_EXAMPLES=ON \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCPU_BASELINE_DISABLE=SSE3 \
    -DCPU_BASELINE_REQUIRE=SSE2 \
    -DOPENCV_EXTRA_MODULES_PATH="$srcdir/opencv_contrib-$pkgver/modules" \
    -DOPENCV_SKIP_PYTHON_LOADER=ON \
    -DOPENCV_PYTHON3_INSTALL_PATH=$_pythonpath \
    -DLAPACK_LIBRARIES="/usr/lib/liblapack.so;/usr/lib/libblas.so;/usr/lib/libcblas.so" \
    -DLAPACK_CBLAS_H="/usr/include/cblas.h" \
    -DLAPACK_LAPACKE_H="/usr/include/lapacke.h" \
    -DOPENCV_GENERATE_PKGCONFIG=ON \
    -DOPENCV_ENABLE_NONFREE=ON \
    -DOPENCV_JNI_INSTALL_PATH=lib \
    -DOPENCV_GENERATE_SETUPVARS=OFF \
    -DEIGEN_INCLUDE_PATH=/usr/include/eigen3
```
We usually don't build static package. Is that a problem?

**Comment by JanuszL** [comment]
> this symbol is found in /usr/lib/libstdc++.so, not sure why ld want it from /usr/lib/libopencv_imgcodecs.so.4.2.0

I don't think it is about DALI looking for a symbol in `libopencv_imgcodecs.so.4.2.0`, but rather when DALI is linked with the OpenCV this ld tries to resolve this symbol as well but it cannot find it. Are you sure that this symbol, with this particular version `@GLIBCXX_3.4.26` is present in your system? You can try to rebuild OpenCV locally and see if that helps - you can even use [the recipe you linked](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/opencv#n45).

**Comment by hubutui** [comment]
hmm, according to [this bug report](https://bugs.archlinux.org/task/63408), there are issues with cuda, gcc8 and gcc9. cuda 10.2 support gcc 8 by default, but ArchLinux build everything with latest gcc (currently 9) by default. So there is an issue of mixing gcc8 and gcc9 ABI. I try to set [CUDAHOSTCXX](https://cmake.org/cmake/help/latest/envvar/CUDAHOSTCXX.html#envvar:CUDAHOSTCXX) or [CMAKE_CUDA_HOST_COMPILER](https://cmake.org/cmake/help/latest/variable/CMAKE_CUDA_HOST_COMPILER.html#variable:CMAKE_CUDA_HOST_COMPILER) to gcc8, but still got the same error.

**Comment by JanuszL** [comment]
So the only issue between CUDA and gcc is that CUDA enforces compiler version to be XXX at most and on less than YYY.
Both logs([here](https://build.archlinuxcn.org/~imlonghao/log/python-nvidia-dali/2020-03-28T01%3A17%3A01.html) and [dali-gcc8.txt](https://github.com/NVIDIA/DALI/files/4397199/dali-gcc8.txt)) show that you are compiling with gcc 8.4, so the issue is as in the [mentioned bug report](https://bugs.archlinux.org/task/63408),  because [the CUDA package from ArchLinux](https://www.archlinux.org/packages/community/x86_64/cuda/) implies GCC 8.4. OpenCV is built against gcc 9.x and it requires other things it is linked against to be built with gcc 9.x as well. This is an issue not related to DALI but rather how packages are compiled and what dependencies have in ArchLinux.
I'm afraid we cannot do much with that.

**Comment by hubutui** [comment]
Yes, maybe I need to recompile opencv (there might be a lot related pkgs too) with gcc8. Or I could wait NVIDIA release a new version cuda with gcc 9 support. Anyway, I would like to use dali 0.19.0 for now. Thanks for your help.

**Comment by JanuszL** [comment]
> Yes, maybe I need to recompile opencv (there might be a lot related pkgs too) with gcc8.
This is a solution available now.

> Or I could wait NVIDIA release a new version cuda with gcc 9 support
Hard to tell when that would happen.

**Comment by hubutui** [comment]
I'm not sure why the compiler is set to gcc 8 while default gcc version in ArchLinux is gcc 9. After setting:
```
CC=/usr/bin/gcc
CXX=/usr/bin/g++
CMAKE_CUDA_HOST_COMPILER=/usr/bin/g++
```
May this message might help someone with a similar issue. Note: ArchLinux patches cuda to allow gcc 9 as CUDA HOST compiler.

**Comment by JanuszL** [comment]
So as I understand it works now, right?

**Comment by hubutui** [comment]
@JanuszL Yes, it works.
