### ISSUE TITLE
batch nvjpeg decode doesn't speedup image reading

### ISSUE THREAD

**Issue by musicbeer** [NVIDIA/DALI#1847]
hi, I am trying do inference using nvjpeg, however batched =true and batchsize=4  does not work better than batched=false, in my test. Is it reasonable and why?

**Comment by JanuszL** [comment]
Hi,
Are you asking about `ImageDecoder` with a `mixed` backend? DALI once supported `use_batched_decode` in nvJPEGDecoder but it is no longer available since 0.8 release, as in typical workload that DALI supports it didn't provide any speedup.
