### ISSUE TITLE
Shard ID should be changed in multi-gpu example

### ISSUE THREAD

**Issue by lazykyama** [NVIDIA/DALI#1849]
This is a trivial bug report.

## Issue

In the following example, `Caffe2Reader` is called but one argument looks like wrong.
https://github.com/NVIDIA/DALI/blob/master/docs/examples/frameworks/tensorflow/tensorflow-dataset-multigpu.ipynb

Caller of `MnistPipeline` gives `i` (representing device id) into `shard_id` parameter. But, in `MnistPipeline.__init__()`, `shard_id` is ignored and `Caffe2Reader`'s `shard_id` is fixed by 0.
Therefore, labels fed into a model are the same on all devices. That shouldn't be expected behavior.

I can make a PR for this issue. If you, team, don't have enough time to fix it, please let me know. I will help you. Thanks!

**Comment by JanuszL** [comment]
HI,
Thank you for spotting this. https://github.com/NVIDIA/DALI/pull/1850 should fix the issue.

**Comment by JanuszL** [comment]
0.21 is available and should fix this problem.
