### ISSUE TITLE
Can you supply a docker image to build DALI

### ISSUE THREAD

**Issue by SunGaofeng** [NVIDIA/DALI#1853]
I tried to build DALI by docker. However, due to the too slow network, it failed to build docker image. I tried several times and found that it timed out at 'curl xxx ....', then the building process terminated.
Can you supply a docker image which has proper env to build DALI source code? I want Python3.7 && CUDA9.0 . 
Thanks.

**Comment by JanuszL** [comment]
Hi,
I'm sorry but currently are not able to share such a docker.
I can only guess that your curl may fail due to some proxy settings. Try to follow [this guide](https://docs.docker.com/network/proxy/) and see how that works for you.
