### ISSUE TITLE
JPEG version check error during cmake

### ISSUE THREAD

**Issue by SunGaofeng** [NVIDIA/DALI#1855]
Hi, I tried to build Dali from source code in ubuntu16.04
libjpeg-turbo-1.5.3 was downloaded, source code was built  and installed into the directory: /xxx, which includes,
                  bin  include  lib  share
and in the /xxx/lib directory, it includes
![image](https://user-images.githubusercontent.com/26536764/78343181-0a504680-75cd-11ea-8489-1d06d5efce84.png)

Then I add 
      -DJPEG_LIBRARY=/xxx/lib \
      -DJPEG_INCLUDE_DIR=/xxx/include \
to the cmake command.

However, it turned to be error with the following message

-- Performing Test HAVE_STEADY_CLOCK
-- Performing Test HAVE_STEADY_CLOCK -- success
CMake Error at /usr/local/cmake/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find JPEG: Found unsuitable version "", but required is at least
  "62" (found
  /ssd2/ttt/2020/q1/dali/build_from_source/libjpeg/build/lib)
Call Stack (most recent call first):
  /usr/local/cmake/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:376 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/cmake/share/cmake-3.13/Modules/FindJPEG.cmake:89 (find_package_handle_standard_args)
  cmake/Dependencies.common.cmake:59 (find_package)
  cmake/Dependencies.cmake:73 (include)
  CMakeLists.txt:98 (include)

-- Configuring incomplete, errors occurred!
See also "/ssd2/ttt/2020/q1/dali/build_from_source/dali/build/CMakeFiles/CMakeOutput.log".
See also "/ssd2/ttt/2020/q1/dali/build_from_source/dali/build/CMakeFiles/CMakeError.log".

**Comment by JanuszL** [comment]
It is strange. I would check how [CMake implements](https://github.com/Kitware/CMake/blob/master/Modules/FindJPEG.cmake) `find_package(JPEG 62 REQUIRED) ` DALI do use to find libjpeg-turbo. I see that it greps headers looking for `JPEG_LIB_VERSION XXX` string. Can you check if the headers you have include this string?

**Comment by JanuszL** [comment]
I just tired this with my setup - CMake "3.12.4", "libjpeg-turbo-2.0.2" and it works as expected.

**Comment by SunGaofeng** [comment]
> I just tried this with my setup - CMake "3.12.4", "libjpeg-turbo-2.0.2" and it works as expected.

Should I install libjepg in default directories, such as /usr/local ?
In my env, it is installed in the directory, /ssd2/ttt/2020/q1/dali/build_from_source/libjpeg/build

**Comment by JanuszL** [comment]
> I just tried this with my setup - CMake "3.12.4", "libjpeg-turbo-2.0.2" and it works as expected.

I installed it in `/tmp/jpeg`, so the install directory is not a problem.

**Comment by SunGaofeng** [comment]
> > I just tried this with my setup - CMake "3.12.4", "libjpeg-turbo-2.0.2" and it works as expected.
> 
> I installed it in `/tmp/jpeg`, so the install directory is not a problem.

Thanks to your kind help, I reinstalled libjpeg with version "libjpeg-turbo-2.0.2" and it works now.
