### ISSUE TITLE
Syntax error in external_source.py#L177

### ISSUE THREAD

**Issue by SunGaofeng** [NVIDIA/DALI#1859]
I build the Dali source code and try to run it, but get an error

![image](https://user-images.githubusercontent.com/26536764/78470174-e0785a80-7759-11ea-9c51-72826064d668.png)

https://github.com/NVIDIA/DALI/blob/03ecab037d0c4b8d6a2d7c0b60b17b1997957e7d/dali/python/nvidia/dali/external_source.py#L177

**Comment by JanuszL** [comment]
Hi,
Cold you tell more about this issue?
What is the python version do you use? Could you provide some [minimal and self-contained repro of this problem](https://github.com/NVIDIA/DALI#reporting-problems-asking-questions)?

**Comment by klecki** [comment]
Hi,
this is Python 3 thing indicating keyword only arguments: https://www.python.org/dev/peps/pep-3102/
Are you sure you are not running Python 2? Python 2 support was deprecated at the start of the year.

**Comment by SunGaofeng** [comment]
> Hi,
> this is Python 3 thing indicating keyword only arguments: https://www.python.org/dev/peps/pep-3102/
> Are you sure you are not running Python 2? Python 2 support was deprecated at the start of the year.

Yes, I previously built with python2. Now changed to python3 and it turns to be ok. Thanks.

**Comment by JanuszL** [comment]
Python 2.x is considered End Of Life since this year. DALI doesn't support it anymore as well.
