### ISSUE TITLE
nvmlInit() failed

### ISSUE THREAD

**Issue by SunGaofeng** [NVIDIA/DALI#1863]
I tried to build Dali from the latest source code, then try to run the demo in the getting started documents
https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/getting%20started.html#Defining-the-pipeline

The env is: python3.7, cuda9.0,  GPU: P40 x 8,   driver: NVIDIA-SMI 418.39

But get the following error "nvmlInit() failed". 
I uninstalled the home-built nvidia-dali, and reinstalled 0.20.0 by pip install, and got the same error.
Is there anything wrong?

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
WARNING:

You should always run with libnvidia-ml.so that is installed with your
NVIDIA Display Driver. By default it's installed in /usr/lib and /usr/lib64.
libnvidia-ml.so in GDK package is a stub library that is attached only for
build purposes (e.g. machine that you build your application doesn't have
to have Display Driver installed).
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Traceback (most recent call last):
  File "test3.py", line 23, in <module>
    pipe.build()
  File "/usr/local/python3/lib/python3.7/site-packages/nvidia/dali/pipeline.py", line 317, in build
    self._pipe.Build(self._names_and_devices)
RuntimeError: [/opt/dali/dali/util/nvml_wrap.cc:94] nvmlInit() failed: 
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
WARNING:

You should always run with libnvidia-ml.so that is installed with your
NVIDIA Display Driver. By default it's installed in /usr/lib and /usr/lib64.
libnvidia-ml.so in GDK package is a stub library that is attached only for
build purposes (e.g. machine that you build your application doesn't have
to have Display Driver installed).
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Stacktrace (21 entries):
[frame 0]: /usr/local/python3/lib/python3.7/site-packages/nvidia/dali/libdali.so(+0x6a47e) [0x7f9517f4147e]
[frame 1]: /usr/local/python3/lib/python3.7/site-packages/nvidia/dali/libdali.so(dali::nvml::wrapNvmlInit()+0x125) [0x7f95180546a5]
[frame 2]: /usr/local/python3/lib/python3.7/site-packages/nvidia/dali/libdali.so(dali::ThreadPool::ThreadPool(int, int, bool)+0x403) [0x7f9518018603]
[frame 3]: /usr/local/python3/lib/python3.7/site-packages/nvidia/dali/libdali.so(+0xe89e7) [0x7f9517fbf9e7]
[frame 4]: /usr/local/python3/lib/python3.7/site-packages/nvidia/dali/libdali.so(+0x168c09) [0x7f951803fc09]
[frame 5]: /usr/local/python3/lib/python3.7/site-packages/nvidia/dali/libdali.so(dali::Pipeline::Build(std::vector<std::pair<std::string, std::string>, std::allocator<std::pair<std::string, std::string> > >)+0xa4) [0x7f9518033334]
[frame 6]: /usr/local/python3/lib/python3.7/site-packages/nvidia/dali/backend_impl.cpython-37m-x86_64-linux-gnu.so(+0x4c06f) [0x7f953048306f]
[frame 7]: /usr/local/python3/lib/python3.7/site-packages/nvidia/dali/backend_impl.cpython-37m-x86_64-linux-gnu.so(+0x1ab53) [0x7f9530451b53]
[frame 8]: python(_PyMethodDef_RawFastCallKeywords+0x35a) [0x43ce5a]
[frame 9]: python(_PyObject_FastCallKeywords+0x230) [0x43d0d0]
[frame 10]: python(_PyEval_EvalFrameDefault+0x5b25) [0x427315]
[frame 11]: python() [0x420668]
[frame 12]: python(_PyEval_EvalFrameDefault+0x82b3) [0x429aa3]
[frame 13]: python(_PyEval_EvalCodeWithName+0xa28) [0x4ebf28]
[frame 14]: python(PyEval_EvalCode+0x23) [0x4ec013]
[frame 15]: python(PyRun_FileExFlags+0x16f) [0x52331f]
[frame 16]: python(PyRun_SimpleFileExFlags+0xec) [0x52354c]
[frame 17]: python() [0x430221]
[frame 18]: python(_Py_UnixMain+0x39) [0x4304b9]
[frame 19]: /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7f9530ab8830]
[frame 20]: python(_start+0x29) [0x42a089]

**Comment by SunGaofeng** [comment]
> Could you tell me more about how you run it? Bare metal or inside Docker?
> Can you provide a minimal and self-contained repro?

I found that there is something wrong with CUDA installed. I rebuilt the env and it works Now. It's great!
  
Thanks to all your help.

**Comment by xuzheyuan624** [comment]
I meet the same problem. I run the code inside Docker and I don't know how to solve it.

**Comment by JanuszL** [comment]
@xuzheyuan624 have you created it on your own or it is one of ours nvidia/cuda images?

**Comment by xuzheyuan624** [comment]
> @xuzheyuan624 have you created it on your own or it is one of ours nvidia/cuda images?

on my own

**Comment by JanuszL** [comment]
@xuzheyuan624 - have you tried to rebuild you env as @SunGaofeng did?

**Comment by xuzheyuan624** [comment]
> rebuild you env

emmm, I don't know how to rebuilt my env, is that means to reinstall CUDA?

**Comment by JanuszL** [comment]
That sounds like a good start. You can also try to run everything in docker if possible to make sure that your env is clean.
