### ISSUE TITLE
multi-machine multi-gpu test

### ISSUE THREAD

**Issue by pawopawo** [NVIDIA/DALI#1866]
If the same checkpoint file is tested with multi-nodes(multi-machines) and multi-gpu, the accuracy will be incorrect. The result is different from the single-machine.

The code if from https://github.com/NVIDIA/DALI/blob/master/docs/examples/use_cases/pytorch/resnet50/main.py

hope for help

**Comment by JanuszL** [comment]
One reason is that DALI reader is infinite and just wraps up. So if you have multi GPU config your inference run will see a different set of samples the for the single GPU (single will wrap up to the beginning, multi will move shards ahead so some samples from the beginning of each shard would repeat).
We have a PR under review to make it a bit better - https://github.com/NVIDIA/DALI/pull/1831.

**Comment by pawopawo** [comment]
thank you for your help.
 I used two machines, each with 8 GPUs, for a total of 16 GPUs. My batch size is 25,  so total batch size is 400, which is divisible by the test picture 50000, but the test accuracy is still wrong

**Comment by JanuszL** [comment]
Have you tried to run this without DALI?

**Comment by pawopawo** [comment]
thanks, I will have a try xiaxin 邮箱：xiaxin@buaa.edu.cn 签名由 网易邮箱大师 定制 On 04/10/2020 00:34, Janusz Lisiecki wrote: Have you tried to run this without DALI? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
