### ISSUE TITLE
mulit-gpu problem

### ISSUE THREAD

**Issue by mjq93** [NVIDIA/DALI#1867]
I have a lot of 3d data and need to do various data augmentation including resize, slice, elastic, affine and so on. I want to do data augmentation in parallel on the gpu, but it seems that pytorch does not allow gpu operation in the dataloader. So I found the DALI may support my need, but I still had trouble processing data with multiple gpus using DALI.
In my vision, data load is directly fed into multiple gpus, which process data at the same time, and then gather the data to do gpu parallel training. I have found few examples of multiple gpus on DALI github web, could anyone give me some more suggestions?

**Comment by JanuszL** [comment]
Hi,
The recommended way for multi GPU training with DALI is a Distributed Data-Parallel approach. So each GPU (process) has a separate DALI instance that does the data processing in parallel to the training on that particular GPU. From the user point of view, DALI needs to know how many shards (GPU) are there, which shard it should use (global rank) and which GPU it should operate on (local rank). The two first values are only for the reader. If you are planning to use ExternalSource operator it is up to you to handle sharding.
So first make sure DALI with a single GPU training, then moving to multi GPU one should be a trivial task.

**Comment by tianmaliuixing** [comment]
Thank you for your reply，can you give me some more detailed examples. I found some examples in docs/examples, but they didn't meet my need. For example, I have to read 3d data using third-party libraries, and I'm going to read the excel sheet, get the bbox coordinates, and then intercept the data. But I found that most of the examples used nvidia's native ops operations，I don't know how to customize these operations and use multiple gpus at the same time.

**Comment by JanuszL** [comment]
Hi,
For such custom data please use the [ExternalSourcae ](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html#nvidia.dali.ops.ExternalSource )operator. As, said please focus on making your pipeline operation for the 1GPU, making it multi GPU setup is the next step.
