### ISSUE TITLE
DALI_extra out of LFS bandwith

### ISSUE THREAD

**Issue by slawekslex** [NVIDIA/DALI#1873]
I'm attempting to clone the DALI_extra repo, and getting the error:
```This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.```
As far as I understand you need to increase the quota on your side.

**Comment by JanuszL** [comment]
Hi @slawekslex,
Thank you for your issue report We are working on this. I let you know when our quota is enlarged.

**Comment by npanpaliya** [comment]
@JanuszL - We are also seeing the same error. Is the quota enlarged now?

**Comment by JanuszL** [comment]
@npanpaliya - not yet

**Comment by npanpaliya** [comment]
Even for older versions of DALI_extra (736aa07d2ae679679c08cc5476f4787676c79dac), git lfs pull errors the same. Is that expected? Or older versions should work?

**Comment by JanuszL** [comment]
This is expected. The quota is per repository, no the revision.

**Comment by JanuszL** [comment]
Hi,
We have extended our quota. Please check now.

**Comment by slawekslex** [comment]
Thansk @JanuszL  I confirm I'm now able to clone it without errors.

**Comment by npanpaliya** [comment]
Thanks @JanuszL , even I'm able to clone without errors.
