### ISSUE TITLE
labels must have the same shape?

### ISSUE THREAD

**Issue by 1757525671** [NVIDIA/DALI#1875]
I use Dali to handle the detection task, but it requires me that labels must have the same shape. How to solve this problem, thank you

**Comment by 1757525671** [comment]
The toolkit I use is ExternalSource operator

**Comment by JanuszL** [comment]
You can try using [`Pad` operator](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html#nvidia.dali.ops.Pad) to unify the shape if I understand your problem correctly. To track the real shape you need to pass another tensor with it through the pipeline but it should be straightforward.
