### ISSUE TITLE
Torch DataLoader with Horovod

### ISSUE THREAD

**Issue by gfiameni** [NVIDIA/DALI#1893]
Hi all,
I have a code loading a quite complex data structure based on COCO (oversimplified in the snippet below). It is using Torch DataLoader with Horovod to fetch data. How would you suggest to restructure it to employ DALI? Thanks!

```
from torch.utils.data import DataLoader as TorchDataLoader
from pycocotools.coco import COCO
from torch.utils.data.distributed import DistributedSampler

class DataLoader(TorchDataLoader):
    def __init__(self, dataset, *args, **kwargs):
        super(DataLoader, self).__init__(dataset, *args, collate_fn=dataset.collate_fn(), **kwargs)

train_dataset = COCO(..)

train_sampler = DistributedSampler(train_dataset, num_replicas=hvd.size(), rank=hvd.rank())
dataloader_train = DataLoader(train_dataset, batch_size=args.batch_size, shuffle=False, num_workers=args.workers, drop_last=True, sampler=train_sampler, **kwargs)
```

**Comment by JanuszL** [comment]
Hi,
First I would recommend checking how you can use [COCO reader in the pipeline](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/use_cases/detection_pipeline.html). More about the COCO reader itself can be found in the [ops description](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html#nvidia.dali.ops.COCOReader).
Regarding horovood - it is rather transparent from DALI point of view. All you need to do is to get local rank, global rank, and world size from the horovood and assign it to device_id (local id), shard_id (global rank), and num_shards (world size). For a real use case, you can check [TensorFlow and DALI example](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/use_cases/tensorflow/resnet-n/README.html).

**Comment by gfiameni** [comment]
Thanks @JanuszL!
