### ISSUE TITLE
Python 3.8 wheel

### ISSUE THREAD

**Issue by Mmdixon** [NVIDIA/DALI#1900]
Would it be possible to add a prebuilt python 3.8 wheel to [future] releases?
Ubuntu 20.04 LTS is out now and python 3.8 is the default https://wiki.ubuntu.com/FocalFossa/ReleaseNotes#Python3_by_default
That would make transitioning pretty smooth.

**Comment by JanuszL** [comment]
It will be available in the next release.

**Comment by klecki** [comment]
The python 3.8 wheels are in the latest release: https://github.com/NVIDIA/DALI/releases/tag/v0.21.0
