### ISSUE TITLE
How to not drop the last batch with smaller batch size in validatation stage

### ISSUE THREAD

**Issue by bl0** [NVIDIA/DALI#1901]
Hi, thanks for the marvelous library. It improves the speed a lot.

When I use `ExternalInputIterator` to get batches of data, the last batch has a smaller batch size. In the training stage, I can simply drop the last batch and everything works fine.
But in the validation stage, the last batch should not be dropped, then the following exception is raised:
```
RuntimeError: Data list provided to feed_input needs to have batch_size length
```

What can I do for this?

**Comment by JanuszL** [comment]
Hi,
DALI is not able to change the batch size in flight. What you can do (as you probably know your data set size ahead) is to slice the DALI output at the very last batch. DALI Framework iterators can do this for other readers, but in the case of the ExternlSource it is not possible.

**Comment by bl0** [comment]
Thanks for your quick and helpful reply.
