### ISSUE TITLE
No package devtoolset-4 available.

### ISSUE THREAD

**Issue by bl0** [NVIDIA/DALI#1905]
When I compile DALI from source (using Docker builder) using `PYVER=3.7 CUDA_VERSION=10 ./build.sh`, it failed with error `No package devtoolset-4 available.`
What should I do for this?

Thanks in advance.

**Comment by JanuszL** [comment]
Hi,
Just checked and it doesn't work for me as well. According to this [site](https://www.softwarecollections.org/en/scls/rhscl/devtoolset-4/) it should be available. I think you should report this to the centos 7 packages maintainers.
In the near feature, we plan to move to prebuild manylinux2014 images to avoid this kind of problem. However, it won't happen until CUDA 9 is deprecated as it doesn't work with the compiler available in this package.

**Comment by bl0** [comment]
Thanks very much.
