### ISSUE TITLE
Can I introduce randomness in image augmentation?

### ISSUE THREAD

**Issue by cai-linjin** [NVIDIA/DALI#1907]
In operators like `Flip` or `CropMirrorNormalize`, we can pass random 1-0 produced by `CoinFlip`, thus achieve random-augmentaion. For example:
in `__init__`:

    self.coin1 = ops.CoinFlip(probability=0.5)
    self.coin2 = ops.CoinFlip(probability=0.5)
    self.flip = ops.Flip(device="gpu", horizontal=0)
    self.cmnp = ops.CropMirrorNormalize(mean=[0.485, 0.456, 0.406],
                                               std=[0.229, 0.224, 0.225],
                                               device='gpu',
                                               output_layout='CHW',
                                               output_dtype=types.FLOAT,)

in `define_graph`:

    rng1 = self.coin1()
    rng2 = self.coin2()
    images = self.cmnp(images, mirror=rng1)
    images = self.flip(images, vertical=rng2)

What I want to achieve is to have a group of augmentation functions, and invoke one of it in `define_graph`. For example:
in `__init__`:

    self.augmentations = [ops.Jitter(device = "gpu"), ops.Water(device = "gpu"), ops.Sphere(device = "gpu")]

and in `define_graph`:
    
    # pseudo DALI code
    a =  randomInt() 
    image = self.augmentations[a](image)
    return image

Are there any ways that enable me to do this? Thank you for helping and advice!

**Comment by JanuszL** [comment]
Hi,
DALI doesn't support conditional execution of the subgraph, still, you can do try to apply masking like in [this example](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/general/expressions/expr_conditional_and_masking.html).

**Comment by cai-linjin** [comment]
@JanuszL Hi! Thank you for your reply! I decide to implement such a "random augmentation" outsite the pipeline, and it should work.
