### ISSUE TITLE
Is it possible to apply different `Resize`s to differenct elements inside a batch?

### ISSUE THREAD

**Issue by cai-linjin** [NVIDIA/DALI#1920]
Thank you for your great work! 
In `nvidia.dali.ops.Resize`'s, we can pass parameters like `resize_longer`, `resize_shorter`, etc. to control the shape of output images. Is it possible to declare multiple `Resize` in `MyPipeline`'s `__init__`, and apply these different `Resize`s to different elements of a batch? For example: assuming our bach size is 3, and in `class MyPipeline(Pipeline)`'s `__init__`:

    self.res1 = ops.Resize(max_size=1024, resize_shorter=600)
    self.res2 = ops.Resize(max_size=800, resize_shorter=600)
    self.res3 = ops.Resize(max_size=400, resize_shorter=400)
in `define_graph`:
    
    # psudo DALI code
    images[0] = res1(images[0])
    images[1] = res1(images[1])
    images[2] = res1(images[2])

Is there any way to accomplish such a task? Thanks for help and advice in advance!

**Comment by JanuszL** [comment]
Hi,
DALI doesn't support conditional execution of part of its graph, but you can use [this approach](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/general/expressions/expr_conditional_and_masking.html) to mask maska selected operators.

**Comment by cai-linjin** [comment]
@Januszl Thank you for your hint!
