### ISSUE TITLE
Load video together with optical flow 

### ISSUE THREAD

**Issue by matanjacoby** [NVIDIA/DALI#1941]
Hi,
I have an application where I want to provide as input to a NN both image stream together with 2 GT optical flow streams (one represents motion between current-to-previous frames, another between current-to-next frame). It seems that loading the data to the GPU is the bottleneck, so I wondered if DALI can help here?

Currently I generate each datum as a set of images (N files of HxWxC images) along with N .npy files of HxWx4 (for  2 optical flows).  But I can pack it differently. 

Can you please advise how to pack the data efficiently so that DALI can boost the loading?
Should I pack it as video? Will VideoReader be the efficient tool here?
Any guidelines &| code are highly appreciated.

Many thanks!
Matan

**Comment by JanuszL** [comment]
Hi,
We have just recently added a numpy reader but it doesn't support sequences.
However we have a [VideoReader ](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html#nvidia.dali.ops.VideoReader)and a [OpticalFlow](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html#nvidia.dali.ops.OpticalFlow) operators.
How to use the VideoReader can be found [here](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/sequence_processing/index.html), how optical flow [here](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/sequence_processing/optical_flow_example.html).
In your case what you can do is to:
- read a sequence of 3 frames, where the 2nd one is the `current`
- use [ElementExtract operator](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html#nvidia.dali.ops.ElementExtract) to reverse the elements in the sequence
- call the optical flow on the normal and reversed sequences (so you have flows current-to-next frame and current-to-previous frame)

**Comment by JanuszL** [comment]
@szalpal - anything that I have missed?

**Comment by matanjacoby** [comment]
Hi @JanuszL, thanks for your kind help!
To clarify - I don't want an efficient optical flow calculation via DALI - I already generated the ground-truths together with the image sequences (in Blender, at first with a similar way to what you've suggested :) ).
I want the efficient data loading of this data to the GPU. Currently (no use of DALI), this IO is very slow. Ideally, I think I want to load a single tensor that holds all that data, but I have no experience with DALI.

How can I do that? I'm open to ideas of how to input the data to DALI (set of files, single video container like mp4...)

Thanks again!
Matan

**Comment by JanuszL** [comment]
Hi,
If you are not doing any processing and you are still IO limited then reading data from your storage is a problem and DALI can do very little with that.
However, if you would store your data as a video, decode on and calculate the optical flow using DALI then you would save your IO and improve the performance.
The IO is the reason why it is faster to load encoded JPEG files and decode them than read raw data (not to mention the storage space required for such an approach).

**Comment by matanjacoby** [comment]
Thanks very much, I'll try your suggestion!

**Comment by omer11a** [comment]
> Hi,
> We have just recently added a numpy reader but it doesn't support sequences.
> However we have a [VideoReader ](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html#nvidia.dali.ops.VideoReader)and a [OpticalFlow](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html#nvidia.dali.ops.OpticalFlow) operators.
> How to use the VideoReader can be found [here](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/sequence_processing/index.html), how optical flow [here](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/sequence_processing/optical_flow_example.html).
> In your case what you can do is to:
> 
> * read a sequence of 3 frames, where the 2nd one is the `current`
> * use [ElementExtract operator](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html#nvidia.dali.ops.ElementExtract) to reverse the elements in the sequence
> * call the optical flow on the normal and reversed sequences (so you have flows current-to-next frame and current-to-previous frame)

We get the following error when trying to calculate optical flow of the reversed sequence.
`RuntimeError: Critical error in pipeline: [/opt/dali/dali/operators/sequence/optical_flow/optical_flow.h:123] Assert on "shape.sample_dim() == 4" failed: Input for Optical Flow must be a sequence of frames.`
It seems that ElementExtract doesn't return a sequence.

**Comment by JanuszL** [comment]
@omer11a - sorry for providing inaccurate information. I confused Rearrange operator (which is not merged yet https://github.com/NVIDIA/DALI/pull/465) with ElementExtract.
Currently, it is not possible to do what you want - unless you use Python operator (you can use CuPy for the GPU data).

**Comment by klecki** [comment]
Hi, 
@omer11a we're revisiting the SequenceRearrange Operator, I will notify you when it's available in the nightly builds, I hope to get it merged by the end of this week.

**Comment by omer11a** [comment]
@JanuszL @klecki Thank you both!
BTW, is there a way to couple two different readers together (one for data and the other for metadata) such that shuffling keeps the input consistent? I want to try reading the GT optical flow using ExternalSource, and I would like to be able to shuffle the videos and flows consistently.

**Comment by JanuszL** [comment]
Hi,
If you are using the `ExternalSource` then it is up to you to have them synced. If you are using the build-in reader if you provide the same data layout (number of samples, directory structure, file list) and the same seed it should be in sync.

**Comment by klecki** [comment]
Hi, #465 is merged, I will confirm when in lands in nightly build, should be available tomorrow.

**Comment by klecki** [comment]
The SequenceRearrange should be available in the latest nightly build. 
You can install the nightly build by following this instructions: https://docs.nvidia.com/deeplearning/dali/master-user-guide/docs/installation.html#nightly-and-weekly-release-channels

**Comment by JanuszL** [comment]
0.23 has been released with the relevant functionality.
