### ISSUE TITLE
Incompatible type "DataNode"

### ISSUE THREAD

**Issue by kl844477** [NVIDIA/DALI#1942]
Hello, 
I want to integrate the DALI in my current project and ran into a strange error. So, maybe you can help me a bit. Specifically, I am very interested in using the tfrecord pipeline for data loading. On my workstation everything works quite well but when I transfer the same code to my HPC cluster I get a strange problem. 

On my cluster, I have compiled DALI from source (bare metal, no access to docker on the cluster) as explained in the docs which seems to work. I used Cuda 10.1.105 and the driver 418.87. The GPUs are Tesla K80. 

When I now run the example code from the [pytorch-various-readers](https://github.com/NVIDIA/DALI/blob/master/docs/examples/frameworks/pytorch/pytorch-various-readers.ipynb) example, I end up with this error: 
```
Traceback (most recent call last):
  File "DDP_frame_jureca.py", line 1172, in <module>
    main()
  File "DDP_frame_jureca.py", line 491, in main
    pipes[0].build()
  File "/p/project/cjhpc54/ddp_frame/jureca_files/DALI/dali/python/nvidia/dali/pipeline.py", line 406, in build
    self._prepare_graph(define_graph)
  File "/p/project/cjhpc54/ddp_frame/jureca_files/DALI/dali/python/nvidia/dali/pipeline.py", line 325, in _prepare_graph
    _data_node._check(outputs[i])
  File "/p/project/cjhpc54/ddp_frame/jureca_files/DALI/dali/python/nvidia/dali/data_node.py", line 116, in _check
    .format(type(maybe_node).__name__))
TypeError: Expected outputs of type compatible with "DataNode". Received output type with name "DataNode" that does not match.
srun: error: jrc0475: task 0: Exited with exit code 1
```
Do you have an idea what is wrong? I appreciate every help.

**Comment by JanuszL** [comment]
Hi,

Can you provide the full log? Has the script started at all and do any iteration? Does the prebuild DALI wheel work?
Judging from this brief error I can guess that you didn't compile support for TFRecord and that is why you get this failure.

**Comment by JanuszL** [comment]
If it still doesn't work please reopen.
