### ISSUE TITLE
Question on the operation for image augmentation - Gaussian blur

### ISSUE THREAD

**Issue by weberxie** [NVIDIA/DALI#1947]
DALI is really an amazing project for pre-processing, it greatly speed up the pre-processing speed in our production environment.

But, when we migrate the pre-processing code with PIL library to DALI, we found that there is no op can do Gaussian blur.

So, is there an approach to do Gaussian blur? If not, is there a plan to add the new operation?

Thanks!

**Comment by JanuszL** [comment]
Hi,

Currently there no such operator in DALI. We have that in our ToDo list (but we cannot commit to any particular date). However, we would be more than happy to review and accept any PR that would add such functionality.

**Comment by mzient** [comment]
We don't have an operator for that. Depending on your accuracy requirements, you could scale down and up again with Gaussian filter (INTERP_GAUSSIAN) - it's going to be approximate, but may be sufficient for some use cases.

**Comment by klecki** [comment]
Hi, we're looking into implementing the Gaussian Blur Operator. Can I ask you for your typical parameters like size of the filter that you use? Do you have other input data than 3-channel images?

**Comment by weberxie** [comment]
Great! Below is the typical usage scenario.

```
class GaussianBlur(object):
    def __init__(self, sigma=[.1, 2.]):
        self.sigma = sigma

    def __call__(self, x):
        sigma = random.uniform(self.sigma[0], self.sigma[1])
        x = x.filter(ImageFilter.GaussianBlur(radius=sigma))
        return x```

**Comment by klecki** [comment]
The Gaussian Blur for CPU was merged with #2038. It should be available in nightly build soon or in the 0.24 release.
I'm now looking into GPU implementation.

**Comment by klecki** [comment]
Hi again,
the GaussianBlurGPU was merged last Friday and it should be available in both nightly and weekly builds of DALI. It will also be a part of 0.27 release.

**Comment by weberxie** [comment]
Hi, @klecki thanks for your great work! We have tested the CPU implementation, it worked as expected.

Now, We will test the GPU implementation.

**Comment by JanuszL** [comment]
DALI 0.27 is available. It should address your request.
