### ISSUE TITLE
Hard to build the project from source

### ISSUE THREAD

**Issue by weberxie** [NVIDIA/DALI#1957]
Hi,

I'm trying to build the project from source, I met a lot of problems such as `no package devtoolset-4 available`, and still can't build it success now, because of the specific network environment in China.

So, could you push the related base images to the docker repository, then we can pull them directly instead of build them from source.

Thanks!

**Comment by szalpal** [comment]
Hi,

Have you followed [Docker build tutorial](https://docs.nvidia.com/deeplearning/dali/master-user-guide/docs/compilation.html#compiling-dali-from-source-using-docker-builder-recommended), or are you building bare-metal version?

**Comment by RDruon** [comment]
Hello,

I was able to successfully build DALI using the Docker build instruction.
I changed the devtoolset-4 to devtoolset-7 in `docker/0001-An-approximate-manylinux3_x86_64.patch` file to be able to do it. 
Please find below the patch file I used
[DALI-devtoolset7-mod.patch.txt](https://github.com/NVIDIA/DALI/files/4626677/DALI-devtoolset7-mod.patch.txt)

**Comment by weberxie** [comment]
yes, it did work after changed the devtoolset-4 to devtoolset-7. thanks for you kind reply.

**Comment by JanuszL** [comment]
Hi,

We are going to deprecate CUDA 9 as CUDA 11 will be available pretty soon.
As a part of this transition, we can move to manylinux2014. If you are not building for CUDA 9 (and this was the only reason why we sicked to devtolset-4) you can check https://github.com/NVIDIA/DALI/pull/1965.
