### ISSUE TITLE
NumpyReader is unable to load uint8 files

### ISSUE THREAD

**Issue by RDruon** [NVIDIA/DALI#1958]
Hello DALI Team,

It seems the new NumpyReader operator can't load numpy files saved as uint8 array.

Please find below the minimal reproducible example:
```
import os
from nvidia.dali.pipeline import Pipeline
from nvidia.dali.plugin.pytorch import DALIGenericIterator
import nvidia.dali.ops as ops
import numpy as np

class NumpyFilesPipeline(Pipeline):
    def __init__(self, files_path, batch_size=1, num_threads=1, device_id=0):
        super(NumpyFilesPipeline, self).__init__(batch_size,
                                         num_threads,
                                         device_id)
        self.input = ops.NumpyReader(file_root  = files_path)
    def define_graph(self):
        numpy_files = self.input(name="Reader")
        return numpy_files
    def iter_setup(self):
        pass

def create_img_numpy(width, height, output_path, idx, base_filename='img{}'):
    a = np.random.rand(width,height,3) * 255
    final_output_path = os.path.join(output_path, base_filename.format(idx) + ".npy")
    np.save(final_output_path, a.astype(np.uint8))

if __name__ == "__main__":
    # Create numpy file
    for j in range(10):
        os.makedirs('/tmp/numpy_test/class{}'.format(j))
        for i in range(10):
            create_img_numpy(256, 256, '/tmp/numpy_test/class{}'.format(j), i)
    # Create numpy pipeline
    pipeline = NumpyFilesPipeline('/tmp/numpy_test/')
    pipeline.build()
    pipeline.run()
```
This code produces the following error:

> RuntimeError: Critical error in pipeline: Error in thread 0: [/opt/dali/dali/pipeline/data/buffer.h:143] Assert on "IsValidType(type_)" failed: Buffer has no type, 'mutable_data<T>()' or 'set_type' must be called on non-const buffer to set valid type

Running the same code and changing `np.uint8` to `np.int32` (in create_img_numpy function) fix the issue.
I think it's related to [this file](https://github.com/NVIDIA/DALI/blob/e50d1e0daa847904d5e14cc473cbee97903e90e5/dali/operators/reader/loader/numpy_loader.cc#L26), numpy format "u1" (uint8) is missing.

**DALI version**: nvidia_dali-0.23.0.dev0-12345-cp36-cp36m-manylinux1_x86_64.whl (built using docker)
**Python version**: Python 3.6.9

**Comment by szalpal** [comment]
@RDruon , that was right. Created PR with fix.

**Comment by szalpal** [comment]
Fix merged. Please verify and reopen if necessary

**Comment by JanuszL** [comment]
Let us close when it is available in the release binary.

**Comment by JanuszL** [comment]
0.23 has been released with the relevant fix.
