### ISSUE TITLE
NumpyReader can't use GPU backend

### ISSUE THREAD

**Issue by RDruon** [NVIDIA/DALI#1959]
Hello DALI Team,

The new NumpyReader operator can't be used in a pipeline with GPU backend.

Please find below the minimal reproducible example:

```
import os
from nvidia.dali.pipeline import Pipeline
import nvidia.dali.ops as ops
import numpy as np

class NumpyFilesPipeline(Pipeline):
    def __init__(self, files_path, batch_size=1, num_threads=1, device_id=0):
        super(NumpyFilesPipeline, self).__init__(batch_size,
                                         num_threads,
                                         device_id)
        self.input = ops.NumpyReader(file_root  = files_path)
        self.resize = ops.Resize(device = "gpu", resize_shorter = 256)

    def define_graph(self):
        numpy_files = self.input(name="Reader")
        output = self.resize(numpy_files)
        return output

    def iter_setup(self):
        pass

def create_img_numpy(width, height, output_path, idx, base_filename='img{}'):
    a = np.random.rand(width,height,3) * 255

    final_output_path = os.path.join(output_path, base_filename.format(idx) + ".npy")
    np.save(final_output_path, a.astype(np.int32))

if __name__ == "__main__":
    # Create numpy file
    for j in range(10):
        os.makedirs('/tmp/numpy_test/class{}'.format(j))
        for i in range(10):
            create_img_numpy(256, 256, '/tmp/numpy_test/class{}'.format(j), i)

    # Create numpy pipeline
    pipeline = NumpyFilesPipeline('/tmp/numpy_test/')
    pipeline.build()
    pipeline.run()
```
This code produces the following error:
> RuntimeError: Critical error in pipeline: [/opt/dali/dali/pipeline/workspace/workspace.h:419] Assert on "tensor_meta.storage_device == StorageDevice::GPU" failed: Input with given index (0) does not have the calling backend type (GPUBackend)

Changing the backend of the Resize operator to `cpu` produces the following error:

> RuntimeError: Critical error in pipeline: Error in thread 0: [/opt/dali/dali/operators/image/resize/resize.cc:95] Assert on "IsType<uint8>(input.type())" failed: Expected input data as uint8.

Using ImageDecoder operator with `mixed` backend instead of Resize produces the following error:

> RuntimeError: Critical error in pipeline: [/opt/dali/dali/pipeline/data/buffer.h:114] Assert on "type_.id() == TypeTable::GetTypeID<T>()" failed: Calling type does not match buffer data type: uint8 v. int32

It seems the ImageDecoder and Resize operator are waiting for uint8 input, but the NumpyReader can't read files saved in that format (see issue #1958).

**Comment by szalpal** [comment]
Hi @RDruon ,

[`NumpyReader`](https://docs.nvidia.com/deeplearning/dali/master-user-guide/docs/supported_ops.html#nvidia.dali.ops.NumpyReader) operator works currently only for CPU backend, so it provides outputs on the CPU. If you want to use CPU output with GPU operator in DALI, you need to explicitly create graph edge between CPU and GPU ops. In your code it would look like:
```python
        numpy_files = self.input(name="Reader")
        output = self.resize(numpy_files.gpu())   # <---
        return output
```
Furthermore, currently `Resize` operator accepts only 8-bit images, so your `np.int32` won't work - you should have `np.uint8`.

Anyhow, as you pointed out in #1958 , indeed there seems to be a bug. We'll take a look

**Comment by RDruon** [comment]
It was indeed the issue. I didn't know about the `gpu()` method, thanks for the tip 👍 .
Using the fix for NumpyReader uint8 fix all my issues.
Thanks
