### ISSUE TITLE
Operator that reads an image from the file name?

### ISSUE THREAD

**Issue by slawekslex** [NVIDIA/DALI#1960]
Is there a way to use ExternalSource to feed filenames to be loaded into DALI, rather than open file in Python and pass its contents as a numpy array (as the ExternalSource example does)? In my experiments, reading a file in Python was few times slower than with FileReader and completely nullified speed benefit of using DALI.

Usecase:
I'm trying to integrate DALI Pipeline with fastai and have a general way of supporting a wide range of image tasks, so the Pipeline input is not just (image, label) but for example (image, image), (image, mask), (image, multiple labels), (image, bounding boxes, labels), etc. 
I already have the structure I need in Python code so using the ExternalSource seemed to me as the most logical and flexible.

**Comment by szalpal** [comment]
Hi @slawekslex ,

`FileReader` currently does not accept any input. We have an ongoing discussion, how it should be properly done, as reading custom list of files has some caveats.

From what I see, I think that you can handle some of your cases right now, but not all of them unfortunately. 
1. For (image, image) pairs, you can use 2 `FileReader` operators - passing them the same `seed` you'll be sure, that they randomize your files the same way, so you'll the preserve mapping between them. 
2. In (image, mask) scenario, if mask is just a binary image, you can go the same path.

The multiple labels thing will be more problematic - right now DALI uses only integer for labelling. It is possible, however, to create an helper file, that will contain only the integer labels and image paths. The idea is that images will be "labelled" with consecutive integers (`0, 1, 2...`) and the labels will map these integer-labels onto label sets, e.g.
```
{
  0: "dog, cat",
  1: "godzilla, drone",
}
```
which can be done outside of pipeline, by implementing a wrapper-decorator for DALI iterator.

Anyway, `FileReader` accepting file names is something we may handle in near future.

pzdr

**Comment by slawekslex** [comment]
Thanks Michał I appreciate the prompt response. I'm happy to hear this had been already on your radar. Is there a place I can follow along for updates on that?

I'm aware of the workaround for multilabel case from other threads here, however this seems to me  more like a temporary hack than a general solution. I already have all the data in the memory and here I have to:
- Write a file with paths and indices to disk
- Get a batch of data from the pipeline (with Pytorch iterator in my case)
- Get the labels tensor to CPU
- Index into my dataset for actual labels.
- Collate it back into a batch
- Move it back to GPU

I hope you agree this is a roundabout way of doing things. 

It gets even worse when labels contain coordinates relative to the image, like in detection use case. Now I'd have to output the random parameters used in crops and augmentation to recalculate the coordinates outside the Pipeline.

Cheers!
Sławek

**Comment by JanuszL** [comment]
Hi,

It is hard to commit to any schedule. Now we are rather focused on audio and Reader improvement is still far away on our ToDo list.

**Comment by klecki** [comment]
Hi,
I know the current solution involving writing back to disk is cumbersome (and it some applications the need to write additional data is not optimal). I want to highlight the fact that DALI utilizes prefetching and double buffering (tripple or more if you configure it) of the processed data. For good shuffling we may need to read ahead a significant number of samples. 

Just passing the input file names through external source may not be enough for some use-cases, we need to provide a solution that would allow the Pipeline to be saturated with the data and probably request more samples when it needs to. We also don't have support for ExternalSource in TF yet.

Regards,
Krzysiek.

**Comment by slawekslex** [comment]
Thanks for the detailed response. I realise this is not trivial. My feedback from a user standpoint is that it will be a welcomed improvement when you get to it.

FWIW in my particular usecase I don't mind feeding the data ahead of time, doing my own shuffling, or even providing an indexable structure for random access.

**Comment by JanuszL** [comment]
Hi @slawekslex,

The most recent improvements in [the `external_source` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.external_source) make it possible to scale it to multiple GPUs. Please check `parallel` and `prefetch_queue_depth` parameteres.
It will work in parallel to other processing and should be good enough to read data in any custom order you like.
