### ISSUE TITLE
How to re-shuffle an instantiated pipeline

### ISSUE THREAD

**Issue by ben0it8** [NVIDIA/DALI#1969]
Hi,

I'm using a pipeline that reads a bunch of TFRecords with random shuffling. Now, in each epoch, I'd like to fetch freshly shuffled data. Is there a way to re-shuffle the reader op?
Unfortunately, re-initializing the pipeline is expensive. One option that comes to my mind is serializing the pipeline once and just deserializing it for each epoch, but based on my experience with earlier Dali versions, every time you build the pipe it blocks some extra memory on the GPU.

How to do this best?

Thanks in advance :+1:

**Comment by JanuszL** [comment]
Hi,

When you are using TFRecords and enable shuffling then you are good, you should not get the same order epoch to epoch.
DALI (and TensorFlow) reads TFRecord sequentially and then used some prefetch buffer (size 1000 in DALI) that is used to randomly sample data to form a batch. The random generator is not reset every epoch, and it just wraps up. If your data set size is not equal to the random generator cycle size then you won't get the same order of samples epoch to epoch.
We expect that TFRecord is preshuffled, so you won't get only samples from class 0 at the very beginning (as you may have more samples in given class than the prefetch buffer can house).
Despite global shuffling is possible but random access to TFRecord would be slow and is I don't think anyone is using such an approach.

**Comment by ben0it8** [comment]
Thanks a lot Janusz!
