### ISSUE TITLE
Lanczos3 interpolation vs PIL

### ISSUE THREAD

**Issue by melgor** [NVIDIA/DALI#1993]
Hi,
I'm using DALI for training and works well. But I would like to try Lanczos interpolation. However, while training with dali, in production use-case I use PIL. And after some analysis, look like DALI Lanczos works much different compared to PIL (and also ImageMagic).
I provided minimal example to reproduce the difference in JupyterNotebook.
To just show the results (difference are 5x amplified to see the differences better)
DALI vs PIL
![image](https://user-images.githubusercontent.com/2587438/83636699-b0590680-a5a6-11ea-884c-9deb34522afd.png)

PIL vs ImageMagic
![image](https://user-images.githubusercontent.com/2587438/83636724-bb139b80-a5a6-11ea-94e8-29af7170c724.png)

Look like that Lanczos filter is not consistent in alll library.
Also, I added 2 images in images folder. First one works better, but in second one the difference are more visible.
[minimal_example.zip](https://github.com/NVIDIA/DALI/files/4723253/minimal_example.zip)

**Comment by JanuszL** [comment]
@mzient can you look at it?

**Comment by mzient** [comment]
@melgor 
1. The archive with example is empty.
2. Regarding the difference - it will only appear when downscaling. libImaging, which is used by PIL, keeps the filter scale from becoming less than 1 (which would happen when downscaling). This causes the filters to stop working as advertised - e.g. linear filter becomes in fact a triangular filter, Lanczos filter becomes something different yet (in Lanczos filter, the zeros should be spaced one by sample, forcing the filter scale to 1 breaks that). This produces some reasonably well looking image without much mathematical foundation.
To get the best results, I recommend the following:
```mag_filter=types.INTERP_LANCZOS3, min_filter=types.INTERP_GAUSSIAN```
which will switch from Lanczos when upscaling to Gaussian when downscaling in given axis.

**Comment by mzient** [comment]
...conttinued:
what PIL does causes sever overshoot when downscaling - this image was scaled anisotropically (vertical downscaling from 960 to 256 pixels) - see ringing artifacts around horizontal edges:
![out_pil](https://user-images.githubusercontent.com/17044837/83648636-91fb0700-a5b6-11ea-98b6-def996687f61.png)
...and lack thereof in DALI when using Gaussian for dowscaled axis:
![out_dali](https://user-images.githubusercontent.com/17044837/83648680-9fb08c80-a5b6-11ea-8585-a3fe06fac4b0.png)

**Comment by melgor** [comment]
[minimal_example.zip](https://github.com/NVIDIA/DALI/files/4723933/minimal_example.zip)
1. Sorry for uploading empty zip, now everything should work.
2. Unfortunately, Gaussian does not match the results for PIL. 

Thanks for detailed explanation!


Look like I would not be able to use Lanczos as I have fashion images and look like that when there are striped shirt or checkered shirt, resized artefact influence the model.  I need to look closer why such small changes in resize operation influence the model accuracy (>2%)

**Comment by JanuszL** [comment]
@melgor 
> Unfortunately, Gaussian does not match the results for PIL.

Do you mean DALI Gaussian and PIL Gaussian?

**Comment by JanuszL** [comment]
And do you test inference? If so you need to retrain the model using the same interpolation as you are using during the inference as model recognizes resize artifacts as the object features.

**Comment by melgor** [comment]
1. About matching the results, I mean PIL Lanczos vs DALI Gaussian. It is of course obvious :)
But this stop me from using Lanczos interpolation from PIL in production. 

2. I only test inference. This issue was about using Lanczos interpolation during training and inference stages. But as  PIL have difference Lanczos interpolation than DALI, it is not possible currently. The only thing I have in my mind is to resize all images before training to have size 224x224 and just omit resizing in DALI.

**Comment by JanuszL** [comment]
> PIL Lanczos vs DALI Gaussian
It won't match. The point from @mzient was to use DALI Gaussian as it provides better results when down-sampling but it won't match PIL Lanczos.

> But as PIL have difference Lanczos interpolation than DALI, it is not possible currently. The only thing I have in my mind is to resize all images before training to have size 224x224 and just omit resizing in DALI.

If you use DALI for training and inference with the same resize interpolation you should get better results than mixing DALI and PIL (or any two libraries together like OpenCV and PIL).

**Comment by melgor** [comment]
I get your answers, but currently there is not option for using DALI for inference.

**Comment by JanuszL** [comment]
Sure

**Comment by mzient** [comment]
@melgor Since what we had was not really usable for downscaling anyway, we've decided to follow PIL way of dealing with Lacznos3 - it's already merged as #2041 and should be available in release 0.24 (and tomorrow's nightly build if you need it sooner).

**Comment by PrinceP** [comment]
@mzient  Hi Michal, Is there a way to run the Lanczos resize separately in a single c(Cuda) file?

**Comment by PrinceP** [comment]
@mzient  Thanks Michal, I am planning to use below https://github.com/NVIDIA/DALI/blob/66e46c0f840845cb6cdff58a7bb7b14d33e7ed0b/dali/kernels/test/resampling_test/resampling_internal_test.cu#L494 

I will try out your suggestion also.
