### ISSUE TITLE
How to load image data from memory (not from files) and use ops from NVIDIA-DALI?

### ISSUE THREAD

**Issue by liuchanglab** [NVIDIA/DALI#1998]
Can NVIDIA-DALI provide python interface to load image data from memory? 
We want use ops from NVIDIA-DALI, and the inputs for DALI are intermediate products (not load from files).

Yet, We find feed_input may help to solve this problem.

**Comment by JanuszL** [comment]
Please check [the `ExternalSource` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.ops.ExternalSource).

**Comment by liuchanglab** [comment]
We have checked the ExternalSource operator. Since the input of ops is generated by other network, it is difficult to define iterator or callable function for  ExternalSource.
We just want to do:
1、feed_input to pipeline
2、pipeline.run() get the results

**Comment by JanuszL** [comment]
> We have checked the ExternalSource operator. Since the input of ops is generated by other network, it is difficult to define iterator or callable function for ExternalSource.
We just want to do:
1、feed_input to pipeline
2、pipeline.run() get the results

You could use some queue to communicate between the iterator that feeds DALI input and the output from your network. DALI would block until data is available in the iterator.

**Comment by liuchanglab** [comment]
Yes, we have tested it: DALI would block until data is available in the iterator.
Can you provide some example or documentation for this: You could use some queue to communicate between the iterator that feeds DALI input and the output from your network.

**Comment by JanuszL** [comment]
>Can you provide some example or documentation for this

This is a rough idea.
A pseudo-code may look like:
```
in_q = queue.Queue()
out_q = queue.Queue()

class ExternalInputIterator(object):
    def __init__(self, queue, batch_size):
        self._queue = queue
        (...)
    def __next__(self):
        item = self._queue.get()
        (...)
 

class ExternalSourcePipeline(Pipeline):
    (...)

def work(in_q, out_q):
    eii = ExternalInputIterator(in_q, batch_size)
    pipe = ExternalSourcePipeline(batch_size=batch_size, eii, num_threads=2, device_id = 0)
    pipe.build()
    pipe_out = pipe.run()
    out_q.put(pipe_out )

threading.Thread(target=worker, daemon=True).start()
in_q.put(input_data)
out_q.get(output_data)
```

**Comment by CharlieCheckpt** [comment]
Hello, 
First of all thank you for this library !

Would it be possible to share a more detailed code for this use case ? I am using pytorch and have trouble "converting" my code to work with DALI, even with the pseudo-code given above. 

Like the author, my data is already in memory. What I am doing at the moment (only with pytorch) is : 

```python
# Let X be a torch.tensor, and model be a torch.nn.Module
dataset = TensorDataset(X)
dataloader = DataLoader(dataset, batch_size=16, num_workers=0)
for batch in dataloader:
   model.forward(batch[0].to("cuda:0"))
   ... 
```

**Comment by JanuszL** [comment]
Hi @CharlieCheckpt,

Please check [this example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/use_cases/pytorch/resnet50/pytorch-resnet50.html) to see how to integrate DALI with PyTorch. More details can be found [here](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/plugins/pytorch_tutorials.html).
To learn how to use the `external_source` please check [this one](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/external_input.html).
As the documentation for [the `external_source` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.external_source) states:
```
The data samples must be in one of the compatible array types:
- NumPy ndarray (CPU)
- MXNet ndarray (CPU)
- PyTorch tensor (CPU or GPU)
- CuPy array (GPU)
- objects implementing __cuda_array_interface__
- DALI Tensor object```
So the code inside the external source operator needs to slice the Tensor you provided.
Something like:
```

Something like this basic example should work:
```
from nvidia.dali import fn, pipeline_def

batch_size=2

input = torch.rand(size=[batch_size*10, 1]) * 255
print("Torch tensor: ", input)

index = 0
def get_data():
    global index
    out = [input[idx] for idx in range(index, index+batch_size)]
    index = index+batch_size
    return out

@pipeline_def
def test_pipe():
    return fn.external_source(source=get_data)

pipe = test_pipe(batch_size=batch_size, num_threads=1, device_id=0)
pipe.build()
o = pipe.run()
print("Iter: ", o[0].as_array())
o = pipe.run()
print("Iter: ", o[0].as_array())```

**Comment by CharlieCheckpt** [comment]
This is helpful, thank you very much @JanuszL
