### ISSUE TITLE
Make error with cuda 9.0 and cmake 3.8

### ISSUE THREAD

**Issue by jacob1017** [NVIDIA/DALI#2]
DALI/dali/image/jpeg.cc:47:8: error: ‘TJSAMP_411’ was not declared in this scope
   case TJSAMP_411:
DALI/dali/image/jpeg.cc:142:40: error: invalid conversion from ‘const uint8* {aka const unsigned char*}’ to ‘unsigned char*’ [-fpermissive]
                w, 0, h, pixel_format, 0);
/usr/include/turbojpeg.h:729:23: error:   initializing argument 2 of ‘int tjDecompress2(tjh
andle, unsigned char*, long unsigned int, unsigned char*, int, int, int, int, int)’ [-fperm
issive]
 DLLEXPORT int DLLCALL tjDecompress2(tjhandle handle,

may be version of libjpeg-turbo can't compatible with the branch?

**Comment by JanuszL** [comment]
Hi,
Which version of libjpeg-turbo do you use? DALI needs at least 1.5.x.

**Comment by slayton58** [comment]
@JanuszL is correct -- your version of libtubojpeg is too old (Ubuntu 16.04 installs 1.4.x for instance).

**Comment by JanuszL** [comment]
If installing required version of libtubojpeg doesn't resolve your problem please reopen.
