### ISSUE TITLE
build error due to protobuf

### ISSUE THREAD

**Issue by as754770178** [NVIDIA/DALI#2003]
I compile protobuf according to #817,but still report error:
```
/usr/bin/ld: /usr/local/lib/libprotobuf.a(common.o): relocation R_X86_64_32S against `_ZTVN6google8protobuf7ClosureE' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libprotobuf.a: error adding symbols: 错误的值
```

1. 
compile protobuf command:
```
# due to error: configure.in:18: required file `build/ltmain.sh' not found
libtoolize --automake --copy --debug --force 

./autogen.sh
./configure CXXFLAGS="-fPIC" --prefix=/usr/local/protobuf --disable-shared
make -j
make install
```
my libtoolizer version is
```
libtoolize --version
libtoolize (GNU libtool) 2.4.6
```

2. due to error: `致命错误：google/protobuf/port_def.inc：没有那个文件或目录`

I add `INCLUDE_DIRECTORIES(/usr/local/protobuf/include) ` in `CMakeLists.txt`.

**Comment by JanuszL** [comment]
Hi,

Please check how we build protobuf https://github.com/NVIDIA/DALI/blob/master/docker/Dockerfile.deps#L37.
Also, I recommend to try dockerized build env, the most recent version of it is in https://github.com/NVIDIA/DALI/pull/1965.
