### ISSUE TITLE
custom operator error

### ISSUE THREAD

**Issue by as754770178** [NVIDIA/DALI#2004]
I want to create a custom operator by c++refer to [document ](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/custom_operations/custom_operator/create_a_custom_operator.html).
In the example, the code `#include "dali/pipeline/operator/operator.h"`
so I must compile DALI by source?
Is there any other way for me？ I compile DALI report error.

**Comment by awolant** [comment]
Hi, thanks for the question.

No, you don't have to compile DALI from source. You only need to compile your own operator. For this you need DALI headers (include you mentioned) somewhere where compiler can find them.

You can install DALI package and build your own operator. Then, you can load this operator at runtime and use it as part of DALI pipeline.

**Comment by as754770178** [comment]
Thanks, But I replicate program in [Create a custom operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/custom_operations/custom_operator/create_a_custom_operator.html).
report error:
```
c++: 错误：unrecognized command line option ‘-std=c++14’
```

I change CMakeLists.txt as
```
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 ${DALI_COMPILE_FLAGS} ")
set(CUDA_NVCC_FLAGS "${CUDA_NVCC_FLAGS} -std=c++11 ${DALI_COMPILE_FLAGS} ")
```
report error:
```
[ 33%] Building NVCC (Device) object CMakeFiles/customdummy.dir/customdummy_generated_dummy.cu.o
/opt/anaconda3/lib/python3.7/site-packages/nvidia/dali/include/dali/core/span.h(40): error: namespace "std" has no member "remove_cv_t"

/opt/anaconda3/lib/python3.7/site-packages/nvidia/dali/include/dali/core/span.h(40): error: expected a ";"

............ 

/opt/anaconda3/lib/python3.7/site-packages/nvidia/dali/include/dali/core/tensor_shape.h(1131): error: expected a declaration

/opt/anaconda3/lib/python3.7/site-packages/nvidia/dali/include/dali/core/tensor_shape.h(1132): error: expected a declaration

/usr/local/gcc-5.4.0/include/c++/5.4.0/bits/hashtable_policy.h(85): error: identifier "declval" is undefined

/usr/local/gcc-5.4.0/include/c++/5.4.0/bits/hashtable_policy.h(85): error: expected an expression

/usr/local/gcc-5.4.0/include/c++/5.4.0/bits/hashtable_policy.h(85): error: expected an expression

/usr/local/gcc-5.4.0/include/c++/5.4.0/bits/hashtable_policy.h(85): error: expected an expression

/usr/local/gcc-5.4.0/include/c++/5.4.0/bits/hashtable_policy.h(85): error: expected an expression

/usr/local/gcc-5.4.0/include/c++/5.4.0/bits/hashtable_policy.h(214): error: __bool_constant is not a template

Error limit reached.
100 errors detected in the compilation of "/tmp/tmpxft_00003276_00000000-6_dummy.cpp1.ii".
Compilation terminated.
CMake Error at customdummy_generated_dummy.cu.o.cmake:280 (message):
  Error generating file
  /home/110482/temp/test/build/CMakeFiles/customdummy.dir//./customdummy_generated_dummy.cu.o

```

**Comment by as754770178** [comment]
cmake --version
cmake version 3.17.3

**Comment by as754770178** [comment]
sovlve the issue by `cmake -DCMAKE_CXX_COMPILER=/usr/local/gcc-5.4.0/bin/g++ ..`

**Comment by JanuszL** [comment]
Removing `c++14` is a bad idea as DALI relies on C++14. We glad you managed to solve your problem.
