### ISSUE TITLE
Error with example of RN50

### ISSUE THREAD

**Issue by ACbccc** [NVIDIA/DALI#2005]
Hello! I used your code of https://github.com/NVIDIA/DALI/blob/master/docs/examples/use_cases/pytorch/resnet50/main.py
but I got error:
Traceback (most recent call last):
  File "068_apexmain.py", line 592, in <module>
    main()
  File "068_apexmain.py", line 324, in main
    train_loader = DALIClassificationIterator(pipe, reader_name="Reader", fill_last_batch=False)
TypeError: __init__() got an unexpected keyword argument 'reader_name'
How should I fix this error? Thank you.

**Comment by klecki** [comment]
Hi,
the example you mentioned relies on changes that were recently merged https://github.com/NVIDIA/DALI/commit/dbca1396c886294744f7841275468f6abed46529 and are not yet available in a released version of DALI. 
As we had some CI maintenance, the nightly version doesn't have it either - we will notify you when it's there.

For now you should be able to use those examples before that commit.

**Comment by JanuszL** [comment]
I would recommend using script version from the last public release https://github.com/NVIDIA/DALI/tree/release_v0.21.
