### ISSUE TITLE
support for LiDAR PointCloud data from KITTI or NuScense datasets

### ISSUE THREAD

**Issue by RRK13** [NVIDIA/DALI#2013]
Please inform if DALI can support for handling Lidar and RADAR pointCloud or PCD or PCD.bin files, from KITTI or NuScense datasets.
Please share the steps.

**Comment by JanuszL** [comment]
Hi,

Currently, DALI doesn't support pointCloud kind of data. The only operator that supports any other kind of point data than detection bounding boxes it is [`CoordFlip`](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.ops.CoordFlip) developed for mask polygon.
However, we would be more than happy to see an external contribution implementing such functionality.

**Comment by JanuszL** [comment]
Hi,
You can check [this example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/math/geometric_transforms.html) to see how point cloud could be processed with DALI.
To load the data you can use [the `external_source` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.external_source). Please check `parallel` and `prefetch_queue_depth` parameters.
