### ISSUE TITLE
os.environ['CUDA_VISIBLE_DEVICES'] not work

### ISSUE THREAD

**Issue by as754770178** [NVIDIA/DALI#2014]
In my code, I write `os.environ['CUDA_VISIBLE_DEVICES']="3,4"`, but the program still run in [0,1].

I exec `CUDA_VISIBLE_DEVICES=3,4 python3 train.py`,  the program run in [3,4].

**Comment by JanuszL** [comment]
Hi,

Do you call `os.environ['CUDA_VISIBLE_DEVICES']="3,4"` at the beginning of your script? Maybe you do it after DALI has initialized already?

**Comment by as754770178** [comment]
thanks, the issue fixed
