### ISSUE TITLE
[Feature Request] GPU Memory Save Mode

### ISSUE THREAD

**Issue by dhkim0225** [NVIDIA/DALI#2015]
Hello, I'm an avid user of nvidia dali. Thanks to all contributors. I was able to improve our project's data_loader.

However, there's a new feature I want. It's about GPU Memory usage. our pipeline's gpu memory usage is very high since image data are too huge like (size (3000, 4000, 3)).
Augmentation logic is simple. (image-decoder => rotate => crop => resize => color jitter)
In my loader, one pipeline(8 batches) is allocated for each GPU. (4GPU => 32batch)

Memory was insufficient even on 32GB V100 equipment. To solve this problem, I created a 1-batch pipeline and aggregated the results to create an 8 batch.
Following code is what I've used.

```python
class BlahBlah:
    def __init__(self):
        self.dali_iter = DALIGenericIterator([dali_pipe], dali_keys, 9999999999)

    def _get_batch_with_memory_trick(self):
        imgs, heat_chars, heat_links, heat_upvs, w_masks = [], [], [], [], []
        err_char = 0
        for _ in range(self.local_batch_size):
            dali_out = next(self.dali_iter)[0]
            imgs.append(dali_out['imgs'].clone())
            heat_chars.append(dali_out['heat_chars'].clone())
            heat_links.append(dali_out['heat_links'].clone())
            heat_upvs.append(dali_out['heat_upvs'].clone())
            w_masks.append(dali_out['w_masks'].clone())
            err_char += torch.sum(dali_out['err_chars']).item()

        imgs = torch.cat(imgs, dim=0)
        heat_chars = torch.cat(heat_chars, dim=0)
        heat_links = torch.cat(heat_links, dim=0)
        heat_upvs = torch.cat(heat_upvs, dim=0)
        w_masks = torch.cat(w_masks, dim=0)

        return imgs, heat_chars, heat_links, heat_upvs, w_masks, err_char
```

* ```clone()``` was essential to avoid same data output.

According to my knowledge, modules like nvjpeg usually consume a lot of gpu memory. How about making dali to create "8 batches" recursivelly and internally (only with [a lot of memory consumption modules]) (memory_save_mode). Please tell me what you think of this idea.

Regards,
Anthony

**Comment by dhkim0225** [comment]
Sorry for my dumb issue. It was all about num_threads. Just use ```num_thread=1``` solve all my problems.

**Comment by JanuszL** [comment]
Hi,

`num_thread=1` is used by DALI to create as many nvJPEG library instances to parallelize CPU side of JPEG decoding.

> How about making dali to create "8 batches" recursivelly and internally

I think you can just run DALI 8 times and assemble a batch of 8 samples outside of the DALI using tensor concatenation.
