### ISSUE TITLE
how to using dali in human pose estimation task 

### ISSUE THREAD

**Issue by MoonBunnyZZZ** [NVIDIA/DALI#2027]
Different from classification task,  the labels of human pose estimation task are complex and diverse.
For example, there  are heatmaps,vector filed labels , masks and so on.

Now, i face the difficulty of how to read heatmaps. which is CHW 3-D tensor(C larger than 3 and HW differs), into pipeline(maybe using numpyreader API?) and which decoder to use?
And the labels need to be processed by the same augments as input image.

**Comment by JanuszL** [comment]
Hi,
I would start with [the ExternalSource](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.ops.ExternalSource) first as it gives you the most flexibility, and move to numpyreader later. This way you can feed any data type you want into the DALI pipeline.

> which decoder to use

It depends if your data is encoded, if not then you can just skip the decoding step.

>And the labels need to be processed by the same augments as the input image.

The first thing is to check if DALI operators you need to use supports the dimensional of the labels you have. If all data you need to process has the same type and dimensionality you can just do:
```
def __init__(...):
    self.op = dali.ops.some_op(...)
def define_graph(...):
    input1, input2 = ops.inputs()
    output1 = self.op(input1)
    output2 = self.op(input2)
    return output1, output2
```
Calling one instance of the operator to different data will apply the same transformation to all of them.
However, if data types and dimensionality differ between input1 and input2 then the question is how to define the same operation on each of them. It would be good if you can provide an example of data and operation you want to apply.

**Comment by abdksyed** [comment]
Hi,
I am working on a similar problem, where I am trying to detect Mask and the Depth.
I am having two Input RGB Images. So I am planning to concat them and make them as 6 channels. 
It is a custom crated dataset and since I am working on Google Colab, I kept all the size to 192x192.
My output will be two images of Mask and Depth Image (1 Channel each). But for time being I am trying for one output Image.

I am not able to understand how do I concat two Images, Since I came across DALI very recently, not able to understand it well. I am using tutorials and created my ExternalInputIterator and ExternalSourcePipeline.

This is My Input Iterator (Taken from Tutorial)
```
class ExternalInputIterator(object):
    def __init__(self, batch_size):
        self.fg_bg_dir = "Data/Dataset/fg_bg/"
        self.bg_dir = "gdrive/My Drive/Pull-0-Depth/bg_64"
        self.mask_dir = "Data/Dataset/mask/"
        self.batch_size = batch_size
        self.files = list_f
        self.bg_files = list_b
        self.data_set_len = len(self.files)
        self.n = len(self.files)

    def __iter__(self):
        self.i = 0
        shuffle(self.files)
        return self

    def __next__(self):
        inp1 = []
        inp2 = []
        labels = []

        if self.i >= self.n:
            raise StopIteration

        for _ in range(self.batch_size):
            fgbg_filename = self.files[self.i]
            bg_filename = self.bg_files[self.i]
            mask_filename = self.files[self.i]
            fg = open(self.fg_bg_dir + fgbg_filename, 'rb')
            bg = open(self.bg_dir + bg_filename, 'rb')
            mk = open(self.mask_dir + mask_filename, 'rb')
            inp1.append(np.frombuffer(fg.read(), dtype = np.uint8))
            inp2.append(np.frombuffer(bg.read(), dtype = np.uint8))
            labels.append(np.frombuffer(mk.read(), dtype = np.uint8))
            self.i = (self.i + 1) % self.n
        return (inp1, inp2, labels) #Returning Two Input and One Output Images

    @property
    def size(self,):
        return self.data_set_len

    next = __next__
```

Here is my External Source Pipeline.
```
class ExternalSourcePipeline(Pipeline):
    def __init__(self, batch_size, num_threads,
                  device_id, external_data):
        super(ExternalSourcePipeline, self).__init__(batch_size,
                                      num_threads,
                                      device_id,
                                      seed=42)
        self.inp_image_fgbg = ops.ExternalSource()
        self.inp_image_bg = ops.ExternalSource()
        self.input_label = ops.ExternalSource()
        self.decode_rgb = ops.ImageDecoder(device = "mixed", output_type = types.RGB)
        self.decode_gray = ops.ImageDecoder(device = "mixed", output_type = types.GRAY)
        self.norm_fgbg = ops.Normalize(device="gpu", mean = [0.49589815735816956, 0.4921991527080536, 0.46450406312942505],
                                       std = [0.21221362054347992, 0.21272724866867065, 0.23032782971858978])
        self.norm_bg = ops.Normalize(device="gpu", mean = [0.5058152675628662, 0.5046470165252686, 0.47556382417678833],
                                     std= [0.19492648541927338, 0.19461843371391296, 0.21560588479042053])
        self.norm_mask = ops.Normalize(device="gpu", mean = [0.09645408391952515, 0.09645408391952515, 0.09645408391952515],
                                       std = [0.27314358949661255, 0.27314358949661255, 0.27314358949661255])
        self.cast = ops.Cast(device = "gpu",
                             dtype = types.UINT8)
        self.external_data = external_data
        self.iterator = iter(self.external_data)

    def define_graph(self):
        self.jpegs_fgbg = self.inp_image_fgbg()
        self.jpegs_bg = self.inp_image_bg()
        self.labels = self.input_label()
        images_fgbg = self.decode_rgb(self.jpegs_fgbg)
        output_fgbg = self.norm_fgbg(images_fgbg)
        images_bg = self.decode_rgb(self.jpegs_bg)
        output_bg = self.norm_bg(images_bg)

#I have this two Input Images output_fgbg and output_bg, how do I concat them into 6 channel image?
        
        label = self.decode_gray(self.labels)
        label_out = self.norm_mask(label)

        return (output_fgbg, output_bg, label_out) #I want to return only one output and one label.

    def iter_setup(self):
        try:
            (fg_bg,bg,labels) = self.iterator.next()
            self.feed_input(self.jpegs_fgbg, fg_bg)
            self.feed_input(self.jpegs_bg, bg)
            self.feed_input(self.labels, labels)
        except StopIteration:
            self.iterator = iter(self.external_data)
            raise StopIteration
```

**Comment by JanuszL** [comment]
Hi @abdksyed,

DALI doesn't support concatenation of tensors yet so you need to yield them as two separate outputs and combine in the Framework of your selection.
I would also recommend using [FileReaders ](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.ops.FileReader)instead of ExternalSource. The ExternalSource operators are most flexible but inferior regarding the performance. If you want to pass only a selected set of files you can use the file_list argument of the FileReader.

**Comment by JanuszL** [comment]
Hi,
In that case, you would need to replace ExternalSource with the FileReader and create a file_list like in [this example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/getting%20started.html#Defining-the-pipeline) listing all files you want to use - fg_bg, bg, and label. If you keep the corresponding order in all of them and set the same seed to each FileReader you should get the same shuffling pattern in each reader. ExternalInputIterator won't be needed anymore.

**Comment by abdksyed** [comment]
Hi,
As you suggested I am using filereader,
My directory Dataset has 3 folders for 3 sets of images.(2 input 1 output)

Dataset
->fg_bg
->bg
->mask

I tried to give 3 separate inputs and it gave error that it expect DataNode and "list" is given.

So I directly passed entire Dataset folder directly to filereader, but the filereader is giving only 2 outputs not three.

**Comment by JanuszL** [comment]
You should have 3 separate inputs:
```
def __init__(...)
    self.input_fg_bg = ops.FileReader(file_root = fg_bg_dir, file_list = 'fg_bg_file_list.txt', seed=reader_seed, random_shuffle=True)
    self.input_bg = ops.FileReader(file_root = bg_dir, file_list = 'bg_file_list.txt', seed=reader_seed, random_shuffle=True)
    self.input_mask = ops.FileReader(file_root = mas_dir, file_list = 'mask_file_list.txt', seed=reader_seed, random_shuffle=True)
def define_graph(self):
   input_fg_bg, _ = self.input_fg_bg()
   input_bg, _ = self.input_bg()
   input_mask, _ = self.input_mask()
```
fg_bg_file_list content should look like:
```
fg_bg_image1.jpg 0
fg_bg_image2.jpg 0
```
bg_file_list:
```
bg_image1.jpg 0
bg_image2.jpg 0
```
mask_file_list:
```
mask_image1.jpg 0
mask_image2.jpg 0
```

**Comment by abdksyed** [comment]
Oh great.
So, I have the list of files, just have to make a txt file of the names and give 0 after it. So the output for each will be image and 0, but when returning the final output, I can use the images only. That's great.
Also, the shuffling will occur at each epoch, or is the shuffling done once when the generic dali iterator is created?

**Comment by JanuszL** [comment]
Hi,
This `0` is the label value assigned to each image. In your case, it could be any as you are not using it.
First of all, DALI does global shuffling one for the whole pipeline instance to avoid getting samples with the same label during the first iterations (the seed is the same for all instances and hardcoded). In the case of data containers - like LMDB, TFRecord or RecordIO DALI expects data to be already shuffled. Then DALI uses the internal prefetch buffer (`initial_fill` parameter of the reader) to create a batch by sampling data randomly from it. FileReader itself supports `shuffle_after_epoch` which asks it to repeat this global shuffling after each epoch (to get better entropy), however, due to slow random access to data containers only FielReader and COCOReader support this argument.

**Comment by abdksyed** [comment]
I get it.
Thanks a lot @JanuszL for all your answers and help.
I will try to run it using all the above mentioned methods. Again, thanks for the help!
