### ISSUE TITLE
How to cast TensorGPU to TensorCPU

### ISSUE THREAD

**Issue by XiaotaoChen** [NVIDIA/DALI#2031]
'm trying to generate detection loader with `COCOReader` for detection tasks. due to the `bbox` generated in `COCOReader` is relative and in . I want to get its' absolute values. So i got the resized shape of `images`. However, the `images` generated in `imDecode` is in `GPU`, So the `shape` is the same. In this case, How should do to get absolute values of `gt_bbox` with  relative `gt_bbox` in `CPU` and `resized shape` in `GPU`.   **Is there any `operator` can implement this ? Or is there any operator can convert `TensorCPU` to `TensorGPU` ? which can align `relative gt_bbox` in `CPU` with `resized shape` in `GPU`.
And if I implement `gt_bbox_absolute_value`  in `DALI` with `resized_shape` and `relative gt_bbox`, Can i pass `resized_shape` in GPU as one of inputs in `CPUBackend` ?**
May you can give some advice. Thanks.

below is my naive pipeline.
```shell

class COCOPipeline(Pipeline):
    def __init__(self, batch_size, num_threads, device_id, 
                 file_root, annotations_file, short, long, 
                 max_num_gt=100,
                 num_gpus=1, direction="horizontal"):
        super(COCOPipeline, self).__init__(
            batch_size, num_threads, device_id, seed=15)
        assert direction in ["horizontal", "vertical"]
        self.input = ops.COCOReader(
            file_root=file_root,
            annotations_file=annotations_file,
            shard_id=device_id,
            num_shards=num_gpus,
            ratio=True,
            ltrb=True)
        self.decode = ops.ImageDecoder(device="mixed", output_type=types.RGB)
        # resize
        self.resize = ops.Resize(device="gpu", interp_type=types.INTERP_LINEAR,
                                 resize_shorter=short, max_size=long)
        self.shape = ops.Shapes(device="gpu")


    def define_graph(self):
        inputs, bboxes, labels = self.input()
        images = self.decode(inputs)
        images = self.flip(images)
        bboxes = self.bbflip(bboxes)
        src_shape = self.shape(images)
        images = self.resize(images)
        resized_shape = self.shape(images)
        return (images, bboxes, labels, src_shape, resized_shape)
```

**Comment by JanuszL** [comment]
Hi,
DALI can only transfer data from CPU->GPU in the pipeline, the other way around is not supported. You can transfer data from the GPU to CPU outside the DALI pipeline, so if the output is on the GPU you can call `as_cpu()` on it.
I'm afraid that you need to write a custom operator that would resize bboxes as well, you can start [using python cod](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/custom_operations/gpu_python_operator.html)e and then write [a full custom operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/custom_operations/custom_operator/create_a_custom_operator.html).

**Comment by XiaotaoChen** [comment]
Thanks for your suggestions. Currently, We do other custom operator outside DALI with python implemention. such as `AnchorTarget` whose inputs is `im_info` and `gt_bbox`. and it seems like cpu-implement is more effective than gpu(I'm not sure). That is why we get `src_shape` and `resized_shape` from DALI. However, the performance is bad, due to the fake multi-threads of Python. So we want to implement those custom opeartor in DALI. And this can make loader more clear than DALI + python preprocess. 
May you can provide some advices for our scene. Thanks.
And which operator can convert TensorCPU to TensorGPU ? I don't know how to convert `gt_bbox` in CPU to GPU. @JanuszL

**Comment by JanuszL** [comment]
> May you can provide some advices for our scene

I would recommend taking a look into existing operators to see how that works, maybe @mzient can say more.

> And which operator can convert TensorCPU to TensorGPU ? I don't know how to convert gt_bbox in CPU to GPU

What I mean is that you can convert GPU to CPU when you have the output of the DALI pipeline, but it is not possible inside.

**Comment by mzient** [comment]
If having the boxes with absolute coordinates on GPU is ok, then you can scale them using an extremely ugly hack - but it's **unsupported, unofficial**, ugly method - however, it's possible, see #1904 
If you need the boxes on CPU, you can't really get them back from GPU to CPU inside DALI pipeline.

**Comment by XiaotaoChen** [comment]
@mzient @JanuszL  Thanks for your suggestions. Maybe i should implement those complicated operator in DL framework instead treating them as data-preprocess in python.
