### ISSUE TITLE
Random seed in CropMirrorNormalize and Crop

### ISSUE THREAD

**Issue by shonigs** [NVIDIA/DALI#2040]
Hi i'm using Dali for Image segmentation my inputs are an RGB image and a grayscale image as a label , many of the augmentations that I do for the Image I also need to do for the label (segmentation map) 
I would like to use CropMirrorNormalize (with mirror =0) for the Image and Crop for the Label. 
If I give each the same seed and the same parameters (crop size) can I be sure that they will both return the same crop?

**Comment by JanuszL** [comment]
Hi,
In most cases you can just:
```
def __init__(...):
    self.op_1 = dali.ops.some_op(...)
def define_graph(self):
   self.lables =  self.op_1(self.labels)
   self.images=  self.op_1(self.images)
```
So applying the same instance of the operator to many, different inputs should apply the same operation to each of them.
