### ISSUE TITLE
A PythonFunction problem

### ISSUE THREAD

**Issue by lisc199** [NVIDIA/DALI#2047]
I was using a pythonfunction to process my image, and then apply a crop operation. like:
```python
class MyPipeline(Pipeline):
    def __init__():
        self.crop = ops.Crop(device='gpu', crop=(self.crop_h, self.crop_w))
        self.image_edit = ops.PythonFunction(function=image_edit, num_outputs=2, device='gpu')
    def define_graph(self):
        images = self.img_decoder(self.images)
        labels = self.lbl_decoder(self.labels)
        im, lb = self.image_edit(images, labels)
        im = self.crop(im, crop_pos_x=crop_pos_x, crop_pos_y=crop_pos_y)
        lb = self.crop(lb, crop_pos_x=crop_pos_x, crop_pos_y=crop_pos_y)

def image_edit(images1, images2):
    return images1, images2
```
However, I get an error even the function image_edit only returns the input
```shell
Traceback (most recent call last):
  File "/workspace/dali/dataloaders/datasets/cityscapes_dali.py", line 215, in <module>
    dali_iter = PyTorchIterator(pipe, ['image', 'label'], len(pipe[0].dataset))
  File "/opt/anaconda3/lib/python3.7/site-packages/nvidia/dali/plugin/pytorch.py", line 171, in __init__
    self._first_batch = self.next()
  File "/opt/anaconda3/lib/python3.7/site-packages/nvidia/dali/plugin/pytorch.py", line 272, in next
    return self.__next__()
  File "/opt/anaconda3/lib/python3.7/site-packages/nvidia/dali/plugin/pytorch.py", line 186, in __next__
    outputs.append(p.share_outputs())
  File "/opt/anaconda3/lib/python3.7/site-packages/nvidia/dali/pipeline.py", line 529, in share_outputs
    return self._pipe.ShareOutputs()
RuntimeError: Critical error in pipeline: [/opt/dali/dali/operators/image/crop/crop.cu:29] Assert on "in_layout.ndim() == input.shape().sample_dim()" failed
```

What can I do to solve this problem?

**Comment by JanuszL** [comment]
Hi,
Could you provide the full repro of your problem?
Have you tried to run [the official example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/custom_operations/python_operator.html)?

**Comment by lisc199** [comment]
Sorry that I can not provide the full repro.
I have tried and passed the official example.
Thanks very much for your reply~

**Comment by JanuszL** [comment]
> Sorry that I can not provide the full repro.

By the full repro I mean the minimal case that reproducer the problem but not necessarily reveals the code you developed.

You have mentioned:
> I get an error even the function image_edit only returns the input

So if you can provide a self-contained script that just does that I would allow us to tell more about the problem.

**Comment by lisc199** [comment]
I am very willing to provide you the script but I am limited by the company's privacy policy.
Anyway, appreciate for your reply. I will close this issue and find another way to process my data. If I find any solution, I am glad to share it.

**Comment by JanuszL** [comment]
Maybe it is the same problem as https://github.com/NVIDIA/DALI/issues/2387. Please check this issue to learn more.
