### ISSUE TITLE
How sharding works on a multiple GPU setup ? 

### ISSUE THREAD

**Issue by cristyioan2000** [NVIDIA/DALI#2054]
Hi, I've tried to use the COCOReader that was presented in the Dali examples on this repo from the RetinaNet using multiple GPUs. And I've encountered some problems with the distribution of the data(sharding) over the GPUs. I tried to debug and print the image paths that each GPU was processing. And I found some of the images repeating on multiple GPUs, which got me thinking that the sharding it's not working how I was expected.

I did the setup for the Reader with the following parameters:
- random_shuffle: False
- shuffle_after_epoch: True
- stick_to_shard: False

Can you please explain which are the correct parameters to have a different  chunk of data on each GPU ? And explain if can how the dataset it's shuffled and splited into shards ?
Is there a way to make the DaliDataIterator reshuffle the data before the epoch it's finished ?

**Comment by awolant** [comment]
Hi, 
Thanks for the question. Can you share some code sample that would reproduce the issue and describe what exactly you want to happen? We have some small COCO-like dataset in [DALI_extra](https://github.com/NVIDIA/DALI_extra/tree/master/db/coco) for convenience.
Maybe looking into our [sharding docs](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/multigpu.html#Sharding) would make things clear?

**Comment by JanuszL** [comment]
Also, do you use a Framework iterator? If so then I would recommend using nightly DALI build that adds better [integration between iterator and the reader](https://docs.nvidia.com/deeplearning/dali/master-user-guide/docs/plugins/pytorch_plugin_api.html) - see `reader_name` parameter. If used with `pad_last_batch=True` in the reader it should always pad samples up to the full batch in the last iteration instead of wrapping up. If you wrap up you may see the same across different shards in a given epoch.

**Comment by cristyioan2000** [comment]
Sorry for the long response time. This seem to answer my question regarding the parameters of the pipeline to control the shards https://github.com/NVIDIA/DALI/issues/2060.

I have another question, unrelated, after this I can close the issue. 
Dali needs to iterate through the whole data-set that is available on a GPU to go to a new epoch. Is there a way to force a new epoch without iterating through the whole data-set ? 
I want to have a custom way to force the reshuffle of the whole data-set and re-splitting it in shards.

Let's say I have a 100k data-set and 2x GPUs, there will be 2 shards, 50k/50k on each GPU. I want to run reshuffle the data-set after 25k samples. Is there a way to force Dali to reshuffle the data-set ?

**Comment by JanuszL** [comment]
Hi,
>Let's say I have a 100k data-set and 2x GPUs, there will be 2 shards, 50k/50k on each GPU. I want to run reshuffle the data-set after 25k samples. Is there a way to force Dali to reshuffle the data-set ?

There is no easy way to do so but you can try to create 4 shards, so each GPU (if you have only 2 of them) will traverse only 25% of the data set during the epoch. After that, if you have `shuffle_after_epoch: True` the whole data set should be reshuffled.

**Comment by cristyioan2000** [comment]
Thank you for the answers!
