### ISSUE TITLE
Which is the correct Cocoreader parameter configuration to run on multiple GPU's with sharding?

### ISSUE THREAD

**Issue by bamfpga** [NVIDIA/DALI#2055]
Hi,
I am trying to understand these parameters, and the documentation is very scarce:
-stick_to_shard - with this on False is there still sharding going on, or each GPU receives the whole dataset?
-shuffle_after_epoch - how does this differ from random_shuffle
-random_shuffle - I noticed that this shuffles the whole dataset before sharding. Is this correct?
I am experimenting with 2 configurations that seem correct:
First:
    random_shuffle=True (when I set this to False I see the indices in order, they are different on the 2 gpus, as i expected, each gpu having half of the data)
    stick_to_shard=True
    shuffle_after_epoch=False
With this one what bothers me that on gpu 0 for example I have the same indices at every epoch (but in different order)

Second:
    random_shuffle=False
    stick_to_shard=False
    shuffle_after_epoch=True  (but when I set this to False all the dataset appear on both my gpus)

Which of these two would you recommend? Or which is the correct way to have different data on each gpu.
Thanks in advance!

**Comment by JanuszL** [comment]
Hi,
Please take a look into [this example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/multigpu.html).
`stick_to_shard` tells DALI not to rotate shards across the GPUs after each epoch. So each GPU is assigned to given shard one for all.
`shuffle_after_epoch` - tells DALI to shuffle the whole data set after each epoch. It is supported by the data types where random access doesn't impose any performance penalty. In most cases, DALI reads data sequentially and uses an internal buffer that is randomly sampled to form a batch. In some cases, a small improvement in the randomness provided by `shuffle_after_epoch` helps, but usually, it doesn't matter.
`random_shuffle` - it shuffles data inside the internal prefetch buffer( the default `initial_fill` value is 1024), the data set is read sequentially. For some data types like RecordIO or TFRecord, random access is very slow and this is a usual pattern applied by other FWs.

> random_shuffle=True (when I set this to False I see the indices in order, they are different on the 2 GPUs, as i expected, each gpu having half of the data)
stick_to_shard=True
shuffle_after_epoch=False
With this one what bothers me that on GPU 0, for example, I have the same indices at every epoch (but in a different order)

This is expected, each GPU sticks to its shard but the order is random. So GPU0 always gets the samples from the shard 0 but in a different order each epoch.

>random_shuffle=False
stick_to_shard=False
shuffle_after_epoch=True (but when I set this to False all the dataset appear on both my gpus)

It provides the best entropy. `stick_to_shard` doesn't matter in this case as the whole dataset is reshuffled after each epoch.

What I would recommend is `shuffle_after_epoch=True, stick_to_shard=False/True, random_shuffle=False/True` or `shuffle_after_epoch=False, stick_to_shard=False, random_shuffle=True` (this setting works for every reader).
Please also check [this part of the documentation](https://docs.nvidia.com/deeplearning/dali/master-user-guide/docs/advanced_topics.html#sharding) when you plan to use FW iterator.

**Comment by bamfpga** [comment]
Extremely helpful! Thank you!

**Comment by JanuszL** [comment]
You welcome.
