### ISSUE TITLE
Question about using ImageDecoder

### ISSUE THREAD

**Issue by kikoaumond** [NVIDIA/DALI#2066]
Hello

I am using an ExternalSource to load my images to do some preprocessing.
The images are converted to numpy arrays of dimension height x width x channels with dtype=np.uint8

When passing the images to an ImageDecoder ops defined as 

 ```
# decode images and move them from the CPU to the GPU
 self._decode = ops.ImageDecoder(device="mixed", output_type=types.RGB)
```

I am getting the following error:
```
RuntimeError: Critical error in pipeline: [/opt/dali/dali/image/image_factory.cc:87] Assert on "CheckIsPNG(encoded_image, length) + CheckIsBMP(encoded_image, length) + CheckIsGIF(encoded_image, length) + CheckIsJPEG(encoded_image, length) + CheckIsTiff(encoded_image, length) + CheckIsPNM(encoded_image, length) == 1" failed: Encoded image has ambiguous format
```

This is a 240 x 416 RGB image, i.e. a numpy array with shape (416, 240, 3) where all values are np.uint8 and therefore bounded between 0 and 255.   Do I need to specify anything else for ImageDecoder to know what to do with it?

Thank you

**Comment by JanuszL** [comment]
Hi,
If you providing raw, decoded data you no longer need to use the ImageDecoder in your pipeline. so just remove it.

**Comment by kikoaumond** [comment]
The problem is that it seems I need one of the ImageDecoder ops, since they are the only ops that accept device='mixed', otherwise I can't move the images to the GPU since ExternalSource only works on the CPU
And the ExternalSource examples in 

https://docs.nvidia.com/deeplearning/dali/archives/dali_0210_beta/dali-developer-guide/docs/examples/general/data_loading/external_input.html 

use ImageDecoder as the first step so the images are moved to the GPU
The images are read using opencv.imread() to provide a numpy array.  Is there anything I need to specify to make it work?
opencv reads the images and converts them to numpy arrays without errors.

**Comment by kikoaumond** [comment]
I figured it out.  After augmenting, one can re-encode the image 2D array read by opencv into an encoded 1D array that can be passed to Dali with

```
 _, buffer = cv2.imencode('.jpg', image)
```

That will create the one-dimensional encoded array (buffer) that ImageDecoder can now process

**Comment by JanuszL** [comment]
Hi,
You can deal with that in two ways:
- ask DALI to move the ExternalSource CPU output to GPU and then call a GPU operator:
```
def __init__(...):
    sefl.input = dali.ops.ExternalSource()
    self.op = dali.ops.SomeOp(device="gpu")
def define_graph(self):
    in = sefl.input()
    ret = self.op(in.gpu())
    return ret
```
- use ExernalSource with the GPU backend, so the ExternalSource will move the data to the GPU on its own:
```
def __init__(...):
    sefl.input = dali.ops.ExternalSource(device="gpu")
    self.op = dali.ops.SomeOp(device="gpu")
def define_graph(self):
    in = sefl.input()
    ret = self.op(in)
    return ret
```
I recommend checking what is faster in your case.

**Comment by samra-irshad** [comment]
> I figured it out. After augmenting, one can re-encode the image 2D array read by opencv into an encoded 1D array that can be passed to Dali with
> 
> ```
>  _, buffer = cv2.imencode('.jpg', image)
> ```
> 
> That will create the one-dimensional encoded array (buffer) that ImageDecoder can now process

Hey I am facing the same problem, I am directly encoding the image as bytes using `numpy.frombuffer` to avoid first reading the image and then encoding it (to reduce the data loading time). But it's giving me the same issue as `failed: Encoded image has ambiguous format.` I have verified reading the image using `imageio`, the image is not broken.

**Comment by JanuszL** [comment]
@samra-irshad - can you provide a simple self-contained repro that would show your problem? You can use https://github.com/NVIDIA/DALI_extra as a data source for it, so we can run this and debug on our side.
