### ISSUE TITLE
This package should not be installed

### ISSUE THREAD

**Issue by qiuhaining** [NVIDIA/DALI#2067]
my python version is 3.7

The error info is 
"""
Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-b_v6jcv5/nvidia-dali/setup.py", line 130, in <module>
        raise RuntimeError("This package should not be installed.\nPlease refer "
    RuntimeError: This package should not be installed.
    Please refer to NVIDIA instructions: https://github.com/nvidia/tensorflow.
    Your PIP command defaults to the official PyPI as a package repository.
"""

**Comment by rivergold** [comment]
I got the same error…

**Comment by JanuszL** [comment]
Hi,
DALI is not directly hosted on pypi.com due to several limitations. What is there is only a defensive package that reserves the DALI package name. To install DALI please follow this guide:
https://docs.nvidia.com/deeplearning/dali/user-guide/docs/installation.html#installing-prebuilt-dali-packages, and make sure you have the latest pip installed, or install `nvidia-pyindex` as https://github.com/nvidia/tensorflow guide states.

**Comment by qiuhaining** [comment]
> Hi,
> DALI is not directly hosted on pypi.com due to several limitations. What is there is only a defensive package that reserves the DALI package name. To install DALI please follow this guide:
> https://docs.nvidia.com/deeplearning/dali/user-guide/docs/installation.html#installing-prebuilt-dali-packages, and make sure you have the latest pip installed, or install `nvidia-pyindex` as https://github.com/nvidia/tensorflow guide states.

Hi, I re-install dali according to what you said, but i meet a new error，do you know why？
error info：
“”“
ERROR: Could not install packages due to an EnvironmentError: HTTPSConnectionPool(host='developer.download.nvidia.cn', port=443): Max retries exceeded with url: /compute/redist/cuda/10.0 (Caused by NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4d6f950dd0>: Failed to establish a new connection: [Errno -2] Name or service not known')
”””

**Comment by JanuszL** [comment]
It works for me
```
pip install --extra-index-url https://developer.download.nvidia.com/compute/redist/cuda/10.0 nvidia-dali
```
Can you try to use any direct links from https://github.com/NVIDIA/DALI/releases?

**Comment by qiuhaining** [comment]
> It works for me
> 
> ```
> pip install --extra-index-url https://developer.download.nvidia.com/compute/redist/cuda/10.0 nvidia-dali
> ```
> 
> Can you try to use any direct links from https://github.com/NVIDIA/DALI/releases?

 https://github.com/NVIDIA/DALI/releases,this url works for me! Thank you very much!
