### ISSUE TITLE
gcc 4.8.5 compiling error

### ISSUE THREAD

**Issue by crucifyml** [NVIDIA/DALI#207]
1. json.h 3.1.2 not support gcc 4.8.5
- update it to 3.3.0

2. Cannot convert to struct from brace-enclosed initializer list
- remove user-provided constructors
```diff
diff --git a/dali/pipeline/operators/displacement/displacement_filter.h b/dali/pipeline/operators/displacement/displacement_filter.h
index 31f90be..1b168a7 100644
--- a/dali/pipeline/operators/displacement/displacement_filter.h
+++ b/dali/pipeline/operators/displacement/displacement_filter.h
@@ -42,7 +42,8 @@ struct HasParam <T, decltype((void) (typename T::Param()), 0)> : std::true_type
 template <typename T>
 struct Point {
   const T x, y;
-  Point() = delete;
+  // FIXME: gcc 4.8.5 Cannot convert to struct from brace-enclosed initializer list
+  // Point() = delete;

   template <typename U>
   Point<U> Cast() {
```

**Comment by JanuszL** [comment]
Hi,
Currently we are not planning to provide support for older GCC compiler. Ubuntu 16.04 got GCC 5.x version by the default. Also according to https://en.cppreference.com/w/cpp/language/aggregate_initialization for aggregate initialization deleted constructors should be allowed so second point is definitely fault of GCC being not compliant.
What we could recommend is to update your GCC or adjust your code locally.

**Comment by crucifyml** [comment]
Maybe add minimum gcc version in README
