### ISSUE TITLE
How to release the gpu memory allocated to pipeline?

### ISSUE THREAD

**Issue by ben0it8** [NVIDIA/DALI#2070]
Hi,

Following #1842 I've tried  `del pipeline; gc.collect()`.

Here's the how the gpu memory changes for my little toy pipeline:

* after `build`: 168 MB
* after `run`: 314 MB
* after `gc.collect()`: 214 MB

I've also tried `pipeline._pipe=None` and it had the same effect.

I find this a bit confusing, shouldn't at least free up ~140 MB for the buffers allocated for the batch instead of just 100 MB?
Is there a general way to deallocate the gpu memory blocked by a pipeline?

Thanks a lot,
Oliver

**Comment by JanuszL** [comment]
Hi,
That is not expected. Can you provide a minimal, self-contained script that would reproduce this issue?

**Comment by ben0it8** [comment]
I've tried to use the record file in `DALI_extra`, but with 0.22 it says that the record file is invalid when I try to create the index with `tfrecord2idx`, so my minimal example assumes TF2.0 and Pillow:
```
import os
import io
import subprocess

from nvidia.dali.pipeline import Pipeline
import nvidia.dali.ops as ops
import nvidia.dali.types as types
import nvidia.dali.tfrecord as tfrec
import tensorflow as tf
import numpy as np
from PIL import Image

def get_x(value, format="JPEG"):
    img = Image.fromarray(value)
    byte_arr = io.BytesIO()
    img.save(byte_arr, format=format)
    bytes_ = byte_arr.getvalue()
    return tf.train.Feature(bytes_list=tf.train.BytesList(value=[bytes_]))
    
def serialize(x):
    feature = {
      'x': get_x(x, format="JPEG"),
    }
    proto = tf.train.Example(features=tf.train.Features(feature=feature))
    return proto.SerializeToString()

def get_mem():
    base_cmd = ["nvidia-smi", "--query-gpu=memory.used", "--format=csv,nounits,noheader"]
    return subprocess.check_output(base_cmd).decode("utf-8").strip().split("\n")
    
class TFRecordPipeline(Pipeline):
    
    def __init__(self, tfrecord, index_path, batch_size, num_threads, device_id):
        super(TFRecordPipeline, self).__init__(batch_size,
                                               num_threads,
                                               device_id)
        
        self.input = ops.TFRecordReader(path = tfrecord,
                                        index_path = index_path,
                                        num_shards=1, 
                                        shard_id=0,
                                        
                                        features = {
                                            "x": tfrec.FixedLenFeature((), tfrec.string, ""),
                                        })

        self.decode = ops.ImageDecoder(
            device='mixed',
            output_type=types.GRAY)
        self.bc = ops.BrightnessContrast(brightness=2.0, contrast=0.5, device="gpu")
        
    def define_graph(self):
        inputs = self.input()
        x = self.decode(inputs["x"])
        x = self.bc(x)
        return x

# Get data
X, _ = tf.keras.datasets.mnist.load_data()[0]
X= X[:100].astype("uint8")

# Define record file name and some data
tfrecord = "tfrecord"

# Create records
with tf.io.TFRecordWriter(tfrecord) as writer:
    for i in range(len(X)):
        x = X[i, ...]
        serialized_feature = serialize(x)
        writer.write(serialized_feature)

# Create index file
subprocess.check_call(["tfrecord2idx", "tfrecord", "tfrecord.idx"])

print("before:", get_mem())
pipe = TFRecordPipeline(tfrecord, "tfrecord.idx", batch_size=64, num_threads=1, device_id = 0)
pipe.build()
print("after build:", get_mem())
x = pipe.run()
print("after run:", get_mem())
del pipe
del x 
import gc; gc.collect()
print("after gc.collect():", get_mem())
```

Without a color op the final allocated memory size is the same as after build.

As for the original question: is there a general way to release gpu memory?

Best,
Oliver

**Comment by JanuszL** [comment]
>  but with 0.22 it says that the record file is invalid when I try to create the index with tfrecord2idx

Do you have git-lfs installed? If not please follow [this guide](https://git-lfs.github.com/) and resync `DALI_extra`.

**Comment by JanuszL** [comment]
Hi,

I have double-checked and that behavior you see is intended. There is no memory leak in DALI. This additional grow comes from the fact that DALI consists of a couple of separated dynamic libraries.  When you issue pipeline builds you interact only with libdali and the backend. When you call the color operation you interact with libdali_kernels (this happens after DALI build). When libdali_kernels is invoked operator code is loaded to the device and that is why you see this memory consumption grow.

> As for the original question: is there a general way to release gpu memory?
Only when you remove the pipeline. In other cases, we don't do that as any memory allocation/deallocation requires a device to synchronize and take dozens of ms. Depp Learning FWs usually don't do that either.

**Comment by JanuszL** [comment]
Also, if you repeat
```
print("before:", get_mem())
pipe = TFRecordPipeline(tfrecord, "tfrecord.idx", batch_size=64, num_threads=1, device_id = 0)
pipe.build()
print("after build:", get_mem())
x = pipe.run()
print("after run:", get_mem())
del pipe
del x 
import gc; gc.collect()
print("after gc.collect():", get_mem())
```
a couple of times the memory usage won't increase.

**Comment by ben0it8** [comment]
Thanks for the clarification.

**Comment by cceyda** [comment]
Is it possible to release memory after an exception occurs? I tried a couple of things mentioned at https://github.com/NVIDIA/DALI/issues/2070 without success 

```py
del pipe
gc.collect()
```
works when no exception occurs.but 
```py
try:
   pipe.run()
except Exception as e:
   del pipe
   gc.collect()
```
just hangs.
