### ISSUE TITLE
python binding install error

### ISSUE THREAD

**Issue by songtaoshi** [NVIDIA/DALI#2074]
ERROR: Directory 'dali/python' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.

Hi, I have followed the instruction on the docs, but I have trouble in the python binding installation.  

Here are the files in the build folder.  

![image](https://user-images.githubusercontent.com/20240391/86077427-89ff8b80-babe-11ea-9b2c-6b0746fa681d.png)

![image](https://user-images.githubusercontent.com/20240391/86077455-92f05d00-babe-11ea-93b7-73e6e6c399e7.png)

![image](https://user-images.githubusercontent.com/20240391/86077482-9e438880-babe-11ea-9c95-4fcac83e6e5e.png)

**Comment by JanuszL** [comment]
Hi,
You should have more files inside `dali/python`. Can you provide the exact build command do you use?
Remember to pass `-DBUILD_PYTHON=ON`  to CMake to have python bindings build.

**Comment by songtaoshi** [comment]
![image](https://user-images.githubusercontent.com/20240391/86113160-77577780-bafb-11ea-927f-28a6048d242c.png)

I just follow the instructions in the docs. 

cmake -D CMAKE_BUILD_TYPE=Release ..


So I need to add the -DBUILD_PYTHON=ON to the CMAKE?

**Comment by JanuszL** [comment]
`-DBUILD_PYTHON=ON` should be set by default, but I just wanted to be sure that is set.
I just checked our master branch and it works as the guide states.
Can you try to capture and provide all logs from build (cmake and make)?

**Comment by songtaoshi** [comment]
do you follow the instruction from BUILD DALI down to Install Python bindings?

**Comment by JanuszL** [comment]
What I did is:
```
$cd DALI
$mkdir build
$cd build
$cmake ../
$make -j
l$s dali/python
Acknowledgements.txt  CMakeFiles  cmake_install.cmake  COPYRIGHT  LICENSE  Makefile  MANIFEST.in  nvidia  rec2idx.py  setup.py  tfrecord2idx
$pip install dali/python
```

**Comment by songtaoshi** [comment]
Thanks for your reply. maybe it is caused by **-D CMAKE_BUILD_TYPE=Release**. If cmake with this flag. We may not need to install python binding and also **pip install dali/python** cannot find the setup. I think you can have a try.

**Comment by JanuszL** [comment]
It still works as expected done your way.
Have you tried to[ dockerized build](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/compilation.html#compiling-dali-from-source-using-docker-builder-recommended)?

**Comment by songtaoshi** [comment]
No, but I have successfully build a pipeline, I am wondering what would the python binding do?  import ops written in python function?

**Comment by JanuszL** [comment]
>  I am wondering what would the python binding do? 

It allows to use of DALI from Python level and exposes C++methods in Python. It is possible to use C++ API directly although it is not stable and that is why it is not documented.

**Comment by songtaoshi** [comment]
Got it. Thanks a lot!
