### ISSUE TITLE
How to make a new batch on one picture with Slice in Pipline

### ISSUE THREAD

**Issue by qiuhaining** [NVIDIA/DALI#2085]
Hello,I have a question:  how to make a new batch on one picture with Slice ops in Pipline！the attrbutions： ‘anchor ’and ‘shape’   are given by ops.ExternalSource()?

Obviously, the length of  the ‘anchor ’and ‘shape’ is larger than batch_size in Pipline, because i want to repeat sampling to make a new batch on one picture.

**Comment by klecki** [comment]
Hi,
DALI keeps the same batch size for all operators in pipeline - if input to Slice is just 1 image you can only output 1 image from it.

What you can do it to set the batch size to 1, create as many Slice operators as you want to have samples, and return every sample as a separate output from the DALI pipeline. If you are only processing one sample, you don't need to use ExternalSource to provide the parameters.
Arguments provided in Slice Operator constructor will be used for all the samples (in your case it is only 1 sample).
You can concatenate them into one batch outside DALI using Tensor operation from the deep learning framework of your choice.

**Comment by JanuszL** [comment]
Hi @qiuhaining,

You can use [the `stack` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.stack) to build a sequence of frames and then have a DL FW tensor with all images one next to another.
