### ISSUE TITLE
Cannot seem to use a tuple size for nvidia.dali.ops.RandomResizedCrop

### ISSUE THREAD

**Issue by samarth4149** [NVIDIA/DALI#2086]
Hi, 

Using a tuple of 2 ints as the `size` argument to represent height and width seems to throw an error. The documentation seems to suggest that a list of integers should work for that argument. 

I tried using a single integer in the same argument and I did not find an error. However I'm unsure if that is interpreted as both height and width being the same.

**Comment by JanuszL** [comment]
Hi,
What error do you receive?
Can you provide a self-contained and minimal reproduction script?
We are using RandomResizedCrop in this way in our test, like [here](https://github.com/NVIDIA/DALI/blob/master/dali/test/python/test_RN50_data_fw_iterators.py#L30) and we don't have any problems.

**Comment by samarth4149** [comment]
Hi, I found a bug in my implementation. Thanks for the response.
