### ISSUE TITLE
Best way to implement sequence of image transforms

### ISSUE THREAD

**Issue by samarth4149** [NVIDIA/DALI#2087]
Hi, 

I wish to implement the following sequence of transforms: Resize image -> Random crop -> Random Horizontal flip -> Normalize image pixel-wise

I am not sure what the best way to get there is. From the operators available and looking at the imagenet training example, I thought of a couple ways, but I encountered some problems with both of them. A [link](https://gist.github.com/samarth4149/cd9ed0895bc0e00461a0b7e4e385c8b8) to my code snippet 

Method 1 : I can't figure out a way to use Normalize for my use case since it only seems to allow a single floating point mean and stddev.

Method 2 : I get the following error:
`RuntimeError: [/opt/dali/dali/operators/image/resize/resize_crop_mirror.h:54] Assert on "(resize_shorter_ || resize_longer_) != (resize_x_ || resize_y_)" failed: Options `resize_{short
er,longer}` and `resize_x` or `resize_y` are mutually exclusive for schema "Resize"`

Also, is there a more straightforward way of getting this sequence of transforms?  Currently I'm not use the entire functionality of the operators used.

**Comment by JanuszL** [comment]
Hi,
>Resize image -> Random crop -> Random Horizontal flip -> Normalize image pixel-wise

How this differs from the RN50 pipeline?

> Method 1 : I can't figure out a way to use Normalize for my use case since it only seems to allow a single floating point mean and stddev.

```
- mean (float, optional, default = 0.0) – Mean value to subtract from the data. It can be either a scalar or a batch of tensors with same dimensionality as the input and the extent in each dimension must either match that of the input or be equal to 1 (in which case the value will be broadcast in this dimension). If not specified, the mean is calculated from the input. Non-scalar mean cannot be used when batch argument is True.
- stddev (float, optional, default = 0.0) – Standard deviation value to scale the data. For shape constraints, see mean argument. If not specified, the standard deviation is calculated from the input. Non-scalar mean cannot be used when batch argument is True.
```
You need to provide or scalar common to all channels, or batch of data that matches the input. So you need to use the external source and provide normalization data with the following dimensionality [batch_size, 1, 1, 3].

> Method 2 : I get the following error:
RuntimeError: [/opt/dali/dali/operators/image/resize/resize_crop_mirror.h:54] Assert on "(resize_shorter_ || resize_longer_) != (resize_x_ || resize_y_)" failed: Options resize_{short
er,longer}andresize_xorresize_y are mutually exclusive for schema "Resize"

You have misused the resize operator. Please check [the documentation ](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.ops.Resize), `max_size` can be used only with `resize_shorter`. Maybe you need to use `resize_x` and `resize_y`?
