### ISSUE TITLE
question about the ops.pad align parameters

### ISSUE THREAD

**Issue by songtaoshi** [NVIDIA/DALI#2089]
![image](https://user-images.githubusercontent.com/20240391/86608586-513f4500-bfdd-11ea-9a22-18bcd2491717.png)
Hi, I think I am struggling with docs TAT, It's really hard to know what the align option do even though I really want to use some more operations.

**Comment by JanuszL** [comment]
Hi,
`align` aligns elected axis/dimension size to be a multiply of its value. In the first example, all tensors have it 0 dimensions made multiply of 4, in the second multiply of 2.

**Comment by songtaoshi** [comment]
Thanks for your reply. But why in the first case, the [2,2] is not aligned to [2,2,-1,-1]

**Comment by JanuszL** [comment]
Hi,
Please check:
```
shape (int or list of int, optional, default = []) – The extents of the output shape in the axes specified by axes or axis_names. Specifying -1 for an axis restores the default behavior of extending the axis to accommodate the (aligned) size of the largest sample in the batch. If the provided extent is smaller than the one of the sample, no padding will be applied, except what is needed to match required alignment.
```
which has a default value of -1 in the first example and makes all samples to be extended to the largest one.

**Comment by songtaoshi** [comment]
got it thanks!

**Comment by songtaoshi** [comment]
But I think most of the readers care more about what the align do, and really hope to get the meaning in a short time. So maybe you can put this on the example or put it to introduction of align. You put in such place really waste the reader's time!

**Comment by JanuszL** [comment]
We plan to move code samples after the operator description. Do you think would that improve readability?

**Comment by songtaoshi** [comment]
I think the order is not the key.      
1) explain the shape -1 default affect the align in the code example      
2) move the shape -1 default value effect to the explanation of align part

**Comment by JanuszL** [comment]
If you have any specific wording in mind feel free to improve [pad docs here](https://github.com/NVIDIA/DALI/blob/master/dali/operators/generic/pad.cc) and fill a PR with changes.

**Comment by jantonguirao** [comment]
@songtaoshi Could you take a look at this documentation change proposal and let us know if it makes it clearer:
https://github.com/NVIDIA/DALI/pull/2098

Thank you
