### ISSUE TITLE
Segmentation fault (core dumped) when running the videoreader example

### ISSUE THREAD

**Issue by Oldog** [NVIDIA/DALI#2090]
Hello I'm trying to use DALI to read frames from compressed video files. But when I run the video example ( as instructed [here]( https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/sequence_processing/video/video_reader_simple_example.html))  I just get a segmentation fault. The following is my code:

```
from __future__ import print_function
from __future__ import division
import os
import cv2
#import ToolsForLF
import numpy as np
import json
import time
import torch

from nvidia.dali.pipeline import Pipeline
import nvidia.dali.ops as ops
import nvidia.dali.types as types

batch_size = 2
sequence_length = 8

initial_prefetch_size = 16

video_directory = os.path.join('/home/zhaosy/Work/Multi-view_medical/lightfieldwarping/data/DALI_extra', "db", "video", "sintel", "video_files")

video_files=[video_directory + '/' + f for f in os.listdir(video_directory)]

shuffle = False

n_iter = 6


class VideoPipe(Pipeline):
  def __init__(self, batch_size, num_threads, device_id, data, shuffle):
    super(VideoPipe, self).__init__(batch_size, num_threads, device_id, seed=16)
    self.input = ops.VideoReader(device="gpu", filenames=data, sequence_length=sequence_length,
                                 shard_id=0, num_shards=1,
                                 random_shuffle=shuffle, initial_fill=initial_prefetch_size)
  
  def define_graph(self):
    output = self.input(name="Reader")
    return output


pipe = VideoPipe(batch_size=batch_size, num_threads=2, device_id=0, data=video_files, shuffle=shuffle)
pipe.build()
```
Here the video directory is where I put the DALI_extra folder.
But when I ran the script, I just got the result:
![image](https://user-images.githubusercontent.com/9655283/86615403-fca0c780-bfe6-11ea-8f83-ae2db784bc6b.png)
![image](https://user-images.githubusercontent.com/9655283/86615503-1b9f5980-bfe7-11ea-8a67-2fae57941544.png)

Does anyone know what's wrong? I really appreciate for your help.

**Comment by Oldog** [comment]
My environment:
Pytorch 1.20
Cuda 10.1
Python 3.7

**Comment by JanuszL** [comment]
Hi,
Do you have your [git LFS](https://git-lfs.github.com/) installed?  Without it files downloaded from DALI_extra are invalid as they have git-lfs metadata.
If that doesn't help please capture full DALI error - if you run it from the console you should get it.

**Comment by Oldog** [comment]
> Hi,
> Do you have your [git LFS](https://git-lfs.github.com/) installed? Without it files downloaded from DALI_extra are invalid as they have git-lfs metadata.
> If that doesn't help please capture full DALI error - if you run it from the console you should get it.

I installed git LFS just now, but nothing changed. Also I ran it from the console but I just got one-line result (as shown in the figure).

I'm using the conda environment. I don't know if it is the conda which prevents script from outputing full error. 

![image](https://user-images.githubusercontent.com/9655283/86618056-d1b87280-bfea-11ea-9fa2-615e49f13d5a.png)

**Comment by JanuszL** [comment]
Can you run gdb and show the full stack trace?
```
gdb python
r testDALI.py
```
?

**Comment by Oldog** [comment]
> Can you run gdb and show the full stack trace?
> 
> ```
> gdb python
> r testDALI.py
> ```
> 
> ?

Thanks for the reply. Here is the result.

![image](https://user-images.githubusercontent.com/9655283/86625985-9a50c280-bff8-11ea-855f-353699a5b9fe.png)

Also I use pdb to debug it. It just throws a segment fault (pipline.py, line 437).

![image](https://user-images.githubusercontent.com/9655283/86626735-b30da800-bff9-11ea-9813-af36ac92e8e0.png)

**Comment by JanuszL** [comment]
I have run your code inside nvidia/cuda:10.2-devel-ubuntu18.04, installed miniconda, created 3.7 python env, installed `conda install pytorch=1.2 torchvision cudatoolkit=10.2 -c pytorch`, installed DALI `pip install --extra-index-url https://developer.download.nvidia.com/compute/redist nvidia-dali-cuda100` and your code works just fine.
Keep in mind to run DALI in docker you need to pass appropriate capabilities  --gpus 'all,"capabilities=compute,utility,video"'.
Yous stack trace shows a problem inside FFmpeg library. However, this is the version we build and ship so it should not interfere with the one you have installed in your system.

**Comment by JanuszL** [comment]
I would double check if the files you have inside `/home/zhaosy/Work/Multi-view_medical/lightfieldwarping/data/DALI_extra/db/video/sintel/video_files` can be played.

**Comment by Oldog** [comment]
> I would double check if the files you have inside `/home/zhaosy/Work/Multi-view_medical/lightfieldwarping/data/DALI_extra/db/video/sintel/video_files` can be played.

You're right. The video files are broken and it works when I re-download them from the extra repository.

Also it works well with my own data after I mux HEVC file into .mp4 file.

That's my silly mistake... So grateful for your patience and help! :smile::smile:

Just one more question: does there exist any O(1) operation to convert TensorGPU to pytorch tensor (on GPU) ? I find function feed_ndarray but it needs to copy the data first.

**Comment by JanuszL** [comment]
Hi,
I'm glad it works.
> Just one more question: does there exist any O(1) operation to convert TensorGPU to pytorch tensor (on GPU) ? I find function feed_ndarray but it needs to copy the data first.
It is device 2 device copy so it is rather fast. Also, DALI supports array interface and CUDA array interface representation. So if Torch supports this API (and as far as I know it does) you can just pass DALI Tensor/TensorList (if TorchList is uniform) to Torch tensor constructor. You need to keep DALI output alive as long as you are using Torch tensor created from it.

**Comment by Oldog** [comment]
> Hi,
> I'm glad it works.
> 
> > Just one more question: does there exist any O(1) operation to convert TensorGPU to pytorch tensor (on GPU) ? I find function feed_ndarray but it needs to copy the data first.
> 
> It is device 2 device copy so it is rather fast. Also, DALI supports array interface and CUDA array interface representation. So if Torch supports this API (and as far as I know it does) you can just pass DALI Tensor/TensorList (if TorchList is uniform) to Torch tensor constructor. You need to keep DALI output alive as long as you are using Torch tensor created from it.

I tried but it told me "the read only flag is not supported, should always be False“. It seems like the TensorGPU gotten from the videoReader is read-only.

**Comment by JanuszL** [comment]
Yes, it is read only.
