### ISSUE TITLE
RuntimeError: [/opt/dali/dali/pipeline/operators/reader/video_reader_op.h:51] [/opt/dali/dali/pipeline/operators/reader/loader/video_loader.cc:59] ]

### ISSUE THREAD

**Issue by Shuai-Yuan-sjtu** [NVIDIA/DALI#2091]
When I use the nvidia-dali 0.10.0, "RuntimeError: [/opt/dali/dali/pipeline/operators/reader/video_reader_op.h:51] [/opt/dali/dali/pipeline/operators/reader/loader/video_loader.cc:59] ]

**Comment by JanuszL** [comment]
Hi,
Could you provide the code you run? What data did you use to run it?
According to `/opt/dali/dali/pipeline/operators/reader/video_reader_op.h:51` you may have provided wrong output data type. Only Float and Int8 are supported.

**Comment by Shuai-Yuan-sjtu** [comment]
Thanks for your reply. Actually I'm working on  https://github.com/m-tassano/fastdvdnet  this project. My version is cuda10.0 and use the nvidia-dali 0.10.0 just like the authors. My training dataset is .mp4.

**Comment by JanuszL** [comment]
HI,
I was asking about the piece of code that uses DALI directly? Have you tried to run [video example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/sequence_processing/video/video_reader_simple_example.html)?
If it still doesn't work please provide a minimal, self-contained code sample that reproduces your problem.

**Comment by Shuai-Yuan-sjtu** [comment]
hi, 
dlopen "libnvcuvid.so" failed!
[opt/dali/dali/operators/reader/video_reader_op.h:66][/opt/dali/dali/operators/reader/loader/video_loader.h:182] assert on "lib_handle_" failed: falied to load libnvcuvid.so, neede by the VideoReader operator.

Do I need to install extra software?

**Comment by JanuszL** [comment]
Hi,
Do you run it from the docker? If so you need to pass a right capabilities, [see more](https://github.com/NVIDIA/nvidia-docker/issues/1128#issuecomment-557930809).

**Comment by Shuai-Yuan-sjtu** [comment]
Hi, I just use 
pip install --extra-index-url https://developer.download.nvidia.com/compute/redist/cuda/10.0 nvidia-dali==0.10.0  
to install dali.

Sorry, I don't know what do you mean. Could you please give me more instructions?

**Comment by JanuszL** [comment]
What driver and gpu you have? What os version? Are you running in bare metal or a docker container?
`libnvcuvid.so` is part of the driver so it should be there.

**Comment by Shuai-Yuan-sjtu** [comment]
Diver version:440.33.01 ,CUDA version :10.2  GPU: TITAN Xp, docker container

**Comment by JanuszL** [comment]
So try to add to your nvidia-docker/docker command following option `--gpus '"capabilities=compute,utility,video"'` as described [here](https://github.com/NVIDIA/nvidia-docker/issues/1128#issuecomment-557930809).

**Comment by Shuai-Yuan-sjtu** [comment]
Thanks for your help. The problem has been solved.

**Comment by cailijing** [comment]
Hello！For an established Docker, can we modify its configuration parameters. Or we have to create a new docker

**Comment by JanuszL** [comment]
Hi @cailijing,

You can either provide the runtime parameters, like `--gpus '"capabilities=compute,utility,video"'` or set environment variables when building it from a docker file `ENV NVIDIA_DRIVER_CAPABILITIES=compute,utility,video`.
I think it is best to reference the docker documentation.

**Comment by cailijing** [comment]
@JanuszL  Thank you!

**Comment by cailijing** [comment]
@JanuszL 
Hello, I create the docker with the command
sudo docker run -e NVIDIA_DRIVER_CAPABILITIES=all --gpus all -d -itv /home/data0/cailijing:/home/cailijing --shm-size=8g -p 28:22 --name cailijing 05ab39bc02ee /bin/bash

but I still meet the problem
[/opt/dali/dali/operators/reader/loader/video_loader.h:183] Assert on "ret" failed: Failed to load libnvcuvid.so, needed by the VideoReader operator. If you are running in a Docker container, please refer to https://github.com/NVIDIA/nvidia-docker/wiki/Usage

Could you help me analyze why I still report this mistake?

**Comment by cailijing** [comment]
I'm also working on https://github.com/m-tassano/fastdvdnet this project.
Driver Version: 470.103.01   CUDA Version: 11.4  GPU: 3090

**Comment by JanuszL** [comment]
Hi @cailijing,

I think you forgot to add `video` to the capabilities. Try:
```
sudo docker run -e NVIDIA_DRIVER_CAPABILITIES=all --gpus 'all,"capabilities=compute,utility,video"' -d -itv /home/data0/cailijing:/home/cailijing --shm-size=8g -p 28:22 --name cailijing 05ab39bc02ee /bin/bash```

**Comment by cailijing** [comment]
@JanuszL  The problem has been solved.Thank you.
