### ISSUE TITLE
DALI CPU mode reduce the training speed

### ISSUE THREAD

**Issue by weberxie** [NVIDIA/DALI#2095]
Hi team,

I train the ResNet 50 with PyTorch 1.2, DALI 0.19, Horovod 0.19 on 8 V100 cards,

If I feed the input with random data, the time of per iteration is about 170ms,
If I feed the input with DALI CPU, the time of per iteration is about 260ms,

I profiled it with nvprof and nvvp, the results show that there are some idle time of GPU, even though I did prefetch, the time to get the next batch from  Pipeline is about zero.

So, are there any suggestions that can guide me in further analysis? Thanks!

<img width="1256" alt="Screen Shot 2020-07-08 at 9 14 39 PM" src="https://user-images.githubusercontent.com/3942083/86923222-55e03680-c160-11ea-9636-6996df4ec94b.png">

[preprocess_and_synthetic_nvvp.zip](https://github.com/NVIDIA/DALI/files/4890838/preprocess_and_synthetic_nvvp.zip)

**Comment by JanuszL** [comment]
Hi,
Will take a look into your profile. Do you train one of the examples provided in our repo or you have own code?
What do you mean by `feed the input with DALI CPU` and `feed the input with random data`? Do you use ExternalSource operator?

**Comment by weberxie** [comment]
Hi,

I train it with my own code.

> What do you mean by feed the input with DALI CPU and feed the input with random data? Do you use ExternalSource operator?

**feed_ the input with DALI CPU** means feed the input with ExternalSource operator.

**feed the input with random data** means generate random input data and feed it into model directly.

Below is my code:

[train.py.zip](https://github.com/NVIDIA/DALI/files/4895796/train.py.zip)

Thanks!

**Comment by JanuszL** [comment]
Hi,
The ExternalSource operator is not the best way to feed data to the DALI pipeline, it blocks on python user thread until data provided is staged inside DALI internal buffer.
Another thing is that you are using a CPU pipeline which maybe not as fast as you need.
I also recommend to update to the latest DALI version as the one you are using doesn't have NVXT ranges enabled by default os it is hard to tell when DALI do its job compared to the GPU timeline.

**Comment by JanuszL** [comment]
Hi,

The most recent improvements of [the `external_source` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.external_source) make it parallel to the training and scales with the number of CPUs. Please check `parallel` and `prefetch_queue_depth` options.
