### ISSUE TITLE
Extracting multiple patches with offsets from one image and modifying the labels for the patches with the same offset

### ISSUE THREAD

**Issue by bensuucar** [NVIDIA/DALI#2104]
Hello,

I would like to extract  multiple patches from one image with different offsets. For example, I extract one patch from the center of the image and the next patch is extracted with one pixel offset from the x direction and one pixel from the y direction. 
Furthermore, I would like to update the labels associated for these different patches. For example, if the patch from the center has a label of 0.2, the patch extracted with an offset of 1 should have a label of 1.2. 
Is there any way/feature that I can have this interactive patch extraction together with label updates?

Besides, the labels are not integer, this is another problem that I am facing while loading the labels from ExternalInputIterator

Thank you!

**Comment by JanuszL** [comment]
Hi,
> Besides, the labels are not integer, this is another problem that I am facing while loading the labels from ExternalInputIterator

ExternalSource supports floats as well, can you be more specific what is the problem there?

> I would like to extract multiple patches from one image with different offsets

I think you can use the slice operator and drive it from the data provided by ExternalSource. If you pass labels and coordinates using ExternalSource you can do this label correction at the python side.

**Comment by bensuucar** [comment]
Thank you for your fast reply!

I have been trying to use the Slice operator however I couldn't succeed. After struggling with different errors, I would like to ask more clarification.
Could you please explain the difference between Slice and Crop?
And what is the role of the anchor and shape parameters? I couldn't understand even though I went through the documentation couple of times. Does it have to be multiple x values as described as 'the starting point of the slice (x0, x1, x2, …)' ? Then where should I provide y values?

Besides, I have many images in my dataset, however I would like to get multiple patches from each image. Do I have to introduce a 'for loop' for every image in the batch to get multiple slices with different coordinates? Because if I am supposed to provide this different coordinates in anchor and size parameter of Slice, how does it make sure that it applies all these different coordinates to each individual images? 

Plus, I couldn't find any informative example of Slice operator, it would be great if you can point me to one! 

Thank you very much!

**Comment by jantonguirao** [comment]
Hello @bensuucar,

Slice and Crop operators perform the same operation, but their APIs differ. The main difference is that Crop operator API is designed for images and it provides a slightly more friendly way to provide image coordinates. Slice operator, on the other hand, is more generic, and it allows you to extract slices from any kind of data layout.

None of them support extracting multiple patches. To do that, you'll need different operator instances, one per patch.
```
#in pipeline ctor:
self.crop1 = ops.Crop(device='gpu', crop_w=..., crop_h=..., crop_pos_x=..., crop_pos_y=...)
self.crop2 = ops.Crop(device='gpu', crop_w=..., crop_h=..., crop_pos_x=..., crop_pos_y=...)
...

#in define_graph():
patch1 = self.crop1(images)
patch2 = self.crop2(images)
```

To achieve something similar with Slice operator, you need to specify the layout of your arguments, and those are feed as regular inputs. For instance:
```
#in pipeline ctor:
self.slice1 = ops.Slice(device='gpu', axis_names = 'WH')  # Arguments will be ordered as x, y
self.slice2 = ops.Slice(device='gpu', axis_names = 'WH')  # Arguments will be ordered as x, y

# in define_graph():
patch1 = self.slice1(images, anchor1, shape1)
patch2 = self.slice2(images, anchor2, shape2)
```
In this example,  `anchor` is expected to be a 2-element tensor, where the first element represents start `x` (because of the 'W' dimension) and the second argument represents start `y`. Similarly, `shape`'s first element is interpreted as the width and height of the slice.

The issue here is that patch1 and patch2 are two separate batches. Currently, there is no way to combine those, because DALI assumes the batch_size is fixed, so each pipeline output should have the same number of samples. Depending on how you plan to use those patches that might be a problem or not.

If what you need selecting either patch1 or patch2 based on a random variable or something like that, you could achieve that with arithmetic expressions. You can see an example here: 
https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/expressions/expr_conditional_and_masking.html#The-multiplexing-operation

You can also modify the labels with arithmetic expressions:
```
# in define_graph():
labels2 = labels1 + 1.0
```

**Comment by bensuucar** [comment]
Hi,

Thanks again for your informative reply. 

I couldn't really understand why patch1 and patch2 are two separate batches ( if my batch size is larger than 2).
I understand that since I am looping over the elements in a batch in __next__ function in ExternalInputIterator, so I already get batch size number of images and I am introducing multiple patches, it is indeed a little complicated how they are going to be fed through the network.

I would like to extract around 50patches from one single image in a batch and feed them to the network since I can increase my training dataset in this way and make use of other parts of the raw image. But as you said , I need to write 50 operator instances and I am not sure how they will be fed to the network since I am increasing the number of samples in one batch. 

Furthermore, another difference between Slice and Crop is that I can use raw pixel coordinates with Slice by specifying normalized_anchor and normalized_shape. It would be easier to use Crop if this feature was possible as well. Because when I try to use Slice it is giving me data type issues, perhaps I cannot fed anchor and shape parameters as tensors even though I define them in ExternalInputIterator and pass them together with images and labels. How can I define anchor and shape parameters as Tensorlist?

And as a last thing, could you please explain the difference between using Decode and Crop and using ImageDecoderCrop (or similiarly Decode+Slice and ImageDecoderSlice ) ?

Thanks!

**Comment by jantonguirao** [comment]
@bensuucar

DALI works always on a fixed batch size along the pipeline, so every output will have the same number of samples. So if you feed Crop with 16 images, you'll get 16 images in the output. You can't alter that. If you need to extract multiple patches from a single image, the only way to do that now is to have multiple outputs of your pipeline and then you can combine them outside of the DALI pipeline.

Regarding Slice vs Crop, yes Slice can handle both normalized and absolute coordinates, while Crop works slightly differently. If your slice shapes are coming from external sources and are potentially relative, Slice would be the way to go. If you have any issues with your pipeline, please share your pipeline code here and we could tell what might wrong.

`ImageDecoderCrop` and `ImageDecoderSlice` are fused operators that combine the functionality of `ImageDecoder` and `Crop`/`Slice`. The results you get are equivalent to chaining those two operators, but you can benefit from the fact that that fused decoders can make use of region-of-interest (ROI) decoding APIs (only supported for JPEGs currently), so only the relevant part of the image is decoded, saving memory and compute.

**Comment by bensuucar** [comment]
Hello,

My code for Crop operation is below, however I am getting a Type error and when I checked the position and shape parameters, they appear as DataNode.

Besides, I used  **crop_x = crop_x_norm * (W - crop_W)** function to convert the pixel coordinates to normalised ones.  It does not seem the most efficient one. 

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-109-1968debb80a7> in <module>
    134 
    135 pipe = SimplePipeline(image_dir, batch_size, 1, 0 )
--> 136 pipe.build()
    137 pipe_out = pipe.run()
    138 images_out = pipe_out[0].as_array()

~/anaconda3/envs/efficientDet/lib/python3.7/site-packages/nvidia/dali/pipeline.py in build(self, define_graph)
    474 
    475         if not self._prepared:
--> 476             self._prepare_graph(define_graph)
    477 
    478         self._pipe.Build(self._names_and_devices)

~/anaconda3/envs/efficientDet/lib/python3.7/site-packages/nvidia/dali/pipeline.py in _prepare_graph(self, define_graph)
    393                 import nvidia.dali.ops
    394                 outputs[i] = nvidia.dali.ops._instantiate_constant_node("cpu", outputs[i])
--> 395             _data_node._check(outputs[i])
    396 
    397         # Backtrack to construct the graph

~/anaconda3/envs/efficientDet/lib/python3.7/site-packages/nvidia/dali/data_node.py in _check(maybe_node)
    114         raise TypeError(("Expected outputs of type compatible with \"DataNode\"."
    115                 " Received output type with name \"{}\" that does not match.")
--> 116                 .format(type(maybe_node).__name__))

TypeError: Expected outputs of type compatible with "DataNode". Received output type with name "NoneType" that does not match.


```from __future__ import division
import os
import glob
import types
import collections
import numpy as np
from random import shuffle
from nvidia.dali.pipeline import Pipeline
import nvidia.dali.ops as ops
import nvidia.dali.types as types
import matplotlib.gridspec as gridspec
import matplotlib.pyplot as plt


batch_size = 2
epochs = 3
mode = 'train'
image_dir = '/home/bensu/Desktop/Share/im_folder/'
device_id = 0


def show_images(image_batch):
    columns = 2
    rows = (batch_size + 1) // (columns)
    fig = plt.figure(figsize = (32,(32 // columns) * rows))
    gs = gridspec.GridSpec(rows, columns)
    for j in range(rows*columns):
        plt.subplot(gs[j])
        plt.axis("off")
        plt.imshow(image_batch.at(j))

class ExternalInputIterator(object):
    def __init__(self,image_dir, mode, batch_size, device_id):
        self.mode = mode

        self.images_dir = image_dir
        self.batch_size = batch_size
        self.device_id = device_id

        with open(self.images_dir + "file_list.csv", 'r') as f:
            self.files = [line.rstrip() for line in f if line is not '']
        # whole data set size
        self.data_set_len = len(self.files)
        # based on the device_id and total number of GPUs - world size
        # get proper shard
        print('!!!!!!!!!!!!!!!!!!!!', self.files)
        self.files = self.files[self.data_set_len * device_id :
                                self.data_set_len * (device_id + 1)]
        self.n = len(self.files)

        '''if self.mode=='train':
            c = list(zip(self.image_path_list, self.label_path_list,self.imsize))
            random.shuffle(c)
           
            self.image_path_list, self.label_path_list,self.imsize = zip(*c)    '''

    def __iter__(self):
        self.i = 0
        shuffle(self.files)
        return self


    def __next__(self):
        batch = []
        labels = []
        crop_x = []
        crop_y = []
        crop_shape = []
       
        crop_y = 0
        H = 1234
        crop_H = 52
        crop_y_norm = crop_y / (H - crop_H)
       
        crop_x = 580
        W = 1624
        crop_W = 52
        crop_x_norm = crop_x / (W - crop_W)

        if self.i >= self.n:
            raise StopIteration

        for _ in range(self.batch_size):
            jpeg_filename, label = self.files[self.i].split(' ')
            f = open(self.images_dir + jpeg_filename, 'rb')
            batch.append(np.frombuffer(f.read(), dtype = np.uint8))
            labels.append(np.array([label], dtype = np.float))
            crop_shape.append([52,52])
            crop_x.append(np.array([crop_x_norm] , dtype = np.float))
            crop_y.append(np.array([crop_y_norm] , dtype = np.float))
            self.i = (self.i + 1) % self.n
        return (batch, labels , crop_shape , crop_x , crop_y)

    @property
    def size(self,):
        return self.data_set_len

    next = __next__


class SimplePipeline(Pipeline):
    def __init__(self,image_dir,batch_size,num_threads, device_id):
        super(SimplePipeline,self).__init__(batch_size,num_threads,device_id, seed=12)
        eii = ExternalInputIterator(image_dir,mode,batch_size,device_id)
        self.iterator = iter(eii)
        self.input = ops.ExternalSource()
        self.input_label = ops.ExternalSource()
        self.crop_shape = ops.ExternalSource()
        self.crop_x = ops.ExternalSource()
        self.crop_y = ops.ExternalSource()
        self.decode = ops.ImageDecoder(device = 'gpu', output_type=types.RGB)    #BE CAREFULL THE DEVICE IS SET TO CPU
        self.crop = ops.Crop(device = 'gpu')
       
       
    def define_graph(self):
        self.jpegs = self.input()
        self.labels = self.input_label()
        self.crop_shape = self.crop_shape()
        self.crop_x = self.crop_x()
        self.crop_y = self.crop_y()
        images = self.decode(self.jpegs)
        output = self.crop(images, crop  = self.crop_shape, crop_pos_x=self.crop_x, crop_pos_y =self.crop_y)
       

    def iter_setup(self):
        try:
            (images, labels) = self.iterator.next()
            self.feed_input(self.jpegs, images)
            self.feed_input(self.labels, labels)
        except StopIteration:
            self.iterator = iter(self.external_data)
            raise StopIteration


pipe = SimplePipeline(image_dir, batch_size, 1, 0 )
pipe.build()
pipe_out = pipe.run()
images_out = pipe_out[0].as_array()
labels_out = pipe_out[1].as_array()
print(images_out[0].shape)
show_images( pipe_out[0])


```

**Comment by jantonguirao** [comment]
Since you are using absolute crop coordinates and you are providing them as tensors, we recommend you use Slice operator instead. I adjusted your pipeline code here to use `Slice`:
```
import os
import glob
import types
import collections
import numpy as np
from random import shuffle
from nvidia.dali.pipeline import Pipeline
import nvidia.dali.ops as ops
import nvidia.dali.types as types
import nvidia.dali.fn as fn
import matplotlib.gridspec as gridspec
import matplotlib.pyplot as plt


batch_size = 2
epochs = 3
mode = 'train'
image_dir = '/home/bensu/Desktop/Share/im_folder/'
device_id = 0


def show_images(image_batch):
    columns = 2
    rows = (batch_size + 1) // (columns)
    fig = plt.figure(figsize = (32,(32 // columns) * rows))
    gs = gridspec.GridSpec(rows, columns)
    for j in range(rows*columns):
        plt.subplot(gs[j])
        plt.axis("off")
        plt.imshow(image_batch.at(j))

class ExternalInputIterator(object):
    def __init__(self,image_dir, mode, batch_size, device_id):
        self.mode = mode

        self.images_dir = image_dir
        self.batch_size = batch_size
        self.device_id = device_id

        with open(self.images_dir + "file_list.csv", 'r') as f:
            self.files = [line.rstrip() for line in f if line is not '']
        # whole data set size
        self.data_set_len = len(self.files)
        # based on the device_id and total number of GPUs - world size
        # get proper shard
        print('!!!!!!!!!!!!!!!!!!!!', self.files)
        self.files = self.files[self.data_set_len * device_id :
                                self.data_set_len * (device_id + 1)]
        self.n = len(self.files)

        '''if self.mode=='train':
            c = list(zip(self.image_path_list, self.label_path_list,self.imsize))
            random.shuffle(c)

            self.image_path_list, self.label_path_list,self.imsize = zip(*c)    '''

    def __iter__(self):
        self.i = 0
        shuffle(self.files)
        return self


    def __next__(self):
        batch = []
        labels = []
        crop_anchor = []
        crop_shape = []

        crop_y = 0
        crop_H = 52

        crop_x = 580
        crop_W = 52

        if self.i >= self.n:
            raise StopIteration

        for _ in range(self.batch_size):
            jpeg_filename, label = self.files[self.i].split(' ')
            f = open(self.images_dir + jpeg_filename, 'rb')
            batch.append(np.frombuffer(f.read(), dtype = np.uint8))
            labels.append(np.array([label], dtype = np.float32))
            crop_shape.append(np.array([52,52], dtype=np.float32))
            crop_anchor.append(np.array([crop_x, crop_y] , dtype = np.float32))
            self.i = (self.i + 1) % self.n
        return (batch, labels, crop_anchor, crop_shape)

    @property
    def size(self,):
        return self.data_set_len

    next = __next__


class SimplePipeline(Pipeline):
    def __init__(self,image_dir,batch_size,num_threads, device_id):
        super(SimplePipeline,self).__init__(batch_size,num_threads,device_id, seed=12)
        eii = ExternalInputIterator(image_dir,mode,batch_size,device_id)
        self.iterator = iter(eii)
        self.decode = ops.ImageDecoder(device = 'mixed', output_type=types.RGB)
        self.slice = ops.Slice(device = 'gpu', normalized_anchor = False, normalized_shape = False, axis_names = "WH", out_of_bounds_policy='pad')

    def define_graph(self):
        self.jpegs       = fn.external_source(device = 'cpu', name = "jpegs")
        self.labels      = fn.external_source(device = 'cpu', name = "labels")
        self.crop_anchor = fn.external_source(device = 'cpu', name = "crop_anchor")
        self.crop_shape  = fn.external_source(device = 'cpu', name = "crop_shape")
        images = self.decode(self.jpegs)
        output = self.slice(images, self.crop_anchor, self.crop_shape)
        return output, self.labels

    def iter_setup(self):
        (images, labels, crop_anchor, crop_shape) = self.iterator.next()
        self.feed_input("jpegs", images)
        self.feed_input("labels", labels)
        self.feed_input("crop_anchor", crop_anchor)
        self.feed_input("crop_shape", crop_shape)

pipe = SimplePipeline(image_dir, batch_size, 1, 0 )
pipe.build()
pipe_out = pipe.run()
images_out = pipe_out[0].as_cpu()
labels_out = pipe_out[1].as_array()
show_images(images_out)
```
