### ISSUE TITLE
Compute optical flow with 2 images instead of a sequence

### ISSUE THREAD

**Issue by castim** [NVIDIA/DALI#2111]
Hi,

I would like to compute the optical flow between two images that I have loaded and transformed in DALI. However, the OpticalFlow operator only takes a sequence as input. I cannot find an operator that allows to concatenate the two images into a sequence in DALI.

So is there a way two use optical flow with two separate images?
Is there a way to concatenate two images to form a sequence?

Thanks!

**Comment by JanuszL** [comment]
Hi,
It is currently not possible. The OpticalFlow operates only on Video sequences, however, it should be easy to create the operator that would create a sequence from to batches of images or rework OpticalFlow to accept two batches directly.
We will put this on our ToDo list and we would be more than happy to see an external contribution adding such functionality.

**Comment by mohankumarSriram** [comment]
Hi @JanuszL,
I would like to add the functionality to compute optical flow with two images. Please let me know if I should start by creating a new operator or rework OpticalFlow as stated above.

In general, I'm looking to start contributing to DALI and I found this issue to be interesting. I would love to receive pointers to other issues too which might be more beginner-friendly. (I'm comfortable with C++ and CUDA)

**Comment by JanuszL** [comment]
Hi,
Let me check with the team what could be a good task for the beginner.
Regarding this issue now it is possible to stack two batches together using [the `stack` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.stack) to create a sequence and feed the optical flow.
Let me close this issue as it is possible not and get back to you with the follow-up when I check with the team.

**Comment by JanuszL** [comment]
@mohankumarSriram what comes to my mind could be either https://github.com/NVIDIA/DALI/issues/2660 or https://github.com/NVIDIA/DALI/issues/2239#issuecomment-683687127.
The first one would require writing the EXIF parser and optionally apply a rotation of the images. The second is about adding additional color space conversion. It was started in https://github.com/NVIDIA/DALI/pull/2275 but never finished.
