### ISSUE TITLE
How to normalize input values of network between 0 and 1 when using CropMirrorNormalize?

### ISSUE THREAD

**Issue by KleinXin** [NVIDIA/DALI#2129]
I used image list with label to create the pipeline
How can I normalize the input values of network between 0 and 1？

**Comment by KleinXin** [comment]
thx!

**Comment by samra-irshad** [comment]
> Hi,
> Please use mean and std parameters accordingly to the equation provided in the [CropMirrorNormalize operator docs](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.ops.CropMirrorNormalize). So you need to remove the mean value of your data, dived by the range so you will get the values in range 0-1, and you need to set `output_dtype` to Float.
> For example, in the case of images, std should be equal to 255, mean 0.

Hi, I am trying to normalize the images within [0,1] range by giving zero mean and 255 std via ops.Normalize. But the output is somehow not right, the output is reduced size and all black. It only happens when I normalize my images as well as label images (ground-truths). Any tip?

**Comment by JanuszL** [comment]
Normalize can be an overkill for that, you can check this example [this example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/frameworks/tensorflow/tensorflow-dataset.html) and use just CropMirrorNormalize.
If you want to use normalize, you need to define an axis for the normalization, by default all are used. Please check [the operator description](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.ops.Normalize) for the details.
Another solution is just:
```
   output = self.decode(image)
   output = output / 255
```
