### ISSUE TITLE
Support operator as graph output

### ISSUE THREAD

**Issue by crucifyml** [NVIDIA/DALI#213]
Any plan to allow setting support ops as output in graph definition?

**Comment by crucifyml** [comment]
This feature can be easily implemented by adding a bridge operator which copy its argument to its output. However, I don't know how to define an argument with arbitrary type. You need to define an argument for every DALI_TYPE. This way lacks flexibility.

However, there should be more elegant way to do so.

**Comment by JanuszL** [comment]
Hi,
This is very good idea. We have ToDo for that and will try to support in the near future.
Br,
Janusz

**Comment by JanuszL** [comment]
This should be achieved in https://github.com/NVIDIA/DALI/pull/1423/.

**Comment by szalpal** [comment]
Merged!
