### ISSUE TITLE
Displacement filter add output height/width as optional arguments

### ISSUE THREAD

**Issue by T2hhbmEK** [NVIDIA/DALI#214]
Manually set output height/width for displacement operator to save computation.

**Comment by crucifyml** [comment]
When we perform crop after displacement, the cropped pixels should not be computed. We can absorb the crop operation into displacement to save computation. In other words, we do not need to compute the pixels outside crop box. It will save much time, if output size is much smaller than input size.

In fact, we can combine Rotation, Translation, Resize, Flip, ... , and Crop into WarpAffine with well defined affine matrix and Crop.

With https://github.com/NVIDIA/DALI/issues/215, we can implement many augmentations with WarpAffine and Crop with external pre-calculated affine matrix.

**Comment by JanuszL** [comment]
Hi,
This sounds like a fused operator. For some use cases you are right, corp operator comes after the displacement. But DALI is not meant to be focused only on one kind of workflow. Now we want to focus on completes and supporting as many use cases as possible. In the long term we would try to optimize more common usage patterns.
In the mean time we are open to any contribution, so if you have some spare time feel free to hack DALI and create PR with your changes.
Br,
Janusz

**Comment by JanuszL** [comment]
Internally tracked DALI-286.
