### ISSUE TITLE
Support for bbox and coord rotate

### ISSUE THREAD

**Issue by alphinside** [NVIDIA/DALI#2142]
It will be nice if we have these operators considering that bbflip and coordflip have already been supported

**Comment by JanuszL** [comment]
Hi,
We will add it to our ToDo list, still, we would be more than happy to welcome and review a PR that would add this feature.

A few things that need to be considered for sure:
- what if the vertices go beyond the canvas after rotation - should it be extended (we have such option in image rotation) or replaced by smaller box, or the box should be removed
- what if only on vertices goes beyond the canvas?
- the same applies to coord - should additional coord be created at the border of the image?

**Comment by JanuszL** [comment]
Hi,

You can check [this example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/math/geometric_transforms.html) to see what operations DALI provides for coordinates.
