### ISSUE TITLE
how to appy colortwist on each image

### ISSUE THREAD

**Issue by centorchen** [NVIDIA/DALI#2167]
when I use dali in pytorch , I'm confuse how to colortwist each image in a batch
here is some of my code:
```
class TrainPipeline(Pipeline): 
        def __init__(self, batch_size, num_threads, device_id, seed=317):
                super(TrainPipeline, self).__init__(batch_size=batch_size, num_threads=num_threads, device_id=device_id)
                ...
                self.twist = ops.ColorTwist(device="gpu")
                self.rng_saturation = ops.Uniform(range=[0.6, 1.4])
                self.rng_contrast = ops.Uniform(range=[0.6, 1.4])
                self.rng_brightness = ops.Uniform(range=[0.6, 1.4])
                self.rng_hue = ops.Uniform(range=[-0.4, 0.4])

        def define_graph(self):
                ...
                saturation = self.rng_saturation()
                contrast = self.rng_contrast()
                brightness = self.rng_brightness()
                hue = self.rng_hue()
                batch_images = self.twist(batch_images, saturation=saturation, contrast=contrast, brightness=brightness,
                                  hue=hue)
                return batch_images
```
in my observations, I thought it work on the whole batch images using one group of staturation,  contrast, brightness and hue. but I want twist on each image, and I don't want increase any more exteralInput.
Is there any suggestion?

**Comment by JanuszL** [comment]
Hi,
It works as you expect. DALI will create a batch of random saturation, contrast, hue, and brightness values, different for each sample then apply it inside ColorTwist operator.
You can return the saturation, contrast, brightness, and hue and examine them.

**Comment by centorchen** [comment]
Yep，I can return and examine them. I neglect that. 
Thanks a lot
