### ISSUE TITLE
dtype argument unsupported error when running against DALI in NGC 20.06-tf2-py3 container

### ISSUE THREAD

**Issue by joehandzik** [NVIDIA/DALI#2168]
Trace below:

GPUs: 8, batch: 180, workers: 3, prefetch depth: 2, loging interval: 10, fp16: False, NHWC: False, READ_SHUFFLE: False, DISABLE_MMAP: True, small dataset: False,
Using nvJPEG
WARNING: DALI_EXTRA_PATH not initialized.
Traceback (most recent call last):
  File "/dali/dali/test/python/test_RN50_data_pipeline.py", line 339, in <module>
    reader_queue_depth=READER_QUEUE_DEPTH) for n in range(N)]
  File "/dali/dali/test/python/test_RN50_data_pipeline.py", line 339, in <listcomp>
    reader_queue_depth=READER_QUEUE_DEPTH) for n in range(N)]
  File "/dali/dali/test/python/test_RN50_data_pipeline.py", line 144, in __init__
    super(TFRecordPipeline, self).__init__(**kwargs)
  File "/dali/dali/test/python/test_RN50_data_pipeline.py", line 64, in __init__
    std=[0.229 * 255,0.224 * 255,0.225 * 255])
  File "/usr/local/lib/python3.6/dist-packages/nvidia/dali/ops.py", line 413, in __init__
    dtype = self._schema.GetArgumentType(key)
RuntimeError: [/opt/dali/dali/pipeline/operator/op_schema.cc:127] Assert on "HasArgument(name)" failed: Argument "dtype" is not supported by operator "CropMirrorNormalize".
Stacktrace (40 entries):
[frame 0]: /usr/local/lib/python3.6/dist-packages/nvidia/dali/libdali.so(+0xbb2ce) [0x7f0f780332ce]
[frame 1]: /usr/local/lib/python3.6/dist-packages/nvidia/dali/libdali.so(dali::OpSchema::GetArgumentType(std::string const&) const+0x353) [0x7f0f780e7ce3]
[frame 2]: /usr/local/lib/python3.6/dist-packages/nvidia/dali/backend_impl.cpython-36m-x86_64-linux-gnu.so(+0x6ff84) [0x7f0f9d9e7f84]
[frame 3]: /usr/local/lib/python3.6/dist-packages/nvidia/dali/backend_impl.cpython-36m-x86_64-linux-gnu.so(+0x5a073) [0x7f0f9d9d2073]
[frame 4]: python3(_PyCFunction_FastCallDict+0x35c) [0x5669ac]
[frame 5]: python3() [0x50a5c3]
[frame 6]: python3(_PyEval_EvalFrameDefault+0x444) [0x50bfb4]
[frame 7]: python3() [0x507d64]
[frame 8]: python3(_PyFunction_FastCallDict+0x2e2) [0x509042]
[frame 9]: python3() [0x594931]
[frame 10]: python3() [0x549e5f]
[frame 11]: python3() [0x5513d1]
[frame 12]: python3(_PyObject_FastCallKeywords+0x19c) [0x5a9cbc]
[frame 13]: python3() [0x50a5c3]
[frame 14]: python3(_PyEval_EvalFrameDefault+0x1226) [0x50cd96]
[frame 15]: python3() [0x507d64]
[frame 16]: python3(_PyFunction_FastCallDict+0x2e2) [0x509042]
[frame 17]: python3() [0x594931]
[frame 18]: python3(PyObject_Call+0x3e) [0x59fc4e]
[frame 19]: python3(_PyEval_EvalFrameDefault+0x17e6) [0x50d356]
[frame 20]: python3() [0x507d64]
[frame 21]: python3(_PyFunction_FastCallDict+0x2e2) [0x509042]
[frame 22]: python3() [0x594931]
[frame 23]: python3() [0x549e5f]
[frame 24]: python3() [0x5513d1]
[frame 25]: python3(_PyObject_FastCallKeywords+0x19c) [0x5a9cbc]
[frame 26]: python3() [0x50a5c3]
[frame 27]: python3(_PyEval_EvalFrameDefault+0x1226) [0x50cd96]
[frame 28]: python3() [0x509758]
[frame 29]: python3() [0x50a48d]
[frame 30]: python3(_PyEval_EvalFrameDefault+0x444) [0x50bfb4]
[frame 31]: python3() [0x507d64]
[frame 32]: python3(PyEval_EvalCode+0x23) [0x50ae13]
[frame 33]: python3() [0x634c82]
[frame 34]: python3(PyRun_FileExFlags+0x97) [0x634d37]
[frame 35]: python3(PyRun_SimpleFileExFlags+0x17f) [0x6384ef]
[frame 36]: python3(Py_Main+0x591) [0x639091]
[frame 37]: python3(main+0xe0) [0x4b0d00]
[frame 38]: /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f0f9ee3eb97]
[frame 39]: python3(_start+0x2a) [0x5b250a]

It's because of this line (because when I manually change back to the older variable name, everything works fine):

https://github.com/NVIDIA/DALI/blame/master/dali/test/python/test_RN50_data_pipeline.py#L60

It's highly desirable from my end to not need to maintain a fork that makes sure this test works with slightly older versions of DALI, but let me know if that's just my reality. Not sure what the best way would be to allow this line to support both versions of the variable.

**Comment by JanuszL** [comment]
Hi,
It is hard to stick to backward compatibility in case of tests and examples where we want to show the user how to use the newest features and discourage from using deprecated one.
If you have any good idea how we may approach this let us know.

**Comment by joehandzik** [comment]
I would say that, for this particular sort of change, it's nice to support both arguments and give a release or two before completely removing the value. But I an also accept that for this sort of test that is tied into the codebase, that flexibility isn't critical. I'll think about it and see if I can come up with anything that would work without changing core DALI source, but I think the longer-term solution for a customer would be to support both values and dump out a warning when using the one being deprecated.

**Comment by JanuszL** [comment]
And that is what we do, we support both but in the example, we use the newer one. You can still run the older code with the newer DALI version.

**Comment by joehandzik** [comment]
Ah I see, so the version I'm on just flat-out doesn't support the argument yet. I'll close this.
