### ISSUE TITLE
error in make command for DALI

### ISSUE THREAD

**Issue by nirajkale** [NVIDIA/DALI#2173]
I'm trying to build DALI from source for aarch64 system.
while I have installed all the required dependency before the make,
I'm still running into below error in make command:

![image](https://user-images.githubusercontent.com/40765055/89127120-c6cd0100-d508-11ea-9d67-7a94a70d3e2b.png)

Is there anything wrong that I'm doing ?
Will appreciate any help.

**Comment by JanuszL** [comment]
Hi,
Can you provide the exact steps that lead you to this error? Are you building using docker or bare metal? Is it for SBSA or Xavier? What is your cmake invocation command?
