### ISSUE TITLE
Error installing nvidia-dali-tf-plugin-cuda100

### ISSUE THREAD

**Issue by pengtu** [NVIDIA/DALI#2179]
Getting the following gcc compiler errors when invoking: pip install --extra-index-url https://developer.download.nvidia.com/compute/redist nvidia-dali-tf-plugin-cuda100

 ---> Running in 12119fe89de0
Looking in indexes: https://pypi.org/simple, https://developer.download.nvidia.com/compute/redist
Collecting nvidia-dali-tf-plugin-cuda100
  Downloading https://developer.download.nvidia.com/compute/redist/nvidia-dali-tf-plugin-cuda100/nvidia-dali-tf-plugin-cuda100-0.24.0.tar.gz (374 kB)
Requirement already satisfied: nvidia-dali-cuda100==0.24.0 in /usr/local/lib/python3.6/dist-packages (from nvidia-dali-tf-plugin-cuda100) (0.24.0)
Requirement already satisfied: future in /usr/local/lib/python3.6/dist-packages (from nvidia-dali-cuda100==0.24.0->nvidia-dali-tf-plugin-cuda100) (0.18.2)
Building wheels for collected packages: nvidia-dali-tf-plugin-cuda100
  Building wheel for nvidia-dali-tf-plugin-cuda100 (setup.py): started
  Building wheel for nvidia-dali-tf-plugin-cuda100 (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-urbmh8hn/nvidia-dali-tf-plugin-cuda100/setup.py'"'"'; __file__='"'"'/tmp/pip-install-urbmh8hn/nvidia-dali-tf-plugin-cuda100/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-k6c8yym2
       cwd: /tmp/pip-install-urbmh8hn/nvidia-dali-tf-plugin-cuda100/
  Complete output (103 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/nvidia
  creating build/lib.linux-x86_64-3.6/nvidia/dali_tf_plugin
  copying nvidia/dali_tf_plugin/dali_tf_plugin.py -> build/lib.linux-x86_64-3.6/nvidia/dali_tf_plugin
  copying nvidia/dali_tf_plugin/__init__.py -> build/lib.linux-x86_64-3.6/nvidia/dali_tf_plugin
  running egg_info
  writing nvidia_dali_tf_plugin_cuda100.egg-info/PKG-INFO
  writing dependency_links to nvidia_dali_tf_plugin_cuda100.egg-info/dependency_links.txt
  writing requirements to nvidia_dali_tf_plugin_cuda100.egg-info/requires.txt
  writing top-level names to nvidia_dali_tf_plugin_cuda100.egg-info/top_level.txt
  reading manifest file 'nvidia_dali_tf_plugin_cuda100.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'nvidia_dali_tf_plugin_cuda100.egg-info/SOURCES.txt'
  running build_ext
  Checking build environment for DALI TF plugin ...
  
   Environment:
   ---------------------------------------------------------------------------------------------------------
   Platform system:                      Linux
   Platform machine:                     x86_64
   DALI lib path:                        /usr/local/lib/python3.6/dist-packages/nvidia/dali
   TF path:                              /usr/local/lib/python3.6/dist-packages/tensorflow
   DALI TF plugin destination directory: build/lib.linux-x86_64-3.6/nvidia/dali_tf_plugin
   Is Conda environment?                 No
   Using compiler:                       "g++", version 7.5
   TF version installed:                 2.3
   g++ version used to compile TF:       7.3
   Prebuilt plugins available for g++:   "5.4 4.8"
   Is g++-7.3 present in the system?     No
   Can install prebuilt plugin?          No
   Can compile with default compiler?    Yes
   Can compile with alt compiler?        No
  ---------------------------------------------------------------------------------------------------------
  Proceed with build...
  2020-08-04 18:34:30.330981: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
  Build command:
  
   g++ -Wl,-R,'$ORIGIN/..' -std=c++11 -DNDEBUG -shared  /tmp/pip-install-urbmh8hn/nvidia-dali-tf-plugin-cuda100/daliop.cc /tmp/pip-install-urbmh8hn/nvidia-dali-tf-plugin-cuda100/dali_dataset_op.cc -o build/lib.linux-x86_64-3.6/nvidia/dali_tf_plugin/libdali_tf_current.so -fPIC -I/usr/local/lib/python3.6/dist-packages/nvidia/dali/include -I/usr/local/lib/python3.6/dist-packages/tensorflow/include -D_GLIBCXX_USE_CXX11_ABI=0 -I/usr/local/cuda/include -L/usr/local/lib/python3.6/dist-packages/nvidia/dali -ldali -L/usr/local/lib/python3.6/dist-packages/tensorflow -l:libtensorflow_framework.so.2  -O2
  
  
  /tmp/pip-install-urbmh8hn/nvidia-dali-tf-plugin-cuda100/dali_dataset_op.cc: In member function ‘virtual void dali_tf_impl::DALIDatasetOp::MakeDataset(tensorflow::OpKernelContext*, tensorflow::data::DatasetBase**)’:
  /tmp/pip-install-urbmh8hn/nvidia-dali-tf-plugin-cuda100/dali_dataset_op.cc:74:85: error: invalid new-expression of abstract class type ‘dali_tf_impl::DALIDatasetOp::Dataset’
         *output = new Dataset(context, pipeline_def_, shapes_, dtypes_, is_gpu_device_);
                                                                                       ^
  /tmp/pip-install-urbmh8hn/nvidia-dali-tf-plugin-cuda100/dali_dataset_op.cc:117:9: note:   because the following virtual functions are pure within ‘dali_tf_impl::DALIDatasetOp::Dataset’:
     class Dataset : public DatasetBase {
           ^~~~~~~
  In file included from /tmp/pip-install-urbmh8hn/nvidia-dali-tf-plugin-cuda100/dali_dataset_op.cc:29:0:
  /usr/local/lib/python3.6/dist-packages/tensorflow/include/tensorflow/core/framework/dataset.h:818:18: note: 	virtual tensorflow::Status tensorflow::data::DatasetBase::CheckExternalState() const
     virtual Status CheckExternalState() const = 0;
                    ^~~~~~~~~~~~~~~~~~
  In file included from /usr/local/lib/python3.6/dist-packages/tensorflow/include/tensorflow/core/framework/dataset.h:22:0,
                   from /tmp/pip-install-urbmh8hn/nvidia-dali-tf-plugin-cuda100/dali_dataset_op.cc:29:
  /usr/local/lib/python3.6/dist-packages/tensorflow/include/absl/memory/memory.h: In instantiation of ‘typename absl::lts_2020_02_25::memory_internal::MakeUniqueResult<T>::scalar absl::lts_2020_02_25::make_unique(Args&& ...) [with T = dali_tf_impl::DALIDatasetOp::Dataset::Iterator; Args = {tensorflow::data::DatasetIterator<dali_tf_impl::DALIDatasetOp::Dataset>::Params, daliPipelineHandle&, const bool&}; typename absl::lts_2020_02_25::memory_internal::MakeUniqueResult<T>::scalar = std::unique_ptr<dali_tf_impl::DALIDatasetOp::Dataset::Iterator, std::default_delete<dali_tf_impl::DALIDatasetOp::Dataset::Iterator> >]’:
  /tmp/pip-install-urbmh8hn/nvidia-dali-tf-plugin-cuda100/dali_dataset_op.cc:140:92:   required from here
  /usr/local/lib/python3.6/dist-packages/tensorflow/include/absl/memory/memory.h:170:29: error: invalid new-expression of abstract class type ‘dali_tf_impl::DALIDatasetOp::Dataset::Iterator’
     return std::unique_ptr<T>(new T(std::forward<Args>(args)...));
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /tmp/pip-install-urbmh8hn/nvidia-dali-tf-plugin-cuda100/dali_dataset_op.cc:230:11: note:   because the following virtual functions are pure within ‘dali_tf_impl::DALIDatasetOp::Dataset::Iterator’:
       class Iterator : public DatasetIterator<Dataset> {
             ^~~~~~~~
  In file included from /tmp/pip-install-urbmh8hn/nvidia-dali-tf-plugin-cuda100/dali_dataset_op.cc:29:0:
  /usr/local/lib/python3.6/dist-packages/tensorflow/include/tensorflow/core/framework/dataset.h:649:18: note: 	virtual tensorflow::Status tensorflow::data::IteratorBase::SaveInternal(tensorflow::data::SerializationContext*, tensorflow::data::IteratorStateWriter*)
     virtual Status SaveInternal(SerializationContext* ctx,
                    ^~~~~~~~~~~~
  /usr/local/lib/python3.6/dist-packages/tensorflow/include/tensorflow/core/framework/dataset.h:660:18: note: 	virtual tensorflow::Status tensorflow::data::IteratorBase::RestoreInternal(tensorflow::data::IteratorContext*, tensorflow::data::IteratorStateReader*)
     virtual Status RestoreInternal(IteratorContext* ctx,
                    ^~~~~~~~~~~~~~~
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-urbmh8hn/nvidia-dali-tf-plugin-cuda100/setup.py", line 53, in <module>
      distclass=CustomDistribution
    File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 165, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 204, in run
      self.run_command('build')
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-urbmh8hn/nvidia-dali-tf-plugin-cuda100/setup.py", line 25, in run
      helper.install()
    File "/tmp/pip-install-urbmh8hn/nvidia-dali-tf-plugin-cuda100/dali_tf_plugin_install_tool.py", line 178, in install
      subprocess.check_call(cmd, cwd=self.src_path, shell=True)
    File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command 'g++ -Wl,-R,'$ORIGIN/..' -std=c++11 -DNDEBUG -shared  /tmp/pip-install-urbmh8hn/nvidia-dali-tf-plugin-cuda100/daliop.cc /tmp/pip-install-urbmh8hn/nvidia-dali-tf-plugin-cuda100/dali_dataset_op.cc -o build/lib.linux-x86_64-3.6/nvidia/dali_tf_plugin/libdali_tf_current.so -fPIC -I/usr/local/lib/python3.6/dist-packages/nvidia/dali/include -I/usr/local/lib/python3.6/dist-packages/tensorflow/include -D_GLIBCXX_USE_CXX11_ABI=0 -I/usr/local/cuda/include -L/usr/local/lib/python3.6/dist-packages/nvidia/dali -ldali -L/usr/local/lib/python3.6/dist-packages/tensorflow -l:libtensorflow_framework.so.2  -O2' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for nvidia-dali-tf-plugin-cuda100
  Running setup.py clean for nvidia-dali-tf-plugin-cuda100
Failed to build nvidia-dali-tf-plugin-cuda100
Installing collected packages: nvidia-dali-tf-plugin-cuda100
    Running setup.py install for nvidia-dali-tf-plugin-cuda100: started
    Running setup.py install for nvidia-dali-tf-plugin-cuda100: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-urbmh8hn/nvidia-dali-tf-plugin-cuda100/setup.py'"'"'; __file__='"'"'/tmp/pip-install-urbmh8hn/nvidia-dali-tf-plugin-cuda100/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-3_mp3yt2/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6/nvidia-dali-tf-plugin-cuda100
         cwd: /tmp/pip-install-urbmh8hn/nvidia-dali-tf-plugin-cuda100/
    Complete output (105 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/nvidia
    creating build/lib.linux-x86_64-3.6/nvidia/dali_tf_plugin
    copying nvidia/dali_tf_plugin/dali_tf_plugin.py -> build/lib.linux-x86_64-3.6/nvidia/dali_tf_plugin
    copying nvidia/dali_tf_plugin/__init__.py -> build/lib.linux-x86_64-3.6/nvidia/dali_tf_plugin
    running egg_info
    writing nvidia_dali_tf_plugin_cuda100.egg-info/PKG-INFO
    writing dependency_links to nvidia_dali_tf_plugin_cuda100.egg-info/dependency_links.txt
    writing requirements to nvidia_dali_tf_plugin_cuda100.egg-info/requires.txt
    writing top-level names to nvidia_dali_tf_plugin_cuda100.egg-info/top_level.txt
    reading manifest file 'nvidia_dali_tf_plugin_cuda100.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'nvidia_dali_tf_plugin_cuda100.egg-info/SOURCES.txt'
    running build_ext
    Checking build environment for DALI TF plugin ...
    
     Environment:
     ---------------------------------------------------------------------------------------------------------
     Platform system:                      Linux
     Platform machine:                     x86_64
     DALI lib path:                        /usr/local/lib/python3.6/dist-packages/nvidia/dali
     TF path:                              /usr/local/lib/python3.6/dist-packages/tensorflow
     DALI TF plugin destination directory: build/lib.linux-x86_64-3.6/nvidia/dali_tf_plugin
     Is Conda environment?                 No
     Using compiler:                       "g++", version 7.5
     TF version installed:                 2.3
     g++ version used to compile TF:       7.3
     Prebuilt plugins available for g++:   "5.4 4.8"
     Is g++-7.3 present in the system?     No
     Can install prebuilt plugin?          No
     Can compile with default compiler?    Yes
     Can compile with alt compiler?        No
    ---------------------------------------------------------------------------------------------------------
    Proceed with build...
    2020-08-04 18:34:38.899814: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
    Build command:
    
     g++ -Wl,-R,'$ORIGIN/..' -std=c++11 -DNDEBUG -shared  /tmp/pip-install-urbmh8hn/nvidia-dali-tf-plugin-cuda100/daliop.cc /tmp/pip-install-urbmh8hn/nvidia-dali-tf-plugin-cuda100/dali_dataset_op.cc -o build/lib.linux-x86_64-3.6/nvidia/dali_tf_plugin/libdali_tf_current.so -fPIC -I/usr/local/lib/python3.6/dist-packages/nvidia/dali/include -I/usr/local/lib/python3.6/dist-packages/tensorflow/include -D_GLIBCXX_USE_CXX11_ABI=0 -I/usr/local/cuda/include -L/usr/local/lib/python3.6/dist-packages/nvidia/dali -ldali -L/usr/local/lib/python3.6/dist-packages/tensorflow -l:libtensorflow_framework.so.2  -O2
    
    
    /tmp/pip-install-urbmh8hn/nvidia-dali-tf-plugin-cuda100/dali_dataset_op.cc: In member function ‘virtual void dali_tf_impl::DALIDatasetOp::MakeDataset(tensorflow::OpKernelContext*, tensorflow::data::DatasetBase**)’:
    /tmp/pip-install-urbmh8hn/nvidia-dali-tf-plugin-cuda100/dali_dataset_op.cc:74:85: error: invalid new-expression of abstract class type ‘dali_tf_impl::DALIDatasetOp::Dataset’
           *output = new Dataset(context, pipeline_def_, shapes_, dtypes_, is_gpu_device_);
                                                                                         ^
    /tmp/pip-install-urbmh8hn/nvidia-dali-tf-plugin-cuda100/dali_dataset_op.cc:117:9: note:   because the following virtual functions are pure within ‘dali_tf_impl::DALIDatasetOp::Dataset’:
       class Dataset : public DatasetBase {
             ^~~~~~~
    In file included from /tmp/pip-install-urbmh8hn/nvidia-dali-tf-plugin-cuda100/dali_dataset_op.cc:29:0:
    /usr/local/lib/python3.6/dist-packages/tensorflow/include/tensorflow/core/framework/dataset.h:818:18: note: 	virtual tensorflow::Status tensorflow::data::DatasetBase::CheckExternalState() const
       virtual Status CheckExternalState() const = 0;
                      ^~~~~~~~~~~~~~~~~~
    In file included from /usr/local/lib/python3.6/dist-packages/tensorflow/include/tensorflow/core/framework/dataset.h:22:0,
                     from /tmp/pip-install-urbmh8hn/nvidia-dali-tf-plugin-cuda100/dali_dataset_op.cc:29:
    /usr/local/lib/python3.6/dist-packages/tensorflow/include/absl/memory/memory.h: In instantiation of ‘typename absl::lts_2020_02_25::memory_internal::MakeUniqueResult<T>::scalar absl::lts_2020_02_25::make_unique(Args&& ...) [with T = dali_tf_impl::DALIDatasetOp::Dataset::Iterator; Args = {tensorflow::data::DatasetIterator<dali_tf_impl::DALIDatasetOp::Dataset>::Params, daliPipelineHandle&, const bool&}; typename absl::lts_2020_02_25::memory_internal::MakeUniqueResult<T>::scalar = std::unique_ptr<dali_tf_impl::DALIDatasetOp::Dataset::Iterator, std::default_delete<dali_tf_impl::DALIDatasetOp::Dataset::Iterator> >]’:
    /tmp/pip-install-urbmh8hn/nvidia-dali-tf-plugin-cuda100/dali_dataset_op.cc:140:92:   required from here
    /usr/local/lib/python3.6/dist-packages/tensorflow/include/absl/memory/memory.h:170:29: error: invalid new-expression of abstract class type ‘dali_tf_impl::DALIDatasetOp::Dataset::Iterator’
       return std::unique_ptr<T>(new T(std::forward<Args>(args)...));
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /tmp/pip-install-urbmh8hn/nvidia-dali-tf-plugin-cuda100/dali_dataset_op.cc:230:11: note:   because the following virtual functions are pure within ‘dali_tf_impl::DALIDatasetOp::Dataset::Iterator’:
         class Iterator : public DatasetIterator<Dataset> {
               ^~~~~~~~
    In file included from /tmp/pip-install-urbmh8hn/nvidia-dali-tf-plugin-cuda100/dali_dataset_op.cc:29:0:
    /usr/local/lib/python3.6/dist-packages/tensorflow/include/tensorflow/core/framework/dataset.h:649:18: note: 	virtual tensorflow::Status tensorflow::data::IteratorBase::SaveInternal(tensorflow::data::SerializationContext*, tensorflow::data::IteratorStateWriter*)
       virtual Status SaveInternal(SerializationContext* ctx,
                      ^~~~~~~~~~~~
    /usr/local/lib/python3.6/dist-packages/tensorflow/include/tensorflow/core/framework/dataset.h:660:18: note: 	virtual tensorflow::Status tensorflow::data::IteratorBase::RestoreInternal(tensorflow::data::IteratorContext*, tensorflow::data::IteratorStateReader*)
       virtual Status RestoreInternal(IteratorContext* ctx,
                      ^~~~~~~~~~~~~~~
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-urbmh8hn/nvidia-dali-tf-plugin-cuda100/setup.py", line 53, in <module>
        distclass=CustomDistribution
      File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 165, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.6/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-urbmh8hn/nvidia-dali-tf-plugin-cuda100/setup.py", line 25, in run
        helper.install()
      File "/tmp/pip-install-urbmh8hn/nvidia-dali-tf-plugin-cuda100/dali_tf_plugin_install_tool.py", line 178, in install
        subprocess.check_call(cmd, cwd=self.src_path, shell=True)
      File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command 'g++ -Wl,-R,'$ORIGIN/..' -std=c++11 -DNDEBUG -shared  /tmp/pip-install-urbmh8hn/nvidia-dali-tf-plugin-cuda100/daliop.cc /tmp/pip-install-urbmh8hn/nvidia-dali-tf-plugin-cuda100/dali_dataset_op.cc -o build/lib.linux-x86_64-3.6/nvidia/dali_tf_plugin/libdali_tf_current.so -fPIC -I/usr/local/lib/python3.6/dist-packages/nvidia/dali/include -I/usr/local/lib/python3.6/dist-packages/tensorflow/include -D_GLIBCXX_USE_CXX11_ABI=0 -I/usr/local/cuda/include -L/usr/local/lib/python3.6/dist-packages/nvidia/dali -ldali -L/usr/local/lib/python3.6/dist-packages/tensorflow -l:libtensorflow_framework.so.2  -O2' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-urbmh8hn/nvidia-dali-tf-plugin-cuda100/setup.py'"'"'; __file__='"'"'/tmp/pip-install-urbmh8hn/nvidia-dali-tf-plugin-cuda100/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-3_mp3yt2/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6/nvidia-dali-tf-plugin-cuda100 Check the logs for full command output.

**Comment by JanuszL** [comment]
Hi,
I guess you have TensorFlow 2.3 installed. DALI 0.24 doesn't support it yet. It was just recently added in https://github.com/NVIDIA/DALI/pull/2160. You can try out our [nightly build](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/installation.html#nightly-builds) or wait for 0.25 release.

**Comment by JanuszL** [comment]
0.25 was released. The issue should be fixed.
