### ISSUE TITLE
fail to install 

### ISSUE THREAD

**Issue by hyqyoung** [NVIDIA/DALI#2182]
>>>pip install --extra-index-url https://developer.download.nvidia.com/compute/redist/nightly nvidia-dali-nightly-cuda110

Looking in indexes: https://pypi.org/simple, https://developer.download.nvidia.com/compute/redist/nightly
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f336ef99b70>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/nvidia-dali-nightly-cuda110/

**Comment by JanuszL** [comment]
Hi,
Can you check if the direct download from https://developer.download.nvidia.com/compute/redist/nightly/nvidia-dali-nightly-cuda110/nvidia_dali_nightly_cuda110-0.25.0.dev20200804-1518409-py3-none-manylinux2014_x86_64.whl works?

**Comment by hyqyoung** [comment]
thansk, and it works

**Comment by hyqyoung** [comment]
thansk, and it works

**Comment by JanuszL** [comment]
Maybe it is a pip issue. No ida.
