### ISSUE TITLE
[Question] How to make the reading in ops.ExternalSource parallel?

### ISSUE THREAD

**Issue by cfzd** [NVIDIA/DALI#2183]
Hi, thanks for your great work!

I'm currently using `ops.ExternalSource` as my data source in DALI, which could significantly improve the reading speed compared with PyTorch vanilla DataLoader. 

But I meet a problem. `ops.ExternalSource` requires providing batched data. Generally, reading a batch in `ops.ExternalSource` is sequential and looks like this:
```
class ExternalSourceIterator:
    ...init code...
    def __next__(self):
        images = []
        for _ in range(self.batch_size):
            images.append(np.frombuffer(some_bytes, dtype=np.uint8))
        return images

class MyPipeline(Pipeline):
    def __init__(...):
        ...init code...
        self.data_iterator = iter(ExternalSourceIterator())
        self.input = ops.ExternalSource()
    def define_graph(self):
        self.jpegs = self.input()
    def iter_setup(self):
        images = self.data_iterator.next()
        self.feed_input(self.jpegs, images)
```
The above Pipeline is still relatively slow since it doesn't make full use of my GPU.

Is there any recommended way to make the reading in `ops.ExternalSource` parallel?

**Comment by JanuszL** [comment]
Hi,

> Is there any recommended way to make the reading in ops.ExternalSource parallel?

It is not possible with the way how Python multithreading work (that each thread needs to take GIL that block any true parallel code execution). Other frameworks, like PyTorch, resolves this by spawning multiple processes and communication via shared memory. We think about transplanting such a solution to DALI but this is rather a significant rework to how ExternalSource operates.
We still would be more than happy to see an external contribution adding such functionality to DALI.

**Comment by cfzd** [comment]
My understanding is that you want to make `ops.ExternalSource` a finer level operator for each sample, and wrap it with multiprocessing somewhere outside to support parallel reading of batched data. Am I correct?

I also tried another way that directly using multiprocessing inside `ops.ExternalSource` , `__next__` method. It looks like this:
```
def _read_bytes_numpy(path):
    with open(path, 'rb') as f:
        res = np.frombuffer(f.read(), dtype=np.uint8)
    return res

class ExternalSourceIterator:
    def __init__(...)
        ...
        self.works = multiprocessing.Pool(self.num_workers)

    def __next__(self):
        image_paths = []
        for _ in range(self.batch_size):
            image_paths.append(somepath)
        #collect paths for multiprocessing reading

        images = self.works.map(_read_bytes_numpy, image_paths )

        return images
```

But the speed is even slower than sequential reading, and I don't know why.

**Comment by cfzd** [comment]
@JanuszL 

Sorry, I found the problem why I can't make full use of my GPU.  It is just a problem of `num_threads` in `nvidia.dali.pipeline.Pipeline`.  The `num_threads` should be large enough to get a high reading speed. I thought all my operators are executed on GPU or in 'mixed' mode, so the `num_threads = 4` is fair enough. But I got doubled speed when I set `num_threads = 8` although all the operators are executed on GPU or in 'mixed' mode.

Also, I carefully checked the sequential reading time in `ops.ExternalSource`.  Although it is sequential, reading bytes without decoding them from disk is not that slow as I thought.  With Intel(R) Xeon(R) E5 CPU and SSD, reading eight images with a resolution of `1600x600` only takes 1.2-1.6 ms. 

So I don't think there is a need for parallelizing the `ops.ExternalSource`. Sorry for my misunderstanding. Hope this wouldn't bring you extra work.

**Comment by JanuszL** [comment]
Hi,
Glad that you managed to solve your problem. Personally, I haven't used `multiprocessing` python module and I don't know if that would solve all our problems.

> The num_threads should be large enough to get a high reading speed. I thought all my operators are executed on GPU or in 'mixed' mode, so the num_threads = 4 is fair enough. But I got doubled speed when I set num_threads = 8 although all the operators are executed on GPU or in 'mixed' mode.

Can you share your pipeline? ImageDecoder utilizes CPU a lot even in the mixed mode. You can offload more of the decoding to the GPU lowering the `hybrid_huffman_threshold` value.
