### ISSUE TITLE
Can import mxnet affect performance of DALI on torch?

### ISSUE THREAD

**Issue by bhheo** [NVIDIA/DALI#2185]
Hi

I'm using DALI on ImageNet model
Recently, I found a weird case and would like to ask for comments on it.

My code is based on PyTorch.
And my docker includes CUDA 10.0, MxNet 1.5.1, PyTorch 1.4 and DALI 0.23.0

When I run only the DALI dataloader except for the other parts, the data loading speed is 4500 images/sec.
However, if I write `import mxnet` at the beginning of the code, the data loading speed increases to 9000 images/sec.
The batch-size is 1024, and the speed is the average value of one epoch.

My code is not using mxnet at all, but `import mxnet` affects the speed of DALI.
I would like to ask for advice on how this could happen, and if there is a way to improve speed without `import mxnet`.

**Comment by JanuszL** [comment]
HI,
This is not expected. Can you provide a minimal and self contained reproduction script?

**Comment by bhheo** [comment]
I have solved this issue while writing codes for reproduce.

The problem is one hot vector converting based on PyTorch.
So, I changed it to `dali.ops.OneHot`

I still don't know how `import mxnet` increase the speed of converting
But, I think it is not related with dali
