### ISSUE TITLE
[Question] Is it possible to return metadata?

### ISSUE THREAD

**Issue by JuanFMontesinos** [NVIDIA/DALI#2195]
I was wondering if it's possible to return metadata using DALI.
In concret I'd like to return a python dictionary.

**Comment by JanuszL** [comment]
Hi,
It is not possible to do that directly in DALI.
When you are talking about ExternalSource, you can use Python [queue](https://docs.python.org/3/library/queue.html), put data there and get without DALI knowing you are doing that. Place `put` inside the ExternalSource, and `get` next to DALI iterator.

**Comment by JuanFMontesinos** [comment]
@JanuszL Thanks :)
