### ISSUE TITLE
How to match class name and label on inference stage?

### ISSUE THREAD

**Issue by Yogurt2019** [NVIDIA/DALI#2198]
I use DALI to do image classification tasks, 
but I don't know how to ensure that in training stage and inference stage the label and class name is same matched?(like class2idx in torchvision dataset)
for example:
    training stage: 0 -> cat    1-> dog
how can I ensure the same match during inference stage?
thanks for any help!

**Comment by JanuszL** [comment]
Hi,
In the case of all readers, you get the numerical value preset in the data set and attached to each image (each classification data set in the format of RecordII, TFRecord, or caffe LMDB entry defines the image and well-defined class value attached to it). In the case of the FileReader you have a guarantee that folder names have an assigned a unique label value from 0 to N in lexicographical order. If you want to assign an own label value to each image please use `file_list` argument and prepare your data set description like in [this example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/getting%20started.html#Defining-the-pipeline).

**Comment by Yogurt2019** [comment]
> Hi,
> In the case of all readers, you get the numerical value preset in the data set and attached to each image (each classification data set in the format of RecordII, TFRecord, or caffe LMDB entry defines the image and well-defined class value attached to it). In the case of the FileReader you have a guarantee that folder names have an assigned a unique label value from 0 to N in lexicographical order. If you want to assign an own label value to each image please use `file_list` argument and prepare your data set description like in [this example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/getting%20started.html#Defining-the-pipeline).

thx for replying!
I'm using the ops.FileReader, but how to get the default label from FileReader?

**Comment by JanuszL** [comment]
As said, if you want to set given label use `file_list`, if not then sort your folder in lexicographical order and assign values starting from 0 - this should provide you a mapping that DALI creates internally.

**Comment by Yogurt2019** [comment]
> As said, if you want to set given label use `file_list`, if not then sort your folder in lexicographical order and assign values starting from 0 - this should provide you a mapping that DALI creates internally.

OK, thank you again for patient replying!
