### ISSUE TITLE
Error: "Variable frame rate videos are unsupported " - Unable to process video using VideoReader. 

### ISSUE THREAD

**Issue by ptirupat** [NVIDIA/DALI#2212]
I am trying to read a video using the VideoReader and I get the following error
[/opt/dali/dali/operators/reader/video_reader_op.h:66] [/opt/dali/dali/operators/reader/loader/video_loader.cc:375] Assert on "skip_vfr_check_ || almost_equal(av_q2d(file.frame_base_), pkt.duration * av_q2d(file.stream_base_), 2)" failed: Variable frame rate videos are unsupported.
nvidia-dali version : 0.22
ffmpeg version : 4.2.1

Please let me know a way to solve this problem. Thank you.

**Comment by JuanFMontesinos** [comment]
It's not an issue. Variable frame rate is not supported. You can reencode videos to a constant framerate using ffmpeg

**Comment by klecki** [comment]
Hi @ptirupat, indeed we don't support variable frame rate videos. The reason is we currently produce evenly-spaced sequences of the same length from the input data in the video reader and it is not that straightforward in the case of vfr videos - but we're investigating the possible solutions.

The suggestion from @JuanFMontesinos to reencode the videos is a good one, thank you for that.

**Comment by ptirupat** [comment]
Thank you for the reply. I am able to read the video now. I have a related issue. How can I read all the frames from a video using the VideoReader? Here is the code snippet I am using

`class VideoPipe(Pipeline):
    def __init__(self, batch_size, num_threads, device_id, file_list, shuffle):
        super(VideoPipe, self).__init__(batch_size, num_threads, device_id, seed=16)
        sequence_length = 8
        initial_prefetch_size = 16
        self.input = ops.VideoReader(device="gpu", filenames=file_list, sequence_length=sequence_length,
                                     shard_id=0, num_shards=1,
                                     random_shuffle=shuffle, initial_fill=initial_prefetch_size)


    def define_graph(self):
        output = self.input(name="Reader")
        return output

if __name__ == '__main__':
    video_folder = <folder_path>
    file_list = [os.path.join(video_folder, f) for f in os.listdir(video_folder)]
    shuffle = False
    batch_size = 1
    pipe = VideoPipe(batch_size=batch_size, num_threads=2, device_id=0, file_list=file_list, shuffle=shuffle)
    pipe.build()
    n_iter = 6
    for i in range(n_iter):
        pipe_out = pipe.run()
        print(len(pipe_out))
        sequences_out = pipe_out[0].as_cpu().as_array()
        print(sequences_out.shape)`

**Comment by klecki** [comment]
Hi, the Video readers partitions the video into sequences of frames, according to the `sequence_length` `step` and `stride` parameters.
It will output batches of 4D tensors in FHWC layout - the first dimension is the Frame dimension corresponding to `sequence_length` provided. The `HWC` part are the decoded frames.

With the default values for `step` and `stride`, the code you provided will give you, in every iteration a batch of 1 sample, consisting of frames 8 frames in range: `[i * 8, (i + 1) * 8)` - where `i` is the iteration number (as there is no shuffling). Making the batch size bigger will pack more consecutive sequences into one batch.

After specifying what sequences you want you can check the epoch size for given video reader using `epoch_size` method of the Pipeline:
https://docs.nvidia.com/deeplearning/dali/user-guide/docs/pipeline.html#nvidia.dali.pipeline.Pipeline.epoch_size

or use one of the dedicated framework iterators to handle the epoch size, which are described here: https://docs.nvidia.com/deeplearning/dali/user-guide/docs/framework_plugins.html

**Comment by ptirupat** [comment]
Thank you so much for your reply. It was very helpful. I still have a couple of questions. 

1. I set batch_size to 1 and I currently have only one video in the file_list. Using `epoch_size` method I see that there are 1800 sequences for that video with a `sequence_length` of 2. If I set `batch_size` to 2, I still see that the `epoch_size` method still returns 1800. What does this mean?

2. If my video has odd number of frames and I set the `sequence_length` to 2, will the final sequence still have a 2 frames or 1 frame?

3. If there are multiple videos in the file_list, are the videos read one after the other in an order? What does `epoch_size` return when the videos in the file_list have different number of frames?

Thank you for taking time to reply.

**Comment by klecki** [comment]
> Thank you so much for your reply. It was very helpful. I still have a couple of questions.
> 
>     1. I set batch_size to 1 and I currently have only one video in the file_list. Using `epoch_size` method I see that there are 1800 sequences for that video with a `sequence_length` of 2. If I set `batch_size` to 2, I still see that the `epoch_size` method still returns 1800. What does this mean?

My apologies, the epoch_size you obtain is in **samples**, not in the iterations, sorry for the confusion.

>     2. If my video has odd number of frames and I set the `sequence_length` to 2, will the final sequence still have a 2 frames or 1 frame?

Here is the part that generates or valid sequences for the videos you provided: https://github.com/NVIDIA/DALI/blob/master/dali/operators/reader/loader/video_loader.h#L212

Only sequences that fully fit in the video are produced, so in this case the final sequence will have 2 frames and the last frame will be not used.

>     3. If there are multiple videos in the file_list, are the videos read one after the other in an order? What does `epoch_size` return when the videos in the file_list have different number of frames?

Yes, they are read one after another (you can also specify shuffle to mix the sequences). The epoch size will give you the sum of the sequences generated for all your files.

**Comment by ptirupat** [comment]
Thank you very much for your reply. I really appreciate it.
