### ISSUE TITLE
Does ops.colorSpaceConversion  output_type=type.GRAY respect LUMA weights 0.299 0.58 0.114?

### ISSUE THREAD

**Issue by bamfpga** [NVIDIA/DALI#2217]
Hi, I am trying to convert to grayscale. Originally I performed YCbCr conversion and chose the first Y channel (grayscale with luma weights), and I'd like to know whether this equivalent or not to grayscale conversionwith types.GRAY does? My question is, does type.GRAY mean grayscale conversion with Luma coefficients? 
![image](https://user-images.githubusercontent.com/47028243/90525659-2ae1fd00-e178-11ea-94e0-5906dbb67886.png)
Thanks in advance!

**Comment by klecki** [comment]
Hi @bamfpga.
For the RGB to Gray the formula you provided is used.

On GPU, DALI uses npp for RGB to Gray conversion, which you can see here: https://github.com/NVIDIA/DALI/blob/master/dali/operators/image/color/color_space_conversion.cu#L181
namely the `nppiRGBToGray_8u_C3C1R`: https://docs.nvidia.com/cuda/npp/group__image__color__to__gray.html

For CPU we use OpenCV's cvtColor for the RGB to Gray, call originating around here:
https://github.com/NVIDIA/DALI/blob/master/dali/operators/image/color/color_space_conversion.cc#L60
https://github.com/NVIDIA/DALI/blob/master/dali/util/ocv.cc#L170
Here's the doc for OpenCV: https://docs.opencv.org/4.4.0/de/d25/imgproc_color_conversions.html

Both libraries use that formula.

**Comment by bamfpga** [comment]
Thank you!
