### ISSUE TITLE
RuntimeError: Critical error in pipeline: Failed to create Optical Flow context: Verify that your device supports Optical Flow.

### ISSUE THREAD

**Issue by ptirupat** [NVIDIA/DALI#2218]
I am using a TITAN X (PASCAL) GPU with the CUDA Version and Driver Version as shown below.
![image](https://user-images.githubusercontent.com/2749299/90542273-d4fa5e80-e151-11ea-8b48-090461c0c715.png)

I am using the following code to read frames and compute optical flow. 

```python
    class VideoPipe(Pipeline):
        def __init__(self, batch_size, num_threads, device_id, file_list, sequence_length):
              super(VideoPipe, self).__init__(batch_size, num_threads, device_id, seed=16)
              self.input = ops.VideoReader(device="gpu", filenames=file_list, sequence_length=sequence_length,
                                     shard_id=0, num_shards=1,
                                     random_shuffle=False, dtype=types.FLOAT)
              self.of_op = ops.OpticalFlow(device="gpu", output_format=4)
        def define_graph(self):
            output = self.input(name="Reader")
            flow = self.of_op(output.gpu())
            return (output, flow)
```

With this code, I get the error "RuntimeError: Critical error in pipeline: Failed to create Optical Flow context: Verify that your device supports Optical Flow."

I have installed latest version of nvidia-dali, version 0.24.0. Please suggest how I can fix this issue.

Thank you

**Comment by ptirupat** [comment]
I realized that currently optical flow library is supported only on Volta GPUs. Closing this issue.

**Comment by JanuszL** [comment]
Hi,
@ptirupat, side note, Ampere architecture supports OpticalFlow as well.
