### ISSUE TITLE
how to install DALI offline

### ISSUE THREAD

**Issue by Doom9234** [NVIDIA/DALI#2224]
Hi,
I need install without 'pip --extra-index-url https:xxx' , is DALI can be installed offline?

**Comment by klecki** [comment]
Hi @Doom9234,
you can just download the wheels (and tf plugin as well) and install them directly.

We always list the direct links in releases like here: https://github.com/NVIDIA/DALI/releases/tag/v0.24.0


If you want a nightly or weekly build, you can look up the
https://developer.download.nvidia.com/compute/redist/nightly/{package-name} or
https://developer.download.nvidia.com/compute/redist/weekly/{package-name} urls, like:

https://developer.download.nvidia.com/compute/redist/nightly/nvidia-dali-nightly-cuda110/

and download the latest one.

**Comment by klecki** [comment]
One more thing:
up till our latest (0.24.0) release, the wheel is specific to minor Python version (so you need to match cp37-cp37m in the wheel name to python 3.7 etc).
The TF Plugin works with any Python.

Starting from 0.25 (the nightly builds already use this) we have one wheel that works with all Python 3 versions (from 3.5 to 3.8).

**Comment by Doom9234** [comment]
> Hi @Doom9234,
> you can just download the wheels (and tf plugin as well) and install them directly.
> 
> We always list the direct links in releases like here: https://github.com/NVIDIA/DALI/releases/tag/v0.24.0
> 
> If you want a nightly or weekly build, you can look up the
> [https://developer.download.nvidia.com/compute/redist/nightly/{package-name}](https://developer.download.nvidia.com/compute/redist/nightly/%7Bpackage-name%7D) or
> [https://developer.download.nvidia.com/compute/redist/weekly/{package-name}](https://developer.download.nvidia.com/compute/redist/weekly/%7Bpackage-name%7D) urls, like:
> 
> https://developer.download.nvidia.com/compute/redist/nightly/nvidia-dali-nightly-cuda110/
> 
> and download the latest one.

Thank you for the quick replay,  I think that closes this issue.

**Comment by Doom9234** [comment]
> Hi @Doom9234,
> you can just download the wheels (and tf plugin as well) and install them directly.
> 
> We always list the direct links in releases like here: https://github.com/NVIDIA/DALI/releases/tag/v0.24.0
> 
> If you want a nightly or weekly build, you can look up the
> [https://developer.download.nvidia.com/compute/redist/nightly/{package-name}](https://developer.download.nvidia.com/compute/redist/nightly/%7Bpackage-name%7D) or
> [https://developer.download.nvidia.com/compute/redist/weekly/{package-name}](https://developer.download.nvidia.com/compute/redist/weekly/%7Bpackage-name%7D) urls, like:
> 
> https://developer.download.nvidia.com/compute/redist/nightly/nvidia-dali-nightly-cuda110/
> 
> and download the latest one.

Hi @klecki ,
Thank you for the quick replay, I think that closes this issue.
