### ISSUE TITLE
Memory leak of AudioDecoder

### ISSUE THREAD

**Issue by milkpot** [NVIDIA/DALI#2233]
Run the following code with the attached files.

```
import nvidia.dali.ops
import nvidia.dali.pipeline
import nvidia.dali.types

class MyPipeline(nvidia.dali.pipeline.Pipeline):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.reader = nvidia.dali.ops.FileReader(file_root='.', file_list='filelist.txt')
        self.decoder = nvidia.dali.ops.AudioDecoder(dtype=nvidia.dali.types.DALIDataType.FLOAT)

    def define_graph(self):
        data, label = self.reader()
        data, rate = self.decoder(data)
        return data

pipeline = MyPipeline(batch_size=128, num_threads=1, device_id=0)
pipeline.build()

while True:
    pipeline.run()
```

[filelist.txt](https://github.com/NVIDIA/DALI/files/5134838/filelist.txt)

[440hz.ogg.zip](https://github.com/NVIDIA/DALI/files/5134837/440hz.ogg.zip)

Run the top command in another terminal.
The VIRT and RES of the process increase constantly (at the speed of 100MB/sec on my machine) and finally the process is killed by the OOM killer.

**Comment by JanuszL** [comment]
Hi,
Thank you for the code sample. I was able to reproduce the problem.
I will try to narrow down the problem and get back to you with the fix.

**Comment by JanuszL** [comment]
https://github.com/NVIDIA/DALI/pull/2235 should fix this problem. Please try nightly build that follow merge of this change.

**Comment by JanuszL** [comment]
DALI 0.26 is available and should include the needed functionality.
