### ISSUE TITLE
Contributing to DALI

### ISSUE THREAD

**Issue by ijpq** [NVIDIA/DALI#2239]
Hi, 
I am a computer major. DALI is a really great tool. It can read datasets across frameworks and optimize the processing speed. I have seen a lot of external contribution welcome on github, and I very much hope that I can do my best to contribute code to the open source project of DALI. I have studied C/C++/CUDA_certificate and tried to learn the source code of DALI these days. I also read the instructions written here https://github.com/NVIDIA/DALI/issues/1953, but I still feel a sense of loss. I am more accustomed to reading code from the main function, and I don’t know where to start when facing the DALI source code.

Respectfully

**Comment by JanuszL** [comment]
Hi,
I'm glad you are willing to contribute. DALI is a bit bigger project that you probably used to work with so examining only the main function won't help much.
However, you can start from https://github.com/NVIDIA/DALI/issues/1829.
You should look into [CPU](https://github.com/NVIDIA/DALI/blob/master/dali/operators/image/color/color_space_conversion.cc) and [GPU](https://github.com/NVIDIA/DALI/blob/master/dali/operators/image/color/color_space_conversion.cc), enum definition for [python](https://github.com/NVIDIA/DALI/blob/master/dali/python/backend_impl.cc#L1104) and [c++ side](https://github.com/NVIDIA/DALI/blob/master/include/dali/core/common.h#L117) implementation and add a separate code path for the requested functionality. To check it you can add an additional python test, something similar to [flip operator test](https://github.com/NVIDIA/DALI/blob/master/dali/test/python/test_operator_flip.py) that compares DALI implementation with the python one.
You can learn how to build DALI using this [guideline](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/compilation.html).
