### ISSUE TITLE
[Question] CropMirrorNormalize vs Normalize

### ISSUE THREAD

**Issue by JuanFMontesinos** [NVIDIA/DALI#2247]
What's the relationship between `CropMirrorNormalize` and 'Normalize`?
In the latter you can choose the axis to normalize.

I was looking for to get the same normalization than
`ops.Normalize(device='gpu', batch=False, axes=[0, 1, 2])`

**Comment by JanuszL** [comment]
Hi,
`CropMirrorNormalize` requires to have provided stddev and mean values during operator instantiation while the `Normalize` can compute them based on each sample/batch values. Also `CropMirrorNormalize` can crop, flip and permute the layout from NHWC to NCHW. So, there is no way to do the operation you want with just `CropMirrorNormalize`.

**Comment by JuanFMontesinos** [comment]
Okaaay thank you. 
I though operators with similar names would behave the same way.

**Comment by JanuszL** [comment]
> I though operators with similar names would behave the same way.

Yes and no.
Yes - they both perform normalization.
No - thy way to obtain the mean and stdev differ.

**Comment by Data-drone** [comment]
How can I achieve

`ops.CropMirrorNormalize(device="gpu",
                                            output_dtype=types.FLOAT,
                                            output_layout=types.NCHW,
                                            image_type=types.RGB,
                                            mean=[0.50707516 * 255,0.48654887 * 255,0.44091784 * 255], 
                                            std=[0.26733429 * 255,0.25643846 * 255,0.27615047 * 255])`

with `ops.Normalize` ? I want to just normalize without Crop and Mirror

**Comment by JanuszL** [comment]
Hi,
You can still use `CropMirrorNormalize`, but don't provide Crop and Mirror arguments.
To learn how to use `ops.Normalize` please check [this guide](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/normalize.html).
