### ISSUE TITLE
[Question] Segmentation pipeline with images and masks in TIFF files

### ISSUE THREAD

**Issue by kindoblue** [NVIDIA/DALI#2252]
Is there an operator like the FileReader that can return two files (input image and mask image) instead of image and label? I cannot use ExternalSource pipeline and I would like to avoid the TFRecord creation. The input files, both images and masks will be TIFF files.

**Comment by klecki** [comment]
Hi @kindoblue,
we don't support this directly. I would suggest to use two separate FileReader operators - first for the images and a second for the masks.
If you provide them file_lists (they would need to contain some dummy label values unfortunately), and specify the same seed they should output the samples in the same order (and also work well wrt to sharding the dataset).

**Comment by kindoblue** [comment]
Thanks @klecki for the help. Perhaps I will also consider writing a custom operator for that. I was surprised to learn this use case is not directly supported.
