### ISSUE TITLE
Feature Request - RTX IO and GPUDirect Storage for image data

### ISSUE THREAD

**Issue by kleingeo** [NVIDIA/DALI#2255]
I am not entirely sure if this is the proper channel for this, but I'm not sure where else to post a question like this (if another location, please let me know). With the up-coming RTX 3000 series and their improved I/O capabilities, will there be upcoming support for using that hard-ware for loading images into GPUs directly from storage devices?

**Comment by klecki** [comment]
Hi,
we're investigating the integration with GPUDirect Storage but for now I cannot provide any concrete timeline.
We will keep you posted when we will have more details.

We're looking into the GPUDirect Storage (and not the RTX IO) as this is more aimed at the HPC and DL. 

We are also interested in your use-case. Do you have a need for those technologies or experience any kind of IO-related bottleneck? Can you tell us a bit more?

**Comment by kleingeo** [comment]
Our work flow generally has IO bottle necks and bottle necks related to preprocessing data in the dataloader on the CPU rather than accelerating it on the GPU. Our (the lab I'm apart of) deals with medical images, so generally larger 3D image volumes (either in numpy or medical image formats like nifti or mha) or extremely large 2D histology images. 

I know that numpy images are supported now, but I couldn't find specific documentation for 3D images. Are they supported currently?

**Comment by JanuszL** [comment]
@kleingeo - thank you for clarification.
DALI doesn't support pure GPU decoding of images. Also, 3D images are not supported yet (this is also a thing in our backlog). So you need to use NumPy for now.
Do you know how much your pipeline is blocked by the data reading itself and how much by the processing?

**Comment by kleingeo** [comment]
I dont know the exact numbers, and it differs between myself and other members in our lab (I am probably the least impacted as I've taken steps to reduce it). Probably the largest bottleneck are `*.svs` images which are high resolution 2D images that are opened with OpenSlide. 

Are 3D numpy volumes supported currently, and not 3D volumes in other formats, or are no 3D type data supported at all?

**Comment by JanuszL** [comment]
> Are 3D numpy volumes supported currently, and not 3D volumes in other formats, or are no 3D type data supported at all?

We support reading any numpy volume, and you need to check the operator description to see if it can process 3D volume (like warp, rotate or flip).

**Comment by kleingeo** [comment]
> > Are 3D numpy volumes supported currently, and not 3D volumes in other formats, or are no 3D type data supported at all?
> 
> We support reading any numpy volume, and you need to check the operator description to see if it can process 3D volume (like warp, rotate or flip).

It seems like most operations I would need to augmentation are supported for 3D volumes. One think I am confused about is when loading an image, does it load the image directly into the GPU or are images loaded to the GPU then need to be transferred to the GPU? I assume if it is the latter that integrating GPUDirect Storage would help this?

**Comment by klecki** [comment]
> It seems like most operations I would need to augmentation are supported for 3D volumes. One think I am confused about is when loading an image, does it load the image directly into the GPU or are images loaded to the GPU then need to be transferred to the GPU? I assume if it is the latter that integrating GPUDirect Storage would help this?

This is true, currently all readers are CPU operators - that means the data is produced as CPU buffers and needs to be transferred to GPU (which can be done by DALI). Most of the data we read still needs some CPU processing to for example parse the shape/size of the inputs and allocate accordingly.

If the data can be loaded directly to GPU like in the case of numpy volumes it should be a good case for GDS with several benefits (we only need GPU allocation, we skip the loading of the whole volume to CPU).

As a side note - our ExternalSource operator which is used for accepting custom user inputs for the cases, that are not covered by our Readers and Decoders, can accept GPU buffers.

**Comment by JanuszL** [comment]
Hi,
In the recent nightly build DALI enables GPU Direct storage support in the GPU variant of the NumpyReader operator. Fell free to check it out.

**Comment by JanuszL** [comment]
0.29 has been released and should address this request.
