### ISSUE TITLE
Adding pytorch plugin

### ISSUE THREAD

**Issue by Hemantr05** [NVIDIA/DALI#2257]
I have some experience working with pytorch would like it to know if it would helpful developing a plugin for DALI for the same.

**Comment by klecki** [comment]
Hi,
our current PyTorch integration consist of the iterators:
https://docs.nvidia.com/deeplearning/dali/user-guide/docs/plugins/pytorch_tutorials.html
and our [ExternalSource](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.ops.ExternalSource) operator can accept PyTorch tensors.

If you have any ideas on how to make our PyTorch integration better or how to extend it we are happy to discuss them here or see and review any PRs.

**Comment by JanuszL** [comment]
Hi @Hemantr05 ,

One idea that comes to my mind is to extend the DALI PyTorch iterator to produce sparse tensors. You can check [GluonIterator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/plugins/mxnet_plugin_api.html#nvidia.dali.plugin.mxnet.DALIGluonIterator) SPARSE_TAG and DENSE_TAG.

**Comment by Hemantr05** [comment]
@JanuszL would there happen to be a discussion forum or a platform where the above can be discussed ?

**Comment by Hemantr05** [comment]
@klecki Would developing a computational graph of the  same be helpful?

**Comment by JanuszL** [comment]
@Hemantr05 - GitHub is our platform. I think we can discuss it here, in this issue.
Could you elaborate more on what exactly you have in mind by `a computational graph of the same `?

**Comment by Hemantr05** [comment]
@JanuszL 
Creating a computational graph for DALI which shows the workflow or a visualization toolkit like tensorboard.

**Comment by JanuszL** [comment]
> Creating a computational graph for DALI which shows the workflow or a visualization toolkit like tensorboard.

Plugin DALI to tensorboard would be very nice but I'm afraid that this may be a too big task for the beginning without knowing much about DALI internals. DALI is mostly a C++ library with a thin Python API layer on top. If you are more familiar with Python development then extending PyTorch iterator would be a good task for the beginning. If you are fine with working with the native code then go ahead with the tensorboard.

**Comment by Hemantr05** [comment]
@JanuszL Will look into PyTorch Iterator for now.

**Comment by Hemantr05** [comment]
Hello @JanuszL could you please assign me this issue?

**Comment by JanuszL** [comment]
I have created https://github.com/NVIDIA/DALI/issues/2365, but I cannot assign it to you (it appears that I can assign only people from the Nvidia organization). Anyway, please feel the owner of the task.

**Comment by Hemantr05** [comment]
Oh alright! @JanuszL thanks!

**Comment by Hemantr05** [comment]
@ksaur Apologies for the delay.
Will resolve this by the end of the week.

**Comment by Hemantr05** [comment]
Hi, @JanuszL  Apologies for the delay.
Will resolve this by the end of the week.

**Comment by JanuszL** [comment]
Sure, not problem. We are not pushing.
