### ISSUE TITLE
Assert on "in_layout.ndim() == input.shape().sample_dim()" failed

### ISSUE THREAD

**Issue by konioyxgq** [NVIDIA/DALI#2259]
`from nvidia.dali.pipeline import Pipeline
import nvidia.dali.ops as ops
import nvidia.dali.types as types
import numpy as np
from timeit import default_timer as timer
import numpy as np
import matplotlib.pyplot as plt
import math
import os.path

from PIL import Image

image_dir = 

class HybridPipe(Pipeline):
    def __init__(self, batch_size, num_threads, device_id, pipelined = True, exec_async = True):
        super(HybridPipe, self).__init__(batch_size, num_threads, device_id, seed = 12, exec_pipelined=pipelined, exec_async=exec_async)
        self.input = ops.FileReader(file_root=image_dir, random_shuffle=True)
        self.decode_cpu = ops.ImageDecoder(device = "cpu", output_type = types.RGB)
        self.Gaussian_Blur = ops.GaussianBlur(device = 'cpu',sigma = [1])
        self.crop = ops.Crop(device = "gpu", crop = [110,110],out_of_bounds_policy= 'pad')
    def define_graph(self):
        self.jpegs, self.labels = self.input(name="Reader")
        images = self.decode_cpu(self.jpegs)
        images = self.Gaussian_Blur(images)
        images = self.crop(images.gpu())
        return images

    def iter_setup(self):
        pass

batch_size = 1

for i in range(10):
    pipe = HybridPipe(batch_size=batch_size, num_threads=1, device_id = 0)
    pipe.build()
    pipe_out = pipe.run()
    pipe_out_cpu = pipe_out[0].as_cpu()
    img_chw = pipe_out_cpu.at(0)`
I got an error.
`RuntimeError: Critical error in pipeline: [/opt/dali/dali/operators/image/crop/crop.h:43] Assert on "in_layout.ndim() == input.shape().sample_dim()" failed
Stacktrace (11 entries):
[frame 0]: /opt/conda/lib/python3.6/site-packages/nvidia/dali/libdali_operators.so(+0x3bbc96) [0x7f1160b4dc96]
[frame 1]: /opt/conda/lib/python3.6/site-packages/nvidia/dali/libdali_operators.so(+0xa8d886) [0x7f116121f886]
[frame 2]: /opt/conda/lib/python3.6/site-packages/nvidia/dali/libdali_operators.so(+0x7a64d5) [0x7f1160f384d5]
[frame 3]: /opt/conda/lib/python3.6/site-packages/nvidia/dali/libdali_operators.so(+0x7808ef) [0x7f1160f128ef]
[frame 4]: /opt/conda/lib/python3.6/site-packages/nvidia/dali/libdali.so(+0x1110d2) [0x7f114a37c0d2]
[frame 5]: /opt/conda/lib/python3.6/site-packages/nvidia/dali/libdali.so(+0x1119df) [0x7f114a37c9df]
[frame 6]: /opt/conda/lib/python3.6/site-packages/nvidia/dali/libdali.so(+0xeada8) [0x7f114a355da8]
[frame 7]: /opt/conda/lib/python3.6/site-packages/nvidia/dali/libdali.so(+0x15bb9c) [0x7f114a3c6b9c]
[frame 8]: /opt/conda/lib/python3.6/site-packages/nvidia/dali/libdali.so(+0x8d61bf) [0x7f114ab411bf]
[frame 9]: /lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7f117c5696db]
[frame 10]: /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7f117c292a3f]

Current pipeline object is no longer valid.`
What can I do to solve this problem?

**Comment by mzient** [comment]
It's a known bug, fixed in version 0.25.

**Comment by JanuszL** [comment]
@konioyxgq can you update to 0.25 and check if it works?

**Comment by konioyxgq** [comment]
Thank you for your reply. I will try to update and check.

**Comment by konioyxgq** [comment]
It's ok! Thank you very much!
