### ISSUE TITLE
[question] How could I do random brightness changes

### ISSUE THREAD

**Issue by RichardMLe** [NVIDIA/DALI#2260]
I want to change the brightness of the input randomly, like this:
definition in __init__ of pipeline
`self.brightness = ops.ColorTwist(device="gpu", ) `
`self.random = ops.PythonFunction(function = random.random)`

and code in  define_graph is :
`output = self.brightness(images, brightness = self.random())`

but the ops.ColorTwist function can not run because of the 'brightness = self.random()' code.

**Comment by mzient** [comment]
First of all, don't use ColorTwist for adjusting just brigtness - there's a BrightnessContrast that runs faster.
DALI has internal random number generators - the simplest one being uniform distribution.

```Python
from nvidia.dali.pipeline import Pipeline
import nvidia.dali.fn as fn
import nvidia.dali.types as types
import numpy as np

def get_dummy_image():
    image = np.zeros([480, 640, 3], dtype=np.float32) + 128
    return [image]  # batch of 1

pipe = Pipeline(batch_size=1, device_id=0, num_threads=3)
with pipe:
    input = fn.external_source(source=get_dummy_image, layout="HWC")
    rand = fn.uniform(range=(0.5,1.5))
    out = fn.brightness_contrast(input, brightness=rand)
    pipe.set_outputs(rand, out)

pipe.build()
o = pipe.run()
print("Brightness:  ", o[0].at(0))
print("Pixel value: ", o[1].at(0)[0,0,0])
```

**Comment by RichardMLe** [comment]
> 
> 
> First of all, don't use ColorTwist for adjusting just brigtness - there's a BrightnessContrast that runs faster.
> DALI has internal random number generators - the simplest one being uniform distribution.
> 
> See an example (using the new functional API):
> 
> ```python
> from nvidia.dali.pipeline import Pipeline
> import nvidia.dali.fn as fn
> import nvidia.dali.types as types
> import numpy as np
> 
> def get_dummy_image():
>     image = np.full([480, 640, 3], 128, dtype=np.float32)
>     return [image]  # batch of 1
> 
> pipe = Pipeline(batch_size=1, device_id=0, num_threads=3)
> with pipe:
>     input = fn.external_source(source=get_dummy_image, layout="HWC")
>     rand = fn.uniform(range=(0.5,1.5))
>     out = fn.brightness_contrast(input, brightness=rand)
>     pipe.set_outputs(rand, out)
> 
> pipe.build()
> o = pipe.run()
> print("Brightness:  ", o[0].at(0))
> print("Pixel value: ", o[1].at(0)[0,0,0])
> ```

thankyou for your help.  This solves my problem
