### ISSUE TITLE
Segmentation fault when using RandomBBoxCrop

### ISSUE THREAD

**Issue by tri-e** [NVIDIA/DALI#2262]
When I make a call to a `RandomBBoxCrop` op in my `define_graph`, I get a segfault.

The line offending line looks like:
```python
anchor, shape, bboxes = self.random_bbox_crop(bboxes)
```

If I comment it out, the pipeline functions properly with no segfaults.

I have not been able to glean anything about what might be causing the issue, other than whether the op *must* receive non-empty  `bboxes` as input. Some images, of course, do not have any bboxes, so occasionally `bboxes` input is empty array: `[]` (as observed via a print function through `ops.PythonFunction`)

**Comment by JanuszL** [comment]
Hi,
Please take a look into [this](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/use_cases/detection_pipeline.html) or [this](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/use_cases/pytorch/single_stage_detector/pytorch_ssd.html) example.
You need to pass labels as well to the operator so when it discards bounding boxes it needs to do the same for the corresponding labels.

**Comment by tri-e** [comment]
Hello @JanuszL, thank you very much for your help.

This fixed my segfault issue.

**Comment by tri-e** [comment]
While now obvious in retrospect, I always appreciate when the docs are explicit about when args (like labels) should not be considered optional. Thanks again!

**Comment by JanuszL** [comment]
@tri-e - I just checked the code and indeed labels should be optional. So your crash is a real but. I will try to fix it. In the mean time please use the suggested work around.

**Comment by JanuszL** [comment]
https://github.com/NVIDIA/DALI/pull/2265 should solve the crash. Please check the nightly build form the day that would follow the merge of this change.

**Comment by JanuszL** [comment]
DALI 0.27 is available. It should address your request.
