### ISSUE TITLE
Facing an issue while creating a simple pipeline,

### ISSUE THREAD

**Issue by manish0079** [NVIDIA/DALI#2278]
RuntimeError                   Traceback (most recent call last)
<ipython-input-33-ba5e29343fc5> in <module>()
----> 1 pipe.build()

/usr/local/lib/python3.6/dist-packages/nvidia/dali/pipeline.py in build(self, define_graph)
    476             self._prepare_graph(define_graph)
    477 
--> 478         self._pipe.Build(self._names_and_devices)
    479         self._built = True

RuntimeError: Critical error when building pipeline:
Error when constructing operator: FileReader encountered:
[/opt/dali/dali/operators/reader/loader/file_label_loader.h:110] Assert on "Size() > 0" failed: No files found.

This is my code

image_dir="/content/sample_data/images"
batch_size = 1

```
class SimplePipeline(Pipeline):
    # print("helo")
    def __init__(self, batch_size, num_threads, device_id):
        super(SimplePipeline, self).__init__(batch_size, num_threads, device_id, seed = 12)
        # self.input = ops.FileReader(file_root = image_dir)
        # print(self.input)
        # instead of path to file directory file with pairs image_name image_label_value can be provided
        self.input = ops.FileReader(file_root = image_dir, file_list = image_dir + '/content/sample_data/images/label.txt')
        self.decode = ops.ImageDecoder(device = 'cpu', output_type = types.RGB)
``
    def `define_graph(self):`
        jpegs, labels = self.input()
        images = self.decode(jpegs)
        return (images, labels)
```

Ps:I am new to Deep Learning and this technology ,Can u help me in setting up the environment?I want to know the format of labels,while uploading the custom data i am getting an error

**Comment by JanuszL** [comment]
I see that is the absolute path, how about:
```
self.input = ops.FileReader(file_root = image_dir, file_list = image_dir + '/label.txt')
```
Also, keep in mind that `file_root` is added to each file entry in the `file_list`. I would recommend looking into this [tutorial](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/getting%20started.html). There is an example of using `file_list` you can examine and run on your own.

**Comment by manish0079** [comment]
Thank you @JanuszL ,One think i am not getting is like labels,If i am directly passing the image_dir 
 self.input = ops.FileReader(file_root = image_dir)
if I passed this above line ,i am getting the same error

Which format we have to give for file_list or label list

I couldnt see anything about labels in documentation

**Comment by JanuszL** [comment]
When you pass `file_root` you need to pass a parent directory with subdirs, and each of it houses images from one class.
Like:
```
parent_dir
  \-class_1:
    - image_1
    - image_2
  \-class_2:
    - image_3
    - image_4
...
```
DALI would assign a unique class to each subdir.
If you wan to to have a control over classes values you should create a file_list, using the following format:
```
class_1/image_1 1
class_1/image_2 1
class_2/image_3 2
class_2/image_4 2
```
And pass `parent_dir` as the root dir.

**Comment by manish0079** [comment]
Thank you @JanuszL ..
