### ISSUE TITLE
Segmentation fault while JPEG Decoding

### ISSUE THREAD

**Issue by melgor** [NVIDIA/DALI#2280]
Hi,
I have faced the problem of SIGSEGV for single image. I'm attaching minimal example to reproduce this behaviour (Notebook which died after reading the image and script where we can notice Segmentation fault)
The image look normally.
![bad_img](https://user-images.githubusercontent.com/2587438/93480349-a06af580-f8fd-11ea-9a88-b59a5df1defd.jpeg)

In my case, it was just single image from 2M, but OpenCV and PIL read this image without the problem.
[minimal_example_SIGSEGV.zip](https://github.com/NVIDIA/DALI/files/5239558/minimal_example_SIGSEGV.zip)

Tested on DALI 0.24

**Comment by JanuszL** [comment]
Hi,
I'm sorry but I'm not able to reproduce your problem. Can you be more specific regarding Torch and DALI version you are using?
In my case running everything in docker it just works:
```
docker run --rm -ti --gpus=all nvidia/cuda:11.0-devel-ubuntu18.04
apt update && apt install curl python3 python3-distutils wget -y
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python get-pip.py
pip install --extra-index-url https://developer.download.nvidia.com/compute/redist nvidia-dali-cuda110
pip install torch
wget https://github.com/NVIDIA/DALI/files/5239558/minimal_example_SIGSEGV.zip
unzip minimal_example_SIGSEGV.zip
cd minimal_example_SIGSEGV
python3 minimal_example_dali.py
```
Can you try to run the pipeline itself without the Pytorch iterator?

**Comment by JanuszL** [comment]
It works in my case for 0.24 and 0.25.

**Comment by melgor** [comment]
Thanks for quick response. 
I'm using VM on Google-Cloud (also AI-Platform fails while training). I'm not sure it you are familiar with GCP, but those are 
My exact setup:
GPU: `NVIDIA-SMI 418.87.01    Driver Version: 418.87.01    CUDA Version: 10.1`
DALI: `https://developer.download.nvidia.com/compute/redist/nvidia-dali-cuda100/nvidia_dali_cuda100-0.24.0-1446725-cp37-cp37m-manylinux2014_x86_64.whl`
Python: 3.7.4
requirements.txt: [requirements.txt](https://github.com/NVIDIA/DALI/files/5243825/requirements.txt)

Full list of packages from conda: [environment.txt](https://github.com/NVIDIA/DALI/files/5243830/environment.txt) (I upload txt because github block YML, but this is YML)

System:
```
lsb_release -a                                                                                                                        ─╯
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.11 (stretch)
Release:	9.11
Codename:	stretch
```


And in this setup, problem occurs. Look like I setup have different:
- System (Debian vs Ubuntu)
- PyTorch Version (I'm using old 1.3 v 1.6 by default)
- CUDA 10.1 vs 11

**Comment by JanuszL** [comment]
Hi,
I have reproduced the issue with CUDA 10 based build however it works fine with CUDA 11 one. Apparently, the issue was fixed inside the nvJPEG library somewhere in between.
What I could recommend is to update the GPU diver to CUDA 11 capable and use DALI CUDA 11 based build. The rest of your software stack doesn't have to change (including the CUDA toolkit as DALI doesn't link to it dynamically), and you can still use your environment.

**Comment by melgor** [comment]
Thanks for help.
