### ISSUE TITLE
about ‘ops.PythonFunction’ issue

### ISSUE THREAD

**Issue by konioyxgq** [NVIDIA/DALI#2281]
I used **ops.PythonFunction** in pipline, which will cause the speed of loading data to drop by about 4 times.

Some data enhancement operations that are not supported by DALI are done in **ops.PythonFunction**, and they are done with CPU.
Is this expected? How to solve this slow problem?

**Comment by JanuszL** [comment]
Hi,
PythonFunction Operators are mainly aimed to prototype new augmentations or debug the Pipeline. So the low performance is the thing you can expect, as the python operator is executed synchronously in the main python thread and is not distributed between different threads/processes.
However, you can try to use CuPy and offload this operation to the GPU or write a custom native operator on your own. Please check related documentation sections [here](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/custom_operations/index.html).

**Comment by konioyxgq** [comment]
Hello, do you mean that although the parameter num_threads is set to 5 when I initialize pipline, when ops.PythonFunction is executed, it is executed 5 times in sequence, and then multi-threaded to do the following operations?

**Comment by JanuszL** [comment]
Hi,
I mean that `num_threads` doesn't apply to the `ops.PythonFunction`, only to the native operators.

**Comment by konioyxgq** [comment]
What are native operators? 
Does it refer to the operations listed here at https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html?highlight=compress?

**Comment by JanuszL** [comment]
This is one of the examples. How to create your own that you can dynamically load to DALI can be found in this guide https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/custom_operations/custom_operator/create_a_custom_operator.html.

**Comment by konioyxgq** [comment]
I got it.
Sorry, I want to confirm again.
Is there any other way besides writing CC or CU files? Because my cuda programming is very poor, this workload is a bit heavy.

**Comment by JanuszL** [comment]
You can try to use https://docs.python.org/3.7/library/multiprocessing.html inside the python operator to scale your workload to multiple CPUs, but still the pipelining inside DALI won't work so I'm not sure how much performance you can get.

**Comment by konioyxgq** [comment]
Good, thank you very much
