### ISSUE TITLE
Can we integrate dali with Object detection algorithm?

### ISSUE THREAD

**Issue by Harish872** [NVIDIA/DALI#2283]
Can we integrate dali with Object detection algorithm like Yolo Pytorch implementation??I have started exploring Dali,In the example pf Simple Pipeline i can able to see the classification part ,My question is like how to start integrating Dali  Pipeline with different object detection model how to setup the environmental flow,I have tested simple pipeline but don't no how to approach for Object detection

**Comment by JanuszL** [comment]
Hi,
It very much depends on the processing pipeline your model may require. I would start by checking if DALI supports all required operations, if not you can add missing one writing them in python or in C++ using [this guide](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/custom_operations/index.html).
If you think that any operator you are missing may be useful to the wide audience feel free to fill a PR and contribute to the DALI core.
