### ISSUE TITLE
Batch Cropping pipeline with different cropping centers for each run and for each batch element

### ISSUE THREAD

**Issue by dariodematties** [NVIDIA/DALI#2286]
Hi, I want to make a Pipeline in which I can crop a batch of images but I want to pass a different batch of crop center positions in each run of the pipeline. The position for each element of the batch is different too.
How can I do that?
Thanks!

**Comment by klecki** [comment]
Hi @dariodematties,
we have [Uniform Operator](https://docs.nvidia.com/deeplearning/dali/master-user-guide/docs/supported_ops.html#nvidia.dali.ops.Uniform) that allows to generate random parameters in DALI pipeline, that can be fed to the `crop_x`, `crop_y`, `crop_pos_x`, `crop_pos_y` etc parameters. Some examples in [getting started](https://docs.nvidia.com/deeplearning/dali/master-user-guide/docs/examples/getting%20started.html#Tensors-as-arguments-and-Random-Number-Generation).

If you want to control what numbers are provided there, you can use [ExternalSource Operator](https://docs.nvidia.com/deeplearning/dali/master-user-guide/docs/supported_ops.html#nvidia.dali.ops.ExternalSource) which allows to feed DALI Pipeline with data generated in Python, tutorial available [here](https://docs.nvidia.com/deeplearning/dali/master-user-guide/docs/examples/general/data_loading/external_input.html) - you can for example provide a callback that would return a batch of `crop_pos_x` and second for `crop_pos_y`.

Both approaches allow you to specify different numbers per sample, you will need to pass the result of calling the Operator `Uniform` or `ExternalSource` to appropriate keyword parameter of `Crop` inside `define_graph`.

**Comment by JanuszL** [comment]
You can also look into [Slice operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.ops.Slice) and provide not only a position of the window but its size as well each iteration.

**Comment by dariodematties** [comment]
Thank you @klecki and @JanuszL! 
Finally I used ExternalSource Operator and adapted the example in order to introduce tensors.
I am so glad about the fast and relevant responses.
Thanks!
