### ISSUE TITLE
Data augmentation on 3D images

### ISSUE THREAD

**Issue by quartermaine** [NVIDIA/DALI#2305]
I am working with medical images which I have convert to TfReocords and I want to do some augmentations of the fly when I read the records does DALI augmentations support 3D images?

**Comment by JanuszL** [comment]
Hi,
Please check which operator supports 3D volumetric data in [our documentation](https://docs.nvidia.com/deeplearning/dali/master-user-guide/docs/supported_ops.html).
You can also check [the example](https://docs.nvidia.com/deeplearning/dali/master-user-guide/docs/examples/image_processing/3d_transforms.html).
This docs and examples refers to the latest commit and nightly build. [Stable release](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html) has smaller coverage.

**Comment by quartermaine** [comment]
@JanuszL 
Hi,
Thank you for the information provided. 
Is it  possible to write custom augmentations in numpy and wrap them with DALI?
I am facing some performance bottlenecks when I use custom functions in my pipeline.

**Comment by JanuszL** [comment]
You can use:
- numpy
- cupy to get GPU acceleration
- write your native operator
Please check [these guides](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/custom_operations/index.html).
Numpy code would be the easiest to write but the performance would be inferior compared to the native code, it is mostly intended for prototyping.

**Comment by quartermaine** [comment]
@JanuszL 

Ok, I will check and see if am successful.

**Comment by quartermaine** [comment]
@JanuszL 

Is there a way to build a dali pipeline with TfRecords from Nifti images?

**Comment by JanuszL** [comment]
@quartermaine - not now, we don't have any decoder that could decode Nifti images. What you would need to do is to use ExternalSource and write accessing and decoding the images in python.

**Comment by JanuszL** [comment]
Still, we would be more than happy to review and accept any PR enabling Nifti decoding capability.

**Comment by quartermaine** [comment]
@JanuszL  

So what I need is to build a custom ExternalSource that reads the Nifti images? 
At current my process of reading the Nifti images involves an external library named nibabel.

I would also welcome an extension with Nifti capabilities, do I have to open a new PR?

**Comment by JanuszL** [comment]
Honestly, I'm not that much into medical imagining. If nibabel works then it may be the way to go.
> I would also welcome an extension with Nifti capabilities, do I have to open a new PR?

I mean if you are willing and capable to write the necessary code feel more than welcome to.

**Comment by JanuszL** [comment]
@quartermaine,

You can check the last improvements in [the `external_source`` oeprator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.external_source), especially `parallel` and `prefetch_queue_depth` options. If you use them it may provide sufficient performance when you implement your Nifti image data loading at the python side.

**Comment by quartermaine** [comment]
@JanuszL 

Thank you for the update I will have a look at it.
