### ISSUE TITLE
Module 'nvidia.dali.ops' has no attribute 'CropCastPermute

### ISSUE THREAD

**Issue by Syzygianinfern0** [NVIDIA/DALI#2323]
I am currently on the latest version of DALI (as of writing this `nvidia-dali-cuda100-0.26.0`). I'm trying to run code meant for version `nvidia-dali==0.10.0`, but this API seems to be deprecated. What do I replace it with? Is there a guide/docs/wiki anywhere pointing out the changes in API with versions?

This is the exact stack trace:
```
    self.crop = ops.CropCastPermute(device="gpu", \
AttributeError: module 'nvidia.dali.ops' has no attribute 'CropCastPermute'
```

**Comment by JanuszL** [comment]
Hi,
Please try to use `CropMirrorNormalize` instead. Now when the operator is deprecated, the appropriate info which should be used instead is present in the documentation, but back in 0.10 there was no proper deprecation warning.
