### ISSUE TITLE
Prepare the output from dali pipe to feed NN

### ISSUE THREAD

**Issue by dariodematties** [NVIDIA/DALI#2330]
Hi, let's say I have a pipe which returns 5 outputs, from 5 different operations

Each output is living on GPU and has the following shape [batch_size, W, H, C] (they are dali tensors)

I want to put these 5 outputs in a unique dali TensorListGPU or dali TensorGPU,

for instance whose shape is [5, batch_size, W, H, C]

then I want to reshape, permute, etc such thing in order to get the following shape [batch_size, 5*C, W, H]

This is the shape my NN is waiting

Or maybe I could copy, cast, etc the dali GPU tensors to the conventional GPU pytorch tensor, so I can operate on it as ussual

I do not know if pytorch NN can process dali TensorListGPU or dali TensorGPU neither

How should I proceed?

Thanks!

**Comment by JanuszL** [comment]
DALI still doesn't support tensor stacking. This functionality is under the development. Until them please use DALI iterator to return tensors in relevant framework and use the stacking operation from there, for example https://pytorch.org/docs/stable/generated/torch.stack.html.

**Comment by dariodematties** [comment]
Thanks @JanuszL, so I suppose I have to use nvidia.dali.plugin.pytorch.DALIGenericIterator in order to get the outputs from the pipeline in standard pytorch GPU tensors.

Well, I tried to do so.

This is my pipeline

```
class FoveatedRetinalProcessor(Pipeline):
    def __init__(self, batch_size, num_threads, device_id, num_gpus, fixation, images):
        super(FoveatedRetinalProcessor, self).__init__(batch_size, num_threads, device_id, seed = 15, exec_pipelined=False, exec_async=False, prefetch_queue_depth=1)
        self.resize_zero = ops.Resize(device = "gpu", resize_x = 640, resize_y = 640)
        
        self.rotate = ops.Rotate(device = "gpu")
        
        self.resize_one  = ops.Resize(device = "gpu", resize_x = 30, resize_y = 30)

        self.crop_zero  = ops.Crop(device = "gpu", crop_h = 640, crop_w = 640)
        self.crop_one   = ops.Crop(device = "gpu", crop_h = 400, crop_w = 400)
        self.crop_two   = ops.Crop(device = "gpu", crop_h = 240, crop_w = 240)
        self.crop_three = ops.Crop(device = "gpu", crop_h = 100, crop_w = 100)
        self.crop_four  = ops.Crop(device = "gpu", crop_h = 30, crop_w = 30)
        
        self.img_batch = ops.ExternalSource(device="gpu", source = images)
        self.fixation_source = ops.ExternalSource(source = fixation, num_outputs = 3)

    def define_graph(self):
        images = self.img_batch()

        crop_pos_x, crop_pos_y, angle = self.fixation_source()
        
        images   = self.rotate(self.resize_zero(images), angle=angle)

        cropped0 = self.crop_zero(images)
        cropped1 = self.crop_one(cropped0, crop_pos_x=crop_pos_x, crop_pos_y=crop_pos_y)
        cropped2 = self.crop_two(cropped0, crop_pos_x=crop_pos_x, crop_pos_y=crop_pos_y)
        cropped3 = self.crop_three(cropped0, crop_pos_x=crop_pos_x, crop_pos_y=crop_pos_y)
        cropped4 = self.crop_four(cropped0, crop_pos_x=crop_pos_x, crop_pos_y=crop_pos_y)
        
        sized0   = self.resize_one(cropped0)
        sized1   = self.resize_one(cropped1)
        sized2   = self.resize_one(cropped2)
        sized3   = self.resize_one(cropped3)
        sized4   = self.resize_one(cropped4)
        
        return (cropped0, cropped1, cropped2, cropped3, cropped4, sized0, sized1, sized2, sized3, sized4)
```
I built it and run it as always and it worked

When I built it I called it pipe1

Then I try to define the DALI iterator in order to get sized0, sized1, sized2, sized3 and sized4, out in pytorch GPU tensors 

```
from nvidia.dali.plugin.pytorch import DALIGenericIterator

outputs = DALIGenericIterator(pipelines=[pipe1], output_map=["sized0", "sized1", "sized2", "sized3", "sized4"])
```

And I receive the following error message

```
RuntimeError: Mixing pipeline API type. Currently used: PipelineAPIType.BASIC, but trying to use: PipelineAPIType.ITERATOR
```

Any help will be highly appreciated!

Thanks

**Comment by JanuszL** [comment]
You can find more about this topic in [this documentation section](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/advanced_topics.html#running-dali-pipeline). So if you are using DALIGenericIterator, don't call run() manually on the pipeline.

**Comment by dariodematties** [comment]
Thanks @JanuszL , now I receive the following error

`IndexError: list index out of range`

This is the code line

`outputs = DALIGenericIterator(pipelines=pipes1, output_map=["sized0", "sized1", "sized2", "sized3", "sized4"])`

Where pipes1 is a list with one pipeline inside it

`[<NVIDIA_DALI_Pipelines.FoveatedRetinalProcessor at 0x7fbed3d64828>]`

**Comment by JanuszL** [comment]
Your `output_map` should match the output from the pipeline. You returns `(cropped0, cropped1, cropped2, cropped3, cropped4, sized0, sized1, sized2, sized3, sized4)` while the `output_map` cares only about part of it.

**Comment by dariodematties** [comment]
Thank you @JanuszL! I thought I could chose which returned values to pick.

It is working now, but there is an issue

To put you in context, remember that I bring a batch of images running one pipeline and then operate on the same batch running a second pipeline several times

When I want the next batch, I just have to run the first pipe again and the I can operate on the new batch running the second pipe several times

Well, now I have a DALI iterator in place of the second pipe, I simply use next() instead of run() now

I can run the second pipe several times on the same batch of images using next() repeatedly and it works well, but when I bring the next batch using the first pipe I have to do next() twice in order to operate in the new batch since in the first execution of next() the pipe continues still operating in the first batch

This is something didn't happen before running the second pipe using run()

Why is it happening and how can I solve this problem?

Thanks!

**Comment by JanuszL** [comment]
DALI FW iterators were developed with non conditional execution in mind like in your case and they are scheduling runs ahead, so when you consume the data the next batch is being prepared. What you can try to do it to try to use custom, wrapper over the DALI pipeline, something like:
```
def pytorch_wrapper(pipes):
    outs = []
    for p in pipes:
        p.schedule_run()
    for p in pipes:
        outs.append([])
        dev_id = p.device_id
        torch_gpu_device = torch.device('cuda', dev_id)
        torch_cpu_device = torch.device('cpu')
        out = p.share_outputs()
        for o in out:
            if type(o) is TensorGPU:
                tensor_type = torch_gpu_device
            else:
                tensor_type = torch_cpu_device
            o = o.as_tensor()
            t = torch.empty(o.shape(),
                            dtype=to_torch_type[np.dtype(o.dtype())],
                            device=tensor_type)
            if isinstance(o, (TensorGPU, TensorListGPU)):
                # Using same cuda_stream used by torch.zeros to set the memory
                stream = torch.cuda.current_stream(device=dev_id)
                feed_ndarray(o, t, cuda_stream=stream)
            else:
                feed_ndarray(o, t)
            outs[-1].append(t)
        p.release_outputs()
    return outs
```
It accepts the list of pipelines and returns the outputs as Torch tensors, so you can run it as:
```
from nvidia.dali.pipeline import Pipeline
import nvidia.dali.fn as fn
import nvidia.dali.types as types
import numpy as np
from nvidia.dali.plugin.pytorch import feed_ndarray, to_torch_type
import torch
from nvidia.dali.backend import TensorGPU, TensorListGPU

batch_size = 2
test_data_shape = [1, 2]
def get_data():
    out = [np.random.randint(0, 255, size = test_data_shape, dtype = np.uint8) for _ in range(batch_size)]
    return out

pipe = Pipeline(batch_size=batch_size, num_threads=3, device_id=0)
outs = fn.external_source(source = get_data, device = "gpu")
pipe.set_outputs(outs)
pipe.build()
dali_out = pipe.run()
print("The first pipe\n", dali_out[0].as_cpu().as_array())

class image_collector(object):
    def __init__(self):
        pass
    def __iter__(self):
        return self
    def __next__(self):
        return self.data[0]
    next = __next__

def pytorch_wrapper(pipes):
    outs = []
    for p in pipes:
        p.schedule_run()
    for p in pipes:
        outs.append([])
        dev_id = p.device_id
        torch_gpu_device = torch.device('cuda', dev_id)
        torch_cpu_device = torch.device('cpu')
        out = p.share_outputs()
        for o in out:
            if type(o) is TensorGPU:
                tensor_type = torch_gpu_device
            else:
                tensor_type = torch_cpu_device
            o = o.as_tensor()
            t = torch.empty(o.shape(),
                            dtype=to_torch_type[np.dtype(o.dtype())],
                            device=tensor_type)
            if isinstance(o, (TensorGPU, TensorListGPU)):
                # Using same cuda_stream used by torch.zeros to set the memory
                stream = torch.cuda.current_stream(device=dev_id)
                feed_ndarray(o, t, cuda_stream=stream)
            else:
                feed_ndarray(o, t)
            outs[-1].append(t)
        p.release_outputs()
    return outs

iterator = image_collector()
iterator.data = dali_out

pipe2 = Pipeline(batch_size=batch_size, num_threads=3, device_id=0, prefetch_queue_depth=1)
outs2 = fn.external_source(source = iterator, device = "gpu")
pipe2.set_outputs(outs2)
pipe2.build()
final_out = pytorch_wrapper([pipe2])
print("The second pipe\n", final_out)
final_out = pytorch_wrapper([pipe2])
print("The second pipe, get the same data\n", final_out)

dali_out = pipe.run()
print("The first pipe run again to get new data\n", dali_out[0].as_cpu().as_array())
iterator.data = dali_out
final_out = pytorch_wrapper([pipe2])
print("The second pipe get new data from the first one\n", final_out)
```

**Comment by dariodematties** [comment]
Thanks so much @JanuszL, it is a clean solution but the returned values do not live in cuda, they live on cpu and I do not want a back and forth between cuda and cpu for each batch.

When I used DALI iterators they lived in GPU!   

I think

```
out = p.share_outputs()
```

is not satisfying 

```
if type(o) is TensorGPU:
```

in your code, could it be the case?

Thanks!

**Comment by JanuszL** [comment]
My bad, it should be:
```
(...)
o = o.as_tensor()
if type(o) is TensorGPU:
  tensor_type = torch_gpu_device
 else:
  tensor_type = torch_cpu_device
(...)
```

**Comment by dariodematties** [comment]
Thanks so much @JanuszL, now it is working!
