### ISSUE TITLE
Sequence length, step size and stride how to use them

### ISSUE THREAD

**Issue by Timen** [NVIDIA/DALI#2331]
A common method of training video based models is to use a certain sequence length such as 32 or 64. While it is an option to preprocess videos to sample sequences of that length and encode them as individual videos. On large datasets this can very quickly lead to a lot of files being generated, unfortunately due to some data caching in the VideoReader this can cause ram issues see #2220 . 

It seems however that it is possible to sample sequences from the original video using the video reader, specifically the args:
sequence_length (Frames to load per sequence.)
step (Frame interval between each sequence)
stride (Distance between consecutive frames in sequence.)

With these args one could sample a number of different sequences from the video, however what isn't clear is how these sequences will be processed in a batch. If it is the case that each video is sampled for sequences using the args above, does that mean that one batch would be filled with multiple sequences from a video or is there some shuffling that still happens with intra video sequences. Having multiple sequences of the same video per batch is problematic for obvious reasons. One other option would be to not use the VideoReader to sample sequences at all but simply decode the whole video and sample using some of the other DALI ops. Ideally the sampling could be done in the videoreader but I'm unsure if this is possible?

**Comment by JanuszL** [comment]
Hi,
This https://github.com/NVIDIA/DALI/pull/2308 should reduce memory consumption when the shuffling is enabled.
The shuffling strategy is as follow:
- discover all files and their lengths in the dataset
- generate all possible sequences
- preschuffle all possible sequences (once for the pipeline existence, it is deterministic)
- read sequences sequentially to sampling buffer, then sample it randomly to form the batch

So it is very unlikely that samples in the batch would come from the same video/would be neighboring sequences if there is only one video.

**Comment by Timen** [comment]
Yes, I'm looking forward for that one to get merged! But this means that one can simply use the original videos and they automatically get cut up in sequences spread over batches. That's very cool! 

One last thing, as for the stride, let's say I use stride=2 which means every other frame is sampled, does that mean that only even-frame sequences are created or are uneven-frame sequences also created (so starting from frame 0 vs 1)?

**Comment by JanuszL** [comment]
`stride` is used to specify the distance between frames in the sequence, `step` the distance between the first frame of the consecutive sequences, like:
```
stride = 2
step = 1
sequence_length = 3
[0, 2, 4], [1, 3, 5]

stride = 3
step = 1
sequence_length = 3
[0, 3, 6], [1, 4, 7]

stride = 1
step = 2
sequence_length = 3
[0, 1, 2], [2, 3, 4]
```

**Comment by Timen** [comment]
Perfect so the stride is applied after the first frame is determined. That is all I needed to know, thank you again @JanuszL for your quick responses 👍

**Comment by JanuszL** [comment]
https://github.com/NVIDIA/DALI/pull/2308 has just been merged, it should be available in the next nightly build.
