### ISSUE TITLE
about pipline issue

### ISSUE THREAD

**Issue by konioyxgq** [NVIDIA/DALI#2348]
In the process of using dali pipline, I found that the pipline of data processing used in the whole training process is fixed, which means that the define_graph in pipline is defined, and the data processing is the same in future training.
But when I want to use different data processing methods for each image or each batch in training (for example, one batch uses crop, and the other bantch uses resize), what should I do?

**Comment by konioyxgq** [comment]
I have tried the following method：
`pipe = HybridPipe(batch_size=batch_size, num_threads=1, device_id = 0)
for i in range(10):
    pipe.define_graph()
    pipe.build()
    pipe_out = pipe.run()`
In **pipe.define_graph()**, I implemented two random selections from 5 data enhancement methods.
But I saved the 10 pictures I processed and looked at them, it seems that they all adopted the data enhancement method of **pipe.build()**.
I expected that every time I load **pipe.define_graph()** and **pipe.build()**, I will get different data enhancement methods. But from the results, it seems that the pipe will not be built multiple times.
What should I do to achieve my goal?

**Comment by klecki** [comment]
Hi.
To use different augmentations for each sample, we use DALI random generator Operators like: [CoinFlip](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.ops.CoinFlip) or [Uniform](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.ops.Uniform).

At the end of this tutorial: https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/erase.html you can see how Uniform can be used to generate random erase regions.

Unfortunately, we don't support conditional augmentations in the pipeline yet. Closes you can get is either using such parameters, that the Operator would be no-op (for example Rotate by 0 degrees) or you can approximate it with arithmetic Operators: https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/expressions/expr_conditional_and_masking.html 
Keep in mind that both methods will still compute the outputs, so the image would be rotated by 0 degrees and for referenced multiplexing you need to compute all alternatives upfront and than select the desired one.
