### ISSUE TITLE
ExternalSource with multi GPUs error

### ISSUE THREAD

**Issue by wjgaas** [NVIDIA/DALI#235]
I use ExternalSource with multi GPUs, some times it gives me a wrong label, such as -9223372036854775808.
Can you give an example that use ExternalSource with multi GPUs on the MxNet?

IndexError: index -9223372036854775808 is out of bounds for axis 1 with size 180855

**Comment by JanuszL** [comment]
Hi,
Which DALI version are you using?
Do you have any sample script that could reproduce that problem?
Internally tracked DALI-294.
Br,
Janusz

**Comment by wjgaas** [comment]
this is my sample script, it is ok when using single gpu , but when i use multi gpus it sometimes gives me a wrong label. i use pip to install the DALI, pip install --extra-index-url https://developer.download.nvidia.com/compute/redist nvidia-dali.

class ExternalInputIterator(object):
    def __init__(self, db_folder, batch_size):
        self.record = mx.recordio.MXIndexedRecordIO(db_folder+"data.idx",
                                                    db_folder+"data.rec", 'r')
        self.batch_size = batch_size
        self.epoch_size = 9000000
        self.data_idx = list(range(0, self.epoch_size))
        random.shuffle(self.data_idx)

    def __iter__(self):
        self.i = 0
        return self

    def __next__(self):
        batch = []
        labels = []
        for _ in range(self.batch_size):
            s = self.record.read_idx(self.data_idx[self.i])
            header, jpeg = recordio.unpack(s)

            self.i += 1
            if self.i == self.epoch_size:
                self.i = 0
                random.shuffle(self.data_idx)

            batch.append(jpeg)
            labels.append(np.array([header.label], np.float32))

        return batch, labels

    next = __next__


class HybridTrainPipe(Pipeline):
    def __init__(self, eii_iterator, batch_size, num_threads, device_id):
        super(HybridTrainPipe, self).__init__(batch_size, num_threads, device_id,
                                              seed = 12 + device_id)
        self.eii_iterator = eii_iterator
        self.input = ops.ExternalSource()
        self.input_label = ops.ExternalSource()

        self.decode = ops.nvJPEGDecoder(device="mixed", output_type=types.BGR)
        self.jitter = ops.Jitter(device="gpu")
        self.contrast = ops.Contrast(device="gpu", image_type=types.BGR)
        self.brightness = ops.Brightness(device="gpu", image_type=types.BGR)
        self.saturation = ops.Saturation(device="gpu", image_type=types.BGR)
        self.hue = ops.Hue(device="gpu", image_type=types.BGR)
        self.uniform = ops.Uniform(range=(0.8, 1.2))

        self.cmnp = ops.CropMirrorNormalize(device="gpu",
                                            output_dtype=types.FLOAT,
                                            output_layout=types.NCHW,
                                            crop=(112, 96),
                                            crop_pos_x=0,
                                            crop_pos_y=0,
                                            image_type=types.BGR,
                                            mean=[127.5, 127.5, 127.5],
                                            std=[128.0, 128.0, 128.0])
        self.coin = ops.CoinFlip(probability=0.5)

    def iter_setup(self):
        (images, labels) = self.eii_iterator.next()
        self.feed_input(self.jpegs, images)
        self.feed_input(self.labels, labels)

    def define_graph(self):
        self.jpegs = self.input()
        self.labels = self.input_label()
        images = self.decode(self.jpegs)
        images = self.jitter(images, mask=self.coin())
        images = self.contrast(images, contrast=self.uniform())
        images = self.brightness(images, brightness=self.uniform())
        images = self.saturation(images, saturation=self.uniform())
        images = self.hue(images, hue=self.uniform())
        images = self.cmnp(images, mirror=self.coin())
        return [images, self.labels]

    from image_iter import ExternalInputIterator, HybridTrainPipe
    eii = ExternalInputIterator(db_folder=data_dir,
                                batch_size=args.per_batch_size)
    eii_iterator = iter(eii)

    trainpipes = [HybridTrainPipe(eii_iterator=eii_iterator,
                                  batch_size=args.per_batch_size,
                                  num_threads=1,
                                  device_id=gpu_id) for gpu_id in range(len(ctx))]

    print("Training pipeline epoch size: {}".format(eii.epoch_size))

    from nvidia.dali.plugin.mxnet import DALIClassificationIterator
    train_dataiter = DALIClassificationIterator(trainpipes, eii.epoch_size)

**Comment by wjgaas** [comment]
when i compile from the github source code with release_v0.3, release_v0.4 and master, i get a run time error, 
'''
RuntimeError: [/home/wjg/software-install/dali/dali/pipeline/data/allocator.h:113] CUDA error "an illegal instruction was encountered"
terminate called after throwing an instance of 'std::runtime_error'
  what():  [/home/wjg/software-install/dali/dali/pipeline/util/stream_pool.h:47] CUDA error "an illegal instruction was encountered"
'''

**Comment by JanuszL** [comment]
Hi,
Could you tell more what version of CUDA do you have and what GPU you are using?
Br,
Janusz

**Comment by wjgaas** [comment]
i use cuda9.0 with cuda-linux64-nvjpeg-9.0-v0.2.0, and my gpu is v100.

**Comment by JanuszL** [comment]
Hi,
Could you recheck with the latest binary?

**Comment by JanuszL** [comment]
If it still doesn't work please reopen.
