### ISSUE TITLE
Strange behavior when converting to a torch tensor (feed_ndarray)

### ISSUE THREAD

**Issue by MrNeither** [NVIDIA/DALI#2354]
Hello. I built a pipeline in DALI, and in the end I want to convert it to the torch format. I use this code:
```python
self.torch_buffer = torch.empty(self.batch_size, 64, 64, 3, dtype=torch.float, device=torch.device('cuda:0'))
out = self.run()
print(out.as_cpu().as_array()[30, 30, 13:16])
feed_ndarray(dali_tensor=out.as_tensor(), arr=self.torch_buffer)
print(self.torch_buffer.cpu().numpy()[30, 30, 13:16])
```

output:
```
[[108  67 103]
 [103  61  97]
 [ 85  42  80]]
[[2.4585118e+00 5.2808062e+13 7.8258412e-13]
 [1.1031319e+04 8.4953353e+14 1.7555011e-22]
 [9.4810082e-03 8.3168331e+14 1.1179479e-23]]
```

Could you help me figure it out? I will be grateful for any help.

**Comment by MrNeither** [comment]
#2227  Please excuse me, I should have looked at issues here first.
For those who will face the same problem, note that the os.GaussianBlur method returns DALIDataType.UINT8, so you need to explicitly specify what output format you want.

**Comment by JanuszL** [comment]
This works but the copy from GPU to GPU through CPU is far from perfect. Please check `pytorch_wrapper` from 
https://github.com/NVIDIA/DALI/issues/2330#issuecomment-704589278 (with a correction from https://github.com/NVIDIA/DALI/issues/2330#issuecomment-704748183).

**Comment by MrNeither** [comment]
Thank you very much!!
