### ISSUE TITLE
i want install DALI in docker，and this errror。

### ISSUE THREAD

**Issue by seeyouagain111** [NVIDIA/DALI#2362]
Error when constructing operator: VideoReader encountered:
[/opt/dali/dali/operators/reader/loader/video_loader.h:182] Assert on "lib_handle_" failed: Failed to load libnvcuvid.so, needed by the VideoReader operator. If you are running in a Docker container, please refer to https://github.com/NVIDIA/nvidia-docker/wiki/Usage

what should i do？thanks

**Comment by JanuszL** [comment]
Hi,
Nvidia docker runtime doesn't expose video capability by default. Either you need to add:
```
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,video,utility
``` 
inside your docker file or run it with `--gpus '"capabilities=compute,utility,video"'` option.

**Comment by seeyouagain111** [comment]
> Hi,
> Nvidia docker runtime doesn't expose video capability by default. Either you need to add:
> 
> ```
> ENV NVIDIA_VISIBLE_DEVICES all
> ENV NVIDIA_DRIVER_CAPABILITIES compute,video,utility
> ```
> 
> inside your docker file or run it with `--gpus '"capabilities=compute,utility,video"'` option.

thanks for your reply.i got a question. 
my image name is  'slowfast' and my docker name is 'slowfast' too.how can i run it?
i used start my docker with'docker exec -it slowfast bash'
so, how to add '--gpus '"capabilities=compute,utility,video"'' ?

**Comment by JanuszL** [comment]
I think it would be best to ask this question on docker related forum.

**Comment by seeyouagain111** [comment]
![图片](https://user-images.githubusercontent.com/24680495/96097057-18c7d500-0f03-11eb-8249-344a49279158.png)
look red boxes. but i still got the error:Failed to load libnvcuvid.so

**Comment by JanuszL** [comment]
Where/how you run it? Do you have any self-contained reproduction we can run?
Can you check if `/usr/lib/x86_64-linux-gnu/libnvcuvid.so` file exits? You can also try to reinstall your driver.

**Comment by seeyouagain111** [comment]
i got it ，thanks
