### ISSUE TITLE
Spaces in file_list will be regarded as invalid

### ISSUE THREAD

**Issue by Kipsora** [NVIDIA/DALI#2369]
Hi, thanks for developing such an awesome library but my problem here is that I want to give `file_list` to `ops.FileReader` but the path contains spaces. Those spaces will cause parsing `file_list` failed. I then checked the [C++ codes](https://github.com/NVIDIA/DALI/blob/343fa809eeec30cc3af15febe4ddd4a75cbe2969/dali/operators/reader/loader/file_label_loader.h#L98-L125) (pasted below).

```C++
  void PrepareMetadataImpl() override {
    if (image_label_pairs_.empty()) {
      if (file_list_ == "") {
        image_label_pairs_ = filesystem::traverse_directories(file_root_);
      } else {
        // load (path, label) pairs from list
        std::ifstream s(file_list_);
        DALI_ENFORCE(s.is_open(), "Cannot open: " + file_list_);

        string image_file;
        int label;
        while (s >> image_file >> label) {
          auto p = std::make_pair(image_file, label);
          image_label_pairs_.push_back(p);
        }
        DALI_ENFORCE(s.eof(), "Wrong format of file_list: " + file_list_);
      }
    }
    DALI_ENFORCE(Size() > 0, "No files found.");

    if (shuffle_) {
      // seeded with hardcoded value to get
      // the same sequence on every shard
      std::mt19937 g(kDaliDataloaderSeed);
      std::shuffle(image_label_pairs_.begin(), image_label_pairs_.end(), g);
    }
    Reset(true);
  }

```

Let's say our path is `datasets/angry bacon/028.jpg` and the label for it is `angry bacon`, then the code will take `datasets/angry` as the path and `bacon/028.jpg` as the label, which is incorrect.

In order to avoid the X-Y problem, my original purpose is to create a pipeline for multiple data folders and each folder has a weight (for all images in the folder so that each image has its label along with its weight). The only method I came up with is to use `file_list` to read all the images along with the indices of each item and then use the indices to lookup the weights table and labels table. But as stated above, if the class label contains spaces it will fail and it's not convenient to rename the classes of the whole dataset.

I am sorry if I missed something but any suggestions would be appreciated. Thanks!

**Comment by Kipsora** [comment]
It would be most convenient if the `FileReader` can take a dict from python as the `file_list` instead of reading from a file. But in the case where a file is used, I think it should take one line at a time and then regard the last piece of the line as the label and the remaining as the path.

**Comment by JanuszL** [comment]
Hi,
Passing a direct from python instead of creating a `file_list` is on our ToDo list. We would be more than happy to accept a PR that would add such functionality.
Reworking parsing logic doesn't seem like the best idea as we have requested to add an ability to read more than one label per image. What sounds like a viable option is to change the separator between entries to `;` for example.

**Comment by Kipsora** [comment]
Thanks for replying to this issue. I am happy to contribute but I got some problems after viewing the codes. I am straight to the point: 

- I don't know whether `pybind` has interface for binding a function to multiple types. So currently, in order to maintain the backward compatibility, instead of changing the behaviour for `file_list`, I think it's better to put another argument like `file_list_dict` which, once provided, can override the behaviour of `file_list`.
- I am not a experienced user with C++ template programming and I just find that to pass a `dict` from python to C++ you will need to `DALI_REGISTER_TYPE(<a dict type>, <id for that dict type>)`. 

  I can define a new type by `using DALIStrToIntMapping = std::map<std::string, int>;` but I feel like this is too specific to this issue and may confuse other people. And I found in order to defining a new type, `to_string` and `SerializeToProtobuf` need to be implemented as well. So basically, the design choices are:
  - (I've already done) Create a new specific data type like `DALIStrToIntMapping` dedicating to the `file_list_dict` argument and implement `to_string` and `De/SerializeToProtobuf` as well.
  - Implement a general mapping datatype, which involves a lot of template programming. I feel like this is beyond my scope but I would be happy to learn :). 

I have no idea which one is preferred but it would be nice to have the voice from the DALI developers.

**Comment by JanuszL** [comment]
No one said it is going to be an easy task. However, I think this PR https://github.com/NVIDIA/DALI/pull/2389 may do what you are looking for more straightforwardly and easily.

**Comment by mzient** [comment]
#2389 Is addressing also this issue directly - you will be able to have spaces in file names (except trailing whitespace, but that would be an insane thing to have!).

**Comment by Kipsora** [comment]
> #2389 Is addressing also this issue directly - you will be able to have spaces in file names (except trailing whitespace, but that would be an insane thing to have!).

Thanks. I will keep my eye on the PR.
