### ISSUE TITLE
Multi-gpu pipeline execution

### ISSUE THREAD

**Issue by dariodematties** [NVIDIA/DALI#2370]
Hi, I have a second pipeline (pipe2) which receives images externally from  a first pipeline (pipe1)

pipe1 reads a batch of images from coco datasets

then pipe2 process such batch N times.

As long as I do not call pipe1 again pipe2 continues processing the same batch of images brought by pipe1

Then I want to use a dual GPU and set num_gpu = 2.
Consequently, pipe1 brings 2 batches

```
pipe_out1 = [pipe1.run() for pipe1 in pipes1]
```

The two batches are in pipe_out1[0] and pipe_out1[1]

But, here is the problem, because I do not know how to pass those two batches in order to get pipe2 process them

I will show pipe2 code here:

```

class ImageCollector(object):
    def __init__(self):
        pass
    def __iter__(self):
        return self
    def __next__(self):
        return self.data
    next = __next__




     






class FixationCommand(object):
    def __init__(self, batch_size):
        self.batch_size = batch_size

    def _get_vectors(self):
        self.vector1 = fixation_pos_x
        self.vector2 = fixation_pos_y
        self.vector3 = fixation_angle

    def __iter__(self):
        self._get_vectors()
        assert len(self.vector1) == self.batch_size
        assert len(self.vector2) == self.batch_size
        assert len(self.vector3) == self.batch_size
        self.i = 0
        self.n = len(self.vector1)
        return self

    def __next__(self):
        batch1 = []
        batch2 = []
        batch3 = []
        self._get_vectors()
        for _ in range(self.batch_size):
            element1 = self.vector1[self.i]
            batch1.append(element1)
            element2 = self.vector2[self.i]
            batch2.append(element2)
            element3 = self.vector3[self.i]
            batch3.append(element3)
            self.i = (self.i + 1) % self.n
        return batch1, batch2, batch3




class FoveatedRetinalProcessor(Pipeline):
    def __init__(self, batch_size, num_threads, device_id, num_gpus, fixation, images):
        super(FoveatedRetinalProcessor, self).__init__(batch_size, num_threads, device_id, seed = 15, exec_pipelined=False, exec_async=False, prefetch_queue_depth=1)
        self.resize_zero = ops.Resize(device = "gpu", resize_x = 640, resize_y = 640)
        
        self.rotate = ops.Rotate(device = "gpu")
        
        self.resize_one  = ops.Resize(device = "gpu", resize_x = 30, resize_y = 30)

        self.crop_zero  = ops.Crop(device = "gpu", crop_h = 640, crop_w = 640)
        self.crop_one   = ops.Crop(device = "gpu", crop_h = 400, crop_w = 400)
        self.crop_two   = ops.Crop(device = "gpu", crop_h = 240, crop_w = 240)
        self.crop_three = ops.Crop(device = "gpu", crop_h = 100, crop_w = 100)
        self.crop_four  = ops.Crop(device = "gpu", crop_h = 30, crop_w = 30)
        
        self.img_batch = ops.ExternalSource(device="gpu", source = images)
        self.fixation_source = ops.ExternalSource(source = fixation, num_outputs = 3)

    def define_graph(self):
        images = self.img_batch()

        crop_pos_x, crop_pos_y, angle = self.fixation_source()
        
        images   = self.rotate(self.resize_zero(images), angle=angle)

        cropped0 = self.crop_zero(images)
        cropped1 = self.crop_one(cropped0, crop_pos_x=crop_pos_x, crop_pos_y=crop_pos_y)
        cropped2 = self.crop_two(cropped0, crop_pos_x=crop_pos_x, crop_pos_y=crop_pos_y)
        cropped3 = self.crop_three(cropped0, crop_pos_x=crop_pos_x, crop_pos_y=crop_pos_y)
        cropped4 = self.crop_four(cropped0, crop_pos_x=crop_pos_x, crop_pos_y=crop_pos_y)
        
        sized0   = self.resize_one(cropped0)
        sized1   = self.resize_one(cropped1)
        sized2   = self.resize_one(cropped2)
        sized3   = self.resize_one(cropped3)
        sized4   = self.resize_one(cropped4)
        
        return (cropped0, cropped1, cropped2, cropped3, cropped4, sized0, sized1, sized2, sized3, sized4)



def pytorch_wrapper(pipes):
    outs = []
    for p in pipes:
        p.schedule_run()
    for p in pipes:
        outs.append([])
        dev_id = p.device_id
        torch_gpu_device = torch.device('cuda', dev_id)
        torch_cpu_device = torch.device('cpu')
        out = p.share_outputs()
        for o in out:
            o = o.as_tensor()
            if type(o) is TensorGPU:
                tensor_type = torch_gpu_device
            else:
                tensor_type = torch_cpu_device

            t = torch.empty(o.shape(),
                            dtype=to_torch_type[np.dtype(o.dtype())],
                            device=tensor_type)
            if isinstance(o, (TensorGPU, TensorListGPU)):
                # Using same cuda_stream used by torch.zeros to set the memory
                stream = torch.cuda.current_stream(device=dev_id)
                feed_ndarray(o, t, cuda_stream=stream)
            else:
                feed_ndarray(o, t)
            outs[-1].append(t)
        p.release_outputs()
    return outs
```

I pass the batch toe pipe2 through ImageCollector iterator  as well as certain parameters for a particular run through FixationCommand
I run the pipes (pipe2) which are 2 since I setted num_gpu=2 using pytorch_wrapper

This is how I create pipe2

```
images = NDP.ImageCollector()
fixation = NDP.FixationCommand(batch_size)

images.data = images_gpu

start = time()
pipes2 = [NDP.FoveatedRetinalProcessor(batch_size=batch_size, num_threads=2, device_id=device_id, num_gpus=num_gpus, fixation=fixation, images=images)  for device_id in range(num_gpus)]
for pipe2 in pipes2:
  pipe1.build()

total_time = time() - start
print("Computation graph built and dataset loaded in %f seconds." % total_time)
```

And this is how I run the pipies (pipe2)

```
NDP.fixation_pos_x = torch.rand((batch_size,1))
NDP.fixation_pos_y = torch.rand((batch_size,1))
NDP.fixation_angle = (torch.rand((batch_size,1))-0.5)*60

start = time()
pipe_out2 = NDP.pytorch_wrapper(pipes2)
total_time = time() - start
print("Computation graph run in %f seconds." % total_time)

print('Does pipe_out2 live in GPU: ', pipe_out2[0][0].is_cuda)

crop_images_cpu0 = pipe_out2[0][0].to('cpu')
crop_images_cpu1 = pipe_out2[0][1].to('cpu')
crop_images_cpu2 = pipe_out2[0][2].to('cpu')
crop_images_cpu3 = pipe_out2[0][3].to('cpu')
crop_images_cpu4 = pipe_out2[0][4].to('cpu')

sized_images_cpu0 = pipe_out2[0][5].to('cpu')
sized_images_cpu1 = pipe_out2[0][6].to('cpu')
sized_images_cpu2 = pipe_out2[0][7].to('cpu')
sized_images_cpu3 = pipe_out2[0][8].to('cpu')
sized_images_cpu4 = pipe_out2[0][9].to('cpu')
```

In the line 
images.data = images_gpu
 I pass the images that pipe1 brought but pipe2 process the same batch in the two gpus, how should I proceed in order to pass the two batches to the pipes in pipe2?

Thanks!

Dario

**Comment by JanuszL** [comment]
The recommended way is to use DDP (distributed data-parallel) and let one process handle one GPU to have better load balancing between CPU and GPU.
If you want to proceed with your approach I would do something like:
```
images = [NDP.ImageCollector(), NDP.ImageCollector()]
images[0].data = images_gpu[0]
images[1].data = images_gpu[1]

pipes2 = [NDP.FoveatedRetinalProcessor(batch_size=batch_size, num_threads=2, device_id=device_id, num_gpus=num_gpus, fixation=fixation, images=images[device_id])  for device_id in range(num_gpus)]```
Anyway, you need to make sure that each DALI pipeline - `pipes2` get a corresponding input from the pipes1.

**Comment by dariodematties** [comment]
Thank you @JanuszL, to tell you the truth, I was expecting you to recommend me doing just like that.

I thought it could be better to manage parallelism inside a shared memory system (a node) using threads but after reading during the weekend I realized the advantages in using DDP.

Therefore, I imagined DALI must be well integrated with DDL.

Thank you @JanuszL!

**Comment by JanuszL** [comment]
> I thought it could be better to manage parallelism inside a shared memory system (a node) using threads but after reading during the weekend I realized the advantages in using DDP.

From my point of view this case different handling of mulitnode and inter node data handling. For DDP is it the same in every case.

**Comment by dariodematties** [comment]
Tell me if I am wrong please, as far as I understand using threads you cannot go beyond one node since threads communicate with each other sharing the memory in the node and in their model abstraction they do not have other than share memory to communicate. Processes instead manage a different abstraction in which each process has its own private memory (at least virtually when they are inside the same node). Processes can communicate with each other using specific tools.

What I was thinking about is that since threads are lighter than processes and I have two GPUs sharing their memory in a node, maybe it could be better to use two threads inside a node and processes (each process running two threads) between nodes.

I have used such strategy in the past through MPI + OpenMP

But in my experience I have arrived to the conclusion that it is always better using processes no matter you are in a shared or distributed memory system

What do you think?

**Comment by JanuszL** [comment]
In the case of python, multithreading doesn't work well due to [GIL](https://wiki.python.org/moin/GlobalInterpreterLock). Besides that, models don't need much of synchronization besides reduction, and this is handled by other libraries like nccl which abstract away GPU2GPU, node2node communication.
I would say that it depends in general, and the way it is recommended it rather due to performance than can be obtained with available engineering effort, and not necessarily due to the best possible performance that handcrafted assembler can achieve.

**Comment by dariodematties** [comment]
> In the case of python, multithreading doesn't work well due to [GIL](https://wiki.python.org/moin/GlobalInterpreterLock). Besides that, models don't need much of synchronization besides reduction, and this is handled by other libraries like nccl which abstract away GPU2GPU, node2node communication.
> I would say that it depends in general, and the way it is recommended it rather due to performance than can be obtained with available engineering effort, and not necessarily due to the best possible performance that handcrafted assembler can achieve.

Thanks @JanuszL,  I think the best way to go is as you suggest, using DDP.

Thanks for the support!
