### ISSUE TITLE
DALI -> NN pipeline parallelization on distributed memory systems

### ISSUE THREAD

**Issue by dariodematties** [NVIDIA/DALI#2378]
Hi, I am using DALI interactively as an integral part of my network

My pipeline is the following:

First pipe1 brings a batch of images

Then I have the following closed loop

```
            ----<----
           |         ^
           v         |
pipe1 -> pipe2 -> NN -

```

where pipe2 augments the batch received from pipe1 accordingly to commands received from NN

After several runs of the closed loop pipe1 is called again and it brings the following batch in the dataset

Memory shared on a single node is not enough to deal with the batch sizes I am managing

I would really appreciate certain guidance in how to implement distributed memory parallelization of this approach

The cluster I am working on has Horovod available and is well integrated with pytorch

I want to distribute the batch among different nodes having the same NN in each node processing the different sections of the batch

This can be done easily on [pytorch](https://horovod.readthedocs.io/en/stable/pytorch.html) just modifying a couple of lines of code applying initialization, partitioning the dataset among workers using DistributedSampler, distributing the optimizer using DistributedOptimozer and finally broadcasting the parameters using broadcast_parameters.

I am asking myself if Horovod is integrated with DALI as well and how should I proceed?

**Comment by JanuszL** [comment]
Hi,
As far as I know, the Horovod is not recommended for PyTorch but the native way of distributing the workload (but I would check on the PyTorch-related forum for more details).
From the DALI side, it is handled in the same way, all you need to know is the world size and global rank. These two values should be passed to the relevant reader in your pipeline, and it will handle sharding internally. If you are using ExternalSource operator then it is the user's responsibility to deal with the sharding, and guarantee that each pipeline works on a separate, nonoverlapping shard of data.
You can check [this example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/use_cases/pytorch/resnet50/pytorch-resnet50.html) how RN50 can be run with multiple GPUs, processes, and DALI.

**Comment by dariodematties** [comment]
Hi @JanuszL 

I think this example is all what I nedd

Thank you for your help!
