### ISSUE TITLE
Functional API: pipeline reset possible after exception?

### ISSUE THREAD

**Issue by cceyda** [NVIDIA/DALI#2380]
I know exception handling is not possible in the current pipelines ref: https://github.com/NVIDIA/DALI/issues/1727 https://github.com/NVIDIA/DALI/issues/1435

But I was wondering if this was also the case for the Functional API.
My objective is to do integrity check on my images. So I have tried the following code. The problem is pipeline keeps spitting out the same exception after the first exception occurs. Is there a way to reset the pipeline? 

```py
import nvidia.dali as dali

batch_size=1

def gen_batch(dataset,batch_size): 
    imgs = []
    paths = []
    for _ in range(batch_size):
        i,p=next(dataset)
        imgs.append(i)
        paths.append(p)
    return (imgs, paths)

####init pipeline
pipe = dali.pipeline.Pipeline(batch_size = batch_size, num_threads = 2, device_id = 0)
with pipe:
    files = dali.fn.external_source()
    images = dali.fn.image_decoder(files, device = "mixed")
    pipe.set_outputs(images)
pipe.build()
#####

ds=iter(dataset) 

has_data=True
while has_data:
    try:
        (images,paths) = gen_batch(ds,batch_size)
        pipe.feed_input(files, images)
        try:
            pipe.run()
        except Exception as e:
            print("poo")
            # get? and remove corrupted image
            # Is there a way to reset the pipeline? because I keep getting same exception after first err. 
            # I tried using init pipeline block again but then the code hangs indefinitely, no errs.
    except StopIteration:
        has_data=False
        print('end')
```
In https://github.com/NVIDIA/DALI/issues/1435 @JanuszL says
> Also, there is the question of what should happen with other images in the batch that are fine - how to put it back to the pool used to generate batches.

Can it be an option to drop a batch if it has a corrupted item/s? I have millions of images in the pipeline I wouldn't mind dropping some batches, rather than checking them one by one priorly.

similar: https://github.com/NVIDIA/DALI/issues/306

**Comment by JanuszL** [comment]
Hi,
Functional API is just a different kind of interface, but the internals is the same. Regarding dropping the batch it is not currently possible nor straightforward, still, we will be more than happy to review and accept any PR that would tackle that functionality.

**Comment by cceyda** [comment]
Is it possible to release memory after an exception occurs? I tried a couple of things mentioned at #2070 without success

del pipe
gc.collect()
works when no exception occurs.but

try:
   pipe.run()
except Exception as e:
   del pipe
   gc.collect()
just hangs.

**Comment by JanuszL** [comment]
@cceyda - it may be a bug, let me dive deeper and get back to you later.

**Comment by JanuszL** [comment]
I have checked and I don't see any hang, and the memory is released when the code exit exception handling routine. You cannot expect to delete the pipe inside the exception handling as the reference to it is keep on the stack. This works fine for me:
```
import nvidia.dali as dali
from nvidia.dali.pipeline import Pipeline
import nvidia.dali.ops as ops
import nvidia.dali.types as types
import numpy as np
import nvidia.dali.fn as fn
import gc

batch_size = 2000
test_data_shape = [100, 200, 3]
iter = 0
limmit = 3
import sys

def get_data():
    global iter
    out = [np.random.randint(0, 255, size = test_data_shape, dtype = np.uint8) for _ in range(batch_size)]
    if iter == limmit - 1:
        out = [o.astype(dtype=np.float64) for o in out]
    iter += 1
    iter %= limmit
    return out

def test(input_layout = "HWC", get_data = get_data):
    pipe = Pipeline(batch_size=batch_size, num_threads=4, device_id=0)
    data = fn.external_source(source = get_data, layout = input_layout)
    processed = fn.rotate(data.gpu(), angle = 25, device="gpu")
    pipe.set_outputs(processed)
    pipe.build()
    try:
        for _ in range(limmit + 1):
            pipe.run()
            print("iter")
    except:
        print("stop")
        del pipe
        gc.collect()
    print("after stop")
    while 1:
        pass

test()
```

**Comment by cceyda** [comment]
Your example works but when I use `pipe.feed_input()` the "after stop" never prints, am I using feed_input wrong or bug or expected?

```py
import nvidia.dali as dali
from nvidia.dali.pipeline import Pipeline
import nvidia.dali.ops as ops
import nvidia.dali.types as types
import numpy as np
import nvidia.dali.fn as fn
import gc

batch_size = 2000
test_data_shape = [100, 200, 3]
iter = 0
limmit = 3
import sys

def get_data():
    global iter
    out = [np.random.randint(0, 255, size = test_data_shape, dtype = np.uint8) for _ in range(batch_size)]
    if iter == limmit - 1:
        out = [o.astype(dtype=np.float64) for o in out]
    iter += 1
    iter %= limmit
    return out

def test(input_layout = "HWC", get_data = get_data):
    pipe = Pipeline(batch_size=batch_size, num_threads=4, device_id=0)
    data = fn.external_source()
    processed = fn.rotate(data.gpu(), angle = 25, device="gpu")
    pipe.set_outputs(processed)
    pipe.build()
    print("made pipe")
    try:
        for _ in range(limmit + 1):
            pipe.feed_input(data, get_data())
            pipe.run()
            print("iter")
    except:
        print("stop")
        del pipe
        gc.collect()
        print("mid stop")
        
    print("after stop")
    while 1:
        pass
    
test()

```
Thank you

**Comment by JanuszL** [comment]
DALI by default prefetches ahead batches to keep the pipeline busy. If you are using `feed_input` method you should feed the pipeline ahead as well. In your case pipeline cannot be deleted as the `external_source` waits for the last batch of data. It happens that way as the exception is thrown in the GPU operator while the CPU one (`external_source`) works in parallel and is not aware of the pipeline error.
I would recommend not to use `feed_input` directly with the functional API as it is up to the user to know when to call it, with the classical API DALI know when to call `iter_setup` Or just provide the data generator as a source argument to the `external_source`.
If you must follow this path this code should work:
```
import nvidia.dali as dali
from nvidia.dali.pipeline import Pipeline
import nvidia.dali.ops as ops
import nvidia.dali.types as types
import numpy as np
import nvidia.dali.fn as fn
import gc

batch_size = 2000
test_data_shape = [100, 200, 3]
iter = 0
prefetch = 2
limmit = 3
import sys

def get_data():
    global iter
    out = [np.random.randint(0, 255, size = test_data_shape, dtype = np.uint8) for _ in range(batch_size)]
    if iter == limmit - 1:
        out = [o.astype(dtype=np.float64) for o in out]
    iter += 1
    iter %= limmit
    return out

def test(input_layout = "HWC", get_data = get_data):
    pipe = Pipeline(batch_size=batch_size, num_threads=4, device_id=0, prefetch_queue_depth=prefetch)
    data = fn.external_source()
    processed = fn.rotate(data.gpu(), angle = 25, device="gpu")
    pipe.set_outputs(processed)
    pipe.build()
    print("made pipe")
    try:
        # prefetch
        for _ in range(prefetch - 1):
            pipe.feed_input(data, get_data())
        for _ in range(limmit + 1):
            pipe.feed_input(data, get_data())
            pipe.run()
            print("iter")
    except:
        print("stop")
        del pipe
        gc.collect()
        print("mid stop")

    print("after stop")
    while 1:
        pass

test()```

**Comment by cceyda** [comment]
@JanuszL with the help of your suggestions I have put together a python lib https://github.com/cceyda/image-checker for scanning folders/files for corrupted images 🥳  You can now easily get a list of problematic files that would otherwise cause an error on a DALI pipeline. (And remove/move/fix them at your own discretion)
It should be helpful in issues like: #1435

**Comment by JanuszL** [comment]
Thanks for your code. We will discuss how this is alignment with our codebase and how it can be utilized.
Maybe you can just make a PR and add it to the tools available in DALI?
