### ISSUE TITLE
Custom augmentation. How can I write a mean augmentation?

### ISSUE THREAD

**Issue by bamfpga** [NVIDIA/DALI#2383]
Hello,
I'd like to create a custom augmentation like this:  input/mean(input)
I started with the mean computation. Is there a way I can achieve this by combining cupy.ElementWiseKernel and cupy.ReductionKernel. Is there a simpler way to achieve this or do I have to write some cuda kernels like this: https://github.com/NVIDIA/DALI/blob/master/dali/kernels/reduce/mean_gpu.cu? Do I stand a chance? 
Thanks!

**Comment by JanuszL** [comment]
Hi,
This sounds like normalization. Please check [this tutorial](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/normalize.html) how to do that.

**Comment by bamfpga** [comment]
HI, I don't want to divide by standard deviation, but the mean. Can I compute the mean separately somehow?

**Comment by JanuszL** [comment]
Oh, I missed that you want to divide, not subtract. We are developing a mean reduce operator and then you can just divide the input by the result of the mean operator. We will get back to you when the relevant operator is ready.
@awolant - FYI

**Comment by JanuszL** [comment]
This PR should do what you are asking for. https://github.com/NVIDIA/DALI/pull/2395. Please check the nightly DALI build after it is merged.

**Comment by JanuszL** [comment]
@bamfpga - https://github.com/NVIDIA/DALI/pull/2395 just have been merged. Can you check the most recent nightly build that follows it to see if that works for you?

**Comment by bamfpga** [comment]
That's great! Thank you very much!

**Comment by JanuszL** [comment]
DALI 0.28 has been released, it should address this issue.

**Comment by bamfpga** [comment]
Great news. thank you!
