### ISSUE TITLE
Can DALI read videos with different frames radio?

### ISSUE THREAD

**Issue by seeyouagain111** [NVIDIA/DALI#2384]

**Comment by JanuszL** [comment]
Hi,
It should work. We have [a test](https://github.com/NVIDIA/DALI/blob/master/dali/operators/reader/video_reader_op_test.cc#L515) for that running over [this test data](https://github.com/NVIDIA/DALI_extra/tree/master/db/video/multiple_framerate).

**Comment by seeyouagain111** [comment]
thanks for your reply，and there is another question。I want use pyav to load  video dataset(.mp4) ，can i turn this tensor data to DALI data? so that i can use DALI operator such as resize、cope。which operator should i use？

**Comment by seeyouagain111** [comment]
> Hi,
> It should work. We have [a test](https://github.com/NVIDIA/DALI/blob/master/dali/operators/reader/video_reader_op_test.cc#L515) for that running over [this test data](https://github.com/NVIDIA/DALI_extra/tree/master/db/video/multiple_framerate).

thanks for your reply，and there is another question。I want use pyav to load video dataset(.mp4) ，can i turn this tensor data to DALI data? so that i can use DALI operator such as resize、cope。which operator should i use？

**Comment by JanuszL** [comment]
Hi,
I haven't used pyav, but as long as it can return numpy or cupy arrays you can use the ExternalSource operator to load the data from it, like in [this example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/external_input.html).

**Comment by seeyouagain111** [comment]
> Hi,
> I haven't used pyav, but as long as it can return numpy or cupy arrays you can use the ExternalSource operator to load the data from it, like in [this example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/external_input.html).

hello，i use ExternalSource to load my video ，i want use ExternalSource to output three nums_outs, fisrt is 32fps video，second is 8fps video，thirs is  label。but i got the error:

RuntimeError: [/opt/dali/dali/pipeline/pipeline.h:175] Cannot find __ExternalSource_0 tensor, it doesn't exists or was pruned as unused one.

how can i fix it?

**Comment by JanuszL** [comment]
Hi,
It seems that one of the ExternalSource outputs is neither used by any other operator nor is the pipeline output. In such case, DALI removes such graph edge but the ExternalSource still tries to feed it with the data. Please use all ExternalSource outputs.

**Comment by seeyouagain111** [comment]
> Hi,
> It seems that one of the ExternalSource outputs is neither used by any other operator nor is the pipeline output. In such case, DALI removes such graph edge but the ExternalSource still tries to feed it with the data. Please use all ExternalSource outputs.

this is useful ，thanks！

**Comment by seeyouagain111** [comment]
> Hi,
> It seems that one of the ExternalSource outputs is neither used by any other operator nor is the pipeline output. In such case, DALI removes such graph edge but the ExternalSource still tries to feed it with the data. Please use all ExternalSource outputs.

i want DALI dataloader output [slow_pathway,fast_pathway],labels.so i use pythonfunction ,code is
def merge(video1,video2):
        list=[]
        list.append(video2)
        list.append(video1)
        return list

class ExternalSourcePipeline(Pipeline):
        def __init__(self,batch_size,eii,num_threads,device_id):
            super(ExternalSourcePipeline,self).__init__(batch_size,
                                          num_threads,
                                          device_id,
                                          exec_async=False,
                                          exec_pipelined=False,
                                          seed=12)
              .....
             ......
             self.merge=ops.PythonFunction(device="gpu",function=merge,num_outputs=1)
       def define_graph(self):
             ....
            result=self.merge(slow_pathway,fast_pathway)
            return result,labels

slow_pathway shape is [2,32,3,224,244],fast_pathway shape is [2,8,3,224,224].but, the result is not a list and its shape is [2,8,3,224,224]。i dont know why，and how can i get a list append slow_pathway and fast_pathway?

**Comment by seeyouagain111** [comment]
> > Hi,
> > It seems that one of the ExternalSource outputs is neither used by any other operator nor is the pipeline output. In such case, DALI removes such graph edge but the ExternalSource still tries to feed it with the data. Please use all ExternalSource outputs.
> 
> this is useful ，thanks！

i want use multigpus when use externalSource loading data, can it achieve?

**Comment by JanuszL** [comment]
> i want use multigpus when use externalSource loading data, can it achieve?

When you are using the ExternalSource it is up to you to do the sharding and make sure that each DALI instance reads from the non-overlapping set of data. What you can do is:
- preshuffle the whole data set with the fixed seed in each DALI process instance
- spit it into a number of DALI pipeline instances equal parts/shards
- make each ExternalSource read from the separate shard

**Comment by seeyouagain111** [comment]
> > i want use multigpus when use externalSource loading data, can it achieve?
> 
> When you are using the ExternalSource it is up to you to do the sharding and make sure that each DALI instance reads from the non-overlapping set of data. What you can do is:
> 
> * preshuffle the whole data set with the fixed seed in each DALI process instance
> * spit it into a number of DALI pipeline instances equal parts/shards
> * make each ExternalSource read from the separate shard

thanks for your advice，i use DALI successfully on my slowfast demo.but the speed isn't faster than before.I use DALI with two pythonfuction operator. If these two operetor slow down speed?

**Comment by JanuszL** [comment]
> i use DALI successfully on my slowfast demo.but the speed isn't faster than before.I use DALI with two pythonfuction operator

Python functions are not utilizing multithreading and asynchronous, pipelined execution. It is mostly meant for prototyping and debugging, so moderate performance is expected. Please check the relevant notice in the [documentation](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.ops.PythonFunction).

**Comment by seeyouagain111** [comment]
> > i use DALI successfully on my slowfast demo.but the speed isn't faster than before.I use DALI with two pythonfuction operator
> 
> Python functions are not utilizing multithreading and asynchronous, pipelined execution. It is mostly meant for prototyping and debugging, so moderate performance is expected. Please check the relevant notice in the [documentation](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.ops.PythonFunction).

i found a interesting thing.i used DALI's VideoReader to load  videos . When i use DALi , load and augment   videos cost 0.8s oen batch, forward and backward cost 0.8s.when i use pytorch to load videos in cpu, load and augment  videos cost 1.4s one batch ,forward and backward cost 0.2s. so ,DALI  videoreader operator exactly speed up loading data, but it cost GPU-Util,so that slow down  training speed.in total,DALI do not speed up the network when training.

**Comment by seeyouagain111** [comment]
> > > i use DALI successfully on my slowfast demo.but the speed isn't faster than before.I use DALI with two pythonfuction operator
> > 
> > 
> > Python functions are not utilizing multithreading and asynchronous, pipelined execution. It is mostly meant for prototyping and debugging, so moderate performance is expected. Please check the relevant notice in the [documentation](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.ops.PythonFunction).
> 
> i found a interesting thing.i used DALI's VideoReader to load videos . When i use DALi , load and augment videos cost 0.8s one batch, forward and backward cost 0.8s.when i use pytorch to load videos in cpu, load and augment videos cost 1.4s one batch ,forward and backward cost 0.2s. so ,DALI videoreader operator exactly speed up loading data, but it cost GPU-Util,so that slow down training speed.in total,DALI do not speed up the network when training.


i found the reason above . i used pythonfunction . This lead to high GPU-Util.i remove my pythonfuction. After using DALI,forward and backward cost 0.2s

**Comment by JanuszL** [comment]
I'm happy that it works for you.
