### ISSUE TITLE
Add tensor layout information for ops.PythonFunction?

### ISSUE THREAD

**Issue by ruiyuanlu** [NVIDIA/DALI#2387]
Hi, thanks for such an outstanding framework. I met the same issue just like [issue_2116](https://github.com/NVIDIA/DALI/issues/2116#issue-657299188). Yet differently, in my case, the `Assertion Error` is triggered by a self-defined python function before the `ops.CropMirrorNormalize`.

Thus, what about adding a parameter list in `ops.PythonFuction.__init__()` to let users describe the layout of each output tensor?

```python
Error when executing GPU operator CropMirrorNormalize encountered:
[/opt/dali/dali/operators/image/crop/crop_mirror_normalize.h:170] Assert on "ImageLayoutInfo::IsImage(input_layout_)" failed: Unsupported layout: '' for input 0 '__PythonFunction_3'
```

For example:

Suppose we have a python function that has 1 input and 2 outputs, we can describe the layout of out1 and out2 separately as follows:

```python
def my_py_func(img):
    # processing images here
    return [out1, out2]

import nvidia.dali.ops as ops
myop = ops.PythonFunction(device='gpu', function=my_py_func, num_outputs=2, output_layout=["CHW", "HWC"])
```

Looking forward to your reply. Thanks anyway.

**Comment by banasraf** [comment]
Hi @ruiyuanlu!
I agree that such argument for the `PythonFunction` would be helpful. I've added a task for that to our backlog. It's hard to say when we could approach this so we're open for external contributions. 

A workaround for this is to use the `Reshape` operator to set the layouts.
```python
# (....)
   myop = ops.PythonFunction(device='gpu', function=my_py_func, num_outputs=2)
   set_chw = ops.Reshape(layout="CHW")
   set_hwc = ops.Reshape(layout="HWC")

def define_graph(self):
   # (...)
   out1, out2 = self.myop(input)
   out1 = self.set_chw(out1)
   out2 = self.set_hwc(out2)
```

**Comment by banasraf** [comment]
Hello @ruiyuanlu!
We have just merged a PR that adds the `output_layouts` argument to the `PythonFunction` Operator. 
The usage is as straightforward as you described:
```python
myop = ops.PythonFunction(device='gpu', function=my_py_func, num_outputs=2, output_layouts=["CHW", "HWC"])
```

Thanks for signalizing the issue and proposing a solution!

**Comment by JanuszL** [comment]
0.29 has been released and should address this issue.
