### ISSUE TITLE
Run DALI without CUDA

### ISSUE THREAD

**Issue by macsmy** [NVIDIA/DALI#2396]
Hello!
I would like to ask, if there is any possibility to run DALI without CUDA? As i read in release 2.6 description, there should be one. Unfortunately, I am still getting following error: 'CUDA runtime api error "no CUDA-capable device is detected"'.

**Comment by JanuszL** [comment]
Hi,
Please use `None` as a `device_id` value according to [the documentation](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/pipeline.html#nvidia.dali.pipeline.Pipeline). You can also check [cpu only test](https://github.com/NVIDIA/DALI/blob/master/dali/test/python/test_dali_cpu_only.py).

**Comment by macsmy** [comment]
thank You! indeed, no-cuda mode is enabled and pipeline is properly build. however, during run() i am still getting cuda-oriented error:
'RuntimeError: Critical error in pipeline:
Error when executing CPU operator ArithmeticGenericOp, instance name: "__ArithmeticGenericOp_15", encountered:
CUDA runtime API error cudaErrorNoDevice (38):
no CUDA-capable device is detected
Current pipeline object is no longer valid.'

**Comment by JanuszL** [comment]
Could you provide a minimal and self contained reproduction code so we can run it on our side?

**Comment by mchalecki** [comment]
Did you install with pip command or install from source ? 

By the way. How can one build from source without cuda ? I dont see an option in cmake to build without nvcc. Or are there prebuild packages cpu only ?

**Comment by JanuszL** [comment]
> By the way. How can one build from source without cuda ? I dont see an option in cmake to build without nvcc. Or are there prebuild packages cpu only ?

It is not possible to build without CUDA as DALI is coupled with it in the very roots, and I don't think it will be ever possible.

**Comment by JanuszL** [comment]
I have managed to reproduce the issue, https://github.com/NVIDIA/DALI/pull/2400 should fix that.

**Comment by JanuszL** [comment]
DALI 0.28 has been released, it should address this issue.
