### ISSUE TITLE
Can I crop image out_of_bounds using nvidia.dali.ops.Crop ?

### ISSUE THREAD

**Issue by NizhnikovaVS-voir** [NVIDIA/DALI#2399]
Hello,
Seems like out_of_bounds policy will not work properly.
<img width="386" alt="Screenshot 2020-10-26 at 14 10 30" src="https://user-images.githubusercontent.com/67599152/97165589-02d4d280-1795-11eb-9cda-557d66c9e341.png">

I init  nvidia.dali.ops.Crop(out_of_bounds_policy="pad")
and set up params: crop_pos_x, crop_pos_y, crop_w, crop_h
according to documentation:
 
<img width="510" alt="Screenshot 2020-10-26 at 14 11 40" src="https://user-images.githubusercontent.com/67599152/97165712-2d269000-1795-11eb-8006-cc5d0eb88103.png">

so, in my case for bound_box=[x_left, y_top, crop_w, crop_h]
crop_pos_x = x_left/(W_image-crop_w)
crop_pos_y = y_top/(H_image-crop_h)
but with condition 0<crop_pos_x<=1, it's impossible to crop area ouside of image
because to satisfy this condition:
1) x_left must be positive
2) (W_image - w_crop) must be positive
3) x_left must be <= (W_image - w_crop)

These conditions forbid the box to be outside of the image.

This is a bug? or I using this Crop wrong?

Thanks!

**Comment by NizhnikovaVS-voir** [comment]
Great Idea, works great! Thank you!

**Comment by jantonguirao** [comment]
Happy to help. I'll close this issue. If you have more issues please reopen or create a new one.
