### ISSUE TITLE
DALI could not recognize relative path of image

### ISSUE THREAD

**Issue by KleinXin** [NVIDIA/DALI#2401]
I have a trainning list of images with labels in the format

image1.jpg 10
 image2.jpg 33
 image3.jpg 95
 ...

Name of each image and its label is separated by a space. When I change the path of images to absolute path which looks like

'/data/home/KleinXin/images/image1.jpg 10
/data/home/KleinXin/images/image2.jpg 33
/data/home/KleinXin/images/image3.jpg 95
...'

Then give this list to FileReadPipeline, the code is

`trainingPipes = FileReadPipeline(batch_size = args.batch_size, 
                                     num_threads = args.workers, 
                                     device_id = 0,
                                     image_lst = trainImg_lst,
                                     randomFlip = True)`

The trainning works fine.

However, when the paths of images in the list is in relative mode which looks like

'./images/image1.jpg 10
./images/image2.jpg 33
./images/image3.jpg 95
...'

The trainning process gives an error that says 

'RuntimeError: Critical error in pipeline: [/opt/dali/dali/util/local_file.cc:101] File mapping failed: /./images/image1.jpg'

Why a slash appears before the relative path of the image?

I am using dali version 0.13.0 which seems too old. Can newer version solve this problem?

**Comment by klecki** [comment]
Hi,
we have a PR that improves both the documentation and flexibility of the readers in regards to the file_list and related arguments: #2389 

For the current version of DALI, you need to specify the `file_root` parameter - the contents of file list will be relative to the path you provide there.

If you want it to be current working directory, use: `file_root="."`.

**Comment by KleinXin** [comment]
> Hi,
> we have a PR that improves both the documentation and flexibility of the readers in regards to the file_list and related arguments: #2389
> 
> For the current version of DALI, you need to specify the `file_root` parameter - the contents of file list will be relative to the path you provide there.
> 
> If you want it to be current working directory, use: `file_root="."`.

Does version 0.13.0 provide this option?

**Comment by KleinXin** [comment]
> Hi,
> we have a PR that improves both the documentation and flexibility of the readers in regards to the file_list and related arguments: #2389
> 
> For the current version of DALI, you need to specify the `file_root` parameter - the contents of file list will be relative to the path you provide there.
> 
> If you want it to be current working directory, use: `file_root="."`.

thx! I will try to use newer version in the future.

**Comment by JanuszL** [comment]
I would give it a try and see if that helps. I possible please update to the most recent DALI version. 0.13 is over a year old.

**Comment by KleinXin** [comment]
> I would give it a try and see if that helps. I possible please update to the most recent DALI version. 0.13 is over a year old.

thx! But do not waste so much time because my problem is solved by using absolute paths. 
Upgrading DALI to newer version is on my agenda now.
