### ISSUE TITLE
Enhancement: Add frame padding for video reader

### ISSUE THREAD

**Issue by Timen** [NVIDIA/DALI#2404]
I'm using the VideoReaderResize for my trainings, and while it performs excellent there is a feature that I'm missing that I'm thinking about adding. Namely I noticed that a number of videos I want to use during training aren't long enough to fill a whole sequence. In this case I believe the videoreader is simply not adding them to the list of examples. 

What I would prefer is that I could add padding (possibly in a randomized type) to fill out the frames to create a full sequence. Dropping an example that is 29 frames when your sequence length is 32 is a bit of waste. I would actually be happy to look into/implement something myself but I don't really know where to get started and if this is possible to do with reasonable performance.

Open for suggestions!

**Comment by JanuszL** [comment]
Hi,

DALI assumes that all read sequences are the same length. What I would do is:
- add info about requested sequence length [here](https://github.com/NVIDIA/DALI/blob/master/dali/operators/reader/loader/video_loader.h#L268)
- use that info [here](https://github.com/NVIDIA/DALI/blob/master/dali/operators/reader/loader/video_loader.cc#L698) and invoke a kernel that would fill the remaining samples with the randomized data, or just leave it as it is if you are fine with any random data there

**Comment by JanuszL** [comment]
Hi @Timen,

You can use `pad_sequences` in [the `video reader` oeprator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.readers.video.html) to achieve what you want.
