### ISSUE TITLE
multiple num_shards + single GPU

### ISSUE THREAD

**Issue by zhiheng-ldj** [NVIDIA/DALI#2418]
Thanks for your help in advance!

I have a question about ops.FileReader. If I set 16 to 'num_shards' in single GPU environment, the speed of loading images will rise dramatically. Does it seem normal?

Thanks for your help sincerely!

**Comment by JanuszL** [comment]
Hi,
Could you clarify your question? Do you mean that increasing `num_shards` makes every batch to be produced faster, or each epoch is shorted?
If it is the second case then it is expected as increasing the number of shards makes the slice of the data set that each reader work on smaller. Also please check [this example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/multigpu.html).
If you can provide a simple, self-contained reproduction we can run on our side that illustrates your observation it would help us a lot.

**Comment by zhiheng-ldj** [comment]
Hi,

I mean increasing num_shards in ops.FileReader makes every batch to be loaded faster. Or could you make me sense what will happen if num_shards != num of gpu?

Thanks!

**Comment by JanuszL** [comment]
> I mean increasing num_shards in ops.FileReader makes every batch to be loaded faster. 

We would need a simple, self-contained reproduction we can run on our side to tell you more.

> Or could you make me sense what will happen if num_shards != num of gpu

In most use cases it doesn't make any sense, as you would see only a part of the data set each epoch.

**Comment by zhiheng-ldj** [comment]
Ok thanks, I will try!
