### ISSUE TITLE
failed: Encoded image has ambiguous format

### ISSUE THREAD

**Issue by samra-irshad** [NVIDIA/DALI#2421]
Hi, I am trying to load images by first encoding them from a buffer (np.frombuffer) and then decoding using ops.ImageDecoder. However, it gives me the error of 'failed: Encoded image has ambiguous format'. I have checked the images, they are not broken. any idea why this is happening?

```
RuntimeError: Critical error in pipeline:
Error when executing Mixed operator ImageDecoder encountered:
[/opt/dali/dali/operators/decoder/nvjpeg/decoupled_api/nvjpeg_decoder_decoupled_api.h:532] [/opt/dali/dali/image/image_factory.cc:89] Assert on "CheckIsPNG(encoded_image, length) + CheckIsBMP(encoded_image, length) + CheckIsGIF(encoded_image, length) + CheckIsJPEG(encoded_image, length) + CheckIsTiff(encoded_image, length) + CheckIsPNM(encoded_image, length) + CheckIsJPEG2k(encoded_image, length) == 1" failed: Encoded image has ambiguous format
Stacktrace (11 entries):

```

**Comment by JanuszL** [comment]
@samra-irshad - can you provide a simple self-contained repro that would show your problem? You can use https://github.com/NVIDIA/DALI_extra as a data source for it, so we can run this and debug on our side.

**Comment by samra-irshad** [comment]
Hi thanks I was able to overcome the issue

**Comment by zhiheng-ldj** [comment]
> Hi thanks I was able to overcome the issue

Hi, could you provide your solution please? Thanks! I am facing the same problem with you.

**Comment by leijuzi** [comment]
@samra-irshad Hi , I met the same err too, could you provide your solution please
