### ISSUE TITLE
Dataset API

### ISSUE THREAD

**Issue by bhack** [NVIDIA/DALI#243]
Any plan for an integration with [dataset API](https://www.tensorflow.org/guide/datasets)?

**Comment by JanuszL** [comment]
Hi,
We have not considered moving to this API anytime soon.
But we may reconsider this. Could you tell what benefit from your perspective it would give if we move to dataset API?
Tracked as DALI-308.
Br,
Janusz

**Comment by bhack** [comment]
Mainly in TF is the default ETL and it used also for distribute training. https://www.tensorflow.org/performance/datasets_performance

**Comment by bhack** [comment]
I really don't know how it could fit well I.e. with estimators and distributed training (that it is going do be the default and recommended approach in TF) without involve some Dataset API interaction.

**Comment by bhack** [comment]
Yes probably a good standalone example to feed Estimators could help to disambiguate

**Comment by JanuszL** [comment]
https://github.com/NVIDIA/DALI/pull/251 should be sufficient to understand how to use DALI with TensorFlow.
We think that reworking TensorFlow Op to use Dataset API won't provide much benefit. So for now we will stick with the current implementation.
