### ISSUE TITLE
unable to integrate DALI with model in pytorch

### ISSUE THREAD

**Issue by samra-irshad** [NVIDIA/DALI#2439]
Hi, I have been trying to integrate DALI-based dataloading pipeline to my model in Pytorch. But it does not work. It does not give any error but just gets stuck and no output comes even after 10 minutes. I have checked the DALI pipeline and my code independently, they both are okay but dont work when integrated together. I am pasting the code for DALI-based iterator and model training. 

DALI pipeline and iterator:

```
class ExternalInputIterator(object):
    def __init__(self, batch_size):
        self.dir = ".../dir/"
        root=self.dir
        self.batch_size = batch_size
        self.files=[]
        self.data_set_len = len(self.files)
        self.n = len(self.files)
    
    def __iter__(self):
        self.i = 0
        shuffle(self.files)
        return self

    def __next__(self):
        imgs = []
        labels = []
        if self.i >= self.n:
            raise StopIteration
        for _ in range(self.batch_size):
            img,mask= self.files[self.i]
            img1 = open(img, 'rb')
            imgs.append(np.frombuffer(img1.read(), dtype = np.uint8))

            mask1 = open(mask, 'rb')
            labels.append(np.frombuffer(mask1.read(), dtype = np.uint8))

            self.i = (self.i + 1) % self.n
        return imgs, labels
    @property
    def size(self,):
        return self.data_set_len

    next = __next__

class trainPipeline(Pipeline):
    def __init__(self, batch_size, eii, num_threads, device_id):
        super(trainPipeline, self).__init__(batch_size,
                                      num_threads,
                                      device_id,
                                      seed=12)

        self.source = ops.ExternalSource(source = eii, num_outputs = 2)
        self.decode = ops.ImageDecoder(device = "mixed", output_type = types.GRAY)
        self.flip = ops.Flip(device="gpu", horizontal = 1, vertical=1)
        self.Normalize=ops.CropMirrorNormalize(device="gpu", std=255.0,output_layout='CHW')
        self.external_data = eii
        self.iterator = iter(self.external_data)
        


    def define_graph(self):
        self.images, self.labels = self.source()
        images,labels = self.decode(self.images),self.decode(self.labels)
        images, labels = self.flip(images), self.flip(labels)
        images, labels = self.Normalize(images), self.Normalize(labels)
        return images,labels
 
    def iter_setup(self):
        try:
            (images, labels) = self.iterator.next()
            self.feed_input(self.images, images)
            self.feed_input(self.labels, labels)
        except StopIteration:
            self.iterator = iter(self.external_data)
            raise StopIteration


def iter_pipeline(batch_size):
        eii = ExternalInputIterator(batch_size)
        pipe = trainPipeline(batch_size=batch_size, eii=eii, num_threads=4, device_id = 0)
        pipe.build()
    return pipe


```
Training code:

```
 train_dataset = iter_pipeline(batch_size)
 train_loader = DALIGenericIterator(train_dataset, output_map=["images", "labels"], fill_last_batch=False)
 for epoch in range(start_epoch, args.epochs + 1):
        for i, data in enumerate(train_loader):
              img = data[0]['images']
              mask = data[0]['labels']
              print('img-shape',img.shape)
              print('mask-shape',mask.shape)
             output = net(img)
```

When I run this, it keeps printing the shape of images and masks but does not feed the input to model and I dont see any output even after 10 minutes.

**Comment by JanuszL** [comment]
Hi,
If you see the output from:
```
print('img-shape',img.shape)
print('mask-shape',mask.shape)
```
it means that DALI does what it suppose to. Can you tell me how you checked your model code independently? Have you tried to add debug prints in the middle of your model?

**Comment by samra-irshad** [comment]
> Hi,
> If you see the output from:
> 
> ```
> print('img-shape',img.shape)
> print('mask-shape',mask.shape)
> ```
> 
> it means that DALI does what it suppose to. Can you tell me how you checked your model code independently? Have you tried to add debug prints in the middle of your model?

My code contains logging at several points. I ran my code using naive dataloader of pytorch, its working fine and I see the training progress (per-batch error and epoch error). But when I try to integrate DALI, I see no output even after 15 minutes.

**Comment by samra-irshad** [comment]
The odd thing is the program outputs the size of inputs consecutively for whole dataset, what I expected was to see the shapes of input for a specific batch-size (for example, it should only print shapes of four inputs (corresponding to batch size: 4)) but it shows input-shapes for (complete dataset). So I think it gets stuck in iterating over whole dataset at once and the input never goes to model.

**Comment by JanuszL** [comment]
Not knowing your code, not having any self-contained repro we could run on our side I cannot tell much.

> what I expected was to see the shapes of input for a specific batch-size (for example, it should only print shapes of four inputs (corresponding to batch size: 4)) but it shows input-shapes for (complete dataset). So I think it gets stuck in iterating over whole dataset at once and the input never goes to model.

I think this is not related to DALI then. You print the shapes that DALI has returned. So if you can print it is not transferred to the model itself it is not DALI fault.
Please double check this code, `img` is a PyTorch tensor and if you can examine it you should be able to pass it to the model:
```
              img = data[0]['images']
              mask = data[0]['labels']
              print('img-shape',img.shape)
              print('mask-shape',mask.shape)
             output = net(img)
```

**Comment by samra-irshad** [comment]
I think the iterator is causing problems. Can I read the images and masks separately using ops.FileReader?

**Comment by JanuszL** [comment]
You can provide [a list of files to the FileReader](https://docs.nvidia.com/deeplearning/dali/master-user-guide/docs/supported_ops.html#nvidia.dali.ops.FileReader) directly from python using [the latest nighty DALI build](https://docs.nvidia.com/deeplearning/dali/master-user-guide/docs/installation.html#nightly-builds). If you set the same seed to both readers and keep the file list consistent between the readers you should be able to read mask and files in a synchronized way.
Could you tell why do you suspect the iterator?

**Comment by samra-irshad** [comment]
1. I have tried this and got error: ```
RuntimeError: Critical error when building pipeline:
Error when constructing operator: FileReader encountered:
[/opt/dali/dali/operators/reader/loader/file_label_loader.h:133] Assert on "s.is_open()" failed: Cannot open: /Dataset/fold2/img_list.txt
```

2. I am running it on remote compute node, I can see verify the output sizes from model through login node but I cannot see any loss etc due to small memory on login node. The iterator based dataloader does not do anything further when ran on remote node (does not show any output) and the program is just stuck. So I am trying some other data reader.

**Comment by JanuszL** [comment]
Ad 1, are you sure that the mentioned file exits and can be accessed by DALI. Also, I was thinking about using `files` FileReader argument.

**Comment by samra-irshad** [comment]
> Ad 1, are you sure that the mentioned file exits and can be accessed by DALI. Also, I was thinking about using `files` FileReader argument.

I managed to address the issue. My program is working now using `ops.FileReader` but the issue is the data pipeline never stops feeding data to the model. Number of batches being fed to the model in one epoch exceed far than they should be. So it never goes to second epoch and remains feeding the model with inputs. Any idea what could be the issue?

**Comment by samra-irshad** [comment]
```
Epoch[1], Batch [23363], total loss is 0.801585
Epoch[1], Batch [23364], total loss is 0.777242
Epoch[1], Batch [23365], total loss is 0.800195
Epoch[1], Batch [23366], total loss is 0.800102
Epoch[1], Batch [23367], total loss is 0.800823
Epoch[1], Batch [23368], total loss is 0.800080
Epoch[1], Batch [23369], total loss is 0.783077
```
It should have produced only 400 batches, but as shown here, it's just continuing

**Comment by JanuszL** [comment]
FileReader is an infinite data source. One of the responsibilities of the DALIGenericIterator is to count the number of batches it should return and stop when needed.

**Comment by samra-irshad** [comment]
Yeah I forgot to assign size parameter in DALIGenericIterator. By the way is there any size attribute of class nvidia.dali.pipeline.Pipeline that we can use directly to indicate the size of dataset (when using `ops.FileReader`) or we have to specify it explicitly using `len` when creating an iterator?

**Comment by samra-irshad** [comment]
Hi I was able to ran the code. However, the code does not iterate over the complete dataset within one epoch. I am giving the size of pipeline as `len(dataset)/batchsize` in `Class nvidia.dali.plugin.pytorch.DALIGenericIterator`.

**Comment by JanuszL** [comment]
If you really want to set the size explicitly you can use the data returned by the pipeline from []the `reader_meta` function (https://docs.nvidia.com/deeplearning/dali/user-guide/docs/pipeline.html#nvidia.dali.pipeline.Pipeline.reader_meta). What I recommend it to pass the reader name to the iterator directly like in [this example](https://github.com/NVIDIA/DALI/blob/1073e9b650e278a19db184016b5cc173c6c40a95/docs/examples/use_cases/pytorch/resnet50/main.py):
```
def define_graph(self):
        self.jpegs, self.labels = self.input(name="Reader")
(...)
train_loader = DALIClassificationIterator(pipe, reader_name="Reader", fill_last_batch=False)
```
The iterator itself would extract necessary information. You can read more about this in [this documentation section](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/advanced_topics.html#sharding).

**Comment by samra-irshad** [comment]
Thanks for your suggestions. I was able to overcome the error using `ops.FileReader`, but the results are different from what I got by using original pytorch's dataloader. I am trying to use a different data-reader (External-source, if that can help). But I got the error: ```
in _prepare_graph
    self._default_cuda_stream_priority)
RuntimeError: [/opt/dali/dali/pipeline/pipeline.cc:78] Assert on "res" failed: Error parsing serialized pipeline.
```
Any hint where the problem is coming from ?

**Comment by JanuszL** [comment]
>  I am trying to use a different data-reader (External-source, if that can help). But I got the error:

Could you provide a minimal repro for that? How do you instantiate the pipeline?

**Comment by samra-irshad** [comment]
Iterator:

```
class ExternalInputIterator(object):
    def __init__(self, batch_size,mode, root):
        self.batch_size = batch_size
        self.files=[]
         
        if mode == 'train':
            train_img_path = os.path.join(root, 'train', 'Img')
            train_mask_path = os.path.join(root, 'train', 'GT')

            images = os.listdir(train_img_path)
            labels = os.listdir(train_mask_path)

            images.sort()
            labels.sort()

            for it_im, it_gt in zip(images, labels):
                item = (os.path.join(train_img_path, it_im), os.path.join(train_mask_path, it_gt))
                self.files.append(item)
        self.data_set_len = len(self.files)
        self.n = len(self.files)
    


    def __iter__(self):
        self.i = 0
        shuffle(self.files)
        return self

    def __next__(self):
        imgs = []
        labels = []
        if self.i >= self.n:
            raise StopIteration
        for _ in range(self.batch_size):
            img,mask= self.files[self.i]
            img1 = open(img, 'rb')
            imgs.append(np.frombuffer(img1.read(), dtype = np.uint8))

            mask1 = open(mask, 'rb')
            labels.append(np.frombuffer(mask1.read(), dtype = np.uint8))

            self.i = (self.i + 1) % self.n
        return imgs, labels
    @property
    def size(self,):
        return self.data_set_len

    next = __next__
```

Pipeline:

```
class trainPipeline(Pipeline):
    def __init__(self, batch_size, eii, num_threads, device_id):
        super(trainPipeline, self).__init__(batch_size,
                                      num_threads,
                                      device_id,
                                      seed=12)

        self.source = ops.ExternalSource(source = eii, num_outputs = 2)
        self.decode = ops.ImageDecoder(device = "mixed", output_type = types.GRAY)
        self.flip = ops.Flip(device="gpu", horizontal = 1, vertical=1)
        #self.rotate = ops.Rotate(device="gpu",angle=30,interp_type=types.INTERP_NN, keep_size=True, fill_value=0.0)
        self.Normalize=ops.CropMirrorNormalize(device="gpu", std=255.0,output_layout='CHW')
        #self.onehot = ops.OneHot(num_classes=5)
        self.external_data = eii
        self.iterator = iter(self.external_data)
        


    def define_graph(self):
        self.images, self.labels = self.source(name="Reader")
        images,labels = self.decode(self.images),self.decode(self.labels)
        images, labels = self.flip(images), self.flip(labels)
        #images, labels = self.rotate(images), self.rotate(labels)
        images, labels = self.Normalize(images), self.Normalize(labels)
        #labels = self.onehot(labels)
        return images,labels

    def iter_setup(self):
        try:
            (images, labels) = self.iterator.next()
            self.feed_input(self.images, images)
            self.feed_input(self.labels, labels)
        except StopIteration:
            self.iterator = iter(self.external_data)
            raise StopIteration
```
pipeline initializing:
```
def iter_pipeline(mode, batch_size, root):
    eii = ExternalInputIterator(batch_size,'train', root)
    pipe = trainPipeline(batch_size=batch_size, eii=eii, num_threads=4, device_id = 0)
    pipe.build()
    return pipe
```
data=num_of_samples
train_dataset = iter_pipeline(batch_size, 'train', data_path)
train_loader = DALIGenericIterator(train_dataset, size=len(data),output_map=["images", "labels"])

Error:
`RuntimeError: [/opt/dali/dali/pipeline/pipeline.cc:78] Assert on "res" failed: Error parsing serialized pipeline.
`

**Comment by JanuszL** [comment]
You have an error in the API usage:
```
--  iter_pipeline(batch_size, 'train', data_path)
++   iter_pipeline( 'train', batch_size, data_path)
```
So you are passing a string as a batch size to DALI and that confuses the DALI backend.

**Comment by samra-irshad** [comment]
Thanks. I tried with both ops.FileReader and External_iterator. The results for both of these readers are same but different from pytorch's native data_loader. Any thoughts?

**Comment by JanuszL** [comment]
> different from pytorch's native data_loader

It is a very vague description. What do you mean by different? Functionally different? Not bit-exact? Which operation is different?

**Comment by samra-irshad** [comment]
Sorry, I described it in vague terms. I trained my image segmentation model using two ways; (a). pytorch native data-loader, (b). DALI. The training loss that I see in both cases is different. The loss corresponding to the model that I train using pytorch native data-loader starts from a much lower value as compared to the model trained using DALI data-loader. So, what I see is quite a difference between training losses between two models after a specific number of epochs.

**Comment by samra-irshad** [comment]
Another thing I am curious to know is when I use native pytorch loader, I explicitly place the input tensor on GPU via `.to(device)`, however, I did not do it for DALI (I assumed it automatically places the tensors on GPU, because I made the data-augmentation pipeline to operate on GPU). My question is when DALI operates on data inside `Pipeline` and `define_graph`, does it unload the data from GPU and we need to place the data explicitly to GPU or it does not off-load? I checked the type of input-tensors returned by DALI, they are `torch.float32` unlike `torch.cuda.floattensor` .

**Comment by samra-irshad** [comment]
Moreover I dont see if DALI has caused any acceleration in model's training speed. I am seeing the same amount of time spent per epoch during training for pytorch data-loader and DALI.

**Comment by JanuszL** [comment]
Hi @samra-irshad ,
ExternalSource is not the most performant way to load the data into DALI. Another thing to consider is if your training speed is capped by the DataLoading. I recommend checking [this blog post](https://developer.nvidia.com/blog/case-study-resnet50-dali/) to learn if you would see any difference if the data processing was free.

**Comment by JanuszL** [comment]
Hi,

The most recent improvements of [the `external_source` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.external_source) make it parallel to the training and scales with the number of CPUs. Please check `parallel` and `prefetch_queue_depth` options.
