### ISSUE TITLE
Multi-gpu Support for Pytorch Frame

### ISSUE THREAD

**Issue by zhiheng-ldj** [NVIDIA/DALI#2446]
Hi,

Thanks for your kindly recent helps!

I am confused about how to support multi-gpu training in Pytorch. I have read the documentation https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/frameworks/pytorch/pytorch-basic_example.html but I am still confused that how to implement the frame:

If I have N gpus, then I will have N pipes needing building and running and N dali_iters. However, I can have only one global data_iter in training script. Could you help me about integrating these dali_iters into one global iter (dataloader)?

Thanks for your help!

**Comment by JanuszL** [comment]
Hi,
The recommended way to run multi-GPU training is Distributed Data Parallel, you can read more about [it here](https://pytorch.org/tutorials/intermediate/ddp_tutorial.html). If you really must you can still use Data Parallel strategy with DALI.
Just create as many pipelines as you have GPUs (remember to set a unique GPU id to each pipeline). Then pass a list of pipelines to the iterator. Iterator would return a list of outputs, where each element on the list corresponds to a separate pipeline.
The approach showed in [this MXNet](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/use_cases/mxnet/mxnet-resnet50.html) example applies to PyTorch as well.
