### ISSUE TITLE
CUDA driver API error <unknown error> (2422081744)

### ISSUE THREAD

**Issue by LcenArthas** [NVIDIA/DALI#2456]
Hi, I had a strange problem running a video demo. The demo is in the 

[https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/sequence_processing/video/video_reader_simple_example.html](url)

```
class VideoPipe(Pipeline):
    def __init__(self, batch_size, num_threads, device_id, data, shuffle):
        super(VideoPipe, self).__init__(batch_size, num_threads, device_id, seed=16)
        self.input = ops.VideoReader(device="gpu", filenames=data, sequence_length=sequence_length,
                                     shard_id=0, num_shards=1,
                                     random_shuffle=shuffle, initial_fill=initial_prefetch_size)
    def define_graph(self):
        output = self.input(name="Reader")
        return output

pipe = VideoPipe(batch_size=batch_size, num_threads=2, device_id=0, data=video_files, shuffle=shuffle)
pipe.build()
for i in range(n_iter):
    pipe_out = pipe.run()
    sequences_out = pipe_out[0].as_cpu().as_array()
    print(sequences_out.shape)
```

But I met：

<Trial 1714615 worker_0> slow_fast_simple $ python3 dali1.py
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x558038464880] Could not find codec parameters for stream 1 (Audio: aac (mp4a / 0x6134706D), 48000 Hz, 2 channels, 127 kb/s): unspecified sample format
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x558038456dc0] Could not find codec parameters for stream 1 (Audio: aac (mp4a / 0x6134706D), 48000 Hz, 2 channels, 127 kb/s): unspecified sample format
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Traceback (most recent call last):
  File "dali1.py", line 26, in <module>
    pipe.build()
  File "/home/tiger/.local/lib/python3.8/site-packages/nvidia/dali/pipeline.py", line 479, in build
    self._pipe.Build(self._names_and_devices)
RuntimeError: Critical error when building pipeline:
Error when constructing operator: VideoReader encountered:
CUDA driver API error <unknown error> (2422081744)
Current pipeline object is no longer valid.

My running data is：
`video_directory = os.path.join("DALI_extra", "db", "video", "sintel", "video_files")`

This question has bothered me for a long time. I look forward to your reply. Thank you very much！

**Comment by JanuszL** [comment]
Hi,
Could you tell us what GPU you have, what DALI version do you use?
Does that reproduce only on your machine or on others as well?

**Comment by LcenArthas** [comment]
My GPU is Tesla V100 and the DALI is ‘DALI v0.27.0’ ， 
I used [](https://developer.download.nvidia.com/compute/redist/nvidia-dali-cuda100/nvidia_dali_cuda100-0.27.0-1699645-py3-none-manylinux2014_x86_64.whl) to build on my machine.

My colleague also encountered this problem, his machine configuration is the same as mine.

**Comment by JanuszL** [comment]
What driver version do you have?

**Comment by LcenArthas** [comment]
hi, sorry for the late reply，I've solved this problem.
Just turn on nvidia docker's video option.

**Comment by votnhan** [comment]
Hi @LcenArthas, could you post your fix in the Dockerfile, I had the same problem as you :(((
