### ISSUE TITLE
best_prec1 does not get updated outside resume() function in ImageNet training in PyTorch example

### ISSUE THREAD

**Issue by dariodematties** [NVIDIA/DALI#2465]
Hi, I am trying to use the [ImageNet training in PyTorch](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/use_cases/pytorch/resnet50/pytorch-resnet50.html) example for my needs.

The issue seems to be [here](https://github.com/NVIDIA/DALI/blob/1073e9b650e278a19db184016b5cc173c6c40a95/docs/examples/use_cases/pytorch/resnet50/main.py#L288) in the code since in my case the variable `best_prec1` is indeed updated inside the function `resume()` but it continues having the same value (which is 0) outside.

Have you evidenced the same behavior?

Thanks!

Dario

**Comment by JanuszL** [comment]
Hi,
Good catch. We have just adopted the example from [APEX repository](https://github.com/NVIDIA/apex/blob/master/examples/imagenet/main_amp.py).
You need to add:
```
nonlocal best_prec1
```
before using it.
I will post a fix soon or you can do it if you want.

**Comment by dariodematties** [comment]
Hi, @JanuszL 

I do not know how to do it. Is there a step by step recipe to do it? Where?

I would love to contribute, at least with this little thing

**Comment by JanuszL** [comment]
https://github.com/NVIDIA/DALI/pull/2466 should fix this
