### ISSUE TITLE
one normal image cause Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by pokerc** [NVIDIA/DALI#2475]
got Segmentation fault (core dumped) when i use dali in my python code. I run for 4 rounds, and the first 2 rounds are ok. I find it is always the certain image cause the error。

Here is part of the  python code:

`
import pdb
pdb.set_trace()
import os
import sys
import numpy as np
from download_utils import download_url

from nvidia.dali.pipeline import Pipeline
import nvidia.dali as dali
import nvidia.dali.ops as ops
import nvidia.dali.types as types

IMG_MEAN = np.array([0.485, 0.456, 0.406], dtype=np.float32)
IMG_STD = np.array([0.229, 0.224, 0.225], dtype=np.float32)
IMG_MEAN_LIST = [0.485, 0.456, 0.406]
IMG_STD_LIST = [0.229, 0.224, 0.225]

def data_generator(data_l):
    while True:
        if len(data_l) > 0:
            item = data_l.pop()
            if item == "done":
                break
            # print("item: ", item)
            yield item
            # img_array = np.array([np.frombuffer(item, dtype=np.uint8)])
            # yield img_array
        else:
            pass

class SimplePipeline(Pipeline):
    def __init__(self, batch_size, num_threads, device_id, data_gen):
        super(SimplePipeline, self).__init__(batch_size, num_threads, device_id, seed=12, prefetch_queue_depth=1)
        # self.input = ops.FileReader(file_root=image_dir, file_list=file_list)
        self.input = ops.ExternalSource(source=data_gen)
        self.decode = ops.ImageDecoder(device='mixed', output_type=types.RGB)
        self.resize = ops.Resize(device='gpu', resize_x=224, resize_y=224)
        self.norm = ops.CropMirrorNormalize(device='gpu', mean=IMG_MEAN_LIST, std=IMG_STD_LIST, output_layout='HWC')
        self.cast = ops.Cast(device='gpu', dtype=types.FLOAT)

    def define_graph(self):
        jpegs = self.input()
        images = self.decode(jpegs)
        images_reshaped = self.resize(images)
        images_reshaped = images_reshaped / 255.
        images_reshaped = dali.fn.crop_mirror_normalize(images_reshaped, mean=IMG_MEAN_LIST, output_layout='HWC', std=IMG_STD_LIST)
        return images_reshaped

def main():
    batch_size = 2
    data_l = []
    dg = data_generator(data_l)
    dali_pipe = SimplePipeline(batch_size, 1, 0, data_gen=dg)
    dali_pipe.build()

    fr = open("images.txt", "r")
    total_image_num = 8
    img_bin_list = []
    for line in fr.readlines():
        img_bin = download_url(line.strip())
        img_bin_list.append(img_bin)
    img_np_ls = [np.frombuffer(img_bin, dtype=np.uint8) for img_bin in img_bin_list]
    for i in range(int(total_image_num/batch_size)):
        print("round {}".format(i+1))
        data_l.append(img_np_ls[2*i:2*(i+1)])
        try:
            print("111")
            dali_gpu_out, = dali_pipe.run()
            print("222")
        except Exception as e:
            print("round {} fialed, pass".format(i+1))
        dali_cpu_out = dali_gpu_out.as_cpu().as_array()
        # print("dali_cpu_out: ", type(dali_cpu_out), dali_cpu_out.shape, dali_cpu_out)
        print("dali_cpu_out: ", type(dali_cpu_out), dali_cpu_out.shape)

if __name__ == '__main__':
    main()
`

Got some gdb error info below:

`
[New Thread 0x7fffd78f6700 (LWP 72055)]
[New Thread 0x7fffd50f5700 (LWP 72056)]
round 1
111
222
dali_cpu_out:  <class 'numpy.ndarray'> (2, 224, 224, 3)
round 2
111
222
dali_cpu_out:  <class 'numpy.ndarray'> (2, 224, 224, 3)
round 3
111
222
dali_cpu_out:  <class 'numpy.ndarray'> (2, 224, 224, 3)
round 4
111

Thread 72 "python" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd50f5700 (LWP 72056)]
0x00007fff2b36ef4d in nvjpeg::huffmancpu::decodeBlockProgressiveACRefine(nvjpeg::huffmancpu::BitStream&, short*, short&, short&, unsigned char, unsigned char, unsigned char, unsigned char, nvjpeg::HuffmanTable const&, nvjpeg::HuffmanTable const&) ()
   from /usr/local/lib/python3.6/dist-packages/nvidia/dali/libdali_operators.so
`

environments are:
nvidia-dali-cuda100  0.23.0
python 3.6.8
Ubuntu 18.04.2 LTS

**Comment by pokerc** [comment]
I have tried to use opencv preprocess the certain image and it worked fine. I want to know what can cause this error.

**Comment by JanuszL** [comment]
Hi,
Can you open the faulty image in the viewer? Can you provide any faulty image so we can debug what is wrong?
It seems like an internal error of nvJPEG.

**Comment by pokerc** [comment]
> Hi,
> Can you open the faulty image in the viewer? Can you provide any faulty image so we can debug what is wrong?
> It seems like an internal error of nvJPEG.

here is the image url:  https://drive.google.com/file/d/1UexxeQ7thDK0RdrSPPCrT8JFwJipI9W0/view?usp=sharing

**Comment by JanuszL** [comment]
Hi,
I'm able to reproduce the issue with CUDA 10.0 DALI build, but it works fine with CUDA 11.0. Please move to DALI based on CUDA 11.0. It will work as long as you have a host driver >= 450.xx (CUDA 11.0 capable). DALI doesn't depend on the CUDA toolkit installed so you don't have to worry about the compatibility with other libraries you have already installed.

**Comment by pokerc** [comment]
> Hi,
> I'm able to reproduce the issue with CUDA 10.0 DALI build, but it works fine with CUDA 11.0. Please move to DALI based on CUDA 11.0. It will work as long as you have a host driver >= 450.xx (CUDA 11.0 capable). DALI doesn't depend on the CUDA toolkit installed so you don't have to worry about the compatibility with other libraries you have already installed.

Hi, unfortunately i can not upgrade CUDA or the host driver. If there is any other method to solve this problem (like manually modify the dali python code?), or what kind of image will case this error then i can drop this kind of images.

**Comment by JanuszL** [comment]
> Hi, unfortunately i can not upgrade CUDA or the host driver. If there is any other method to solve this problem (like manually modify the dali python code?), or what kind of image will case this error then i can drop this kind of images.

It is not related to the python code, all you can do is remove the images from your dataset.

**Comment by JanuszL** [comment]
Also you can:
- use CUDA 11.0 build and use [the CUDA forward compatibility mode](https://docs.nvidia.com/deploy/cuda-compatibility/index.html#forward-compatible-upgrade) just replacing the user space part of the driver - 
-build your own DALI version for CUDA 10.1. To do so please place the attached docker file in the docker folder in the DALI repository and issue the following command `cd docker &&  CUDA_VERSION=.101 REBUILD_BUILDERS=YES ./build.sh && pip install ../wheelhouse/nvidia_dali_cuda101*`.
[Dockerfile.cuda101.x86_64.deps.zip](https://github.com/NVIDIA/DALI/files/5588704/Dockerfile.cuda101.x86_64.deps.zip)
