### ISSUE TITLE
DALI for keypoints?

### ISSUE THREAD

**Issue by spurra** [NVIDIA/DALI#2484]
I'm trying to evaluate if I should switch to DALI for my data loading. One thing I have not found in the Image Processing tutorials is if labels and images can be processed differently. My task is keypoint predictions. Therefore any geometric operations such as WarpAffine or rotation would affect the keypoints as well, but appearance transformations such as changing HSV or contrast levels do not affect the keypoints. Is it possible to build such a graph using DALI? If so, can you provide a minimal example or reference me to documentation?

**Comment by JanuszL** [comment]
Hi,
You can independently process images and keypoints. The best and simplest example is [SSD detector pipeline](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/use_cases/detection_pipeline.html).
To process the keypoints please use the most recently introduced [transform operation family](https://docs.nvidia.com/deeplearning/dali/master-user-guide/docs/supported_ops.html#module-nvidia.dali.ops.transforms) - it is available in the nightly build and will be soon part of the 0.28 release.

**Comment by JanuszL** [comment]
Hi,

You can check [this example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/math/geometric_transforms.html) to see how to process keypoints with DALI.
