### ISSUE TITLE
DALI + Pytorch for Async Prefetch to GPU: feed_ndarray() bottleneck

### ISSUE THREAD

**Issue by FarzanT** [NVIDIA/DALI#2485]
Hello, I am mainly interested in DALI at the moment because Pytorch DataLoaders do not asynchronously transfer prefetched batches to the GPU. I am not using DALI's GPU operators as I am not using image-based data, rather tabular drug and genomic data.
After going through the tutorials and docs for a few days (I hope you don't mind me saying that they're not easy to follow), I have set up the following:
1. data iterator (inheriting `object`), with a `__next__` method
2. ExternalSourcePipeLine (inheriting `Pipeline`) using `op.ExternalResource` with GPU, `define_graph()` and `iter_setup()`,
3. A set of instantiations that result in my train validation data loaders that are of class `DALIGenericIterator`

**DataIterator**: Shortened for brevity, **not necessary** to read through, I just think there's something wrong with how I'm using the `size` property 
```python
...
    @property
    def size(self,):
        return self.len_drug_data

    def __len__(self):
        return self.len_drug_data
    def __iter__(self):
        # Reset the index counter
        print("Reset the index counter...")
        self.i = 0
        # Shuffle the training data (or the order of cell lines in AUC data)
        if self.valid_mode is False:
            np.random.seed(42)
            np.random.shuffle(self.drug_data_keys)

        return self

    def __next__(self):
        batch = []
        targets = []

        # Batch data and update self.i/idx
        for _ in range(self.batch_size):
            # Get the cell line name for the given index
            cur_cell = self.drug_data_keys[self.i]
            # Get the cell line omics data from non-drug pandas, and remove the keycolumn for training
            cur_data = [cur_dict[cur_cell] for cur_dict in self.dicts]

            # Here we only have one cell line, and we assume that we have 1 sample
            # cur_data = [panda.iloc[0, ] for panda in cur_data]

            cur_data = [self.drug_fps[self.i, :]] + cur_data

            # Subset data based on requested data types (in the case of bottleneck selection)
            if self.required_data_indices is not None:
                cur_data = [cur_data[i] for i in self.required_data_indices]

            batch.append(cur_data)
            targets.append(self.drug_data_targets[self.i])

            # Update self.i
            self.i += 1
            # Stop iteration if reached end of dataset
            if self.i >= self.len_drug_data:
                print("No more batches left in epoch!")
                raise StopIteration

        return batch, targets
    next = __next__

```
** ExternalSourcePipeLine**: 
```python
class ExternalSourcePipeline(Pipeline):
    def __init__(self, batch_size, pdi, num_threads, device_id, cuda_stream):
        super(ExternalSourcePipeline, self).__init__(batch_size,
                                                     num_threads,
                                                     device_id,
                                                     prefetch_queue_depth=10,
                                                     seed=12)
        self.pdi = pdi
        self.external_source_list = []
        # Extra ExternalSource for the targets
        for i in range(self.pdi.len_datatypes + 1):
            self.external_source_list.append(ops.ExternalSource(device="gpu", cuda_stream=cuda_stream))
        # Cast data to float32 on the GPU
        self.cast = ops.Cast(device="gpu", dtype=types.FLOAT)
        self.iterator = iter(self.pdi)

    def define_graph(self):
        # Directly transfer to GPU, and cast as float32
        self.encoders_and_target = [ext_source() for ext_source in self.external_source_list]
        casted_output = [self.cast(data_type) for data_type in self.encoders_and_target]

        # Return as a whole list
        return casted_output

    def iter_setup(self):
        # the external data iterator is consumed here and fed as input to Pipeline
        try:
            encoder_data, dr_target = next(self.pdi)

            # Must return the whole batch for each data type at once
            unzipped_encoder_data = list(zip(*encoder_data))
            for i in range(len(unzipped_encoder_data)):
                self.feed_input(self.encoders_and_target[i], list(unzipped_encoder_data[i]))

            self.feed_input(self.encoders_and_target[len(self.external_source_list) - 1], dr_target)

        except StopIteration:
            # raise exception when the iterator runs out of data and renew iterator
            print("Finished iteration, resetting...")
            self.iterator = iter(self.pdi)
            raise StopIteration
```
**Finally**: Create the iterator, create the pipeline and pass to the `DALIGenericIterator`
```python
    # Pair given data types based on fixed/assumed key column names
    train_pdi = PairDataIterator(data_module_list=data_list, key_columns=key_columns, drug_index=drug_index,
                                     valid_size=0.2, valid_mode=False,
                                     drug_dr_column=drug_dr_column)
    valid_pdi = PairDataIterator(data_module_list=data_list, key_columns=key_columns, drug_index=drug_index,
                                     valid_size=0.2, valid_mode=True,
                                     drug_dr_column=drug_dr_column)
    cur_cuda_stream = torch.cuda.current_stream
    # Pass DataLoaders (source) to NVIDIA DALI for pipelining
    train_pipe = ExternalSourcePipeline(batch_size=batch_size, pdi=train_pdi, num_threads=2, device_id=0,
                                        cuda_stream=cur_cuda_stream)
    train_pipe.build()
    # train_pipe_out = train_pipe.run()

    valid_pipe = ExternalSourcePipeline(batch_size=batch_size, pdi=valid_pdi, num_threads=2, device_id=0,
                                        cuda_stream=cur_cuda_stream)
    valid_pipe.build()
    # valid_pipe_out = valid_pipe.run()

    cur_output_map = ['encoder_data_' + str(i) for i in range(len(data_list))]
    cur_output_map += ['dr_target']
    train_loader = DALIGenericIterator(pipelines=[train_pipe], output_map=cur_output_map,
                                       last_batch_padded=True,
                                       fill_last_batch=False)
    valid_loader = DALIGenericIterator(pipelines=[valid_pipe], output_map=cur_output_map)

```
This is how I query the data during training:
```python
    cur_dr_data = [local_batch[0]['encoder_data_' + str(j)] for j in range(len(cur_model.encoder_list))]
    cur_dr_target = local_batch[0]['dr_target']
```
As you can see in the profiler results below (from torch.utils.bottleneck), `feed_ndarray()` and `feed_input()` seem to have become bottlenecks (at the top):
<img width="1237" alt="gpu() , cast, stream, prefetch 10" src="https://user-images.githubusercontent.com/21085967/99738947-ae71f980-2a99-11eb-8fd6-689fddb55b72.png">

Usually, this benchmark takes ~93 seconds to run, with the bottleneck being the `torch to` calls. I wish to use DALI to overlap the `to` calls and prefetch more data and put them on the GPU, but the aforementioned functions seem to cause a bottleneck of their own.
From my understanding, `feed_ndarray` turns `DALITensor` to `Torch.Tensor`, but this step seems redundant to me. 
Is it possible that this is a bug? Or perhaps I'm approaching DALI incorrectly in general?

Thank you for your time!

**Comment by JanuszL** [comment]
Hi,
`feed_ndarray` is fully synchronous as it needs to make sure that the data was copied out from DALI before the DALI pipeline can be executed again. To make it fully asynchronous we would need to attach the information about the stream the each DALI output was computed on so then we can use the right, event-based synchronization point.
We will add it to our ToDo list.
Have you run your pipeline with the real training, how sever is the bottleneck compared to the whole e2e performance?

**Comment by FarzanT** [comment]
I see, thank you for your explanation. I was able to implement the `data_prefetcher()` function from https://github.com/NVIDIA/apex/blob/8a1ed9e8d35dfad26fb973996319965e4224dcdd/examples/imagenet/main_amp.py#L264 and was able to run the same setup in 108 seconds:
<img width="1246" alt="Screen Shot 2020-11-23 at 4 02 12 PM" src="https://user-images.githubusercontent.com/21085967/100015257-ae2d7300-2da5-11eb-9e39-6ee53033a80e.png">
So there's a 40 second differences for my data, repeated at each epoch! I'm sure if you somehow improve `feed_ndarray()`, everyone will see great performance boosts.

Thanks again for your time.

**Comment by JanuszL** [comment]
What I can add is that your pipeline is pretty simple and it just loads data to the GPU. DALI is more about processing. If you are not doing any processing then the PyTorch data loader should be more than enough.

**Comment by FarzanT** [comment]
@JanuszL Thanks, you are right, I didn’t need image processing but I still had some GPU utilization issues where it kept jumping around 80 and 90 percent, but when I implemented the simple prefetcher from the apex examples, I got 100% utilization. The DataLoader alone even with multiple workers wasn’t enough as I think our compute cluster has old CPUs but new GPUs.
