### ISSUE TITLE
Get the shape inside pipeline and resize with it

### ISSUE THREAD

**Issue by bamfpga** [NVIDIA/DALI#2492]
Hello. I am trying to do the following thing: I use ops.Rotate with keep=False that increases the size of my image canvas. I'd like to resize it back to the original size. For this, I have to get the shapes before the Rotate operation and reshape/resize with those shapes after the Rotate operation.
I couldn't manage to find a solution to get a shape and resize with it inside the pipeline with ops.
Could you help me out? (I tried to use ops.Shape and ops.Resize but I cannot make them compatible).
 ### instantiate shape and resize ops
        self.get_image_shape = ops.Shapes(device='gpu',dtype=types.DALIDataType.FLOAT64)
        self.rotate_resize = ops.Resize(device='gpu',interp_type=types.DALIInterpType.INTERP_TRIANGULAR,
                                       save_attrs=True)
 ### get image shape and resize with it
            images_shape = self.get_image_shape(images)
            images = self.rotate_resize(images,size=images_shape)
Thanks in advance!

**Comment by mzient** [comment]
Hello,
The first thing that you need to know about `Shapes` operator is that its usability is very limited when it's applied to a GPU DataNode. You can go around it by using `PeekImageShape` operator which returns the shape of the images from the yet-undecoded binary file.
NOTE 1: In the code below I'll use the new (and soon the _main_) API for building DALI pipelines:
NOTE 2: Some of the features in the examples are from the upcoming release - use one of our latest nightly builds
```Python
import nvidia.dali as dali
import nvidia.dali.fn as fn
import PIL.Image

file = "../data/images/kitten/cat_2.jpg"
pipe = dali.pipeline.Pipeline(batch_size=1, num_threads=3, device_id=0)
with pipe:
    jpegs, _ = fn.file_reader(files=[file])
    images = fn.image_decoder(jpegs, device='mixed')
    shapes = fn.peek_image_shape(jpegs)
    rotated = fn.rotate(images, angle=fn.uniform(range=(-90,90)), fill_value=0)
    size = fn.slice(shapes, 0, 2, axes=[0])  # remove the channel axis
    out = fn.resize(rotated, size=size*1.0, mode='not_larger')  # maintain aspect ratio
    pipe.set_outputs(out)
    
pipe.build()
images, = pipe.run()
PIL.Image.fromarray(images.as_cpu().at(0))
```

However, if you are fine with linear interpolation, you can do prepare an affine transform matrix and use WarpAffine to run the whole transform in one go:
```Python
import nvidia.dali as dali
import nvidia.dali.fn as fn
import numpy as np
import PIL.Image

file = "../data/images/kitten/cat_2.jpg"
pipe = dali.pipeline.Pipeline(batch_size=1, num_threads=3, device_id=0)
with pipe:
    jpegs, _ = fn.file_reader(files=[file])
    images = fn.image_decoder(jpegs, device='mixed')
    
    shapes = fn.cast(fn.peek_image_shape(jpegs), dtype=dali.types.FLOAT)
    
    w = fn.slice(shapes, 1, 1, axes=[0])  # remove the channel axis
    h = fn.slice(shapes, 0, 1, axes=[0])  # remove the channel axis
    wh = fn.cat(w, h, axis=0)
    center = wh / 2
    m = fn.transforms.rotation(angle=fn.uniform(range=(-90,90), shape=[1]), center=center)  # shape=[1] is a workaround for a bug
    
    corners = fn.stack(
        np.float32([0, 0]),
        fn.cat(w, 0.0),
        fn.cat(0.0, h),
        wh)
    corners = fn.coord_transform(corners, MT=m)
    lo = fn.reductions.min(corners, axes=0)
    hi = fn.reductions.max(corners, axes=0)
    out_wh = hi - lo
    ratio = wh / out_wh
    
    ratio = fn.reductions.min(ratio)  # maintain aspect ratio
    ratio = fn.stack(ratio, ratio)  # scale expects a vector

    m = fn.transforms.scale(m, scale=ratio, center=center)
    out = fn.warp_affine(images, matrix=m, inverse_map=False, fill_value=0)
    pipe.set_outputs(out)
    
pipe.build()
images, = pipe.run()
PIL.Image.fromarray(images.as_cpu().at(0))
```

**Comment by cristyioan2000** [comment]
Hi,

I see that PeekImageShape has support only for the 'cpu', is there a way to get the shapes for each image in a GPU batch and resize them in the graph ? 

Thanks

**Comment by mzient** [comment]
@cristyioan2000 PeekImageShapes tells you what the shape of the image would be after decoding - it takes _raw files_ as input. There are no GPU-only decoders that could handle such files, so there's no point in having PeekImageShapes for GPU.
There's Shapes operator which will return the shapes of a batch of tensors and return in in the same backend as the input. You can't get the shapes back to CPU. That's a severe limitation and we're trying to figure out how to handle it without ripping whole DALI apart.

**Comment by cristyioan2000** [comment]
Can you please provide an example on how I can get the shapes using the Shapes operator and use the resulting shape for resizing the images ?

**Comment by mzient** [comment]
If the image is already on the GPU - unfortunately this can't be done, since the arguments like "size" need to be on the CPU. I said that's a _severe_ limitation and I meant it. You have to get the shape earlier in the pipeline, where the data is on the GPU.

**Comment by mzient** [comment]
If your images are on CPU (as in the example below), you can take the shape there:
```Python
import nvidia.dali as dali
import nvidia.dali.fn as fn
import PIL.Image

file = "../data/images/kitten/cat_2.jpg"
pipe = dali.pipeline.Pipeline(batch_size=1, num_threads=3, device_id=0)
with pipe:
    jpegs, _ = fn.file_reader(files=[file])
    images = fn.image_decoder(jpegs, device='cpu')
    shapes = fn.shapes(images)  # get the shape while the images are still on the CPU
    rotated = fn.rotate(images.gpu(), angle=fn.uniform(range=(-90,90)), fill_value=0)  # transfer to GPU here
    size = fn.slice(shapes, 0, 2, axes=[0])  # remove the channel axis
    out = fn.resize(rotated, size=size*1.0, mode='not_larger')
    pipe.set_outputs(out)
    
pipe.build()
images, = pipe.run()
PIL.Image.fromarray(images.as_cpu().at(0))
```

**Comment by cristyioan2000** [comment]
My goal is to rotate an image on GPU using `nvidia.dali.ops.Rotate` using `keep_size = False` because I don't want to lose any bounding boxes in the process of image rotation. I need to have the image size output fixed at 704x396 (w,h). 

Is there a way to resize an image, keeping the aspect ration, without passing a fixed size, just passing a maximum accepted value (upper margin) ? I'm thinking to rotate the image using `keep_size=False` resize it to a <704 resolution and use the `ops.Paste` operator to create a 704x396 (w,h) canvas and paste the rotate image on top of it.

**Comment by JanuszL** [comment]
I think [this](https://github.com/NVIDIA/DALI/issues/2492#issuecomment-732345216) answers what you want to do, rotate and scale back to the original size. You can read more [here](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/image_processing/resize.html) regarding different resize strategies.

**Comment by mzient** [comment]
You can force resize to keep aspect ratio _and_ fit in a particular upper bound - it's called `mode="not_larger"` I used it in the first example. It will resize the image to a size that does not exceed given boundaries. However, since the rotation can change the aspect ratio, the actual output size can be smaller in one of the dimensions.
Don't use operator Paste, it's broken. Use Crop with a padding option.
```Python
import nvidia.dali as dali
import nvidia.dali.fn as fn
import PIL.Image

file = "../data/images/kitten/cat_2.jpg"
pipe = dali.pipeline.Pipeline(batch_size=1, num_threads=3, device_id=0)
with pipe:
    jpegs, _ = fn.file_reader(files=[file])
    images = fn.image_decoder(jpegs, device='mixed')
    rotated = fn.rotate(images, angle=fn.uniform(range=(-90,90)), fill_value=0)
    width = 704
    height = 396
    out = fn.resize(rotated, size=[height, width], mode='not_larger')  # maintain aspect ratio
    out = fn.crop(out, crop_w=width, crop_h=height, out_of_bounds_policy="pad")
    pipe.set_outputs(out)
    
pipe.build()
images, = pipe.run()
PIL.Image.fromarray(images.as_cpu().at(0))
```
or you can use the WarpAffine option (but then you need to have the size of the non-rotated images on the CPU)
import nvidia.dali as dali
import nvidia.dali.fn as fn
import numpy as np
import PIL.Image

file = "../data/images/kitten/cat_2.jpg"
pipe = dali.pipeline.Pipeline(batch_size=1, num_threads=3, device_id=0)
with pipe:
    jpegs, _ = fn.file_reader(files=[file])
    images = fn.image_decoder(jpegs, device='mixed')
    
    shapes = fn.cast(fn.peek_image_shape(jpegs), dtype=dali.types.FLOAT)  # shape is HWC
    
    w = fn.slice(shapes, 1, 1, axes=[0])  # extract width
    h = fn.slice(shapes, 0, 1, axes=[0])  # extract height
    wh = fn.cat(w, h, axis=0)
    center = wh / 2
    m = fn.transforms.rotation(angle=fn.uniform(range=(-90,90), shape=[1]))  # shape=[1] is a workaround for a bug
    
    corners = fn.stack(
        np.float32([0, 0]),
        fn.cat(w, 0.0),
        fn.cat(0.0, h),
        wh)
    corners = fn.coord_transform(corners, MT=m)
    lo = fn.reductions.min(corners, axes=0)
    hi = fn.reductions.max(corners, axes=0)
    out_wh = hi - lo
    ratio = dali.types.Constant(np.float32([704, 396])) / out_wh
    
    ratio = fn.reductions.min(ratio)  # maintain aspect ratio
    ratio = fn.stack(ratio, ratio)  # scale expects a vector

    m = fn.transforms.translation(m, offset=-center, reverse_order=True)
    m = fn.transforms.scale(m, scale=ratio)
    m = fn.transforms.translation(m, offset=[704/2, 396/2])
    out = fn.warp_affine(images, size=[396, 704], matrix=m, inverse_map=False, fill_value=0)
    pipe.set_outputs(out)
    
pipe.build()
images, = pipe.run()
PIL.Image.fromarray(images.as_cpu().at(0))
```
In any case, you don't need the rotated size.

**Comment by cristyioan2000** [comment]
I tried with this:
```
        self.rotate = ops.Rotate(device='gpu',keep_size=False,fill_value=0)
        self.final_crop = ops.Crop(device='gpu')
        self.rotate_resize = ops.Resize(device='gpu',interp_type=types.DALIInterpType.INTERP_TRIANGULAR,mode='not_larger')

```

```
width = 704
height=396
rotated_images = self.rotate(images, angle=rotation_angle)
resized_images = self.rotate_resize(rotated_images ,size=resize)
cropped_images = self.final_crop(resized_images,crop_w=width,crop_h=height,out_of_bounds_policy="pad")

```
And it crashes with this error message:
```
  File "dali.py", line 282, in define_graph
    cropped_images = self.final_crop(resized_images,crop_w=width,crop_h=height,out_of_bounds_policy="pad")
  File "augmentations/lib/python3.7/site-packages/nvidia/dali/ops.py", line 460, in __call__
    op_instances.append(_OperatorInstance(input_set, self, **kwargs))
  File "augmentations/lib/python3.7/site-packages/nvidia/dali/ops.py", line 279, in __init__
    .format(type(arg_inp).__name__))
TypeError: Expected inputs of type `DataNode`. Received input of type 'int'.
```

**Comment by JanuszL** [comment]
Either you need to switch to the functional API as @mzient provided in his examples, or pass the width and height in when the operator is instantiated not when used in the `define_graph` method.

**Comment by mzient** [comment]
....or use a nightly build, because argument handling was unified somewhere between 0.27 and upcoming 0.28.

**Comment by cristyioan2000** [comment]
When the next version will be released ?

**Comment by JanuszL** [comment]
We are doing our best to keep the monthly release cadence, so the next version can be expected by the end of the month (or a bit after it).

**Comment by JanuszL** [comment]
All the discussed functionality should be available in the most recent official DALI release.
