### ISSUE TITLE
Performance Difference with DALI

### ISSUE THREAD

**Issue by SoHardToMakeAName** [NVIDIA/DALI#2498]
Hello and thanks for help! I am using DALI to speed up my training process for Single Image Super-Resolution (SISR) and find some obvious performance difference. But a huge gap occurs when I compare the same model trained with DALI PyTorch API (nvidia.dali.plugin.pytorch.DALIClassificationIterator) and original PyTorch DataLoader: the model (IMDN) gets 2dB lower PSNR on the DIV2K validation set with DALI. And I've checked my codes carefully to make sure that they are the same except the dataloader part, and I followed the guidance on official document ([https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/frameworks/pytorch/pytorch-external_input.html]). Actually the only part modified is the following one:

```
class SRPipeline(Pipeline):
    def __init__(self, batch_size, augmentations, eii, num_threads, device_id, scale=2, crop_size=96):
        super(SRPipeline, self).__init__(batch_size,
                                      num_threads,
                                      device_id)

        self.lr_input = ops.ExternalSource()
        self.hr_input = ops.ExternalSource()
        self.decode = ops.ImageDecoder(device = "mixed", output_type = types.RGB)
        self.transpose = ops.Transpose(device="gpu", perm=[2, 0, 1])
        self.cast = ops.Cast(device="gpu", dtype=types.FLOAT)
        self.crop_size = crop_size
        self.rng = ops.Uniform(range=(0.0, 1.0))
        self.crop_1 = ops.Crop(device="gpu", crop=(crop_size, crop_size))
        self.crop_2 = ops.Crop(device="gpu", crop=(scale*crop_size, scale*crop_size))
        self.rotate_90 = ops.Rotate(device="gpu", angle=90.0)
        self.rotate_180 = ops.Rotate(device="gpu", angle=180.0)
        self.rotate_270 = ops.Rotate(device="gpu", angle=270.0)
        self.flip_v = ops.Flip(device="gpu", vertical = 1, horizontal = 0)
        self.flip_h = ops.Flip(device="gpu", vertical = 0, horizontal = 1)
        self.use_rot90 = augmentations['rot90']
        self.use_rot180 = augmentations['rot180']
        self.use_rot270 = augmentations['rot270']
        self.use_flip_h = augmentations['flip_h']
        self.use_flip_v = augmentations['flip_v']
        self.external_data = eii
        self.iterator = iter(self.external_data)

    def define_graph(self):
        self.lr = self.lr_input()
        self.hr = self.hr_input()
        lr_img = self.decode(self.lr)
        hr_img = self.decode(self.hr)
        x_start = self.rng()
        y_start = self.rng()
        lr_crop = self.crop_1(lr_img, crop_pos_x=x_start, crop_pos_y=y_start)
        hr_crop = self.crop_2(hr_img, crop_pos_x=x_start, crop_pos_y=y_start)
        lr_crop, hr_crop = self.cast(lr_crop), self.cast(hr_crop)
        if self.use_rot90:
            lr_crop_rot_90, hr_crop_rot_90 = self.rotate_90(lr_crop), self.rotate_90(hr_crop)
        else:
            lr_crop_rot_90, hr_crop_rot_90 = lr_crop, hr_crop
        if self.use_rot180:
            lr_crop_rot_180, hr_crop_rot_180 = self.rotate_180(lr_crop), self.rotate_180(hr_crop)
        else:
            lr_crop_rot_180, hr_crop_rot_180 = lr_crop, hr_crop
        if self.use_rot270:
            lr_crop_rot_270, hr_crop_rot_270 = self.rotate_270(lr_crop), self.rotate_270(hr_crop)
        else:
            lr_crop_rot_270, hr_crop_rot_270 = lr_crop, hr_crop
        if self.use_flip_v:
            lr_crop_flip_v, hr_crop_flip_v = self.flip_v(lr_crop), self.flip_v(hr_crop)
        else:
            lr_crop_flip_v, hr_crop_flip_v = lr_crop, hr_crop
        if self.use_flip_h:
            lr_crop_flip_h, hr_crop_flip_h = self.flip_h(lr_crop), self.flip_h(hr_crop)
        else:
            lr_crop_flip_h, hr_crop_flip_h = lr_crop, hr_crop
        lr_crop, hr_crop = self.transpose(lr_crop), self.transpose(hr_crop)
        lr_crop_rot_90, hr_crop_rot_90 = self.transpose(lr_crop_rot_90), self.transpose(hr_crop_rot_90)
        lr_crop_rot_180, hr_crop_rot_180 = self.transpose(lr_crop_rot_180), self.transpose(hr_crop_rot_180)
        lr_crop_rot_270, hr_crop_rot_270 = self.transpose(lr_crop_rot_270), self.transpose(hr_crop_rot_270)
        lr_crop_flip_v, hr_crop_flip_v = self.transpose(lr_crop_flip_v), self.transpose(hr_crop_flip_v)
        lr_crop_flip_h, hr_crop_flip_h = self.transpose(lr_crop_flip_h), self.transpose(hr_crop_flip_h)
        return (lr_crop, lr_crop_rot_90, lr_crop_rot_180, lr_crop_rot_270, lr_crop_flip_h, lr_crop_flip_v,
                hr_crop, hr_crop_rot_90, hr_crop_rot_180, hr_crop_rot_270, hr_crop_flip_h, hr_crop_flip_v)
```

So does anyone get the same problem? I've debuged for days and still wonder how it could be possible. 

Thanks in advance!

**Comment by JanuszL** [comment]
Hi,
A few questions and remarks:
- you can replace crop-transpose-cast with [CropMirrorNormalize](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.ops.CropMirrorNormalize) operator
- do you use the same DALI pipeline for validation as for training - if you validate with the different data processing FW the processing discrepancies would yield different accuracy results
- I don't know how the reference pipeline looks like. Have you tried compare side by side if the pipeline you have built with DALI does the same as the reference one (including interpolation method used in the rotate operator)

**Comment by SoHardToMakeAName** [comment]
@JanuszL Thanks a lot! I think the second item is to the point: I use original PyTorch pipeline for validation because DALI does not support different tensor sizes among mini-batches and images in validation set have various sizes. But most augmentation operations are only needed in training process and I only want to speed up my training while DALI is not capable for validation sometimes.

Besides, does DALI normalize the image in crop-transpose-cast operations? This could be why the difference occurs since PyTorch ToTensor operation does not normalize imame but just devides it by 255.0. And Here's the PyTorch pipeline used for training (skimage lib is used):
`class SRIter(Dataset):

    def __init__(self, lr_dir, hr_dir, scale=2, crop_size=48):
        super(SRIter, self).__init__()
        self.hr_imgs = list()
        self.lr_imgs = list()
        for x in os.listdir(lr_dir):
            if x.find(".png") == -1 and x.find('.JPG') == -1:
                continue
            hr_name = x[:4] + '.png'
            if os.path.exists(os.path.join(hr_dir, hr_name)):
                self.lr_imgs.append(os.path.join(lr_dir, x))
                self.hr_imgs.append(os.path.join(hr_dir, hr_name))
        self.crop_size = crop_size
        self.scale = scale

    def __len__(self):
        return len(self.lr_imgs)

    def __getitem__(self, index):
        crop_size = self.crop_size
        scale = self.scale
        lr_pth = self.lr_imgs[index]
        hr_pth = self.hr_imgs[index]
        lr_img = np.array(io.imread(lr_pth))
        hr_img = np.array(io.imread(hr_pth))
        h, w = lr_img.shape[:2]
        left = random.randint(0, w-crop_size)
        top = random.randint(0, h-crop_size)
        lr_crop = lr_img[top:top+crop_size, left:left+crop_size]
        hr_crop = hr_img[scale*top:scale*(top+crop_size), scale*left:scale*(left+crop_size)]
        mode = random.randint(0, 3)
        lr_crop, hr_crop = self.my_augment(lr_crop, mode), self.my_augment(hr_crop, mode)
        lr_crop, hr_crop = lr_crop / 255.0, hr_crop / 255.0
        lr_crop, hr_crop = np.transpose(lr_crop, (2, 0, 1)), np.transpose(hr_crop, (2, 0, 1))
        return lr_crop.astype(np.float32), hr_crop.astype(np.float32)

    def my_augment(self, img, mode):
        if mode == 0:
            return img
        elif mode == 1:
            return img.transpose(1, 0, 2)
        else:
            return img[:, ::-1, :]`

**Comment by JanuszL** [comment]
>  I use original PyTorch pipeline for validation because DALI does not support different tensor sizes among mini-batches and images in validation set have various sizes.

You cannot yield them as PyTorch tensor, but DALI can output such batch and you can access each tensor in the batch separately. I'm curious how your network can consume a batch of tensors with different shapes, usually, networks have well-defined input shape.

> Besides, does DALI normalize the image in crop-transpose-cast operations? This could be why the difference occurs since PyTorch ToTensor operation does not normalize imame but just devides it by 255.0. 

Default values (mean=0, std=1) are transparent, if you want to divide by 255.0 set `std` to 255.0 and output type to FLOAT.

**Comment by SoHardToMakeAName** [comment]
> You cannot yield them as PyTorch tensor, but DALI can output such batch and you can access each tensor in the batch separately. I'm curious how your network can consume a batch of tensors with different shapes, usually, networks have well-defined input shape.

Maybe my words are not so precise and cause some misunderstanding. When I use DALI PyTorch Plugin API for validation, the batch size is set to 1 (e.g. each batch only contains one test image). And since the sizes of images are different, the tensor shape of the first batch and the second one's are usually not equal. Take Set5 as an example, the image Babyx2.png has shape [1, 3, 256, 256] and next image headx2.png has shape [1, 3, 140, 140]. Then I get this error:
`Traceback (most recent call last):
  File "test_SR.py", line 42, in <module>
    for i, data in enumerate(testloader, 0):
  File "/data/disk_b/lzq0330/main_venv/lib/python3.6/site-packages/nvidia/dali/plugin/pytorch.py", line 223, in __next__
    feed_ndarray(tensor, pyt_tensors[category], cuda_stream=stream)
  File "/data/disk_b/lzq0330/main_venv/lib/python3.6/site-packages/nvidia/dali/plugin/pytorch.py", line 56, in feed_ndarray
    ", but PyTorch Tensor has size {1}".format(dali_tensor.shape(), list(arr.size())))
AssertionError: Shapes do not match: DALI tensor has size [1, 3, 140, 140], but PyTorch Tensor has size [1, 3, 256, 256]`
It seems that this API does not support different batches to have different shapes.

**Comment by JanuszL** [comment]
@SoHardToMakeAName - please set `dynamic_shape` to True in the DALI PyTorch Plugin to enable changing the tensor size batch to batch.

**Comment by SoHardToMakeAName** [comment]
@JanuszL Thanks. It works.
