### ISSUE TITLE
Why only use the data come from gpu0?

### ISSUE THREAD

**Issue by One-punch24** [NVIDIA/DALI#2505]
well , I want to ask a stupid question and I would be appreciated if someone could help me.
I don't understand that although we use many gpu for preprocessing, but when training ,we only use data from pipe[0] , like the following code from official website.
![6](https://user-images.githubusercontent.com/63431994/100491746-1c38b800-3161-11eb-8a53-b70f76ccf0d2.PNG)
Thank you for answering !!

**Comment by JanuszL** [comment]
Hi,
DALI supports two approaches:
- Distributed Data-Parallel - DDP (each GPU is handled by a separated process)
- Data-Parallel - DP (all GPUs within a node are served by one process)

In the case of DP, you create a list of as many DALI pipelines as GPUs, then you pass them to the FW iterator. Each GPU data would be indexed by the GPU id - data[0], data[1] ...
In the case of DDP, each process serves a different GPU so you create only one pipeline in each script instance and pass it to the FW iterator, in such case you will access only data[0].
The DDP is the recommended way to train networks that is why in DALI examples only data[0] has valid content.

**Comment by One-punch24** [comment]
Thank you!
