### ISSUE TITLE
"RuntimeError: Critical error in pipeline" when using pytorch DALIGenericIterator plugin

### ISSUE THREAD

**Issue by aaroswings** [NVIDIA/DALI#2525]
I am trying to build a pipeline with matching image pairs as training examples. I'm testing it on a very small subset of my dataset (13 pairs - 26 images total). The goal is to randomly crop examples to 256x256 and perform other geometric augmentations.

The pipeline works for a few iterations, but at some point after I draw enough batches from it I receive this error:
`RuntimeError: Critical error in pipeline:
Error when executing CPU operator ImageDecoder, instance name: "__ImageDecoder_2", encountered:
Error in thread 3: CUDA allocation failed
Current pipeline object is no longer valid.`

I am running my code in WSL 2, with Ubuntu 18.04.  Checking my task manager, GPU memory usage does not appear to go over 10% at any point.
My CUDA version is 11.2 and my driver version is 465.12 according to the output of `nvidia-smi`.

My code is as follows:
```
batch_size = 4
size = 256
output_map = ['inputs', 'targets']
pipe_n_threads = 4
SEED = 2142 
IGNORE_LAST_BATCH = 1

class TestPipe(Pipeline):
    def __init__(self, batch_size, num_threads, device_id):
        super(TestPipe, self).__init__(batch_size, num_threads, device_id)
        
        self.inp_reader = ops.FileReader(file_root = input_examples_dir, name='inp_reader',
                                        seed=SEED, shuffle_after_epoch=True, device='cpu')
        self.tar_reader = ops.FileReader(file_root = target_examples_dir, name='tar_reader',
                                        seed=SEED, shuffle_after_epoch=True, device='cpu')
        
        self.decode_inp = ops.ImageDecoder(device="cpu", output_type=types.GRAY)
        self.decode_tar = ops.ImageDecoder(device="cpu", output_type=types.GRAY)
        
        self.crop_inp = ops.RandomResizedCrop(device="gpu", size=256, minibatch_size=batch_size,
                                             random_aspect_ratio=[1.,1.], seed=SEED)
        self.crop_tar = ops.RandomResizedCrop(device="gpu", size=256, minibatch_size=batch_size,
                                             random_aspect_ratio=[1.,1.], seed=SEED)
        self.cast = ops.Cast(device = "gpu",
                             dtype = types.FLOAT16)


    def define_graph(self):
        # Load and decode
        inp_imgs, _ = self.inp_reader()
        tar_imgs, _ = self.tar_reader()
        
        inp = self.decode_inp(inp_imgs)
        tar = self.decode_tar(tar_imgs)
        
        # Augment
        inp, tar = self.crop_inp(inp.gpu()), self.crop_tar(tar.gpu())
        inp = self.cast(inp)
        tar = self.cast(tar)
        
        return (inp, tar)

pipe = TestPipe(batch_size, pipe_n_threads, 0)
pipe.build()
dali_iter = DALIGenericIterator(pipe, output_map, EPOCH_SIZE, last_batch_policy = IGNORE_LAST_BATCH)

def make_batch():
    try:
        data = next(dali_iter)
    except StopIteration:
        dali_iter.reset()
        data = next(dali_iter)
    for d in data:
        return d["inputs"], d['targets']
```
The allocation error message occurs after calling `make_batch()` about 30 times.
What am I not aware of here - what are the probable causes of this?

**Comment by JanuszL** [comment]
Does it happen only with your data set? Does it reproduce with [DALI_extra](https://github.com/NVIDIA/DALI_extra) as well?
Similar code runs fine on Linux so I guess there might be some problem with WSL. Let me check this on my own.

**Comment by aaroswings** [comment]
I re-ran the code with the coco_pixelwise images and the error doesn't occur.
It may be due to the resolution of my images (some were quite large), even though my GPU memory was not close to being used up - I'm going to resize them to a smaller upper limit and test if this fixes the problem for the original files.

**Comment by aaroswings** [comment]
There was at least one really large image in my dataset folder that needed to be resized down (around 8k). So far since performing the resizing, no issues - so I believe that was the problem. 
Something to be aware of!

**Comment by JanuszL** [comment]
I'm glad it works. Even you may have only 10% of the memory utilized, the big image can ask for more memory than you have and fail.

**Comment by Freed-Wu** [comment]
I met

```
RuntimeError: Critical error in pipeline:
Error when executing GPU operator CropMirrorNormalize encountered:
Can't allocate 226492416 bytes on device 1.
Current pipeline object is no longer valid.
```

Although it is different from `CUDA allocation failed`, I guess it still means CUDA doesn't have enough memory? Thanks!

**Comment by JanuszL** [comment]
Hi @Freed-Wu,

You are right. We have moved to a more advanced allocation mechanism that uses an internal memory pool which is why the error message is a bit different, but still, it means out of memory problem.

**Comment by zimenglan-sysu-512** [comment]
hi @Freed-Wu

**Comment by zimenglan-sysu-512** [comment]
hi @Freed-Wu
