### ISSUE TITLE
Load image from a binary file

### ISSUE THREAD

**Issue by Vert53** [NVIDIA/DALI#2534]
Hi, I want to load an image that is saved in a binary file and implement myself the loading part. So instead of define_graph having for example: FileReader, ImageDecoder, op, I will have loading of the file to numpy (for example numpy.fromfile) and then the op.
Is such thing possible?
example:
`    def define_graph(self):
        numpy.fromfile(self.image_path, dtype=float32).reshape(100,100,3,1)
        images = self.crop_mirror_normalize_0(images)
`

Thanks,
Vert

**Comment by JanuszL** [comment]
HI,
You can use [NumpyReader](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.ops.NumpyReader) operator, [ExternalSource](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/external_input.html) or implement a [custom operator in Python](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/custom_operations/python_operator.html).

**Comment by Vert53** [comment]
> Hi,
> You can use [NumpyReader](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.ops.NumpyReader) operator, [ExternalSource](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/external_input.html) or implement a [custom operator in Python](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/custom_operations/python_operator.html).

That works perfectly. Thanks.
