### ISSUE TITLE
how to train own dataset.

### ISSUE THREAD

**Issue by zcf2020DPL** [NVIDIA/DALI#2554]
Hello, I want to train my own dataset .I want to ask if I must to write my own dataset reader like cocoreader or convert the dataset to coco format? thanks.

**Comment by zcf2020DPL** [comment]
use example pytorch single_detect_ssd only two classes in my own dataset..

> Hello, I want to train my own dataset .I want to ask if I must to write my own dataset reader like cocoreader or convert the dataset to coco format? thanks.

use example pytorch single_detect_ssd only two classes in my own dataset..

**Comment by zcf2020DPL** [comment]
> Hello, I want to train my own dataset .I want to ask if I must to write my own dataset reader like cocoreader or convert the dataset to coco format? thanks.

use example pytorch single_detect_ssd only two classes in my own dataset..

**Comment by JanuszL** [comment]
Hi @zcf2020DPL,

It depends on what you want to do. If you want to train a detection network you probably need to convert to COCO or try to feed DALI with the data another way around. You can use FileReaders for the images and NumpyReader for metadata, or use the ExternalSource operator. But this is a very vague question, that is hard to answer without more details.

**Comment by zcf2020DPL** [comment]
> Hi @zcf2020DPL,
> 
> It depends on what you want to do. If you want to train a detection network you probably need to convert to COCO or try to feed DALI with the data another way around. You can use FileReaders for the images and NumpyReader for metadata, or use the ExternalSource operator. But this is a very vague question, that is hard to answer without more details.

ok,get,thanks.
