### ISSUE TITLE
Quickly Getting Frames from a Video? (without saving them) 

### ISSUE THREAD

**Issue by Wilann** [NVIDIA/DALI#2562]
I'm trying to use DALI to read a video and pass batches of frames to a network quickly. 

Currently I'm using: 

```
vid = cv2.VideoCapture(vid_path)
ret, frame = vid.read()
```

With ~100,000 frames for a 1h video at 25 fps and 1080p, this takes ~3h. 
Is there a way to use DALI to speed up the process?

So far, I've only seen examples where DALI it reads images already saved. 
In this case, is there a way to save all ~100,000 frames quickly? 
I would use this, but it also takes a long time (and ~2TB) :
```
cv2.write(frame)
```

Is there another way I can approach this problem?

**Comment by JanuszL** [comment]
Hi,
Please take a look into [this example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/sequence_processing/index.html). It shows how to read video and process a batch of sequences. You can also check [this one](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/use_cases/video_superres/README.html) showing how to feed that data to the network itself.

**Comment by Wilann** [comment]
@JanuszL Thank you for the links - they were just what I was looking for!
