### ISSUE TITLE
Reference code for test-time augmentation?

### ISSUE THREAD

**Issue by dreavjr** [NVIDIA/DALI#2570]
Is there a reference code recommendation for test-time augmentation? In a "vanilla" pipeline I would replicate my test item n times before feeding it to the dataloader, with the dataloader creating the batches. If batch_size%n==0, such scheme works fairly well. 

In DALI, to do that, I am forced to switch to an external source (or am I? am I missing anything?), so I'm wondering if I can use the other --Reader operators and still create the needed test replicates.

**Comment by jantonguirao** [comment]
If you are using FileReader, you can specify a filename list with the `files` argument. The list can contain duplicates, so you can repeat each file N times to achieve N consecutive copies of each test sample.

In the future, we plan to support batch size changes across the pipeline, but we are not there yet. Once this is enabled, you could read the file once, apply N augmentation branches and later combine the results to a single batch.

Hope this helps.

**Comment by dreavjr** [comment]
Assuming the dataset batch has a "friendly" size (e.g., is a divisor of the actual GPU input batch size), would a custom operator based on PermuteBatch allowing extra samples in the output tensor be a feasible solution? Or would that naïve solution mess up the internal logic of DALI?

**Comment by JanuszL** [comment]
@dreavjr DALI doesn't allow batch size variability inside the pipeline (we are slowly enabling run to run variability, and we plan to enable such thing as well someday in the future).
What you can do now is only replace one sample by the other but you should not produce any additional samples or remove any samples changing the output batch size from the operator.
