### ISSUE TITLE
How to implement solarize in DALI?

### ISSUE THREAD

**Issue by SunDoge** [NVIDIA/DALI#2574]
Hi. I want to transfer the [solarize](https://github.com/pytorch/vision/blob/master/torchvision/transforms/functional_tensor.py#L820) from torchvision to DALI. However, this operation is not supported by DALI yet. After reading the [docs](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/expressions/expr_conditional_and_masking.html), is it possible to implement one as 

```python
class Solarize:

    def __init__(self, threshold: int = 128) -> None:
        self._threshold = threshold

    def __call__(self, img):
        inverted_img = 255 - img
        mask = img >= self._threshold
        return mask * inverted_img + (True ^ mask) * img
```

or is there an alternative operation in DALI?

**Comment by jantonguirao** [comment]
Currently, we do not have a specialized solarize operator. Your implementation looks good.

**Comment by JanuszL** [comment]
I would say if it works (and it should as arithmetic operations are supported by DALI) then it is good.
If you feel that the performance is inferior feel free to implement a dedicated, custom operator for this following [this guide](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/custom_operations/custom_operator/create_a_custom_operator.html). You can even create a PR and upstream in the DALI itself so, other users can benefit from it as well.
