### ISSUE TITLE
i use VideoReader to load my video data,but get "Segmentation fault (core dumped)"

### ISSUE THREAD

**Issue by seeyouagain111** [NVIDIA/DALI#2578]
i use this https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/sequence_processing/video/video_reader_label_example.html#

when my data only have 3 classes and 30 videos,It works,but when my data extend to 401 classes and about 23K videos,i got "Segmentation fault (core dumped)". why?

**Comment by jantonguirao** [comment]
Could you please provide a way to reproduce this problem? If the data is public, it would be good if you could share it. Otherwise, try to reproduce the problem with generated data.

**Comment by seeyouagain111** [comment]
> Could you please provide a way to reproduce this problem? If the data is public, it would be good if you could share it. Otherwise, try to reproduce the problem with generated data.

i used Kinetics-400 videos,i change the classed names to 0-399,and change all videos fps to 30 fps,then i used ops.VideoReader to load data and got the error "Segmentation fault (core dumped)".But if i only use part of Kinetics-400 videos,It is Ok,for example,i use VideoReader only load three classes video(class. 0、100、200). it looks like if there are too many classes and too many videos as training data, it will cause segmentation fault.

**Comment by jantonguirao** [comment]
This looks like a bug.
To be able to reproduce it, we would need the pipeline code you used, and if possible, a script to produce the data you used.
Thank you

**Comment by seeyouagain111** [comment]
> Could you please provide a way to reproduce this problem? If the data is public, it would be good if you could share it. Otherwise, try to reproduce the problem with generated data.

i know why this happen ，because some videos only have two seconds，but videoreaders squence_length is 64 meanwhile fps is 30,so i got "Segmentation fault (core dumped)"

**Comment by seeyouagain111** [comment]
I got a new BUG,i use Kinetics-400 dataset to train model,so i translate 400 classes name to 0,1....399.i rename 400 docs to 0,1,2...399.After using VideoReader to load video，i show the frame and label but found the frame do not corresponding with the label, why?

**Comment by seeyouagain111** [comment]
class VideoPipe(Pipeline):
        def __init__(self,batch_size,num_threads,device_id,data,shuffle):
            super(VideoPipe,self).__init__(batch_size,
                                          num_threads,
                                          device_id,
                                          seed=12)
                                          
            min_size=cfg.DATA.TRAIN_JITTER_SCALES[0]
            max_size=cfg.DATA.TRAIN_JITTER_SCALES[1]
            size = int(round(np.random.uniform(min_size, max_size)))
            pos_x=round(np.random.uniform(0.2,0.8),1)
            pos_y=round(np.random.uniform(0.2,0.8),1)
            self.input=ops.VideoReader(device="gpu",file_root=data,sequence_length=cfg.DATA.NUM_FRAMES,shard_id=device_id,num_shards=cfg.NUM_GPUS,random_shuffle=shuffle,initial_fill=0,stride=cfg.DATA.SAMPLING_RATE)
            crop_size=cfg.DATA.TRAIN_CROP_SIZE
            self.resize=ops.Resize(device="gpu",resize_shorter=size)
            self.crop=ops.Crop(device="gpu",crop_h=crop_size,crop_w=crop_size,crop_pos_x=pos_x,crop_pos_y=pos_y)
            self.flip=ops.Flip(device="gpu")
            self.transpose=ops.Transpose(device="gpu",perm=[3,0,1,2])
            self.normalize=ops.Normalize(device="gpu",mean=0.45*255,stddev=0.225*255)
            self.A=np.random.random()
        def define_graph(self): 
            output,labels = self.input(name="Reader")
            fast_pathway=self.resize(output)
            fast_pathway=self.crop(fast_pathway)
            if self.A>0.5:
                fast_pathway=self.flip(fast_pathway)
            #fast_pathway=self.normalize(fast_pathway)   
            fast_pathway=self.transpose(fast_pathway)
            return fast_pathway,labels

**Comment by seeyouagain111** [comment]
``      class VideoPipe(Pipeline):
        def __init__(self,batch_size,num_threads,device_id,data,shuffle):
            super(VideoPipe,self).__init__(batch_size,
                                          num_threads,
                                          device_id,
                                          seed=12)
                                          
            min_size=cfg.DATA.TRAIN_JITTER_SCALES[0]
            max_size=cfg.DATA.TRAIN_JITTER_SCALES[1]
            size = int(round(np.random.uniform(min_size, max_size)))
            pos_x=round(np.random.uniform(0.2,0.8),1)
            pos_y=round(np.random.uniform(0.2,0.8),1)
            self.input=ops.VideoReader(device="gpu",file_root=data,sequence_length=cfg.DATA.NUM_FRAMES,shard_id=device_id,num_shards=cfg.NUM_GPUS,random_shuffle=shuffle,initial_fill=0,stride=cfg.DATA.SAMPLING_RATE)
            crop_size=cfg.DATA.TRAIN_CROP_SIZE
            self.resize=ops.Resize(device="gpu",resize_shorter=size)
            self.crop=ops.Crop(device="gpu",crop_h=crop_size,crop_w=crop_size,crop_pos_x=pos_x,crop_pos_y=pos_y)
            self.flip=ops.Flip(device="gpu")
            self.transpose=ops.Transpose(device="gpu",perm=[3,0,1,2])
            self.normalize=ops.Normalize(device="gpu",mean=0.45*255,stddev=0.225*255)
            self.A=np.random.random()
        def define_graph(self): 
            output,labels = self.input(name="Reader")
            fast_pathway=self.resize(output)
            fast_pathway=self.crop(fast_pathway)
            if self.A>0.5:
                fast_pathway=self.flip(fast_pathway)
            #fast_pathway=self.normalize(fast_pathway)   
            fast_pathway=self.transpose(fast_pathway)
            return fast_pathway,labels

**Comment by seeyouagain111** [comment]
`class VideoPipe(Pipeline):
        def __init__(self,batch_size,num_threads,device_id,data,shuffle):
            super(VideoPipe,self).__init__(batch_size,
                                          num_threads,
                                          device_id,
                                          seed=12)
                                          
            min_size=cfg.DATA.TRAIN_JITTER_SCALES[0]
            max_size=cfg.DATA.TRAIN_JITTER_SCALES[1]
            size = int(round(np.random.uniform(min_size, max_size)))
            pos_x=round(np.random.uniform(0.2,0.8),1)
            pos_y=round(np.random.uniform(0.2,0.8),1)
            self.input=ops.VideoReader(device="gpu",file_root=data,sequence_length=cfg.DATA.NUM_FRAMES,shard_id=device_id,num_shards=cfg.NUM_GPUS,random_shuffle=shuffle,initial_fill=0,stride=cfg.DATA.SAMPLING_RATE)
            crop_size=cfg.DATA.TRAIN_CROP_SIZE
            self.resize=ops.Resize(device="gpu",resize_shorter=size)
            self.crop=ops.Crop(device="gpu",crop_h=crop_size,crop_w=crop_size,crop_pos_x=pos_x,crop_pos_y=pos_y)
            self.flip=ops.Flip(device="gpu")
            self.transpose=ops.Transpose(device="gpu",perm=[3,0,1,2])
            self.normalize=ops.Normalize(device="gpu",mean=0.45*255,stddev=0.225*255)
            self.A=np.random.random()
        def define_graph(self): 
            output,labels = self.input(name="Reader")
            fast_pathway=self.resize(output)
            fast_pathway=self.crop(fast_pathway)
            if self.A>0.5:
                fast_pathway=self.flip(fast_pathway)
            #fast_pathway=self.normalize(fast_pathway)   
            fast_pathway=self.transpose(fast_pathway)
            return fast_pathway,labels`

**Comment by seeyouagain111** [comment]
class VideoPipe(Pipeline):
        def __init__(self,batch_size,num_threads,device_id,data,shuffle):
            super(VideoPipe,self).__init__(batch_size, num_threads, device_id, seed=12)
            min_size=cfg.DATA.TRAIN_JITTER_SCALES[0]
            max_size=cfg.DATA.TRAIN_JITTER_SCALES[1]
            size = int(round(np.random.uniform(min_size, max_size)))
            pos_x=round(np.random.uniform(0.2,0.8),1)
            pos_y=round(np.random.uniform(0.2,0.8),1)
            self.input=ops.VideoReader(device="gpu",file_root=data,sequence_length=cfg.DATA.NUM_FRAMES,shard_id=device_id,num_shards=cfg.NUM_GPUS,random_shuffle=shuffle,initial_fill=0,stride=cfg.DATA.SAMPLING_RATE)
            crop_size=cfg.DATA.TRAIN_CROP_SIZE
            self.resize=ops.Resize(device="gpu",resize_shorter=size)
            self.crop=ops.Crop(device="gpu",crop_h=crop_size,crop_w=crop_size,crop_pos_x=pos_x,crop_pos_y=pos_y)
            self.flip=ops.Flip(device="gpu")
            self.transpose=ops.Transpose(device="gpu",perm=[3,0,1,2])
            self.normalize=ops.Normalize(device="gpu",mean=0.45*255,stddev=0.225*255)
            self.A=np.random.random()
        def define_graph(self): 
            output,labels = self.input(name="Reader")
            fast_pathway=self.resize(output)
            fast_pathway=self.crop(fast_pathway)
            if self.A>0.5:
                fast_pathway=self.flip(fast_pathway)
            #fast_pathway=self.normalize(fast_pathway)   
            fast_pathway=self.transpose(fast_pathway)
            return fast_pathway,labels

**Comment by seeyouagain111** [comment]
class VideoPipe(Pipeline):
        def __init__(self,batch_size,num_threads,device_id,data,shuffle):
            super(VideoPipe,self).__init__(batch_size, num_threads, device_id, seed=12)
            min_size=cfg.DATA.TRAIN_JITTER_SCALES[0]
            max_size=cfg.DATA.TRAIN_JITTER_SCALES[1]
            size = int(round(np.random.uniform(min_size, max_size)))
            pos_x=round(np.random.uniform(0.2,0.8),1)
            pos_y=round(np.random.uniform(0.2,0.8),1)
            self.input=ops.VideoReader(device="gpu",file_root=data,sequence_length=cfg.DATA.NUM_FRAMES,shard_id=device_id,num_shards=cfg.NUM_GPUS,random_shuffle=shuffle,initial_fill=0,stride=cfg.DATA.SAMPLING_RATE)
            crop_size=cfg.DATA.TRAIN_CROP_SIZE
            self.resize=ops.Resize(device="gpu",resize_shorter=size)
            self.crop=ops.Crop(device="gpu",crop_h=crop_size,crop_w=crop_size,crop_pos_x=pos_x,crop_pos_y=pos_y)
            self.flip=ops.Flip(device="gpu")
            self.transpose=ops.Transpose(device="gpu",perm=[3,0,1,2])
            self.normalize=ops.Normalize(device="gpu",mean=0.45*255,stddev=0.225*255)
            self.A=np.random.random()
        def define_graph(self): 
            output,labels = self.input(name="Reader")
            fast_pathway=self.resize(output)
            fast_pathway=self.crop(fast_pathway)
            if self.A>0.5:
                fast_pathway=self.flip(fast_pathway)
            #fast_pathway=self.normalize(fast_pathway)   
            fast_pathway=self.transpose(fast_pathway)
            return fast_pathway,labels

**Comment by seeyouagain111** [comment]
`class VideoPipe(Pipeline):
        def __init__(self,batch_size,num_threads,device_id,data,shuffle):
            super(VideoPipe,self).__init__(batch_size, num_threads, device_id, seed=12)
            min_size=cfg.DATA.TRAIN_JITTER_SCALES[0]
            max_size=cfg.DATA.TRAIN_JITTER_SCALES[1]
            size = int(round(np.random.uniform(min_size, max_size)))
            pos_x=round(np.random.uniform(0.2,0.8),1)
            pos_y=round(np.random.uniform(0.2,0.8),1)
            self.input=ops.VideoReader(device="gpu",file_root=data,sequence_length=cfg.DATA.NUM_FRAMES,shard_id=device_id,num_shards=cfg.NUM_GPUS,random_shuffle=shuffle,initial_fill=0,stride=cfg.DATA.SAMPLING_RATE)
            crop_size=cfg.DATA.TRAIN_CROP_SIZE
            self.resize=ops.Resize(device="gpu",resize_shorter=size)
            self.crop=ops.Crop(device="gpu",crop_h=crop_size,crop_w=crop_size,crop_pos_x=pos_x,crop_pos_y=pos_y)
            self.flip=ops.Flip(device="gpu")
            self.transpose=ops.Transpose(device="gpu",perm=[3,0,1,2])
            self.normalize=ops.Normalize(device="gpu",mean=0.45*255,stddev=0.225*255)
            self.A=np.random.random()
        def define_graph(self): 
            output,labels = self.input(name="Reader")
            fast_pathway=self.resize(output)
            fast_pathway=self.crop(fast_pathway)
            if self.A>0.5:
                fast_pathway=self.flip(fast_pathway)
            #fast_pathway=self.normalize(fast_pathway)   
            fast_pathway=self.transpose(fast_pathway)
            return fast_pathway,labels`

**Comment by seeyouagain111** [comment]
class VideoPipe(Pipeline):
        def __init__(self,batch_size,num_threads,device_id,data,shuffle):
            super(VideoPipe,self).__init__(batch_size, num_threads, device_id, seed=12)
            min_size=cfg.DATA.TRAIN_JITTER_SCALES[0]
            max_size=cfg.DATA.TRAIN_JITTER_SCALES[1]
            size = int(round(np.random.uniform(min_size, max_size)))
            pos_x=round(np.random.uniform(0.2,0.8),1)
            pos_y=round(np.random.uniform(0.2,0.8),1)
            self.input=ops.VideoReader(device="gpu",file_root=data,sequence_length=cfg.DATA.NUM_FRAMES,shard_id=device_id,num_shards=cfg.NUM_GPUS,random_shuffle=shuffle,initial_fill=0,stride=cfg.DATA.SAMPLING_RATE)
            crop_size=cfg.DATA.TRAIN_CROP_SIZE
            self.resize=ops.Resize(device="gpu",resize_shorter=size)
            self.crop=ops.Crop(device="gpu",crop_h=crop_size,crop_w=crop_size,crop_pos_x=pos_x,crop_pos_y=pos_y)
            self.flip=ops.Flip(device="gpu")
            self.transpose=ops.Transpose(device="gpu",perm=[3,0,1,2])
            self.normalize=ops.Normalize(device="gpu",mean=0.45*255,stddev=0.225*255)
            self.A=np.random.random()
        def define_graph(self): 
            output,labels = self.input(name="Reader")
            fast_pathway=self.resize(output)
            fast_pathway=self.crop(fast_pathway)
            if self.A>0.5:
                fast_pathway=self.flip(fast_pathway)
            #fast_pathway=self.normalize(fast_pathway)   
            fast_pathway=self.transpose(fast_pathway)
            return fast_pathway,labels

**Comment by seeyouagain111** [comment]
if cfg.dali==1:
      class VideoPipe(Pipeline):
        def __init__(self,batch_size,num_threads,device_id,data,shuffle):
            super(VideoPipe,self).__init__(batch_size,
                                          num_threads,
                                          device_id,
                                          seed=12)
                                          
            min_size=cfg.DATA.TRAIN_JITTER_SCALES[0]
            max_size=cfg.DATA.TRAIN_JITTER_SCALES[1]
            size = int(round(np.random.uniform(min_size, max_size)))
            pos_x=round(np.random.uniform(0.2,0.8),1)
            pos_y=round(np.random.uniform(0.2,0.8),1)
            self.input=ops.VideoReader(device="gpu",file_root=data,sequence_length=cfg.DATA.NUM_FRAMES,shard_id=device_id,num_shards=cfg.NUM_GPUS,random_shuffle=shuffle,initial_fill=4,stride=cfg.DATA.SAMPLING_RATE)
            crop_size=cfg.DATA.TRAIN_CROP_SIZE
            self.resize=ops.Resize(device="gpu",resize_shorter=size)
            self.crop=ops.Crop(device="gpu",crop_h=crop_size,crop_w=crop_size,crop_pos_x=pos_x,crop_pos_y=pos_y)
            self.flip=ops.Flip(device="gpu")
            self.transpose=ops.Transpose(device="gpu",perm=[3,0,1,2])
            self.normalize=ops.Normalize(device="gpu",mean=0.45*255,stddev=0.225*255)
            self.A=np.random.random()
        def define_graph(self): 
            output,labels = self.input(name="Reader")
            fast_pathway=self.resize(output)
            fast_pathway=self.crop(fast_pathway)
            if self.A>0.5:
                fast_pathway=self.flip(fast_pathway)
            #fast_pathway=self.normalize(fast_pathway)   
            fast_pathway=self.transpose(fast_pathway)
            return fast_pathway,labels

**Comment by seeyouagain111** [comment]
this is my "VideoReader" code

**Comment by jantonguirao** [comment]
> i know why this happen ，because some videos only have two seconds，but videoreaders squence_length is 64 meanwhile fps is 30,so i got "Segmentation fault (core dumped)"

Thanks for spotting that. We should definitely not segfault in that case. We will investigate what we can do about it (at the very least better error reporting, perhaps a possibility to discard short or pad with zeros.

> I got a new BUG,i use Kinetics-400 dataset to train model,so i translate 400 classes name to 0,1....399.i rename 400 docs to 0,1,2...399.After using VideoReader to load video，i show the frame and label but found the frame do not corresponding with the label, why?

To be able to start investigating this potential bug, could you please share a script to prepare the dataset in the same way you did? Thanks

**Comment by seeyouagain111** [comment]
> > i know why this happen ，because some videos only have two seconds，but videoreaders squence_length is 64 meanwhile fps is 30,so i got "Segmentation fault (core dumped)"
> 
> Thanks for spotting that. We should definitely not segfault in that case. We will investigate what we can do about it (at the very least better error reporting, perhaps a possibility to discard short or pad with zeros.
> 
> > I got a new BUG,i use Kinetics-400 dataset to train model,so i translate 400 classes name to 0,1....399.i rename 400 docs to 0,1,2...399.After using VideoReader to load video，i show the frame and label but found the frame do not corresponding with the label, why?
> 
> To be able to start investigating this potential bug, could you please share a script to prepare the dataset in the same way you did? Thanks

thanks for your reply。i found the reason! acturally when we use VideoReader, The real groundtruth of the video classes do dont depend on the name of doc,but depend on Order of folders。for example, If  i have 400 classes of videos, i rename folders to 0,1,2,...399。but DALI will reorder them   0,1,10,100,101..2,200,201...... 。so i show the frame and label but found the frame do not corresponding with the label，the truth is that the true label is 10,but DALI read it as 2。

**Comment by seeyouagain111** [comment]
another question!I have all  20452 videos。 4GPUS and batch_size=16 for training. I use VideoReader to load data. but i print pips.epoch_size("Reader")，this number is 96920 ,what is the relationship between 20452 and 96920?

**Comment by jantonguirao** [comment]
> thanks for your reply。i found the reason! acturally when we use VideoReader, The real groundtruth of the video classes do dont depend on the name of doc,but depend on Order of folders。for example, If i have 400 classes of videos, i rename folders to 0,1,2,...399。but DALI will reorder them 0,1,10,100,101..2,200,201...... 。so i show the frame and label but found the frame do not corresponding with the label，the truth is that the true label is 10,but DALI read it as 2，true label is 100,but DALI read it as 3。

That's right, DALI doesn't interpret the name of the folder as a number, it just assigns consecutive numbers to the folders that are sorted alphabetically. If you want to preserve your labels, just add leading zeros to the folder names: 001, 002, 003, ...

> another question!I have all 20452 videos。 4GPUS and batch_size=16 for training. I use VideoReader to load data. but i print pips.epoch_size("Reader")，this number is 96920 ,what is the relationship between 20452 and 96920?

Video reader extracts several sequences from a single video file. The number of iterations you get depends on how many videos you have, how many sequences can be extracted from each video file, your batch size, and whether you are sharding the dataset. The number of sequences extracted from each video depends on the `sequence_length` and `step` arguments.

> i know why this happen ，because some videos only have two seconds，but videoreaders squence_length is 64 meanwhile fps is 30,so i got "Segmentation fault (core dumped)"

I could not reproduce this segfault on my own. Could you please share your the and video samples that led to it?

**Comment by seeyouagain111** [comment]
> > thanks for your reply。i found the reason! acturally when we use VideoReader, The real groundtruth of the video classes do dont depend on the name of doc,but depend on Order of folders。for example, If i have 400 classes of videos, i rename folders to 0,1,2,...399。but DALI will reorder them 0,1,10,100,101..2,200,201...... 。so i show the frame and label but found the frame do not corresponding with the label，the truth is that the true label is 10,but DALI read it as 2，true label is 100,but DALI read it as 3。
> 
> That's right, DALI doesn't interpret the name of the folder as a number, it just assigns consecutive numbers to the folders that are sorted alphabetically. If you want to preserve your labels, just add leading zeros to the folder names: 001, 002, 003, ...
> 
> > another question!I have all 20452 videos。 4GPUS and batch_size=16 for training. I use VideoReader to load data. but i print pips.epoch_size("Reader")，this number is 96920 ,what is the relationship between 20452 and 96920?
> 
> Video reader extracts several sequences from a single video file. The number of iterations you get depends on how many videos you have, how many sequences can be extracted from each video file, your batch size, and whether you are sharding the dataset. The number of sequences extracted from each video depends on the `sequence_length` and `step` arguments.
> 
> > i know why this happen ，because some videos only have two seconds，but videoreaders squence_length is 64 meanwhile fps is 30,so i got "Segmentation fault (core dumped)"
> 
> I could not reproduce this segfault on my own. Could you please share your the and video samples that led to it?

you mean iterations depend on how train video length？ for example my trian video are all 10-seconds 30fps videos, sequence_length=30 and step=2 . you mean one train video can product 5 iterations?

**Comment by jantonguirao** [comment]
> you mean iterations depend on train video length？ 
Yes, that's right.

> for example my trian video are all 10-seconds 30fps videos, sequence_length=30 and step=2 . you mean one train video can product 5 iterations?

The step is not in seconds but in frames.
`10 * 30 = 300` total frames in a 10sec video. With a sequence length of 30 frames and a step of 2 frames, you are getting 149 full sequences. If you have a batch size of 1, I believe you should be getting 149 iterations from that file.

**Comment by seeyouagain111** [comment]
> > you mean iterations depend on train video length？
> > Yes, that's right.
> 
> > for example my trian video are all 10-seconds 30fps videos, sequence_length=30 and step=2 . you mean one train video can product 5 iterations?
> 
> The step is not in seconds but in frames.
> `10 * 30 = 300` total frames in a 10sec video. With a sequence length of 30 frames and a step of 2 frames, you are getting 136 full sequences. If you have a batch size of 1, I believe you should be getting 136 iterations from that file.

"stride=2" does not mean Interval one frame sampling all 30 frames? If i want interval sampling using VideoReader,how should i do?

**Comment by JanuszL** [comment]
To provide your class numbers you can use either `file_list` argument or `files` and `labels`.

I just tried to repro the crash with Videos that are shorted than the requested sequence lenght:
```
ffmpeg -f lavfi -i color=c=blue:s=1280x720:d=1:r=10 -c:v libx264 -vf "format=pix_fmts=yuv420p, drawtext=fontsize=64: fontcolor=white: font=monospace: x=(w-text_w)/2: y=(h-text_h)/2: r=60: text='%{frame_num}'" cfr_test.mp4
ffmpeg -f lavfi -i color=c=blue:s=1280x720:d=101:r=10 -c:v libx264 -vf "format=pix_fmts=yuv420p, drawtext=fontsize=64: fontcolor=white: font=monospace: x=(w-text_w)/2: y=(h-text_h)/2: r=60: text='%{frame_num}'" cfr_test2.mp4

from nvidia.dali.pipeline import Pipeline
from nvidia.dali.plugin.pytorch import DALIGenericIterator
import nvidia.dali.ops as ops
import nvidia.dali.types as types
import os

vid_path = ["cfr_test.mp4", "cfr_test2.mp4"]

batch_size = 1
sequence_length = 30
initial_prefetch_size = 1
num_iterations = 1

class VideoPipeline(Pipeline):

    def __init__(self, batch_size, num_threads, device_id, data, shuffle):
        super(VideoPipeline, self).__init__(batch_size, num_threads, device_id, seed=0)

        self.input = ops.VideoReader(device='gpu', filenames=data, sequence_length=sequence_length,
                                     shard_id=0, num_shards=1,
                                     random_shuffle=shuffle,
                                     initial_fill=initial_prefetch_size)

    def define_graph(self):
        frames = self.input(name='Reader')
        return frames

video_pipe = VideoPipeline(batch_size=batch_size, num_threads=2, device_id=0, data=vid_path, shuffle=False)
pipes = video_pipe
pipes.build()
out = pipes.run()
print(out[0][0].shape())
```
It creates two videos, one with 10 frames and one with 1010 frames. Then the files are passed to the pipeline. 
If you pass only the sorter one you will get:
```
 Assert on "!frame_starts_.empty()" failed: There are no valid sequences in the provided dataset, check the length of the available videos and the requested sequence length.
```
What is expected as there is no valid sequence that can be build from the passed video file.
