### ISSUE TITLE
Does prefetching to GPU in TensorFlow lead to speed increases?

### ISSUE THREAD

**Issue by yingusxiaous** [NVIDIA/DALI#2580]
TensorFlow runs all ops in the cuda default stream (e.g., see https://stackoverflow.com/questions/36098947/how-does-tensorflow-support-cuda-streams), which means that *all* GPU operations are synchronous. I've seen claims that TF uses separate memcopy streams, but this design would suggest that that it's impossible to overlap copies and computes (in my experience looking at traces, this seems to be the case). Does Dali work around this? Otherwise, it would seem that prefetching to GPU would contribute little to overall performance.

**Comment by jantonguirao** [comment]
In the link you shared it says that TF uses one compute stream, it does not say it is the default stream. Nevertheless, if they use the same stream for copying and for computing, then it is true that those operations will be serialized.

DALI runs prefetching on its own and can serve the data directly to GPU memory. In that case, there will only be a copy from DALI GPU outputs to the TF GPU tensors used by the model, which should be a small overhead.

**Comment by yingusxiaous** [comment]
Hmm, that's a good point that "one compute stream" is not necessarily the same as "default stream". Digging into the TF source, it looks like [cuda_driver.h](https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/stream_executor/cuda/cuda_driver.h) is the wrapper for stream creation, and unfortunately, I think only default streams are created in the corresponding [cuda_driver.cc](https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/stream_executor/cuda/cuda_driver.cc;l=743-747?q=CreateStream&ss=tensorflow).

**Comment by jantonguirao** [comment]
The default stream is the 0 stream. This is not the case. They are creating one with `cuStreamCreate` or `cuStreamCreateWithPriority`.

In any case, as I said in the previous comment, if you use DALI you will benefit from its prefetching capabilities and the DALI outputs can be in GPU memory which means that the copy to the framework tensors will be just a device-to-device copy. In this scenario, the d2d copy and the computations from TF will be serialized, but the data processing and transfer to the GPU performed by DALI will overlap.
