### ISSUE TITLE
Pytorch-Lightning Documentation

### ISSUE THREAD

**Issue by Data-drone** [NVIDIA/DALI#2584]
When following the Dali PyTorch-Lightning documentation, I got:

`
 Warning: Please do not use `fill_last_batch` and use `last_batch_policy` instead.
  _DaliBaseIterator.__init__(self, pipelines, size, reader_name, auto_reset, fill_last_batch, last_batch_padded, last_batch_policy)
`

Guessing something has changed in the API and the docs need updating?

https://docs.nvidia.com/deeplearning/dali/master-user-guide/docs/examples/frameworks/pytorch/pytorch-lightning.html

**Comment by jantonguirao** [comment]
You are right, this part of the documentation is still using a deprecated option. We will update it. Thanks for pointing that out.

**Comment by JanuszL** [comment]
It will be fixed in https://github.com/NVIDIA/DALI/pull/2585.

**Comment by Data-drone** [comment]
thanks
