### ISSUE TITLE
Way to eliminate ExternalSource overhead?

### ISSUE THREAD

**Issue by shanesyy-1992** [NVIDIA/DALI#2586]
Hi, sorry for bothering. It seems that where is around 20-30ms overhead (depends on the input data size) involved by `SetDataSource` of `ExternalSource` at the beginning of each training batch when using DALI for data preprocessing (shown as the pic below). I wonder is there any way to eliminate it? Or make it overlap with the training, instead of blocking the following kernel launch. I'm training the resnet50 and the code of DALI part is exactly the same as the example [here](https://github.com/NVIDIA/DALI/blob/2a85811d379f07cd94de9265eabf28b6d4e38f77/docs/examples/use_cases/pytorch/resnet50/main.py) . Many Thanks!

<img width="1267" alt="Screen Shot 2021-01-04 at 3 54 40 PM" src="https://user-images.githubusercontent.com/72180088/103598464-860e5500-4eb7-11eb-9d80-a72e79237f44.png">

**Comment by jantonguirao** [comment]
The code you linked doesn't use ExternalSource. Could you share the actual code you used?

One thing to try would be to change the prefetching queue depth of the DALI pipeline.
Also, if you have control of your data source and you can guarantee that the input buffer is alive and unmodified throughout the iteration, then you could try `no_copy` option in ExternalSource.

**Comment by shanesyy-1992** [comment]
> The code you linked doesn't use ExternalSource. Could you share the actual code you used?

Oh right, sorry for missing that. Below is the code we used for dali pipeline, in which we use an external source to get the required data and feed them into the pipe in `iter_setup` function:
```
class TrainImageDecoderPipeline(Pipeline):
    def __init__(self, batch_size, num_threads, device_id, external_data, crop, seed=100, dali_cpu=False, prefetch_queue_depth=2):
        super(TrainImageDecoderPipeline, self).__init__(
            batch_size, num_threads, device_id, seed=seed, prefetch_queue_depth=prefetch_queue_depth)
        self.external_data = external_data
        self.data_iter = iter(self.external_data)

        self.input_raw_images = ops.ExternalSource(device="cpu")
        self.input_labels = ops.ExternalSource(device="cpu")
        self.input_input_ids = ops.ExternalSource(device="cpu")
        self.input_input_mask = ops.ExternalSource(device="cpu")
            
        dali_device = 'cpu' if dali_cpu else 'gpu'
        decoder_device = 'cpu' if dali_cpu else 'mixed'

        # This padding sets the size of the internal nvJPEG buffers to be able to handle all images from full-sized ImageNet
        # without additional reallocations
        device_memory_padding = 211025920 if decoder_device == 'mixed' else 0
        host_memory_padding = 140544512 if decoder_device == 'mixed' else 0
        self.decode = ops.ImageDecoderRandomCrop(device=decoder_device, output_type=types.RGB,
                                                 device_memory_padding=device_memory_padding,
                                                 host_memory_padding=host_memory_padding,
                                                 random_aspect_ratio=[
                                                     0.8, 1.25],
                                                 random_area=[0.1, 1.0],
                                                 num_attempts=100)
        self.res = ops.Resize(device=dali_device,
                              resize_x=crop,
                              resize_y=crop,
                              interp_type=types.INTERP_TRIANGULAR)

        self.cmnp = ops.CropMirrorNormalize(device="gpu",
                                            dtype=types.FLOAT,
                                            output_layout=types.NCHW,
                                            crop=(crop, crop),
                                            mean=[0.485 * 255, 0.456 *
                                                  255, 0.406 * 255],
                                            std=[0.229 * 255, 0.224 * 255, 0.225 * 255])
        self.coin = ops.CoinFlip(probability=0.5)

    def define_graph(self):
        rng = self.coin()
        self.raw_images = self.input_raw_images()
        self.labels = self.input_labels().gpu()
        self.input_ids = self.input_input_ids().gpu()
        self.input_mask = self.input_input_mask().gpu()

        images = self.decode(self.raw_images)
        images = self.res(images)
        images = self.cmnp(images, mirror=rng)
        
        return images, self.labels, self.input_ids, self.input_mask

    def iter_setup(self):
        try:
            data_dict = next(self.data_iter)
            images = data_dict["image"]
            labels = data_dict["label"]
            input_ids = data_dict["input_ids"]
            input_mask = data_dict["input_mask"]

            self.feed_input(self.raw_images, images)
            self.feed_input(self.labels, np.array(labels))
            self.feed_input(self.input_ids, np.array(input_ids))
            self.feed_input(self.input_mask, np.array(input_mask))

        except StopIteration:
            self.data_iter = iter(self.external_data)
            raise StopIteration
```

**Comment by shanesyy-1992** [comment]
> One thing to try would be to change the prefetching queue depth of the DALI pipeline.
> Also, if you have control of your data source and you can guarantee that the input buffer is alive and unmodified throughout the iteration, then you could try `no_copy` option in ExternalSource.

Thanks a lot for your suggestions! We'll do some test to see if they work, and update here late.

**Comment by JanuszL** [comment]
Hi,
`ExternalSource` is fully synchronous with the main Python thread and doesn't scale with the number of thread DALI uses. We will address this in [this PR](https://github.com/NVIDIA/DALI/pull/2543).
In the meantime, you can check if you can replace ExternalSource with FileReader/NumpyReader, pass the list of files to the `files` argument, and set the same seed to all readers so they work in sync. The native readers work in the background and don't block the main python thread.

**Comment by shanesyy-1992** [comment]
> Hi,
> `ExternalSource` is fully synchronous with the main Python thread and doesn't scale with the number of thread DALI uses. We will address this in [this PR](https://github.com/NVIDIA/DALI/pull/2543).

Thanks a lot for pointing out! It seems promising! Looking forward to it!

> In the meantime, you can check if you can replace ExternalSource with FileReader/NumpyReader, pass the list of files to the `files` argument, and set the same seed to all readers so they work in sync. The native readers work in the background and don't block the main python thread.

Unfortunately, our data is now on HDFS so we can only read the data into memory first and then feed it into dali pipeline. It would be great if DALI could provide HDFS reader directly, but I think so far we have to tolerate the ExternalSource overhead and wait for its new `parallel` feature.

**Comment by JanuszL** [comment]
1.0 has been released and it should address this issue.
