### ISSUE TITLE
Chain Ops versus using prechained ops

### ISSUE THREAD

**Issue by Data-drone** [NVIDIA/DALI#2590]
I notice that there is `ImageDecoder`, `Crop` and `ImageDecoderCrop`

is chaining up `ImageDecoder` and `Crop` equivalent to `ImageDecoderCrop` or are there extra enhancements that make `ImageDecoderCrop` work faster than chaining the separate ops?

**Comment by jantonguirao** [comment]
In the case of JPEG images, `ImageDecoderCrop` will perform partial decoding of only the selected region of interest (the cropping window), as opposed to first decode the whole image (ImageDecoder) and later crop it (Crop). You also eliminate the intermediate step, reducing the memory requirements.
