### ISSUE TITLE
SsdRandomCrop with keypoints/coco polygon mask

### ISSUE THREAD

**Issue by vladpaunescu** [NVIDIA/DALI#2593]
Hello! 

I'm trying to modify the `dali/operators/ssd/random_crop.cc` with Cropping on segmentations masks provided by polygon vertices.  I need this feature since I'm also predicting object keypoints besides bbox, but since there is no support for keypoint in cocoreader, I've decided to use COCO mask encoded as list of polygons. 

Unfortunately I stumbled when I found there no support for SsdRandomCrop for mask polygons, besides bbox, label, img.

I also have a question regarding debugging and docker. How can we debug C++ code (I'm using vscode) using docker?
Is there any C driver code? I have compiled DALI from sources using Docker https://docs.nvidia.com/deeplearning/dali/user-guide/docs/compilation.html 
Since there si no C++ API, I was wondering how I can debug the code, preferably inside `docker`.

**Comment by JanuszL** [comment]
Hi,

That is true, SsdRandomCrop lacks support for polygons. What you can do is:
- add a render operation and convert mask into the image and then process it as any other image
- crop list of vertices directly. However this leads to problems with what to do when only part of the polygon is cut - would this discard only a selected vertice, and/or create new vertices in the intersection of crop window and polygon edge, or discard the whole polygon?
When you finish your work and you think that other DALI user may benefit from it feel free to post a PR to DALI main repo.

Regarding debugging in the container - please check [this Visual Studio code guide](https://code.visualstudio.com/docs/remote/containers) first. When you compiling using this guide you can run manually the docker in the interactive mode and mount your source code inside, the command would be something like (the exact command is print when you invoke build.sh script from the mentioned guide):
```docker run --rm -ti -u 1000:1000 -v /Dali/dali:/opt/dali nvidia/dali:cu111_x86_64.build```.
