### ISSUE TITLE
Repeat batch n times

### ISSUE THREAD

**Issue by ben0it8** [NVIDIA/DALI#2594]
Hi,

Is there a way to replicate a batch of data n times along axis 0 with the existing ops? With PythonOperator and cupy its trivial to do so, but as far as I know PythonOperator is not compatible with the tf.data API.

Cheers,
Oliver

**Comment by JanuszL** [comment]
I don't think I fully understand what you want to do? Do you want to replicate the first sample in the whole batch?
Could you give a particular example of what you want to achieve (pseudo-code would do)?

**Comment by ben0it8** [comment]
Given a tensor of shape `B, H, W, C` I'd like to make it `n * B, H, W, C`.

Somethling like numpy/cupy.repeat: https://docs.cupy.dev/en/stable/reference/generated/cupy.repeat.html

**Comment by JanuszL** [comment]
So you want to create from a batch of tensor a batch of sequences?
If so please use Stack/Cat operators.

**Comment by ben0it8** [comment]
Well rather "repeat a batch of data along axis 0 n times".

Assuming `cat_op = ops.Cat(axis=0)` is it valid to do `x = cat_op([x for _ in range(n)])` or alike in the graph?

**Comment by JanuszL** [comment]
Rather something like:
```
cat_op(*[x for _ in range(n)])
```
As cat doesn't accept list but positional arguments.

**Comment by ben0it8** [comment]
See, thanks Janusz! :+1:
