### ISSUE TITLE
Ｈｏｗ to get images labels by ops.FileReader?

### ISSUE THREAD

**Issue by yjjiang11** [NVIDIA/DALI#260]
when I get to know the method 'ops.FileReader', which has parameter 'file_list'.
my code is as follows:
```python
   self.input = ops.FileReader(file_root = image_dir,file_list=file_list)
```
but got error:
RuntimeError: [/opt/dali/dali/pipeline/operators/reader/loader/file_loader.h:109] Assert on "s.is_open()" failed
The problem is about file_list.
if remove file_list, it works well,but the label the FileReader it returns is not expected.

**Comment by JanuszL** [comment]
If that doesn't help you please reopen.

**Comment by XiaoqiangZhou** [comment]
@yjjiang11 Hi, I meet the same problem. Could you please tell me how did you solve it?

**Comment by JanuszL** [comment]
@XiaoqiangZhou - please check [this example](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/getting%20started.html#Defining-the-pipeline) and [this file](https://github.com/NVIDIA/DALI/blob/master/docs/examples/images/file_list.txt).

**Comment by XiaoqiangZhou** [comment]
@JanuszL Got it! Thanks for your help~
