### ISSUE TITLE
RandomResizedCrop fixed seed not fixed crop region

### ISSUE THREAD

**Issue by guanfuchen** [NVIDIA/DALI#2601]
```
        ops.RandomResizedCrop(
            size=(image_size, image_size),
            random_area=resize_scale,
            random_aspect_ratio=resize_ratio,
            seed=seed,
            num_attempts=100,
            device=device,
            interp_type=interp_types[interp_type],
        ),
```
I fix the seed for the same image, but I get different results for every iteration. What should I do for the fixed seed. I want to use DALI for self supervised learning data transformations, so two views must be different using different size, now the acc is lower than origin torchvision implementation. But I have checked every transformation.

**Comment by JanuszL** [comment]
Hi,
`seed` sets only the initial state of the operator. So if you run the training with the same sequence of images the RandomResizedCrop would be repeatable between training. Setting seed doesn't strip randomness from the operator, so the operation result still differs from sample to sample, iteration to iteration.
If you want to debug `RandomResizedCrop` I would replace it with crop and resize to get deterministic results.

**Comment by guanfuchen** [comment]
I think DALI will be great for SimCLR or BYOL transformation later.
