### ISSUE TITLE
total_time does not integrate with checkpointing in RESNET training on imagenet

### ISSUE THREAD

**Issue by dariodematties** [NVIDIA/DALI#2603]
Hi
I am  analyzing [this example](https://github.com/NVIDIA/DALI/blob/2a85811d379f07cd94de9265eabf28b6d4e38f77/docs/examples/use_cases/pytorch/resnet50/main.py#L340) in your repo.

In [this line](https://github.com/NVIDIA/DALI/blob/2a85811d379f07cd94de9265eabf28b6d4e38f77/docs/examples/use_cases/pytorch/resnet50/main.py#L340) you initialize `total_time` which is an `AverageMeter` class that keeps track of the time the network takes to train during one batch.

Please, correct me if I am wrong but the issue I am seeing here is that this variable does not integrate well with checkpointing, since if the run ends prematurely for some reason,  total time starts from scratch no mater the starting epoch

Another point is that in order to make `total_time.sum` be the complete time of the training process, in [this line of code](https://github.com/NVIDIA/DALI/blob/2a85811d379f07cd94de9265eabf28b6d4e38f77/docs/examples/use_cases/pytorch/resnet50/main.py#L442), shouldn't it be `batch_time.update((time.time() - end)/args.print_freq, args.print_freq)`?

Could it be right?
Thanks!

**Comment by JanuszL** [comment]
Hi,
You are right. These statistics disregard checkpoints. The goal of this script is to show how to integrate DALI with a classification network, like ResNet50, and it is based on this [example](https://github.com/NVIDIA/apex/blob/master/examples/imagenet/main_amp.py) from [APEX repository](https://github.com/NVIDIA/apex).
If you feel that this functionality is critical feel free to post PR and enhance this training script.
