### ISSUE TITLE
How to read video file with DALI by skipped keyframes

### ISSUE THREAD

**Issue by tonnywang** [NVIDIA/DALI#2604]
This is demo script with imageio to load video file by skipping keyframes. **As the below, how to use DALI to load video file with the specific frames.**

Demo script:

   import imageio
   import cv2
   file_dir = './UCF-101/ApplyEyeMakeup/v_ApplyEyeMakeup_g02_c01.avi'
   frame_dir = './images'
  try:
       with imageio.get_reader(file_dir, 'ffmpeg') as vid:
           **frames_indices = [10, 20]**
           for i in frames_indices:
               **frame = vid.get_data(i)**
               frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
               cv2.imshow('frame',frame_rgb)
              cv2.waitKey(1)
             cv2.destroyAllWindows()
    except Exception as error:
        print('runtime error:', file_dir, str(error))

**Comment by JanuszL** [comment]
Hi,
Please check the documentation of the [VideoReader operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.ops.VideoReader). Using `step`, `stride` and `sequence_length` you can control what sequences you get. You can also use `file_list` and provide a fine-grained description in the `file label [start_frame [end_frame]]` format so you can ask to extract sequences from given fragments of the video files. However, it is not possible to pass an arbitrary set of frames.
If you think that others may benefit from such functionality we would be more than happy to review and accept a PR that adds it.

**Comment by tonnywang** [comment]
@JanuszL Thanks your reply. This is for the case of TSN model,  it needs to extract the specific frames, such as 16 or 32 frames, but these frames are not continuous. I think these are typical cases for extracting frames, such as dense samples or sparse samples in a video. It is useful for some DNN models training in video applications.
  If latest DALI version does not have this function, could you please give some workarounds to handle this case.

**Comment by JanuszL** [comment]
If you need sequence assembled from random frames then there is no applicable WAR for now. If you are fine to have these random frames in separate samples `file_list` argument is the best option, then you set `sequence_length` to 1 and specify allowed frames in the provided file.

**Comment by tonnywang** [comment]
@JanuszL To summarize my understanding,  i.e. for 16 frames' case in one video, we can set up 16 VideoReader instances with the video file, and each VideoReader instance only extract one frame, right?
If so, could you please give some demo configuration parameters, I will try it. Thanks

**Comment by JanuszL** [comment]
> To summarize my understanding, i.e. for 16 frames' case in one video, we can set up 16 VideoReader instances with the video file, and each VideoReader instance only extract one frame, right?

Not really. I would recommend sticking to only one VideoReader instance. And the file that you set `sequence_length` to 1 and provide in the `file_list` argument can look like (based on [this example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/sequence_processing/video/video_file_list_outputs.html):
```
your_file 0 0 1
your_file 0 10 11
your_file 0 22 13
your_file 0 34 35
```
So your batch would consist of 1 frame videos (in random order) in each sample [0, 10, 22, 34].
It is what you are asking for?

**Comment by tonnywang** [comment]
model training batch size is given in advance, such as 16, or 32, etc. so Video Reader instance can also take 16 or 32 video files, right?  for multi video files case, could you please give reference configuration.

**Comment by JanuszL** [comment]
Batch size is set in a separate argument. Feel free to set it to 16 or 32 depending on your network.
For multi configuration just use:
```
your_file_1 0 0 1
your_file_2 0 10 11
your_file_3 0 22 13
your_file_3 0 34 35
...
```
> Another issue, for extracted samples of each video , whether the order of samples is consistent with file list order? model training need to keep samples order according to file list

If you set `shuffling` to False it should follow the order.

**Comment by tonnywang** [comment]
@JanuszL Thanks,  the new demo script is as the below, but there are still some error. could you please help to check issues.
  from __future__ import print_function
  from __future__ import division
  import numpy as np
  from nvidia.dali.pipeline import Pipeline
  import nvidia.dali.ops as ops
  import nvidia.dali.types as types
  import time
  import tempfile

  file_dir_1 = './data/HtyahZRL330KBiXim10ywnp5h2I.mp4'
  file_dir_2 = './data/NdsHw-VJw9ugtRS4XasIE3KvYK4.mp4'
  indices_1 = [200, 600, 1200, 1600, 2000, 2400, 2900, 3300, 3700, 4100, 4500, 4900, 5300, 5700, 6100, 6500]  # 7478
  label_1 = 1
  indices_2 = [50, 170, 290, 410, 530, 650, 770, 890, 1010, 1130, 1250, 1370, 1490, 1610, 1730, 1850]  # 1862
  label_2 = 0
  # frame_dir = './dali-output'

 class VideoPipe(Pipeline):
     def __init__(self, batch_size, num_threads, device_id, data, shuffle):
          super(VideoPipe, self).__init__(batch_size, num_threads, device_id, seed=16)
          self.input = ops.VideoReader(device="gpu", file_list=data, sequence_length=1,
                                     shard_id=0, num_shards=1,enable_frame_num=True,
                                     file_list_frame_num=True,
                                     random_shuffle=shuffle, initial_fill=1)

      def define_graph(self):
          output = self.input(name="Reader")
          return output

count = 0
for index in indices_1:
    if count == 0:
        vid_frames_list = file_dir_1 + " " + str(label_1) + " " + str(index) + " " + str(int(index)+1) + "\n"
    else:
        vid_frames_list += file_dir_1 + " " + str(label_1) + " " + str(index) + " " + str(int(index)+1) + "\n"
    count += 1

for index in indices_2:
    vid_frames_list += file_dir_2 + " " + str(label_2) + " " + str(index) + " " + str(int(index) + 1) + "\n"

tf = tempfile.NamedTemporaryFile()
tf.write(str.encode(vid_frames_list))
tf.flush()

pipe = VideoPipe(batch_size=1, num_threads=4, device_id=0, data=vid_frames_list, shuffle=False)
pipe.build()

time_dali = []

for index in range(5):
    st = time.time()
    # print(index)
    sequences_out = pipe.run()[0].as_cpu().as_array()
    time_dali.append(time.time() - st)

print('DALI: {} sec'.format(np.mean(time_dali)))


**The error messages**:
Traceback (most recent call last):
  File "dali_video_read_v2.py", line 50, in <module>
    pipe.build()
  File "/usr/local/lib/python3.6/dist-packages/nvidia/dali/pipeline.py", line 481, in build
    self._pipe.Build(self._names_and_devices)
RuntimeError: Critical error when building pipeline:
Error when constructing operator: VideoReader encountered:
[/opt/dali/dali/operators/reader/loader/video_loader.cc:147] Assert on "s.is_open()" failed: ./data/HtyahZRL330KBiXim10ywnp5h2I.mp4 1 200 201
./data/HtyahZRL330KBiXim10ywnp5h2I.mp4 1 600 601
./data/HtyahZRL330KBiXim10ywnp5h2I.mp4 1 1200 1201
./data/HtyahZRL330KBiXim10ywnp5h2I.mp4 1 1600 1601
./data/HtyahZRL330KBiXim10ywnp5h2I.mp4 1 2000 2001
./data/HtyahZRL330KBiXim10ywnp5h2I.mp4 1 2400 2401
./data/HtyahZRL330KBiXim10ywnp5h2I.mp4 1 2900 2901
./data/HtyahZRL330KBiXim10ywnp5h2I.mp4 1 3300 3301
./data/HtyahZRL330KBiXim10ywnp5h2I.mp4 1 3700 3701
./data/HtyahZRL330KBiXim10ywnp5h2I.mp4 1 4100 4101
./data/HtyahZRL330KBiXim10ywnp5h2I.mp4 1 4500 4501
./data/HtyahZRL330KBiXim10ywnp5h2I.mp4 1 4900 4901
./data/HtyahZRL330KBiXim10ywnp5h2I.mp4 1 5300 5301
./data/HtyahZRL330KBiXim10ywnp5h2I.mp4 1 5700 5701
./data/HtyahZRL330KBiXim10ywnp5h2I.mp4 1 6100 6101
./data/HtyahZRL330KBiXim10ywnp5h2I.mp4 1 6500 6501
./data/NdsHw-VJw9ugtRS4XasIE3KvYK4.mp4 0 50 51
./data/NdsHw-VJw9ugtRS4XasIE3KvYK4.mp4 0 170 171
./data/NdsHw-VJw9ugtRS4XasIE3KvYK4.mp4 0 290 291
./data/NdsHw-VJw9ugtRS4XasIE3KvYK4.mp4 0 410 411
./data/NdsHw-VJw9ugtRS4XasIE3KvYK4.mp4 0 530 531
./data/NdsHw-VJw9ugtRS4XasIE3KvYK4.mp4 0 650 651
./data/NdsHw-VJw9ugtRS4XasIE3KvYK4.mp4 0 770 771
./data/NdsHw-VJw9ugtRS4XasIE3KvYK4.mp4 0 890 891
./data/NdsHw-VJw9ugtRS4XasIE3KvYK4.mp4 0 1010 1011
./data/NdsHw-VJw9ugtRS4XasIE3KvYK4.mp4 0 1130 1131
./data/NdsHw-VJw9ugtRS4XasIE3KvYK4.mp4 0 1250 1251
./data/NdsHw-VJw9ugtRS4XasIE3KvYK4.mp4 0 1370 1371
./data/NdsHw-VJw9ugtRS4XasIE3KvYK4.mp4 0 1490 1491
./data/NdsHw-VJw9ugtRS4XasIE3KvYK4.mp4 0 1610 1611
./data/NdsHw-VJw9ugtRS4XasIE3KvYK4.mp4 0 1730 1731
./data/NdsHw-VJw9ugtRS4XasIE3KvYK4.mp4 0 1850 1851
 could not be opened.
Stacktrace (28 entries):
[frame 0]: /usr/local/lib/python3.6/dist-packages/nvidia/dali/libdali_operators.so(+0x401dee) [0x7f55c61a7dee]
[frame 1]: /usr/local/lib/python3.6/dist-packages/nvidia/dali/libdali_operators.so(+0x2337340) [0x7f55c80dd340]
[frame 2]: /usr/local/lib/python3.6/dist-packages/nvidia/dali/libdali_operators.so(+0x2375129) [0x7f55c811b129]
[frame 3]: /usr/local/lib/python3.6/dist-packages/nvidia/dali/libdali_operators.so(+0x2376b02) [0x7f55c811cb02]
[frame 4]: /usr/local/lib/python3.6/dist-packages/nvidia/dali/libdali_operators.so(+0x2378352) [0x7f55c811e352]
[frame 5]: /usr/local/lib/python3.6/dist-packages/nvidia/dali/libdali_operators.so(std::_Function_handler<std::unique_ptr<dali::OperatorBase, std::default_delete<dali::OperatorBase> > (dali::OpSpec const&), std::unique_ptr<dali::OperatorBase, std::default_delete<dali::OperatorBase> > (*)(dali::OpSpec const&)>::_M_invoke(std::_Any_data const&, dali::OpSpec const&)+0xc) [0x7f55c61a442c]
[frame 6]: /usr/local/lib/python3.6/dist-packages/nvidia/dali/libdali.so(+0x157e61) [0x7f55c4ff5e61]
[frame 7]: /usr/local/lib/python3.6/dist-packages/nvidia/dali/libdali.so(dali::InstantiateOperator(dali::OpSpec const&)+0x25b) [0x7f55c4ff547b]
[frame 8]: /usr/local/lib/python3.6/dist-packages/nvidia/dali/libdali.so(dali::OpGraph::InstantiateOperators()+0xa2) [0x7f55c4fa7ed2]
[frame 9]: /usr/local/lib/python3.6/dist-packages/nvidia/dali/libdali.so(dali::Pipeline::Build(std::vector<std::pair<std::string, std::string>, std::allocator<std::pair<std::string, std::string> > >)+0x9f0) [0x7f55c5014f90]
[frame 10]: /usr/local/lib/python3.6/dist-packages/nvidia/dali/backend_impl.cpython-36m-x86_64-linux-gnu.so(+0x45c9f) [0x7f55e95d9c9f]
[frame 11]: /usr/local/lib/python3.6/dist-packages/nvidia/dali/backend_impl.cpython-36m-x86_64-linux-gnu.so(+0x890dc) [0x7f55e961d0dc]
[frame 12]: python3(_PyCFunction_FastCallDict+0x35c) [0x565d5c]
[frame 13]: python3() [0x503073]
[frame 14]: python3(_PyEval_EvalFrameDefault+0x449) [0x506859]
[frame 15]: python3() [0x504c28]
[frame 16]: python3() [0x502540]
[frame 17]: python3() [0x502f3d]
[frame 18]: python3(_PyEval_EvalFrameDefault+0x449) [0x506859]
[frame 19]: python3() [0x504c28]
[frame 20]: python3(PyEval_EvalCode+0x23) [0x506393]
[frame 21]: python3() [0x634d52]
[frame 22]: python3(PyRun_FileExFlags+0x9a) [0x634e0a]
[frame 23]: python3(PyRun_SimpleFileExFlags+0x188) [0x6385c8]
[frame 24]: python3(Py_Main+0x57a) [0x63915a]
[frame 25]: python3(main+0xe0) [0x4a6f10]
[frame 26]: /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f5621aa5bf7]
[frame 27]: python3(_start+0x2a) [0x5afa0a]

Current pipeline object is no longer valid.

**Comment by JanuszL** [comment]
> @JanuszL the script can work now. But it meets another issues, the ops.VideoReader only loaded one frame per each sequence with batch size, 1 , and sequence length, 1, and file_list, 32 lines. If the whole 32 lines in file_list needs to be loaded per Pipeline run, how to set the input parameters?

If I understand correctly your ask please just change the batch size to 32. Then you get 32 samples, 1 frame each.

**Comment by tonnywang** [comment]
@JanuszL yes, I just set the batch size with 32, thanks.
