### ISSUE TITLE
Iterator returns wrong length when last batch policy is drop

### ISSUE THREAD

**Issue by rsaite** [NVIDIA/DALI#2607]
When creating a DALI iterator with `LastBatchPolicy.DROP`, the iterator returns a wrong length value which counts the last (dropped) batch.

Here is the code in question from [base_iterator.py](https://github.com/NVIDIA/DALI/blob/9dbfe386da7be747af1121eddfc33435157fc2b6/dali/python/nvidia/dali/plugin/base_iterator.py#L362), lines 362-366 where `math.ceil` accounts for the last (possibly incomplete and dropped) batch:
```
    def __len__(self):
        if self._reader_name:
            return math.ceil(self.size / self.batch_size)
        else:
            return math.ceil(self.size / (self._num_gpus * self.batch_size))
```

I think it should be something like this:
```
    def __len__(self):
        if self._reader_name:
            full_batches = self._size // self.batch_size
            remaining_samples = self._size % self.batch_size
            drop = self._last_batch_policy == LastBatchPolicy.DROP
            last_batch = 1 if (remaining_samples > 0 and not drop) else 0
        else:
            full_batches = self._size // (self._num_gpus * self.batch_size)
            remaining_samples = self._size % (self._num_gpus * self.batch_size)
            drop = self._last_batch_policy == LastBatchPolicy.DROP
            last_batch = 1 if (remaining_samples > 0 and not drop) else 0
        return full_batches + last_batch

```
This at least fixes the issue for my use case where I pad the last batch and has also been applied here: [PyTorch Lightning PR #4925](https://github.com/PyTorchLightning/pytorch-lightning/pull/4925)

**Comment by JanuszL** [comment]
Hi,
Good catch. We will prepare the fix and let you know when it is ready.

**Comment by klecki** [comment]
DALI 0.31.0 has been released. It fixes the reported issue.
