### ISSUE TITLE
The data time goes longer after several iterations when training on ImageNet

### ISSUE THREAD

**Issue by SkeletonOne** [NVIDIA/DALI#2608]
Hi, I am using DALI on training imagenet with resnet50. I use 8 V100 gpus with batch size 256. and I observe something like this:

    Epoch 1/30
    Current time: 2021-01-13 01:36:30
    Epoch: [1][0/5005]	Time 0.414 (0.414)	Data 0.001 (0.001)	Loss 1.0910 (1.0910)	Prec@1 72.656 (72.656)	Prec@5             
    89.062 (89.062)
    Epoch: [1][20/5005]	Time 0.200 (0.186)	Data 0.045 (0.040)	Loss 1.2701 (1.0801)	Prec@1 71.875 (74.554)	Prec@5 
    87.500 (90.123)
    Epoch: [1][40/5005]	Time 0.170 (0.178)	Data 0.045 (0.041)	Loss 1.5020 (1.1632)	Prec@1 65.625 (72.713)	Prec@5 
    83.984 (89.139)
    Epoch: [1][60/5005]	Time 0.169 (0.177)	Data 0.046 (0.043)	Loss 1.3916 (1.2151)	Prec@1 65.234 (71.100)	Prec@5 
    87.500 (88.653)
    Epoch: [1][80/5005]	Time 0.168 (0.176)	Data 0.046 (0.044)	Loss 1.3164 (1.2476)	Prec@1 69.141 (70.158)	Prec@5 
    87.891 (88.334)
    Epoch: [1][100/5005]	Time 8.719 (0.361)	Data 8.597 (0.230)	Loss 1.2987 (1.2753)	Prec@1 69.141 (69.524)	Prec@5 
    86.328 (87.891)
    Epoch: [1][120/5005]	Time 8.955 (1.784)	Data 8.831 (1.654)	Loss 1.2661 (1.2975)	Prec@1 70.312 (68.895)	Prec@5 
    87.500 (87.668)
    Epoch: [1][140/5005]	Time 8.576 (2.767)	Data 8.436 (2.637)	Loss 1.5963 (1.3146)	Prec@1 62.109 (68.442)	Prec@5 
    83.984 (87.447)

where Data is the data time. So it becomes very slow after several iters. Below is my code:

    class HybridTrainPipe(Pipeline):
        def __init__(self, batch_size, num_threads, device_id, data_dir, crop, dali_cpu=False, local_rank=0, world_size=1):
            super(HybridTrainPipe, self).__init__(batch_size, num_threads, device_id, seed=12 + device_id)
            dali_device = "gpu"
            self.input = ops.FileReader(file_root=data_dir, shard_id=local_rank, num_shards=world_size, random_shuffle=True)
            self.decode = ops.ImageDecoder(device="mixed", output_type=types.RGB)
            self.res = ops.RandomResizedCrop(device="gpu", size=crop, random_area=[0.08, 1.25])
            self.cmnp = ops.CropMirrorNormalize(device="gpu",
                                            dtype=types.FLOAT,
                                            output_layout=types.NCHW,
                                            mean=[0.485 * 255, 0.456 * 255, 0.406 * 255],
                                            std=[0.229 * 255, 0.224 * 255, 0.225 * 255])
            self.coin = ops.CoinFlip(probability=0.5)
            print('DALI "{0}" variant'.format(dali_device))

        def define_graph(self):
            rng = self.coin()
            self.jpegs, self.labels = self.input(name="Reader")
            images = self.decode(self.jpegs)
            images = self.res(images)
            output = self.cmnp(images, mirror=rng)
            return [output, self.labels]

    pip_train = HybridTrainPipe(batch_size=256, num_threads=4, device_id=0,
                                    data_dir=image_dir + '/train',
                                    crop=224, world_size=1, local_rank=0)
    pip_train.build()
    dali_iter_train = DALIClassificationIterator(pip_train, size=pip_train.epoch_size("Reader") // world_size)

Could you please help? Thanks!

**Comment by JanuszL** [comment]
Hi,

It looks like you are blocked by the disc IO. Where you have your data stored? NVME storage or some network one?
I would check [IO utilization][(https://unix.stackexchange.com/questions/55212/how-can-i-monitor-disk-io). As soon as your data is cached in RAM (disc cache) the perf should go up. I don't think DALI can do much about your IO access time.

**Comment by JanuszL** [comment]
Please reopen when you can provide more info about your issue.
