### ISSUE TITLE
The speed of loading data to memory is very slow?

### ISSUE THREAD

**Issue by zhiheng-ldj** [NVIDIA/DALI#2624]
Hi,

Thanks for your time for this issue.

I encountered a problem that when I load my dataset (batches of images and npy data) to memory, the speed is very slow. Is it normal?

I set read_ahead=True for each ops.FileReader and ops.NumpyReader.

Here is the monitor image:

![截屏2021-01-21 下午5 28 07](https://user-images.githubusercontent.com/67734380/105331141-14037300-5c0e-11eb-9f0a-faa14b1c31ee.png)

Thanks!

**Comment by JanuszL** [comment]
Hi @zhiheng-ldj,
Can you provide a simple, self-contained repro?
Can you check your IO utilization - maybe your processing is blocked by slow disc access?
You can read more about this in [this thread](https://unix.stackexchange.com/questions/55212/how-can-i-monitor-disk-io).

**Comment by zhiheng-ldj** [comment]
> Hi @zhiheng-ldj,
> Can you provide a simple, self-contained repro?
> Can you check your IO utilization - maybe your processing is blocked by slow disc access?
> You can read more about this in [this thread](https://unix.stackexchange.com/questions/55212/how-can-i-monitor-disk-io).

Thanks for your help.

That is exactly the reason. However, the loading time of torch dataloader is about 3 minutes for whole dataset. Is there any difference for loading data to memory through GPU or CPU?

PS, here is the iostat monitor:

![截屏2021-01-21 下午5 45 49](https://user-images.githubusercontent.com/67734380/105333298-86755280-5c10-11eb-857d-99accaa4e34c.png)

Thanks!!

**Comment by JanuszL** [comment]
If I read your measurement correctly it seems that there is very little time spent on waiting for IO, for most of the time the process is idle.
It is hard to tell more without a minimal repro code.

**Comment by JanuszL** [comment]
Please reopen when you can provide more details.
