### ISSUE TITLE
Is it thread safe to call Pipeline.run from multiple threads ?

### ISSUE THREAD

**Issue by aljeshishe** [NVIDIA/DALI#2627]
1. I'm using keras and I'm specifying workers parameter in Model.fit method. This leads to calls to Pipeline.schedule_run from multiple threads. Is it thread safe ? 
2. It looks like schedule_run is not truly async, because it also get data from external source. Is it ok if I call Pipeline.schedule_run from one thread(producer) and Pipeline.share_outputs from other thread(consumer)?

**Comment by JanuszL** [comment]
> I'm using keras and I'm specifying workers parameter in Model.fit method. This leads to calls to Pipeline.schedule_run from multiple threads. Is it thread safe ?

I don't think this is what you rely on want. As I understand Keras assumes that each worker returns a sample, so multiple threads will process the whole batch faster. In the case of DALI threading is a build-in feature, and it returns a whole batch at the time.

> It looks like schedule_run is not truly async, because it also get data from external source. Is it ok if I call Pipeline.schedule_run from one thread(producer) and Pipeline.share_outputs from other thread(consumer)?

In the case of the ExternalSource operator, it is true, if you use the build-in reader like FileReader it should be fully async. We haven't tested running `schedule_run` and `share_outputs` from multiple threads. They both modify the state of the python pipeline wrapper so it can be inconsistent if you do it from separate threads so I would not recommend it. We have a PR that should make ExternalSource asynchronous https://github.com/NVIDIA/DALI/pull/2543. I would recommend waiting for it to be available in the nightly build and check if that helps you.

**Comment by JanuszL** [comment]
Hi,

The most recent improvements of [the `external_source` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.external_source) make it parallel to the training and scales with the number of CPUs. Please check `parallel` and `prefetch_queue_depth` options.
