### ISSUE TITLE
Dynamic input from operator

### ISSUE THREAD

**Issue by edwin-19** [NVIDIA/DALI#2633]
Hi, I've got a question, to my understanding any operator i run in the graph will automatically become a DataNode object, is there any way to extract the value of that data node and pass an input for a different operator?

```python
pad_w = fn.cast((width / stride) * stride, dtype=types.INT64)
resized = fn.pad(images, shape=[3, pad_w, 1280]) # Pad expects an input of int
```

Would appreciate it if someone could give some pointers, or is it not possible with the current api?

**Comment by JanuszL** [comment]
Hi,
You should create a tensor using cat operator, like:
```
pad_w = fn.cast((width // stride) * stride, dtype=types.INT32)
new_shape = fn.cat(3, pad_w, 1280)
resized = fn.pad(images,, shape = new_shape )
```
You may also look into the `align` argument to see if that does what you try to achieve using pad_w.

**Comment by edwin-19** [comment]
Hi, firstly thanks for the response,
Secondly i ran to another problem, it crashes when i try to add the converted input to the cat operator:



I have attached the full code below in case you need to reference.
```python
pipeline = Pipeline(batch_size=32, num_threads=4, device_id=0)
with pipeline:
    jpegs, _ = fn.file_reader(files=[file])
    images = fn.image_decoder(jpegs, device='cpu', output_type=types.RGB)
    
    shapes = fn.cast(fn.peek_image_shape(jpegs), dtype=types.FLOAT)  # shape is HWC
    
    w = fn.slice(shapes, 1, 1, axes=[0])  # extract width
    h = fn.slice(shapes, 0, 1, axes=[0])  # extract height
    wh = fn.cat(w, h, axis=0)
    
    max_size = 1280
    min_original_size = fn.reductions.min(wh)
    max_original_size = fn.reductions.max(wh)
    ratio = max_size / max_original_size
    
    if w < h:
        ow = ratio * min_original_size 
        oh = max_size
    else:
        ow = ratio * min_original_size 
        oh = max_size
    
    resized = fn.resize(images, resize_x=ow, resize_y=oh)
    resized = resized / 255.
    resized = fn.crop_mirror_normalize(
        resized,
        pad_output=False,
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225],
        output_layout=types.NCHW
    )
    
    # Pad image
    stride = 32
    width = fn.cast(ow, dtype=types.INT32)
    pad_w = fn.cast((width / stride) + 0.5, dtype=types.INT32) # Ceiling cast
    pad_w = pad_w * stride
    pad_shape = fn.cat(3, pad_w, 1280) # Crashes here but if i hard code with a value it works
    resized = fn.pad(resized, shape=pad_shape)
    pipeline.set_outputs(resized, pad_shape)

```

**Comment by JanuszL** [comment]
Hi,
Runtime `if` condition is not supported in the pipeline definition. In the incoming release, you should get a more verbose message with an error like this.
Maybe I'm missing something but what exactly you want to do with this if statement?

**Comment by edwin-19** [comment]
Well to be honest i am converting a preprocessing code for a pytorch model i'm currently using and part of the resizing involves if statements so i am trying to replicate it as close as possible

**Comment by JanuszL** [comment]
I mean that both branches of your if statement looks the same, but I guess you just want to resize in such a way that the longer edge of the image is `max_size`.
I think this whole logic can be handled by the resize operator itself. Please check [resize tutorial](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/image_processing/resize.html#Scaling-modes), especially focus on `not_larger` mode.

**Comment by edwin-19** [comment]
Oo yea i had a typo on my if statement but yes i wanted to keep the longer edge as max size. 

Ok thanks for clearing up the issue. And the usage of if statements

**Comment by edwin-19** [comment]
I will close this for now will see if theres any further issues

**Comment by greaber** [comment]
Fwiw, I hit this using the audio resampler.  It would be nice to let the caller specify the quality parameter, but I have to hard-code it.  It's not a big deal for us, but it would be great if a future version of Dali could get rid of this limitation of various things having to be defined at pipeline creation

**Comment by JanuszL** [comment]
Hi @greaber,

Thank you for your feedback. Can you create a separate issue with RFE so we can track this?
