### ISSUE TITLE
The pytorch-external example seems to be wrong

### ISSUE THREAD

**Issue by cfzd** [NVIDIA/DALI#2639]
Hi, I found that the [example of the PyTorch ExternalSource operator](https://github.com/NVIDIA/DALI/blob/master/docs/examples/frameworks/pytorch/pytorch-external_input.ipynb) seems to be wrong. The `StopIteration` will never be triggered, as the red rectangle shows.

Moreover, the `ExternalInputIterator` can only shuffle the data for one time as the green rectangle shows. Is it possible to shuffle the data every epoch?
![image](https://user-images.githubusercontent.com/17758403/105958536-b3fd4880-60b5-11eb-8064-a78a987c89c3.png)

**Comment by JanuszL** [comment]
Hi,
Good catch. Let me fix it and get back to you soon.

**Comment by JanuszL** [comment]
https://github.com/NVIDIA/DALI/pull/2641 should address this issue
