### ISSUE TITLE
Recommended Input Formats?

### ISSUE THREAD

**Issue by dreavjr** [NVIDIA/DALI#2647]
If I have the luxury of the choice, is there a recommended default input format / reader? (E.g., maybe ____Reader is the fastest reader?) 

Or maybe there's a recommended input format for a given scenario (E.g., use Caffe2Reader for a lot of small records but NumpyReader for a few big samples?) Or maybe for a given platform/hardware (E.g., HD vs SSD?)

Or maybe that choice makes no actual difference?

**Comment by JanuszL** [comment]
Hi,
I would recommend using fast storage, so rather SSD in RAID than a traditional HDD. Also, the rule of thumb is that reading data from the container - like RecordIO, TFRecord, or LMDB would be faster than separate files.
What we usually see is that if you have enough RAM after the first epoch the data would be cached by OS and the real IO access speed would not matter anymore for the rest of the training.
