### ISSUE TITLE
cannot build pipeline on jetson xavier nx

### ISSUE THREAD

**Issue by ymdyt** [NVIDIA/DALI#2649]
Hi,
Thanks for your help.

I installed dali on jetson and followed the tutorial to define a pipeline, and encountered the following error.

```
read 10 files from 1 directories
Traceback (most recent call last):
  File "dali_test.py", line 22, in <module>
    pipe.build()
  File "/home/yamada/.local/lib/python3.6/site-packages/nvidia/dali/pipeline.py", line 492, in build
    self._pipe.Build(self._names_and_devices)
RuntimeError: Critical error when building pipeline:
Error when constructing operator: ImageDecoder encountered:
[/dali/dali/pipeline/operator/operator_factory.h:54] Assert on "creator_it != registry_.end()" failed: Operator "ImageDecoder" not registered for mixed.
Current pipeline object is no longer valid.

```

The development environment is jetpack4.4, CUDA10.2, jetson xavier nx (developer's kit), and I am using a cross-compiled dali on docker following the documentation.
What are the possible causes?

For reference, the source code is as follows.

```python:
from nvidia.dali.pipeline import Pipeline
import nvidia.dali.ops as ops
import nvidia.dali.types as types

image_dir = "images"
batch_size = 2
seed = 1549361629

class ImageDecoderPipeline(Pipeline):
    def __init__(self, batch_size, num_threads, device_id):
        super(ImageDecoderPipeline, self).__init__(batch_size, num_threads, device_id, seed = seed)
        self.input = ops.FileReader(file_root = image_dir)
        self.decode = ops.ImageDecoder(device = 'mixed', output_type = types.RGB)

    def define_graph(self):
        jpegs, labels = self.input()
        images = self.decode(jpegs)
        return (images, labels)

pipe = ImageDecoderPipeline(batch_size, 1, 0)

pipe.build()
pipe_out = pipe.run()
```

**Comment by JanuszL** [comment]
Hi,
There is no GPU acceleration of JPEG decoding on the Jetson platform as the nvJPEG library is not available there.
In this case, you need to use `"cpu"` backed for ImageDecoder.
You can look into [this part of the docker file](https://github.com/NVIDIA/DALI/blob/master/docker/Dockerfile.build.aarch64-linux#L295) to see what other DALI functionalities are not supported on Jetson (VideoRead and Optical Flow to name a few).

**Comment by ymdyt** [comment]
Thanks for the answer.
I had already tried that the pipeline can be built using the CPU backend.
It's sad for me to see that GPU acceleration is not available on jetson.

What do we need to  use nvJPEG?
If you know, could you please tell us about the current technical challenges to use GPU acceleration on jetson?

**Comment by JanuszL** [comment]
> What do we need to use nvJPEG?
If you know, could you please tell us about the current technical challenges to use GPU acceleration on jetson?

There is just no nvJPEG build available for Jetson. JPEG acceleration is mostly needed for the training and offline inference. In the case of Jetson, you usually want to do an inference directory on the video stream from the camera (DALI cannot do that yet). So that is why making nvJPEG available for Jetson has a lower priority than other features were requested from that library.

**Comment by ymdyt** [comment]
I see, I understand it well.
Thank you for your quick answer.
