### ISSUE TITLE
error：../python/nvidia/dali/libdali_operators.so：undefined reference to `av_bsf_flush' 

### ISSUE THREAD

**Issue by mandylyin** [NVIDIA/DALI#2659]
I build ffmpeg4.2.2 according to this:
./configure \
--prefix=/usr/local \
--disable-static \
--disable-all \
--disable-autodetect \
--disable-iconv \
--enable-shared \
--enable-avformat \
--enable-avcodec \
--enable-avfilter \
--enable-protocol=file \
--enable-demuxer=mov,matroska,avi \
--enable-bsf=h264_mp4toannexb,hevc_mp4toannexb,mpeg4_unpack_bframes  && \
make

And build DALI like this:
git clone --recursive https://github.com/NVIDIA/DALI
cd DALI
mkdir build
cd build
cmake -D CMAKE_BUILD_TYPE=Release ..
make -j"$(nproc)"

**Comment by JanuszL** [comment]
I guess you have another instance of FFmpeg installed on your system and DALI tries to link with that.
Try running cmake with `-DFFMPEG_ROOT_DIR=/usr/local/` which will point to your custom FFmpeg build location.

**Comment by mandylyin** [comment]
@JanuszL I run cmake with -DFFMPEG_ROOT_DIR=/usr/local/ and it works. DALI is built successfully. Thank you!

**Comment by JanuszL** [comment]
I'm glad it works.
