### ISSUE TITLE
VideoReader op missing after source build

### ISSUE THREAD

**Issue by ColinRioux** [NVIDIA/DALI#2662]
Hello!

I am trying to use DALI on a Jetson Xavier NX. I understand getting DALI to work with cuda 10.2 on aarch64 is still experimental and may not work. I followed [this](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/compilation.html#setup) guide to building a wheel compatible with the Jetson. I built a 0.31.0-dev and 0.30.0 version and have tried both.

After successfully installing the wheel and having access to most of the library, `nvidia.dali.ops.VideoReader` does not exist. I am wondering if I forgot to set some environment variable somewhere.

**Comment by JanuszL** [comment]
Hi,
Video decoding API differs between Jetson and PC class GPUs and is not supported by DALI.
You can look into this part of the docker file to see what other DALI functionalities are not supported on Jetson (nvJPEG and Optical Flow to name a few).
VideoReader in DALI is designed to provide randomly selected sequences from the input that is usable for training. I doubt you want to train any network on Jetson, you probably want to do the inference and DALI doesn't accept stream as an input yet. For this, I would recommend checking [DeepStrea](https://developer.nvidia.com/Deepstream-sdk) which may be a better fit for your use case.
