### ISSUE TITLE
Extract elements out of sequence

### ISSUE THREAD

**Issue by gismo07** [NVIDIA/DALI#2670]
Within the pipeline there is a sequence of F frames. The shape is FxHxWxC
Out of this sequence we want to extract only a specific range of n frames.
![dali](https://user-images.githubusercontent.com/27283752/107516904-58e74d80-6bad-11eb-8c17-a215f3ed4776.png)

To do this, we started with `nvidia.dali.ops.ElementExtract` to pick the first three frames with a stride of 2:
```pyhton
self.framesElementExtract = ops.ElementExtract(element_map=[0,2,4], device="gpu")
```

Within `define_graph`:
```python

# get frames FxHxWxC
frames= self.reshapeFrames(inputs["frames"].gpu())

# get the strided first three
stridedFrames= self.framesElementExtract(frames)
```

We expect `stridedFrames` to be of type `nvidia.dali.pipeline.DataNode` however its of type `List`

What is needed to transform the result of ElementExtract back to the 'normal' type of the pipeline?

**Comment by JanuszL** [comment]
Hi,
`ElementExtract` returns a batch of single image per element on the `element_map`. So if you ask for 0, 2, and 4 fame, you get 3 outputs.
To achieve what you want please check [`SequenceRearrange` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.ops.SequenceRearrange):
```
self.framesElementExtract = ops.SequenceRearrange(new_order =[0,2,4], device="gpu")
```
should do the trick.

**Comment by klecki** [comment]
> We expect stridedFrames to be of type nvidia.dali.pipeline.DataNode however its of type List

As @JanuszL mentioned, the ElementExtract returns 3 outputs that you specified, so you got list of three DataNodes. Each of those outputs would be HWC.

The SequenceRearrange will return one output that is the desired seqence (FHWC layout, the first dimension will be those 3 frames).

Keep it mind that the output of the pipeline would be a batch of such sequences.
