### ISSUE TITLE
jpeg2000 decoding is ignoring the gpu for large files

### ISSUE THREAD

**Issue by RaananHadar** [NVIDIA/DALI#2673]
Hi,
Very impressed with DALI and its potential. My current setup shows considerable gain for jpeg images but jpeg2000 is a hit or miss for large jp2 images (over 150mb or so). It is pretty straightforward to reproduce. 

I've used the image [here.](https://www.dpreview.com/sample-galleries/8756710484/sony-a7r-iv-sample-gallery-dpreview-tv/3109174190), converted one of the the raw images to jpeg2000.

Comparing DALI with another open source library called [rasterio](https://github.com/mapbox/rasterio), the DALI code seemed to bypass the GPU for such files with run times being identical for the CPU. Please note that i've tested the same code on smaller files and DALI seems to work perfectly for smaller files.

its interesting to note also, that DALI is faster than rasterio for jpeg in both CPU and GPU but is slower in jpeg2000.

**Comment by JanuszL** [comment]
Hi,
DALI relies on [nvJPEG2000](https://developer.nvidia.com/nvjpeg) to GPU accelerate JPEG2000 image format decoding. nvJPEG2000 doesn't support all JPEG2000 formats yet and it is possible that DALI in your cases just falls back to the CPU.
You provide an exact JPEG2000 image you used for test or, step by step guide on how to create one? Each option used for conversion may count.

**Comment by RaananHadar** [comment]
Hi,
Thank you for the answer. Here is a [link with the JPEG 2000 image](https://drive.google.com/file/d/1VzWddbCSVb4JBqVoPQ3kN4fVtqQhWMdQ/view?usp=sharing) used for the test.

If you wish to understand how I created the image, if this is also beneficial: i've used the [sample arw image gallery from above](https://www.dpreview.com/sample-galleries/8756710484/sony-a7r-iv-sample-gallery-dpreview-tv/3109174190), opened the raw file in matlab [using this library](https://github.com/farhi/matlab-readraw) and saved the arw image as a jp2 using `imwrite(im,'sample.jp2','jp2');` in matlab.

Thank you.

**Comment by JanuszL** [comment]
Thanks for the image. It looks like nvJPEG2000 cannot parse it properly. Let me check with the nvJPEG team and get back to you as soon as we learn anything.

**Comment by JanuszL** [comment]
nvJPEG2000 doesn't support the Jpeg2000 flavor you have. It is planned for the next release.

**Comment by RaananHadar** [comment]
Thanks for the reply. 

I didn't know that there are multiple jpeg2000 flavors. Can you please provide me to some docs and is there a way to see which flavor I am using and what flavor is supported?

Thank you.

**Comment by JanuszL** [comment]
Please check on nvJPEG2000 [dev site](https://developer.nvidia.com/nvjpeg).

**Comment by JanuszL** [comment]
We updated the nvJPEG2000 version but I see that DALI doesn't support your image correctly.
Let us check what is wrong and get back to you soon.

**Comment by JanuszL** [comment]
Hi,
https://github.com/NVIDIA/DALI/pull/2867 should enable your use case. I should be merged soon.

**Comment by JanuszL** [comment]
https://github.com/NVIDIA/DALI/pull/2867 has been merged. Please check the nightly build that follows it or DALI 1.2 release when it is available.

**Comment by JanuszL** [comment]
Hi,
DALI 1.2 has been released and should fix the issue.
