### ISSUE TITLE
Failed to decode data in tfrecord format

### ISSUE THREAD

**Issue by KleinXin** [NVIDIA/DALI#2674]
I am trying to read images and labels in tfrecord format.

### **The script I used to generate tfrecord is as below, codes are from** https://www.machinelearningmindset.com/tfrecords-for-tensorflow/

```
import os
import io
import sys

import tensorflow as tf
from tensorflow import keras
import numpy as np

from PIL import Image
import cv2

def _bytes_feature(value):
    if isinstance(value, type(tf.constant(0))):
        value = value.numpy()  # BytesList won't unpack a string from an EagerTensor.
    return tf.train.Feature(bytes_list=tf.train.BytesList(value=[value]))

def _float_feature(value):
    return tf.train.Feature(float_list=tf.train.FloatList(value=[value]))

def _int64_feature(value):
    return tf.train.Feature(int64_list=tf.train.Int64List(value=[value]))

def anno_dict(image, label):
    feature = {
        'label': _int64_feature(label),
        'image': _bytes_feature(image.tobytes()),
    }
    return tf.train.Example(features=tf.train.Features(feature=feature))

if __name__ == "__main__":
   record_file_name = './CarColorRecog_50k/CarColorRecog_50k_val.tfrecords'

   img_lst_name = '/work/Dataset/CarColorRecog/CarColorRecog_50k_val_lst.txt'

   with tf.io.TFRecordWriter(record_file_name) as tf_record_writer:

        with open(img_lst_name,'r') as f_img_lst:

             lines = f_img_lst.readlines()

             for line in lines:

                 line = line[:-1]

                 img_path,label = line.split(' ')
                 label = int(label)

                 img = cv2.imread(img_path)

                 tf_example = anno_dict(img, label)
                 tf_record_writer.write(tf_example.SerializeToString())
```

### **Then the idx file is generated as shown in the guide** https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/dataloading_tfrecord.html

```
from subprocess import call
import os.path

if __name__ == "__main__":

   tfrecord_file_name = './CarColorRecog_50k/CarColorRecog_50k_val.tfrecords'
   tfrecord_idx_file_name = './CarColorRecog_50k/CarColorRecog_50k_val.idx'
   tfrecord2idx_script = "./tfrecord2idx"

   call([tfrecord2idx_script, tfrecord_file_name, tfrecord_idx_file_name])
```

### **Finally, I tried to decode the tfrecord file as shown in the guide**

```
import os
import tensorflow as tf
import numpy as np

from nvidia.dali.pipeline import Pipeline
import nvidia.dali.ops as ops
import nvidia.dali.types as types
import nvidia.dali.tfrecord as tfrec
from nvidia.dali.plugin.pytorch import DALIGenericIterator

class CommonPipeline(Pipeline):
    def __init__(self, batch_size, num_threads, device_id):
        super(CommonPipeline, self).__init__(batch_size, num_threads, device_id)

        self.decode = ops.ImageDecoder(device = "mixed", output_type = types.RGB)
        self.resize = ops.Resize(device = "gpu",
                                 interp_type = types.INTERP_LINEAR)
        self.cmn = ops.CropMirrorNormalize(device = "gpu",
                                            dtype = types.FLOAT,
                                            crop = (227, 227),
                                            mean = [128., 128., 128.],
                                            std = [1., 1., 1.])
        self.uniform = ops.Uniform(range = (0.0, 1.0))
        self.resize_rng = ops.Uniform(range = (256, 480))

    def base_define_graph(self, inputs, labels):
        images = self.decode(inputs)
        images = self.resize(images, resize_shorter = self.resize_rng())
        output = self.cmn(images, crop_pos_x = self.uniform(),
                          crop_pos_y = self.uniform())
        return (output, labels)

class TFRecordPipeline(CommonPipeline):
    def __init__(self, tfrecord_path,tfrecord_idx_path,batch_size, num_threads, device_id, num_gpus):
        super(TFRecordPipeline, self).__init__(batch_size, num_threads, device_id)
        self.input = ops.TFRecordReader(path = tfrecord_path,
                                        index_path = tfrecord_idx_path,
                                        features = {"image" : tfrec.FixedLenFeature((), tfrec.string, ""),
                                                    "label": tfrec.FixedLenFeature([1], tfrec.int64,  -1)
                                        })

    def define_graph(self):
        inputs = self.input(name="Reader")
        images = inputs["image"]
        labels = inputs["label"]
        return self.base_define_graph(images, labels)

if __name__ == "__main__":

   tfrecord_file_name = './CarColorRecog_50k/CarColorRecog_50k_val.tfrecords'
   tfrecord_idx_file_name = './CarColorRecog_50k/CarColorRecog_50k_val.idx'
   
   num_gpus = 4
   num_threads = 4
   batch_size = 8
   num_max_iters = 10

   pipes = [TFRecordPipeline(tfrecord_path=tfrecord_file_name,
                             tfrecord_idx_path=tfrecord_idx_file_name,
                             batch_size=batch_size,
                             num_threads=num_threads,
                             device_id=device_id,
                             num_gpus=num_gpus) for device_id in range(num_gpus)]

   pipes[0].build()
   dali_iter = DALIGenericIterator(pipes, ['image', 'label'], pipes[0].epoch_size("Reader"))

   for i, data in enumerate(dali_iter):
        if i >= num_max_iters:
            break
        # Testing correctness of labels
        for d in data:
            label = d['label']
            image = d['image']
```

### **Unfortunately, it gives the error as below**

_Traceback (most recent call last):
  File "tfrecord_parser.py", line 66, in <module>
    dali_iter = DALIGenericIterator(pipes, ['image', 'label'], pipes[0].epoch_size("Reader"))
  File "/usr/local/lib/python3.6/dist-packages/nvidia/dali/plugin/pytorch.py", line 170, in __init__
    self._first_batch = DALIGenericIterator.__next__(self)
  File "/usr/local/lib/python3.6/dist-packages/nvidia/dali/plugin/pytorch.py", line 181, in __next__
    outputs = self._get_outputs()
  File "/usr/local/lib/python3.6/dist-packages/nvidia/dali/plugin/base_iterator.py", line 246, in _get_outputs
    outputs.append(p.share_outputs())
  File "/usr/local/lib/python3.6/dist-packages/nvidia/dali/pipeline.py", line 682, in share_outputs
    return self._pipe.ShareOutputs()
RuntimeError: Critical error in pipeline:
Error when executing Mixed operator ImageDecoder encountered:
[/opt/dali/dali/operators/decoder/nvjpeg/nvjpeg_decoder_decoupled_api.h:546] [/opt/dali/dali/image/image_factory.cc:89] Assert on "CheckIsPNG(encoded_image, length) + CheckIsBMP(encoded_image, length) + CheckIsGIF(encoded_image, length) + CheckIsJPEG(encoded_image, length) + CheckIsTiff(encoded_image, length) + CheckIsPNM(encoded_image, length) + CheckIsJPEG2k(encoded_image, length) == 1" failed: Encoded image has ambiguous format_

Anyone knows what is wrong?

Any help is appreciated!

**Comment by JanuszL** [comment]
Hi,
As I see you write the raw image to TFRecord (cv2.imread). In the DALI examples, when you use ImageDecoder it is assumed that data is encoded. What you should do is just save the data from `tf.gfile.FastGFile(img_path, 'rb').read()` call, or not use ImageDecoder (as your data is already decoded), read shapes (you should store them in TFRecord), and use DALI reshape function to reshape the 1D data read from TFRecord properly.

**Comment by KleinXin** [comment]
@JanuszL 

As you suggested, I changed cv2.imread to tf.compat.v1.gfile.FastGFile because I am using tensorflow 2.1.1

So the codes I used to generate the tfrecord becomes

```
import os
import io
import sys

import tensorflow as tf
from tensorflow import keras
import numpy as np

from PIL import Image
import cv2

# codes from https://www.machinelearningmindset.com/tfrecords-for-tensorflow/
# Convert values to compatible tf.Example types.

def _bytes_feature(value):
    """Returns a bytes_list from a string / byte."""
    if isinstance(value, type(tf.constant(0))):
        value = value.numpy()  # BytesList won't unpack a string from an EagerTensor.
    return tf.train.Feature(bytes_list=tf.train.BytesList(value=[value]))

def _float_feature(value):
    """Returns a float_list from a float / double."""
    return tf.train.Feature(float_list=tf.train.FloatList(value=[value]))

def _int64_feature(value):
    """Returns an int64_list from a bool / enum / int / uint."""
    return tf.train.Feature(int64_list=tf.train.Int64List(value=[value]))

# Create the features dictionary.
def anno_dict(image, label):
    feature = {
        'label': _int64_feature(label),
        #'image': _bytes_feature(image.tobytes()),
        'image': _bytes_feature(image),
    }

    return tf.train.Example(features=tf.train.Features(feature=feature))

if __name__ == "__main__":

   record_file_name = './CarColorRecog_50k/CarColorRecog_50k_val.tfrecords'

   img_lst_name = '/work/Dataset/CarColorRecog/CarColorRecog_50k_val_lst.txt'

   with tf.io.TFRecordWriter(record_file_name) as tf_record_writer:

        with open(img_lst_name,'r') as f_img_lst:

             lines = f_img_lst.readlines()

             for line in lines:

                 line = line[:-1]

                 img_path,label = line.split(' ')
                 label = int(label)

                 #img = cv2.imread(img_path)

                 img = tf.compat.v1.gfile.FastGFile(img_path, 'rb').read()

                 tf_example = anno_dict(img, label)
                 tf_record_writer.write(tf_example.SerializeToString())
```

During decoding, error message is as below

Traceback (most recent call last):
  File "tfrecord_parser.py", line 68, in <module>
    dali_iter = DALIGenericIterator(pipes, ['image', 'label'], pipes[0].epoch_size("Reader"))
  File "/usr/local/lib/python3.6/dist-packages/nvidia/dali/plugin/pytorch.py", line 170, in __init__
    self._first_batch = DALIGenericIterator.__next__(self)
  File "/usr/local/lib/python3.6/dist-packages/nvidia/dali/plugin/pytorch.py", line 181, in __next__
    outputs = self._get_outputs()
  File "/usr/local/lib/python3.6/dist-packages/nvidia/dali/plugin/base_iterator.py", line 246, in _get_outputs
    outputs.append(p.share_outputs())
  File "/usr/local/lib/python3.6/dist-packages/nvidia/dali/pipeline.py", line 682, in share_outputs
    return self._pipe.ShareOutputs()
RuntimeError: Critical error in pipeline:
Error when executing GPU operator Resize encountered:
std::bad_alloc
Current pipeline object is no longer valid.

**Comment by JanuszL** [comment]
I can only guess you run out of GPU memory. Try to reduce batch size. I recommend trying DALI examples first to see how that works.

**Comment by KleinXin** [comment]
I also tried to store data without encoding together with with,height and depth of the image, the codes are as below

'''
import os
import io
import sys

import tensorflow as tf
from tensorflow import keras
import numpy as np

from PIL import Image
import cv2

# codes from https://www.machinelearningmindset.com/tfrecords-for-tensorflow/
# Convert values to compatible tf.Example types.

def _bytes_feature(value):
    """Returns a bytes_list from a string / byte."""
    if isinstance(value, type(tf.constant(0))):
        value = value.numpy()  # BytesList won't unpack a string from an EagerTensor.
    return tf.train.Feature(bytes_list=tf.train.BytesList(value=[value]))

def _float_feature(value):
    """Returns a float_list from a float / double."""
    return tf.train.Feature(float_list=tf.train.FloatList(value=[value]))

def _int64_feature(value):
    """Returns an int64_list from a bool / enum / int / uint."""
    return tf.train.Feature(int64_list=tf.train.Int64List(value=[value]))

# Create the features dictionary.
def anno_dict(image, label):
    feature = {
        'label': _int64_feature(label),
        'image': _bytes_feature(image.tobytes()),
        #'image': _bytes_feature(image),
        'image_height':_int64_feature(image.shape[0]),
        'image_width':_int64_feature(image.shape[1]),
        'image_depth':_int64_feature(image.shape[2]),
    }

    return tf.train.Example(features=tf.train.Features(feature=feature))

if __name__ == "__main__":

   record_file_name = './CarColorRecog_50k/CarColorRecog_50k_val_raw.tfrecords'

   img_lst_name = '/work/Dataset/CarColorRecog/CarColorRecog_50k_val_lst.txt'

   with tf.io.TFRecordWriter(record_file_name) as tf_record_writer:

        with open(img_lst_name,'r') as f_img_lst:

             lines = f_img_lst.readlines()

             for line in lines:

                 line = line[:-1]

                 img_path,label = line.split(' ')
                 label = int(label)

                 img = cv2.imread(img_path)

                 #img = tf.compat.v1.gfile.FastGFile(img_path, 'rb').read()

                 tf_example = anno_dict(img, label)
                 tf_record_writer.write(tf_example.SerializeToString())
'''

The tfrecord parser script is also changed accordingly

```
import os
import tensorflow as tf
import numpy as np

from nvidia.dali.pipeline import Pipeline
import nvidia.dali.ops as ops
import nvidia.dali.types as types
import nvidia.dali.tfrecord as tfrec
from nvidia.dali.plugin.pytorch import DALIGenericIterator

class CommonPipeline(Pipeline):
    def __init__(self, batch_size, num_threads, device_id):
        super(CommonPipeline, self).__init__(batch_size, num_threads, device_id)

        self.decode = ops.ImageDecoder(device = "mixed", output_type = types.RGB)
        self.resize = ops.Resize(device = "gpu",
                                 interp_type = types.INTERP_LINEAR)
        self.cmn = ops.CropMirrorNormalize(device = "gpu",
                                            dtype = types.FLOAT,
                                            crop = (227, 227),
                                            mean = [128., 128., 128.],
                                            std = [1., 1., 1.])
        self.uniform = ops.Uniform(range = (0.0, 1.0))
        self.resize_rng = ops.Uniform(range = (256, 480))

    def base_define_graph(self, inputs, labels):
        #images = self.decode(inputs)
        images = inputs
        images = self.resize(images, resize_shorter = self.resize_rng())
        output = self.cmn(images, crop_pos_x = self.uniform(),
                          crop_pos_y = self.uniform())
        return (output, labels)

class TFRecordPipeline(CommonPipeline):
    def __init__(self, tfrecord_path,tfrecord_idx_path,batch_size, num_threads, device_id, num_gpus):
        super(TFRecordPipeline, self).__init__(batch_size, num_threads, device_id)
        self.input = ops.TFRecordReader(path = tfrecord_path,
                                        index_path = tfrecord_idx_path,
                                        features = {"image" : tfrec.FixedLenFeature((), tfrec.string, ""),
                                                    "label": tfrec.FixedLenFeature([1], tfrec.int64,  -1)
                                        })

    def define_graph(self):
        inputs = self.input(name="Reader")
        images = inputs["image"]
        labels = inputs["label"]
        return self.base_define_graph(images, labels)

if __name__ == "__main__":

   tfrecord_file_name = './CarColorRecog_50k/CarColorRecog_50k_val_raw.tfrecords'
   tfrecord_idx_file_name = './CarColorRecog_50k/CarColorRecog_50k_val_raw.idx'
   
   num_gpus = 4
   num_threads = 4
   batch_size = 8
   num_max_iters = 10

   pipes = [TFRecordPipeline(tfrecord_path=tfrecord_file_name,
                             tfrecord_idx_path=tfrecord_idx_file_name,
                             batch_size=batch_size,
                             num_threads=num_threads,
                             device_id=device_id,
                             num_gpus=num_gpus) for device_id in range(num_gpus)]

   pipes[0].build()
   dali_iter = DALIGenericIterator(pipes, ['image', 'label'], pipes[0].epoch_size("Reader"))

   for i, data in enumerate(dali_iter):
        if i >= num_max_iters:
            break
        # Testing correctness of labels
        for d in data:
            label = d['label']
            image = d['image']
```
   
During decoding, the error message is as below

Traceback (most recent call last):
  File "tfrecord_parser_raw.py", line 69, in <module>
    dali_iter = DALIGenericIterator(pipes, ['image', 'label'], pipes[0].epoch_size("Reader"))
  File "/usr/local/lib/python3.6/dist-packages/nvidia/dali/plugin/pytorch.py", line 170, in __init__
    self._first_batch = DALIGenericIterator.__next__(self)
  File "/usr/local/lib/python3.6/dist-packages/nvidia/dali/plugin/pytorch.py", line 181, in __next__
    outputs = self._get_outputs()
  File "/usr/local/lib/python3.6/dist-packages/nvidia/dali/plugin/base_iterator.py", line 246, in _get_outputs
    outputs.append(p.share_outputs())
  File "/usr/local/lib/python3.6/dist-packages/nvidia/dali/pipeline.py", line 682, in share_outputs
    return self._pipe.ShareOutputs()
RuntimeError: Critical error in pipeline:
Error when executing GPU operator Resize encountered:
[/opt/dali/dali/pipeline/operator/op_schema.h:427] The number of dimensions 1 does not match any of the allowed layouts for input 0. Valid layouts are:
HWC
FHWC
CHW
FCHW
CFHW
DHWC
FDHWC
CDHW
FCDHW
CFDHW

**Comment by JanuszL** [comment]
It doesn't work as TFRecord store just 1D data. You need to read width, height and pass them to Reshape operator (just concat/join x and w and make the shape that you pass to Reshape) so your 1D data becomes HWC data.

**Comment by KleinXin** [comment]
> I can only guess you run out of GPU memory. Try to reduce batch size. I recommend trying DALI examples first to see how that works.

tf.compat.v1.gfile.FastGFile method works, thx!
