### ISSUE TITLE
Question about nvidia.dali.ops.VideoReader API

### ISSUE THREAD

**Issue by HieuTrLuu** [NVIDIA/DALI#2689]
Hi,

# Question 1
I am trying to get the frame_numbers and timestamps of the decoded frames using enable_frame_num and enable_timestamps parameters following the update in https://github.com/NVIDIA/DALI/pull/1500. However it was unsuccessful.  

I have been trying to play with different parameter to fix the problem but did not have any luck.

## Code 

```python
class VideoPipe(Pipeline):
    def __init__(self, batch_size, num_threads, device_id, data, shuffle):
        super(VideoPipe, self).__init__(batch_size, num_threads, device_id, seed=16)
        self.input = ops.VideoReader(device="gpu", sequence_length=sequence_length,
                                     shard_id=0, num_shards=1,
                                     filenames=data,
                                     enable_frame_num=True,
                                     random_shuffle=shuffle, initial_fill=initial_prefetch_size)

    def define_graph(self):
        # name="Reader"
        output = self.input()
        return output



        
pipe = VideoPipe(batch_size=batch_size, num_threads=2, device_id=0, data=[video_files[0]], shuffle=shuffle)
pipe.build()

for i in range(n_iter):
    pipe_out = pipe.run()
    sequences_out = pipe_out[0].as_cpu().as_array()
    print(sequences_out.shape)

```
##

## Error
Error when constructing operator: VideoReader encountered:
[/opt/dali/dali/operators/reader/video_reader_op.h:79] Assert on "can_use_frames_timestamps_ || !enable_frame_num_" failed: frame numbers can be enabled only when `file_list` or `filenames` argument is passed
##

Google Colab of the experiment: https://colab.research.google.com/drive/1Nin_84Lu9m3iN2FJDEQOuKnI9lxzYGTr?usp=sharing

What am I doing wrong here ?

# Question 2
Currently, nvidia.dali.ops.VideoReader return the parent folder by declaring file_root parameters. Can we do something so it return the absolute path of the read video/file ?

Best regards

**Comment by JanuszL** [comment]
Hi @HieuTrLuu,

> [/opt/dali/dali/operators/reader/video_reader_op.h:79] Assert on "can_use_frames_timestamps_ || !enable_frame_num_" failed: frame numbers can be enabled only when file_list or filenames argument is passed

As the error message states you need to either use `file_root` and follow the directory structure as FILE_ROOT/CLASS_NAME_FOLDER/videoXYZ.avi, or `filenames` and `labels` where you provide either an empty python list `[]` or a list of corresponding to each video numerical values of the class. The timestamps are bound to labels as frame number itself doesn't provide much value when you don't know which video they correspond to and for that, you need to at least know the class it belongs to.

> Currently, nvidia.dali.ops.VideoReader return the parent folder by declaring file_root parameters. Can we do something so it return the absolute path of the read video/file ?

If I understand the ask correctly, you the reader to return the path to the video you read, right? Now it is not possible and the best you can do is just map the video files to the unique id/label the reader returns.

**Comment by HieuTrLuu** [comment]
Thank you very much, this solves my problem
