### ISSUE TITLE
how to clean the prefetch data?

### ISSUE THREAD

**Issue by zwangZJU** [NVIDIA/DALI#2695]
My data source changes in each loop, but the newly changed data will not be used immediately. Instead, the new data will be loaded after the prefetched data is consumed. How to clear the prefetched data before each loop ?

my code:
`
    data = [np.zeros([255, 255, 3]).astype(np.uint8)]

    rec_batch_size = 2
    eii = ExternalInputIterator(data, rec_batch_size)
    pipe = LoadImagePipe(eii, rec_batch_size, num_threads=16, device_id=0)
    pipe.build()
    dataloader = DALIGenericIterator(pipe, ["images"], size=-1)

    for i in range(1, 5):
        cur_data = [np.ones([255, 255, 3]).astype(np.uint8) * i ]
        data.clear()
        data.extend(cur_data)
        eii.__iter__()
        pipe.reset()
        dataloader.reset()
        for batch_idx, batch_data in enumerate(dataloader):
            imgs = batch_data[0]["images"].clone()
            print(imgs)
            if (batch_idx + 1) * rec_batch_size >= len(cur_data):
                break
`
    
    class ExternalInputIterator(object):
        def __init__(self, goods_imgs=[], batch_size=32):
            self.goods_imgs = goods_imgs
            self.batch_size = batch_size
    
        def __iter__(self):
            self.i = 0
            self.n = len(self.goods_imgs)
            return self
    
        def __next__(self):
            images = []
            if self.n == 0:
                return images
            for idx in range(self.batch_size):
                images.append(self.goods_imgs[self.i])
                self.i = (self.i + 1) % self.n
    
            return images
    
    
    class LoadImagePipe(Pipeline):
        def __init__(self, eii, batch_size, num_threads, device_id):
            super(LoadImagePipe, self).__init__(batch_size, num_threads, device_id, prefetch_queue_depth=1)
            self.eii = eii
            self.source = ops.ExternalSource(source=self.eii)#, num_outputs=1
            #self.decode = ops.ImageDecoder(device='cpu', output_type=types.RGB)
            self.resize = ops.Resize(device='gpu', resize_x=224, resize_y=224, interp_type=types.INTERP_TRIANGULAR)
            self.normalize = ops.Normalize(device="gpu", mean=127.5, stddev=127.5)
            self.transpose = ops.Transpose(device="gpu", perm=[2, 0, 1])
    
        def define_graph(self):
            inputs = self.source()
            output = self.resize(inputs.gpu())
            output = self.transpose(output)
            return output`

**Comment by JanuszL** [comment]
Hi @zwangZJU,

In this case when your `ExternalInputIterator` runs out of data just raise `StopIteration` and DALI will not prefetch more data from the ExternalSource and just consume one that is already in the pipeline.

**Comment by zwangZJU** [comment]
> Hi @zwangZJU,
> 
> In this case when your `ExternalInputIterator` runs out of data just raise `StopIteration` and DALI will not prefetch more data from the ExternalSource and just consume one that is already in the pipeline.
> Also in such case you won't need:
> 
> ```
> if (batch_idx + 1) * rec_batch_size >= len(cur_data):
>             break
> ```
> 
> as DALIGenericIterator will yield `StopIteration` as well.

`dataloader = DALIGenericIterator(pipe, ["images"], size=-1)`
I set the size=-1，it will always be loaded cyclically,  Should I modify `ExternalInputIterator` or modify the parameter `size`

**Comment by JanuszL** [comment]
Hi,
Please try out:
```
import nvidia.dali.fn as fn
import nvidia.dali.ops as ops
import nvidia.dali.math as math
import nvidia.dali.types as types
from nvidia.dali.pipeline import Pipeline
import numpy as np
from nvidia.dali.plugin.pytorch import DALIGenericIterator as DALIGenericIterator

class ExternalInputIterator(object):
    def __init__(self, goods_imgs=[], batch_size=32):
        self.goods_imgs = goods_imgs
        self.batch_size = batch_size
        self.should_stop = False

    def __iter__(self):
        self.i = 0
        self.n = len(self.goods_imgs)
        self.should_stop = False
        return self

    def __next__(self):
        if self.should_stop or self.n == 0:
            raise StopIteration
        images = []
        for _ in range(self.batch_size):
            images.append(self.goods_imgs[self.i])
            self.i += 1
            if self.i == self.n:
                self.i = 0
                self.should_stop = True

        return images


class LoadImagePipe(Pipeline):
    def __init__(self, eii, batch_size, num_threads, device_id):
        super(LoadImagePipe, self).__init__(batch_size, num_threads, device_id, prefetch_queue_depth=1)
        self.eii = eii
        self.source = ops.ExternalSource(source=self.eii)#, num_outputs=1
        #self.decode = ops.ImageDecoder(device='cpu', output_type=types.RGB)
        self.resize = ops.Resize(device='gpu', resize_x=224, resize_y=224, interp_type=types.INTERP_TRIANGULAR)
        self.normalize = ops.Normalize(device="gpu", mean=127.5, stddev=127.5)
        self.transpose = ops.Transpose(device="gpu", perm=[2, 0, 1])

    def define_graph(self):
        inputs = self.source()
        output = self.resize(inputs.gpu())
        output = self.transpose(output)
        return output

data = [np.zeros([255, 255, 3]).astype(np.uint8)]
rec_batch_size = 2
eii = ExternalInputIterator(data, rec_batch_size)
pipe = LoadImagePipe(eii, rec_batch_size, num_threads=16, device_id=0)
pipe.build()
dataloader = DALIGenericIterator(pipe, ["images"])

for i in range(1, 5):
    cur_data = [np.ones([255, 255, 3]).astype(np.uint8) * i ]
    data.clear()
    data.extend(cur_data)
    if i == 1:
        # flush the first dummy input that was consumed when the iterator was created
        next(dataloader)
    eii.__iter__()
    dataloader.reset()
    print("start now")
    for batch_idx, batch_data in enumerate(dataloader):
        imgs = batch_data[0]["images"].clone()
        print(imgs)```
