### ISSUE TITLE
Seed in ops.Flip?

### ISSUE THREAD

**Issue by zhiheng-ldj** [NVIDIA/DALI#2707]
Hi,

Thanks for your recent help!

I now have a question about how to use ops.Flip:

It seems that there is no randomness in this operation: No matter how I set random seed, it will always perform flip. So why do we have this seed parameter?

Besides, if I want to implement flip with a probability of 0.5, how should I do with an easy way?

Mant thanks!!

**Comment by JanuszL** [comment]
Hi @zhiheng-ldj,

I recommend checking [ResNet50 example with PyTorch](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/use_cases/pytorch/resnet50/pytorch-resnet50.html).
You can do something like:
```
fn.flip(images, horizontal = fn.random.coin_flip(probability=0.5))
```

**Comment by ShiquanYu** [comment]
Hi @JanuszL,

What abort other functions like `transform.xxx()/Brightness/Contrast`, If I want to execute those function with probability=0.5, what should I do?

Looking forward to your reply.

**Comment by JanuszL** [comment]
Hi,

You can apply two approaches:
- use [conditional like execution](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/expressions/expr_conditional_and_masking.html) as DALI doesn't support yet fully conditional operator execution. Pro - the concept of this approach is easy to generalize, the cons - it executes code for both conditions so it is slower
- use CoinFlip to select between natural and augmented values. Something like (faster but a bit more complicated):
```
    if_apply = fn.random.coin_flip(probability=0.5)
    # contrast = fn.uniform(range=[0.5, 1.5]) * if_apply + (if_apply ^ True) * 1
    contrast = fn.uniform(range=[-0.5, 0.5]) * if_apply + 1
    # brightness = fn.uniform(range=[0.875, 1.125]) * if_apply + (if_apply ^ True) * 1
    brightness = fn.uniform(range=[-0.275, 0.125]) * if_apply + 1
    images = fn.brightness_contrast(images,
                                    contrast_center = 128,  # input is in float, but in 0..255 range
                                    dtype = types.UINT8,
                                    brightness = brightness,
                                    contrast = contrast)
```

**Comment by ShiquanYu** [comment]
> Hi,
> 
> You can apply two approaches:
> 
> * use [conditional like execution](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/expressions/expr_conditional_and_masking.html) as DALI doesn't support yet fully conditional operator execution. Pro - the concept of this approach is easy to generalize, the cons - it executes code for both conditions so it is slower
> * use CoinFlip to select between natural and augmented values. Something like (faster but a bit more complicated):
> 
> ```
>     if_apply = fn.random.coin_flip(probability=0.5)
>     # contrast = fn.uniform(range=[0.5, 1.5]) * if_apply + (if_apply ^ True) * 1
>     contrast = fn.uniform(range=[-0.5, 0.5]) * if_apply + 1
>     # brightness = fn.uniform(range=[0.875, 1.125]) * if_apply + (if_apply ^ True) * 1
>     brightness = fn.uniform(range=[-0.275, 0.125]) * if_apply + 1
>     images = fn.brightness_contrast(images,
>                                     contrast_center = 128,  # input is in float, but in 0..255 range
>                                     dtype = types.UINT8,
>                                     brightness = brightness,
>                                     contrast = contrast)
> ```

Thanks!

It's a good idea, I will have a try～
