### ISSUE TITLE
color_jitter vs jitter?

### ISSUE THREAD

**Issue by zhiheng-ldj** [NVIDIA/DALI#2708]
Hi,

Thanks for your help and time regarding to this issue!

Is ops.jitter equivalent to color_jitter?

color_jitter: Randomly distort the brightness, contrast, saturation and hue of images, and add PCA based noise into images.

ops.jitter: Performs a random Jitter augmentation. The output images are produced by moving each pixel by a random amount, in the x and y dimensions, and bounded by half of the nDegree parameter.

If not, can we implement color jitter in DALI?

Many thanks!!

**Comment by JanuszL** [comment]
Hi @zhiheng-ldj,

You can check [this example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/image_processing/augmentation_gallery.html) to see how Jitter works - it is a spatial augmentation.
To implement color jitter please use something like (these code snipet is taken from SSD - Single Shot Detector, data procesing pipeline):
```
    saturation = fn.uniform(range=[0.5, 1.5])
    contrast = fn.uniform(range=[0.5, 1.5])
    brightness = fn.uniform(range=[0.875, 1.125])
    hue = fn.uniform(range=[-0.5, 0.5])

    images = fn.hsv(images, dtype=types.FLOAT, hue=hue, saturation=saturation)  # use float to avoid clipping and
                                                         # quantizing the intermediate result
    images = fn.brightness_contrast(images,
                                    contrast_center = 128,  # input is in float, but in 0..255 range
                                    dtype = types.UINT8,
                                    brightness = brightness,
                                    contrast = contrast)
```
