### ISSUE TITLE
Random sample data during training

### ISSUE THREAD

**Issue by zhiheng-ldj** [NVIDIA/DALI#2709]
Hi,

Thanks for your help!

I have a question about how to sample data in training dataset:

For example, I have 100 images in a specific folder. If I want to sample 10 images randomly for each epoch, how should I implement it? The easier the better.

Many thanks for your help!

**Comment by JanuszL** [comment]
Hi @zhiheng-ldj,

This is tricky but you can do something like:
```
fn.file_reader(files=["file1", "file2",...., "file100"], shard_id=0, num_shards=10, shuffle_after_epoch = True)
```
The reader will read only 1/10 of your data set each epoch (10 shards, each reader gets 1/10 of the dataset), `shuffle_after_epoch` will cause to randomly shuffle whole data set each epoch.

**Comment by zhiheng-ldj** [comment]
> Hi @zhiheng-ldj,
> 
> This is tricky but you can do something like:
> 
> ```
> fn.file_reader(files=["file1", "file2",...., "file100"], shard_id=0, num_shards=10, shuffle_after_epoch = True)
> ```
> 
> The reader will read only 1/10 of your data set each epoch (10 shards, each reader gets 1/10 of the dataset), `shuffle_after_epoch` will cause to randomly shuffle whole data set each epoch.

Thanks for your help!

Actually I am trying to use DALI to help with a video classification task. Specifically:

For example, I have a folder containing 100 images, which are the frames sampled from a video. The sample interval is 5 and the clip length is 8, which means I may need sample images of (13(start index),18,23,28,33,38,43,48,53,58)......

Of course I can make use of files to sample images.

However, if I use ops.FileReader, it will walk through all folders. How can I set the start index and sample list for these subfolders?

Thanks!!

**Comment by JanuszL** [comment]
Hi,

You can try [`SequenceReader` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.ops.SequenceReader) or [`ExternalSource`](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/external_input.html).
The former is dedicated to your use case but it has very rudimentary functionality, while ExternalSource trades performance for flexibility.
I think you should check what works best for you.

**Comment by zhiheng-ldj** [comment]
> Hi,
> 
> You can try [`SequenceReader` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.ops.SequenceReader) or [`ExternalSource`](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/external_input.html).
> The former is dedicated to your use case but it has very rudimentary functionality, while ExternalSource trades performance for flexibility.
> I think you should check what works best for you.

Hi,

Thanks for your help!

I am trying to use SequenceReader and have some confusing points.

1. How should I return the result of this reader? Specifically, I define the reader in init, use it in define_graph and return it in pytorch iterator:

~~~
# init
self.input = ops.SequenceReader(file_root=data_dir, sequence_length=8, step=8, shard_id=shard_id, num_shards=num_shards, random_shuffle=shuffle)

# define_graph
seq = self.input(name="Reader")
return seq

# iterator
class DaliIteratorGPU(DaliIterator):
    """
    Wrapper class to decode the DALI iterator output & provide iterator that functions the same as torchvision

    pipelines (Pipeline): DALI pipelines
    size (int): Number of examples in set

    Note: allow extra inputs to keep compatibility with CPU iterator
    """

    print('Using DALI GPU iterator')
    def __next__(self):
        try:
            data = next(self._dali_iterator)
        except StopIteration:
            print('Resetting DALI loader')
            self._dali_iterator.reset()
            raise StopIteration

        input = data

        return input
~~~

And it raises an error like this:

~~~
RuntimeError: [../dali/pipeline/data/tensor_list.h:567] Assert on "this->IsDenseTensor()" failed: All tensors in the input TensorList must have the same shape and be densely packed.
~~~

2. Do we need something like image decoder to decode the output of Sequence Reader? Moreover, how should we process this sequence?

3. If the dataset is like:

~~~
dataset
-class1
--video name
---images
-class2
--video name
---images
~~~

How should we process the path?

Thanks!!

**Comment by JanuszL** [comment]
Hi,
Please check [this example ](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/sequence_processing/sequence_reader_simple_example.html?highlight=sequencereader) to see how to use the `SequenceReader` operator.

> And it raises an error like this:

Are you sure that all images/sequences in the batch have the same shape? If not you may try resizing them to one, well-defined shape.

Regarding your questions:
> Do we need something like image decoder to decode the output of Sequence Reader?

No. The `SequenceReader` operator does decoding on its own on the CPU, there is not GPU accelerated decoding variant so far.

>how should we process this sequence?

Please use the operators that support Sequences. You can find them easily in [this](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#support-table) list.

> How should we process the path?

You need to stick to the directory layout that [the `SequenceReader`](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.ops.SequenceReader) supports. If this is not possible please please try using the `ExternalSource` operator.

**Comment by JanuszL** [comment]
Hi,

The most recent improvements of [the `external_source` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.external_source) make it parallel to the training and scales with the number of CPUs. Please check `parallel` and `prefetch_queue_depth` options.
