### ISSUE TITLE
Error : Operator "ImageDecoder" not registered on gpu. 

### ISSUE THREAD

**Issue by pshwetank** [NVIDIA/DALI#2712]
I was trying to run a simple tutorial of DALI pipeline to return a batch of images and labels. It works completely fine when I use device='cpu' in ops.ImageDecoder but the following error occurs when I try to use 'gpu' as device: 

```bash
RuntimeError: Critical error when building pipeline:
Error when constructing operator: ImageDecoder encountered:
[/opt/dali/dali/pipeline/operator/operator_factory.h:54] Assert on "creator_it != registry_.end()" failed: Operator "ImageDecoder" not registered for gpu.
```

I am using CUDA 11.0 and Nvidia Tesla K80 GPU on my instance. 

The code I am using is as follows:
```python
#Designing simple module to read the images
class DALIBackendPipeline(Pipeline):
    def __init__(self, root_dir, batch_size, n_workers, device_id=0):
        super(DALIBackendPipeline, self).__init__(batch_size, n_workers, device_id, seed=42)
        self.input = ops.FileReader(file_root=root_dir)
        self.decode = ops.ImageDecoder(device='gpu', output_type=types.RGB)
    
    def define_graph(self):
        jpegs, labels = self.input()
        images = self.decode(jpegs)
        return (images, labels)
```

The error occurs while building the pipeline :
```python
pipe = DALIBackendPipeline(img_folder_path, batch_size, 8)
pipe.build()
```
I know GPU decoding is not supported on Jetson platform but is it also the case with other GPUs as well? Not sure what is the underlying issue.

**Comment by JanuszL** [comment]
Hi @pshwetank,

Please use:
```
self.decode = ops.ImageDecoder(device='mixed', output_type=types.RGB)
```
as in [this example.](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/getting%20started.html#Hybrid-decoding)

**Comment by pshwetank** [comment]
Thanks @JanuszL . It worked very well. I was curious why the sole gpu mode is not working in my case?
