### ISSUE TITLE
how to set dali Pipeline .build() only once?

### ISSUE THREAD

**Issue by xiuxin121** [NVIDIA/DALI#2723]
background：when infer online , get data(images/vedio) per request;  we want only build pipe once;   but in dai demo  the images dir must set befor pipe .build() is there any idea how can i  build pipe once;?
DALI DEMO:
image_dir="./images"
class HybridPipeline(Pipeline):
    def __init__(self, batch_size, num_threads, device_id):
        super(HybridPipeline, self).__init__(batch_size, num_threads, device_id, seed = 12)
        self.input = ops.FileReader(file_root = image_dir,initial_fill=8)
        self.decode = ops.ImageDecoder(device = "mixed", output_type = types.RGB)
        self.resize=ops.Resize(device = "gpu",interp_type = types.INTERP_LINEAR,resize_x=256,resize_y=256, minibatch_size =batch_size)
        self.transpose=ops.Transpose(device = "gpu",perm=[2,0,1])

    def define_graph(self):
        jpegs, labels = self.input()
        images = self.decode(jpegs)
        images = self.resize(images)
        images=self.transpose(images)
        # images are on the GPU
        return (images, labels)
 pipe = HybridPipeline(batch_size, 4, 0)
 pipe.build()  # we don't want build pepiline per request,but we don't know how to change image_dir after  pipe.build()
  for i in range(10):
        pipe_out = pipe.run()  ## 
        images, labels = pipe_out

**Comment by xiuxin121** [comment]
may be i can use always same image dir

**Comment by JanuszL** [comment]
Hi,
In your case, ExternalSource is probably the best option. I guess you receive data in the memory, not as a file.
I recommend checking [DALI backend for TRITON](https://github.com/triton-inference-server/dali_backend) as well, which would make the deployment of your inference workflow easier.

**Comment by JanuszL** [comment]
> may be i can use always same image dir

It won't work, as DALI discovers the files available only once at the build stage. So adding new files won't make DALI use them.

**Comment by xiuxin121** [comment]
> > may be i can use always same image dir
> 
> It won't work, as DALI discovers the files available only once at the build stage. So adding new files won't make DALI use them.
