### ISSUE TITLE
More labels in DALIClassificationIterator other than ["data", "label"]

### ISSUE THREAD

**Issue by pshwetank** [NVIDIA/DALI#2724]
Hi, I have been trying to get more than one label from pytorch wrapper of DALI. I correctly encoded it as an integer but it when I add it to DALIClassificationIterator, it gives the following error:

```bash
  File "/data/anaconda3/envs/torchenv/lib/python3.8/site-packages/nvidia/dali/plugin/pytorch.py", line 369, in __init__
    super(DALIClassificationIterator, self).__init__(pipelines, ["data", "label"],
  File "/data/anaconda3/envs/torchenv/lib/python3.8/site-packages/nvidia/dali/plugin/pytorch.py", line 170, in __init__
    self._first_batch = DALIGenericIterator.__next__(self)
  File "/data/anaconda3/envs/torchenv/lib/python3.8/site-packages/nvidia/dali/plugin/pytorch.py", line 189, in __next__
    category_outputs[self.output_map[j]] = out
IndexError: list index out of range
```

I think Index error is occuring because currently it only has two labels : 'data' and 'label'. Is it possible to have more labels?

**Comment by JanuszL** [comment]
Hi,
Please use `DALIGenericIterator` and pass `["data", "label_1", "label_2"]` to the `output_map`.
`DALIClassificationIterator` uses it under the hood with `["data", "label"]`. It is provided mostly as a simple wrapper for `DALIGenericIterator` with predefined values for most common classification tasks.

**Comment by pshwetank** [comment]
@JanuszL Thanks for answering the query.
