### ISSUE TITLE
How to speed up the tfrecord reading speed

### ISSUE THREAD

**Issue by ShiquanYu** [NVIDIA/DALI#2728]
Hi,

I'm using dali to read tfrecord in pytorch(**cpu only**), but the reading speed is very slow(about **100samples/s**, in tf_parser it can be raise to 2000samples/s) even the cpu utilization is low(800% in 36 core). 
I have tried to  **move the data from hhd to ssd**, set bigger num_threads(20~64), try different prefetch_queue_depth, but it's useless.

Here is my code:
```python
class CommonPipeline(Pipeline):
    def __init__(self, batch_size, num_threads, device_id, input_size, warp_kwargs:dict):
        super(CommonPipeline, self).__init__(batch_size, num_threads, device_id)

        self.device="cpu"
        self.input_size = np.array(input_size)
        max_obj_per_img = warp_kwargs.get('max_obj_per_img', 100)
        self.warp_kwargs = warp_kwargs
        self.decode = ops.ImageDecoder(device = "cpu", output_type = types.RGB)
        self.pad = ops.Pad(device="cpu", align=max_obj_per_img, axes=0)
        self.shape = ops.Shapes(device=self.device)
        self.warp_affine = ops.WarpAffine(device="cpu", size=input_size, fill_value=0.0, inverse_map=False, interp_type = types.INTERP_LINEAR)
        self.shape_extra = ops.ElementExtract(device="cpu", element_map=[0, 1])
        self.combine = ops.transforms.Combine(device="cpu")
        self.cmn = ops.CropMirrorNormalize(
            device=self.device,
            dtype=types.FLOAT,
            output_layout=types.NHWC,
            mean=self.warp_kwargs['normalize'][0],
            std=self.warp_kwargs['normalize'][1])

    def base_define_graph(self, inputs, bboxes, labels):
        device = self.device
        img = self.decode(inputs)
        if 'brightness' in self.warp_kwargs:
            delta = self.warp_kwargs['brightness']
            brightness = fn.uniform(range=[1-delta, 1+delta])
            img = fn.brightness(img, brightness=brightness, device=device)
        if 'contrast' in self.warp_kwargs:
            contrast = fn.uniform(range=self.warp_kwargs['contrast'])
            img = fn.contrast(img, contrast=contrast, device=device)
        if 'saturation' in self.warp_kwargs:
            saturation = fn.uniform(range=self.warp_kwargs['saturation'])
            img = fn.saturation(img, saturation=saturation, device=device)
        flip_probability = fn.coin_flip(probability = 0.5)
        img = self.cmn(img, mirror=flip_probability)
        img_shape = self.shape(img)
        h = fn.slice(img_shape, 0, 1, axes=[0], dtype=types.FLOAT)
        w = fn.slice(img_shape, 1, 1, axes=[0], dtype=types.FLOAT)
        bboxes = fn.reshape(bboxes, shape=(-1, 2))
        bboxes = fn.coord_flip(bboxes, flip_x=flip_probability, center_x=w/2)
        M = fn.reshape([1.0, 0.0, 0, 0.0, 1.0, 0], shape=(-1, 3))
        M_list = [M]
        if 'scale' in self.warp_kwargs:
            uniform = fn.uniform(range=self.warp_kwargs['scale'], shape=[1])
            uniform = fn.cat(uniform, uniform)
            M = fn.transforms.scale(scale=uniform, center=fn.cat(w/2, h/2))
            M_list.append(M)
        if 'rotation' in self.warp_kwargs and self.warp_kwargs['rotation'] > 0:
            degree = self.warp_kwargs['rotation']
            angle = fn.uniform(range=[-degree, degree])
            M = fn.transforms.rotation(angle=angle, center=fn.cat(w/2, h/2))
            M_list.append(M)
        if 'shear' in self.warp_kwargs and self.warp_kwargs['shear'] > 0:
            degree = self.warp_kwargs['shear']
            uniform = fn.uniform(range=[-degree, degree], shape=[1])
            uniform = fn.cat(uniform, uniform)
            M = fn.transforms.shear(device='cpu', angles=uniform, center=fn.cat(w/2, h/2))
            M_list.append(M)
        if len(M_list) > 1:
            M = self.combine(*M_list)
        else:
            M = M_list[0]
        img = self.warp_affine(img, matrix=M)
        img = fn.transpose(img, perm=[2, 0, 1])
        bboxes = fn.coord_transform(bboxes, MT=M)
        bboxes = fn.reshape(bboxes, shape=(-1, 4))
        return img, self.pad(bboxes), self.pad(labels), self.shape(labels)

import nvidia.dali.tfrecord as tfrec

class TFRecordPipeline(CommonPipeline):
    def __init__(self, batch_size, num_threads, device_id, num_gpus, tfrecord, tfrecord_idx, input_size, warp_kwargs):
        super(TFRecordPipeline, self).__init__(batch_size, num_threads, device_id, input_size, warp_kwargs)
        features = {
            'image_string': tfrec.FixedLenFeature((), tfrec.string, ""),
            'bboxes': tfrec.VarLenFeature([4], tfrec.float32, -1.0),
            'labels': tfrec.VarLenFeature([], tfrec.int64, -1),
        }
        self.input = ops.TFRecordReader(path = tfrecord,
                                        index_path = tfrecord_idx,
                                        # read_ahead = True,
                                        features = features,
                                        prefetch_queue_depth = num_threads//2 if num_threads>1 else 1,
                                        shard_id = 0,
                                        num_shards = 1,
                                        random_shuffle = True,
                                        initial_fill = batch_size*100,
                                        pad_last_batch = True)

    def define_graph(self):
        inputs = self.input(name="Reader")
        images = inputs["image_string"]
        bboxes = inputs["bboxes"]
        labels = inputs["labels"]
        return self.base_define_graph(images, bboxes, labels)

```

I have tried to simplify the function `base_define_graph`, but it's use less too:

```python

    def base_define_graph(self, inputs, bboxes, labels):
        device = self.device
        img = self.decode(inputs)
        flip_probability = fn.coin_flip(probability = 0.5)
        img = self.cmn(img, mirror=flip_probability)
        img_shape = self.shape(img)
        h = fn.slice(img_shape, 0, 1, axes=[0], dtype=types.FLOAT)
        w = fn.slice(img_shape, 1, 1, axes=[0], dtype=types.FLOAT)
        bboxes = fn.reshape(bboxes, shape=(-1, 2))
        bboxes = fn.coord_flip(bboxes, flip_x=flip_probability, center_x=w/2)
        M = fn.reshape([1.0, 0.0, 0, 0.0, 1.0, 0], shape=(-1, 3))
        M_list = [M]
        if len(M_list) > 1:
            M = self.combine(*M_list)
        else:
            M = M_list[0]
        img = self.warp_affine(img, matrix=M)
        img = fn.transpose(img, perm=[2, 0, 1])
        bboxes = fn.coord_transform(bboxes, MT=M)
        bboxes = fn.reshape(bboxes, shape=(-1, 4))
        return img, self.pad(bboxes), self.pad(labels), self.shape(labels)
```

I'm also tried to use `device="gpu"`, but some op is cpu only and I don't know how to copy data from gpu to cpu.

Can you give me some suggestions, thanks!

**Comment by ShiquanYu** [comment]
I find that because of I use cpu only cause this problem, but how can i move data between cpu&gpu?

It raise a lot of error like:

```python
RuntimeError: [/opt/dali/dali/pipeline/pipeline.cc:290] Assert on "it->second.has_cpu" failed: cpu input requested by op exists only on GPU. (op: 'CoordFlip', input: '__ArithmeticGenericOp_18')
```

If can change device to gpu.

**Comment by JanuszL** [comment]
To move data between CPU and GPU use:
```
input = self.cpu_op()
out_gpu = self.gpu_op(input.gpu())
```
Please keep in mind that not all operators support GPU backend, and once you move data to the GPU you cannot move it back to the CPU for the performance reasons inside the pipeline.

**Comment by ShiquanYu** [comment]
Hi @JanuszL ,

I have tried this way, but it also raise error like:

```
RuntimeError: [/opt/dali/dali/pipeline/pipeline.cc:290] Assert on "it->second.has_cpu" failed: cpu input requested by op exists only on GPU. (op: 'WarpAffine', input: 'Reshape 5')
```

Here is my code, all inputs/ops set to gpu:

```python
    def base_define_graph(self, inputs, bboxes, labels):
        device = "gpu"
        img = self.decode(inputs)
        flip_probability = fn.coin_flip(probability = 0.5)
        img = self.cmn(img, mirror=flip_probability)
        M = fn.reshape([1.0, 0.0, 0, 0.0, 1.0, 0], shape=(-1, 3), device=device)
        M_list = [M]
        if len(M_list) > 1:
            M = self.combine(*M_list)
        else:
            M = M_list[0]
        img = self.warp_affine(img.gpu(), matrix=M.gpu())
        img = fn.transpose(img, perm=[2, 0, 1])
        return img, self.pad(bboxes), self.pad(labels), self.shape(labels)
```
There are `fn.coord_flip` and `fn.coord_transform` in the same error.

**Comment by ShiquanYu** [comment]
Look for this code:

```python
    def base_define_graph(self, inputs, bboxes, labels):
        device = "gpu"
        img = self.decode(inputs)             # now `img` is in gpu
        img_shape = self.shape(img)       # `img_shape` is in gpu, if I set device to cpu, it will raise error
        flip_probability = fn.coin_flip(probability = 0.5)
        w = fn.slice(img_shape, 1, 1, axes=[0], dtype=types.FLOAT)  # `w` is in gpu, if I set device to cpu, it will raise error
        bboxes = fn.reshape(bboxes, shape=(-1, 2))
        bboxes = fn.coord_flip(bboxes, flip_x=flip_probability, center_x=w/2)
```

it raise error:

```
RuntimeError: [/opt/dali/dali/pipeline/pipeline.cc:290] Assert on "it->second.has_cpu" failed: cpu input requested by op exists only on GPU. (op: 'CoordFlip', input: '__ArithmeticGenericOp_18')
```
If I set `center_x` to a number, it can works correctly. Does it mean the parameter `center_x` must be a cpu input? But how can I get cpu input from a data in gpu?

I find that some parameters in GPU op must be gpu input, but parameters must be cpu input, I don't know how to distinguish whether this is gpu input or cpu input.

I'm very confused about this, please give me some suggestions.

Thanks!

**Comment by JanuszL** [comment]
Hi @ShiquanYu,

The rule of thumb is that all named arguments need to exist on the CPU.

Regarding:
> RuntimeError: [/opt/dali/dali/pipeline/pipeline.cc:290] Assert on "it->second.has_cpu" failed: cpu input requested by op exists only on GPU. (op: 'WarpAffine', input: 'Reshape 5')

In this case `img = self.warp_affine(img.gpu(), matrix=M.gpu())`, `M` should be on the CPU, not GPU as stated in the error message.

> RuntimeError: [/opt/dali/dali/pipeline/pipeline.cc:290] Assert on "it->second.has_cpu" failed: cpu input requested by op exists only on GPU. (op: 'CoordFlip', input: '__ArithmeticGenericOp_18')

In this case you cannot `img_shape = self.shape(img)` as your shape is on the GPU. Please use [`PeekImageShape`](*https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.ops.PeekImageShape) on raw, undecoded image `img_shape = self.peek_shape(inputs)` to have image shape on the GPU.

**Comment by ShiquanYu** [comment]
Hi @JanuszL ,

Thanks for your help in recent weeks.

Now my project works correctly and more faster than it before. Finally I resolve the problem by:

```python
img = self.decode(inputs, device='cpu')
img_shape = self.shape(img)
img = img.gpu()
```

DALI is powerful, but it seems that DALI has no CPU optimization. At the beginning, I use `PythonFunctions` to link up the old framework, it's simple and can be well compatible with the old framework, nut quickly I find that `PythonFunctions` can't run asynchronously. So I have to reconstruction all functions with DALI's API, the CPU is idle, so I decide to preprocess data in cpu, to free up more GPU for training, but even if I enabled `exec_async`, the DALI reading data speed is still very slow in CPU.

Maybe this goes against the original intention of DALI design, but I hope DALI can have a better optimize in CPU. Data can be transferred between CPU and GPU instead of only being transferred from CPU to GPU, maybe it is slower but it's much more friendly to novices, DALI can raise a warning instead an error.

Finally, thanks again for your help and DALI, and hope this is my last issue under the DALI T^T

**Comment by JanuszL** [comment]
> DALI is powerful, but it seems that DALI has no CPU optimization

We mostly focus on optimization for the GPU, rarely for the CPU. However, we would appreciate any community effort to optimize also DALI CPU operators.

`PythonFunctions` is mostly meant for prototyping, not for the performance.

> the DALI reading data speed is still very slow in CPU.

Do you mean processing or reading itself? I don't think DALI can do much about your disc IO speed, it is mostly meant for processing speed optimization.

> Data can be transferred between CPU and GPU instead of only being transferred from CPU to GPU

I think it would defeat DALI as a high performant GPU processing library and encourage inefficient coding patterns. In a such situation, in most cases sticking to the CPU side would be equally fast.

**Comment by ShiquanYu** [comment]
> > the DALI reading data speed is still very slow in CPU.
> 
> Do you mean processing or reading itself? I don't think DALI can do much about your disc IO speed, it is mostly meant for processing speed optimization.

I mean processing, it can be 200samples/s while I set device to CPU(the CPU is almost free), but it raise to 2500~3000samples/s while set the device to GPU.

**Comment by JanuszL** [comment]
> I mean processing, it can be 200samples/s while I set device to CPU(the CPU is almost free), but it raise to 2500~3000samples/s while set the device to GPU.

I think that is the whole reason why DALI was developed. To accelerate processing on the GPU. Even if more effort is put into CPU optimization I don't think it can match GPU.
