### ISSUE TITLE
Custom crop args

### ISSUE THREAD

**Issue by tarunn2799** [NVIDIA/DALI#2746]
Hey so i've created a Pipeline where I read images using `ops.FileReader` with a file_list (txt file) containing images, labels. 
In my dataset csv, I have another column called "crops" for each of these data points that specifies the dimensions of the crop that should be applied to each corresponding image. 

I've defined my graph within the pipeline that looks something like this 

```
def define_graph: 
   jpegs, labels = self.input() #ops.FileReader
   jpegs = ops.ImageDecoder(args)(jpegs)
   jpegs = dali.ops.Crop("insert crop args here")(jpegs)
```

I noticed that jpegs is a DataNode object and I can't seem to extract file information from it. How do I pass the crop dims from my csv corresponding to my filename,  to my Crop function here?

I've explored ExternalSource as an option, but I'm keeping that as my last resort at the moment.

**Comment by JanuszL** [comment]
Hi,

Can you update DALI to the latest version and check again (the most recent one is 0.31)?
Can you also check if [this example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/dataloading_lmdb.html) works?

**Comment by JanuszL** [comment]
Hi,

I think the easiest solution for you is to use [`ExternalSource`](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/external_input.html) operator to load images together with any custom data you need.
The second thing to consider is that you probably need to use [`Slice`](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.ops.Slice) operator as you want per sample shape and anchor while the Crop operator applies the same crop across all samples in the batch (you can even try using [`ImageDecoderSlice`](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.ops.ImageDecoderSlice) to avoid decoding not used part of the image).

**Comment by tarunn2799** [comment]
Hey, thanks for the quick response. 

I'm a little apprehensive towards using ExternalSource because of the loss in performance, but yeah I'll definitely check it out. 
In the meantime, I just stumbled upon COCOReader within dali.ops, and it sort of claims to be doing what I exactly need, just that the crops need to come in a JSON file. Will this work for my use case since it returns images, bbox, labels? 
Also, I'm not able to get a clear idea of how to pass my images, labels to COCOReader, and the format to be followed to create an annotation_file. Could you help me out with that?

**Comment by JanuszL** [comment]
Hi,
COCO could be a way to go. You can learn more about this data format [here](https://cocodataset.org/). I think it should be doable to use bboxes as a window for the Slice operator.

**Comment by tarunn2799** [comment]
Hi, so once I get the bbox values out of COCOReader, how do I pass that to Slice? 
I don't quite understand how to use that function 😅

**Comment by JanuszL** [comment]
`Slice` accepts 3 inputs:
- data
- anchors
- shape
If you split bboxes [n, 4] into two tensors [N, 2] and [N, 2] using Slice operator:
```
first_half = fn.slice(bb, 0 2, axes=[1])
second_half = fn.slice(bb, 2, 2, axes=[1])
```
You also need to call reshape to collapse unneeded dimensions:
```
fn.reshape(fn.slice(bb, 0, 2, axes=[1]), shape=[-1])
```
In effect you can:
```
out = fn.slice(images, fn.reshape(fn.slice(bbox, 0, 2, axes=[1]), shape=[-1]), fn.reshape(fn.slice(bbox, 2, 2, axes=[1]), shape=[-1]))
```

**Comment by tarunn2799** [comment]
Okay that makes sense. What does [0,2] and [2,2] within the slice function denote exactly?

**Comment by JanuszL** [comment]
These are anchor and shape, please check [`Slice` operator documentation for details](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.ops.Slice).

**Comment by tarunn2799** [comment]
So I got slice and COCO Reader to return what I want, thank you.  
My code is basically 
`image = fn.slice(image_batch,  anchor, shape, axes)`

Now it worked for me when I passed a static value for anchor and shape args like your example, and it cut out that same window for me from all the images in my image_batch. 

How do I go about it if I want to pass a different slice value for each of my images in the image_batch? Assuming that my COCO reader returns the corresponding bounding box values for each batch in the form of a TensorList? 
![image](https://user-images.githubusercontent.com/28048963/109695605-1c0de580-7bb2-11eb-8e17-572ff19204b0.png)

Above fig : example of what my bounding box dim output looks like from COCOReader (obtained by passing through a pythonfunction operator

```
    def define_graph(self):
        jpegs, bboxes, labels = self.input() #COCOReader outputs three TensorLists for me 
        image = self.decode(jpegs)  #ImageDecoder
        image = fn.slice(image, anchor, shape, axes=[0, 1], device = 'gpu') 
#image is a batch of images, what should anchor and shape be here?
 
```

**Comment by JanuszL** [comment]
If I understand your ask correctly, it should be something like:
```
 def define_graph(self):
        jpegs, bbox_coords, labels = self.input() #COCOReader outputs three TensorLists for me 
        image = self.decode(jpegs)  #ImageDecoder
        anchor =  fn.reshape(fn.slice(bbox_coords, 0, 2, axes=[1]), shape=[-1])
        shape =  fn.reshape(fn.slice(bbox_coords, 2, 2, axes=[1]), shape=[-1])
        image = fn.slice(image, anchor, shape, axes=[0, 1], device = 'gpu') 
```
If you have distinct bbox data for each image it will be applied to it (it can differ from sample to sample).
