### ISSUE TITLE
std::bad_alloc when training with single machine multi-gpu

### ISSUE THREAD

**Issue by mandylyin** [NVIDIA/DALI#2752]
I trained ImageNet with the following command:
python -m torch.distributed.launch --nproc_per_node=2 --nnodes=1 --node_rank=0 --master_addr=localhost --master_port=6006 main.py ImageNet -j 16 --opt-level=O1
And I got a std::bad_alloc error. The training script is main.py from the examples of pytorch resnet50.
Here is the log:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
opt_level = O1
keep_batchnorm_fp32 = None <class 'NoneType'>
loss_scale = None <class 'NoneType'>

CUDNN VERSION: 8005

opt_level = O1
keep_batchnorm_fp32 = None <class 'NoneType'>
loss_scale = None <class 'NoneType'>

CUDNN VERSION: 8005

=> creating model 'resnet18'
=> creating model 'resnet18'
Selected optimization level O1:  Insert automatic casts around Pytorch functions and Tensor methods.

Defaults for this optimization level are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Processing user overrides (additional kwargs that are not None)...
After processing overrides, optimization options are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
read 1281167 files from 1000 directories
read 1281167 files from 1000 directories
Traceback (most recent call last):
  File "main.py", line 569, in <module>
    main()
  File "main.py", line 298, in main
    pipe.build()
  File "/home/ubuntu/anaconda3/envs/open-mmlab-2.9/lib/python3.7/site-packages/nvidia/dali/pipeline.py", line 492, in build
    self._pipe.Build(self._names_and_devices)
RuntimeError: Critical error when building pipeline:
Error when constructing operator: ImageDecoderRandomCrop encountered:
std::bad_alloc
Current pipeline object is no longer valid.
Traceback (most recent call last):
  File "main.py", line 569, in <module>
    main()
  File "main.py", line 298, in main
    pipe.build()
  File "/home/ubuntu/anaconda3/envs/open-mmlab-2.9/lib/python3.7/site-packages/nvidia/dali/pipeline.py", line 492, in build
    self._pipe.Build(self._names_and_devices)
RuntimeError: Critical error when building pipeline:
Error when constructing operator: ImageDecoderRandomCrop encountered:
std::bad_alloc
Current pipeline object is no longer valid.
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/open-mmlab-2.9/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/anaconda3/envs/open-mmlab-2.9/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/anaconda3/envs/open-mmlab-2.9/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/ubuntu/anaconda3/envs/open-mmlab-2.9/lib/python3.7/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/ubuntu/anaconda3/envs/open-mmlab-2.9/bin/python', '-u', 'main.py', '--local_rank=1', '/home/ubuntu/zll/ImageNet', '-j', '16', '--opt-level=O1']' returned non-zero exit status 1.

**Comment by JanuszL** [comment]
Hi,
Can you try to reduce the number of cpu threads to 3 or 4 `-j 4` and reducing the batch size to `-b 64` (just for a basic check)?

**Comment by mandylyin** [comment]
@JanuszL I used -j 4 and -b 64 to train again, and it works. So std::bad_alloc is an error about out of memory. Thank you for the help.

**Comment by JanuszL** [comment]
@mandylyin - yes, the `std::bad_alloc` error means that the library was unable to allocate memory.
