### ISSUE TITLE
AttributeError: module 'nvidia.dali.ops' has no attribute 'random'

### ISSUE THREAD

**Issue by thierrypin** [NVIDIA/DALI#2763]
I'm trying to implement randomized data augmentation using DALI (as in https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.ops.random.Uniform), but I have this error:

```
AttributeError: module 'nvidia.dali.ops' has no attribute 'random'
```

My DALI version is 0.29.0.

**Comment by JanuszL** [comment]
Hi @thierrypin,
The documentation you linked applies to the most recent stable version - 0.31, please update DALI to the latest.

**Comment by JanuszL** [comment]
You can also check [0.31 user guide](https://docs.nvidia.com/deeplearning/dali/archives/dali_031/user-guide/docs/index.html) that is relevant to your version of DALI.
