### ISSUE TITLE
AttributeError: module 'nvidia.dali.fn' has no attribute 'readers'

### ISSUE THREAD

**Issue by qingqing01** [NVIDIA/DALI#2768]
When I use DALI in PyTorch by reference to the example  https://github.com/NVIDIA/DALI/blob/master/docs/examples/use_cases/pytorch/resnet50/main.py

There is error:

```
    images, labels = fn.readers.file(file_root=data_dir,
AttributeError: module 'nvidia.dali.fn' has no attribute 'readers'
```

DALI version: 0.31.0
PyTorch version: 1.7.1+cu101

**Comment by JanuszL** [comment]
Hi,
If you are using 0.31 please use the example from that particular version - https://github.com/NVIDIA/DALI/blob/v0.31.0/docs/examples/use_cases/pytorch/resnet50/main.py. If you want to use the top of the tree please install the latest nightly/weekly build.

**Comment by qingqing01** [comment]
@JanuszL Got it. Thansk for your help!
