### ISSUE TITLE
jpeg turbo and llvm error. 

### ISSUE THREAD

**Issue by owenustc** [NVIDIA/DALI#277]
Hi, I have meet the error as follow.  But I have install libjeg-turbo 2.0, and llvm-6.0 tools. I don't know why, could anyone help me?.  my libjpeg-turbo is in /opt/, and I had copy library and header files to /usr/lib64 and /usr/inclue.
-- DALI version: 0.5.0dev
-- Failed to find LLVM FileCheck
-- git Version: v1.4.0-505be96a
-- Version: 1.4.0
-- Performing Test HAVE_STD_REGEX -- success
-- Performing Test HAVE_GNU_POSIX_REGEX -- failed to compile
-- Performing Test HAVE_POSIX_REGEX -- success
-- Performing Test HAVE_STEADY_CLOCK -- success
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find JpegTurbo: Found unsuitable version "", but required is at
  least "1.5" (found /usr/include)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleSt

**Comment by JanuszL** [comment]
Super. Ciesze sie ze zacynasz sie udzielac na forum GitHubowym.

Br,
Janusz

________________________________

**Comment by owenustc** [comment]
I had installed JpegTurbo library, which the two header files, named  jconfig.h and turbojpeg.h, is in /usr/include.  But I also meet the above error.  The version of turbojpeg is  2.0, which is too higher??
root@nodeip-dev115:/opt/libjpeg-turbo/include# cat /usr/include/jconfig.h
/* Version ID for the JPEG library.
 * Might be useful for tests like "#if JPEG_LIB_VERSION >= 60".
 */
#define JPEG_LIB_VERSION  62

/* libjpeg-turbo version */
#define LIBJPEG_TURBO_VERSION  2.0.1

/* libjpeg-turbo version in integer form */
#define LIBJPEG_TURBO_VERSION_NUMBER  2000001

/* Support arithmetic encoding */
#define C_ARITH_CODING_SUPPORTED 1

/* Support arithmetic decoding */

#endif
root@nodeip-dev115:/opt/libjpeg-turbo/include# cat /usr/include/turbojpeg.h  | more
/*
 * Copyright (C)2009-2015, 2017 D. R. Commander.  All Rights Reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * - Redistributions of source code must retain the above copyright notice,
 *   this list of conditions and the following disclaimer.
 * - Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 * - Neither the name of the libjpeg-turbo Project nor the names of its
 *   contributors may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS",
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef __TURBOJPEG_H__
#define __TURBOJPEG_H__

#if defined(_WIN32) && defined(DLLDEFINE)
#define DLLEXPORT  __declspec(dllexport)
#else
#define DLLEXPORT
#endif
#define DLLCALL

**Comment by JanuszL** [comment]
Hi,
We relay on pkg-config at the first place to discover libturbojpeg version and path. If you just copied headers pkg-config pc is still old and may return some strange value. Please check what you gets after issuing:
```
pkg-config --modversion libturbojpeg
```
As some temporary fix you can try to comment out following lines in the ```DALI\cmake\modules\FindJpegTurbo.cmake```:
```
# find_package(PkgConfig QUIET)
# if (PkgConfig_FOUND)
#     # use pkg-config only if it has been found, if it fails it fall back to
#     # JPEG_TURBO_ROOT_DIR hint
#     pkg_check_modules(JpegTurbo QUIET libturbojpeg)
# endif()
```
in order to force cmake to use only JPEG_TURBO_ROOT_DIR.

**Comment by JanuszL** [comment]
#285 should address your case.
