### ISSUE TITLE
failed to use caffeReader load lmdb dataset

### ISSUE THREAD

**Issue by zhou3968322** [NVIDIA/DALI#2772]
I tried to use caffe_reader read lmdb dataset as in https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/dataloading_lmdb.html.

as following:

```python
pipe = Pipeline(batch_size=batch_size, num_threads=4, device_id=0)
with pipe:
    jpegs, labels = fn.caffe_reader(path=db_folder)
    images = fn.image_decoder(jpegs, device="mixed", output_type=types.RGB)
    pipe.set_outputs(images, labels)
pipe.build()
pipe_out = pipe.run()
```
and I failed with error ,
```bash
RuntimeError: Critical error in pipeline:
Error when executing CPU operator CaffeReader encountered
```
it seems like caffeReader is not valid for two cursons.

but dali is not easily to debug and see what happened when loading lmdb, any way to solve it ?

successful pytorch dataset code is as followings:
```python
    def __init__(self, ... ):
        ...
        self.data_root = data_root
        self.env = lmdb.open(data_root, max_readers=32, readonly=True, lock=False, readahead=False, meminit=False)

    def __getitem__(self, index):
        assert index <= len(self), 'index range error'
        _image_db = self.env.open_db(b"image")
        _label_db = self.env.open_db(b"label")
        with self.env.begin(write=False) as txn:
            image_cursor = txn.cursor(db=_image_db)
            label_cursor = txn.cursor(db=_label_db)
            byte_index = bytes('%09d' % (index + 1), encoding='utf-8')
            imgbuf = image_cursor.get(byte_index)
            label = str(label_cursor.get(byte_index), encoding='utf-8')
           ....
```

**Comment by JanuszL** [comment]
Hi,
DALI doesn't have a generic LMDB reader, only a caffe and caffe2 reader which assumes a certain layout of the LMDB database. You can read more about it at https://github.com/NVIDIA/DALI/issues/2747.
If you have a custom LMDB structure I think it would be best to use ['ExternalSource operator'](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/external_input.html).

**Comment by zhou3968322** [comment]
ok, thanks. external source operator perhaps is not as fast as caffeReader. 
Any dali c api develop documentation to write my own lmdb Reader?

**Comment by JanuszL** [comment]
With the recent improvement it can be executed in parallel, please check the most [recent documentation](https://docs.nvidia.com/deeplearning/dali/master-user-guide/docs/supported_ops.html#nvidia.dali.fn.external_source) of the operator.

Regarding the documentation we don't have any, I would start by looking into [`readers` code](https://github.com/NVIDIA/DALI/tree/master/dali/operators/reader). In general, they are separated into the loader that reads sample by sample, generic loader part you probably should not bother about that is responsible for shuffling, a parser that interprets read data, and the operator itself that connects things.

**Comment by zhou3968322** [comment]
[create_a_custom_operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/custom_operations/custom_operator/create_a_custom_operator.html#CPU-Operator-Implementation), this can help us to write a new reader and the way to use it .

**Comment by JanuszL** [comment]
> create_a_custom_operator, this can help us to write a new reader and the way to use it .

This could be a way, although DALI doesn't expose all the necessary internals to build on top of the existing Reader infrastructure. So you need to deal with the sharing and shuffling on your own, as well as you may want to run a background thread to fetch data in parallel.
