### ISSUE TITLE
Normalize an image with custom mean and stddev across 3 channels?

### ISSUE THREAD

**Issue by tarunn2799** [NVIDIA/DALI#2775]
Hey, so I am trying to normalize an image using ops.Normalize, and I noticed that the mean and stddev arguments take custom values of either a single float (across all channels) or a TensorList of floats. 

Say I have an image and I want to normalize it with values like [0.432, 0.485, 0.583] across RGB channels, and pass this list to the mean/stdev argument within ops.Normalize in my Pipeline, how do I go about it? 

I've tried passing a np.array/ list/ torch.Tensor but they obviously didn't work. Is it possible to create a TensorList with these values within the pipeline?

**Comment by JanuszL** [comment]
Hi @tarunn2799,

I think the easiest would be to use [`CropMirrorNormalize` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.ops.CropMirrorNormalize). Just:
```
fn.crop_mirror_normalize(images,
                                      dtype=types.FLOAT,
                                      mean=[0.485 * 255,0.456 * 255,0.406 * 255],
                                      std=[0.229 * 255,0.224 * 255,0.225 * 255])
```
should work.

**Comment by tarunn2799** [comment]
Oh that's convenient! Thank you!
