### ISSUE TITLE
Get image size for resize?

### ISSUE THREAD

**Issue by zhiheng-ldj** [NVIDIA/DALI#2780]
Hi,

Thanks for your help!

I am trying to get image size in pipeline and do some mathematic operations.

For example,

~~~
shape = self.get_shape(images)
size = fn.slice(shape, 0, 2, axes=[0])
scale = random.choice(self.scales)
w_step = 146 * (1-scale) // 4
h_step = (256 - 146*scale) // 4

crop_x, crop_y = self.get_crop_param(w_step, h_step)
images = self.crop(images, crop_pos_x=crop_x, crop_pos_y=crop_y)
~~~

146 is the height and 256 is the width. Can I obtain it from shape or size?

Thanks!

**Comment by JanuszL** [comment]
Hi,
In your case it is better to use [`PeekImageShape` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.ops.PeekImageShape) on encoded images as the data would be on the CPU, while [`Shapes` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.ops.Shapes) returns the data on the same backend as the input. So if `images` are on the GPU you would get GPU output and you won't be able to feed it to crop/slice operator.
Your pipeline should rather look like:
```
shape = fn.peek_image_shape(images)
size = fn.slice(shape, 0, 2, axes=[0])
scale = fn.random.uniform(values=self.scales, shape=[1])
# if you need to have the same scale for the whole batch
#  scale = fn.permute_batch(scale , indices=[0]*dali.Pipeline.current().batch_size)
w_step = 146 * (1-scale) // 4
h_step = (256 - 146*scale) // 4
crop_x, crop_y = self.get_crop_param(w_step, h_step)
images = self.crop(images, crop_pos_x=crop_x, crop_pos_y=crop_y)
```
assuming that `get_crop_param` is consists only from DALI supported operations. You cannot expect this function to be executed for every DALI run.
You can also check https://github.com/NVIDIA/DALI/issues/2559#issuecomment-791294208 for a reference,

**Comment by zhiheng-ldj** [comment]
> Hi,
> In your case it is better to use [`PeekImageShape` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.ops.PeekImageShape) on encoded images as the data would be on the CPU, while [`Shapes` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.ops.Shapes) returns the data on the same backend as the input. So if `images` are on the GPU you would get GPU output and you won't be able to feed it to crop/slice operator.
> Your pipeline should rather look like:
> 
> ```
> shape = fn.peek_image_shape(images)
> size = fn.slice(shape, 0, 2, axes=[0])
> scale = fn.random.uniform(values=self.scales, shape=[1])
> # if you need to have the same scale for the whole batch
> #  scale = fn.permute_batch(scale , indices=[0]*dali.Pipeline.current().batch_size)
> w_step = 146 * (1-scale) // 4
> h_step = (256 - 146*scale) // 4
> crop_x, crop_y = self.get_crop_param(w_step, h_step)
> images = self.crop(images, crop_pos_x=crop_x, crop_pos_y=crop_y)
> ```
> 
> assuming that `get_crop_param` is consists only from DALI supported operations. You cannot expect this function to be executed for every DALI run.
> You can also check [#2559 (comment)](https://github.com/NVIDIA/DALI/issues/2559#issuecomment-791294208) for a reference,

Hi,

Thanks for your help!

I mean 146 is the height and 256 is the width of a specific image. Can I get them from fn.peek_image_shape or something like that?

Just like this:

~~~
shape = fn.peek_image_shape(images)
size = fn.slice(shape, 0, 2, axes=[0])
scale = fn.random.uniform(values=self.scales, shape=[1])
# if you need to have the same scale for the whole batch
#  scale = fn.permute_batch(scale , indices=[0]*dali.Pipeline.current().batch_size)
w_step = size[0] * (1-scale) // 4
h_step = (size[1] - size[0]*scale) // 4
crop_x, crop_y = self.get_crop_param(w_step, h_step) # random choose a certain region to be cropped baed on steps
images = self.crop(images, crop_pos_x=crop_x, crop_pos_y=crop_y)
~~~

Can we do something like that? Or equivalent idea?

**Comment by JanuszL** [comment]
@zhiheng-ldj,
Something like bellow should extract width and height of the image:
```
shape = fn.peek_image_shape(jpeg)
w = fn.slice(shape, 0, 1, axes=[0])
h = fn.slice(shape, 1, 1, axes=[0])
```

**Comment by zhiheng-ldj** [comment]
> @zhiheng-ldj,
> Something like bellow should extract width and height of the image:
> 
> ```
> shape = fn.peek_image_shape(jpeg)
> w = fn.slice(shape, 0, 1, axes=[0])
> h = fn.slice(shape, 1, 1, axes=[0])
> ```

It seems we can only get shape of jpegs, can we get shape of resized image?

Besides, w and h should be DataNode. How should I process them as numbers?

Specifically, here is how I define self.get_crop_param:

~~~
    def get_crop_param(self, w_step,h_step):

            crop_param = [(4 * w_step, 0),  # upper right
                    (0, 4 * h_step),  # lower left
                    (4 * w_step, 4 * h_step),  # lower right
                    (2 * w_step, 2 * h_step),
                    (0, 2 * h_step),  # center left
                    (4 * w_step, 2 * h_step),  # center right
                    (2 * w_step, 4 * h_step),  # lower center
                    (2 * w_step, 0 * h_step),  # upper center
                    (1 * w_step, 1 * h_step),  # upper left quarter
                    (3 * w_step, 1 * h_step),  # upper right quarter
                    (1 * w_step, 3 * h_step),  # lower left quarter
                    (3 * w_step, 3 * h_step)  # lower right quarter
                    ]
            return random.choice(crop_param)
~~~

Can we realize it with DataNode in Pipeline? Or convert DataNode to real number?

Thanks!!

**Comment by JanuszL** [comment]
You cannot convert DataNode to a real number. It represents an output in the DALI graph. You can still call mathematical operations that DALI implements as well, but you cannot implement imperative python code.
I wonder if you need to know the size of the image after all? `crop_pos_x` and `crop_pos_y` are in relative coordinates. From the [`Crop` operator documentation](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.ops.Crop):
```
The actual position is calculated as crop_x = crop_pos_x * (W - crop_W), where crop_pos_x is the normalized position, W is the width of the image, and crop_W is the width of the cropping window.
```
If you just want to randomly pic one of 25 windows in your image, just:
```
crop_x_pos = fn.random.uniform(values=[0, 0,25 , 0,5, 0,75 , 1], shape=[1])
crop_y_pos = fn.random.uniform(values=[0, 0,25 , 0,5, 0,75 , 1], shape=[1])
images = self.crop(images, crop_pos_x=crop_x_pos , crop_pos_y=crop_y_pos)
```

**Comment by zhiheng-ldj** [comment]
> You cannot convert DataNode to a real number. It represents an output in the DALI graph. You can still call mathematical operations that DALI implements as well, but you cannot implement imperative python code.
> I wonder if you need to know the size of the image after all? `crop_pos_x` and `crop_pos_y` are in relative coordinates. From the [`Crop` operator documentation](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.ops.Crop):
> 
> ```
> The actual position is calculated as crop_x = crop_pos_x * (W - crop_W), where crop_pos_x is the normalized position, W is the width of the image, and crop_W is the width of the cropping window.
> ```
> 
> If you just want to randomly pic one of 25 windows in your image, just:
> 
> ```
> crop_x_pos = fn.random.uniform(values=[0, 0,25 , 0,5, 0,75 , 1], shape=[1])
> crop_y_pos = fn.random.uniform(values=[0, 0,25 , 0,5, 0,75 , 1], shape=[1])
> images = self.crop(images, crop_pos_x=crop_x_pos , crop_pos_y=crop_y_pos)
> ```

Hi,

From my understanding, it will sample a crop segment. For example, crop_x_pose=0.75 and crop_y_pose=0.5. It will yield a section which x ranging from (0,0.75) and y ranging from (0,0.5)?

Can I implement a segment from (0.5,0.75) and (0.25,0.5)?

Is that available?

Thanks!!

**Comment by JanuszL** [comment]
@zhiheng-ldj,
crop_x_pose=0.75 and crop_y_pose=0.5 will yield (in absolute coordinates):

`(0.75 * (W - crop_W), 0.75 * (W - crop_W) + crop_W) and (0.25 * (H - crop_H), 0.25 * (H - crop_H) + crop_H)`

The crop operator has a cropping window fixed in size, if you need something flexible please check the slice operator that accepts anchor and shape that can be adjusted per each sample.

**Comment by zhiheng-ldj** [comment]
> @zhiheng-ldj,
> crop_x_pose=0.75 and crop_y_pose=0.5 will yield (in absolute coordinates):
> 
> `(0.75 * (W - crop_W), 0.75 * (W - crop_W) + crop_W) and (0.25 * (H - crop_H), 0.25 * (H - crop_H) + crop_H)`
> 
> The crop operator has a cropping window fixed in size, if you need something flexible please check the slice operator that accepts anchor and shape that can be adjusted per each sample.

Hi,

Can I code as following?

~~~
        shape = self.shape(images)
        w = fn.slice(shape, 0, 1, axes=[0])
        h = fn.slice(shape, 1, 1, axes=[0])

        crop_x_pos = fn.uniform(values=[0, 0,25 , 0,5, 0,75 , 1], shape=[1])
        crop_y_pos = fn.uniform(values=[0, 0,25 , 0,5, 0,75 , 1], shape=[1])
        # crop_x_pos, crop_y_pos = fn.uniform(values=[[0, 0,25] ,[0,5, 0,75]], shape=[2])
        images = self.crop(images.gpu(), crop_pos_x=crop_x_pos , crop_pos_y=crop_y_pos, crop_w=0.75*w, crop_h=0.75*h)
~~~

It raises that:

~~~
RuntimeError: Critical error in pipeline:
Error when executing GPU operator Crop encountered:
[../dali/operators/image/crop/crop_attr.h:162] Assert on "anchor_norm[dim] >= 0.0f && anchor_norm[dim] <= 1.0f" failed: Anchor for dimension 1 (25.000000) is out of range [0.0, 1.0]
~~~

Can I fix it?

**Comment by JanuszL** [comment]
HI,
If you want to set the crop window relative to the image size you should use slice.
```
images, labels = fn.readers.file(file_root="test",
                                   shard_id=0,
                                   num_shards=1,
                                   random_shuffle=False,
                                   name="Reader")
  raw_images = fn.decoders.image(images, device="mixed", output_type=types.RGB)

  crop_x_pos = fn.uniform(values=[0, 0.0625 , 0.125, 0.1875 , 0.25], shape=[1])
  crop_y_pos = fn.uniform(values=[0, 0.0625 , 0.125, 0.1875 , 0.25], shape=[1])
  anchor = fn.cat(crop_x_pos, crop_y_pos)
  images = fn.slice(raw_images, anchor, [0.75, 0.75])
```
should do. You set the shape to be 0.75x0.75 of image width and height respectively, and randomly selects anchor from 5 values between 0 and 0.25.
Is that something you want to do?
