### ISSUE TITLE
enbale

### ISSUE THREAD

**Issue by owenustc** [NVIDIA/DALI#279]
hi, I want to enable tfrecord.  And follow dali note to use BUILD_PROTO3. But I met the error as follow. 
I want to know what is the right cmake option?  The version of my libprotoc is 2.6.   
ing dependencies of target benchmark
example.protofeature.proto::3:10: Unrecognized syntax identifier "proto3".  This parser only recognizes "proto2".56:
10: Unrecognized syntax identifier "proto3".  This parser only recognizes "proto2".
dali/pipeline/operators/reader/parser/CMakeFiles/TF_PROTO.dir/build.make:62: recipe for target 'dali/pipeline/operators/reader/parser/example.pb.cc' failed
make[2]: *** [dali/pipeline/operators/reader/parser/example.pb.cc] Error 1
make[2]: *** Waiting for unfinished jobs....
dali/pipeline/operators/reader/parser/CMakeFiles/TF_PROTO.dir/build.make:70: recipe for target 'dali/pipeline/operators/reader/parser/feature.pb.cc' failed
make[2]: *** [dali/pipeline/operators/reader/parser/feature.pb.cc] Error 1
CMakeFiles/Makefile2:925: recipe for target 'dali/pipeline/operators/reader/parser/CMakeFiles/TF_PROTO.dir/all' failed
make[1]: *** [dali/pipeline/operators/reader/parser/CMakeFiles/TF_PROTO.dir/all] Error 2

**Comment by JanuszL** [comment]
Hi,
To use tfrecord you need libprotoc in version higher than 3 as we are using proto3 syntax - https://developers.google.com/protocol-buffers/docs/proto3.
Now we are using 3.5.1 version, please check with that one.
