### ISSUE TITLE
Assert on "input_device == "cpu"" failed when use ops.Resize after ops.ImageDecoder

### ISSUE THREAD

**Issue by zhou3968322** [NVIDIA/DALI#2795]
Hey, I use ops.Resize after ops.ImageDecoder, but raised Exception:

```
Traceback (most recent call last):
  File "/data/xxx/project/xxx/datasets/tr_dali_dataset.py", line 206, in <module>
    train_pipe.build()
  File "/data/xxx/miniconda3/lib/python3.7/site-packages/nvidia/dali/pipeline.py", line 490, in build
    self._prepare_graph(define_graph)
  File "/data/xxx/miniconda3/lib/python3.7/site-packages/nvidia/dali/pipeline.py", line 453, in _prepare_graph
    related_logical_id[op.relation_id] = self._pipe.AddOperator(op.spec, op.name)
RuntimeError: [/opt/dali/dali/pipeline/pipeline.cc:261] Assert on "input_device == "cpu"" failed: cpu/mixed ops can only take cpu inputs. CPU op cannot follow GPU op. (op: 'Resize', input: '__ImageDecoder_1')
```

However, when I use fn.resize after fn.image_decoder, it not happened.

Is there a weird bug for ops.

my sample code is as following,  one pipeline use ops, another use fn:
```
...
class TrDaliPipe(Pipeline):

    def __init__(self, batch_size, num_threads, device_id, data_root, max_text_len=40):
        eii = LmdbExternalSource(batch_size=batch_size,
                                 data_root=data_root,
                                 max_text_len=max_text_len)
        self.input = ops.ExternalSource(source=eii, num_outputs=1)
        self.decoder = ops.ImageDecoder(device="mixed", output_type=types.GRAY)
        self.res = ops.Resize(resize_x=800, resize_y=48)
        self.cast = ops.Cast(dtype=types.UINT8)
        super(TrDaliPipe, self).__init__(batch_size, num_threads, device_id, seed=12 + device_id)
        logger.info("DALI dataloader inited")

    def define_graph(self):
        jpegs = self.input()
        imgs = self.decoder(jpegs)
        imgs = self.res(imgs)
        imgs = self.cast(imgs)
        return (imgs,)


class TestTrPipe(Pipeline):

    def __init__(self, batch_size, num_threads, device_id, data_root, max_text_len=40):
        self.data_root = data_root
        self.max_text_len = max_text_len
        super(TestTrPipe, self).__init__(batch_size, num_threads, device_id)
        logger.info("DALI dataloader inited")

    def define_graph(self):
        eii = LmdbExternalSource(batch_size=self.batch_size,
                                 data_root=self.data_root,
                                 max_text_len=self.max_text_len)
        jpegs = fn.external_source(source=eii, num_outputs=1)
        imgs = fn.image_decoder(jpegs, device="mixed", output_type=types.GRAY)
        imgs = fn.resize(imgs, resize_x=800, resize_y=48)
        imgs = fn.cast(imgs, dtype=types.UINT8)
        return (imgs,)


if __name__ == '__main__':
    lmdb_dir = "/data/xxx/lmdb_dataset/xxx"
    # # use fn,  success
    # train_pipe = TestTrPipe(batch_size=64, num_threads=16, device_id=0, data_root=lmdb_dir)

    ## use ops, failed
    # train_pipe = TrDaliPipe(batch_size=64, num_threads=16, device_id=0, data_root=lmdb_dir)

    train_pipe.build()
    logger.info("pipe line build finished")
    pipe_out = train_pipe.run()
    batch_cpu = pipe_out[0]
    img = batch_cpu.as_cpu().at(0)
    print(img.shape)
```

**Comment by JanuszL** [comment]
Hi,

Functional API automatically selects the backend of the operator based on the input. In you code you need to:
```
        self.res = ops.Resize(device="gpu", resize_x=800, resize_y=48)
        self.cast = ops.Cast(device="gpu", dtype=types.UINT8)
```
And I would recommend using functional API as it is easier and more compact. In 1.0 we moved all the examples to this API and we won't advertise the `ops` any longer, although it is still supported to not made users rework their scripts.

**Comment by tarunn2799** [comment]
Hey @JanuszL  do you have a timeline on when 1.0 is releasing? Excited to see all the new features that are coming to DALI!

**Comment by JanuszL** [comment]
@tarunn2799 - we will do our best to keep the Monthly release cadence, and you can expect the release by the end of the month.

**Comment by zhou3968322** [comment]
> Hi,
> 
> Functional API automatically selects the backend of the operator based on the input. In you code you need to:
> 
> ```
>         self.res = ops.Resize(device="gpu", resize_x=800, resize_y=48)
>         self.cast = ops.Cast(device="gpu", dtype=types.UINT8)
> ```
> 
> And I would recommend using functional API as it is easier and more compact. In 1.0 we moved all the examples to this API and we won't advertise the `ops` any longer, although it is still supported to not made users rework their scripts.

i tried it but failed, raised following Exception:
```bash
RuntimeError: Critical error when building pipeline:
Error when constructing operator: ImageDecoder encountered:
[/opt/dali/dali/pipeline/operator/operator_factory.h:54] Assert on "creator_it != registry_.end()" failed: Operator "ImageDecoder" not registered for gpu.
```

in [supported operations](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html?highlight=normalize#operators-documentation) , ImageDecoder not support gpu backend in dali 0.31?

**Comment by JanuszL** [comment]
`self.decoder = ops.ImageDecoder(device="mixed", output_type=types.GRAY)` if fine. There is not GPU only image decoder.

**Comment by zhou3968322** [comment]
> `self.decoder = ops.ImageDecoder(device="mixed", output_type=types.GRAY)` if fine. There is not GPU only image decoder.

i have used mixed mode.

```
class TrDaliPipe(Pipeline):

    def __init__(self, batch_size, num_threads, device_id, data_root, max_text_len=40):
        eii = LmdbExternalSource(batch_size=batch_size,
                                 data_root=data_root,
                                 max_text_len=max_text_len)
        self.input = ops.ExternalSource(source=eii, num_outputs=1)
        self.decoder = ops.ImageDecoder(device="mixed", output_type=types.GRAY)
        self.res = ops.Resize(resize_x=800, resize_y=48)
        self.cast = ops.Cast(dtype=types.UINT8)
        super(TrDaliPipe, self).__init__(batch_size, num_threads, device_id, seed=12 + device_id)
        logger.info("DALI dataloader inited")

    def define_graph(self):
        jpegs = self.input()
        imgs = self.decoder(jpegs)
        imgs = self.res(imgs)
        imgs = self.cast(imgs)
        return (imgs,)
```

**Comment by JanuszL** [comment]
The error you see is:
`Operator "ImageDecoder" not registered for gpu.`
which states that DALI thinks you try using ImageDecoder for "gpu" backend.

Can you try?
```
class TrDaliPipe(Pipeline):

    def __init__(self, batch_size, num_threads, device_id, data_root, max_text_len=40):
        eii = LmdbExternalSource(batch_size=batch_size,
                                 data_root=data_root,
                                 max_text_len=max_text_len)
        self.input = ops.ExternalSource(source=eii, num_outputs=1)
        self.decoder = ops.ImageDecoder(device="mixed", output_type=types.GRAY)
        self.res = ops.Resize(device="gpu", resize_x=800, resize_y=48)
        self.cast = ops.Cast(device="gpu", dtype=types.UINT8)
        super(TrDaliPipe, self).__init__(batch_size, num_threads, device_id, seed=12 + device_id)
        logger.info("DALI dataloader inited")

    def define_graph(self):
        jpegs = self.input()
        imgs = self.decoder(jpegs)
        imgs = self.res(imgs)
        imgs = self.cast(imgs)
        return (imgs,)
```

**Comment by zhou3968322** [comment]
> The error you see is:
> `Operator "ImageDecoder" not registered for gpu.`
> which states that DALI thinks you try using ImageDecoder for "gpu" backend.
> 
> Can you try?
> 
> ```
> class TrDaliPipe(Pipeline):
> 
>     def __init__(self, batch_size, num_threads, device_id, data_root, max_text_len=40):
>         eii = LmdbExternalSource(batch_size=batch_size,
>                                  data_root=data_root,
>                                  max_text_len=max_text_len)
>         self.input = ops.ExternalSource(source=eii, num_outputs=1)
>         self.decoder = ops.ImageDecoder(device="mixed", output_type=types.GRAY)
>         self.res = ops.Resize(device="gpu", resize_x=800, resize_y=48)
>         self.cast = ops.Cast(device="gpu", dtype=types.UINT8)
>         super(TrDaliPipe, self).__init__(batch_size, num_threads, device_id, seed=12 + device_id)
>         logger.info("DALI dataloader inited")
> 
>     def define_graph(self):
>         jpegs = self.input()
>         imgs = self.decoder(jpegs)
>         imgs = self.res(imgs)
>         imgs = self.cast(imgs)
>         return (imgs,)
> ```

thanks, it solved with this.

ops must set device, but fn not need.
