### ISSUE TITLE
Make the Pipeline CPU only

### ISSUE THREAD

**Issue by tarunn2799** [NVIDIA/DALI#2799]
I'm currently using DALI for inference on a CPU machine, and I want to make my pipeline work on a CPU only. I've made all the operators use CPU in their arguments, but I'm not sure what I should pass to the device_id argument within Pipeline arguments to make it CPU only. 
I get an error that says. "device_id should be >=0 or equal to CPU_ONLY_DEVICE_ID. What integer value do I pass to the device_id argument to make the pipeline CPU only?

Also, would love for some pointers or examples for when people have used DALI in inference. :)

**Comment by JanuszL** [comment]
Hi @tarunn2799,

Please use None as the `device_id`:
```
device_id (int, optional, default = -1) – Id of GPU used by the pipeline. A None value for this parameter means that DALI should not use GPU nor CUDA runtime. This limits the pipeline to only CPU operators but allows it to run on any CPU capable machine.
```
