### ISSUE TITLE
Dtype of label tensor is float32 when i use TFRecordReader with TensorFlow 

### ISSUE THREAD

**Issue by chmod644** [NVIDIA/DALI#28]
GPU: GeForce GTX 1060
Dataset: flower photo dataset
tensorflow-gpu==1.8.0
nvidia-dali==0.1.1

When i use nvidia-dali with TensorFlow, dtype of label tensor is float32.
I believe that should be integer. Is this correct?

Sample code is here: https://gist.github.com/chmod644/8decaf796243afab90b23246213c21c5

**Comment by cliffwoolley** [comment]
@Kh4L - does your pending polymorphism change address this?

**Comment by Kh4L** [comment]
@cliffwoolley That's right
@chmod644 This pending PR add the option to choose your outputs types on TF side
https://github.com/NVIDIA/DALI/pull/33

**Comment by cliffwoolley** [comment]
@chmod644 - https://github.com/NVIDIA/DALI/pull/33 is now merged.  Can you take a look and make sure that addresses your concern?
