### ISSUE TITLE
Iterator doesn't give data out after the first epoch when using GenericIterator and ExternalSource. 

### ISSUE THREAD

**Issue by tarunn2799** [NVIDIA/DALI#2802]
Hey, 
I'm facing an issue with my pipeline that currently takes values from the ExternalSource operator. My issue is very similar to that seen in issue #1134 [here](https://github.com/NVIDIA/DALI/issues/1134). I see that the error has been fixed in #1136 where if the data is exhausted, it is fixed. 
I have a DALIGenericIterator that encloses the pipeline, with auto_reset set to True and a last_batch_policy. I have tried adding a StopIteration call within iter_setup as mentioned in those issues. Apologies that some parts look like pseudo code, I've tried to condense the main parts.

```
class MultiTaskPipeline(Pipeline):
    def __init__(self, file_list, std_train_config, batch_size, num_threads, device_id, external_data):
        super(MultiTaskPipeline, self).__init__(batch_size, num_threads, device_id)
        self.input = ops.FileReader(file_list= file_list, random_shuffle = False)
        self.crops = ops.ExternalSource()
        self.identifier = ops.ExternalSource()
        
        self.decode = ops.ImageDecoder(device="mixed", output_type=types.RGB)
        self.res = ops.Resize(resize_x= self.image_size , resize_y=self.image_size, interp_type=types.INTERP_TRIANGULAR, device="gpu")
        self.external_data = external_data
        self.iterator = iter(external_data)
####### other init functions of DALI operators

    def define_graph(self):
        jpegs, labels = self.input(name='reader')
        self.crop_dims = self.crops()
        self.identifier_batch = self.identifier()

        anchor =  fn.reshape(fn.slice(self.crop_dims, 0, 2, axes=[1]), shape=[-1])
        shape = fn.reshape(fn.slice(self.crop_dims, 2, 2, axes = [1]), shape= [-1])
        anchor = self.cast(anchor)
        shape = self.cast(shape)

        jpegs = ops.ImageDecoder(device = 'mixed', output_type = types.RGB)(jpegs)
        jpegs = self.res(jpegs)
        #other transformations applied

        jpegs = self.swapaxes(jpegs)
        labels = labels.gpu()
        labels = self.to_int64(labels)
     
        return (jpegs, labels, self.crop_dims, self.identifier_batch)

    def iter_setup(self):
        try:
            crops, identifier = list(next(self.iterator))[0]
            self.feed_input(self.crop_dims, crops)
            self.feed_input(self.identifier_batch, identifier)

        except StopIteration: #It does not even get to this block of the code even when theres no data
            self.iterator = iter(self.external_data)
            crops, identifer = next(self.iterator)
            self.feed_input(self.crop_dims, crops)
            self.feed_input(self.identifier_batch, identifier)
            raise StopIteration 



train_multi_iter = SampleIteratorClass(data, train_batch_size, std_train_config) #just my generatort
val_multi_iter = SampleIteratorClass(val)

train_pipe = MultiTaskPipeline(train_file_list, int(train_batch_size), 4, gpu_id, external_data=train_multi_iter) #the dali pipeline
val_pipe =MultiTaskPipeline(val_file_list, int(train_batch_size), 4, gpu_id, external_data=val_multi_iter)

train_loader = CustomGenericIterator(std_train_config, trainset.dataset_len, pipelines=multi_pipe,
                                       output_map=["images", "labels", "crops", "identifier"], reader_name="reader", auto_reset = True, last_batch_policy = LastBatchPolicy.PARTIAL, dynamic_shape = True)

val_loader = CustomGenericIterator(std_train_config, valset.dataset_len , pipelines=multi_pipe,
                                       output_map=["images", "labels", "crops", "identifier"], reader_name="reader", auto_reset = True, last_batch_policy = LastBatchPolicy.PARTIAL, dynamic_shape = True)
``` 

It just seems to suspend after the first epoch. Kindly help me out here. Thanks in advance!

**Comment by JanuszL** [comment]
Hi,
Could you provide a self-contained repro that would illustrate this problem? Maybe the problem itself is inside the `train_multi_iter` or `val_multi_iter`, or how they interact with DALI. Even a toy example should do.

BTW - I don't know if it is relevant but you have a typo `identifer` -> `identifier`,  so you may not get what you really want.
In the meantime you can run and check if the following snippet works for you:
```
from nvidia.dali.pipeline import Pipeline
import nvidia.dali.types as types
import nvidia.dali.fn as fn
import nvidia.dali.ops as ops
import numpy as np
import random
from nvidia.dali.plugin.pytorch import DALIGenericIterator as PyTorchIterator

max_batch_size = 4
iter_limit = 4
runs = 3
test_data_shape = [2, 3, 4]
i = 0
dataset = [[[np.random.randint(0, 255, size=test_data_shape, dtype=np.uint8)
              for _ in range(max_batch_size)]] for _ in range(iter_limit)]

def get_data():
    global i
    if i == iter_limit:
        i = 0
        raise StopIteration
    out = dataset[i]
    i += 1
    return out

pipe = Pipeline(batch_size=max_batch_size, num_threads=1, device_id=0)
with pipe:
    outs = fn.external_source(source=get_data, num_outputs=1)
pipe.set_outputs(*outs)

it = PyTorchIterator([pipe], auto_reset=True, output_map=["data"])
counter = 0
for r in range(runs):
    for j, data in enumerate(it):
        assert (data[0]["data"].numpy() == np.concatenate(dataset[j])).all()
        counter += 1
        print(r, j)
assert counter == iter_limit * runs
```

**Comment by tarunn2799** [comment]
Hey Janusz, here's the generator I'm using. This is designed for multi-task models so we pass a different dataset to the model at each batch. 1st iteration contains dataset 1  batch1, 2nd iteration gives dataset 2 batch 1, and so on..  

```
class MultiTaskDataGen(object):

    def __init__(self, datasets, batch_size, std_train_config):
        len_df = [len(df) for df in datasets]
        self.datasets = datasets
        self.largest_dataset = max(len_df)
        self.largest_dataset_idx = len_df.index(self.largest_dataset)
        self.counter_index = {i: 0 for i, dataset in enumerate(datasets)}
        self.counter_dataset = 0
        self.iterable_datasets = itertools.cycle(datasets)
        self.data_dict = std_train_config["data_dict"]
        self.inp_dict = std_train_config["data_dict"]["data"] #ignore these, these are just rows in a CSV file 
        self.out_dict = {"labels": std_train_config['data_dict']['labels']}
        self.std_train_config = std_train_config
        self.batch_size = batch_size

    def customroundrobin(self, iterable, index): #function gives data in a round robin structure
        start_over = 0
        if index >= len(iterable):
            start_over += 1
        while True:
            for i, element in enumerate(iterable):
                if i >= index or start_over:
                    if i == len(iterable) - 1:
                        start_over += 1
                    yield element
    def __iter__(self):
        return self

    def __next__(self):
        batch_identifier = []
        batch_crops = []
        if self.counter_index[self.largest_dataset_idx] < self.largest_dataset:
                batch_counter = 0
                cur_iterable = self.customroundrobin(self.iterable_datasets.__next__(), self.counter_index[self.counter_dataset])
                while batch_counter < self.batch_size:
                    self.counter_index[self.counter_dataset] += 1 #shifts between different datasets
                    data_point = cur_iterable.__next__() #gives next row of csv, runs for "batch_size" no. of times
                    crops = data_point["labels_crops"]
                    crops = ast.literal_eval(crops)
                    crops = [crops[0], crops[1], crops[2] - crops[0], crops[3] - crops[1]]
                    batch_crops.append(np.array([crops], dtype = np.int32))  #these are the bounding box coords for cropping
                    batch_identifier.append(np.array(self.std_train_config["identifiers"].index(data_point["identifier"]))) #identifier is simply an integer for identify the different datasets.
                    batch_counter += 1
                self.counter_dataset += 1
                if self.counter_dataset == len(self.datasets):
                    self.counter_dataset = 0
                yield (batch_crops, batch_identifier)
    
    @property
    def size(self):
        return self.largest_dataset

    # So ideally this gives out a batch_size number of corresponding values for each dataset in my training set. Multiple datasets due to multi-task model.
```

That typo isnt an issue, haha. That was just a mistake I made while I was writing pseudo code within the github issue. 

So I pass this to my pipeline object under the external_data argument, and the iterator seems to give me datapoints in the correct order, I verified it separately.  That pipeline object goes to my CustomGenericIterator, where i'm facing this issue. 


Meanwhile, I did try out your example and I got an output that looked like this: 

```
0 0
0 1
0 2
0 3
1 0
1 1
1 2
1 3
2 0
2 1
2 2
2 3 
```

**Comment by JanuszL** [comment]
I think I have more understanding of what you are doing in your pipeline.
`MultiTaskDataGen` is just an auxiliary data source, but the flow is controlled by the FileReader. `MultiTaskDataGen` never raises StopIteration, and you don't need to handle that case in `iter_setup`. (BTW - I think you can replace ```yield (batch_crops, batch_identifier)``` by just ```return```).
I did another toy example that checks if the FileReader can work with ExternalSource:
```
from nvidia.dali.pipeline import Pipeline
import nvidia.dali.types as types
import nvidia.dali.fn as fn
import nvidia.dali.ops as ops
import numpy as np
import random
from nvidia.dali.plugin.pytorch import DALIGenericIterator as PyTorchIterator

max_batch_size = 1
iter_limit = 4
runs = 3
test_data_shape = [2, 3, 4]
dataset = [[[np.random.randint(0, 255, size=test_data_shape, dtype=np.uint8)
              for _ in range(max_batch_size)]] for _ in range(iter_limit)]

def get_data():
    return dataset[0]

pipe = Pipeline(batch_size=max_batch_size, num_threads=1, device_id=0)
with pipe:
    images, _ = fn.readers.file(files=["test/1/1.jpeg", "test/1/1_a.jpeg", "test/1/1_b.jpeg"], name="Reader")
    outs = fn.external_source(source=get_data, num_outputs=1)
pipe.set_outputs(*outs, images)

it = PyTorchIterator([pipe], auto_reset=True, output_map=["data", "lab"], reader_name="Reader", dynamic_shape=True)
for r in range(runs):
    for j, data in enumerate(it):
        print(r, j)
```
And it stills runs 3 times per epoch (as there are 3 samples in the reader), ExternalSource is infinite as in your case.
Can you try to minimize your sample code, check if removing ExternalSource changes the behavior?
If you can narrow down it to a self-contained toy example we can run on our side it would help a lot.

**Comment by tarunn2799** [comment]
Hey @JanuszL , sorry for the delay. I've prepared a self-contained repository that you can run with our pipeline, iterator, and the data here: 
https://github.com/tarunn2799/toy_dali 

So I have a custom Generator that passes data to my ExternalSource operator. My custom GenericIterator takes values from the pipeline and gives it to me. 

Problems I'm facing : 
1. Observe the output printed when I initialise the GenericIterator. For some reason it already calls iter_setup thrice and updates my counter_index within my generator. 
2. When I do a next(iterator) on my custom generic iterator, It starts from the beginning, but my counter_index is not reset and its mismatched. 
3. I'm not exactly sure where I should call for a StopIteration here. I'm currently using the size argument within the GenericIterator to raise stopiteration, but observe that when I simply print the next(iterator), it stops midway and does not cover the entire dataset. 
4. With respect to the previous issue I had where the iterator was getting exhausted, I realized there was an error in the Generator. I removed stopiteration everywhere to make sure the feed was infinite and it worked.

**Comment by JanuszL** [comment]
Hi @tarunn2799,

> Observe the output printed when I initialise the GenericIterator. For some reason it already calls iter_setup thrice and updates my counter_index within my generator.

It happens due to prefetching that is executed in the Iterator. When it is constructed it schedules run, and obtains the output so when Iterator is asked for data for the first time is has it right away. In 1.0 (and the most recent nightly build) there is a `prepare_first_batch` option you can set to `False` to prevent this.

> When I do a next(iterator) on my custom generic iterator, It starts from the beginning, but my counter_index variable is not reset and its mismatched.

Iterator reset doesn't reset the state of the ExternalSource operator. `GenericIterator` is mostly a python wrapper on top of pipeline object with very little control over what is happening under the hood, so that is why `counter_index` is not reset. Its main purpose is to count the samples returned by having a notion of epoch and fill the native framework tensors with DALI data.

> Edit : This issue was fully resolved when I used ExternalSource for all the input operations, and decoding the image inside. What is the performance difference one sees between ExternalSource and using a FileReader? I remember reading that the ExternalSource performance is going to boosted with the new 1.0 release.

In 1.0 you can distribute the work to multiple CPUs and the performance scales with the number of CPUs assigned. The major limitation you would face is the fact you need to provide the iterator to the `ExternalSource` that would return only one sample at the time so work can be independly distributed to multiple CPUs.

> I'm not exactly sure where I should call for a StopIteration here. I'm currently using the size argument within the GenericIterator to raise stopiteration, but observe that when I simply print the next(iterator), it stops midway and does not cover the entire dataset.

In such a use case, there is no need to raise StopIteration. I think `MultiClassIterator` could reset by itself internally. How about the below code? Does it achieve what you need?
I added an internal reset() method that is called when the data set has been exhausted (assuming that the dataset passed to ExternalSource is in sync with the file list passed to the FileReader).
I also added `pad_last_batch` to the FileReader to make sure that when it wraps up the dataset (when it reaches the end it starts from the beginning), it will duplicate the last sample up to the full batch to not wrap inside the given batch so ExternalSource and FileReader stay in sync. `LastBatchPolicy.PARTIAL` makes sure that the redundant samples in the batch are cut out.

I have also reworked your code to the fn API that is much cleaner and easy to understand. I hope you don't mind.
```
#!/usr/bin/env python
# coding: utf-8

# In[1]:


import nvidia.dali.ops as ops
import nvidia.dali.types as types
from nvidia.dali.pipeline import Pipeline
from nvidia.dali.plugin.pytorch import DALIGenericIterator, DALIClassificationIterator
from nvidia.dali.plugin.pytorch import LastBatchPolicy
import os
import random
import torch
import numpy as np
import pandas as pd
import glob
from PIL import Image
import itertools
import nvidia.dali.fn as fn
import cupy
import ast


# # External Source Example
#

class MultiClassIterator(object):
    def __init__(self, datasets, batch_size):
        len_df = [len(df) for df in datasets]
        self.largest_dataset = max(len_df) #length of csv file with the most number of datapoints
        self.largest_dataset_idx = len_df.index(self.largest_dataset) #identifier for which one the largest is
        self.reset()
        self.batch_size = batch_size
        self.datasets = datasets
        self.iter_size = sum(len_df)

    def customroundrobin(self, iterable, index):
        '''
        Performs a round robin over the smaller dataset. In the case where one CSV is smaller than the other, the
        smaller one is iterated through again till we reach the length of the largest CSV dataset.
        '''
        start_over = 0
        if index >= len(iterable):
            start_over += 1
        while True:
            for i, element in enumerate(iterable):
                if i >= index or start_over:
                    if i == len(iterable) - 1:
                        start_over += 1
                    yield element

    def __iter__(self):
        return self

    def reset(self):
        self.counter_index = {i: 0 for i, dataset in enumerate(datasets)} #a counter to see how many datapoints have been taken from each dataset
        self.counter_dataset = 0 #identifier for which dataset we're currently on
        self.iterable_datasets = itertools.cycle(datasets)

    def __next__(self):
        batch_crops = []
        batch_labels = [np.array(i) for i in range(4)] #Ignore this, just a dummy label being generated.
        print('Counter Index Updated', self.counter_index)

        #takes a row from our CSV file dataset, and appends the result values to a list. Value is yielded.
        batch_counter = 0
        cur_iterable = self.customroundrobin(self.iterable_datasets.__next__(), self.counter_index[self.counter_dataset])
        while batch_counter < self.batch_size:
            self.counter_index[self.counter_dataset] += 1
            data_point = cur_iterable.__next__()
            crops = data_point["labels_crops"]
            crops = ast.literal_eval(crops)
            crops = [crops[0], crops[1], crops[2] - crops[0], crops[3] - crops[1]] #Format to support ops.slice
            batch_crops.append(np.array([crops], dtype=np.int32))
            batch_counter += 1
        self.counter_dataset += 1
        if self.counter_dataset == len(datasets):
            self.counter_dataset = 0
        if sum(self.counter_index.values()) >= self.size:
            self.reset()
        print(batch_crops, batch_labels)
        return (batch_crops, batch_labels)


    @property
    def size(self):
        return self.largest_dataset


class GenericIterator(DALIGenericIterator):
    def __init__(self, **args):
        super().__init__(**args)
        pass

    def custom_collate(self, loader_dict):
        #using this function for adding custom collate functionalit
        pass

    def __next__(self):
        #Removed a few nuances, but we do require a custom DALIGenericIterator (for custom functions)
        loader_dict = {}
        out = super().__next__()
        out = out[0]
        loader_dict["input"] = out[self.output_map[0]].float()
        loader_dict["labels"] = torch.squeeze(out[self.output_map[1]])

        return loader_dict

datasets = [pd.read_csv(df, index_col= 'Unnamed: 0').to_dict(orient='records') for df in glob.glob('*.csv')]


multi_iter = MultiClassIterator(datasets, 4)


pipe = Pipeline(batch_size=4, num_threads=2, device_id=0)
with pipe:
    jpegs, _ = fn.readers.file(file_list= 'single_image.txt', pad_last_batch=True)
    crop, labels = fn.external_source(multi_iter, num_outputs=2)
    images = fn.decoders.image(jpegs, device="mixed", output_type=types.RGB)
    anchor =  fn.reshape(fn.slice(crop, 0, 2, axes=[1]), shape=[-1])
    shape = fn.reshape(fn.slice(crop, 2, 2, axes = [1]), shape= [-1])
    anchor = fn.cast(anchor, dtype=types.INT32)
    shape = fn.cast(shape, dtype=types.INT32)
    images = fn.resize(images, resize_x=224, resize_y=224)
    pipe.set_outputs(images, labels, crop)

pii = GenericIterator(pipelines = pipe, output_map=['data', 'label', 'crops'], auto_reset = True, size = multi_iter.size, last_batch_policy=LastBatchPolicy.PARTIAL)

for i, x in enumerate(pii):
    print(x['labels'], i)
for i, x in enumerate(pii):
    print(x['labels'], i)
```

**Comment by tarunn2799** [comment]
Hey @JanuszL , thanks for the reponse. Those are some really good points, let me take some time to try out your suggestions. Meanwhile, I faced a really weird issue. I have an image file that I want to Decode within DALI. And I got the nVJPEG error code 8, which according to another issue here means that its a corrupted JPEG file. 

My system does prevent this normally, by checking if images are corrupted before they enter the DALI pipeline, but I took the file out separately, and tried running PIL as well as cv2 and the images show up perfectly, whereas DALI throws the nvJPEG error. Do you have any idea why this is happening?

**Comment by JanuszL** [comment]
Hi @tarunn2799 ,

> And I got the nVJPEG error code 8, which according to another issue here means that its a corrupted JPEG file.

Can you provide a full error log reported by DALI? It would help us narrow down the problem.
In the meantime can you check if the DALI cpu decoder can handle that image?
Can you share the image itself? Maybe there is an issue inside nvJPEG (we are using under the hood).

**Comment by tarunn2799** [comment]
Hey @JanuszL, 
Here's the error log. 
![image](https://user-images.githubusercontent.com/28048963/111871017-05d39800-89ae-11eb-96ad-6592e65971ab.png)

Yes, the image decodes on cpu, how is this happening?

I've uploaded the image to the same repository with the toy example https://github.com/tarunn2799/toy_dali . Its under the name 'fcdd6003-801b-53c2-9bbb-c7fd44855186.jpg'. The image does look unusual, but right now my point of concern is how even this was corrupted it goes through PIL,  CV2, and DALI CPU but not on the mixed operator, and how I can prevent this from happening. 

Thank you for all the help Janusz.

**Comment by JanuszL** [comment]
Hi @tarunn2799,

The image is clearly corrupted:
![image](https://user-images.githubusercontent.com/39967756/111964211-a9c75b80-8af4-11eb-9c33-23c6d4e80919.png)

CPU decoder just warns with `Corrupt JPEG data: premature end of data segment` while the `mixed` ends with a hard error. In that case, I don't know what is the best course of action - feed the network with the garbage and let the training continue, or just fail, ask the user to remove the corrupted image and then continue.
I think in this case fix or remove the image from the data set as it just confuses the network during the training.

**Comment by tarunn2799** [comment]
Hey Janusz, thanks for the response. I understand that training with such images will confuse the network during training, but this is a negligibly small fraction of images within our datasets. 

So we have a mechanism within our system that either lets these images into training directly, or we validate every single image to see if its corrupted individually. The latter is a painfully slow process in comparison, whereas the former sends the image through as long as PIL.Image.open() works. Its somewhat of a tradeoff we choose to make and we have observed that a few corrupted images doesn't break our performance, so we just let them through.

Is there a way for me to be able to use the mixed operator, and continue to throw warnings similar to the cpu version. Is there a specific reason why it throws a hard error but the cpu decoder lets us off with a warning?

**Comment by marisancans** [comment]
Hello, im having a really similar experience to this, first epoch is working for me but after many hours I cannot figure out why Pipeline doesnt reset the iterator and give next batch.

Heres the code:
```
from nvidia.dali.pipeline import Pipeline
import nvidia.dali.ops as ops
import nvidia.dali.types as types
import nvidia.dali.fn as fn


#Using ExternalSource
class SimplePipeline(Pipeline):
    #Define the operations in the pipeline
    def __init__(self, external_datasource, sequence_length_max, num_threads=1, device_id=0, resolution=256, crop=224, is_train=True):
        super(SimplePipeline, self).__init__(sequence_length_max, num_threads, device_id, seed=0)

        self.jpegs = ops.ExternalSource()
        self.external_datasource = iter(external_datasource)

    def define_graph(self):
        self.jpegs = self.jpegs()
        images = fn.decoders.image(self.jpegs, device="mixed", output_type=types.RGB)
        return images


    def iter_setup(self):
        images = next(self.external_datasource)
        self.feed_input(self.jpegs, images)
```


```
class RandomSamplerWrapper(object):
    def __init__(self, dataset):
        self.dataset = dataset

    def __iter__(self):
        self.sampler = iter(RandomSampler(self.dataset))
        return self

    def __next__(self):
        idx = next(self.sampler)
        print(idx)
        return self.dataset[idx]
```


```
  ds = pytorch generic dataset-sublass of Dataset
  it = RandomSamplerWrapper(ds)

  pipe = load_pipeline(dataloader_args, it)
  pipe.build()



  pipe_iter = DALIGenericIterator(pipe, ['images'], dynamic_shape=True, auto_reset=True, prepare_first_batch=False)
  # dl = ExternalInputIterator(ds, pipe_iter, training_args.batch_size)


  counter = 0
  runs = 10

  for r in range(runs):
      for j, data in enumerate(pipe_iter):
          counter += 1
          print(r, j)
      x=0
  x=0
```


I am passing auto_reset=True to pipeline but I think is has no effect since im using external source, I cant figure out how to reset the iterator passed to pipe after each epoch

**Comment by JanuszL** [comment]
Hi @marisancans,

I would recommend checking [this example ](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/external_input.html) to see how to simplify usage of the external source. Please check `cycle` parameters.
If this doesn't apply to your case/you don't want to change your code please add a reset to the `def iter_setup(self)` method, maybe something like:
```
def __next__(self):
        try:
            idx = next(self.sampler)
        except StopIteration:
            self.sampler.reset()
            raise
        print(idx)
        return self.dataset[idx]
```

**Comment by marisancans** [comment]
@JanuszL That did the trick! Thanks a lot! Couldnt figure out how to properly propegate and throw the exception.

**Comment by JanuszL** [comment]
Hi @tarunn2799,

I forgot to mention that a CPU fallback will be added in 1.1.0 to address https://github.com/NVIDIA/DALI/issues/2802#issuecomment-803319734.
You could check the nightly build in the meantime.

**Comment by tarunn2799** [comment]
That's amazing! This is going to save a lot of time for us because we had to add a separate image validator module that consumed a lot of time. 
Thanks @JanuszL 


I had a doubt with the FileReader class, is there a way to look the order in which FileReader reads the images from my directory structure?

**Comment by JanuszL** [comment]
Hi @tarunn2799,

You can check [this file](https://github.com/NVIDIA/DALI/blob/master/dali/operators/reader/loader/filesystem.cc) to see how the `file` reader orders the files. In general, if you disable shuffling, you should get folders and files inside them in the lexicographical order. If you enable shuffling, it should be random.
If you want to have a custom order, please `files` argument of the reader and pass a list of filenames in any order you like, and the reader will just follow it (when `random_shuffle=False`).

**Comment by JanuszL** [comment]
BTW - 1.1.0 has been released. You can update and check if that works as you expect.
