### ISSUE TITLE
Seed for coco_reader

### ISSUE THREAD

**Issue by MendelXu** [NVIDIA/DALI#2807]
Thanks for your great job. When I try to use the `coco_reader` in my code, I find a `seed` option for it. However, I find that the reader actually uses a constant value `kDaliDataloaderSeed` to generate a shuffled file list, so what is the `seed` for?

**Comment by JanuszL** [comment]
Hi,

`kDaliDataloaderSeed` is used to preschuffled data set once and for all at the very beginning. The `seed` itself is used to the batch to batch shuffling.
For example, when you data set is:
- file_a class_1
- - file_a class_1

**Comment by MendelXu** [comment]
Got it. Thank you very much
