### ISSUE TITLE
The GPUs are unbalanced

### ISSUE THREAD

**Issue by zimbobwe** [NVIDIA/DALI#2808]
Hi,
When I use DALI with DDP, the GPUs are so unbalanced that I can only use a very small batch size. Is there any solution?
![image](https://user-images.githubusercontent.com/22854241/111806917-6eb70380-890d-11eb-9bc7-705dd70c66f6.png)

**Comment by JanuszL** [comment]
Hi @zimbobwe,

It looks that GPU 0 does definitely more work than other GPUs. Are you sure you using DALI correctly?
Have you checked our examples, like [ResNet50 in PyTorch](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/use_cases/pytorch/resnet50/pytorch-resnet50.html).

**Comment by zimbobwe** [comment]
> Hi @zimbobwe,
> 
> It looks that GPU 0 does definitely more work than other GPUs. Are you sure you using DALI correctly?
> Have you checked our examples, like [ResNet50 in PyTorch](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/use_cases/pytorch/resnet50/pytorch-resnet50.html).

Thank you for your reply.
I check the examples carefully, finally, I found this is because I was given the wrong parameters to  device_id and shard_id when initializing the pipeline. 
Thanks again!
