### ISSUE TITLE
The time of one iteration

### ISSUE THREAD

**Issue by MendelXu** [NVIDIA/DALI#2813]
I implement a dali iterator and try to measure the time it consumes. With following code
```python
import time

total_time = []
t1 = time.time()
for sample in iterator:
  t2=time.time()-t1
  print(t2)
  total_time.append(t2)
  t1 = time.time()
print(sum(total_time)/len(total_time))
```
the result is about 0.005s for each iteration.
However, when I run it together with a model with 
```python
import time

total_time = []
t1 = time.time()
for sample in iterator:
  t2=time.time()-t1
  print(t2)
  total_time.append(t2)
  loss = model(sample)
  loss.backward()
  optimizer.step()
  optimizer.zero_grad()
  t1 = time.time()
print(sum(total_time)/len(total_time))
```
The result is about 0.1s/iteration event with `torch.cuda.synchroize()` before `t1=time.time()`. So which time is the true time? Or why the result is so different? Is it possible to make the gpu ultilization keep 100%?

Other information:
- The  io ultilization is not 100% in both situation.
- In situation 1, the gpu memory usage is about 900MB and ultilization is 40%. In situation 2, the gpu memory usage is about 6000MB and ultilization is 87%.

**Comment by JanuszL** [comment]
Hi,
I think it would be best to capture [nsight system profile](https://developer.nvidia.com/nsight-systems) to see how your GPU execution timeline looks like.
If you want to do such profiling I would also recommend to:
- set GPU frequency to fixed value using `nvidia-smi` and `-lgc` option
- [set CPU frequency](https://community.mellanox.com/s/article/how-to-set-cpu-scaling-governor-to-max-performance--scaling-governor-x) to the fixed, most performant value 

In some cases, CPU can lower its frequency due to low utilization making some operation last longer.

**Comment by MendelXu** [comment]
Thanks~I'll try it!

**Comment by MendelXu** [comment]
Sorry to bother you again~How can I know the bottleneck from the report? 
![image](https://user-images.githubusercontent.com/44802022/112312982-59155580-8ce2-11eb-8f01-37434b36cf86.png)
I have referred to https://github.com/NVIDIA/DALI/issues/2790#issuecomment-799537148 but don't find any useful information in my report.

**Comment by JanuszL** [comment]
I would check how GPU utilization looks like. If it is low or there are gaps I would check if the model is waiting for the data.
If you can share the report we can take a look.
You can also use [DLProf](https://docs.nvidia.com/deeplearning/frameworks/dlprof-user-guide/) - a convenient tool to profile your deep learning flow.

**Comment by MendelXu** [comment]
Thank you very much. I have uploaded it here [Google Drive](https://drive.google.com/file/d/1lRrLbOaboGAYhojaiqEnG7_teMhLVfSR/view?usp=sharing).

**Comment by JanuszL** [comment]
Hi,
What I see in the profiles is a GPU gap connected with ExternalSource execution:
![image](https://user-images.githubusercontent.com/39967756/112327715-f73ef680-8cb5-11eb-84dc-8af9048afeb1.png)
In 1.0 that would be available soon ([you can check nightly/weekly build preview](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/installation.html#nightly-and-weekly-release-channels)) [external source](https://docs.nvidia.com/deeplearning/dali/master-user-guide/docs/supported_ops.html#nvidia.dali.fn.external_source) can be run in parallel to the main process and you can also prefetch samples ahead of time - see `parallel` and `prefetch_queue_depth` options.
Another one relates to memory allocations made by DALI (they make the GPU synchronize its execution)
![image](https://user-images.githubusercontent.com/39967756/112327866-1473c500-8cb6-11eb-89b9-70db485a81a9.png)
but when DALI allocates enough memory there are no gaps anymore:
![image](https://user-images.githubusercontent.com/39967756/112328108-4d139e80-8cb6-11eb-9991-f6cdd210096d.png)
You can read [how to allocate memory ahead of time by providing hints](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/advanced_topics.html#operator-buffer-presizing).
The last one is not connected with DALI:
![image](https://user-images.githubusercontent.com/39967756/112327934-22c1e100-8cb6-11eb-9c2d-ed8e46edfb4a.png)

**Comment by MendelXu** [comment]
OK. Thanks for your help! I will try your solutions.
