### ISSUE TITLE
bug: program get stuck when use ops.videoreader read a mp4 file

### ISSUE THREAD

**Issue by pokerc** [NVIDIA/DALI#2818]
Hi there, here my program (dali videoreader) always get stuck when processing the mp4 files down below, is there any solutions for this.

heres the mp4 file urls:
https://drive.google.com/file/d/1qCTHlgXtb22tZtfr06KNW8jAUyLBwc1q/view?usp=sharing
https://drive.google.com/file/d/1BdppV7x9hih7WQJyLw1cKGC_xdFklhVT/view?usp=sharing
https://drive.google.com/file/d/1ExxpvKzwqpheSqZz4QrxerThi1KA5KJx/view?usp=sharing
https://drive.google.com/file/d/1_kBufPCndOW9iQ4MgPK-cItAy9AnFEYt/view?usp=sharing
https://drive.google.com/file/d/1_kBufPCndOW9iQ4MgPK-cItAy9AnFEYt/view?usp=sharing

here's my code:
```python
import os
import cv2
import math
from nvidia.dali.pipeline import Pipeline
import nvidia.dali.ops as ops


class VideoPipe(Pipeline):
    def __init__(self, batch_size, num_threads, device_id, filenames, shuffle, sequence_length, step, stride):
        super(VideoPipe, self).__init__(batch_size, num_threads, device_id, seed=16)
        self.input = ops.VideoReader(device="gpu", filenames=filenames, sequence_length=sequence_length,
                                     shard_id=0, num_shards=1,
                                     random_shuffle=shuffle, skip_vfr_check=True, read_ahead=True, step=step,
                                     stride=stride)

    def define_graph(self):
        output = self.input(name="Reader") 
        return output


video_filename = "test.mp4"
cap = cv2.VideoCapture(video_filename)
video_total_count = cap.get(cv2.CAP_PROP_FRAME_COUNT)
video_fps = int(cap.get(cv2.CAP_PROP_FPS))
cap.release()

# extract a frame per 2 seconds
sequence_length = 2 * video_fps
max_round_count = min(math.floor(video_total_count / sequence_length), 30)
dali_pipe = VideoPipe(batch_size=1, num_threads=4, device_id=0, filenames=video_filename,
                      shuffle=False, sequence_length=1, stride=1, step=sequence_length)
dali_pipe.build()
for i in range(max_round_count):
    dali_out_gpu, = dali_pipe.run()
    dali_out_cpu = dali_out_gpu.as_cpu().as_array()
    print(dali_out_cpu.shape)


```

**Comment by JanuszL** [comment]
Hi,

It seems to be a bug in the way DALI does decoding and seeking (but it is unclear how to fix that now). We are started thinking about how to rework VideoReader internals. We will get back to this issue sometime later this year.
From the logs I see that frames are not ordered by the time in the video stream - maybe this is one of the reasons. Can you check if reencoding help?

**Comment by JanuszL** [comment]
Hi,
We have merged a possible fix in https://github.com/NVIDIA/DALI/pull/2916. Can you check tomorrow nightly build to see if that helps?

**Comment by JanuszL** [comment]
Hi,
DALI 1.2 has been released and should fix the issue.
