### ISSUE TITLE
How to skip bounding boxes with iscrowd=1 annotations in readers.coco?

### ISSUE THREAD

**Issue by lettuan** [NVIDIA/DALI#2821]
I noticed that currently for polygon_masks the objects with iscrowd=1 annotations are skipped. Can I skip the bounding boxes with iscrowd=1 annotations in readers.coco?

**Comment by jantonguirao** [comment]
Hi @lettuan,

For polygon masks, we are skipping those masks that were represented as an RLE mask originally (that is, those with iscrowd=1). We are still parsing the sample though, so you'd get the image and bounding box, but not the mask.

If you wanted to drop iscrowd=1 samples completely, there's no built-in way to do that, but there's a way you can achieve it. You can use the `images` argument of the COCO reader, to specify the list of image files that you want to read. You'd have to parse your JSON file first, and build a list of image files of those samples that you want to load (those with iscrowd=0 in your case).

I hope that helps.

**Comment by JanuszL** [comment]
Hi @lettuan,

If you think that a dedicated option to skip such a sample entirely would be useful for the general audience you can fill a PR with it:
- first, add a dedicated option in [this file](https://github.com/NVIDIA/DALI/blob/master/dali/operators/reader/coco_reader_op.cc)
- adjust the logic in [coco_loader](https://github.com/NVIDIA/DALI/blob/master/dali/operators/reader/loader/coco_loader.cc) - `ParseAnnotations` and probably `ParseJsonAnnotations`

**Comment by JanuszL** [comment]
@lettuan - it was added by https://github.com/NVIDIA/DALI/pull/4792. Please check the latest nightly/weekly build. It will be a part of the 1.26 release.

**Comment by JanuszL** [comment]
It was enabled in DALI 1.26.
