### ISSUE TITLE
undefined reference to `ff_sine_64` when building from source

### ISSUE THREAD

**Issue by twmht** [NVIDIA/DALI#2825]
Can't build from source (master branch)

```
[ 99%] Building CXX object dali/operators/CMakeFiles/dali_operator_test.dir/__/test/dali_test_config.cc.o
[ 99%] Building CXX object dali/operators/CMakeFiles/dali_operator_test.dir/__/test/dali_operator_test_utils.cc.o
[ 99%] Linking CXX executable ../python/nvidia/dali/test/dali_operator_test.bin
/home/shared/nfs/acer-share/ffmpeg-4.2.2_build/lib/libavcodec.so: undefined reference to `ff_sine_64'
/home/shared/nfs/acer-share/ffmpeg-4.2.2_build/lib/libavcodec.so: undefined reference to `ff_mdct_end'
/home/shared/nfs/acer-share/ffmpeg-4.2.2_build/lib/libavcodec.so: undefined reference to `ff_fft_init'
/home/shared/nfs/acer-share/ffmpeg-4.2.2_build/lib/libavcodec.so: undefined reference to `ff_mdct_init'
/home/shared/nfs/acer-share/ffmpeg-4.2.2_build/lib/libavcodec.so: undefined reference to `ff_init_ff_sine_windows'
/home/shared/nfs/acer-share/ffmpeg-4.2.2_build/lib/libavcodec.so: undefined reference to `ff_sine_128'
/home/shared/nfs/acer-share/ffmpeg-4.2.2_build/lib/libavcodec.so: undefined reference to `ff_fft_end'
```

i have pointed to ffmpeg-4.2.2.

any idea?

**Comment by JanuszL** [comment]
Hi,
DALI uses FFmpeg 4.3.1 and we just moved to 4.3.2.
You can see how FFmpeg is built [here](https://github.com/NVIDIA/DALI_deps/blob/main/build_scripts/build_ffmpeg.sh).
The easiest way to build DALI is to use dockerized environment by following [this guide](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/compilation.html#using-docker-builder-recommended).

**Comment by twmht** [comment]
@JanuszL 

ok. I just followed the document (https://docs.nvidia.com/deeplearning/dali/user-guide/docs/compilation.html#) which says  

```
We recommend using version 4.2.2 compiled following the instructions below.
```

**Comment by JanuszL** [comment]
> it seems that the document need to be updated.

We will update it, still I'm not sure what could be the source of the problem. It seems to be a compilation problem with FFmpeg 4.2.2 and its configuration we use (compilation says that there is a missing symbol inside FFmpeg itself, which is not part of DALI).

**Comment by JanuszL** [comment]
HI,
We have provided the exact info which dependency version DALI expects in this separate repository - https://github.com/NVIDIA/DALI_deps.
