### ISSUE TITLE
How to decode 16bit png images?

### ISSUE THREAD

**Issue by delkov** [NVIDIA/DALI#2827]
I'm trying to load 16bit image:
```

def ExternalSourcePipeline(batch_size, num_threads, device_id, external_data):
    pipe = Pipeline(batch_size, num_threads, device_id)
    with pipe:
        jpegs = fn.external_source(source=external_data, num_outputs=1)
        images = fn.decoders.image(jpegs, device="cpu", output_type=types.GRAY)
        output = fn.cast(images, dtype=types.UINT16)
        pipe.set_outputs(output)
    return pipe
```
Error in thread 0: [/opt/dali/dali/operators/decoder/host/host_decoder.cc:32] Assert on "IsType<uint8>(input.type())" failed: Input must be stored as uint8 data.

How to work with 16bit img?

**Comment by delkov** [comment]
Error in thread 0: [/opt/dali/dali/operators/decoder/host/host_decoder.cc:32] Assert on "IsType<uint8>(input.type())" failed: Input must be stored as uint8 data.

**Comment by JanuszL** [comment]
Hi,
DALI doesn't support 16b images.
Can you tell us what input format you have and what is the use case?
What you can do is to encode the lower 8b as one channel and the higher 8b as another one. Then you can use ['slice'](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.slice), ['cat`](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.cat)/['stack'](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.stack) and [`reinterpret` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.reinterpret) to get only two relevant channels/join them and reinterpret to UINT16 data type tensor.

**Comment by delkov** [comment]
Thank you!
I just have high resolution 10bit image, which encoded like 16-bit img.

**Comment by JanuszL** [comment]
> Thank you!
> I just have high resolution 10bit image, which encoded like 16-bit img.

What format is that? TIFF?

**Comment by JanuszL** [comment]
> No, just 16-bit png (grayscale)
> Is there any way to save precision of 16bit? Say save img like float?

Sorry, we don't support any flavor of 16bit images. As I suggested, try to split 16bit values into two 8bit ones. I don't think there is any other way around with DALI now.

**Comment by delkov** [comment]
Ok!
But what about augmentation, does DALI work well on 16bit?
So you suggest save it like 2 8bit images, then by using decoderes.image() get it and then slice it?
Thank you/

**Comment by JanuszL** [comment]
Hi @delkov:

> But what about augmentation, does DALI work well on 16bit?

Most of the operators should work, but we don't have a complete list anywhere, sorry.

> So you suggest save it like 2 8bit images, then by using decoderes.image() get it and then fn.cat() it?

You can try that. Please remember that when you use lossy compression, then compressing each half of 16b value and combining them later would yield different results than compressing 16b value. If you are using lossless compression then you won't be impacted.
Another available solution is to use [the 'external_source` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.external_source) and do the decoding using python available libraries. Please check `parallel` and `prefetch_queue_depth` options to improve the performance.

**Comment by JanuszL** [comment]
Hi @delkov,

Please check [this example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/external_input.html). It shows how to connect your python code with the rest of the pipeline.

**Comment by javierztl** [comment]
@JanuszL  Hi, I am doing monocular depth estimation, the ground truth is labled by 16-bit. FYI if you have planning to add this feature.

**Comment by mzient** [comment]
The upcoming DALI release will have a new operator `fn.experimental.decoders.image` (and all other flavors, with fused slice/crop/...) and will support other bit depths. You will be able to get images in any format by specifying `dtype` - you can even load images as `float` and get the intensities in normalized 0..1 range. Until it's released, you should be able to get one of our nightly builds to get it early.

**Comment by JanuszL** [comment]
You can read their documentation [here](https://docs.nvidia.com/deeplearning/dali/main-user-guide/docs/operations/nvidia.dali.fn.experimental.decoders.image.html#nvidia.dali.fn.experimental.decoders.image.

**Comment by javierztl** [comment]
@mzient @JanuszL  Thank you for your reply, I tried the `experimental.decoders.image` and set the dtype to `DALIDataType.UINT16`, it said 
`category_torch_type[category] = to_torch_type[category_tensors[category].dtype]
KeyError: <DALIDataType.UINT16: 1>`
I tried INT16, it works well, please kindly have a look the UINT16. 
My DALI version is `nvidia-dali-weekly-cuda110      1.21.0.dev20221127`

**Comment by JanuszL** [comment]
Hi @javierztl,

While DALI may output UINT16, as far as I see PyTorch doesn't support this type - https://pytorch.org/docs/stable/tensors.html, which is why it is not present in [this mapping](https://github.com/NVIDIA/DALI/blob/main/dali/python/nvidia/dali/plugin/pytorch.py#L26).
Something like this fails as well:
```
torch.from_numpy(np.array([1], dtype=np.uint16))
TypeError: can't convert np.ndarray of type numpy.uint16. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.

```

**Comment by javierztl** [comment]
@JanuszL  thank you for your support
I did some conversation and it works.
