### ISSUE TITLE
Decode .flo files

### ISSUE THREAD

**Issue by gemenerik** [NVIDIA/DALI#2829]
I'm working on an optical flow data pipeline (image0, image1, flow_gt)
Trying to load .flo files. If you are unfamiliar, you can consider them 32 bit, 2 channel images.
```python
@pipeline_def
def simple_pipeline():
    jpegs0, _ = fn.readers.file(file_root=args.data, files=image_0_train_list, seed=1)
    images0 = fn.decoders.image(jpegs0, device='cpu')
    jpegs1, _ = fn.readers.file(file_root=args.data, files=image_1_train_list, seed=1)
    images1 = fn.decoders.image(jpegs1, device='cpu')
    flow, _ = fn.readers.file(file_root=args.data, files=flo_test_list, seed=1)
    # insert flow decoder

    return images0, images1, flow
```

When I run the pipeline without decoding the flow, it returns an array of a length 4 times what it should be. It seems it expects 8 bits, where 32 bits are used in gt.

What is the best approach? Can I implement a custom decoder with e.g. numpy? Can I trick e.g. two grayscale decoders to read the two 32 bit channels and stack them afterwards?

<details>
  <summary>Example .flo reader from NVIDIA/flownet2-pytorch</summary>
 
```python
def readFlow(fn):
    """ Read .flo file in Middlebury format"""
    # Code adapted from:
    # http://stackoverflow.com/questions/28013200/reading-middlebury-flow-files-with-python-bytes-array-numpy

    # WARNING: this will work on little-endian architectures (eg Intel x86) only!
    # print 'fn = %s'%(fn)
    with open(fn, 'rb') as f:
        magic = np.fromfile(f, np.float32, count=1)
        if 202021.25 != magic:
            print('Magic number incorrect. Invalid .flo file')
            return None
        else:
            w = np.fromfile(f, np.int32, count=1)
            h = np.fromfile(f, np.int32, count=1)
            # print 'Reading %d x %d flo file\n' % (w, h)
            data = np.fromfile(f, np.float32, count=2*int(w)*int(h))
            # Reshape data into 3D array (columns, rows, bands)
            # The reshape here is for visualization, the original code is (w,h,2)
            return np.resize(data, (int(h), int(w), 2))
```
  
</details>

**Comment by JanuszL** [comment]
Hi @gemenerik,

> When I run the pipeline without decoding the flow, it returns an array of a length 4 times what it should be. It seems it expects 8 bits, where 32 bits are used in gt.

Indeed, `fn.readers.file` returns int8 output, still you can use ['reinterpret' operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.reinterpret) to change the underlying data type. However, you won't be able to extract magic, w, and h fields. It would be best if you can just save flo files as plain numpy arrays with shapes embedded in numpy metadata.
Another solution is to use [the `external_source` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.external_source); please also check `prefetch_queue_depth' and `parallel` options to increase its performance.

**Comment by gemenerik** [comment]
Thanks very much. I converted all `.flo` to `.npy` files, imported them with `fn.readers.numpy`, and I can successfully train the network now. 

I noticed the crop_mirror_normalize function does not support my npy input, but other than that, all transformations I tried work.

```
[/opt/dali/dali/operators/image/crop/crop_mirror_normalize.h:173] Assert on "ImageLayoutInfo::IsImage(input_layout_)" failed: Unsupported layout: '' for input 0 '__Numpy_6'
```

My training speed has improved 10-fold. Congrats on the brilliant and intuitive library.

**Comment by JanuszL** [comment]
Hi @gemenerik,

I'm glad it works for you.

Regarding:
> I noticed the crop_mirror_normalize function does not support my npy input, but other than that, all transformations I tried work.

Numpy reader doesn't output any layout, and the `crop` operator needs one to properly interpret the data. To add one you can use ['reshape' operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.reshape), and do something like:
```
flo = fn.reshape(flo , layout="hwc")
# do your crop now
```
