### ISSUE TITLE
RuntimeError encountered

### ISSUE THREAD

**Issue by KleinXin** [NVIDIA/DALI#2836]
I am trying to read data in tfrecord format. However, RuntimeError encountered. 

PyTorch Version：1.6.0 with cuda 10.1
DALI Version：0.30.0 with cuda 10.0

Codes were tested with another dataset two months ago. When I used a new dataset, problem happens.

Any one knows the possible cause of the error below？

Traceback (most recent call last):
  File "main_tfrecord.py", line 568, in <module>
    main()
  File "main_tfrecord.py", line 182, in main
    train( model, criterion, optimizer, epoch,save_path)
  File "main_tfrecord.py", line 252, in train
    **for (i, in_var) in enumerate(train_loader):**
  File "/usr/local/lib/python3.6/dist-packages/nvidia/dali/plugin/pytorch.py", line 181, in __next__
    outputs = self._get_outputs()
  File "/usr/local/lib/python3.6/dist-packages/nvidia/dali/plugin/base_iterator.py", line 246, in _get_outputs
    outputs.append(p.share_outputs())
  File "/usr/local/lib/python3.6/dist-packages/nvidia/dali/pipeline.py", line 682, in share_outputs
    return self._pipe.ShareOutputs()
RuntimeError: Critical error in pipeline:
Error when executing Mixed operator ImageDecoder encountered:
CUDA allocation failed
Current pipeline object is no longer valid.

**Comment by JanuszL** [comment]
Hi,
Can you try to reduce batch size and number of DALI threads (to 3 or 4) and see if that helps? `Error when executing Mixed operator ImageDecoder encountered: CUDA allocation failed` usually means you just run out of GPU memory.

**Comment by KleinXin** [comment]
> Hi,
> Can you try to reduce batch size and number of DALI threads (to 3 or 4) and see if that helps? `Error when executing Mixed operator ImageDecoder encountered: CUDA allocation failed` usually means you just run out of GPU memory.

I set initial_fill to 10240 as you suggested in [issue 2688](https://github.com/NVIDIA/DALI/issues/2688)
so that random shuffle can work properly.

Is that the cause of this error?

![image](https://user-images.githubusercontent.com/13084622/113300469-868c7f80-9330-11eb-8c51-35fefb740153.png)

**Comment by JanuszL** [comment]
`initial_fill` affects the CPU memory consumption, and should not result in the error you see.

**Comment by KleinXin** [comment]
> `initial_fill` affects the CPU memory consumption, and should not result in the error you see.

After reducing the batch size from 128 to 96,  it works fine. thx!
