### ISSUE TITLE
Problems replicating fn.readers.video tutorial

### ISSUE THREAD

**Issue by ilianherzi** [NVIDIA/DALI#2838]
Following the tutorial as closely as possible,  I cloned v0.18.0 of DALI_extra and linked my path to the sintel videos.  The following code is a copy of what I put into a single script. Note I have CUDA Version 11.0 and downloaded nvidia-dali from the build for CUDA 11 (pip install --extra-index-url https://developer.download.nvidia.com/compute/redist nvidia-dali-cuda110)

```python
import os
import numpy as np

from nvidia.dali import pipeline_def
import nvidia.dali.fn as fn
import nvidia.dali.types as types


batch_size=2
sequence_length=8
initial_prefetch_size=11
video_directory = os.path.join('/path/to/DALI_extra/', "db", "video", "sintel", "labelled_videos")
shuffle=True
n_iter=6

@pipeline_def
def video_pipe(file_root):
    video, labels = fn.readers.video(device="gpu", file_root=file_root, sequence_length=sequence_length,
                                     random_shuffle=True, initial_fill=initial_prefetch_size)
    return video, labels

pipe = video_pipe(batch_size=batch_size, num_threads=2, device_id=0, file_root=video_directory, seed=12345)
pipe.build()
for i in range(n_iter):
    sequences_out, labels = pipe.run()
    sequences_out = sequences_out.as_cpu().as_array()
    labels = labels.as_cpu().as_array()
    print(sequences_out.shape)
    print(labels.shape)

```
Running the following code results in a hang however and I am unable to debug what precisely is going on.  Not sure if this is an issue or a misconfiguration on my part but any help would be greatly appreciated. Thanks

**Comment by JanuszL** [comment]
Hi @ilianherzi,

Does it hang at the very beginning or after a couple of iterations?
DALI doesn't support variable frame rate videos yet and this may end up as DALI waiting for a frame with a given timestamp that is just not there.

**Comment by ilianherzi** [comment]
Hi @JanuszL 

Thanks for the fast reply. I copied from this [tutorial](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/sequence_processing/video/video_reader_label_example.html) using the exact same sintel videos, which I believe have no variable frame rate. Could this be something else?

**Comment by JanuszL** [comment]
Hi,
I'm able to run this snippet without any problems.
You can try changing:
```
batch_size=1
sequence_length=1
initial_prefetch_size=1
```
and see if there is any difference?

Can you also provide the exact DALI version you have `pip show nvidia-dali-cuda110`, driver version, and GPU model?
Can you try to run your code in https://colab.research.google.com/ (it has free GPU available)?

**Comment by ilianherzi** [comment]
here's the output of pip show ```nvidia-dali-cuda110```

```bash
Name: nvidia-dali-cuda110
Version: 1.0.0
Summary: NVIDIA DALI  for CUDA 11.0. Git SHA: e825c53bbfde66cdc6df7f8050ab40f3e53be775
Home-page: https://github.com/NVIDIA/dali
Author: NVIDIA Corporation
Author-email: None
License: Apache License 2.0
Location: /home/ilian/miniconda3/envs/aai/lib/python3.8/site-packages
Requires: 
Required-by: 
```
 I just ran the tutorial with the changes you mentioned above on google [colab](https://colab.research.google.com/drive/1cwxHbJ2JgErotVz0ljmDEh58LZc85bWL?usp=sharing) and am getting the same errors I'm finding on my machine. 

Thanks!

**Comment by JanuszL** [comment]
I just run this snippet in colab with the GPU runtime:
```
!apt-get install git-lfs
!git lfs install
!pip install --extra-index-url https://developer.download.nvidia.com/compute/redist nvidia-dali-cuda110
!pip install numpy
!git clone https://github.com/NVIDIA/DALI_extra.git
import os
import numpy as np

from nvidia.dali import pipeline_def
import nvidia.dali.fn as fn
import nvidia.dali.types as types


batch_size=2
sequence_length=8
initial_prefetch_size=11
video_directory = os.path.join('DALI_extra/', "db", "video", "sintel", "labelled_videos")
shuffle=True
n_iter=6

@pipeline_def
def video_pipe(file_root):
    video, labels = fn.readers.video(device="gpu", file_root=file_root, sequence_length=sequence_length,
                                     random_shuffle=True, initial_fill=initial_prefetch_size)
    return video, labels

pipe = video_pipe(batch_size=batch_size, num_threads=2, device_id=0, file_root=video_directory, seed=12345)
pipe.build()
for i in range(n_iter):
    sequences_out, labels = pipe.run()
    sequences_out = sequences_out.as_cpu().as_array()
    labels = labels.as_cpu().as_array()
    print(sequences_out.shape)
    print(labels.shape)
```
And obtained:
```
(2, 8, 720, 1280, 3)
(2, 1)
(2, 8, 720, 1280, 3)
(2, 1)
(2, 8, 720, 1280, 3)
(2, 1)
(2, 8, 720, 1280, 3)
(2, 1)
(2, 8, 720, 1280, 3)
(2, 1)
(2, 8, 720, 1280, 3)
(2, 1)
```

**Comment by JanuszL** [comment]
I just checked the output from your run:
```
Assert on "ret >= 0" failed: Could not open file ./DALI_extra/db/video/sintel/labelled_videos/0/sintel_trailer-720p_0.mp4 because of Invalid data found when processing input
```
It is because you don't have git-lfs installed, and files tracked by it are just sha. 
Please check https://github.com/NVIDIA/DALI_extra#usage.
