### ISSUE TITLE
Is there mirror padding while cropping?

### ISSUE THREAD

**Issue by delkov** [NVIDIA/DALI#2840]
Assume, I have 400x600 img, & I want to crop 500x500, so I want to mirror some part of orig. img.
I know how to do it with filling zeros, 
`            images = fn.crop(images, device="gpu", crop=(758, 1014), out_of_bounds_policy='pad')`

How can I make mirror-like padding? 
* I want to make random-cropping also, like RandomCrop in albumentations.
Thank you!

**Comment by JanuszL** [comment]
Hi @delkov,

DALI doesn't support a mirror padding policy. What you can try to do is craft the required part of the image using a slice operator and then add these two images together.
