### ISSUE TITLE
Illegal memory access error during JP2 images decoding

### ISSUE THREAD

**Issue by JonghyunBae** [NVIDIA/DALI#2842]
When I try to decode JP2 formatted images, the program is terminated.
When decoding with 'cpu', it works without problems, but when decoding with 'mixed',
the following error is displayed:

Traceback (most recent call last):
&nbsp;&nbsp;File "decoding_dali.py", line 37, in <module>
&nbsp;&nbsp;&nbsp;&nbsp;pipe_out = pipe.run()
&nbsp;&nbsp;File "/home/ubuntu/anaconda3/envs/jp2/lib/python3.7/site-packages/nvidia/dali/pipeline.py", line 916, in run
&nbsp;&nbsp;&nbsp;&nbsp;return self.outputs()
&nbsp;&nbsp;File "/home/ubuntu/anaconda3/envs/jp2/lib/python3.7/site-packages/nvidia/dali/pipeline.py", line 815, in outputs
&nbsp;&nbsp;&nbsp;&nbsp;return self._outputs()
&nbsp;&nbsp;File "/home/ubuntu/anaconda3/envs/jp2/lib/python3.7/site-packages/nvidia/dali/pipeline.py", line 899, in _outputs
&nbsp;&nbsp;&nbsp;&nbsp;return self._pipe.Outputs()
RuntimeError: Critical error in pipeline:
Error when executing Mixed operator decoders__Image encountered:
Error in thread 0: CUDA runtime API error cudaErrorIllegalAddress (700):
an illegal memory access was encountered
Current pipeline object is no longer valid.
terminate called after throwing an instance of 'dali::CUDAError'
&nbsp;&nbsp;what():  CUDA runtime API error cudaErrorIllegalAddress (700):
an illegal memory access was encountered
Aborted (core dumped)

I tried both DALI built from source code and installed with pip, but both shows the same error.
I already checked that "BUILD_NVJPEG2K" option is turned on when I compiled the DALI source code.

My server system informations are as follows:
- Linux Ubuntu 18.04 (AWS p3 instance)
- python version: 3.7.10
- NVIDIA Tesla V100 SXM2 16GB
- NVIDIA driver Version: 460.32.03
- CUDA Version: 11.2
- DALI version: 1.0.0
- NVJPEG2k version: 0.2.0 (latest version in NVIDIA homepage)

My image folders are constructed as follows:
(The images are fixed resolution as 720x480 with RGB format.
The JP2 images are converted using python PIL package: 
```Image.open("XXXX.jpg").convert('RGB').save("XXXX.jp2")```
)
[image_samples.zip](https://github.com/NVIDIA/DALI/files/6262512/image_samples.zip)
**train_jp2_VGA**
|
-- 0
|    |-000000.jp2
|    |-000001.jp2
   ...
|    |-000999.jp2
-- 1
|    |-001000.jp2
.
..

My DALI decoding source code as follows:
```
try:
    from nvidia.dali import pipeline_def
    import nvidia.dali.types as types
    import nvidia.dali.fn as fn
except ImportError:
    raise ImportError("Please install DALI from https://www.github.com/NVIDIA/DALI to run this example.")


@pipeline_def
def create_dali_pipeline():

    images, labels = fn.readers.file(file_root="/home/ubuntu/kitti/images/train_jp2_VGA",
                                     shard_id=0, num_shards=1, random_shuffle=True, pad_last_batch=True)

    decoder_device = 'mixed'
    device_memory_padding = 211025920
    host_memory_padding = 140544512

    images = fn.decoders.image(images,
                               device=decoder_device, output_type=types.RGB,
                               device_memory_padding_jpeg2k=device_memory_padding,
                               host_memory_padding_jpeg2k=host_memory_padding)

    labels = labels.gpu()
    return images, labels


pipe = create_dali_pipeline(batch_size=64, num_threads=8, device_id=0)
pipe.build()
pipe_out = pipe.run()
```

Thank you.

**Comment by JanuszL** [comment]
Hi,
I just tested DALI 1.0 and the following code works:
```
import nvidia.dali.pipeline as pipeline
import nvidia.dali.types as types
import nvidia.dali.fn as fn
import numpy as np
import random
from PIL import Image

Image.open("dali/test/1/test.jpeg").convert('RGB').save("dali/test/1/test.jp2")

batch_size = 1
pipe = pipeline.Pipeline(batch_size=batch_size, num_threads=4, device_id=0)
with pipe:
  images, labels = fn.readers.file(files=["dali/test/1/test.jp2"],
                                   shard_id=0,
                                   num_shards=1,
                                   random_shuffle=False,
                                   name="Reader")
  images = fn.decoders.image(images, device="mixed", output_type=types.RGB)
  pipe.set_outputs(images)

pipe.build()
for _ in range (10):
  out = pipe.run()
```
Can you provide a fault image, maybe I missed something?

**Comment by JonghyunBae** [comment]
Sure, here is my sample images (2 images in zip file).
I just guess that my JP2 file format has something wrong.
[image_samples.zip](https://github.com/NVIDIA/DALI/files/6264341/image_samples.zip)

**Comment by JanuszL** [comment]
Hi,

I have managed to reproduce the problem. DALI disregards the number of channels from the image and assumes that it is always 3. We will check how we can fix that.
Thank you for reporting this.

**Comment by JanuszL** [comment]
Hi,
DALI 1.2 has been released and should fix the issue.
