### ISSUE TITLE
How to use logic expression with img shape

### ISSUE THREAD

**Issue by delkov** [NVIDIA/DALI#2845]
I want to get img. size and slice it depends on it, e.g:
```
            images = fn.decoders.image(jpegs, device="mixed", output_type=types.GRAY)
            shapes = fn.peek_image_shape(jpegs)
            info = fn.reductions.max(shapes) # MAX W/H
            if info>1024:
                   images = fn.slice(images, start=(0,0), end=(200,200),  axes=[0,1])
            else:            
                   images = fn.slice(images, start=(0,0), end=(100,100),  axes=[0,1])

                  


```
How this 'if' can be implemented? 
How can I extract value from DataNode via cast or somehow..? Or I should use types.Constant()?

**Comment by JanuszL** [comment]
Hi,
How about something like:
```
    images = fn.decoders.image(jpegs, device="mixed", output_type=types.GRAY)
    shapes = fn.peek_image_shape(jpegs)
    info = fn.reductions.max(shapes) # MAX W/H
    condition = (info > 1024) * 100 + 100
    end = fn.stack(condition, condition)
    images = fn.slice(images, start=(0,0), end=end,  axes=[0,1])
```
?

**Comment by delkov** [comment]
> Hi,
> How about something like:
> 
> ```
>     images = fn.decoders.image(jpegs, device="mixed", output_type=types.GRAY)
>     shapes = fn.peek_image_shape(jpegs)
>     info = fn.reductions.max(shapes) # MAX W/H
>     condition = (info > 1024) * 100 + 100
>     end = fn.stack(condition, condition)
>     images = fn.slice(images, start=(0,0), end=end,  axes=[0,1])
> ```
> 
> ?

Hi! Thank you for reply.
Actually, start is not necessary (0,0) but random.. via Uniform().
My final goal is to make mirror-like padding, so first I got img size and if it is too small -> make fn.slice and fn.cat to get mirror-like padding;
Looks like I need to make more actions than just slice..
