### ISSUE TITLE
Use pipeline like feed for Pytorch

### ISSUE THREAD

**Issue by delkov** [NVIDIA/DALI#2848]
I know how to dela with DALI & Pytorch by using DALIGenericIterator;
But! All tensors should be the same size, how can I avoid it?
I want to manually reshape all tensors which got from DALI and then feed it to Pytorch

```
pipe.build()
pipe_out = pipe.run()
images = pipe_out[0]
for i in range(len(images)):
   temp_img = images.at(i).squeeze()
   ## some manipulation


```

**Comment by JanuszL** [comment]
Hi @delkov,

DALIGenericIterator doesn't support non-dense tensors.
In your case, you can use [`feed_ndarray`](https://github.com/NVIDIA/DALI/blob/master/dali/python/nvidia/dali/plugin/pytorch.py#L38) to transfer data from DALI tensor to Torch one. You will lose all notion of the epoch that DALIGenericIterator has, but is should do what you need.

**Comment by delkov** [comment]
Great!
I have small question about pipeline, with DALIGenericIterator I can iterate like:
```
for i, data in enumerate(pii):
    img = data[0]['images']
```
Whats the right way to iterate pipeline?
```
pipe.build()

pipe_out = pipe.run() # got first batch
images = pipe_out[0]
torch_arr = torch.zeros(1, 1536, 2048)

for i in range(len(images)):
    feed_ndarray(images[i], torch_arr)
    # do some manipulation and stack batch with correct shapes
```
To get one more batch I make pipe.run() again, but how can I make loop to iter till the end?
Something like while pipe.run():

For another epoch should I build pipe again?
Thank you so much!

**Comment by JanuszL** [comment]
@delkov,

DALI pipeline is an infinite data source. So unless you use `external_source` you can call `run` as many times as you like.
In your case, you need to determine on your own how many times you need to run the pipeline (based on the data set size, number of shards, and batch size). You can check [base_iterator.py](https://github.com/NVIDIA/DALI/blob/master/dali/python/nvidia/dali/plugin/base_iterator.py) for a reference but I don't expect you to implement all edge cases `DALIGenericIterator` supports.

**Comment by delkov** [comment]
Thank you!
I use like this:
```
class ExternalInputIterator(object):
    def __init__(self, batch_size, device_id, num_gpus):
        self.images_dir = 'TEST_DALI.txt'
        self.batch_size = batch_size
        self.files=get_new_split(self.images_dir)
        self.data_set_len = len(self.files)
        shuffle(self.files)
        self.n = len(self.files)
    def __iter__(self):
        self.i = 0
        return self
    def __next__(self):
        batch = []
        labels = []
        if self.i >= self.n:
            self.__iter__()
            raise StopIteration
        for _ in range(self.batch_size):
            batch.append(np.fromfile(self.files[self.i], dtype = np.uint8)) 
            self.i += 1
        return (batch, None)
    def __len__(self):
        return self.data_set_len
    next = __next__

eii = ExternalInputIterator(batch_size, 0, 1)
dataset_len = eii.__len__()
print('DATASET LEN: ', dataset_len)
pipe = ExternalSourcePipeline(batch_size=batch_size, num_threads=workers, device_id=0, external_data = eii)
pipe.build()
pipe_out = pipe.run()

```
How should I modify it?

**Comment by JanuszL** [comment]
In this case, something like this should work:
```
while True:
    try:
        pipe_out = pipe.run()
        # do things
    except StopIteration:
        break
```
`ExternalInputIterator` should rise `StopIteration` and `run` should throw it when appropriate.

**Comment by JanuszL** [comment]
Just:
```
pipe.reset()
```
and then just call:
```
while True:
    try:
        pipe_out = pipe.run()
        # do things
    except StopIteration:
        break
```
for the next epoch.

**Comment by delkov** [comment]
Thank you so much! I have a last question, how can I set default aspect_ratio, like this:
        shapes = fn.peek_image_shape(jpegs) # HWC
        h = fn.slice(shapes, 0, 1, axes = [0])
        w = fn.slice(shapes, 1, 1, axes = [0])
        ratio = w/h
        images = fn.random_resized_crop(images, device='gpu', size=(480, 640), random_area=[0.1,0.2], random_aspect_ratio=[ratoio, ratio])

**Comment by JanuszL** [comment]
@delkov,

I'm sorry, but `random_resized_crop` supports only a fixed `random_aspect_ratio` range. It cannot be a runtime value.
