### ISSUE TITLE
Question about the randomness when doing the sharding

### ISSUE THREAD

**Issue by tztztztztz** [NVIDIA/DALI#2849]
When using the fileReader with sharding, each gpu on each process only takes part of data.
It makes sense only when the shuffling in each process is exactly same (with same seed). 
However, I notice that you usually use a different seed for pipes (12 + device_id).
That makes me confused. Can you help me? Thanks!

**Comment by tztztztztz** [comment]
I know DALI does deterministic shuffling after I refer to #1774

However, I have one further question: how this works when my programs involve resuming?

For example, there are total N epochs to run. After I finished the training of the first epoch and save the checkpoint, my program crashed due to some reason. So I need to resume my program with the first checkpoint file then start training from the second epoch. The problem is: when I restart my program, the DALI instance needs to be re-initialized with *current_epoch = 0*. This makes each GPU actually use the same split of data between the first epoch and the second epoch because the global shuffling keeps the same and the shard id does not rotate.

Is there a solution that I can set the current epoch when initializing the file reader so it knows how to do global shuffling and rotate the shard id?

**Comment by JanuszL** [comment]
Hi,

Honestly, we haven't test DALI in the scenario you describes. What DALI does when moving from one epoch to another is that each GPU moves to the next shard (unless you set `stick_to_shard=True`). So in your case, you can do something like:
```
fn.readers.file(shard_id=(shard_id+epoch_id)%num_shards)
```
The shard rotation doesn't have a significant impact on the training result, in your case, it may show up that not rotating the data between GPUs doesn't have any impact.

**Comment by tztztztztz** [comment]
Thanks for your reply.

```
fn.readers.file(shard_id=(shard_id+epoch_id)%num_shards)
```
with those codes that you suggested, we can only rotate the shard id. However, since the shuffling of file_list and sharding is deterministic, the overall data from all devices are still kept unchanged.

For example:
the file_list is [0, 1, 2, 3, 4, 5, 6, 7]
num_gpu is 2
mini-batch size: 2

at epoch 1, Assume that DALI shuffled file_list to: [7, 6, 5, 4, 3, 2, 1, 0]
data partition for gpu0: [7, 6, 5, 4]
data portion for gpu1: [3, 2, 1, 0]
so the first batch data is (7,6,3,2)

in my case,
resume at epoch 2, the shuffled file_list is deterministic: [7, 6, 5, 4, 3, 2, 1, 0]
**rotate the shard id as you suggested**
data partition for gpu0: [3, 2, 1, 0] 
data portion for gpu1: [7, 6, 5, 4]
so the first batch data is **still** (7, 6, 3, 2)

----- 

So my solution is that I shuffle the file_list myself (with epoch as seed), then use the shuffled file_list to create a DALI instance.

or do I misunderstand something?

**Comment by JanuszL** [comment]
Hi @tztztztztz,

The content of the shard is preshuffled deterministically. However when you set `random_shuffle=True` then the output from the reader should be random.
DALI does shuffling by sequentially reading the data set into the internal buffer (its size can be adjusted by `initial_fill` value), then the buffer is randomly sampled to form a batch.
In the case of separate files, as you noticed, the data set is preshufled, but for TFRecord or RecordIO, it is expected that the data set is already preshuffled.
So the algorithm would work like this:
```
at epoch 1
data partition for gpu0: [3, 2, 1, 0]
data portion for gpu1: [7, 6, 5, 4]
internal buffer gpu0 [3, 2, 1]
internal buffer gpu1: [7, 6, 5]
batch gpu0: [3, 1]
batch gpu1: [6, 5]
at epoch 2
data partition for gpu0: [7, 6, 5, 4]
data portion for gpu1: [3, 2, 1, 0]
internal buffer gpu0 [7, 6, 5]
internal buffer gpu1: [3, 2, 1]
batch gpu0: [5, 7]
batch gpu1: [2, 3]
```

**Comment by tztztztztz** [comment]
Hi @JanuszL 
Seems that in my case of resuming, the key is to set `random_shuffle=True` even if I set `shuffle_after_epoch=True`

Thank you for your help, now I'm happy with a better understanding of DALI!

**Comment by JanuszL** [comment]
I'm glad that it works as you need.

**Comment by zhaoyang-0204** [comment]
Hi, 
After reading #1774 and this, I came to understand the machanism of dali a bit.  The seeds argument in the FIlereader object would have an effect on the random_shuffle, which shuffles the data after doing the determinstic pre-shuffling, and it would not have effects on the pre-shuffling behavior and shuffle_after_epoch parameter. The system actually use the kDaliDataloaderSeed as the hardcoded seed, and shuffle after_epoch would add its epoch on it after the each epoch. I wonder if I understand correctly. 
Thanks for the excellent work.

Best and regards

**Comment by JanuszL** [comment]
Hi @zhaoyang-0204,

Yes, I think you have captured the gist of how DALI shuffling works.

**Comment by zhaoyang-0204** [comment]
> Hi @zhaoyang-0204,
> 
> Yes, I think you have captured the gist of how DALI shuffling works.

Thanks for your response.
