### ISSUE TITLE
QA: The relationship of framework's version and DALI's version.

### ISSUE THREAD

**Issue by linmuchuiyang** [NVIDIA/DALI#2851]
As we know, DALI could use other DL framework (pytorch, tensorflow, mxnet and paddle)  plugins. However, what's the corresponding relationship between DALI versions and DL frameworks' versions. Where could I find the related illustration?

**Comment by JanuszL** [comment]
Hi,

DALI should work with the versions listed https://docs.nvidia.com/deeplearning/dali/user-guide/docs/installation.html#prerequisites. For PyTorch, MXNet, and Paddle Paddle the integration is based on the python API which is very stable at the FW side.
TensorFlow relies on the custom plugin that is either prebuild (provided for the most recent TF version) or built during the installation (if not available). Our experience shows that TF is more sensitive to API changes while with other FWs we haven't encountered many (if any) compatibility issues.
Have you encountered any problems with the compatibility?
