### ISSUE TITLE
Is it possible to use DALI to accelerate single image preprocess?

### ISSUE THREAD

**Issue by tangchen2** [NVIDIA/DALI#2857]
i want to use DALI in Inference, where image path is unknown. the input is one single image, I use ExternalSourcePipeline and DALIGenericIterator to get the final torch tensor, however it cost huge time to build the pipeline, Is is possible to accelerate building pipeline in this case?

**Comment by JanuszL** [comment]
Hi,
I don't think you need to build your pipeline for each inference request. Just do it once and feed with the input on demand.
You can also check [a dedicated DALI TRITON backend](https://github.com/triton-inference-server/dali_backend) that was designed for such purpose.
Also, keep in mind that GPU acceleration is proportional to the problem size. So while it won't be significant for a single image it will much better with a batch of images.

**Comment by tangchen2** [comment]
> Hi,
> I don't think you need to build your pipeline for each inference request. Just do it once and feed with the input on demand.
> You can also check [a dedicated DALI TRITON backend](https://github.com/triton-inference-server/dali_backend) that was designed for such purpose.
> Also, keep in mind that GPU acceleration is proportional to the problem size. So while it won't be significant for a single image it will much better with a batch of images.

Thanks for your reply, but the problem is i dont know the next request image path, so i cant build the pipeline in ways like "files or file_root", i can just build the pipeline based on the request single image instead of a whole test(which is unknown to me)

**Comment by tangchen2** [comment]
> Hi,
> I don't think you need to build your pipeline for each inference request. Just do it once and feed with the input on demand.
> You can also check [a dedicated DALI TRITON backend](https://github.com/triton-inference-server/dali_backend) that was designed for such purpose.
> Also, keep in mind that GPU acceleration is proportional to the problem size. So while it won't be significant for a single image it will much better with a batch of images.

Now i build the pipeline with ExternalSourcePipeline and ExternalInputIterator(this iterator only return this request single image) which is very low efficient

**Comment by tangchen2** [comment]
Here is my code

class ExternalInputIterator(object):
    def __init__(self, binary_imgs):
        self.batch_size = 1

        # with open(os.path.join(images_dir), 'r') as fd:
        #     imgs = fd.readlines()
        #
        # imgs = [os.path.join(root, img[:-1]) for img in imgs]
        self.imgs = np.array([binary_imgs])
        self.len = len(self.imgs)

    def __iter__(self):
        self.i = 0
        self.n = len(self.imgs)
        return self

    def __next__(self):
        batch = []
        # labels = []
        for _ in range(self.batch_size):
            sample = self.imgs[self.i]
            batch.append(sample)
            # labels.append(np.array([0], dtype=np.uint8))
            # with open(sample, 'rb') as f:
            #     batch.append(np.frombuffer(f.read(), dtype=np.uint8))
            #     labels.append(np.array([0], dtype=np.uint8))
            self.i = (self.i + 1) % self.n
        # return (batch, labels)
        return batch

    def __len__(self):
        return self.len

    @property
    def size(self, ):
        return self.len

    next = __next__

class ExternalSourcePipeline(Pipeline):
    def __init__(self, iterator, batch_size, num_threads, device_id, fix_size, mean, std):
        super(ExternalSourcePipeline, self).__init__(batch_size, num_threads, device_id, seed=12)
        self.iterator = iterator
        self.input = ops.ExternalSource()
        self.input_label = ops.ExternalSource()
        self.decode = ops.decoders.Image(device='mixed', output_type=types.BGR)
        self.resize = ops.Resize(device='gpu', resize_longer=fix_size)
        self.cmnp = ops.CropMirrorNormalize(device="gpu",
                                            output_layout=types.NCHW,
                                            mean=mean,
                                            std=std
                                            )

    def define_graph(self):
        self.images = self.input()
        # self.labels = self.input_label()
        images = self.decode(self.images)
        images = self.resize(images)
        # output = self.cmnp(images.gpu())
        output = self.cmnp(images)
        # return output, self.labels
        return output

    def iter_setup(self):
        # (images, labels) = self.iterator.next()
        images = self.iterator.next()
        self.feed_input(self.images, images)
        # self.feed_input(self.labels, labels)

Do you mean i use a queue in ExternalInputIterator __next__ function to produce data to ExternalSourcePipeline iter_setup() func and put new request single image data to the queue in other thread?

**Comment by JanuszL** [comment]
> Do you mean i use a queue in ExternalInputIterator next function to produce data to ExternalSourcePipeline iter_setup() func and put new request single image data to the queue in other thread?

That is one of the ideas.

**Comment by tangchen2** [comment]
> > Do you mean i use a queue in ExternalInputIterator next function to produce data to ExternalSourcePipeline iter_setup() func and put new request single image data to the queue in other thread?
> 
> That is one of the ideas.

Thank you so much , i will try it!

**Comment by JanuszL** [comment]
@tangchen2

A side note. I recommend checking the new, functional DALI API and the most recent improvement in the `exteranl_source` functionality you can find in [this](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/external_input.html) example.

**Comment by tangchen2** [comment]
Here is my code

  class IterableQueue(Queue):

    _sentinel = object()

    def __iter__(self):
        return self

    def close(self):
        self.put(self._sentinel)

    def next(self):
        item = self.get()
        if item is self._sentinel:
            raise StopIteration
        else:
            return item

  img_queue = IterableQueue()
  pipe = ExternalSourcePipeline(img_queue, batch_size=1, num_threads=1, device_id=0, fix_size=608,
                                  mean=mean, std=stddev)
  pii = DALIGenericIterator(pipe, output_map=['data'])
  for i in range(len(os.listdir(img_root))):
      path = os.listdir(img_root)[i]
      img_path = os.path.join(img_root, path)

      img = cv2.imread(img_path)
      if img is None:
          continue
      base64_img = image_to_base64(img)
      binary_img = base64_to_binary(base64_img)
      np_img = np.frombuffer(binary_img, dtype=np.uint8)

      fetch_start = time.time()
      img_queue.put(np_img)
      tensor_data = next(pii)  # shape [1, 3, h, w]
      tensors = tensor_data[0]['data'].to(torch.device('cuda'))

i use img_queue as iterator, use DALIGenericIterator to transfer the output to tensor, each time i put a single image to queue, and call next(pii) to get the processed data, however it occurs error 
RuntimeError: The external source callback returned an unexpected batch size. Expected batch_size <= 1, actual: 56403

**Comment by JanuszL** [comment]
I suspect you may need to:
```
def next(self):
    item = self.get()
    if item is self._sentinel:
        raise StopIteration
    else:
        return [item]
```
As the `external_source` source needs to return a batch of data (list of elements) in your case.

**Comment by tangchen2** [comment]
> I suspect you may need to:
> 
> ```
> def next(self):
>     item = self.get()
>     if item is self._sentinel:
>         raise StopIteration
>     else:
>         return [item]
> ```
> 
> As the `external_source` source needs to return a batch of data (list of elements) in your case.

i refix this error, but the code waits at "pii = DALIGenericIterator(pipe, output_map=['data'])" initialization, it seems the inital queue doesnt have data, so it wait here cant go into the loop

    pii = DALIGenericIterator(pipe, output_map=['data'])
  File "/home/tangchen/.conda/envs/dali/lib/python3.6/site-packages/nvidia/dali/plugin/pytorch.py", line 174, in __init__
    prepare_first_batch=prepare_first_batch)
  File "/home/tangchen/.conda/envs/dali/lib/python3.6/site-packages/nvidia/dali/plugin/base_iterator.py", line 176, in __init__
    self._schedule_runs(False)
  File "/home/tangchen/.conda/envs/dali/lib/python3.6/site-packages/nvidia/dali/plugin/base_iterator.py", line 287, in _schedule_runs
    p.schedule_run()
  File "/home/tangchen/.conda/envs/dali/lib/python3.6/site-packages/nvidia/dali/pipeline.py", line 830, in schedule_run
    self._prefetch()
  File "/home/tangchen/.conda/envs/dali/lib/python3.6/site-packages/nvidia/dali/pipeline.py", line 927, in _prefetch
    self._run_once()
  File "/home/tangchen/.conda/envs/dali/lib/python3.6/site-packages/nvidia/dali/pipeline.py", line 937, in _run_once
    self._iter_setup()
  File "/home/tangchen/.conda/envs/dali/lib/python3.6/site-packages/nvidia/dali/pipeline.py", line 1178, in _iter_setup
    self.iter_setup()
  File "compare_dali_time.py", line 228, in iter_setup
    images = self.iterator.next()
  File "compare_dali_time.py", line 195, in next
    item = self.get()
  File "/home/tangchen/.conda/envs/dali/lib/python3.6/queue.py", line 164, in get
    self.not_empty.wait()
  File "/home/tangchen/.conda/envs/dali/lib/python3.6/threading.py", line 295, in wait
    waiter.acquire()

**Comment by JanuszL** [comment]
DALI does prefetching. So as soon as you create `DALIGenericIterator` it will run the `external_source` generator function and hang waiting for the data. You need to either fill the queue with some data before that or run the thread that would populate it.

**Comment by tangchen2** [comment]
> DALI does prefetching. So as soon as you create `DALIGenericIterator` it will run the `external_source` generator function and hang waiting for the data. You need to either fill the queue with some data before that or run the thread that would populate it.

Thank you so much! It works!

**Comment by tangchen2** [comment]
Sorry to reopen the issue, can DALI close the DALIGenericIterator prefectching? (i set prepare_first_batch == False, but didnt work), because iterator prefetching would prefetch 2 data in iterator, next time when i call next(pii)  to get torch tensor, it would call iter_setup internally(ExternalSourcePipeline) which would call queue.get to populate new data to Iterator, however, the iterator returned data was prefetched before not the queue polled data, how to solve this problem?

**Comment by tangchen2** [comment]
> Sorry to reopen the issue, can DALI close the DALIGenericIterator prefectching? (i set prepare_first_batch == False, but didnt work), because iterator prefetching would prefetch 2 data in iterator, next time when i call next(pii) to get torch tensor, it would call iter_setup internally(ExternalSourcePipeline) which would call queue.get to populate new data to Iterator, however, the iterator returned data was prefetched before not the queue polled data, how to solve this problem?

Pipeline parameters "prefetch_queue_depth" seems must be positive which means iterator has to do the prefetch?

**Comment by JanuszL** [comment]
Hi,

`prepare_first_batch == False` only tells if the Iterator construction should start processing right away or wait for the first `next` call.

> Pipeline parameters "prefetch_queue_depth" seems must be positive which means iterator has to do the prefetch?

It is the number of batches DALI processing. Setting to 1 would make DALI not process any batches ahead of time. Still, the iterator when returns the output would schedule another run.
In your case the best would be to just call `pipe.run` and then use `feed_ndarray` from nvidia.dali.plugin.pytorch to feed the PyTorch tensor with DALI data.

**Comment by tangchen2** [comment]
> Hi,
> 
> `prepare_first_batch == False` only tells if the Iterator construction should start processing right away or wait for the first `next` call.
> 
> > Pipeline parameters "prefetch_queue_depth" seems must be positive which means iterator has to do the prefetch?
> 
> It is the number of batches DALI processing. Setting to 1 would make DALI not process any batches ahead of time. Still, the iterator when returns the output would schedule another run.
> In your case the best would be to just call `pipe.run` and then use `feed_ndarray` from nvidia.dali.plugin.pytorch to feed the PyTorch tensor with DALI data.

Thank you so much! I tried this way and it works, referred #2330
