### ISSUE TITLE
Multi GPUs Failed when using TFRecords format data

### ISSUE THREAD

**Issue by KleinXin** [NVIDIA/DALI#2866]
I changed the data into TFRecords format with .tfrecords and .idx files. It works fine when I use only one GPU.

However, Some strange errors encounterred when I changed the number of GPU to more than 1.

The Error messages are as below

Error 1 

```
for (batch_idx, in_var) in enumerate(train_loader):
  File "/usr/local/lib/python3.6/dist-packages/nvidia/dali/plugin/pytorch.py", line 181, in __next__
    outputs = self._get_outputs()
  File "/usr/local/lib/python3.6/dist-packages/nvidia/dali/plugin/base_iterator.py", line 246, in _get_outputs
    outputs.append(p.share_outputs())
  File "/usr/local/lib/python3.6/dist-packages/nvidia/dali/pipeline.py", line 682, in share_outputs
    return self._pipe.ShareOutputs()
RuntimeError: Critical error in pipeline:
Error when executing Mixed operator ImageDecoder encountered:
Error in thread 1: [/opt/dali/dali/operators/decoder/nvjpeg/nvjpeg_decoder_decoupled_api.h:824] NVJPEG error "5" : NVJPEG_STATUS_ALLOCATOR_FAILURE
```

Error 2

```
for (batch_idx,in_var) in enumerate(val_loader):
  File "/usr/local/lib/python3.6/dist-packages/nvidia/dali/plugin/pytorch.py", line 181, in __next__
    outputs = self._get_outputs()
  File "/usr/local/lib/python3.6/dist-packages/nvidia/dali/plugin/base_iterator.py", line 246, in _get_outputs
    outputs.append(p.share_outputs())
  File "/usr/local/lib/python3.6/dist-packages/nvidia/dali/pipeline.py", line 682, in share_outputs
    return self._pipe.ShareOutputs()
RuntimeError: Critical error in pipeline:
Error when executing Mixed operator ImageDecoder encountered:
CUDA allocation failed
Current pipeline object is no longer valid.
```

The PyTorch version is 1.6.0 with cuda 10.1 and DALI version 0.30.0 with cuda 10.0

**Comment by JanuszL** [comment]
Hi @KleinXin,

This error means that you run out of GPU memory. If that works fine for 1 GPU, make sure that in the multi-GPU scenario each pipeline gets an appropriate device_id. It may happen that all pipelines land on the GPU 0.

**Comment by KleinXin** [comment]
> Hi @KleinXin,
> 
> This error means that you run out of GPU memory. If that works fine for 1 GPU, make sure that in the multi-GPU scenario each pipeline gets an appropriate device_id. It may happen that all pipelines land on the GPU 0.

Ok! I will have a try.

Could you please give some examples that I can follow? thx

**Comment by JanuszL** [comment]
@KleinXin,

You can check [this PyTorch RN50 example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/use_cases/pytorch/resnet50/pytorch-resnet50.html), similar [one for MXNet](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/use_cases/mxnet/mxnet-resnet50.html) or [TensorFlow](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/use_cases/tensorflow/resnet-n/README.html).

**Comment by KleinXin** [comment]
After decreasing the batch, codes can successully run on multi-gpus. 
I think even device_id=0, mlti-gpus can be used.
