### ISSUE TITLE
Image artifacts on 6 channel resize/random_resized_crop operations, only on gpu

### ISSUE THREAD

**Issue by gemenerik** [NVIDIA/DALI#2869]
I have a pipeline where two input (.ppm) images are concatenated after decoding and reshaping to the correct layout (e.g., HWC for TensorFlow). After concatenation follows either a `resize` operation for my validation pipeline, or a `random_resized_crop` for my train pipeline. If I move the tensors to GPU before the `resize`/`random_resized_crop` operation the resulting output images get severe artifacts. The images look fine when I do the concatenation after the `resize` or `random_resized_crop` operations. Clearly, the `resize` and `random_resized_crop` don't properly handle the 6 channel tensors when they are on GPU. On CPU, concatenating before resize works correctly.

![image](https://user-images.githubusercontent.com/49898887/114997828-8fd52a80-9ea0-11eb-9ecf-0b84ebc2a526.png)
_Desired output image_
![image](https://user-images.githubusercontent.com/49898887/114997860-9a8fbf80-9ea0-11eb-89fd-1f969fede1fb.png)
_Output image with artifacts_

Happens both in TensorFlow and PyTorch.

They are not just artifacts from retrieving the images from GPU for visualization; training suffers significantly.

Concatenating after the transformations is fine for my and probably many other applications, but just letting you know about the bug.

**Comment by mzient** [comment]
Indeed, there's a bug somewhere when using more fancy resampling. Performancewise there shouldn't be much difference between running resize twice and then concatenating, so you can use it as a workaround. Also, the bug doesn't affect INTERP_NN and INTERP_LINEAR interpolation modes. The default mode is INTERP_TRIANGULAR, but it the difference between linear and triangular only becomes important when downscaling.

**Comment by mzient** [comment]
Fix #2871 merged.

**Comment by JanuszL** [comment]
Please check the next nightly build to see if that fixes your problem.

**Comment by JanuszL** [comment]
Hi,
DALI 1.2 has been released and should fix the issue.
