### ISSUE TITLE
Does DALI support training on multiple servers using MXNet?

### ISSUE THREAD

**Issue by NanYan1119** [NVIDIA/DALI#287]
I have completed the training on single server using MXNet framework according to the guidance of DALI. 
https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/mxnet/mxnet-resnet50.html
I want to know if this support training on multiple servers. Is there an example? Thank you!

**Comment by JanuszL** [comment]
@ptrendx ?

**Comment by ptrendx** [comment]
Hi @NanYan1119. Yes, training on multiple nodes is supported. We don't have an example, but basically what you need to do on the DALI side is to set `num_shards` and `shard_id` parameters in reader to your total number of GPUs and the worker id.
If you use kvstore from MXNet your total number of GPUs is
```
kv.num_workers * n_gpus_per_worker
```
and your worker id:
```
my_gpu_id + kv.rank * n_gpus_per_worker
```
Hope this helps!

**Comment by NanYan1119** [comment]
@ptrendx Thank you for your answer! I tried to do the following work but not successfully. Can you help me?

I use openmpi to create 8 processes on a single server with 8 GPUs, each process for each GPU. The DALI pipeline may build in train_imagenet.py like this:

# local_rank means the GPU device number,
trainpipes = [HybridTrainPipe(batch_size=batch_size, num_threads=8, device_id = local_rank, num_gpus = 8) ]
# build pipeline
trainpipes[0].build()

When the size of train data is 1281167 and totally 8 GPUs, my expected result is that each GPU should train 1281167/8=160145 samples. But the result is that each of the 8 GPUs trains the whole samples 1281167 not one eighth. So I think this method may not expand to multiple servers. Can you tell me where is the error? Thank you!

**Comment by JanuszL** [comment]
Hi,
You can check MLPerf code for RN50 and MXNet - https://github.com/mlperf/results/tree/master/v0.5.0/nvidia/submission/code/image_classification/mxnet and especially https://github.com/mlperf/results/blob/master/v0.5.0/nvidia/submission/code/image_classification/mxnet/common/dali.py.
There is full info how you can run for single and multi node.
