### ISSUE TITLE
PyTorch DALIGenericIterator will loop indefinitely if initialized without reader_name for video pipelines

### ISSUE THREAD

**Issue by dwrodri** [NVIDIA/DALI#2873]
After porting some of my DALI code to 1.1.0 from 0.31, I was struggling to figure out why my `DALIGenericIterator` was looping indefinitely.

It turns out if both `reader_name` **and** `size` are unset in the call to `__init__`, then the DALIGenericIterator will loop indefinitely.

Here is a minimal example demonstrating this behavior.

```python
import sys

from nvidia.dali import fn
from nvidia.dali.pipeline import pipeline_def
from nvidia.dali.plugin.pytorch import DALIGenericIterator

@pipeline_def(batch_size=1, num_threads=1, device_id=0)
def simple_vid_loader(source: str, num_frames: int):
    frames = fn.readers.video(  # type: ignore
        sequence_length=num_frames,
        filenames=source,
        device="gpu",
        name="Reader",
    )
    return frames


if __name__ == "__main__":
    pipe = simple_vid_loader(sys.argv[1], num_frames=12)
    pipe.build()
    pytorch_iter = DALIGenericIterator(
        pipelines=pipe,
        output_map=["frames"],
        # reader_name="Reader", # uncomment this to fix the infinite loop
        auto_reset=False,
    )

    for i, batch in enumerate(pytorch_iter, 1):
        sys.stdout.write(f"{i}\r") # you'll see this number never stops going up when the reader line is uncommented
```

The documentation on the `size` parameter in `DALIGenericIterator` does suggest this behavior, so I don't know if this is really a "bug", but I thought sharing my experience would at the very least help others troubleshooting their code as they port to 1.0.0+

**Comment by JanuszL** [comment]
Hi @dwrodri,

It is expected. If you do not set the `size` or provide the `reader_name` the iterator is not able to determine the number of iteration it should loop every epoch. In this case, it waits for `StopIteration` exception that could be rise if your pipeline uses `external_source`, but this is not the case.
