### ISSUE TITLE
AutoaugmentImageNetPolicy in DALI - automatic augmentations support

### ISSUE THREAD

**Issue by pawopawo** [NVIDIA/DALI#2880]
How to use [AutoaugmentImageNetPolicy](https://github.com/NVIDIA/DeepLearningExamples/blob/26206dbf8704c91eb57d04baa777bc869bea7e13/PyTorch/Classification/ConvNets/image_classification/dataloaders.py#L427) in dali ？

**Comment by JanuszL** [comment]
Hi,
You can either try emulating it in the way [this examples](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/expressions/expr_conditional_and_masking.html) shows. DALI doesn't support conditional execution of operators/subgraphs yet. We do have that on our ToDo list.

**Comment by klecki** [comment]
Hi @pawopawo 
the support for conditional execution in DALI, expressed as `if` statements, was recently merged and is already available in the [nightly builds](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/installation.html#pip-nightly-and-weekly-releases) and will be a part of upcoming 1.23 release. The functionality is now available as experimental, we are still working on adding more features to it, and the documentation is currently under review in this PR: https://github.com/NVIDIA/DALI/pull/4589. You can preview the tutorial from that PR under this link: https://github.com/klecki/DALI/blob/cond-intro-tutorial/docs/examples/general/conditionals.ipynb, I will post an update when the actual documentation is visible in the nightly docs.

The support for conditionals (if statements) allows us to implement the AutoAugment and other automatic augmentation policies like RandAugment and TrivialAugment. We have prototypes for them already and we are testing them to iron out some details of our implementation. We plan to introduce them as a part of library in the near future, so they can be easily used as well as customized. I will be posting updates when we have something ready.

**Comment by klecki** [comment]
Hi @pawopawo,
DALI 1.23 (already released) contains the experimental support for conditional execution. The [docs are here](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/pipeline.html#conditional-execution-experimental) and the [tutorial is here](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/conditionals.html).

DALI 1.24 will add support for `and`, `or` and `not` expressions in graph definition, for now only for inputs of boolean type: https://github.com/NVIDIA/DALI/pull/4629.  It should be already available in nightly and weekly builds. 

We are currently working on providing implementation for automatic augmentations: AutoAugment, RandAugment and TrivialAugment as DALI module. It should land in DALI 1.24 or 1.25.

**Comment by stiepan** [comment]
Hi @pawopawo,

Followin up on the issue, [DALI 1.24](https://github.com/NVIDIA/DALI/releases/tag/v1.24.0) was released and contains `auto_aug` module with [auto augment implementation](https://github.com/NVIDIA/DALI/blob/main/dali/python/nvidia/dali/auto_aug/auto_augment.py). Running the policy for ImageNet + EfficientNet is avialable out of the box as `auto_augment_image_net` (https://github.com/NVIDIA/DALI/blob/main/dali/python/nvidia/dali/auto_aug/auto_augment.py#L120).

The EfficientNet example from NVIDIA Deep learning examples has been adapated to use DALI and is avialable here: https://github.com/NVIDIA/DALI/tree/main/docs/examples/use_cases/pytorch/efficientnet
