### ISSUE TITLE
NO responsing while creating the pipline

### ISSUE THREAD

**Issue by LZhangMorilab** [NVIDIA/DALI#2892]
I created a pipline like this:

```
tfrecoder_list = [os.path.join(r'tfrecorder', r'train{}.tfrecords'.format(i)) for i in range(n_split)]
index_path = ["idx_files/train{}.idx".format(i) for i in range(n_split)]
while pipe:

    inputs = fn.readers.tfrecord(
            path=tfrecoder_list,
            index_path=index_path,
            features={ 'label': tfrec.FixedLenFeature([1], tfrec.int64, -1),
                      'img' : tfrec.FixedLenFeature((), tfrec.string, "")})

    pipe.set_outputs(inputs["img"], inputs["label"])
    
pipe.build()

```
 While the idx file was created successfully, I cannot run the pipline-creating code. I ran it and wait for about 20 mins but there is no responsing yet. Each tfrecord file is in the size of about 10GB while the 'img' array are all in the size of (4,256,256). I load these tfrecord files by tensorflow dataset, and it can be load successfully. 

As another question, is there any decoder like `tf.io.decode_raw` to decode the tfrecoder input into the array?

Thank you.

**Comment by JanuszL** [comment]
Hi,

Have you checked [this example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/dataloading_tfrecord.html#) using the data from https://github.com/NVIDIA/DALI_extra repository?

**Comment by LZhangMorilab** [comment]
I checked the code and found a foolish bug: I replaced 'with' into 'while', that cased the no response. Thank you for your reply and sorry for wasted your time :).
