### ISSUE TITLE
Is there any tfrecord decoder for array?

### ISSUE THREAD

**Issue by zwy314** [NVIDIA/DALI#2895]
Is there any decoder like tf.io.decode_raw to decode the array data from strings?
I saved the 3D array data into the tfrecord files as the type of tf.string, but I cannot find any decoder in fn.decoders for array data. Is there any function that can change the tf.string data into the array or image?
?

**Comment by JanuszL** [comment]
Hi,

You can check [this example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/dataloading_tfrecord.html) first. This way you can read this data as a 1D array (no additional decoding is required).
If you want to make it 3D you need to save its shape in another field of TFRecord and use [the `reshape` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.reshape).
