### ISSUE TITLE
GPU utility is low using pipeline for video

### ISSUE THREAD

**Issue by zhangxuan1918** [NVIDIA/DALI#2896]
Hello,

I'm using the video pipeline from the tutorial found here: [video](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/sequence_processing/video/video_reader_label_example.html).
What I see is that my GPU's utility is not high, jumping from 1% to 100% and back. On average, the utility is around 20-40%.

I tried different configurations for

* batch_size
* num_threads
* initial_prefetch_size

I didn't see any big difference.

My current config for the pipeline

* batch_size: 64,
* num_threads: 6,
* sequence_length: 16,
* num_shards: 1,
* initial_prefetch_size: 10240
* 3 videos, each 1 hour in a folder
   * fps: 23.98
   * resolution: 256 x 144
        
driver Version: 460.56       
CUDA Version: 11.2
pytorch version: 1.8.0
1 GPU: RTX 3090

Any suggestion how I can improve it? Thx

**Comment by JanuszL** [comment]
Hi,
Video decoder usage doesn't contribute to overall GPU utilization. In this case, the decoder does most (if not all of the GPU-related work).
If you want to check how the decoder is utilized you can run:
```
nvidia-smi -q -g 0 -d UTILIZATION -l
```

**Comment by zhangxuan1918** [comment]
> Hi,
> Video decoder usage doesn't contribute to overall GPU utilization. In this case, the decoder does most (if not all of the GPU-related work).
> If you want to check how the decoder is utilized you can run:
> 
> ```
> nvidia-smi -q -g 0 -d UTILIZATION -l
> ```

Hi Janusz,

thanks for your reply. If I understand it correctly, the hardware decoder is independent of gpu (except it uses some memory). Thus, in the perfect situation, I should see gpu 100% used.

For me, this is not the case. It looks like when the decoder is fully loaded, the gpu is idle and vice versa.
I checked the gpu memory. I still have 6GB gpu memory available when I train the model.

In my configuration, the `initial_prefetch_size` is set to be the size of 10 batches. Thus, I expect to see gpu more or less 100% used when training the model.

Do you have any suggestions or pointers on how to improve gpu utility? Thx.

**Comment by JanuszL** [comment]
Hi @zhangxuan1918,

It is hard to tell without looking into the [GPU profile](https://developer.nvidia.com/nsight-systems) why you see such behavior. In the perfect case, the data loading part should overlap with the training and you should see stable GPU utilization all the time.
What you can try to do is to change the `prefetch_queue_depth` value in the reader.

I can only guess that the loading part is still a bottleneck and you are not able to fully overlap it with the training.

**Comment by zhangxuan1918** [comment]
thanks @JanuszL . Will check the GPU profile. I will close this issue.
