### ISSUE TITLE
[ENHANCEMENT PROPOSAL] (image, image) in addition to (image, label) for supervised learning

### ISSUE THREAD

**Issue by opetrova** [NVIDIA/DALI#290]
Hi,
I opened an [issue](https://github.com/NVIDIA/DALI/issues/274) about this a little while ago, and after getting some very helpful feedback from @JanuszL I got the functionality I needed. I had to make a small change to the `DALIGenericIterator` class in `nvidia.dali.plugin.pytorch` to make it work though, so I would like to propose a pull request, if anyone else finds it useful.

The use case is needing (image, image) pairs rather than (image, label) pairs for supervised learning, as is the case in super resolution or image colorisation for instance. An appropriate Pipeline can be written using `ExternalSource`, but there is an issue with using `DALIGenericIterator` with it: the `("data", "label")` structure does not work if the second output of the `Pipeline` is on the GPU, plus there can be additional issues e.g. if greyscale images are used, because the `"label"` tensor gets squeezed. The `("data", "data")` labelling does not work because both outputs of the pipeline get fed into the same tensor. Using multiple pipelines does not work if the data gets shuffled. My solution is to introduce an additional label `"target"` which deals with cases when the target for a given input is something other than a number stored on the CPU (such as `"label"`).

If this functionality sounds like something useful for the wider community, I'll go ahead and send a pull request and maybe add a DALI/Pytorch super resolution example that uses it.

**Comment by JanuszL** [comment]
@klecki I think you are trying to do something similar in #282.

**Comment by JanuszL** [comment]
Besides that feel free to contribute super resolution example that uses it. Please just follow https://github.com/NVIDIA/DALI/blob/master/CONTRIBUTING.md and make sure you can contribute super resolution (no license/royalty issue).

**Comment by opetrova** [comment]
Thanks @JanuszL ! Right now I'd have to make a change to `DALIGenericIterator` in `nvidia.dali.plugin.pytorch` to make it work, so I guess I should wait till [#282](https://github.com/NVIDIA/DALI/pull/282) is done.

**Comment by klecki** [comment]
Yes, the idea behind #282 is to allow for arbitrary categories/labels beside "data" and "labels" in generic way. Also it should fix a bug, because currently it fails without specifying "labels".

**Comment by JanuszL** [comment]
Done in https://github.com/NVIDIA/DALI/pull/282

**Comment by BostonLobster** [comment]
@opetrova  I'm also experimenting on super resolution with DALI, and in great request for your proposed funtionality! Have you merged your pull request to the main repository? Can I use it right now? Or could you share your DALI/Pytorch super resolution example with me? Many thanks!
