### ISSUE TITLE
How to read same video twice?

### ISSUE THREAD

**Issue by SunDoge** [NVIDIA/DALI#2901]
Hi, 

I want to read same video twice with different timestamps.  If I am going to read an image twice, I can do something like this:

```python
files, labels = fn.readers.file(file_root)
view1 = fn.decoders.image_random_crop(files)
view2 = fn.decoders.image_random_crop(files)
```

However, the functionality `fn.decoders.video` is missing. Is there any workaround? This pipeline is important for self-supervised learning.

**Comment by JanuszL** [comment]
Hi @SunDoge,

You can check [these examples](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/sequence_processing/index.html) to learn how to read video files.

Regarding your sample code, you read the same images but you apply a different crop operator. In this case, it could be better to read, decode and then apply [the random_resized_crop](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.random_resized_crop) operator to save redoing the time-consuming decoding process twice.

**Comment by SunDoge** [comment]
Hi @JanuszL ,

I have already read the examples and I know how to read the video files. My snippet is only pseudo code and I know we can only decode part of a JPEG image which is more performant. 

In self-supervised learning, e.g., [MoCo](https://github.com/facebookresearch/moco/), we need two augmented view of the same image. In practice, we can load the image and apply the random spatial crop twice. And for video, we want to apply both spatial and temporal crop, e.g. sampling 8 frames at the beginning of the video and 8 frames at the end. However, the "temporal crop" is in `fn.readers.video` operation, which makes it difficult to take two different clips of the same video.

Actually there is a workaround. I can make two video readers sharing the same `file_list` and `random_shuffle=False`. But I hope there will be some official supports.
