### ISSUE TITLE
Video Pipeline Error: "[mov,mp4,m4a,3gp,3g2,mj2 @ 0x559331a60180] stream 0, timescale not set"

### ISSUE THREAD

**Issue by Wilann** [NVIDIA/DALI#2905]
I'm currently using the [Simple Video Pipeline Reading From Multiple Files](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/sequence_processing/video/video_reader_simple_example.html) tutorial from the docs and get this error while running the pipeline: 
`[mov,mp4,m4a,3gp,3g2,mj2 @ 0x559331a60180] stream 0, timescale not set`

The output of the pipeline is frozen at `(2, 8, 1080, 1920, 3)`

Can anyone see the issue? Please let me know! 

Full Code:
```
import os
import numpy as np
from nvidia.dali import pipeline_def
import nvidia.dali.fn as fn
import nvidia.dali.types as types

batch_size = 2
sequence_length = 8
initial_prefetch_size = 16
file_name = './20181108 - R16 _ MS _ Kento MOMOTA (JPN) [1] vs Hans-Kristian Solberg VITTINGHUS (DEN) _ BWF 2018.mp4'
n_iter = 10

@pipeline_def
def video_pipe(filenames):
    videos = fn.readers.video(device="gpu", filenames=file_name, sequence_length=sequence_length,
                              shard_id=0, num_shards=1, random_shuffle=True, initial_fill=initial_prefetch_size)
    return videos

pipe = video_pipe(batch_size=batch_size, num_threads=4, device_id=0, filenames=file_name, seed=123456)
pipe.build()
for i in range(n_iter):
    pipe_out = pipe.run()
    sequences_out = pipe_out[0].as_cpu().as_array()
    print(sequences_out.shape)
```

**Comment by JanuszL** [comment]
Hi,
I think the warning you see is irrelevant.
The issue seems to be similar to https://github.com/NVIDIA/DALI/issues/2818. Currently, we don't have a solution to the mentioned problem, it is still under investigation.

**Comment by JanuszL** [comment]
Hi,
We have merged a possible fix in https://github.com/NVIDIA/DALI/pull/2916. Can you check tomorrow nightly build to see if that helps?

**Comment by Wilann** [comment]
Hi, will check in a bit.

**Comment by JanuszL** [comment]
Hi,
DALI 1.2 has been released and should fix the issue.
