### ISSUE TITLE
About transpose augmentation

### ISSUE THREAD

**Issue by KleinXin** [NVIDIA/DALI#2908]
I want to add some transpose augmentation（rotate by 90 or 270 degrees） to the trainning process.

Can I use ops.Rotate or ops.Transpose？

I think ops.Transpose should be better.

If the input is in HWC format, can I use ops.Transpose in this way?

```
output = ops.Transpose(input,
                        perm=[1,0,2])
```

I think this can rotate the image with 90 or 270 degrees, another horizontal flip is also needed.

**Comment by JanuszL** [comment]
Hi @KleinXin,

In your case, it is best to use flip and define horizontal and/or vertical options when needed. Transpose reverse or permute the axes.

**Comment by KleinXin** [comment]
> Hi @KleinXin,
> 
> In your case, it is best to use flip and define horizontal and/or vertical options when needed. Transpose reverse or permute the axes.

Do you mean rotation followed by flipping? For example, I want to change a image with dimension 400x300x3 to 300x400x3. 
How can I do that?

**Comment by JanuszL** [comment]
My bad, I was thinking about something else.
Yes, in your case, you need to use rotate.

**Comment by KleinXin** [comment]
> My bad, I was thinking about something else.
> Yes, in your case, you need to use rotate.

I'm afraid images may be cropped during the rotation. Is that true?
For example, if the image is rotated by 45 degrees clock-wise, the dimension of the image is still 400x300x3, but only a few part is left, most of the image is filled with 0 by default.

**Comment by JanuszL** [comment]
> > My bad, I was thinking about something else.
> > Yes, in your case, you need to use rotate.
> 
> I'm afraid images may be cropped during the rotation. Is that true?
> For example, if the image is rotated by 45 degrees clock-wise, the dimension of the image is still 400x300x3, but only a few part is left, most of the image is filled with 0 by default.

Please set `keep_size=False` and the canvas would be adjusted (enlarged) to house the whole image.

**Comment by KleinXin** [comment]
> > > My bad, I was thinking about something else.
> > > Yes, in your case, you need to use rotate.
> > 
> > 
> > I'm afraid images may be cropped during the rotation. Is that true?
> > For example, if the image is rotated by 45 degrees clock-wise, the dimension of the image is still 400x300x3, but only a few part is left, most of the image is filled with 0 by default.
> 
> Please set `keep_size=False` and the canvas would be adjusted (enlarged) to house the whole image.

thx！This helps me improve the top-1 about 7 points.
