### ISSUE TITLE
PyTorch iterators provide only a single datapoint and label duplicated when asking for batches

### ISSUE THREAD

**Issue by ndalton12** [NVIDIA/DALI#2910]
Hi,

So I was trying to debug why my network performance was different in DALI rather than custom solutions. I discovered that the pytorch plugin iterators (both `DALIGenericIterator` and `DALIGenericIterator` have this issue) will only return a single data point (the same single data point) when asking for more batches after the first.

When I manually build the pipeline and ask for samples, I get the correct output, with labels 0, 1, and 2 all present in at least a couple examples. But when I wrap said pipeline in the PyTorch plugins, I only see outputs with label 2.

Here is a full recreation:

```
docker run --rm -ti --gpus '"capabilities=compute,utility,video"' nvidia/cuda:11.1.1-runtime-ubuntu18.04

apt update && apt install -y wget git git-lfs && git lfs install
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
chmod +x Miniconda3-latest-Linux-x86_64.sh
./Miniconda3-latest-Linux-x86_64.sh  # follow default install
bash
conda install pytorch cudatoolkit=11.1 -c pytorch -c conda-forge  # follow defaults
pip install --extra-index-url https://developer.download.nvidia.com/compute/redist --upgrade nvidia-dali-cuda110
git clone https://github.com/NVIDIA/DALI_extra
git clone https://gist.github.com/d88b69a199982d1bd6c6612fda4462e2.git
python d88b69a199982d1bd6c6612fda4462e2/dali_bad_labels.py
```

Random seeding does not affect this. Same issue but just with a different label duplicated instead. I also tried a bunch of different parameters in both the pipeline and the iterator, but nothing fixed the issue, including playing with prefetching. Changing batch size made it so a couple labels could be seen, but then the rest of the iterations were duplicated. I.e. batch size 4 might return [1, 0, 0, 0] labels, but then all subsequent batches will also have exactly [1, 0, 0, 0] as labels.

Even explicitly providing a `file_list` with explicit labels for each clip does not fix the issue.

**Comment by JanuszL** [comment]
Hi @ndalton12 ,

As stated in [the documentation](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/plugins/pytorch_plugin_api.html) `Please keep in mind that Tensors returned by the iterator are still owned by DALI. They are valid till the next iterator call. If the content needs to be preserved please copy it to another tensor.` calling `items.append(item[0])` will append the same set of tensors over and over and its content will change over time. If you call:
```
for item in loader1:
    items.append(item[0])
    print(item[0]["label"])
```
you will see that the labels have desired values.

**Comment by ndalton12** [comment]
Ah, okay, thank you.
