### ISSUE TITLE
Possible to build new version of DALI?

### ISSUE THREAD

**Issue by ghop02** [NVIDIA/DALI#292]
There is some code regarding multiple outputs that I would love to use, but have been struggling to compile.  Would it be possible to build a new version of DALI from master? Not 100% sure what the release process is. 

Thanks!

**Comment by JanuszL** [comment]
Hi,
As you can see we are doing our best to follow the monthly release process. We hope to release 0.6 with this change somewhere in the middle of December (a tentative plan that may change without notice form our side).
You can still try to build on your own, please try again to follow https://github.com/NVIDIA/DALI#compiling-dali-from-source - if you have any question regarding the build process feel free to ask.

**Comment by awolant** [comment]
Hi,
you can also look into [Dockerfile.deps](https://github.com/NVIDIA/DALI/blob/master/Dockerfile.deps) for how to set up dependencies and [Dockerfile](https://github.com/NVIDIA/DALI/blob/master/Dockerfile) for how to build DALI. It helped me a lot with building it lately.

**Comment by JanuszL** [comment]
@ghop02 if you use Docker.deps. please comment out L11 and uncomment L12.

**Comment by JanuszL** [comment]
If it doesn't work for you please reopen.

**Comment by ghop02** [comment]
Thanks! I ended up not needing to compile. Thought I needed more than two outputs, but turns out I do not.
