### ISSUE TITLE
Using SSD scratch drives to eliminate I/O bottleneck

### ISSUE THREAD

**Issue by dariodematties** [NVIDIA/DALI#2922]
Hi guys!

I am trying to use SSD scratch disks in order to eliminate I/O bottlenecks in my code

As I understand it, transferring data sets to the node local scratch space should preferentially be done in large contiguous chunks to maximize transfer speed, otherwise the copying process takes forever.

A good way to achieve this is to store the data set on centre storage (in your /projects folder for instance) in an uncompressed tar archive and transfer this and finally unpacking to scratch in your job on the allocated GPU node like

```
cd /raid/scratch
mkdir ImageNet
cd ImageNet
mkdir ILSVRC
cd ILSVRC  
mkdir Data
cd Data
mkdir CLS-LOC
cd CLS-LOC
mkdir train
mkdir val

echo "Copying train tarballs to scratch"

cp -rv /lus/theta-fs0/software/datascience/ImageNet/tarballs/img_train/*.tar ./train

cd train

echo "Untaring train tarballs in scratch"

for f in `ls *.tar`; do echo $f; mkdir ${f%.tar}; tar -xf $f -C ${f%.tar}; done


```
But when I want to run the code I receive the following error

```
RuntimeError: Critical error when building pipeline:
Error when constructing operator: FileReader encountered:
[/opt/dali/dali/operators/reader/loader/file_label_loader.cc:59] Assert on "dir != nullptr" failed: Directory /raid/scratch/ImageNet/ILSVRC/Data/CLS-LOC/train could not be opened.


```
I have checked it and I have permissions to the scratch file space

The error is produced when I try to build the pipe

```
        elif args.dataset == 'imagenet':
                file_root = os.path.join(test_data_root, 'ImageNet', 'ILSVRC', 'Data', 'CLS-LOC', 'train')

                pipe1 = NDP.ImagenetReader(batch_size=args.batch_size,
                                           num_threads=args.workers,
                                           device_id=args.gpu,
                                           file_root=file_root,
                                           shard_id=args.gpu,
                                           num_shards=args.world_size,
                                           dali_cpu=args.dali_cpu)

                pipe1_reader_name = 'ImagesReader'

        else:
                raise Exception("error: I do not accept {} as a viable dataset".format(args.dataset))

        start = time()
        pipe1.build()
        total_time = time() - start
        meta_data = pipe1.reader_meta()[pipe1_reader_name]

```
Any idea of what could be happening here?

Thanks!

**Comment by JanuszL** [comment]
Hi,

Could you check in your python script if the directory exists and if you can create/read any files outside DALI?
Maybe there is an additional level in the path after you unpack the tar archive?

**Comment by dariodematties** [comment]
Thank you very much @JanuszL, I want to apologize. I didn't realize I forgot to add the path in singularity (-B /raid:/raid)
However, singularity cannot mount /raid but it is another problem that has nothing to do with DALI
Thank you and I am sorry

**Comment by JanuszL** [comment]
No problem. Happy to help.
