### ISSUE TITLE
External Source: Exception in CPU stage

### ISSUE THREAD

**Issue by KarelvdVrie** [NVIDIA/DALI#2923]
Hi,

I am testing my DALI pipeline before serializing it for use in the TRITON server. 
With the below example using the feed_input function ends half of the time in the error below , and the other half it runs correctly. When I use the code written for the TRITON server it fails 100% of the time with the below error.

### The code:
```
import nvidia.dali as dali
import numpy as np

pipe = dali.pipeline.Pipeline(batch_size=1, num_threads=1, device_id=0)

with pipe:
    x = dali.fn.external_source(device="cpu", name="DALI_INPUT")
    pipe.set_outputs(x)

pipe.build()

pipe.feed_input("DALI_INPUT", np.array([400.0], dtype=np.uint16))

pipe_out = pipe.run()
```

### The error:
```
Traceback (most recent call last):
  File "/Development/Bug.py", line 15, in <module>
    pipe_out = pipe.run()
  File "/usr/local/lib/python3.8/dist-packages/nvidia/dali/pipeline.py", line 917, in run
    return self.outputs()
  File "/usr/local/lib/python3.8/dist-packages/nvidia/dali/pipeline.py", line 816, in outputs
    return self._outputs()
  File "/usr/local/lib/python3.8/dist-packages/nvidia/dali/pipeline.py", line 900, in _outputs
    return self._pipe.Outputs()
RuntimeError: Critical error in pipeline:
Exception in CPU stage: Attempted to peek element that doesn't exist. Add more elements to CachingList before calling PeekProphet. Even the prophet can't see outside the event horizon.
Current pipeline object is no longer valid.
```

### Software versions
I have tested with both the DALI 1.1.0 and 1.0.0 versions, the python versions were 3.8 and 3.6.9. The code is all run in Docker containers, one version build from the `nvidia/cuda:11.1-devel` image and the other the `nvcr.io/nvidia/tritonserver:21.04-py3` image. The nvidia driver versions tested were 460 and 465 although the code is purely CPU based, so don't expect the problem to be there.

**Comment by JanuszL** [comment]
Hi,

You should not call `feed_input` directly in your case. There is a race condition in this case. DALI pipeline does prefetch and tries to consume data from `external_source`. If it happens before `feed_input` is executed it fails.
I recommend checking [this guide](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/external_input.html) and pass data generator function as an `external_source` argument.

**Comment by JanuszL** [comment]
Correction. In your case, the prefetch depth has a default value. So it is 2. So DALI tries to consume 2 batches of data while you provide only one. If the script ends faster than DALI consumes the second batch it won't throw anything, if not you see the error.

**Comment by JanuszL** [comment]
If you want to mimic what TRITON DALI Backend does you should do:
```
import nvidia.dali as dali
import numpy as np

pipe = dali.pipeline.Pipeline(batch_size=1, num_threads=1, device_id=0, prefetch_queue_depth=1, exec_pipelined=False, exec_async=False)

with pipe:
    x = dali.fn.external_source(device="cpu", name="DALI_INPUT")
    pipe.set_outputs(x)

pipe.build()

pipe.feed_input("DALI_INPUT", np.array([400.0], dtype=np.uint16))

pipe_out = pipe.run()
```

**Comment by KarelvdVrie** [comment]
That works!

Thank you for the quick responses and clear result.
