### ISSUE TITLE
Reset in the middle of the epoch

### ISSUE THREAD

**Issue by AlbertiPot** [NVIDIA/DALI#2938]
Hi, the DALI dataloader is really much faster! 

However, I encountered some unusual cases: In my model, I have to explore only part of the batches from an epoch to calibrate the BN layer. Once finished calibrating, the dataloader should be reset. But the reset() function currently only supports resetting at the end of an epoch. Is there any way to reset in the middle of the epoch? 

Many many thanks for this amazing fast loader!

**Comment by JanuszL** [comment]
Hi @AlbertiPot,

The reset operation mostly affects the python part and doesn't change the internal state of the native part. As DALI does prefetch and computes batches ahead of time it would be hard to reset it. In this case, the easiest approach would be to just recreate the DALI pipeline and the iterator.
If you want to do it every epoch you can create a separate DALI pipeline using only a subset of the data, and use it only for the calibration. However, it may be too much regarding memory consumption.
