### ISSUE TITLE
difference result between dali and opencv

### ISSUE THREAD

**Issue by ThiagoMateo** [NVIDIA/DALI#2940]
i try to read image in 2 way: dali and opencv
![4](https://user-images.githubusercontent.com/48821989/117621521-e41bb380-b19b-11eb-976e-c7003c5cc63f.jpg)

origin image size is [w, h, c] = [4032, 3024, 3]
with opencv, i just read, show and write image. it seem that image auto rotate 90 degree clockwise. it's so convenient
![tmp](https://user-images.githubusercontent.com/48821989/117621977-55f3fd00-b19c-11eb-87e2-2f5b0c1aa710.jpg)
with dali, image show below.
```
jpegs, _ = fn.readers.file(files=[file])
    images = fn.decoders.image(jpegs, device='mixed')
#     images = fn.rotate(images, angle=-90, fill_value=0)
    width = 640
    height = 480
    #out = fn.resize(images, size=[height, width], mode='not_larger')  # maintain aspect ratio
    #out = fn.crop(out, crop_w=width, crop_h=height, out_of_bounds_policy="pad")
    pipe.set_outputs(images)
    
```
![Screenshot from 2021-05-10 14-32-16](https://user-images.githubusercontent.com/48821989/117622400-cef35480-b19c-11eb-9bfc-7649d8047c89.png)

question is that, how to do like opencv without rotate manually?

**Comment by JanuszL** [comment]
Hi @ThiagoMateo,

DALI doesn't support EXIF metadata yet - 
![image](https://user-images.githubusercontent.com/39967756/117642228-5635cd80-b187-11eb-9259-204deb9eb411.png).
There is a task for that https://github.com/NVIDIA/DALI/issues/2660#issuecomment-817139055 but I don't think there have been any progress there.
