### ISSUE TITLE
Video reader profiling speed (DALI vs opencv)

### ISSUE THREAD

**Issue by albanie** [NVIDIA/DALI#2954]
Thanks for contributing this library. I had a few questions about expected runtime performance for the DALI video reader. My questions are:
1. Is it expected that changing the `sequence_length` for [nvidia.dali.fn.readers.video](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.readers.video) and the and `batch_size` parameter for a [pipeline_def generated object](https://docs.nvidia.com/deeplearning/dali/master-user-guide/docs/pipeline.html?highlight=pipeline_def#nvidia.dali.pipeline_def) dramatically changes performance even while holding their product fixed (i.e. maintaining the same total number of frames that are read per iteration)? In particular, I observed that a batch size of 100 with a sequence length of 10 is much slower than a batch size of 10 with a sequence length of 100.
2. Would you expect DALI to be slower than opencv when reading a video onto the GPU sequentially, rather than with random access, for the case when short sequences of frames are read?

When trying out DALI with various settings, I found it to be slower than opencv, but it’s possible I’m missing something - if so any suggestions on how to improve things are appreciated.  I read through the performance tuning guide [here](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/advanced_topics_performance_tuning.html), but given the note suggesting that default parameters should work well for “typical use cases”, I haven’t yet played around with thread affinity etc.

I’ve added a minimal working example of the benchmark code used to produce the results below as a gist [here](https://gist.github.com/albanie/49a1e0c844ed91c473648ee5803846f4). The timings I got were:
```
===========================================
Hardware summary (note, only using one GPU)
'GPU 0: GeForce GTX 1080 Ti (UUID: GPU-a1823874-987c-b285-32e6-f91b3dd502eb)'
===========================================
Platform summary:
3.7.7 (default, May  7 2020, 21:25:33) 
[GCC 7.3.0]
===========================================
DALI version: 1.1.0
Torch cuda: 10.1
===========================================
Timing results (averages across 3):
cv2-batch_size-1-seq_len-8: 1956.2 Hz +/- 57.9
cv2-batch_size-1-seq_len-16: 1973.8 Hz +/- 39.0
cv2-batch_size-1-seq_len-32: 2099.1 Hz +/- 55.0
cv2-batch_size-1-seq_len-64: 1989.5 Hz +/- 22.4
cv2-batch_size-10-seq_len-8: 2014.3 Hz +/- 37.7
cv2-batch_size-10-seq_len-16: 2086.0 Hz +/- 13.3
cv2-batch_size-10-seq_len-32: 2089.2 Hz +/- 27.8
cv2-batch_size-10-seq_len-64: 2081.2 Hz +/- 41.6
dali-batch_size-1-seq_len-8-num_threads-1: 380.8 Hz +/- 0.8
dali-batch_size-1-seq_len-8-num_threads-4: 380.4 Hz +/- 0.7
dali-batch_size-1-seq_len-8-num_threads-8: 378.9 Hz +/- 0.2
dali-batch_size-1-seq_len-8-num_threads-16: 380.0 Hz +/- 0.5
dali-batch_size-1-seq_len-16-num_threads-1: 707.7 Hz +/- 2.3
dali-batch_size-1-seq_len-16-num_threads-4: 706.8 Hz +/- 1.4
dali-batch_size-1-seq_len-16-num_threads-8: 705.7 Hz +/- 1.3
dali-batch_size-1-seq_len-16-num_threads-16: 703.5 Hz +/- 0.8
dali-batch_size-1-seq_len-32-num_threads-1: 1233.7 Hz +/- 2.4
dali-batch_size-1-seq_len-32-num_threads-4: 1229.5 Hz +/- 1.5
dali-batch_size-1-seq_len-32-num_threads-8: 1231.5 Hz +/- 1.9
dali-batch_size-1-seq_len-32-num_threads-16: 1231.0 Hz +/- 4.0
dali-batch_size-1-seq_len-64-num_threads-1: 2027.1 Hz +/- 15.8
dali-batch_size-1-seq_len-64-num_threads-4: 2017.5 Hz +/- 20.7
dali-batch_size-1-seq_len-64-num_threads-8: 2004.3 Hz +/- 6.0
dali-batch_size-1-seq_len-64-num_threads-16: 2003.3 Hz +/- 12.8
dali-batch_size-10-seq_len-8-num_threads-1: 373.1 Hz +/- 1.1
dali-batch_size-10-seq_len-8-num_threads-4: 372.1 Hz +/- 0.1
dali-batch_size-10-seq_len-8-num_threads-8: 373.0 Hz +/- 1.2
dali-batch_size-10-seq_len-8-num_threads-16: 372.0 Hz +/- 0.2
dali-batch_size-10-seq_len-16-num_threads-1: 719.7 Hz +/- 0.7
dali-batch_size-10-seq_len-16-num_threads-4: 720.3 Hz +/- 1.1
dali-batch_size-10-seq_len-16-num_threads-8: 720.4 Hz +/- 0.7
dali-batch_size-10-seq_len-16-num_threads-16: 719.5 Hz +/- 0.5
dali-batch_size-10-seq_len-32-num_threads-1: 1300.1 Hz +/- 2.8
dali-batch_size-10-seq_len-32-num_threads-4: 1304.8 Hz +/- 3.0
dali-batch_size-10-seq_len-32-num_threads-8: 1300.0 Hz +/- 2.1
dali-batch_size-10-seq_len-32-num_threads-16: 1301.2 Hz +/- 3.0
dali-batch_size-10-seq_len-64-num_threads-1: 2058.8 Hz +/- 3.7
dali-batch_size-10-seq_len-64-num_threads-4: 2053.5 Hz +/- 3.6
dali-batch_size-10-seq_len-64-num_threads-8: 2059.3 Hz +/- 5.4
dali-batch_size-10-seq_len-64-num_threads-16: 2065.4 Hz +/- 10.5
```

Further comments about the interpretation of the strings are given in the code, but the takeaways for me were: 
* For most settings I tried, reading an mp4 file with DALI was significantly slower than opencv
* This difference in speed is particularly prevalent when the sequence length is reduced
* Adding more threads doesn't seem to increase speed (this is on an otherwise idle machine with 32 CPUs and 252GB of RAM)

One other observation (in case it's a useful clue): monitoring the profiler with `htop` suggests that total CPU utilisation and GPU utilisation is fairly low throughout these benchmarks for the DALI reader, whereas opencv makes much heavier use of the CPUs.  

The reason for my question is that I'm particularly interested in using DALI for the case when the batch size is large, but the sequence length is short (this appears to significantly slow down the DALI reader in my comparison).  Specifcally, it would be great to be able to load tensors of video frames of shape `B x F x H x W x 3` (where `B = batch_size, F = frames per sequence, H = height, W = width, 3 = RGB channels`) quickly when B is large and F is small (this is currently slow). By contrast, when F is large and B is small, DALI is as fast as opencv for me (and sometimes faster).  Does that seem feasible within the current framework?

Thanks!

**Comment by JanuszL** [comment]
Hi @albanie,

DALI video reader is designed to generate random sequences from the input videos. For every sample in the batch DALI randomly pick all available sequences with a given length, step, and stride from available videos, seeks to the keyframe that precedes the one that is first in the sequence, then it sequentially reads and decodes frames until the last one that needs to be decoded. Frames that are not in the requested sequence still need to be decoded as the video can be accessed only sequentially. So the shorter sequence or the step between frames is bigger the more frames need to be decoded and dropped.
To check the video decoder utilization please issue `nvidia-smi -q -g 0 -d UTILIZATION -l`. This value is separated from the overall GPU compute utilization.
Increasing the number of CPU threads doesn't affect DALI decoding performance as it is performed by a dedicated HW unit inside the GPU.
It seems that for your current use case DALI may not be the best choice.

**Comment by albanie** [comment]
Ok - thanks @JanuszL !
