### ISSUE TITLE
Is sobel filtering implemented in DALI?

### ISSUE THREAD

**Issue by dariodematties** [NVIDIA/DALI#2963]
Basically this is my question. Is sobel or another set of filtering toolkit implemented in DALI?

Thanks!

Dario

**Comment by JanuszL** [comment]
Hi, @dariodematties,

DALI doesn't support the Sobel operator. However we do support Gaussian filer which is based on separable convolution, so it should not be that hard to add Sobel as well.
We will add it to our ToDo list.

**Comment by dariodematties** [comment]
Thanks @JanuszL , I will take a look at how the Gaussian filter is implemented.


Thanks!

**Comment by stiepan** [comment]
The sobel filter can now be implemented using filter operator (https://github.com/NVIDIA/DALI/pull/4525).

**Comment by JanuszL** [comment]
DALI 1.22 has been released with this functionality included.
