### ISSUE TITLE
Accuracy is quite different by using pytorch dataloader instead of DALI

### ISSUE THREAD

**Issue by KleinXin** [NVIDIA/DALI#2966]
I am preparing a competition of classification task where only pytorch environment without DALI is provided. So I have to use the pytorch dataloader to load images and use the model weights pretrained by DALI.

When I use DALI to load images, the top1 accuracy is about 80.41 on validation set. However, when pytorch dataloader is used, it can only achieve 72.52. I think maybe it is the problem of interpolation, so I changed the interpolation of pytorch dataloader to BICUBIC instead of BILINEAR which is used by default. The top1 accuracy is a little bit better and becomes 74.57.

The codes of pytorch dataloader is

```
class Dset(torch.utils.data.Dataset):
      def __init__(self, img_folder,img_size=512, crop_size=448):
          
          self.img_size = img_size
          self.crop_size = crop_size
          self.img_folder = img_folder
          
          normalize = transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
          self.transform_test = transforms.Compose([
                             transforms.Resize(img_size),
                             transforms.CenterCrop(crop_size),
                             transforms.ToTensor(),
                             normalize
                             ])
          
          test_folder = os.path.join(img_folder)
          
          self.test_img_lst = []
          img_names = os.listdir(test_folder)
          img_names = sorted(img_names)
          
          for img_name in img_names:
              self.test_img_lst.append(os.path.join(test_folder,img_name))
              
      def __len__(self):
          return(len(self.test_img_lst))
          
      def __getitem__(self, idx):
          img = Image.open(self.test_img_lst[idx])
          img = img.convert('RGB')
          img = self.transform_test(img)
          
          return img,self.test_img_lst[idx]

test_dataset = Dset(img_folder,img_size,crop_size)
   
data_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle= False, num_workers=8, pin_memory=True)

for i, (img_tensor,img_name) in enumerate(data_loader):  
       
           img_tensor = img_tensor.cuda()
           
           output = model(img_tensor)
           
           _, pred = output.topk(top5, 1, True, True)
           pred = pred.squeeze().cpu().numpy()    
```        

The codes of pytorch dali tfrecords dataloader is as below. Resize is not used because for tfrecords data, all images are resized to 512x512 during the generation of tfrecords.

```
import os

from nvidia.dali.pipeline import Pipeline
import nvidia.dali.ops as ops
import nvidia.dali.types as types
import nvidia.dali.tfrecord as tfrec
from nvidia.dali.plugin.pytorch import DALIGenericIterator

import cv2
import numpy as np

class CommonPipeline(Pipeline):
    def __init__(self, 
                 batch_size, 
                 num_threads, 
                 device_id,
                 crop_size=448,
                 img_size=512,
                 randomFlip=True,
                 eps=1e-6):
        super(CommonPipeline, self).__init__(batch_size, 
                                             num_threads, 
                                             device_id)
                                             
        self.randomFlip = randomFlip
        self.eps = eps
        self.crop_size = crop_size
        self.img_size = img_size
        
        self.decode = ops.ImageDecoder(device = "mixed", output_type = types.RGB)
        self.cmn = ops.CropMirrorNormalize(device = "gpu",
                                            dtype = types.FLOAT)

        self.center_crop = ops.CropMirrorNormalize(device = "gpu",
                                            dtype = types.FLOAT,
                                            crop_w = crop_size,
                                            crop_h = crop_size,
                                            crop_pos_x = 0.5,
                                            crop_pos_y = 0.5,
                                            mirror = 0,
                                            mean = [123, 117, 104],
                                            std = [58.395, 57.12, 57.375])

        self.flip = ops.Flip(device = "gpu")

        self.coin = ops.CoinFlip(probability=0.5)

    def base_define_graph(self, inputs, labels):
        images = self.decode(inputs)

        if self.randomFlip == True:

           pos_x = np.random.uniform(low=0.0,high=0.99)
           pos_y = np.random.uniform(low=0.0,high=0.99)

           output = self.cmn(images,
                             crop_w = self.crop_size,
                             crop_h = self.crop_size,
                             crop_pos_x = pos_x,
                             crop_pos_y = pos_y,
                             mean = [123, 117, 104],
                             std = [58.395, 57.12, 57.375],
                             mirror = self.coin())
        else:
           output = self.center_crop(images)
                          
        return (output, labels)
        
class TFRecordPipeline(CommonPipeline):
    def __init__(self, tfrecord_path,
                       tfrecord_idx_path,
                       batch_size,
                       num_threads,
                       device_id,
                       crop_size=224,
                       image_size=256,
                       randomFlip=True,
                       random_shuffle=True,
                       initial_fill=10240):
        super(TFRecordPipeline, self).__init__(batch_size, num_threads, device_id,crop_size,image_size,randomFlip)
        self.input = ops.TFRecordReader(path = tfrecord_path,
                                        index_path = tfrecord_idx_path,
                                        features = {"image" : tfrec.FixedLenFeature((), tfrec.string, ""),
                                                    "label": tfrec.FixedLenFeature([1], tfrec.int64,  -1)
                                        },
                                        initial_fill=initial_fill,
                                        random_shuffle=random_shuffle)

    def define_graph(self):
        inputs = self.input(name="Reader")
        images = inputs["image"]
        labels = inputs["label"]
        return self.base_define_graph(images, labels)
```

I do not know what's wrong.

**Comment by JanuszL** [comment]
Hi,
It is a non-trivial problem to solve.
I would start by running the inference on a couple of images and check the scores for each of them.
The next thing that differs is the resize - I don't know how the images were resized to 512x512 during the generation of tfrecords. Maybe OpenCV was used or any other library that won't match what PyTorch can do.
The last thing is how images are decoded - there is no JPEG decoding gold standard, and mixed implementation yields a bit different results than CPU one (libjpeg-turbo uses a fancy upsampling - more about it [here](https://libjpeg-turbo.org/About/Performance).
Our experience shows that a network trained with one processing pipeline yields the best results inferred with the same data processing library.

**Comment by KleinXin** [comment]
> Hi,
> It is a non-trivial problem to solve.
> I would start by running the inference on a couple of images and check the scores for each of them.
> The next thing that differs is the resize - I don't know how the images were resized to 512x512 during the generation of tfrecords. Maybe OpenCV was used or any other library that won't match what PyTorch can do.
> The last thing is how images are decoded - there is no JPEG decoding gold standard, and mixed implementation yields a bit different results than CPU one (libjpeg-turbo uses a fancy upsampling - more about it [here](https://libjpeg-turbo.org/About/Performance).
> Our experience shows that a network trained with one processing pipeline yields the best results inferred with the same data processing library.

About the generation of tfrecords, images are first resized to 512x512 by using OpenCV with cubic interpolation and saved to local disk. Then tfrecords are generated by using those resized images.

The JPEG decoding method I used can be found in the codes above.

Hope this problem can be solved in a short time because the deadline of the competiton is coming soon. Other model that have better performance are also trained with DALI. I think meybe I do not have enough time to retrain those models.

Anyway, I will try to start retrain the model with pytorch dataloader.

**Comment by JanuszL** [comment]
> About the generation of tfrecords, images are first resized to 512x512 by using OpenCV with cubic interpolation and saved to local disk. Then tfrecords are generated by using those resized images.

I'm not sure if OpenCV resize is flip-invariant (resize(x) != flip(x)->resize(x)->flip(x)).

> The JPEG decoding method I used can be found in the codes above.

`Image.open` uses libjpeg-turbo (AFAIK), while `ops.ImageDecoder` uses nvJPEG.

> Hope this problem can be solved in a short time because the deadline of the competiton is coming soon.

I don't know if we can provide any other hints besides what I have already shared.

**Comment by KleinXin** [comment]
> > About the generation of tfrecords, images are first resized to 512x512 by using OpenCV with cubic interpolation and saved to local disk. Then tfrecords are generated by using those resized images.
> 
> I'm not sure if OpenCV resize is flip-invariant (resize(x) != flip(x)->resize(x)->flip(x)).
> 
> > The JPEG decoding method I used can be found in the codes above.
> 
> `Image.open` uses libjpeg-turbo (AFAIK), while `ops.ImageDecoder` uses nvJPEG.
> 
> > Hope this problem can be solved in a short time because the deadline of the competiton is coming soon.
> 
> I don't know if we can provide any other hints besides what I have already shared.

Looking forward for your good news！

**Comment by JanuszL** [comment]
Hi @KleinXin,

> Looking forward for your good news！

To be perfectly clear, we don't plan to look into that problem anytime soon. Please use the provided guidance to narrow down the problem on our end.

**Comment by KleinXin** [comment]
> Hi @KleinXin,
> 
> > Looking forward for your good news！
> 
> To be perfectly clear, we don't plan to look into that problem anytime soon. Please use the provided guidance to narrow down the problem on our end.

Never mind！I find that I can install DALI in jupyter notebook, so I want to use ops.FileReader to load and decode images by using image list. This the way I used DALI about half a year ago.

However, error reported which says

Traceback (most recent call last):
  File "test_dataset_dali_lst.py", line 66, in <module>
    testPipes.build()
  File "/usr/local/lib/python3.6/dist-packages/nvidia/dali/pipeline.py", line 481, in build
    self._pipe.Build(self._names_and_devices)
RuntimeError: Critical error when building pipeline:
Error when constructing operator: FileReader encountered:
[/opt/dali/dali/operators/reader/loader/file_label_loader.h:129] Assert on "s.is_open()" failed: Cannot open: ['001..jpg', '002..jpg', '003..jpg', ...]

Then I trace the error in your source code, the error occurs in dali/operators/reader/loader/file_label_loader.h line 129

![image](https://user-images.githubusercontent.com/13084622/118656761-68fe7100-b81d-11eb-91bb-f254d98ba232.png)

It seems the program failed to open the image list file. Then I copy the file to the current folder and it still fails. So I am sure it is not permission problem.

Any idea?

**Comment by KleinXin** [comment]
Problem solved by passing files and labels directly to FileReadPipeline.
It is a good idea to provide these two parameters.
thx

**Comment by KleinXin** [comment]
Until now, DALI can only be used to read images stored on local disk.
How about online use?
For example, first using urlopen to get binary data from the image url, then decode the data by using DALI？
Now I am using opencv to decode the data.
As discussed above, decoding standards of DALI and Opencv/PIL  are quite different. So if I train the model using DALI and use opencv or pillow to decode images online, the accuracy of the model will drop dramatically according to my experience.

Do you have any idea to solve this problem? @JanuszL 

thx

**Comment by JanuszL** [comment]
Hi @KleinXin,
I missed your previous question. Sorry.
I don't think that the format of your file list is correct. The error `['001..jpg', '002..jpg', '003..jpg', ...]` shows that the files you passed don't have an absolute path. You can check [this example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/expressions/expr_conditional_and_masking.html?highlight=file_list) to see how to use it.

> For example, first using urlopen to get binary data from the image url, then decode the data by using DALI？

I think you can use [the external_source operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/external_input.html) in that case as you have a custom load logic DALI doesn't cover yet.

**Comment by KleinXin** [comment]
> Hi @KleinXin,
> I missed your previous question. Sorry.
> I don't think that the format of your file list is correct. The error `['001..jpg', '002..jpg', '003..jpg', ...]` shows that the files you passed don't have an absolute path. You can check [this example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/expressions/expr_conditional_and_masking.html?highlight=file_list) to see how to use it.
> 
> > For example, first using urlopen to get binary data from the image url, then decode the data by using DALI？
> 
> I think you can use [the external_source operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/external_input.html) in that case as you have a custom load logic DALI doesn't cover yet.

You may misunderstand something. My problem was solved by giving absolute paths as you said.

Now we want to provide a web service in which circumstance what we get are image urls instead of paths of local disk.
I have a look at the link you gave. Maybe I can try to change those paths to urls and download the images in __next__ function.

The problem maybe that every time a request with image urls comes, a new external iter have to be constructed. 
I do not know if it is time and memory consuming.

**Comment by JanuszL** [comment]
> The problem maybe that every time a request with image urls comes, a new external iter has to be constructed.
I do not know if it is time and memory consuming.

This sounds like an inference use case. You may think about trying out [TRITON with DALI backend](https://github.com/triton-inference-server/dali_backend), the only thing you need to add is a lightweight client/backend that would download images from URL and send them to DALI.
If you want to do it the present way how about creating a queue and a thread that would wait for the user's request. The thread would receive them and pass them to the queue, the second end would be read by the external source function.
You can also set `exec_async` and `exec_pipelined` to false, and `prefetch_queue_depth` to 1.  Then when the request comes call `feed_input` method with the requested content and run the pipeline in a synchronous way.
