### ISSUE TITLE
CPU operation after GPU op

### ISSUE THREAD

**Issue by tarunn2799** [NVIDIA/DALI#2967]
Hey, 

As a part of my DALI augmentation pipeline, I'm currently at a point where I need to use `transforms.shear/scale/rotate` which are currently cpu only operations. 

Since they follow GPU ops, the pipeline throws an error. Is there any way by which I can shift the datanode to the cpu and perform a cpu op after a gpu op within my pipeline? Any hacky fixes that can do this for me are appreciated.

**Comment by JanuszL** [comment]
Hi @tarunn2799,

I'm sorry but this is one of DALI's hard limitations now. Can you tell more how your flow looks like, maybe this data can be placed on the CPU? Where the data to `transforms.shear/scale/rotate` cames from?

**Comment by tarunn2799** [comment]
Hey @JanuszL , thanks for the response. I figured that warpaffine works on the gpu, so I was still able to use the cpu functions as a part of my pipeline. 

Can DALI be installed as a CPU-only version for a machine? I have a DALI pipeline that does inference for my images, and it exists within a CPU only instance, so even the pipeline is cpu based. Is it possible for me to install DALI on this instance without the CUDA dependency?

**Comment by JanuszL** [comment]
Hi @tarunn2799,

> Can DALI be installed as a CPU-only version for a machine? I have a DALI pipeline that does inference for my images, and it exists within a CPU only instance, so even the pipeline is cpu based. Is it possible for me to install DALI on this instance without the CUDA dependency?

Yes, it should work. You need to pass `None` as a `device_id` and use CPU-only operators. You don't need to have a GPU driver (DALI doesn't depend on CUDA itself).

**Comment by tarunn2799** [comment]
Hey @JanuszL  so I tried installing the CUDA 10.2 pip installable version that's available on the website, and I get this error. 
I'm unsure whether python allows me to import DALI in my code. 
![image](https://user-images.githubusercontent.com/28048963/119015026-29b75800-b9b6-11eb-9df3-b31773d02b56.png)

**Comment by JanuszL** [comment]
Hi @tarunn2799,

Could you tell which python version do you have and which DALI version you managed to install?
Could you also provide a minimal, self-contained reproduction code we can run on our side?

I have run the following code and it works fine:
```
docker run --rm -ti ubuntu:18.04
apt update && apt install -y nano python3 python3-distutils python3-pip wget &&\
pip3 install --upgrade pip && 
pip3 install --extra-index-url https://developer.download.nvidia.com/compute/redist --upgrade nvidia-dali-cuda100 numpy &&\
pip3 install torch==1.8.1+cu102 torchvision==0.9.1+cu102 torchaudio===0.8.1 -f https://download.pytorch.org/whl/torch_stable.html

python3 -c "from nvidia.dali.plugin.pytorch import LastBatchPolicy"
```

**Comment by JanuszL** [comment]
OK, I see that is python 3.7. I don't see anything that could lead to this problem. Without repro code, I can't tell much.

**Comment by tarunn2799** [comment]
Hey @JanuszL , I tested the commands you gave on a different CPU instance and it worked!
Realized my initial environment had traces of a CUDA 9 installation in it, causing the issue. 

Tried it on a fresh instance and it worked. Thank you!

**Comment by JanuszL** [comment]
Hi @tarunn2799,

> Realized my initial environment had traces of a CUDA 9 installation in it, causing the issue.

As I understand you had an old DALI version that didn't support CPU-only mode. Otherwise, it is still very strange as it should have nothing to do about CPU instance or present CUDA installation.

**Comment by tarunn2799** [comment]
Actually, that makes more sense.  Reinstalling DALI on that same instance fixed it.
