### ISSUE TITLE
ImageRandomCrop broke after 1 epoch

### ISSUE THREAD

**Issue by macsmy** [NVIDIA/DALI#2975]
Hello, 
Ive noticed, that `nvidia.dali.ops.decoders.ImageRandomCrop` probably has implementation bug. 
If used for segmentation, after one epoch images and masks become misaligned. It can be clearly see below:
this it the loss over steps, after 1 epoch (around 9k step) loss increase
![image](https://user-images.githubusercontent.com/38138022/118796832-42334f80-b89c-11eb-9956-5a8e37bb3ebd.png)

**Comment by macsmy** [comment]
I use it in a standard way:
decode = ops.ImageDecoderRandomCrop(
            device=self.dali_devices.cpu_to_gpu,
            random_aspect_ratio=1.0,
            random_area=1.0,
        )
images, masks = decode([img_files, mask_files])
in the first epoch everything is just fine, the problems appears in the second epoch end later

**Comment by JanuszL** [comment]
That should work fine. Can you visually inspect samples and see if they are aligned (the content itself and the crop operation)?

**Comment by macsmy** [comment]
yeah, i can clearly see they are not (after the first epoch). the shift is vertical (for vertical images) or horizontal (for horizontal images), that is why I assume that this is the ImageDecoderRandomCrop bug. tested using both tf 1.15 and tf 2.4

**Comment by macsmy** [comment]
i've just checked, that using 'cpu' device for decoding (instead of 'mixed') the bug seems to be gone

**Comment by JanuszL** [comment]
If your masks are gay scale images there was a bug in how they were handled. Can you check the latest nightly build and see if that helps?
If not can you provide a minimal, self-contained repro we can run on our side (including test data - you can use https://github.com/NVIDIA/DALI_extra)?

**Comment by macsmy** [comment]
some of the masks are gray scale indeed. but how it explains, that the problem starts after 1 epoch? anyway, i will check the nightly build

**Comment by JanuszL** [comment]
> some of the masks are gray scale indeed. but how does it explain, that the problem starts after 1 epoch? anyway, i will check the nightly build

It does not (at least directly), but I want to explore all options first.

**Comment by macsmy** [comment]
let me just perform the last few experiments with 'cpu' decoding to ultimately confirm that problem disappears.

**Comment by JanuszL** [comment]
Still, I would very much appreciate a minimal repro to see why the `mixed` variant doesn't work.

**Comment by macsmy** [comment]
'mixed' mode bug confirmed. i will provide the code later today

**Comment by macsmy** [comment]
So the answer is not so straight as I though. 
Changing mixed to cpu only delayed misalignment (that is why I was pretty sure it is the proper solution), but in the end did not eliminate it. I run few other experiments, including decoding images and masks with `ImageDecoder` op followed by `RandomResizedCrop` op, but nothing seem to work. For smaller datasets experiments, which I ran to make debugging faster, however, the bug did not appear. Considering that fact I added `ops.Resize` with `resize_shorter` parameter to perform `RandomResizedCrop` on smaller images and - surprisingly - everything works correctly. 
It seems, that the problem is related to the Dali performance when operating on big datasets with quite large images size.

**Comment by JanuszL** [comment]
@macsmy - can you check if masks and images match regarding size? It may happen that there is a mask off by one regarding the size making RandomResizedCrop run more iterations trying to selected crop that matches constraints and making its internal state for images and labels out of sync.

**Comment by mzient** [comment]
@macsmy I recommend you to double check if this still happens when you set `seed` explicitly.

**Comment by JanuszL** [comment]
Hi @macsmy,
If it still doesn't work and you can provide a minimal and self-contained reproduction code please reopen.
