### ISSUE TITLE
how to do random Jitter with CoinFlip

### ISSUE THREAD

**Issue by ccthebest** [NVIDIA/DALI#30]
I find that the CropMirrorNormalize op has a 'Mirror' parameter for randomly applying mirror operation,  when it is used with the int tensor generated by the CoinFlip op.
But when I do the samething with the Jitter op it fails(use 'mask' parameter ):  
`RuntimeError: [/opt/dali/dali/pipeline/operators/op_spec.cc:56] Assert on "schema.HasArgument(arg_name)" failed: Argument mask is not part of the op schema`

So how to use the 'mask' parameter in ops like Jitter, Rotate?Or how to apply an augmentation randomly?

**Comment by ptrendx** [comment]
This is a bug in `HasArgument` function. I have a fix to this as part of a larger PR I'm working on.

**Comment by JanuszL** [comment]
Tracked internally in DALI-145
