### ISSUE TITLE
torch_python_function: exec_async & exec_pipelined

### ISSUE THREAD

**Issue by henrique** [NVIDIA/DALI#3005]
Similarly to #1824 I'd like to ask if there is any plan or possibility to speed up torch_python_function / DLTensorPythonFunctionImpl ?

It would be amazing if we could use general purpose and fully featured augmentation libraries like https://github.com/kornia/kornia for both GPU/CPU
or even https://github.com/albumentations-team/albumentations on CPU (through openCV)

I did some testing, but obviously torch_python_function/python_function becomes a major bottleneck to the loader.
Kornia on GPU (with batch_processing) is better, but still slows down the whole training about 20% on small models like resnet50

Anyway, thank you for the great work again.
We found DALI specially useful for loading tfrecords on PyTorch.

**Comment by henrique** [comment]
```
import kornia.augmentation as K
import nvidia.dali.plugin.pytorch as dalitorch

transform = torch.nn.Sequential(
    K.RandomRotation(p=0.8, degrees=30),
    K.RandomSolarize(p=0.5),
    K.RandomCutMix(p=0.5),
    # ...
)

def fn_transform(img):
    img = torch.stack(img).permute(0, 3, 1, 2)  # channels first "bCHW"
    return transform(img)
images = dalitorch.fn.torch_python_function(images, function=fn_transform,
                                            batch_processing=True,
                                            output_layouts="CHW",
                                            device='gpu' if gpu else 'cpu')
```
This is basically what I'm using to run it with Kornia.
Thanks

**Comment by JanuszL** [comment]
Hi @henrique,

The main problem why the Python-based operators have such limitations is the interleave of python code exaction in the main Python thread and DALI thread.
Dealing with it requires a more thorough examination of the current state of pybind11, how things work when Python 2.7 is not supported anymore, and a better understanding of python interpreter operation principles.
This feature was from the very beginning designed as a thing for rapid prototyping not a production-quality solution. Even if we can make it faster it still may be inferior to what DALI native operations provide.
We have this on our ToDo list but we cannot commit to any date. However, we would be more than happy to assist any community member willing to take this task.

**Comment by JanuszL** [comment]
Hi @henrique,

Now you can run the Python function in DALI in true asynchronous and pipelined mode.
