### ISSUE TITLE
Reading newly added data in file directory using fn.readers.file()

### ISSUE THREAD

**Issue by pshwetank** [NVIDIA/DALI#3006]
Hi DALI team,

I was experimenting with existing file reading methods in DALI like fn.readers.file( ). What I wanted to do is to prepare the list of frames that is to be read beforehand and then keep dumping those frames periodically in file directory. Problem is that when I run the DALI pipeline, I receive the error that file doesnt exist in directory even though they are being dumped periodically in that folder. 
Is there a way to modify this behavior so that it can keep reading the frames as they are dumped inside the directory? 

My use case is in this way: FFMPEG will be reading the frames from a video stream and keep dumping the frames in predefined name format like [1.jpg, 2.jpg, 3.jpg.....etc] and we will initialise fn.readers.file() with already a list with such names. Then, once there are sufficient frames dumped in directory, we can start churning the batches simultaneously. 

Please let me know if such use case is possible or not.

Thank you.

**Comment by JanuszL** [comment]
Hi @pshwetank,

File reader discovers files available only once, during pipeline initialization, so when you add new files they won't be read.
What you can do is to use [the external source operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/external_input.html) to either read data or even run FFmpeg there.
Please check the `parallel` and `prefetch_queue_depth` options and use them to improve the performance.

**Comment by pshwetank** [comment]
Thanks @JanuszL . This was indeed very helpful.
