### ISSUE TITLE
Segfault in libdalioperators.so

### ISSUE THREAD

**Issue by dwrodri** [NVIDIA/DALI#3015]
I have a computer vision pipeline where I pull videos from remote storage, preprocess them with DALI, and feed them into a PyTorch model.

Here is the error message retrieved using `dmesg -T`:
```
[Thu Jun  3 22:38:28 2021] python[26597]: segfault at 100 ip 00007f3c6b7eb8e3 sp 00007ffc55e1b2f0 error 4 in libdali_operators.so[7f3c69106000+133db000]
[Thu Jun  3 22:38:28 2021] Code: ad 38 02 00 00 4d 39 ec 74 4e 0f 1f 44 00 00 49 8b 14 24 49 8b 5c 24 08 48 39 d3 74 32 49 89 d6 0f 1f 80 00 00 00 00 49 8b 06 <48> 8b b8 00 01 00 00 48 85 ff 74 10 e8 9c f8 70 00 85│
 c0 41 89 c7
 ```
 
 Unfortunately, I am still tracking down a specific Python code sequence which is causing this bug. I've got the fault handler enabled now in my Python runtime, so hopefully I'll update this with more info.
 
 Environment:
 - Python 3.8.5
 - DALI 1.2.0
 - CUDA 11.1 
 - Nvidia Driver version 450.80.02

**Comment by JanuszL** [comment]
Hi @dwrodri,
This error comes from the native DALI side. Without a minimal, self-contained reproduction example we can run on our side I don't think we would be able to fix this problem.
Please provide one if possible.

**Comment by JanuszL** [comment]
Hi @dwrodri,
If it still doesn't work and you can provide a minimal and self-contained reproduction code please reopen.
