### ISSUE TITLE
NVJPEG error 4

### ISSUE THREAD

**Issue by sosherio** [NVIDIA/DALI#306]
When I use Dali on a relatively large data set (a couple of hundred thousand images), I ran into the following error. However, when I ran the same code on a smaller data set (a few thousands), it works just fine. I suspect that it breaks in the case of having a large data set because some of the images may be somehow broken (all are jpeg), but I was wondering if there is a way to ask Dali to ignore such cases.

```
RuntimeError: Critical error in pipeline: Error in thread 0: [/opt/dali/dali/pipeline/operators/decoder/nvjpeg_decoder.h:349] NVJPEG error "4"
Current pipeline object is no longer valid.
```

**Comment by JanuszL** [comment]
Hi,
Which version of DALI do you use?
In DALI 0.5 we will add more verbose logging pointing you to exact file which causes this problem.
Tracked as DALI-365.

**Comment by JanuszL** [comment]
It is https://github.com/NVIDIA/DALI/blob/v0.4.0/dali/pipeline/operators/decoder/nvjpeg_decoder.h#L349. So nvJPEG already determined after parsing header that this file is supposed to be supported.
Please rerun after 0.5 is released and check if you are able to open and display this faulty jpeg in any image viewer. If so it would be good if you can share it for the debugging purpose.

**Comment by ghop02** [comment]
I ran into this problem also. I have a clunky way of removing the bad images, but it's good to see that debugging will be easier.  I'll post any update if I find out more.

**Comment by sosherio** [comment]
@JanuszL 
Sure, I will rerun it once the new version is released and post the result here.

**Comment by sosherio** [comment]
@JanuszL 

Just a quick update after running my code using Dali 0.5: I was able to see the faulty images in the error message this time and remove them from my database. Thanks.
I was also able to open them (I tried two of them) with the preview application on Mac.

**Comment by ptrendx** [comment]
Would it be possible for you to share those images with DALI and nvJPEG team?

**Comment by sosherio** [comment]
@ptrendx 
Sure, [here](https://drive.google.com/open?id=10mknBWnBprMfods45TrNgB5JiY-tLSUb) is the link to the images that caused this error.

**Comment by JanuszL** [comment]
@sosherio - thanks, we will check them with the nvJPEG team.

**Comment by JanuszL** [comment]
@sosherio - #365 should address this issue.

**Comment by sosherio** [comment]
@JanuszL - Cool, thanks!

**Comment by GY0913** [comment]
can these 'bad' images be ignore?

**Comment by JanuszL** [comment]
@GY0913 - not with the present DALI architecture. The pipeline is working only one way: read data->decode->process->output, and it works for the whole batch of data. When decoding fails for one image there is no mechanism to tell previous step (in this case data loader) to provide one more sample to replace one that decoder cannot handle. What is possible to do it to pad this faulty sample with 0 or other preselected value but I don't know if the user expects this behavior.
In case of other data processing frameworks, it works like that because they process one sample at the time and only at the very end the batch is formed, so when one sample is discarded another one could replace it at the very last operator.

**Comment by GY0913** [comment]
@JanuszL so what kind of image  is decoder cannot handle, i try to check my dataset before training,but there still a lot 'bad' image left

**Comment by JanuszL** [comment]
@GY0913 what DALI supports now are:
- JPEGs
- BMP
- PNM
- PNG
- TIFF
Only decoding JPEGs is accelerated on GPU, while other formats silently are falling back to the CPU implementation. Nevertheless, they should work.
If you have some valid image (not corrupted and you can display it in any viewer), in supported format (no GIF with .jpeg file name) and DALI reports some error please let us know and provide this sample image so we can investigate the problem you have.

**Comment by GY0913** [comment]
@JanuszL when setting batch=1 ,can we have a test mode that can return  the path of bad images and  process next ? if the image is not corrupted and can display it in any viewer ,it is hard to pick up the bad sample one by one

**Comment by JanuszL** [comment]
@GY0913 - it would require a couple of things - first of all you would need to store somehow in the decoder what image failed and then create some feedback loop to the reader with the list of faulty images. While I see it possible for the decoder (we are carrying on the names of the files so decoder could return meaningful error with the filename in the message), I don't know how to create this feedback loop reasonably with all the architecture DALI is based on.
What I would prefer is to fix support for image formats that currently doesn't work in DALI than to spend time adding workarounds with skipping images.

**Comment by GY0913** [comment]
@JanuszL thank you very much !

**Comment by JanuszL** [comment]
@GY0913 - if you have any image that doesn't work for you feel free to share it, so we can check there the problem is.
