### ISSUE TITLE
Inference Video Pipeline for Action Recognition

### ISSUE THREAD

**Issue by psandev** [NVIDIA/DALI#3072]
Hi,
I was not able to find any example of video inference with dali.  Can you point me to some? If there is none, would you please, suggest an alternative GPU pipeline? Thanks a lot.
Another question: How do I create a pipeline for an unlabeled video? So far I am not able to.

**Comment by JanuszL** [comment]
Hi @psandev,
You can start from [this example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/use_cases/video_superres/README.html), although DALI doesn't work with video stream but only a predefined set of files. You can also check [DeepStream](https://developer.nvidia.com/deepstream-sdk) to see if that works for you.

To load video without labels just use the `filenames` argument and skip `labels` in [the `video` reader operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.readers.video).
