### ISSUE TITLE
Device incompatibility when trying to get image shapes from batch

### ISSUE THREAD

**Issue by dariodematties** [NVIDIA/DALI#3073]
Hi there!

I have a pipe in which I use

```
self.get_shape = ops.PeekImageShape(device = "cpu", preserve = True)
self.slice = ops.Slice(device = "gpu", preserve = True)

```
in the pipe initialization.
Then I use

```
shapes = self.get_shape(images)
w = self.slice(shapes, 1, 1, axes=[0])  # extract width
h = self.slice(shapes, 0, 1, axes=[0])  # extract height

```
inside `define_graph`

I want to use w and h to properly crop images in the batch

I receive the following error message

`Assert on "input_device == "cpu"" failed: cpu/mixed ops can only take cpu inputs. CPU op cannot follow GPU op. (op: 'PeekImageShape', input: '__ExternalSource_6')`

What could be happening here?

Thanks!

Dario

**Comment by JanuszL** [comment]
Hi,
It means that images are on the GPU while `PeekImageShape` expects them on the CPU. Also, this operator is meant to operate on raw, encoded images, while I believe in your case the data is decoded already.
For decoded images please use [`shapes` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.shapes) - in this case, the input needs to be located on the CPU as well if you want to have CPU output you want to use as an argument for image slice operator.

**Comment by dariodematties** [comment]
Thanks @JanuszL, I need my images on GPU, isn't there a way to get images shape directly on gpu?
An alternative could be to bring images on cpu and after obtaining their shapes moving them to gpu.
Two questions regarding this:
1_ How to do it?
2_ Could it be expensive?

Thanks!

Dario

**Comment by JanuszL** [comment]
Hi @dariodematties,

It is not possible to get the data back to the CPU from the GPU in the middle of the pipeline. What you can do is have them on the CPU, obtain shapes and then move to the GPU.

**Comment by dariodematties** [comment]
Thank you @JanuszL , I will proceed as you suggest. It is possible to use the shape of the images in a batch (i.e. w and h) to crop them individualy afterwards in one crop operation, isn't it?
Something like this: once I have two vectors of batch size (w and h) then I would like to do
`self.crop(images, crop_pos_x=crop_pos_x, crop_pos_y=crop_pos_y, crop_h = h*0.1, crop_w = w*0.1)
`Can I do that?
Thanks!
Dario

**Comment by JanuszL** [comment]
In this case please use [the `slice`](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.slice) operator where you can provide the anchor and the shape per each image separately.

**Comment by dariodematties** [comment]
Thank you @JanuszL !
