### ISSUE TITLE
Speed up dataset loading in DALI with pytorch lightning

### ISSUE THREAD

**Issue by nickKyr** [NVIDIA/DALI#3081]
Hello,

I am trying to add DALI in my pytorch lightning workflow in order to load faster my dataset, which is in numpy format (.npz files). Following the online examples, I employed a pipeline and then a DALIGenericIterator to load the samples. However, the time needed for each epoch is now larger, not significantly, than the time recorded in a previous training, where the default pytorch dataloader was used. As I am not quite certain that the process is the suggested one for loading numpy arrays in DALI, so I attach the code below for reference. Is a speed-up expected in such cases? Is there a similar example available, apart from loading JPEG files? 

I found a similar issue ([#2645](https://github.com/NVIDIA/DALI/issues/2645)), but when I tried to add the arguments `parallel=True, batch= False` in `fn.external_source ` as suggested, I get the following error:

_RuntimeError: Cannot fork process when there is CUDA context bound to it. Make sure you build pipeline before CUDA context is acquired or change Python workers starting method from ``fork`` to ``spawn`` (see Piepline's ``py_start_method`` option). If you are trying to build multiple pipelines that use Python workers, you will need to call ``start_py_workers`` method on all of them before calling ``build`` method of any pipeline._

I am not sure that I can decouple the pipeline from CUDA, as when you create the trainer, you specify the number of GPUs: `trainer = pl.Trainer(gpus=1)`.

Thanks,
Nikos

samples loader:
```
import nvidia.dali.fn as fn
from nvidia.dali.plugin.pytorch import DALIGenericIterator
from nvidia.dali import ops
from nvidia.dali.pipeline import Pipeline

class samplesIterator(object):
    def __init__(self, mode, batch_size):
        if mode=="train":
            files = os.listdir(trainDataDir)
            files.sort()
            random.shuffle(files)
            self.path = trainDataDir
            trainLength = len(files) - min( int(len(files)*0.2) , 400)
            self.validFiles = files[trainLength:]
            self.files = files[:trainLength]
        elif mode=="test":
            self.files = os.listdir(testDataDir)
            self.files.sort()
            self.path = testDataDir
        elif mode=="predict":
            self.files = os.listdir(aiOutputDir +"predict/") 
            self.files.sort()
            self.path = aiOutputDir +"predict/"

        self.totalLength = len(self.files)
        self.batch_size = batch_size

    def __iter__(self):
        self.i = 0
        self.n = len(self.files)
        return self

    def __next__(self):
        inputs = []
        targets = []
        names = []
        for _ in range(self.batch_size):
            npfile = np.load(self.path + self.files[self.i] )
            d = npfile['a']
            inputs.append(d[0:ninput])#ninput=1
            targets.append(d[0:ntotal])#ntotal=ninput+noutput=1+4=5
            names.append( self.files[self.i].split('.npz')[0] )
            self.i = (self.i + 1) % self.n
        return (inputs, targets)


class samplesIteratorValid(samplesIterator):
    def __init__(self, iter):
        self.files = iter.validFiles
        self.batch_size = iter.batch_size
        self.path = iter.path
        self.totalLength = len(self.files)

    def __iter__(self):
        self.i = 0
        self.n = len(self.files)
        return self

    def __next__(self):
        inputs = []
        targets = []
        names = []
        for _ in range(self.batch_size):
            npfile = np.load(self.path + self.files[self.i] )
            d = npfile['a']
            inputs.append(d[0:ninput]) 
            targets.append(d[0:ntotal])
            names.append( self.files[self.i].split('.npz')[0] )
            self.i = (self.i + 1) % self.n
        return (inputs, targets)


class DALInetwork(network):

    def __init__(self, netDims, mode=None, levels=levels):
        super(DALInetwork, self).__init__(netDims, mode, levels)

    def setup(self, stage=None):
        if stage == 'fit':
            self.train_iter = samplesIterator("train", batch_size)
            self.valid_iter = samplesIteratorValid(self.train_iter)
        if stage == 'test':
            if self.mode=="test":
                self.test_iter = samplesIterator("test", 1)

    def train_dataloader(self):
        pipe = Pipeline(batch_size=batch_size, num_threads=8, device_id=0)
        with pipe:
            inputs, targets = fn.external_source(source=self.train_iter, num_outputs=2, parallel=True, batch= False)
            pipe.set_outputs(inputs, targets)
        pipe.build()         
        dbldr = DALIGenericIterator(
                                    pipe,
                                    output_map=["inputs", "targets"],
                                    size=self.train_iter.totalLength,
                                    #reader_name="reader",
                                    auto_reset=True,
                                    last_batch_policy=False
                                    )
        return dbldr

    def val_dataloader(self):
        pipe = Pipeline(batch_size=batch_size, num_threads=8, device_id=0)
        with pipe:
            inputs, targets = fn.external_source(source=self.valid_iter, num_outputs=2)
            pipe.set_outputs(inputs, targets)
        pipe.build()
        dbldr = DALIGenericIterator(
                                    pipe,
                                    output_map=["inputs", "targets"],
                                    size=self.valid_iter.totalLength,
                                    #reader_name="reader",
                                    auto_reset=True,
                                    last_batch_policy=False
                                    )
        return dbldr

    def test_dataloader(self):
        pipe = Pipeline(batch_size=batch_size, num_threads=4, device_id=0)
        with pipe:
            inputs, targets = fn.external_source(source=self.test_iter, num_outputs=2)
            pipe.set_outputs(inputs, targets)
        pipe.build()  
        dbldr = DALIGenericIterator(
                                    pipe,
                                    output_map=["inputs", "targets"],
                                    size=self.test_iter.totalLength,
                                    #reader_name="reader",
                                    auto_reset=True,
                                    last_batch_policy=False
                                    )
        return dbldr
```

**Comment by klecki** [comment]
Hi, @nickKyr,
you can try setting `py_start_method='spawn'` for the Pipeline, this is different method of launching the workers that doesn't interfere with CUDA. But the idea behind parallel External Source is similar to Pytorch distributed data loader (worker Python processes that load the data).

Also, as you are loading numpy data, did you know, that we have a dedicated, native, [Numpy Reader](https://docs.nvidia.com/deeplearning/dali/main-user-guide/docs/supported_ops.html#nvidia.dali.fn.readers.numpy). It might be faster than the external source method.

As far as I can see, the example you shared is doing only the loading. In all cases, you will be limited by the speed of the IO. The Pytorch DDP, parallel External Source and Numpy Reader can only parallelize that reading from disc to memory, so I expect the results to be mostly similar. There are no augmentations that DALI can speed up & overlap with other compute.

**Comment by JanuszL** [comment]
Hi @nickKyr,

Small correction,
>Also, as you are loading numpy data, did you know, that we have a dedicated, native, Numpy Reader. It might be faster than the external source method.

If you load `npz` files, DALI's [Numpy Reader](https://docs.nvidia.com/deeplearning/dali/main-user-guide/docs/supported_ops.html#nvidia.dali.fn.readers.numpy) won't help as it supports only raw numpy files, noncompressed one.

**Comment by nickKyr** [comment]
Hi,

thank you both for your feedback. I will check `py_start_method='spawn'` and the `nvidia.dali.fn.readers.numpy`, even if it may not be applicable in my case.

Cheers,
Nikos

**Comment by jalola** [comment]
Hi @klecki and @JanuszL ,

Do you have a concrete example for `py_start_method='spawn'`? It would be very great for us. I tried it but it says my Iterator's callback cannot be pickled.

Thanks,
Hung

**Comment by JanuszL** [comment]
Closing as stalled.
