### ISSUE TITLE
 NVJPEG error "4" : NVJPEG_STATUS_JPEG_NOT_SUPPORTED on A100, but works on V100

### ISSUE THREAD

**Issue by melgor** [NVIDIA/DALI#3084]
Hi, I encounter the error while reading my dataset after switching GPU from **V100** to **A100** on exactly the same software stack (GCP instance):
OS- Ubuntu
CUDA: NVIDIA-SMI 450.80.02    Driver Version: 450.80.02    CUDA Version: 11.0
DALI: 1.1
Pytorch: 1.7.1

I upload the minimal example to reproduce (use old API, but on a new one I also face the same problem). Last time you did advise me that I should upgrade to CUDA 11.1 what is the option for me, but need additional work. Also, I check that when I read and write the images using OpenCV, then those images works also at A100 (so look like it the JPEG coding problem?).

But my main concern is that the decoding does not work in the same way in V100 and A100 what does not give as-needed flexibility.

Example image:
![6e83485f4aad83bab23eba8b2c7d_TH](https://user-images.githubusercontent.com/2587438/123219781-92ba5000-d4cd-11eb-9ab7-fd90678fd698.jpeg)

[minimal_example_SIGSEGV.zip](https://github.com/NVIDIA/DALI/files/6707130/minimal_example_SIGSEGV.zip)

**Comment by JanuszL** [comment]
Hi,
I can confirm the bug. https://github.com/NVIDIA/DALI/pull/3086 should fix that.
Please check the nightly build that follows the merge of it or the next release (1.4 most probably).

**Comment by melgor** [comment]
I have a question about HW decoder. So when I would set 
```
ops.ImageDecoder(device = "mixed", output_type = types.RGB, hw_decoder_load=0.0)
```
then above error should not occur as HW decoder would not get any images to decode, right? As the above error is caused by HW.

Because in my case, in the above settings, the problem still occurs.

**Comment by JanuszL** [comment]
Hi @melgor,

The issue happens before the `hw_decoder_load` value is applied. First DALI parses all images in the batch to know how many of them can be offloaded to HW decoder, or hybrid decoder, or need to be processed by CPU. After then numbers are adjusted depending on the load. The problem happens during the parsing.
I don't think there is much you can do besides waiting for the nightly build with the fix.

**Comment by melgor** [comment]
Thanks, I was just thinking that in case when I turn off HW decoder, the error should not occur, what would mean another bug. But it is not the case. Thanks for helpl

**Comment by melgor** [comment]
Hi. I installed nightly version of dali ('1.4.0dev.20210630') but the new one occurs now.
```
RuntimeError: Critical error in pipeline:
Error when executing Mixed operator ImageDecoder encountered:
[/opt/dali/dali/operators/decoder/nvjpeg/nvjpeg_decoder_decoupled_api.h:803] NVJPEG error "3" : NVJPEG_STATUS_BAD_JPEG
```
In the attachment, there is code and images which raise this error.
Also, I noticed that when `hw_decoder_load` is turned-off (hw_decoder_load=0.0) then everything works properly. 
[minimal_example_SIGSEGV.zip](https://github.com/NVIDIA/DALI/files/6747318/minimal_example_SIGSEGV.zip)
![2fa9f96445e583784c23b911cfe9_TH](https://user-images.githubusercontent.com/2587438/124106608-a4b76800-da64-11eb-8f0d-54fd4824ed65.jpeg)

**Comment by JanuszL** [comment]
Hi @melgor,

It seems that problem is raised during the decoding itself. Let us check it and get back to you.

**Comment by JanuszL** [comment]
@melgor,

In non A100 GPU, I see it reports `Premature end of JPEG data.` so it means that the decoding fallbacks to the CPU which is more error-resilient in this case. I need to check if we can provide a similar fallback for the A100 HW decoder.

**Comment by JanuszL** [comment]
Hi @melgor,

https://github.com/NVIDIA/DALI/pull/3113 should fix the problem. Again please check the nightly build that follows the merge of the mentioned PR.

**Comment by melgor** [comment]
Any reason why there is not nightly-build from 2021-07-06 (yesterday?) 

Current version is `nvidia_dali_nightly_cuda110-1.4.0.dev20210705`

**Comment by JanuszL** [comment]
@melgor,

Sometimes the nightly build fails and we are not posting it (either a bug in DALI or in the test environment).
I hope there will be one today.

**Comment by melgor** [comment]
I checked the nightly build from 2021-07-07.  Everything works. Thanks for your help!
