### ISSUE TITLE
Video decoder determining its own size

### ISSUE THREAD

**Issue by TobiFisch** [NVIDIA/DALI#3087]
Hi, 

I am experimenting with DALI to decode videos to the GPU for efficient inference of a pytorch model. I can successfully load videos at the hw decoder speed limit. However the pipeline loops the video instead of stopping once the video ends. I read the documentation and don't see any API to let the video decoder stop once the video ends.

I can provide a [colab notebook](https://colab.research.google.com/drive/1ufOndAbqQQ6jerDox3hvA9iCqvIXByLR#scrollTo=8mqG1mDKr7Yd) to reproduce the behavior.  The core idea is:

```python
from nvidia.dali import pipeline_def
import nvidia.dali.fn as fn
from nvidia.dali.plugin.pytorch import DALIGenericIterator

@pipeline_def
def video_pipe(filenames):
    return fn.readers.video(device="gpu", filenames=filenames, sequence_length=64)

pipe = video_pipe(batch_size=1, num_threads=1, device_id=0, filenames=["test_video.mp4"])
pipe.build()

dali_iter = DALIGenericIterator([pipe], ["image"])

for data in dali_iter:
    pass  # this will loop forever, repeating the video. I would like to stop once the video is over
```

The function `nvidia.dali.fn.readers.video()` does not seem to have a total size argument. That makes sense to me, since in order to know how long a video is one actually needs to decode it.

`DALIGenericIterator` has a `size` argument, but as stated the video size cannot be determined without decoding it fully. Also, the docs state: `Providing -1 [this is the default value as well] means that the iterator will work until StopIteration is raised from the inside of iter_setup()`. Ther is also `reader_name`, which seems to be necessary for knowing the size? The docs state: `Name of the reader which will be queried to the shard size, number of shards and all other properties necessary to count properly the number of relevant and padded samples that iterator needs to deal with.`

I would expect, that the video reader raises some kind of exception once the video ends, signaling the `DALIGenericIterator` to stop. Providing the reader name seems insufficient, because the video length cannot be determined a priori.

I would appreciate any insights on this topic :) If this is not the right place for such questions, please direct me to the correct contact point.

**Comment by JanuszL** [comment]
Hi @TobiFisch,

You can query the DALI pipeline for the reader's size using [`reader_meta`](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/pipeline.html#nvidia.dali.Pipeline.reader_meta) method.
The reader itself doesn't have such property as it is just a symbolic entry in the graph of operation, that is instantiated when the pipeline is built.

What you should do is just use the `reader_name` argument of the iterator.
```
from nvidia.dali import pipeline_def
import nvidia.dali.fn as fn
from nvidia.dali.plugin.pytorch import DALIGenericIterator

@pipeline_def
def video_pipe(filenames):
    return fn.readers.video(device="gpu", filenames=filenames, sequence_length=64, name="my_reader")

pipe = video_pipe(batch_size=1, num_threads=1, device_id=0, filenames=["test_video.mp4"])
pipe.build()

dali_iter = DALIGenericIterator([pipe], ["image"], reader_name="my_reader")

for data in dali_iter:
    pass  # this will loop forever, repeating the video. I would like to stop once the video is over
```

`Providing -1 [this is the default value as well] means that the iterator will work until StopIteration is raised from the inside of iter_setup()` - it is mostly meant for the external source implementation. Other operators don't raise them as they have native, not python implementation.

> because the video length cannot be determined a priori.

The video reader operator queries video for the number of frames - so it knows when the pipeline is built.

**Comment by TobiFisch** [comment]
Hi @JanuszL 

that works perfectly, thanks a lot! Also for the swift response :)

Could you by chance point me to the frame counting implementation in DALI? This could be relevant to our pipeline as well, outside of the whole deep learning machinery. I have little experience with that and it could be a good reference. This is not related to the original issue though.

**Comment by JanuszL** [comment]
Hi @JanuszL,

You can find it in:
- https://github.com/NVIDIA/DALI/blob/main/dali/operators/reader/loader/video_loader.h#L237
- https://github.com/NVIDIA/DALI/blob/main/dali/operators/reader/loader/video_loader.h#L219
- https://github.com/NVIDIA/DALI/blob/main/dali/operators/reader/loader/video_loader.cc#L267
- https://github.com/NVIDIA/DALI/blob/main/dali/operators/reader/loader/video_loader.cc#L390

```
    file.frame_count_ = av_rescale_q(duration,
                                     stream->time_base,
                                     file.frame_base_);
```
We are using FFmpeg project libraries to access this data directly from the container.

**Comment by TobiFisch** [comment]
Thank you, that is quite insightful.

I just noticed the following, but that is most probably intended behavior:
The video reader produces sequences of frames, and the generator batches them together. Our inference uses single images only and does not require temporal information, so I can either use the sequence length to load batches, or tell the generator to batch. Abusing the sequence length as the batching mechanism is much more performant for some reason. However it will discard the last few frames, and not produce a shorter sequence in the end.

It does not really matter though, since we infer on hours of video, and a few missing seconds in the end are not that important. If there is a solution for that, I would take it though :)

**Comment by JanuszL** [comment]
Hi @TobiFisch,

Yes, abuse of the sequence length would be faster, as the video reader seeks the first frame for each sample and decode consecutive one. When the length is 1 you have batch size seeks, when you have batch size 1 you have one seek per each sequence.
Also just recently we merged - https://github.com/NVIDIA/DALI/pull/3002 which allows you to pad the last sequence to read all from the video. You can check the most recent nightly build or wait for the 1.4 release.

**Comment by TobiFisch** [comment]
Cool, what a timing! Thank you for the guidance and the swift and friendly interaction. I have no more questions :)
