### ISSUE TITLE
Could DALI skip reading and decoding the unsupported format image in pipeline instead of raising an error?

### ISSUE THREAD

**Issue by haoxintong** [NVIDIA/DALI#309]
### 1
I use DALI loading a MXNet .rec dataset of about 7M images with some broken image  (it is 0-sized image actually in my case).

Although I have built #303, when the Iterator try to load these broken images,  it raised `RuntimeError` as below, and **the pipeline is no longer valid**:

```
RuntimeError: Critical error in pipeline: [/.../nvjpeg_decoder.h:204] Unsupported image format.
Current pipeline object is no longer valid.
```
I checked the changes in #303, and found in [dali/pipeline/operators/reader/loader/recordio_loader.h#L62](../blob/master/dali/pipeline/operators/reader/loader/recordio_loader.h#L62) use `size = temp[i + 1] - temp[i]` as image size. But from `mxnet/tools/im2rec.py`, the offsets in `train.idx` include the header size, which means size computed by `temp[i+1]-temp[i]` can not get 0 then never skip `push_back` 0-sized images.

### 2
When using MXnet dataloader, if the next image is broken, I use this code to choose another image.
```python
 def __getitem__(self, idx):
        while True:
            record = super().__getitem__(idx)
            header, img = recordio.unpack(record)
            if _check_valid_image(img):
                decoded_img = image.imdecode(img, self._flag)
            else:
                idx = np.random.randint(low=0, high=len(self))
                continue
            return decoded_img, header.label

def _check_valid_image(s):
    return False if len(s) == 0 else True
```
This works well for me, so could DALI make the pipeline still valid when the format is unsupported?

**Comment by yaysummeriscoming** [comment]
I've also had some troubles with this, this would be a great feature.  Returning the offending image name would also be nice

**Comment by JanuszL** [comment]
Hi,
It is not that simple to ask DALI to skip corrupted image as DALI works in the pipeline model. The main problem I see now is that the reader will report more images available that there is a valid one, so if you have N images, but only N-x is valid, then the reader will need to duplicate x images to still provide you N of them. This constraint exists because we first parse dataset then load each file one by one in the runtime. So during parsing, we learn how much of them are available - `epoch_size()`, and this values is used to determine how much iterations we need to do during each epoch.
I made #313 so when idx is created corrupted images are skipped. Another possibility is to validate the whole dataset when the pipeline is built but it may take a lot of time and hit the performance.

**Comment by yaysummeriscoming** [comment]
Fair enough, perhaps it's possible to create a flag to allow the user to validate the dataset on pipeline construction?  Then you could run it once on dataset creation, which is where I had a problem with an image.  Turns out one of the images had somehow become corrupted during preperation.

**Comment by PistonY** [comment]
@JanuszL I suggest that validate the whole dataset when the pipeline is build,it take a lot of time only the first time,and you can give us a flag in interface made us choose use it or not.Some of the dataset may not have error image but others it may got better performance.

**Comment by haoxintong** [comment]
@JanuszL Hi, 
There's still problem in #313, because when packing special labels (like multi label array or mask images) , mxnet will put this kind of label encoding after the header as below:
```python
  if isinstance(header.label, numbers.Number):
        header = header._replace(flag=0)
    else:
        label = np.asarray(header.label, dtype=np.float32)
        header = header._replace(flag=label.size, label=0)
        s = label.tostring() + s
    s = struct.pack(_IR_FORMAT, *header) + s
```
We can change the condition:
```python
    _, s = mx.recordio.unpack(cont)
    # if len(cont) <= mx.recordio._IR_SIZE:
    if len(s) == 0:
        counter = counter + 1
        continue
```
And in my `train.idx`, the result of ` temp[i + 1] - temp[i]` is 40 for empty images. So I use `if (size > 100) ` to skip them rather than `if (size)`.  

But all these things can only solve the empty image problem, if there are unsupported format or corrupted images (not 0-sized), I have to decode the images in `rec2idx.py` and check, which will take a lot of time.

**Comment by JanuszL** [comment]
Hi,
The idea to run the pipeline and validate it is also not that simple. We need some way to provide feedback from the end of the pipeline to the reader to let it know which images skip.
We will think how to include this into current design, in the meantime please try to repair your data set.

**Comment by PistonY** [comment]
Hi@JanuszL ,does DALI support mxnet-gluon dataset format to read images,which means you do not use .rec file but straight load images with defined imgage path and length of all images.
For more details you can have a look [this].(https://github.com/apache/incubator-mxnet/blob/38eeb0c20333fa065941204523ba881c8c01ad44/python/mxnet/gluon/data/dataset.py#L29)
In another word, you can expose interface like that so we could check out image by ourselves.

**Comment by JanuszL** [comment]
Hi,
@PistonY - as I see mxnet-gluon dataset is an interface, not the format itself. If you want to check images on your self I think it is enough to build a pipeline with the only loader inside and check what kind of data it returns - if any tensor inside the returned tensor list is empty it means that your image doesn't contain any data.
If you want to work with separate images, not the RecordIO - please use FileReader operator.
