### ISSUE TITLE
file_list - the parameters of ops.FileReader

### ISSUE THREAD

**Issue by zhengge** [NVIDIA/DALI#31]
|   - `file_list` : `string`
 |        Path to the file with a list of pairs ``file label``
 |        (leave empty to traverse the `file_root` directory to obtain files and labels) (default value: ``)

self.input = ops.FileReader(file_root='images/kitten', file_list='file_list.txt') is wrong.
The 'file_list.txt' is 

> cat_9.jpg kitten
> cat_1.jpg kitten

`RuntimeError: [XXXXX/DALI/dali/pipeline/operators/reader/loader/file_loader.h:104] Assert on "Size() > 0" failed: No files found.`
Could you give me a example of file_list?
Thanks!

**Comment by JanuszL** [comment]
Hi,
file_list expects following format:
file_name_N[string] label_M[int]
Please try:
cat_9.jpg 0
cat_1.jpg 0
We will add more sanity check logic to the data loader and extend documentation as well.

**Comment by makslevental** [comment]
@JanuszL i'm trying to load files (jpegs) and i don't care about labels. i've supplied file_list 

```python
        file_list = glob.glob(os.path.join(data_dir, "*.jpg"))
        file_list = list(zip(file_list, range(len(file_list))))
```

and i get 

```
RuntimeError: [/opt/dali/dali/pipeline/operators/reader/loader/file_loader.h:97] Assert on "s.is_open()" failed
```

which is [here](https://github.com/NVIDIA/DALI/blob/master/dali/pipeline/operators/reader/loader/file_loader.h#L97)

not sure why the `ifstream` would fail to open? any ideas?

**Comment by austinmw** [comment]
Hi, @JanuszL I'm trying to use a file list with subdirectories that represent different videos, for example:

```
11-EO.mp4_0/11-EO.mp4_0-001.jpg
11-EO.mp4_0/11-EO.mp4_0-002.jpg
11-EO.mp4_0/11-EO.mp4_0-003.jpg
12-EO.mp4_0/12-EO.mp4_0-001.jpg
12-EO.mp4_0/12-EO.mp4_0-002.jpg
12-EO.mp4_0/12-EO.mp4_0-003.jpg
```
However, it seems the file path that is created ends up cutting off the beginning digits:

> File mapping failed: /home/user/project/images/-EO.mp4_0/11-EO.mp4_0-001.jpg

**Comment by JanuszL** [comment]
@austinmw - I'm sorry but I cannot reproduce your bug. Can you provide a simple, self-contained repro we could run on our side?
Also please check how it works with the latest DALI release as well as the latest nightly build.
