### ISSUE TITLE
PIL backend automatically rotate few images, messing up BBoxes, while processing.

### ISSUE THREAD

**Issue by alaap001** [NVIDIA/DALI#3120]
Hey, Thank you for the great repo. 

I faced this one issue when I try to get some images through 
`pipe.run()` I realized that some images were rotated automatically randomly. I never applied any fn to rotate yet some images from the batch are rotated by pipeline. This could be due to PIl backend or any other bug I guess. 
This is the simple code snippet:
 
```
@pipeline_def
def simple_pipeline():
      jpegs, labels = fn.readers.file(file_root=image_dir,
                                      name="Reader",
                                      pad_last_batch=True,
                                      random_shuffle = True)
      
      images = fn.decoders.image(jpegs, device='mixed')
      images = fn.resize(images.gpu(), size=[1080, 1920])
      
      return images, labels

pipe = simple_pipeline(batch_size=max_batch_size, num_threads=2, device_id=0)
pipe.build()
```

Upon some debugging, I realized this is due to PIL library issue of not being able to read some EXIF data from images. This happens when image is taller than it is wide. this is an issue with PIL but not opencv. Opencv loads the image as is.
Reference: [PIL Rotates Image issue](https://stackoverflow.com/questions/4228530/pil-thumbnail-is-rotating-my-image)

Because few images are randomly rotated it messes up the relevant BBoxes or the object in general. Hope there is a general solution to this or a bug that can be fixed. 

Here is an example:
 
Normal:
![dan-gold-N7RiDzfF2iw-unsplash](https://user-images.githubusercontent.com/22341728/124390464-642c4880-dd09-11eb-9c10-2d46bce5b365.jpg)

Output from pipeline:
![dan-gold-N7RiDzfF2iw-unsplash-rot](https://user-images.githubusercontent.com/22341728/124390469-68586600-dd09-11eb-857a-79e5fb8ed0aa.jpg)

**Comment by JanuszL** [comment]
Hi @alaap001,

DALI disregards EXIF orientation metadata. You can read more about it https://github.com/NVIDIA/DALI/issues/2660.
The quickest solution to that problem is to preprocess the data set, you can find more details in the [thread like this one](https://superuser.com/questions/36645/how-to-rotate-images-automatically-based-on-exif-data).
