### ISSUE TITLE
[Question] How can I do the translation data agumentation on GPU or something similar very fast

### ISSUE THREAD

**Issue by Rullec** [NVIDIA/DALI#3121]
Hi,
   Thanks a lot for this data loading library `DALI`! It boost a lot on my training speed.
   But now here is a very big question: I have about 100000~ single channel .png images which I want to apply the **translation augmentation** on. But the translation operator `fn.transforms.translation` offered in `DALI` is in CPU mode, which can be relatively slow. It makes the training time per epoch twice longer than before.
   How can I achieve a fast, translation augmentaion over my dataset? Can I combine some other operators (such as GPU-resize or GPU-crop) and mimic a similar effects? Or Can I help to support it in GPU?

  Thanks a lot for your time in advance.

**Comment by JanuszL** [comment]
Hi @Rullec,

Please check [this example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/math/geometric_transforms.html). It is true that `fn.transforms.translation` is a CPU only operation, but its purpose is to build a transformation matrix (and this process is rather fast) and use it to drive the `warp_affine` operation that can be run on the GPU.

**Comment by Rullec** [comment]
Thanks a lot for your explanation ;-) Sorry for this dull question. 
Closed
