### ISSUE TITLE
Scaling data into [0, 255] in dali official examples

### ISSUE THREAD

**Issue by Ema1997** [NVIDIA/DALI#3132]
Hi, 
I have checked your official codes to use the dali dataloader to load data in `https://github.com/NVIDIA/DALI/blob/2d81d5ee8d318d1733e18cd8f7f1129d4451b0cf/docs/examples/use_cases/pytorch/resnet50/main.py`, and in this code, I found that the data feeded into the network has values ranging from 0 to 255. However, when I read the official codes of the pytorch examples in `https://github.com/pytorch/examples/blob/2639cf050493df9d3cbf065d45e6025733add0f4/imagenet/main.py#L312`, I find that this code scales the data into [0, 1].
Therefore, do the scales of the data affect the training and evaluating results?

Thanks,
Ema1997.

**Comment by JanuszL** [comment]
Hi @Ema1997,

The DALI example is based on [APEX's one](https://github.com/NVIDIA/apex/tree/master/examples/imagenet) and it is meant to show how to integrate DALI with classification network implemented in PyTorch.
You can check [the official Nvidia Deep Learning examples repository](https://github.com/NVIDIA/DeepLearningExamples), if you are looking for state-of-the-art implementations.
