### ISSUE TITLE
DaliGenericITerator causing issue:  Mixing pipeline API type

### ISSUE THREAD

**Issue by alaap001** [NVIDIA/DALI#3133]
Hey, thank you for the amazing repo.

I had created a custom ExternalSourcePipeline and it worked just fine. pipe.run() gives proper outputs but since I want to use it for training I need an iterator that'll iterate over all the batches like - DALIGenericIterator, or DALIClassificationIterator. 
But when I use to create GenericIterator I get this error:

`Mixing pipeline API type. Currently used: PipelineAPIType.BASIC, but trying to use: PipelineAPIType.ITERATOR`

I referred to this issue but didn't help me much #2330 

Here's my code: Also since I'm new to Dali let me know if I can improve this. This just reads data from Yolov5 format ( images/ labels/ )

I believe it needs a diff iterator like DALICocoIterator, not sure
```
class ExternalInputIterator(object):
    def __init__(self, batch_size, device_id, num_gpus, images_dir, class_labels, use_cuda=False):
        self.images_dir = images_dir
        self.batch_size = batch_size
        self.class_labels = class_labels
        self.use_cuda = use_cuda
        
        self.files = []
        self.labels = []
        for file in os.listdir(os.path.join(self.images_dir,'images')):
            self.files.append(os.path.join(os.path.join(self.images_dir,'images'),file))
            
            label_name = ''.join(file.split('.')[:-1])+'.txt'
            self.labels.append(os.path.join(os.path.join(self.images_dir,'labels'),label_name))        
        
    def __iter__(self):
        self.i = 0
        self.data_set_len = len(self.files)
        return self

    def __next__(self):
        batch = []
        labels = []
        bboxes = []

        for _ in range(self.batch_size):
            jpeg_filename = self.files[self.i]
            label_filename = self.labels[self.i]
            
            img = imageio.imread(jpeg_filename)
            w,h = img.shape[1], img.shape[0]
            
            bbox = convert_yolo_kitti(jpeg_filename, label_filename, class_labels, w, h)
            temp_bbox = []
            for bb in bbox:
                temp_bbox.append(list(map(int,bb)))

            temp_bbox = torch.tensor(temp_bbox)
            
            if not self.use_cuda:
                f = open(jpeg_filename, 'rb')
                batch.append(np.ascontiguousarray(np.frombuffer(f.read(), dtype = np.uint8)))
#             else:
#                 im = cp.asarray(img)
# #                 im = im * 0.6
#                 batch.append(np.ascontiguousarray(im.astype(cp.uint8)))

            bboxes.append(np.ascontiguousarray(temp_bbox[:,:4], dtype=np.float32))
            labels.append(np.ascontiguousarray(temp_bbox[:,-1])) # or PyTorch's native tensors
            
            self.i = (self.i + 1) % self.data_set_len
            
        return (batch, labels, bboxes)

    def __len__(self):
        return self.data_set_len

    next = __next__

```

Pipeline:

```
eii = ExternalInputIterator(batch_size, 0, 1,images_dir,class_labels)
pipe = Pipeline(batch_size=batch_size, num_threads=2, device_id=0)

with pipe:
    jpegs, labels , bboxes = fn.external_source(source=eii, num_outputs=3)
    decode = fn.decoders.image(jpegs, device="mixed", output_type=types.RGB)

    pipe.set_outputs(jpegs, labels,bboxes)
```

Everything works up to this point but fails here:

`outputs = DALIGenericIterator(pipelines=pipe, last_batch_padded=True,output_map=["images", "labels", "bboxes"])`

with error: `RuntimeError: Mixing pipeline API type. Currently used: PipelineAPIType.BASIC, but trying to use: PipelineAPIType.ITERATOR`

I tried this link [ExternalSource operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/frameworks/pytorch/pytorch-external_input.html) also and ran below code, still got same error:

`pii = PyTorchIterator(pipe, last_batch_padded=True, last_batch_policy=LastBatchPolicy.PARTIAL)`

I want to use it like:

```
train_loader = DALIClassificationIterator(pipe, reader_name="Reader", last_batch_policy=LastBatchPolicy.PARTIAL)
for i, data in enumerate(train_loader):
```

**Comment by JanuszL** [comment]
Hi @alaap001,

As I understand you cannot run [the mentioned example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/frameworks/pytorch/pytorch-external_input.html) as it is, right?

From the error I guess your code looks like this:
```
pipe.build()
pipe.run()
outputs = DALIGenericIterator(pipelines=pipe, last_batch_padded=True,output_map=["images", "labels", "bboxes"])
```
What you should avoid is void mixing the `run` method and DL FW iterator.
You can read more about this [here](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/advanced_topics_pipe_run.html).

If it is not the case please, provide a full, self-contained reproduction code we can run on our side. You can use [DALI test data](https://github.com/NVIDIA/DALI_extra).

**Comment by alaap001** [comment]
> Hi @alaap001,
> 
> As I understand you cannot run [the mentioned example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/frameworks/pytorch/pytorch-external_input.html) as it is, right?
> 
> From the error I guess your code looks like this:
> 
> ```
> pipe.build()
> pipe.run()
> outputs = DALIGenericIterator(pipelines=pipe, last_batch_padded=True,output_map=["images", "labels", "bboxes"])
> ```
> 
> What you should avoid is void mixing the `run` method and DL FW iterator.
> You can read more about this [here](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/advanced_topics_pipe_run.html).
> 
> If it is not the case please, provide a full, self-contained reproduction code we can run on our side. You can use [DALI test data](https://github.com/NVIDIA/DALI_extra).


Hey yes removing pipe.run() worked, thank you. But gave me another error -

`Assert on "this->IsDenseTensor()" failed: All tensors in the input TensorList must have the same shape and be densely packed.`

This happens when I increase my batch size from 1

Here is the reproducible code:

**This just reads data in this dir structure 
                -- images/*.jpg 
                -- labels/*.txt (bboxes) where bboxes are in yolo format**

```
def determine_label_kitti(label, labels):
    return str(labels[int(label)])


def parse_labels_kitti(label_file, labels, img_width, img_height):
    """
    Definition: Parsers label file to extract label and bounding box coordinates. Converts (x, y, width, height) YOLO format to
        (x1, y1, x2, y2) KITTI format.
    """

    lfile = open(label_file)
    coords = []
    all_coords = []
    all_labels = []
    for line in lfile:
        l = line.split(" ")
        #       all_labels.append(determine_label_kitti(l[0], labels))
        all_labels.append(l[0])
        coords = list(map(float, list(map(float, l[1:5]))))
        x1 = float(img_width) * (2.0 * float(coords[0]) - float(coords[2])) / 2.0
        y1 = float(img_height) * (2.0 * float(coords[1]) - float(coords[3])) / 2.0
        x2 = float(img_width) * (2.0 * float(coords[0]) + float(coords[2])) / 2.0
        y2 = float(img_height) * (2.0 * float(coords[1]) + float(coords[3])) / 2.0
        tmp = [x1, y1, x2, y2]
        all_coords.append(list(map(int, tmp)))
    lfile.close()
    return all_labels, all_coords

def convert_yolo_kitti(img_dir, label_dir, labels_split=None,w=None,h=None):
    if os.path.isfile(img_dir):
        labels, coords = parse_labels_kitti(label_dir, labels_split, w, h)
        bboxes = []
        for l, c in zip(labels, coords):
            bboxes.append([c[0], c[1], c[2], c[3], l])
        return np.array(bboxes)
```

```
from nvidia.dali.plugin.pytorch import LastBatchPolicy, DALIGenericIterator
import imageio
import types
import collections
import numpy as np
from random import shuffle
from nvidia.dali.pipeline import Pipeline
import nvidia.dali.types as types
import nvidia.dali.fn as fn
import torch

batch_size = 8

class ExternalInputIterator(object):
    def __init__(self, batch_size, device_id, num_gpus, images_dir, class_labels, use_cuda=False):
        self.images_dir = images_dir
        self.batch_size = batch_size
        self.class_labels = class_labels
        self.use_cuda = use_cuda
        
        self.files = []
        self.labels = []
        for file in os.listdir(os.path.join(self.images_dir,'images')):
            self.files.append(os.path.join(os.path.join(self.images_dir,'images'),file))
            
            label_name = ''.join(file.split('.')[:-1])+'.txt'
            self.labels.append(os.path.join(os.path.join(self.images_dir,'labels'),label_name))        
        
        
    def __iter__(self):
        self.i = 0
        self.data_set_len = len(self.files)
        return self

    def __next__(self):
        batch = []
        labels = []
        bboxes = []

        for _ in range(self.batch_size):
            jpeg_filename = self.files[self.i]
            label_filename = self.labels[self.i]
            
            img = imageio.imread(jpeg_filename)
            w,h = img.shape[1], img.shape[0]
            
            bbox = convert_yolo_kitti(jpeg_filename, label_filename, class_labels, w, h)
            temp_bbox = []
            for bb in bbox:
                temp_bbox.append(list(map(int,bb)))

            temp_bbox = torch.tensor(temp_bbox)
            
            if not self.use_cuda:
                f = open(jpeg_filename, 'rb')
                batch.append(np.ascontiguousarray(np.frombuffer(f.read(), dtype = np.uint8)))
#             else:
#                 im = cp.asarray(img)
# #                 im = im * 0.6
#                 batch.append(np.ascontiguousarray(im.astype(cp.uint8)))

            bboxes.append(np.ascontiguousarray(temp_bbox[:,:4], dtype=np.float32))
            labels.append(np.ascontiguousarray(temp_bbox[:,-1])) # or PyTorch's native tensors
            
            self.i = (self.i + 1) % self.data_set_len
            
        return (batch, labels, bboxes)

    def __len__(self):
        return self.data_set_len

    next = __next__


class_labels = ['list of class labels'] #[1,2.3]
images_dir = 'img_dir'

eii = ExternalInputIterator(batch_size, 0, 1,images_dir,class_labels)
pipe = Pipeline(batch_size=batch_size, num_threads=2, device_id=0)

with pipe:
    jpegs, labels , bboxes = fn.external_source(source=eii, num_outputs=3)
    decode = fn.decoders.image(jpegs, device="mixed", output_type=types.RGB)
    pipe.set_outputs(jpegs, labels, boxes)

pipe.build()

data_loader = DALIGenericIterator(pipelines=pipe, last_batch_padded=True,output_map=["images", "labels", "bboxes"])

```

This code will give this error: `[/opt/dali/dali/pipeline/data/tensor_list.h:575] Assert on "this->IsDenseTensor()" failed: All tensors in the input TensorList must have the same shape and be densely packed.`

**Comment by JanuszL** [comment]
Hi @alaap001,
It means that either batch of images, labels or bboxes cannot be converted to a Torch tensor. DALI operates on a list of samples - batch. Each sample may have different dimensions. When DL FW iterator is used the DALI output is converted to a framework tensor. In your case list of samples cannot be expressed as tensor. What you can do is to use [the 'pad' operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.pad) to have uniform data across the batch and [the `shapes` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.shapes) to return the original, unpadded shapes.

**Comment by alaap001** [comment]
Hey, thankyou for the reply, padding took me one step further. Got another error, here's a brief:
I read images batch with --
```
batch.append(np.ascontiguousarray(np.frombuffer(f.read(), dtype = np.uint8)))
bboxes.append(np.ascontiguousarray(temp_bbox[:,:4], dtype=np.float32))
labels.append(np.ascontiguousarray(temp_bbox[:,-1])) # or PyTorch's native tensors

return (batch, labels, bboxes)
```

and like you said they all had different lengths so I added padding in my pipeline like this:

```
with pipe:
    jpegs, labels , bboxes = fn.external_source(source=eii, num_outputs=3)
    images = fn.decoders.image(jpegs, device="mixed", output_type=types.RGB)

    **images = fn.pad(images,fill_value = 0)**
    **labels = fn.pad(labels,fill_value = -1)**
    **bboxes = fn.pad(bboxes,fill_value = -1)**
    
    pipe.set_outputs(images, labels, bboxes)
```

LET me know if I've done anything wrong so far in changes.

Now `outputs = DALIGenericIterator(pipelines=[pipe], last_batch_padded=True,output_map=["images", "labels", "bboxes"])` works perfectly fine but  **I got another error while iterating outputs in for loop:**

`Shapes do not match: DALI tensor has size [4, 908, 512, 3], but PyTorch Tensor has size [4, 288, 512, 3]`
or
`Shapes do not match: DALI tensor has size [4, 23], but PyTorch Tensor has size [4, 10]`

Where [4,32]  is my box and [4,908,513,3] is my image. I get any random errors like above.

**Comment by JanuszL** [comment]
Hi @alaap001,

Please try to add `dynamic_shape=True` to `DALIGenericIterator`.
By default, the iterator assumes the output has the same size iteration to iteration (as in most cases the network input has fixed size). This option relax this requirement.

**Comment by alaap001** [comment]
> Hi @alaap001,
> 
> Please try to add `dynamic_shape=True` to `DALIGenericIterator`.
> By default, the iterator assumes the output has the same size iteration to iteration (as in most cases the network input has fixed size). This option relax this requirement.

Thank you so much, it worked nicely. Just one simple issue, my `outputs.size` is -1 which I understand is due to StopIteration not being called in Generator or not mentioning size in `DALIGenericIterator`. I don't want to mention size explicitly in `DALIGenericIterator` So I edited my Generator to add StopIteration but maybe I am calling it at the wrong location? I called in def __next__(). Can you please look at what could be wrong with my Iterator?
now it says `Index out of Range` which simply means it is not stopping at the end of batch.

```
from imgaug.augmentables.bbs import BoundingBox, BoundingBoxesOnImage
from custom_augment_utils import *
# import cupy as cp
from nvidia.dali.plugin.pytorch import DALIClassificationIterator as PyTorchIterator
from nvidia.dali.plugin.pytorch import LastBatchPolicy
import imageio
import types
import collections
import numpy as np
from random import shuffle
from nvidia.dali.pipeline import Pipeline
import nvidia.dali.types as types
import nvidia.dali.fn as fn
import torch

batch_size = 8

class ExternalInputIterator(object):
    def __init__(self, batch_size, device_id, num_gpus, images_dir, class_labels, use_cuda=False):
        self.images_dir = images_dir
        self.batch_size = batch_size
        self.class_labels = class_labels
        self.use_cuda = use_cuda
        
        self.files = []
        self.labels = []
        for file in os.listdir(os.path.join(self.images_dir,'images')):
            self.files.append(os.path.join(os.path.join(self.images_dir,'images'),file))
            
            label_name = ''.join(file.split('.')[:-1])+'.txt'
            self.labels.append(os.path.join(os.path.join(self.images_dir,'labels'),label_name))   
        self.data_set_len = len(self.files)     
        
        
    def __iter__(self):
        self.i = 0
        return self

    def __next__(self):
        batch = []
        labels = []
        bboxes = []
        image_paths_ord = []
        print(self.i)
        
        if self.i >= self.data_set_len:
            self.__iter__()
            raise StopIteration

        for _ in range(self.batch_size):
            jpeg_filename = self.files[self.i]
            label_filename = self.labels[self.i]
            
            img = imageio.imread(jpeg_filename)
            w,h = img.shape[1], img.shape[0]
            
            bbox = convert_yolo_kitti(jpeg_filename, label_filename, self.class_labels, w, h)
            temp_bbox = []
            for bb in bbox:
                temp_bbox.append(list(map(int,bb)))

            temp_bbox = torch.tensor(temp_bbox)
            
            if not self.use_cuda:
                f = open(jpeg_filename, 'rb')
                batch.append(np.ascontiguousarray(np.frombuffer(f.read(), dtype = np.uint8)))

            bboxes.append(np.ascontiguousarray(temp_bbox[:,:4], dtype=np.float32))
            labels.append(np.ascontiguousarray(temp_bbox[:,-1])) # or PyTorch's native tensors
        
            # hack for path 
            image_path_ord = [ord(x) for x in jpeg_filename] #this is a hacky trick used to pass image_paths(strings) through DALI.
            image_paths_ord.append(np.ascontiguousarray(image_path_ord))
            self.i += 1
            
        return (batch, labels, bboxes,image_paths_ord)

    def __len__(self):
        return self.data_set_len

    next = __next__
```

**Comment by JanuszL** [comment]
Hi @alaap001,

DALIGenericIterator `size` attribute provides the size of the reader that drives is (if you pass `readers_name` argument), or the size that is set in the `size` parameter.
In the case of the `external_source` operator the size of the data set in most cases cannot be known ahead of time, as the source can be callable or iterable, and the only reliable indicator that it exhausted the data is the `StopIteration` exception.
What is the particular reason to query DALIGenericIterator for the `size` value? If you iterate over it it will end when `StopIteration` is raised by the `external source`.

**Comment by alaap001** [comment]
> Hi @alaap001,
> 
> DALIGenericIterator `size` attribute provides the size of the reader that drives is (if you pass `readers_name` argument), or the size that is set in the `size` parameter.
> In the case of the `external_source` operator, the size of the data set in most cases cannot be known ahead of time, as the source can be callable or iterable, and the only reliable indicator that it exhausted the data is the `StopIteration` exception.
> What is the particular reason to query DALIGenericIterator for the `size` value? If you iterate over it it will end when `StopIteration` is raised by the `external source`.

ya sorry actually StopIteration was not being raised and my code gave error of `list Index out of range`
Upon debugging it was due to this code snippet:
```
def __next__(self):
        batch = []
        labels = []
        bboxes = []
        image_paths_ord = []
        print(self.i)
        
        if self.i >= self.data_set_len:
            self.__iter__()
            raise StopIteration

        for _ in range(self.batch_size):
            jpeg_filename = self.files[self.i]
```

I had to put StopIteration block inside for loop of batch, it was outside so never got triggered. Fixed it. Thankyou.
