### ISSUE TITLE
TypeError: 'DataNode' object is not callable when using fn.readers.video

### ISSUE THREAD

**Issue by Hayoung93** [NVIDIA/DALI#3136]
Hi, I'm trying to use DALI as a data loader for Pytorch, first starting as using it for reading frames from a video.

I found some example sources and followed them, facing some errors and warnings. I handled part of them but can't solve this problem even though I tried to look inside of `nvidia.dali.pipeline.py` file, with my ability.

This is the original code that I used:
```
from nvidia.dali.pipeline import Pipeline
import nvidia.dali.ops as ops
import nvidia.dali.fn as fn
import nvidia.dali.types as types
from nvidia.dali.plugin.pytorch import DALIGenericIterator, LastBatchPolicy

videopath = EXAMPLE_VIDEO_FILE

class PreprocessPipeline(Pipeline):
	def __init__(self, batch_size, num_threads, device_id, data, seq_len):
		super().__init__(batch_size, num_threads, device_id, exec_async=False, exec_pipelined=False)
		self.input = ops.VideoReader(device="gpu", filenames=data, sequence_length=seq_len,
						shard_id=0, num_shards=1,
						random_shuffle=False, dtype=types.FLOAT)
	def define_graph(self):
		raw_input = self.input(name="Reader")
		return raw_input
pipe = PreprocessPipeline(1, 1, 0, videopath, 5)
pipe.build()
dali_iter = DALIGenericIterator([pipe], ['frame'], reader_name="Reader", last_batch_policy=LastBatchPolicy.PARTIAL)
```

Executing the above code gives a warning:
`WARNING: 'video_reader' is now deprecated. Use 'readers.video' instead.`.
So I searched docs and found two `readers.video`, in `fn` and `ops`. Replacing `ops.VideoReader` with `ops.readers.video` gives no error nor warning, but with `fn.readers.video` gives `TypeError: 'DataNode' object is not callable`.
I may use the one from `ops` but it was tagged as Legacy, so I tried to use the one from `fn`.

Can someone tell me why this happens and the difference between the two of them?

Thanks in advance!

**Comment by JanuszL** [comment]
Hi @Hayoung93,

I recommend starting from [this example ](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/sequence_processing/video/video_reader_simple_example.html).
With the functional API, you don't have to create a derived class from Pipeline, and you can define your workflow as just a simple function.

**Comment by Hayoung93** [comment]
@JanuszL, Thanks for the kind answer. I misunderstood the difference between class and function.

I followed the mentioned example, it was helpful.

However, can you suggest a way to use something like `nvidia.dali.plugin.pytorch.DALIGenericIterator` or converting `TensorListGPU` to torch tensor, so I could receive torch.Tensor?
I tried .as_tensor method but only get `TensorGPU`.

Thanks a lot!

**Comment by JanuszL** [comment]
Hi @Hayoung93,

Can you check [this example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/frameworks/pytorch/pytorch-basic_example.html) and just pass your pipeline to the DALIGenericIterator?

**Comment by Hayoung93** [comment]
@JanuszL, I checked the example, Thanks.

It throws `Assert on "meta" failed: Operator Reader not found or does not expose valid metadata.`, as I try to pass it to the DALIGenericIterator.
I didn't follow the example exactly (because the example is associated with images), but it seems to have similar architecture to me except for the existence of labels which I assume it's not a problem because the `labels` argument is not provided to the video reader.

This is the code I've got the error (at the definition of `dali_iter`):
```
import glob

from nvidia.dali import pipeline_def
import nvidia.dali.fn as fn

batch_size = 5
sequence_length = 1
initial_prefetch_size = 16
video_directory = "/data/data/"
video_files = glob.glob(video_directory + "/*.mp4")
n_iter = 60

@pipeline_def
def video_pipe(filenames):
    videos = fn.readers.video(device="gpu", filenames=filenames, sequence_length=sequence_length,
                              shard_id=0, num_shards=1, random_shuffle=False, initial_fill=initial_prefetch_size)
    return videos

pipe = video_pipe(batch_size=batch_size, num_threads=2, device_id=0, filenames=video_files, seed=123456)
pipe.build()

from nvidia.dali.plugin.pytorch import DALIGenericIterator
dali_iter = DALIGenericIterator([pipe], ['frame'], reader_name="Reader")
```

I can't figure out the reason myself.

Thank you!

**Comment by JanuszL** [comment]
Can you try:
```
import glob

from nvidia.dali import pipeline_def
import nvidia.dali.fn as fn

batch_size = 5
sequence_length = 1
initial_prefetch_size = 16
video_directory = "/data/data/"
video_files = glob.glob(video_directory + "/*.mp4")
n_iter = 60

@pipeline_def
def video_pipe(filenames):
    videos = fn.readers.video(device="gpu", filenames=filenames, sequence_length=sequence_length,
                              shard_id=0, num_shards=1, random_shuffle=False, initial_fill=initial_prefetch_size, name="Reader")
    return videos

pipe = video_pipe(batch_size=batch_size, num_threads=2, device_id=0, filenames=video_files, seed=123456)
pipe.build()

from nvidia.dali.plugin.pytorch import DALIGenericIterator
dali_iter = DALIGenericIterator([pipe], ['frame'], reader_name="Reader")
```

**Comment by Hayoung93** [comment]
@JanuszL  OMG It works!

Thank you so much!
