### ISSUE TITLE
Reading Video Frames Stored as Images with start and end frame numbers

### ISSUE THREAD

**Issue by duduheihei** [NVIDIA/DALI#3138]
Dear Dali Group:
Q1:
Dali provide the [readers.sequence](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.readers.sequence) to read frames of sequence from dir. However, sometimes we need to read frames within specific interval, Here is the example list file like I use:
```
dir_frames    label    start_frame    end_frame
video1         2       13                  64
video2         6       87                 130
```
For "video1" above, I need to get a sequence of frames ranging from 13nd frame   to 64th frame with fixed sample rate and sequence length. I do not find appropriate ops for this situation. Will this case be solved in the feature? 

Q2:
An alternative solution to Q1 is using [external source](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.external_source) and self-defined graph as mentioned in [here](https://github.com/NVIDIA/DALI/issues/1984), However this solution does not output tensors with format "DCHW", so I need to stack the tensors with format "CHW" manually during my training process which is inconvenient. I want to ask is there a way that can change format from "CHW" to "DCHW", or output format "DCHW" directly  after decoding?

**Comment by JanuszL** [comment]
Hi @duduheihei,

We don't plan to extend the sequence reader functionality in foreseeable future. 

Yes, you should use [the `external source` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/external_input.html) and implement any loading logic you want (please check `parallel ` and `prefetch_queue_depth` to obtain the optimal performance).

To have the data in "DCHW" format please use the `layout` parameter and make sure that each sample you output has 4 dimensions. Something like this should illustrate the very basic use case:
```
import numpy as np
import nvidia.dali.fn as fn
from nvidia.dali import pipeline_def

batch_size = 4

def get_data():
    out = [(np.random.ranf(size=[2, 3, 4, 5]).astype(dtype=np.float32)*60 + 30) for _ in range(batch_size)]
    return out

@pipeline_def
def simple_pipeline():
    data = fn.external_source(source=get_data, layout="dchw")
    return data

pipe = simple_pipeline(batch_size=batch_size, num_threads=4, prefetch_queue_depth=2, device_id=0)
pipe.build()
pipe.run()
out = pipe.run()[0]
print(out.as_array().shape)
```

**Comment by duduheihei** [comment]
> Hi @duduheihei,
> 
> We don't plan to extend the sequence reader functionality in foreseeable future.
> 
> Yes, you should use [the `external source` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/external_input.html) and implement any loading logic you want (please check `parallel ` and `prefetch_queue_depth` to obtain the optimal performance).
> 
> To have the data in "DCHW" format please use the `layout` parameter and make sure that each sample you output has 4 dimensions. Something like this should illustrate the very basic use case:
> 
> ```
> import numpy as np
> import nvidia.dali.fn as fn
> from nvidia.dali import pipeline_def
> 
> batch_size = 4
> 
> def get_data():
>     out = [(np.random.ranf(size=[2, 3, 4, 5]).astype(dtype=np.float32)*60 + 30) for _ in range(batch_size)]
>     return out
> 
> @pipeline_def
> def simple_pipeline():
>     data = fn.external_source(source=get_data, layout="dchw")
>     return data
> 
> pipe = simple_pipeline(batch_size=batch_size, num_threads=4, prefetch_queue_depth=2, device_id=0)
> pipe.build()
> pipe.run()
> out = pipe.run()[0]
> print(out.as_array().shape)
> ```

Hi, Thanks for you reply. Your code example above use "get_data" function to get "dchw" tensors to feed the graph. However, this means I have to decode images before the graph, so I cannot utilize dali to speed up decoding process. Is there a way of changing sequences of  frames to "DCHW" in the graph, just as numpy's op "stack"?

**Comment by JanuszL** [comment]
Hi,
In this case, you can return multiple outputs from the external source operator, one per batch of frames in sequence, run decoder and stack the results:
```
@pipeline_def
def simple_pipeline():
    jpegs = fn.external_source(source=get_data, num_outputs=sequence_lenght)
    images = fn.decoders.image(jpegs)
    sequence = fn.stack(*images)
    sequence = fn.reshape(sequence, layout="DHWC")
    return sequence
```
However, it will create a decoder operator instance for each frame in sequence what can consume a lot of memory. Still, you can try this out and see how that works in your case,

**Comment by duduheihei** [comment]
> Hi,
> In this case, you can return multiple outputs from the external source operator, one per batch of frames in sequence, run decoder and stack the results:
> 
> ```
> @pipeline_def
> def simple_pipeline():
>     jpegs = fn.external_source(source=get_data, num_outputs=sequence_lenght)
>     images = fn.decoders.image(jpegs)
>     sequence = fn.stack(*images)
>     sequence = fn.reshape(sequence, layout="DHWC")
>     return sequence
> ```
> 
> However, it will create a decoder operator instance for each frame in sequence what can consume a lot of memory. Still, you can try this out and see how that works in your case,

Hi ， I tyied your code above and have some bug. My squence length is 16, However the final tensor shape I got is Bx15xHxWxC.
Here is my code example:
```python
    # this pseuado code illustrate what External Source return
    def __next__(self):
        batch = [[] for _ in range(self.seq_len)]
        labels = []
        for _ in range(self.batch_size):
            if self.i >= self.n:
                raise StopIteration
            for k in range(self.seq_len):
                f = open('{xxx}.jpg','r')
                batch[k].append(np.frombuffer(f.read(), dtype = np.uint8))
                f.close()
            labels.append(np.array([1], dtype = np.uint8))
            self.i = self.i + 1
        return (*batch,labels)
# pipeline
def ExternalSourcePipeline(batch_size, num_threads, device_id, external_data,seq_len=16):
    pipe = Pipeline(batch_size, num_threads, device_id)
    with pipe:
        outputs = fn.external_source(source=external_data, num_outputs=seq_len+1)
        jpegs = outputs[:-1]
        labels = outputs[-1]
        images = fn.decoders.image(jpegs, device="mixed")
        images = fn.stack(*images)
        images = fn.reshape(images, layout="DHWC")
        images = fn.resize(images, resize_x=240, resize_y=240)
        output = fn.cast(images, dtype=types.UINT8)
        pipe.set_outputs(images,labels)
    return pipe

pipe = ExternalSourcePipeline(BATCH_SIZE, NUM_THREADS, DEVICE_ID, ext_source)
pii = DALIGenericIterator(pipe,['data0','label'])
```
After I show the tensor shape, I got  Bx(SEQ_LEN-1)xHxWx3. Interestingly, after I commemt this line "images = fn.resize(images, resize_x=240, resize_y=240)", the shape was right. Could you give me some advice?

**Comment by duduheihei** [comment]
> > Hi,
> > In this case, you can return multiple outputs from the external source operator, one per batch of frames in sequence, run decoder and stack the results:
> > ```
> > @pipeline_def
> > def simple_pipeline():
> >     jpegs = fn.external_source(source=get_data, num_outputs=sequence_lenght)
> >     images = fn.decoders.image(jpegs)
> >     sequence = fn.stack(*images)
> >     sequence = fn.reshape(sequence, layout="DHWC")
> >     return sequence
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > However, it will create a decoder operator instance for each frame in sequence what can consume a lot of memory. Still, you can try this out and see how that works in your case,
> 
> Hi ， I tyied your code above and have some bug. My squence length is 16, However the final tensor shape I got is Bx15xHxWxC.
> Here is my code example:
> 
> ```python
>     # this pseuado code illustrate what External Source return
>     def __next__(self):
>         batch = [[] for _ in range(self.seq_len)]
>         labels = []
>         for _ in range(self.batch_size):
>             if self.i >= self.n:
>                 raise StopIteration
>             for k in range(self.seq_len):
>                 f = open('{xxx}.jpg','r')
>                 batch[k].append(np.frombuffer(f.read(), dtype = np.uint8))
>                 f.close()
>             labels.append(np.array([1], dtype = np.uint8))
>             self.i = self.i + 1
>         return (*batch,labels)
> # pipeline
> def ExternalSourcePipeline(batch_size, num_threads, device_id, external_data,seq_len=16):
>     pipe = Pipeline(batch_size, num_threads, device_id)
>     with pipe:
>         outputs = fn.external_source(source=external_data, num_outputs=seq_len+1)
>         jpegs = outputs[:-1]
>         labels = outputs[-1]
>         images = fn.decoders.image(jpegs, device="mixed")
>         images = fn.stack(*images)
>         images = fn.reshape(images, layout="DHWC")
>         images = fn.resize(images, resize_x=240, resize_y=240)
>         output = fn.cast(images, dtype=types.UINT8)
>         pipe.set_outputs(images,labels)
>     return pipe
> 
> pipe = ExternalSourcePipeline(BATCH_SIZE, NUM_THREADS, DEVICE_ID, ext_source)
> pii = DALIGenericIterator(pipe,['data0','label'])
> ```
> 
> After I show the tensor shape, I got Bx(SEQ_LEN-1)xHxWx3. Interestingly, after I commemt this line "images = fn.resize(images, resize_x=240, resize_y=240)", the shape was right. Could you give me some advice?

Do I used the wrong format in fn.reshape, after I change param from "DHWC" to "FHWC", the result is right!

**Comment by klecki** [comment]
Hi,
> Do I used the wrong format in fn.reshape, after I change param from "DHWC" to "FHWC", the result is right!

Yes, it would appear so. The difference is `D` means depth and `DHWC` data is treated as volumetric input - the resize would work in all three data axes: Depth, Height and Width.

`F` means frames, and is used with sequences - for `FHWC` tensor, each "frame" or "sequence element" (`HWC` image) is processed the same way, so resized only in Height and Width.

**Comment by klecki** [comment]
Also isn't the double nested loop creating sequences supposed to work like:
```
...
        for sample_idx in range(self.batch_size):
            if self.i >= self.n:
                raise StopIteration
            for k in range(self.seq_len):
                f = open('{xxx}.jpg','r')
                batch[sample_idx].append(np.frombuffer(f.read(), dtype = np.uint8))
                f.close()
...
```

**Comment by klecki** [comment]
Also expanding on the DHWC vs FHWC, the [resize operator](https://docs.nvidia.com/deeplearning/dali/main-user-guide/docs/supported_ops.html#nvidia.dali.fn.resize) which in the "default" mode works by:
> Missing extents are scaled with the average scale of the provided ones

so with the DHWC when you had 3 data axes, the 3rd one also got scaled.

**Comment by duduheihei** [comment]
> Also isn't the double nested loop creating sequences supposed to work like:
> 
> ```
> ...
>         for sample_idx in range(self.batch_size):
>             if self.i >= self.n:
>                 raise StopIteration
>             for k in range(self.seq_len):
>                 f = open('{xxx}.jpg','r')
>                 batch[sample_idx].append(np.frombuffer(f.read(), dtype = np.uint8))
>                 f.close()
> ...
> ```

Could you give more detailed code? If use this kind of nested loog, how to return the batch and labels? like:
```python
return (batch, labels)
```
or
```python
return (*batch,labels)
```
And what the "num_outputs" parameter of "fn.external_source" should be.
Moreover, How to receive data in the pipeline and stack them into "FHWC".

**Comment by klecki** [comment]
Sorry, my mistake, I was thrown off by the variable named `batch`. Indeed it's a list of batches, the first element is batch of the first frames, second element batch of second frames etc.
Your code here is fine. The use of num_outputs is correct.

**Comment by duduheihei** [comment]
> Your code here is fine. The use of num_outputs is correct.
That's ok. Thanks your reply. I got the right result in the end, and dali provide many efficient ops for users. Thanks for dali group!
And  this issue will be close.
