### ISSUE TITLE
support for python 3.9

### ISSUE THREAD

**Issue by Borda** [NVIDIA/DALI#3144]
May I kindly ask to extend support also for python 3.9, at this moment, the newest version to be installed 0.27
for installation I used recommended:
```bash
pip install --extra-index-url https://developer.download.nvidia.com/compute/redist nvidia-dali-cuda110
```
and getting
```
ERROR: Packages require a different Python. 3.9.5 not in:
'<=3.9,>=3.6' (required by nvidia-dali-cuda110 1.3.0 (from https://developer.download.nvidia.com/compute/redist/nvidia-dali-cuda110/nvidia_dali_cuda110-1.3.0-2471497-py3-none-manylinux2014_x86_64.whl (from https://developer.download.nvidia.com/compute/redist/nvidia-dali-cuda110/)))
'<=3.9,>=3.6' (required by nvidia-dali-cuda110 1.2.0 (from https://developer.download.nvidia.com/compute/redist/nvidia-dali-cuda110/nvidia_dali_cuda110-1.2.0-2356513-py3-none-manylinux2014_x86_64.whl (from https://developer.download.nvidia.com/compute/redist/nvidia-dali-cuda110/)))
'<=3.9,>=3.6' (required by nvidia-dali-cuda110 1.1.0 (from https://developer.download.nvidia.com/compute/redist/nvidia-dali-cuda110/nvidia_dali_cuda110-1.1.0-2239649-py3-none-manylinux2014_x86_64.whl (from https://developer.download.nvidia.com/compute/redist/nvidia-dali-cuda110/)))
```

**Comment by JanuszL** [comment]
Hi @Borda,
There is a bug in the Python wheel manifest that prevents DALI from installing for python 3.9.
It should be fixed in the nightly/weekly build and the next, 1.4 release.

**Comment by Borda** [comment]
ok, seems to be fixed by #3092, but there is no release till 1.4 is out...

**Comment by JanuszL** [comment]
Hi,

Please check [this guide](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/installation.html#pip-nightly-and-weekly-releases) to install nightly/weekly builds (1.4 candidates).

**Comment by Borda** [comment]
Thank you, is there any eta for the 1.4 release?

**Comment by JanuszL** [comment]
We do our best to keep a monthly release cadence. So it should be by the end of July.
