### ISSUE TITLE
mutilple gpu dataloader and mutiple gpu training

### ISSUE THREAD

**Issue by janice555** [NVIDIA/DALI#3149]
hello, when I use external_source as data input iterator ,how to use mutiple gpus ? cause I want to use mutiple gpus for both data augment and training.

**Comment by janice555** [comment]
and my dataset is a segmentation dataset , it seems I can not use ops.filereader and fn.readers.file

**Comment by klecki** [comment]
Hi,
we have a dedicated COCO reader that may be useful in segmentation use case, here is a [tutorial](https://docs.nvidia.com/deeplearning/dali/main-user-guide/docs/examples/general/data_loading/coco_reader.html) and the [operator doc](https://docs.nvidia.com/deeplearning/dali/main-user-guide/docs/supported_ops.html#nvidia.dali.fn.readers.coco). 


For running on multiple GPUs [this tutorial](https://docs.nvidia.com/deeplearning/dali/main-user-guide/docs/examples/general/multigpu.html) might help.
Every DALI pipeline should be created with appropriate `device_id` parameter, to indicate on which GPU it run. 

If you plan on using External Source as input in such pipelines, you will need to shard the data manually. That means when creating pipeline for specific `device_id`, the callback/iterable passed as `source` to External Source must be aware of it (the id of the shard), and the total number of shards as well.

Also depending on how your data is stored, you can use for example two `readers.file`, one that will read images, the other will read segmentation masks. You just need to pass them corresponding lists of images and masks, and set the same seeds if you plan on using shuffling. You can add some dummy labels that will be ignored in the pipeline.

Overall using dedicated readers should be faster than using external source in most cases.
