### ISSUE TITLE
Support for the text preprocessing at the Triton server side

### ISSUE THREAD

**Issue by sachinsharma9780** [NVIDIA/DALI#3157]
Can we add the support for text preprocessing especially for transformer models for e.g. performing tokenization at the Triton server side?

**Comment by klecki** [comment]
Hi @sachinsharma9780,
as of now we don't have plans of supporting text preprocessing in DALI. DALI focuses on dense data like images, video and audio.

For accelerated text preprocessing I think you can take a look at [RAPIDS](https://rapids.ai/).

**Comment by sachinsharma9780** [comment]
would you be interested if I can write some python backends for text preprocessing and contribute to triton server repository ?

**Comment by szalpal** [comment]
Hi @sachinsharma9780 !

Sure, we're always interested in external contributions! Although DALI itself is not really suitable for text processing, our internals don't really support it. But please take look into [Python Backend](https://github.com/triton-inference-server/python_backend). There's an `examples` directory. If you can provide an example, please file a PR and we'll take care of it.
