### ISSUE TITLE
Abnormal termination of training

### ISSUE THREAD

**Issue by pawopawo** [NVIDIA/DALI#3161]
![image](https://user-images.githubusercontent.com/38682321/126094580-05bbbc00-5ea9-4e30-940d-99731561d25b.png)
In the training process using DALI, the above phenomenon often occurs, and the utilization rate of a gpu becomes 0 and program stops running.

**Comment by klecki** [comment]
Hi @pawopawo,

Can you provide a minimal and self-contained reproduction that would show the problem?
You can use data from https://github.com/NVIDIA/DALI_extra as an example.

**Comment by pawopawo** [comment]
Thanks. When I use the ILSVRC2012 dataset, there is no problem in training. When I use imagenet22k, the above problem occurs.

**Comment by pawopawo** [comment]
There is no error in the log

**Comment by JanuszL** [comment]
Hi @pawopawo,
It looks like GPU 5 crashed and all remaining are waiting for it?
Are you sure there is no log or error message? Maybe your data set is corrupted?
