### ISSUE TITLE
died with <Signals.SIGSEGV: 11>

### ISSUE THREAD

**Issue by pawopawo** [NVIDIA/DALI#3164]
![image](https://user-images.githubusercontent.com/38682321/126196474-a2939be8-13ac-4731-b2e7-cb45b79fcc27.png)
The frequency of this error is very high

**Comment by mzient** [comment]
@pawopawo Thanks for the report. Please provide more details:
- CPU, GPU (is it a DGX or sth else?)
- OS
- driver version
- DLFW container version, if used
- where is the data located (local disk, network storage)

**Comment by pawopawo** [comment]
```
Collecting environment information...
PyTorch version: 1.6.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 10 (buster) (x86_64)
GCC version: (Debian 8.3.0-6) 8.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.10

Python version: 3.7.4 (default, Aug 13 2019, 20:35:49)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-4.14.81.bm.20-amd64-x86_64-with-debian-10.3
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration: 
GPU 0: Tesla V100-SXM2-32GB
GPU 1: Tesla V100-SXM2-32GB
GPU 2: Tesla V100-SXM2-32GB
GPU 3: Tesla V100-SXM2-32GB
GPU 4: Tesla V100-SXM2-32GB
GPU 5: Tesla V100-SXM2-32GB
GPU 6: Tesla V100-SXM2-32GB
GPU 7: Tesla V100-SXM2-32GB

Nvidia driver version: 418.116.00
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.6.0
[pip3] torchvision==0.7.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2020.0                      166  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.15           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0  
[conda] numpy                     1.19.5                   pypi_0    pypi
[conda] torch                     1.6.0                    pypi_0    pypi
[conda] torchvision               0.7.0                    pypi_0    pypi
```

**Comment by pawopawo** [comment]
![image](https://user-images.githubusercontent.com/38682321/126254152-9372e520-44dc-4c8a-99d2-b2c015264bdc.png)

**Comment by mzient** [comment]
As noted in issue #3163, the driver/toolkit versions don't match. See compatibility table:


CUDA Toolkit | Linux x86_64 Required Driver Version
-- | --
CUDA 11.3 | >= 450.80.02
CUDA 11.2 | >= 450.80.02
CUDA 11.1 (11.1.0) | >= 450.80.02
CUDA 11.0 (11.0.3) | >= 450.36.06
CUDA 10.2 (10.2.89) | >= 440.33
CUDA 10.1 (10.1.105) | >= 418.39
CUDA 10.0 (10.0.130) | >= 410.48
CUDA 9.2 (9.2.88) | >= 396.26
CUDA 9.1 (9.1.85) | >= 390.46
CUDA 9.0 (9.0.76) | >= 384.81
CUDA 8.0 (8.0.61 GA2) | >= 375.26
CUDA 8.0 (8.0.44) | >= 367.48
CUDA 7.5 (7.5.16) | >= 352.31
CUDA 7.0 (7.0.28) | >= 346.46

**Comment by pawopawo** [comment]
thanks~

**Comment by zhiheng-ldj** [comment]
Hi @mzient ,

Thanks for your help. I am facing a similar problem when I train ImageNet LMDB:

```
Traceback (most recent call last):
  File "/home/admin/miniconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/admin/miniconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/admin/miniconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/admin/miniconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/admin/miniconda3/bin/python3', '-u', 'dist_train.py', '--local_rank=1', '--cfg', '3090_test.yaml']' died with <Signals.SIGSEGV: 11>.
```

Here is my CUDA and driver information and it seems good:

![截屏2021-08-03 下午3 35 29](https://user-images.githubusercontent.com/67734380/127976479-7c8213da-e4f6-4c43-b3c2-d1df8e44ccf0.png)


Thanks for your help!!

**Comment by JanuszL** [comment]
Hi @zhiheng-ldj,

Does it happen always or just sometimes? Can you provide a complete and self-contained repro we can run on our side (if it can be reproduced in the dockerized environment that would be great)?
Otherwise, it is hard to tell what went wrong.
