### ISSUE TITLE
Does DALI support training using multi-labels by reading MXNET .rec ?

### ISSUE THREAD

**Issue by jiqirenno1** [NVIDIA/DALI#317]

**Comment by JanuszL** [comment]
Hi,
Currently we support only one label per image if we are talking about RecordIOReader, FileReader and CaffeReader. However Caffe2Reader and TFRecord reader allows you to read more than one label per image and return additional tensor with that. Then you need to write own metrics that accepts this multiple tensor list with labels per batch.
Also you need to create custom DALI iterator to handle more than one label per sample - please check dali/python/nvidia/dali/plugin/mxnet.py.
So DALI can support this use case for data types and requires you to create custom iterator.

**Comment by pbamotra** [comment]
Can I use DALI to read multiple but fixed number of labels per image? I've a pretty big data set and arranging images in sub-folders is a unnecessary and time consuming.

Let's say I've a csv

1, image_1.jpg, lab_1, lab_2, lab_3
2, image_2.jpg, lab_1, lab_2, lab_3

**Comment by JanuszL** [comment]
@pbamotra - I think you you RecordIO reader or TFRecord to store multiple labels per image. For FileReader it is not possible.

**Comment by pbamotra** [comment]
Thanks @JanuszL, however I was thinking if we can modify [ExternalSource](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/external_input.html) operator accommodate multiple labels?

**Comment by JanuszL** [comment]
@pbamotra -  I think you can use it directly and return as a integer label a 1D tensor with all labels. Like in https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/external_input.html you reads jpegs, you can read labels.
