### ISSUE TITLE
image path in DALIClassificationIterator

### ISSUE THREAD

**Issue by pawopawo** [NVIDIA/DALI#3170]
How to get the `image-path` of each picture, or the fixed id of each picture, even if the dataset is shuffled

**Comment by klecki** [comment]
Hi @pawopawo,
unfortunately, you cannot get the file path for the images returned by the reader, but you can get the image class (the readers usually return two outputs - the encoded image and the class).

What you can do, is provide a separate class for every image to have distinct identification, for example via the `file_list` - you can find more in reader docs, for example File Reader: https://docs.nvidia.com/deeplearning/dali/main-user-guide/docs/supported_ops.html#nvidia.dali.fn.readers.file
