### ISSUE TITLE
How to feed the image path into dali.Pipeline ? 

### ISSUE THREAD

**Issue by pawopawo** [NVIDIA/DALI#3171]
```
File "/home/tiger/.local/lib/python3.7/site-packages/nvidia/dali/external_source.py", line 83, in feed
    self._group.feed(self._pipepline, self._data, self._batch_size)
  File "/home/tiger/.local/lib/python3.7/site-packages/nvidia/dali/external_source.py", line 200, in feed
    pipeline.feed_input(op._name, data, op._layout, self._cuda_stream, self.use_copy_kernel)
  File "/home/tiger/.local/lib/python3.7/site-packages/nvidia/dali/pipeline.py", line 766, in feed_input
    inp = Tensors.TensorCPU(datum, layout or "")
RuntimeError: [/opt/dali/dali/util/pybind.h:183] Cannot create type for unknown format string: O
```

**Comment by klecki** [comment]
Hi @pawopawo,
if you want to read an images via their paths, I recommend to read the docs for the [File Reader](https://docs.nvidia.com/deeplearning/dali/main-user-guide/docs/supported_ops.html#nvidia.dali.fn.readers.file).

There are several options, you can either provide a directory to be scanned, or a list of relative paths and labels.

The first example in [Getting Started](https://docs.nvidia.com/deeplearning/dali/main-user-guide/docs/examples/getting_started.html#Pipeline) discusses how to read and decode images with DALI. It is important to specify `device=mixed` for the decoder, to get the GPU acceleration as described in the latter part of the tutorial: https://docs.nvidia.com/deeplearning/dali/main-user-guide/docs/examples/getting_started.html#Hybrid-Decoding.
