### ISSUE TITLE
RuntimeError: CUDA runtime API error cudaErrorInitializationError (3):

### ISSUE THREAD

**Issue by JackyChan97** [NVIDIA/DALI#3178]
When build the pipeline there is an error.
```import os
from nvidia.dali.pipeline import Pipeline
from nvidia.dali.plugin import pytorch
import nvidia.dali.ops as ops
import nvidia.dali.types as types

class VideoReaderPipeline(Pipeline):
    def __init__(self, batch_size, sequence_length, num_threads, device_id, files,
                 crop_size, random_shuffle=True, step=-1):
        super(VideoReaderPipeline, self).__init__(batch_size, num_threads, device_id, seed=12)
        # Define VideoReader
        self.reader = ops.readers.Video(device="gpu",
                                        filenames=files,
                                        sequence_length=sequence_length,
                                        normalized=False,
                                        random_shuffle=random_shuffle,
                                        image_type=types.DALIImageType.RGB,
                                        dtype=types.DALIDataType.UINT8,
                                        step=step,
                                        initial_fill=102400,
                                        prefetch_queue_depth=2)

        # Define crop and permute operations to apply to every sequence
        self.crop = ops.CropMirrorNormalize(device="gpu",
                                            crop_w=crop_size,
                                            crop_h=crop_size,
                                            output_layout='FCHW',
                                            dtype=types.DALIDataType.FLOAT)
        self.uniform = ops.Uniform(range=(0.0, 1.0))  # used for random crop

    def define_graph(self):
        '''Definition of the graph--events that will take place at every sampling of the dataloader.
        The random crop and permute operations will be applied to the sampled sequence.
        '''
        input = self.reader(name="Reader")
        cropped = self.crop(input, crop_pos_x=self.uniform(), crop_pos_y=self.uniform())
        return cropped

if __name__ == "__main__":
    pipeline = VideoReaderPipeline(2, 15, 2, 0, ['/public_data/VSRDATA/REDS/sharp_video/000.mp4'], 128,True, 1)
    pipeline.build()
```

### error message

``` Traceback (most recent call last):
  File "test_dali.py", line 120, in <module>
    pipeline.build()
  File "/usr/local/lib64/python3.6/site-packages/nvidia/dali/pipeline.py", line 658, in build
    self._init_pipeline_backend()
  File "/usr/local/lib64/python3.6/site-packages/nvidia/dali/pipeline.py", line 573, in _init_pipeline_backend
    self._default_cuda_stream_priority)
RuntimeError: CUDA runtime API error cudaErrorInitializationError (3):
initialization error
```
I run the code in an docker container, and the docker version is Docker version 18.09.6, build adbf89666f

### Running environment

```Collecting environment information...
PyTorch version: 1.5.1+cu101
Is debug build: False
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A
OS: Tencent tlinux 2.2 (Final) (x86_64)
GCC version: (GCC) 7.3.1 20180303 (Red Hat 7.3.1-6)
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.3.4
Python version: 3.6.8 (default, Aug  7 2019, 17:28:10)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] (64-bit runtime)
Python platform: Linux-4.14.105-1-tlinux3-0011-x86_64-with-centos-7.2-Final
Is CUDA available: True
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: GRID P40-6C
Nvidia driver version: 430.46
cuDNN version: /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7
HIP runtime version: N/A
MIOpen runtime version: N/A
Versions of relevant libraries:
[pip3] numpy==1.18.2
[pip3] pytorch-ignite==0.4.4
[pip3] torch==1.5.1+cu101
[pip3] torchvision==0.6.1
[conda] Could not collect
```

**Comment by JackyChan97** [comment]
> When build the pipeline there is an error.
> 
> ```
> from nvidia.dali.pipeline import Pipeline
> from nvidia.dali.plugin import pytorch
> import nvidia.dali.ops as ops
> import nvidia.dali.types as types
> 
> class VideoReaderPipeline(Pipeline):
>     def __init__(self, batch_size, sequence_length, num_threads, device_id, files,
>                  crop_size, random_shuffle=True, step=-1):
>         super(VideoReaderPipeline, self).__init__(batch_size, num_threads, device_id, seed=12)
>         # Define VideoReader
>         self.reader = ops.readers.Video(device="gpu",
>                                         filenames=files,
>                                         sequence_length=sequence_length,
>                                         normalized=False,
>                                         random_shuffle=random_shuffle,
>                                         image_type=types.DALIImageType.RGB,
>                                         dtype=types.DALIDataType.UINT8,
>                                         step=step,
>                                         initial_fill=102400,
>                                         prefetch_queue_depth=2)
> 
>         # Define crop and permute operations to apply to every sequence
>         self.crop = ops.CropMirrorNormalize(device="gpu",
>                                             crop_w=crop_size,
>                                             crop_h=crop_size,
>                                             output_layout='FCHW',
>                                             dtype=types.DALIDataType.FLOAT)
>         self.uniform = ops.Uniform(range=(0.0, 1.0))  # used for random crop
> 
>     def define_graph(self):
>         '''Definition of the graph--events that will take place at every sampling of the dataloader.
>         The random crop and permute operations will be applied to the sampled sequence.
>         '''
>         input = self.reader(name="Reader")
>         cropped = self.crop(input, crop_pos_x=self.uniform(), crop_pos_y=self.uniform())
>         return cropped
> 
> if __name__ == "__main__":
>     pipeline = VideoReaderPipeline(2, 15, 2, 0, ['/public_data/VSRDATA/REDS/sharp_video/000.mp4'], 128,True, 1)
>     pipeline.build()
> ```
> 
> ### error message
> ```
>     pipeline.build()
>   File "/usr/local/lib64/python3.6/site-packages/nvidia/dali/pipeline.py", line 658, in build
>     self._init_pipeline_backend()
>   File "/usr/local/lib64/python3.6/site-packages/nvidia/dali/pipeline.py", line 573, in _init_pipeline_backend
>     self._default_cuda_stream_priority)```
> 
> I run the code in an docker container, and the docker version is Docker version 18.09.6, build adbf89666f
> ### Running environment
> Collecting environment information...
> PyTorch version: 1.5.1+cu101
> Is debug build: False
> CUDA used to build PyTorch: 10.1
> ROCM used to build PyTorch: N/A
> OS: Tencent tlinux 2.2 (Final) (x86_64)
> GCC version: (GCC) 7.3.1 20180303 (Red Hat 7.3.1-6)
> Clang version: Could not collect
> CMake version: Could not collect
> Libc version: glibc-2.3.4
> Python version: 3.6.8 (default, Aug  7 2019, 17:28:10)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] (64-bit runtime)
> Python platform: Linux-4.14.105-1-tlinux3-0011-x86_64-with-centos-7.2-Final
> Is CUDA available: True
> CUDA runtime version: 10.1.243
> GPU models and configuration: GPU 0: GRID P40-6C
> Nvidia driver version: 430.46
> cuDNN version: /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7
> HIP runtime version: N/A
> MIOpen runtime version: N/A
> Versions of relevant libraries:
> [pip3] numpy==1.18.2
> [pip3] pytorch-ignite==0.4.4
> [pip3] torch==1.5.1+cu101
> [pip3] torchvision==0.6.1
> [conda] Could not collect
> ```

**Comment by mzient** [comment]
Which version of DALI are you trying to use? If you're trying to use one of our nightly/weekly builds, then the problem could be explained by the fact that we've switched to CUDA 10.2 and your container has insufficient driver - for CUDA 10.2 you'd need at least 440.33.

**Comment by JackyChan97** [comment]
> Which version of DALI are you trying to use? If you're trying to use one of our nightly/weekly builds, then the problem could be explained by the fact that we've switched to CUDA 10.2 and your container has insufficient driver - for CUDA 10.2 you'd need at least 440.33.
> Are you able to run any CUDA code inside that container? You need to run it with `docker run --runtime=nvidia --gpus all` or `nvidia-docker run --gpus all ...`

I install the latest version of DALI by `pip install --extra-index-url https://developer.download.nvidia.com/compute/redist --upgrade nvidia-dali-cuda110`, do I need to switch to old version? And my cuda version installed in the docker container is 10.1, when I abort the DALI and use pytorch dataloader, the code can excute normally.
And I run the docker container by `docker run -it -e NVIDIA_VISIBLE_DEVICES=all  -v /apdcephfs/:/apdcephfs/  mirrors.tencent.com/ziggychen_docker/pytorch1.5.1-cuda10.1:latest /bin/bash`

**Comment by mzient** [comment]
That's not the right release. `nvidia-dali-cuda110` is for CUDA 11 and you have your container set up for CUDA 10. Use
`nvidia-dali-cuda100`.

**Comment by mzient** [comment]
Also, please note that we support CUDA 10.0 only up to DALI 1.3 - the next release (which is on Monday) will be for CUDA 10.2 and CUDA 11.
