### ISSUE TITLE
Does DALI support CUDA10?

### ISSUE THREAD

**Issue by chenhuan0** [NVIDIA/DALI#318]
Hi,
I compiled tensorflow 1.12 with CUDA10, and try to use DALI with that. However, I got the following errors:

Traceback (most recent call last):
  File "/home/benchmarks-cnn_tf_v1.12_compatible/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py", line 27, in <module>
    import benchmark_cnn
  File "/home/benchmarks-cnn_tf_v1.12_compatible/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 42, in <module>
    import datasets
  File "/home/benchmarks-cnn_tf_v1.12_compatible/scripts/tf_cnn_benchmarks/datasets.py", line 32, in <module>
    import preprocessing
  File "/home/benchmarks-cnn_tf_v1.12_compatible/scripts/tf_cnn_benchmarks/preprocessing.py", line 40, in <module>
    import nvidia.dali.plugin.tf as dali_tf
  File "/usr/local/lib/python2.7/dist-packages/nvidia/dali/plugin/tf.py", line 29, in <module>
    raise Exception('No matching DALI plugin found for installed TensorFlow version')
Exception: No matching DALI plugin found for installed TensorFlow version

I manually execute tf.load_op_libary, and got the following errors:

>>> tf.load_op_library("/usr/local/lib/python2.7/dist-packages/nvidia/dali/plugin/libdali_tf_1_12.so")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/load_library.py", line 60, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /usr/local/lib/python2.7/dist-packages/nvidia/dali/plugin/libdali_tf_1_12.so: undefined symbol: _ZN10tensorflow12OpDefBuilder4AttrESs

Can somebody tell me if the reason is that DALI doesn't support CUDA10 now? Or I should set some flag when compiling tensorflow to let it support DALI?

Thanks

**Comment by chenhuan0** [comment]
> Hi,
> Does it work for you with the prebuild tensorflow-gpu 1.12?
> Could you check if you really have 1.12 source code? Have you also checked if your TensorFlow build works without DALI?
> Basically this error tells that DALI cannot find `tensorflow::OpDefBuilder::Attr(std::basic_string<char, std::char_traits<char>, std::allocator<char> >)` function which is provided by the TensorFlow itself. I can clearly see that it should be - https://github.com/tensorflow/tensorflow/blob/v1.12.0/tensorflow/core/framework/op_def_builder.h#L87.
> Also, this log has (I guess) very little to do with CUDA 10. DALI links CUDA related stuff statically and as long as you have a compatible driver you can have any CUDA runtime you want.

Yes, the prebuild tensorflow-gpu 1.1.2 works for me, but it is for CUDA-9.
I'll try to compile tf again and come back with you the latest results.

**Comment by JanuszL** [comment]
@chenhuan0 - please check in your build, in libtensorflow_framework.so if this function is available (tensorflow::OpDefBuilder::Attr) and what signature it has. You can use following command to test it:
```
nm -C libtensorflow_framework.so | grep tensorflow::OpDefBuilder::Att
```
As a sanity check you can try to build with CUDA 9.x and see if that works.

**Comment by chenhuan0** [comment]
> @chenhuan0 - please check in your build, in libtensorflow_framework.so if this function is available (tensorflow::OpDefBuilder::Attr) and what signature it has. You can use following command to test it:
> 
> ```
> nm -C libtensorflow_framework.so | grep tensorflow::OpDefBuilder::Att
> ```
> As a sanity check you can try to build with CUDA 9.x and see if that works.

The problem is solved after I add --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" to the bazen build command.

**Comment by JanuszL** [comment]
Great!

**Comment by Latootoo** [comment]
> > @chenhuan0 - please check in your build, in libtensorflow_framework.so if this function is available (tensorflow::OpDefBuilder::Attr) and what signature it has. You can use following command to test it:
> > ```
> > nm -C libtensorflow_framework.so | grep tensorflow::OpDefBuilder::Att
> > ```
> > As a sanity check you can try to build with CUDA 9.x and see if that works.
> 
> The problem is solved after I add --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" to the bazen build command.

--cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" should be added to the cmake configuration of DALI !! Not Bazel.

**Comment by JanuszL** [comment]
> > > @chenhuan0 - please check in your build, in libtensorflow_framework.so if this function is available (tensorflow::OpDefBuilder::Attr) and what signature it has. You can use following command to test it:
> > > ```
> > > nm -C libtensorflow_framework.so | grep tensorflow::OpDefBuilder::Att
> > > ```
> > > As a sanity check you can try to build with CUDA 9.x and see if that works.
> > 
> > 
> > The problem is solved after I add --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" to the bazen build command.
> 
> --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" should be added to the cmake configuration of DALI !! Not Bazel.

And it is https://github.com/NVIDIA/DALI/blob/master/dali/CMakeLists.txt#L172
