### ISSUE TITLE
How to use Dali correctly for PyTorch distributed training

### ISSUE THREAD

**Issue by Kyrie10favor** [NVIDIA/DALI#3182]
Dear author, this problem has been bothering me for a long time, could you give me some effective suggestions。
Here are some descriptions ... 
**my ExternalInputIterator**
```
class ExternalInputIterator(object):
    def __init__(self, batch_size,root='',list_list_abspath=['list1.txt','list1.txt'],device_id=0, num_gpus=1):
        self.device_id = device_id
        self.num_gpus = num_gpus
        self.batch_size = batch_size
        self.root = root
        self.img_ids = []
        for list in list_list_abspath:
            for i in open(list):
                self.img_ids.append(i.strip())
        self.allfiles = []

        for name in self.img_ids:
            img_file = osp.join(self.root, name.split()[0])
            label_file = osp.join(self.root, name.split()[1])
            name = name.split(" ")[0].split('/')[-1].split('.')[0]
            self.allfiles.append({"img": img_file, "label": label_file, "name": name})
        # whole data set size
        self.data_set_len = len(self.allfiles)
        # for multi gpu
        self.files = self.allfiles[self.data_set_len * device_id // num_gpus:
                                self.data_set_len * (device_id + 1) // num_gpus]
        self.n = len(self.files)

    def __iter__(self):
        self.i = 0
        shuffle(self.files)
        return self

    def __next__(self):
        batch = []
        labels = []
        if self.i >= self.n:    # self.n = 781
            self.__iter__()
            raise StopIteration

        for _ in range(self.batch_size):
            datafiles = self.files[self.i % self.n]
            f = open(datafiles["img"], 'rb')
            batch.append(np.frombuffer(f.read(), dtype = np.uint8))
            f2 = open(datafiles["label"], 'rb')
            labels.append(np.frombuffer(f2.read(), dtype = np.uint8))
            self.i += 1
        return (batch, labels)
    def __len__(self):
        # return whole dataset size
        return len(self.allfiles)
```
--------------------------------------
**my TrainSet**
```
class TrainSet(object):
    def __init__(self, batch_size=8, crop_size=512,root='',list_list_path=['',''],mean=None, std=None):
        self.batch_size = batch_size
        self.*= *
        ...

    @pipeline_def
    def my_pip(self,external_data):
        jpegs, labels = fn.external_source(source=external_data, num_outputs=2)
        imgs = fn.decoders.image(jpegs, device="mixed", output_type=types.RGB)
        lals = fn.decoders.image(labels, device="mixed", output_type=types.GRAY)
        # some transforms here...
        return (imgs, lals)

    def getDataIterator(self, num_gpus = 4  , device_id = 0):
        bs = self.batch_size // num_gpus
        eii = ExternalInputIterator(batch_size=bs,root=self.root,list_list_abspath=self.list_list_path,device_id=device_id,num_gpus=num_gpus)
        pipe = self.my_pip(external_data=eii, batch_size=bs, num_threads=2, device_id=device_id)    
        # pipe.build()
        data_loader = DALIGenericIterator([pipe], ['imgs', 'label'],size=eii.n, last_batch_policy="DROP"  ,  auto_reset=True)  
        return data_loader
```

---------------------
**Then I use it in my train.py**
```
daset = TrainSet(args.batch_size, crop_size=args.crop_size)
trainLoader = daset.getDataIterator(num_gpus=len((os.environ["CUDA_VISIBLE_DEVICES"]).split(",")),
                                             device_id=args.local_rank)
for iteration, batch in enumerate(train_loader):
        images = batch[0]['imgs']
        labels = batch[0]['label']
        ......

```
---------------------
**The problem I encountered was:**
  When I trained with 4 GPUs，
It takes **47s** to train 1 epoch using the original `torch.utils.distributed.DistributedSampler`, with 12s of getting data in it。
However, It takes **54.1s** to train 1 epoch using the original `the dali_DataIterator` implemented  by me, with 24.2s of getting data in it。
Happily, with Dali, when I used  1 gpu for predicting(infering), the time went from 25s to 13s, thanks to Dali.

What's wrong with my implementation? And how should I modify my code,.
thank u.

**Comment by JanuszL** [comment]
Hi,
In the DALI case the `external_source` provided callback is run synchronously with the main python process/thread, while in PyTorch it is run in parallel. You should check `parallel` and `prefetch_queue_depth` parameters of [the `external_source` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.external_source).

**Comment by Kyrie10favor** [comment]
Thx for your reply.
After reading your reply, I set the params to: `fn.external_source(source=external_data, num_outputs=2, batch=False, parallel= True,)`
And then I get this **error** message:
`
RuntimeError: Cannot fork process when there is CUDA context bound to it. Make sure you build pipeline before CUDA context is acquired or change Python workers starting method from ``fork`` to ``spawn`` (see Piepline's ``py_start_method`` option). If you are trying to build multiple pipelines that use Python workers, you will need to call ``start_py_workers`` method on all of them before calling ``build`` method of any pipeline.
`
I tried the following, but it doesn't work
```
pipe.start_py_workers() # new added
pipe.build()
data_loader = DALIGenericIterator([pipe], ['imgs', 'label'],size=eii.n, last_batch_policy="DROP"  ,  auto_reset=True)
```
What should I do next? thx

**Comment by klecki** [comment]
Hi,
we recently updated the error message, so it might be a bit more helpful at explaining what is going on:
```
Error when starting Python worker threads for DALI parallel External Source. 
Cannot fork a process when there is a CUDA context already bound to the process. 
CUDA context is acquired during ``Pipeline.build()``, or can be acquired by another 
library that interacts with CUDA, for example a DL framework creating CUDA tensors.
If you are trying to build multiple pipelines that use Python workers, you will need to 
call ``start_py_workers`` method on all of them before calling ``build`` method of any pipeline 
to start Python workers before CUDA context is acquired by ``build`` or other CUDA operation.
Alternatively you can change Python workers starting method from ``fork`` to ``spawn`` 
(see DALI Pipeline's ``py_start_method`` option for details). 
```

Basically, you need to call `start_py_workers` on the pipeline before you start interacting with CUDA - which is done in `pipe.build()`, under the hood of DALIGenericIterator or by other Deep Learning framework that accesses CUDA. The alternative is to change the Pipeline's `start_py_workers` parameter to `spawn`, but it has some additional limitations - the `source` for External Source needs to be the some module-level function in most cases.

**Comment by Kyrie10favor** [comment]
@klecki @JanuszL 
I tried two ways to call start_py_workers, but it still doesn't work.
I still get the same error message as before,, I think i don't know how to call ' 'start_py_workers'' method before calling ' 'build' 'method of any pipeline. 
btw, i also try to set `py_start_method ="spawn"`, It looks more complicated .

_Can you help implement this part of the code?_ 

(way1)
```
def getDataIterator(self, num_gpus = 4  , device_id = 0):
    bs = self.batch_size // num_gpus
    eii = ExternalInputIterator(batch_size=bs,root=self.root,list_list_abspath=self.list_list_path,device_id=device_id,num_gpus=num_gpus)
    pipe = ExternalSourcePipeline(eii=eii, batch_size=bs, num_threads=2, device_id=device_id,))    
    pipe.start_py_workers() # call it before pipe.build()
    pipe.build()
    data_loader = DALIGenericIterator([pipe], ['imgs', 'label'],size=eii.n, last_batch_policy="DROP"  ,  auto_reset=True)
    return data_loader
```
(way2)
```
def ExternalSourcePipeline(eii=None,batch_size=0, num_threads=2, device_id=0, crop_size=512,mean=0, std=0):
    pipe = Pipeline(batch_size, num_threads, device_id)
    # pipe.start_py_workers() # Call it here, it will raise 'NotImplementedError'
    with pipe:
        jpegs, labels = fn.external_source(source=eii, num_outputs=2,  )#batch=False,parallel=True, prefetch_queue_depth=2)
        # pipe.start_py_workers() # Call it here, it will raise 'NotImplementedError'
        imgs = fn.decoders.image(jpegs, device="mixed", output_type=types.RGB)
        lals = fn.decoders.image(labels, device="mixed", output_type=types.GRAY)
        
       shapes = fn.peek_image_shape(jpegs) 
        size = fn.slice(shapes, 0, 2, axes=[0])

        w = fn.slice(shapes, 1, 1, axes=[0])  # extract width
        h = fn.slice(shapes, 0, 1, axes=[0])  # extract height
        ratio = (w > h) * crop_size / w + (h > w) * crop_size / h 
        imgs = fn.resize(imgs, size=size * ratio, mode='not_smaller', interp_type=types.INTERP_LINEAR)  # Same scaling
        lals = fn.resize(lals, size=size * ratio, mode='not_smaller', interp_type=types.INTERP_NN)

        imgs = fn.pad(imgs, fill_value=0, axes=(0, 1), shape=(crop_size, crop_size)) 
        lals = fn.pad(lals, fill_value=0, axes=(0, 1), shape=(crop_size, crop_size))
        imgs = fn.crop_mirror_normalize(imgs, dtype=types.FLOAT, mean=mean, std=std)
        pipe.set_outputs(imgs, lals)
    return pipe
```

**Comment by klecki** [comment]
@Kyrie10favor,
what it means, is if you have more than 1 pipeline in your script (be it either training and validation) or build several pipelines for several GPUs you need to do something like:

```
list_of_pipes = [GetTrainPipeline(i) for i in ranks] # collect all pipelines, but do not build them
list_of_pipes += [GetValidationPipeline(i) for i in ranks] # same here, do not build them

for pipe in list_of_pipes:
    pipe.start_py_workers() # we need to start workers of all pipelines (that use workers)

for pipe in list_of_pipe:
    pipe.build()  # workers started, now we can build, the first one will take CUDA context
```

It's roughly what I meant.

Also in the case of parallel External Source, the `source` can't be an iterator - we distribute the `source` to all of the workers and than we wouldn't be able to acquire samples without duplicating the work (just by calling next()).

You can a callable (function or object if you wish to capture some initial parameters) that accepts one argument of type [SampleInfo](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/data_types.html#nvidia.dali.types.SampleInfo) - it will describe the index of requested sample.

I'm adjusting the checks in External Source and documentation to mention that, sorry for the confusion.

**Comment by huxuan** [comment]
After looking through the documentation, I wonder if there is any demo for production integration of DALI and PyTorch. To be more specifically, better to have a demo combines parallel external source, DALIGenericIterator and DistributedDataParallel for multi-node distributed training.

**Comment by JanuszL** [comment]
Hi @huxuan,

> a demo combines parallel external source, DALIGenericIterator and DistributedDataParallel for multi-node distributed training

We don't have such a full e2e demo. I recommend checking
- https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/frameworks/pytorch/pytorch-external_input.html
- https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/parallel_external_source.html
- https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/use_cases/pytorch/resnet50/pytorch-resnet50.html

and building on top of it.
