### ISSUE TITLE
dali_test_matching.h

### ISSUE THREAD

**Issue by tendar** [NVIDIA/DALI#3183]
Hi, I have a question about this function in the file of "dali_test_matching.h"

  Reference(const vector<TensorList<CPUBackend>*> &inputs, DeviceWorkspace *ws) override {
    if (GetOpType() == OpType::GPU)
      return this->CopyToHost(ws->Output<GPUBackend>(1));
    else
      return this->CopyToHost(ws->Output<CPUBackend>(1));
  }

why you get the second output with the index = 1,by return this->CopyToHost(ws->Output<GPUBackend>(1));
should it be index = 0,by return this->CopyToHost(ws->Output<GPUBackend>(0)); ?
Because i see another funtion writen like this in the file of dali_test_sigle_op.h

  void RunOperator(const OpSpec& spec, double eps, DeviceWorkspace *pWS = nullptr) {
    AddSingleOp(spec);
    DeviceWorkspace ws;
    if (!pWS)
      pWS = &ws;
    RunOperator(pWS);
    SetEps(eps);
    CheckAnswers(pWS, {0});
  }
  void CheckAnswers(DeviceWorkspace *ws,
                    const vector<int>& output_indices) {
    // outputs_ contains map of idx -> (name, device)
    auto res = Reference(input_data_, ws);

    std::unique_ptr<TensorList<CPUBackend>> calc_output(new TensorList<CPUBackend>());
    // get outputs from pipeline, copy to host if necessary
    for (size_t i = 0; i < output_indices.size(); ++i) {
      auto output_device = outputs_[i].second;

      auto idx = output_indices[i];
      if (output_device == "gpu") {
        // copy to host
        calc_output->Copy(ws->Output<GPUBackend>(idx), nullptr);
      } else {
        calc_output->Copy(ws->Output<CPUBackend>(idx), nullptr);
      }

      auto& ref_output = res[i];
      calc_output->SetLayout(ref_output->GetLayout());

      // check calculated vs. reference answers
      CheckTensorLists(calc_output.get(), ref_output.get());
    }
  }

    CheckAnswers(pWS, {0}); check the first tensorList buffer

**Comment by JanuszL** [comment]
Hi @tendar,

Please check the comment a couple of lines before:
```
    // Launching the same transformation on CPU (outputIdx 0) and GPU (outputIdx 1)
    this->AddOperatorWithOutput(descr);
    this->RunOperator(descr);
```
.
I think you are mixing two tests that look similar but work a bit differently. The first one checks CPU vs GPU implementation while the second checks the DALI implementation vs a reference implemented inside the test.
Could you tell me what you want to achieve? Now we mostly moved to python level test where we test DALI output with the reference implemented in other python libraries.

**Comment by tendar** [comment]
Hi, Januszl
Thank you for your reply. I got it. So The this test, we create two  outputs, the first one is create by cpu operator, and the second one is create by the GPU operator, and then we comprare the two results.
Thx. 
I heard that the framework of DALI is very clear and good designed, so i want to read all the source code of DALI to impove my ability.
THX again!
