### ISSUE TITLE
Raw vs Encoded (jpeg, png) images loading speed with tfrecord

### ISSUE THREAD

**Issue by dorucia** [NVIDIA/DALI#3186]
Hi,

I have two quick questions.

Which way is faster to load an image with dali?
1) Raw image data saved in tfrecord
2) Jpeg encoded data saved in tfrecord

In addition, will method 1) also benefit from dali?

**Comment by JanuszL** [comment]
Hi @dorucia,

In the case of 1) the IO would be probably a bottleneck, as reading encoded data and decoding it would be faster. It may very much depend on your IO speed (spinning drive vs SSD vs network storage). 

> In addition, will method 1) also benefit from dali?

Loading itself won't benefit much but if you perform online random transformations then using DALI and offloading to the GPU should help. If you just want to load the data you may not see any benefit.

**Comment by dorucia** [comment]
Thank you!
