### ISSUE TITLE
Question: How to use images as ground truth?

### ISSUE THREAD

**Issue by thierrypin** [NVIDIA/DALI#3192]
This question has been asked before, but it has been a while and a lot has changed in DALI. In that issue (https://github.com/NVIDIA/DALI/issues/274), the answer was to use external source, which I did for a while.

But then I attended a workshop given by a Nvidia employee, here in Brazil, and he told me I could use two FileReaders, as long as the files in both readers had the same names -- it works well, but I can not always rename the files to match. Is there a way to match the readers with different filenames?

**Comment by JanuszL** [comment]
Hi @thierrypin,

The external source should still work. If you prefer to use the file reader operator you can provide a list of files as the `files` argument. If you set the same seed to each reader to order of reading from all provided lists should be the same.
