### ISSUE TITLE
3D zoom in/out (and along a certain direction) 

### ISSUE THREAD

**Issue by llodds** [NVIDIA/DALI#3194]
Does DALI provide 3D zoom in/out and keep the original cube size? Or do I have to build some operators on my own? Also, does DALI provide 3D zoom in/out along a certain axis direction?

Thanks

**Comment by JanuszL** [comment]
Hi @llodds,

Please check [the `resize` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.resize). It can transform 2D and 3D data in all axis separately.
Please check [this](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/image_processing/resize.html) and [this](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/image_processing/3d_transforms.html#Result:-Resize) tutorials.

**Comment by llodds** [comment]
@JanuszL Thanks. I will take a try.
