### ISSUE TITLE
Not sure how to use ElementExtract

### ISSUE THREAD

**Issue by dorucia** [NVIDIA/DALI#3197]
Hi,

I'm trying to use ElementExtract but getting an error.

Here's my input and how I use the operation.

Input
- Saved in tfrecord
- Nx1 matrix where N is varying per example. Therefore I define decoder using VarLenFeature, e.g.,
`'x': tfrec.VarLenFeature(tfrec.float32, 0.0),`

How I use ElementExtract
- `dali_ops.ElementExtract(device='gpu', element_map=[0,1,2])(features['x'].gpu())`

Error
- TypeError: 'nvidia.dali.backend_impl.tfrecord.Feature' object is not iterable

Am I missing something?

**Comment by JanuszL** [comment]
Hi @dorucia,

Can you provide a full code that causes that problem?
How the `features` variable is defined in your case?
I recommend checking [this TFRecord loading example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/dataloading_tfrecord.html#Overview) for reference.

**Comment by dorucia** [comment]
Hi,
I found a typo in my `features` variable definition.
I fixed the typo and it leads me to the next error message.
Please allow me to ask without the full code.

- Variable `features['x']`: <nvidia.dali.pipeline.DataNode object at 0x7fdc24fd8400>
- Output from ElementExtract:  [<nvidia.dali.pipeline.DataNode object at 0x7fdc24fdf710>, <nvidia.dali.pipeline.DataNode object at 0x7fdc24fdf748>, <nvidia.dali.pipeline.DataNode object at 0x7fdc24fdf780>]
- Error: TypeError: Expected outputs of type compatible with "DataNode". Received output type with name "list" that does not match.

**Comment by dorucia** [comment]
Found this reply https://github.com/NVIDIA/DALI/issues/1716#issuecomment-816766440
so I tried

```
x = dali_ops.ElementExtract(device='gpu', element_map=[0,1,2])(features['x'].gpu())
x = dali_ops.Stack(device='gpu')(*x)
```

but I got this error. 

`AttributeError: module 'nvidia.dali.ops' has no attribute 'Stack'`

hmm..?

**Comment by klecki** [comment]
@dorucia What version of DALI do you use? Stack was added in DALI 0.28.

ElementExtract gives you as many outputs as you requested in element_map, so you got 3 data nodes representing 3 batches.

**Comment by dorucia** [comment]
Thank you, it works with a newer version.
