### ISSUE TITLE
WebP support for the image decoder

### ISSUE THREAD

**Issue by lbhm** [NVIDIA/DALI#3203]
According to the DALI docs at [nvidia.com](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.decoders.image), the image decoder does not support the WebP format. Are there any plans to support WebP in the future? I couldn't find any information about that in the 2021 roadmap, prior issues, or on Google so please excuse me if this has been answered before.

**Comment by JanuszL** [comment]
Hi @lbhm,

DALI doesn't support WebP format and we don't have that in our 2021 roadmap.
If you are willing to contribute to DALI we would be more than happy to review and accept a PR adding such functionality.

The necessary steps that come to my mind are:
- update how OpenCV for DALI is built and enable WebP format support [there](https://github.com/NVIDIA/DALI_deps/blob/main/build_scripts/build_opencv.sh)
- add WebP format test data to [DALI_extra repository](https://github.com/NVIDIA/DALI_extra/tree/main/db/single)
- add WebP support to [image_factory](https://github.com/NVIDIA/DALI/blob/main/dali/image/image_factory.cc)
- extend [the decoder test](https://github.com/NVIDIA/DALI/blob/main/dali/test/python/test_operator_decoders_image.py) to check if WebP data is decoded correctly

**Comment by lbhm** [comment]
Hi @JanuszL,

Thank you for the quick response. I will try working on a PR and see if I can figure it out with my limited C++ knowledge.

One question regarding the DALI_extra repo since I'm not a license expert: Am I allowed to simply take some of the existing images (e.g., the `jpeg` folder), recompress them as WebP, and commit them to the repo?

**Comment by JanuszL** [comment]
Hi,

> One question regarding the DALI_extra repo since I'm not a license expert: Am I allowed to simply take some of the existing images (e.g., the `jpeg` folder), recompress them as WebP, and commit them to the repo?

Yes, you can (we do like this, and the image there have permissive license), still, you need to sign [the CLA](https://github.com/NVIDIA/DALI_extra#contributing) and send it to us via mail. If for any reason you cannot do that we can create a WebP data when your PR is ready for testing.

**Comment by lbhm** [comment]
Solved in 0bec4dcf3d1093dd2a7ef9d3dfebb9ff402c6a82
