### ISSUE TITLE
failing to run the basic example

### ISSUE THREAD

**Issue by danbider** [NVIDIA/DALI#3218]
I'm trying to run the basic Getting Started tutorial. https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/getting_started.html.

```
from nvidia.dali import pipeline_def
import nvidia.dali.fn as fn
import nvidia.dali.types as types

image_dir = "data/images"
max_batch_size = 8


@pipeline_def
def simple_pipeline():
    jpegs, labels = fn.readers.file(file_root=image_dir)
    images = fn.decoders.image(jpegs, device='cpu')

    return images, labels
```

Running on CUDA 11.

Initializing the instance:
`pipe = simple_pipeline(batch_size=max_batch_size, num_threads=1, device_id=0)`

Results in:
`TypeError: simple_pipeline() got an unexpected keyword argument 'batch_size'`

any ideas what's wrong?

**Comment by JanuszL** [comment]
Hi @danbider,

Which DALI version do you have? Can you update to 1.4?

**Comment by danbider** [comment]
using:
nvidia-dali-cuda110               1.4.0

**Comment by JanuszL** [comment]
Hi @danbider,

It works fine on my side. You can try it out in docker:
```
docker run --rm -ti --gpus all ubuntu:20.04
```
Then inside:
```
apt update && apt install -y python3 python3-pip && \
pip3 install pip --upgrade && pip install --extra-index-url https://developer.download.nvidia.com/compute/redist --upgrade nvidia-dali-cuda110  && \
echo "from nvidia.dali import pipeline_def
import nvidia.dali.fn as fn
import nvidia.dali.types as types

image_dir = 'data/images'
max_batch_size = 8

@pipeline_def
def simple_pipeline():
    jpegs, labels = fn.readers.file(file_root=image_dir)
    images = fn.decoders.image(jpegs, device='cpu')

    return images, labels
pipe = simple_pipeline(batch_size=max_batch_size, num_threads=1, device_id=0)
" > test.py  && \
python3 test.py
```
No error is raised.

**Comment by danbider** [comment]
trying it out soon in Docker... I tried to install `nvidia-dali` as in the installation guides, and i'm using a [Grid.ai ](https://www.grid.ai/) session. During installation, I get 
```WARNING: Ignoring invalid distribution -ygments (/home/jovyan/conda/lib/python3.8/site-packages)```
have you seen this before?

**Comment by JanuszL** [comment]
Hi @danbider,

My intention was to show that it works on clean insulation. I'm sorry but I haven't used Grid.ai so I cannot tell much about the source of the error.
