### ISSUE TITLE
How to pad left or top to a image?

### ISSUE THREAD

**Issue by DatCanCode** [NVIDIA/DALI#3219]
In opencv there's a function call `copyMakeBorder` that can pad solid color to 4 sides around an image:

`cv2.copyMakeBorder(im, top, bottom, left, right, cv2.BORDER_CONSTANT, value=color)`

 but in DALI I found that `nvidia.dali.fn.pad` function only pad to right/bottom. I want to pad to 4 sides around an image with out padding, then flip, then pad and flip back. How can I do that in DALI.
Thank you!

**Comment by JanuszL** [comment]
Hi @DatCanCode,

There is no direct OpenCV `copyMakeBorder` counterpart in DALI. What you can try is:
- check [the paste operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.paste)
- write your own operator using [this guide](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/custom_operations/index.html)

**Comment by wangchengdng** [comment]
Hello, we have similar needs, is this solved now?

**Comment by jantonguirao** [comment]
I'd add that you can also control the value used for padding with `fill_value`, and that you can use absolute coordinates for slice arguments as well. You can see the full documentation here: https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.slice.html
