### ISSUE TITLE
RuntimeError - Dali + Pytorch Lightning + DDP

### ISSUE THREAD

**Issue by psandev** [NVIDIA/DALI#3229]
Hi,
I am running action recognition on 4xT4s and I encounter a runtime error at the end of the second epoch. I am pretty sure that the issue is related to the last batch definition, since the error does not occur when I run with a specific number of batches.
Another weird thing is that it happens at the end of the second training epoch, the first one (train + val) 
passes with no issue.
I suspect incorrect pipelines and iterators definitions , but after more than a week at this,  I am at the end of my wits.
If I use last_batch_policy=LastBatchPolicy.PARTIAL the runtime error does not happen, but the output of my validation epoch are all zeros. 
Attaches is my code and the error stack. Thanks a lot.

Setup:
Ubuntu 18.04
Dali - latest version 1.4.0 +cu11.0
Pytotch Lightning - latest version  1.4.1
Pytorch  - 1.8.0+cu11.1

[dali_runtime_error.txt](https://github.com/NVIDIA/DALI/files/6945728/dali_runtime_error.txt)
[dali_train.txt](https://github.com/NVIDIA/DALI/files/6945729/dali_train.txt)

**Comment by psandev** [comment]
Some more info:
if pad_last_batch=False the error doe snot occur, but then I do not have output from validation_epoch_end  after epoch 0. I calculate confusion matrix  in train_epoch_end and validation_epoch_end, but for some reason validation_epoch_end is skipped after epoch 0. Here is my log:
Epoch 0:  17%|█████████████████████████▎                                                                                                                        | 99/570 [02:29<11:44,  1.50s/it, t_f1_step=0.133, t_acc_step=0.250, t_loss_step=0.305]wandb: Network error (ConnectTimeout), entering retry loop.
Epoch 0:  18%|██████████████████████████                                                                                                                      | 103/570 [02:36<11:41,  1.50s/it, t_f1_step=0.310, t_acc_step=0.812, t_loss_step=0.0398]wandb: Network error resolved after 0:00:39.055846, resuming normal operation.
Epoch 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋| 569/570 [14:11<00:01,  1.49s/it, t_f1_step=0.489, t_acc_step=0.938, t_loss_step=0.01162021-08-06 13:36:26.182 | INFO     | __main__:validation_epoch_end:242 - █████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 115/115 [01:16<00:00,  1.51it/s]
Epoch=0, Val Confusion matrix:
 tensor([[144., 104.,  32.,   4.,   4.,   0.],
        [116., 300.,  24.,   0.,   0.,   0.],
        [  8.,  20., 248.,   0.,   0.,   0.],
        [  8.,   0.,   0., 216., 120.,   0.],
        [  0.,   0.,   0.,  36., 248.,   4.],
        [  0.,   0.,   0.,   0.,   0., 204.]], device='cuda:0')
2021-08-06 13:36:26.189 | INFO     | __main__:validation_epoch_end:249 - 
Epoch=0/50, val_f1=0.75, val_acc=0.74, val_loss=0.05096, lr_rate=0.00500
Epoch 0: 100%|████████████████████████████████| 570/570 [14:13<00:00,  1.49s/it, t_f1_step=0.489, t_acc_step=0.938, t_loss_step=0.0116, v_f1_step=0.300, v_acc_step=0.750, v_loss_step=0.0851, v_f1_epoch=0.754, v_acc_epoch=0.739, v_loss_epoch=0.0512021-08-06 13:36:26.199 | INFO     | __main__:training_epoch_end:264 -                                                                                                                                                                                  
Epoch=0, Train Confusion matrix:
 tensor([[604., 394., 160.,  18.,  28.,   0.],
        [420., 721., 161.,  23.,  23.,   0.],
        [138., 204., 851.,   4.,   7.,   0.],
        [ 32.,  11.,  11., 813., 358.,  27.],
        [  3.,  14.,  12., 378., 912.,  49.],
        [  1.,   0.,   6.,  52.,  70., 775.]], device='cuda:0')
2021-08-06 13:36:26.206 | INFO     | __main__:training_epoch_end:272 - Epoch=0/50, train_f1=0.65, train_acc=0.64, train_loss=0.09357, lr_rate=0.00500
Epoch 1:  80%|▊| 454/570 [13:37<03:28,  1.80s/it, t_f1_step=0.500, t_acc_step=1.000, t_loss_step=0.000172, v_f1_step=0.300, v_acc_step=0.750, v_loss_step=0.0851, v_f1_epoch=0.754, v_acc_epoch=0.739, v_loss_epoch=0.051, t_f1_epoch=0.655, t_acc_epoc2021-08-06 13:50:04.874 | INFO     | __main__:training_epoch_end:264 - 
Epoch=1, Train Confusion matrix:
 tensor([[      801.,       350.,       101.,        10.,        10.,         0.],
        [      369.,       790.,       129.,         4.,         4.,         0.],
        [      101.,        91.,      1016.,         0.,         0.,         0.],
        [       12.,         4.,         4.,       810.,       289.,         5.],
        [       12.,         8.,         2.,       282.,      1162.,        22.],
        [        0.,         0.,         1.,         7.,        16.,       852.]], device='cuda:0')
2021-08-06 13:50:04.881 | INFO     | __main__:training_epoch_end:272 - Epoch=1/50, train_f1=0.76, train_acc=0.75, train_loss=0.04941, lr_rate=0.00500
Epoch 2:  80%|▊| 454/570 [13:38<03:28,  1.80s/it, t_f1_step=0.465, t_acc_step=0.875, t_loss_step=0.00646, v_f1_step=0.300, v_acc_step=0.750, v_loss_step=0.0851, v_f1_epoch=0.754, v_acc_epoch=0.739, v_loss_epoch=0.051, t_f1_epoch=0.758, t_acc_epoch2021-08-06 14:03:43.028 | INFO     | __main__:training_epoch_end:264 - 
Epoch=2, Train Confusion matrix:
 tensor([[      610.,       443.,       109.,        23.,         7.,         0.],
        [      374.,       937.,       118.,         7.,         0.,         0.],
        [      105.,       112.,       875.,         0.,         0.,         0.],
        [        7.,         2.,         0.,       903.,       264.,        12.],
        [        6.,         3.,         1.,       205.,      1196.,         5.],
        [        0.,         0.,         3.,         6.,         1.,       930.]], device='cuda:0')
2021-08-06 14:03:43.034 | INFO     | __main__:training_epoch_end:272 - Epoch=2/50, train_f1=0.76, train_acc=0.75, train_loss=0.04998, lr_rate=0.00500
Epoch 3:  60%|▌| 343/570 [10:18<06:48,  1.80s/it, t_f1_step=0.426, t_acc_step=0.875, t_loss_step=0.0046, v_f1_step=0.300, v_acc_step=0.750, v_loss_step=0.0851, v_f1_epoch=0.754, v_acc_epoch=0.739, v_loss_epoch=0.051, t_f1_epoch=0.759, t_acc_epoch=

**Comment by JanuszL** [comment]
Hi @psandev,

It looks that `RuntimeError: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema` means that the batch is empty. However, I don't see any clear reason why.

> but the output of my validation epoch are all zeros.
Can you check how the DALI validation pipeline output looks like in that case?

> if pad_last_batch=False the error doe snot occur, but then I do not have output from validation_epoch_end after epoch 0
Can you dry run the pipeline without the network and double-check if DALI doesn't return any output in such a case?

Can you try to create [a minimal and self-contained repro](https://github.com/NVIDIA/DALI#reporting-problems-asking-questions) we can run on our side that? You can use data from https://github.com/NVIDIA/DALI_extra repository.

**Comment by psandev** [comment]
Hi guys,
thanks for the swift response. I created a minimalist example  with a small sample of my data, which is in the data folder.
please, install https://github.com/facebookresearch/TimeSformer , download the pretrained model https://www.dropbox.com/s/g5t24we9gl5yk88/TimeSformer_divST_8x32_224_K400.pyth?dl=0 and place in the models folder.
The script is configured for a single gpu. Please, change the cofig.run,n_gpu parameter to  run on multiple gpus. Thanks again.


[for_dali_debug.zip](https://github.com/NVIDIA/DALI/files/6948871/for_dali_debug.zip)

**Comment by psandev** [comment]
Hi guys,
it turned out it was a PL bug. The validation output list from the second epoch was completely empty.
I downgraded to 1.38 and the bug disappeared. A few days ago I downgraded to 1.40 and the bug was there, so I thought there is no point to go further back, but today I went crazier than usual and there it was  :). Thanks anyway.

**Comment by JanuszL** [comment]
Hi @psandev,

Pytorch Lightning is rapidly evolving. It is possible that the internal implementation changes and the code that used to work no longer work. I would recommend checking [this example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/frameworks/pytorch/pytorch-lightning.html) to see how DALI can be used with PL.
