### ISSUE TITLE
Core dump with self-compiled tensorflow

### ISSUE THREAD

**Issue by chenhuan0** [NVIDIA/DALI#323]
Hi,

I'm compiling the source of tensorflow to train resnet50 with imagenet. But I found that while I use "-march=native -O3" compile options to compile tensorflow. DALI will got Core Dump. So does -O2.

When I remove -O3 or -O2, only keep "-march=native", DALI works well. However, I need to use the optimization options to achieve a higher throughput. Is there a way to solve this? Or do you have the same issues?

Thanks

**Comment by chenhuan0** [comment]
BTW: The tensorflow version is 1.12.0, bazel-0.18.1, the source is from the official github.

**Comment by chenhuan0** [comment]
@cliffwoolley I already pass the --cxxopt=-D_GLIBCXX_USE_CXX11_ABI=0 to the bazel build commandline, if not the DALI cannot be imported.

However, it still got core dump after I used -O2/-O3.

**Comment by cliffwoolley** [comment]
Hmm, ok, seems we need to dig in a bit more, then.  Which version of DALI are you working with?  Can you please provide a backtrace of the crash?

**Comment by JanuszL** [comment]
@chenhuan0 - please also provide exact way how you build TF on your own, if it works without DALI and some simple, minimal repro script too.
Thanks!
