### ISSUE TITLE
/tmp/file_list_frame_num.txt  could not be opened.

### ISSUE THREAD

**Issue by tendar** [NVIDIA/DALI#3230]
Hi, i meet some test case is failed, could you please help me find the reason?
serval test case is failed as follows, cause could not open the /tmp/file.
[ RUN      ] VideoReaderTest.FrameLabelsWithFileListFrameNum
unknown file: Failure
C++ exception with description "Critical error when building pipeline:
Error when constructing operator: VideoReader encountered:
[/root/dali-1.3.0/DALI/dali/operators/reader/loader/video_loader.cc:147] Assert on "s.is_open()" failed: /tmp/file_list_frame_num.txt could not be opened.
Stacktrace (20 entries):
[frame 0]: /root/dali-1.3.0/DALI/build/dali/python/nvidia/dali/libdali_operators.so(+0x492f06) [0x7f33afc4bf06]
[frame 1]: /root/dali-1.3.0/DALI/build/dali/python/nvidia/dali/libdali_operators.so(+0x27f9d81) [0x7f33b1fb2d81]
[frame 2]: /root/dali-1.3.0/DALI/build/dali/python/nvidia/dali/libdali_operators.so(+0x28f4c52) [0x7f33b20adc52]
[frame 3]: /root/dali-1.3.0/DALI/build/dali/python/nvidia/dali/libdali_operators.so(+0x28f74cf) [0x7f33b20b04cf]
[frame 4]: /root/dali-1.3.0/DALI/build/dali/python/nvidia/dali/libdali_operators.so(+0x28f8ae2) [0x7f33b20b1ae2]
[frame 5]: ./dali_operator_test.bin(std::_Function_handler<std::unique_ptr<dali::OperatorBase, std::default_delete<dali::OperatorBase> > (dali::OpSpec const&), std::unique_ptr<dali::OperatorBase, std::default_delete<dali::OperatorBase> > (*)(dali::OpSpec const&)>::_M_invoke(std::_Any_data const&, dali::OpSpec const&)+0x20) [0x55c2ef5e1270]
[frame 6]: /root/dali-1.3.0/DALI/build/dali/python/nvidia/dali/libdali.so(+0x124448) [0x7f33aec04448]
[frame 7]: /root/dali-1.3.0/DALI/build/dali/python/nvidia/dali/libdali.so(dali::InstantiateOperator(dali::OpSpec const&)+0x2a5) [0x7f33aec01445]
[frame 8]: /root/dali-1.3.0/DALI/build/dali/python/nvidia/dali/libdali.so(dali::OpGraph::InstantiateOperators()+0xaf) [0x7f33aebb3f7f]
[frame 9]: /root/dali-1.3.0/DALI/build/dali/python/nvidia/dali/libdali.so(dali::Pipeline::Build(std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >)+0x8bc) [0x7f33aec1b69c]
[frame 10]: ./dali_operator_test.bin(+0x4f658a) [0x55c2ef60658a]
[frame 11]: ./dali_operator_test.bin(+0x56848a) [0x55c2ef67848a]
[frame 12]: ./dali_operator_test.bin(+0x556f33) [0x55c2ef666f33]
[frame 13]: ./dali_operator_test.bin(+0x5570f8) [0x55c2ef6670f8]
[frame 14]: ./dali_operator_test.bin(+0x557371) [0x55c2ef667371]
[frame 15]: ./dali_operator_test.bin(+0x55e20c) [0x55c2ef66e20c]
[frame 16]: ./dali_operator_test.bin(+0x55e551) [0x55c2ef66e551]
[frame 17]: ./dali_operator_test.bin(+0xf9217) [0x55c2ef209217]
[frame 18]: /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f339c70ebf7]
[frame 19]: ./dali_operator_test.bin(+0xf9a1a) [0x55c2ef209a1a]

Current pipeline object is no longer valid." thrown in the test body.
[  FAILED  ] VideoReaderTest.FrameLabelsWithFileListFrameNum (3 ms)

**Comment by JanuszL** [comment]
Hi @tendar,

Please check [this file](https://github.com/NVIDIA/DALI/blob/main/qa/TL0_self-test/test.sh#L3) and see how data is prepared for the failing test cases.
I hope that helps.
