### ISSUE TITLE
Loading sequence of images in GPU / mixed mode

### ISSUE THREAD

**Issue by devashishshankar** [NVIDIA/DALI#3232]
Hi, I'm new to DALI and was evaluating it to speed up our NN training pipelines. Our use-case involves reading a sequence of images - and `readers.video` or `readers.video_resize` works perfectly for us. However, I'm finding two issues with it:
* I'm finding it slow compared to image reader. I could at max achieve 400 images/sec using 1 T4 GPU, compared to 1900 images/sec I got on the same hardware using image reader (4 threads).
* It requires constant FPS videos. Our video storage is variable FPS - and hence I'll need to re-encode all my videos to use this, which would be quite costly (and slow down the overall pipeline)

In the above experiments, I was reading a 720p video - and resizing the final images to [320,320]. My sequence length is 64. Increasing number of threads, somehow didn't help the speed of readers.video (but immensely helped in case of decoders.image)

I know that there is a `readers.sequence` - which is exactly what I want, but it doesn't support mixed mode and hence is very slow. So, my question is - can I somehow use ExternalSource operator along with `decoders.image` to read 64 images as part of each sample - convert it to a [D, H, W, C] tensor, and apply augmentations - just like `readers.video`? I tried something along the lines but got stuck with numpy array deserialization issues. I am reading images into numpy string arrays just like [here](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/external_input.html). But I want to read 64 images in one sample - hence I made batch=False - but then it couldn't handle string arrays. (I got the error `Cannot create type for unknown format string: O`)

So, is this route something I should explore? Or is `readers.video` the only way to do this? If the latter, can I do something to speed the video reader up?

**Comment by JanuszL** [comment]
Hi @devashishshankar,

The Video Reader operator performance very much depends on the `stride` (if it is bigger than 1 DALI still needs to decode frames but drops them). Also, DALI does seek inside the video for each sequence it decodes and it takes time as well.
Regarding Variable Frame support, this is a work in progress.
`readers.sequence` implementation is rudimentary and we don't plan to extend it in the near future, but we would be more than happy to review a PR that would implement it.
What you can do now is, load the `sequence_lenght` number of inputs in parallel, decode, and then stack it:
```
import numpy as np
import nvidia.dali.fn as fn
from nvidia.dali import pipeline_def

batch_size = 4
sequence_lenght = 4

def get_data():
    out = [[np.fromfile("/home/jlisiecki/Dali/DALI_extra/db/single/jpeg/100/swan-3584559_640.jpg", dtype=np.uint8)]*sequence_lenght for _ in range(batch_size)]
    return out

@pipeline_def
def simple_pipeline():
    jpegs = fn.external_source(source=get_data, num_outputs=sequence_lenght)
    images = fn.decoders.image(jpegs)
    sequence = fn.stack(*images)
    sequence = fn.reshape(sequence, layout="DHWC")
    return sequence

pipe = simple_pipeline(batch_size=batch_size, num_threads=4, prefetch_queue_depth=2, device_id=0)
pipe.build()
pipe.run()
out = pipe.run()[0]
print(np.array(out[0]).shape)
```
However, it will create a `sequence_lenght` number of decoder instances, in the case of `mixed` backend you can run out for the GPU memory (as each instance uses GPU memory).

**Comment by devashishshankar** [comment]
Thanks for your quick reply! The above snippet works, but I think seq_len and batch_size need to be interchanged:

```
def get_data():
    out = [[np.fromfile("/home/jlisiecki/Dali/DALI_extra/db/single/jpeg/100/swan-3584559_640.jpg", dtype=np.uint8)]*batch_size for _ in range(sequence_lenght)]
    return out
```

However, as you had guessed GPU memory usage is pretty high - and I didn't find this very fast as well.

I was fiddling a bit more, and I decoded the videos using `skip_vfr_check=True` and it didn't hang and decoded the correct number of frames. For the original videos, I was able to decode them at 800 FPS (With re-encoded constant FPS videos I got 400 fps, but that may be due to some optimization not done during re-encode). 800 fps / GPU is actually more than enough for my use case.

A bit more about my use case - I'm not interested in timestamps within the videos. Our labelled data is based on frame_ids within the videos - and as long as correct frames are returned, we are good. So even if I use `file_list`, I will keep `file_list_frame_num=True`. AFAIU, the VFR issue is related to fetching the correct timestamp right? So, is it okay to assume that we won't hit the issue if we're just fetching data based on frame_nums?

**Comment by JanuszL** [comment]
Hi @devashishshankar,

You are right, I have switched `batch_size` and `sequence_lenght`

> AFAIU, the VFR issue is related to fetching the correct timestamp right? So, is it okay to assume that we won't hit the issue if we're just fetching data based on frame_nums?
The issue is not about returning the timestamps but rather how the DALI video reader works internally. When DALI reads the video it checks its fps, length, and calculates the number of frames it can read from it. It builds the list of all available sequences with a given length, stride, and step. Then it picks one of the sequences (randomly or in order) and reads it - seeks to the first frame from sequences (a keyframe preceding it to be precise so the decoding can be resumed) and decodes the frames. The decoder returns the frame and its timestamp (so the application knows when to display it), DALI uses this timestamp and fps to calculate the frame number. In the case of VFR, DALI may wait for frame X but there is not frame with a given number (timestamp) as the frames are not equally distributed over the time domain.

**Comment by devashishshankar** [comment]
Got you, thanks. I actually decoded 100+ videos from my dataset using DALI and didn't hit the issue, but that could just be because our videos are almost constant frame rate (but that is not guaranteed). But, I see that the fix is in 2021 roadmap, which is great!

I had a different question on data augmentations. Is it possible to use augmentations like rotate, HSV, brightness_contrast augmentations for video data? I could only make certain transform like `erase` work for videos. Is there a way to make image processing transforms work for videos - or is it in the roadmap?

**Comment by JanuszL** [comment]
> Got you, thanks. I actually decoded 100+ videos from my dataset using DALI and didn't hit the issue, but that could just be because our videos are almost constant frame rate (but that is not guaranteed). But, I see that the fix is in 2021 roadmap, which is great!

We rely on heuristics to detect VFR videos ahead of time (to be 100% we would need to read the whole video stream, not the header) and it may be sometimes wrong. That is why there is an option to turn it off.

>  Is it possible to use augmentations like rotate, HSV, brightness_contrast augmentations for video data? I could only make certain transform like erase work for videos. Is there a way to make image processing transforms work for videos - or is it in the roadmap?

Most of the operations but not all are available for video. For color augmentation, you can try out [the coord transformation operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.coord_transform) that can apply matrix operation over input data.
We used to have information if a given operator supports sequences but we removed it to improve the overall documentation readability. If you see that a given operator doesn't support sequences feel free to report an issue with a request for enhancement.

**Comment by devashishshankar** [comment]
Thanks a lot! Looks like I can apply any linear transformation using this. I think there is missing documentation/ tutorial for video augmentations - so once I get it working, I can contribute the same, if there is interest.

Looks like my original question is resolved, so I'll close the issue. Will open new ones if I have more questions.
