### ISSUE TITLE
Normalizing image data in range [-1, 1] on GPU

### ISSUE THREAD

**Issue by Michelvl92** [NVIDIA/DALI#3236]
How can I normalize image date read with readers.video_reszie, on the GPU?

**Comment by JanuszL** [comment]
Hi @Michelvl92,

You can check ][the 'crop_mirror_normalize` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.crop_mirror_normalize) or just use `the `normalize` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.normalize) (see [this example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/normalize.html)).
