### ISSUE TITLE
i have a problem about fn.readers.mxnet

### ISSUE THREAD

**Issue by daixiangzi** [NVIDIA/DALI#3241]
first , my rec file is multilabel
when i user fn.readers.mxnet, i only get one label,how to get multilabel???

**Comment by JanuszL** [comment]
Hi @daixiangzi,

Now, DALI supports only a basic RecordIO schema - image and label. As far as I understand the format, the way how to store any additional data is not well defined and could be custom implemented.
If you feel that other DALI users can benefit from this functionality we will be more than happy to review and accept such PR. I would start by looking into:
- [recordio_parser.h](https://github.com/NVIDIA/DALI/blob/main/dali/operators/reader/parser/recordio_parser.h)
- [mxnet_reader_op.h](https://github.com/NVIDIA/DALI/blob/main/dali/operators/reader/mxnet_reader_op.h)
- [mxnet_reader_op.cc](https://github.com/NVIDIA/DALI/blob/main/dali/operators/reader/mxnet_reader_op.cc)
