### ISSUE TITLE
readers.video hangs when reading HEVC

### ISSUE THREAD

**Issue by castim** [NVIDIA/DALI#3243]
Hi, 

When I run the following code

```python
from tqdm import tqdm

from nvidia import dali
import nvidia.dali.fn as fn

@dali.pipeline_def
def video_pipeline():
    seq = fn.readers.video(device="gpu", filenames="sintel_trailer-1080p-g5-hevc.mp4", sequence_length=3)
    return seq

pipe = video_pipeline(batch_size=16, num_threads=1, device_id=0)

pipe.build()

for i in tqdm(range(99999999)):
    pipe.run()
```
The loop gets stuck after 21 iterations.

I use the [sintel trailer 1080p](https://download.blender.org/durian/trailer/sintel_trailer-1080p.mp4) which I reencoded to get a smaller gop size using the HEVC codec with:
```
ffmpeg -i sintel_trailer-1080p.mp4 -c:v hevc -an sintel_trailer-1080p-g5-hevc.mp4
```

I use DALI 1.4.0 with cuda 10 (also tested with cuda 11).

With H264, it works fine, and it is also much (6-7x) faster.
Is HEVC not supported by DALI?

**Comment by JanuszL** [comment]
Hi @castim,

DALI does support the HEVC codec. I just checked your script and on my NVIDIA TITAN XP, I get ~2-3s per batch with the original encoding while ~1.2s per batch with HEVC.
Regarding the hang, it seems in the case of HEVC preceding frames may appear after the next keyframe so [the condition](https://github.com/NVIDIA/DALI/blob/main/dali/operators/reader/loader/video_loader.cc#L583L602) of not reading the video stream anymore is no longer correct. Let us check if we can do anything with that.

**Comment by castim** [comment]
Regarding the H264 HEVC speed difference, my bad, I was testing between two files with different GOP structures, probably the source of the speed difference.

(My command should have been 
```
ffmpeg -i sintel_trailer-1080p.mp4 -c:v hevc -an -x265-params "keyint=5" sintel_trailer-1080p-g5-hevc.mp4
```
to get a GOP size of 5; ffmpeg -g does not work with hevc)

**Comment by JanuszL** [comment]
I think I have found a fix for the issue you reported - https://github.com/NVIDIA/DALI/pull/3247. Please check the nightly build that follows the day the fix is merged.

**Comment by castim** [comment]
Great, will do!

**Comment by JanuszL** [comment]
The fix has been merged. It should be available in tomorrow's nightly build and 1.6 release.

**Comment by castim** [comment]
I confirm my small script works. However, I still have om problems with my training in HEVC, I need to dig into it to see if it is related to DALI, I will get back to you.

**Comment by castim** [comment]
Ok it works, I close the issue. Thank you!

**Comment by JanuszL** [comment]
I hope this PR may help https://github.com/NVIDIA/DALI/pull/3858. Please check nightly/weekly build after it is merged to see if it resolves your problem.

**Comment by JanuszL** [comment]
[1.14](https://github.com/NVIDIA/DALI/releases/tag/v1.14.0) is available and should address this issue.
