### ISSUE TITLE
readers.video fails to read some short clip when using timestamps

### ISSUE THREAD

**Issue by zero0kiriyu** [NVIDIA/DALI#3251]
Hi,
When I use dali to read some short clips by timestamps, it tells me the start time number should be lesser or equal to the end time.

```
auto frame_rate = av_inv_q(file.frame_base_);
if (start >= 0) {
  start_frame = static_cast<int>(std::ceil(start * av_q2d(frame_rate)));
} else {
  start_frame = file.frame_count_ +
                static_cast<int>(std::ceil(start * av_q2d(frame_rate)));
}
if (end > 0) {
  end_frame = static_cast<int>(std::floor(end * av_q2d(frame_rate)));
} else {
  end_frame = file.frame_count_ + static_cast<int>(std::floor(end * av_q2d(frame_rate)));
}
```

I check the `video_loader.h`, if the clip is so short, the calculated start_frame would become bigger than end_frame. Maybe the start_frame should be calculated by floor and the end_frame should be calculated by ceil?

**Comment by JanuszL** [comment]
Hi @zero0kiriyu,

Can you provide any sample video that would reproduce the problem?

**Comment by zero0kiriyu** [comment]
It is pretty easy to reproduce this problem on any video. It just needs some specific timestamp. For example, just take the 8.11s~8.12s frames from a 25fps video, the start_frame would be 203 and the end_frame would be 202.

**Comment by JanuszL** [comment]
@zero0kiriyu I'm not sure if we can call this a bug or just a way it works. It is still possible to do what you need by adjusting timestamps accordingly.
Modifying the behavior would be a breaking change.
Let me check with the team how we can approach this request.

**Comment by JanuszL** [comment]
Hi @zero0kiriyu,

We decided to make this behavior configurable, and by default set to the present one to preserve the existing code compatibility.
Please check the nightly build after https://github.com/NVIDIA/DALI/pull/3252 is merged if it does what you expect. Please use `file_list_include_preceding_frame =True` option (the exact name may change in the review process).

**Comment by klecki** [comment]
Hi @zero0kiriyu,
the PR has been merged, and the change should be available in our nightly build if you want to try it out.

**Comment by zero0kiriyu** [comment]
That's would be great, thank you.

**Comment by klecki** [comment]
Here are the instructions to install nightly build: https://docs.nvidia.com/deeplearning/dali/main-user-guide/docs/installation.html#pip-nightly-and-weekly-releases
