### ISSUE TITLE
Nvidia DALI On Jetson Devices with Triton Inference Server

### ISSUE THREAD

**Issue by sarperkilic** [NVIDIA/DALI#3259]
Hello everyone,

I have Jetson Nano and Xavier.

I couldn't find if I can use DALI on Jetson device or not. If yes, could you provide me how can I install and use, please.

My purpose is that using DALI in Triton inference server pipeline. I installed Triton Inference DALI backend, but when I run the example DALI script, I got an error that 'Import error: No module named nvidia.dali' for import nvidia.dali as dali line.

Thanks

**Comment by klecki** [comment]
Hi @sarperkilic,
we don't have official DALI wheels for Jetson Nano or Xavier. 
There is aarch64 DALI wheel, but it's for aarch64 SBSA systems.

For Xavier it's possible to build DALI wheel on your own from the source, and we provide instructions how to do it here: https://docs.nvidia.com/deeplearning/dali/user-guide/docs/compilation.html#cross-compiling-for-aarch64-jetson-linux-docker


Details on the DALI support of different platforms can be found here:
https://docs.nvidia.com/deeplearning/dali/user-guide/docs/support_matrix.html

**Comment by qraleq** [comment]
@sarperkilic I had the same issue and managed to fix it after a lot of trial and error. You can check my blog with detailed instructions here: https://ralasic1.medium.com/how-to-install-nvidia-dali-triton-backend-on-jetson-devices-9dea8973b699
