### ISSUE TITLE
Module 'nvidia.dali.ops' has no 'FileReader' member

### ISSUE THREAD

**Issue by umie0128** [NVIDIA/DALI#3260]
Module 'nvidia.dali.ops' has no 'FileReader' member
Module 'nvidia.dali.ops' has no 'ImageDecoder' member
Module 'nvidia.dali.ops' has no 'RandomResizedCrop' member
Module 'nvidia.dali.ops' has no 'CropMirrorNormalize' member
--------------------------------------version-------------------------------
pytorch-lightning       1.3.7.post0
torch                   1.8.1
torch-tb-profiler       0.2.1
torchmetrics            0.4.0
torchsummary            1.5.1
torchvision             0.9.1
nvidia-dali             0.22.0
nvidia-dali-cuda110     1.4.0

please help me

**Comment by klecki** [comment]
Hi @umie0128,
from the log you posted, it seems like you have two DALI versions installed at the same time:
```
nvidia-dali 0.22.0
nvidia-dali-cuda110 1.4.0
```

Can you try to completely uninstall them both and then install DALI again following our installation guide:
https://docs.nvidia.com/deeplearning/dali/user-guide/docs/installation.html

Please install DALI for your CUDA version, if you have CUDA 11 it's:
```
pip install --extra-index-url https://developer.download.nvidia.com/compute/redist --upgrade nvidia-dali-cuda110
```

**Comment by umie0128** [comment]
it still could not find when i uninstall both and only install nvidia-dali-cuda110     1.4.0

**Comment by klecki** [comment]
Can you give us some more details about your environment?
Are you using pip, conda, running in a container?

For pip, make sure you have the latest one.

What is the minimal script that reproduces the issue? 

I just took a clean ubuntu:20.04 docker image, installed python3 and python3-pip, did

```
pip3 install --extra-index-url https://developer.download.nvidia.com/compute/redist --upgrade nvidia-dali-cuda110

python3

> from nvidia.dali.ops import FileReader, ImageDecoder, RandomResizedCrop, CropMirrorNormalize

```
And it runs as expected, installing DALI 1.4 and importing those classes successfully.

**Comment by umie0128** [comment]
zijing.wang@AI-S002:~$ pip3 install --extra-index-url https://developer.download.nvidia.com/compute/redist --upgrade nvidia-dali-cuda110
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple, https://pypi.ngc.nvidia.com, https://developer.download.nvidia.com/compute/redist
Collecting nvidia-dali-cuda110
  Downloading https://developer.download.nvidia.cn/compute/redist/nvidia-dali-cuda110/nvidia_dali_cuda110-1.4.0-2575285-py3-none-manylinux2014_x86_64.whl (789.4 MB)
     |████████████████████████████████| 789.4 MB 3.1 MB/s 
Installing collected packages: nvidia-dali-cuda110
Successfully installed nvidia-dali-cuda110-1.4.0
-------------------------------------------------------------
zijing.wang@AI-S002:~$ pip3 install --extra-index-url https://developer.download.nvidia.com/compute/redist --upgrade nvidia-dali-cuda110
Looking in indexes: https://pypi.org/simple, https://developer.download.nvidia.com/compute/redist
Requirement already satisfied: nvidia-dali-cuda110 in ./.local/lib/python3.6/site-packages (1.4.0)
----------------------------------------------------------------
pip version:                       21.2.4
nvidia-dali-cuda110     1.4.0
nvidia-ml-py3           7.352.0
nvidia-pyindex          1.0.9
----------------------------------------------------------------
class HybridTrainPipe(Pipeline):
    def __init__(self, batch_size, num_threads, device_id, data_dir, crop, dali_cpu=False, local_rank=0, world_size=1):
        super(HybridTrainPipe, self).__init__(batch_size, num_threads, device_id, seed=12 + device_id)
        dali_device = "gpu"
        self.input = ops.FileReader(file_root=data_dir, shard_id=local_rank, num_shards=world_size, random_shuffle=True)
        self.decode = ops.ImageDecoder(device="mixed", output_type=types.RGB)
        self.res = ops.RandomResizedCrop(device="gpu", size=crop, random_area=[0.08, 1.25])
        self.cmnp = ops.CropMirrorNormalize(device="gpu",
                                            output_dtype=types.FLOAT,
                                            output_layout=types.NCHW,
                                            image_type=types.RGB,
                                            mean=[0.485 * 255, 0.456 * 255, 0.406 * 255],
                                            std=[0.229 * 255, 0.224 * 255, 0.225 * 255])
        self.coin = ops.CoinFlip(probability=0.5)
        print('DALI "{0}" variant'.format(dali_device))
----------------------------------------------------------------
i try recovery ~/.config/pip/pip.conf and install again,but still could not find. my project can run. i want to add imgaug part, so check the dataloard. now i add the imgaug part before 'output = model(img)'
sorry my english bad

**Comment by szalpal** [comment]
@umie0128 ,

I see you are using the old, objective API. Please use new, functional API with decorator. You can find the info in the [getting started](https://docs.nvidia.com/deeplearning/dali/master-user-guide/docs/examples/getting%20started.html) section or the [pipeline](https://docs.nvidia.com/deeplearning/dali/master-user-guide/docs/pipeline.html) section.

If you have any problems, please provide us with your pipeline code and the error message, then we'll be able to help you.

**Comment by JanuszL** [comment]
Hi @umie0128,

You may also need to update pip to the latest version: `pip install --upgrade pip` as the old one doesn't support python wheels tags used by the most recent DALI releases.
