### ISSUE TITLE
a bug in test code dali/pipeline/data/tensor_test.cc

### ISSUE THREAD

**Issue by tendar** [NVIDIA/DALI#3265]
template <typename Backend, typename T = float>
std::vector<T> to_vec(Tensor<Backend> &tensor) {
  std::vector<T> tmp(tensor.size());
  if (std::is_same<Backend, GPUBackend>::value) {
    CUDA_CALL(
      cudaMemcpyAsync(tmp.data(), tensor.template data<T>(),
                      tensor.size(), cudaMemcpyDeviceToHost, 0));  // it should be tensor.nbytes() here, tensor.size() will get element number
    CUDA_CALL(cudaStreamSynchronize(0));
  } else if (std::is_same<Backend, CPUBackend>::value) {
    memcpy(tmp.data(), tensor.template data<float>(), tensor.size());
  }
  return tmp;
}

**Comment by klecki** [comment]
Hi @tendar,
yes, you are right.
Thank you for reporting that issue, I will post a fix soon.
