### ISSUE TITLE
i use fn.transforms.scale error?

### ISSUE THREAD

**Issue by daixiangzi** [NVIDIA/DALI#3272]
code:  
`def dali_transforms(img,scale=(0.5,1)): 
    img = fn.transforms.scale(img,scale =scale)
    return img `

`def get_data():
        img = cv2.imread("test.jpeg")
        img = img.astype(np.float32)
        img = img[np.newaxis,...]
        return img`

`data = fn.external_source(source=get_data))
 data = dali_transforms(data)
 pipe.set_outputs(data)
 pipe.build()
out = pipe.run()`

Error when executing CPU operator transforms__Scale encountered:
[/opt/dali/dali/operators/geometry/affine_transforms/transform_base_op.h:87] Assert on "shape.sample_dim() == 2 && shape.size() > 0 && shape[0][1] == (shape[0][0] + 1)" failed: The input, if provided, is expected to be a 2D tensor with dimensions (ndim, ndim+1) representing an affine transform. Got: {256 x 256 x 3}

**Comment by klecki** [comment]
Hi @daixiangzi,
you probably want to use [resize](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.resize) instead of the [transforms.scale](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.transforms.scale).

Resize is intended to resize images (and other data like volumes and sequences) - it supports more interpolations and scaling modes. Here is an example describing different options in resize operator: https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/image_processing/resize.html 
 
All operators in `nvidia.dali.fn.transforms` define a transform matrix that can be applied to data with [coord_transform](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.coord_transform) or [warp_affine](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.warp_affine). Here is an example of using warp affine: https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/image_processing/warp.html - but unless you want to combine several affine transforms, it's better to use resize for scaling images.

**Comment by daixiangzi** [comment]
no ,i not use resize function. i only want to use transforms.scale.

**Comment by daixiangzi** [comment]
other,i use resize to downsample pic( random different interp_type),how i should to do ?

**Comment by daixiangzi** [comment]
look like : 
        methds = [
            dali.types.INTERP_NN,
            dali.types.INTERP_LINEAR,
            dali.types.INTERP_CUBIC,
            dali.types.INTERP_TRIANGULAR,
            dali.types.INTERP_GAUSSIAN,
            dali.types.INTERP_LANCZOS3]
   index  = np.random.randint(0,6)
    out = fn.resize(img, resize_x=960, resize_y=960, interp_type=methds[index])

**Comment by daixiangzi** [comment]
> look like :
> methds = [
> dali.types.INTERP_NN,
> dali.types.INTERP_LINEAR,
> dali.types.INTERP_CUBIC,
> dali.types.INTERP_TRIANGULAR,
> dali.types.INTERP_GAUSSIAN,
> dali.types.INTERP_LANCZOS3]
> index = np.random.randint(0,6)
> out = fn.resize(img, resize_x=960, resize_y=960, interp_type=methds[index])

i know my code is error,please tell me relative work method

**Comment by mzient** [comment]
@daixiangzi 
It's not currently directly supported, but with a few workarounds it can be achieved. The following code does it:

```Python
pipe = dali.Pipeline(batch_size, 3, 0)
with pipe:
    files, labels = fn.readers.caffe(path = db_folder, random_shuffle = True, seed = 1234)
    images = dali.fn.decoders.image(files, device = "mixed")

    # here's your list of interpolation types to choose from
    interp_types = [dali.types.INTERP_NN, dali.types.INTERP_LINEAR, dali.types.INTERP_LANCZOS3]
    # convert them t integer and pick a random value from these
    interp = fn.random.uniform(values=[int(x) for x in interp_types], dtype=dali.types.INT32)
    # reinterpret the result to INTERP_TYPE
    interp = fn.reinterpret(interp, dtype=dali.types.INTERP_TYPE)
    # resize with the run-time randomly selected method
    images = fn.resize(images, size=(100,100), interp_type=interp, mode="not_larger")
    pipe.set_outputs(images, interp)
```

**Comment by daixiangzi** [comment]
> @daixiangzi
> It's not currently directly supported, but with a few workarounds it can be achieved. The following code does it:
> 
> ```python
> pipe = dali.Pipeline(batch_size, 3, 0)
> with pipe:
>     files, labels = fn.readers.caffe(path = db_folder, random_shuffle = True, seed = 1234)
>     images = dali.fn.decoders.image(files, device = "mixed")
> 
>     # here's your list of interpolation types to choose from
>     interp_types = [dali.types.INTERP_NN, dali.types.INTERP_LINEAR, dali.types.INTERP_LANCZOS3]
>     # convert them t integer and pick a random value from these
>     interp = fn.random.uniform(values=[int(x) for x in interp_types], dtype=dali.types.INT32)
>     # reinterpret the result to INTERP_TYPE
>     interp = fn.reinterpret(interp, dtype=dali.types.INTERP_TYPE)
>     # resize with the run-time randomly selected method
>     images = fn.resize(images, size=(100,100), interp_type=interp, mode="not_larger")
>     pipe.set_outputs(images, interp)
> ```
very thank you ,i understand

**Comment by daixiangzi** [comment]
> @daixiangzi
> It's not currently directly supported, but with a few workarounds it can be achieved. The following code does it:
> 
> ```python
> pipe = dali.Pipeline(batch_size, 3, 0)
> with pipe:
>     files, labels = fn.readers.caffe(path = db_folder, random_shuffle = True, seed = 1234)
>     images = dali.fn.decoders.image(files, device = "mixed")
> 
>     # here's your list of interpolation types to choose from
>     interp_types = [dali.types.INTERP_NN, dali.types.INTERP_LINEAR, dali.types.INTERP_LANCZOS3]
>     # convert them t integer and pick a random value from these
>     interp = fn.random.uniform(values=[int(x) for x in interp_types], dtype=dali.types.INT32)
>     # reinterpret the result to INTERP_TYPE
>     interp = fn.reinterpret(interp, dtype=dali.types.INTERP_TYPE)
>     # resize with the run-time randomly selected method
>     images = fn.resize(images, size=(100,100), interp_type=interp, mode="not_larger")
>     pipe.set_outputs(images, interp)
> ```

hi,when I use this code, error:

Error when executing GPU operator Resize encountered:
[/opt/dali/dali/operators/image/resize/resize_base.cc:45] Unsupported type: int32. Supported types are: uint8, int
16, uint16 and float
Stacktrace (11 entries):
