### ISSUE TITLE
Question: resizing both images and keypoints

### ISSUE THREAD

**Issue by danbider** [NVIDIA/DALI#3293]
For a keypoint detection resnet, I'm loading images and their corresponding keypoints (each keypoint = (x,y) pixel coords). 
I know how to resize the images -- how can I do so for the corresponding keypoints?

**Comment by JanuszL** [comment]
Hi @danbider,

We don't have a dedicated operator to resize key points however you can:
- if you know the scales you can use [DALI arithmetic operations](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/math.html) and [tensor indexing/slicing](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/indexing.html) to scale the coordinates
- you can implement a dedicated operator on your own according to [this guide](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/custom_operations/index.html)

**Comment by mzient** [comment]
The solution above will work only for CPU resize. For GPU resize, you need this:
```Python
resized = fn.resize(images, ...)  # whatever arguments are there
in_sizes = fn.sizes(images)[:2]  # strip channels
out_sizes = fn.sizes(images)[:2]

ratios = out_sizes / in_sizes

# assuming that keypoints are stored in a 2D tensor as:
# [[x y],
#  [x, y],
#  ...
#  [x, y]]

x = keypoints[:,0] * ratios[1] # size is stored as h, w, hence ratios[1] for x
y = keypoints[:,1] * ratios[0] # ... and ratios[0] for y
keypoints_resized = fn.stack(x, y, axis=1)
```

**Comment by danbider** [comment]
Thanks @JanuszL and @mzient. Testing it out and reporting back.

**Comment by xinlinxie** [comment]
> The solution above will work only for CPU resize. For GPU resize, you need this:
> 
> ```python
> resized = fn.resize(images, ...)  # whatever arguments are there
> in_sizes = fn.shapes(images)[:2]  # strip channels
> out_sizes = fn.shapes(resized)[:2]
> 
> ratios = out_sizes / in_sizes
> 
> # assuming that keypoints are stored in a 2D tensor as:
> # [[x y],
> #  [x, y],
> #  ...
> #  [x, y]]
> 
> x = keypoints[:,0] * ratios[1] # size is stored as h, w, hence ratios[1] for x
> y = keypoints[:,1] * ratios[0] # ... and ratios[0] for y
> keypoints_resized = fn.stack(x, y, axis=1)
> ```
> 
> A possible problem with this solution is that keypoints will land on whatever backend the resized images are.

Hi, for GPU resize,  i have a question,  if my datasets have some negative samples, and the corresponding keypoint list is empty, when we use  keypoints[:,0] and  keypoints[:,1] to index will report an error,  how should i solve this problem? looking forward to your reply~

**Comment by mzient** [comment]
Hello @xinlinxie ,
Your empty lists of coordinates must have a wrong shape - they likely are shaped `[0,0]` and should be `[0,2]` (there might be none, but it's still XY, hence the second extent is 2). You can either fix your data loading code to provide the correct shape, or you can reshape your data to ensure that it's always 2D:
```
coords = fn.reshape(coords, shape=[-1,2])
```

**Comment by danbider** [comment]
@JanuszL @mzient -- how would you similarly rotate keypoints alongside the image? i.e., rotate both image and keypoints by 40 degrees say.
