### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by daixiangzi** [NVIDIA/DALI#3294]
def dali_random_resize(img):
 methds = [
            dali.types.INTERP_NN,
            dali.types.INTERP_LINEAR,
            dali.types.INTERP_CUBIC,
            dali.types.INTERP_TRIANGULAR,
            dali.types.INTERP_GAUSSIAN,
            dali.types.INTERP_LANCZOS3]
    interp = fn.random.uniform(values=[int(x) for x in methds], dtype=dali.types.INT32)
    interp = fn.reinterpret(interp, dtype=dali.types.INTERP_TYPE)
    out = fn.resize(img, resize_x=256, resize_y=256,interp_type=interp)
    return out

def multiplexing(condition, true_case, false_case):
    neg_condition = condition ^ True
    return condition * true_case + neg_condition * false_case

 condition_resize = fn.random.coin_flip(probability=1.0)
 images = multiplexing( condition=condition_resize, true_case=dali_random_resize(images), false_case=images)

error:
Error when executing GPU operator Resize encountered:
[/opt/dali/dali/operators/image/resize/resize_base.cc:45] Unsupported type: int32. Supported types are: uint8, int
16, uint16 and float

but when I use under code is right: 
methds = [
            dali.types.INTERP_NN,
            dali.types.INTERP_LINEAR,
            dali.types.INTERP_CUBIC,
            dali.types.INTERP_TRIANGULAR,
            dali.types.INTERP_GAUSSIAN,
            dali.types.INTERP_LANCZOS3]
interp = fn.random.uniform(values=[int(x) for x in methds], dtype=dali.types.INT32)
interp = fn.reinterpret(interp, dtype=dali.types.INTERP_TYPE)
images = fn.resize(images, resize_x=256, resize_y=256,interp_type=interp)

**Comment by mzient** [comment]
@daixiangzi Are you sure that there are no more instances of `resize` in the pipeline? I don't see a reason for the first resize to see a different type, but the result of the multiplexing function _is_ promoted to int32 because you use operator `*`.

Also, I'm afraid that the multiplexing function will not work (in general), because you try to mix images of different sizes (resized and non-resized). This approach is also very inefficient, because you resize regardless of whether you want the resized image or  not - and on top of that, you apply an arithmetic operation which needs to read both inputs. Instead, try to mask the sizes - `0` size has a special meaning (keep original). To save time (and avoid INTERP_GAUSSIAN which will yield slightly blurred image even when not resizing) you can also mask the interpolation method - INTERP_NN corresponds to a numerical value of 0.

```Python
batch_size = 8

pipe = dali.Pipeline(batch_size, 3, 0)
with pipe:
    files, labels = fn.readers.caffe(path = db_folder, random_shuffle = True, seed = 1234)
    images = dali.fn.decoders.image(files, device = "mixed")

    mask = fn.random.coin_flip(probability=0.5, dtype=dali.types.INT32)
    interp_types = [dali.types.INTERP_NN, dali.types.INTERP_LINEAR, dali.types.INTERP_LANCZOS3]
    interp = fn.random.uniform(values=[int(x) for x in interp_types], dtype=dali.types.INT32) * mask
    interp = fn.reinterpret(interp, dtype=dali.types.INTERP_TYPE)
    size = mask * np.float32([256,256])
    images = fn.resize(images, size=size, interp_type=interp)
    pipe.set_outputs(images, interp)
    
pipe.build()
images, interp_type = pipe.run()
show(images)
```

Hint: place your code between ` ```Python ` and ` ``` ` for pretty formatting.

**Comment by daixiangzi** [comment]
> @daixiangzi Are you sure that there are no more instances of `resize` in the pipeline? I don't see a reason for the first resize to see a different type, but the result of the multiplexing function _is_ promoted to int32 because you use operator `*`.
> 
> Also, I'm afraid that the multiplexing function will not work (in general), because you try to mix images of different sizes (resized and non-resized). This approach is also very inefficient, because you resize regardless of whether you want the resized image or not - and on top of that, you apply an arithmetic operation which needs to read both inputs. Instead, try to mask the sizes - `0` size has a special meaning (keep original). To save time (and avoid INTERP_GAUSSIAN which will yield slightly blurred image even when not resizing) you can also mask the interpolation method - INTERP_NN corresponds to a numerical value of 0.
> 
> ```python
> batch_size = 8
> 
> pipe = dali.Pipeline(batch_size, 3, 0)
> with pipe:
>     files, labels = fn.readers.caffe(path = db_folder, random_shuffle = True, seed = 1234)
>     images = dali.fn.decoders.image(files, device = "mixed")
> 
>     mask = fn.random.coin_flip(probability=0.5, dtype=dali.types.INT32)
>     interp_types = [dali.types.INTERP_NN, dali.types.INTERP_LINEAR, dali.types.INTERP_LANCZOS3]
>     interp = fn.random.uniform(values=[int(x) for x in interp_types], dtype=dali.types.INT32) * mask
>     interp = fn.reinterpret(interp, dtype=dali.types.INTERP_TYPE)
>     size = mask * np.float32([256,256])
>     images = fn.resize(images, size=size, interp_type=interp)
>     pipe.set_outputs(images, interp)
>     
> pipe.build()
> images, interp_type = pipe.run()
> show(images)
> ```
> 
> Hint: place your code between `` ```Python `` and `` ``` `` for pretty formatting.

sorry,next time i notice code format,thank you for your reply,i have understood
