### ISSUE TITLE
About  data shuffle ?  local shuffle or global shuffle?

### ISSUE THREAD

**Issue by jiqirenno1** [NVIDIA/DALI#331]
when i print the labels, it gradually increases.
like this
[18. 22. 18.  2. 21.  8.  9. 13. 12. 25.  7.  8. 23.  3.  6.  6. 23.  8.
 15.  0.  7. 11. 10. 22.  7.  6. 21. 21. 21. 16.  9. 23.]
<NDArray 32 @gpu(0)>]
labels: [
[18. 25. 21. 23. 16. 25. 18. 22. 21.  2. 23. 12. 10. 11. 21.  5.  6. 14.
 18. 12. 23.  7.  1. 24. 18. 12. 13. 22. 15. 15. 21.  9.]
....
....
 97. 101. 101.  81.  94. 101. 100. 103.  80.  75. 103.  83. 100.  99.
 100.  88.  72.  79.  92.  94.  88.  99.  89. 101.  94. 101.  93.  51.
 102. 100.  93.  93.]
<NDArray 32 @gpu(0)>]
labels: [
[ 90.  84.  47.  66.  93.  90.  38.  85. 101.  40.  96.  47. 100.  91.
  94. 103.  94.  96.  89. 100.  90.  99.  95.  87.  92.  88.  84.  89.
  99. 103.  91.  99.]

**Comment by JanuszL** [comment]
Hi,
_tl;dr_
We do it globally and locally.
**Long explanation.**
It depends on the dataset. For readers that loads separate files from the disk (COCO or FileReader) we do initial shuffling globally during operator initialization - https://github.com/NVIDIA/DALI/blob/master/dali/pipeline/operators/reader/loader/file_loader.h#L80. For TFRecord, RecordIO or Caffe LMDB we expect data set to be pre-shuffled already.
Then we do local shuffling during reading (as long as random_shuffle operator parameter is set to True), we fill prefetch buffer (default size is 1024) with data and then randomly chose samples one by one until the batch is full (replacing taken samples with a new one) - https://github.com/NVIDIA/DALI/blob/master/dali/pipeline/operators/reader/loader/loader.h#L102.

**Comment by jiqirenno1** [comment]
Thanks a lot !
To make the locally shuffle to globally shuffle,
can i change buffer default size 1024 to the length of data ?

**Comment by JanuszL** [comment]
Keep in mind that TFRecord, RecordIO or Caffe LMDB are fast because files are concatenated and file seek is faster because of that. So assumption about having them pre-schuffled is valid.

**Comment by Mmdixon** [comment]
@JanuszL would it help to maybe clarify the documentation, or are local/global shuffle patterns subject to change? Some of the caveats aren't clear from the get-go.
semi-related the discussion here: https://github.com/NVIDIA/DALI/issues/665

For example it was pointed out the loader does local shuffle, so `initial_fill=1` would be in order and no duplicates. But the VideoLoader loader does global shuffle https://github.com/NVIDIA/DALI/blob/b869de6f67f2c3cd3d20c733d4604f4fab7ddf0d/dali/pipeline/operators/reader/loader/video_loader.h#L167-L173 independent of `initial_fill`. However, if you want to see all images/frames in an epoch then `initial_fill` should essentially be 1 or small enough for the tolerance of the overlap between the tail end of the epoch and the beginning of the sequence again (compounded). Or the alternative use the file loader which does global shuffle.

**Comment by JanuszL** [comment]
@Mmdixon - the VideoReader code you pointed out is to avoid feeding your network with all class 0, then class 1 and so on(FileReader does that too). Having this initial, global preshuffle (which happens only once during pipeline creation) allows having different classes inside one batch. In the case of TFRecord, RecordIO or Caffe LMDB data sets are preshuffled and constitutive entries come from different classes. Without it, in case of multi GPU training, each GPU will see samples only from some subset of classes.
