### ISSUE TITLE
how to solve "libArcus/src/Socket_p.h:551:77: error: no matching function for call to ‘google::protobuf::io::CodedInputStream::SetTotalBytesLimit(const int&, const int&)’

### ISSUE THREAD

**Issue by Nicolas8989** [NVIDIA/DALI#3313]
lesenfans@ubuntu:~/Desktop/protobuf/libArcus/build$ make
Scanning dependencies of target Arcus
[  4%] Building CXX object CMakeFiles/Arcus.dir/src/Socket.cpp.o
In file included from /home/lesenfans/Desktop/protobuf/libArcus/src/Socket.cpp:20:
/home/lesenfans/Desktop/protobuf/libArcus/src/Socket_p.h: In member function ‘void Arcus::Socket::Private::sendMessage(const MessagePtr&)’:
/home/lesenfans/Desktop/protobuf/libArcus/src/Socket_p.h:365:51: warning: ‘int google::protobuf::MessageLite::ByteSize() const’ is deprecated: Please use ByteSizeLong() instead [-Wdeprecated-declarations]
  365 |         uint32_t message_size = message->ByteSize();
      |                                                   ^
In file included from /usr/local/include/google/protobuf/generated_enum_util.h:36,
                 from /usr/local/include/google/protobuf/generated_enum_reflection.h:44,
                 from /usr/local/include/google/protobuf/generated_message_reflection.h:46,
                 from /usr/local/include/google/protobuf/message.h:122,
                 from /home/lesenfans/Desktop/protobuf/libArcus/src/Socket_p.h:41,
                 from /home/lesenfans/Desktop/protobuf/libArcus/src/Socket.cpp:20:
/usr/local/include/google/protobuf/message_lite.h:433:7: note: declared here
  433 |   int ByteSize() const { return internal::ToIntSize(ByteSizeLong()); }
      |       ^~~~~~~~
In file included from /home/lesenfans/Desktop/protobuf/libArcus/src/Socket.cpp:20:
/home/lesenfans/Desktop/protobuf/libArcus/src/Socket_p.h: In member function ‘void Arcus::Socket::Private::handleMessage(const std::shared_ptr<Arcus::Private::WireMessage>&)’:
/home/lesenfans/Desktop/protobuf/libArcus/src/Socket_p.h:551:77: error: no matching function for call to ‘google::protobuf::io::CodedInputStream::SetTotalBytesLimit(const int&, const int&)’
  551 |         stream.SetTotalBytesLimit(message_size_maximum, message_size_warning);
      |                                                                             ^
In file included from /usr/local/include/google/protobuf/message_lite.h:47,
                 from /usr/local/include/google/protobuf/generated_enum_util.h:36,
                 from /usr/local/include/google/protobuf/generated_enum_reflection.h:44,
                 from /usr/local/include/google/protobuf/generated_message_reflection.h:46,
                 from /usr/local/include/google/protobuf/message.h:122,
                 from /home/lesenfans/Desktop/protobuf/libArcus/src/Socket_p.h:41,
                 from /home/lesenfans/Desktop/protobuf/libArcus/src/Socket.cpp:20:
/usr/local/include/google/protobuf/io/coded_stream.h:402:8: note: candidate: ‘void google::protobuf::io::CodedInputStream::SetTotalBytesLimit(int)’
  402 |   void SetTotalBytesLimit(int total_bytes_limit);
      |        ^~~~~~~~~~~~~~~~~~
/usr/local/include/google/protobuf/io/coded_stream.h:402:8: note:   candidate expects 1 argument, 2 provided
make[2]: *** [CMakeFiles/Arcus.dir/build.make:63：CMakeFiles/Arcus.dir/src/Socket.cpp.o] error 1
make[1]: *** [CMakeFiles/Makefile2:125：CMakeFiles/Arcus.dir/all] error 2
make: *** [Makefile:152：all] error 2
lesenfans@ubuntu:~/Desktop/protobuf/libArcus/build$ protoc --version
libprotoc 3.17.3

**Comment by JanuszL** [comment]
Hi @Nicolas8989,

Can you elaborate more on your issue? I don't see how it is related to DALI. What I can tell is whatever project you compile you have an incompatible version of protobuf (different function signatures). I recommend reporting it to the authors of the project you are trying to compile.

**Comment by Nicolas8989** [comment]
thanks， I see the problem！！！Because 'protobuf' version is too high.
