### ISSUE TITLE
terminate called after throwing an instance of 'dali::CUDAError'

### ISSUE THREAD

**Issue by hoangtnm** [NVIDIA/DALI#3314]
Hi, I'm using DALI v1.5 to preprocess data, and use `python function` to encode bounding boxes inside the DALI pipeline and train with PyTorch Lightning, however, it meets this weird issue:

```
  File "/home/miniconda3/envs/rodan/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/workspace/head-quality-assessment/src/ulfd_lightning/nn/multibox_loss.py", line 48, in forward
    predicted_locations = predicted_locations[pos_mask, :].reshape(-1, 4)
RuntimeError: CUDA error: device-side assert triggered
Epoch 0: 100%|██████████| 2/2 [00:00<00:00,  2.62it/s, loss=12.3, v_num=]                                                                                                                                        

terminate called after throwing an instance of 'dali::CUDAError'                                                                                                                                                 
  what():  CUDA runtime API error cudaErrorAssert (710):
device-side assert triggered
[1]    24707 abort (core dumped)  python main_dali.py --gpus 1 --data_dir DATA_DIR
```

**Comment by JanuszL** [comment]
Hi @hoangtnm,

This definitely deserves a thorough investigation. Can you provide a self-contained and minimal reproduction script for us so we can debug it?

**Comment by hoangtnm** [comment]
@JanuszL Hi, because this is private code, so can you give me your email so that I can share the jupyter notebook with you, and you can debug it? thank you

**Comment by JanuszL** [comment]
Hi @hoangtnm,

You can use our Dali-Team@nvidia.com email.

Thanks!

**Comment by hoangtnm** [comment]
@JanuszL I've sent the email, can you check it? thank you

**Comment by JanuszL** [comment]
We will check that and get back to you.

**Comment by JanuszL** [comment]
Hi @hoangtnm,

In my case, I needed to reduce the batch size as 64 was too much for the GPU I use for testing.
When rerun provided script as plain python code with `CUDA_LAUNCH_BLOCKING=1` env variable I get:
```
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:115: operator(): block: [0,0,0], thread: [6,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.

Traceback (most recent call last):
  File "test.py", line 381, in <module>
    confidence, locations, labels, boxes, training=True
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "test.py", line 358, in forward
    confidence.view(-1, num_classes), labels[mask], training)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "test.py", line 316, in forward
    nll_loss = -logprobs.gather(dim=-1, index=target.unsqueeze(1))
```
Are you sure that `nll_loss = -logprobs.gather(dim=-1, index=target.unsqueeze(1)` does what you want? Maybe it should be `  nll_loss = -logprobs.gather(dim=0, index=target.unsqueeze(1)`?

**Comment by hoangtnm** [comment]
Hi @JanuszL, the loss implementation is from [NVIDIA repo](https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/Classification/ConvNets/image_classification/smoothing.py#L36), and the shape of target is `[N, C]` where N is batch_size and C is class. And if I run the preprocessing using PyTorch dataloader natively. It doesn't occur this problem. 
So I think `dim=-1` is not the problem.

**Comment by JanuszL** [comment]
Hi @hoangtnm,

In my experiment `logprobs.shape` is `[3800, 3]` and values inside `target.unsqueeze(1)` are [0-49].
Just to be sure we are talking about the same issue I would recommend exporting the notebook you shared as *.py, run with `CUDA_LAUNCH_BLOCKING=1` environment variable set, and checking the error message.
The fact the code doesn't work with DALI while it works with the native loader doesn't mean there is an error in DALI. Maybe the pipeline you build using DALI doesn't reassemble the behavior of the native one. I would thoroughly check the values you get and compare them with the expected ones.

**Comment by hoangtnm** [comment]
Hi @JanuszL, I think I found the root cause, which is `fn.readers.coco`. For example, if the `category_id` in `/tmp/coco.json` is 0, the labels returned by `fn.readers.coco` will be `increased by 1` and become `1` rather than `0`, which seems inconsistent with the `category_id` defined in `/tmp/coco.json`.
In my case, I assume `category_id: 0` will be `background` and `category_id` for other objects will starts from `1`. But the labels returned by `fn.readers.coco` starts from `2` rather than `1`. So, if the model predicts `cat, dog`, the expected target will be `1, 2`; but the labels returned by `fn.readers.coco` becomes `2, 3`. Therefore, `3` becomes outbound `2`, which causes the problem why loss cannot be computed. Here is my [notebook](https://colab.research.google.com/drive/1ai0nUluj-OkJesyjB_IRCzdEKHYgUKWb?usp=sharing) to reproduce this issue

**Comment by JanuszL** [comment]
Hi @hoangtnm,

Yes, DALI's coco reader does remapping between categories - it treats 0 as a background and then enumerates available categories from 0 to 1. It doesn't use categories from the JSON file directly.
The relevant function can be found [here](https://github.com/NVIDIA/DALI/blob/main/dali/operators/reader/loader/coco_loader.cc#L247).
Feel free to post a PR that would make this behavior optional:
- new option is needed to be added to [coco_reader_op.cc](https://github.com/NVIDIA/DALI/blob/main/dali/operators/reader/coco_reader_op.cc)
- you need to read its value and make the usage of the mapping [optional ](https://github.com/NVIDIA/DALI/blob/main/dali/operators/reader/loader/coco_loader.cc#L543)
- add a test to [test_operator_readers_coco.py](https://github.com/NVIDIA/DALI/blob/main/dali/test/python/test_operator_readers_coco.py)

**Comment by JanuszL** [comment]
Hi @hoangtnm,

[This PR](https://github.com/NVIDIA/DALI/pull/3333) should address requested functionality. Please check the nightly build that follows its merge.

**Comment by hoangtnm** [comment]
> Hi @hoangtnm,
> 
> [This PR](https://github.com/NVIDIA/DALI/pull/3333) should address requested functionality. Please check the nightly build that follows its merge.

Hi @JanuszL Thank you, I will check it :D
