### ISSUE TITLE
"TypeError: Unsupported callback return type" when creating a DALIDatasetWithInputs object

### ISSUE THREAD

**Issue by pbruneau** [NVIDIA/DALI#3321]
**Environment:** 
- from rapidsai/rapidsai-dev:21.06-cuda11.0-devel-ubuntu18.04-py3.7 docker image
- DALI: 1.5.0 (installed nvidia-dali-cuda110 and nvidia-dali-tf-plugin-cuda110)
- Tensorflow: 2.4.1

**Reproducing example:**
- Please refer to this gist: https://gist.github.com/pbruneau/b6a41b930ac5c2f7d368057153563d5c
- The image folder used by the example can be downloaded here: https://www.kaggle.com/kvpratama/pokemon-images-dataset but possibly replaced by any folder containing jpg files.

**Problem:**

I am basically trying to combine an external source operator for loading images from a folder (see https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/external_input.html) and integrate this pipeline to Tensorflow/Keras using the Tensorflow DALI plugin (see https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/frameworks/tensorflow/tensorflow-dataset.html).

No problem with the pipeline creation, the traces show it is created and works as expected:
```
<class 'cupy._core.core.ndarray'>
(256, 256, 3)
```

However, the DALIDataset creation fails with the following trace:
```
Traceback (most recent call last):
  File "keras_pipeline_trial.py", line 63, in <module>
    device_id=0)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/nvidia/dali/plugin/tf.py", line 807, in __init__
    dataset_impl = _DALIDatasetImpl(pipeline, **kwargs)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/nvidia/dali/plugin/tf.py", line 446, in __init__
    self._setup_inputs(input_datasets)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/nvidia/dali/plugin/tf.py", line 608, in _setup_inputs
    inputs_from_source = self._input_lists_from_source(callbacked_es_map)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/nvidia/dali/plugin/tf.py", line 568, in _input_lists_from_source
    source_desc, self._batch_size, external_source._batch)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/nvidia/dali/_utils/external_source_impl.py", line 460, in _get_generator_from_source_desc
    return get_iterable_from_iterable_or_generator(source_desc, is_batched)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/nvidia/dali/_utils/external_source_impl.py", line 409, in get_iterable_from_iterable_or_generator
    dtype, shape = _inspect_data(first, is_batched)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/nvidia/dali/_utils/external_source_impl.py", line 293, in _inspect_data
    as_numpy = batch_to_numpy(data, _tf_batch_error_msg, non_uniform_str=_tf_uniform_error_msg)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/nvidia/dali/_utils/external_source_impl.py", line 132, in batch_to_numpy
    assert_cpu_batch_data_type(batch, error_str)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/nvidia/dali/_utils/external_source_impl.py", line 100, in assert_cpu_batch_data_type
    elif assert_cpu_sample_data_type(batch, error_str):
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/nvidia/dali/_utils/external_source_impl.py", line 89, in assert_cpu_sample_data_type
    raise TypeError(error_str.format(type(sample)))
TypeError: Unsupported callback return type. Expected NumPy array, PyTorch or MXNet cpu tensors, DALI TensorCPU, list of those types or DALI TensorListCPU representing batch. Got `<class 'tuple'>` instead.
```

Could you please point out what I'm doing wrong?

PS: you would notice that I used `dali_tf.experimental.DALIDatasetWithInputs` instead of `dali_tf.DALIDataset` as of the recommendation in the execution trace when trying to use the latter in my case:
```
Traceback (most recent call last):
  File "keras_pipeline_trial.py", line 63, in <module>
    device_id=0)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/nvidia/dali/plugin/tf.py", line 770, in __init__
    raise ValueError(("DALIDataset got a DALI pipeline containing External Source "
ValueError: DALIDataset got a DALI pipeline containing External Source operator nodes. External Source nodes can be used to express placeholders for tf.data.Dataset inputs to DALI or to run user-provided Python code via `source` parameter. Support for Dataset inputs and External Source's `source` is allowed only in 'experimental.DALIDatasetWithInputs'.
```

**Comment by klecki** [comment]
Hi @pbruneau,
thank you for very clear description :)

Indeed, external inputs via `fn.external_source` nodes are supported only in `experimental.DALIDatasetWithInputs`. 
Currently only CPU data can be accepted this way - CuPy buffers won't work. As this feature is still in experimental phase we might extend it at some point, but now we are limited to what [tf.data.Dataset.from_generator](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#from_generator) or [tf.numpy_function](https://www.tensorflow.org/api_docs/python/tf/numpy_function) can handle - that is only CPU data. 

Here is a detailed tutorial on how to use `DALIDatasetWithInputs`: https://docs.nvidia.com/deeplearning/dali/main-user-guide/docs/examples/frameworks/tensorflow/tensorflow-dataset-inputs.html

In your case you can modify your iterator, to return just the loaded data as numpy arrays, so something similar to:
```
    def __next__(self):
        batch = []
        for _ in range(self.batch_size):
            im = imageio.imread(self.files[self.i])
            im = np.asarray(im) 
            batch.append(im)
            self.i = (self.i + 1) % self.n
        return (batch,)
```
And we can move the normalization to DALI pipeline:
```
with pipe_gpu:
    images = fn.external_source(source=eii_gpu, num_outputs=1, device="gpu")
    images = images / 255.0
    ...
```
As you placed the DALIDatasetWithInputs on `/gpu:0`, TF will do the transfer from CPU to GPU for us. This is current limitation, described in the tutorial - if you were to specify `fn.external_source(device="cpu")` in DALIDataset placed on `/gpu:0` we would still get that memory on GPU and DALI will need to transfer it back, resulting in a warning shown in your logs. We are evaluating possible solutions.

More details on supported mathematical operations can be found in the [doc](https://docs.nvidia.com/deeplearning/dali/main-user-guide/docs/math.html) and [examples](https://docs.nvidia.com/deeplearning/dali/main-user-guide/docs/examples/general/expressions/index.html) - specifically Python `float` constants are treated as `float32`, so the `images = images / 255.0` will promote the expression to `float32`.

If you have any more questions feel free to ask.

**Comment by pbruneau** [comment]
Hi @klecki, thanks for your answer,

But as far as I correctly understood it, my original issue remains. In support to my answer, here is an updated gist: https://gist.github.com/pbruneau/3e067421c61d3c99e27cc5b386cfbccd

**1/** 
Regarding the normalization, I tried out your suggestion (i.e. commenting line 30 and uncommenting line 43 in my gist). But then I get the following error:
```
Traceback (most recent call last):
  File "keras_pipeline_trial.py", line 43, in <module>
    images = images / 255.0 # uncomment if line 30 is commented
TypeError: unsupported operand type(s) for /: 'list' and 'float'
```

**2/**
As it is, the gist applies your suggestion - actually, it leaves the GPU completely aside, just trying to see if everything works as expected on the CPU and host memory. And I get exactly the same error, that is:
```
 Traceback (most recent call last):
  File "keras_pipeline_trial.py", line 64, in <module>
    device_id=0)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/nvidia/dali/plugin/tf.py", line 807, in __init__
    dataset_impl = _DALIDatasetImpl(pipeline, **kwargs)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/nvidia/dali/plugin/tf.py", line 446, in __init__
    self._setup_inputs(input_datasets)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/nvidia/dali/plugin/tf.py", line 608, in _setup_inputs
    inputs_from_source = self._input_lists_from_source(callbacked_es_map)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/nvidia/dali/plugin/tf.py", line 568, in _input_lists_from_source
    source_desc, self._batch_size, external_source._batch)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/nvidia/dali/_utils/external_source_impl.py", line 460, in _get_generator_from_source_desc
    return get_iterable_from_iterable_or_generator(source_desc, is_batched)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/nvidia/dali/_utils/external_source_impl.py", line 409, in get_iterable_from_iterable_or_generator
    dtype, shape = _inspect_data(first, is_batched)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/nvidia/dali/_utils/external_source_impl.py", line 293, in _inspect_data
    as_numpy = batch_to_numpy(data, _tf_batch_error_msg, non_uniform_str=_tf_uniform_error_msg)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/nvidia/dali/_utils/external_source_impl.py", line 132, in batch_to_numpy
    assert_cpu_batch_data_type(batch, error_str)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/nvidia/dali/_utils/external_source_impl.py", line 100, in assert_cpu_batch_data_type
    elif assert_cpu_sample_data_type(batch, error_str):
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/nvidia/dali/_utils/external_source_impl.py", line 89, in assert_cpu_sample_data_type
    raise TypeError(error_str.format(type(sample)))
TypeError: Unsupported callback return type. Expected NumPy array, PyTorch or MXNet cpu tensors, DALI TensorCPU, list of those types or DALI TensorListCPU representing batch. Got `<class 'tuple'>` instead.
```

Could you please tell me if I misunderstood something?

**Comment by klecki** [comment]
The DALIDatasetWithInputs doesn't handle well external_source with multiple outputs if you return just the batch (I used some placeholder data):
```
    def __next__(self):
        batch = []
        for _ in range(self.batch_size):
            im = np.full((200, 200, 3), 42, dtype=np.uint8)
            batch.append(im.astype(cp.float32))
            self.i = (self.i + 1) % self.n
        return batch
        ```
and adjust the external source by removing the num_outputs (there is a difference between `num_outputs=1` where it returns 1-element tuple and `num_outputs=None` when it just returns the output).
```
images = fn.external_source(source=eii_gpu, device="gpu")
```

Now I can run the provided code, pasting here full example for reference:
```
import glob
import numpy as np
import cupy as cp
import imageio
from random import shuffle
from nvidia.dali import Pipeline
import nvidia.dali.fn as fn
import nvidia.dali.plugin.tf as dali_tf
import tensorflow as tf

BATCH_SIZE = 16
FILE_PATH_GLOB = "/files/data/pokemon_jpg/*.jpg" # replacing with local path

class ExternalInputGpuIterator(object):
    def __init__(self, batch_size):
        self.files = glob.glob(FILE_PATH_GLOB)
        self.batch_size = batch_size
        shuffle(self.files)

    def __iter__(self):
        self.i = 0
        self.n = 200 # len(self.files)
        return self

    def __next__(self):
        batch = []
        for _ in range(self.batch_size):
            im = np.full((200, 200, 3), 42, dtype=np.uint8)
            batch.append(im.astype(cp.float32))
            self.i = (self.i + 1) % self.n
        return batch

# creating and testing iterator
eii_gpu = ExternalInputGpuIterator(BATCH_SIZE)
print(type(next(iter(eii_gpu))[0][0]))

# creating pipeline
pipe_gpu = Pipeline(batch_size=BATCH_SIZE, num_threads=2, device_id=0)
with pipe_gpu:
    images = fn.external_source(source=eii_gpu, device="gpu")
    images = fn.resize(images, size=[256,256])
    pipe_gpu.set_outputs(images)
pipe_gpu.build()

# testing pipeline
pipe_out_gpu = pipe_gpu.run()
batch_gpu = pipe_out_gpu[0].as_cpu()
img = batch_gpu.at(0)
print(img.shape)

# trying to create DALIDataset
shapes = ((BATCH_SIZE, 256, 256, 3),)
dtypes = (tf.float32,)

with tf.device('/gpu:0'):
    dataset = dali_tf.experimental.DALIDatasetWithInputs(
        pipeline=pipe_gpu,
        batch_size=BATCH_SIZE,
        output_shapes=shapes,
        output_dtypes=dtypes,
        device_id=0)

    for data in dataset:
        print(data)
        break
```

Sorry, I didn't try running it earlier.

I will add a task for investigating more scenarios with `num_outputs` specified, but I'm not sure if we will be able to handle them easily, if you need more outputs several separate `external_source` ops would be a way to go for now.

**Comment by pbruneau** [comment]
Thanks for your fast answer!

So it appears `num_outputs` was the cause of my misery after all! Actually, I did try to return `batch` instead of `(batch,)` in my iterator previously, but the pipeline was angry then (now I know it was because of `num_outputs`).

Now it seems to be fine - only the cupy case remains, and now the returned error message accurately reflects the aforementioned limitation: 
```
TypeError: Unsupported callback return type. Expected NumPy array, PyTorch or MXNet cpu tensors, DALI TensorCPU, list of those types or DALI TensorListCPU representing batch. Got `<class 'cupy._core.core.ndarray'>` instead.
```

I'm closing the issue then.

**Comment by pbruneau** [comment]
Hi again, I'm sorry to reopen the issue, but it is still happening if I want the pipeline to yield data and target (instead of data alone as up to now). Here is the adapted gist, which returns dummy labels along with the data: https://gist.github.com/pbruneau/2f76d33e15e2a3673825cc08bcc2415b

In a nutshell: if I want to return a batch and associated labels, I need to set `num_outputs = 2`... And here we go again, as Carl would say:

```
TypeError: Unsupported callback return type. Expected NumPy array, PyTorch or MXNet cpu tensors, DALI TensorCPU, list of those types or DALI TensorListCPU representing batch. Got `<class 'tuple'>` instead.
```

**Comment by klecki** [comment]
Hi, as previously suggested, if you want to do this, you need to implement two iterators that will work in sync and pass them to two separate external_source nodes, that don't specify `num_outputs` as a workaround. 

Here is an extended example:
```
import glob
import numpy as np
import cupy as cp
import imageio
from random import shuffle
from nvidia.dali import Pipeline
import nvidia.dali.fn as fn
import nvidia.dali.plugin.tf as dali_tf
import tensorflow as tf

BATCH_SIZE = 16
FILE_PATH_GLOB = "/files/data/pokemon_jpg/*.jpg" # replacing with local path

DATA_LEN = 42

class ExternalInputIteratorImages(object):
    def __init__(self, batch_size):
        self.files = glob.glob(FILE_PATH_GLOB)
        self.batch_size = batch_size
        shuffle(self.files)

    def __iter__(self):
        self.i = 0
        self.n = DATA_LEN # len(self.files)
        return self

    def __next__(self):
        batch = []
        labels = []
        for _ in range(self.batch_size):
            # im = imageio.imread(self.files[self.i])
            # im = np.asarray(im, dtype=np.float32)
            # im = im / 255.0

            # read image self.i
            im = np.full((10, 10, 3), 128, dtype=np.float32)

            batch.append(im)
            self.i = (self.i + 1) % self.n
        return batch

class ExternalInputIteratorLabels(object):
    def __init__(self, batch_size):
        self.files = glob.glob(FILE_PATH_GLOB)
        self.batch_size = batch_size
        shuffle(self.files)

    def __iter__(self):
        self.i = 0
        self.n = DATA_LEN # len(self.files)
        return self

    def __next__(self):
        batch = []
        labels = []
        for _ in range(self.batch_size):
            # Get the label for image self.i
            labels.append(np.array([1], dtype = np.uint8))
            self.i = (self.i + 1) % self.n
        return labels

# creating and testing iterator
eii_imgs = ExternalInputIteratorImages(BATCH_SIZE)
eii_labels = ExternalInputIteratorLabels(BATCH_SIZE)
print(type(next(iter(eii_imgs))[0][0]))

# creating pipeline
pipe = Pipeline(batch_size=BATCH_SIZE, num_threads=2, device_id=0)
with pipe:
    images = fn.external_source(source=eii_imgs, device="cpu")
    labels = fn.external_source(source=eii_labels, device="cpu")
    images = fn.resize(images, size=[256,256])
    pipe.set_outputs(images, labels)
pipe.build()

# testing pipeline
pipe_out = pipe.run()
batch = pipe_out[0]
img = batch.at(0)
print(img.shape)

# trying to create DALIDataset
shapes = ((BATCH_SIZE, 256, 256, 3), (BATCH_SIZE))
dtypes = (tf.float32, tf.uint8)

with tf.device('/cpu:0'):
    dataset = dali_tf.experimental.DALIDatasetWithInputs(
        pipeline=pipe,
        batch_size=BATCH_SIZE,
        output_shapes=shapes,
        output_dtypes=dtypes,
        device_id=0)

    for d in dataset:
        print(d)
        break
```

**Comment by pbruneau** [comment]
Hi,

Indeed you adressed it initially, my bad! Sorry to have you repeating. Closing right away.

**Comment by klecki** [comment]
Sure, no problem.

I'm happy to hear any feedback regarding this feature as we want to move it out of the experimental stage.

**Comment by pbruneau** [comment]
Hi again,

If you're interested in additional feedback: in the end it works as suggested. But I was hoping for better performance in comparison to my previous pipeline (based on a Keras Sequence subclass + Numpy + OpenCV). Disappointingly, it is almost 50% slower than the single threaded version of my pipeline (I also have a multi-threaded version based on concurrent.futures, which has runtime divided by ~6). BTW, increasing the `num_threads` parameter in the `Pipeline()` call does not seem to bring much improvement.

Please tell me whenever you would want additional details.
