### ISSUE TITLE
Varying batch sizes with Dali

### ISSUE THREAD

**Issue by sosherio** [NVIDIA/DALI#333]
Is it possible to change the batch sizes while training a network using Dali?

**Comment by yaysummeriscoming** [comment]
Is it possible to rebuild the processing pipe with a different batch size during training?  One possible use case is the variable resolution training approach used by fast.ai:

https://www.fast.ai/2018/08/10/fastai-diu-imagenet/
https://www.fast.ai/2018/04/30/dawnbench-fastai/

They apparently got the idea from some GAN papers.

**Comment by JanuszL** [comment]
Hi,
It sounds like a reasonable use case. I will add this feature request to our back log.
Tracked internally DALI-413.

**Comment by ptrendx** [comment]
Just to add to this: rebuilding with different batch size is possible and, as long as you don't do it very often, it should be fast enough to not slow down training. Just make sure that you del() the previous pipeline to ensure that memory is freed from the pipeline you no longer use.

**Comment by sosherio** [comment]
I have a similar use case as mentioned by @yaysummeriscoming above.

Also, even though rebuilding the pipeline with different batch sizes is possible in the current verison, I think it comes with some major complications with respect to the `file list` passed to the reader, especially if the batch size needs to be changed dynamically within an epoch, because rebuilding the pipeline essentially means the data will be loaded from the beginning again.

**Comment by JanuszL** [comment]
Hi,
Now you can change the batch size using [the `external_source` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.external_source) but just providing any number of sample each iteration.
