### ISSUE TITLE
how to resize the image randomly？

### ISSUE THREAD

**Issue by hiredd** [NVIDIA/DALI#3331]
I have a input  image with size of HWC= [256 ,256 ,3]
i want to resize it to HWC= [256*ratio, 256*ratio ,3]] ,  in which ratio is between random.uniform(range=[1,3]).
and then crop the resized image with fixed size ,such as HWC= [128,128 ,3]. 
how can i do it? 
it seems nvidia.dali.fn.random_resized_crop does not work

**Comment by JanuszL** [comment]
Hi @hiredd,

The `random_resized_crop ` has a bit more different purpose. What you can do is something like this:
```
size = fn.random.uniform(range=[1, 3], shape=[2]) * 256
images = fn.resize(images, size=size)
```
Then just call [`crop`](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.crop)/[`crop_mirror_normalize`](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.crop_mirror_normalize) on the output to get `[128,128 ,3]` shaped output.

**Comment by hiredd** [comment]
thanks for your replay  I write the code as this:
def define_graph(self):
        self.img1 = self.input_img1()
        self.img2 = self.input_img2()
        self.img3 = self.input_img3()
        ratio = fn.random.uniform(range=[1,3])
        img1 = fn.decoders.image(self.img1)
        img2 = fn.decoders.image(self.img2)
        img3 = fn.decoders.image(self.img3)
        n_sizes = fn.shapes(img1)[:2]
        out_sizes =  n_sizes * ratio

        img1 = fn.resize(img1,size=out_sizes)
        img2 = fn.resize(img2,size=out_sizes)
        img3 = fn.resize(img3,size=out_sizes)

**Comment by JanuszL** [comment]
Hi @hiredd,

In your case, the output size of each image in the batch differs, while the error message says that in your use case they need to be uniform. So you need to resize/crop all of them to the same size.

**Comment by hiredd** [comment]
thanks！   how can I print the value  variable " n_sizes"

**Comment by hiredd** [comment]
the size of the input image  is  same

**Comment by JanuszL** [comment]
Hi @hiredd,

I recommend using [the `peek_image_shape` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.peek_image_shape) as `shapes` will return output on the same device as the input, while the resize accepts parameters only from the CPU (so if you use `mixed` decoder it won't work).
Something like this should give you insight into image sizes:
```
import os
import numpy as np
import nvidia.dali.fn as fn
from nvidia.dali import pipeline_def

batch_size = 1

@pipeline_def
def simple_pipeline():
    jpegs, _ = fn.readers.file(files=[YOUR_IMAGES])
    n_sizes = fn.peek_image_shape(jpegs)
    images = fn.decoders.image(jpegs)
    size = fn.random.uniform(range=[1, 3], shape=[2]) * 256
    images = fn.resize(images, size=size)

    return images, n_sizes

pipe = simple_pipeline(batch_size=batch_size, num_threads=4, prefetch_queue_depth=2, device_id=0)
pipe.build()
pipe.run()
out = pipe.run()
print(out[1].as_array())```

**Comment by hiredd** [comment]
> Hi @hiredd,
> 
> I recommend using [the `peek_image_shape` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.peek_image_shape) as `shapes` will return output on the same device as the input, while the resize accepts parameters only from the CPU (so if you use `mixed` decoder it won't work).
> Something like this should give you insight into image sizes:
> 
> ```
> import os
> import numpy as np
> import nvidia.dali.fn as fn
> from nvidia.dali import pipeline_def
> 
> batch_size = 1
> 
> @pipeline_def
> def simple_pipeline():
>     jpegs, _ = fn.readers.file(files=[YOUR_IMAGES])
>     n_sizes = fn.peek_image_shape(jpegs)
>     images = fn.decoders.image(jpegs)
>     size = fn.random.uniform(range=[1, 3], shape=[2]) * 256
>     images = fn.resize(images, size=size)
> 
>     return images, n_sizes
> 
> pipe = simple_pipeline(batch_size=batch_size, num_threads=4, prefetch_queue_depth=2, device_id=0)
> pipe.build()
> pipe.run()
> out = pipe.run()
> print(out[1].as_array())```
> ```
Thank you for your answer !  it helps me a lot~
“while the resize accepts parameters only from the CPU ”  means DALI  only resize the image by cpu? or the DALI will copy the input to the gpu and resize ？ besides， what is difference between the  “”nvidia.dali.ops.Resize“ and the fn.resize?  sorry for troubbling for with this simple questions
,

**Comment by JanuszL** [comment]
Hi @hiredd,

> “while the resize accepts parameters only from the CPU ” means DALI only resize the image by cpu? or the DALI will copy the input to the gpu and resize ?

You can read about this [here](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/pipeline.html#processing-graph-structure). In overall, keyword arguments, like `size` needs to be placed on the CPU side, however the inputs, like images in case of the `resize` operator need to placed on the same device as the operator - either CPU or GPU. In other words, you can use input on CPU or GPU, while the named arguments need to be on the CPU.

> what is difference between the “”nvidia.dali.ops.Resize“ and the fn.resize?

the functional (`fn` API) is just syntactic sugar over the `nvidia.dali.ops.`, and it makes the code shorter and more comprehensive. Functionally it is the same. We recommend switching to the functional whenever possible.

**Comment by hiredd** [comment]
thanks for your answer

**Comment by JanuszL** [comment]
Hi @hiredd,

In the default mode, the `external_source` operator works in the main python thread what blocks the execution and may lead to inferior performance. I recommend checking the parallel mode described [here](https://docs.nvidia.com/deeplearning/dali/main-user-guide/docs/examples/general/data_loading/parallel_external_source.html) or [here](https://docs.nvidia.com/deeplearning/dali/main-user-guide/docs/examples/general/data_loading/parallel_external_source_fork.html).
