### ISSUE TITLE
i have a proble about Pipeline?

### ISSUE THREAD

**Issue by daixiangzi** [NVIDIA/DALI#3335]
in Dali ,whether customize WeightedRandomSampler ? i find Pipeline Api have't about params

**Comment by JanuszL** [comment]
Hi @daixiangzi,

Build-in DALI data readers don't support user-provided sampling methods. However, there is [the `external_source`](https://docs.nvidia.com/deeplearning/dali/main-user-guide/docs/supported_ops.html#nvidia.dali.fn.external_source) operator that allows you to implement your custom loading logic. Please check following tutorials [1](https://docs.nvidia.com/deeplearning/dali/main-user-guide/docs/examples/general/data_loading/external_input.html), [2](https://docs.nvidia.com/deeplearning/dali/main-user-guide/docs/examples/general/data_loading/parallel_external_source.html), [3](
https://docs.nvidia.com/deeplearning/dali/main-user-guide/docs/examples/general/data_loading/parallel_external_source_fork.html) to learn more about its usage.

**Comment by daixiangzi** [comment]
> Hi @daixiangzi,
> 
> Build-in DALI data readers don't support user-provided sampling methods. However, there is [the `external_source`](https://docs.nvidia.com/deeplearning/dali/main-user-guide/docs/supported_ops.html#nvidia.dali.fn.external_source) operator that allows you to implement your custom loading logic. Please check following tutorials [1](https://docs.nvidia.com/deeplearning/dali/main-user-guide/docs/examples/general/data_loading/external_input.html), [2](https://docs.nvidia.com/deeplearning/dali/main-user-guide/docs/examples/general/data_loading/parallel_external_source.html), [3](https://docs.nvidia.com/deeplearning/dali/main-user-guide/docs/examples/general/data_loading/parallel_external_source_fork.html) to learn more about its usage.

i understand ,thank you
