### ISSUE TITLE
two bug about file "include/dali/core/dev_buffer.h"

### ISSUE THREAD

**Issue by tendar** [NVIDIA/DALI#3340]
1. the first bug is:  
void copy(const DeviceBuffer &src, cudaStream_t stream = 0) {
    clear();
    resize(src.size());
    copyH2D(data_.get(), src.data(), size(), stream);  // here it should be "copyD2D"
  }

2. the second bug is, the 4 test cases as follows should sync the stream
TEST(DeviceBuffer, FromHost) {
  DeviceBuffer<int> db;
  std::vector<int> v1(123), v2;
  db.from_host(v1);
  ASSERT_EQ(db.size(), v1.size());
  v2.resize(db.size());
  copyD2H(v2.data(), db.data(), v2.size());
  // add sync stream
  EXPECT_EQ(v1, v2);
}

**Comment by mzient** [comment]
@tendar Thank you for reporting the bug.
While the first one is indeed a bug, the second relies on the fact that copying from device to unregistered host memory results in implicit synchronization, so it should work as expected.

**Comment by tendar** [comment]
@mzient  Thank you for your reply.
I got it,  cudaStream = 0  means a  synchronization operation. thank you.

**Comment by mzient** [comment]
@tendar 
It's not like this. It's not about the stream (stream 0 is just as asyncrhonous as any) - it's about the kind of memory we're copying to. If the memory is registered (i.e. directly accessible to the device) - such as memory allocated with `cudaMallocHost` - then the copy is truly asynchronous. If, however, the memory is not registered with the device, then there are two ways to go for the driver:
- copy (asynchronously) to a driver-internal staging buffer, synchronize and copy to the target buffer
- register the target buffer in the driver, issue a copy, wait until the copy finishes and unregister the buffer
Both options include synchronization.

**Comment by mzient** [comment]
The bug was fixed. Closing.
