### ISSUE TITLE
Create multiple segments of the same spectrogram

### ISSUE THREAD

**Issue by sofiaele** [NVIDIA/DALI#3368]
Hello, 

I just started using dali and experimenting with it. So I am kind of newbie!

My goal is to deploy an ensemble model to the triton inference server which consists of a dali pipeline model (for feature extraction) and a cnn (for predictions). The entrie in the dali pipeline is an audio signal from which I extract the mel spectrogram and send it to cnn for testing. 
So far so good!

What I am trying to do now is to segment the spectrogram in the dali pipeline so that I can create multiple samples that will be sent to the cnn model to generate predictions. 

To do this I thought of placing the segments in a common batch to be sent to the prediction model. Nevertheless it is difficult to create this batch of segments due to limitation of dali operations. 

Ιs there any idea of how to do this? 
Is there another way to  achieve this without sending multiple requests from the client-side (just doing all the segmentation functionality inside the dali pipeline) ? 

Thanks in advance!

**Comment by JanuszL** [comment]
Hi @sofiaele,

As I understand correctly your need to change the batch size inside the pipeline. So you have n spectrograms and then x * n samples (where x is the number of segments from each spectrogram).
I'm afraid it is not possible in DALI now.
What you can do is:
- run the inference multiple times over the same sample but each of them gets different slice arguments together with the audio sample itself
- provide only a part of the whole batch as a valid sample, rest fill with empty data, then use permute_batch to clone spectrograms across the batch and slice them

**Comment by JanuszL** [comment]
Hi @sofiaele,

> I have another question: If I provide a batch input to the dali pipeline (with batch size greater than 1) consisted of multiple audio signals, is it possible to extract spectrogram for each of the samples of the batch

As I understand correctly your ask you want to provide a batch of audio samples and get a batch of spectrograms? If so there is nothing you need to do, `dali.fn.spectrogram operation expects 1D array` means that each sample needs to be a 1D array, not the whole batch. In the case of DALI batch processing is transparent, and the operators should behave the same way no matter if you provide 1 sample (batch==1) or many.

**Comment by sofiaele** [comment]
Hi @JanuszL,

I see what you mean! But when I am trying to extract spectrograms from a batch (batch_size = 102) of audio samples I get this error: 

[/opt/dali/dali/operators/signal/fft/spectrogram.cc:196] Assert on "extent == 1 || extent == n" failed: Input data must be 1D or all but one dimensions must be degenerate (extent 1). Got: 102 x 144000

**Comment by JanuszL** [comment]
Hi @sofiaele,

It seems that you are not providing data to the pipeline correctly.
Do you use external_source or file reader and decoder?
You also need to set the batch size to 102.
If you can provide a code snippet that would reproduce your problem it would help a lot.

**Comment by sofiaele** [comment]
Actually my dali pipeline is part of an ensemble model. So I use external_source to read the batch provided by the client. Specifically: 

1. In the client-side I segment the audio signal into samples of 3sec so that I produce a batch of 102 samples each of wich has length 144000 (numpy array of size 102 x 144000) .
2. Then the serialized dali pipeline goes as follows: 

```
@pipeline_def(batch_size=102, num_threads=4, device_id=None)
def inception_pipeline():
    batched_audio = fn.external_source(device=device, name="DALI_INPUT_0")
    spectrogram = fn.spectrogram(bathed_audio, device=device, nfft=n_fft, window_length=n_fft,
                                 window_step=hop_length)
```
This layout worked well for batch size=1, but stopped working as soon as I created more samples (batch size=102).

Is there any step I have missed?

**Comment by szalpal** [comment]
Hi @sofiaele !

How is your DALI model configured within Triton? Could you also show how you send the requests to the Triton server?

A tip that might help you here is that the `batch_size` property in `@pipeline_def` decorator is actually a `max_batch_size`. Therefore it doesn't matter if you put `1` or `102` there, the DALI pipeline is going to work in the same way. If your pipeline works for `batch_size=1` and doesn't for `batch_size=102`, then it might suggest, that there is something wrong in model configuration or sending the request to the server.

**Comment by sofiaele** [comment]
Hi  @szalpal !

Thank you very much for your reply!

You are right. The problem was in the configuration file of dali model. I thought of putting max_batch_size = 0 and -1 as first dimension of 'dims', because somewhere I read that this way the batch_size can be variable. But as soon as I changed it to 102, it worked. 

Does this mean that batch_size cannot be variable? As the audio input may differ from call to call, the number of audio segments generated is not fixed and so the batch_size changes each time.

**Comment by szalpal** [comment]
@sofiaele 

`batch_size` can vary from iteration to iteration. All you need to remember is that the value you pass to the `@pipeline_def(batch_size=...)` decorator is the maximum batch size that will be handled by this DALI pipeline. On top of that, this value will be overwritten by the `max_batch_size` value, that you passed to the `config.pbtxt` file. So as long as you set the `max_batch_size` property in `config.pbtxt`, you can put any positive number in `@pipeline_def(batch_size=...)`. The good practice would be to keep both of these values the same.

Therefore in your use-case everything should work fine.

**Comment by sofiaele** [comment]
@szalpal 

Yes I understand your point. Maybe I didn't explain properly. I meant that I want the max_batch_size in the config file to be variable. So as I understand, the only way is to set it at a high value that you know is not going to be exceeded. (!?)

**Comment by JanuszL** [comment]
Hi @sofiaele,

> So as I understand, the only way is to set it at a high value that you know is not going to be exceeded. (!?)

That is correct. It is the main purpose of this variable - to let know DALI the upper limit of the batch it may need to process so DALI can preallocate some buffers ahead of time.

**Comment by sofiaele** [comment]
@JanuszL @szalpal 

Thank you very much guys! You helped a lot.
