### ISSUE TITLE
Error checking out the RMM library in v1.5.0 or earlier

### ISSUE THREAD

**Issue by kzibrahim** [NVIDIA/DALI#3380]
While attempting to checkout DALI v1.5.0 or earlier I encountered an error in getting the third party library rmm. 

git  clone --recursive --branch  v1.5.0 https://github.com/NVIDIA/DALI DALI_v1.5.0
...
fatal: The remote end hung up unexpectedly
Fetched in submodule path 'third_party/rmm', but it did not contain c50cf5a4f3f331828724640d88fe97a25d30b509. Direct fetching of that commit failed.

Downloading it manually, ignoring the special commit, causes the build to fail.

**Comment by mzient** [comment]
@kzibrahim That commit wasn't tagged and was not at the head of any branch. I added a tag and it works now.

**Comment by yiakwy-xpu-ml-framework-team** [comment]
@mzient for debug purpose, I recently rebuild DALI from scratch to have a trial to work with **NLP** in LLM. I am specifically interested in NV's version of prefetch, and I found DALI might be an easy way to work with pytorch. Correct me if I am wrong.

I found RMM version is no correctly mentioned in .gitmodule or dockerfile, by default:

<img width="750" alt="截屏2024-01-31 14 35 36" src="https://github.com/NVIDIA/DALI/assets/89890040/4afb3252-56b7-4b6c-9661-7dbc5c84c7d5">

I checkout RMM and unexpectedly found QNX_build branch has the definition:

<img width="750" alt="截屏2024-01-31 14 35 07" src="https://github.com/NVIDIA/DALI/assets/89890040/efbd5333-fbe9-4fb6-9738-8be3c5c797b2">

Note without adding branch or commit in .gitmodule, git submodule init will fetch all the branches. Hence I highly recommend the team to review .gitmodules and dockerfile again.

Have a nice day.

**Comment by mzient** [comment]
Hello @yiakwy-xpu-ml-framework-team ,
You must be using an outdated version of DALI - we haven't used RMM for a long time now (I think more than a year).
Please use a recent version of DALI to avoid the problem.

Thanks,
Michal

**Comment by yiakwy-xpu-ml-framework-team** [comment]
Hi @mzient I am using NGC which shipped with DALI 1.30 . And you can checked the latest NGC, which shipped with DALI 1.33.

The container contains the lastest pytorch feature. Could you help check with product team whether the DALI version is correct ?

Thank you michal.

**Comment by JanuszL** [comment]
Hi @yiakwy-xpu-ml-framework-team,

DALI 1.30 is quite recent. The mentioned error doesn't correspond to the source code - https://github.com/NVIDIA/DALI/blob/release_v1.30/include/dali/core/mm/memory_resource.h#L21, as @mzient stated we no longer use RMM directly. Can you tell us more about how the version of DALI available in the container corresponds to the source code you want to compile on your own? What do you want to achieve by compiling it from scratch?
