### ISSUE TITLE
DALI Error when executing Mixed operator; Assert on cinfo.output_height = cinfo.output_scanline

### ISSUE THREAD

**Issue by shenwenxiao** [NVIDIA/DALI#3409]
There is an error when I train ResNet50 with Imagenet dataset. Then the program is stopped by the error. I check the image "n04418357/n04418357_4671.JPEG" and make sure that it is a common image and can be opened without any warning." How can I solve the problem?
![QQ图片20211007105433](https://user-images.githubusercontent.com/48246620/136313586-bbe9c94e-6ea3-4f6d-9401-165858c6d077.jpg)

**Comment by JanuszL** [comment]
Closed as stale.
