### ISSUE TITLE
RandomBBoxCrop - aspect_ratio

### ISSUE THREAD

**Issue by kache1995** [NVIDIA/DALI#3424]
when i set the aspect_ratio=[1.0,1.0]， from the point of api document，the crop window should be square windows， but the result is not square windoow, the result is a rectangle and its crop_w/crop_h is same as images.
why ？ why the result is not same as what in api document？

**Comment by kache1995** [comment]
> Thanks for reporting the issue, @kache1995.
> 
> Most likely RandomBBoxCrop is falling into the "no_crop" case, which is by default one of the allowed outcomes. This can happen randomly or when the threshold requirements are too high, so no valid crop will satisfy it.
> 
> If you don't want to allow the no-crop case as a valid outcome, you can disable it by setting `allow_no_crop=False`. If you do so, please remember to set `total_num_attempts` to prevent running into an infinite loop if the threshold requirements are too high. For example, if you set `total_num_attempts=100`, the algorithm will try up to 100 times to produce a cropping window satisfying your threshold requirements, and after 100 tries it will use the best candidate. If you let the default value it will continue trying until satisfying the threshold requirement, potentially running into an infinite loop if it's not achievable.

thank you for reply!
if the no_crop case happen, the result should be the source image, but i find the result is a crop_window, but the crop has the same w/h ratio as the source images.
how to explain this phenomenon？

here is example:
![image](https://user-images.githubusercontent.com/43060760/137263206-4c098fa6-1822-462c-b28c-b765562f7e44.png)
blue is the crop window

**Comment by jantonguirao** [comment]
@kache1995

After looking at the implementation, I confirm this is a problem. The crop dimensions are calculated in relative terms, so the aspect ratio range doesn't really reflect the actual aspect ratio, but the relative one to the input dimensions. This is because we don't have info on the original image's aspect ratio.

I agree this behavior is misleading. We will think about a solution and let you know.

Thanks again for reporting this.

**Comment by JanuszL** [comment]
The DALI 1.8 version has been released that includes the fix.
