### ISSUE TITLE
Resizing Video frames before feeding it to model

### ISSUE THREAD

**Issue by mritunjaymusale** [NVIDIA/DALI#3427]
I recently came accross this library and I have been trying to incorporate it into my project. The current issue that I am facing is how do I resize each frame before feeding it to my model.
my current state of code is as follows:

```
@pipeline_def
def video_pipe(filenames):
    video = fn.readers.video(device="gpu", filenames=filenames, sequence_length=sequence_length,
                             initial_fill=initial_prefetch_size)
    return video

pipe = video_pipe(filenames=video_filename, batch_size=batch_size, num_threads=2, device_id=0)
pipe.build()

pipe_output=pipe.run()
```
The resize operation shown in [docs](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/image_processing/resize.html) is designed for images, is there any way to use this operation for individual video frames ?

**Comment by JanuszL** [comment]
Hi @mritunjaymusale,

Yes, you can just apply [the `resize` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.resize) on the video data. Each sequence will be uniformly resized according to provided parameters. You can also check [the fused `resize` with the `video reader`](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.readers.video_resize).
