### ISSUE TITLE
Deprecated import of Iterable from the 'collections' module

### ISSUE THREAD

**Issue by anibali** [NVIDIA/DALI#3428]
Importing the DALI PyTorch plugin results in the following deprecation notice:

```
/home/aiden/Software/miniconda3/envs/dettrack-pytorch/lib/python3.8/site-packages/nvidia/dali/plugin/base_iterator.py:21: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  from collections import Iterable
```

I believe that the solution is to replace this line: https://github.com/NVIDIA/DALI/blob/53c66becd637a236157907395b4abb4ff35b466e/dali/python/nvidia/dali/plugin/base_iterator.py#L21

with

```python
from collections.abc import Iterable
```

**Comment by JanuszL** [comment]
Hi @anibali,

Thank you for reporting this issue. https://github.com/NVIDIA/DALI/pull/3429 should fix that.

**Comment by JanuszL** [comment]
The DALI 1.8 version has been released that includes the fix.
