### ISSUE TITLE
wheel for aarch64 with cuda10.2?

### ISSUE THREAD

**Issue by twmht** [NVIDIA/DALI#3430]
Hi,

I am using jetpack 4.5 now and it uses cuda10.2.

But the prebuilt only provides cuda11 for aarch64.

Any idea?

**Comment by klecki** [comment]
Hi @twmht,
we do not provide official DALI builds for Jetson, but you can build one on your own following this instructions: https://docs.nvidia.com/deeplearning/dali/main-user-guide/docs/compilation.html#cross-compiling-for-aarch64-jetson-linux-docker

**Comment by klecki** [comment]
We are currently in the process of updating the instruction, you can take a look at the: https://github.com/NVIDIA/DALI/pull/3432

**Comment by twmht** [comment]
ok.

Finally I successfully built the wheel by windows docker.

for windows users, there are many ^M and ^r from the git cloned files.

so the better way is to clone the DALI source in the interactive mode. otherwise there would be many build problems.

the steps would be following after you build the image

```
docker -it nvidia/dali:builder_aarch64-linux bash
cd /
git clone https://github.com/NVIDIA/DALI.git --recursive
mkdir build
cd build
```

then run the commands under CMD

```
WERROR=ON           \
ARCH=aarch64-linux  \
BUILD_TEST=ON       \
BUILD_BENCHMARK=OFF \
BUILD_NVTX=OFF      \
BUILD_LMDB=ON       \
BUILD_JPEG_TURBO=ON \
BUILD_LIBTIFF=ON    \
BUILD_LIBSND=ON     \
BUILD_LIBTAR=ON     \
BUILD_FFTS=ON       \
BUILD_NVJPEG=OFF    \
BUILD_NVJPEG2K=OFF  \
BUILD_NVOF=OFF      \
BUILD_NVDEC=OFF     \
BUILD_NVML=OFF      \
VERBOSE_LOGS=OFF    \
BUILD_CUFILE=OFF    \
TEST_BUNDLED_LIBS=NO\
WHL_PLATFORM_NAME=manylinux2014_aarch64            \
BUNDLE_PATH_PREFIX="/usr/aarch64-linux-gnu"        \
EXTRA_CMAKE_OPTIONS="-DCMAKE_TOOLCHAIN_FILE:STRING=$PWD/../platforms/aarch64-linux/aarch64-linux.toolchain.cmake \
                        -DCMAKE_COLOR_MAKEFILE=ON                                 \
                        -DCMAKE_CUDA_COMPILER=/usr/local/cuda-10.2/bin/nvcc       \
                        -DCUDA_HOST=/usr/local/cuda-10.2                          \
                        -DCUDA_TARGET=/usr/local/cuda-10.2/targets/aarch64-linux" \
cd /DALI/dali_tf_plugin                         && \
bash /DALI/dali_tf_plugin/make_dali_tf_sdist.sh && \
mv /dali_tf_sdist/*.tar.gz /wheelhouse/         && \
 cp -r /wheelhouse /dali/
```
