### ISSUE TITLE
How do you use gpudirect storage in Dali?

### ISSUE THREAD

**Issue by ksm9413** [NVIDIA/DALI#3449]
How is it related to gpudirect storage dali and how can I utilize gpudirect storage in deep learning frameworks such as sensorflow and pytorch?

Lastly, what should I do if Dali and gpudirect storage are linked?

**Comment by johnnynunez** [comment]
It is possible with rtx 3090 FE?

**Comment by johnnynunez** [comment]
thanks @JanuszL because magnus IO is only for data gpus like a100 etc

**Comment by noamsgl** [comment]
Hi,
Is the Webdataset format also GPUDirect Compatible?
Concerning speed with DALI readers, is it preferable to store data as numpy v1 or Webdataset?

**Comment by JanuszL** [comment]
Hi @noamsgl,

Currently, DALI Webdataset is not GPUDirect compatible however there are no technical reasons not to make it. The challenge is that in many cases it may be inefficient. If the data can be directly consumed by the GPU then it should work just fine, but if this needs parsing on the GPU first (like the image or video decoding) you need the data on the CPU first anyway.

**Comment by noamsgl** [comment]
Hi @JanuszL  Thanks for you reply!

The data is already in Numpy format inside the .Tar archives which the Webdataset consists of.
The benefit of enabling GPU direct would be to reduce the need to extract the .Tar archives and create millions of tiny .npy files on the hard drive, because this amount can be hard to work with.

**Comment by JanuszL** [comment]
Hi @noamsgl,

For the numpy files we still need to preserve a part of the data on the CPU - headers, to parse it and know how to read the rest. In the case of multiple small numpy files, the GPU direct may not yield the expected speed up as the constant overhead of initiating the transfer may outweigh the reduction of the overhead of the transfer itself.
In your case, the web dataset should be good enough, and there is no overhead of extracting multiple small files, but rather an overhead of reading them from the container. Currently, DALI doesn't provide the ability to read numpy files directly from the web dataset, but I think it should be doable. Let me add this to our to-Do list.
