### ISSUE TITLE
DALI reading problem

### ISSUE THREAD

**Issue by nlp-tokio** [NVIDIA/DALI#3473]
I use code file [Dali main.py](https://github.com/NVIDIA/DALI/blob/54034c4ddd7cfe2b6dda7e8cec5f91ae18f7ad39/docs/examples/use_cases/pytorch/resnet50/main.py) to train my won model, but find that, DALI's processing speed (500 FPS)is faster at the beginning and end of every epoch, the average of epoch is 300 FPS.

By observing iotop, it is found that DALI will not read data from disk at the beginning and end of every epoch

**Comment by JanuszL** [comment]
Hi @nlp-tokio,

In this script, DALI randomly accesses the data from the disc. The OS has a [disc cache in RAM](https://medium.com/marionete/linux-disk-cache-was-always-there-741bef097e7f). The data from the beginning and the end of the epoch can be already in the RAM so no physical access to the disc needs to happen and that is why you may see better performance. DALI speeds up the data processing but if the disc access it the main bottleneck DALI cannot help much.
