### ISSUE TITLE
Slicing/cropping video in the depth dimension with random start position.

### ISSUE THREAD

**Issue by Michelvl92** [NVIDIA/DALI#3478]
Hi,

I want to slice/crop a video (read with `fn.readers.video_resize` ) randomly at a different starting position (for every new video) with a fixed depth window. I have done this in the following way:

```
    pos_x = fn.random.uniform(range=(0., 1.))
    pos_y = fn.random.uniform(range=(0., 1.))
    pos_z = fn.random.uniform(range=(0., 1.))
    video = fn.crop(video, crop=(8, 100, 100), crop_pos_x=pos_x, crop_pos_y=pos_y, crop_pos_z=pos_z)
```

But I don't have the feeling that crop_pos_z is changing. Is this the correct way?

**Comment by jantonguirao** [comment]
@Michelvl92 
`fn.crop` API is meant to work with specifically named dimensions in the layout, namely: 'D', 'H', 'W'. In your case, videos have layout `"FHWC"`, so there is no explicit depth dimension. Depth is used in volumetric images. What I believe is happening in your case is that the `z` dimension is being ignored.

What you'd like to do is to treat the frame dimensions as a depth dimension. You can achieve that with the `fn.reshape` operator, which is an operator that allow you to change the interpretation of the shape and layout of the tensor, without needing to make copy of the data.

```
video = fn.reshape(video, layout='DHWC')  # Assuming your original layout was 'FHWC'
video = fn.crop(video, ...)
```

Hope that helps

**Comment by Michelvl92** [comment]
@jantonguirao 
Thank you for your clear explanation.
