### ISSUE TITLE
TFrecord reader ignores last_batch_policy='PARTIAL'

### ISSUE THREAD

**Issue by henrique** [NVIDIA/DALI#3488]
nvidia.dali.fn.readers.tfrecord seems to ignore last_batch_policy, repeating the first images on the last batch, so it will affect validation if the total number of images is not divisible by the batch size.
Is there another way of doing this?
Thank you

```
from nvidia.dali.plugin.pytorch import DALIClassificationIterator, LastBatchPolicy
from nvidia.dali.pipeline import Pipeline
import nvidia.dali.fn as fn
import nvidia.dali.types as types
import nvidia.dali.tfrecord as tfrec

def dali_dataloader(
        tfrec_filenames,
        tfrec_idx_filenames,
        shard_id=0,
        num_shards=1,
        batch_size=128,
        num_threads=24,
        resize=256,
        crop=224,
        prefetch=20,
        gpu_aug=True):
    pipe = Pipeline(batch_size=batch_size,
                    num_threads=num_threads,
                    device_id=0)
    with pipe:
        inputs = fn.readers.tfrecord(
            path=tfrec_filenames,
            index_path=tfrec_idx_filenames,
            random_shuffle=False,
            shard_id=shard_id,
            num_shards=num_shards,
            initial_fill=0,
#             read_ahead=True,
#             prefetch_queue_depth=prefetch,
            pad_last_batch=False,
            stick_to_shard=True,
            name='Reader',
            features={
                'image/encoded': tfrec.FixedLenFeature((), tfrec.string, ""),
                'image/class/label': tfrec.FixedLenFeature([1], tfrec.int64,  -1),
            })
        decode_device = "mixed" if gpu_aug else "cpu"
        resize_device = "gpu" if gpu_aug else "cpu"

        # decode jpeg and resize
        images = fn.decoders.image(inputs["image/encoded"],
                                   device=decode_device,
                                   output_type=types.RGB)
        images = fn.resize(images, device=resize_device, resize_shorter=resize)
        images = fn.crop_mirror_normalize(images,
                                          crop=(crop, crop),
                                          output_layout="HWC",
                                          mirror=False)
        label = inputs["image/class/label"] - 1  # 0-999
        pipe.set_outputs(images.gpu(), label.gpu())

    pipe.build()
    loader = DALIClassificationIterator(
        pipe,
        reader_name="Reader",
        last_batch_padded=False,
        auto_reset=True,
        last_batch_policy='PARTIAL',
    )
    return loader


train_loader = dali_dataloader(
    batch_size=8,
    tfrec_filenames=list_of_files[0],
    tfrec_idx_filenames=indexes[0],
)
print(len(train_loader))
```
running this on a standard imagenet tfrecord with 1252 images, DALI generates 157 batches (the last one padded again with the first 4 images)

`nvidia-dali-cuda110     1.7.0`

**Comment by jantonguirao** [comment]
Here there are 3 variables that control what happens:
- `tfrecord` operator's  `pad_last_batch`. This control what is the content of the "tail" of the last batch of the epoch provided. If set to true, it will pad the last batch by repeating the last sample in the epoch. If set to false, the tail will contain samples from the second epoch.
- `DALIClassificationIterator` iterator's `last_batch_padded`. It tells the iterator about the contents the last batch.
- `DALIClassificationIterator` iterator's `last_batch_policy`. It controls what the iterator does with the tail of the last batch. If set to partial, the tail will be simply ignored

So, in order to avoid samples from the next epoch in your last batch you should set:
```
pad_last_batch=True,               # The reader will fill the tail of the last batch with the last sample of the epoch (won't wrap around)
last_batch_padded=True,         # We tell the iterator that we are padding the last batch
last_batch_policy='PARTIAL'     # Drop the tail of the last batch
```

**Comment by jantonguirao** [comment]
Also, if you use `reader_name` in the iterator, then the `last_batch_padded` value is taken from the reader directly. So, all you need to do is change `pad_last_batch=True` on the reader, and remove the `last_batch_padded` argument from the iterator.

**Comment by henrique** [comment]
Hi @jantonguirao 
Thanks for your quick reply.
I have tried your suggestion but as you mention `last_batch_padded` can't be set with `reader_name`:
`AssertionError: When reader_name is provided, last_batch_padded should not be set`

Now, just with `pad_last_batch=True` and any `last_batch_policy='PARTIAL'|'DROP'|'FILL'` I get the last image repeated 5 times, which makes no sense in any application I can imagine :)

**Comment by jantonguirao** [comment]
@henrique 
I think the problem is that you are passing a string for `last_batch_policy`, while an instance of `LastBatchPolicy` is expected. Please try `last_batch_policy=LastBatchPolicy.PARTIAL`.

In the meantime, I'll file a PR with some data type validation.

**Comment by henrique** [comment]
@jantonguirao :face_palm: yes, that works obviously! I have no idea where I copied this from, apologies and thanks again for your attention!
