### ISSUE TITLE
NVIDIA DALI : unable to load videos using readers.video in NVIDIA DALI pipeline

### ISSUE THREAD

**Issue by AbhijitManepatil** [NVIDIA/DALI#3503]
Trying to load the video for NVIDIA DALI pipeline for video processing but not able to load the .mp4 video.

```
import os
import numpy as np    
from nvidia.dali import pipeline_def
import nvidia.dali.fn as fn
import nvidia.dali.types as types       

batch_size=2
sequence_length=8
initial_prefetch_size=16 

video_directory=['sintel_trailer-720p_0.mp4']
n_iter=6

print(video_directory)


@pipeline_def
def video_pipe(file_root):
    video, labels = fn.readers.video(device="gpu", file_root=file_root, sequence_length=sequence_length,
                                     random_shuffle=True, initial_fill=initial_prefetch_size)
    return video, labels


pipe = video_pipe(batch_size=batch_size, num_threads=2, device_id=0, file_root=video_directory, seed=12345)
pipe.build()
```

Above DALI pipeline shows the following issue while loading the video:

_RuntimeError: Critical error when building pipeline: Error when constructing operator: readers__Video encountered: [/opt/dali/dali/operators/reader/loader/video_loader.cc:117] Assert on "dir != nullptr" failed: Directory ['sintel_trailer-720p_0.mp4'] could not be opened._

I have referred the documentation from NVIDIA DALI for video processing but was not been to able solve it,

Please check for reference: NVIDIA DALI DOCS VIDEO PROCESSING [https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/sequence_processing/video/video_reader_simple_example.html](url)

**Comment by JanuszL** [comment]
Hi @AbhijitManepatil,

`file_root` - Path to a directory that contains the data files. So in your code, you should pass the directory where the `sintel_trailer-720p_0.mp4` file is located.
You may also consider using the `filenames` argument and passing a list of files you want to read.

**Comment by AbhijitManepatil** [comment]
@JanuszL Thanks for your response,
Can please share some example for the same?

**Comment by AbhijitManepatil** [comment]
@JanuszL all normal .mp4 are not supported to dali video pipeline?
can it support RTSP feeds?

**Comment by JanuszL** [comment]
Hi @AbhijitManepatil,

You can try:
```
from nvidia import dali
import nvidia.dali.fn as fn

@dali.pipeline_def
def video_pipeline():
    seq = fn.readers.video(device="gpu", filenames="sintel_trailer-1080p.mp4", sequence_length=3, step=5)
    return seq

pipe = video_pipeline(batch_size=16, num_threads=1, device_id=0)

pipe.build()
```

**Comment by AbhijitManepatil** [comment]
@JanuszL Thanks for sharing it works.

**Comment by AbhijitManepatil** [comment]
> Hi @AbhijitManepatil,
> 
> `file_root` - Path to a directory that contains the data files. So in your code, you should pass the directory where the `sintel_trailer-720p_0.mp4` file is located. You may also consider using the `filenames` argument and passing a list of files you want to read.

Yes, this help me too in following way:
we can add files to the directory using 

```
import os
os.environ['DALI_EXTRA_PATH']="YOUR VIDEO FILE FOLDER"
video_directory = os.path.join(os.environ['DALI_EXTRA_PATH'], "db", "video", "sintel", "video_files")
```
and we can use this video_directory for dali pipeline building.
Thanks for help @JanuszL
