### ISSUE TITLE
About how to do synchronization with the internal DALI stream used for data preprocessing

### ISSUE THREAD

**Issue by sneaxiy** [NVIDIA/DALI#3513]
Hi, I have some questions on DALI. 

Considering the `copy_to_external` method when copy DALI tensor data to external tensor data, we can pass a `cudaStream_t` parameter to specify which CUDA stream is used for `cudaMemcpyAsync`. But how can I do synchronization with the internal DALI stream used for data preprocessing? Is it any possible that when I call the `copy_to_external` method using my own CUDA stream, the DALI tensor may be changed by the internal DALI stream for data preprocessing?

My questions come when I use the DALI PaddlePaddle plugin to load and preprocess the ImageNet dataset. I found that in some cases, the training results of my model may be different. I do not know whether it is a subtle bug of DALI.

If so, is there any method that we can do the right stream synchronization? For example, expose the internal DALI stream to the Python side?

**Comment by sneaxiy** [comment]
I found that we can expose `UserStream::Get()->GetStream(t)` to the Python side to solve this question?

**Comment by JanuszL** [comment]
Hi @sneaxiy,

There is no mechanism to expose DALI internal stream/streams or ask it to use one provided externally. The pipeline output memory is valid until next call to `release_outputs` called from `_schedule_runs()` inside framework plugins.
You have raised a valid concern, maybe we should add a synchronization mechanism to make sure that the copy (when the external stream is provided) has finished before the memory is reused. What can be done now is to set `non_blocking=False` in `copy_to_external` to call synchronization on the provided stream.

**Comment by sneaxiy** [comment]
@JanuszL Thanks for your reply! I am sorry that maybe I have not make myself clear.

My real question is: DALI may use its internal stream for data preprocessing. CUDA kernel is usually asynchronous to the host. Inside the framework plugin, when we get the DALI tensor from the pipeline, the data preprocessing may not finish (because CUDA kernel is asynchronous). At this time, when `copy_to_external` method is called with an external stream, the data copy on the external stream and data preprocessing CUDA kernel on the DALI internal stream may run at the same time. 

Would the situation I mentioned above happen？

**Comment by sneaxiy** [comment]
@JanuszL If the case I mentioned would happen, I think that DALI should expose the interface of internal stream to Python. In this way, the plugin developer can make proper synchronization handly, such as using `cudaEvent_t`.

**Comment by sneaxiy** [comment]
@JanuszL I would only need to get the DALI internal stream instead of setting it.

**Comment by JanuszL** [comment]
Hi @sneaxiy,

Yes, I understand your concern. For now to make sure that there is no race condition you should `set non_blocking=False in copy_to_external to call synchronization on the provided stream to make sure that copy finishes before you exit the function.
We need to discuss if we want to leave this synchronization to the user or let it do at the DALI side via a proper API.

**Comment by sneaxiy** [comment]
@JanuszL I do not think `copy_to_external(non_blocking=False)` is enough for my cases. The `non_blocking=False` would only do stream synchronization after `cudaMemcpyAsync` but not before `cudaMemcpyAsync`. What I need is stream synchronization before `cudaMemcpyAsync`.

**Comment by JanuszL** [comment]
@sneaxiy,

You don't need to do the synchronization before `cudaMemcpyAsync`. When `_get_outputs` is called in the paddle plugin, `share_outputs` is called to obtain outputs from DALI. It calls synchronization on the relevant stream so the DALI GPU memory is ready. The only issue you pointed is that the memory can be reused by DALI before `cudaMemcpyAsync` finishes.

**Comment by sneaxiy** [comment]
@JanuszL Got it! Thank you!

**Comment by JanuszL** [comment]
@sneaxiy,

Let me keep that issue open. There is still a bug if a custom stream is provided and `non_blocking=True`, DALI can reuse the memory that is still used by `cudaMemcpyAsync ` on the external stream.

**Comment by JanuszL** [comment]
Tracked internally as DALI-2467.

**Comment by JanuszL** [comment]
Hi @sneaxiy,

The DALI 1.15 has been released and should include the mentioned fix. Please reopen it if it still doesn't work.

**Comment by sneaxiy** [comment]
Thanks a lot! @JanuszL

**Comment by JanuszL** [comment]
@mzient is the one to thank.
