### ISSUE TITLE
How can I define the pipeline if I want to change the preprocess of data during training?

### ISSUE THREAD

**Issue by LSC527** [NVIDIA/DALI#3514]
Like _Progressive Learning_ describe in _EfficientNetV2: Smaller Models and Faster Training_, gradually increase the input image size as the training process continues.

**Comment by klecki** [comment]
Hi @LSC527,
you can use [external source](https://docs.nvidia.com/deeplearning/dali/main-user-guide/docs/supported_ops.html#nvidia.dali.fn.external_source) operator to pass custom parameters to the pipeline - it can be done by specifying the `source` parameter - you can pass a Python lambda, callback or iterator there, which can produce samples or whole batch of parameters, which can be later used to control other operators in the pipeline.

**Comment by JanuszL** [comment]
@LSC527,

This short example shows how to change the resize operator parameters in runtime:
```
import numpy as np
import nvidia.dali.fn as fn
import nvidia.dali.types as types
from nvidia.dali import pipeline_def

batch_size = 4

def get_data():
    out = [(np.random.ranf(size=[2]).astype(dtype=np.float32)*60 + 30) for _ in range(batch_size)]
    return out

@pipeline_def
def simple_pipeline():
    jpegs, _ = fn.readers.file(files=["sample_image.jpg"])
    images = fn.decoders.image(jpegs)
    size = fn.external_source(source=get_data)
    images = fn.resize(images, size=size)
    return images

pipe = simple_pipeline(batch_size=batch_size, num_threads=4, device_id=0)
pipe.build()
pipe.run()
out = pipe.run()[0]
print(np.array(out[0]).shape)
out = pipe.run()[0]
print(np.array(out[0]).shape)
out = pipe.run()[0]
print(np.array(out[0]).shape)
```

**Comment by LSC527** [comment]
@klecki @JanuszL Thanks! This helps a lot.

**Comment by LSC527** [comment]
My intention is to increase image size and possibly decrease batch size as the training process continues.

**Comment by LSC527** [comment]
My intention is to increase image size and possibly decrease batch size (due to GPU OOM) as the training process continues.
For example, epoch 1-10 with image_size=128\*128 and batch_size=256, epoch 11-20 with image_size=256\*256 and batch_size=128.
I still can't figure out how to do this using external source. It seems hard to pass global training step to change the pipeline.
An easy way to do this is to define multiply piplines, but it may cost more time and more memory usage (I guess?).

**Comment by JanuszL** [comment]
Hi @LSC527,

You can control batch size in the same way, like in this example (it uses `batch_info` which is going to be available in 1.8 or the most recent nightly/weekly build):
```
import numpy as np
import nvidia.dali.fn as fn
from nvidia.dali import pipeline_def
from nvidia.dali.plugin.pytorch import DALIGenericIterator as DALIGenericIterator

max_batch_size = 5
num_epochs = 2
epoch_size = 3

def get_images(sample_info):
    epoch_batch_size = 5 if sample_info.epoch_idx < 1 else 2
    out = [np.fromfile("/home/jlisiecki/Dali/DALI_extra/db/single/jpeg/100/swan-3584559_640.jpg", dtype=np.uint8) for _ in range(epoch_batch_size)]
    if sample_info.iteration > epoch_size:
        raise StopIteration
    return out
def get_size(sample_info):
    epoch_batch_size = 5 if sample_info.epoch_idx < 1 else 2
    resize_param = 128 if sample_info.epoch_idx < 1 else 256
    out = [np.array([resize_param, resize_param], dtype=np.float32) for _ in range(epoch_batch_size)]
    if sample_info.iteration > epoch_size:
        raise StopIteration
    return out

@pipeline_def
def simple_pipeline():
    jpegs = fn.external_source(source=get_images, batch_info=True)
    images = fn.decoders.image(jpegs)
    size = fn.external_source(source=get_size, batch_info=True)
    images = fn.resize(images, size=size)
    return images

pipe = simple_pipeline(batch_size=max_batch_size, num_threads=4, device_id=0)
iter = DALIGenericIterator(pipe, ["data"], auto_reset=True)
for _ in range (num_epochs):
    for out in iter:
        print(out[0]["data"].shape)```

**Comment by LSC527** [comment]
AWESOME! This new feature is exactly what I need. Thanks again for your help.

**Comment by LSC527** [comment]
It is ok to pass `external_source` to `fn.resize`, but when I add another fn `fn.crop(images, crop=size)`, I got:
TypeError: The argument `crop` for operator `Crop` should not be a `DataNode` but a float or list of float

**Comment by LSC527** [comment]
Well, `fn.crop(images, crop_h=size_h, crop_w=size_w)` works fine with external_source.
Is this the same as `fn.crop(images, crop=[size_h, size_w])`？

**Comment by JanuszL** [comment]
Hi @LSC527,

> Is this the same as fn.crop(images, crop=[size_h, size_w])？

Functionally it yields the same results but differs in the accepted data types. You can checks [operator's documetation](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.crop) to see what can be provided as an input (value, list, or tensor).

**Comment by LSC527** [comment]
@JanuszL Thanks! 
I noticed that `external_source` can only pass to an argument if it can accept TensorList data.

**Comment by JanuszL** [comment]
> @JanuszL Thanks! I noticed that `external_source` can only pass to an argument if it can accept TensorList data.

Yes, `TensorList` means data that the external source or any other operator produces, while values and lists are provided directly from python when the data processing graph is defined.
