### ISSUE TITLE
How to create DALI batch of combination of two different videos together

### ISSUE THREAD

**Issue by AbhijitManepatil** [NVIDIA/DALI#3530]
I have two different videos as input for the DALI pipeline, I would like to form the batch from a combination of these two videos together.
example: 
suppose V1.mp4 & V2.mp4 are the two videos and if the batch size is 2, then the batch output will be expecting like;
batch=[frame1V1, frame1V2]
The next batch would be; batch=[frame2V1,frame2V2] and so on..
So, the batch should be a combination of frames from both videos at a time.
Can anyone share some examples of this!

**Comment by JanuszL** [comment]
Hi @AbhijitManepatil,

DALI video reader builds a list of all available sequences and either return them in order or completely randomly. If you want to make sure that you get frames from both videos in the same batch you could use two video readers, with the same seed (so you get the same shuffling order), return two outputs and then concatenate them outside DALI. Something like:
```
from nvidia import dali
import nvidia.dali.fn as fn
import numpy as np

@dali.pipeline_def
def video_pipeline():
    seq1 = fn.readers.video(device="gpu", filenames="DALI_extra/db/video/sintel/video_files/sintel_trailer-720p_0.mp4", sequence_length=3, step=5, seed=1)
    seq2 = fn.readers.video(device="gpu", filenames="DALI_extra/db/video/sintel/video_files/sintel_trailer-720p_1.mp4", sequence_length=3, step=5, seed=1)
    return seq1, seq2

pipe = video_pipeline(batch_size=1, num_threads=1, device_id=0)

pipe.build()

outs = pipe.run()
merged = np.concatenate((outs[0].as_cpu().as_array(), outs[1].as_cpu().as_array()))
print(merged.shape)```

**Comment by AbhijitManepatil** [comment]
@JanuszL Thanks,
How many readers.video object we can create in a single DALI pipeline, is there any limit?

**Comment by JanuszL** [comment]
Hi @AbhijitManepatil,

There is no upper limit of the operator instance you can create inside the DALI pipeline but please keep in mind that each `readers.video` instance uses memory on its own, to keep the decoded output and intermediate surfaces. So it very much depends on the image size you want to decode and the amount of your GPU memory.

**Comment by AbhijitManepatil** [comment]
Thanks for the information.
