### ISSUE TITLE
Can DALI pipeline support to read RTSP feeds?

### ISSUE THREAD

**Issue by AbhijitManepatil** [NVIDIA/DALI#3537]
I am trying to read multiple RTSP feeds for the DALI pipeline but not getting any solution,
can RTSP feed are supported by the DALI pipeline to read;
or any decoding technique need to use to read RTSP?
Please provide an example/solution if any?

**Comment by JanuszL** [comment]
Hi @AbhijitManepatil,

I'm sorry to say that DALI doesn't support the RTSP feed. I recommend checking if [the Deep Stream SDK](https://developer.nvidia.com/deepstream-sdk) better suits your needs.

**Comment by AbhijitManepatil** [comment]
Hi @JanuszL, 
So, apart from RTSP does DALI support any of the live streaming protocols to read from the camera?
Does it read from USB camera?

**Comment by JanuszL** [comment]
@AbhijitManepatil,

DALI video reader operator only supports files, no live stream from any source.

**Comment by AbhijitManepatil** [comment]
Thanks for response.

**Comment by HaoLIU94** [comment]
Hello @JanuszL ,

With no RTSP support from camera, does it mean that we can only DALI for accelerating trainings
and offline inference on videos but it is not possible to use it for steaming inference. Am I right?

**Comment by JanuszL** [comment]
Hi @HaoLIU94,

> With no RTSP support from camera, does it mean that we can only DALI for accelerating trainings
and offline inference on videos but it is not possible to use it for steaming inference. Am I right?

That is correct. DALI doesn't support streaming.

Regarding the mentioned talk it would be best to reach its author and ask for particular details. Honestly, I don't know how the input was provided in this particular use case (definitely not as a video as DALI doesn't support video decoding for Xavier due to a different API for it). Now the recommended way to use DALI with inference is through TRITON and [DALI backend](https://github.com/triton-inference-server/dali_backend).

**Comment by AbhijitManepatil** [comment]
I have prepared one custom solution in the following way by applying python multiprocessing;
1. Create the first process to read the RTSP feed and store those frames in a queue as a data structure.
2. spawn another process that reads those frames from a queue of 1st process.
3. Note: Both above processes run in parallel and queues are shared among the processes.
5. user DALI pipeline framework to read those frames from the queues which will accept frames from your RTSP feeds continuously.

This way above custom logic will help to execute the power of Dali pipeline while reading and processing live RTSP feeds.
Thanks

**Comment by JanuszL** [comment]
@AbhijitManepatil,

With the recent extension of the external source operator supporting [parallel processing](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/parallel_external_source.html), you can provide an iterator that would read RTSP feed and it would happen in parallel to the main python thread - no additional logic should be necessary.

**Comment by qulei123** [comment]
> I have prepared one custom solution in the following way by applying python multiprocessing;
> 
> 1. Create the first process to read the RTSP feed and store those frames in a queue as a data structure.
> 2. spawn another process that reads those frames from a queue of 1st process.
> 3. Note: Both above processes run in parallel and queues are shared among the processes.
> 4. user DALI pipeline framework to read those frames from the queues which will accept frames from your RTSP feeds continuously.
> 
> This way above custom logic will help to execute the power of Dali pipeline while reading and processing live RTSP feeds. Thanks

I have implemented a similar functionality, but I'm facing some issues and I'm not sure how you've resolved them.
1. I'm using ffmpeg to capture an RTSP stream and save the raw stream data in memory.
2. I'm packetizing the raw stream data in memory into GOPs (Group of Pictures), where each GOP contains 50 frames per second (fps), and then sending it to a decoders.video or inputs.video for decoding. This approach results in processing 50 fps of data at once, causing a delay of 2 seconds.
3. However, if I try to send the raw stream data for decoding one frame at a time, the program does not function properly and gives me the following error:
```
Error in thread 2: [/opt/dali/dali/operators/reader/loader/video/frames_decoder.cc:221] Assert on "ret == 0" failed: Failed to open video file memory filedue to Invalid data found when processing input
Current pipeline object is no longer valid.
```

**Comment by JanuszL** [comment]
Hi @qulei123,

Thank you for reporting your problem. The error you see is reported by libaviformat which cannot open the `raw stream data for with frame at a time`. Is it possible for you to share [a minimal and self-contained repro we can run on our end](https://github.com/NVIDIA/DALI?tab=readme-ov-file#reporting-problems-asking-questions) to investigate it further?
