### ISSUE TITLE
Image Processing Question | Triton Inference Server

### ISSUE THREAD

**Issue by chiehpower** [NVIDIA/DALI#3543]
Thanks for sharing this awesome tool!

I have tested the simple case for DALI on Triton. 

I am wondering whether the post-processing is able to apply DALI as well?

Because most of the models are quite hard to wrap the post-processing part into one model, the hardware configuration of edge device is weak for doing any processing that I wish everything can be handled on the Triton inference server including pre-processing, inference and post-processing (rendering or drawing).

Thank you in advance if there is any feedback!

Best regards,
Chieh

**Comment by JanuszL** [comment]
Hi @chiehpower,

From DALI's point of view, there is no clear distinction between pre and post-processing. It very much depends on the type of input data and transformation you want to apply.
You may also want to check [the Python backend](https://github.com/triton-inference-server/python_backend) which may lack some performance in the exchange for flexibility.

**Comment by chiehpower** [comment]
Hi @JanuszL 

Got it. Thanks for your information!
