### ISSUE TITLE
Read numpy array list in NVIDIA DALI pipeline

### ISSUE THREAD

**Issue by AbhijitManepatil** [NVIDIA/DALI#3549]
I was trying to read the numpy array of images which is stored in a list,
I am trying to use the following way but got an issue while reading numpy reader.

```
from nvidia.dali import pipeline_def, fn
import cv2

batch_size=1

img1=cv2.imread("dog_1.jpg")
img2=cv2.imread("cat_1.jpg")

img_list=[]   #list of numpay array of images to read
img_list.append(img1)
img_list.append(img2)

type(img_list[0])
#numpy.ndarray

@pipeline_def(batch_size=batch_size, num_threads=1, device_id=0)
def pipe1():
    data = fn.readers.numpy(device='cpu', file_root=img_list)   #pipeline use the img_list to read
    return data

def run(p):
    p.build()  # build the pipeline
    outputs = p.run()  # Run once
    # Getting the batch as a list of numpy arrays, for displaying
    batch = [np.array(outputs[0][s]) for s in range(batch_size)]
    return batch

data1 = run(pipe1())

```

I am referring to the DALI documentation for data loading in using numpy from [here](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/numpy_reader.html#Overview)

I am getting the following issue:

**RuntimeError: Critical error when building pipeline:
Error when constructing operator: readers__Numpy encountered:
[/opt/dali/dali/operators/reader/loader/filesystem.cc:166] Assert on "dir != nullptr" failed: Directory [array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,**

So, I want to ask can I read a direct numpy array list to the pipeline reader?
Can anyone share some examples of this?

Thanks

**Comment by JanuszL** [comment]
Hi @AbhijitManepatil,

`fn.readers.numpy` operator accepts file names, not the numpy arrays. To do that please use the external source operator. Please check [this example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/external_input.html) for a reference.

**Comment by AbhijitManepatil** [comment]
Yes, thanks for your response @JanuszL 
I tried the same earlier but got the following error:

**RuntimeError: The external source callback returned an unexpected batch size. Expected batch_size <= 2, actual: 427**

As I am missing something!!

**Comment by JanuszL** [comment]
Hi @AbhijitManepatil,

Please check [the `source` argument documentation](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.external_source) and all relevant examples for this operator: [1](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/external_input.html), [2](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/parallel_external_source.html) and [3](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/parallel_external_source_fork.html).
If it still doesn't work feel free to provide a minimal and self-contained example that reproduces your problem.

**Comment by mzient** [comment]
@AbhijitManepatil The `source` should produce _batches_. If you pass a collection there, it should be a collection of batches, no separate images. It was done so that you can pass batch tensors (with an extra batch dimension for the samples in the batch) to external source. You should either add another level of nesting or specify `batch=False` for `external_source`.

**Comment by AbhijitManepatil** [comment]
Thanks @JanuszL and @mzient 
by specifying `batch=False`  that works for me.
Thanks
