### ISSUE TITLE
Run DALI example code error

### ISSUE THREAD

**Issue by LuckyZxy182** [NVIDIA/DALI#3559]
using nvidia-docker2, NGC Containers and example code: 
1.  docker pull nvcr.io/nvidia/pytorch:21.11-py3
2.  docker run --gpus all --privileged=true --net=host -it -d --shm-size=8g --name="nvidia-ngc" nvcr.io/nvidia/pytorch:21.11-py3 bash
3.  pytorch example code, test.py: https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/frameworks/pytorch/pytorch-basic_example.html
4. DALI_EXTRA_PATH=DALI_extra python3 test.py
5. error logs:
"Traceback (most recent call last):
  File "test.py", line 48, in <module>
    pipe.build()
  File "/opt/conda/lib/python3.8/site-packages/nvidia/dali/pipeline.py", line 703, in build
    self._pipe.Build(self._names_and_devices)
RuntimeError: Critical error when building pipeline:
Error when constructing operator: readers__Caffe encountered:
[/opt/dali/dali/operators/reader/loader/lmdb.h:52] Assert on "mdb_env_open(mdb_env_, path.c_str(), mdb_flags, 0664) == 0" faError: Invalid argument, with file: DALI_extra/db/lmdb
Stacktrace (28 entries):
[frame 0]: /opt/conda/lib/python3.8/site-packages/nvidia/dali/libdali_operators.so(+0x5651be) [0x7f4f512031be]
[frame 1]: /opt/conda/lib/python3.8/site-packages/nvidia/dali/libdali_operators.so(+0x2b414fb) [0x7f4f537df4fb]
[frame 2]: /opt/conda/lib/python3.8/site-packages/nvidia/dali/libdali_operators.so(+0x2b47471) [0x7f4f537e5471]
[frame 3]: /opt/conda/lib/python3.8/site-packages/nvidia/dali/libdali_operators.so(std::_Function_handler<std::unique_ptr<darBase, std::default_delete<dali::OperatorBase> > (dali::OpSpec const&), std::unique_ptr<dali::OperatorBase, std::default_delperatorBase> > (*)(dali::OpSpec const&)>::_M_invoke(std::_Any_data const&, dali::OpSpec const&)+0xc) [0x7f4f511ff2cc]
[frame 4]: /opt/conda/lib/python3.8/site-packages/nvidia/dali/libdali.so(+0x14c091) [0x7f4f501bb091]
[frame 5]: /opt/conda/lib/python3.8/site-packages/nvidia/dali/libdali.so(dali::InstantiateOperator(dali::OpSpec const&)+0x2601b82a4]
[frame 6]: /opt/conda/lib/python3.8/site-packages/nvidia/dali/libdali.so(dali::OpGraph::InstantiateOperators()+0xac) [0x7f4f
[frame 7]: /opt/conda/lib/python3.8/site-packages/nvidia/dali/libdali.so(dali::Pipeline::Build(std::vector<std::pair<std::ststring>, std::allocator<std::pair<std::string, std::string> > >)+0x9f0) [0x7f4f501d8de0]
[frame 8]: /opt/conda/lib/python3.8/site-packages/nvidia/dali/backend_impl.cpython-38-x86_64-linux-gnu.so(+0x4ea98) [0x7f4f6
[frame 9]: /opt/conda/lib/python3.8/site-packages/nvidia/dali/backend_impl.cpython-38-x86_64-linux-gnu.so(+0x8b0ae) [0x7f4f6
[frame 10]: python3(PyCFunction_Call+0x54) [0x56395a6d4f44]
[frame 11]: python3(_PyObject_MakeTpCall+0x31e) [0x56395a6e430e]
[frame 12]: python3(+0x1b0ece) [0x56395a759ece]
[frame 13]: python3(_PyEval_EvalFrameDefault+0x4e03) [0x56395a77a133]
[frame 14]: python3(_PyEval_EvalCodeWithName+0x2c3) [0x56395a757db3]
[frame 15]: python3(_PyFunction_Vectorcall+0x378) [0x56395a759198]
[frame 16]: python3(_PyEval_EvalFrameDefault+0xa63) [0x56395a775d93]
[frame 17]: python3(_PyEval_EvalCodeWithName+0x2c3) [0x56395a757db3]
[frame 18]: python3(PyEval_EvalCodeEx+0x39) [0x56395a758e19]
[frame 19]: python3(PyEval_EvalCode+0x1b) [0x56395a7fb24b]
[frame 20]: python3(+0x2522e3) [0x56395a7fb2e3]
[frame 21]: python3(+0x26e543) [0x56395a817543]
[frame 22]: python3(+0x273562) [0x56395a81c562]
[frame 23]: python3(PyRun_SimpleFileExFlags+0x1b2) [0x56395a81c742]
[frame 24]: python3(Py_RunMain+0x36d) [0x56395a81ccbd]
[frame 25]: python3(Py_BytesMain+0x39) [0x56395a81ce79]
[frame 26]: /usr/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f4f6c4d70b3]
[frame 27]: python3(+0x1e6d69) [0x56395a78fd69]

Current pipeline object is no longer valid."

7. I tested DALI_extra main branch, DALI_extra-1.7.0, DALI_extra-1.8.0 and DALI_extra_0.10.0, but got same error logs.

**Comment by JanuszL** [comment]
Hi @LuckyZxy182,

Do you have [git-lfs](https://git-lfs.github.com/) installed? Can you check what is the size and content of db/lmdb/data.mdb file?

**Comment by LuckyZxy182** [comment]
Thanks a lot! The problem has been solved. My ignorace amuses me.
