### ISSUE TITLE
Significant performance drop using multiple pipelines

### ISSUE THREAD

**Issue by LSC527** [NVIDIA/DALI#3564]
[previously](https://github.com/NVIDIA/DALI/issues/3514#issue-1058328475)
I was testing my legacy code which defines multiple pipelines to change the batchsize or image size during training process. Then I noticed a significant performance (i.e. training throughput) drop in the later pipline. 
For example，
    stage 1：64x64 image inputs trained for 10 epochs
    stage 2:   128x128 image inputs trained for 10 epochs
    stage 3:   224x224  image inputs trained for 10 epochs
In stage 3, the training throughput drops nearly 40% compared to the case which only define one pipeline i.e. use only 224x224 image inputs during training.
Is there anything I need to do to destory the previous pipeline before going to the next stage?

**Comment by JanuszL** [comment]
Hi @LSC527,

Having multiple pipelines defined in parallel should not affect the overall performance as long as you use only one at a time.
Can you provide a self-contained reproduction script (it doesn't have to use real data, https://github.com/NVIDIA/DALI_extra should do) that would illustrate the problem you see?

**Comment by LSC527** [comment]
Sry my bad. Found some bugs in my code.
