### ISSUE TITLE
How can I share 'nvidia.dali.backend_impl.TensorGPU' object in multiple processes. 

### ISSUE THREAD

**Issue by AbhijitManepatil** [NVIDIA/DALI#3567]
I am trying to share the **nvidia.dali.backend_impl.TensorGPU** object in multiple processes,
that process is defined using the python multiprocessing way and I have created a shared queue where I have put the TensorGPU object in that queue, now I shared the same queue with other processes for further use but it gives me a pickle issue.

```
....
.....
pipe_out = pipe.run()
images, labels = pipe_out

import multiprocessing as mp
shared_queue= mp.Manager().Queue()

#function used to process the dali GPU object to process further
def convertfunc(imgs):
    shared_queue.put(imgs)

p=mp.Process(target=convertfunc, args=[images[0]])
p.start()
p.join()
```
NOTE: Requirement is only GPU object needs to share not by converting to as_cpu() format.

Above way to share the dali GPU object gives me an error that:
_TypeError: cannot pickle 'nvidia.dali.backend_impl.TensorGPU' object_

How can I resolve this, @JanuszL can you please help,
Thanks

**Comment by JanuszL** [comment]
Hi @AbhijitManepatil,

To share GPU memory that is represented by *TensorGPU* please use CUDA IPC API ([cupy seems to have a nice set of bindings](https://docs.cupy.dev/en/stable/reference/cuda.html#runtime-api)). [This example](https://docs.nvidia.com/cuda/cuda-samples/index.html#simpleipc) ([the implementation](https://github.com/NVIDIA/cuda-samples/blob/master/Samples/simpleIPC/simpleIPC.cu)) shows overall operation principle. What you need to do is:
- obtain the pointer from TensorGPU, for example for using `__cuda_array_interface__` it implements or plain `data_ptr` property
- create a handle for it
- pass the handle to another process
- obtain the pointer from the handle
- create TensorGPU for this pointer of any other GPU memory object like cuPy array or Deep Learning framework tensor

**Comment by AbhijitManepatil** [comment]
Hi @JanuszL,
Thanks for the guidelines, I will work on this.

**Comment by AbhijitManepatil** [comment]
I was trying to work on the above approach,

```
import pycuda.autoinit
import pycuda.driver as drv
...............
...............
pipe_out = pipe.run()
batch_gpu = pipe_out
data=batch_gpu.at(0)
handle = drv.mem_get_ipc_handle(data.data_ptr())
print("handle1====>",handle)
```
Above code gives me pointer to the GPU object(data which is of type <class 'nvidia.dali.backend_impl.TensorListGPU'>) from data_ptr() as referred from [this](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/data_types.html#tensor) documentation.
but when I pass this data_ptr() pointer value to create an IPC handle, later on, used for a pass to multiprocessing, it gives me errors like: _exception :  cuIpcGetMemHandle failed: invalid argument_
any suggetion? @JanuszL

**Comment by JanuszL** [comment]
Hi @AbhijitManepatil,

As I see `mem_get_ipc_handle` expects a `DeviceAllocation object representing` not a raw pointer DALI provides.
However, it seems that `cudaIpcGetMemHandle` doesn't support memory obtained by the `cuMemMap` call (as this is how DALI manages internally its allocations).
For now, it seems you need to copy the memory to a buffer obtained from cudaMalloc, something like this should work:
```
from nvidia.dali import fn, pipeline_def
import numpy as np
import cupy

# Pipe parameters
batch_size = 5

def get_data():
    out = [(np.random.ranf(size=[1, 1, 3]) * 255).astype(dtype=np.uint8) for _ in range(batch_size)]
    return out

@pipeline_def
def test_pipe():
    data = fn.external_source(source=get_data, device="gpu")
    return data

pipe = test_pipe(batch_size=batch_size, num_threads=1, device_id=0)
pipe.build()
o = pipe.run()
data = o[0].as_tensor()
# copy data to cupy array
cp_data = cupy.array(data)
h = cupy.cuda.runtime.ipcGetMemHandle(cp_data.data.ptr)
```

**Comment by JanuszL** [comment]
Hi @AbhijitManepatil,

I have double-checked what is feasible and there is [an API](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__VA.html#group__CUDA__VA) that allows sharing memory obtained by cuMemMap, however, it may be not feasible to use it with memory returned by DALI. DALI internally creates a memory pool and each buffer usually represents only a piece of it while the mentioned API work on full allocation granularity.
What I recommend is to stick to the solution proposed in https://github.com/NVIDIA/DALI/issues/3567#issuecomment-1002028487.

**Comment by AbhijitManepatil** [comment]
> Hi @AbhijitManepatil,
> 
> I have double-checked what is feasible and there is [an API](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__VA.html#group__CUDA__VA) that allows sharing memory obtained by cuMemMap, however, it may be not feasible to use it with memory returned by DALI. DALI internally creates a memory pool and each buffer usually represents only a piece of it while the mentioned API work on full allocation granularity. What I recommend is to stick to the solution proposed in [#3567 (comment)](https://github.com/NVIDIA/DALI/issues/3567#issuecomment-1002028487).

Hi, @JanuszL,
Thanks for information, this will help me, Thanks
