### ISSUE TITLE
Questions about nvidia.dali.fn.readers.video

### ISSUE THREAD

**Issue by liveseongho** [NVIDIA/DALI#3571]
Hi, I have a few questions about `nvidia.dali.fn.readers.video`.

1) Should all videos have the same codec? and if they should, why it doesn't support multiple codecs?
I found an error as follows:
`error: /video/th6IUBNf3so.webm is not the same codec as previous files`

2) Can I get metadata from each video file and apply customized crop size for each video file?
For example, assume I have two video files with different heights and widths. How can I set different crop positions for each video?
If I set `lazy_init = True`, can I get metadata for each video file?

3) Can I get a file index of each sequence?
I can get batch of sequences `(N, F, H, W, C)` for all video files I set, but don't know what file each sequence is from. I need sequences for each file.

Thanks!

**Comment by JanuszL** [comment]
Hi @liveseongho,

Let me answer your questions:

1) Currently DALI requires to have all videos encoded with the same coded. NVDEC doesn't support reconfiguration where you can change the codec itself, it is possible to change other stream properties like resolution. To change the code we would need to recreate the decoder instance what could significantly affect performance. Still, we will add this to our ToDo list.
2) `lazy_init = True` has nothing to do with the video metadata. What you can do is assign a different label to each video file and based on that utilize [the `lookup` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.lookup_table) to obtain crop parameters.
3) What you can do is assign a distinct label to each video file and set `enable_frame_num=True` then you can get a label and exact frame for each sequence the reader returns.

**Comment by liveseongho** [comment]
Thanks a lot. 😃
