### ISSUE TITLE
Scale in box_encode.cc 

### ISSUE THREAD

**Issue by wantacool** [NVIDIA/DALI#3575]
Hi there,

Could anybody here explain for me what is the "scale" parameter used for in "GetOffsets" function of "DALI/dali/operators/ssd/box_encoder.cc" ? From the code, the parameter just do nothing to the result. Please see below. Thanks. 

----------------------------------------------------------

std::pair<vec2, vec2>
GetOffsets(vec2 box_center,
           vec2 box_extent,
           vec2 anchor_center,
           vec2 anchor_extent,
           const std::vector<float>& means,
           const std::vector<float>& stds,
           float scale) {
  box_center *= scale;
  box_extent *= scale;
  anchor_center *= scale;
  anchor_extent *= scale;
  vec2 center, extent;
  center[0] = ((box_center[0] - anchor_center[0]) / anchor_extent[0] - means[0]) / stds[0];
  center[1] = ((box_center[1] - anchor_center[1]) / anchor_extent[1] - means[1]) / stds[1];
  extent[0] = (std::log(box_extent[0] / anchor_extent[0]) - means[2]) / stds[2];
  extent[1] = (std::log(box_extent[1] / anchor_extent[1]) - means[3]) / stds[3];
  return std::make_pair(center, extent);
}

**Comment by awolant** [comment]
Hi, thanks for the question.

This formula looks like this to keep the results exactly the same as the reference implementation from [here](https://github.com/mlcommons/training/blob/master/single_stage_detector/ssd/utils.py).
I added some comments in #3581 , so it is clear in the future.

**Comment by wantacool** [comment]
Hi Albert,

Thanks for the response. However this still does not make much sense to me, due to:

(1) The encode method of the referred pytorch implementation looks quite different from here, where the "scale_xy", "scale_wh" (assume those are your reference augments) were used only in decode.

(2) It is inconsistent with the python documentation, where it states:

_Returns normalized offsets ``((encoded_bboxes*scale - anchors*scale) - mean) / stds``
in EncodedBBoxes that use ``std`` and the ``mean`` and ``scale`` arguments_

If the above is true, then you should do
center[0] = ((box_center[0] - anchor_center[0]) / anchor_extent[0] * scale - means[0]) / stds[0];
center[1] = ((box_center[1] - anchor_center[1]) / anchor_extent[1] * scale - means[1]) / stds[1];
extent[0] = (std::log(box_extent[0] / anchor_extent[0]) * scale - means[2]) / stds[2];
extent[1] = (std::log(box_extent[1] / anchor_extent[1]) *scale - means[3]) / stds[3];

**Comment by awolant** [comment]
Right. As I mentioned before, we want to have the results be the same, not necessarily the exact calculation. We generated some data from the reference code and are compering the DALI results to these in the tests.
This was tested quite extensively when it was included in DALI and looked like it was the same.

**Comment by wantacool** [comment]
Thanks for the clarification. So I guess the correct scale value to keep the numerical results same in all cases is the input size of the network. Is it right?
