### ISSUE TITLE
do you implement ImageNet val acc on pytorch ?

### ISSUE THREAD

**Issue by daixiangzi** [NVIDIA/DALI#3577]

**Comment by daixiangzi** [comment]
use this code[:](https://github.com/NVIDIA/DALI/blob/842defee0081e62c6f00c100ea5bdf3668267602/docs/examples/use_cases/pytorch/resnet50/main.py)

**Comment by JanuszL** [comment]
Hi @daixiangzi,

If I understand your question correctly you are asking about particular ResNet 50 example model functionality. The mentioned example is to only show how DALI can be used in classification networks, like ResNet 50, with the PyTorch framework. If you are looking for a feature reach example please check this project https://github.com/NVIDIA/DeepLearningExamples.

**Comment by daixiangzi** [comment]
> Hi @daixiangzi,
> 
> If I understand your question correctly you are asking about particular ResNet 50 example model functionality. The mentioned example is to only show how DALI can be used in classification networks, like ResNet 50, with the PyTorch framework. If you are looking for a feature reach example please check this project https://github.com/NVIDIA/DeepLearningExamples.

yes, good link, thank you
