### ISSUE TITLE
‘class dali::OperatorBase’ has no member named ‘GetArgument’

### ISSUE THREAD

**Issue by SunNy820828449** [NVIDIA/DALI#3598]
Hi, I get the this error 
"/root/sunli/software/DALI/dali/operators/audio/mfcc/mfcc.h:94:35: error: ‘class dali::OperatorBase’ has no member named ‘GetArgument’ arg.dct_type = spec_.template GetArgument<int>("dct_type");" has no member named ‘GetArgument’" when compile DALI.

I found it had be fixed this problem in [commit](https://github.com/NVIDIA/DALI/pull/1320). But when i compile V1.9, still get this error。

**Comment by JanuszL** [comment]
Hi @SunNy820828449,

What compiler do you use? Can you provide a simple repro for that?

**Comment by JanuszL** [comment]
Closing as stalled.
