### ISSUE TITLE
error : std::bad_alloc in pipeline Outputs

### ISSUE THREAD

**Issue by Eleanor456** [NVIDIA/DALI#3599]
When I use Dali to preprocess my data, I get the error: 

terminate called after throwing an instance of 'std::runtime_error'
  what():  Critical error in pipeline: std::bad_alloc
Current pipeline object is no longer valid.

There is the error code in my cpp file (the last line: pipe_->Outputs(ws_.get());):
pipe_->SetExternalInput("data", tl_);
pipe_->RunCPU();
pipe_->RunGPU();
pipe_->Outputs(ws_.get());

The pipe_ and ws_ were defined in the .h file as fellows:
std::shared_ptr<dali::Pipeline> pipe_;
std::shared_ptr<dali::DeviceWorkspace> ws_;

I can successfully execute this project on a machine with P40, but can not execute on a new machine with T4. How should I do to fix this problem. The version of DALI I used is v0.11.0.

Thx

**Comment by JanuszL** [comment]
Hi @Eleanor456,

Please update DALI to the latest version (the most recent one is 1.8), and check again. Also, please test your code with a smaller batch size Maybe P40 has more GPU RAM than the newer T4?

**Comment by Eleanor456** [comment]
My batch size is set to be 1. But the version of DALI is 0.11.0.&nbsp;




------------------ Original ------------------
From: Janusz Lisiecki ***@***.***&gt;
Date: Tue,Dec 28,2021 5:58 PM
To: NVIDIA/DALI ***@***.***&gt;
Cc: Eleanor456 ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [NVIDIA/DALI] error : std::bad_alloc in pipeline Outputs (Issue#3599)





 
Hi @Eleanor456,
 
Please update DALI to the latest version (the most recent one is 1.8), and check again. Also, please test your code with a smaller batch size Maybe P40 has more GPU RAM than the newer T4?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JanuszL** [comment]
@Eleanor456,

Please retest with the latest version. If it doesn't work we need [a simple, self-contained repro to run on our side](https://github.com/NVIDIA/DALI#reporting-problems-asking-questions).
