### ISSUE TITLE
Questions about nvidia.dali.fn.readers.video

### ISSUE THREAD

**Issue by Gray-OREO** [NVIDIA/DALI#3606]
Hi,

I'm new to DALI. I want to design a video dataloder based DALI under pytorch, but there is something wrong when I want to use `nvidia.dali.fn.readers.video(*inputs, **kwargs)`. 

Becaused I have a list of file path like `['/home/videos/001.mp4','/home/videos/003.mp4',...]` then I set the argument `filenames` with it, which raises an error :
`TypeError: ('The objects of type <class 'nvidia.dali.pipeline.DataNode'> are not iterable.')`

Did I do something wrong about argument setting?

Thanks!

**Comment by JanuszL** [comment]
Hi @Gray-OREO,

Could you post your code snippet so we can reproduce the issue on our side? Without it, it is hard to tell what is wrong? The issue seems to be more about how DALI is called than a bug.

**Comment by Gray-OREO** [comment]
@pipeline_def
        def video_pipe(filenames):
            video, label = fn.readers.video(device="gpu", filenames=filenames, sequence_length=240, random_shuffle=False)
            return video, label

        pipe = video_pipe(batch_size=args.batch_size, num_threads=2, device_id=args.deviceID,
                          filenames=video_names, seed=12345)
        pipe.build()
        n_iter = len(trainindex)

        for i in range(n_iter):
            pipe_out = pipe.run()
            sequences_out = pipe_out[0].as_cpu().as_array() # [B,T,H,W,C]
            print(sequences_out.shape)

where video_names is a list of str, `['/home/amax/Gray/Database/KoNViD_1k/KoNViD_1k_videos/8536919744.mp4', '/home/amax/Gray/Database/KoNViD_1k/KoNViD_1k_videos/6408325533.mp4', '/home/amax/Gray/Database/KoNViD_1k/KoNViD_1k_videos/5319047612.mp4']`.

**Comment by JanuszL** [comment]
Hi @Gray-OREO,

Please check the `labels` argument description:
```
labels (int or list of int, optional) – Labels associated with the files listed in filenames argument.

If an empty list is provided, sequential 0-based indices are used as labels. If not provided, no labels will be yielded.```

So either:
```
@pipeline_def
    def video_pipe(filenames):
        video, label = fn.readers.video(device="gpu", filenames=filenames, labels=[],sequence_length=240, random_shuffle=False)
        return video, label```
or:
```
@pipeline_def
    def video_pipe(filenames):
        video = fn.readers.video(device="gpu", filenames=filenames, sequence_length=240, random_shuffle=False)
        return video```

**Comment by Gray-OREO** [comment]
👍 Thanks!!!

**Comment by Gray-OREO** [comment]
Hi @JanuszL ,

I'm in a dilemma that my label is a list of float ( I can't use `labels` for building the dataloader as the argument description), and there are also several ways for it.

1. If I can do it with the way in  'External Source Operator' of Docs, or there is other function for my goal ?

2. If I can use  `nvidia.dali.fn.readers.video` just for video reading and data transform and define a common Pytorch iterator for training? ( may be I need to convert the GPUTensor to torch.cuda.Tensor?) And if I did so, is there any efficiency decline for training?

Could you give me some advice for it? Thanks a lot! 😊

**Comment by JanuszL** [comment]
Hi @Gray-OREO,

> If I can do it with the way in 'External Source Operator' of Docs, or there is other function for my goal ?

I'm sorry but there is no easy way to sync external sources and the video reader when you do random shuffling.

> If I can use nvidia.dali.fn.readers.video just for video reading and data transform and define a common Pytorch iterator for training? ( may be I need to convert the GPUTensor to torch.cuda.Tensor?) And if I did so, is there any efficiency decline for training?

What you can try to do is assign integer labels to videos and then map them to floating-point one using an external lookup table.

**Comment by Gray-OREO** [comment]
Hi @JanuszL ,

Thanks for your quick response. It seems the best way for float-point label. So may I just use the video (Tensor list) for Pytorch model training? Or other function should be used for data type converting?

**Comment by JanuszL** [comment]
Hi @JanuszL,

> So may I just use the video (Tensor list) for Pytorch model training? Or other function should be used for data type converting?

Please check DALI framework integrators that convert pipeline output into native framework tensors, like [this one](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/plugins/pytorch_tutorials.html) for PyTorch.

**Comment by ChickenTarm** [comment]
H @JanuszL i, just to piggy back off of this, how do I use a list of filenames, but also a list of ints that indicate the frame number i would like to extract from each file from the reader?

**Comment by JanuszL** [comment]
Hi @ChickenTarm,

I'm sorry, but you can't pass the list of frame indices the same way as the file names. What you can do is specify the ranges of frames you want to extract from the video using the `file_list` argument. The file list format is:
```
file label [start_frame [end_frame]]
```

**Comment by Gray-OREO** [comment]
Hi @JanuszL ,

Thanks a lot for your help, the iterator can be realized with `dali_iter = DALIGenericIterator(pipes, ['data', 'label'], reader_name='Reader')`. But CUDA memory is also be occupied after the iteration of training phase, are there some ways to release the memory after the iteration of current phase?

**Comment by JanuszL** [comment]
Hi @Gray-OREO,

The memory is occupied after the iteration as DALI prefetches (computes) the next batch of the data in the background. Theoretically, you can delete the iteration and the pipeline, but recreating will consume a lot of time and also affect the randomness so it is not recommended.
Can you provide the pseudo-code of the flow you have in mind?

**Comment by Gray-OREO** [comment]
Hi @JanuszL ,

I want the flow like this:

for i  in epochs:
    build train_pipe and train_iter
    for i in train_iter:
        …
        delete pipe and iter
    build val_pipe and val_iter
    for i in val_iter:
        …
        delete pipe and val_iter

Actually, I think the pipe building time in every epoch is tolerable considering the memory limit which affects the number of iteration. And I will also test them for choosing the best flow.

**Comment by JanuszL** [comment]
I think this approach should work. Please try it and let us know if you have any problems.

**Comment by Gray-OREO** [comment]
Hi, @JanuszL ,

I finished the DALI_Iterator for Pytorch, but threre is a question that  how to  normalize a video by schedule mean and std like ` mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225`?

**Comment by Gray-OREO** [comment]
Hi @JanuszL ,

Thanks for your help, but `crop_mirror_normalize` seems like only can be used in loop for videos, is there some influences for efficiency? 

And I had tried my code in another server, but there is an error as following: 
`RuntimeError: Critical error when building pipeline: 
Error when constructing operator: readers__Video encountered: [/opt/dali/dali/operators/reader/loader/video_loader.cc:227] Assert on "file_data->file_stream" failed: Could not open file /data/Gray/Database/6408325533.mp4 Stacktrace (32 entries):
`
I tried install `FFmpeg` but which dosen't work, Could you tell me what should I do next?

**Comment by JanuszL** [comment]
Hi @Gray-OREO,

> Thanks for your help, but crop_mirror_normalize seems like only can be used in loop for videos, is there some influences for efficiency?

It works fine on my end:
```
video = fn.crop_mirror_normalize(video, output_layout="FHWC")```

> And I had tried my code in another server with Quadro GP100, but there is an error as following:

Are you sure that the file `/data/Gray/Database/6408325533.mp4` exists? The error comes from the file open function that is not connected with FFmpeg usage itself. Also, DALI ships its own build of relevant libav* libraries so you don't have to install FFmpeg separately.

**Comment by Gray-OREO** [comment]
Hi @JanuszL ,
 
Thanks for your help, I checked the file in this path and find some file lost indeed. And I mistakenly think the function only work for an image by the document. I will try it in next work.

Finally, I wonder that if the professional GPU like Tesla do better than  GTX/RTX under same number of CUDA cores?

**Comment by Gray-OREO** [comment]
Hi, @JanuszL ,

Thanks for your reply, it's very useful. But I met some difficulties in the use of DALI.

1. I'm not sure if there are any functions in DALI for video augmentation. 
2. If the function `nvidia.dali.fn.noise` can also be used for videos?

**Comment by mzient** [comment]
@Gray-OREO noise augmentations can be used with arbitrary data, including videos. Resize works (also as a fused decoder) and you can reinterpret the frame dimension as depth and use Rotate and WarpAffine.

**Comment by Gray-OREO** [comment]
@mzient , thanks for your reply, it's very useful.

**Comment by mzient** [comment]
You're most welcome.
