### ISSUE TITLE
Qusetions about fn.readers.video

### ISSUE THREAD

**Issue by ielym** [NVIDIA/DALI#3617]
Hi, my dali version is nvidia-dali-cuda110==1.9.0, I tried to execute the fn.readers.video following the demo [Simple Video Pipeline Reading From Multiple Files](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/sequence_processing/video/video_reader_simple_example.html). I used a part of the UCF-101 datasets (about 200 videos) for experiment. But I got :
```
[avi @ 0x562670ca3bc0] Could not find codec parameters for stream 1 (Audio: mp3 (U[0][0][0] / 0x0055), 44100 Hz, 2 channels, 125 kb/s): unspecified frame size
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
```

So, it's an error should be fixed or just a warning that can be ignored?

Thanks

**Comment by JanuszL** [comment]
Hi @ielym,

You can disregard this warning. It is about the codec of the audio stream. We don't support decoding audio from the video files for now. The video stream should work fine.
