### ISSUE TITLE
How to assign labels when using fn.readers.numpy

### ISSUE THREAD

**Issue by ielym** [NVIDIA/DALI#3622]
Hi, how can I assign labels when using `fn.readers.numpy` ?, just like `data, labels = fn.readers.numpy(files=['1.npy', ...], labels=[0, ...], seed=2020)`

**Comment by JanuszL** [comment]
Hi @ielym,

You cannot assign labels directly to NumPy files.
What you can do it, for example, have a separate list of files that have the labels inside, create a second reader, and read both data with the same seed:
```
data = fn.readers.numpy(files=['1.npy', ...], seed=2020)
labels = fn.readers.numpy(files=['label_1.npy', ...], seed=2020)
```
Another option is to use [the `get_property` operator](https://docs.nvidia.com/deeplearning/dali/main-user-guide/docs/supported_ops.html#nvidia.dali.fn.get_property) (it is going to be available in the next release until then you can try out nightly/weekly build) to obtain the file name and map it to the corresponding label inside your python code.

**Comment by ielym** [comment]
Thanks, but if I set suffle in `fn.readers.numpy` , can they still keep matching?

**Comment by JanuszL** [comment]
If you provide the same seed to both readers they should stay in sync.

**Comment by ielym** [comment]
Ok, thanks~
