### ISSUE TITLE
Chaining pipelines

### ISSUE THREAD

**Issue by StrongAlexTan** [NVIDIA/DALI#3702]
Is it possible to chain two pipelines together (use the output of one pipeline as input for the next)

```python
@pipeline_def
def pipeline1():
  ...
  return ...

@pipeline_def
def pipeline2(input):
  ...
  return ...

pipe1 = pipeline1()
pipe1.build()
pipe1_output = pipe1.run()

pipe2 = pipeline2()
pipe2.build()
# I want to use the output of pipeline1 as the input to pipeline2; is something like this possible?
pipe2.run(pipe1_output)
```

**Comment by szalpal** [comment]
Hi @StrongAlexTan ,

It's hard to answer your question without some specifics about your use-case. I'd say it might be inefficient to chain pipelines, since there would have to be a synchronization point between them, while having both part in a single pipeline leverages async execution within DALI pipeline.

Anyway, to answer your question, it is possible using `fn.external_source` in the `pipeline2` and feeding it with `feed_input`:
```python
@pipeline_def
def pipeline2():
  input = fn.external_source(name="pipeline2_input", device="gpu")
  return ...

pipe1 = pipeline1()
pipe1.build()
pipe1_output = pipe1.run()

pipe2 = pipeline2()
pipe2.build()
pipe2.feed_input("pipeline2_input", pipe1_output[0])
pipe2.run()
```

**Comment by StrongAlexTan** [comment]
Thanks for the reply. Basically I want to load a dataset and benchmark how long it takes to apply a DALI operation to it, say the rotate operation. I don't want to include the dataset loading time into the benchmark so I thought about splitting it into two pipelines, one for loading the images, and a second for rotating the images - then I plan to benchmark just the second pipeline.

**Comment by mzient** [comment]
@StrongAlexTan 
By default DALI runs asyncrhonously, so if you want to time the pipeline, you should use @szalpal 's example and additionally set `exec_pipelined=False, exec_async=False` on the pipeline which you want to time. Note that doing so will distort the result. Another approach to timing would be to pre-load the dataset (or a representative part thereof) into memory and pass it to `external_source.

```Python

for _ in range(num_iters):
  data.append(pipe1.run())

@pipeline_def
def pipeline2(data):
  images = fn.external_source(data, batch=False)
  return fn.whatever(images)

pipe2 = pipeline2(data, batch_size=..., num_threads=..., device_id=...)
pipe2.build()
# start timing
for _ in range(num_iters):
  pipe2.run()
#end timing

```
