### ISSUE TITLE
NumPy arrays for classification purpose

### ISSUE THREAD

**Issue by 4fee8fea** [NVIDIA/DALI#3742]
Hi, thanks for your time!

My application is classification targeted. So the data point is `(data, label)` pair. 

The data used in training is NumPy arrays with shape `[H, W, C]`, where `C >> 3`.

I wonder which kind of data format can be used, `tfrecord` or `lmdb` or `NumPy` itself?

**Comment by JanuszL** [comment]
Hi @4fee8fea,

You can use [the numpy reader operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/numpy_reader.html). If you want to read data and labels in parallel the best would be to build a list of file names and pass it to the `files` argument (list of images names and corresponding labels need to match) of two instances of the reader and provide the same seed to both of them so you know that shuffling matches.
You can also try out [the external source operator in parallel mode](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/parallel_external_source.html).
TFRecord or LMDB will work with DALI only if you store raw data there (not NumPy array) as the dedicated reader cannot parse NumPy arrays inside mentioned containers.

**Comment by 4fee8fea** [comment]
Dear @JanuszL, thanks for you reply!

I will give it a try.

**Comment by 4fee8fea** [comment]
```python
class TrainPipeline(Pipeline):
    def __init__(self, args):
        super().__init__(
            batch_size=args.batch_size,
            num_threads=args.num_workers,
            device_id=0,
            seed=args.seed
        )
        
        patches_files = sorted(os.listdir(os.path.join(args.dali_file_root, 'data')))
        labels_files = sorted(os.listdir(os.path.join(args.dali_file_root, 'labels')))
        
        self.patches = fn.readers.numpy(device='cpu', file_root=args.dali_file_root, files=patches_files, shuffle_after_epoch=True, seed=args.seed)
        self.labels = fn.readers.numpy(device='cpu', file_root=args.dali_file_root, files=labels_files, shuffle_after_epoch=True, seed=args.seed)

        # Define the data augmentation operations
        self.rotate = fn.rotate(90)
        self.randomResizedCrop = fn.random_resized_crop(args.patch_size)
        self.horizontalFlip = fn.flip(horizontal=1, vertical=0)
        self.verticalFlip = fn.flip(horizontal=0, vertical=1)
        self.erase = fn.erase()
    
    def define_graph(self):
        patches = self.rotate(self.patches)
        patches = self.randomResizedCrop(patches)
        patches = self.horizontalFlip(patches)
        patches = self.verticalFlip(patches)
        patches = self.erase(patches)
        return (patches, self.labels)
```

Hi @JanuszL, here is my current pipeline, is there anything else I should consider?

**Comment by JanuszL** [comment]
Hi @4fee8fea,

I don't see anything worrying with the code. It should work.
I also recommend moving to the fully functional API, please check [this guide](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/getting_started.html) - so you can remove `define_graph`.

BTW - I think you can merge flips into one call as you `fn.flip(horizontal=1, vertical=1)`, you don't have to do it in two steps.

**Comment by 4fee8fea** [comment]
Thanks for your prompt reply and valuable suggestions, and I wish you all the best!
