### ISSUE TITLE
[Question] Random access from idx files

### ISSUE THREAD

**Issue by austinmw** [NVIDIA/DALI#3749]
Hi, I have `.idx` files created with the wds2idx tool. I've been using these for DALI loading, but was wondering, does this repository also include a way to use the info from these idx files in order to perform random access of my tar samples?

Pseudocode of what I'm trying to do is very roughly like:
```python
def get_sample(tar_filepath, idx_filepath, sample_key):
    key_info = get_key_info(idx_filepath, sample_key)
    x,y = get_sample(tar_filepath, key_info)
    return x,y
```

**Comment by austinmw** [comment]
I guess I can just iterate through the idx until I get to the sample name, open the tar as bytes, seek to the offsets and read the corresponding sizes.

**Comment by szalpal** [comment]
Hi @austinmw ,

The purpose of using tar files in the WDS format is that the samples are stored consecutively in the memory, which optimizes the cache usage. For this reason, random access of samples in the tar file is discouraged and we don't plan to introduce a functionality to do it.

However, should you like to access samples in the tar file at a random fashion, your description in the post above is generally the way to do it. Quite frankly, inside DALI we do it the same way, only we read samples one after another, so we skip the part `iterate through the idx until I get to the sample name` :)

**Comment by JanuszL** [comment]
@austinmw,

Usually this kind of data container (similarly to TFRecord or RecordIO) doesn't support fully random access, or at least it is not recommended. In the case of DALI, we create index files to seek the part of the file assigned to a given shard, however, the format itself doesn't support random seek.
The way these formats are used is to read data sequentially into a local buffer, and randomly sample it to form a batch. It doesn't provide the same level of entropy as fully random access but in most cases if good enough.

**Comment by austinmw** [comment]
Thanks!
