### ISSUE TITLE
How to apply or link compiled(built) DALI library to system.

### ISSUE THREAD

**Issue by Heelim-Hong** [NVIDIA/DALI#3758]
Hi~!
I have put some codes modifying "core/mm" part to study how memory works using DALI and compiled it by following instructions at compiling DALI form the source in documentation. 

Now I'd want to check how it performs while using PyTorch.
In this case, how can I apply compiled DALI library to sysytem. 

1. Is there any way to use pip to install compiled DALI library to Conda env ? just like wheel. If there is a way, I am also wondering installing and using compiled DALI library would cause a conflict with the original DALI library that I have installed at first time. 

2. Or, should I remove original DALI library(found in envs/.../lib/python3.8/site-packages/nvidia/dali) that I have installed using "pip" and then replace it with the compiled DALI ?

Thank you.

**Comment by JanuszL** [comment]
Hi @Heelim-Hong,

If you want to create a portable wheel please follow [these steps](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/compilation.html#using-docker-builder-recommended). It produces a wheel binary in the `wheelhouse` directory in the source code root dir.
The safest way would be to uninstall the old DALI using `pip uninstall ... ` and install the wheel file.

**Comment by Heelim-Hong** [comment]
Thank you! I greatly appreciate your prompt assistance.
