### ISSUE TITLE
there are two pipes exist, is it ok? one for images, another for audio.  

### ISSUE THREAD

**Issue by leijuzi** [NVIDIA/DALI#3766]
when I run this code I got an error
                                           freq_high = 8000.0)

        self.dB = ops.ToDecibels(device=self.device,
                                 multiplier = 10.0,
                                 cutoff_db = -80.0)

        self.mfcc = ops.MFCC(device=self.device,
                             axis=0,
                             dct_type=dct_type,
                             n_mfcc=n_mfcc,
                             normalize=normalize,
                             lifter=lifter)

    def define_graph(self):
        self.data = self.external_source()
        out = self.data.gpu() if self.device == 'gpu' else self.data
        out = self.spectrogram(out)
        out = self.mel_fbank(out)
        out = self.dB(out)
        #out = self.mfcc(out)
        return out

    def iter_setup(self):
        self.feed_input(self.data, self.batch_data)

if __name__=='__main__':
    n_fft=512
    hop_length=512
    pipe = MFCCPipeline(device='cpu', batch_size=1, nfft=512, window_length=512, window_step=256,
                        dct_type=2, n_mfcc=40, normalize=True, lifter=0)
    pipe.batch_data = [np.zeros([98412345,])]
    pipe.build()
    #pipe2 = MFCCPipeline(device='cpu', batch_size=1, nfft=512, window_length=512, window_step=256,
    #                    dct_type=2, n_mfcc=40, normalize=True, lifter=0)
    #pipe2.batch_data = [np.zeros([12345,])]
    #pipe2.build()
    #pipe2.run()
    outputs = pipe.run()
    mfccs_dali = outputs[0].at(0)
    print(mfccs_dali.shape)
                                                                                        66,5          Bot

<img width="1085" alt="image" src="https://user-images.githubusercontent.com/42333539/160411570-356bb1f9-a7e2-4757-b5df-50b8ed1cd1dc.png">

**Comment by leijuzi** [comment]
a similar class exit in py image preprocess, it is fine,  but when I copy to audio I always got this error

**Comment by jantonguirao** [comment]
You are welcome
