### ISSUE TITLE
 Error while building

### ISSUE THREAD

**Issue by ksm9413** [NVIDIA/DALI#3770]
/usr/bin/ld: /usr/local/lib/libprotobuf.a(arena.o): relocation R_X86_64_TPOFF32 against hidden symbol `_ZN6google8protobuf8internal15ThreadSafeArena13thread_cache_E' can not be used when making a shared object
collect2: error: ld returned 1 exit status
make[2]: *** [dali/CMakeFiles/dali.dir/build.make:901: dali/python/nvidia/dali/libdali.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:2766: dali/CMakeFiles/dali.dir/all] Error 2

The above error occurred during make. How do I solve it?

**Comment by JanuszL** [comment]
Hi @ksm9413,

DALI links libprotobuf to avoid version conflicts (protobuf complains if the dynamically loaded library differs from the one used during the build). The distro provided libprotobuf.a seems to miss some compilation options that would allow to link it statically into a shared library, like DALI.
What you can do is to either build it from sources on your own (like [we do](https://github.com/NVIDIA/DALI_deps/blob/main/build_scripts/build_protobuf.sh)) or build [DALI inside docker ](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/compilation.html#using-docker-builder-recommended).

**Comment by JanuszL** [comment]
Closing as stalled.
