### ISSUE TITLE
Can DALI support grayscale video?

### ISSUE THREAD

**Issue by cailijing** [NVIDIA/DALI#3773]
Hello, Can DALI support grayscale video?
In the video_reader_op.h:71，assert on "image_type == DALI_RGB || image_type == DALI_YCbCr" failed: Image type must be RGB or YCbCr.
But I want to use dali to deal with grayscale video, could I fix the problem?

**Comment by JanuszL** [comment]
Hi @cailijing,

The video decoder operates only on color videos. If you want to process gray scale you need to explicitly convert to it using [the color convert operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.color_space_conversion).
```
@pipeline_def
def simple_pipeline():
    video = fn.readers.video(filenames=["sample.mp4"], sequence_length=2, device="gpu")
    video = fn.color_space_conversion(video, image_type=types.RGB, output_type=types.GRAY)
    return video
```

**Comment by cailijing** [comment]
I change the code ,but I meet the other problem. 
TypeError: 'DataNode' object is not callable
Maybe there's something wrong with the way I use it.

This is my code


class VideoReaderPipeline(Pipeline):
	def __init__(self, batch_size, sequence_length, num_threads, device_id, files,
				 crop_size, random_shuffle=True, step=-1):
		super(VideoReaderPipeline, self).__init__(batch_size, num_threads, device_id, seed=12)
		# Define VideoReader
		video = fn.readers.video(device="gpu",
								 filenames=files,
								 sequence_length=sequence_length,
								 normalized=False,
								 random_shuffle=random_shuffle,
								 image_type=types.DALIImageType.RGB,
								 dtype=types.DALIDataType.UINT8,
								 step=step,
								 initial_fill=16,
								 name="Reader")
		video = fn.color_space_conversion(video, image_type=types.RGB, output_type=types.GRAY)
		self.reader = video

		self.crop = ops.CropMirrorNormalize(device="gpu",
										crop_w=crop_size,
										crop_h=crop_size,
										output_layout='FCHW',
										dtype=types.DALIDataType.FLOAT)
		self.uniform = ops.Uniform(range=(0.0, 1.0))  # used for random crop

	def define_graph(self):
		input = self.reader(name="Reader")
		cropped = self.crop(input, crop_pos_x=self.uniform(), crop_pos_y=self.uniform())
		return cropped

### class train_dali_loader():
        self.pipeline = VideoReaderPipeline(batch_size=batch_size,
											        sequence_length=sequence_length,
											        num_threads=2,
											        device_id=0,
											        files=container_files,
											        crop_size=crop_size,
											        random_shuffle=random_shuffle,
											        step=temp_stride)
		        self.pipeline.build()

**Comment by JanuszL** [comment]
Hi @cailijing,

You are mixing the new functional and the old API. Please refer to the latest version of [the getting started guide](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/getting_started.html) to see how to use it.
