### ISSUE TITLE
fn.decoders.image_random_crop--num_attempts?

### ISSUE THREAD

**Issue by qsunyuan** [NVIDIA/DALI#3803]
Does the parameter seem to be useless?

According to Doc.

num_attempts (int, optional, default = 10) – Maximum number of attempts used to choose random area and aspect ratio.

what details have I missed, could you pls provide some insights?

**Comment by JanuszL** [comment]
Hi @qsunyuan,

This operator decodes the image and performs a random crop operation that meets `random_aspect_ratio` and `random_area`. The `num_attempts` parameter makes sure that if the provided constraints are hard to meet, the random selection will end after `num_attempts`  to avoid an infinite loop.
Please check [for the reference](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.random_resized_crop).

**Comment by qsunyuan** [comment]
Thx for your replay.

Why are there hard constraints for `fn.decoders.image_random_crop`? 

For example: ImageNet is set by default to

`random_aspect_ratio`=[0.75, 1.333333]
`random_area`=[0.08, 1.0]

It seems to me that it is possible to operate directly on the coefficients to get the random cropped image.

Any example is about `nvidia.dali.fn.random_bbox_crop`, perhaps hard constraints may arise for it.

**Comment by JanuszL** [comment]
Hi,

These are not hard constraints, just default values used by other frameworks, like [TorchVision](https://pytorch.org/vision/main/generated/torchvision.transforms.RandomResizedCrop.html#torchvision.transforms.RandomResizedCrop). I'm not 100% but it may have come from one of the papers which introduces this augmentation.
[The `random_bbox_crop` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.random_bbox_crop) is used for detection networks, like SSD. It has a similar name but serves a bit different purpose.
