### ISSUE TITLE
resize operator min_filter_ wrong

### ISSUE THREAD

**Issue by tendar** [NVIDIA/DALI#3805]
1. According to user guide,  both the  min_filter_ and mag_filter of resize operator is DALIInterpType.INTERP_LINEAR;
2. But in the source code of file "operators/image/resize/resampling_attr.cpp".
`void ResamplingFilterAttr::PrepareFilterParams(
      const OpSpec &spec, const ArgumentWorkspace &ws, int num_samples) {
  GetPerSampleArgument(interp_type_arg_, "interp_type", spec, ws, num_samples);
  GetPerSampleArgument(min_arg_, "min_filter", spec, ws, num_samples);
  GetPerSampleArgument(mag_arg_, "mag_filter", spec, ws, num_samples);
  if (!spec.TryGetArgument(dtype_arg_, "dtype"))
    dtype_arg_ = DALI_NO_TYPE;
  bool has_interp = spec.ArgumentDefined("interp_type");
  bool has_min = spec.ArgumentDefined("min_filter");
  bool has_mag = spec.ArgumentDefined("mag_filter");

  min_filter_.resize(num_samples, ResamplingFilterType::Triangular);  // default min_filter is ResamplingFilterType::Triangular
  mag_filter_.resize(num_samples, ResamplingFilterType::Linear);

  auto convert = [](auto &filter_types, auto &interp_types) {
    for (int i = 0, n = filter_types.size(); i < n; i++)
      filter_types[i] = interp2resample(interp_types[i]);
  };

  if (has_min)
    convert(min_filter_, min_arg_);
  else if (has_interp)
    convert(min_filter_, interp_type_arg_);

  if (has_mag)
    convert(mag_filter_, mag_arg_);
  else if (has_interp)
    convert(mag_filter_, interp_type_arg_);
}`

**Comment by JanuszL** [comment]
Hi, @tendar,

I'm sorry but I do not fully understand the nature of the issue you reported. Do you mean that there is a flaw in the way how the operator obtains `min_filter` and `mag_filter`?

**Comment by mzient** [comment]
@tendar Thanks for reporting, it looks like an error in the documentation. We will update the documentation to reflect the actual behavior.

**Comment by tendar** [comment]
Thanks for your repaly. and can you give me some docs of ResamplingFilterType::Triangular instructions. i had consult opencv docs， i do not find any infomation of this InterpType.

**Comment by tendar** [comment]
Thanks for your help.

**Comment by JanuszL** [comment]
@tendar - https://github.com/NVIDIA/DALI/pull/3816 should fix this.

**Comment by JanuszL** [comment]
[1.14](https://github.com/NVIDIA/DALI/releases/tag/v1.14.0) is available and should address this issue.
