### ISSUE TITLE
Question about video pipe memory allocation

### ISSUE THREAD

**Issue by Renzzauw** [NVIDIA/DALI#3812]
Hi!

I use a DALI video pipeline to decode & pre-process batches of video frames on the GPU and feed these as PyTorch tensors directly to a Yolov5 object detection model, which greatly improves the speed of our object detection in videos. At the moment we pass a fixed sequence length when initializing the pipeline, but in various cases (e.g. when using a larger Yolov5 model, when decoding higher resolution videos, or when using a different GPU with a different memory capacity) I could run into memory issues, such as not enough memory being free to be allocated to the DALI pipe.

My question is: is it possible to automatically assign a sequence length based on free GPU memory, and if not, is there a way to calculate beforehand how much GPU memory a pipeline will require?

I am able to determine how much GPU memory I have left after loading my Yolov5 model, so if I could somehow use this information to pick a sequence length for my DALI pipe, that would be ideal in my case!

Thanks in advance!

**Comment by JanuszL** [comment]
Hi @Renzzauw,

It is not always possible to calculate the memory needed ahead of time, especially when randomness comes to play (samples with different resolutions are randomly selected to the batch, and samples are randomly resized). You can read more about the memory management strategies [here](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/advanced_topics_performance_tuning.html#memory-consumption).
You can try to estimate the required amount of the memory by calculating the size of each operator's outputs (image size x sequence length x batch size), and account for additional [buffering](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/advanced_topics_performance_tuning.html#prefetching-queue-depth) at the output of each DALI [stages](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/pipeline.html#processing-graph-structure).

**Comment by Renzzauw** [comment]
@JanuszL Thanks for your reply! 

In my case, I can make the assumption that the videos I process with my pipe will have a fixed resolution. Additionally, as far as I know, I do not make use of any random processes. I have attached my inference pipe, which is based on an [earlier issue](https://github.com/NVIDIA/DALI/issues/2832). This pipe pre-processes my videos for object detection using a Yolov5 model.

Would under these circumstances it be best to estimate it the way you mentioned (image size x sequence length x batch size + additional buffering)?

Thanks!

```py
@pipeline_def
def inference_pipe(filename, sequence_length, img_size=1280, pad=64):
    """
    Video decoding pipeline that pre-processes the data to a shape Yolov5 supports.
    :param filename: Filename of the video file that should be decoded
    :param sequence_length: The number of frames returned per batch of decoding
    :param img_size: Input size of the object detection model
    :param pad: Resized video dimensions should be divisible by this value. This is a requirement of Yolov5
    """
    # Pipeline adjusted to perform preparations for Yolov5 inference
    # Steps:
    # 1. Decode & resize video frames batch to match network size
    # 2. Make width & height divisible by 'pad'
    # 3. Shift the image so padded pixels occur evenly on top, bottom, left and right side of image (letterbox)
    # 4. Normalize image to range [0, 1]
    # 5. Shift channels BHWC -> BCHW (requirement for Yolov5 Tensor input)
    # Based on: https://github.com/NVIDIA/DALI/issues/2832

    video = fn.readers.video_resize(device="gpu",
                                    filenames=filename,
                                    sequence_length=sequence_length,
                                    skip_vfr_check=True,
                                    pad_sequences=True,
                                    file_list_include_preceding_frame=True,
                                    name="Reader",
                                    size=img_size,
                                    mode="not_larger",
                                    dtype=types.FLOAT)

    padded = fn.pad(video, axis_names="HW", shape=[1,1], align=pad)
    shift = fn.cast((fn.shapes(video) - fn.shapes(padded)) // 2, dtype=types.FLOAT)
    dx = fn.slice(shift, 2, 1, axes=[0])
    dy = fn.slice(shift, 1, 1, axes=[0])
    shift = fn.stack(dx, dy, 0.0, axis=0)
    matrix = fn.cat(np.identity(3,dtype=np.float32), shift, axis=1)
    as_volume = fn.reshape(padded, layout="DHWC")
    warped = fn.warp_affine(as_volume, matrix, fill_value=0, interp_type=types.INTERP_NN)
    letterboxed = fn.reshape(warped, layout="FHWC")
    norm = fn.normalize(letterboxed, mean=0, stddev=255)
    shifted = fn.transpose(norm, perm=[0, 3, 1, 2])

    return shifted
```

**Comment by JanuszL** [comment]
Hi @Renzzauw,

In your case `video`, `padded`, `warped`, `norm`, and `shifted` data nodes occupy GPU memory. The `reshape` operator changes only metadata and should not consume GPU memory. Besides that `fn.readers.video_resize`uses some memory internally, especially surfaces for the decoding. So the overall memory consumption should be proportional to the batch size and the sequence length with a constant consumption from the inside of the video decoder itself.
I think it would be best to check how much of the GPU RAM your pipeline is using and if you can easily project the parameters to the memory consumption.

**Comment by Renzzauw** [comment]
Hi @JanuszL,

Thanks for the details on the various operators. I agree it would be easiest to stick to profiling under different batch sizes, so I will try this out!
