### ISSUE TITLE
How to get batch number in epoch when using external_source in `DALIGenericIterator`

### ISSUE THREAD

**Issue by buptweixin** [NVIDIA/DALI#3829]
As the title, I am using external source in the DALIGenericIterator as the tutorial: https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/frameworks/mxnet/mxnet-external_input.html?highlight=external_source : 

```python

class ExternalSourceReader:
    def __init__(
        self,
        root_dir,
        list_file_path,
        batch_size: int,
        shuffle_after_epoch: bool,
        shard_id: int = 0,
        num_shards: int = 1,
        seed: int = 42,
    ):
        self.list_file_path = list_file_path
        self.batch_size = batch_size
        self.metas = load_jsonlines(self.list_file_path)

    def __len__(self):
        return len(self.metas)

    def __call__(self, sample_info):
        if sample_info.iteration >= self.full_iterations:
            # Indicate end of the epoch
            raise StopIteration
        if self.shuffle_after_epoch:
           # blabla..


@pipeline_def(py_num_workers=4, py_start_method="spawn")
def lmk_pipeline(
    eii,
    crop_size,
    aug_cfg,
    shard_id,
    num_shards,
    meta_info,
    is_training,
):
    jpegs, landmarks = fn.external_source(
        source=eii,
        num_outputs=2,
        batch=False,
        parallel=True,
        dtype=[types.UINT8, types.FLOAT],
        # name="Reader",
    )
   # some augmentations
   return jpegs, landmarks

  loader = DALIGenericIterator(
      pipe,
      ["data", "label"],
      last_batch_padded=True,
      last_batch_policy=LastBatchPolicy.PARTIAL,
      size=len(extern_source),
  )
```

However， I cannot get the batch number by `len(loader)` as the build in DataLoaders(such as filereader). I try to to set the `size` parameter to solve it, but there is a warning `Warning: Please set `reader_name` and don't set last_batch_padded and size manually whenever possible. This may lead, in some situations, to missing some samples or returning duplicated ones. Check the Sharding section of the documentation for more details`. 

Could you please help to take a look at is there something wrong with my code? Thanks a lot!

**Comment by JanuszL** [comment]
Hi @buptweixin,

I think the best you can do is just disregard the warning. In the case of the external source, the iterator cannot infer the size of the data set as the `__call__(self, sample_info):` can raise `StopIteration` anytime, for example when reading data from network.
If you know the data set size is fixed and won't change, just set the `size` in the iterator as you do now.

**Comment by buptweixin** [comment]
> Hi @buptweixin,
> 
> I think the best you can do is just disregard the warning. In the case of the external source, the iterator cannot infer the size of the data set as the `__call__(self, sample_info):` can raise `StopIteration` anytime, for example when reading data from network. If you know the data set size is fixed and won't change, just set the `size` in the iterator as you do now.

Ok, thank you for your reply.
