### ISSUE TITLE
Multiple DALIGenericIterators Simultaneously

### ISSUE THREAD

**Issue by jasonxzhou** [NVIDIA/DALI#3833]
Hi DALI team,
(For PyTorch), what is the recommended way to wrap multiple `DALIGenericIterators`, where the iterators all have different sizes? (a simple example behavior would be to terminate the epoch upon finishing the shortest iterator).

**Comment by JanuszL** [comment]
Hi @jasonxzhou,

Could you provide more details regarding your use case?
Maybe you want to wrap multiple pipelines into one iterator?
If so,
> (a simple example behavior would be to terminate the epoch upon finishing the shortest iterator).

then this is a problem that cannot be easily solved. Usually, the idea is to wrap multiple pipelines with the same length for the Data Parallel strategy (one process per node driver the training for all GPUs, so one DALI iterator wraps pipeline for all GPUs), so it doesn't consider the case where pipelines have different lengths.

**Comment by jasonxzhou** [comment]
Hi @JanuszL - thanks for your help. This is a particularly niche use-case in which we do want to wrap pipelines of different lengths together - however, I can work around this at the file list level to pad/force the lists to be of equal length. Thanks!
