### ISSUE TITLE
Post-processing with Nvidia Dali

### ISSUE THREAD

**Issue by justlike-prog** [NVIDIA/DALI#3835]
Hi, I was looking for a way where I could augment an image right after getting it back form the inference still on the GPU. To be more precise I would like to have a way to pass a Tensor to a blurring function and do the blurring on the GPU.

I saw that Nvidia Dali is capable of doing such a thing when it comes to preprocessing. How would that work if I would do postprocessing?

**Comment by JanuszL** [comment]
Hi @justlike-prog,

It is possible. You can use [the external source operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/external_input.html) to feed raw data into the DALI pipeline. In your case, you can disable pipelining and prefetching as you probably want to process samples as they appear.

If you are using TRITON, there is a dedicated [DALI backend ](https://github.com/triton-inference-server/dali_backend) that would handle data passing from the model, and all you have to do is just define the postprocessing flow.
