### ISSUE TITLE
Conditional Assignment

### ISSUE THREAD

**Issue by jasonxzhou** [NVIDIA/DALI#3837]
Hi DALI team,
Is there a way to conditionally overwrite/assign values as part of the pipeline? For example, something such as:
```
arr = fn.decoders.image(files, device='mixed')
arr[arr == 1] = 0 
```
Thanks for your help.

**Comment by JanuszL** [comment]
Hi @jasonxzhou,

You can try out [mathematical expression](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/expressions/expr_conditional_and_masking.html) to achieve what you want.
You can also check [the `lookup_table` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.lookup_table).

**Comment by jasonxzhou** [comment]
Thank you very much!
