### ISSUE TITLE
Batch Size Uniformity with external_source

### ISSUE THREAD

**Issue by jasonxzhou** [NVIDIA/DALI#3842]
Hi DALI team - thanks for the help thus far. I am currently working on the following issue:

Say I have a list of 130 images, as well as a corresponding length 130 numpy array (where entry i in the array corresponds to the i'th image). For batch size =  64, I would expect to get 3 batches total, of size [64, 64, 2]. 

I load in the images as usual using readers, and I would like to use `external_source` for the numpy array (such that a given batch contains the images and the corresponding entries from the numpy array). 

However, I am running into the following issue:
```
    return self._pipe.ShareOutputs()
RuntimeError: Critical error in pipeline:
Error when executing CPU operator readers__File encountered:
[/opt/dali/dali/pipeline/operator/operator.cc:42] Assert on "ref_batch_size == output_batch_size" failed: Batch size has to be uniform across one iteration. Expected: 2; Actual: 64
```

With `external_source` (without it - where I only load the images - I do get [64, 64, 2] as expected), the first two iterations produce size 64 batches as expected, and the above error occurs on the third iteration. I have attached code snippet below:

```
class ExternalInputIterator():
    def __init__(self, data, batch_size):
        self.batch_size = batch_size
        self.data  = data

    def __iter__(self):
        self.i = 0
        return self 
    
    def __next__(self):
        self.i += 1
        return self.data[(self.i - 1) * self.batch_size : self.i * self.batch_size]

    def __len__(self):
        return len(self.data)

@pipeline_def
def simple_pipeline(file_root, files, eii):
    files, _ = fn.readers.file(file_root=file_root, files=files, random_shuffle=False, name='reader')
    images = fn.decoders.image(files, device='mixed')
    simple_arr = fn.external_source(source=eii, batch=True, dtype=types.UINT8)
    return images, simple_arr

pipe = simple_pipeline(
    file_root=file_root,
    files=file_list,
    eii=ExternalInputIterator(data=np.ones(130, dtype=np.uint8), batch_size=64),
    batch_size=64,
    num_threads=2,
    device_id=0
)

dali_iter = DALIGenericIterator(
    pipelines=pipe,
    output_map=["image", "arr"],
    reader_name='reader',
    last_batch_policy=LastBatchPolicy.PARTIAL,
    auto_reset=False 
)
```
Thanks!

**Comment by szalpal** [comment]
Hello @jasonxzhou !

It's hard to tell what precisely is the problem, without a repro with data. Could you tell, what is the shape of `data` passed to `ExternalInputIterator` constructor?

Additionally, please note, that you can use the [debug mode](https://docs.nvidia.com/deeplearning/dali/main-user-guide/docs/examples/general/debug_mode.html) to resolve this kind of errors.

**Comment by JanuszL** [comment]
Hi @jasonxzhou,

I think you just run out of data in external source. Please try:
```
        def __next__(self):
        ret =  self.data[self.i : self.i + self.batch_size]
        self.i += self.batch_size
        self.i %= len(self.data)
        if len(ret) != self.batch_size:
            # wrap up or just stop
            ret = np.concatenate((ret, self.data[0 : self.i]))
            # raise StopIteration
        return ret
```

**Comment by jasonxzhou** [comment]
@JanuszL my understanding was that I can return a partial batch on the last iteration - do I instead need to always return a full `batch_size` from external input iterator regardless of `LastBatchPolicy.PARTIAL`?

**Comment by JanuszL** [comment]
Hi @jasonxzhou,

This is a bit challenging. DALI supports variable batch size as long as the data source is the `external_source` operator. If you combine it with the regular reader it is expected that the batch size would be constantan.
`LastBatchPolicy.PARTIAL` mostly applies to cases when the `pad_last_batch` is set in the reader, [please check this part of the documentation](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/advanced_topics_sharding.html?highlight=lastbatchpolicy%20partial#sharding).
In your particular case please pad the last batch in the `external_source` operator and if the data in it is in sync with the `file_reader` (the same number of samples) then the remainder of the batch would be dropped.
Another solution is to move the whole loading into the `external_source` and not use the `file_reader` in this case. Something like this should work:
```
class ExternalInputIterator():
    def __init__(self, data, images_files, batch_size):
        self.batch_size = batch_size
        self.data  = data
        self.images_files = images_files

    def __iter__(self):
        self.i = 0
        return self

    def __next__(self):
        if self.i > len(self.data):
            raise StopIteration
        ret_arr =  self.data[self.i : self.i + self.batch_size]
        file_names = images_files[self.i : self.i + self.batch_size]
        imgs = [np.fromfile(f, dtype=np.uint8) for f in file_names]
        self.i += self.batch_size
        return [imgs, ret_arr]

    def __len__(self):
        return len(self.data)

@pipeline_def
def simple_pipeline(eii):
    files, simple_arr = fn.external_source(source=eii, batch=True, dtype=types.UINT8, num_outputs=2)
    images = fn.decoders.image(files, device='mixed')
    return images, simple_arr

pipe = simple_pipeline(
    eii=ExternalInputIterator(data=np.ones(130, dtype=np.uint8), images_files=images_files, batch_size=max_batch_size),
    batch_size=64,
    num_threads=2,
    device_id=0
)

dali_iter = DALIGenericIterator(
    pipelines=pipe,
    output_map=["image", "arr"],
    auto_reset=False
)
```
