### ISSUE TITLE
Can I just change Keyword Arguments to achieve [ops.CropMirrorNormalize] just Normalize no crop?

### ISSUE THREAD

**Issue by leijuzi** [NVIDIA/DALI#3845]
hi 

I wonder to know if my function just have Normalize, can I still use ops.CropMirrorNormalize?

**Comment by leijuzi** [comment]
my function just like this 
![image](https://user-images.githubusercontent.com/42333539/164960027-9151992d-c752-408c-8c3a-760283d43f83.png)

**Comment by JanuszL** [comment]
Hi @leijuzi,
You can still use `CropMirrorNormalize`, just do:
```
images = fn.crop_mirror_normalize(images,
                                              dtype=types.FLOAT,
                                              mean=[0.485 * 255, 0.456 * 255, 0.406 * 255],
                                              std=[0.229 * 255, 0.224 * 255, 0.225 * 255])
```

**Comment by leijuzi** [comment]
> Hi @leijuzi, You can still use `CropMirrorNormalize`, just do:
> 
> ```
> images = fn.crop_mirror_normalize(images,
>                                               dtype=types.FLOAT,
>                                               mean=[0.485 * 255, 0.456 * 255, 0.406 * 255],
>                                               std=[0.229 * 255, 0.224 * 255, 0.225 * 255])
> ```
hi @JanuszL 
Thank for your reply,  according to you suggestion all I need to do is change :
self.cmnp = ops.CropMirrorNormalize(device="gpu",
                                            output_dtype=types.FLOAT,
                                            output_layout=types.NCHW,
                                            crop=crop,
                                            image_type=types.RGB,
                                            mean=mean,
                                            std=std)
to:
self.cmnp = ops.CropMirrorNormalize(device="gpu",
                                            output_dtype=types.FLOAT,
                                            output_layout=types.NCHW,
                                            image_type=types.RGB,
                                            mean=mean,
                                            std=std)
is it right?  I am afraid crop default = (0,0) means nothing output

**Comment by JanuszL** [comment]
In this case not providing the `crop` parameters should make the image dimensions not modified.

**Comment by leijuzi** [comment]
got that,  thank you very much again @JanuszL

**Comment by JanuszL** [comment]
Hi @leijuzi,
Can you check the resize operation itself?
[This](https://github.com/NVIDIA/DALI/issues/3846#issuecomment-1108349400) can provide you with some insight.

**Comment by leijuzi** [comment]
Hi @JanuszL 
I already use subpixel_scale=False ， if just rest the diff like this: -> y_trt present result of dali
<img width="772" alt="企业微信截图_b222ee09-56a1-49a3-af4a-ae042b5a6d9d" src="https://user-images.githubusercontent.com/42333539/167537714-a220b517-5c7f-4e92-bc9f-44aa1613e5b3.png">
than I add ops.CropMirrorNormalize the diff is bigger like this:
<img width="573" alt="image" src="https://user-images.githubusercontent.com/42333539/167537842-ea520a6e-2526-40cf-aa19-8681db197aae.png">

**Comment by JanuszL** [comment]
@leijuzi,

Can you paste a standalone reproduction that would illustrate the problem you see (you can use https://github.com/NVIDIA/DALI_extra as a source of the test data)?
One more thing you can check is [this](https://github.com/NVIDIA/DALI/blob/main/docs/examples/use_cases/pytorch/resnet50/main.py#L137) usage of the normalization that converts data to 0-1 range. Maybe that is the problem?
