### ISSUE TITLE
resize operator　error

### ISSUE THREAD

**Issue by tendar** [NVIDIA/DALI#3846]
I test resize operator, and compare DALI resize operator with opencv resize , the 'max_allowed_error' may reach up to　127,  interp_type=types.DALIInterpType.INTERP_LINEAR and datatype=uint8.

what's the difference between DALI CPU resize algorithm and opencv?

**Comment by JanuszL** [comment]
Hi @tendar,

Please try setting `subpixel_scale` to False as in the attached example [Resize_example.zip](https://github.com/NVIDIA/DALI/files/8553498/Resize_example.zip).

**Comment by tendar** [comment]
Hi, @JanuszL 

Thank you for your help, It really solved my problem.

**Comment by JanuszL** [comment]
Hi @sunhs,

I think you should adjust eh way you calculate the difference:
```
abs = np.abs(cv_image.astype(np.int32) - dali_image.astype(np.int32))
```a
If you keep the values in `uint8` then the difference can wrap up and be as big as 255. After the proposed change the difference is in the [0, 1] range.

**Comment by sunhs** [comment]
My bad. Thanks a lot! @JanuszL

**Comment by JanuszL** [comment]
@sunhs - happy to help.
