### ISSUE TITLE
pipeline can produce 0-size batch

### ISSUE THREAD

**Issue by jasonxzhou** [NVIDIA/DALI#3855]
Hi DALI team,
I came across the following issue where the pipeline can yield a size-0 batch. Is this intended? (Concise code and output below)

```
num_samples = 26    # total number of image files, same as length of file_list
batch_size = 6           
num_shards = 4

# simple pipeline definition
@pipeline_def
def simple_pipeline(file_root, files, shard_id, num_shards):
    files, _ = fn.readers.file(
        file_root=file_root, 
        files=files, 
        random_shuffle=False, 
        name='reader', 
        pad_last_batch=True, 
        shard_id=shard_id, 
        num_shards=num_shards
    )
    images = fn.decoders.image(files, device='mixed')
    return images

# test for shard_id = 0
shard_id = 0 
pipe = simple_pipeline(
    file_root=file_root,
    files=file_list,
    batch_size=batch_size,
    num_threads=2,
    device_id=shard_id, 
    shard_id=shard_id, 
    num_shards=num_shards
)

dali_iter = DALIGenericIterator(
    pipelines=pipe,
    output_map=["image"],
    reader_name='reader',
    last_batch_policy=LastBatchPolicy.PARTIAL,
    auto_reset=True 
)

epochs = 2
for i in range(epochs):
    print(f'Epoch {i}')
    for d in dali_iter:
        print(d[0]['image'].shape)
```

Output:
```
Epoch 0
torch.Size([6, 480, 640, 3])
torch.Size([0, 480, 640, 3]) # <- 0-sized output
Epoch 1
torch.Size([6, 480, 640, 3])
torch.Size([1, 480, 640, 3])
```

**Comment by jasonxzhou** [comment]
(This is perhaps a related issue): 
With the following values, we get a segmentation fault directly. 
Does pipeline assume `num_samples >> batch_size`? 
```
num_samples = 3
batch_size = 6           
num_shards = 6
```

**Comment by JanuszL** [comment]
Hi @jasonxzhou,

With the `LastBatchPolicy.PARTIAL` set is expected. In this case, all `DALIGenericIterator` would iterate the same number of times each epoch, however, there are not enough samples to fill all returned batches with samples in the last iteration.
Regarding the ` segmentation fault,` it is a problem when the number of shards is greater than the number of available samples (which doesn't sound like a very real-life case). https://github.com/NVIDIA/DALI/pull/3856 should add a relevant check for that.

**Comment by jasonxzhou** [comment]
Hi @JanuszL - it's very useful to know that `batch_size=0` is indeed expected behavior with that particular `LastBatchPolicy`. 

For the segmentation fault - I agree that is not a realistic configuration, and I am glad to hear that that is indeed the issue (and not  perhaps something else in my pipeline causing problems). 

Thank you very much for your help, I appreciate it.
