### ISSUE TITLE
Epoch skipping behavior with PyTorch Lightning + DDP 

### ISSUE THREAD

**Issue by jasonxzhou** [NVIDIA/DALI#3865]
Hi DALI Team,
I have 3 items that all pertain to compatibility between DALI & PyTorch-Lightning, and would appreciate any help with these items. 
1. For the docs located at (https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/frameworks/pytorch/pytorch-lightning.html), the following line should be updated in the last code box (I believe `distributed_backend` is no longer a keyword argument for `Trainer`, and has become `strategy`): 
```
# trainer = Trainer(gpus=8, distributed_backend="ddp", max_epochs=5) <- current
# trainer = Trainer(gpus=8, strategy="ddp", max_epochs=5) <- new 
```

2. Is there an officially supported/tested version of PyTorch-Lightning we should be using with NVIDIA DALI? 
3. I believe there are some changes in PyTorch-Lightning `>=1.6.0` that produces an odd issue (reproduced with 1.6.2, 1.6.0, **no issue when using 1.5.10**) where when training with `ddp`, the epoch times are inconsistent and have a skipping pattern:
```
Time for epoch 0: 6.885962247848511
Time for epoch 1: 0.0005702972412109375     <- skipped?
Time for epoch 2: 7.945626497268677
Time for epoch 3: 0.0005924701690673828     <- skipped?
Time for epoch 4: 7.870784759521484
...
```

Reproducible code (identical to code from the docs above, but I have added `on_train_epoch_start` and `on_train_epoch_end` to illustrate the issue): 
```
from nvidia.dali import pipeline_def
import nvidia.dali.fn as fn
import nvidia.dali.types as types
from nvidia.dali.plugin.pytorch import DALIClassificationIterator, LastBatchPolicy
import os 
from pytorch_lightning import Trainer
import torch
from torch.nn import functional as F
from torch import nn
from pytorch_lightning.core.lightning import LightningModule
from pytorch_lightning import Trainer
from torch.optim import Adam
import os
import time 

BATCH_SIZE = 64
# Path to MNIST dataset
data_path = os.path.join(os.environ['DALI_EXTRA_PATH'], 'db/MNIST/training/')

class LitMNIST(LightningModule):

    def __init__(self):
        super().__init__()

        # mnist images are (1, 28, 28) (channels, width, height)
        self.layer_1 = torch.nn.Linear(28 * 28, 128)
        self.layer_2 = torch.nn.Linear(128, 256)
        self.layer_3 = torch.nn.Linear(256, 10)

    def forward(self, x):
        batch_size, channels, width, height = x.size()

        # (b, 1, 28, 28) -> (b, 1*28*28)
        x = x.view(batch_size, -1)
        x = self.layer_1(x)
        x = F.relu(x)
        x = self.layer_2(x)
        x = F.relu(x)
        x = self.layer_3(x)

        x = F.log_softmax(x, dim=1)
        return x

    def training_step(self, batch, batch_idx):
        x, y = self.process_batch(batch)
        logits = self(x)
        loss = F.nll_loss(logits, y)
        return loss

    def cross_entropy_loss(self, logits, labels):
        return F.nll_loss(logits, labels)

    def configure_optimizers(self):
        return Adam(self.parameters(), lr=1e-3)

@pipeline_def
def GetMnistPipeline(device, shard_id=0, num_shards=1):
    jpegs, labels = fn.readers.caffe2(path=data_path, shard_id=shard_id, num_shards=num_shards, random_shuffle=True, name="Reader")
    images = fn.decoders.image(jpegs,
                               device='mixed' if device == 'gpu' else 'cpu',
                               output_type=types.GRAY)
    images = fn.crop_mirror_normalize(images,
                                      dtype=types.FLOAT,
                                      std=[0.3081 * 255],
                                      mean=[0.1307 * 255],
                                      output_layout="CHW")
    if device == "gpu":
        labels = labels.gpu()
    # PyTorch expects labels as INT64
    labels = fn.cast(labels, dtype=types.INT64)
    return images, labels

class DALILitMNIST(LitMNIST):
    def __init__(self):
        super().__init__()

    def prepare_data(self):
      # no preparation is needed in DALI
      pass

    def setup(self, stage=None):
        device_id = self.local_rank
        shard_id = self.global_rank
        num_shards = self.trainer.world_size
        mnist_pipeline = GetMnistPipeline(batch_size=BATCH_SIZE, device='gpu', device_id=device_id, shard_id=shard_id,
                                       num_shards=num_shards, num_threads=8)
        self.train_loader = DALIClassificationIterator(mnist_pipeline, reader_name="Reader",
                                                       last_batch_policy=LastBatchPolicy.PARTIAL, auto_reset=True)
    def train_dataloader(self):
        return self.train_loader

    def process_batch(self, batch):
        x = batch[0]["data"]
        y = batch[0]["label"].squeeze(-1)
        return (x, y)

    def on_train_epoch_start(self):
        self.start_time = time.time()
    
    def on_train_epoch_end(self):
        print(f'Time for epoch {self.current_epoch}: {time.time() - self.start_time}')

# Even if previous Trainer finished his work it still keeps the GPU booked, force it to release the device.
if 'PL_TRAINER_GPUS' in os.environ:
    os.environ.pop('PL_TRAINER_GPUS')
model = DALILitMNIST()

trainer = Trainer(gpus=1, strategy="ddp", max_epochs=5)
trainer.fit(model)
```

**Comment by JanuszL** [comment]
Hi @jasonxzhou,

Thank you for reporting this.
Would you mind filing a PR that would address 1st point?
Regarding the 2nd and 3rd, there is no recommended version that would work with DALI. DALI is rather a framework agnostic and it tries to not aim at a particular FW version (although we do our best to support the most popular versions). The mentioned issues with PyTorch-Lightning seem to be not caused by DALI. The mentioned example relies on a couple of things that should be provided by PyTorch-Lightning:
- local_rank, global_rank and world_size
- train_dataloader is called to obtain data loader iterator for training

Still, it is possible that PyTorch-Lightning API changes as it is a very active and rapidly developed project, and the mentioned example needs adjustments. It is still an example and not a build-in integration plugin like nvidia.dali.plugin.pytorch.

**Comment by jasonxzhou** [comment]
Thanks @JanuszL  - I have opened PR https://github.com/NVIDIA/DALI/pull/3867. 
I agree that the issue is most likely with some subtle API change on the PyTorch-Lightning side. I will investigate that further separately. Thanks!

**Comment by jasonxzhou** [comment]
@JanuszL Re-opening as I believe I've figured out the reason for the epoch skipping behavior, and wanted to share in case you think a change (most likely just in documentation, and not code) is warranted. 

There's a change in behavior from Lightning `1.5.10` -> `1.6.0+`:
- `1.5.10`: Lightning makes calls to `DALIGenericIterator.__next__`  until the following is triggered at end of epoch: 
https://github.com/NVIDIA/DALI/blob/8b13a9ff6f38f0d864d60d46efa01132aa1b4ae0/dali/python/nvidia/dali/plugin/base_iterator.py#L280
- `1.6.0+`: Lightning makes calls to `DALIGenericIterator.__next__`  but stops exactly at end of epoch (i.e. it no longer makes calls until `StopIteration` is raised) - this means that the iterator is not reset on end of epoch. Thus on the 2nd epoch, in the first call to `DALIGenericIterator.__next__` , the reset occurs and `StopIteration` is thrown, which ends the 2nd epoch immediately. The 3rd epoch proceeds with no issue, the 4th epoch will end immediately, etc. - producing epoch skipping, essentially. 

The simple fix I've done is to modify `base_iterator.py` to not throw that `StopIteration` when we are using lightning `1.6.0+`, which resolves the issue. 

In case it may be helpful, I've also updated the reproducible script above to be more concise.

**Comment by JanuszL** [comment]
Hi @jasonxzhou,

Thank you for your investigation. Indeed, if the loader provides the `len` the Lightning iterates over the data `len` times not waiting for `StopIteration`.
I'm not sure if we should not throw `StopIteration`, in this case, we would break the flow when the user just iterates over the data set. Also documenting this seems to be fragile as the Lighting may change again.
Honestly, I have no idea why Lighting implements this behavior which seems a bit strange and not very pythonic.

**Comment by jasonxzhou** [comment]
Thanks @JanuszL - I agree. I don't think changes are needed on DALI side then. 
Lightning devs are looking into this change in behavior, I'm waiting on their response. Closing - thanks!

**Comment by JanuszL** [comment]
@jasonxzhou - if you reported an issue to Lightning devs can you provide a link to it? I'm interested in tracking the progress as well.

**Comment by jasonxzhou** [comment]
discussion is on the torch-lightning slack group currently (https://pytorch-lightning.slack.com/archives/CRBLFHY79/p1651187723046849), I will open a proper issue today as I haven't heard back in 3-4 days.

**Comment by jasonxzhou** [comment]
@JanuszL made issue here: https://github.com/PyTorchLightning/pytorch-lightning/issues/12956

**Comment by JanuszL** [comment]
@jasonxzhou - thanks!
