### ISSUE TITLE
Randomly applying operators

### ISSUE THREAD

**Issue by jasonxzhou** [NVIDIA/DALI#3868]
Hi DALI Team,
Is there a way to apply `nvidia.dali.fn` operators randomly? (specifically, I would like to apply `nvidia.dali.fn.grid_mask` on each image randomly, according to some probability _p_).

Thanks.

**Comment by JanuszL** [comment]
Hi @jasonxzhou,

DALI doesn't support yet fully conditional execution, however, you can mimic it with a mask. Please check this [example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/expressions/expr_conditional_and_masking.html).

**Comment by jasonxzhou** [comment]
got it, thanks very much @JanuszL.

**Comment by klecki** [comment]
Hi @jasonxzhou,
DALI supports conditional execution now: https://docs.nvidia.com/deeplearning/dali/main-user-guide/docs/pipeline.html#conditional-execution

You can use a random operator like `fn.random.coin_flip` in condition to apply operators randomly. Here is an example of doing that: https://docs.nvidia.com/deeplearning/dali/main-user-guide/docs/examples/general/conditionals.html

**Comment by jasonxzhou** [comment]
The masked approach was working but computing multiplexing between both augmented and non-augmented images took a lot of memory. Will try out the new conditional execution, thanks @klecki!
