### ISSUE TITLE
NVML Error on WSL2

### ISSUE THREAD

**Issue by omri-cavnue** [NVIDIA/DALI#3878]
I am trying to use DALI on WSL2 and I am getting the following error:
```
RuntimeError: Critical error when building pipeline:
Error when constructing operator: decoders__Image encountered:
Error in thread 0: nvml error (999): A nvml internal driver error occurred
Current pipeline object is no longer valid.
```
I saw the following [issue](https://github.com/NVIDIA/DALI/issues/2921), but setting `DALI_DISABLE_NVML` doesn't seem to fix this.

To reproduce:
```
pip3 install --extra-index-url https://developer.download.nvidia.com/compute/redist --upgrade nvidia-dali-cuda110
export DALI_DISABLE_NVML="true"
python3 DALI.py
```
My CUDA version is `CUDA Version: 11.6` from nvidia-smi. I have also tried running the code in a docker container based on the `nvcr.io/nvidia/pytorch:22.03-py3` image and I get the same error

**Comment by JanuszL** [comment]
Hi @omri-cavnue,

Thank you for reporting this.
It is not expected. Can you provide a DALI pipeline that reproduces this problem?

**Comment by omri-cavnue** [comment]
I am using the pipeline from this (example)[https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/dataloading_webdataset.html]

**Comment by JanuszL** [comment]
Can you set ```export DALI_DISABLE_NVML=1``` and try again?

**Comment by omri-cavnue** [comment]
@JanuszL looks like that fixed it. I just saw that it is using [atoi](https://github.com/NVIDIA/DALI/pull/3404/files), which is why it was returning 0 for non-numeric inputs
