### ISSUE TITLE
Updating files/file_root in fn.readers.file at end of epoch

### ISSUE THREAD

**Issue by jasonxzhou** [NVIDIA/DALI#3916]
Hi DALI team,
For a simple pipeline such as:
```
@pipeline_def
def simple_pipeline(image_dir, image_files):
    jpegs, labels = fn.readers.file(file_root=image_dir, files=image_files)
    images = fn.decoders.image(jpegs, device='cpu')
    return images, labels
```
Is there a way to change, at the end of each epoch, the `file_root` or `files` args that `fn.readers.file` accesses? 
I think this can be achieved by re-instantiating & building the pipeline at the end of each epoch and passing in the new `file_root/files` arguments to `fn.readers.file`, but wondering if there is a better way to do so.
(Using PyTorch-Lightning, and `DALIGenericIterator` as the dataloader).

**Comment by JanuszL** [comment]
Hi @jasonxzhou,

If you need to use `fn.readers.file` there is no other way to do it. If you want to have full flexibility you may consider [the `external_source` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/parallel_external_source.html).

**Comment by jasonxzhou** [comment]
Got it, thanks @JanuszL.
