### ISSUE TITLE
Question on shuffling order while using ExternalSource and fn.readers.file

### ISSUE THREAD

**Issue by KsawerySmoczynski** [NVIDIA/DALI#3947]
I have a semantic segmentation pipeline with images and labels being loaded with fn.readers.file operators.
Currently I'd like to add additional input stored in tiff files as a floating point one channel data.

All of the sources (images, tiff images and labels) have to be aligned. 
Loading tiff floating point images resulted in nullpointer exceptions (fn.decoder.image node had output_type set to ANY_DATA). In docs I saw that DALI relies on OpenCV for loading them. I also saw that cv2.imread requires special flags for loading floating point tiffs, otherwise it loads nulls, which made sense in relation with the error I saw while trying to load them with DALI.

Therefore I've deceided to create custom external source operator for this input, however what I'm worried about is the order of drawn samples which has to be aligned with normal images and labels while shuffling between epochs.
I've read [this](https://docs.nvidia.com/deeplearning/dali/main-user-guide/docs/examples/general/data_loading/parallel_external_source.html#Shuffling-dataset-between-epochs) tutorial from docs on shuffling, but I'm not sure how to tackle this issue, so that permutation function from callback would follow the one from fn.readers.files operators. 

Would you have any recommendations regarding what would be the best way to approach this problem?
Is the approach with ExternalSource operator correct or am I missing something with regular fn.readers.file workflow?

Initial simplified pipeline with fn.readers.file only:
```python
@pipeline_def
def EnhancedSegmentationPipeline(
    imgs_list: List[str],
    tiffs_list: List[str],
    labels_list: List[str],
    readers_config: Dict,
    precision: int = 32,
):
    use_gpu = Pipeline.current().device_id is not None
    decoder_device, device = ("mixed", "gpu") if use_gpu else ("cpu", "cpu")

    img_type = dali.types.FLOAT16 if precision == 16 else dali.types.FLOAT
    imgs, _ = fn.readers.file(files=imgs_list, name="Reader_imgs", **readers_config)
    tiffs, _ = fn.readers.file(files=tiffs_list, name="Reader_tiffs", **readers_config)
    labels, _ = fn.readers.file(files=labels_list, **readers_config)
    imgs = fn.decoders.image(imgs, device=decoder_device)
    dsms = fn.decoders.image(dsms, device=decoder_device, output_type=dali.types.ANY_DATA)
    labels = fn.decoders.image(labels, device=decoder_device, output_type=dali.types.GRAY)

    imgs = fn.cat(imgs, tiffs, 3)
    return imgs, labels
```

Pipeline with ExternalSource operator which I'm thinking of:
```python
@pipeline_def
def EnhancedSegmentationPipeline(
    imgs_list: List[str],
    tiffs_callback: Callable[dali.types.SampleInfo],
    labels_list: List[str],
    readers_config: Dict,
    precision: int = 32,
):
    use_gpu = Pipeline.current().device_id is not None
    decoder_device, device = ("mixed", "gpu") if use_gpu else ("cpu", "cpu")

    img_type = dali.types.FLOAT16 if precision == 16 else dali.types.FLOAT
    imgs, _ = fn.readers.file(files=imgs_list, name="Reader_imgs", **readers_config)
    tiffs, _ = fn.external_source(source=tiffs_callback, num_outputs=1, dtype=dali.types.FLOAT)
    labels, _ = fn.readers.file(files=labels_list, **readers_config)
    imgs = fn.decoders.image(imgs, device=decoder_device)
    tiffs = fn.decoders.image(tiffs, device=decoder_device, output_type=dali.types.ANY_DATA)
    labels = fn.decoders.image(labels, device=decoder_device, output_type=dali.types.GRAY)

    imgs = fn.cat(imgs, tiffs, 3)
    return imgs, labels
```

**Comment by JanuszL** [comment]
Hi @KsawerySmoczynski,

I think it is hard to match the sample order from the native reader. The file reader itself first preshuffle globally to make sure that in the very first batch the samples from the end of the dataset could appear, then it uses an internal prefetch buffer that is randomly sampled to form a batch.
The most straightforward option would be to use the `external_source` operator to read all samples, return all of them as raw data and decode only tiffs inside. I recommend using the `parallel` option to make it non-blocking.
The other option is to use the `files` argument to pass all samples in the order you want to read them and turn the shuffling off. In this case, you need to pass the order of samples for the whole training (you can create it in the runtime before the DALI pipeline is created).

**Comment by KsawerySmoczynski** [comment]
Thanks a lot for your reply. In terms of performance it would be more beneficial to take a second approach with `files` argument and separate reader for each of the images or reading all of them within one `external_source`?

**Comment by KsawerySmoczynski** [comment]
Great! Thanks a bunch, this resolves all of my concerns.
