### ISSUE TITLE
iterate next video in reader.video_resize()

### ISSUE THREAD

**Issue by royinx** [NVIDIA/DALI#3960]
I am trying to put DALI as video decoder and preprocessor before TensorRT inferencing.
Since reading a long video is RAM consuming, I split it into multiple mini video files, say 1mins video split into 5s *12 videos.

Unfortunately, the DALI video decoder didn't support external_source as a data source.
Although I use `1.mp4` as input video and overwrite the old `1.mp4` with a new video, 
seems once the pipe is built, pipe.run() will always return the same output.

Now I can only rename the video, rebuild the DALI pipe, and run it every time. 

```
import nvidia.dali as dali
import nvidia.dali.fn as fn
import nvidia.dali.types as types

sequence_length = 150

@dali.pipeline_def(batch_size=1, num_threads=1, device_id=0)
def video_pipe():
    target_dimension = [608,608]
    video = fn.readers.video_resize(device="gpu", 
                                     filenames=["1.mp4"],
                                    sequence_length=150,
                                    mode="not_smaller", 
                                    max_size = target_dimension, 
                                    size = target_dimension,
                                    interp_type = dali.types.INTERP_LINEAR,
                                    pad_last_batch = True,
                                    pad_sequences = True
                                    )
    return video

for idx, i in enumerate([f"to_read_%02d.mp4"%n for n in range(12 )]):
    if os.path.exists(i):
        shutil.copyfile(i,"1.mp4")
        pipe = video_pipe(batch_size=2, num_threads=2, device_id=0, seed=12345)
        pipe.build()
        pipe_out = pipe.run()
```

This is the only way I found while rebuilding the pipe every time is inefficient 
Is there any faster way like, 
1) call a func to iter the next video? ( using`file_root=video_directory` / `filenames=["1.mp4","2.mp4", ...]` )
2) any way to import nvvl to decode video and return GPU pointer directly, then I can use CuPy / CUDA kernal_module (in CuPy / Pycuda) to resize and normalise before inference. 
3) other faster way to avoid multiple build process

**Comment by JanuszL** [comment]
Hi @royinx,

The DALI video reader operates on the dataset fixed during the pipeline build process. If you need to decode the video for inference, I recommend checking [DeepStream](https://docs.nvidia.com/metropolis/deepstream/dev-guide/text/DS_Quickstart.html) or [VPF](https://github.com/NVIDIA/VideoProcessingFramework).

**Comment by royinx** [comment]
Thank you @JanuszL , 
Now im working on VPF, FFmpeg and NVcodec directly.
And I hope DALI can support video external node for video string (like JPEG image) in future. Thanks a lot :D

**Comment by JanuszL** [comment]
Hi @royinx,

> And I hope DALI can support video external node for video string (like JPEG image) in future. Thanks a lot :D

We have that on our ToDo list, but rather with low priority as there exist other solutions. I think there would be not much value to adding it to DALI compared to what you have available already. You can combine FFmpeg or VPF with DALI using the [`external source` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/parallel_external_source.html).
