### ISSUE TITLE
Latest scaling mode to resize longer

### ISSUE THREAD

**Issue by austinmw** [NVIDIA/DALI#3966]
Hi, now that `resize_longer` is deprecated, I'm a bit confused about how to use the latest scaling modes.

I'd like to resize images so that the longest side is scaled to 640, and then pad the shorter side with zeros.

Could you please help me determine the right combination of `resize` and `pad` to accomplish this?

**Comment by JanuszL** [comment]
Hi @austinmw,

Please check [the resize tutorial](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/image_processing/resize.html). Regarding padding I think it would be best to use [the `pad` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.pad.html#nvidia.dali.fn.pad).

**Comment by austinmw** [comment]
Hi @JanuszL , I read the resize tutorial, but I found the note on the legacy operations like `resize_longer` to be confusing. Does it mean to say that if I use:

```dali.fn.resize(images, size=[640, 640], mode="not_larger")```

It will always resize the longest side to 640, even if it is shorter than 640 to start with?

**Comment by JanuszL** [comment]
@austinmw - the package is just a single file available here https://github.com/NVIDIA/DALI/blob/main/docs/examples/image_processing/synsets.py. If you run the notebook from its location in the repo, python should import the file seamlessly.
