### ISSUE TITLE
resize raise Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by JunLeecus** [NVIDIA/DALI#3968]
I used DALI in Triton to dowmsample image. When the input image shape is same as dowmsampled image shape, it works well. But when the input image is larger (shape 640 * 480), it broke down and raise Segmentation fault (core dumped). The input image size is the only change.

Keypoint codes are follows:
```
@dali.pipeline_def(batch_size=1, num_threads=1, device_id=0)
def pipe():
    image = dali.fn.external_source(device="gpu", name="image", layout='HWC') 
    image = dali.fn.resize(image, size=(120, 160), dtype=dali.types.FLOAT) 
    image = dali.fn.transpose(image, perm = [2, 0, 1])
    return image
```

It does not raise other errors, so I can't locate the cause of the error.
<img width="1010" alt="截屏2022-06-07 下午10 58 59" src="https://user-images.githubusercontent.com/47651397/172413968-4cd43718-7c99-4897-bec6-6a231eb07ede.png">

**Comment by JanuszL** [comment]
Hi @JunLeecus,

Does it happen only in TRITON? Can you share a standalone and self-contained repro we can run on our own?

**Comment by banasraf** [comment]
Hi @JunLeecus,
Could you also provide config file for the DALI model?

**Comment by JunLeecus** [comment]
Config file for the DALI model:
```
name: "superpoint-pipe"
backend: "dali"
max_batch_size : 1
input [
  {
    name: "image"
    data_type: TYPE_UINT8
    format: FORMAT_NHWC
    dims: [ -1, -1, 1 ]
  }
]
output [
  {
    name: "image_resized"
    data_type: TYPE_FP32
    dims: [ 1, 120, 160 ]
  }
]
```

Codes that you can experiment with are the [official expample](https://github.com/triton-inference-server/server/blob/v2.19.0/docs/examples/jetson/concurrency_and_dynamic_batching/people_detection.cc). Then change the value of `input0_shape` in line 838 to {1, 480, 640, 1}. `TRITONSERVER_TYPE_FP3` to `TRITONSERVER_TYPE_UINT8` in line 840.  Image loading part need to do the corresponding modification, and line 766 `ParseModelMetadata` can be annotated directly.

I know this short description has caused you a lot of trouble. But upload my entire project is not allowed.
Thank you for your help.

**Comment by JunLeecus** [comment]
I found the source of the error. DALI received an empty data, which caused the error. I'm going to keep working on my problems. Thank you for your help.
