### ISSUE TITLE
How can I fix this:

### ISSUE THREAD

**Issue by umie0128** [NVIDIA/DALI#3977]
from nvidia.dali.pipeline import Pipeline
    import nvidia.dali.ops as ops
    from nvidia.dali.plugin.pytorch import DALIClassificationIterator

    class TrainPipeline(Pipeline):
    def __init__(self, batch_size, num_threads, device_id, data_root, file_list, size):
        super(TrainPipeline, self).__init__(num_threads = num_threads, device_id = device_id, prefetch_queue_depth=4)

        self.input = ops.readers.File(file_root=data_root,
                                        shard_id=device_id,
                                        num_shards=num_threads,
                                        random_shuffle=True,
                                        pad_last_batch=True,
                                        file_list=file_list,
                                        name="Reader")
        dali_device ='gpu'
        decoder_device = 'mixed'
        device_memory_padding = 211025920 if decoder_device == 'mixed' else 0
        host_memory_padding = 140544512 if decoder_device == 'mixed' else 0
        self.decoders = ops.decoders.ImageRandomCrop(
                                               device=decoder_device, output_type=types.BGR,
                                               device_memory_padding=device_memory_padding,
                                               host_memory_padding=host_memory_padding,
                                               random_aspect_ratio=[0.8, 1.25],
                                               random_area=[0.8, 1],
                                               num_attempts=100)  
        self.resize = ops.Resize(
                        device=dali_device,
                        size = size,
                        mode="default",  # not_larger default stretch
                        interp_type=types.INTERP_TRIANGULAR)
        self.normalize = ops.CropMirrorNormalize(
                                      dtype=types.FLOAT,
                                      output_layout="CHW",
                                      crop=size,
                                      fill_values = 0,
                                      out_of_bounds_policy  = "pad",
                                    #   pad_output = True,
                                      mean=0,
                                      std=255,
                                      mirror=fn.random.coin_flip(probability=0.5))
        self.rng1 = ops.random.Uniform()
        self.colortwist = ops.ColorTwist(device=decoder_device)
        self.rotate = ops.Rotate(device=decoder_device, fill_value=0)
        self.gridmask = ops.GridMask(device=decoder_device)
        def define_graph(self):
            rng1 = self.rng1(range=(0.5, 1.3))  # brightness or contrast
            rng2 = self.rng1(range=(0.5, 1.0))  # saturation
            rng3 = self.rng1(range=(0, 0.1))  # hue
            rng4 = self.rng1(range=(-20, 20))  # rotation
            rng6 = self.rng1(range=(0.75, 1))  # gridmask: ratio between black square width and tile width.
            rng7 = self.rng1(range=(0, 10))  # gridmask: offset of mask
            jpegs, labels = self.input(name='Reader')
            images = self.decoders(jpegs)
            images = self.resize(images)
            images = self.inputops.ColorTwist(images, brightness=rng1, contrast=rng1, saturation=rng2, hue=rng3,         device=decoder_device)
            images = self.inputops.Rotate(images, angle=rng4, device=decoder_device, fill_value=0)
            images = self.inputops.GridMask(images, ratio=rng6, shift_x=rng7, shift_y=rng7, tile=int(img_size*0.25),         device=decoder_device)
            images = self.normalize(images)
            return images.gpu(), labels.gpu()

    pipe_train = TrainPipeline(batch_size = args.batch_size, num_threads = args.workers, device_id = args.local_rank, data_root = 
    args.data, size = args.pic_size, file_list = f'{args.data}/dali_train_list.txt')
    pipe_train.build()
    train_loader = DALIClassificationIterator(pipe_train, size=pipe_train.epoch_size('Reader'),
                                                  last_batch_policy=LastBatchPolicy.PARTIAL, auto_reset=True)

    Traceback (most recent call last):
    File "vr_dali.py", line 687, in <module>
    main()
    File "vr_dali.py", line 371, in main
    pipe_train.build()
    File "/home/.local/lib/python3.6/site-packages/nvidia/dali/pipeline.py", line 657, in build
    self.start_py_workers()
    File "/home/.local/lib/python3.6/site-packages/nvidia/dali/pipeline.py", line 628, in start_py_workers
    self._build_graph()
    File "/home/.local/lib/python3.6/site-packages/nvidia/dali/pipeline.py", line 477, in _build_graph
    outputs = define_graph()
    File "/home/.local/lib/python3.6/site-packages/nvidia/dali/pipeline.py", line 1158, in define_graph
    raise NotImplementedError
NotImplementedError

**Comment by JanuszL** [comment]
Hi @umie0128,

I see you are using the old API and I recommend using [the functional one](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/getting_started.html). In [this tutorial](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops_legacy.html) you can see how to use the original API.

**Comment by songyuc** [comment]
Hi, @JanuszL, I notice that [DALI_docs_SSD (11 Aug 2021)](https://github.com/NVIDIA/DALI/blob/e5b9768738f46a40c7ec62acff35dabd0e061428/docs/examples/use_cases/pytorch/single_stage_detector/src/coco_pipeline.py#L21-L41) uses `@pipeline_def`, while [DeepLearningExamples/PyTorch/Detection/SSD (9 Nov 2021)](https://github.com/NVIDIA/DeepLearningExamples/blob/048370a0df5debb1fe366401a0b8204724d38bb4/PyTorch/Detection/SSD/ssd/coco_pipeline.py#L25-L35) uses `Pipeline`.

So, I am a little confused, which one is the most recommended?
Looking forward to your response!

**Comment by songyuc** [comment]
Thank you @JanuszL for the explanation!
