### ISSUE TITLE
Is there an better way to apply the same RandomResizedCrop on image and mask but with different interp_type?

### ISSUE THREAD

**Issue by mayujie** [NVIDIA/DALI#3983]
Hello Dear
I'm doing a segmentation task, i want to add `RandomResizedCrop ` to the image and mask.

1st way I did like this

```
   def augment(self, feature):
        image_output, mask_output = self.op_image_mask(feature)
        return image_output, mask_output

    def define_op(self, size, device, **kwargs):
        self.op_image_mask = ops.RandomResizedCrop(
            size=size,
            interp_type=[dali.types.INTERP_LINEAR, dali.types.INTERP_NN],
            random_area=[self.min_value, self.max_value],
            random_aspect_ratio=1.,
            device=device,
        )
```
but it gives an error like this, 
```
 File "/home/yujiema/project/nasomat/venv/lib/python3.8/site-packages/nvidia/dali/types.py", line 94, in _type_convert_value
    return _known_types[dtype][1](val)
  File "/home/yujiema/project/nasomat/venv/lib/python3.8/site-packages/nvidia/dali/types.py", line 55, in <lambda>
    DALIDataType.INTERP_TYPE : ("nvidia.dali.types.DALIInterpType", lambda x: DALIInterpType(int(x))),
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'
```

the documentation says `or TensorList of nvidia.dali.types.DALIInterpType`, but i didn't found where i can create DALIInterpType as an `TensorList`
```
interp_type (nvidia.dali.types.DALIInterpType or TensorList of nvidia.dali.types.DALIInterpType, optional, default = DALIInterpType.INTERP_LINEAR) –

Type of interpolation to be used.
```

2nd way, I'm doing it separately, but need to set them with the same seed. after checking the result, I saw that the random possibility was fixed somehow, even set the seed as -1. I always got the same augmented output. 

```
    def augment(self, feature):
        image_output = self.op_image(feature[0])
        mask_output = self.op_mask(feature[1])
        return image_output, mask_output

    def define_op(self, size, device, **kwargs):
        self.op_image = ops.RandomResizedCrop(
            size=size,
            interp_type=dali.types.INTERP_LINEAR,
            random_area=[self.min_value, self.max_value],
            random_aspect_ratio=1.,
            device=device,
            seed=self.seed,
        )
        self.op_mask = ops.RandomResizedCrop(
            size=size,
            interp_type=dali.types.INTERP_NN,
            random_area=[self.min_value, self.max_value],
            random_aspect_ratio=1.,
            device=device,
            seed=self.seed,
        )
```
I found this issue, https://github.com/NVIDIA/DALI/issues/772
It's a bit different in my case. Because I want to apply different interp_type.

**Q:** Is there a better way to apply the same RandomResizedCrop but only with a different `interp_type` for image and mask?

**Comment by JanuszL** [comment]
Hi @mayujie,

Regarding the 1) option you can use [one of the random generators](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.random.html) to generate a list of values corresponding to interpolation types for each sample, but you cannot provide a list that corresponds to each input.
The 2) way should work. As I understand you get the same result run to run what is expected as the seed is fixed, still it should differ with different seeds. What you can do is randomly generate the seed when creating the pipeline and set it for both `RandomResizedCrop` instances.

**Comment by mzient** [comment]
@mayujie 
Hello!
Our recommended approach is to go with the seed. If the sizes of the images and masks match, you will get matching random crops. The seed must not be -1 - that is a special value and uses an internal source of randomness for the seed.
If you want the seed to change between runs (although I don't know why you insist on that), you may obtain a seed value from some other generator and pass it to both:
```Python
def segmentation_pipe(input_files):
    image_files, mask_files = unzip(input_files)
    enc_images, _ = fn.readers.file(file_root=".", files=image_files)
    enc_masks, _ = fn.readers.file(file_root=".", files=mask_files)
    images = fn.decoders.image(enc_images, device="mixed")
    masks = fn.decoders.image(enc_masks, device="mixed")
    seed = random.randint(1, 0x7fffffff)  # get a common seed
    image_patches = fn.random_resized_crop(
        images,
        random_area=[area_min, area_max],
        random_aspect_ratio=[0.9, 1.1],
        seed=seed)  # the seed
    mask_patches = fn.random_resized_crop(
        masks,
        interp_type = dali.types.INTERP_NN
        random_area=[area_min, area_max],
        random_aspect_ratio=[0.9, 1.1],
        seed=seed)  # same seed
    return image_patches, mask_patches
```
