### ISSUE TITLE
Replicating Normalize from Torchvision in DALI

### ISSUE THREAD

**Issue by danvass** [NVIDIA/DALI#3994]
Hello,

I'm trying to replicate the image preprocessing behaviour from Torch in DALI, however it seems that the Normalize function renders me different results.

The original transformation with Torch is as follows:

```python
from torchvision.transforms import Compose, Resize, CenterCrop, ToTensor, Normalize
from PIL import Image

def to_rgb(image):
    return image.convert("RGB")

def preprocess(size=224):
    return Compose([
        Resize(size, interpolation=Image.BICUBIC),
        CenterCrop(size),
        to_rgb,
        ToTensor(),
        Normalize((0.48145466, 0.4578275, 0.40821073), (0.26862954, 0.26130258, 0.27577711)),
    ])
```

Then based on the Triton resnet example and the documentation, I've created this pipeline in DALI:

```python
from nvidia.dali import pipeline_def
import nvidia.dali.fn as fn
import nvidia.dali.types as types

@pipeline_def(batch_size=256, num_threads=4, device_id=0)
def inception_pipeline():
   images = fn.external_source(device="cpu", name="DALI_INPUT_0")
   images = fn.decoders.image(images, device="mixed", output_type=types.RGB)
   images = fn.resize(images, resize_shorter=224, interp_type=types.INTERP_CUBIC)
   images = fn.crop_mirror_normalize(
       images,
       dtype=types.FLOAT,
       crop_w=224, crop_h=224,
       mean=[0.48145466,0.4578275,0.40821073],
       std=[0.26862954,0.26130258,0.27577711]
       )
    
   return images
```

I've tested running both without Normalize and it outputs the same image, however after Normalizing these are the images I get:

Torchvision
![download-2](https://user-images.githubusercontent.com/4446203/174557455-e4c93de6-2145-4bd8-8610-c13184990691.png)
DALI
![download-4](https://user-images.githubusercontent.com/4446203/174557470-6a560e6f-dca5-42ad-9f7c-408d19ed58ab.png)

I haven't used DALI before so I suspect I'm missing something obvious but would appreciate any advice on how to make the two pipelines match! Thanks

**Comment by JanuszL** [comment]
Hi @danvass,

I think you want to scale the value by 255 to have them in the [0-1] range. Please try:
```
images = fn.crop_mirror_normalize(
       images,
       dtype=types.FLOAT,
       crop_w=224, crop_h=224,
       mean=[0.48145466 * 255,0.4578275 * 255,0.40821073 * 255],
       std=[0.26862954 * 255,0.26130258 * 255,0.27577711 * 255]
       )
```

**Comment by danvass** [comment]
Hey @JanuszL,

Thanks for the suggestion but now it looks like this:

![download (3)](https://user-images.githubusercontent.com/4446203/174582673-b52aa7de-4d4d-4afe-9494-e5a5b2f05900.png)

**Comment by JanuszL** [comment]
Hi @danvass,

I checked that, and when you exclude the resize operator itself and the difference mostly comes from the Bicubic interpolation that DALI and PIL apply (you can comment out the resize and compare the outputs).
See the attached [jupyter notebook](https://github.com/NVIDIA/DALI/files/8940599/Normalize.zip) I used for tests.

**Comment by danvass** [comment]
Got it, I presume that doesn't make much of a difference and that there isn't one that's the same. Thanks for the help!
