### ISSUE TITLE
MemoryError when using tfrecord2idx 

### ISSUE THREAD

**Issue by defqoon** [NVIDIA/DALI#4002]
System:
* CUDA 11.4
* Nvidia Quadro T2000 

Packages:
* nvidia-dali-cuda110==1.15.0
* nvidia-dali-tf-plugin-cuda110==1.15.0

Problem:
I cloned the DALI_extra repo and ran the following:
```
python tfrecord2idx <LOCALPATH>/DALI_extra/db/tfrecord/train train.idx
```
and I am getting the `Not a valid TFRecord file` error message.
Removing the try / except, I get the following:
```
Traceback (most recent call last):
  File "tfrecord2idx", line 22, in <module>
    f.read(proto_len)
MemoryError
```

**Comment by JanuszL** [comment]
Hi @defqoon,

A quick check, do you have [git lfs installed](https://github.com/NVIDIA/DALI_extra#usage)? Can you install it and clone the repo again?

**Comment by defqoon** [comment]
awesome that solved it. However, I am facing the same problem (memory error) when trying to index my own tf record files. My dataset consists in 100 shards of 1.8GB each.

**Comment by JanuszL** [comment]
Hi @defqoon,

This is not expected. Can you share a self-contained repro that shows how you create the data set (you can use DALI extra as the data source)? If we have something we can run on our side that would be great.

**Comment by JanuszL** [comment]
@defqoon,

> it's pretty challenging as I have a few 100s of lines of proprietary code.

I understand that you cannot share it. I'm just asking about something that would reproduce the mentioned problem. I guess there is something specific you do with TFRecord that the `tfrecord2idx` script doesn't support.

**Comment by defqoon** [comment]
so I think I figured it out, my export script is using compression `tf.compat.v1.python_io.TFRecordCompressionType.ZLIB` for the `tf.io.TFRecordOptions`. When I switch to `NONE`, it works.

**Comment by defqoon** [comment]
cool, it's actually not too bad to re-export everything without compression. Thanks
