### ISSUE TITLE
Applying decoders and augmentation to images with float pixel values

### ISSUE THREAD

**Issue by shrutishrestha** [NVIDIA/DALI#4014]
I am using the astronomy data having magnetic filed of unit Gauss as its pixel values. These values are in fits extension and looks like values shown in the picture. It contains float pixel values like -2.5, 4.9 etc. I saw there are only 5 decoders 
1. decoder.audio
2. decoder.image
3. decoder.image_crop
4. decoder.image_random_crop
5. decoder.image_slice

These all need and uint datatype. So how do I use decoder my data which is in float?
<img width="291" alt="Screen Shot 2022-06-27 at 11 38 04 AM" src="https://user-images.githubusercontent.com/33342277/175978948-0379280c-880a-49c7-9247-2df9f731cfe1.png">

**Comment by JanuszL** [comment]
Hi @shrutishrestha,

DALI image decoders don't support floating point outputs. However, you can use [the `external source` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/parallel_external_source.html) and execute any python decoder you like. Thanks to the `parallel` option it should provide good performance.

**Comment by mzient** [comment]
@shrutishrestha There's also a Numpy file reader - so if your files are in `.npy` format, you can read them directly.

**Comment by shrutishrestha** [comment]
@JanuszL and @mzient thank you for the response. Yes I am using the numpy reader and external source operator, so after reading my npy files through numpyreader, how can I do augmentations using DALI, are there any specific libraries like decoder.image_crop or I have to make my own?

**Comment by JanuszL** [comment]
@shrutishrestha - if you use the `external source` operator or the `numpy reader` you don't need to decode your data any further. You have raw images already in the memory and you can use any DALI operator (slice or crop to name a few) directly.

**Comment by JanuszL** [comment]
Hi @shrutishrestha,

I think you can try out [the `reshape` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.reshape.html) - ```high = fn.reshape(high, rel_shape=[1, 1, -1], layout="HWC")``` - it operates only on the metadata so it should have a negligible overhead.

**Comment by JanuszL** [comment]
Hi @shrutishrestha,

This is not expected. Can you tell me what DALI version you use? Does it reproduce with the latest one? Can you set `cache_header_information=False`  and see if it still happens?
Can you provide a minimal repro we can run on our end (you can check https://github.com/NVIDIA/DALI/blob/main/dali/test/python/test_operator_readers_numpy.py to see how to create a test NumPy files on the fly if you cannot share your data)?

**Comment by shrutishrestha** [comment]
Hi @JanuszL I found out that pad_last_batch=True was causing the error. After I deleted this, it worked for more than one thread too. 

Initially I kept this and name="my_reader" when I was getting (8,1,512,512) in both my iterations while I have total 9 samples. So after keeping this, I was able to solve this problem and got (8,1,512,512) sized tensor in 1st iteration and (1,1,512,512)  in my second iteration. I don't know why it didn't work for more number of threads. But once I deleted the pad_last_batch=True parameter, now it is working giving (8,1,512,512) in 1st and (1,1,512,512) in second iterations and also with more number of threads.

Thanks for your quick replies.

**Comment by JanuszL** [comment]
I managed to reproduce the problem. Let me check how we can fix it.

**Comment by JanuszL** [comment]
I think [this ](https://github.com/NVIDIA/DALI/pull/4056) should fix the problem.

**Comment by shrutishrestha** [comment]
Thank you. This fixed the issue.
