### ISSUE TITLE
How to change the batch size of pipeline in next iteration??

### ISSUE THREAD

**Issue by shrutishrestha** [NVIDIA/DALI#4028]
Hi this is my code below:
---initialization---
```
train_batch_size = 8
    pipe_train_gpu = custom_pipeline(batch_size=train_batch_size, device_id=0,num_threads=10, files= trainpathlist, set_affinity=True, data_path = "..")

    dali_train_iter = ExternalInputGpuIterator(pipe_train_gpu, batch_size=train_batch_size, last_batch_policy=LastBatchPolicy.PARTIAL, auto_reset=True, files= trainpathlist)
```

---pipelines---

```
@pipeline_def
def custom_pipeline(files, data_path):
    data = fn.readers.numpy(device='gpu', file_root=data_path, files =files)
    return (data)
```

```
class ExternalInputGpuIterator(DALIGenericIterator):

    def __init__(self, pipelines, batch_size, files, last_batch_policy=LastBatchPolicy.PARTIAL, auto_reset=True):
        super().__init__(pipelines=pipelines, last_batch_policy=last_batch_policy, auto_reset=auto_reset,output_map=['data'])
        self.files = files
        self.batch_size = batch_size
        self.data_set_len = len(self.files)
        self.n = self.data_set_len

    def __iter__(self):
        self.i = 0
        shuffle(self.files)
        return self

    def __len__(self):
        return self.data_set_len

    def __next__(self):
        if self.i >= self.n:
            self.__iter__()
            raise StopIteration

        else:
            out = super().__next__()
            datalist = out[0]['data']

            q = (self.n - self.i) // self.batch_size
            mod = (self.n - self.i) % self.batch_size
            if q>0:
                self.i = self.i + self.batch_size
            else: 
                self.i = self.i + mod
            return (datalist)
   
    next = __next__
```
    
So in my above code, the self.n is 9, the batchsize is 8, the __next__ function in ExternalInputGpuIterator runs 2 iterations of size 
1. iteration 1: torch.Size([8, 512, 512])
2. iteration 2: torch.Size([8, 512, 512])
But, as my total size is 9 and as 8 samples are already gone in iteration 1, so [1, 512, 512] with 1 sample should happen in second iteration.

Here in the docs of pipeline, it is said that ["The batch size might change from iteration to iteration."](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/pipeline.html#:~:text=The%20batch%20size%20might%20change%20from%20iteration%20to%20iteration)

So how can we change the batch size from iteration to iteration because initialization of pipeline with batchsize is only done in the beginning. And, now its giving 8 samples even if in the second iteration only 1 sample should be returned.

**Comment by JanuszL** [comment]
Hi @shrutishrestha,

Hi @shrutishrestha,

The native reader doesn't support changing the batch size during the run. DALI does support variable batch size but only through [the `external source` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/external_input.html).
However, I'm not sure if you need to use it in your use case. What you can do is to:
```
@pipeline_def
def custom_pipeline(files, data_path):
    data = fn.readers.numpy(device='gpu', file_root=data_path, files =files, pad_last_batch=True, name="my_reader")
    return (data)

pipe = custom_pipeline(batch_size=batch_size, x, y)
it = DALIGenericIterator(pipelines=[pipe], files, last_batch_policy=LastBatchPolicy.PARTIAL, auto_reset=True
,output_map=['data'], reader_name="my_reader")
```
`pad_last_batch=True`, `last_batch_policy=LastBatchPolicy.PARTIAL` and `reader_name="my_reader"` should do the job.

**Comment by shrutishrestha** [comment]
Hi JanuszL, 
Thank you for the reply.  So if I have 3 data to take in custom pipeline. How should I keep the reader name? 
@pipeline_def
def custom_pipeline(files, data_path):
    data1 = fn.readers.numpy(device='gpu', file_root=data_path1, files =files, pad_last_batch=True, name="my_reader")
    data2 = fn.readers.numpy(device='gpu', file_root=data_path2, files =files, pad_last_batch=True, name="my_reader")
    data3 = fn.readers.numpy(device='gpu', file_root=data_path3, files =files, pad_last_batch=True, name="my_reader")

    return (data1,data2,data3)

pipe = custom_pipeline(batch_size=batch_size, x, y)
it = DALIGenericIterator(pipelines=[pipe], files, last_batch_policy=LastBatchPolicy.PARTIAL, auto_reset=True
,output_map=['data'], reader_name="my_reader")

When I do this, I get this error.
RuntimeError: [/opt/dali/dali/pipeline/pipeline.cc:338] Assert on "it == edge_names_.end()" failed: Output name 'my_reader' conflicts with existing intermediate result name. (op: 'readers__Numpy', output: 'my_reader')

If I keep three different names formy three numpy readers, my_reader1, my_reader2, my_reader3, then how can I pass there to the DALIGenericIterator __init__ function?

**Comment by JanuszL** [comment]
@shrutishrestha,

In this case, it is enough to just name only one:
```
@pipeline_def
def custom_pipeline(files, data_path):
    data1 = fn.readers.numpy(device='gpu', file_root=data_path1, files =files, pad_last_batch=True, name="my_reader")
    data2 = fn.readers.numpy(device='gpu', file_root=data_path2, files =files, pad_last_batch=True)
    data3 = fn.readers.numpy(device='gpu', file_root=data_path3, files =files, pad_last_batch=True)

    return (data1,data2,data3)

pipe = custom_pipeline(batch_size=batch_size, x, y)
it = DALIGenericIterator(pipelines=[pipe], files, last_batch_policy=LastBatchPolicy.PARTIAL, auto_reset=True,output_map=['data'], reader_name="my_reader")```

One more thing to keep in mind, if you want to enable shuffling remember to set the same seed to each reader.

**Comment by JanuszL** [comment]
@shrutishrestha,

> but I didn't get any specific changes with and without putting this DALI_AFFINITY_MASK environment variable

I'm not sure what you expect. The affinity makes sure that DALI threads don't jump between CPU cores. You can run [`NVIDIA nsight systems`](https://developer.nvidia.com/nsight-systems) with CPU profiling and see if DALI threads maintain affinity over time or not. This particular optimization is most important with highly optimized, multi GPU, multi-node workloads where moving threads between cores (DALI and deep learning frameworks) can cause jitter and increased computation time. For regular workloads, the difference is not significant.

**Comment by shrutishrestha** [comment]
<img width="1509" alt="Screen Shot 2022-07-14 at 1 48 55 PM" src="https://user-images.githubusercontent.com/33342277/179049581-ef2e98f6-1ed3-4e3b-a694-d378af4b178f.png">

Hi @JanuszL, i am using multi gpu in a single node, does it look like threads jumping between CPU's? I am setting args["set_affinity"] = True.

**Comment by JanuszL** [comment]
Hi @shrutishrestha,

Can you share the full profile? Indeed it looks like the main python thread jumps between cores but I cannot tell if that happens for the DALI threads (that are separate from the main python thread) from the screenshot you provided.

**Comment by shrutishrestha** [comment]
Hi Januszl, I am continuing the #4116 thread here, as nsight profiling seems to be relevant in this thread. 

So, this is the native data loader
<img width="1042" alt="Screen Shot 2022-08-04 at 1 08 03 PM" src="https://user-images.githubusercontent.com/33342277/182911172-1865a932-0362-4203-ae13-c173f14894bd.png">

and this is the dali data laoder
<img width="1042" alt="Screen Shot 2022-08-04 at 1 03 02 PM" src="https://user-images.githubusercontent.com/33342277/182911183-a0abff34-584e-4c13-bc99-2e6e62da2282.png">

It seems the python threads are jumping. How can I decrease this? And by seeing this profilers, could you suggest me if I can do something to improve the performance of DALI DataLoaders?

**Comment by JanuszL** [comment]
Hi @shrutishrestha,

Can you share the profile files? I'm sorry but the screen you provided captures only a subset of the whole activity and it is hard to tell which particular part of the processing is slow (IO or the actual processing).

**Comment by shrutishrestha** [comment]
@JanuszL could you please see this drive link? I have uploaded my files in arrows format. If this format does not work in your end, please say me which among these format do you prefer sqlite, hdf5, text, json?

https://drive.google.com/drive/folders/1qPaAr4BCNanKsweb8nzcRlKp2U76RASd?usp=sharing

**Comment by JanuszL** [comment]
@shrutishrestha,

Please forgive my ignorance, but how I can load these files into the Nsight System viewer?

**Comment by shrutishrestha** [comment]
@JanuszL sorry for the format, I have replaced the arrows files with nsys-rep files in the drive. Try opening with File>open. It should work now.

**Comment by JanuszL** [comment]
Hi @shrutishrestha,

It works now. Thank you.
Base on the profiles I see that DALI threads tend to jump over different cores:
![image](https://user-images.githubusercontent.com/39967756/182979577-383e3fd9-f6a1-4efb-b83a-0fadc589b919.png)
However, when I have measured the training iteration time it seems to be comparable with the no-DALI case. I guess your training is not blocked by the data processing time.
A side note for the future, DALI uses heavily NVTX ranges, so tracing them as well should provide better insight what the processing looks like (for example, how much time the CPU stage of the pipeline takes.

**Comment by shrutishrestha** [comment]
Thank you for the informative response @JanuszL. I will see more on NVTX ranges.
