### ISSUE TITLE
How can I get a affine transform matrix according image shape by DALI,

### ISSUE THREAD

**Issue by tendar** [NVIDIA/DALI#4031]
Hi，
   How can I get a affine transform matrix according image shape by DALI, as the code 
````python
a = random.uniform(-degrees, degrees)
    # a += random.choice([-180, -90, 0, 90])  # add 90deg rotations to small rotations
    s = random.uniform(1 - scale, 1 + scale)
    R[:2] = cv2.getRotationMatrix2D(angle=a, center=(img.shape[1] / 2, img.shape[0] / 2), scale=s)
````

**Comment by mzient** [comment]
Hello @tendar 
For images in host memory (CPU), you can use the following:
```Python
shapes = fn.shapes(imgs)
w, h = shapes[1], shapes[0]
center = fn.stack(h, w) / 2
angle = fn.random.uniform(range=(-max_deg, max_deg))
mtx = fn.transforms.rotation(angle=angle, center=center)
s = fn.random.uniform(range=(1 - max_scale, 1 + max_scale))
mtx = fn.transforms.scale(mtx, scale=s, center=center)
```
If your image is already on the GPU, you need to get the shape from somewhere else. One option is `fn.peek_image_shape` to obtain the shapes from raw encoded images.

**Comment by tendar** [comment]
Hi, @mzient 
Thank you so much for your help.

**Comment by tendar** [comment]
Hi, @mzient 

If my GPU image is the output of mixed ImageDecode Operator,  'fn.peek_image_shape'  will not get the shape of my image. because CPU Operator can not follow up Mixed Operator, is it ?

**Comment by mzient** [comment]
You call `fn.peek_image_shape` on the _encoded_ image (the input to mixed decoder).

**Comment by tendar** [comment]
OK， I get it. Thank you.
