### ISSUE TITLE
Using video reader inside a container

### ISSUE THREAD

**Issue by nitsanh** [NVIDIA/DALI#4034]
Hi,

I am trying to run this tutorial - https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/sequence_processing/video/video_reader_simple_example.html inside a docker container (I use the tritonserver:22.05-py3 image).

My first problem was that `libnvcuvid.so` was missing, even though these capabilities were set: `NVIDIA_DRIVER_CAPABILITIES=compute,video,utility.`

This led me to think that something was broken in the way Cuda was installed in the host. I don’t have access to the host itself, so I couldn’t check this theory.

When I ran nvidia-smi inside the container, this was the output I got:

<img width="737" alt="Screen Shot 2022-07-04 at 12 29 49" src="https://user-images.githubusercontent.com/93908036/177145974-077b1134-c733-4756-ac5b-74d0b9866943.png">

What I did next was to install the nvidia driver inside the docker (`apt install nvidia-driver-450`), and then `libnvcuvid` was installed:

```
ldconfig -p | grep libnvcuvid
	libnvcuvid.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libnvcuvid.so.1
	libnvcuvid.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libnvcuvid.so
```

Now when I run the sample code again, I get this error:
```
Traceback (most recent call last):
  File "dali_vid_test.py", line 26, in <module>
    pipe_out = pipe.run()
  File "/usr/local/lib/python3.8/dist-packages/nvidia/dali/pipeline.py", line 981, in run
    return self.outputs()
  File "/usr/local/lib/python3.8/dist-packages/nvidia/dali/pipeline.py", line 880, in outputs
    return self._outputs()
  File "/usr/local/lib/python3.8/dist-packages/nvidia/dali/pipeline.py", line 964, in _outputs
    return self._pipe.Outputs()
RuntimeError: Critical error in pipeline:
Error when executing GPU operator readers__Video encountered:
CUDA driver API error CUDA_ERROR_NO_DEVICE (100):
no CUDA-capable device is detected
Current pipeline object is no longer valid.
```

Any idea what I am doing wrong?

**Comment by jantonguirao** [comment]
@nitsanh Can you share your `docker run` command line? Are you passing `--gpus all`? You shouldn't need to install `nvidia-driver-*` inside the docker (In fact, I think it could cause problems, though I am not sure).

**Comment by nitsanh** [comment]
> @nitsanh Can you share your `docker run` command line? Are you passing `--gpus all`? You shouldn't need to install `nvidia-driver-*` inside the docker (In fact, I think it could cause problems, though I am not sure).

I do pass --gpus all, and I am able to use Dali for images, and use the GPU, my problem starts when I try using the video reader.

I know I shouldn't install nvidia-driver-* inside the container, I was just hoping it'll solve the missing `libnvcuvid` issue I was facing (which it did) without introducing more errors.

I'm just wondering if there's anything I can do *inside* the container that will solve this issue for me (I assume the missing `libnvcuvid` lib and the `CUDA_ERROR_NO_DEVICE (100)` error have to same cause). Since I don't have access to the host machine I can't tell if the driver there is broken / misses anything.

**Comment by jantonguirao** [comment]
@nitsanh I think that your guess was right and there must be something miss-configured on the host side. As far as I know we can't fix or diagnose that from inside the container, so it'd be good if you could check with the person that manages the host.

It might boil down to the driver installation, the library paths, or the docker version. I found a similar issue here: https://github.com/NVIDIA/nvidia-docker/issues/1001

You could check what's suggested in this answer: https://github.com/NVIDIA/nvidia-docker/issues/1001#issuecomment-506809047
That is, check `ldconfig-p | grep cuvid` on the host side.
If everything is correct, this should show the nvcuvid library path inside the container:
```
> docker run -it --runtime nvidia -e NVIDIA_DRIVER_CAPABILITIES=video,compute,utility nvcr.io/nvidia/tritonserver:22.05-py3 sh -c 'ldconfig -p | grep cuvid'
        ...
	libnvcuvid.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvcuvid.so.1
``` 

If you can't access the host, and as a workaround, you could try what's suggested here: 
https://github.com/NVIDIA/nvidia-docker/issues/1466#issuecomment-827059476
That is, installing nvcuvid manually in your docker image.

I hope this helps.

**Comment by nitsanh** [comment]
@jantonguirao thanks for the help, I'll try gaining access to the host
