### ISSUE TITLE
pad on both sides

### ISSUE THREAD

**Issue by tendar** [NVIDIA/DALI#4046]
Hi,

I need your help.
 If i have images with shape of X * Y in DALI pipeline,  both X and Y is smaller than 416. So How can i pad this image up and down,  left and right sides to the shape of 416*416.
Hope you help, thanks.

**Comment by JanuszL** [comment]
Hi @tendar,

Please check [the `pad` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.pad.html).

**Comment by tendar** [comment]
I found the pad operator only can pad at the right side and down size, Is it? I need pad on both left and right side, up and down.

**Comment by JanuszL** [comment]
@tendar,

I'm sorry, I missed the part about padding from both sides.
How about:
```
   shape = fn.peek_image_shape(jpegs)
    images = fn.decoders.image(jpegs, device='mixed')
    anch = fn.stack((416 - shape[1])/2, (416 - shape[0])/2)
    images_pad = fn.slice(images, -anch, (416., 416.), out_of_bounds_policy="pad",
                          normalized_shape=False, normalized_anchor=False)
```

**Comment by jantonguirao** [comment]
There's a simpler way to achieve this, just use:
```
images_pad = fn.crop(images, crop=(416, 416), out_of_bounds_policy="pad")
```
If the image is smaller than the crop size and the out of bounds policy is "pad", you will get padding around the image.
