### ISSUE TITLE
Reading overlapping video frames in pipeline

### ISSUE THREAD

**Issue by g-luo** [NVIDIA/DALI#4061]
Hi, I have a video task that requires the context of surrounding frames, but DALI returns batches of non-overlapping frames.

For example if sequence_length = 3 , 0 represents null padding, and the frames were something like
A B C D E F

DALI currently returns 
[A B C], [D E F]

and I want 
[0 A B], [A B C], [B C D], [C D E], [D E F], [E F 0]

I was wondering if it's possible to configure DALI to return these overlapping frames?

**Comment by JanuszL** [comment]
Hi @g-luo,

Please set `step` to a value smaller than the sequence length. 1 in your case.

**Comment by g-luo** [comment]
Thanks! Issue resolved.

**Comment by g-luo** [comment]
@JanuszL I had another question related to optimizing my DALI setup. I was wondering if it's possible to generate batches by prioritizing sequential frames of a video (but the ordering of videos may be randomized) to avoid unnecessary seek / decode and speed up my dataloading?

Right now I have a dataset of 15k videos with an average of 200 frames / 1000 x 1000 in resolution, and it's taking around 60 hours to even iterate through the whole thing.

**Comment by JanuszL** [comment]
@g-luo,

>  I was wondering if it's possible to generate batches by prioritizing sequential frames of a video (but the ordering of videos may be randomized) to avoid unnecessary seek / decode and speed up my dataloading?

You can turn off shuffling, but it won't prevent DALI from seeking and decoding the frames between the first proceeding keyframe and the is the first in the sequence.

> and it's taking around 60 hours to even iterate through the whole thing.

Is this the number with DALI? You may also check https://github.com/NVIDIA/VideoProcessingFramework to see if it is better aligned with your use case as you just want to decode video with significant additional processing.

**Comment by g-luo** [comment]
I see your point, seems like DALI is not meant for quickly reading over large amounts of data sequentially, but it can do fast random access. Thanks!
