### ISSUE TITLE
How to create mixed operator in DALI?

### ISSUE THREAD

**Issue by leanrdchen00918** [NVIDIA/DALI#4066]
I'm trying to create a custom op with type "Mixed" by referring to  dali/pipeline/pipeline_test.cc, but get an error `Assert on "creator_it != registry_.end()" failed: Operator "MyOperation" not registered for cpu. `Below are the definitions of my op and pipeline:
```
#ifndef MYOPERATION_H_
#define MYOPERATION_H_

#include <vector>

#include "dali/pipeline/operator/operator.h"

namespace other_ns {

class DummyPresizeOpMixed : public ::dali::Operator<::dali::MixedBackend> {
 public:
  explicit DummyPresizeOpMixed(const ::dali::OpSpec &spec)
      : Operator<::dali::MixedBackend>(spec) {
  }

  bool SetupImpl(std::vector<::dali::OutputDesc> &output_desc, const ::dali::MixedWorkspace &ws) override {
    return false;
  }

  using ::dali::Operator<::dali::MixedBackend>::Run;
  void Run(::dali::MixedWorkspace &ws) override{
    auto &input = ws.Input<::dali::CPUBackend>(0);
    int num_samples = input.shape().num_samples();
    auto &output = ws.Output<::dali::GPUBackend>(0);
    output.set_type<size_t>();
    size_t tmp_size[2] = {output.capacity(), input.capacity()};
    output.Resize(::dali::uniform_list_shape(num_samples, std::vector<int64_t>{2}));
    for (int sample_idx = 0; sample_idx < num_samples; sample_idx++) {
      auto *out = output.mutable_tensor<size_t>(sample_idx);
      CUDA_CALL(cudaStreamSynchronize(ws.stream()));
      CUDA_CALL(cudaMemcpy(out, &tmp_size, sizeof(size_t) * 2, cudaMemcpyDefault));
    }
  }
  
};


}  // namespace other_ns
DALI_REGISTER_OPERATOR(MyOperation, ::other_ns::DummyPresizeOpMixed, ::dali::Mixed);

DALI_SCHEMA(MyOperation)
  .DocStr("Dummy")
  .NumInput(1)
  .NumOutput(1);

#endif  // MYOPERATION_H_
```
```
@dali.pipeline_def(num_threads=1, device_id=0)
def pipeline():
    jpegs, labels = dali.fn.readers.file(file_root=args.image_dir, random_shuffle=True, initial_fill=21)
    images = dali.fn.decoders.image(jpegs, device='cpu')
    images = dali.fn.my_operation(images)
    return images
```

**Comment by leanrdchen00918** [comment]
I've solved this problem by assigning my_operation to device 'mixed': ` images = dali.fn.my_operation(images, device="mixed")`

I also wonder if the output device of a mixed operator is limited to GPU? Is there a way I can define a mix operator that takes data from CPU/GPU and output to CPU?
(When I tried to achieve this, I got: `Assert on "tensor_meta.storage_device == StorageDevice::CPU" failed: Output with given index (0) does not have the calling backend type (CPUBackend)`)

**Comment by JanuszL** [comment]
Hi @leanrdchen00918,

I'm glad that you managed to solve your original problem.
You can learn more about the DALI execution model [here](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/pipeline.html#processing-graph-structure).
Now it is possible only to go one way, from CPU to GPU. No other way around. We plan to lift that restriction but I cannot commit to any schedule yet.

**Comment by leanrdchen00918** [comment]
Get it, thanks!

I'm now confused about the way DALI do (de)serialization. I want to pass a struct-like argument to my custom operation to initialize it, by using `pipe.AddOperator(::dali::OpSpec("MyOperation").AddArg("init_arg", my_struct{...})...`. I suppose I have to implement this function `DaliProtoPriv * SerializeToProtobuf(DaliProtoPriv *arg)` for my class/struct. My code works fine running locally, but failed when loading to triton server: `Assert on "it != fn_map.end()" failed: Invalid argument "type" in protobuf`.
```
class VoxelnetPostProcessParams {
  public:
  float nms_iou = 0.f;
  std::vector<float> types_nms_iou_thresholds;

  VoxelnetPostProcessParams(){}
  VoxelnetPostProcessParams(float nms_iou_, std::vector<float> types_nms_iou_thresholds_)
  : nms_iou(nms_iou_), types_nms_iou_thresholds(types_nms_iou_thresholds_){}

  dali::DaliProtoPriv * SerializeToProtobuf(dali::DaliProtoPriv *arg) const {
    arg->set_type("VoxelnetPostProcessParams");
    arg->set_is_vector(false);

    auto nms_iou_arg = arg->add_extra_args();
    nms_iou_arg.set_name("nms_iou");
    dali::SerializeToProtobuf(nms_iou, &nms_iou_arg);

    auto types_nms_iou_thresholds_arg = arg->add_extra_args();
    types_nms_iou_thresholds_arg.set_name("types_nms_iou_thresholds");
    types_nms_iou_thresholds_arg.set_is_vector(true);
    for (size_t i = 0; i < types_nms_iou_thresholds.size(); ++i) {
      dali::SerializeToProtobuf(types_nms_iou_thresholds[i], &types_nms_iou_thresholds_arg);
    }

    return arg;
  }

  static VoxelnetPostProcessParams DeserializeFromProtobuf(const dali::DaliProtoPriv& arg) {
    return VoxelnetPostProcessParams(
      arg.extra_args(0).floats(0),
      arg.extra_args(1).floats()
    );
  }

  std::string ToString() const {
    // return "";
    std::string ret = "VoxelnetPostProcessParams {";
    ret += "nms_iou " + std::to_string(nms_iou) + ", ";
    ret += "types_nms_iou_thresholds [";
    for(int i = 0; i < types_nms_iou_thresholds.size(); i++){
      ret += std::to_string(types_nms_iou_thresholds[i]) + ", ";
    }
    ret += "], ";
    ret += "}";
    return ret;
  }
```

Is it possible to do so without recompiling DALI? An example would be really helpful!

**Comment by JanuszL** [comment]
Hi @leanrdchen00918,

Have you checked [this example](https://github.com/triton-inference-server/dali_backend/tree/main/docs/examples/dali_plugin)?
Does your plugin load successfully?

**Comment by leanrdchen00918** [comment]
If I pass the arguments separately, my plugin can be loaded successfully and everything else is fine~ But I can't find a way to wrap these arguments in a struct/class and pass a C++ object to my operator

**Comment by leanrdchen00918** [comment]
Plus, the example you mentioned is very helpful~ Unfortunately it does not cover my problem.

**Comment by JanuszL** [comment]
@leanrdchen00918,

Can you provide a standalone example that we can run on our own that would reproduce the problem you experience?

**Comment by leanrdchen00918** [comment]
@JanuszL 
Sure, thanks! Please see my demo in this [repo](git@github.com:leanrdchen00918/dali_triton.git): git@github.com:leanrdchen00918/dali_triton.git

**Comment by JanuszL** [comment]
Thank you for providing repro, when I run it I get:
```E0725 10:07:27.947752 1 model_repository_manager.cc:2063] Poll failed for model directory 'mydali': failed to open text file for read /models/mydali/config.pbtxt: No such file or directory```. Can you add missing files? (I guess they reside inside your private /home/yychen/Work/triton/test/dali_triton/model_repo/).

**Comment by leanrdchen00918** [comment]
Sorry for my mistake. It's fixed now.

**Comment by JanuszL** [comment]
After a more thorough analysis (I missed this initially, sorry) I see that the deserialization code was never designed to be extensible (please check [this](https://github.com/NVIDIA/DALI/blob/main/dali/pipeline/operator/argument.cc#L54), especially the function map that his hardcoded and it cannot be easily extended).
What you can do is serialize this structure as separate entries or post a PR that would make registration of custom deregistration methods possible.

**Comment by leanrdchen00918** [comment]
Got it, thanks! I'm closing this issue and will think about posting a PR~
