### ISSUE TITLE
Will dali.fn.encoders ever be implemented?

### ISSUE THREAD

**Issue by zeruniverse** [NVIDIA/DALI#4070]
I know DALI stands for data loading library, but encoders can be useful, especially in the Triton server use case. Some use cases include:

- I have a GAN model served by Triton which generates a new image. Currently I have to use Python backend (low efficiency) or encode array to JPEG in another machine (high bandwidth cost since I have to transfer entire image array). If DALI has nvJPEGEncoder, I can simply use the DALI backend to encode the resulting image.

- I want to apply such GAN model to a video. Now the result encoding will be even more difficult without some fast video encoders.

- I want to deploy some TTS model and directly serve encoded audios.

**Comment by mzient** [comment]
Hello @zeruniverse, thanks for reaching out to us.
There are no immediate plans for that. First, we need to remove the limitation that we can only move data from CPU to GPU and not the other way round. After this is removed, we might start thinking about encoders.

**Comment by zeruniverse** [comment]
I saw here GPU->CPU is on the feature list 3 years ago. Do you have a plan for this? https://github.com/NVIDIA/DALI/issues/1176#issuecomment-522501587

**Comment by JanuszL** [comment]
Hi @zeruniverse,

> I saw here GPU->CPU is on the feature list 3 years ago. Do you have a plan for this? https://github.com/NVIDIA/DALI/issues/1176#issuecomment-522501587

We are planning to redesign the execution model. But it is still in a very early stage and we can't provide any schedule yet.
