### ISSUE TITLE
pipe rebuild has a memory leak?

### ISSUE THREAD

**Issue by ronzhou18** [NVIDIA/DALI#4076]
If the wrong picture is encountered, the dali pipline will be unavailable, and the pipline needs to be rebuilt. At this time, the memory will continue to grow.

Is this a dali‘s’ bug?

**Comment by jantonguirao** [comment]
Hi @ronzhou18. To better answer this question, I would need a minimal reproduction example. If you could attach a small code snippet and perhaps an "image" file that would cause an error we could reproduce on our end and analyze what is happening with the memory. Thank you

**Comment by ronzhou18** [comment]
ok，thank you for your reply, I am preparing a minimal reproduction example.
In addition, I just use dali to do picture mixing decoding. Dali pipe will become invalid when DALI decoding one damaged image among many images. And then I rebuild this pipe. After many repetitions, system memory is getting bigger and bigger.

**Comment by jantonguirao** [comment]
I can imagine that the pipeline is not properly deleted for some reason. When you share the code we'll be able to check it and give a solution. Thanks

**Comment by ronzhou18** [comment]
```Python
import os
import gc
from tqdm import trange
import numpy as np
import nvidia.dali.fn as fn
import nvidia.dali.types as types
from nvidia.dali import pipeline_def

class GetIterTensor:
    def __init__(self, batch_size: int, tensor_list: list):
        self.batch_size = batch_size
        self.tensor_list = tensor_list

    def __iter__(self):
        self.len = len(self.tensor_list)
        self.index = 0
        return self

    def __next__(self):
        if self.index == 0:
            self.len = len(self.tensor_list)

        batch_size = self.len if self.len < self.batch_size else self.batch_size
        batch = self.tensor_list[self.index:batch_size + self.index]
        print(len(batch))

        self.index += batch_size
        self.len -= batch_size
        if self.len <= 0:
            self.index = 0
        return batch

@pipeline_def(batch_size=16,num_threads=4,device_id=0,prefetch_queue_depth=1)
def my_pipeline(source):
    jpegs = fn.external_source(source, device="cpu", name="DALI_INPUT_0", dtype=types.UINT8)
    images_ = fn.decoders.image(jpegs, output_type=types.RGB, device="mixed")
    raw_size = 640
    images = fn.resize(images_, resize_longer=raw_size)
    crop_image = fn.crop_mirror_normalize(images,
                                          crop_w=raw_size,
                                          crop_h=raw_size,
                                          crop_pos_x=0.5,
                                          crop_pos_y=0.5,
                                          scale=1 / 255.0,
                                          dtype=types.FLOAT,
                                          fill_values=0,
                                          out_of_bounds_policy="pad",
                                          output_layout="CHW")
    return crop_image

def build(iter_func):
    my_pipe = my_pipeline(source=iter_func)
    my_pipe.build()
    return my_pipe

if __name__ == "__main__":
    path = "test_img_error"
    images = [os.path.join(path, image) for image in os.listdir(path)]
    batch_size = 16
    tensor_list = []
    get_data = GetIterTensor(batch_size=16, tensor_list=tensor_list)
    pipe = build(get_data)

    while True:
        for batch_id in trange(int(len(images)/batch_size)):
            batch = images[batch_id*batch_size:(batch_id+1)*batch_size]
            for img in batch:
                tensor_list.append(np.fromfile(img, dtype=np.uint8))

            try:
                pipe.run()
                tensor_list.clear()
            except Exception as e:
                tensor_list.clear()
                del pipe
                gc.collect()
                pipe = build(get_data)


```

image set:https://pan.baidu.com/s/1j8Jcbo6Gl3K-aRXc29foaw  password:lm5p 

Thanks

**Comment by jantonguirao** [comment]
I've tried your snippet, and I can see the memory utilization stabilizing. I measured with 
```
# Importing the library
import psutil
  
# Getting % usage of virtual_memory ( 3rd field)
print('RAM memory % used:', psutil.virtual_memory()[2])
```
On every `pipe.run()`.

**Comment by ronzhou18** [comment]
ok，this reproduction method may not increase when the memory increases to a certain extent.But if I run with a large number of pictures, I will find that it has been rising and has not stabilized(Increased to 7.5GB in an hour). I don't understand why.I'll try other ways to create data to simulate it.

In addition, I want to ask why I don't add the wrong pictures, the host memory occupies 1.2GB. But like the previous code snippet, after adding the wrong picture data, due to the "build" method, the host memory occupies about 2GB to 3GB. The modified code is as follows:
```Python
if __name__ == "__main__":

    times = 10
    encodeds = []
    encoded = [create_fake_img() for i in range(8)]
    # images = [os.path.join(path, image) for image in os.listdir(path)]
    # batch_size = 1
    tensor_list = []
    get_data = GetIterTensor(batch_size=16, tensor_list=tensor_list)
    pipe = build(get_data)

    index = 0
    while True:
        images = encoded*2
        for img in images:
            tensor_list.append(img)

        try:
            pipe.run()
            tensor_list.clear()
            print("succ")
        except Exception as e:
            print(e)
            tensor_list.clear()
            del pipe
            gc.collect()
            pipe = build(get_data)
        index += 1
        if index == times:
            index = 0

			
```

Test environment: 
    cuda: 11.6
    dali:   1.16
    gpu:   2080ti

**Comment by jantonguirao** [comment]
I can confirm that the memory consumption is higher when we use the corrupted images. We will investigate why

**Comment by mzient** [comment]
I can confirm that there's a leak when rebuilding a pipeline which contains a `mixed` image decoder. We're working on a fix.

**Comment by ronzhou18** [comment]
@mzient ok，thank you very much!

**Comment by mzient** [comment]
I wrote a C++ equivalent of the test program to exclude any leaks in Python and ran it through valgrind. It shoes exactly the same state of the heap after 10 and 100 iterations - down to a single byte.
Even the python program sees very little difference in heap usage.
Interestingly, the working set (or "resident" memory, in Linux terms) increases slightly over time, but it's still well below the system's RAM capacity. At present, I have no evidence to attribute this behavior to anything other than internal operation of the heap.

**Comment by mzient** [comment]
@ronzhou18 Did you experience any low-memory condition due to the effect, or is it just an observation of an otherwise healthy program?
Also, I think the link you provided at the beginning of this issue no longer works (it's hard to tell, I don't read Chinese). I'd like to have a more realistic reproduction, because the values you reported for your dataset are much larger than anything we've observed. In order to confirm that the issue really exists, I'd need a reproduction that's closer to your original problem than the one with artificial dataset, on which we've been testing - and also, it'd have to happen regardless of memory consumption in the system.

**Comment by ronzhou18** [comment]
I uploaded some pictures with problems to Google online disk. You can try them.

**Comment by KrisChou** [comment]
@mzient In both mixed mode or cpu mode, the dataset in the above link will continue to cause memory leaks when we run the program in a loop.

**Comment by KrisChou** [comment]
@mzient Hi, according to my observation, the API cv2.imdecode makes the leak, especially when dealing with corrupted images

**Comment by jantonguirao** [comment]
@ronzhou18 @KrisChou I can confirm a memory leak with the dataset provided. I will publish a fix soon.

**Comment by stiepan** [comment]
Hi @ronzhou18,

DALI  [v1.16.1](https://github.com/NVIDIA/DALI/releases/tag/v1.16.1) with the fix for the reported issue has been released.
