### ISSUE TITLE
Data augmentation rotation and gaussian noise

### ISSUE THREAD

**Issue by shrutishrestha** [NVIDIA/DALI#4079]
Hi, I did the following code for applying augmentation to my dataset
```
images = fn.decoders.image(jpegs, device="mixed", output_type=types.GRAY)
images = fn.transforms.rotation(images, angle=45)
```
But, it gives error of
Assert on "creator_it != registry_.end()" failed: Operator "transforms__Rotation" not registered for gpu.

Is rotation not supported in gpu? If so, what is the benefit of using pytorch rotation transformations vs Nvidia Dali rotation transformation?

Also, when I tried to used gaussian noise I got:
RuntimeError: [/opt/dali/dali/pipeline/pipeline.cc:290] Assert on "input_device == "cpu"" failed: cpu/mixed ops can only take cpu inputs. CPU op cannot follow GPU op. (op: 'GaussianBlur', input: '__Contrast_6')

**Comment by jantonguirao** [comment]
Hi @shrutishrestha. `fn.transforms.*` operators are operators that generate a transformation matrix to be used together with `fn.warp_affine` or `fn.coord_transform`. You can see how they are meant to be used in this tutorial: https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/math/geometric_transforms.html

I understand that you want to rotate your images. For this, you should use `fn.rotate`: https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.rotate.html#nvidia.dali.fn.rotate

**Comment by shrutishrestha** [comment]
Using the fn.warp_affin solved the issue. Thanks @jantonguirao
