### ISSUE TITLE
Assert on "this->IsDenseTensor()" failed

### ISSUE THREAD

**Issue by shrutishrestha** [NVIDIA/DALI#4080]
Hi I am reading the image in grayscale i.e. one channel, here is my code:
```
class ExternalInputGpuIterator(object):

    def __init__(self, batch_size, images_dir, filename, device_id, num_gpus):
        self.images_dir = images_dir
        self.batch_size = batch_size

        with open(filename, 'r') as f:
            self.files = [line.rstrip() for line in f if line != '']
        shuffle(self.files)
        
        # whole data set size
        self.data_set_len = len(self.files)
        # based on the device_id and total number of GPUs - world size
        # get proper shard
        self.files = self.files[self.data_set_len * device_id // num_gpus:
                                self.data_set_len * (device_id + 1) // num_gpus]
        self.n = len(self.files)

    def __iter__(self):
        self.i = 0
        shuffle(self.files)
        return self

    def __next__(self):
        images = []
        labels = []

        if self.i >= self.n:
            self.__iter__()
            raise StopIteration

        for _ in range(self.batch_size):
            jpeg_filename, label = self.files[self.i % self.n].split(',')
            images.append(np.fromfile(self.images_dir + jpeg_filename, dtype = np.uint8))  # we can use numpy
            labels.append(torch.tensor([int(label)], dtype = torch.float16)) # or PyTorch's native tensors
            
            self.i += 1
        return (images, labels)

    def __len__(self):
        return self.data_set_len

    next = __next__
```

```
train_eii = ExternalInputGpuIterator(args["train_batch_size"], args["train_dir"], args["train_file"], device_id=0, num_gpus=2)

pipe_train_gpu = Pipeline(batch_size=args["train_batch_size"], num_threads=1, device_id=0)
        
with pipe_train_gpu:
    jpegs, labels = fn.external_source(source=train_eii, num_outputs=args["dataloader_output"], dtype=[types.UINT8,types.FLOAT16])
    images = fn.decoders.image(jpegs, device="mixed", output_type=types.GRAY)
    pipe_train_gpu.set_outputs(images, labels)
    
pipe_train_gpu.build()

```
This is giving a runtime error:

Traceback (most recent call last):
  File "cancer_classification_dali.py", line 361, in <module>
    main(args)
  File "cancer_classification_dali.py", line 204, in main
    dali_train_iter = DALIGenericIterator([pipe_train_gpu], ['image', 'label']) #loads data once 
  File "/userapp/virtualenv/SR_ENV/venv/lib/python3.7/site-packages/nvidia/dali/plugin/pytorch.py", line 174, in __init__
    self._first_batch = DALIGenericIterator.__next__(self)
  File "/userapp/virtualenv/SR_ENV/venv/lib/python3.7/site-packages/nvidia/dali/plugin/pytorch.py", line 200, in __next__
    category_tensors[category] = out.as_tensor()
RuntimeError: [/opt/dali/dali/pipeline/data/tensor_list.h:567] Assert on "this->IsDenseTensor()" failed: All tensors in the input TensorList must have the same shape and be densely packed.

**Comment by prak-nv** [comment]
Could you please let me know what version of DALI are you using?

**Comment by shrutishrestha** [comment]
Hi @prak-nv thanks for replying. 
My dali version is: nvidia-dali-cuda110==1.14.0

**Comment by mzient** [comment]
I think the problem is not with DALI, but with PyTorch iterator - it doesn't support jagged batches (different shapes for tensors in the batch). I guess you'll need to pad the batch or resize the images to a particular size - or perhaps use a different method of supplying data to PyTorch than the iterator (but I'm not sure PyTorch can work with such data).

**Comment by keshavvinayak01** [comment]
Is support for jagged batches still not added for the DALI Pytorch Iterator? Is there any alternative Iterator I can use?

**Comment by JanuszL** [comment]
Hi @keshavvinayak01,

Could you tell us what behavior would expect in such a case? Should  DALI return a list of PyTorch tensors?
In the case of the PyTorch DataLoader uniformity is also expected to perform collation.
