### ISSUE TITLE
default_cuda_stream_priority 

### ISSUE THREAD

**Issue by tendar** [NVIDIA/DALI#4085]
Hi， 
I have know that DALI pipeline's param default_cuda_stream_priority is the cudaStream priority, and its convention is lower number represent higher priorities.
Could you please show me the scheduling strategy of stream priority?
If I have two cudaStream, the first stream priority is 2 , the second stream priority is 3. Both of these two stream has many tasks to do. So will tasks in second stream begin to be done, only when all the task in the first stream have been done? Or cuda will distribute time slice according to a ratio?

**Comment by JanuszL** [comment]
Hi, @tendar,

I think the best source of truth is just [the CUDA documentation ](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__STREAM.html#group__CUDART__STREAM_1ge2be9e9858849bf62ba4a8b66d1c3540). DALI just uses CUDA API to set the priority and it is up to the runtime and the driver to act accordingly.

**Comment by tendar** [comment]
Hi, @JanuszL 

I have read cuda doc, but  it does't explain the strategy of stream priority.
OK, thank you anyway.

**Comment by JanuszL** [comment]
I think the only guarantee the CUDA provides is `Work in a higher priority stream may preempt work already executing in a low priority stream.`. The rest is up to CUDA, driver, and HW internal implementation which can change.
