### ISSUE TITLE
Multiprocessing and dali_tf

### ISSUE THREAD

**Issue by cooperlab** [NVIDIA/DALI#4091]
Can multiprocessing accelerate `tf.data.Dataset` generated from an external source using `DaliDatasetWithInputs`?

I am writing a course module to teach students DALI and the concepts of i/o or compute bound workflows. I have an external source and pipeline that exhibit speedup when using `Pipeline.run` with multiprocessing but not when running as a tf.data.Dataset after conversion with `dali_tf`. 

This external source has a programmable delay to simulate i/o and preprocessing time, and returns a random array of "images". A trivial keras model calculates an average is timed using model.predict(dataset). I have generated `dataset` objects from Pipelines with a variable number of `py_num_workers`.

The step time that tf displays is consistent with the programmed delay (100ms) indicating that the model/inference overhead is very low. I do not see any speedup though when adding workers.

1 worker:
50/50 [==============================] - 6s 105ms/step
Observed throughput 8.953119748241322 (samples/sec), ideal 10.0 (samples/sec).
2 workers:
50/50 [==============================] - 5s 105ms/step
Observed throughput 9.049385046726956 (samples/sec), ideal 20.0 (samples/sec).

I confirmed that only a single process is being used by modifying the external source to return the output of `os.get_pid()`.

Here is a MWE:

````
import numpy as np
from nvidia.dali import pipeline_def
import nvidia.dali.fn as fn
import nvidia.dali.plugin.tf as dali_tf
import tensorflow as tf
import time

n = 50 # number of samples
io_delay = 0.1 # 100ms of io and preprocessing per sample
workers = [1, 2, 4]

class IoBoundModel(tf.keras.Model):
    def call(self, inputs, *args, **kwargs):
        return tf.reduce_sum(tf.reshape(inputs, [-1]))
    
tiles = """
import os
import numpy as np
import time

class TileSource(object):
    def __init__(self, n, io_delay, batches, size):
        self.n = n
        self.io_delay = io_delay
        self.batches = batches
        self.size = size

    def __call__(self, sample_info):
        sample_idx = sample_info.idx_in_epoch
        if sample_info.iteration >= self.n:
            raise StopIteration()
        time.sleep(self.io_delay)
        tiles = np.random.uniform(-1., 1., (self.batches, *self.size))
        return tiles.astype(np.float32)
"""
with open("./tiles.py", 'w') as f:
    f.write(tiles)
from tiles import TileSource

@pipeline_def(batch_size=1, num_threads=1, device_id=0, py_start_method='spawn')
def mp_tile_pipe(n, io_delay, prefetch, batches=1, size=(224, 224, 3), device='gpu'):
    sample = fn.external_source(source=TileSource(n=n,
                                                  io_delay=io_delay,
                                                  batches=batches,
                                                  size=size),
                                batch=False,
                                parallel=True,
                                prefetch_queue_depth=prefetch)
    if device == 'gpu':
        sample = sample.gpu()
    return sample
    
pipes = [mp_tile_pipe(n, io_delay, py_num_workers=w, prefetch=2*w, device='gpu') for w in workers]

with tf.device('/gpu:0'):
    io_bound = IoBoundModel()

multiprocessing_elapsed = []
for w, pipe in zip(workers, pipes):
    with tf.device('/gpu:0'):
        dataset = dali_tf.experimental.DALIDatasetWithInputs(
            pipeline=pipe,
            batch_size=1,
            output_shapes=None,
            output_dtypes=tf.float32,
            device_id=0)

    start = time.time()
    output = io_bound.predict(dataset, steps=n)
    elapsed = time.time()-start
    multiprocessing_elapsed.append(elapsed)
    
    ideal = w / io_delay
    print(f'Observed throughput {n / elapsed} (samples/sec), ideal {ideal} (samples/sec).')
````

I am sorry if I have overlooked something in the documentation. I see that `DaliDatasetWithInputs` converts external sources to tf generators so maybe this cannot benefit from multiprocessing.

**Comment by klecki** [comment]
Hi @cooperlab,
unfortunately, this is indeed the limitation in the TF - DALI is no longer parallelizing the execution of the Python callbacks, but we  wrap them into `tf.data.Dataset.from_generator` datasets (and effectively: https://www.tensorflow.org/api_docs/python/tf/numpy_function), delegating them to be run by TensorFlow. This is necessary to allow DALI to be run as a part of TF graph - unfortunately we need to hand off the control over some parts of the execution.

This indeed means that the `parallel` and related options are not supported by the DALI TF Dataset. I am sorry for the confusion, we will improve our documentation in that area.

I don't know if that would be of any help - but maybe it would be possible to use multiprocessing directly within the callback that is passed to External Source and later to TensorFlow? I don't know how happy the TF would be about it though.

**Comment by cooperlab** [comment]
Thank you, @klecki. I will investigate and update the issue if I find something interesting.
