### ISSUE TITLE
num_shards_ issue with WebDataset

### ISSUE THREAD

**Issue by Data-drone** [NVIDIA/DALI#4093]
I am trying to read a `tar` file with the webdataset reader.

the pipeline is:

```
@pipeline_def(batch_size=batch_size, num_threads=4, device_id=0)
def wds_pipeline(wds_data=wds_data):
    img_raw = fn.readers.webdataset(
        paths=wds_data,
        ext=["jpeg"],
        num_shards=1,
        missing_component_behavior="skip")
    img = fn.decoders.image(img_raw, device="mixed", output_type=types.RGB)
    resized = fn.resize(img, device="gpu", resize_shorter=256.)
    return resized
```

When I run:
```
pipe = wds_pipeline()
pipe.build()
pipe_out = pipe.run()

```

I get: 

```
Error when constructing operator: readers__Webdataset encountered:
[/opt/dali/dali/operators/reader/loader/loader.h:223] Assert on "num_shards_  > (dali::OpSpec const&), std::unique_ptr > (*)(dali::OpSpec const&)>::_M_invoke(std::_Any_data const&, dali::OpSpec const&)+0xc) [0x7fefc799760c]
```

How can I debug this?

**Comment by JanuszL** [comment]
Hi @Data-drone,

What data source do you use? Have you tried one from DALI_extra used in [this example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/dataloading_webdataset.html)?

**Comment by Data-drone** [comment]
@JanuszL the default worked so is there something wrong with the way I made my tar?

How can I diagnose?

**Comment by JanuszL** [comment]
Hi,
I would double check [the webdataset documentation](https://webdataset.github.io/webdataset/gettingstarted/) and see if that helps.
Please also share the way you applied, maybe there is a small error in the command you use.

**Comment by Data-drone** [comment]
Okay I explored my tar file more and the data has extension JPEG not jpeg and that caused the issue.
Guessing the shard error was a red herring and the problem was that `jpeg` filter returned no data and hence there was nothing to shard?

**Comment by JanuszL** [comment]
> Guessing the shard error was a red herring and the problem was that jpeg filter returned no data and hence there was nothing to shard?

You are right. This is the source of the problem.
