### ISSUE TITLE
Frame appeared twice

### ISSUE THREAD

**Issue by masterwu2115** [NVIDIA/DALI#4095]
Following the [use case](https://github.com/NVIDIA/DALI/blob/ce25d722bc47b8b4f3633ef008a85535db305789/docs/examples/use_cases/video_superres/dataloading/dataloaders.py) of video super resolution provided by the official documentation, I didn't modify any parameters, however, the log is frequently showing something like '/opt/dali/dali/operators/reader/loader/video_loader.cc:619: Frame 57 appeared twice', I'm confused about why this happened? How can I solve this #trouble? btw the version of dali which I used is 1.15.0.

**Comment by JanuszL** [comment]
Hi @masterwu2115,

You can disregard this warning. This https://github.com/NVIDIA/DALI/pull/4092 is supposed to remove this warning.
