### ISSUE TITLE
how to generate an unique value list which has random order using DALI?

### ISSUE THREAD

**Issue by mayujie** [NVIDIA/DALI#4101]
```
>>> ss = np.random.permutation(3)
>>> ss
array([2, 1, 0])

>>> ss = list(range(3))
>>> ss
[0, 1, 2]
>>> np.random.shuffle(ss)
>>> ss
[2, 1, 0]
```
I would like to use DALI to generate a random unique list for each batch, for implementing RGB channel permutation augmentation (each batch randomly switches the image channel order).
But could find a way to do the above implementation using DALI

**Comment by mzient** [comment]
Hello @mayujie, thanks for reaching out to us.
Currently DALI doesn't have an operator that would give you a permutation - however, for RGB the number of permutations is small enough that you can just look them up:
```Python
permutations = dali.types.Constant(np.array([
  [0, 1, 2],
  [0, 2, 1],
  [1, 0, 2],
  [1, 2, 0],
  [2, 0, 1],
  [2, 1, 0]], dtype=np.int32)
perm = dali.fn.random.uniform(range=(0, 6), dtype=np.int32))
channel_indices = permutations[perm]

c0 = image[:,:,channel_indices[0]]
c1 = image[:,:,channel_indices[1]]
c2 = image[:,:,channel_indices[2]]

fn.stack(c0, c1, c2, axis=2)
```

**Comment by mayujie** [comment]
> Hello @mayujie, thanks for reaching out to us. Currently DALI doesn't have an operator that would give you a permutation - however, for RGB the number of permutations is small enough that you can just look them up:
> 
> ```python
> permutations = dali.types.Constant(np.array([
>   [0, 1, 2],
>   [0, 2, 1],
>   [1, 0, 2],
>   [1, 2, 0],
>   [2, 0, 1],
>   [2, 1, 0]], dtype=np.int32)
> perm = dali.fn.random.uniform(range=(0, 6), dtype=np.int32))
> channel_indices = permutations[perm]
> 
> c0 = image[:,:,channel_indices[0]]
> c1 = image[:,:,channel_indices[1]]
> c2 = image[:,:,channel_indices[2]]
> 
> channels_swapped = dali.fn.stack(c0, c1, c2, axis=2)
> ```

```
        self.probability = probability
        self.num_image_channels = num_image_channels
        self.channel_orders_pool = [
            ch for ch in permutations(list(range(self.num_image_channels)), self.num_image_channels)
        ]
        self.channel_permutation_pool = None
        self.permutation = None

    def augment(self, feature):
        print(self.permutation)
        channel_indices = self.channel_permutation_pool[self.permutation]
        input_1st_channel = feature[0][:, :, channel_indices[0]]
        input_2nd_channel = feature[0][:, :, channel_indices[1]]
        input_3rd_channel = feature[0][:, :, channel_indices[2]]

        gt_1st_channel = feature[1][:, :, channel_indices[0]]
        gt_2nd_channel = feature[1][:, :, channel_indices[1]]
        gt_3rd_channel = feature[1][:, :, channel_indices[2]]
        input_image = self.op(input_1st_channel, input_2nd_channel, input_3rd_channel, axis=2)
        gt_image = self.op(gt_1st_channel, gt_2nd_channel, gt_3rd_channel, axis=2)
        return input_image, gt_image

    def define_op(self, device, **kwargs):
        self.channel_permutation_pool = types.Constant(np.array(self.channel_orders_pool), dtype=types.INT32)
        self.permutation = ops.Uniform(values=list(range(len(self.channel_orders_pool))), dtype=types.INT32)()
        self.op = ops.Stack(device=device)
```
@mzient 
Thank you michal, i had similar idea, but i used `dali_fn.constatnt` and it was not working. change to `types.Constant` it works.
That's really helped me.
Milego dnia. :)

**Comment by mzient** [comment]
`fn.constant` is an internal (and, I think, undocumented) operator. `types.Constant` is the proper front-end for it.
