### ISSUE TITLE
Is there a better way Using DALI to create an random vector then Repeats vector along the specified dimensions as an tensor?

### ISSUE THREAD

**Issue by mayujie** [NVIDIA/DALI#4110]
I'm implementing Blend augmentation, which creates a (1, 1, 3) vector with random values for 3 channels, then repeat the (1, 1, 3) for the H, W from the image. 
```
self.blend_constant_vector = ops.Uniform(range=(self.min_blend_value, self.max_blend_value), shape=self.image_channels, dtype=types.FLOAT)()
```
Is there a better way to reproduce this pytorch implementation in DALI?
```
c = torch.empty((img.size(0), 1, 1)).uniform_(0, 255)
rim1 = c.repeat((1, img.size(1), img.size(2)))
```
Current my idea is to create three individual values. Then for each random value Using another ops.uniform to create tensor with shape H W, finally stack them together. But this is not best way i think

**Comment by mzient** [comment]
What exactly are you trying to achieve? Have three independent blend factors for channels? If so, then:
```Python
factors = fn.random.uniform(range=(0, 1), shape=[3])
img_a, img_b = ... # your images

channels = [img_a[:,:c] * (1-factors[c]) + img_b[:,:,0] * (1 - factors[c]) for c in range(3)]
out = fn.stack(channels)
```

**Comment by mayujie** [comment]
Yes, to have three independent blend factors for channels.
I'm using one Uniform to get the vector with value for each channel, then another unifrom which takes value with specified output shape and finally stack them. seems this is the only way.
```
    def augment(self, feature):
        self.blend_matrix = self.op(*self.blend_matrix, axis=2)
        blend_image = self.alpha * feature[0] + (1 - self.alpha) * self.blend_matrix
        return blend_image

    def define_op(self, device, **kwargs):
        self.blend_constant_vector = [ops.Uniform(range=(self.min_blend_value, self.max_blend_value), shape=1, dtype=types.FLOAT)() for i in range(self.image_channels)]
        self.blend_matrix = [ops.Uniform(values=self.blend_constant_vector[ch], shape=[self.image_h, self.image_w], dtype=types.FLOAT)() for ch in range(self.image_channels)]
        self.op = ops.Stack(device=device)
```

Thank you

**Comment by mzient** [comment]
@mayujie Is there anything else you need help with or can we close the issue?

**Comment by mayujie** [comment]
> @mayujie Is there anything else you need help with or can we close the issue?

Hello, thank you very much. I think you can close this issue.
Dziekuje za pomoc :D
