### ISSUE TITLE
How to set the address of data on cuda?

### ISSUE THREAD

**Issue by 980202006** [NVIDIA/DALI#4113]
I have a batch of videos that need to be read to cuda, but only one video is read at a time, if I create a pipeline of video and bind it to tensorRT, how can I get the cuda address of the output location of this piepline, and use it to create the pipeline of the second video, or can i modify the video path of one pipeline?

**Comment by JanuszL** [comment]
Hi @980202006,

DALI GPU pipeline returns TensorListGPU, each Tensor has [`data_ptr`](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/data_types.html#nvidia.dali.backend.TensorCPU.data_ptr) property with the address, if that is what you are asking for.

> can i modify the video path of one pipeline

I'm sorry but it is not supported yet.

**Comment by 980202006** [comment]
Thank you for your prompt reply.
When I print the address of the output on cuda, I find that the odd-numbered batch and the even-numbered batch are not at the same address. Is it possible to fix the cuda address of all outputs?
The following is part of the code.

```
      video = fn.readers.video(device="gpu", filenames=filenames, sequence_length=sequence_length,
                              normalized=True,random_shuffle=False,dtype=types.DALIDataType.FLOAT,
                              initial_fill=initial_prefetch_size)
    def __getitem__(self):
        pipe_out = self.pipe.run()
        return pipe_out
    for i in range(dali_pipe.get_epoch_size(dali_pipe.pipe)):
        output = dali_pipe.__getitem__()
        # img = Image.fromarray((np.array(output[0][0].as_cpu())[0]*255).astype(np.uint8))
        print(output[0][0].data_ptr())
```

4404686094336
4401366302720
4404686094336
4401366302720
4404686094336
4401366302720
4404686094336

**Comment by 980202006** [comment]
If I create another pipeline, how do I pass the address obtained by data_ptr() to the pipeline？

**Comment by JanuszL** [comment]
If you want to keep the address buffer the same please reduce the `prefetch_queue_depth` to 1. Please keep in mind that if the output size changes the memory will be reallocated and the address will change.

> If I create another pipeline, how do I pass the address obtained by data_ptr() to the pipeline？

In this case, you can use [the `external source` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.external_source.html#nvidia.dali.fn.external_source) and pass the output from the first pipeline directly there, like in https://github.com/NVIDIA/DALI/issues/3702.

**Comment by 980202006** [comment]
Thanks, I will try.Thank you for your prompt reply.

**Comment by 980202006** [comment]
Sorry to reopen this issue, if you want to reuse the first pipeline, that is, the address of the second pipeline and the first pipeline data output to cuda is the same, these two pipelines are fn.reader.video, but the file path is different Same, how should I create the second pipeline?

**Comment by JanuszL** [comment]
If I understand the question correctly, if you want to change the video file path you need to recreate the pipeline and the output buffer address is likely to change.
