### ISSUE TITLE
Is it possible to write the frames data in cuda to the video file without using numpy and as_cpu?

### ISSUE THREAD

**Issue by 980202006** [NVIDIA/DALI#4119]
I want to further reduce the time-consuming of the model. Is there a video writing function of dali that can quickly write data into the video file?

**Comment by JanuszL** [comment]
Hi @980202006,

I'm sorry but DALI doesn't support encoding (not images, nor video). What you can try out if [VPF](https://developer.nvidia.com/blog/vpf-hardware-accelerated-video-processing-framework-in-python/) and use it to process DALI output.
