### ISSUE TITLE
Pipeline cannot return duplicate tensors

### ISSUE THREAD

**Issue by addisonklinke** [NVIDIA/DALI#412]
I would like to be able to create a pipeline that returns multiple copies of the _same exact_ tensor, but DALI does not allow this. Please see my minimal example at the end of this post to reproduce the error `RuntimeError: [/opt/dali/dali/pipeline/op_graph.cc:189] Assert on "ret.second" failed: Operator 'MakeContiguous' has output with name contiguous_ExternalSource_id_1_output_0_cpu, but output with this name already exists as output of op 'MakeContiguous'`. I interpret the error message to mean the pipeline has already output the values of this tensor under a given name, and therefore I cannot create a duplicate.

An example use case is augmenting images with bounding boxes. Some augmentations that only change pixel values (i.e. contrast, hue, saturation, etc.) do not affect the bounding box. Therefore, augmentations in those categories will all have identical bounding boxes. On the other hands, augmentations like rotation, crop, etc. _do_ require adjusting the bounding boxes. When a combination of augmentations from the two categories are used, there are two options for organizing the pipeline's output:

**Option 1:** no duplicates of `original_bbox`
```
    pipe_out = [
        'original_image',
        'contrast_augmentation',
        'hue_augmentation',
        'saturation_augmentation',
        'rotation_augmentation',
        'crop_augmentation',
        'original_bbox',
        'rotated_bbox',
        'cropped_bbox'
    ]
```

**Option 2:** duplicate `original_bbox` (not allowed by DALI)
```
    pipe_out = [
        'original_image',
        'contrast_augmentation',
        'hue_augmentation',
        'saturation_augmentation',
        'rotation_augmentation',
        'crop_augmentation',
        'original_bbox',
        'original_bbox',
        'original_bbox',
        'original_bbox',
        'rotated_bbox',
        'cropped_bbox'
    ]
```

I find Option 2 much easier to deal with for plotting the augmentations or feeding pairs of (image, bbox) to a model during training. The reason being, the `pipe_out` list is equally split into images and bounding box sections (i.e. 6 images followed by 6 bounding boxes instead of 6 images followed by 3 bounding boxes). With Option 2's format, you can process the output as

```
n_imgs = int(len(pipe_out) / 2)
imgs = pipe_out[:n_imgs]
bboxes = pipe_out[n_imgs:]
model_inputs = [(i, b) for i, b in zip(imgs, bboxes)]
print(model_inputs)
```

Compared to Option 1 where you have to determine manually which bounding box is supposed to be paired with which crop (since there are fewer bounding boxes than augmentations in `pipe_out`). This is further complicated by the fact that the ratio of bounding boxes to augmentations for Option 1 changes depending on how many augmentations are pixel-value vs. global transformations.

**Reproducible Example**
```
import numpy as np
import nvidia.dali.ops as ops
from nvidia.dali.pipeline import Pipeline

class ExternalInputIterator():
    """Dummy iterator that returns random NumPy arrays."""
    def __init__(self, batch_size):
        self.batch_size = batch_size

    def __iter__(self):
        self.i = 0
        self.n = 10
        return self

    def __next__(self):
        batch = []
        if self.i < self.n:
            for _ in range(self.batch_size):
                batch.append(np.random.rand(3))
                self.i += 1
            return batch
        else:
            raise StopIteration

    next = __next__

class RepetitivePipeline(Pipeline):
    """Pipeline to receive output from ExternalInputIterator and optionally
    duplicate it if `cause_error=True`."""
    def __init__(self, batch_size, num_threads, device_id, cause_error=True):
        super(RepetitivePipeline, self).__init__(batch_size, num_threads, device_id, seed=12)
        self.input = ops.ExternalSource()
        self.iterator = iter(ExternalInputIterator(batch_size))
        self.cause_error = cause_error

    def define_graph(self):
        self.batch = self.input()
        if self.cause_error:
            output = [self.batch for _ in range(10)]
        else:
            output = self.batch
        return output

    def iter_setup(self):
        batch = self.iterator.next()
        self.feed_input(self.batch, batch)

if __name__ == '__main__':

    # Don't create duplicate tensors in the pipeline --> no error
    pipe = RepetitivePipeline(
        batch_size=5,
        num_threads=1,
        device_id=0,
        cause_error=False)
    pipe.build()
    pipe_out = pipe.run()

    # Create duplicate tensors in pipeline --> error building pipe
    pipe = RepetitivePipeline(
        batch_size=5,
        num_threads=1,
        device_id=0,
        cause_error=True)
    pipe.build()  # error occurs here
    pipe_out = pipe.run()
```

**Comment by JanuszL** [comment]
I think https://github.com/NVIDIA/DALI/pull/405 should fix that. @jantonguirao could you check this?

**Comment by addisonklinke** [comment]
That PR looks promising. Is there an estimate for when the build will be available at https://developer.download.nvidia.com/compute/redist/nvidia-dali/?

**Comment by JanuszL** [comment]
We are trying to keep monthly release cadence but cannot promise exact date.

**Comment by JanuszL** [comment]
Mhh, we checked deeper your description and #405  won't fix that.

**Comment by addisonklinke** [comment]
@JanuszL Is there another approach that would allow that functionality then?

**Comment by jantonguirao** [comment]
@addisonklinke Allowing duplicate outputs is not that simple with current design and will require us to do a deeper analysis. It shall be addressed in the future.

As a temporary solution, you could use the Copy operator to generate the duplicates:

Add to your pipeline's constructor:
`self.copy = ops.Copy()` 

then use it in your graph definition:
`output = [self.copy(self.batch) for _ in range(10)]`

**Comment by addisonklinke** [comment]
`ops.Copy()` does the trick

**Comment by JanuszL** [comment]
@addisonklinke https://github.com/NVIDIA/DALI/pull/1556 should address your case
