### ISSUE TITLE
How to directly convert dali's tensor to torch's tensor without copying?

### ISSUE THREAD

**Issue by 980202006** [NVIDIA/DALI#4126]
Can I directly use the address of the dali data to create the tensor of the torch?Which is the fastest way to convert dali data to torch tensor (cuda)?

**Comment by JanuszL** [comment]
Hi @980202006,

What you can do is:
```
import cupy as cp
o = pipe_out[0].as_tensor()
cp_o = cp.asarray(o)
a = torch.tensor(cp_o)
```
For now, we need to go through a CuPy array as the DALI tensor is set as a read-only, and Torch doesn't accept it. CuPy removes the read-only flag from the cuda_array_interface. Still, the memory is passed without any copy. Please keep in mind that when you issue `pipe.run()` again the data would be overwritten by the next DALI iteration result.

**Comment by 980202006** [comment]
Thank You!
