### ISSUE TITLE
Does the brightness operator support absolute values?

### ISSUE THREAD

**Issue by Hughen** [NVIDIA/DALI#4132]
The current brightness operator formula is as follows:
```txt
out = brightness_shift * output_range + brightness * in
```
There will be a problem in this way. `brightness` is a ratio value. If the original image is very bright, it will lead to overexposure.
Can the brightness operator provide an absolute value operation, such as:
```txt
out = brightness + in
```

**Comment by klecki** [comment]
Hi @Hughen,
here is the documentation for the supported mathematical operations: https://docs.nvidia.com/deeplearning/dali/main-user-guide/docs/math.html

Note that what @JanuszL showed will give you int32 as a result (due to the type promotions).

**Comment by Hughen** [comment]
@JanuszL @klecki 
That's great. Thanks a lot.
