### ISSUE TITLE
TensorListCPU allocating GPU as well

### ISSUE THREAD

**Issue by fversaci** [NVIDIA/DALI#4158]
Hi,
I'm trying to allocate a TensorList in the host memory using the following code:

```python
from nvidia import dali
import numpy as np

n_ar = np.empty([2,3])
d_ten = dali.tensors.TensorCPU(n_ar)
d_tl = dali.tensors.TensorListCPU([d_ten])
```
However, when the `TensorListCPU` is created, GPU 0 is also used (with 151 MB allocated).
Is there a way to avoid the GPU allocation (or, at least, to choose which GPU is used)?

Note: `dali.__version__ == '1.17.0dev.20220810'`

Thanks!

**Comment by fversaci** [comment]
Could it be that the TensorList is created in pinned memory by default?
`tens_vect.set_pinned(false)` in C++ seems to solve the issue...

**Comment by fversaci** [comment]
To sharpen the question a bit:

- Is there a way (both in C++ and Python) to set the default GPU used by the pinning?
- Is there a way, in Python, to create a `TensorListCPU` which is not in pinned memory?

**Comment by szalpal** [comment]
Hi @fversaci !

My apologies for the late response.

It's true, our documentation is not perfect in this manner. The reason why DALI uses pinned memory is that we can allocate it once and then reuse allocated part (optionally reallocating to fit larger buffer if necessary). And pinned memory saves us from one additional copy every iteration when CPU->GPU transfer occurs in the pipeline. In CUDA, whenever the copy from non-pinned CPU memory occurs, the buffer is first copied into pinned memory anyhow. Therefore it's hard to find a good reason not to use the pinned memory.

So answering your two questions:
1. I'm afraid no, CUDA always uses GPU0 for allocating page-locked memory
2. As I explained above, there aren't many reasons to do it, so we do not expose this option.


IIUC, this additional portion of memory is problematic in your use-case, is that correct? In that case, if you'd like to share some details, we'd be happy to help you with optimizing your pipeline.

**Comment by fversaci** [comment]
Hi @szalpal ,
thanks a lot for your reply!

I showed a Python example for simplicity, but my use-case is actually in C++: I'm working on a CPU->CPU operator, so it makes little sense to allocate pinned memory (and even less to allocate space in GPU). However, I have been able to solve the issue using `set_pinned(false)`. 

Regarding instead CPU->GPU operators, I think it would still be interesting if, at least in C++, one could choose which GPU to use when first allocating pinned memory (since one might need to have different processes run on different GPUs, possibly without interference). But this is not currently a problem for me, so please take it simply as a low priority suggestion.

**Comment by szalpal** [comment]
@fversaci ,

I did a little mistake describing everything, so let me explain it once again.

`TensorListCPU` is the python wrapper and carries the underlying C++ buffer and thus is the same type as the C++ one. So if you create non-pinned memory buffer in C++, the `TensorListCPU` should be the same. Should you see otherwise when working on your CPU operator, this might be a bug. In that case please provide us with the repro and we'll handle the issue.

Please refer to https://docs.nvidia.com/deeplearning/dali/user-guide/docs/data_types.html#nvidia.dali.backend.TensorListCPU.__init__ , you may set the `is_pinned` filed in the constructor.

**Comment by fversaci** [comment]
Thanks for your clarification.

**Comment by JanuszL** [comment]
@fversaci,

Indeed there is an issue with the creation of the CPU TensorList from the list of CPU Tensors. As there is an unnecessary CUDA call issue that creates CUDA context you see a portion of GPU memory occupied.
https://github.com/NVIDIA/DALI/pull/4203 should fix that.
