### ISSUE TITLE
Random shuffle stalls Pipeline in Jupyter Notebook

### ISSUE THREAD

**Issue by tkanmae** [NVIDIA/DALI#417]
This is a possible bug report.

I have been following Getting Started tutorial and found that [`ShuffledSimplePipeline`](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/getting%20started.html#Random-shuffle) stalls when `FileReader` is configured so that random shuffle is enabled and labels are obtained from a file.

```python
class ShuffledSimplePipeline(dali.pipeline.Pipeline):
    def __init__(self, batch_size, num_threads, device_id):
        super().__init__(batch_size, num_threads, device_id, seed=12)
        # This does not work.
        self.input = dali.ops.FileReader(file_root='images', file_list='train.csv',
                                         random_shuffle=True, initial_fill=100)
        # This works fine.
        # self.input = dali.ops.FileReader(file_root='images', file_list='train.csv')
        self.decode = dali.ops.HostDecoder(output_type=dali.types.RGB)
        
    def define_graph(self):
        jpegs, labels = self.input()
        images = self.decode(jpegs)
        return images, labels
```

Note that each JPEG file is directly placed  in 'images' directory. I can instantiate the class and successfully build the instance. But calling `run()` method is running forever.

The above class definition without random shuffle works just fine.

**Comment by JanuszL** [comment]
Hi,
Could you provide the content of your `train.csv` file?
In my case following code works fine:
```
class ShuffledSimplePipeline(Pipeline):
    def __init__(self, batch_size, num_threads, device_id):
        super(ShuffledSimplePipeline, self).__init__(batch_size, num_threads, device_id, seed = 12)
        self.input = ops.FileReader(file_root = image_dir, file_list = image_dir + '/file_list.txt', random_shuffle = True, initial_fill = 100)
        #self.input = ops.FileReader(file_root = image_dir, random_shuffle = True, initial_fill = 100)
        self.decode = ops.HostDecoder(output_type = types.RGB)

    def define_graph(self):
        jpegs, labels = self.input()
        images = self.decode(jpegs)
        return (images, labels)
```

**Comment by tkanmae** [comment]
Janusz

Thanks. I figured out that `train.csv` includes names of files that do not exist. After I deleted those entries, the issue is gone. 

Initially, I ran the relevant code in Jupyter Notebook and the cell that calls `ShuffledSimplePipeline.run()` ran forever. I ported the code to a Python script and executed it, and then I had the following error message.

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  [/opt/dali/dali/pipeline/operators/reader/reader_op.h:92] Prefetch Failed: [/opt/dali/dali/util/local_file.cc:35] Assert on "fp_ != nullptr" failed: Could not open file images/american_bull1_194.jpg: No such file or directory
[1]    7761 abort (core dumped)  python test.py
```

That's why I could figure out what went wrong and fixed the issue. It would be helpful to be able to see the error message in Jupyter Notebook as well.

**Comment by ptrendx** [comment]
Ohhh, I see what the problem is. Normally the `std::runtime_error` would have been caught and pushed to Python thread as Python `RuntimeError`. However, in this case, the error originates from the prefetch thread in Loader, which does not have this set up the same way as all the other threads. @Kh4L, you did the original infrastructure to forward exceptions, could you look at this as well?

**Comment by JanuszL** [comment]
Tracked as DALI-478

**Comment by JanuszL** [comment]
https://github.com/NVIDIA/DALI/pull/429 should fix that

**Comment by JanuszL** [comment]
0.7 has been released
