### ISSUE TITLE
Question: about external_source parallel

### ISSUE THREAD

**Issue by Yaicky** [NVIDIA/DALI#4190]
First thanks for your great work, DALI extremely shortens my data loading time.

### situation
> Here is my circumstance, after loading image, there is an opencv preprocess(on-the-fly?) before DA. When image becomes bigger, cpu is heavy. GPU-Util drops to 0% and stuck constantly when I use pytorch:DataLoader, ddp. So I turn to DALI for help if I could separate some calculations from cpu to gpu.
But I failed,  seems that fn.external_source is quite limited and also hard for me to separate those preprocess. Now, what I have done is sth like that just warp a pytorch:Dataset into a callabel function(ExternalInputCallabel), I implement batch_info part in \_\_call\_\_ and get data successfully.

```
def ExternalSourcePipelineParallel(batch_size, num_threads, device_id, image_size, data_path, shard_id, world_size, seed=42, only_part=False, num_workers=4, prefetch=4):
    pipe = Pipeline(batch_size, num_threads, device_id, py_num_workers=num_workers,
                    py_start_method='spawn', prefetch_queue_depth=prefetch)
    with pipe:
        img_blended, img_raw = fn.external_source(
            source=ExternalInputCallabel(data_path=data_path, batch_size=batch_size, image_size=image_size,
                                         shard_id=shard_id, world_size=world_size, seed=seed, only_part=only_part),
                                        num_outputs=2, batch=True, batch_info=True, parallel=True, prefetch_queue_depth=prefetch)
        # do some DALI DA here.

        pipe.set_outputs(img_blended, img_raw) 

    return pipe
```
### experiment & comparison
> Cause I failed to use DALI to do DA, It seems that I just rewrite a new dataloader in DALI way. So I did some experiments with this one and pytorch_ver in one node.

```
# common
batch_size = 16
num_workers = 4
prefetch = 8
```

```
# pytorch == 1.10.1
train_loader = DataLoader(train_dataset, batch_size=batch_size, num_workers=num_workers, prefetch_factor=prefetch,
                              drop_last=True, pin_memory=True, shuffle=False, collate_fn=utils.collate_fn)

quarter_iteration = len(train_loader) // 4  # assume 4 shards
start = time.time()
for batch_idx, batch in enumerate(tqdm(train_loader)):
    if batch_idx == quarter_iteration:
        break
    
print('{:.3f} s.'.format(time.time() - start))
```
```
# DALI == 1.12.0
pipe = ExternalSourcePipelineParallel(batch_size=batch_size,                                    
                                      num_threads=1, # pytorch does not have similar one, so I set to 1.
                                      device_id=0,
                                      data_path=...,
                                     shard_id=0, world_size=4, seed=42,  
                                     py_num_workers=num_workers,
                                     prefetch_queue_depth=prefetch)
# comment out permutation part in ExternalInputCallabel so it equals shuffle=False.

pii = DALIGenericIterator(pipe,
                          ['blended', 'raw'],
                          )
start = time.time()
for i, data in enumerate(tqdm(pii, total=quarter_iteration)):
    if i == quarter_iteration:  # only for same op.
        break 

print('{:.3f} s.'.format(time.time() - start))
pii.reset()
```

#### tablet1: bs=16, num_workers=2
|  time   | pytorch  | dali |  
|  :---:  | :---:  | :---: |  
| prefetch=2 | 161.623 s | 149.087 s|
| prefetch=4 | 162.527 s | 137.616 s|
| prefetch=8 | 161.932 s | 120.179 s| 
| prefetch=16 | 162.977 s | 108.607 s| 

 

#### table2: bs=16, num_workers=4 
|  time   | pytorch  | dali |  
|  :---:  | :---:  | :---: |  
| prefetch=2 | 83.165 s | 149.554 s|
| prefetch=4 | 82.405 s | 73.470 s|
| prefetch=8 | 83.036 s | 64.523 s|  
| prefetch=16 | 82.986 s | 52.379 s|  

#### table3: bs=16, num_workers=8 
|  time   | pytorch  | dali |  
|  :---:  | :---:  | :---: |  
| prefetch=2 | 50.305 s | 151.972 s|
| prefetch=4 | 50.450 s | 73.367 s|
| prefetch=8 | 52.036 s | 38.082 s|  
| prefetch=16 | 50.274 s | 24.176 s|  
  
> We can see that changing the prefetch does not change anything in pytorch ver, maybe that preprocess is heavy. "If your workers are not fast enough to preload data, increasing the prefetch_factor won’t help" quote from PyTorch Forums, nevermind.
  
> In my experiment it seems that Pipeline.prefetch_queue_depth do the job that pytorch.DataLoader.num_workers do. According to table3, double the prefetch do the scale until  prefetch_queue_depth and py_num_workers are equal, it sounds reasonable. 

### question
> Any instructions about how external_source parallel do in detail?  
It really does the job,  my GPU-Util can keep in a high rate (99%, 98%, sometimes lower but never 0% or stuck), even though I don't have any DALI DA ops.

**Comment by JanuszL** [comment]
Hi @Yaicky,

I think the best source of information is [the documentation ](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.external_source.html) of the `external_source` operator and the examples listed on the bottoms of the mentioned page.
Regarding your observation it is expected; let me quote the relevant part of the documentation:
```
Callable source can be run in parallel by multiple workers. For batch=True multiple batches can be prepared in parallel, with batch=False it is possible to parallelize computation within the batch.

When batch=True, callables performance might especially benefit from increasing prefetch_queue_depth so that a few next batches can be computed in parallel.```

In your experiment I don't think you need to adjust `prefetch_queue_depth` of the pipeline itself, I think the external source one should do.
