### ISSUE TITLE
quite slow operators of resize

### ISSUE THREAD

**Issue by frankxyy** [NVIDIA/DALI#4198]
I use the ``resize.ipynb`` script in this repo. However, I found the operation of one resize operator may cost around 200ms which I consider to be quite long. How can I understand this situation?

**Comment by szalpal** [comment]
@frankxyy ,

It's hard to tell without any details of your pipeline, setup, hardware, batch_size, etc. Could you share some more information?

**Comment by frankxyy** [comment]
@szalpal Got it. Sorry, I will collect the background information then

**Comment by JanuszL** [comment]
Closing as stalled.
