### ISSUE TITLE
what's the meaning of type_of_size_helper

### ISSUE THREAD

**Issue by tendar** [NVIDIA/DALI#4204]
Hi,
 the meaning of type_of_size_helper confused me. The code position is as follows.
https://github.com/NVIDIA/DALI/blob/main/dali/kernels/common/type_erasure.h#L40

struct type_of_size_helper<1> : same_as<int8_t> {};  int8_t occupy 1 byte;
struct type_of_size_helper<8> : same_as<int64_t> {}; int64_t occupy 8 bytes;
so why struct type_of_size_helper<16> : same_as<int4> {}; int4 occupy 16 bytes?

this struct is used at : https://github.com/NVIDIA/DALI/blob/main/dali/operators/segmentation/select_masks.cc#L235

**Comment by mzient** [comment]
Hello @tendar,
Thanks for your interest in DALI's internals.

`type_of_size<N>` gives you a type of size N bytes with appropriate alignment requirements. It was used to limit the number of template instances where the function doesn't really need to look at the data and is only interested in the size - an example of such a template is transposition - you rearrange the array elements, but you don't care whether your element is `int32`, `uint32` or `float` - all of them occupy 4 bytes. By reinterpreting the input/output types as this "standardized" type of size N, we cut the number of template instances by more than half.

Regarding int4 - this is not a 4-bit integer; it's a vector type consisting of four integers and, as such, it has a size of `4*sizeof(int) == 16` bytes.

Thanks,
Michal

**Comment by tendar** [comment]
OK， Thanks a lot.
