### ISSUE TITLE
Unrecognized image format when passing index file to fn.readers.webdataset

### ISSUE THREAD

**Issue by skull8888888** [NVIDIA/DALI#4215]
I have the following error. It only occurs when I pass the index file to the reader. Once I remove the index_paths argument the error disappears.

```
Unrecognized image format. Supported formats are: JPEG, PNG, BMP, TIFF, PNM, JPEG2000 and WebP.
```

My pipeline
```python
@pipeline_def
def wds_pipeline(urls, index_urls):
    img_raw, json = fn.readers.webdataset(
        paths=urls,
        index_paths=index_urls,
        ext=["jpg", "json"],
        missing_component_behavior="error",
        name="Reader")
    img = fn.decoders.image(img_raw, device="mixed", output_type=types.RGB)
    resized = fn.resize(img, device="gpu", resize_shorter=256.)
    output = fn.crop_mirror_normalize(
        resized,
        dtype=types.FLOAT,
        crop=(224, 224),
        device="gpu",
        mean=[0.48145466 * 255, 0.4578275 * 255, 0.40821073 * 255],
        std=[0.26862954 * 255, 0.26130258 * 255, 0.27577711 * 255])
    return output, fn.pad(json, device="cpu")
```

How I call it
```python
urls = "..."
index_urls = "... .idx"
pipe = wds_pipeline(batch_size=16, num_threads=4, device_id=0, urls=urls, index_urls=index_urls)
pipe.build()
pipe.run()
```
I confirmed that index files contain correct information.
```
v1.2 9039
jpg 2560 41185 000000005.jpg json 45568 386 000000005.json txt 47616 7 000000005.txt
jpg 49664 18276 000000031.jpg json 69632 385 000000031.json txt 71680 7 000000031.txt
jpg 73728 50680 000000026.jpg json 125952 441 000000026.json txt 128000 7 000000026.txt
...

**Comment by szalpal** [comment]
@skull8888888 ,

Could you tell, how did you generate the index file you're passing to `index_paths` argument? Did you use the `wds2idx.py` script?

**Comment by skull8888888** [comment]
I used the terminal command `wds2idx ....tar` following [this](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/dataloading_webdataset.html#Creating-an-index) guide

**Comment by szalpal** [comment]
@skull8888888 ,

I tried to reproduce this issue on my end and everything worked for me. Could you put together small webdataset archive which manifests the issue and send it here, so I could reproduce the problem?

While we're at it, I noticed small problem in you pipeline:
```python
    output = fn.crop_mirror_normalize(
        resized,
        dtype=types.FLOAT,
        crop=(224, 224),
        device="gpu",
        mean=[0.48145466 * 255, 0.4578275 * 255, 0.40821073 * 255],
        std=[0.26862954 * 255, 0.26130258 * 255, 0.27577711 * 255])
    return output, fn.pad(json, device="cpu")
```
In DALI, once you go to the GPU, you shouldn't go back. Therefore, the `fn.pad` operator in the last line should have `device="gpu"` assigned.

**Comment by skull8888888** [comment]
Thank you for your response. I will try to put together a small subset. I also was wondering could it be cause by the Jupyter Notebook, since I am currently testing everything there.

Yep, I am using pytorch, and json should be on cpu since it is just an ascii.

**Comment by skull8888888** [comment]
I didn't manage to create a subset, but here's the [link](https://drive.google.com/drive/folders/1xKmoYOIzn5AJykiA0pBXVuf98zqntzDY?usp=sharing) to the folder which contains `00000.tar` - shard that fails when index file `00000.idx` is provided. `00000.tar` was created using `img2dataset` package.

I also included `test.tar` and `test.idx` which I manually tarred and which don't cause any errors.

I also noticed that `00000.idx` contains only the name of the files, while `test.idx` contain relative paths. Maybe it is the key to the error? I am also wondering how does index file is being created when no index file is provided. Because it somehow works with `00000.tar`.

**Comment by JanuszL** [comment]
Hi @skull8888888,

Indeed the scripts for the index creation miss support for POSIX.1-2001 archive, while the build-in index creation (inside the reader itself) can support this correctly. https://github.com/NVIDIA/DALI/pull/4226 should fix this problem.

**Comment by skull8888888** [comment]
great! thank you very much for your quick response
