### ISSUE TITLE
Sorry, bash build_helper.sh  show error

### ISSUE THREAD

**Issue by mathpopo** [NVIDIA/DALI#4231]
(base) chenxin@chenxin-Nitro-AN515-52:~/disk1/github/DALI/docker$ git submodule sync --recursive
为 '../third_party/benchmark' 同步子模组 url
为 '../third_party/boost/preprocessor' 同步子模组 url
为 '../third_party/cocoapi' 同步子模组 url
为 '../third_party/cutlass' 同步子模组 url
为 '../third_party/dlpack' 同步子模组 url
为 '../third_party/ffts' 同步子模组 url
为 '../third_party/googletest' 同步子模组 url
为 '../third_party/libcudacxx' 同步子模组 url
为 '../third_party/pybind11' 同步子模组 url
为 '../third_party/rapidjson' 同步子模组 url
(base) chenxin@chenxin-Nitro-AN515-52:~/disk1/github/DALI/docker$ git submodule update --init --recursive
fatal: detected dubious ownership in repository at '/home/chenxin/disk1/github/DALI/third_party/boost/preprocessor'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/chenxin/disk1/github/DALI/third_party/boost/preprocessor
无法在子模组路径 '../third_party/boost/preprocessor' 中找到当前版本
(base) chenxin@chenxin-Nitro-AN515-52:~/disk1/github/DALI/docker$

**Comment by mathpopo** [comment]
fatal: detected dubious ownership in repository at '/home/chenxin/disk1/github/DALI/third_party/benchmark'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/chenxin/disk1/github/DALI/third_party/benchmark
无法在子模组路径 'third_party/benchmark' 中获取，尝试直接获取 361e8d1cfe0c6c36d30b39f1b61302ece5507320：
fatal: detected dubious ownership in repository at '/home/chenxin/disk1/github/DALI/third_party/benchmark'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/chenxin/disk1/github/DALI/third_party/benchmark
fatal: detected dubious ownership in repository at '/home/chenxin/disk1/github/DALI/third_party/benchmark'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/chenxin/disk1/github/DALI/third_party/benchmark
获取了子模组路径 'third_party/benchmark'，但是它没有包含 361e8d1cfe0c6c36d30b39f1b61302ece5507320。直接获取该提交失败。

**Comment by mathpopo** [comment]
@JanuszL thank you for your help

i use :
 2006  git config --global --add safe.directory '*'
 2007  git submodule sync --recursive
 2008  git submodule update --init --recursive


(base) chenxin@chenxin-Nitro-AN515-52:~/disk1/github/DALI$ git submodule sync --recursive
为 'third_party/benchmark' 同步子模组 url
为 'third_party/boost/preprocessor' 同步子模组 url
为 'third_party/cocoapi' 同步子模组 url
为 'third_party/cutlass' 同步子模组 url
为 'third_party/dlpack' 同步子模组 url
为 'third_party/ffts' 同步子模组 url
为 'third_party/googletest' 同步子模组 url
为 'third_party/libcudacxx' 同步子模组 url
为 'third_party/pybind11' 同步子模组 url
为 'third_party/rapidjson' 同步子模组 url
(base) chenxin@chenxin-Nitro-AN515-52:~/disk1/github/DALI$ git submodule update --init --recursive
子模组路径 'third_party/boost/preprocessor'：检出 'd4e82d7d3f2e2adbe280966ac51ce8f9372f5a44'
子模组路径 'third_party/cutlass'：检出 'e45e77343693e261f9285ee05be4f0498848e5a5'
子模组路径 'third_party/googletest'：检出 '58d77fa8070e8cec2dc1ed015d66b454c8d78850'
子模组路径 'third_party/libcudacxx'：检出 '67624c5f336947192103715348786eb234a4f393'
子模组路径 'third_party/pybind11'：检出 'aa304c9c7d725ffb9d10af08a3b34cb372307020'
子模组路径 'third_party/rapidjson'：检出 '27c3a8dc0e2c9218fe94986d249a12b5ed838f1d'
子模组 'thirdparty/gtest'（https://github.com/google/googletest.git）已对路径 'third_party/rapidjson/thirdparty/gtest' 注册
正克隆到 '/home/chenxin/disk1/github/DALI/third_party/rapidjson/thirdparty/gtest'...
子模组路径 'third_party/rapidjson/thirdparty/gtest'：检出 'ba96d0b1161f540656efdaed035b3c062b60e006'

**Comment by mathpopo** [comment]
CMake Error at cmake/Utils.cmake:93 (message):
  File /home/chenxin/disk1/github/DALI/third_party/ffts/CMakeLists.txt not
  found.  Did you forget to `git clone --recursive`? Try this:

    cd /home/chenxin/disk1/github/DALI && \
    git submodule sync --recursive && \
    git submodule update --init --recursive && \
    cd -

Call Stack (most recent call first):
  cmake/Dependencies.common.cmake:198 (check_and_add_cmake_submodule)
  cmake/Dependencies.cmake:105 (include)
  CMakeLists.txt:201 (include)


-- Configuring incomplete, errors occurred!
See also "/home/chenxin/disk1/github/DALI/docker/CMakeFiles/CMakeOutput.log".
See also "/home/chenxin/disk1/github/DALI/docker/CMakeFiles/CMakeError.log".
(base) chenxin@chenxin-Nitro-AN515-52:~/disk1/github/DALI/docker$ sudo apt search nvJPEG2k
正在排序... 完成
全文搜索... 完成  
(base) chenxin@chenxin-Nitro-AN515-52:~/disk1/github/DALI/docker$ sudo apt search JPEG2k
正在排序... 完成
全文搜索... 完成  
(base) chenxin@chenxin-Nitro-AN515-52:~/disk1/github/DALI/docker$ sudo apt search nvJPEG2k
正在排序... 完成
全文搜索... 完成  
(base) chenxin@chenxin-Nitro-AN515-52:~/disk1/github/DALI/docker$ cd ../
(base) chenxin@chenxin-Nitro-AN515-52:~/disk1/github/DALI$ l
Acknowledgements.txt*  conda/            dali/                dali.png*        docs/                             include/    qa/              third_party/
cmake/                 CONTRIBUTING.md*  DALI_DEPS_VERSION*   dali_tf_plugin/  Doxyfile*                         LICENSE*    README.rst*      tools/
CMakeLists.txt*        COPYRIGHT*        DALI_EXTRA_VERSION*  docker/          guided_contribution_tutorial.md*  platforms/  STYLE_GUIDE.md*  VERSION*
(base) chenxin@chenxin-Nitro-AN515-52:~/disk1/github/DALI$ git submodule update --init --recursive
(base) chenxin@chenxin-Nitro-AN515-52:~/disk1/github/DALI$ git submodule sync --recursive
为 'third_party/benchmark' 同步子模组 url
为 'third_party/boost/preprocessor' 同步子模组 url
为 'third_party/cocoapi' 同步子模组 url
为 'third_party/cutlass' 同步子模组 url
为 'third_party/dlpack' 同步子模组 url
为 'third_party/ffts' 同步子模组 url
为 'third_party/googletest' 同步子模组 url
为 'third_party/libcudacxx' 同步子模组 url
为 'third_party/pybind11' 同步子模组 url
为 'third_party/rapidjson' 同步子模组 url
为 'third_party/rapidjson/thirdparty/gtest' 同步子模组 url
(base) chenxin@chenxin-Nitro-AN515-52:~/disk1/github/DALI$ git submodule update --init --recursive
(base) chenxin@chenxin-Nitro-AN515-52:~/disk1/github/DALI$ cd third_party/
(base) chenxin@chenxin-Nitro-AN515-52:~/disk1/github/DALI/third_party$ ls
benchmark  boost  cocoapi  cpplint.py  cutlass  dlpack  ffts  googletest  libcudacxx  opencv  pybind11  rapidjson  README.rst
(base) chenxin@chenxin-Nitro-AN515-52:~/disk1/github/DALI/third_party$ cd ffts/
(base) chenxin@chenxin-Nitro-AN515-52:~/disk1/github/DALI/third_party/ffts$ ls
(base) chenxin@chenxin-Nitro-AN515-52:~/disk1/github/DALI/third_party/ffts$ 
(base) chenxin@chenxin-Nitro-AN515-52:~/disk1/github/DALI/third_party/ffts$

**Comment by mathpopo** [comment]
@JanuszL i update thirdparty ,but have no info about ffts

**Comment by JanuszL** [comment]
Hi @mathpopo,

As you can see [here](https://github.com/NVIDIA/DALI/tree/main/third_party) there is a reference to valid SHA from an FFTS fork. Can try again and clone the DALI repo once again?

**Comment by mathpopo** [comment]
-- Generating done
-- Build files have been written to: /home/chenxin/disk1/github/DALI/docker
+ '[' ON = ON ']'
+ make -j lint
Performing Python linter check
Performing C++ linter check
/home/chenxin/disk1/github/DALI/dali/python/nvidia/dali/plugin/base_iterator.py:156:16: E127 continuation line over-indented for visual indent
/home/chenxin/disk1/github/DALI/dali/python/nvidia/dali/plugin/base_iterator.py:183:16: E127 continuation line over-indented for visual indent
/home/chenxin/disk1/github/DALI/dali/python/nvidia/dali/plugin/base_iterator.py:185:16: E127 continuation line over-indented for visual indent
/home/chenxin/disk1/github/DALI/dali/python/nvidia/dali/plugin/base_iterator.py:187:16: E127 continuation line over-indented for visual indent
/home/chenxin/disk1/github/DALI/dali/python/nvidia/dali/plugin/triton.py:15:1: E302 expected 2 blank lines, found 1
/home/chenxin/disk1/github/DALI/dali/python/nvidia/dali/_multiproc/shared_queue.py:153:67: F821 undefined name 'MSG_CLASS'
/home/chenxin/disk1/github/DALI/dali/test/python/nose_utils.py:26:1: E402 module level import not at top of file
/home/chenxin/disk1/github/DALI/dali/test/python/nose_utils.py:27:1: E402 module level import not at top of file
/home/chenxin/disk1/github/DALI/dali/test/python/nose_utils.py:28:1: E402 module level import not at top of file
/home/chenxin/disk1/github/DALI/dali/test/python/operator/test_crop_mirror_normalize.py:136:12: E127 continuation line over-indented for visual indent
/home/chenxin/disk1/github/DALI/dali/test/python/operator/test_rotate.py:330:16: E127 continuation line over-indented for visual indent
/home/chenxin/disk1/github/DALI/dali/test/python/reader/test_shuffling.py:222:12: E127 continuation line over-indented for visual indent
/home/chenxin/disk1/github/DALI/dali/test/python/reader/test_shuffling.py:281:12: E127 continuation line over-indented for visual indent
8     E127 continuation line over-indented for visual indent
1     E302 expected 2 blank lines, found 1
3     E402 module level import not at top of file
1     F821 undefined name 'MSG_CLASS'

**Comment by JanuszL** [comment]
Closing as stalled.
