### ISSUE TITLE
How much can DALI speedup

### ISSUE THREAD

**Issue by tendar** [NVIDIA/DALI#4246]
Hi,

From the link https://developer.nvidia.com/blog/rapid-data-pre-processing-with-nvidia-dali/ , I know DALI cam speed up training woks from 17kfps to 22kfps.
And can you tell me what's the performance parameter of server CPU?
And can DALI spped up any network traing? and  what scene DALI will have a speed up than CPU?

Thanks.

**Comment by JanuszL** [comment]
Hi @tendar,

The best would be to follow [this blog post](https://developer.nvidia.com/blog/case-study-resnet50-dali/) so check all steps indicating if DALI can help in your case.

**Comment by tendar** [comment]
Hi, @JanuszL 

This blog help me so much, thank you.
