### ISSUE TITLE
Would you consider cache the decoded data into the RAM instead of GPU memory?

### ISSUE THREAD

**Issue by songyuc** [NVIDIA/DALI#4251]
Hi, guys,
I am continueing learning DALI today. Since the the decoded data (like the decoded image) can be reused in a second epoch, cache is a promising way to speed up the process of image decoding. And I find that, `nvidia.dali.fn.decoders.image` may have provided the cache mechanism like `cache_size`. From the doc, I infer that, if cache is opening, it would cache the decoded data into the GPU memory. However, GPU memory is always more precious and less than RAM.
So, my question is, would you consider cache the decoded data into the RAM instead of GPU memory, i.e., decoding data on GPU and then transferring into RAM?
Or would it be a promising way for better caching?

Your answer will be appreciated!

**Comment by JanuszL** [comment]
Hi @songyuc,

It is possible to cache them in the RAM memory, however only for the CPU decoder. For the GPU on the round trip from the GPU (where the decoded images are located) to the CPU would yield a slowdown.
However, we are happy to see any experiments and attempts to make DALI better, including one an extension of the CPU image decoder by the caching mechanism.

**Comment by songyuc** [comment]
> Hi @songyuc,
> 
> It is possible to cache them in the RAM memory, however only for the CPU decoder. For the GPU on the round trip from the GPU (where the decoded images are located) to the CPU would yield a slowdown. However, we are happy to see any experiments and attempts to make DALI better, including one an extension of the CPU image decoder by the caching mechanism.

Hi, @JanuszL , thank you for the response!
Since caching the decoded image will save the computations while "the round trip from the GPU (where the decoded images are located) to the CPU would yield a slowdown". So, could this round trip be run in another separate flow, like a sub-thread or sub-progress? I feel it might be able to be free from the slowdown due to the transfer from GPU to CPU.

**Comment by JanuszL** [comment]
Hi @songyuc,

>  So, could this round trip be run in another separate flow, like a sub-thread or sub-progress?

Indeed, that is one of the ideas that a good GPU program should utilize if possible. The most optimal path is to use DMA from the CPU to the GPU that is fully asynchronous and can overlap with the CPU and GPU computations. Still, it occupies the DMA channel that sometimes needs to be used to pass data needed by the training/inference kernels. However, this transfer is not preemptable and can stall other work. Still, I encourage you to try this out and see how that works in the workloads you have.

**Comment by songyuc** [comment]
> Hi @songyuc,
> 
> > So, could this round trip be run in another separate flow, like a sub-thread or sub-progress?
> 
> Indeed, that is one of the ideas that a good GPU program should utilize if possible. The most optimal path is to use DMA from the CPU to the GPU that is fully asynchronous and can overlap with the CPU and GPU computations. Still, it occupies the DMA channel that sometimes needs to be used to pass data needed by the training/inference kernels. However, this transfer is not preemptable and can stall other work. Still, I encourage you to try this out and see how that works in the workloads you have.

Thanks for the guide. I am currently working on the COCO dataset, whose train set is about 20G large on the SSD disk. I guess the bottleneck is mainly caused by the **shuffle** mode in loading data, and there might not be an optimal solution. Reduplicative IO operations and decodings may always be needed, when cache of data is missed, unless the RAM or GPU memory is so sufficient (like ~200G) to cache all the decoded data of the entire dataset.

**Comment by JanuszL** [comment]
I recommend checking [this blog post](https://developer.nvidia.com/blog/case-study-resnet50-dali/) to see if the data loading truly is a bottleneck. Also, you may want to capture a [Nsight profile](https://developer.nvidia.com/nsight-systems) to see what the training timeline looks like.
