### ISSUE TITLE
Missing auto_reset=True in pytorch lightning example

### ISSUE THREAD

**Issue by ferrine** [NVIDIA/DALI#4259]
In the [notebook](https://github.com/NVIDIA/DALI/blob/main/docs/examples/frameworks/pytorch/pytorch-lightning.ipynb) a user should use [auto_reset=True](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/plugins/pytorch_plugin_api.html) argument in order to persist the dataloader between epoches

**Comment by JanuszL** [comment]
Hi @ferrine,

It is not needed anymore. As PyTorch lightning calls `iter` on the provided iterator we made the DALI iterator call reset automatically (in https://github.com/NVIDIA/DALI/pull/3923 and https://github.com/NVIDIA/DALI/pull/4048). So the mentioned example should work fine.
