### ISSUE TITLE
Questions about GPU memory usage for augmentation & free list 

### ISSUE THREAD

**Issue by Heelim-Hong** [NVIDIA/DALI#4260]
Hi,
I have several questions about GPU memory usage. 
Experiment Setup : Tesla V100-PCIE-32GB (1 GPU), 512 batch size

1)
I have profiled GPU memory footprints from image augmentation excluding training part. 
![스크린샷 2022-09-19 오후 4 22 35](https://user-images.githubusercontent.com/74954511/190968032-3ac3b4c1-5a15-4705-8529-66aebf802e2f.png)
It looks only about 1% of GPU memory is used while augmentation. I am wondering if this profiling is valid or not.
If the profiling is valid, why would GPU memory on augmentation uses such a small amounts of memory?
In the same context, CPU uses about 45% of memory. what makes CPU to consume this percentage of memory? 

2) 
Above profiling was done with 512 batch size using about 1% of GPU memory on augmentation.
With 1024 batch size, I was able to see GPU memory usage on augmentation grows up to about 3%. 
In the circumstances, I am curious if the GPU memory usage on augmentation would dramatically grow as the batch size increases and what makes GPU memory on augmentation grow as batch size increase.

3)  
![스크린샷 2022-09-19 오후 5 14 17](https://user-images.githubusercontent.com/74954511/190975926-cdcc3854-deb6-48d3-bb5a-64d0b61a66e1.png)
This is the print of free list "put" call and "get" call. 
If you see the red box, it seems CPU allocated memory on address 0x40000000000 are put into free list by "put" call to free list and gets this allocated memory by fragmenting. 
The question about this is why such a big size of CPU memory are put into the free list and even why such a big size of CPU memory is allocated at first time?

4) 
As I understood, chunks in the free list of DALI seemed not merging with each other but only fragmenting and left them become small useless chunks. Is this right and why? 

Thank you!

**Comment by JanuszL** [comment]
Hi @Heelim-Hong,

Thank you for reaching out.
Can you share the pipeline you used for profiling? It may happen that all the execution is performed by the CPU and the GPU memory consumption comes from the CUDA context creation (GPU kernels are loaded into the GPU memory). Also, if you transfer the results of the pipeline to the GPU then the output buffer proportional to the batch size could be a thing you observe.

**Comment by Heelim-Hong** [comment]
Thank you for your kind reply @JanuszL 

<img width="780" alt="스크린샷 2022-09-19 오후 7 33 12" src="https://user-images.githubusercontent.com/74954511/190999278-bb3c041e-7fb7-461d-aafd-51f6236e9599.png">

Above is the pipeline we used for test which I think is gpu based pipeline. 
I am wondering if consuming only 1% of GPU memory on augmentation would be valid?

**Comment by Heelim-Hong** [comment]
<script src="https://gist.github.com/Heelim-Hong/c88b18cbed27c77ecd1c1b1c12abe30e.js"></script>
This is the full script I used and I measured the memory using nvidia-smi queries.

Thanks.
