### ISSUE TITLE
GPU Memory consumption on loaded dynamic library

### ISSUE THREAD

**Issue by Esthesia** [NVIDIA/DALI#4287]
Is there any reference or experimental data in the DALI team about how much GPU memory is in use loading the dynamic library?
I want to test the DALI's GPU memory usage in detail so I tested it on the simple image set with 224×224 and in *.jpg format. (from 6 to 70KB in size)

With batch size 512, The consumed GPU memory is about 800MB.
For allocated memory for processing data with tracing the `cuMemCreate` is about 330MB. 
Then, for library loading can cause such memory size (about 400MB size)?

This is the code snippet for the pipeline information.
```
eii_gpu = ExternalInputGpuIterator(batch_size)    
    
pipe_gpu = Pipeline(batch_size=batch_size, num_threads=2, device_id=0)
with pipe_gpu:
    images, labels = fn.external_source(source=eii_gpu, num_outputs=2, device="gpu")
    enhance = fn.brightness_contrast(images, contrast=2)
    pipe_gpu.set_outputs(enhance, labels)

pipe_gpu.build()
pipe_gpu.run()
```
Thank you for this work and hope to get the answer.

**Comment by JanuszL** [comment]
Hi @Esthesia,

When the GPU context is created, the relevant GPU execution code (kernels) is loaded to GPU RAM. In this case, it is very likely that 400 MB is the size of all DALI kernels.

**Comment by Esthesia** [comment]
@JanuszL Thank you for the quick response. So, can I assume that 400MB is plausible data? For me, the size of all DALI kernels is quite big.

**Comment by mzient** [comment]
@Esthesia It might be more than just DALI kernels. If there are more shared objects that have CUDA code in them, creating a CUDA context might also load the kernels from these libraries.

**Comment by JanuszL** [comment]
You can also try [lazy loading](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#cuda-general-new-features) `CUDA_MODULE_LOADING=LAZY`

**Comment by JanuszL** [comment]
You can also try [lazy loading](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#cuda-general-new-features) `CUDA_MODULE_LOADING=LAZY`

**Comment by Esthesia** [comment]
@mzient @JanuszL 
How can I track the size of DALI kernels? 
Is there any suggestion or code snippet that I can track them?
I tracked GPU memory consumption indirectly using `nvidia-smi`. 
Is this causing the larger tracked memory consumption?

**Comment by JanuszL** [comment]
I don't think that there are any externally available tools. On top of that the memory consumption may vary from GPU arch to GPU arch as well it may depend on the driver version.
Please check [cudaDeviceSetLimit ](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__DEVICE.html#group__CUDART__DEVICE_1g05956f16eaa47ef3a4efee84563ccb7d) to see what additional allocation the driver may do on the GPU side.

**Comment by Esthesia** [comment]
Thank you for your quick and detailed reply. 
I close this issue and if there is any update for this question, I will reopen this.
