### ISSUE TITLE
Random execution of operators

### ISSUE THREAD

**Issue by danielsoutar** [NVIDIA/DALI#4291]
Hi there, I was wondering if it was possible to enable random execution of a random crop in the pipeline.

Say I want to randomly crop a 128x128 section 50% of the time, and the other 50% to just use the full image. Something like this (pseudo-code used for illustration):

```python
@pipeline_def
def random_flip_pipeline():
    jpegs, labels = fn.readers.file(file_root=image_dir)
    # 50% of the time, randomly take a 128x128 crop of the image.
    # Otherwise, return the unchanged image.
    randomly_cropped_images = fn.decoders.image_slice(jpegs, crop_size=[128, 128], probability=0.5)
    return randomly_cropped_images
```

I specifically want a *fixed-size crop*, but random in where it is, and *also* random in whether it is applied. I know Detectron2 enables this because they have a random operator that can take in any arbitrary operator. Something like that in DALI would be very useful. But any suggestion is welcome - `paste` if that would work, using an `if` statement in the pipeline, etc.

**Comment by mzient** [comment]
Hello @danielsoutar 
While we don't support random execution, you can do quite elaborate calculations to compute the crop start and shape.
For example, you can conditionally select the predefined size [128, 128] or the uncropped image size (obtained from `fn.peek_image_shape`), and then use a randomly placed starting point within the free space.

```Python
@pipeline_def
    jpegs, labels = fn.readers.file(file_root=image_dir)
    shapes = fn.decoders.peek_image_shape(jpegs, dtype=dali.types.INT32)[0:2]

    use_crop = fn.random.coin_flip()
    crop_size = use_crop * dali.types.Constant([128, 128]) + (1 - use_crop) * shapes
    free_space = shapes - crop_size
    crop_start = fn.cast(free_space * fn.random.uniform(range=(0, 1)), dali.types.INT32)

    randomly_cropped_images = fn.decoders.image_slice(jpegs, start=start, size=crop_size, axis_names="HW")
```

**Comment by danielsoutar** [comment]
That's excellent @mzient, thanks for this! That does the trick for me.

**Comment by klecki** [comment]
Hi @danielsoutar,
with recent introduction of conditional execution: https://docs.nvidia.com/deeplearning/dali/main-user-guide/docs/pipeline.html#conditional-execution 
it is now possible to do it more easily in DALI, like this:

```
@pipeline_def(enable_conditionals=True)
def random_flip_pipeline():
    jpegs, labels = fn.readers.file(file_root=image_dir)
    # 50% of the time, randomly take a 128x128 crop of the image.
    # Otherwise, return the unchanged image.
    if fn.random.coin_flip():
      randomly_cropped_images = fn.decoders.image_slice(jpegs, crop=[128, 128])
    else:
      randomly_cropped_images = fn.decoders.image(jpegs)
    return randomly_cropped_images```
