### ISSUE TITLE
CUDA_ERROR_NO_DEVICE for GPU video decoding

### ISSUE THREAD

**Issue by gabgoh** [NVIDIA/DALI#4311]
I am attempting to run a minimal DALI dataloader with a single video. This is the installation script I am using (
```
apt-get update
apt-get install --yes libnvidia-compute-470=470.57.02-0ubuntu1
apt-get install --yes libnvidia-decode-470=470.57.02-0ubuntu1
pip install --extra-index-url https://developer.download.nvidia.com/compute/redist --upgrade nvidia-dali-cuda110
```

and the following is the minimal video dataloader.

```
import os
import numpy as np

from nvidia.dali import pipeline_def
import nvidia.dali.fn as fn
import nvidia.dali.types as types

max_batch_size = 8
sequence_length = 8

@pipeline_def
def video_pipe():
    video, labels = fn.readers.video(device="gpu", file_root="/root/videos/", sequence_length=sequence_length,
                                     random_shuffle=True, initial_fill=8)
    return video, labels

pipe = video_pipe(num_threads=2, device_id=1, seed=12345, batch_size=1)
pipe.build()
pipe_out = pipe.run()
```
Oddly, when I attempt to run the pipeline, I get the following error:
```
RuntimeError: Critical error in pipeline:
Error when executing GPU operator readers__Video encountered:
CUDA driver API error CUDA_ERROR_NO_DEVICE (100):
no CUDA-capable device is detected
Current pipeline object is no longer valid.
```
but nvidia-smi shows that the gpus are present.
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.137      Driver Version: 470.137      CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
```

Also, mixed jpeg decoding (the script below) works.

```
from nvidia.dali import pipeline_def
import nvidia.dali.fn as fn
import nvidia.dali.types as types

image_dir = "data/images"
max_batch_size = 8


@pipeline_def
def simple_pipeline():
    jpegs, labels = fn.readers.file(file_root=image_dir)
    images = fn.decoders.image(jpegs, device='mixed')

    return images, labels

pipe = simple_pipeline(batch_size=max_batch_size, num_threads=1, device_id=0)
pipe.build()
pipe_out = pipe.run()
print(pipe_out)
```

I found three other references to the same error (https://github.com/NVIDIA/DALI/issues/2229, https://github.com/NVIDIA/DALI/issues/1161, and https://github.com/NVIDIA/DALI/issues/4034)
which point to a possible missing library. ldconfig does show that I have the requisite libraries, however.
```
$: ldconfig -p | grep libnvcuvid
        libnvcuvid.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libnvcuvid.so.1
        libnvcuvid.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libnvcuvid.so
```

any help fixing this would be greatly appreciated!

**Comment by jantonguirao** [comment]
Hi @gabgoh. I see that the device_id is different for the two snippets (device_id=1 and device_id=0).
Can you share more information about your system? The full output of `nvidia-smi` would be great.

Generally, we prefer installing the driver from the runfile instead of relying on apt packages. So, alternatively, you could try to download and install the latest NVIDIA driver from the runfile, and see if that fixes any potential issues with your installation. If you choose to do so, please remember to uninstall the apt driver packages you have currently installed first.

**Comment by jantonguirao** [comment]
Closing this issue now. If you still need help, please reopen.
