### ISSUE TITLE
CPU Utilization Variation with different dali versions

### ISSUE THREAD

**Issue by Weigaa** [NVIDIA/DALI#4333]
I have defined the following pipeline to implement Numpy data transfer from NVMe SSD to GPU.
My Cuda version is 11.7.
```
batch_size = 4
@pipeline_def(batch_size=batch_size, num_threads=8, device_id=0)
def pipe_gds():
    data = fn.readers.numpy(device='gpu', file_root=data_dir, files=files)
    return data
```
The previous version of DALI I used was 1.14.0, and I found that the CPU utilization during data reading could reach up to 552%.
Recently, I noticed that the maximum CPU utilization dropped to 80% when using DALI versions 1.15 and 1.18.
Note that I deliberately forced DALI to not use GDS by "`modprobe -r nvidia_fs`" before data transfer, but this method seems to fail in version 1.15 and later.

What happened between version 1.14 and 1.15 that caused CPU utilization to drop?
Is there any way I can force dali to not use GDS? (Because I have to do a comparison experiment)

Thanks！！！

**Comment by JanuszL** [comment]
Hi @Weigaa,

What you can do is to:
- either force GDS to run in the compatibility mode (refer to the GDS manual)
- use the CPU reader and then transfer the data to the GPU:
```
def pipe_gds():
    data = fn.readers.numpy(device='cpu', file_root=data_dir, files=files).gpu()
    return data
```

**Comment by Weigaa** [comment]
Thank you@JanuszL,
The first approach fails in DALI 1.8, even though I have forced compatibility mode（as shown in the figure）, CPU utilization is still low. 
![1665572740760](https://user-images.githubusercontent.com/38322329/195326937-d8c70842-d13f-470b-986f-975375cae64b.png)
The second approach worked where the CPU is at high utilization, but this writing style seemed less than elegant.
Can you tell me the reason why approach 1 is not feasible? 
I noticed that the 1.15 update announcement says that DALI implements custom GDS staging, does this mean that Dali no longer needs nvidia_fs to implement GDS?

Look forward to your reply, thanks!

**Comment by Weigaa** [comment]
Hi,@JanuszL

This improvement seems to have a negative impact on `buffer/memory cache` usage.

In version 1.14, in gds compatibility mode, after I do multiple reads of the same data, I get a significant speed increase when I read it again. However, when it comes to versions after 1.15, this speed improvement is almost insignificant.

In other words, if I use `data = fn.readers.numpy(device='cpu', file_root=data_dir, files=files).gpu() `to read the same data multiple times in a row, it will be more efficient than `data = fn.readers.numpy(device=' gpu', file_root=data_dir, files=files)`, is this normal?

**Comment by mzient** [comment]
@Weigaa Yes, this is normal and expected. GDS uses unbuffered I/O, so it's expected that multiple accesses to the same data are not accelerated - there's no GPU-side file cache and the OS cache is bypassed. GDS is meant for large datasets, often network ones, where the dataset is typically larger than the RAM. If your dataset fits in RAM, then GDS will actually decrease performance (at least for all but the first epoch).

**Comment by Weigaa** [comment]
Thanks, @mzient 
Do you mean that in versions before 1.5, the GDS compatibility mode may go through the OS cache, but not after?

**Comment by JanuszL** [comment]
We still use the same GDS API in DALI but the memory alignment is more GPU friendly now, so it could be implemented through a different code path inside the GDS itself.
Still, I would not rely on the compatibility mode performance it is rather a GPU fallback when native GDS is not available and the performance can vary depending on conditions.

**Comment by Weigaa** [comment]
Thanks@JanuszL 
Could I understand that before version 1.5, the `**data path** when using` fn.readers.numpy(device='cpu', file_root=data_dir, files=files).gpu()  and ` fn.readers.numpy(device= 'gpu', file_root=data_dir, files=files)`  under GDS compat mode is same. And in 1.5 or newer, they become different due to your optimizations or using a different code path inside the GDS?

I believe the compat mode is just a GPU fallback when native GDS is not available, but I'd like to know what has changed in this GPU fallback mechanism since version 1.15 to make it impossible to take advantage of the OS buffer.

I used the `free -g` command to verify that GDS/GDS compat/POSIX would use the buffer/cache. the results are shown below.

GDS:
```
              total        used        free      shared  buff/cache   available
Mem:            502           1         498           0           3         498
Swap:            61           0          61
```
GDS_compat:
```
              total        used        free      shared  buff/cache   available
Mem:            502           1         369           0         131         498
Swap:            61           0          61
```
POSIX:
```
              total        used        free      shared  buff/cache   available
Mem:            502           1         131           0         369         497
Swap:            61           0          61
```

It does seem that GDS almost does not use buffer, GDS_compat uses 131GB buffer/cache and POSIX uses 369GB.
Does the result look like GDS_compat produces a large buffer that could not be used by subsequent accesses?

**Comment by JanuszL** [comment]
> I believe the compat mode is just a GPU fallback when native GDS is not available, but I'd like to know what has changed in this GPU fallback mechanism since version 1.15 to make it impossible to take advantage of the OS buffer.

The fallback is implemented at the GDS level. We still use the same libcufile API, but the provided buffer has a different alignment now, so the internal GDS code path could be different now. In this case, it would be best to check with GDS developers using [NVIDIA developers forum](https://forums.developer.nvidia.com/c/accelerated-computing/cuda/cuda-programming-and-performance/7).

**Comment by Weigaa** [comment]
Thanks for your response, I will gonna talk with  GDS developers further.
