### ISSUE TITLE
Can I have two pipelines on the same gpu?

### ISSUE THREAD

**Issue by danbider** [NVIDIA/DALI#4340]
My package Lightning Pose has two dataloaders: 
1) loads static images and keypoint labels (currently in imgaug)
2) loads video segments without labels (currently in DALI)
We train on 1) + 2) and get a semi-supervised model.

We are considering switching 1) to DALI as well. will I be able to have two pipes running in tandem on the same device and feeding images and videos respectively to a model?

@JanuszL

**Comment by JanuszL** [comment]
Hi @danbider,

I don't see any issue with running concurrently multiple DALI pipelines on the same GPU.
If you experience any problems let us know.

**Comment by mzient** [comment]
The only limitation is the amount of memory you have, since the pipelines will compete for it.
