### ISSUE TITLE
The example notebook "Video Pipeline Demonstrating Applying Labels Based on Timestamps or Frame Numbers" seems wrong!

### ISSUE THREAD

**Issue by RafayAK** [NVIDIA/DALI#4360]
Hi, I'm looking at the notebook ["Video Pipeline Demonstrating Applying Labels Based on Timestamps or Frame Numbers"](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/sequence_processing/video/video_file_list_outputs.html). But it seems wrong. 

The notebook defines a `file_list` that lists on each line the video file name, followed by the label and the start and end frame of the label:

```
test_label.mp4 0  # assuming label 0 is everything other than the sequences specified below, the notebook does not explain this 
test_label.mp4 1 0 100  # output label 1 for all frames 0 - 99
test_label.mp4 2 100 200   # output label 2 for all frames 100 - 199
test_label.mp4 3 200 250  # output label 3 for all frames 200 - 249
``` 
This file is passed to a video pipeline defined as below:
```
BATCH_SIZE=4
COUNT=1
ITER=10
frame_num_based_labels=True

@pipeline_def
def video_pipe(file_list):
    video, label, start_frame_num, timestamps = \
        fn.readers.video(device="gpu", file_list=file_list, sequence_length=COUNT,
                         shard_id=0, num_shards=1, random_shuffle=True, initial_fill=10,
                         image_type=types.RGB, dtype=types.FLOAT, file_list_frame_num=frame_num_based_labels,
                         enable_frame_num=True, enable_timestamps=True)
    return video, label, start_frame_num, timestamps

```

When this pipeline is run and visualized the labels are wrong!

For example, in this image picked directly from the notebook, the ***label should have been 2 (part of 100-199 in the `file_list`), but for some odd reason, it's 0??!***
![image](https://user-images.githubusercontent.com/17025191/195980545-96302466-82b4-44b7-90ec-bba1afe3af56.png)

Similarly, in this image also picked from the notebook, the ***label should have been 1 (part of 0-99 in the `file_list`) but is also 0***.
![image](https://user-images.githubusercontent.com/17025191/195980551-7995ee7a-5029-40c5-886f-d6054694dbef.png)

In some cases the label is correct, too:
![image](https://user-images.githubusercontent.com/17025191/195980517-8c541ca5-205c-416f-b635-88e29368e748.png)

I've downloaded this notebook myself and tested it out, too. This is stopping me from using DALI on something like the MERL shopping dataset or the MPII cooking dataset. Please let me know what is the cause of this weirdness and if it can be fixed with one of the arguments to the `fn.readers.video` function

**Update:** Seems like if I remove the line `test_label.mp4 0` from the `file_list` the results seem to look correct, i.e labels are assigned to frames correctly. Now the problem becomes how to assign a `background` label to all the frames that don't have labels assigned to them by the annotators.

**Comment by JanuszL** [comment]
Hi @RafayAK,

I have fixed the original inconsistency with https://github.com/NVIDIA/DALI/pull/4364.
To answer your second question, I think you need to manually assign the remaining parts of the video to the desired label.
Please check the operator description, especially:
```
Path to the file with a list of file label [start_frame [end_frame]] values.

Positive value means the exact frame, negative counts as a Nth frame from the end (it follows python array indexing schema), equal values for the start and end frame would yield an empty sequence and a warning. This option is mutually exclusive with filenames and file_root.
```
So:
```
test_label.mp4 0 251 0  # output label 0 for all other frames
```

**Comment by RafayAK** [comment]
@JanuszL Thanks for the reply.

Looking at the documentation you pointed to, shouldn't it be?
```
test_label.mp4 0 250 -1  # output label 0 for all other frames from 250 to the last frame
``` 
Negative `-1` would mean the last frame, plus since the last label `3` goes from `200-249` the rest of the labels should iterate from `250` onwards

**Comment by JanuszL** [comment]
Yes, My bad. It should be -1. Sorry for the confusion.

**Comment by RafayAK** [comment]
Thanks!
