### ISSUE TITLE
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /home/***/lib/python3.10/site-packages/torch/lib/libtorch_python.so)

### ISSUE THREAD

**Issue by songyuc** [NVIDIA/DALI#4369]
Hi, guys,
I am learning dali today, and I met a strange error if matplotlib.pyplot was not imported: [[script]](https://gist.github.com/songyuc/f49862cdf92d99a0aaf87be7aaa4c6e6)
> /home/xxx/lib/python3.10/site-packages/nvidia/dali/backend.py:46: Warning: DALI support for Python 3.10 is experimental and some functionalities may not work.
  deprecation_warning("DALI support for Python 3.10 is experimental and some functionalities "
Traceback (most recent call last):
  File "/home/xxx/test/dali/validate_shuffle_by_ids.py", line 4, in <module>
    from nvidia.dali.plugin.pytorch import DALIGenericIterator
  File "/home/xxx/lib/python3.10/site-packages/nvidia/dali/plugin/pytorch.py", line 21, in <module>
    import torch
  File "/home/xxx/lib/python3.10/site-packages/torch/__init__.py", line 202, in <module>
    from torch._C import *  # noqa: F403
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /home/xxx/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
>
> Process finished with exit code 1

Please help solve this issue.

**Comment by JanuszL** [comment]
Hi @songyuc,

This error seems to be caused by PyTorch:
```
File "/home/xxx/lib/python3.10/site-packages/torch/init.py", line 202, in
from torch._C import * # noqa: F403
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /home/xxx/lib/python3.10/site-packages/torch/lib/libtorch_python.so)

Process finished with exit code 1
```

Can you check if `import torch` works in your env?

**Comment by songyuc** [comment]
Hi, @JanuszL ,
Indeed it is an error caused by torch.
Thanks sincerely!

**Comment by songyuc** [comment]
Hi, @JanuszL,
`import torch` alone works fine, but this snippet trigger this error:
```python
from nvidia.dali import pipeline_def
import torch
from nvidia.dali.plugin.pytorch import DALIGenericIterator
```

**Comment by JanuszL** [comment]
@songyuc can you provide a simple standalone repro we can run on our side (the best would be a step-by-step guide on how to set the environment up in the docker)?

**Comment by songyuc** [comment]
Let me take a closer look at it.
