### ISSUE TITLE
I meet the error which called 'dali::CUDAError', could you help me solve it?

### ISSUE THREAD

**Issue by cailijing** [NVIDIA/DALI#4393]
The error message is as follows..
File "/home/cljcode/MDInet/network/MDInet/MDInet_20221018.py", line 1174, in forward
    offset = offset + flow.flip(1).repeat(1, offset.size(1) // 2, 1, 1)
RuntimeError: CUDA error: an illegal memory access was encountered
terminate called after throwing an instance of 'dali::CUDAError'
  what():  CUDA runtime API error cudaErrorIllegalAddress (700):
an illegal memory access was encountered

**Comment by JanuszL** [comment]
Hi @cailijing,

Can you tell me more about the DALI version, GPU model, and driver version you use?
Does this problem also happen when you run DALI without training?
Due to the asynchronous GPU execution model, errors are not reported instantly after issuing the offending call, it is likely that when DALI checks the execution status it catches an error caused by some other library.
You can also check `dmesg` output and see if there are any relevant GPU-related logs.

**Comment by cailijing** [comment]
Hello @JanuszL ,
The nvidia-dali-cuda110 version is 1.2.0, and other information: GTX3090Ti, Driver Version, 470.141.03, CUDA Version, 11.4 .
The problem happens when I training the ModulatedDeformConv2d provided by mmcv.
I run the code in the docker. Dmesg could not be used in it.

**Comment by mzient** [comment]
This is a very old version. If possible, try to update.

**Comment by cailijing** [comment]
@mzient Hello,
I have updated dali to version 1.18. But the problem still occurs when training with multiple gpus

**Comment by cailijing** [comment]
When using single gpu for training, the error did not occur. But the error was happened by multiple gpus. What is the reason for it?

**Comment by JanuszL** [comment]
@cailijing,

Could be. Can you provide a standalone and self-contained reproduction sample so we can debug this on our side?

**Comment by cailijing** [comment]
@JanuszL Hello,could you give me an email?

**Comment by JanuszL** [comment]
Feel free to use [Dali-Team@nvidia.com](mailto:Dali-Team@nvidia.com).

**Comment by cailijing** [comment]
@JanuszL Hello，the email has been sent. Please check it, thank you.

**Comment by JanuszL** [comment]
@cailijing,

Thank you. Let us continue the discussion over email.

**Comment by JanuszL** [comment]
To sum up the email discussion. The issue seems to come from `modulated_deformable_im2col_gpu_kernel` that is a part of [mmcv](https://github.com/open-mmlab/mmcv/blob/master/mmcv/ops/csrc/common/cuda/modulated_deform_conv_cuda_kernel.cuh) and is not related to DALI.
