### ISSUE TITLE
`DALIGenericIterator` parameter `data_layout` not expected

### ISSUE THREAD

**Issue by elmuz** [NVIDIA/DALI#4408]
I noticed that default returned data layout for `fn.readers.video` is of the kind `[B, T, H, W, C]`. This is if leaving all the settings as default.

This is already in contrast to what is stated in the documentation:
> data_layout (str, optional, default = 'NCHW') – Either ‘NHWC’ or ‘NCHW’ - layout of the pipeline outputs.

However, passing explicitly that argument in the iterator constructor (e.g. `data_layout="NCHW"`) raises a `TypeError` exception:
> TypeError: __init __() got an unexpected keyword argument 'data_layout'

It also seems to me that there is no trace of it in the [code](https://github.com/NVIDIA/DALI/blob/main/dali/python/nvidia/dali/plugin/pytorch.py#L74).

Any hint on this?

https://github.com/NVIDIA/DALI/issues/4408#tasklist-block-93d8930f-76f1-4f3d-83f0-a539350e96e9

**Comment by jantonguirao** [comment]
Hi @elmuz. Thanks for reporting this issue. It seems that the documentation is wrong on that one. PyTorch iterator has no such argument and does not need one. It was probably copied from MXNet iterator which does have a `data_layout` argument. We will update the documentation.

**Comment by elmuz** [comment]
Thank you! However, I think that the default behavior should be in line with PyTorch layout of being channel front. Not a big deal though, but I believe that the possibility of choosing between "NCHW" and "NHWC" (with "NCHW" default for PyTorch) is nice.

**Comment by elmuz** [comment]
Ah, I see. Thanks for clarifying.

**Comment by jantonguirao** [comment]
Closing this issue now. If you still need help, please reopen.
