### ISSUE TITLE
Argument "output" is not support by operator Decoders_image

### ISSUE THREAD

**Issue by leo-XUKANG** [NVIDIA/DALI#4413]
my code is this
https://docs.nvidia.com/deeplearning/dali/archives/dali_1_18_0/user-guide/docs/examples/general/data_loading/external_input.html

all the same!

and my image's format is png or jpeg,

no matter what i do, i can't fix it,

and i use nvidia-dali-cuda110==1.18.0
centos
python3.9

Anyone can help me?

the error is 
![image](https://user-images.githubusercontent.com/28701457/199690506-0314c999-c826-4f67-ad72-c4241cc77997.png)

**Comment by JanuszL** [comment]
Hi @leo-XUKANG,

Can you examine all places where you call `decoders.image` and if you use `output_type` argument as in the example, not `output` as in the error message?
I just run the mentioned example without any problems.

**Comment by leo-XUKANG** [comment]
> Hi @leo-XUKANG,
> 
> Can you examine all places where you call `decoders.image` and if you use `output_type` argument as in the example, not `output` as in the error message? I just run the mentioned example without any problems.

i fix the bug now, sorry, it's my problem, God, it is crazy, i got 5327 samples/s!
