### ISSUE TITLE
The pip command install dali 0.27.0 on python-3.11-conda environment 

### ISSUE THREAD

**Issue by songyuc** [NVIDIA/DALI#4417]
Hi, guys,
I am trying to install the latest dali release on my python-3.11-conda environment,  and I run the [pip-command](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/installation.html#pip-official-releases:~:text=nvidia%2Ddali%2Dcuda102-,for%20CUDA%2011.0%3A,-pip%20install%20%2D%2Dextra) in the doc.
But I found that the dali 0.27.0 had been installed as:
![image](https://user-images.githubusercontent.com/27288110/200113941-fdc7af66-1e44-428a-915e-8ba49e1c47ac.png)

So, does dali support python 3.11 now?

Your answer and guide will be appreciated! 

https://github.com/NVIDIA/DALI/issues/4417#tasklist-block-47092442-4290-44e1-a322-85eb4609d56b

**Comment by JanuszL** [comment]
Hi @songyuc,

I'm sorry but DALI doesn't support python 3.11 yet. Version 0.27 is installed as before 0.28 there was no proper python version specifier in the wheel manifest. It was added in 0.28 - see [this line](https://github.com/NVIDIA/DALI/blob/release_v0.28/dali/python/setup.py.in#L26).

**Comment by songyuc** [comment]
Hi, @JanuszL,
Will the support of python 3.11 be added to the following visible roadmap, like [[DALI 2022 roadmap]](https://github.com/NVIDIA/DALI/issues/3774)?

**Comment by JanuszL** [comment]
We don't plan to support python 3.11 yet. Maybe next year as an experimental feature, as just 3.10 has been widely adopted by the available frameworks.

**Comment by songyuc** [comment]
Thanks sincerely for your response, and look forward to the future support🥳

**Comment by songyuc** [comment]
Hi, @JanuszL,
Will the support of python 3.11 be added to the following roadmap, like [[DALI 2023 roadmap]](https://github.com/NVIDIA/DALI/issues/4578)?

**Comment by songyuc** [comment]
I tried the [pip](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/installation.html#nvidia-dali) command of CUDA 11 on my Ubuntu, which has a strange behavior of downloading every history dalis.
And here is the screenshot as
![image](https://user-images.githubusercontent.com/27288110/225307291-084eb521-1a0d-4b63-828a-255c01dd6e95.png)

**Comment by JanuszL** [comment]
@songyuc,

I just checked on my side and it works fine:
```
python3.11 -m pip install --extra-index-url https://developer.download.nvidia.com/compute/redist --upgrade nvidia-dali-cuda110
Looking in indexes: https://pypi.org/simple, https://developer.download.nvidia.com/compute/redist
Collecting nvidia-dali-cuda110
  Downloading https://developer.download.nvidia.com/compute/redist/nvidia-dali-cuda110/nvidia_dali_cuda110-1.23.0-7355173-py3-none-manylinux2014_x86_64.whl (485.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 485.4/485.4 MB 4.5 MB/s eta 0:00:00
Collecting astunparse>=1.6.0
  Downloading astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Collecting gast<=0.4.0,>=0.2.1
  Downloading gast-0.4.0-py3-none-any.whl (9.8 kB)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/lib/python3/dist-packages (from astunparse>=1.6.0->nvidia-dali-cuda110) (0.37.1)
Collecting six<2.0,>=1.6.1
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: six, gast, astunparse, nvidia-dali-cuda110
Successfully installed astunparse-1.6.3 gast-0.4.0 nvidia-dali-cuda110-1.23.0 six-1.16.0
```
The way I tested it:
```
docker run --rm -ti ubuntu:22.10

apt update && apt install -y python3.11 wget -y && \
wget https://bootstrap.pypa.io/get-pip.py && \
python3.11 get-pip.py && \
python3.11 -m pip install --extra-index-url https://developer.download.nvidia.com/compute/redist --upgrade nvidia-dali-cuda110 && \
python3.11 -c "import nvidia.dali"
```

**Comment by songyuc** [comment]
Thanks sincerely for your information. The issue does not appear now.
