### ISSUE TITLE
Implementing Pytorch Dataloder with DALI Pipeline

### ISSUE THREAD

**Issue by debasishaimonk** [NVIDIA/DALI#4435]
Hi!

Lately i have been trying to implement my pytorch dataloader with the DALI  pipeline.

Basically i have a class which inherits dataset class of pytorch and it return 12 outputs in the return part of the __get_item() of it, and this class performs different customized augmentations. 
is it possible to return 12 outputs from my pipeline?? and would my customized augmentation will create any problem while building the pipeline?

**Comment by JanuszL** [comment]
Hi @debasishaimonk,

There is no limit to the number of DALI pipeline outputs. In the [augmentation gallery example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/image_processing/augmentation_gallery.html) we return multiple outputs - one per each augmentation.

**Comment by debasishaimonk** [comment]
i would be writing a dummy example(basically this is how i want to like to implement)

Class ImageDataset(Dataset):
      def __init___():
            ## initializing here

     def aug_fun_1():
           ##custom defined augmentation using pytorch
    
     def aug_fun_2():
           ##another customed defined augmentation in pytorch

     def __get__item():
           ##calling here my custom defined function and implemeting on the image read using cv2. and after that returning my     
                 3 outputs here(i.e orignal image,augmentedimage1,augmentedimage2)

How should i implement this in my Pipeline?? this pipeline should return those 3 outputs

**Comment by JanuszL** [comment]
Hi @debasishaimonk,

If your custom-defined operations in PyTorch can be expressed using DALI operators you can:
```
@pipeline_def()
def three_outs_pipepline(path):
    encoded, _= fn.readers.file(...)
    images = fn.decoders.image(encoded, device = "mixed", output_type = types.RGB)
    res1 = op1(images)
    res2 = op2(images)
    res3 = op3(images)
    return res1, res2, res3
```
However, if the DALI operator coverage is not sufficient, please check [this guide](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/custom_operations/index.html) on how to extend it.
