### ISSUE TITLE
module 'nvidia.dali.ops' has no attribute 'readers'

### ISSUE THREAD

**Issue by zhangbo9674** [NVIDIA/DALI#4437]
Hi, my develop environment is Python3.7 cuda11.2, and install dali by: `pip3.7 install --extra-index-url https://developer.download.nvidia.com/compute/redist nvidia-dali-cuda110`.
But i get an error: `module 'nvidia.dali.ops' has no attribute 'readers'`.

**Comment by JanuszL** [comment]
Hi @zhangbo9674,

Can you tell me what DALI version you have installed?
In my case `import nvidia.dali.ops.readers` works fine.

**Comment by JanuszL** [comment]
Hi @zhangbo9674,

DALI version 0.24 is old and I have no idea why it installs by default in your case.
In my case I get 1.19 and it works as expected:
```
docker run --gpus=all --rm -ti ubuntu:18.04

apt update && apt install -y python3.7 python3-pip -y && \
python3.7 -m pip install --upgrade pip && \
python3.7 -m pip install --extra-index-url https://developer.download.nvidia.com/compute/redist nvidia-dali-cuda110 && \
python3.7 -c "import nvidia.dali.ops.readers"
```

**Comment by zhangbo9674** [comment]
Thank you for your advice！
