### ISSUE TITLE
May I use ninja to build my custom operator?

### ISSUE THREAD

**Issue by songyuc** [NVIDIA/DALI#4439]
Hi, guys,
I am learning C++ for customizing my own operator.
The official doc uses makefile to build the library, and I want to know if I can use ninja to build my custom operator.

Your answer and guide will be appreciated!

https://github.com/NVIDIA/DALI/issues/4439#tasklist-block-a9c3328b-0daf-4f9d-ad09-56ea2f0592fd

**Comment by JanuszL** [comment]
Hi @songyuc,

You can use any build system you want. It is orthogonal to the plugin itself. ninja should work fine.

**Comment by songyuc** [comment]
@JanuszL, thanks sincerely for your help!
