### ISSUE TITLE
Can't download nvidia_dali

### ISSUE THREAD

**Issue by aihcyllop** [NVIDIA/DALI#4444]
Hi, I use the following 2 instructions, it always failed.
Is any other method to install nvidia-dali-cuda110? 
Thanks!
 
pip install --extra-index-url https://developer.download.nvidia.com/compute/redist/nvidia-dali-cuda110==1.19.0
https://developer.download.nvidia.com/compute/redist/nvidia-dali-cuda110/nvidia_dali_cuda110-1.19.0-6205436-py3-none-manylinux2014_x86_64.whl

**Comment by jantonguirao** [comment]
I think there's a typo in your command. You are joining the extra-index-url with the package name. Please try:
```pip install --extra-index-url https://developer.download.nvidia.com/compute/redist --upgrade nvidia-dali-cuda110==1.19.0```

**Comment by jantonguirao** [comment]
Closing this issue now. If you still need help, please reopen.
