### ISSUE TITLE
Why is there a difference of `const auto &input = ws.template Input<Backend>(0);` between the doc and the main branch code for custom operator definition 

### ISSUE THREAD

**Issue by songyuc** [NVIDIA/DALI#4455]
Hi, guys,
I am learning DALI doc today and I found there is a difference between the doc and the main branch code for custom operator definition  for `SetupImpl()` as:
SetupImpl() in the [doc](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/custom_operations/custom_operator/create_a_custom_operator.html#:~:text=bool%20SetupImpl(std%3A%3Avector%3C%3A%3Adali%3A%3AOutputDesc%3E%20%26output_desc%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20const%20%3A%3Adali%3A%3Aworkspace_t%3CBackend%3E%20%26ws)%20override%20%7B%0A%20%20%20%20const%20auto%20%26input%20%3D%20ws.template%20Input%3CBackend%3E(0)%3B):
```cpp
  ...
  bool SetupImpl(std::vector<::dali::OutputDesc> &output_desc,
                 const ::dali::workspace_t<Backend> &ws) override {
    const auto &input = ws.template Input<Backend>(0);
...
```
SetupImpl() in the [main-branch](https://github.com/NVIDIA/DALI/blob/main/docs/examples/custom_operations/custom_operator/customdummy/dummy.h#L28-L30):
```cpp
...
  bool SetupImpl(std::vector<::dali::OutputDesc> &output_desc,
                 const ::dali::Workspace &ws) override {
    const auto &input = ws.Input<Backend>(0);
...
```
It can be seen that `ws.template` is used in the [doc](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/custom_operations/custom_operator/create_a_custom_operator.html#:~:text=bool%20SetupImpl(std%3A%3Avector%3C%3A%3Adali%3A%3AOutputDesc%3E%20%26output_desc%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20const%20%3A%3Adali%3A%3Aworkspace_t%3CBackend%3E%20%26ws)%20override%20%7B%0A%20%20%20%20const%20auto%20%26input%20%3D%20ws.template%20Input%3CBackend%3E(0)%3B).
So, which one is the most recommended way?

Your answer and guide will be appreciated!

**Comment by klecki** [comment]
Hi @songyuc,
there was a C++ API refactoring in place, that unified the Workspace types. 
The main branch has the up-to-date API, and it can be seen in the nightly docs tutorial: https://docs.nvidia.com/deeplearning/dali/main-user-guide/docs/examples/custom_operations/custom_operator/create_a_custom_operator.html

We don't do such changes too often, but we don't promise that the C++ API won't change.

**Comment by klecki** [comment]
There is a VERSION file: https://github.com/NVIDIA/DALI/blob/main/VERSION, but looking through code, we expose it only in Python as a `__version__` variable: https://github.com/NVIDIA/DALI/blob/main/dali/python/__init__.py.in#L16 
It is obtained here from the VERSION file: https://github.com/NVIDIA/DALI/blob/main/CMakeLists.txt#L179
We probably should introduce some version defines to C++ but for now you would need to rely on the file. 
Typically it's either `1.XX.0dev` for main branch and `1.XX.Y` for release branches.

**Comment by songyuc** [comment]
Drawing on the documentation, I think we can use `COMMAND python` within CMake and to check DALI version to make sure its version is no higher than 1.19.0. I will learn more about CMake and try to do this.
Or is there a planned release date for DALI 1.20.0, as I think I can also wait for DALI 1.20.0 and then use the new API.

**Comment by klecki** [comment]
We are keeping a monthly cadence of the releases, the next one is planned around end of this month.

In the meantime you can check our nightly and weekly builds: https://docs.nvidia.com/deeplearning/dali/user-guide/docs/installation.html#pip-nightly-and-weekly-releases (both already include this change).

**Comment by songyuc** [comment]
Thanks sincerely again for the guide!
