### ISSUE TITLE
How to customize input and output based on C++extension?

### ISSUE THREAD

**Issue by cvnovice95** [NVIDIA/DALI#4463]
Hi, I read the document: `https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/custom_operations/custom_operator/create_a_custom_operator.html`
but I have the following question.
1. How to customize any data input and output formats, such as {tensor,...} or [{"a": tensor}, etc.

**Comment by jantonguirao** [comment]
Hi @cvnovice95.
I don't fully understand your question. Could you please give us more details?
Do you mean defining the number inputs of your custom operator? Perhaps if you give us an example of what you'd like to have as an input we can give you some advice.

**Comment by cvnovice95** [comment]
@jantonguirao  Thank you for your reply. I have an example of this.   The input of data is as follows， 
``` 
A = torch.ones((100,100))
B = torch.ones((100,100))
Inputs = { "key_name": [A,B]}
```
I want to customize input like this based C++ extension.

**Comment by jantonguirao** [comment]
Please correct me if I am wrong. It seems that in your example A and B are two independent samples in the batch. DALI already takes care of batching, so all you have to do is set your pipeline batch size to 2.
In such case, all you need to do is write your operator to accept one input:
```
DALI_SCHEMA(YourCustomOperator)
    .DocStr("...")
    .NumInput(1)
    .NumOutput(1);
```
Our inputs are not named though, so you'd use your operator like this
```
@pipeline_def(...)
def your_pipeline():
    data = ... 
    output= your_custom_operator(data)
    return output
```
What your operator sees is a batch of samples, but in the pipeline definition it looks as if it was one sample (we do not explicitly handle batch information in the pipeline definition)

**Comment by cvnovice95** [comment]
@jantonguirao 
```
A = torch.ones((100,100))
B = torch.ones((10,20))
Inputs = { "key_name": [A,B]}
```
Can I customize input like dict format, meanwhile not aligned tensor in batch.

**Comment by jantonguirao** [comment]
We do not accept dictionaries as inputs. Our inputs are positional only ```operator(input_0, input_1, ...)```

**Comment by jantonguirao** [comment]
Closing this issue now. If you still need help, please reopen.
