### ISSUE TITLE
Dali normalization different results from numpy normalization

### ISSUE THREAD

**Issue by Voveka98** [NVIDIA/DALI#4469]
Hi! I faced a problem with image normalization using fn.normalize
I saw this issue (https://github.com/NVIDIA/DALI/issues/3610) but it doesnt help me.
I have dali preprocessing with next code: (Input images usually have shape (1280, 720) but can be bigger.
The idea to get padded images with shape (640, 640) and height-width ratio as in input image.

```
IMAGE_SIZE = (640, 640)
MEAN = np.asarray([0.485, 0.456, 0.406])[None, None, :]
STD = np.asarray([0.229, 0.224, 0.225])[None, None, :]
SCALE = 1 / 255.

OUTPUT_DIR = os.path.dirname(os.path.abspath(__file__))


@pipeline_def(batch_size=32, num_threads=4)
def TritonLoadingPipeline():
    img_files = fn.external_source(name="DALI_INPUT_REC_0")
    orig_images = fn.decoders.image(
        img_files,
        device="mixed",
    )

    shapes = fn.shapes(orig_images, dtype=types.INT64)
    h = fn.slice(shapes, 0, 1, axes=[0])
    w = fn.slice(shapes, 1, 1, axes=[0])
    applied_ratio = max(IMAGE_SIZE) / math.max(h, w)
    resized_images = fn.resize(
        orig_images,
        resize_longer=max(IMAGE_SIZE),
        dtype=types.FLOAT,
        device="gpu"
    )

    normalized_images = fn.normalize(
        resized_images,
        mean=MEAN / SCALE,
        stddev=STD,
        scale=SCALE,
        dtype=types.FLOAT,
        device="gpu",
    )

    padded_images = fn.pad(
        normalized_images,
        axis_names="HW",
        shape=IMAGE_SIZE,
        device="gpu",
    )

    return padded_images, fn.reshape(applied_ratio, shape=[-1, 1])
```

In next steps I get dali outputs
`imgs = pb_utils.get_input_tensor_by_name(request, "PREPROC_REC_INPUT").as_numpy()` and infer my model, but results are different from torch version. If i delete fn.normalize and normalize it with numpy later as 
```
imgs = pb_utils.get_input_tensor_by_name(request, "PREPROC_REC_INPUT").as_numpy()
normalized_imgs = (imgs / 255 - MEAN.reshape((1, 3, 1, 1))) / STD.reshape((1, 3, 1, 1))
```

Example of image difference:
<img width="861" alt="image" src="https://user-images.githubusercontent.com/34947202/204286747-22fc90b9-5872-44d6-9a95-6ca34dcf3b39.png">

i get different results.
What can be the reason of problem?
Thanks in advance

**Comment by JanuszL** [comment]
Hi @Voveka98,

Thank you for reporting this problem. I'm sorry but I cannot reproduce the issue you described. Please check my [jupyter notebook](https://github.com/NVIDIA/DALI/files/10108063/normalize.zip) I used. Can you provide a self-contained repro I can use?

**Comment by Voveka98** [comment]
Hi @JanuszL!

Thanks for sharing your notebook it helped me to find out that problem is another step of pipeline.
Normalizing via dali and python really gives same results
Thx again)
