### ISSUE TITLE
Best way to handle random order of color ops for ColorTwist?

### ISSUE THREAD

**Issue by jramapuram** [NVIDIA/DALI#4471]
In pytorch [ColorJitter](https://pytorch.org/vision/main/_modules/torchvision/transforms/transforms.html#ColorJitter) applies the color operations in random order, i.e. :

```python
        fn_idx = torch.randperm(4)
...
        for fn_id in fn_idx:
            if fn_id == 0 and brightness_factor is not None:
                img = F.adjust_brightness(img, brightness_factor)
            elif fn_id == 1 and contrast_factor is not None:
                img = F.adjust_contrast(img, contrast_factor)
            elif fn_id == 2 and saturation_factor is not None:
                img = F.adjust_saturation(img, saturation_factor)
            elif fn_id == 3 and hue_factor is not None:
                img = F.adjust_hue(img, hue_factor)
```

However I believe in DALI the ops (AFAIK) are of [fixed order](https://github.com/NVIDIA/DALI/blob/main/dali/operators/image/color/color_twist.h#L158-L172) ? 

Is the recommended way to parallel this still muxing?

**Comment by JanuszL** [comment]
Hi @jramapuram,

For now, we don't fully support conditional execution in the way you are asking for, still what you can do is:
```
def appply_conditionally(value, neutral_value, predicate, idx):
    predicate = predicate == idx
    return predicate * value + (1 - predicate) * neutral_value

fn_idx = fn.random.uniform(values=[0, 1, 2, 3, 4], dtype=types.INT8)
brightness = appply_conditionally(brightness_factor, 1, fn_idx, 1)
contrast = appply_conditionally(contrast_factor, 1, fn_idx, 2)
saturation = appply_conditionally(saturation_factor , 1, fn_idx, 3)
hue = appply_conditionally(hue_factor, 1, fn_idx, 4)
images = fn.color_twist(images, brightness=brightness, contrast=contrast, saturation=saturation, hue=hue)
```

**Comment by jramapuram** [comment]
Thanks for the snippet @JanuszL . Appreciate it!

I believe this is slightly different though in that it either enables or disables {brightness, contrast, saturation, hue} in the `ColorTwist` op whereas the pytorch version applies {brightness, contrast, saturation, hue} in a random order (since order does matter for some of these color transforms)?

Will try this to see the model perf tradeoff though! Revisiting DALI for a high performant loader for SSL augmentations :)

**Comment by mzient** [comment]
@jramapuram There's another option that will yield slightly different results (it will avoid clipping in intermediate images) but should be much faster to run.
Basically, all of the operations are just linear transformations of RGB vectors. We can look at an image a a set of 3D points in RGB space and use `fn.coord_transform` to process the color data. We can then produce matrices for all transforms and combine them. Since DALI doesn't have a permutation operator, it would probably be easiest to just use `fn.external_source` to provide the transform matrices.
```Python
import nvidia.dali as dali
import nvidia.dali.fn as fn
import numpy as np

def chain(*matrices):
    ret = 1
    for m in matrices:
        if ret is 1:
            ret = m
        else:
            ret = np.matmul(ret, m)
    return ret

rgb2yiq = np.array([[0.299,  0.587,  0.114, 0],
                    [0.596, -0.274, -0.321, 0],
                    [0.211, -0.523,  0.311, 0],
                    [    0,      0,      0, 1]])
yiq2rgb = np.linalg.inv(rgb2yiq)

def adjust_hue(h):
    h_rad = h * np.pi / 180
    c = np.cos(h_rad)
    s = np.sin(h_rad)
    M = np.array([[1,  0, 0, 0],
                  [0,  c, s, 0],
                  [0, -s, c, 0],
                  [0,  0, 0, 1]])
    return chain(yiq2rgb, M, rgb2yiq)

def adjust_saturation(s):
    M = np.array([[1,  0, 0, 0],
                  [0,  s, 0, 0],
                  [0,  0, s, 0],
                  [0,  0, 0, 1]])
    return chain(yiq2rgb, M, rgb2yiq)

def adjust_brightness(b):
    return np.array([[b, 0, 0, 0],
                     [0, b, 0, 0],
                     [0, 0, b, 0],
                     [0, 0, 0, 1]])

def adjust_contrast(c, neutral=0.5):
    return np.array([[c, 0, 0, 0.5 - c * 0.5],
                     [0, c, 0, 0.5 - c * 0.5],
                     [0, 0, c, 0.5 - c * 0.5],
                     [0, 0, 0, 1]])
                    
def color_augment(order, h, s, b, c):
    transforms = [
        adjust_hue(h),
        adjust_saturation(s),
        adjust_brightness(b),
        adjust_contrast(c)
    ]
    transforms = [transforms[idx] for idx in order]
    M = chain(*transforms)[:3]  # strip the last row
    return M.astype(np.float32)
```
This can be fed to external source, e.g.:
```
def rescale(normalized, lo, hi):
    return lo + normalized * (hi - lo)

from itertools import permutations
# this applies some fixed transforms in all possible orders
def get_transform(info):
    return [color_augment(order, 15, 1.5, 2, 0.4) for order in permutations([0,1,2,3])]

@dali.pipeline_def(batch_size=24, device_id=0, num_threads=4)
def my_pipe():
    transform = fn.external_source(source=get_transform, batch=True)
    images, _ = fn.readers.file(file_root=".", files=["lena.png"])
    images = fn.decoders.image(images) * (1/255)
    return fn.cast(fn.coord_transform(images, MT=transform) * 255, dtype=dali.types.UINT8)

pipe = my_pipe()
pipe.build()
out, = pipe.run()
```
The result
![image](https://user-images.githubusercontent.com/17044837/204766535-ff4563ef-91c5-49d0-9c97-f7b2058db939.png)

To get something more useful, replace the get_transform function with:
```Python
def get_transform():
    h, s, b, c = np.random.rand(4)
    h = rescale(h, -45, 45)
    s = rescale(s, 0, 2)
    b = rescale(b, 0.5, 1.5)
    c = rescale(c, 0.5, 2)
    order = np.random.permutation(4)
    return color_augment(order, h, s, b, c)
```
and set the `batch` parameter of `external_source` to `False`:
```Python
    transform = fn.external_source(source=get_transform, batch=False)
```
A possible result (it's random, so it's different each time you run it):
![image](https://user-images.githubusercontent.com/17044837/204765719-3da662ec-ccf6-471d-9458-6c429662321e.png)

**Comment by jramapuram** [comment]
Many thanks @mzient 🙏 ! Love the first principles based approach here. Very elegant.

Few queries:
1. The speed of this op (with `batch=False`) seems to be a bit slower in practice (322 s / epoch on ImageNet1k vs. 307 s / epoch for @JanuszL's solution -- all other things being equal; will try a few more times for statistical significance though) on 16x A100s with pytorch. Should the matmuls be handled in a DALI primitive type to speed things up? Or could the issue be that we need spawn some py_workers?
2. I'm trying to match the ranges from pytorch's `ColorJitter`. Do you think the following defaults make sense?
```tex
b : [0, 1.0 - b]  # no upper bound, eg: b=0.4
c : [0, 1.0 + c]  # no upper bound, eg: c=0.4
s : [0, 1.0 + s]  # no upper bound, eg: s=0.2
h : [0, 360]      # since we are computing in degrees, eg: 45
```

**Comment by JanuszL** [comment]
Hi @jramapuram,

You can try enabling the `parallel` option in [the external source operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.external_source.html) to speed things up.

**Comment by jramapuram** [comment]
Cool, I was able to shave it down from 322 s/epoch to around 310 s/epoch with : 
- parallel=True 
- py_num_workers=4 
            prefetch_queue_depth=2,
            py_start_method="spawn",
