### ISSUE TITLE
External Source fails to work without labels.

### ISSUE THREAD

**Issue by thisistejaspandey** [NVIDIA/DALI#4482]
Sorry if this is a noob question. I am following the example here: 
https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/external_input.html
It fails to work when there are only batched images and no labels. Adding a random label fixes the issue with warnings.

Is this the intended behavior? Is there a way to directly convert list/numpy arrays to DALI tensors.

Original code:

    class NuScenesFileReader:
        def __init__(self, nusc, batch_size=8):
            self.nusc = nusc
            self.batch_size = batch_size
            self.files = self.load_files()
            self.index = 0
            self.num_files = len(self.files)
    
        def load_files(self):
            files = []
            for scene in self.nusc.scenes:
                for sample in scene.samples:
                    files.append(os.path.join(self.nusc.dataroot, sample.CAM_FRONT.filename))
            return files
    
        def __iter__(self):
            self.index = 0
            self.num_files = len(self.files)
            return self
    
        def __next__(self):
            batch = []
            for _ in range(self.batch_size):
                jpeg_filename = self.files[self.index]
                f = open(jpeg_filename, 'rb')
                batch.append(np.frombuffer(f.read(), dtype=np.uint8))
                self.index = (self.index + 1) % self.num_files
            return (batch)

    class NuScenesDataloader:
        def __init__(self, nusc, batch_size=8):
            self.file_reader = NuScenesFileReader(nusc, batch_size=batch_size)
            self.pipe = self.my_pipeline(batch_size=batch_size, num_threads=2, device_id=0)
            self.pipe.build()
    
        @pipeline_def
        def my_pipeline(self):
            jpegs = fn.external_source(self.file_reader, num_outputs=1, dtype=types.UINT8)
            # decode = fn.decoders.image(jpegs, device="mixed", output_type=types.RGB)
            return jpegs
    
        def __next__(self):
            return self.pipe.run()

Error:

    TypeError: Illegal pipeline output type. The output 0 contains a nested `DataNode`. Missing list/tuple expansion (*) is the likely cause.

With label: 

    class NuScenesFileReader:
        def __init__(self, nusc, batch_size=8) -> None:
            self.nusc = nusc
            self.batch_size = batch_size
            self.files = self.load_files()
            self.index = 0
            self.num_files = len(self.files)
    
        def load_files(self):
            files = []
            for scene in self.nusc.scenes:
                for sample in scene.samples:
                    files.append(os.path.join(self.nusc.dataroot, sample.CAM_FRONT.filename))
            return files
    
        def __iter__(self):
            self.index = 0
            self.num_files = len(self.files)
            return self
    
        def __next__(self):
            batch = []
            for _ in range(self.batch_size):
                jpeg_filename = self.files[self.index]
                f = open(jpeg_filename, 'rb')
                batch.append(np.frombuffer(f.read(), dtype=np.uint8))
                self.index = (self.index + 1) % self.num_files
            return (batch, 0)

    class NuScenesDataloader:
        def __init__(self, nusc, batch_size=8):
            self.file_reader = NuScenesFileReader(nusc, batch_size=batch_size)
            self.pipe = self.my_pipeline(batch_size=batch_size, num_threads=2, device_id=0)
            self.pipe.build()
    
        @pipeline_def
        def my_pipeline(self):
            jpegs, _ = fn.external_source(self.file_reader, num_outputs=2, dtype=types.UINT8)
            # decode = fn.decoders.image(jpegs, device="mixed", output_type=types.RGB)
            return jpegs
    
        def __next__(self):
            return self.pipe.run()

Warning:

    Warning: The external source node '<__main__.NuScenesFileReader object at 0x7f312a1a9dc0>' produces 2 outputs, but the output at the index 1 is not used. For best performance, adjust your callback so that it computes only the needed outputs.
      warnings.warn(
    (TensorListCPU(
        [[255 216 ... 255 217]
        [255 216 ... 255 217]
        ...
        [255 216 ... 255 217]
        [255 216 ... 255 217]],
        dtype=DALIDataType.UINT8,
        num_samples=8,
        shape=[(156379,),
               (154124,),
               (143855,),
               (137583,),
               (137836,),
               (141227,),
               (140893,),
               (138129,)]),)

**Comment by JanuszL** [comment]
Hi @thisistejaspandey,

According to [the external source operator documentation]():
```
num_outputs (int, optional) – If specified, denotes the number of TensorLists that are produced by the source function.

If set, the operator returns a list of DataNode objects, otherwise a single DataNode object is returned.
```
so you need:
```
    @pipeline_def
    def my_pipeline(self):
        [jpegs] = fn.external_source(self.file_reader, num_outputs=1, dtype=types.UINT8)
        # decode = fn.decoders.image(jpegs, device="mixed", output_type=types.RGB)
        return jpegs
```
or
```
    @pipeline_def
    def my_pipeline(self):
        jpegs = fn.external_source(self.file_reader, num_outputs=1, dtype=types.UINT8)
        # decode = fn.decoders.image(jpegs, device="mixed", output_type=types.RGB)
        return jpegs[0]
```
Also:
```
If num_outputs is not set, the source is expected to return one item (a batch or a sample). If this value is specified (even if its value is 1), the data is expected to a be tuple, or list, where each element corresponds to respective return value of the external_source.
```
So you need to:
```
    def __next__(self):
        batch = []
        for _ in range(self.batch_size):
            jpeg_filename = self.files[self.index]
            f = open(jpeg_filename, 'rb')
            batch.append(np.frombuffer(f.read(), dtype=np.uint8))
            self.index = (self.index + 1) % self.num_files
        return [batch]
```

**Comment by thisistejaspandey** [comment]
Thanks! This fixed the issue.
