### ISSUE TITLE
nvidia.dali.fn.experimental.decoders.video does not handle gray video properly

### ISSUE THREAD

**Issue by zeruniverse** [NVIDIA/DALI#4483]
When decoding `gray8` formatted frames, this decoder generates error. The sample mp4 video is: [sample mp4](https://user-images.githubusercontent.com/4648756/204992065-36369bb9-d630-4571-9264-78345be0da9a.mp4).

Error is (with device="mixed"):
```
RuntimeError: Critical error in pipeline:
Error when executing Mixed operator experimental__decoders__Video encountered:
Error in thread 0: CUDA driver API error CUDA_ERROR_NOT_SUPPORTED (801):
operation not supported
Current pipeline object is no longer valid.
```

with device="cpu", the decoding process succeeds, but it does not respect original number of channels (should be C=1, it generates C=3 results)

The repro code

```python
import numpy as np
class ExternalInputIterator(object):
    def __init__(self, batch_size):
        pass

    def __iter__(self):
        self.i = 0
        self.n = 1
        return self

    def __next__(self):
        return [np.frombuffer(open('black.mp4', 'rb').read(), dtype=np.uint8)]
import nvidia.dali as dali
from nvidia.dali import fn
import nvidia.dali.types as types
eii = ExternalInputIterator(1)
@dali.pipeline_def(batch_size=256, num_threads=12, device_id=0)
def i_pipeline():
    vid = fn.external_source(source=eii, device="cpu", name="INPUT_0", ndim=1, dtype=dali.types.UINT8)
    seq = fn.experimental.decoders.video(vid, device='mixed')
    return seq
pipe = i_pipeline()
pipe.build()
pipe.run()
```

The code to generate `black.mp4`:

```python
import av
import numpy as np
c = av.open('black.mp4', 'w', format='mp4')
s = c.add_stream(codec_name='libx265', rate=1)
s.pix_fmt='gray'
s.height, s.width = [300, 300]
for i in range(10):
    f = av.VideoFrame.from_ndarray(np.zeros((300, 300), dtype=np.uint8) + 18,format="gray8")
    for p in s.encode(f):
        c.mux(p)
for p in s.encode():
    c.mux(p)
c.close()
```

**Comment by JanuszL** [comment]
Hi @zeruniverse,

As far as [I see NVDEC](https://developer.nvidia.com/nvidia-video-codec-sdk) doesn't support monochromatic videos (400). https://github.com/NVIDIA/DALI/pull/4484 should improve the error reporting.
Long term we plan to add a fallback to the CPU decoder but is not there yet.

**Comment by zeruniverse** [comment]
Hi @JanuszL 

Thanks for fast reply and MR. In CPU mode, the monochromatic videos decode into channel 3 image sequences. Can DALI provide a flag to set number of output channels (or a flag to keep original number of channels)?

**Comment by JanuszL** [comment]
Hi @zeruniverse,

> Can DALI provide a flag to set number of output channels (or a flag to keep original number of channels)?

The issue is that the NVIDIA GPU hardware block responsible for decoding just cannot decode such videos, so it is not about DALI itself. All we can do long term is to fall back to the CPU for such videos.

**Comment by zeruniverse** [comment]
Thanks!
