### ISSUE TITLE
Convert TensorListGPU to CuPy array

### ISSUE THREAD

**Issue by Renzzauw** [NVIDIA/DALI#4488]
Hi!

I was wondering if it would be possible to zero-copy a pipeline's TensorListGPU output data directly to/as a CuPy array. 

I know it is possible with the PyTorch plugin to do this directly using a PyTorch Tensor, and CuPy supports zero-copy data exchange between Pytorch Tensors and CuPy arrays, since both support `__cuda_array_interface__` ([documented here](https://docs.cupy.dev/en/stable/user_guide/interoperability.html#pytorch)), so I have a feeling this should also be possible with CuPy. 

I'd prefer to do this directly without requiring to convert to a PyTorch tensor first (DALI -> PyTorch -> CuPy), since PyTorch takes quite a bit of time to initialize the CUDA context.

Thanks in advance!

**Comment by JanuszL** [comment]
Hi @Renzzauw,

Yes you can, just use `cupy.asarray(o)` where `o` is a DALI tensor, like in this example:
```
import numpy, cupy

from nvidia.dali import pipeline_def
import nvidia.dali.fn as fn

def cpu_cb(sample_info):
    return numpy.full((1, 1, 3), sample_info.idx_in_epoch, dtype=numpy.float32)

@pipeline_def
def pipeline():
    data = fn.external_source(source=cpu_cb, batch=False)
    data = data.gpu()
    return data


pipe = pipeline(batch_size=8, num_threads=4, device_id=0)
pipe.build()
o = pipe.run()[0].as_tensor()
o_cp = cupy.asarray(o)
print(o.__cuda_array_interface__['data'][0], o_cp.__cuda_array_interface__['data'][0])
```
Please keep in mind that DALI owns the memory it returns. And calling `run` invalidates the previous result.

**Comment by Renzzauw** [comment]
Hi @JanuszL, 

Thanks for such a fast reply! It works perfect on my end.

I'll close this issue as my question has been answered.
