### ISSUE TITLE
What are the indexes used for in the TFRecord reader?

### ISSUE THREAD

**Issue by pietroorlandi** [NVIDIA/DALI#4514]
Hi, thank you for your great work!
I use a _TFRecord_ reader to load data, but when I use it it also asks for an _index_path_ as an argument.
 I generated it with the script _tfrecord2idx_ but I wanted to ask what the indexes are for in this case? Are they just for faster shuffling?

**Comment by JanuszL** [comment]
Hi @pietroorlandi,

I believe that originally TF used one TFRecord file per shard, in the DALI case it is possible to have an arbitral number of files and shards. We use this index file to let DALI know how many samples there are and when the sharding happens to calculate the initial position in the file.
