### ISSUE TITLE
Nvidia DALI data processing under the hood

### ISSUE THREAD

**Issue by pietroorlandi** [NVIDIA/DALI#4516]
Hi, thank you for your great work, I wanted to better understand how NVIDIA DALI works to then improve my data-pipeline.
Is data processing done in batch?
For example in this code:
```@pipeline_def
def pipeline_training():
    # Make also data-augmentation with probability p=0.5
    inputs = fn.readers.tfrecord(
        path=tfrecord_train,
        index_path=tfrecord_idx_train,
        random_shuffle=True,
        features={
            "image" : tfrec.FixedLenFeature((), tfrec.string, ""),
            "label": tfrec.FixedLenFeature([1], tfrec.int64,  -1)
        })
    labels = inputs['label']
    images = inputs["image"]
    images = fn.reinterpret(images, dtype=types.FLOAT)
    images = fn.reshape(images, [3,32,32])
    images = images.gpu()
    labels = labels.gpu()
    images = fn.transpose(images, perm=[1,2,0])
    return (images, labels)

    with tf.device('/gpu:0'):
        pipe_train= pipeline_training(batch_size=64, device_id=0)

        # Create dataset
        dataset_train = dali_tf.DALIDataset(
            pipeline=pipe_train,
            batch_size=64,
            output_shapes=shapes,
            output_dtypes=(tf.float32, tf.int64),
            device_id=0)
        for el in dataset_train.take(4):
            do_something(el)
```
What seems to me to be done under the hood is this in this order:
  1) Read index from tfrecord_idx_train, and shuffling it  (executed on CPU)
  2) Read 64 sampes (batch_size) from TFRecord file (tfrecord_train) based on shuffling done on index (executed on CPU)
  3) Extract _labels_ and _images_ (executed on CPU)
  4) Using _fn.reinterpret_ on batch of images (executed on CPU)
  5) Using _fn.reshape_ on batch of images (executed on CPU)
  6) Copy the batch of images from CPU RAM to GPU memory
  7) Copy the batch of labels from CPU RAM to GPU memory
  8) Executing the _fn.transpose_ on batch of images to convert from CHW to HWC (executed on GPU)

Is that right?

**Comment by JanuszL** [comment]
Hi @pietroorlandi,

Yes, the description you provided is accurate. `fn.reinterpret` and `fn.reshape` changes only the interoperation of the underlying storage so are cheep and having them on the CPU is negligible from the performance point of view.

Regarding 1) and 2) DALI uses an internal shuffling buffer that is filled by the sequential reads from the TFRecord and then randomly samples to form the batch. So it is not possible to get the very last sample from the TFRecord in the first batch (assuming there is no sharding), and it is very unlikely to receive the very first sample in the last batch.

**Comment by pietroorlandi** [comment]
@JanuszL Thanks a lot!
I saw that both _DALIDataset_ and _Pipeline_ have the _prefetch_queue_depth_ parameter, and that by default it is set to 2. 
This parameter refers to the number of batches? So all the procedure done above will be done for two batches and not just one. So in 6) and 7) the two batches will be copied from CPU RAM to GPU memory and not only one batch? Am I wrong?

**Comment by JanuszL** [comment]
@pietroorlandi,

`prefetch_queue_depth` means how many batches, at most, can be ready to be consumed.

> So in 6) and 7) the two batches will be copied from CPU RAM to GPU memory and not only one batch? Am I wrong?

When the reader reads the first batch it tried to read another and another until there is a space in the output buffer. You can check our GTC talks ([this](http://on-demand.gputechconf.com/gtc/2018/presentation/s8906-fast-data-pipelines-for-deep-learning-training.pdf) or [this](https://developer.download.nvidia.com/video/gputechconf/gtc/2019/presentation/s9925-fast-ai-data-pre-processing-with-nvidia-dali.pdf)) ([videos are also available](https://github.com/NVIDIA/DALI#additional-resources)).

**Comment by pietroorlandi** [comment]
Okay thank you very much! @JanuszL 
Last question, since I didn't see it in the documentation: does NVIDIA DALI have a method to limit the values of an image between [0,1]? Because after operations like saturation sometimes the image has negative values, so I would need something to bring it back into the [0,1] range (something equivalent to tf.clip_by_value()).
To consider, however, that the data is already in the GPU.

**Comment by JanuszL** [comment]
Hi @pietroorlandi,

Please check [math functions](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/math.html#mathematical-functions), especially `nvidia.dali.math.clamp`.

**Comment by pietroorlandi** [comment]
Hi, I am rewriting here because I need more details, however if you prefer I can open a new issues, this will be a long question. I would have to understand in great detail what happens inside DALI, starting from the data source and ending with the batch in GPU memory ready to be pulled by Tensorflow. I would also need to understand the details related to data transfers, even perhaps at a low level.
For purposes of understanding, I have prepared a another simple code that uses DALI to do training of a convolutional neural network. The code is purposely not optimized to make it simpler and make the workflow description easier.
I tried to watch several DALI seminars like [this](https://on-demand.gputechconf.com/gtc/2018/presentation/s8906-fast-data-pipelines-for-deep-learning-training.pdf) this workflow is what I was able to understand from the information in them. If there are any errors (and it is likely) please also explain to me in detail what is going on.
(Note that the whole workflow is based on _num_threads=4_ and _batch_size=8_).
As I understand it, what happens in the code presented below is this:
1) Since there are 4 threads, and since CPU operators operate per-sample (as mentioned [here](https://on-demand.gputechconf.com/gtc/2018/presentation/s8906-fast-data-pipelines-for-deep-learning-training.pdf), the 4 threads process 4 samples (1 sample per thread). First they execute the TFRecord operator which is responsible for reading data from disk and decoding it. For reading each sample, **DMA is used to load the data from storage to CPU DRAM**, then once here the data is decoded. As soon as the sample is decoded, the thread also runs the CPU operator Hue on the sample, which applies the transformation on it. The sample is put into a buffer and since the thread has now finished its execution it can do the same process with another thread.
2) The threads do the same process as described in 1) for the other 4 samples (since the batch_size is 8 and only 4 samples have been put into the buffer for now)
3) When the buffer has reached batch_size, the data transfer from CPU DRAM to GPU memory takes place. **This data transfer occurs again using DMA,** which allows for optimized performance, and it is done through _.gpu()_ operator.
4) Now the batch is on GPU memory and is processed using _warp_affine_ GPU operator. GPU operators operate per-batch and are implemented through CUDA kernels.
5) The batch now resides in the GPU and has been transformed correctly. It is now ready for training via Tensorflow

For greater clarity of explanation, **I have also prepared a diagram present [here](https://pasteboard.co/zTrf9JeK4zeN.png)**.
Probably what I have said is not right, so please if something is not right or I am misunderstanding, it would be very kind if you could explain step by step what happens in the dataflow of the data using DALI, even getting to a low level of detail.
Thank you in advance!
```
from nvidia.dali import pipeline_def, Pipeline
import nvidia.dali.fn as fn
import nvidia.dali.types as types
import nvidia.dali.plugin.tf as dali_tf
import tensorflow.compat.v1 as tf_v1
import tensorflow as tf
import nvidia.dali.tfrecord as tfrec
from tensorflow.keras import layers
from tensorflow import keras

NUM_CLASSES = 10 # Cifar10 has 10 classes
BATCH_SIZE = 8
EPOCHS=5
SIZE_DATASET_TRAIN = 40000


# Set Memory Growth of tensorflow equals true so Tensorflow won't allocate all the GPU memory
gpus = tf.config.list_physical_devices('GPU')
if gpus:
    try:
        # Currently, memory growth needs to be the same across GPUs
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
        logical_gpus = tf.config.list_logical_devices('GPU')
        print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
    except RuntimeError as e:
        # Memory growth must be set before GPUs have been initialized
        print(e)

# PATH 
tfrecord_train = r"tfrecord_dataset/train/train.tfrecords" # train tfrecord file path
tfrecord_idx_train = r"tfrecord_dataset/idx_files/train.idx" # index-train path

# Set DALI pipeline for training
@pipeline_def
def pipeline_training():
    inputs = fn.readers.tfrecord(
        path=tfrecord_train,
        index_path=tfrecord_idx_train,
        random_shuffle=True,
        initial_fill=40000,
        features={
            "image" : tfrec.FixedLenFeature((), tfrec.string, ""),   
            "label": tfrec.FixedLenFeature([1], tfrec.int64,  -1)
        })
    labels = inputs['label']
    images = inputs["image"]
    images = fn.reinterpret(images, dtype=types.FLOAT) 
    images = fn.reshape(images, [32,32,3]) # Because images are saved in the format CHW and not in HWC
    images = fn.hue(images, hue=0.1)
    images = images.gpu() # Copy the data on GPU
    labels = labels.gpu()
    
    mt = fn.transforms.rotation(angle = fn.random.uniform(range=(-36,+36)), center=(16,16))
    random_zoom = fn.random.uniform(range=(0.8, 1.2)) # [-20%, +20%]
    mt = fn.transforms.scale(mt, scale = fn.stack(random_zoom, random_zoom), center=(16,16))
    augmented = fn.warp_affine(images, matrix = mt)

    return augmented, labels 



def main():    
    shapes = ((BATCH_SIZE, 32, 32, 3), (BATCH_SIZE))
    with tf.device('/gpu:0'):
        pipe_train= pipeline_training(batch_size=BATCH_SIZE, num_threads=4, device_id=0)
        dataset_train = dali_tf.DALIDataset(  
            pipeline=pipe_train,
            batch_size=BATCH_SIZE,
            output_shapes=shapes,
            num_threads=4,
            output_dtypes=(tf.float32, tf.int64),
            device_id=0)

        STEP_PER_EPOCH = SIZE_DATASET_TRAIN//BATCH_SIZE 

        model = tf.keras.Sequential([
        layers.Conv2D(64, 3, activation='relu'),
        layers.MaxPooling2D(),
        layers.Dropout(0.1),
        layers.Conv2D(128, 3, activation='relu'),
        layers.MaxPooling2D(),
        layers.Dropout(0.1),
        layers.Conv2D(128, 3, activation='relu'),
        layers.MaxPooling2D(),
        layers.Dropout(0.2),
        layers.Flatten(),
        layers.Dense(256, activation='relu'),
        layers.Dropout(0.3),
        layers.Dense(10, activation='softmax')
        ])
        adam_opt = keras.optimizers.Adam(learning_rate=0.001)
        model.compile(optimizer = adam_opt,
                    loss=tf.keras.losses.SparseCategoricalCrossentropy(),
                    metrics=['accuracy'])
        
        history = model.fit(dataset_train, 
                steps_per_epoch=STEP_PER_EPOCH, 
                epochs=EPOCHS,
                )
        return model, history

if __name__=='__main__':
    model, history= main()



```

**Comment by JanuszL** [comment]
Hi @pietroorlandi,

You are mostly correct regarding how DALI operates. Adding more details.
The `fn.readers.tfrecord` uses one thread to read data from the disc, and `num_threads` to parse the samples. DMA is not used, but DALI mmaps file to the memory and we copy from it directly saving on `read` syscalls.

> When the buffer has reached batch_size, the data transfer from CPU DRAM to GPU memory takes place. This data transfer occurs again using DMA, which allows for optimized performance, and it is done through .gpu() operator.

We are using `cudaMemcpyAsync` from pinned memory, on most platforms it indeed uses DMA between host and device memory, on some (like Jetson) it could be a plain copy as the memory is shared between CPU and GPU.

When the data is ready `DALIDataset` copies the memory from DALI to a TensorFlow tensor using fast device-to-device copy.

Could you tell me more about what concerns you? I can provide more details regarding this particular aspect of the DALI operator.

Also:
```
images = fn.reshape(images, [32,32,3]) # Because images are saved in the format CHW and not in HWC
```
Reinterprets the data, but it doesn't transpose it. If your images are saved as CHW you need to call [the `fn.transpose`](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.transpose.html) operator to convert them to `HWC`

**Comment by pietroorlandi** [comment]
Thank you for your constant help @JanuszL!
First I would like to start you off on the point regarding the _TFRecordReader_, once this is solved I will then ask you for more details on the rest.
I have looked at various books and sites (like [this](https://realpython.com/python-mmap/), but also [this paper](https://seec.cs.vt.edu/pubs/papers/pumma-lmdbio-lmm-hpcc2017.pdf)) to better understand file memory mapping but there are still some things that are not clear.
Is the whole file (so all the _train.tfrecords_ ) mapped to RAM memory? So as I understand it, with `mmap`, initially in memory there is no "real data" but it is the references (addresses) to the file. So if we initially try to read (and since initially the data is not there), _page fault_ happens, and the page-fault handler will issue an I/O request to read the page and its neighboring pages to memory. Is it right?

**Comment by JanuszL** [comment]
> First I would like to start you off on the point regarding the TFRecordReader, once this is solved I will then ask you for more details on the rest.
I have looked at various books and sites (like [this](https://realpython.com/python-mmap/), but also [this paper](https://seec.cs.vt.edu/pubs/papers/pumma-lmdbio-lmm-hpcc2017.pdf)) to better understand file memory mapping but there are still some things that are not clear.
Is the whole file (so all the train.tfrecords ) mapped to RAM memory? So as I understand it, with mmap, initially in memory there is no "real data" but it is the references (addresses) to the file. So if we initially try to read (and since initially the data is not there), page fault happens, and the page-fault handler will issue an I/O request to read the page and its neighboring pages to memory. Is it right?

Yes, that is correct. There is a parameter `dont_use_mmap=True` that switched to the regular `read`, and `read_ahead=True` asks the operating system to read the whole file ahead (using `MAP_POPULATE` flag in mmap call). The overall gain is still due to a lack of saving on issuing `read` syscall, which will do similar things *page fault* with additional syscall overhead.

**Comment by pietroorlandi** [comment]
Okay, I got it! However when it makes the I/O request (when page-fault happens), don't you use DMA to optimize the performance?
_read_ahead_ parameter refers to "regular read" or refers also to "mmap read"? Since I saw that the default value for this parameter is False, what portion of the file is mmapped (since it is not all mapped)?

**Comment by JanuszL** [comment]
> don't you use DMA to optimize the performance?

The DMA is usually used by the devices to access the memory from RAM directly without the need for CPU cycles. In our cases, we do need the CPU to be involved as it needs to read the data from the disc and move them to the RAM, which involves (AFAIK) the interpretation of the data representation in a given FS.
*read_ahead* applies to mmaped files. It doesn't affect the mapping but asks the OS to fill the memory with the real data ahead of time, not on demand so the page faults happened during mapping, not during the access itself.

**Comment by pietroorlandi** [comment]
Okay, so putting it all together you could say this (considering that my TFRecordReader has the parameters random_shuffle=True and initial_fill=40000):
1) The file _train.tfrecords_ is mapped in full to memory via mmap
2) Then the first 40000 samples (initial_fill) of the file are extracted. The addresses representing the beginning and end of the samples to be extracted are in the _tfrecord_idx_train_ file. However the data requested is not present in memory so page-faults happen and the page-fault handler will issue an I/O request to read the pages
3) Now the data are present in memory, and now 8 samples are drawn randomly from the data in memory. (I don't know if in this case is used an additional buffer)
4) The 8 samples are decoded by 4 threads (only read is done by a single thread from what I understand): a thread takes a sample and perform decoding and hue transformation on it and save this in a buffer

**Comment by JanuszL** [comment]
Hi,

> 2. Then the first 40000 samples (initial_fill) of the file are extracted. The addresses representing the beginning and end of the samples to be extracted are in the _tfrecord_idx_train_ file. However the data requested is not present in memory so page-faults happen and the page-fault handler will issue an I/O request to read the pages
> 3. Now the data are present in memory, and now 8 samples are drawn randomly from the data in memory. (I don't know if in this case is used an additional buffer)

Samples are read to an internal buffer of size 40000 in your case and then 8 are randomly selected to form a batch and be processed further.

> 4.The 8 samples are decoded by 4 threads (only read is done by a single thread from what I understand): a thread takes a sample and perform decoding and hue transformation on it and save this in a buffer

Yes, samples are processed in parallel, one at a time by 4 threads.

**Comment by pietroorlandi** [comment]
Ok thank you @JanuszL , so anyway almost always, between each DALI operator the data is saved in intermediate buffers.
Now I would like to know more instead about the memory transfer of data from CPU to GPU and from GPU to GPU: 
- You use `cudaMemcpyAsync` to transfer data from CPU buffer to GPU, so from what I understand you always make use of pinned memory (so that it is faster).
- Then you apply the transformations through a CUDA kernel running per-batch and then when the data is ready (the DALI pipeline is finished) you copy this data present in the GPU to a Tensorflow Tensor through _device to device copying_: does this mean that if the size of my batch is M bytes, I will occupy about 2M bytes in memory (because I have to save the batch in a DALI Tensor and a Tensorflow Tensor)? Why is this necessary? What CUDA method is used to execute this device to device copy?

**Comment by JanuszL** [comment]
> You use cudaMemcpyAsync to transfer data from CPU buffer to GPU, so from what I understand you always make use of pinned memory (so that it is faster).

It makes the transfer non-blocking from the CPU side. So we can issue a transfer and work on other things at the CPU while the GPU transfers the data to its memory. If the memory is not pinned it is first staged by the driver in an internal pinned buffer and then the copy starts and the control is returned to the caller. So you have an overhead os CPU to CPU transfer, plus sometimes the internal buffer is occupied by another copy and it just halts your execution until it is available again.

> does this mean that if the size of my batch is M bytes, I will occupy about 2M bytes in memory (because I have to save the batch in a DALI Tensor and a Tensorflow Tensor)? Why is this necessary? What CUDA method is used to execute this device to device copy?

It is a design decision, as DALI cannot output the data directly to the externally provided memory yet, so we need to complete the processing using an internal buffer and then transfer it to a TF-owned one. As far as I understand TensorFlow cannot accept externally provided memory (at least it was not possible some time ago) which is why a copy is needed.
The method we use is `cudaMemcpyAsync` which is up to the driver's internal implementation, but usually (but there is no guarantee) it is a dedicated kernel that copies the data (it cannot be executed concurrently with other cuda kernels).

**Comment by pietroorlandi** [comment]
Thank you very much!
One more thing: if I read files generated using `tfrecord2idx` command I see something like this:
```
0 30717
30717 30717
61434 30717
92151 30717
122868 30717
............
............
522189 30717
552906 30717
583623 30717
614340 30717
645057 30717
............
```
And this is for each file.idx that I have (for example I have 5 file called _train_shard00.idx_, .., _train_shard04.idx_ and I noticed that the content is exactly the same).
I don't understand the benefit of using these index files. Why is it done and why has to be used?

**Comment by pietroorlandi** [comment]
Thank you, now I would like to know more details:
When I have a TFRecord file that does not fit in RAM (for example, a 100GB file and the available RAM is 16GB) the general procedure is this or I'm wrong:
1) All the big file is mmaped in RAM memory
2) Initially, since no real data is in RAM memory (only addresses), when data is requested it is loaded by doing the procedure for page fault
3) At some point, when RAM memory is full, you will have to free up space from this memory to have enough space for the new data being requested. Where will the data go? In the Swap memory on the disk?
From what I think so there will be a continuous flow of data from RAM to swap area
Thanks in advance @JanuszL

**Comment by JanuszL** [comment]
Hi @pietroorlandi,

> 3. At some point, when RAM memory is full, you will have to free up space from this memory to have enough space for the new data being requested. Where will the data go? In the Swap memory on the disk?

In this case, it is up to the OS to do the right thing. I would suspect that just releases the memory (pages) that is less likely to be used next. There is no reason to swap the memory to the disk as it is already there (the modified pages should be written back to the file on the storage), unless the mapping is private - see more [here](https://www.gnu.org/software/libc/manual/html_node/Memory_002dmapped-I_002fO.html).

**Comment by pietroorlandi** [comment]
Thanks @JanuszL 
When instead we using parameter such as the _random_zoom_ as shown below, is the ` fn.transforms.scale` operator executed in CPU and the result is then passed to GPU (for warp_affine), or is it immediately executed in GPU?

```
random_zoom = fn.random.uniform(range=(0.8, 1.2)) # [-20%, +20%]
mt = fn.transforms.scale(mt, scale = fn.stack(random_zoom, random_zoom), center=(16,16))
augmented = fn.warp_affine(images, matrix = mt)
```

**Comment by JanuszL** [comment]
Hi @pietroorlandi,

DALI work is split into stages. So first all CPU operations are performed for a given batch, then mixed, then GPU ones. In the mentioned example, as long as the `images` are on the GPU, the `mt` is computed on the CPU, then passed to the `warp_affine` operator that is executed during the GPU stage (internally it copies the argument to the GPU). The named arguments are CPU side things and it is up to the operator to move them to the GPU if needed (sometimes, they are not passed directly, but used to configure the operator, and the derivative parameters are passed to the GPU operation).
I hope that helps.

**Comment by pietroorlandi** [comment]
Sure, I got it! Thanks!
Another question is related to HSV transformation and specifically to the _hue_ transformation.
You, as you had already explained to me, DALI don't use the standard implementation of HSV but for efficiency reasons it use an approximation given by a linear transformation in RGB space.
Can one get more information about this transformation applied to the RGB space that you implement? Are there any links where you explain the formula used?
Because in my case I am dealing with orange objects and hue transformation with negative degrees give slightly different visual results between DALI and opencv (in DALI the color is more "pink")
Thanks in advance!

**Comment by mzient** [comment]
Hello @pietroorlandi 
About HSV: originally, we didn't have such an operator - what we had was ColorTwist which applied a linear transform to colors in RGB space. One of the transforms it applied was hue adjustment. The new HSV operator is (more or less) the same as adjusting hue, saturation and brightness in the old ColorTwist operation (with a notable difference in hue sign, which we flipped to match OpenCV).
The transform we use is.
First, we convert RGB to some kind of luma/chroma space. For that, we use the following matrix:
```math
\begin{vmatrix}
C
\end{vmatrix}
= \begin{vmatrix}
0.299 & 0.587 & 0.114 \\
0.596 & -0.0274 & -0.321 \\
0.211 & -0.523 & 0.311
\end{vmatrix}
```
The final matrix that's applied is as follows:
```math
M = C^{-1} \cdot
\begin{vmatrix}
1 & 0 & 0 \\
0 & cos(hue_{rad}) & sin(hue_{rad}) \\
0 & -sin(hue_{rad}) & cos(hue_{rad})
\end{vmatrix}
\begin{vmatrix}
1 & 0 & 0 \\
0 & saturation & 0 \\
0 & 0 & saturation
\end{vmatrix}
\cdot value
\cdot C
```
where $hue_{rad} = hue \cdot \frac{\pi}{180}$

The pixels are transformed as:
```math
\begin{vmatrix}
R_{out} \\
G_{out} \\
B_{out}
\end{vmatrix}
= M \cdot
\begin{vmatrix}
R_{in} \\
G_{in} \\
B_{in}
\end{vmatrix}
```

**Comment by JanuszL** [comment]
@pietroorlandi ,

> Last question: I want to know the behavior of GPU operators. They are implemented with CUDA kernels, so for example, when I use warpAffine in GPU, it is a CUDA kernel that will take in input the mt matrix (which will be a matrix (3x3xbatch_size) ) and the batch of images (in this case so a tensor (batch_size, 32, 32, 3) and apply in SIMT mode the transformation. is this right or is there any error?

Yes, that is correct.

> Then the result (so an image tensor) remains in the GPU and if another GPU operator was applied to the pipeline there would be another invocation of a CUDA kernel.

You are on the spot again. Most DALI operators invoke one kernel, there are some that still work on the sample basis and invoke one kernel per sample, and some multi-step like normalization where computing std, mean and normalized values are divided into separate kernels.
