### ISSUE TITLE
Pipeline.run() calls ops.ExternalSource() iterator twice on first __next__ method

### ISSUE THREAD

**Issue by addisonklinke** [NVIDIA/DALI#452]
I define a class `MyIterator` which is used to create an iterator object. When using the next method on the iterator itself, the values yielded and the point at which `StopIteration` is raised are as expected. However, when the iterator is used as input to a pipeline with `ops.ExternalSource()`, the pipeline calls the iterator's next method _twice_ in the first run. This also causes `StopIteration` to be raised one run early. Is there an explanation for this inconsistent behavior?

I noticed this is similar to issue #153 which was supposedly addressed in version 0.3.0. However, I am running 0.6.0 currently and still experiencing the problem. In that thread, @JanuszL recommends

> "After the first run, [Dali] needs to feed data twice, once for this run, one for next batch which will be prepared in the background ... For this please use iter_setup method and feed data there. Dali will know when it needs to prepare the next batch and will call iter_setup appropriately."

So that explains why two batches are buffered on the first run, but that means the `self.i` counter in `MyIterator` must be manually reset to account for this. I would need to add a boolean attribute to `MyPipe` called `has_run=False`. During calls to `iter_setup`, I would check the value of this boolean, and if it is False, subtract 1 from `MyPipe.iterator.i` and set `MyPipe.has_run=True` so that the behavior doesn't repeat on subsequent runs. Is there a more elegant way to achieve this that I'm missing? 

**Reproducible Example:**
```
import numpy as np
import nvidia.dali.ops as ops
from nvidia.dali.pipeline import Pipeline

class MyIterator():
    """Dummy iterator that returns sequential NumPy arrays."""
    def __init__(self, batch_size, n_batches):
        self.batch_size = batch_size
        self.n_batches = n_batches

    def __iter__(self):
        self.i = 0
        self.n = self.batch_size*self.n_batches
        return self

    def __next__(self):
        batch = []
        if self.i < self.n:
            for _ in range(self.batch_size):
                batch.append(np.arange(self.i*5, (self.i + 1)*5, dtype=np.float))
                self.i += 1
            print('\tBatch #{:.0f}'.format(self.i / self.batch_size))
            for i, b in enumerate(batch):
                print('\t\tElement {}) {}'.format(i + 1, b))
            return batch
        else:
            raise StopIteration

    next = __next__

class MyPipe(Pipeline):
    """Pipeline to return output from MyIterator."""
    def __init__(self, iterator, num_threads=1, device_id=0):
        super(MyPipe, self).__init__(iterator.batch_size, num_threads, device_id, seed=1234)
        self.input = ops.ExternalSource()
        self.iterator = iterator

    def define_graph(self):
        self.batch = self.input()
        return self.batch

    def iter_setup(self):
        batch = next(self.iterator)  # Why does the first call do an extra iteration?
        self.feed_input(self.batch, batch)

if __name__ == '__main__':

    batch_size = 2
    n_batches = 5

    # Using just the iterator, everything functions as expected
    iterator = iter(MyIterator(batch_size, n_batches))
    print('{:=^79}'.format(' Pure Iterator '))
    i = 0
    while True:
        try:
            print('\n{:-<50}'.format('Call {} '.format(i)))
            batch = next(iterator)
            i += 1
        except StopIteration:
            print('\tStopIteration raised')
            break

    # Iterator used in pipeline --> first next() call does 2 iterations
    iterator = iter(MyIterator(batch_size, n_batches))
    pipe = MyPipe(iterator)
    pipe.build()

    print('\n{:=^79}'.format(' Inside Pipeline '))
    i = 0
    while True:
        try:
            print('\n{:-<50}'.format('Run {} '.format(i)))
            pipe_out = pipe.run()
            i += 1
        except StopIteration:
            print('\tStopIteration raised')
            break
```

**Comment by JanuszL** [comment]
Hi,
I think there are two things:
1) DALI does the prefetching, that is why at the begging you have two calls to your `MyIterator`
2) DALI even if its your last iteration it still tries to prefetch next iteration - and that is why it calls `MyIterator` one more time that you obtain outputs from DALI
We can just skip running DALI when `iter_setup` rises `StopIteration` and doing `_prefetch()` at iterators reset.

**Comment by addisonklinke** [comment]
@JanuszL is this this correct way to implement your suggestion?
```
def iter_setup(self):
    try:
        batch = next(self.iterator)
        self.feed_input(self.batch, batch)
        if self._first_iter:
            self.iterator.i -= 1
    except StopIteration:
        print('Exhausted iterator')
```

**Comment by JanuszL** [comment]
I was refering how we can change DALI internals to properly support that. And this will require changes in pipeline and plugins python code.
Until we fix that in DALI you need to relay on some workaround - up to you what works bets, but nothing would be clean (I guess).

**Comment by addisonklinke** [comment]
@JanuszL Ok I think I figured out a good workaround for now. If you set `pipe._prefetch_queue_depth=1`, then the iterator will behave the same within the pipeline. As far as I can tell, this shouldn't affect much because that attribute is only used on [line 282](https://github.com/NVIDIA/DALI/blob/52df99fc3214142acb39a25c9f7c4b9aca7d3d28/dali/python/nvidia/dali/pipeline.py#L282) of pipeline.py. Once `_first_iter` is False, the `_prefetch_queue_depth` attribute is no longer used. Are there any consequences of this approach that I missed?

```
    # Iterator used in pipeline --> first next() call does 2 iterations
    iterator = iter(MyIterator(batch_size, n_batches))
    pipe = MyPipe(iterator)
    pipe._prefetch_queue_depth = 1
    pipe.build()
```

**Comment by JanuszL** [comment]
prefetch_queue_depth is the argument in the pipeline construction is the desired way to set that.
And this will hit your performance.
If you are not doing prefetching, then your call flow would look like that
```
pipe.run()
-> compute
-> wait for the end of compute
-> return output
```
If you are using prefetching you have your data prepared already so you don't need to wait for completion of the computing, and you it happens in the background.
```
pipe.run()
-> start compute in the background
-> return output
```
So basically it is the question if you want to compute next batch during you are consuming it or not.

**Comment by JanuszL** [comment]
https://github.com/NVIDIA/DALI/pull/453 should address this.

**Comment by addisonklinke** [comment]
@JanuszL I re-ran my example with the build for #453, and the call to `StopIteration` is raised at the correct time now (see output below). Thanks! 

Pre-fetching in the first run is still present though. Is there a plan to prevent running the iterator twice that doesn't rely on setting `prefetch_queue_depth=1`, or is that the only option and we have to accept the performance losses you described above? 

```
=============================== Inside Pipeline ===============================
Run 0 --------------------------------------------
	Batch #1
		Element 1) [0. 1. 2. 3. 4.]
		Element 2) [5. 6. 7. 8. 9.]
	Batch #2
		Element 1) [10. 11. 12. 13. 14.]
		Element 2) [15. 16. 17. 18. 19.]
Run 1 --------------------------------------------
	Batch #3
		Element 1) [20. 21. 22. 23. 24.]
		Element 2) [25. 26. 27. 28. 29.]
Run 2 --------------------------------------------
	Batch #4
		Element 1) [30. 31. 32. 33. 34.]
		Element 2) [35. 36. 37. 38. 39.]
Run 3 --------------------------------------------
	Batch #5
		Element 1) [40. 41. 42. 43. 44.]
		Element 2) [45. 46. 47. 48. 49.]
Run 4 --------------------------------------------
Run 5 --------------------------------------------
	StopIteration raised
```

**Comment by JanuszL** [comment]
Not really, it is the idea behind the prefetching. If you prefetch then you need to run iter_setup more than once to have prefetch queue filled. Otherwise I don't have idea how we could compute something in advance not calling input iterator as many times as we need.
Could you elaborate how this behavior affects you?

**Comment by addisonklinke** [comment]
The prefetching affects me since `batch #2` from the iterator is never passed to the pipeline. It gets prefetched in run 0, then run 0 returns only `batch #1`, and when run 1 happens the pipeline skips to `batch #3`

**Comment by JanuszL** [comment]
If that is not the case please reopen.
