### ISSUE TITLE
Error out of bound while using DALI random_box_crop for face detection data

### ISSUE THREAD

**Issue by tsangz189** [NVIDIA/DALI#4530]
Hi,

The error message is as follows:
```
Error in thread 7: [/opt/dali/dali/pipeline/util/bounding_box_utils.h:165] Assert on "limits.contains(boxes[i])" failed: box {(4.03981, 0.912037), (4.14444, 1.08565)} is out of bounds {(0, 0), (1, 1)}
```

I do check that each of the bounding box coordinates are within the image boundaries and so are the keypoints (face landmark points)

Please refer to this [line of code](https://github.com/ShiqiYu/libfacedetection.train/blob/a3bc97c7e85bb206c9feca97fbd541ce82cfa3a9/tools/data.py#L62) where the author using `random_crop_bbox`

**Comment by JanuszL** [comment]
Hi @tsangz189,

Is it possible to narrow down the offending sample and provide its definition?
You can check [the debug mode](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/debug_mode.html) for that.

**Comment by tsangz189** [comment]
@JanuszL 
The current nvidia-dali is 1.5.0, it's quite old to have the experimental feature

```
ModuleNotFoundError: No module named 'nvidia.dali.pipeline.experimental'; 'nvidia.dali.pipeline' is not a package
```

**Comment by tsangz189** [comment]
And one more thing, when I try to remove the random_bbox_crop function, everything works fine

**Comment by JanuszL** [comment]
@tsangz189,

I'm sorry but without the reproduction we can run it is hard to tell if this is a real bug or the problem with the data.

**Comment by tsangz189** [comment]
@JanuszL 
Thanks for replying,
Btw, this is not a problem with the function, it's my own mistake while merging training two different datasets.
Thank you for your time
