### ISSUE TITLE
Imagenet example: Segmentation fault when using multiple workers & CPU mode

### ISSUE THREAD

**Issue by yaysummeriscoming** [NVIDIA/DALI#454]
I noticed recently in the imagenet example script (https://github.com/NVIDIA/DALI/blob/master/docs/examples/pytorch/resnet50/main.py) that for CPU mode, the CropMirrorNormalize operator is always in GPU mode.  I figured I'd try & make a full CPU version to reduce GPU memory usage - whilst DALI throughput is great I notice that DALI CPU mode still uses ~35% more GPU RAM than torchvision for my usecase.

I was able to get it working with 1 worker, however when using multiple workers I get a segmentation fault:
Segmentation fault (core dumped)

I've modified the training pipeline as follows:

```
class HybridTrainPipe(Pipeline):
    def __init__(self, batch_size, num_threads, device_id, data_dir, crop, dali_cpu=False):
        super(HybridTrainPipe, self).__init__(batch_size, num_threads, device_id, seed=12 + device_id)
        self.input = ops.FileReader(file_root=data_dir, shard_id=args.local_rank, num_shards=args.world_size, random_shuffle=True)
        #let user decide which pipeline works him bets for RN version he runs
        if dali_cpu:
            dali_device = "cpu"
            self.decode = ops.HostDecoder(device=dali_device, output_type=types.RGB)
        else:
            dali_device = "gpu"
            # This padding sets the size of the internal nvJPEG buffers to be able to handle all images from full-sized ImageNet
            # without additional reallocations
            self.decode = ops.nvJPEGDecoder(device="mixed", output_type=types.RGB, device_memory_padding=211025920, host_memory_padding=140544512)

        self.rrc = ops.RandomResizedCrop(device=dali_device, size =(crop, crop))
        self.cmnp = ops.CropMirrorNormalize(device=dali_device,  # 1: changed from "cpu" to dali_device
                                            output_dtype=types.FLOAT,
                                            output_layout=types.NCHW,
                                            crop=(crop, crop),
                                            image_type=types.RGB,
                                            mean=[0.485 * 255,0.456 * 255,0.406 * 255],
                                            std=[0.229 * 255,0.224 * 255,0.225 * 255])
        self.coin = ops.CoinFlip(probability=0.5)
        print('DALI "{0}" variant'.format(dali_device))

    def define_graph(self):
        rng = self.coin()
        self.jpegs, self.labels = self.input(name="Reader")
        images = self.decode(self.jpegs)
        images = self.rrc(images)
        output = self.cmnp(images, mirror=rng)  # 2: removed gpu transfer
        return [output.gpu(), self.labels]  # 3: added gpu transfer
```

I run the script with the following options.  Increasing the workers count results in the error:
--dali_cpu --workers 1

Additionally, I notice that the CropMirrorNormalize output type is always types.FLOAT.  When running in fp16 mode, would it be more efficient to output to types.FLOAT16 and avoid the additional cast in apex?

**Comment by JanuszL** [comment]
Hi,
This is an example of how to integrate DALI with pyTorch training RN50. Feel free to change output type to FLOAT16, however, I haven't noticed any significant performance hit asking apex to do that cast.
Regarding CropMirrorNormalize, you can check that works best for you, CPU was provided not that long time ago and this is one of the reasons why we are using GPU one here. If you get better results with CPU one feel free to change it. Also, it is expected that DALI will consume more memory than TorchVision on the GPU, as we need to have intermediate buffers to house a full batch of training data we are processing.
Regarding crash you are experiencing - I cannot reproduce that with DALI 0.6. Could you provide more details and some simple reproduction script?

**Comment by yaysummeriscoming** [comment]
Ok, thanks for the info.  I did a bit more troubleshooting & it turns out I just didn't have enough RAM.  48GB will support 1 worker only, whilst 78GB gives me about 3 workers.

Thanks for the pointer on the fp16 cast.  I gave it a go & it works fine on GPU.  I also don't notice a difference in performance.  When I try the fp16 cast on the CPU however I get an error:

Traceback (most recent call last):
  File "/home/user/.pycharm_helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/home/user/.pycharm_helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/user/.pycharm_helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/user/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/user/acceltorch/imagenet-dali-orig.py", line 495, in <module>
    main()
  File "/home/user/acceltorch/imagenet-dali-orig.py", line 255, in main
    train_loader = DALIClassificationIterator(pipe, size=int(pipe.epoch_size("Reader") / args.world_size))
  File "/home/user/anaconda3/envs/pytorch/lib/python3.6/site-packages/nvidia/dali/plugin/pytorch.py", line 215, in __init__
    size)
  File "/home/user/anaconda3/envs/pytorch/lib/python3.6/site-packages/nvidia/dali/plugin/pytorch.py", line 98, in __init__
    self._first_batch = self.next()
  File "/home/user/anaconda3/envs/pytorch/lib/python3.6/site-packages/nvidia/dali/plugin/pytorch.py", line 171, in next
    return self.__next__();
  File "/home/user/anaconda3/envs/pytorch/lib/python3.6/site-packages/nvidia/dali/plugin/pytorch.py", line 136, in __next__
    category_torch_type[category] = to_torch_type[np.dtype(category_tensors[category].dtype())]
RuntimeError: [/opt/dali/dali/python/backend_impl.cc:58] Cannot convert type N10half_float4halfE to format descriptor string

I've made a fork of the script here incorporating full CPU mode & output to fp16:
https://github.com/yaysummeriscoming/DALI/blob/master/docs/examples/pytorch/resnet50/main.py

This runs:
--arch resnet18 --workers 4 --print-freq 1 --fp16

This results in the error:
--arch resnet18 --workers 4 --print-freq 1 --fp16 --dali_cpu

**Comment by JanuszL** [comment]
Hi,
Definitely, this is a bug, we will handle this - tracked as DALI-502.
Side note regarding using Float16 on CPU - we use SW library for that so it is not very fast.  If there is no difference at the network training speed with FLOAT, don't use FLOAT16.
We will use HW instruction for conversion but CPU variant is not the most commonly used for that operator so we have this on the bottom of our ToDo list.

**Comment by JanuszL** [comment]
https://github.com/NVIDIA/DALI/pull/464 should fix the problem

**Comment by yaysummeriscoming** [comment]
Wow thats a quick fix, thanks!  I understand I'm using DALI away from the intended use case of GPU accelerated pre-processing.  I did a bit more experimenting & was able to come up with a fully CPU pipeline that allows for the same batch size as torchvision whilst being quite a bit faster.  Thanks for the help.

**Comment by JanuszL** [comment]
This PR will need some polishing to address issues pointed during the review but generally we will include in in the next release cycle.
