### ISSUE TITLE
Additional information about what fn.transforms.crop does

### ISSUE THREAD

**Issue by pietroorlandi** [NVIDIA/DALI#4540]
Hi, sorry for yet another question but looking through the documentation I can't figure out. 
What does `fn.transforms.crop` method do? What is the detailed purpose of the parameters `from_end` `from_start` and `to_end` and `to_start`? What I would like to do is a random zoom (zoom-in or zoom-out) to the image.
For example to have a zoom-out of 80% of the image (32x32x3) is it right to do this?
```
mt = fn.transforms.crop(mt, from_start = [0, 0], from_end = [32.,32.], to_start = [-3.2,-3.2], to_end=[35.2,35.2])
augmented = fn.warp_affine(images, matrix = mt, interp_type=types.INTERP_NN, fill_value=0.)```
Thanks in advance!

**Comment by jantonguirao** [comment]
`transforms.crop` maps a rectangular region in the original coordinate space, to another rectangular region in the output coordinate space.

Let's use an example:
from_start = [10, 10] from_end = [20, 20]
I am selecting a squared box 10x10, starting at coordinate (10, 10).
Now let's say I select to_start = (200, 200) to_end = (400, 400)
What I am saying is that point (10 ,10) maps to (200, 200) and point (20, 20) maps to (400, 400).

A more relevant example for your use case:
```fn.transforms.crop(from_start = [32, 32] * 0.1, from_end = [32, 32] * 0.9, to_start = [0,0], to_end=[32, 32])```
This is zooming into the center 80% of the input, keeping the same size of 32x32

If you wanted to zoom out, you could do:
```fn.transforms.crop(from_start = [32, 32] * -0.1, from_end = [32 * 32] * 1.1, to_start = [0, 0], to_end=[32, 32])```

Hope that helps.

**Comment by pietroorlandi** [comment]
Okay thank you very much I got it.
One last question: I would like in my data-pipeline to apply random data-augmentation operations while still keeping 50% of the original examples. This I have done and it works via this code:
```
   ...
    augmented = fn.warp_affine(augmented, matrix = mt, inverse_map=False)
    augmented = clamp(augmented, lo=0, hi=1)
    bool_is_augmented = fn.random.coin_flip(dtype=types.DALIDataType.BOOL)
    bool_not_augmented = bool_is_augmented ^ True
    out_images = bool_is_augmented * augmented + bool_not_augmented * images
    return out_images, labels 
```
This works and in this way each batch consists of both original and augmented images.
However, to compare with tf.data I should have the behavior of having batches composed of completely original images and batches composed only of augmented images (with different random transformations). Is it possible with DALI?

**Comment by JanuszL** [comment]
Hi @pietroorlandi,

You can use [the `permute_batch` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.permute_batch.html#nvidia.dali.fn.permute_batch) to pick one random value for the whole batch:
```
rand = fn.random.coin_flip()
broadcasted = fn.permute_batch(rand, indices  = [0] * batch_size)
```

**Comment by pietroorlandi** [comment]
Ok thanks, it works!
But why when I execute this code it gives me this error: "TypeError: float() argument must be a string or a number, not 'DataNode'"
```
random_zoom = fn.random.uniform(range=(-3.2, +3.2)) # [-20%, +20%]
upperbound_zoom = 32-random_zoom
mt = fn.transforms.crop(mt, from_start = [random_zoom, random_zoom], from_end = [upperbound_zoom, upperbound_zoom], to_start = [0, 0], to_end=[32, 32])
```
I tried to edit in `random_zoom = np.random.uniform(low=-3.2, high=+3.2)` but it gives the same random number for each sample of the batch

**Comment by JanuszL** [comment]
Hi @pietroorlandi,

You cannot easily stack the output of the DALI operator using a python list, you need to use `fn.stack`, as the operator accepts only ```float or list of float or TensorList of float```. So something like this should work:
```
 fn.transforms.crop(mt, from_start = fn.stack(random_zoom, random_zoom), from_end = fn.stack(upperbound_zoom, upperbound_zoom), to_start = [0, 0], to_end=[32, 32])
```

**Comment by pietroorlandi** [comment]
Hi @JanuszL , 
It doesn't work. The problem is in `upperbound_zoom = 32-random_zoom` where _random_zoom_ is a DataNode (`fn.random.uniform(range=(-3.2, +3.2))`).
Is there a way to do addition and subtraction to a _DataNode_ that contains a number like in this case?

**Comment by JanuszL** [comment]
This toy example works for me (with the latest DALI):
```
import nvidia.dali as dali
from nvidia.dali import fn

batch_size = 4
@dali.pipeline_def(batch_size=batch_size, num_threads=4, device_id=0)
def rand_pipeline():
    random_zoom = fn.random.uniform(range=(-3.2, +3.2)) # [-20%, +20%]
    upperbound_zoom = 32-random_zoom
    mt = fn.transforms.crop(from_start = fn.stack(random_zoom, random_zoom), from_end = fn.stack(upperbound_zoom, upperbound_zoom), to_start = [0, 0], to_end=[32, 32])
    return mt

pipe = rand_pipeline()
pipe.build()
print(pipe.run())```

**Comment by pietroorlandi** [comment]
Sorry I had misunderstood. Yes now it works. Thanks a lot @JanuszL !
