### ISSUE TITLE
Process a single image into multiple patches

### ISSUE THREAD

**Issue by Fcsalvagnini** [NVIDIA/DALI#4545]
Hello, I'm working on a Data Loader optimization towards a super resolution problem.

I need to feed Low-Resolution and High-Resolution patches (e.g., 100x100 and 200x200 patches). My first version of the Data Loader decodes an input image, extracts a random crop (High-Resolution patch) and generates the Low-Resolution patch. The code snippet below, shows the implemented logic:

```python
    @pipeline_def(device_id=0, batch_size=8)
    def get_dali_pipeline(self):
        """! Builds Nvidia Dali pipeline for dataset iteration."""
        hr_images, _ = fn.readers.file(
            files=self.paths, read_ahead=False,
            shuffle_after_epoch=True, name="file_reader", device="cpu"
        )
        hr_images = fn.decoders.image(hr_images, device="cpu")

        # Generates HR and LR Patches
        hr_patches = fn.crop(
            hr_images,
            crop=[self.hr_height, self.hr_width],
            crop_pos_x=fn.random.uniform(range=(0.0, 1.0)),
            crop_pos_y=fn.random.uniform(range=(0.0, 1.0)),
            dtype=types.FLOAT,
            out_of_bounds_policy="trim_to_shape",
            device="cpu"
        ).gpu()
        # out = scale * (in - mean) / stddev + shift
        # To normalize as usual (0 - 255) -> (0 - 1)
        # scale = 1 | mean = 0 | stddev = 255 | shift = 0
        # out = 1 * (in - 0) / 255 + 0
        hr_patches = fn.normalize(
            hr_patches,
            dtype=types.FLOAT,
            scale=1.0, mean=0.0, stddev=255, shift=0,
            device="gpu"
        )
        lr_patches = fn.resize(
            hr_patches,
            size=[self.lr_height, self.lr_width],
            interp_type=types.INTERP_LINEAR, # Instead of TensorFlow Bilinear
            antialias=False,
            dtype=types.FLOAT,
            device="gpu"
        )

        return lr_patches, hr_patches
```

However, the Data Loader is still too slow. According to my investigations, decoding each image took approximately 300ms. Since each image generates a single patch, to feed a batch of size 8, the data loader needs to decode 8 images.

Therefore, I want to modify the data loader to feed N patches for each image. For example, by extracting 64 patches from an image, the data loader will feed 8 batches decoding a single image. By doing that, I expect to speed up the data loader.

However, by investigating the NVIDIA Dali library, I did not identify how to implement the desired logic, repeating the random crop operation for a single image. How do you suggest I should tackle this problem?

**Comment by mzient** [comment]
Hello @Fcsalvagnini 
There are several things you can do.
First, if your images are JPEGs, you can use `fn.decoders.image_crop` or `fn.decoders.image_slice` - this will effectively decode only the relevant part of the image. You can use those operators for any format, but only JPEGs will give you significant speed up, owing to their high compression ratios and the fact that we actually implement ROI-based decoding.

If you cannot use cropping/slicing decoder, but you're fine with a batch of patches that come from a single image, you can try other approaches:
1. Use two pipelines with an `external_source` - one would decode the whole image and the other would crop it. You would avoid decoding an image multiple times.
2. Read the images externally and supply them via `external_source` in such a way that only some images in the batch are valid and the rest are dummy (extremely cheap to decode). Then use `fn.permute_batch` to replace the dummy images with meaningful ones and crop.

In the future we plan to enable changing the batch size, so you'll be able to use approach 2 without resorting to supplying dummy files.
