### ISSUE TITLE
How to use same shuffle indices for both images and metadata?

### ISSUE THREAD

**Issue by dazzle-me** [NVIDIA/DALI#4553]
Hi! 

I want to read bunch of images along with metadata, but I can't figure out how to make ```fn.external_source``` object use same indices as ```fn.readers_file```, I want metadata to correspond to loaded images for further usage. 

I'm providing minimalistic example of the issue, 
[dali_minimalistic_example.zip](https://github.com/NVIDIA/DALI/files/10360421/dali_minimalistic_example.zip)

if you set ```do_shuffle``` variable to ```False``` everything works as expected, however if you set it to ```True```, 
```shuffle_after_epoch``` becomes ```True``` and metadata no longer corresponds to labels, any way I can align them?

the version of DALI I'm using:
```
$ pip freeze | grep dali
> nvidia-dali-nightly-cuda110==1.22.0.dev20221230
```

**Comment by JanuszL** [comment]
Hi @dazzle-me,

In the case of the build-in readers, like `fn.readers_file` it uses C++ random number generator whose behavior may change as we change the toolchain version used to build DALI and it is not possible to align it with python random generation.
If you want to read images and their metadata I recommend using [the `external source` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/parallel_external_source.html) to read both.
You can also refer to https://github.com/NVIDIA/DALI/issues/4199 to see how to do shuffling and sharding (including pre-shuffling).
