### ISSUE TITLE
How can I get the wheels?

### ISSUE THREAD

**Issue by Furyboyy** [NVIDIA/DALI#4558]
I want to download a wheel for cuda11.3. Where can I find it?

**Comment by JanuszL** [comment]
Hi @Furyboyy,

Thanks to [the CUDA minor version compatibility](https://docs.nvidia.com/deploy/cuda-compatibility/index.html#minor-version-compatibility) you should use [CUDA 11.x based DALI build](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/installation.html#pip-official-releases):
```
pip install --extra-index-url https://developer.download.nvidia.com/compute/redist --upgrade nvidia-dali-cuda110
```
So DALI is built with the latest CUDA 11.x and can run in your CUDA 11.3 environment.

**Comment by Furyboyy** [comment]
Hi @JanuszL , thank you for your quick response! I need to install Dali in an environment that is off the Internet. So I wonder if there are some wheels so that I can download them to my computer and upload them to my server manually.

**Comment by JanuszL** [comment]
You can access it directly [here](https://developer.download.nvidia.com/compute/redist/nvidia-dali-cuda110/).

**Comment by Furyboyy** [comment]
Thank you!
