### ISSUE TITLE
API for `bytearray` data? I need to deecode `bytearray` data into `<class 'nvidia.dali.pipeline.Pipeline'>`

### ISSUE THREAD

**Issue by Furyboyy** [NVIDIA/DALI#4560]
In the official demo
```
def my_pipeline():
    img_files, labels = fn.readers.file(file_root='image_dir', device='cpu')
    # `images` is GPU data (result of Mixed operator)
    images = fn.decoders.image(img_files, device='mixed')
    return flipped, labels.gpu()

pipe = my_pipeline(batch_size=4, num_threads=2, device_id=0)
pipe.build()
```

`fn.readers.file(file_root='image_dir')` read an image with 'image_dir', the datatype of `img_files` is `<class 'nvidia.dali.pipeline.DataNode'>`. Then `fn.decoders.image(img_files, device='mixed')` decode `img_files` into `images`, which is datatype of  `<class 'nvidia.dali.pipeline.Pipeline'>` type. However, I need to decode a `bytearray` data into datatype of `<class 'nvidia.dali.pipeline.Pipeline'>` 

Pipeline I need:
```
def my_pipeline(data):
    ## 'img_files' is a 'bytearray' data
    img_files, labels = TransferDataIntoBytearray(data)
    # `images` is GPU data (result of Mixed operator)
    images = fn.decoders.image(img_files, device='mixed')
    return flipped, labels.gpu()

pipe = my_pipeline(batch_size=4, num_threads=2, device_id=0)
pipe.build()
```

I know I can save the `bytearray` data as `jpeg` file, then use the pipeline as official demo shows to read. **But I can't save any files in my environment**. Is there any API for `bytearray` data?

**Comment by JanuszL** [comment]
Hi @Furyboyy,

Thank you for reaching out. Please check [the 'external source' operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/external_input.html) to pass Python objects to the DALI pipeline. You can also familiarize yourself with [this](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/parallel_external_source.html) ad [this](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/parallel_external_source_fork.html) examples to learn how to get the best performance out of it.

**Comment by Furyboyy** [comment]
Thank you! I think it's possible to implement my requirement with the [the 'external source' operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/external_input.html) operator. I am not familiar with Dali, so I am still trying to work it out. Please don't close this thread for now.
