### ISSUE TITLE
List of supported video codecs

### ISSUE THREAD

**Issue by tadejsv** [NVIDIA/DALI#4580]
Hi, I want to ask if there is a list of video codecs that are supported by the GPU video readers?
I see that `H.264, VP9 and HEVC` are listed in the readme - is this the full list? Does the same hold for the new experimental readers as well?

**Comment by szalpal** [comment]
Hi @tadejsv !

Looking at the source code of `main` branch, I see:
https://github.com/NVIDIA/DALI/blob/9a4f5cdc69440e2f9b2f4d743e282cd47ca2f050/dali/operators/reader/loader/video/frames_decoder_gpu.cc#L341
that the supported codecs are `HEVC, H264, MPEG4`.

Probably documentation might be a little bit outdated on this.

**Comment by tadejsv** [comment]
Hm okay, thank you for the pointer. I am correct in assuming that this is the list for the new experiemental video reader?

And something like this:

https://github.com/NVIDIA/DALI/blob/9a4f5cdc69440e2f9b2f4d743e282cd47ca2f050/dali/operators/reader/nvdecoder/nvdecoder.cc#L95

is probably for the non-experimental one?

**Comment by JanuszL** [comment]
Hi @tadejsv,

Yes, the [link](https://github.com/NVIDIA/DALI/blob/main/dali/operators/reader/nvdecoder/nvdecoder.cc#L95) you provided covers the regular [video reader operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.readers.video.html#nvidia.dali.fn.readers.video). The experimental one has smaller coverage as @szalpal pointed out (and MPEG4 is not supported yet on CPU).
The readme highlights some of the codes but it may vary from platform to platform (GPU) and, each codec may have a different flavor that is not supported by the NVIDIA GPU decoder. If you have any specific format you would like to get supported please let us know.

**Comment by tadejsv** [comment]
Okay, thank you for the answer!
