### ISSUE TITLE
Resize slower than opencv

### ISSUE THREAD

**Issue by shaochangxu** [NVIDIA/DALI#4581]
I compare dali resize func with opencv, but we find it's much slower than opencv. Is there any wrong in my code?
Here is my code:
and i get result like as: dali cost 10x compared to opencv
![image](https://user-images.githubusercontent.com/85155497/213144865-10081b8f-c2b3-4f0a-ad21-cfda099c134e.png)
```
import numpy as np

from nvidia.dali import pipeline_def
import nvidia.dali.fn as fn
from nvidia.dali.pipeline import Pipeline
import nvidia.dali.types as types

import cv2
import time
batch_size = 1


@pipeline_def
def my_pipe():
    img = fn.external_source(name="image")
    resized = fn.resize(img, size=[2048, 1280], device="cpu")
    return resized

image = cv2.imread("./test.jpg")
pipe = my_pipe(batch_size=batch_size, num_threads=1, device_id = 0, seed = 12, prefetch_queue_depth=1)
pipe.build()
pipe.feed_input("image", np.array([image]))
output = pipe.run()
pipe.feed_input("image", np.array([image]))
t1 = time.time()
output = pipe.run()
t2 = time.time()
print(t2 - t1)

t11 = time.time()
output = cv2.resize(image, (2048, 1280))
t22 = time.time()

print(t22 - t11)
```

**Comment by mzient** [comment]
Hello @shaochangxu 

One thing worth noting is that DALI uses antialiasing by default and OpenCV doesn't. You can disable antialiasing by passing `antialias=False` to `resize`.
Secondly, DALI's CPU implementation isn't optimized very much. You can try passing device="gpu" and see how it performs then.
Third, DALI doesn't parallelize processing of a single image (batch_size=1) and OpenCV is aggressively parallelized.

If you specify `num_threads=<num_cpus>` in your pipeline, disable antialiasing and increase the batch size, you should start seeing much better results, but don't expect the CPU implementation to match OpenCV in speed.

**Comment by shaochangxu** [comment]
@mzient Thanks for your reply！I will try your suggestion.
