### ISSUE TITLE
Problem decoding videos that require unpadding

### ISSUE THREAD

**Issue by mtnwrw** [NVIDIA/DALI#4620]
While experimenting with the NVENC part of the CODEC chip built into most modern NVIDIA GPUs, we found that DALI has a problem decoding videos where the `coded_width` is different from the display width of the image. 

The NVENC hardware requires padding to 32-byte elements for coding a video, which means that the coded width of the image will be a multiple of 32, whereas the image width may actually be different. When experimenting with different resolutions, DALI struggled to decode some videos. The error message is rather generic and is thrown when building the pipe using the `build()` method:

`
terminate called after throwing an instance of 'dali::CUDAError'
  what():  CUDA driver API error CUDA_ERROR_INVALID_VALUE (1):
invalid argument
`
when testing with DALI versions 1.7.0 and also 1.20.0.

An example resolution for a failed test would be:

`
image_width: 2448
image_height: 2048
coded_width: 2464
coded_height: 2048
`

Checking if the underlying NVDEC is the problem, we decoded the stream by using the NVIDIA Video SDK on the NVDEC directly and it came out just fine. Interestingly, it seems to work if the unpadding operation that is required is 8 pixels or less. An unpadding of 16 or 24 pixels does not work.

An example video stream that causes DALI to fail can be found [here](https://www.dropbox.com/s/getck487f84l0yx/sample_video.mp4?dl=0).

**Comment by JanuszL** [comment]
Hi @mtnwrw,

Thank you for reporting this issue. Let me check it and get back to you soon.

**Comment by JanuszL** [comment]
I hope this will fix your issue - https://github.com/NVIDIA/DALI/pull/4622.

**Comment by mtnwrw** [comment]
Looks like it, thanks a lot again !

**Comment by JanuszL** [comment]
The fix should be available in the nightly build and in 1.23 which will be released by the end of February.
