### ISSUE TITLE
going from single-gpu to multi-gpu in a video reader

### ISSUE THREAD

**Issue by danbider** [NVIDIA/DALI#4634]
I need to predict long videos (using a pytorch lightning model). What'll be the best way to split up the video between multiple GPUs in a way that I could then stitch the predictions back up to the original video length? is there an example for that?

**Comment by JanuszL** [comment]
Hi @danbider,

I think it would be best to use `file_list` where you can pass `Path to the file with a list of file label [start_frame [end_frame]] values.`. If you assign non-overlapping ranges and equal for each GPU you should be able to distribute the prediction to multiple GPUs.
Regarding stitching the results, I'm afraid we don't have such an example.
