### ISSUE TITLE
DALIGenericIterator too slow

### ISSUE THREAD

**Issue by sinoaidi** [NVIDIA/DALI#4636]
why DALIGenericIterator consume about six minutes?

**Comment by JanuszL** [comment]
Hi @sinoaidi,

Thank you for reaching out. Could you tell us more about your use case and/or provide [minimal, complete, and verifiable reproduction steps](https://github.com/NVIDIA/DALI#reporting-problems-asking-questions)? Without that, we cannot tell where the problem is.

**Comment by JanuszL** [comment]
Closing as stalled.
