### ISSUE TITLE
Monitoring Dali via NGC Container

### ISSUE THREAD

**Issue by Barathwaja** [NVIDIA/DALI#4647]
I’m using NGC Container in my HPC to run the Dali. I would like to get some metrics out of the NGC Container running Tensorflow. Is there anyway nvidia-smi output of GPU utilization can be extracted via Singularity command line?

**Comment by jantonguirao** [comment]
Hi! Thanks you for your question. I am not very familiar with the Singularity command line. I think the best place to ask this question would be here: https://forums.developer.nvidia.com/c/accelerated-computing/nvidia-gpu-cloud-ngc-users/docker-and-nvidia-docker/33
