### ISSUE TITLE
Can I get all outputs of a batch in a single tensor from DALI?

### ISSUE THREAD

**Issue by Alwahsh** [NVIDIA/DALI#4650]
Hi,

I'm trying to use DALI to do pre-processing and I want to do that in batches.
I'm using ExternalSource as the data I have is not in files. My program is dependent on taking the output of DALI which resides on the GPU and run inference on it. The problem is that DALI outputs each output in a batch in a separate tensor rather than a single tensor that contains a dimension for batches.

Code:

```python
MAX_BATCH = 2

class ExternalInputSource(object):
    def __init__(self):
        return

    def __call__(self):
        return (np.array([np.fromfile('cat.jpg', dtype=np.uint8) for _ in range(MAX_BATCH)]),)

@pipeline_def(batch_size=MAX_BATCH, num_threads=1, device_id=0)
def preprocessing_pipeline():
    jpegs =  fn.external_source(source=ExternalInputSource(), num_outputs=1,
                                       dtype=[types.UINT8])
    images = fn.decoders.image(jpegs, device="mixed")
    images = fn.resize(images, resize_x=224, resize_y=224)
    images = fn.crop_mirror_normalize(images,
                                           dtype=types.FLOAT,
                                           mean=0.5 * 255,
                                           std=0.5 * 255,
                                           output_layout="CHW")
    return images

pipe = preprocessing_pipeline(batch_size=MAX_BATCH, num_threads=1, device_id=0, exec_pipelined=False, exec_async=False)
pipe.build()
pipe.run()
```

A colab showing the code and the output:
https://colab.research.google.com/drive/1Ke_7c1nmAwLQIWVvG7cGWsSxzxISSPie

What I was hoping for is to get a tensor of the shape (2,3,244,244) that I can feed directly into my inference engine.

I tried using the following in the pipeline
```
fn.stack(images, axis = 0)
```
but it seems to be operating over each image in the batch alone still so doesn't get me the result I want. The only way I managed to produce something close to what I want was this:
```
fn.stack(*([images] * MAX_BATCH), axis = 0)
```
but it seems to be doing the stacking multiple times which doesn't really sound right to me.

Thanks

**Comment by JanuszL** [comment]
Hi @Alwahsh,

Thank you for reaching out. Please check [`as_tensor` method](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/data_types.html#nvidia.dali.backend.TensorListGPU.as_tensor) to achieve what you want:
```
pipe.run()[0].as_tensor()
```

**Comment by Alwahsh** [comment]
@JanuszL That's what I was looking for! Thanks a lot :pray:
