### ISSUE TITLE
I can't empty the GPU memory after the iterations of `DALIGenericIterator`

### ISSUE THREAD

**Issue by Furyboyy** [NVIDIA/DALI#4653]
I can't empty the GPU memory after the iteration of `DALIGenericIterator` ends.

GPU Memory before dali: 0GB
GPU Memory after dali: 5GB

Pseudo code:

```
dali_pipe =dali_decode_pipeline(**pipeline_args)
dali_iter = DALIGenericIterator(**generator_args)
for _ in tqdm(dali_iter):
    pass

del dali_pipe, dali_iter
gc.collect()
torch.cuda.empty_cache()
```

**Comment by JanuszL** [comment]
Hi @Furyboyy,

Thank you for reaching out. DALI internally uses a memory poll to speed up the memory allocations. When the DALI pipeline is destroyed the pool is kept alive for future use. To learn how to fully reclaim the memory preallocated by DALI please check [this section](https://docs.nvidia.com/deeplearning/dali/main-user-guide/docs/advanced_topics_performance_tuning.html#freeing-memory-pools) of the DALI documentation. Keep in mind that this functionality is available in the nightly/weekly builds and will be shipped with DALI 1.23 release by the end of February.

**Comment by Furyboyy** [comment]
Exellent! Expecting the new version of Dali

**Comment by Furyboyy** [comment]
Hi @JanuszL , when will DALI 1.23 release be published. I need that funtion eagerly. /(ㄒoㄒ)/~~

**Comment by Furyboyy** [comment]
Or is there anyway to implement that function myself?

**Comment by JanuszL** [comment]
Hi @Furyboyy,

Please use [the nightly build](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/installation.html#pip-nightly-and-weekly-releases) until 1.23 is public.
