### ISSUE TITLE
CPU InputOperator crashing without GPU

### ISSUE THREAD

**Issue by fversaci** [NVIDIA/DALI#4669]
Hi,
I'm experimenting with the InputOperator (DALI v1.22.0) for our Cassandra-DALI-plugin and I noticed that, even when I create a pipeline which should only run on CPU, some GPU space is allocated and, more importantly, if there is no GPU available the pipeline cannot run and exits with error `CUDA runtime API error cudaErrorNoDevice (100)`.

This seems similar to issue #4158 , fixed by #4203 .

**Comment by awolant** [comment]
Hello,
thanks for reporting this. It looks like there is something wrong there. Let me check that a bit more and get back to you.

**Comment by JanuszL** [comment]
Will check that and get back to you soon.

**Comment by JanuszL** [comment]
Hi @fversaci,

Please add:
```
uuids.set_pinned(false);
```
Just after https://github.com/fversaci/cassandra-dali-plugin/blob/inputoperator/crs4/cpp/cassandra_dali.cc#L59.
By default DALI CPU tensors are using non-pagable memory to improve the CPU->GPU transfer speed. To achieve this the CUDA runtime API is used.

**Comment by fversaci** [comment]
Hi @JanuszL ,

thanks  for your quick reply, this might indeed be the cause for the GPU allocation!

However when I add the `set_pinned` line  (either after the `Reset` or in the class constructor) a new error arises:

```
Error when executing CPU operator crs4__cassandra encountered:
[/opt/dali/dali/pipeline/operator/operator.cc:66] Assert on "ref_batch_size == output_batch_size" failed: Batch size has to be uniform across one iteration. Expected: 0; Actual: 128
```

with 128 being the correct batch size. This does not happen immediately, but exactly after `prefetch_buffers` batches have already being produced via `pl.run()` (the Cassandra reader buffers internally `prefetch_buffers` batches the first time is run,  see https://github.com/NVIDIA/DALI/issues/4528#issuecomment-1434797753 ).

Do you have any idea of why, by changing the pinned status of the vector, this new error might arise?

(If this becomes off-topic for this thread we could close it and continue the discussion to #4528 )

Thanks again!

**Comment by JanuszL** [comment]
Hi @fversaci,

This one is a bit tricky. As you consume provided data using `ForwardCurrentData` multiple times before the first DALI iteration, you need to provide your own implementation of `NextBatchSize` and `Advance`. The first should just return `batch_size`, the latter could be noop.
In the usual flow `NextBatchSize` examines the first batch to be consumed provided by `feed_input` and sets the batch size for the whole pipeline, then `Advance` moves to the next sample, and the operator runs consuming this. If you consume more than one sample `NextBatchSize` points to the memory that was already consumed by the operator and sooner or later it consists of garbage, returning 0 in your case.

**Comment by fversaci** [comment]
Hi @JanuszL ,

I added `NextBatchSize` and a no-op `Advance` and everything seems to work just fine :D

Thanks again for your quick reply!
