### ISSUE TITLE
dali/image/jpeg.cc:150:54: error: invalid conversion from 'const uint8* {aka const unsigned char*}' to 'unsigned char*' [-fpermissive]

### ISSUE THREAD

**Issue by owenustc** [NVIDIA/DALI#467]
Hi, I build dali in python3.6, meet the error as follow, and my turbjpeg is the last version 2.01.
-- Found CUDA: /usr/local/cuda (found suitable version "9.0", minimum required is "8.0")
-- Found NVJPEG: /usr/include (found suitable version "9.0", minimum required is "9.0")
-- Looking for nvjpegCreateEx
-- Looking for nvjpegCreateEx - found
-- Found JpegTurbo: /usr/include (found suitable version "2.0", minimum required is "1.5")
-- Found OpenCV: /usr/include/opencv;/usr/include (found suitable version "2.4.9.1", minimum required is "2.0")
-- Found PythonLibs: /opt/conda/lib/libpython3.6m.so
-- pybind11 v2.3.dev0
-- Found LMDB: /usr/include (found suitable version "0.9.17", minimum required is "0.9")
-- Found Protobuf: /usr/local/lib/libprotobuf.so;-pthread (found suitable version "3.6.1", minimum required is "2.0")
-- Enabling TensorFlow TFRecord file format support
-- Exclude libs 'libcudart_static.a:libnvjpeg_static.a:libnppicom_static.a:libnppicc_static.a:libnppig_static.a:libnppc_static.a:libculibos.a:libturbojpeg.a:libopencv_core.a:libopencv_imgproc.a:libopencv_highgui.a:libopencv_imgcodecs.a:liblibwebp.a:libittnotify.a:liblibpng.a:liblibtiff.a:liblibjasper.a:libIlmImf.a:liblibjpeg-turbo.a:liblmdb.a:libprotobuf.a:libsupc++.a:libstdc++.a:libstdc++_nonshared.a'
-- Adding dependencies to dali: '/usr/local/cuda/lib64/libcudart_static.a;-pthread;dl;/usr/lib/x86_64-linux-gnu/librt.so;/usr/lib/libnvjpeg_static.a;/usr/local/cuda/lib64/libnppicom_static.a;/usr/local/cuda/lib64/libnppicc_static.a;/usr/local/cuda/lib64/libnppig_static.a;/usr/local/cuda/lib64/libnppc_static.a;/usr/local/cuda/lib64/libculibos.a;/usr/local/cuda/lib64/libnvToolsExt.so;/usr/lib/x86_64-linux-gnu/libturbojpeg.a;opencv_core;opencv_imgproc;opencv_highgui;/usr/lib/x86_64-linux-gnu/liblmdb.so;/usr/local/lib/libprotobuf.so'
-- Adding dependencies to dali_test.bin: 'dali'
-- Adding dependencies to dali_benchmark.bin: 'dali'
-- Adding dependencies to dali_tf: 'dali'
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- LTO enabled
-- Adding dependencies to backend_impl: 'dali'
-- Configuring done
-- Generating done
-- Build files have been written to: /home/owen/AI/ai-medical-algorithms/DALI-Tencent/build
[  1%] Running C++ protocol buffer compiler on proto/feature.proto
[  1%] Running C++ protocol buffer compiler on proto/caffe.proto
[  1%] Running C++ protocol buffer compiler on proto/example.proto
[  1%] Running C++ protocol buffer compiler on proto/dali.proto
[  1%] Running C++ protocol buffer compiler on proto/caffe2.proto
Scanning dependencies of target gtest
Scanning dependencies of target benchmark
Scanning dependencies of target libdali.map
[  1%] Built target libdali.map
[  2%] Building CXX object third_party/googletest/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
[  3%] Building CXX object third_party/benchmark/src/CMakeFiles/benchmark.dir/statistics.cc.o
[  4%] Building CXX object third_party/benchmark/src/CMakeFiles/benchmark.dir/colorprint.cc.o
[  4%] Building CXX object third_party/benchmark/src/CMakeFiles/benchmark.dir/complexity.cc.o
[  5%] Building CXX object third_party/benchmark/src/CMakeFiles/benchmark.dir/benchmark_register.cc.o
Scanning dependencies of target CAFFE_PROTO
[  6%] Building CXX object third_party/benchmark/src/CMakeFiles/benchmark.dir/benchmark.cc.o
[  6%] Building CXX object third_party/benchmark/src/CMakeFiles/benchmark.dir/csv_reporter.cc.o
[  6%] Building CXX object third_party/benchmark/src/CMakeFiles/benchmark.dir/console_reporter.cc.o
[  7%] Building CXX object third_party/benchmark/src/CMakeFiles/benchmark.dir/json_reporter.cc.o
[  8%] Building CXX object third_party/benchmark/src/CMakeFiles/benchmark.dir/commandlineflags.cc.o
[  8%] Building CXX object third_party/benchmark/src/CMakeFiles/benchmark.dir/reporter.cc.o
[  9%] Building CXX object third_party/benchmark/src/CMakeFiles/benchmark.dir/counter.cc.o
[  9%] Building CXX object third_party/benchmark/src/CMakeFiles/benchmark.dir/sysinfo.cc.o
Scanning dependencies of target TF_PROTO
[ 10%] Building CXX object third_party/benchmark/src/CMakeFiles/benchmark.dir/sleep.cc.o
Scanning dependencies of target DALI_PROTO
[ 10%] Building CXX object third_party/benchmark/src/CMakeFiles/benchmark.dir/timers.cc.o
Scanning dependencies of target CAFFE2_PROTO
[ 10%] Building CXX object third_party/benchmark/src/CMakeFiles/benchmark.dir/string_util.cc.o
[ 11%] Building CXX object dali/pipeline/operators/reader/parser/CMakeFiles/TF_PROTO.dir/feature.pb.cc.o
[ 12%] Building CXX object dali/pipeline/operators/reader/parser/CMakeFiles/CAFFE_PROTO.dir/caffe.pb.cc.o
[ 13%] Building CXX object dali/pipeline/operators/reader/parser/CMakeFiles/TF_PROTO.dir/example.pb.cc.o
[ 13%] Building CXX object dali/pipeline/CMakeFiles/DALI_PROTO.dir/dali.pb.cc.o
[ 14%] Building CXX object dali/pipeline/operators/reader/parser/CMakeFiles/CAFFE2_PROTO.dir/caffe2.pb.cc.o
[ 14%] Built target CAFFE_PROTO
[ 14%] Built target CAFFE2_PROTO
[ 14%] Built target DALI_PROTO
[ 14%] Built target TF_PROTO
[ 15%] Building NVCC (Device) object dali/CMakeFiles/dali.dir/plugin/dali_generated_copy.cu.o
[ 15%] Building NVCC (Device) object dali/CMakeFiles/dali.dir/pipeline/operators/displacement/dali_generated_water.cu.o
[ 15%] Building NVCC (Device) object dali/CMakeFiles/dali.dir/pipeline/operators/fused/dali_generated_crop_mirror_normalize.cu.o
[ 15%] Building NVCC (Device) object dali/CMakeFiles/dali.dir/pipeline/operators/util/dali_generated_copy.cu.o
[ 15%] Building NVCC (Device) object dali/CMakeFiles/dali.dir/pipeline/operators/resize/dali_generated_resize.cu.o
[ 15%] Building NVCC (Device) object dali/CMakeFiles/dali.dir/pipeline/operators/crop/dali_generated_crop.cu.o
[ 16%] Building NVCC (Device) object dali/CMakeFiles/dali.dir/pipeline/operators/util/dali_generated_make_contiguous.cu.o
[ 17%] Building NVCC (Device) object dali/CMakeFiles/dali.dir/pipeline/operators/resize/dali_generated_random_resized_crop.cu.o
[ 18%] Building NVCC (Device) object dali/CMakeFiles/dali.dir/pipeline/operators/displacement/dali_generated_rotate.cu.o
[ 19%] Building NVCC (Device) object dali/CMakeFiles/dali.dir/pipeline/operators/displacement/dali_generated_warpaffine.cu.o
[ 21%] Building NVCC (Device) object dali/CMakeFiles/dali.dir/pipeline/operators/fused/dali_generated_crop_cast_permute.cu.o
[ 21%] Building NVCC (Device) object dali/CMakeFiles/dali.dir/pipeline/operators/util/dali_generated_dump_image.cu.o
[ 21%] Building NVCC (Device) object dali/CMakeFiles/dali.dir/pipeline/operators/displacement/dali_generated_sphere.cu.o
[ 22%] Building NVCC (Device) object dali/CMakeFiles/dali.dir/pipeline/operators/color/dali_generated_color_twist.cu.o
[ 22%] Building NVCC (Device) object dali/CMakeFiles/dali.dir/pipeline/operators/resize/dali_generated_new_resize.cu.o
[ 22%] Building NVCC (Device) object dali/CMakeFiles/dali.dir/pipeline/operators/displacement/dali_generated_flip.cu.o
[ 23%] Building NVCC (Device) object dali/CMakeFiles/dali.dir/pipeline/operators/util/dali_generated_external_source.cu.o
[ 25%] Building NVCC (Device) object dali/CMakeFiles/dali.dir/pipeline/operators/decoder/dali_generated_nvjpeg_decoder.cu.o
[ 24%] Building NVCC (Device) object dali/CMakeFiles/dali.dir/pipeline/operators/tencent/dali_generated_curve.cu.o
[ 25%] Building NVCC (Device) object dali/CMakeFiles/dali.dir/pipeline/operators/tencent/dali_generated_random_noise.cu.o
[ 26%] Building NVCC (Device) object dali/CMakeFiles/dali.dir/pipeline/operators/tencent/dali_generated_format_conversion.cu.o
[ 27%] Building NVCC (Device) object dali/CMakeFiles/dali.dir/pipeline/operators/fused/dali_generated_normalize_permute.cu.o
[ 27%] Building NVCC (Device) object dali/CMakeFiles/dali.dir/pipeline/operators/util/dali_generated_cast.cu.o
[ 28%] Building NVCC (Device) object dali/CMakeFiles/dali.dir/pipeline/operators/util/dali_generated_dummy_op.cu.o
[ 29%] Building NVCC (Device) object dali/CMakeFiles/dali.dir/pipeline/operators/tencent/dali_generated_rgb_hsv.cu.o
[ 29%] Building NVCC (Device) object dali/CMakeFiles/dali.dir/pipeline/operators/tencent/dali_generated_channel_scale.cu.o
[ 29%] Building NVCC (Device) object dali/CMakeFiles/dali.dir/pipeline/operators/paste/dali_generated_paste.cu.o
[ 30%] Building NVCC (Device) object dali/CMakeFiles/dali.dir/pipeline/operators/displacement/dali_generated_jitter.cu.o
[ 31%] Linking CXX static library libbenchmark.a
[ 31%] Built target benchmark
[ 31%] Building NVCC (Device) object dali/CMakeFiles/dali.dir/util/dali_generated_type_conversion.cu.o
[ 31%] Linking CXX static library libgtest.a
[ 31%] Built target gtest
Scanning dependencies of target dali
[ 32%] Building CXX object dali/CMakeFiles/dali.dir/image/image_factory.cc.o
[ 32%] Building CXX object dali/CMakeFiles/dali.dir/image/bmp.cc.o
[ 32%] Building CXX object dali/CMakeFiles/dali.dir/image/image.cc.o
[ 32%] Building CXX object dali/CMakeFiles/dali.dir/image/transform.cc.o
[ 32%] Building CXX object dali/CMakeFiles/dali.dir/image/tiff.cc.o
[ 32%] Building CXX object dali/CMakeFiles/dali.dir/pipeline/data/types.cc.o
[ 34%] Building CXX object dali/CMakeFiles/dali.dir/image/generic_image.cc.o
[ 35%] Building CXX object dali/CMakeFiles/dali.dir/pipeline/data/backend.cc.o
[ 37%] Building CXX object dali/CMakeFiles/dali.dir/pipeline/operators/color/color_twist.cc.o
[ 37%] Building CXX object dali/CMakeFiles/dali.dir/image/jpeg.cc.o
[ 38%] Building CXX object dali/CMakeFiles/dali.dir/image/png.cc.o
[ 38%] Building CXX object dali/CMakeFiles/dali.dir/pipeline/operators/crop/crop.cc.o
[ 38%] Building CXX object dali/CMakeFiles/dali.dir/pipeline/operators/detection/random_crop.cc.o
[ 39%] Building CXX object dali/CMakeFiles/dali.dir/pipeline/data/allocator.cc.o
[ 39%] Building CXX object dali/CMakeFiles/dali.dir/pipeline/operators/crop/bbox_crop.cc.o
[ 40%] Building CXX object dali/CMakeFiles/dali.dir/pipeline/operators/crop/slice.cc.o
[ 41%] Building CXX object dali/CMakeFiles/dali.dir/pipeline/operators/displacement/jitter.cc.o
[ 42%] Building CXX object dali/CMakeFiles/dali.dir/pipeline/operators/decoder/host_decoder.cc.o
[ 42%] Building CXX object dali/CMakeFiles/dali.dir/pipeline/operators/displacement/rotate.cc.o
[ 43%] Building CXX object dali/CMakeFiles/dali.dir/pipeline/operators/displacement/flip.cc.o
[ 44%] Building CXX object dali/CMakeFiles/dali.dir/pipeline/operators/displacement/warpaffine.cc.o
[ 44%] Building CXX object dali/CMakeFiles/dali.dir/pipeline/operators/displacement/water.cc.o
[ 45%] Building CXX object dali/CMakeFiles/dali.dir/pipeline/operators/displacement/sphere.cc.o
[ 45%] Building CXX object dali/CMakeFiles/dali.dir/pipeline/operators/displacement/displacement_filter.cc.o
[ 46%] Building CXX object dali/CMakeFiles/dali.dir/pipeline/operators/fused/normalize_permute.cc.o
[ 46%] Building CXX object dali/CMakeFiles/dali.dir/pipeline/operators/fused/crop_cast_permute.cc.o
[ 46%] Building CXX object dali/CMakeFiles/dali.dir/pipeline/operators/fused/crop_mirror_normalize.cc.o
[ 47%] Building CXX object dali/CMakeFiles/dali.dir/pipeline/operators/reader/loader/loader.cc.o
[ 48%] Building CXX object dali/CMakeFiles/dali.dir/pipeline/operators/fused/resize_crop_mirror.cc.o
[ 48%] Building CXX object dali/CMakeFiles/dali.dir/pipeline/operators/reader/loader/file_loader.cc.o
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/image/jpeg.cc: In member function 'virtual std::pair<std::shared_ptr<unsigned char>, std::tuple<long unsigned int, long unsigned int, long unsigned int> > dali::JpegImage::DecodeImpl(dali::DALIImageType, const uint8*, size_t) const':
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/image/jpeg.cc:150:54: error: invalid conversion from 'const uint8* {aka const unsigned char*}' to 'unsigned char*' [-fpermissive]
                              w, 0, h, pixel_format, 0);
                                                      ^
In file included from /home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/image/jpeg.h:23:0,
                 from /home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/image/jpeg.cc:17:
/usr/include/turbojpeg.h:1134:23: note:   initializing argument 2 of 'int tjDecompress2(tjhandle, unsigned char*, long unsigned int, unsigned char*, int, int, int, int, int)'
 DLLEXPORT int DLLCALL tjDecompress2(tjhandle handle,
                       ^
[ 49%] Building CXX object dali/CMakeFiles/dali.dir/pipeline/operators/reader/file_reader_op.cc.o
[ 50%] Building CXX object dali/CMakeFiles/dali.dir/pipeline/operators/reader/caffe_reader_op.cc.o
[ 50%] Building CXX object dali/CMakeFiles/dali.dir/pipeline/operators/reader/caffe2_reader_op.cc.o
dali/CMakeFiles/dali.dir/build.make:409: recipe for target 'dali/CMakeFiles/dali.dir/image/jpeg.cc.o' failed
make[2]: *** [dali/CMakeFiles/dali.dir/image/jpeg.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:523: recipe for target 'dali/CMakeFiles/dali.dir/all' failed
make[1]: *** [dali/CMakeFiles/dali.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by JanuszL** [comment]
Hi,
Please run 'make VERBOSE=1' and see if the turbjpeg path used during the build is one you desire, then check turbojpeg.h and jconfig.h headers in that path (if they are in the proper version). I just managed to build DALI with JpegTurbo 2.0. The issue you have, looks like your turbojpeg.h header is older than 2.0, as `tjDecompress2` declaration changed somewhere around JpegTurbo 1.4.

**Comment by owenustc** [comment]
/usr/bin/c++ --version
c++ (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by owenustc** [comment]
Hi, you are right, I copy header file and library of turbo with 2.01 into the /usr/local/. It work, but meet another problem, which as follow:
94%] Building CXX object dali/CMakeFiles/dali_test.bin.dir/pipeline/operators/geometric/bb_flip_test.cc.o
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc:73:7: error: 'InterpolationFlags' in namespace 'cv' does not name a type
   cv::InterpolationFlags cvInterp;
       ^
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc:81:1: error: too many initializers for 'dali::InterpolationType'
 };
 ^
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc:81:1: error: too many initializers for 'dali::InterpolationType'
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc:81:1: error: too many initializers for 'dali::InterpolationType'
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc:81:1: error: cannot convert 'cv::<anonymous enum>' to 'dali::DALIInterpType' in initialization
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc:81:1: error: cannot convert 'cv::<anonymous enum>' to 'dali::DALIInterpType' in initialization
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc:81:1: error: cannot convert 'cv::<anonymous enum>' to 'dali::DALIInterpType' in initialization
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc: In member function 'virtual void dali::ResizeTest_ResizeShorter_Default_LINEAR_GPU_Test<gtest_TypeParam_>::TestBody()':
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc:92:50: error: 'struct dali::InterpolationType' has no member named 'cvInterp'
           this->setInterpType(interpType[interp].cvInterp);                     \
                                                  ^
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc:107:13: note: in expansion of macro 'TESTS_WITH_CHECK'
             TESTS_WITH_CHECK(testName, interp, testArgs, Default)       \
             ^
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc:110:1: note: in expansion of macro 'TYPED_TESTS'
 TYPED_TESTS(ResizeShorter,   LINEAR, .AddArg("resize_shorter", 480.f))
 ^
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc: In member function 'virtual void dali::ResizeTest_ResizeShorter_Default_LINEAR_CPU_Test<gtest_TypeParam_>::TestBody()':
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc:98:50: error: 'struct dali::InterpolationType' has no member named 'cvInterp'
           this->setInterpType(interpType[interp].cvInterp);                     \
                                                  ^
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc:107:13: note: in expansion of macro 'TESTS_WITH_CHECK'
             TESTS_WITH_CHECK(testName, interp, testArgs, Default)       \
             ^
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc:110:1: note: in expansion of macro 'TYPED_TESTS'
 TYPED_TESTS(ResizeShorter,   LINEAR, .AddArg("resize_shorter", 480.f))
 ^
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc: In member function 'virtual void dali::ResizeTest_ResizeShorter_Elements_LINEAR_GPU_Test<gtest_TypeParam_>::TestBody()':
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc:92:50: error: 'struct dali::InterpolationType' has no member named 'cvInterp'
           this->setInterpType(interpType[interp].cvInterp);                     \
                                                  ^
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc:108:13: note: in expansion of macro 'TESTS_WITH_CHECK'
             TESTS_WITH_CHECK(testName, interp, testArgs, Elements)
             ^
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc:110:1: note: in expansion of macro 'TYPED_TESTS'
 TYPED_TESTS(ResizeShorter,   LINEAR, .AddArg("resize_shorter", 480.f))
 ^
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc: In member function 'virtual void dali::ResizeTest_ResizeShorter_Elements_LINEAR_CPU_Test<gtest_TypeParam_>::TestBody()':
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc:98:50: error: 'struct dali::InterpolationType' has no member named 'cvInterp'
           this->setInterpType(interpType[interp].cvInterp);                     \
                                                  ^
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc:108:13: note: in expansion of macro 'TESTS_WITH_CHECK'
             TESTS_WITH_CHECK(testName, interp, testArgs, Elements)
             ^
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc:110:1: note: in expansion of macro 'TYPED_TESTS'
 TYPED_TESTS(ResizeShorter,   LINEAR, .AddArg("resize_shorter", 480.f))
 ^
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc: In member function 'virtual void dali::ResizeTest_ResizeShorter_A_Default_LINEAR_GPU_Test<gtest_TypeParam_>::TestBody()':
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc:92:50: error: 'struct dali::InterpolationType' has no member named 'cvInterp'
           this->setInterpType(interpType[interp].cvInterp);                     \
                                                  ^
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc:107:13: note: in expansion of macro 'TESTS_WITH_CHECK'
             TESTS_WITH_CHECK(testName, interp, testArgs, Default)       \
             ^
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc:111:1: note: in expansion of macro 'TYPED_TESTS'
 TYPED_TESTS(ResizeShorter_A, LINEAR, .AddArg("resize_shorter", 224.f))
 ^
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc: In member function 'virtual void dali::ResizeTest_ResizeShorter_A_Default_LINEAR_CPU_Test<gtest_TypeParam_>::TestBody()':
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc:98:50: error: 'struct dali::InterpolationType' has no member named 'cvInterp'
           this->setInterpType(interpType[interp].cvInterp);                     \
                                                  ^
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc:107:13: note: in expansion of macro 'TESTS_WITH_CHECK'
             TESTS_WITH_CHECK(testName, interp, testArgs, Default)       \
             ^
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc:111:1: note: in expansion of macro 'TYPED_TESTS'
 TYPED_TESTS(ResizeShorter_A, LINEAR, .AddArg("resize_shorter", 224.f))
 ^
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc: In member function 'virtual void dali::ResizeTest_ResizeShorter_A_Elements_LINEAR_GPU_Test<gtest_TypeParam_>::TestBody()':
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc:92:50: error: 'struct dali::InterpolationType' has no member named 'cvInterp'
           this->setInterpType(interpType[interp].cvInterp);                     \
                                                  ^
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc:108:13: note: in expansion of macro 'TESTS_WITH_CHECK'
             TESTS_WITH_CHECK(testName, interp, testArgs, Elements)
             ^
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc:111:1: note: in expansion of macro 'TYPED_TESTS'
 TYPED_TESTS(ResizeShorter_A, LINEAR, .AddArg("resize_shorter", 224.f))
 ^
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc: In member function 'virtual void dali::ResizeTest_ResizeShorter_A_Elements_LINEAR_CPU_Test<gtest_TypeParam_>::TestBody()':
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc:98:50: error: 'struct dali::InterpolationType' has no member named 'cvInterp'
           this->setInterpType(interpType[interp].cvInterp);                     \
                                                  ^
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc:108:13: note: in expansion of macro 'TESTS_WITH_CHECK'
             TESTS_WITH_CHECK(testName, interp, testArgs, Elements)
             ^
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc:111:1: note: in expansion of macro 'TYPED_TESTS'
 TYPED_TESTS(ResizeShorter_A, LINEAR, .AddArg("resize_shorter", 224.f))
 ^
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc: In member function 'virtual void dali::ResizeTest_ResizeXY_Default_LINEAR_GPU_Test<gtest_TypeParam_>::TestBody()':
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc:92:50: error: 'struct dali::InterpolationType' has no member named 'cvInterp'
           this->setInterpType(interpType[interp].cvInterp);                     \
                                                  ^
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc:107:13: note: in expansion of macro 'TESTS_WITH_CHECK'
             TESTS_WITH_CHECK(testName, interp, testArgs, Default)       \
             ^
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc:112:1: note: in expansion of macro 'TYPED_TESTS'
 TYPED_TESTS(ResizeXY,        LINEAR, .AddArg("resize_x", 224.f)         \
 ^
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc: In member function 'virtual void dali::ResizeTest_ResizeXY_Default_LINEAR_CPU_Test<gtest_TypeParam_>::TestBody()':
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc:98:50: error: 'struct dali::InterpolationType' has no member named 'cvInterp'
           this->setInterpType(interpType[interp].cvInterp);                     \
                                                  ^
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc:107:13: note: in expansion of macro 'TESTS_WITH_CHECK'
             TESTS_WITH_CHECK(testName, interp, testArgs, Default)       \
             ^
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc:112:1: note: in expansion of macro 'TYPED_TESTS'
 TYPED_TESTS(ResizeXY,        LINEAR, .AddArg("resize_x", 224.f)         \
 ^
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc: In member function 'virtual void dali::ResizeTest_ResizeXY_Elements_LINEAR_GPU_Test<gtest_TypeParam_>::TestBody()':
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc:92:50: error: 'struct dali::InterpolationType' has no member named 'cvInterp'
           this->setInterpType(interpType[interp].cvInterp);                     \
                                                  ^
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc:108:13: note: in expansion of macro 'TESTS_WITH_CHECK'
             TESTS_WITH_CHECK(testName, interp, testArgs, Elements)
             ^
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc:112:1: note: in expansion of macro 'TYPED_TESTS'
 TYPED_TESTS(ResizeXY,        LINEAR, .AddArg("resize_x", 224.f)         \
 ^
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc: In member function 'virtual void dali::ResizeTest_ResizeXY_Elements_LINEAR_CPU_Test<gtest_TypeParam_>::TestBody()':
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc:98:50: error: 'struct dali::InterpolationType' has no member named 'cvInterp'
           this->setInterpType(interpType[interp].cvInterp);                     \
                                                  ^
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc:108:13: note: in expansion of macro 'TESTS_WITH_CHECK'
             TESTS_WITH_CHECK(testName, interp, testArgs, Elements)
             ^
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc:112:1: note: in expansion of macro 'TYPED_TESTS'
 TYPED_TESTS(ResizeXY,        LINEAR, .AddArg("resize_x", 224.f)         \
 ^
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc: In member function 'virtual void dali::ResizeTest_ResizeXY_A_Default_LINEAR_GPU_Test<gtest_TypeParam_>::TestBody()':
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc:92:50: error: 'struct dali::InterpolationType' has no member named 'cvInterp'
           this->setInterpType(interpType[interp].cvInterp);                     \
                                                  ^
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc:107:13: note: in expansion of macro 'TESTS_WITH_CHECK'
             TESTS_WITH_CHECK(testName, interp, testArgs, Default)       \
             ^
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc:114:1: note: in expansion of macro 'TYPED_TESTS'
 TYPED_TESTS(ResizeXY_A,      LINEAR, .AddArg("resize_x", 240.f)         \
 ^
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc: In member function 'virtual void dali::ResizeTest_ResizeXY_A_Default_LINEAR_CPU_Test<gtest_TypeParam_>::TestBody()':
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc:98:50: error: 'struct dali::InterpolationType' has no member named 'cvInterp'
           this->setInterpType(interpType[interp].cvInterp);                     \
                                                  ^
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc:107:13: note: in expansion of macro 'TESTS_WITH_CHECK'
             TESTS_WITH_CHECK(testName, interp, testArgs, Default)       \
             ^
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc:114:1: note: in expansion of macro 'TYPED_TESTS'
 TYPED_TESTS(ResizeXY_A,      LINEAR, .AddArg("resize_x", 240.f)         \
 ^
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc: In member function 'virtual void dali::ResizeTest_ResizeXY_A_Elements_LINEAR_GPU_Test<gtest_TypeParam_>::TestBody()':
/home/owen/AI/ai-medical-algorithms/DALI-Tencent/dali/pipeline/operators/resize/resize_test.cc:92:50: error: 'struct dali::InterpolationType' has no member named 'cvInterp'
           this->setInterpType(interpType[interp].cvInterp);                     \
                                                  ^

**Comment by JanuszL** [comment]
Hi,
It seems that it is OpenCV incompatibility. Recommended configuration requires OpenCV 3, OpenCV 2.x compatibility is provided unofficially by the community. We are not testing that nor paying much attention to correctness or performance. Keep in mind that OpenCV has been released as 4.0 just recently.

**Comment by JanuszL** [comment]
Can you recheck with the latest master branch code?

**Comment by JanuszL** [comment]
If it doesn't work for you please reopen.
