### ISSUE TITLE
How to return the data index?

### ISSUE THREAD

**Issue by Pedrexus** [NVIDIA/DALI#4672]
Hello,

I'm fairly new to the library, so I wanted to ask if it is possible to return the index as an output too? 

In my case, I'm using the `nvidia.dali.fn.readers.file` with pytorch via `nvidia.dali.plugin.pytorch.DALIGenericIterator`. The iterator then outputs a dict with "x" and "y" keys every iteration, but I wonder if there is a way to output the image index somehow. I am running some comparisons and it is not feasible to keep everything in memory, so it would be easier if I could just have an index.

With pytorch, I used to customize the `Dataset` class `def __getitem__(self, idx)` method to return `idx` as well as "x" and "y". Is there a similar approach in DALI. Also, Is there a way to make it work with multiple GPUs?

Thank you very much!

**Comment by JanuszL** [comment]
Hi @Pedrexus,

You can use [the `get_property` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.get_property.html) to obtain the file names from the reader:
```
from nvidia.dali import pipeline_def
import nvidia.dali.fn as fn
from nvidia.dali.plugin.pytorch import DALIGenericIterator
import numpy as np

max_batch_size = 2
images_files=["dali_extra/db/single/jpeg/100/swan-3584559_640.jpg", "dali_extra/db/single/jpeg/134/baukran-3703469_1280.jpg"]

@pipeline_def
def simple_pipeline():
    rgb_files, _ = fn.readers.file(files=images_files, name="main_reader")
    info = fn.get_property(rgb_files, key="source_info")
    info = fn.pad(info)
    return info

def _uint8_tensor_to_string(t):
    return np.array(t).tobytes().decode()

pipe = simple_pipeline(batch_size=max_batch_size, num_threads=1, device_id=0)
iter = DALIGenericIterator([pipe], ['info'], reader_name='main_reader')
for d in iter:
    d = d[0]['info']
    for j in range(max_batch_size):
        print(_uint8_tensor_to_string(d[j]))
```

**Comment by Pedrexus** [comment]
This was what I was looking for! Thank you very much, @JanuszL!
