### ISSUE TITLE
Question: Is there a way to resize the dimensions of an image independently?

### ISSUE THREAD

**Issue by towr** [NVIDIA/DALI#4673]
I'm trying to resize and pad input images with varying sizes and aspect rations to a fixed input size for my model. On top of that I want to augment them with some random variation by scaling x and y independently (and then crop/pad to get back to the target size).

Is there some way to actually achieve this and still having GPU acceleration?

The code below roughly does what I want if I use `device='cpu'` instead of `device='mixed'` in de decoder, but with `mixed` it gives
`RuntimeError: [/opt/dali/dali/pipeline/pipeline.cc:319] Named arguments inputs to operators must be CPU data nodes. However, a GPU data node was provided (op: 'Resize', input: '__ArithmeticGenericOp_312')`

(As a side note, I also can't seem to use `fast_resize_crop_mirror` instead of separate `resize` and `crop`, it raises `Assert on "crop_y >= 0" failed` when I run the pipeline.)

```python
from nvidia.dali.plugin.pytorch import DALIClassificationIterator, LastBatchPolicy, DALIGenericIterator
from nvidia.dali import pipeline_def, Pipeline
import nvidia.dali as dali
import nvidia.dali.fn as fn
import nvidia.dali.ops as ops
import nvidia.dali.types as types

DATA_PATH = 'test_images/'
IMG_SIZE = 256

height_rng = fn.random.uniform(range=(0.9,1.1))
width_rng = fn.random.uniform(range=(0.9,1.1))

def common_pipeline(jpegs, img_size):
    # Decode image
    images = fn.decoders.image(jpegs, device='mixed', output_type=types.RGB)
    
    # calculate the random width/height
    shape = fn.shapes(images)
    height, width, max_axis = shape[0], shape[1], fn.reductions.max(shape[0:2])   
    height = height / max_axis * img_size * height_rng
    width = width / max_axis * img_size * width_rng

    # resize
    images = fn.resize(images, resize_x=width, resize_y=height)

    # crop to size with padding. 
    images = fn.crop(
        images, 
        crop=(img_size, img_size),
        out_of_bounds_policy="pad"
    )
    
    return images

@pipeline_def
def file_reader_pipeline(file_path, img_size, shuffle=False, num_gpus=1):
    jpegs, labels = fn.readers.file(
        file_root=file_path,
        random_shuffle=shuffle,
        shard_id=Pipeline.current().device_id,
        num_shards=num_gpus,
        name='Reader')

    return common_pipeline(jpegs, img_size)

pl = file_reader_pipeline(file_path=DATA_PATH, img_size=IMG_SIZE, shuffle=False,
                          num_gpus=1, batch_size=1, num_threads=1, device_id=0)
pl.build()
```

**Comment by JanuszL** [comment]
Hi @towr,

Please use:
```
shape = fn.peek_image_shape(jpegs)
```
instead of `fn.shapes(images)`. [The `shapes`](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.shapes.html#nvidia.dali.fn.shapes) operator returns the data on the same device as the input (GPU in that case) while named arguments to the operators needs to reside on the CPU.

**Comment by towr** [comment]
Thanks! 
Somehow I overlooked that function in the operation reference.
