### ISSUE TITLE
Filter files based on input

### ISSUE THREAD

**Issue by Pedrexus** [NVIDIA/DALI#4677]
Hello,

I'm still understadning the library, and I would like to know if there is a way to filter the files passed after the pipeline is built.

In my case, I'm using the `nvidia.dali.fn.readers.file` with pytorch via `nvidia.dali.plugin.pytorch.DALIGenericIterator`. The iterator then outputs a dict with "x" and "y" keys every iteration.

 I was looking into using `fn.external_source` and `Pipeline.feed_input` to input a new set of filepaths every epoch and filter the data being read, but I could not make it work yet. Is there a way to make it happen?

Thank you in advance!

**Comment by JanuszL** [comment]
Hi @Pedrexus,

Thank you for reaching out. To learn how to use [the `external source` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.external_source.html#nvidia.dali.fn.external_source) usage please check these guides:
- [intro](https://docs.nvidia.com/deeplearning/dali/user-)guide/docs/examples/general/data_loading/external_input.html
- [making it faster through parallelization](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/parallel_external_source.html)
- [making it faster through parallelization - different approach](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/parallel_external_source_fork.html)

**Comment by Pedrexus** [comment]
Thanks for the links!

Is there a way to set the files and labels argument of `nvidia.dali.fn.readers.file` via the `nvidia.dali.fn.external_source`?

**Comment by JanuszL** [comment]
It is not possible to change `nvidia.dali.fn.readers.file` behavior, but you should use `nvidia.dali.fn.external_source` instead. Then the data source is `nvidia.dali.fn.external_source` itself, as described in [this example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/external_input.html).

**Comment by Pedrexus** [comment]
I understood now. I can use it that way as well.

Thank you for your help.
