### ISSUE TITLE
Question: can I use this library to run my own wavelet kernel ?

### ISSUE THREAD

**Issue by boxerab** [NVIDIA/DALI#4679]
I am interested in batch processing of a collection of 12 bit TIFF images :
1. decode file from disk
1. write to device memory
1. apply colour transform and wavelet kernel on GPU
1. copy back to host memory
1. store to disk. 

I will use the c api for this.
I prefer to use textures if possible rather than buffers for device memory, and also to overlap processing with copy back and forth across PCI bus. 

Is it possible to do this with DALI ? 

Thanks!

**Comment by jantonguirao** [comment]
@boxerab Thank you for your question. What you describe is possible but it might look a little bit convoluted, as currently the C-API is a bit limited. Let me walk you through the necessary steps you need to take:

- Write a Python DALI pipeline performing the processing needed. 
Your pipeline will use a reader (as you need to write your files from disk). Assuming your files are individual `.tiff` files, you'd want to use [fn.readers.file](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.readers.file.html#nvidia.dali.fn.readers.file) for this.
The second step is image decoding. Right now bit-depth other than 8bit is supported via [fn.experimental.decoders.image](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.experimental.decoders.image.html):
```
@pipeline_def(batch_size=BATCH_SIZE, device_id=0, num_threads=3)
def pipe:
  encoded, _ = fn.readers.file(file_root='path/to/dir')
  images = fn.experimental.decoders.image(encoded, device='mixed', dtype=dali.types.UINT16)
  # optional: process here
  return images
```
Depending the color transformation that you need, you can ask DALI to do it for you. What is your target color space?
Regarding the wavelet, you could try to write your own custom operator (see the [tutorial here](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/custom_operations/custom_operator/create_a_custom_operator.html) ), or choose to run this step outside of DALI.

You can test your pipeline in Python, by building and running it:
```
p = pipe()
p.build()
for _ in range(niter):
  images = p.run()[0]
  print(images)
```

When you are satisfied with your pipeline, the next step is to serialize it to be used with the C-API, [example here](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/advanced/serialization.html).

Once your pipeline is serialized, you can run it via the C-API:
```
daliPipelineHandle handle;
daliDeserializeDefault(&handle, serialized.c_str(), serialized.size());
daliPrefetchUniform(&handle, prefetch_queue_depth);

for (...) {
  daliRun(&handle);
  // access outputs, launch kernels, etc
}

daliDeletePipeline(&handle);
```

**Comment by boxerab** [comment]
@jantonguirao thanks very much for your detailed reply. I will try this out.
I have a few questions about the library design - is this documented anywhere ?

**Comment by jantonguirao** [comment]
@boxerab Unfortunately, at the moment we do not have documentation on the library design.

**Comment by JanuszL** [comment]
Hi @boxerab,

The overall 10,000-foot view is:
- DALI consists of kernels (low-level processing operations), operators (interprets arguments, configures kernels, and launches them), and pipeline (execution engine that builds processing graph, runs operators, manages memory)
- DALI processes data in batches to utilize GPU better
- DALI is a native library
- there is a thin python layer that interfaces the native code with frameworks

If you can be more precise about what you want to learn I can point you to the right piece of code.

**Comment by boxerab** [comment]
@JanuszL thanks, what I'm most curious about is how the library designed to achieve efficient overlapping transfers of data between the host and device, and how this is synchronized with the kernel execution.  A high level description would be great, also if you can point me to the places in the code where this happens that would help.

**Comment by JanuszL** [comment]
Hi @boxerab,

Answering your questions, DALI does processing in stages - CPU, mixed and GPU. The type of stage determines the placement (CPU or GPU) of the input and output. The mixed stage does the transfer from the CPU to the GPU either as a plain host to device copy or as an operator that consumes that on the CPU and outputs on the GPU - like image decoding.
Each stage can run in parallel to other ones, due to the multibuffering of data in the stage boundaries.
The synchronization happens only between stages and at the output. The output is synchronous to the main python process, while the stages themselves run in asynchronous threads so much of the DALI work can overlap with the training scripts.
What you can do it capture an [NSight system profile](https://developer.nvidia.com/nsight-systems) of the DALI run to see that in practice.

**Comment by boxerab** [comment]
@JanuszL thanks a lot for the explanation, I will try NSight as you suggest.

**Comment by awolant** [comment]
Hello @boxerab 

Could you tell more about the wavelet kernel that you need? Do you have some implementation on the CPU that you are using already?

Thanks
