### ISSUE TITLE
Call to non-constexpr function set_size(int) from constexpr TensorLayout()

### ISSUE THREAD

**Issue by SomeoneSerge** [NVIDIA/DALI#4688]
Hi! Trying to build dali from source, cf. [logs](https://gist.github.com/SomeoneSerge/50e8573dca9a01eaba26eb8f0b93b097).
You seem to be using `set_size` in `constexpr` functions consistently, so I'm guessing this needs a special toolchain?

https://github.com/NVIDIA/DALI/blob/dfed7275e658f9036a81206b63697c3e0e5c3e9c/include/dali/core/tensor_layout.h#L39

CC https://github.com/NVIDIA/DALI/pull/1237 that introduces this line?

**Comment by JanuszL** [comment]
Hi @SomeoneSerge,

Thank you for reporting this.
One of the issues is indeed a lack of `constexpr`, however, I see there are others. We build DALI successfully with gcc-11 which is the default one available in Ubuntu 22.04.
We will look at these issues, in the meantime feel free to post a PR that could fix them.

**Comment by JanuszL** [comment]
Hi @SomeoneSerge,

I checked the build with gcc 12.2 and https://github.com/NVIDIA/DALI/pull/4692 is the only issue it reported (I cannot repro the other one from your log).
Can you check if this PR fixes all your problems? If not please provide more details on how to set your environment up to repro this.

**Comment by SomeoneSerge** [comment]
Thanks @JanuszL, it worked, I'm past _that_ error now:)
