### ISSUE TITLE
How to install NVIDIA DALI on Windows 10 

### ISSUE THREAD

**Issue by EqUaL90** [NVIDIA/DALI#4690]
Hi.
I discovered that the NVIDIA DALI toolkit is only available for linux OS ([Supported NVIDIA hardware, CUDA, OS, and CUDA driver — NVIDIA DALI 1.23.0 documentation](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/support_matrix.html)).
I have an NVIDIA GeForce RTX 3060 for my deep learning tasks. Is there a way to use my GPU locally using the NVIDIA DALI toolkit on Windows 10?
Or how do I tweak my system to use the DALI’s GPU cloud?
I need help urgently.
Thank you.

**Comment by JanuszL** [comment]
Hi @EqUaL90,

Thank you for reaching out.
To use DALI on the Windows host we recommend using [WSL (Windows Subsystem for Linux](https://developer.nvidia.com/cuda/wsl). For now, we don't have plans to support Windows natively.

> Or how do I tweak my system to use the DALI’s GPU cloud?

All tweaks regarding DALI equally apply to the cloud environment. The best would be to start with [this blog post](https://developer.nvidia.com/blog/case-study-resnet50-dali/) to learn if and how DALI can help in your use case.

Also, if you can provide more details regarding the use case you want to accelerate that would help us to provide more detailed guidance.

**Comment by EqUaL90** [comment]
Thank you Janusz.

I work with satellite imagery for flood mitigation tasks. The goal is to
create a GUI that presents flood impact analysis results and disseminate
early warning messages on phone apps for flood preparedness.

Currently, I use a GeForce RTX 3060 on my computer and it's mindblowing. I
checked your link on WSL, I discovered that I had installed the latest CUDA
driver on my PC already.

Lately, I discovered that the TAO DALI toolkit offers simple workflow
pipelines for training images in highly deep deep learning models and it
contains several pre-trained models.

So, it is only right to explore its applicability to my field of expertise.

Sadly, I use a Windows 10 PC and I do not plan to change my OS permanently
any time soon.

So, I would like to create a hybrid pathway for my PC such that it runs its
default Windows OS and Ubuntu OS, so that I can run the TAO toolkit. I do
not want a dual boot.

*My concern is that if I install  WSL on my machine, will it conflict with
my Windows CUDA-driven Anaconda environment for deep learning?*

Did I answer your question please?

Best regards.
Kola.

**Comment by EqUaL90** [comment]
Simply, I want to run the TAO toolkit, use the docker and deploy models to
create flood dashboards.
So, I require Ubuntu since NVIDIA does not support Windows locally.

What do you think?
Kola

**Comment by JanuszL** [comment]
Hi @EqUaL90,

> *My concern is that if I install  WSL on my machine, will it conflict with
my Windows CUDA-driven Anaconda environment for deep learning?*

These are separate environments. The WSL is more like a virtual machine, and you can access its shell directly from windows. So you can have a separate environment inside WSL and a separate one on your Windows natively, and still, share access to the same filesystem.
I highly recommend checking it out and enjoying the rich Linux ecosystem set of libraries inside your Windows machine.

**Comment by EqUaL90** [comment]
Thank you so much Janusz. I will definitely give it a shot.

**Comment by EqUaL90** [comment]
Dear,

I tried to install NVIDIA DALI on WSL2 through my Ubuntu CMD environment,
but unfortunately, it was unsuccessful. I use Windows 10 and I run Docker
too.

Could you recommend how to install NVIDIA DALI? I believe there ought to be
an all encompassing NVIDIA docker image file.

I seriously need some help.
Kola

**Comment by JanuszL** [comment]
Hi @EqUaL90,

Could you provide the steps you followed?
In my case it seems to work fine:
```
C:\Users\user>wsl
Welcome to Ubuntu 22.04.1 LTS (GNU/Linux 5.15.90.1-microsoft-standard-WSL2 x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Mon Mar 27 09:27:36 CEST 2023

  System load:  0.0732421875       Processes:             9
  Usage of /:   1.4% of 250.92GB   Users logged in:       0
  Memory usage: 2%                 IPv4 address for eth0: xx.xx.xx.xx
  Swap usage:   0%


Expanded Security Maintenance for Applications is not enabled.

0 updates can be applied immediately.

Enable ESM Apps to receive additional future security updates.
See https://ubuntu.com/esm or run: sudo pro status


The list of available updates is more than a week old.
To check for new updates run: sudo apt update


This message is shown once a day. To disable it please create the
/root/.hushlogin file.
root@user-lt:/mnt/c/Users/user# pip install --extra-index-url https://developer.download.nvidia.com/compute/redist --upgrade nvidia-dali-cuda110
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com, https://developer.download.nvidia.com/compute/redist
Requirement already satisfied: nvidia-dali-cuda110 in /usr/local/lib/python3.10/dist-packages (1.22.0)
Collecting nvidia-dali-cuda110
  Downloading https://developer.download.nvidia.com/compute/redist/nvidia-dali-cuda110/nvidia_dali_cuda110-1.23.0-7355173-py3-none-manylinux2014_x86_64.whl (485.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 485.4/485.4 MB 7.3 MB/s eta 0:00:00
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from nvidia-dali-cuda110) (1.6.3)
Requirement already satisfied: gast<=0.4.0,>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from nvidia-dali-cuda110) (0.4.0)
Requirement already satisfied: six<2.0,>=1.6.1 in /usr/lib/python3/dist-packages (from astunparse>=1.6.0->nvidia-dali-cuda110) (1.16.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/lib/python3/dist-packages (from astunparse>=1.6.0->nvidia-dali-cuda110) (0.37.1)
Installing collected packages: nvidia-dali-cuda110
  Attempting uninstall: nvidia-dali-cuda110
    Found existing installation: nvidia-dali-cuda110 1.22.0
    Uninstalling nvidia-dali-cuda110-1.22.0:
      Successfully uninstalled nvidia-dali-cuda110-1.22.0
Successfully installed nvidia-dali-cuda110-1.23.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
root@user-lt:/mnt/c/Users/user# python -c "import nvidia.dali; print(nvidia.dali.__version__)"
/usr/local/lib/python3.10/dist-packages/nvidia/dali/backend.py:46: Warning: DALI support for Python 3.10 is experimental and some functionalities may not work.
  deprecation_warning("DALI support for Python {0}.{1} is experimental and some "
1.23.0
```

**Comment by EqUaL90** [comment]
Thank you for your help @JanuszL. 

I installed WSL2 in a PowerShell environment (https://docs.nvidia.com/cuda/wsl-user-guide/index.html). then, I installed Ubuntu, which works perfectly. I followed the instructions on the weblink religiously.

Then, I installed Docker Desktop to hold my containers.  I pulled the hello.py package and it worked. 

Later, I navigated to _https://docs.nvidia.com/deeplearning/dali/user-guide/docs/installation.html_  and  updated my CUDA 12 drivers using "_pip install --extra-index-url https://developer.download.nvidia.com/compute/redist --upgrade nvidia-dali-cuda120_".

However, I tried to install DALI but unfortunately, I encountered an error warning: 
 _note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for nvidia-dali-tf-plugin-cuda120
  Running setup.py clean for nvidia-dali-tf-plugin-cuda120
Failed to build nvidia-dali-tf-plugin-cuda120
Installing collected packages: nvidia-dali-tf-plugin-cuda120
  Running setup.py install for nvidia-dali-tf-plugin-cuda120 ... error
  error: subprocess-exited-with-error

  × Running setup.py install for nvidia-dali-tf-plugin-cuda120 did not run successfully._ 

I have uploaded some screenshots here .

Currently, I use 'Terminal' which allows the integration of PowerShell, Gitbash, Ubuntu all at once etc.

I look forward to hearing from you.

![SMI](https://user-images.githubusercontent.com/86033072/227981960-87917163-0c99-4fa8-8cb9-3b846ffb5d9a.JPG)
![Docker shot](https://user-images.githubusercontent.com/86033072/227982012-db1acbf9-d1c2-4d70-902f-7d8f467d73ef.JPG)
![DALI fail](https://user-images.githubusercontent.com/86033072/227982104-76517693-b5ba-4446-abc8-2fda456c02a2.JPG)

**Comment by obasekore** [comment]
Hi @EqUaL90,

You may want to try [TensorFlow NGC Container](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/tensorflow). It contains software for accelerating ETL ([DALI](https://developer.nvidia.com/dali), [RAPIDS](https://rapids.ai/)), Training ([cuDNN](https://developer.nvidia.com/cudnn), [NCCL](https://developer.nvidia.com/nccl)), and Inference ([TensorRT](https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html)) workloads. 

If you want to use it with jupyter notebook, consider exposing port 8888 and mounting your volume.

Typical use case example for mounting your current windows directory (in command prompt);

`
docker run --gpus all -it -v "%cd%":/workspace/mycode -p 8888:8888 nvcr.io/nvidia/tensorflow:22.01-tf2-py3
`

Kind regards,

**Comment by EqUaL90** [comment]
Hi @JanuszL and @obasekore ,
I am so grateful for your contributions.
With your help, I have successfully installed all packages.
Have a wonderful day.
Best wishes.

**Comment by richmengsix** [comment]
Looking forward to supporting DALI on windows platform!
