### ISSUE TITLE
fn.slice error with no info

### ISSUE THREAD

**Issue by wukong1992** [NVIDIA/DALI#4691]
This is my code:
```
fronts = fn.slice(fronts, types.Constant(np.array([h_1, h_2])),
                                      types.Constant(np.array([w_1, w_2])), device="gpu", out_of_bounds_policy="trim_to_shape")
        rights = fn.slice(rights, types.Constant(np.array([h_1, h_2])),
                                      types.Constant(np.array([w_1, w_2])), device="gpu", out_of_bounds_policy="trim_to_shape")
        rears = fn.slice(rears, types.Constant(np.array([h_1, h_2])),
                                      types.Constant(np.array([w_1, w_2])), device="gpu", out_of_bounds_policy="trim_to_shape")
        lefts = fn.slice(lefts, types.Constant(np.array([h_1, h_2])),
                                      types.Constant(np.array([w_1, w_2])), device="gpu", out_of_bounds_policy="trim_to_shape")
```

The program failed with no other info，I didn't know where is wrong, cas there is no other trace info.

**Comment by awolant** [comment]
Hello, 
thanks for creating the issue. 

Is there any difference in the images that you load to `fronts`, `rights`, `rears` and `lefts`? If I would use the same path for all of them would it be fair reproduction of your workflow?
Also, what are the values for `h1`, `h2`, `w_1` and `w_2` with relation to the size of images that you are using?

These details will help me narrow down the issue faster. Thanks a lot.

**Comment by wukong1992** [comment]
@awolant Thank you  for your answer. Yes, you can use same path to reproduction. I use the torchrun script to start train, I did not test without torch.distributed, But I am sure, without ops slice, the train is ok. h1, h2, w1, w2 is the crop window.

**Comment by JanuszL** [comment]
Hi @wukong1992,

Can you provide [a full, self-contained reproduction code we can run](https://github.com/NVIDIA/DALI#reporting-problems-asking-questions)? You can use https://github.com/NVIDIA/DALI_extra/tree/main/db as a source of the data if you like.
I don't see any obvious issue with the pipeline code you provided so it could be specific to the data you provide to it or the code that uses it.

**Comment by wukong1992** [comment]
Solved! I miss understand the fn.slice params. This worked: 
``` 
fronts = fn.slice(fronts, types.Constant(np.array([h_1, w_1])),
                                     types.Constant(np.array([h_2, w_2])), device="gpu", out_of_bounds_policy="trim_to_shape")
```
Thank you!

**Comment by awolant** [comment]
Thanks for the question.
Was there anything in the documentation of `slice` that was particularly misleading or unclear that we could improve? Or maybe some example was missing from the tutorials? 
Feedback like this will help us make it better for the users in the future.
