### ISSUE TITLE
When Dali using GPU Direct Storage ?

### ISSUE THREAD

**Issue by aiinfralab** [NVIDIA/DALI#4701]
storage --> cpu --> gpu --> model

I know that nvidia dali uses gpu direct storage, but according to the official guide for dali, it loads the data and moves it to the GPU after CPU primary processing.

Then...what stage is gpu direct storage used?

Doesn't the GPU memory already contain data that has been primary processed by the CPU?
If so, GPU processing doesn't use GPU Direct Storage... ;-|

I want to know when and how GPU direct storage is used during Dali's detailed data processing.

**Comment by JanuszL** [comment]
Hi @aiinfralab,

Thank you for reaching out.
As you correctly pointed out, DALI does processing in stages. Stages can run in parallel, so the CPU can process data for one stage N, mixed operators for stage N-1, and GPU for stage N-2. If there are no operators in the given stage there are just no-ops.
DALI uses GPU direct storage only for the GPU variant of [the numpy reader operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.readers.numpy.html), as in the most of the use case need the initial processing of the data read from the storage processed on the CPU (even the image decoding requires the initial parsing to happen on the CPU). In the case of the numpy reader, only the header needs to be parsed on the CPU while the rest of the data can be directly transferred to the GPU.
So to answer your question, if you use GPU numpy reader and then the GDS transfer happens in the GPU processing stage of DALI.

I hope this answers your question.

**Comment by aiinfralab** [comment]
Great Thank you for your kind answer.
A big problem has been solved.

May I ask one more question?

I understood that fn.readers.numpy reads the file in nvidia.dali.fn.readers.numpy format and processes it.

If so, in what format does fn.readers.file process the data? 

Is the data format normally processed internally by dali something other than nvidia.dali.fn.readers.numpy?

**Comment by JanuszL** [comment]
Hi @aiinfralab,

[The `fn.readers.file` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.readers.file.html#nvidia.dali.fn.readers.file) reads the data as it is and pass it further as a 1D tensor of raw bytes. In the code of [`readers.numpy`](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.readers.numpy.html) it reads the numpy array and presents it as a DALI tensor, what means it preserves the type and dimensionality.
Regarding the GDS example, please check the examples listed on the bottom of the operator dokumentalistą page, for example [this one](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/numpy_reader.html).

**Comment by aiinfralab** [comment]
Hi @JanuszL 
Thanks for your help. 
All problems were solved.
