### ISSUE TITLE
nvidia.fn.experimental.decoders.video does not return the correct frame for higher resolution videos

### ISSUE THREAD

**Issue by hfchong** [NVIDIA/DALI#4709]
When decoding higher resolution videos with `device="mixed"`, this decoder returns the wrong frames (last few frames) on the `prefetch_queue_depth + 1`<sup>th</sup> video

System used
python: 3.8.16
nvidia-dali: 1.23.0 (for CUDA 12.0)
GPU: Tesla T4

To replicate this error, you can download a public video, resize it to 1920 x 1080, and extract multiple 1s videos from it

```
import subprocess
import wget

raw_video = "raw.mp4"
resized_video = "resized.mp4"

WIDTH = 1920

# Download video
response = wget.download("https://motchallenge.net/sequenceVideos/MOT17-02-FRCNN-raw.mp4", raw_video)

# Resize video
cmd = [
    "ffmpeg", "-i", raw_video, "-filter:v", f"scale={WIDTH}:-1", "-an", resized_video
]
subprocess.run(cmd)

# Trim 10 1s videos
for i in range(10):
    cmd = ["ffmpeg", "-ss", str(i), "-i", resized_video, "-t", "1", "-c:v", "libx264", "-crf", "3", "-an", "video{:03}.mp4".format(i)]
    subprocess.run(cmd)
    print(i)
```

Compare dali decoded video with cv2 decoded video on a video by video and frame by frame basis

```
import glob
from itertools import cycle

import matplotlib.pyplot as plt
import cv2
import numpy as np
from nvidia.dali import pipeline_def
import nvidia.dali.fn as fn
import nvidia.dali.types as types

device = "mixed"
batch_size = 1

filenames = sorted(glob.glob("video*.mp4"))

def input_gen(batch_size, filenames=filenames):
    filenames = cycle(filenames)
    while True:
        batch = []
        for _ in range(batch_size):
            batch.append(np.fromfile(next(filenames), dtype=np.uint8))
        yield batch

@pipeline_def
def test_pipeline():
    vid = fn.external_source(device='cpu', source=input_gen(batch_size))
    seq = fn.experimental.decoders.video(vid, device=device)
    seq = fn.color_space_conversion(
        seq,
        image_type=types.DALIImageType.RGB,
        output_type=types.DALIImageType.BGR
    )
    return seq

video_pipeline = test_pipeline(batch_size=1, num_threads=4, device_id=0, prefetch_queue_depth=1)

video_pipeline.build()

found_error = False
for filename in filenames:
    pipe_out = video_pipeline.run()
    if device == "mixed":
        dali_frames = pipe_out[0].as_cpu().as_array()[0]
    else:
        dali_frames = pipe_out[0].as_array()[0]

    cap = cv2.VideoCapture(filename)
    cv2_frames = []
    frame_idx = 0
    while(cap.isOpened()):
        ret, cv2_frame = cap.read()
        if ret:
            cv2_frames.append(cv2_frame)
            # compare dali decoded frame with cv2 decoded frame
            diff = np.mean(np.abs(dali_frames[frame_idx].astype(int) - cv2_frame.astype(int)))
            if diff > 2:
                # Exit to further examine the frames if they seem different
                print(f"Error for file: {filename} and frame: {frame_idx}")
                found_error = True
                break
            frame_idx += 1
        else:
            break
    
    if found_error:
        break
```

The erroneous video starts from `prefetch_queue_depth + 1`<sup>th</sup> video (realised this after experimenting with `prefetch_queue_depth`). If `prefetch_queue_depth = 1`, the first erroneous video will be the second video, i.e., `video001.mp4` starting from frame 26. See below (`frame_idx` is of value 26):

`plt.imshow(dali_frames[frame_idx][:,:,::-1])`
![image](https://user-images.githubusercontent.com/6982447/224910836-5c2d16c6-67bc-41e0-afe6-bbd4dd364cd0.png)

`plt.imshow(cv2_frames[frame_idx][:,:,::-1])`
![image](https://user-images.githubusercontent.com/6982447/224910906-15a3d23d-71e2-4b99-b7c3-4a9a13b02cbf.png)

The frame is correct for frame 25 and below but `nvidia.fn.experimental.decoders.video` returns the wrong frame from 26 onwards. All subsequent videos seem to have similar errors. Also no such error occurs when `device = "cpu"` or when video resolution is low enough, e.g., if we set `WIDTH <= 960`. This also works correctly when using the experimental pipeline debug mode.

**Comment by awolant** [comment]
Hello @hfchong 
Thanks for your question and excellent reproduction. 

Unfortunately, for my environment I did not get the error you did. Could you share more details about your setup? What `ffmpeg` version and `cv2` do you have? Would it be possible for you to upload the cut failing video files? This would allow us to eliminate some variables. 

For the `cpu` variant experimental video decoder uses `ffmpeg` as its backend, so basically the same thing as `cv2`.

**Comment by hfchong** [comment]
Hi @awolant, thanks for the swift reply!

ffmpeg version: 4.2.7
cv2 version: 4.2.0

I used the docker image `nvcr.io/nvidia/pytorch:23.01-py3` and then installed ffmpeg (apt-get update && apt-get upgrade -y && apt-get install ffmpeg). 

However, the preinstalled cv2 version provided in the docker image could not detect the installed ffmpeg package when I ran `python3 -c "import cv2; print(cv2.getBuildInformation())" | grep -i ffmpeg`. It was a bit hacky but I had to run `apt-get install python3-opencv` and `pip3 install opencv-python && pip3 uninstall opencv-python` before `python3 -c "import cv2; print(cv2.getBuildInformation())" | grep -i ffmpeg` showed YES. 

I then ran the above code in a jupyter notebook.

**Comment by hfchong** [comment]
To replicate the environment, below is the Dockerfile
```
FROM nvcr.io/nvidia/pytorch:23.01-py3

RUN apt-get update && apt-get upgrade -y
RUN DEBIAN_FRONTEND=noninteractive apt-get install ffmpeg -y
# Remove manually preinstalled cv2 package (unable to detect ffmpeg that was just installed)
RUN rm -rf /usr/local/lib/python3.8/dist-packages/cv2
RUN pip install --extra-index-url https://developer.download.nvidia.com/compute/redist --upgrade \
    wget==3.2 \
    opencv-python==4.7.0 \
    nvidia-dali-cuda120==1.23.0
```

I have included the Dockerfile as well as the jupyter notebook in the zipped file below.

[Dockerfile+Jupyter Notebook.zip](https://github.com/NVIDIA/DALI/files/10976371/Dockerfile%2BJupyter.Notebook.zip)

**Comment by hfchong** [comment]
@JanuszL I compiled the bug fix and ran the code and it is working fine now! Thanks for the fixing the issue so quickly!

**Comment by JanuszL** [comment]
Thank you for confirming that it works on your end. It should be merged soon and available in the nightly build that follows the merge commit.

**Comment by JanuszL** [comment]
1.25 should be available now. Please check and reopen if it still doesn't work.
