### ISSUE TITLE
yolov4 pipline

### ISSUE THREAD

**Issue by tendar** [NVIDIA/DALI#4711]
HI,

I saw the pipeline of yolov4
https://github.com/NVIDIA/DALI/blob/2197024155f21e38f63d5b0b56959c4a4b1a63a7/docs/examples/use_cases/tensorflow/yolov4/src/dali/ops.py#L109.
Here why should use reduction operator and ' - anchor'
Hope your replay, Thanks

**Comment by JanuszL** [comment]
Hi @tendar,

Thank you for reaching out.
I does exactly `# swap coordinates (x, y) -> (y, x)`.
In steps it does:
- for input [(a,b)]
- `dali.fn.reductions.sum(in_anchor)` -> [(a+b)]
- `dali.fn.reductions.sum(in_anchor) - in_anchor` -> [((a+b) - a, (a+b) -b)] = [(b, a)]. It is possible thanks to shape broadcasting

**Comment by tendar** [comment]
Get it, thanks.
