### ISSUE TITLE
How to provide labels to numpy reader

### ISSUE THREAD

**Issue by Pedrexus** [NVIDIA/DALI#4713]
Hello,

I am currently trying to use the numpy reader for a supervised task, but does not have a "labels" parameter like other readers. Is there a simple way to provide the labels? 

I tried using the `get_property` operator with key`="source_info"` and from there try to retrieve the labels, but I've been facing an issue where the filepath come empty on the last batch if I set `LastBatchPolicy.PARTIAL` and `pad_last_batch=true`. Is there a work around?

Thank you

**Comment by JanuszL** [comment]
Hi @Pedrexus,

> I am currently trying to use the numpy reader for a supervised task, but does not have a "labels" parameter like other readers. Is there a simple way to provide the labels?

Thank you for reaching out. Indeed there is a bug and it should be fixed in https://github.com/NVIDIA/DALI/pull/4714.
In the meantime, the only thing that comes to my mind on how to support your use case until the fix is merged is to create a set of numpy files with the label values inside and create a separate numpy reader instance that would read them. As long as you seed the same seed in both readers and provide the files in the same order to them the results should be in sync.

**Comment by Pedrexus** [comment]
Thank you for the quick response! I will try this idea. For now, I was able to set device = gpu and pad_last_batch = False without big problems on my side. device = cpu does not work at all however.

**Comment by JanuszL** [comment]
There are different flavors of this bug and the mentioned PR should fix it for the CPU and GPU variants of the reader.

**Comment by dyhan316** [comment]
@Pedrexus Hi! Just want to clarify : do you mean that using `get_property` on `readers.numpy` was possible if the `pad_last_batch` was set to False and the image was in the gpu?

Could you share a code? I tried to do as you said to get `get_property`, but was unsuccessful! (below is a code in case you read interested)

```python

import numpy as np
from nvidia.dali.plugin.pytorch import DALIGenericIterator
from nvidia.dali.plugin.base_iterator import LastBatchPolicy

def sharded_pipeline(BATCH_SIZE,device_id, shard_id, num_shards, seed, shuffle, pad_last_batch):
    pipe = Pipeline(batch_size= BATCH_SIZE, num_threads=4, device_id=device_id)
    with pipe:
        img = fn.readers.numpy(file_root = data_path, shard_id = shard_id,
                               num_shards = num_shards, seed = seed, random_shuffle = shuffle,
                              pad_last_batch = pad_last_batch, name = "TestReader")
        img = img.gpu()
        pipe.set_outputs(img, fn.get_property(img, key = "source_info"))

    return pipe
    ```
    
    then, ran,
    ```python
    pipe_one = sharded_pipeline(BATCH_SIZE = 7, device_id=0, shard_id=0, 
                            num_shards=1, seed = 0, shuffle = False,
                            pad_last_batch = False)
pipe_one.build()
img,prop = pipe_one.run()

print(img)
print(prop)
  ====results====
TensorListGPU(
    [[ 0]
     [ 1]
     [10]
     [11]
     [12]
     [13]
     [14]],
    dtype=DALIDataType.INT64,
    num_samples=7,
    shape=[(1,), (1,), (1,), (1,), (1,), (1,), (1,)])
TensorListGPU(
    [],
    dtype=DALIDataType.UINT8,
    num_samples=7,
    shape=[(0,), (0,), (0,), (0,), (0,), (0,), (0,)])
    
    ```

**Comment by Pedrexus** [comment]
Hello, @dyhan316 .

I think in your example, maybe setting `device="gpu"` could fix it for you instead of "img.gpu()", this is the only difference I can see from my own snippet. In my case, I used something like, similar to yours:

```python
 reader = nvidia.dali.fn.readers.numpy(
    device="gpu",
    cache_header_information=True,
    dont_use_mmap=False,
    files=[...],
    fill_value="0",
    initial_fill="1024",
    lazy_init=False,
    out_of_bounds_policy="error",
    pad_last_batch=False,
    prefetch_queue_depth="2",
    preserve=False,
    random_shuffle=True,
    read_ahead=True,
    register_buffers=True,
    skip_cached_images=True,
    tensor_init_bytes="1024",
    shuffle_after_epoch=False,
    stick_to_shard=False
)
```

**Comment by dyhan316** [comment]
Thank you! Ill try as you said!

**Comment by JanuszL** [comment]
@dyhan316 - please wait for the 1.25 release (which should happen this week) or try out the nightly build and check if that works for you.

**Comment by dyhan316** [comment]
Thank you! I'll look forward to the next release :):)

**Comment by Pedrexus** [comment]
Thank you for the update @JanuszL ! Looking forward to the next release as well.

**Comment by JanuszL** [comment]
1.25 should be available now. Please check and reopen if it still doesn't work.
