### ISSUE TITLE
how to calculate  affine transformation matrix from three source points and destination three points using dali？

### ISSUE THREAD

**Issue by DequanZhu** [NVIDIA/DALI#4729]
I want to build my face recognition system using trtionserver . The system is consist of three part: face detection, face keypoint detection and face feature extraction. I want to use dali to implement some preprocess and postprocess calculation. Now I have a problem when dealing face alignment which is preprocess part of face feature extraction. I need to calculate the affine transformation matrix according to source face keypoints which is outputs of face keypoint model loaded by tritionserver  and destination standard reference keypoints coordinates thus I can use this matrix to warpaffine the detected face. Is there any operation can do this operation?

**Comment by JanuszL** [comment]
Hi @DequanZhu,

Thank you for reaching out. Can you tell us more about your request and the use case?
