### ISSUE TITLE
Support for boolean tensors

### ISSUE THREAD

**Issue by eugen-vusak** [NVIDIA/DALI#4756]
Hello,

Is there any good reason why `torch.bool` is not supported? From what I was able to deduce it is missing in `to_torch_type` dictionary which is used when calling `DALIGenericIterator`

https://github.com/NVIDIA/DALI/blob/115cab9f07c5f1d331793fc111d6004cfc1f936d/dali/python/nvidia/dali/plugin/pytorch.py#L26+L35

Thank you.

**Comment by JanuszL** [comment]
Hi @eugen-vusak,

https://github.com/NVIDIA/DALI/pull/4757 should add and test the missed functionality.
If you see any other missing type supported please let us know.

**Comment by JanuszL** [comment]
1.25 should be available now. Please check and reopen if it still doesn't work.
