### ISSUE TITLE
Running conditional execution pipelines on class object

### ISSUE THREAD

**Issue by Esthesia** [NVIDIA/DALI#4767]
I checked the pipeline code works properly and ran via my code and got errors.
This is my code snippet on pipeline definitions.

```python
class RandAugmentPipe(Pipeline):

...

    @experimental.pipeline_def(enable_conditionals=True)            
    def define_graph(self):

        self.jpegs, self.labels = dali.fn.external_source(
            source=self.eii_gpu, num_outputs=2, device="cpu")

        # Combined decode & random crop
        images = fn.decoders.image(self.jpegs, device="mixed")

        extra = {}
        images = rand_augment.rand_augment(images, n=2, m=9, **extra)
        images = fn.random_resized_crop(images, size=[self.crop,self.crop])
        
				self.labels = self.labels.gpu()
        return (images, self.labels)

....

  self.train_pipe = RandAugmentPipe(....)
  self.train_pipe.build()
```

The error logs tell me that the `types.Constant` which the parameter must reside on CPU side.

```jsx
TypeError: Illegal output type. The output 0 is a `<class 'nvidia.dali.pipeline.Pipeline'>`. 
Allowed types are ``DataNode`` and types convertible to `types.Constant` 
(numerical constants, 1D lists/tuple of numbers and ND arrays).
```

Can you give me advice because above errors based on the operator residing on CPU side which is not my intention.

**Comment by stiepan** [comment]
Hi @Esthesia,

Thanks for reaching out! 

Your code mixes two DALI API's: the older one, class-based (`class Pipeline`, `define_graph`), and the newer, functional one (`@pipeline_def(enable_conditionals=True)`, `fn.`).

We keep the class API for backward compataibility, but the functional one is actively developed and recommended. The conditional execution, which is a backbone of automatic augmentations, is currently only supported for functional API.

I've tried running an equivalent code based on functional API and it seems to resolve the issue.

```
@experimental.pipeline_def(enable_conditionals=True)            
def pipeline(crop=224):

    jpegs, labels = dali.fn.external_source(
            source=self.eii_gpu, num_outputs=2, device="cpu")
    images = fn.decoders.image(jpegs, device="mixed")

    images = rand_augment.rand_augment(images, n=2, m=9)

    images = fn.random_resized_crop(images, size=[crop, crop])

    labels = labels.gpu()
    return images, jpegs
 ```

**Comment by Esthesia** [comment]
@stiepan Thanks for detailed and quick response for my inquiry.
By the way, with functional implementation, is there any problems or considerations when making pipeline function as a class member function?

**Comment by Esthesia** [comment]
Thanks for all on detailed information on conditional execution with randaugment
