### ISSUE TITLE
Does randaugment pipeline consume large GPU memory?

### ISSUE THREAD

**Issue by Esthesia** [NVIDIA/DALI#4776]
Dear all,

I use a Python training script based on `docs/examples/use_cases/pytorch/resnet50/main.py`.
The only difference is changing the pipeline code to use RandAugment.
The pipeline code is below.

```
@experimental.pipeline_def(enable_conditionals=True)            
def create_dali_pipeline(data_dir, crop, size, shard_id, num_shards, dali_cpu=False, is_training=True):
    rng = fn.random.coin_flip(probability=0.5)
    images, labels = fn.readers.file(file_root=data_dir,
                                     shard_id=shard_id,
                                     num_shards=num_shards,
                                     random_shuffle=is_training,
                                     pad_last_batch=True)

    mean=(0.485 * 255, 0.456 * 255, 0.406 * 255)
    std=(0.229 * 255, 0.224 * 255, 0.225 * 255) 

    if is_training:
        images = fn.decoders.image(images, device="mixed")
        images = rand_augment.rand_augment(images, n=2, m=9)
        images = fn.random_resized_crop(images, size=[crop, crop], minibatch_size=1)
        output = fn.crop_mirror_normalize(images,
                                            mirror=rng,
                                            mean=mean,
                                            std=std,
                                            dtype=types.DALIDataType.FLOAT,
                                            output_layout=types.NCHW)
```

I ran ResNet-18 on a single RTX3090 GPU (24GB memory) with 500 batch size but got GPU OOM.

```
RuntimeError: Critical error in pipeline:
Error when executing GPU operator ArithmeticGenericOp, instance name: "__ArithmeticGenericOp_226", encountered:
Can't allocate 114622464 bytes on device 0.
```

Should I reset the pipeline every iteration or do any suggestions for this problem?

**Comment by klecki** [comment]
Hi @Esthesia,
yes, the use of automatic augmentations may increase the memory consumption.
We did a change to alleviate some of the problems here: https://github.com/NVIDIA/DALI/pull/4697, but it didn't make to the latest release.
You can try the [nightly or weekly builds](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/installation.html#pip-nightly-and-weekly-releases) to see if it helps in your case or wait for DALI 1.25 which will be released by the end of this month.

Keep in mind, that adding more operators or executing an automatic augmentations scheme like RandAugment, even with the #4697 fix will still increase the memory consumption of the DALI pipeline - at least by the size needed to keep the additional batches in memory.

**Comment by Esthesia** [comment]
@klecki Thanks for answering. I minimized the effect on conditional execution by resizing the image before executing `randaugment` functionality. Thank you for your information, and I will keep track of the nightly version.

```
        ......
        images = fn.resize(images, size=(resize, resize)) # If not resizing, OOM occurs on rand_augment
        images = rand_augment.rand_augment(images, n=2, m=9)
        .......
```
