### ISSUE TITLE
If my data does not have a channel dimension, should I intentionally introduce the dimension?

### ISSUE THREAD

**Issue by dyhan316** [NVIDIA/DALI#4777]
Hello! 

I have the following questions regarding the existence of channels in my data when using DALI 

* If my input data does not have a channel (DHW), should I intentionally add a channel dimension?  I am asking because functions like `nvidia.dali.fn.flip` only seem to take in TensorLists that has a channel dimension. 

* On the contrary, it seems that operations like `dali.fn.gaussian_blur`  does not consider the channel axis. If, for instance, I added a channel dimension to my data to pass it through `fn.flip` (via something like `imp = img[dali.newaxis]`) and want to pass the result through `gaussian_blur`, should I convert it back to drop out the channel dimension? (if so, how should I add/subtract the channel dimensions?)
Thank you in advance for anyone's help!

**Comment by JanuszL** [comment]
Hi @dyhan316,

Thank you for reaching out.
Please try using [the `reshape` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.reshape.html) that operates on metadata and can add/remove channels.

**Comment by dyhan316** [comment]
Thank you!

**Comment by dyhan316** [comment]
I have a further question if you don't mind! @JanuszL  If I want to have two data

**Comment by JanuszL** [comment]
Hi @dyhan316,

If these images are anyhow connected (like image and mask) you can use two readers and set the same seed so they work in sync. You can also use [the 'external source' operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/parallel_external_source.html) and return two items from it.

**Comment by dyhan316** [comment]
Wow! Thank you for your quick response! :)
