### ISSUE TITLE
How to do different batch sizes in DALI and pytorch training?

### ISSUE THREAD

**Issue by dyhan316** [NVIDIA/DALI#4784]
Is there a way to use different batch sizes for when I load the data using DALI and when I am actually feeding in the data as a batch?

In the [documentation](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/frameworks/pytorch/pytorch-basic_example.html) , the example code is like below. However, this means that the variable `BATCH_SIZE` is the same for both the DALI pipeline and the input to the model. Is there a way so that the DALI pipeline's batch size is, say, 16, but the model's batch size is 64? (I am asking because increasing the DALI pipeline's batch size seems to increase the VRAM used, but the bottleneck (after changing to DALI) now is the torch model training itself, not the DALI loader. Therefore I was wondering if I could like aggregate the results of the DALI pipeline on 16 batches 4 times to feed into the model)
```
import numpy as np
from nvidia.dali.plugin.pytorch import DALIGenericIterator


label_range = (0, 999)
pipes = [caffe_pipeline(
    batch_size=BATCH_SIZE, num_threads=2, device_id=device_id, num_gpus=N) for device_id in range(N)]

for pipe in pipes:
    pipe.build()

dali_iter = DALIGenericIterator(pipes, ['data', 'label'], reader_name='Reader')

for i, data in enumerate(dali_iter):
    # Testing correctness of labels
    for d in data:
        label = d["label"]
        image = d["data"]
        ## labels need to be integers
        assert(np.equal(np.mod(label, 1), 0).all())
        ## labels need to be in range pipe_name[2]
        assert((label >= label_range[0]).all())
        assert((label <= label_range[1]).all())

print("OK")
```

Thank you in advance for anyone's help and this wonderful library!!

**Comment by JanuszL** [comment]
Hi @dyhan316,

Thank you for reaching out. The only thing that comes to my mind is to aggregate the data manually:
```
images = [[] for x in range(N)]
labels = [[] for x in range(N)]
for i, data in enumerate(dali_iter):
    for j, d in enumerate(data):
        images[j].append(d["data"])
        labels[j].append(d["label"])
    if int(BATCH_SIZE * i / MODEL_BATH_SIZE) != BATCH_SIZE * i // MODEL_BATH_SIZE:
        continue
    images_to_train = []
    labels_to_train = []
    for j, d in enumerate(images):
        images_to_train.append(torch.cat(*images[j], 0))
    for j, d in enumerate(labels):
        labels_to_train.append(torch.cat(*labels[j], 0))
    images = [[] for x in range(N)]
    labels = [[] for x in range(N)]
   # do the training using images_to_train and labels_to_train
```

**Comment by dyhan316** [comment]
Thank you again so much! :)
