### ISSUE TITLE
Does 'num_threads' option may affect maximum GPU utilization?

### ISSUE THREAD

**Issue by Esthesia** [NVIDIA/DALI#4787]
Dear all,

Always thanks for quick and detailed answers.

I wonder whether num_thread which is the number of CPU threads used by this pipeline may affect the GPU utilization?
I ran DALI pipeline with different `num_threads` options and analyze the GPU utilization. (1, 2, and 4)
I found that maximum GPU utilization is lower when I increased the number of CPU threads.
I think DALI can hide prep stall and utilize the GPU when GPU is not on training but It seems weird to me
that the maximum utilization is decreasing because as far as I know, ResNet model is compute-intensive model which means
it consumes almost utilization on GPU side.

* ResNet-18 model with batch size 500 
* GPU generation - NVIDIA RTX 3090 (24GiB GPU memory)
* Pipeline code snippet that I used below

```
@experimental.pipeline_def(enable_conditionals=True)            
def create_dali_pipeline(data_dir, crop, size, shard_id, num_shards, dali_cpu=False, is_training=True):
    rng = fn.random.coin_flip(probability=0.5)
    images, labels = fn.readers.file(file_root=data_dir,
                                     shard_id=shard_id,
                                     num_shards=num_shards,
                                     random_shuffle=is_training,
                                     pad_last_batch=True,
                                     name="Reader")

    mean=(0.485 * 255, 0.456 * 255, 0.406 * 255)
    std=(0.229 * 255, 0.224 * 255, 0.225 * 255) 

    images = fn.decoders.image(images, device="mixed")
    images = fn.resize(images, size=(244, 244)) # If not resizing, OOM occurs on rand_augment
    images = rand_augment.rand_augment(images, n=2, m=9)
    images = fn.random_resized_crop(images, size=[crop, crop], minibatch_size=1)
    output = fn.crop_mirror_normalize(images,
                                        mirror=rng,
                                        mean=mean,
                                        std=std,
                                        dtype=types.DALIDataType.FLOAT,
                                        output_layout=types.NCHW)
                                            
    labels = labels.gpu()
    return output, labels
```

This is the experiment result graphs that I ran. You can see the utilization in the blue one.

![gpu_utilization_memory_usage_thread_1](https://user-images.githubusercontent.com/41190076/231907894-d024bad4-6982-4b3d-820b-51e6df0316df.jpg)

![gpu_utilization_memory_usage_thread_2](https://user-images.githubusercontent.com/41190076/231907946-edd19add-26b3-4741-8eaa-180eecdb9bfd.jpg)

![gpu_utilization_memory_usage_thread_4](https://user-images.githubusercontent.com/41190076/231907977-fc500a9e-2676-4527-ae83-06105c65622c.jpg)

For reference, this is the naive PyTorch data-loading and the same model training case.

![gpu_utilization_memory_usage_PT_Baseline](https://user-images.githubusercontent.com/41190076/231908842-23797071-6af5-4953-8118-cdb5392486de.jpg)

Thank you

**Comment by JanuszL** [comment]
Hi @Esthesia,

These are interesting findings. Can you also share how the GPU utilization translates to the training speed in your case?
What also can tell us more about the things happening under the hood is [an NSight System profile](https://developer.nvidia.com/nsight-systems).
The way the number of threads may affect the GPU pipeline performance is the fact that the `mixed` image decoder uses threads to perform the CPU part of the decoding (as the JPEG decoding consists of two steps - Huffman decoding - which may happen on the CPU, and the IDCT transformation and color conversion done on the GPU). But the more threads you use the faster the decoding process should be.

**Comment by Esthesia** [comment]
Hello @JanuszL 
Thanks for your answer. I need to verify my profiling, so it needs to take some time.

I found out that the profiling had been misread.

Here is the modified profiling.

![gpu_utilization_memory_usage_thread_1_RN18](https://user-images.githubusercontent.com/41190076/234152168-bf9b5766-34fb-4148-9816-3d53c593180c.jpg)
![gpu_utilization_memory_usage_thread_2_RN18](https://user-images.githubusercontent.com/41190076/234152180-c7ea1c94-0e0a-480e-9cba-1260d70d16ba.jpg)
![gpu_utilization_memory_usage_thread_4_RN18](https://user-images.githubusercontent.com/41190076/234152187-81836d90-8b07-4385-810f-678c878020f4.jpg)
![gpu_utilization_memory_usage_thread_8_RN18](https://user-images.githubusercontent.com/41190076/234152196-cb81e364-8ea9-437c-85b5-5bc61d7684f2.jpg)
![gpu_utilization_memory_usage_thread_16_RN18](https://user-images.githubusercontent.com/41190076/234152203-f765bfc0-560c-438c-aaed-f4b96307ef46.jpg)

It seems that the GPU utilization is saturated by adding more threads on DALI which seems quite a normal symptom.

Thanks for others tagging for consideration, but I think It would be better to close this issue.
