### ISSUE TITLE
pipeline.

### ISSUE THREAD

**Issue by prefer-potato** [NVIDIA/DALI#4789]
can i implement my our Operater in pipeline? How to convert a cpu datanode to a gpu datanode without any other operation like decoder?

**Comment by JanuszL** [comment]
Hi @prefer-potato,

You can check [this section of DALI documentation](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/custom_operations/index.html) that describes possible ways of extending DALI.
> How to convert a cpu datanode to a gpu datanode without any other operation like decoder?

Please just:
```
data_on_gpu = data_on_cpu.gpu()
```

**Comment by prefer-potato** [comment]
oh, thank you!!!very much..
