### ISSUE TITLE
DALI resize operator, putting in inputs of `fn.shapes(img)`

### ISSUE THREAD

**Issue by dyhan316** [NVIDIA/DALI#4791]
I am trying to resize my image (that I cropped) into the original image dimension (I know there's a `fn` that lets me do crop and resize at once, but it seemed that that only worked for 2D images (not 3D volumetric data))

The code I made is something like this : 
```
def define_graph(self):
        img, img_cpu = self.load_data() #move to GPU
        org_shape = fn.shapes(img_cpu) #(get shape from the cpu data node not the gpu one)
        img = self.crop_fn(img, org_shape, crop_size = self.patch_size, type = "random", resize = True) 
       ... 
```

inside of the `self.crop_fn` function, I am trying to input the org_shape into the `fn.resize` operator, by doing something like `img_cropped_resized = fn.resize(img_cropped, size = org_shape)` 

However, it seems that this raises an error. (whereas if I had just used `size = [256,256,256]`, it works)

Is there a way to remedy this?  Thank you in advance for anyone's help!

**Comment by JanuszL** [comment]
Hi @dyhan316,

Thank you for reaching out. Can you provide the full code of the `crop_fn` function?
Something like this should work for you:
```
    shape = fn.shapes(img)
    res_img= fn.resize(img, roi_start=[0, 0, 0], roi_end=self.patch_size, size=fn.cast(shape, dtype=types.FLOAT)[0:3])
```
You need to adjust roi_start depending on where you want to place the ROI (corner or center of the volume).

**Comment by dyhan316** [comment]
@JanuszL  Thank you for your response! 

The code is below : 
```
    
    def crop_fn(self,img, org_shape, crop_size, type = 'random', resize = False):
        """
        * img : original image
        * org_shape : original shape (cpu shape data node)(gpu면 안됨, gpu node끼리는 못주기에)
        * crop_size : size of the crop (single float value b/w 0~1) (dim 마다 다르게 하는 거는 몰라서 적용안함)
        * type : 
            * "random" : random start point 
            * "center" : not implemented (안쓰임)
        * resize : resize여부 resize시켜서 original img와 같은 dim을 가지게 하는가?        
        """
        #need to add zoom later
        patch_dim = crop_size*org_shape #0.75면 shape자체가 0.75배씩됨 #float임! (그래도 되더라)
        if type == "center" : 
            raise NotImplementedError("center not implemented yet")
        elif type == "random" : 
            kwargs = {
                "crop_pos_x" : fn.random.uniform(range = [0.0, 1.0]),
                "crop_pos_y" : fn.random.uniform(range = [0.0, 1.0]),
                "crop_pos_z" : fn.random.uniform(range = [0.0, 1.0]),
            } #random값이 0~1이어도 되는 것이, 1예가 알아서 해주는 듯 
        else : #default (not used)
            kwargs = {}
            
        img_cropped = fn.crop(img, crop = patch_dim, **kwargs)
        
        if resize : 
            raise NotImplementedError("Not done yet, fix the resizing thing after getting response from NVIDIA GitHub person!")
            img_cropped_resized = fn.resize(img_cropped, size = fn.shapes(img))#org_shape)
            return img_cropped_resized#random_augmentation(0.5, img_cropped_resized, img)
        else : 
            return img_cropped
            
```

Thank you! I'll try your suggestion!

**Comment by dyhan316** [comment]
After changing the line to `img_cropped_resized = fn.resize(img_cropped, size = fn.cast(org_shape, dtype = types.FLOAT)[0:3])#org_shape)`, it worked! 

I have a question : why did `fn.cast` solve the job? What does changing the type to FLAOT do? also, why is the size float, when it seems that it should be an integer? (since the shape of the tensor would be a list of integers?)

Also, is there a way to read the results of things like ` fn.shapes(img_cpu)`? Or can it only be read once it is outside of the pipe? (Sorry for a lot of questions!)

**Comment by dyhan316** [comment]
Thank you for your clear and concise answer! :)
