### ISSUE TITLE
`labels` option in `readers.numpy`

### ISSUE THREAD

**Issue by dyhan316** [NVIDIA/DALI#4799]
### Describe the question.

Hello, I want to load `.npy` data while providing labels as a list. 

It seems that `fn.readers.file` has the `labels` argument which allows me to provide a list of labels. 

However, this feature does not exist in `fn.readers.numpy`. Is there another way I can  provide the labels externally? 

Thank you in advance for anyone's response!

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by klecki** [comment]
Hi @dyhan316 
indeed, there is no such option at the moment.
I can suggest two workarounds:
* use the [fn.get_property](https://docs.nvidia.com/deeplearning/dali/main-user-guide/docs/operations/nvidia.dali.fn.get_property.html#nvidia.dali.fn.get_property) to obtain source info - and work out the label outside of the DALI pipeline based on mapping from the file names
* Create a matching set of numpy files that contain the labels and use another fn.readers.numpy to access them. If you pass the same `seed` parameter to both of the readers, they will be shuffled in the same way.

We are aware of this limitation and are thinking on introducing some more generic solution.

**Comment by dyhan316** [comment]
@klecki  Thank you for your response! 

I have tried to fn.get_property to obtain the source info, but it doesn't retrieve the file names! 

(example code below : )

```python 
##trying to just do regular stuff
from nvidia.dali.pipeline import Pipeline
from nvidia.dali import pipeline_def
import nvidia.dali.fn as fn
import nvidia.dali.types as types

data_path = "/hpcgpfs01/scratch/dyhan316/testing_4_dali"

@pipeline_def
def simple_pipeline():
    img = fn.readers.numpy(file_root = data_path)
    #img = fn.reshape(img, layout = "DHW") #CDHW 하면 애러뜸!
    return img , fn.get_property(img, key = "source_info")
```

```python
pipe = simple_pipeline(batch_size = 16, num_threads = 1, device_id = 0, seed = 42)
pipe.build()

simple_images, prop= pipe.run()
```

```python
prop
======(results)====
TensorListCPU(
    [],
    dtype=DALIDataType.UINT8,
    num_samples=16,
    shape=[(0,), 
           (0,), 
           (0,), 
           (0,), 
           (0,), 
           (0,), 
           (0,), 
           (0,), 
           (0,), 
           (0,), 
           (0,), 
           (0,), 
           (0,), 
           (0,), 
           (0,), 
           (0,)])

```

**Comment by dyhan316** [comment]
I believe that I can get help from : `[here](https://github.com/NVIDIA/DALI/issues/4713) `, so will close this issue. I hope the `labels` get implemented soon! :) Thank you for the amazing package!
