### ISSUE TITLE
dali-0.7dev meet segment fault with tensorflow1.8.

### ISSUE THREAD

**Issue by owenustc** [NVIDIA/DALI#480]
Hi, I compile the new version of dali library from github. But I have meed a segment fault with tensorflow plugin.  And another way is right without tensorflow plugin.  The information of dali and tensorflow as follow:
Python 3.6.3 |Anaconda, Inc.| (default, Oct 13 2017, 12:02:49)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
/opt/conda/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
>>> print (tensorflow.__version__)
1.8.0
>>> import nvidia.dali
>>> print (nvidia.dali._version_)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'nvidia.dali' has no attribute '_version_'
>>> print (nvidia.dali.__version__)
0.7.0.dev0
>>>
 And my code is as follow 
import cv2
import types
import collections
import numpy as np
from random import shuffle
from nvidia.dali.pipeline import Pipeline
import nvidia.dali.ops as ops
import nvidia.dali.types as types
import time
import os
import fnmatch
import tensorflow as tf
import nvidia.dali.plugin.tf as dali_tf
import time
BATCH_SIZE = 1
TRIAL = 50

class GPUPipeline(Pipeline):
    def __init__(self, batch_size, num_threads, device_id=0, data_dir='./data/',mask_dir='./data_mask/'):
        super(GPUPipeline, self).__init__(batch_size, num_threads, device_id, seed = 12)
        self.input1 = ops.FileReader(file_root = data_dir, random_shuffle = False, file_list= data_dir  +  '/file_list.txt')
        self.input2 = ops.FileReader(file_root = mask_dir, random_shuffle = False, file_list= mask_dir  +  '/file_list.txt')
        self.decode = ops.HostDecoder(output_type = types.RGB)
        self.rotate = ops.Rotate(device="gpu", angle=45, interp_type = types.INTERP_LINEAR)

    def define_graph(self):
        images, label =self.input1()
        masks, _ = self.input2()
        images = self.decode(images)
        masks = self.decode(masks)
        aug_images = images.gpu()
        aug_masks = masks.gpu()
        #aug_images, aug_masks = self.rotate([aug_images,aug_masks])
        aug_images = self.rotate(aug_images)
        return aug_images,aug_masks,label.gpu()

def test_pipe():
   pipe = GPUPipeline(BATCH_SIZE,1, 3, data_dir='./data/',mask_dir='./data_mask/')
   pipe.build()
   pipe_out = pipe.run()
   image, mask,label = pipe_out
   print (image.asCPU().at(0).shape, mask.asCPU().at(0).shape, label.asCPU().at(0).shape)
   cv2.imwrite("./img.png", image.asCPU().at(0).astype("uint8"))
   cv2.imwrite("./mask.png", mask.asCPU().at(0).astype("uint8"))

def test_error():
   daliop = dali_tf.DALIIterator()
   pipe = GPUPipeline(BATCH_SIZE,1, 0, data_dir='./data/',mask_dir='./data_mask/')
   image,mask = daliop(pipe,
            shapes = [(BATCH_SIZE, 322,431, 3),(BATCH_SIZE, 322,431, 3)],
            dtypes =(tf.float32,tf.float32),device_id=0)

   config = tf.ConfigProto(log_device_placement=True)
   config.gpu_options.allow_growth = True
   config.gpu_options.visible_device_list = "7"
   data=[]
   masks = []
   with tf.Session(config=config) as sess:
        res = sess.run([image, mask])
        data=res
   print (data[0].shape,data[1].shape)
   if data[0].size>0:
       cv2.imwrite("./img.png", data[0][0].astype("uint8"))
       cv2.imwrite("./mask.png", data[1][0].astype("uint8"))

#test_pipe()
test_error()

**Comment by JanuszL** [comment]
Hi,
Regarding TensorFlow related crash - it is hard to tell what is the reason without log, error message and precise env you have. As I said, we recommend using dockerized build to avoid this kind of problems.
In your script you return:
```
aug_images,aug_masks,label.gpu()
```
While `daliop` consumes only two, please remove `label` from the pipeline output.
Also make sure that every image in the pipeline output is `322,431, 3`, you can use `CropMirrorNormalize` for that.
