### ISSUE TITLE
releasing a paper/package soon -- blogpost?

### ISSUE THREAD

**Issue by danbider** [NVIDIA/DALI#4804]
### Describe the question.

hi @JanuszL,

We are releasing our [lightning-pose package ](https://github.com/danbider/lightning-pose) next week, and it uses DALI heavily. Thought about writing a blog post with you. 

If you're interested in that sort of a thing, reach out to me, [db3236@cumc.columbia.edu](mailto:db3236@cumc.columbia.edu)

https://dan-biderman.netlify.app/

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @danbider,

Let me discuss this directly via email.
