### ISSUE TITLE
Does DALI affect computation on training?

### ISSUE THREAD

**Issue by Esthesia** [NVIDIA/DALI#4806]
### Describe the question.

Dear all,

Always thank you for answering questions.

I experimented with DALI on training ResNet-18 with a 500 batch size.
My assumption is that if DALI's num_threads factor is increasing, it may affect training
like interference on computation or memory.

However, the experiment result seems that `Waiting time` is dramatically decreasing, which means
no prep-stall on the data loading side but `Train time` is unaffected.

**Does DALI have no effect on training with respect to interference, such as training time stretching?**

<html xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=PowerPoint.Slide>
<meta name=Generator content="Microsoft PowerPoint 15">

</head>

<body>

  | Waiting time | Train time | Iteration time
-- | -- | -- | --
PyTorch   baseline | 2.713   ± 4.199 | 0.266 ± 0.119 | 2.978   ± 4.217
DALI   baseline     (num_threads =   1) | 1.453   ± 0.055 | 0.257 ± 0.001 | 1.710 ± 0.055
DALI   baseline     (num_threads =   2) | 0.645 ± 0.031 | 0.259 ± 0.001 | 0.903 ± 0.031
DALI   baseline     (num_threads =   4) | 0.236   ± 0.015 | 0.263   ± 0.001 | 0.499   ± 0.016
DALI   baseline     (num_threads =   8) | 0.092   ± 0.017 | 0.266   ± 0.001 | 0.357   ± 0.017

</body>

</html>

Thank you

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @Esthesia,

Thank you for reaching out.
I'm glad to see you experimenting with different configurations on DALI.
> Does DALI have no effect on training with respect to interference, such as training time stretching?

What I can tell is that depends. It depends on the network architecture and kernels that are selected for each layer if CUDA graphs are used. If the GPU occupation is high DALI would compete for the resources with the training part, if there are gaps in the GPU occupation DALI should be able to use them and achieve a high level of overlap.

**Comment by Esthesia** [comment]
Hello @JanuszL,

Thank you for the answer.

An additional question for the DALI is that 
if the prefetch queue is 2 and DALI runs more than 1 thread (which is num_threads option is larger than 2),
when the result queue is full and waiting for training, DALI's running thread is waiting for the training process consuming batch from the prefetch queue.

I ask because when I run DALI for data loading without training, it becomes much more GPU intensive as I increase the num_threads option. The below table shows memory consumption after running 1 epoch. (`worker` means `num_threads` options) I assume this is due to the fact that without training, the data loaded into the prefetch queue is immediately flushed.
I want to know that my assumption is correct.

<html>
<body>


Memory Usage  (w/o training) | ResNet-18 (batch size 500) | ResNet-50 (batch size 240) | ViT-Base (batch size 88)
-- | -- | -- | --
Worker 1 | 5950 | 3707 | 2145
Worker 2 | 5991 | 3843 | 2247
Worker 4 | 6502 | 4297 | 2713
Worker 8 | 7142 | 5111 | 3406
Worker 16 | 8486 | 6242 | 4814


</body>
</html>

<html>
<body>


Memory Usage  (Only dataloading) | ResNet-18 (batch size 500) | ResNet-50 (batch size 240) | ViT-Base (batch size 88)
-- | -- | -- | --
Worker 1 | 8586 | 5455 | 3736
Worker 2 | 8883 | 5677 | 4109
Worker 4 | 9313 | 6009 | 4443
Worker 8 | 9907 | 6995 | 5228
Worker 16 | 11079 | 8089 | 6246


</body>
</html>

**Comment by Esthesia** [comment]
Thanks for clarifications @JanuszL 

I measured with the other process using `nvidia-smi` query.
I don't think the existence of training does affect DALI.
For better understanding,
this code is a snippet of code with training. 

```
   ...
    # switch to train mode
    model.cuda()
    model.train()
    
    for i, data in enumerate(train_loader):

        input = data[0]["data"]
        target = data[0]["label"]
        target = torch.squeeze(target.long())
        
        output = model(input)
        
        ...
```

Without training snippet, 

```
   ...
    # switch to train mode
    # model.cuda()
    # model.train()
    
    for i, data in enumerate(train_loader):
        
        ...
```

If you need any further information, I will share.

**Comment by Esthesia** [comment]
Yes, I assumed that PyTorch has its own memory manager and it pre-allocates GPU memory based on batch size and model.
So, I calculated the consumed GPU memory size without DALI.

- GPU memory usage
    - ResNet-18 (b500) - 9737 MB
    - ResNet-50 (b240) - 12839 MB
    - ViT-Base (b88) - 17069 MB

<html>
<body>


Memory Usage | ResNet-18 | ResNet-50 | ViT-Base
-- | -- | -- | --
Worker 1 | 15687 | 16546 | 19214
Worker 2 | 15728 | 16682 | 19316
Worker 4 | 16239 | 17136 | 19782
Worker 8 | 16879 | 17950 | 20475
Worker 16 | 18223 | 19081 | 21883


</body>
</html>

This is memory consumption at the end of the epoch (with training), and I subtracted.

**Comment by JanuszL** [comment]
DALI also uses it a bit (to create tensors from the iterator) so it may affect the consumption.

**Comment by Esthesia** [comment]
That also needs to be considered. I think I need to recalibrate the model size to compare more concretely.
Thanks for the answer.

BTW, is it better to close and reopen if there is something weird or just leave this open until I checked it?

**Comment by Esthesia** [comment]
I think I can get some answers to this question from my other questions, so it is better to close.
