### ISSUE TITLE
nvidia.dali.fn.warp_affine output all zeros tensor

### ISSUE THREAD

**Issue by DequanZhu** [NVIDIA/DALI#4809]
### Describe the question.

I want to use  nvidia.dali.fn.warp_affine api to get roi from image, the origin image is like below:
![微信图片_20230426153550](https://user-images.githubusercontent.com/26426479/234503411-1b91a5e1-c8e8-4274-a744-6b75865e6366.jpg)
 here is my dali code which is in debug mode:
```

import numpy as np
import nvidia.dali as dali
import nvidia.dali.types as types
from nvidia.dali.pipeline.experimental import pipeline_def
import cv2

warp_m = np.asarray([[1.39490, 0.33963, -610.32982], [-0.33963, 1.39490, -12.91000]])
image = cv2.imread("/tmp/test.jpg")

def transform():
    return warp_m.astype(np.float32)

def external_image():
    return image

@pipeline_def(batch_size=1, num_threads=1, device_id=0)
def simple_pipeline():
    image = dali.fn.external_source(
        batch=False, source=external_image, dtype=dali.types.FLOAT
    )
    warp_m = dali.fn.external_source(
        batch=False, source=transform, dtype=dali.types.FLOAT
    )
    align_face = dali.fn.warp_affine(
        image, warp_m, size=(112, 112), fill_value=0,
        inverse_map=True
    )
    return align_face

pipe = simple_pipeline(debug=True)
pipe.build()
pipe_out = pipe.run()
cv2.imwrite("/tmp/ou2.jpg",pipe_out[0].at(0))
```
the output is all zeros tensor like below:
![微信图片_20230426152022](https://user-images.githubusercontent.com/26426479/234499803-deb95c1e-3b43-489e-bd55-f95e26b9df75.jpg)

but use same warpaffine matrix, the opencv warpAffine api get the some looks much more normal output image like below:
![微信图片_20230426153256](https://user-images.githubusercontent.com/26426479/234502753-dfc45c61-92f6-4973-a74c-358f8ca52d66.jpg)

here is the opencv method:
```
import cv2
warp_m = np.asarray([[1.39490, 0.33963, -610.32982], [-0.33963, 1.39490, -12.91000]])
image = cv2.imread("/tmp/test.jpg")
out = cv2.warpAffine(image, warp_m, (112, 112), borderValue=0.0)
```
My tritonserver is 22.12,and dali version is nvidia-dali-cuda110=1.24.0 use pip by myself in container, anyone know  why this?

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by mzient** [comment]
Hello @DequanZhu 
Your code is _almost_ correct - all you have to do is to set `inverse_map=False`.
We've adopted this parameter (along with the name and semantics) from OpenCV. Frankly, this name is a bit confusing, because it's actually the inverse mapping that's used by internally by the warping operator. That's why default to `inverse_map=True`, because then the matrix can be used as-is.

**Comment by DequanZhu** [comment]
@mzient, thanks a lot, by setting inverse_map=False, the output is normal,I will close this issue
