### ISSUE TITLE
Dali brings error augmentation result with tensorflow plugin.

### ISSUE THREAD

**Issue by owenustc** [NVIDIA/DALI#481]
I used the new dali and tensorflow 1.8 to do image rotation. But I found the result of dali with tensorflow plugin is error.   My test code is as follow:

import cv2
import types
import collections
import numpy as np
from random import shuffle
from nvidia.dali.pipeline import Pipeline
import nvidia.dali.ops as ops
import nvidia.dali.types as types
import time
import os
import fnmatch
import tensorflow as tf
import nvidia.dali.plugin.tf as dali_tf
import time

BATCH_SIZE = 1
TRIAL = 50

class GPUPipeline(Pipeline):
    def __init__(self, batch_size, num_threads, device_id=0, data_dir='./data/',mask_dir='./data_mask/'):
        super(GPUPipeline, self).__init__(batch_size, num_threads, device_id, seed = 12)
        self.input1 = ops.FileReader(file_root = data_dir, random_shuffle = False, file_list= data_dir  +  '/file_list.txt')
        self.decode = ops.HostDecoder(output_type = types.RGB)
        self.rotate = ops.Rotate(device="gpu", angle=45, interp_type = types.INTERP_LINEAR)

    def define_graph(self):
        images, label =self.input1()
        images = self.decode(images)
        aug_images = images.gpu()
        aug_images = self.rotate(aug_images)
        return aug_images,label.gpu()

def test_pipe():
   pipe = GPUPipeline(BATCH_SIZE,1, 3, data_dir='./data/',mask_dir='./data_mask/')
   pipe.build()
   pipe_out = pipe.run()
   image, label = pipe_out
   print (image.asCPU().at(0).shape, label.asCPU().at(0).shape)
   cv2.imwrite("./img_pipe.png", image.asCPU().at(0).astype("uint8"))

def test_error():
   daliop = dali_tf.DALIIterator()
   pipe = GPUPipeline(BATCH_SIZE,1, 0, data_dir='./data/',mask_dir='./data_mask/')
   image,mask = daliop(pipe,
            shapes = [(BATCH_SIZE, 322,431, 3),()],
            dtypes =(tf.float32,tf.int32),device_id=0)

   config = tf.ConfigProto(log_device_placement=True)
   config.gpu_options.allow_growth = True
   config.gpu_options.visible_device_list = "7"
   data=[]
   masks = []
   with tf.Session(config=config) as sess:
        res = sess.run([image, mask])
        data=res
   print (data[0].shape,data[1].shape)
   if data[0].size>0:
       cv2.imwrite("./img_tf.png", data[0][0].astype("uint8"))

test_pipe()
test_error()

![img_pipe](https://user-images.githubusercontent.com/5858028/51838357-ff52b400-2340-11e9-8899-18549c1ff23b.png)
Fig 1 right result of test_pipe.
![img_tf](https://user-images.githubusercontent.com/5858028/51838381-14c7de00-2341-11e9-8f2a-e3a48f915b90.png)
Fig2 error result of test_error

And the information of dali and tensorflow in my system is as follow:
Python 3.6.3 |Anaconda, Inc.| (default, Oct 13 2017, 12:02:49)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nvidia.dali
>>> print (nvidia.dali.__version__)
0.7.0.dev0
>>> import tensorflow
/opt/conda/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
>>> print (tensorflow.__version__)
1.8.0
>>>

**Comment by JanuszL** [comment]
In `daliop` make sure to provide proper type of data. Those types should reflect what you return form the pipeline, if you are not doing any casting then it is uint8, if you want to change it please add casting operator to the pipeline.

**Comment by JanuszL** [comment]
daliop wraps around your pipeline. If you specify `tf.float32` then your data is reinterpreted as `tf.float32`, so instead of `uint8`, you got 4 values of `uint8` interpreted as a `tf.float32`. This happens here https://github.com/NVIDIA/DALI/blob/master/dali/tensorflow/daliop.cc#L185.
