### ISSUE TITLE
Input for video preprocessing pipeline (fn.readers.video)

### ISSUE THREAD

**Issue by Voveka98** [NVIDIA/DALI#4812]
### Describe the question.

Hi, i want to build a preprocessing pipeline for video. I want to use Triton Inference Server for extraction frames from video for further model inference. I want to transfer video encoded as bytes.
I want to build something like that:

```
### Here defining constantas (IMAGE_SIZE, MEAN, STD)
@pipeline_def(batch_size=32, num_threads=4)
def TritonLoadingPipeline():
    video_files = fn.external_source(name="DALI_INPUT_0")  # here i assume input as bytes
    frames = fn.readers.video(
        video_files
        device="gpu",
        filenames=filenames,  # its in docs, but seems like it has to be string or list of strings
        sequence_length=sequence_length,
        random_shuffle=False,
        initial_fill=initial_prefetch_size)
    )
    resized_frames = fn.resize(
        frames,
        resize_longer=max(IMAGE_SIZE),
        dtype=types.FLOAT,
        device="gpu"
    )
    normalized_frames = fn.normalize(
        resized_frames,
        mean=MEAN / SCALE,
        stddev=STD,
        scale=SCALE,
        dtype=types.FLOAT,
        device="gpu",
    )
    return normalized_frames
```
The problem that i see is that fn.readers.video takes input as 
```
filenames (str or list of str, optional, default = []) –
File names of the video files to load.
This option is mutually exclusive with file_list and file_root.
```

Is it possible to get not filenames but bytes?
Tried to find examples in docs and open issues but it was unsuccessful
Thanks in advance!

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @Voveka98,

Thank you for reaching out.
You can try [this DALI TRITON backend example](https://github.com/triton-inference-server/dali_backend/tree/main/docs/examples/video_decoding) that shows how to feed the video and decode them. You can also consider [this one as well](https://github.com/triton-inference-server/dali_backend/tree/main/docs/examples/video_decode_remap) where you don't decode the whole video in one go (as in the previous one) but in `sequence_lenght` chunks.

**Comment by Voveka98** [comment]
I will take a look! Thanks for help :)

**Comment by Voveka98** [comment]
Hi again! Your examples were useful and it works nice. But i faced problem that i have to use legacy version of nvidia.dali (`nvidia.dali.__version__ = 1.12`)
is it possible to find something like `experimental.decoders.video` in old version? 
Upgrading triton inference server is unavailable and maybe there is a solution for specific old version
Thanks in advance again!

**Comment by JanuszL** [comment]
Hi @Voveka98,

I'm afraid that 1.12 is quite old and there have been plenty of fixes and improvements since then. I don't think there is any similar functionality in that version. So please upgrade if/when possible.

**Comment by bpleshakov** [comment]
@Voveka98 if you need to use older version of dali, you can decode video on client side and send to triton a tensor.
