### ISSUE TITLE
trivial_augment_wide randomly creates full black images or values with weird artifacts 

### ISSUE THREAD

**Issue by machineko** [NVIDIA/DALI#4813]
### Version

1.25 + cu 11.7 and rtx 3090

### Describe the bug.

Example "weird" images
![media_images_train_dunno out, noise, y_50_37d26bd048c8f0d37fc1](https://user-images.githubusercontent.com/42299606/234860119-a20ffd01-0aa1-4af3-a273-909204aeb83a.png)
![media_images_train_dunno out, noise, y_7584_2dae9f48c223858ac5db](https://user-images.githubusercontent.com/42299606/234861170-1c70ce36-de22-4964-83d0-f095108fc740.png)

Example "proper" looking images
![media_images_train_dunno out, noise, y_215_434dd91c77e9401e8fae](https://user-images.githubusercontent.com/42299606/234860899-7165cdf5-6701-44d7-adc0-1c7f49257052.png)
![media_images_train_dunno out, noise, y_17813_ef7872bf50c184ce1d26](https://user-images.githubusercontent.com/42299606/234860924-27757028-3b45-4766-8cc0-03e99adedc54.png)
![media_images_train_dunno out, noise, y_13015_2a9fa79a66d3c13ca97a](https://user-images.githubusercontent.com/42299606/234861015-bd30280a-e942-46f1-9263-41c7e4e2850e.png)

### Minimum reproducible example

```python
@pipeline_def(enable_conditionals=True)
      def video_pipe(
          filenames,
          shard_id: int,
          num_shards: int,
          sequence_length: int,
          reader_name: str = "Reader",
      ):

          videos = fn.readers.video(
              device="gpu",
              filenames=filenames,
              sequence_length=sequence_length, # 8-32
              shard_id=shard_id,
              num_shards=num_shards,
              random_shuffle=True,
              initial_fill=1024 * 200,
              name=reader_name,
              # dtype=DALIDataType.FLOAT,
          )

          # inp
          inp = fn.crop(videos, crop=(224, 224), device="gpu")

          augmented_images = trivial_augment.trivial_augment_wide(
              inp, shape=(224, 224)
          )

          return augmented_images
```

### Other/Misc.

This is fully random im not logging corresponding original video at the moment but dataset have no area that are fully black 224x224 boxes and it doesn't happen using combination of random augments (brightness, saturation etc.) before.

Values are divided by 255. and clamped to 0,1 range before processing them as photos using Pillow and logged.

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @machineko,

Thank you for reporting the problem.
Do you obtain similar results without the augmentations (just decoding)? Can you check using the https://github.com/NVIDIA/DALI_extra/tree/main/db/video data (so we know that we are trying to reproduce using the same conditions)?

**Comment by stiepan** [comment]
Hi @machineko,

Thanks for taking interest in DALI and the automatic augmentations. 

Currently, the out-of-the-box support is limited to `images of HWC layout, uint8 type.` as stated in the docs.
However, as long as the expected outcome of applying the trivial augment to video is applying a random augmentation to each frame separately (with single random magnitude shared by all frames in given sequence), the only limitation are two augmentations from the predifined set: contrast and auto_contrast.

The `contrast` is a culprit behind the entierly black frame and the `auto_contrast` causes the unexpected artifact in the next to last image you posted.

So, what you can do is to run `apply_trivial_augment` with custom set of augmentations instead of the `trivial_augment_wide` which uses a predefined one. The only difference between predefined one and the custom set will be replacing the `contrast` and `auto_contrast` with the counterparts that are aware of frames dimension.

First, let's define the two video-aware counterparts:

```
from nvidia.dali.auto_aug import augmentations as a
from nvidia.dali.auto_aug.core import augmentation

@augmentation(mag_range=(0.01, 0.99), randomly_negate=True, mag_to_param=a.shift_enhance_range)
def contrast(data, parameter):
    """
    It follows PIL implementation of Contrast enhancement which uses a channel-weighted
    mean as a contrast center.
    """
    # assumes FHWC layout
    mean = fn.reductions.mean(data, axes=[1, 2])  # FC
    rgb_weights = types.Constant(np.array(
        [[0.299, 0.587, 0.114]],
        dtype=np.float32))  # FC
    center = fn.reductions.sum(mean * rgb_weights, axes=[-1])  # F
    center = fn.expand_dims(center, axes=[1, 2, 3])  # FHWC
    return fn.cast_like(center + (data - center) * parameter, data)

@augmentation
def auto_contrast(data, _):
    # assumes FHWC layout
    lo = fn.reductions.min(data, axes=[1, 2])  # FC
    hi = fn.reductions.max(data, axes=[1, 2])  # FC
    diff = hi - lo  # FC
    mask_scale = diff > 0  # FC
    mask_id = mask_scale ^ True  # FC
    # choose div so that scale ends up being 255 / diff if diff > 0 and 1 otherwise
    div_by = diff * mask_scale + types.Constant(255, dtype=types.UINT8) * mask_id  # FC
    scale = fn.expand_dims(255 / div_by, axes=[1, 2])  # FHWC
    shift = fn.expand_dims(lo * mask_scale, axes=[1, 2])
    scaled = (data - shift) * scale
    return fn.cast_like(scaled, data)
```

Then we re-define the trivial augment set of augmentations by replacing the `(auto_)contrast`.

```
from nvidia.dali.auto_aug.core._utils import get_translations as _get_translations


def get_trivial_augment_wide_suite_video(max_translate_rel=1.):
    translations = _get_translations(use_shape=True, max_translate_rel=max_translate_rel)
    return translations + [
        a.shear_x.augmentation((0, 0.99), True),
        a.shear_y.augmentation((0, 0.99), True),
        a.rotate.augmentation((0, 135), True),
        a.brightness.augmentation((0.01, 0.99), True, a.shift_enhance_range),
#         a.contrast.augmentation((0.01, 0.99), True, a.shift_enhance_range),
        contrast,
        a.color.augmentation((0.01, 0.99), True, a.shift_enhance_range),
        a.sharpness.augmentation((0.01, 0.99), True, a.sharpness_kernel),
        a.posterize.augmentation((8, 2), False, a.poster_mask_uint8),
        a.solarize.augmentation((256, 0)),
        a.equalize,
#         a.auto_contrast,
        auto_contrast,
        a.identity,
    ]
```

and finally we can use it in the pipeline by replacing the

```
augmented_images = trivial_augment.trivial_augment_wide(
              inp, shape=(224, 224)
          )
```

with

```
augmentations = get_trivial_augment_wide_suite_video()
augmented_images = ta.apply_trivial_augment(
  augmentations, inp, shape=(224, 224)
)
```

**Comment by machineko** [comment]
Hey guys thanks for fast reply.
I started new training session and results looks fine atm, if something change I'll just reopen this but otherwise have a great day 😄

**Comment by machineko** [comment]
Ok so indeed there is no more fully black images but there are still saturation/brightness artifacts even with @stiepan update but they are indeed very rare in this version 😄 
![media_images_train_dunno out, noise, y_8587_96670615ab0c444fffe3](https://user-images.githubusercontent.com/42299606/235101348-91d0f3df-956a-4721-a280-76dacdef641e.png)

**Comment by machineko** [comment]
Sure it's not a problem for my model atm. 
As even fully black frames were not creating much burden on training process and if it's indeed expected output of solarize we can close this issue 😄

**Comment by stiepan** [comment]
Hi @machineko,

The augmentations are ajusted in https://github.com/NVIDIA/DALI/pull/5012 to handle video out-of-the-box. The TrivialAugment (as well as RA and AA) in the next release should handle videos just fine without the need for custom policy.
