### ISSUE TITLE
Question about installation on DALI with dockerfile

### ISSUE THREAD

**Issue by Esthesia** [NVIDIA/DALI#4814]
### Describe the question.

I am struggling with installation via the dockerfile in DALI.
Since DALI v.1.24.0 needs a minimum Cmake 3.18 version or higher is required. 
But the docker image contains 3.13.5, how to fix this?

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @Esthesia,

Can you elaborate on what particular steps you are taking? Are you referring to [this](https://github.com/NVIDIA/DALI/blob/main/docker/Dockerfile.deps) docker file where we build CMake from sources, or you want to install DALI wheel inside docker but in this case CMake is not required.

**Comment by Esthesia** [comment]
Hello @JanuszL,

What I try to do is the later one with `./build.sh` command in the `docker` directory to set out wheel.

This is my command to install the DALI.
` sudo CUDA_VERSION=11.1 PYVER=3.8 CMAKE_BUILD_TYPE=Debug ./build.sh
`
But the output is 
```
CMake Error at CMakeLists.txt:18 (cmake_minimum_required):
  CMake 3.18 or higher is required.  You are running version 3.13.5
```

Thank you.

**Comment by JanuszL** [comment]
CUDA 11.1 version is no longer supported (and the compilation may fail). Please build with 11.8 and thanks to the [CUDA minor version compatibility](https://docs.nvidia.com/deploy/cuda-compatibility/index.html#minor-version-compatibility) you can use it with CUDA 11.0 capable driver.
Can you try (to make sure that you have the latest docker image with all deps)?:
```
sudo  REBUILD_BUILDERS=YES CUDA_VERSION=11.8 PYVER=3.8 CMAKE_BUILD_TYPE=Debug ./build.sh
```
(`PYVER` is mostly to set the python used in the build env, but the wheel should support 3.6-3.11).

**Comment by Esthesia** [comment]
@JanuszL Thanks for the notification. Is CUDA 11.4 also not supported?

**Comment by Esthesia** [comment]
@JanuszL Not a specific reason for deciding on that version, Just out of curiosity about CUDA version 11. I think I need to version up. Thanks for answering.

**Comment by JanuszL** [comment]
> I think I need to version up.

It is mostly about the build env, but the driver can remain the same as you have for CUDA 11.1. Also, DALI is based on CUDA 11.x links dependent CUDA libraries directly so it may work with any CUDA in your system as long as the driver is at least 11.0 capable.
