### ISSUE TITLE
Does prefetch_queue_depth in numpy reader use CPU buffers or GPU buffers?

### ISSUE THREAD

**Issue by srikanthmalla** [NVIDIA/DALI#4816]
### Describe the question.

Hi,
I am trying GDS numpy reader example from: https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/numpy_reader.html

The task is to load arrays from SSD to GPU using GDS.

When I increase prefetch_queue_depth the speed increases, but does it use CPUbuffer/RAM? If so, is GDS still valid with this prefetch_queue_depth option? Please let me know.

Thank you,
Srikanth

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @srikanthmalla,

Thank you for reaching out.
It is possible that increasing the `prefetch_queue_depth` average the difference in the loading speed of each batch. To make sure that is the case I would capture an [NSight system profile](https://developer.nvidia.com/nsight-systems) and see how the flow looks like under the hood over time.

**Comment by srikanthmalla** [comment]
Hi, Thanks for the quick reply, I will try to check with the Nsight System as well. Just to clarify, just adding prefetch_queue_depth to the example provided in the dali page (with proper setup and tested GDS), doesn't make it to use RAM for storing buffers right? Could you please clarify this part?
```
@pipeline_def(batch_size=batch_size, num_threads=3, device_id=0)
def pipe_gds():
    data = fn.readers.numpy(device='gpu', file_root=data_dir, files=files)
    return data
```
to
```
@pipeline_def(batch_size=batch_size, num_threads=3, device_id=0)
def pipe_gds():
    data = fn.readers.numpy(device='gpu', file_root=data_dir, files=files, prefetch_queue_depth=8)
    return data
```
Where will that prefetch queue be stored in the case of the second example? Or could you explain how the behavior changes in the above two cases?

Thank you so much!
Srikanth

**Comment by JanuszL** [comment]
> Where will that prefetch queue be stored in the case of the second example? Or could you explain how the behavior changes in the above two cases?

As this is a GPU operator this should be stored in the GPU memory. Please check the usage level of VRAM, it should increase.
