### ISSUE TITLE
CUDA IPC get invalid device context inside "include/dali/core/mm/async_pool.h"

### ISSUE THREAD

**Issue by mansur20478** [NVIDIA/DALI#4817]
### Describe the question.

Hi everyone,

I am trying to IPC Memory Sharing inside "include/dali/core/mm/async_pool.h".
Whenever I try to use:

> cudaIpcOpenMemHandle

I receive the following error:

> RuntimeError: CUDA runtime API error cudaErrorDeviceUninitialized (201):
> invalid device context

The cudaMemHandle_t that I am using is created inside DALI. 
Can you please give me guide on how to solve it?

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @mansur20478,

Thank you for reaching out.
That is an interesting idea to explore.
It seems that there could be many things that can go wrong:
- how do you pass the `handle`?
- are you sure that the CUDA context on the receiving side is initialized

If you can share the code you are experimenting with (even a simple sample that illustrates the flow and the problem) we can tell more. Although the DALI memory manager was never designed nor tested with such a use case in mind so there could be some limitations preventing such flow.

**Comment by mansur20478** [comment]
> Hi @mansur20478,
> 
> Thank you for reaching out. That is an interesting idea to explore. It seems that there could be many things that can go wrong:
> 
> * how do you pass the `handle`?
> * are you sure that the CUDA context on the receiving side is initialized
> 
> If you can share the code you are experimenting with (even a simple sample that illustrates the flow and the problem) we can tell more. Although the DALI memory manager was never designed nor tested with such a use case in mind so there could be some limitations preventing such flow.

Thank you for your response.

I am passing a cudaIpcMemHandle between two processes via "sys/shm.h".
This is the part of code that is relevant to cudaIpc. 
```
void *do_allocate_async(size_t bytes, size_t alignment, stream_view stream) override {
    /////////////////////

    CUDA_CALL(cudaIpcOpenMemHandle(&ptr, my_handle, cudaIpcMemLazyEnablePeerAccess));


    ////////////////////
 }
```
I tried to do cudaInit(), or forcefully change context, but it did not help at all. 
It should be initialized because for experiment purposes, when I did cudaMalloc() or cudaDeviceGetLimit() instead of cudaIpc, they worked fine.

In addition, could you please tell me how to build DALI so that it would do testing only after linking? Right now I just turned them off, but I defined some functions in my own header for "async_pool", and created .cc file with definitions inside "dali/core/mm"
``

**Comment by JanuszL** [comment]
> I am passing a cudaIpcMemHandle between two processes via "sys/shm.h".
> This is the part of code that is relevant to cudaIpc inside "async_pool.h".

As a basic test, you can check if this works fine outside of DALI, with a simple test app.

> In addition, could you please tell me how to build DALI so that it would do testing only after linking? Right now I just turned them off, but I defined some functions in my own header for "async_pool", and created .cc file with definitions inside "dali/core/mm". If I do not turn off tests, I would receive an error that my functions are not defined.
``

I'm not sure if I understand your question. If you want to rebuild DALI you can follow [these steps](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/compilation.html#using-docker-builder-recommended) and then reuse the build image `nvidia/dali:cu121_x86_64.build` with DALI dir mounted (`-v $(pwd):/opt/dali` inside) for rapids development.

**Comment by mzient** [comment]
Hello @mansur20478,
I don't quite understand what you're trying to achieve. Inserting anything inside `async_pool.h` is not a good idea - async_pool is an entity that implements stream-aware memory management. It works on top of some other memory resource (e.g. a `cuda_malloc_resource` or `cuda_vm_resource`). If you want to obtain your memory from another process, then you should implement a custom memory resource. If, on the contrary, you want to share memory allocated by DALI with another process, then you should use `cudaIpcGetMemHandle`, not `cudaIpcOpenMemHandle` - and, again, it's not a good idea to do it in `async_pool.h` - rather, you should implement an adapter resource. If that's the case, please note that the memory allocated with the default resource (`cuda_vm_resource`) is not IPC-shareable by default (and I don't know if it can be made shareable). You'd probably have to force the use of `cuda_malloc_resource` which is inefficient and prone to fragmentation.
