### ISSUE TITLE
Question about compilation with custom files

### ISSUE THREAD

**Issue by Esthesia** [NVIDIA/DALI#4819]
### Describe the question.

Dear all,

I tried to make a custom memory pool.
So I added a header file on `DALI/include/dali/core/mm/custom_resource.h`,
and define the functions on `DALI/dali/core/mm/custom_resource.cc`.

This custom resource is defined as an external in the header file 
`extern CustomPool custom_pool` and used on `DALI/include/dali/core/mm/malloc_resource.h`.

It is compiled with 
`sudo CUDA_VERSION=11.8 PYVER=3.8 BUILD_TEST=0 BUILD_BENCHMARK=0 ./build.sh`, but there is a problem with linking my custom file.

`ImportError: /home/anaconda3/envs/dev/lib/python3.8/site-packages/nvidia/dali/libdali_imgcodec.so: undefined symbol: _ZN4dali2mm12borrow_pool_E`

I think I have a little lack of knowledge on compilation methodology,
could you give me advice on how to make and link my custom files?
I only can find the compilation for custom operators in the documents.

Thank you

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @Esthesia,

By default, DALI symbols are not public. To export them from the binary and make them reusable across the modules then require the `DLL_PUBLIC` property. However, without a simple code sample that illustrates the exact conditions where you see the mentioned problem, it is hard to tell more.

**Comment by Esthesia** [comment]
Hello @JanuszL.

I agree with that. I will illustrate the brief code snippet of my problem.

`DALI/include/dali/core/mm/borrow_pool.h`

```
#ifndef DALI_CORE_MM_BORROW_POOL_H_
#define DALI_CORE_MM_BORROW_POOL_H_

namespace dali {
namespace mm {

class BorrowPool {
 public:
  explicit BorrowPool(int device_id);
....
 private:
 ...
extern BorrowPool borrow_pool_;

}  // namespace mm
}  // namespace dali
#endif  // DALI_CORE_MM_BORROW_POOL_H_
```

I made borrow_pool with `extern` to share with other memory_resources.

The source file of the above declaration is on
`DALI/dali/core/mm/borrow_pool.cc`

```
#include "dali/core/mm/borrow_pool.h"

namespace dali {
namespace mm {

BorrowPool::BorrowPool(int device_id = 0) : device_id(device_id) {
  fprintf(stdout, "Initializtion of Borrow Pool");
  fflush(stdout);
}

void BorrowPool::init() {
...
}


}  // namespace mm
}  // namespace dali
```

I make a function on `DALI/dali/core/mm/default_resources.cc`,
and make this function to python API on `DALI/dali/python/backend_impl.cc`

```
DLL_PUBLIC
void InitBorrowPool() {
  borrow_pool_.init();
}
```

```
  m.def("InitBorrowPool", mm::InitBorrowPool,
R"(Initializes Borrow Pool)");
```

If I misuse the architecture, let me know.

Thank you.

**Comment by JanuszL** [comment]
@mzient can you shed some light on how to use the memory resource in an indented way?

**Comment by Esthesia** [comment]
@JanuszL I tried to check that DALI can use GPU memory supplied by other processes, so this memory pool holds the GPU memory. By installing this, I tried to use this GPU memory, not calling CUDAMalloc in `malloc_resource.h`.

**Comment by JanuszL** [comment]
Although I leave the details to explain for @mzient, as far as I understand only selected interfaces from the memory allocator are available - please check [this](https://github.com/NVIDIA/DALI/blob/main/include/dali/core/mm/default_resources.h) files. All other functionality is based on this public API and the code templates in the header files.
If you want to create your memory resource please register it using `SetDefaultResource` so everything can use it, using the existing now API. If you can expose any new function for this resource you need to add `DLL_PUBLIC` to it so it is visible as a symbol from the libdali_core.so.

**Comment by Esthesia** [comment]
I thought that `extern` might work, but as you said before, setting `DLL_PUBLIC` also and it works.

**Comment by JanuszL** [comment]
[`extern`](https://en.cppreference.com/w/cpp/language/language_linkage) is a link specification that is mostly relevant for a given linage unit, while `DLL_PUBLIC` is extended `DLL_PUBLIC __attribute__ ((visibility ("default")))` which controls symbol visibility from given linkage unit.

**Comment by Esthesia** [comment]
@JanuszL Thanks a lot. This is really helpful to me. I can close my issue, and about the above design, I wish I have a chance to discuss it with you afterward.
