### ISSUE TITLE
Dali0.7 error: ValueError: When feeding symbolic tensors to a model, we expect thetensors to have a static batch size. Got tensor with shape: None

### ISSUE THREAD

**Issue by owenustc** [NVIDIA/DALI#482]
I have compiled the new dali of github, and used it in keras, but met a error, which is as follow:
/opt/conda/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "test_keras.py", line 68, in <module>
    test_error()
  File "test_keras.py", line 65, in test_error
    validation_steps=3
  File "/src/keras/engine/training.py", line 950, in fit
    batch_size=batch_size)
  File "/src/keras/engine/training.py", line 787, in _standardize_user_data
    exception_prefix='target')
  File "/src/keras/engine/training_utils.py", line 90, in standardize_input_data
    data = [standardize_single_array(x) for x in data]
  File "/src/keras/engine/training_utils.py", line 90, in <listcomp>
    data = [standardize_single_array(x) for x in data]
  File "/src/keras/engine/training_utils.py", line 23, in standardize_single_array
    'Got tensor with shape: %s' % str(shape))
ValueError: When feeding symbolic tensors to a model, we expect thetensors to have a static batch size. Got tensor with shape: None
And the information of my keras and dali is as follow:
Python 3.6.3 |Anaconda, Inc.| (default, Oct 13 2017, 12:02:49)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import keras
/opt/conda/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
>>> print (keras.__version__)
2.1.6
>>> import tensorflow
>>> print (tensorflow.__version__)
1.8.0
>>> import nvidia.dali
>>> print (nvidia.dali.__version__)
0.7.0.dev0
>>>

my test code is as follow:
`class GPUPipeline(Pipeline):
      def __init__(self, batch_size, num_threads, device_id=0, data_dir='./data/'):
            super(GPUPipeline, self).__init__(batch_size, num_threads, device_id, seed = 12)
            self.input1 = ops.FileReader(file_root = data_dir, random_shuffle = False, file_list= data_dir  +  '/file_list.txt')
            self.decode = ops.HostDecoder(output_type = types.RGB)
            self.rotate = ops.Rotate(device="gpu", angle=45, interp_type = types.INTERP_LINEAR)

    def define_graph(self):
        images, label =self.input1()
        images = self.decode(images)
        aug_images = images.gpu()
        aug_images = self.rotate(aug_images)
        return aug_images,label.gpu()

def test_error():
   daliop = dali_tf.DALIIterator()
   pipe = GPUPipeline(BATCH_SIZE,1, 0, data_dir='./data/')
   image,label = daliop(pipe,
            shapes = [(BATCH_SIZE, 322,431, 3),()],
            dtypes =(tf.float32,tf.int32), device_id=0)

   model = Sequential()
   model.add(Conv2D(32, (3, 3), padding='same',
                 input_shape=(322,431, 3)))
   model.add(Activation('relu'))
   model.add(Conv2D(32, (3, 3)))
   model.add(Activation('relu'))
   model.add(MaxPooling2D(pool_size=(2, 2)))
   model.add(Dropout(0.25))
   model.add(Flatten())
   model.add(Dense(512))
   model.add(Dense(1))
   model.add(Activation('softmax'))
   opt = adam(lr=0.0001,decay=1e-6)
   model.compile(loss='categorical_crossentropy',
              optimizer=opt,
              metrics=['accuracy'])
   model.fit(image,label,
              validation_split=0.3,
              steps_per_epoch=3,
              validation_steps=3
              )

test_error()
`

**Comment by Kh4L** [comment]
Hi @owenustc ,
The error you got is saying that Keras is missing shape information about the tensors you provide to `model.fit`. My guess is that it can be solve by providing the shape of the labels in `daliop` creation:
```
image,label = daliop(pipe,
shapes = [(BATCH_SIZE, 322,431, 3),(BATCH_SIZE)],
dtypes =(tf.float32,tf.int32), device_id=0)
```
