### ISSUE TITLE
Question about DALI's memory using pattern

### ISSUE THREAD

**Issue by Esthesia** [NVIDIA/DALI#4825]
### Describe the question.

Dear all

I ran an experiment on DALI's memory consumption and found that memory-increasing events occurred with a similar pattern.
This is my DALI pipeline which uses conditional execution.

* DALI v1.25.0
* Model ResNet-18 with batch size 500
* Dataset OpenImage v6
* 1 epoch experiment

```
@experimental.pipeline_def(enable_conditionals=True)            
def create_dali_pipeline(data_dir, crop, size, shard_id, num_shards, dali_cpu=False, is_training=True):
    rng = fn.random.coin_flip(probability=0.5)
    images, labels = fn.readers.file(file_root=data_dir,
                                     shard_id=shard_id,
                                     num_shards=num_shards,
                                     random_shuffle=is_training,
                                     pad_last_batch=True,
                                     prefetch_queue_depth=1,
                                     name="Reader")

    mean=(0.485 * 255, 0.456 * 255, 0.406 * 255)
    std=(0.229 * 255, 0.224 * 255, 0.225 * 255) 

    if is_training:
        images = fn.decoders.image(images, device="mixed")
        images = fn.resize(images, size=(244, 244)) # If not resizing, OOM occurs on rand_augment
        images = rand_augment.rand_augment(images, n=2, m=9)
        images = fn.random_resized_crop(images, size=[crop, crop], minibatch_size=1)
        output = fn.crop_mirror_normalize(images,
                                            mirror=rng,
                                            mean=mean,
                                            std=std,
                                            dtype=types.DALIDataType.FLOAT,
                                            output_layout=types.NCHW)

    pipe = create_dali_pipeline(batch_size=args.batch_size,
                                num_threads=args.workers,
                                device_id=args.local_rank,
                                seed=12 + args.local_rank,
                                data_dir=traindir,
                                crop=crop_size,
                                size=val_size,
                                dali_cpu=args.dali_cpu,
                                shard_id=args.local_rank,
                                num_shards=args.world_size,
                                is_training=True)
    pipe.build()
    train_loader = DALIClassificationIterator(pipe, reader_name="Reader", last_batch_policy=LastBatchPolicy.PARTIAL)
```

This is the memory consumption graph on 1 epoch experiment. We measured on the device-side `async_pool`, which is not considering the pinned-memory region.

![RN18_DALi_device_pool_memory_consumption](https://user-images.githubusercontent.com/41190076/236294046-6c67f478-aa6a-46c8-9dfc-eb2f5bf2ec0d.png)

I want to know 1) why outstanding allocation of memory, as you can see in the figure (There are 3 outstanding allocations), and 2) the reason why the lower bound of memory consumption increases after the outstanding allocation event.

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @Esthesia,

That are interesting findings. Can you tell me more about how exactly you measure the memory consumption? Using nvidia-smi? Does it run with the training as well?

**Comment by Esthesia** [comment]
Hello @JanuszL,

I traced based on allocate/deallocate primitives in `async_pool`.
I added some lines in the DALI source code to trace and accumulate the allocated sizes.
I ran with the training, but I think this is a pure number of DALI's memory allocation.

**Comment by mzient** [comment]
Hello @Esthesia 
Placing traces in `async_pool`, especially only in allocate/deallocate, doesn't necessarily reflect the memory usage.
1. There are _four_ functions: `allocate`, `deallocate`, `allocate_async`, `deallocate_async`. It's possible that memory allocated with `allocate` is deallocated with `deallocate_async` or _vice versa_.
2. This is just the topmost layer of the allocation system. You can track actual memory consumption by periodically probing the underlying memory resource (e.g. `cuda_vm_resource`).
3. Some parts of the code don't utilize this memory resource _yet_ - most notably, NVJPEG decoder.
4. These measurements don't cover any internal memory usage by the driver, CUDA runtime or other libraries out of our control.

I'd recommend tracking the memory with nvidia-smi. It can print memory consumption per-process. I think @JanuszL is more experienced in this area.

**Comment by Esthesia** [comment]
Hello @mzient,

Thanks for the illustration on memory parts in DALI.

As far as I understand from the code, the NVJPEG decoder uses nvjpeg_memory, which gets memory from malloc_resource.
So, I think it is hard to reflect on the `async_pool` side weird allocation request.

Also, I tracked on `cuda_vm_resource` part `map_block(int block_idx, cuvm::CUMem mem)` function so that the request size is really allocated.

What I found in detail is that one of the outstanding allocation requests from the above graph is requesting 1367238656 bytes which are about 1.37GiB and the number of blocks mapped is 21, which is about 1.41 GiB (since one block is 67.10 MiB in default cuda VM).

So I think it is really allocated memory, but based on your comments, I misunderstood in some stages. 
Could I know a little more detailed information about DALI's memory management?

**Comment by Esthesia** [comment]
For `nvidia-sm`i for profriling,
I am not sure you can see; clearly, this is GPU utilization and memory consumption of one epoch training with DALI.
The yellow line is memory consumption, and you can see that weird stepwise accumulation on memory consumption.
I know PyTorch holds GPU memory, so the summation is larger, but PyTorch usually holds GPU memory at the beginning, so I assumed that this is DALI's additional usage.

![gpu_utilization_memory_usage_thread_1_RN18](https://user-images.githubusercontent.com/41190076/236410493-355eaec0-2620-42f1-95a4-b3ea80477d78.jpg)

**Comment by JanuszL** [comment]
It seems that the `nvidia-smi` measurements are aligned with your original measurement - the memory usage increases at the very beginning and then quickly saturates. As @mzient mentioned there are no spikes in the consumption.
To describe how the asynchronous and stream-aware memory management works in DALI we can say that:
- allocation
```
1.  Try to get the smallest free block for the given stream that can accommodate the requested number of bytes
2.  If succeeded:
3.    remove the block from the free list
4.    store information about padding for this block (if it wasn't fully utilized)
5.    return the pointer to the block
6.  Else:
7.    try to allocate from the global pool (not using upstream)
8.    If succeeded:
9.      return the block
10.   Else:
11.     for each per-stream free list:
12.  	     for each free block:
13.        	if the associated event is ready:
14.           return the block to the global pool
15.   allocate from the global pool (requesting more upstream memory, if necessary)
```
- free
```
1. Look up padding
2. If found:
3  	replace the user-provided block with the original
4. Take a CUDA event from an event pool and record it
5. Put the block, along with the event, in a per-stream free list
```
The global pool (device side pool) is using [CUDA VMM](https://developer.nvidia.com/blog/introducing-low-level-gpu-virtual-memory-management/) - we allocate virtual address space, and then we ask for physical pages and map them to the address space on demand.

**Comment by JanuszL** [comment]
> One thing I am curious about is that stepwise increasing is still existing.

It is mostly because the DALI operates on nonuniform batches. In some cases the next batch just needs more memory than the previous one and the reallocations happen as the currently available memory in the pool is not sufficinet (size of images vary, `rand_augment` selected operations that just need more memory).
If you want to avoid that you can try [perallocating the pool memory](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/advanced_topics_performance_tuning.html#memory-pool-preallocation).

**Comment by Esthesia** [comment]
Thank you @JanuszL 
I have a little orthogonal question about `nonuniform batch operating` in DALI.
I thought that DALI operates image by image when preprocessing. Does `nonuniform batch operating` only reflect the image size, or is there any operator that processes the image in batch?
