### ISSUE TITLE
Ask for supporting for Bicubic filtering

### ISSUE THREAD

**Issue by LuoXin-s** [NVIDIA/DALI#4828]
### Is this a new feature, an improvement, or a change to existing functionality?

Improvement

### How would you describe the priority of this feature request

Must have (e.g. DALI adoption is impossible due to lack in functionality).

### Please provide a clear description of problem this feature solves

Biucbic filtering is important for many of low-level vision tasks, they are sensitive to exact resize function be used. Bicubic one is most popular used, so we should provide supporting for it.

### Feature Description

May work like PIL.InterpolationMode.BICUBIC

### Describe your ideal solution

adding Bicubic support to nvidia.dali.fn.resize()

### Additional context

I know there is a relevant issue, however, it is two years old, and no supporting is here.

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @LuoXin-s,

DALI supports cubic interpolation for resize - please see https://docs.nvidia.com/deeplearning/dali/user-guide/docs/data_types.html#nvidia.dali.types.DALIInterpType.

**Comment by LuoXin-s** [comment]
Hi @JanuszL ,  sorry for late response. When I use cubic interpolation for resize, will it implicitly apply bicubic interpolation on image input?

**Comment by JanuszL** [comment]
> Hi @JanuszL , sorry for late response. When I use cubic interpolation for resize, will it implicitly apply bicubic interpolation on image input?

Yes, it translates to cubic interpolation in both directions for images (bicubic) or volumes (tricubic?).
You can also define different interpolations of upsizing (`mag_filter`) and downsizing (`min_filter`).
