### ISSUE TITLE
Invalid argument: model input must specify 'dims' for xxxx

### ISSUE THREAD

**Issue by DequanZhu** [NVIDIA/DALI#4840]
### Describe the question.

I have a dali pipeline  like below, it produced no errors when serialized it :
```
#!/usr/bin/python3
# -*- coding: utf-8 -*-
# @Time    : 2023/5/8 21:17
# @Author  : dequan
import nvidia.dali as dali
import nvidia.dali.types as types
import numpy as np

BATCH_SIZE = 8
INPUT_SIZE = 224
SCALE_SIZE = 256
FILL_VALUE = 0

MEAN = [123.675, 116.28, 103.53]
STD = [58.395, 57.12, 57.375]


def mean_source():
    return np.asarray(MEAN).reshape((1, 1, 3))


def std_source():
    return np.asarray(STD).reshape((1, 1, 3))


def parse_args():
    import argparse

    parser = argparse.ArgumentParser(
        description="Serialize the pipeline and save it to a file"
    )
    parser.add_argument(
        "file_path", type=str, help="The path where to save the serialized pipeline"
    )
    return parser.parse_args()
@dali.pipeline_def(batch_size=BATCH_SIZE, num_threads=1, device_id=0)

def simple_pipeline():
    image = dali.fn.external_source(device="cpu", name="letterboxed_image")
    image_shape = dali.fn.shapes(image)
    image_h = dali.fn.slice(image_shape, start=0, shape=1, axes=[0])
    image_w = dali.fn.slice(image_shape, start=1, shape=1, axes=[0])
    det_box = dali.fn.external_source(device="cpu", name="det_box")
    mean = dali.fn.external_source(batch=False,device="cpu", source=mean_source, dtype=types.FLOAT)
    std = dali.fn.external_source(batch=False,device="cpu", source=std_source, dtype=types.FLOAT)
    det_box = dali.fn.reshape(det_box, shape=[-1, 2])
    det_box_size = det_box[1] - det_box[0]
    det_box_size = dali.fn.cast(det_box_size, dtype=types.FLOAT)
    crop_w = dali.fn.slice(det_box_size, start=0, shape=1, axes=[0])
    crop_h = dali.fn.slice(det_box_size, start=1, shape=1, axes=[0])
    crop_pos_x = det_box[0][0] / (image_w - crop_w)
    crop_pos_y = det_box[0][1] / (image_h - crop_h)
    cropped_image = dali.fn.crop(
        image.gpu(),
        crop_h=crop_h,
        crop_w=crop_w,
        crop_pos_x=crop_pos_x,
        crop_pos_y=crop_pos_y,
    )
    cropped_image = dali.fn.resize(cropped_image, size=INPUT_SIZE, mode="not_larger")
    cropped_image = dali.fn.pad(
        cropped_image,
        axis_names="HW",
        shape=[INPUT_SIZE, INPUT_SIZE],
        fill_value=FILL_VALUE,
    )
    cropped_image = dali.fn.normalize(
        cropped_image, axis_names="HW", mean=mean, stddev=std
    )
def main(filename):
    simple_pipeline().serialize(filename=filename)


if __name__ == "__main__":
    args = parse_args()
    main(args.file_path)
```
and my triton model config is like below:
```
name: "classifier-preprocess"
backend: "dali"
max_batch_size: 8
input [
  {
    name: "letterboxed_image"
    data_type: TYPE_UINT8
    dims: [-1,-1,3]
  },
  {
    name: "det_box"
    data_type: TYPE_FP32
    dims: [ 4 ]
  }
]
output [
  {
    name: "cropped_image"
    data_type:TYPE_FP32
    dims: [3,224, 224]
  }
]
instance_group {
  count: 8
  kind: KIND_GPU
}
```
when I load it by triton, some errors occures, the detailed error message is like below:
![微信图片_20230509203631](https://github.com/NVIDIA/DALI/assets/26426479/9516ded3-1956-4054-8a7d-301184ba23fd)

what does the error message means, is it caused by this two lines code?
```
mean = dali.fn.external_source(batch=False,device="cpu", source=mean_source, dtype=types.FLOAT)
std = dali.fn.external_source(batch=False,device="cpu", source=std_source, dtype=types.FLOAT)
```

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by szalpal** [comment]
Hi @DequanZhu ,

Yes, I believe that these two lines cause the error. These are the `external_source` nodes that do not have corresponding entries in the `input []` section of the model configuration. Triton parses the model, finds the `ExternalSource` nodes but fails to find their configuration.

To solve the problem you should do one of the following:
1. Remove these two lines if they are unnecessary,
2. Add corresponding entries to `input []` section in the model configuration,
3. Add `ndims` argument to these external sources, so that Tritons `autoconfiguration` can pick them up.

The last option assumes that the model can be autoconfigured, which is not always the case. I believe the quickest approach would be option 1 in your case.

If you have any more questions, don't hesitate to ask!

**Comment by DequanZhu** [comment]
Hi, @szalpal ,the `mean` and `std`  is necessary for the pipeline, according to [dali.fn.normalize](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.normalize.html#nvidia-dali-fn-normaliz) api, `mean` and `stddev` keyword arguments must be float or TensorList of float, is there any way I can pass these two parameter to `nvidia.dali.fn.normalize ` api except for using external_source, because they actually should be constant values in this scene.

**Comment by szalpal** [comment]
@DequanZhu ,

The best technical answer: It depends.

If you know these values pre-runtime, you can just hardcode them in the DALI Pipeline:
```python
    cropped_image = dali.fn.normalize(
        cropped_image, axis_names="HW", mean=[123.675, 28.116, 103.53], stddev=[123.675, 28.116, 103.53]
    )
```
Or use a dedicated operator [`fn.constant`](https://docs.nvidia.com/deeplearning/dali/main-user-guide/docs/operations/nvidia.dali.fn.constant.html#nvidia.dali.fn.constant). Which approach you choose would depend on the specifics of your use case. If every sample in the dataset would use the same `mean` and `std` parameters, I believe the former approach would be sufficient.

However, if you don't know these values pre-runtime - e.g. they are calculated by a different model in the model ensemble, you need to use external source. The `fn.external_source` is the only operator which can input runtime custom data into DALI Pipeline in Triton.

One more suggestion from my side - if you find putting together the model configuration problematic, Triton has quite a cool feature called [model autoconfiguration](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/model_configuration.md#auto-generated-model-configuration). [DALI supports this too](https://github.com/triton-inference-server/dali_backend#configuration-auto-complete). You might want to check this out, maybe autoconfiguration would be helpful in your case.

**Comment by DequanZhu** [comment]
Hi, @szalpal, yes I know these values pre-runtime, they are just constant values in this scene. I can't just pass these two constant list to `mean` and `std` parameter like this:
```
    cropped_image = dali.fn.normalize(
        cropped_image, axis_names="HW", mean=[123.675, 28.116, 103.53], stddev=[123.675, 28.116, 103.53]
    )
```
when I serialized the pipeline,I got a error message:
![微信图片_20230510163735](https://github.com/NVIDIA/DALI/assets/26426479/b922546b-8f1e-4743-bcc9-b26906818942)
when use  [fn.constant](https://docs.nvidia.com/deeplearning/dali/main-user-guide/docs/operations/nvidia.dali.fn.constant.html#nvidia.dali.fn.constant) like below:
```
    cropped_image = dali.fn.normalize(
        cropped_image, axis_names="HW", mean=dali.fn.constant(fdata=[123.675, 28.116, 103.53]), stddev=dali.fn.constant(fdata=[123.675, 28.116, 103.53]) )
```
no errors occurs when serialized it, but when load the pipeline by triton and exec a infer request by tritonclient, some errors occurs:
![微信图片_20230510165658](https://github.com/NVIDIA/DALI/assets/26426479/0a5a8f40-ae77-4c31-abc1-0f796e637d1e)
my triton container is r22.12 and I install nvidia_dali_cuda110-1.24.0-7582302-py3-none-manylinux2014_x86_64.whl in this container using pip.

**Comment by szalpal** [comment]
@DequanZhu ,

the error you've pasted comes from `fn.normalize` operator. It might, or might not, be related to the `fn.constant` operator.

The DALI Pipeline you've pasted above most likely suffers from some problems. At the first glance I see, that there is no `return` statement from the Pipeline. I'd encourage you to run DALI pipeline as a stand-alone first, before plugging it into Triton. This way you can use the [debug mode](https://docs.nvidia.com/deeplearning/dali/main-user-guide/docs/examples/general/debug_mode.html) to narrow down errors and polish the pipeline. A developed pipeline can then be easily plugged into Triton.

As always, in case you have any questions, don't hesitate to ask :)
