### ISSUE TITLE
value range in pipeline

### ISSUE THREAD

**Issue by LuoXin-s** [NVIDIA/DALI#4850]
### Describe the question.

I have few questions regarding the data ranges in various stages of pipeline.

Is the output of image decoder `fn.decoders.image(output_type=types.RGB)` in range [0, 255] ? 

Is the output of normalization ops `fn.normalize(p0.gpu(),
                            dtype=types.FLOAT,
                            output_layout="CHW",
                            mean=[0.485 * 255, 0.456 * 255, 0.406 * 255],
                            std=[0.229 * 255, 0.224 * 255, 0.225 * 255])` in range [0, 1]? And why it out data in range[0, 1] though I have to specify mean and std in range [0, 255]?

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @LuoXin-s ,

The normalization performs `out=(in - mean) / stddev`, so in this case it is `out=(in - [0.485 * 255, 0.456 * 255, 0.406 * 255])/[0.229 * 255, 0.224 * 255, 0.225 * 255]`, so first you subtract the mean that is in range [0, 255], then you divide by 255 and again by std in range [0,1]. The divisions can be combined and that is why you divide by `[0.229 * 255, 0.224 * 255, 0.225 * 255]` so the result ends up in range [0,1].

**Comment by LuoXin-s** [comment]
Hi @JanuszL ,

Thank you for detailed explanation. So if I want just normalize a data from [0, 255] to [0, 1], I should call `fn.normalize ` with mean `[0, 0, 0]` and std `[255, 255, 255]`.

**Comment by JanuszL** [comment]
Or even just:
```
out = in / 255
```
As DALI supports [mathematical expression inside the pipeline](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/math.html#).

**Comment by LuoXin-s** [comment]
> As DALI supports [mathematical expression inside the pipeline](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/math.html#).
Ok, this would be great!

Is following code a good way to achieve my purpose?
`img = fn.reinterpret(img.gpu(), dtype=types.FLOAT, layout='CHW') / 255`

**Comment by LuoXin-s** [comment]
@JanuszL Yeah, `crop_mirror_normalize` is my request. Actually, I encounter strange training issues when I use `reinterpret `. Thanks a lot.
