### ISSUE TITLE
Maximizing raw throughput for fn.readers.file

### ISSUE THREAD

**Issue by fversaci** [NVIDIA/DALI#4857]
Hi all,

we're currently testing the developing version of our Cassandra-DALI plugin and we're using the standard `fn.readers.file` (using DALI v1.23) as a benchmark to evaluate and compare against our plugin's performance.

In one of the tests we're trying to obtain the maximum throughput out of `fn.readers.file`, with data staying in CPU memory and with no decoding at all, using the standard ImageNet dataset. [Here](https://github.com/fversaci/cassandra-dali-plugin/blob/test_loop_fs/examples/imagenette/loop_read_fs.py) you can find the simple python script we're using for this purpose.

We're measuring the time to read the complete training dataset (140 GB) in a machine with enough RAM to actually cache the files in memory after doing a few preliminary dataset scans (i.e., the read is only "formally" from the disks). We're testing both a single reader and many concurrent readers (as it would happen when performing a distributed training):

```bash
# single reader
$ python3 loop_read_fs.py --file-root=/data/imagenet/train/  --epochs 5
# 16 concurrent readers
$ torchrun --nproc_per_node=16 loop_read_fs.py --file-root=/data/imagenet/train/  --epochs 5
```
On our machine it takes about 70 seconds to read the dataset with a single reader and about 8 seconds to read it with 16 concurrent readers.

Since it seems that, when using a single reader, the throughput is somehow bottlenecked, we're wondering if there are some options that we should add to `fn.readers.file` or to the pipeline to increase it, or if this is the maximum throughput achievable for this particular case.

Thanks!

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @fversaci,

Thank you for reaching out.
Most of the reader uses only one thread to read the data from the disc and multiple threads to parse it. In this particular case if the data is in the RAM the bottleneck is the transfer of RAM to RAM. If you use multiple parallel DALI pipelines you just use more resources in parallel to copy the data in the RAM. So your numbers are aligned with the expectations.

> Since it seems that, when using a single reader, the throughput is somehow bottlenecked, we're wondering if there are some options that we should add to fn.readers.file or to the pipeline to increase it, or if this is the maximum throughput achievable for this particular case.

In most cases, the default configuration of the reader should be the best and I cannot think of any knob you can use to tune it. What I would check is the theoretical speed of your drive and compare it with it. You can also try out other data set containers, like RecordIO and [the `mxnet reader`](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.readers.mxnet.html) which uses sequential access to the data which may bit faster, than opening and closing each file like in the mentioned file reader.

**Comment by fversaci** [comment]
Hi @JanuszL,

thanks for your answer: it totally makes sense that the bottleneck we observe is in the RAM-to-RAM copy: the raw throughput in the filesystem case is about 2 GB/s, while in our case we manage to saturate a 3 GB/s link, but only by using a thread pool dedicated to data copying.

Also thanks for pointing out RecordIO and the MXNnet reader, we'll surely have a look at them too!
