### ISSUE TITLE
Upgrade `gast` dependency

### ISSUE THREAD

**Issue by thomas-bouvier** [NVIDIA/DALI#4865]
### Is this a new feature, an improvement, or a change to existing functionality?

Change

### How would you describe the priority of this feature request

Nice to have (e.g. Adoption is possible, the feature will enhance the use-case even more).

### Please provide a clear description of problem this feature solves

It would be nice to support recent versions of `gast` (at least version 0.5), as keeping an old version introduces some complexity with my installation (it would relieve Spack's concretizer too).

The requirement is defined here: https://github.com/NVIDIA/DALI/blob/f9a3ee4eb1f918d1d52ddf995ad68b943f108931/dali/python/setup.py.in#LL87C27-L87C27

### Feature Description

I don't know what the `gast` library does exactly. As a user of DALI though, I would expect to use recent versions for dependencies.

### Describe your ideal solution

Ideally, we would have the following:

```yaml
install_requires=[
          # gast and astunparse are required for AutoGraph.
          # Currently supported range of versions.
          'astunparse >= 1.6.0',
          'gast >= 0.2.1',
          ],
```

Some testing has to be done to ensure that this requirement relax does not break anything.

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by klecki** [comment]
Hi @thomas-bouvier,
I will test it and get back to you.

**Comment by thomas-bouvier** [comment]
Thanks. FYI, a specific version of `gast` potentially breaks Tensorflow tests: https://github.com/tensorflow/tensorflow/commit/c762c4501ca017994c1fa5554c3c8e47b7c80b66.

**Comment by JanuszL** [comment]
@thomas-bouvier - the PR you mentioned puts the same constraints on gast as we do so it should be fine (it is included in TF 2.9 and later and DALI seems to work with them just fine).

**Comment by klecki** [comment]
I see that we have a failing test (that was ported from TF) when using newest `gast`, and it appears it was missing the third argument (type_comment) to the gast.Assign node.

https://github.com/NVIDIA/DALI/pull/4869 I will run the CI and see what happens.

**Comment by klecki** [comment]
Checking it further, it doesn't work with older gast versions now, so we need to have yet another layer of generic ast on top of it.

**Comment by klecki** [comment]
@thomas-bouvier 
Looks like with those changes DALI works with newer `gast`: https://github.com/NVIDIA/DALI/pull/4869
But it stops working with anything below 0.5.

One of the solutions would be to, when importing swap the `gast.Assign` with a custom wrapper, based on the version, so it always accepts 3 arguments.
If this issue is urgent for you, would you be able to help us by providing a PR? 

We are now working on other high priority items and won't be able to switch to that for now.

**Comment by klecki** [comment]
@thomas-bouvier  thanks for the contribution, I merged the change.

**Comment by thomas-bouvier** [comment]
Thank you to you @klecki and the entire DALI team for your commitment to this great project!
