### ISSUE TITLE
How to crop multiple tensor in aligned position?

### ISSUE THREAD

**Issue by LuoXin-s** [NVIDIA/DALI#4876]
### Describe the question.

Hi, I want to do something like below:
```python
        p0, p1, ref = fn.crop_mirror_normalize([p0.gpu(), p1.gpu(), ref.gpu()], dtype=types.FLOAT, output_layout='CHW', std=[255, 255, 255])
```

So that, it crop p0, p1, ref in aligned position.

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @LuoXin-s,

The `fn.crop_mirror_normalize` operator is fully deterministic you can just:
```
p0 = fn.crop_mirror_normalize(p0.gpu(), dtype=types.FLOAT, output_layout='CHW', std=[255, 255, 255])
p1 = fn.crop_mirror_normalize(p1.gpu(), dtype=types.FLOAT, output_layout='CHW', std=[255, 255, 255])
ref = fn.crop_mirror_normalize(ref.gpu(), dtype=types.FLOAT, output_layout='CHW', std=[255, 255, 255])
```
To make sure they are aligned just pass the same values of crop position and window dimensions.

**Comment by LuoXin-s** [comment]
Hi @JanuszL, actually, I want to use dynamic position which depends on image shape like below:
```python
  top = fn.random.uniform(range=(0, (shape[0] - patch_size + 1) / shape[0]))
  left = fn.random.uniform(range=(0, (shape[1] - patch_size + 1) / shape[1]))

  p0 = fn.crop_mirror_normalize(p0.gpu(), dtype=types.FLOAT,
                                crop=(patch_size, patch_size),
                                crop_pos_x=left,
                                crop_pos_y=top,
                                output_layout='CHW', std=[255, 255, 255])
```
However, I see DALI do not support DataNode as parameters of `uniform`. Could you please provide me some equivalent implementation? Thanks.

**Comment by JanuszL** [comment]
How about:
```
 top = fn.random.uniform(range=(0, 1)) *  (shape[0] - patch_size + 1) / shape[0]
```
?

**Comment by LuoXin-s** [comment]
Perhaps, I have misunderstated the parameters `crop_pos_x` and `crop_pos_y` for crop_mirror_normalize. The documentation states that "The actual position is calculated as crop_y = crop_y_norm * (H - crop_H)", taking into account boundary issues.

The aforementioned code is implemented to avoid sampling outside the boundaries.

**Comment by LuoXin-s** [comment]
So, should this code be ok?
```python
top = fn.random.uniform(range=(0, 1))
left = fn.random.uniform(range=(0, 1))

p0 = fn.crop_mirror_normalize(p0.gpu(), dtype=types.FLOAT,
                            crop=(patch_size, patch_size),
                            crop_pos_x=left,
                            crop_pos_y=top,
                            output_layout='CHW', std=[255, 255, 255])
p1 = fn.crop_mirror_normalize(p1.gpu(), dtype=types.FLOAT,
                            crop=(patch_size, patch_size),
                            crop_pos_x=left,
                            crop_pos_y=top,
                            output_layout='CHW', std=[255, 255, 255])
ref = fn.crop_mirror_normalize(ref.gpu(), dtype=types.FLOAT,
                            crop=(patch_size, patch_size),
                            crop_pos_x=left,
                            crop_pos_y=top,
                            output_layout='CHW', std=[255, 255, 255])
```

**Comment by JanuszL** [comment]
Sorry for missing what you intent to achieve.
Yes, the position in the `crop_mirror_normalize` is relative, so first the operator taks the window that has predefined size, and then based on the space left (the difference between the image size and the window size) and the value of crop_pos anchors it in the image.
Yes, I think the code above should work just fine.
