### ISSUE TITLE
Working with NV12 in dali?

### ISSUE THREAD

**Issue by joey-trigo** [NVIDIA/DALI#4889]
### Describe the question.

I have an image received from an external source that is a byte array representing a raw nv12 images.

NV12 is YUV 4:2:0 but with the U and V interleaved, so if my image is 1280 * 720 pixels then my array has 1280*720 Y pixels followed by (1280 / 2) * (720 / 2)  U and V pixels interleaved, where each value in U,V is used for a 2x2 square of pixels in the image.

Try as I may I can't figure out how to load this image into dali. What I really want is a function that takes an NV12 image and converts it to an RGB image that dali can comfortably work with.

Barring that, I could do some extra work to convert the image myself. Here's how I could handle the conversion of NV12 -> YCbCr in numpy, after which converting to RGB is straightforward:

```
y = data[:720 * 1280]

uv = data[720 * 1280 : ]

# Split the U and V
uv = uv.reshape((720//2, 1280//2, 2)).transpose()

# Duplicate U and V to a 2x2 box
uv = uv.repeat(2, axis=1).repeat(2, axis=2)

# Undo transpose
u = u.transpose()
v = v.transpose()
```

I can't figure out how to convert this code to DALI, particularly the repeat functions. I'm pretty sure though that this is completely the wrong way to handle this issue.

Is there a way to handle NV12 images in DALI, and if not does converting them manually the way I'm describing make sense?

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by mzient** [comment]
Hello @joey-trigo 
We don't have a native support for NV12. Regarding the repeat function, you can use `resize` instead - you can use INTERP_NN to achieve replication of the UV components or you can use a fancier interpolation method for the chroma for (possibly) higher quality output.

```Python
y = data[:720 * 1280]

uv = data[720 * 1280 : ]

y = fn.reshape(y, shape=(720, 1280, 1))
uv = fn.reshape(uv, shape=(720//2, 1280//2, 2))
uv = fn.resize(uv, size=(720, 1280), interp_type=dali.types.INTERP_NN)

yuv = fn.cat(y, uv, axis=2)  # this produces YUV tensor in CHW layout, which you can convert to RGB with our 
rgb = fn.color_space_conversion(yuv, image_type=dali.types.YCbCr, output_type=dali.types.RBB)
```
If your YUV data requires a custom matrix (other than ITU-T.BT.601), you can use a custom conversion matrix like this:

```Python
rgb = fn.coord_transform(yuv, MT=your_3x4_conversion_matrix, dtype=dali.types.UINT8)
```

**Comment by joey-trigo** [comment]
Thanks! That's very helpful
