### ISSUE TITLE
Clang dependency issue for DALI

### ISSUE THREAD

**Issue by khushbuKinara** [NVIDIA/DALI#4891]
### Describe the question.

I am trying to install dependencies for NVIDIA-Xavier to run ML perf test, using [script](https://github.com/mlcommons/inference_results_v2.0/blob/master/closed/Azure/scripts/install_xavier_dependencies.sh).

First I got the below error(No module named 'clang'):
`Traceback (most recent call last): File "/usr/local/DALI/dali/core/../../tools/stub_generator/stub_codegen.py", line 24, in <module> import clang.cindex **ModuleNotFoundError: No module named 'clang'** dali/core/CMakeFiles/dynlink_cuda.dir/build.make:82: recipe for target 'dali/core/dynlink_cuda_gen.cc' failed make[2]: *** [dali/core/dynlink_cuda_gen.cc] Error 1 CMakeFiles/Makefile2:2203: recipe for target 'dali/core/CMakeFiles/dynlink_cuda.dir/all' failed make[1]: *** [dali/core/CMakeFiles/dynlink_cuda.dir/all] Error 2 make[1]: *** Waiting for unfinished jobs.... [  3%] Linking C static library libffts.a [  3%] Built target ffts_static Makefile:170: recipe for target 'all' failed make: *** [all] Error 2
`

Then I installed clang using `pip3 install clang` 
`$ clang --version`
clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

`$ ls -l /usr/lib/aarch64-linux-gnu/libclang*`
lrwxrwxrwx 1 root root       17 4月   6  2018 /usr/lib/aarch64-linux-gnu/libclang-6.0.so -> libclang-6.0.so.1
-rw-r--r-- 1 root root 24061592 4月   6  2018 /usr/lib/aarch64-linux-gnu/libclang-6.0.so.1
lrwxrwxrwx 1 root root       44 5月  30 23:41 /usr/lib/aarch64-linux-gnu/libclang.so -> /usr/lib/aarch64-linux-gnu/libclang-6.0.so.1

But my DALI installation is looking for libclang-16.so, so I linked libclang-16.so to libclang-6.0.so.1.

`$ ls -lrth /usr/lib/aarch64-linux-gnu/libclang*`
-rw-r--r-- 1 root root 23M 4月 6 2018 /usr/lib/aarch64-linux-gnu/libclang-6.0.so.1
lrwxrwxrwx 1 root root 17 4月 6 2018 /usr/lib/aarch64-linux-gnu/libclang-6.0.so -> libclang-6.0.so.1
lrwxrwxrwx 1 root root 44 5月 30 23:41 /usr/lib/aarch64-linux-gnu/libclang.so -> /usr/lib/aarch64-linux-gnu/libclang-6.0.so.1
lrwxrwxrwx 1 root root 44 6月 1 01:07 /usr/lib/aarch64-linux-gnu/libclang-16.so -> /usr/lib/aarch64-linux-gnu/libclang-6.0.so.1

Now I am getting,
` -- Generating done -- Build files have been written to: /usr/local/DALI/build [  0%] Running C++ protocol buffer compiler on proto/dali.proto Scanning dependencies of target cocoapi [  1%] Building C object CMakeFiles/cocoapi.dir/third_party/cocoapi/common/maskApi.c.o Scanning dependencies of target DALI_PROTO [  1%] Building CXX object dali/pipeline/CMakeFiles/DALI_PROTO.dir/dali.pb.cc.o [  1%] Linking C static library libcocoapi.a [  1%] Built target cocoapi Scanning dependencies of target ffts_static [  1%] Building C object third_party/ffts/CMakeFiles/ffts_static.dir/src/ffts.c.o [  1%] Building C object third_party/ffts/CMakeFiles/ffts_static.dir/src/ffts_chirp_z.c.o [  2%] Building C object third_party/ffts/CMakeFiles/ffts_static.dir/src/ffts_nd.c.o [  2%] Building C object third_party/ffts/CMakeFiles/ffts_static.dir/src/ffts_real.c.o [  2%] Building C object third_party/ffts/CMakeFiles/ffts_static.dir/src/ffts_real_nd.c.o [  2%] Building C object third_party/ffts/CMakeFiles/ffts_static.dir/src/ffts_transpose.c.o [  3%] Building C object third_party/ffts/CMakeFiles/ffts_static.dir/src/ffts_trig.c.o [  3%] Building C object third_party/ffts/CMakeFiles/ffts_static.dir/src/ffts_static.c.o /usr/local/DALI/third_party/ffts/src/ffts_static.c:239:36: warning: ‘ffts_constants_inv_64f’ defined but not used [-Wunused-const-variable=] static const FFTS_ALIGN(16) double ffts_constants_inv_64f[16] = { ^~~~~~~~~~~~~~~~~~~~~~ /usr/local/DALI/third_party/ffts/src/ffts_static.c:195:36: warning: ‘ffts_constants_64f’ defined but not used [-Wunused-const-variable=] static const FFTS_ALIGN(16) double ffts_constants_64f[16] = { ^~~~~~~~~~~~~~~~~~ /usr/local/DALI/third_party/ffts/src/ffts_static.c:141:36: warning: ‘ffts_constants_small_inv_64f’ defined but not used [-Wunused-const-variable=] static const FFTS_ALIGN(16) double ffts_constants_small_inv_64f[24] = { ^~~~~~~~~~~~~~~~~~~~~~~~~~~~ /usr/local/DALI/third_party/ffts/src/ffts_static.c:77:36: warning: ‘ffts_constants_small_64f’ defined but not used [-Wunused-const-variable=] static const FFTS_ALIGN(16) double ffts_constants_small_64f[24] = { ^~~~~~~~~~~~~~~~~~~~~~~~ [  3%] Built target DALI_PROTO [  3%] Running cuda.h stub generator Traceback (most recent call last): File "/home/jetson/.local/lib/python3.8/site-packages/clang/cindex.py", line 4136, in register_function func = getattr(lib, item[0]) File "/usr/lib/python3.8/ctypes/__init__.py", line 386, in __getattr__ func = self.__getitem__(name) File "/usr/lib/python3.8/ctypes/__init__.py", line 391, in __getitem__ func = self._FuncPtr((name_or_ordinal, self)) AttributeError: /usr/lib/aarch64-linux-gnu/libclang-16.so: undefined symbol: clang_CXXMethod_isDeleted`

Can somebody please help me resolve the above error.
Thanks in advance.

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @khushbuKinara,

Thank you for reaching out. The mentioned recipe applies to [DALI 0.31](https://github.com/mlcommons/inference_results_v2.0/blob/master/closed/Azure/scripts/install_xavier_dependencies.sh#L128).
What you can do is to refer the [cross-compilation recipe included in DALI](https://github.com/NVIDIA/DALI/blob/main/docker/Dockerfile.build.aarch64-linux#L53) repo and try to port it to Xavier.
So something like this:
```
pip install clang==14.0 && pip install libclang==14.0.1
```
may help.
You can always compile DALI on x86 using [this guide](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/compilation.html#cross-compiling-for-aarch64-jetson-linux-docker) and then install it on the target system.

**Comment by khushbuKinara** [comment]
Thanks @JanuszL this version works.
