### ISSUE TITLE
How DALI form a batch of data?

### ISSUE THREAD

**Issue by Luciennnnnnn** [NVIDIA/DALI#4901]
### Describe the question.

Hi, I'm doing a video processing project, and I found reading video data is extremely slow establishing a bottleneck in training.

Actually, my dataset is not very large, so I could cache full video data in memory. However, The loading process is still slow than my expectation. After some diagnosis, it is evident that **stack multiple frames in time (explicitly through np.stack by myself) and stack multiple video in batch (implicitly done by Dataloader of Pytorch) is very slow.** I can avoid stack multiple frames in time every time by a memory cache too, however, there is no idea to deal with stacking in batch.

The question is how DALI process data loading? Can I solve my problem by DALI? How should I do that?

Thanks! Any responses and suggestions would be appreciated.

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @LuoXin-s,

Thank you for reaching out.
In the case of DALI [the 'video reader operator'](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.readers.video.html) reads randomly selected sequence of frames to build a sample. This process is repeated multiple times to build a batch. To obtain each sequence DALI needs to seek the preceding keyframe, decode starting from it till to the last frame in the sequence. In effect, some frames need to be discarded (between the keyframe and the frame that is the first in the sequence, and some in between sequence frames when the stride is greater than 1). If you can cache all frames then there is a high chance you can match DALI which would win in case of the data set that cannot be cached in the memory. But feel free to [try it out and comapre](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/sequence_processing/video/video_reader_simple_example.html).
