### ISSUE TITLE
File Path from fn.readers.video

### ISSUE THREAD

**Issue by da2so** [NVIDIA/DALI#4909]
### Describe the question.

As I know, `fn.readers.video` can return the videos and labels. But I want to get the video file paths too.
Is there a way to get a video file path using `fn.readers.video`?

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by awolant** [comment]
Hello,
thanks for the question. For now, unfortunately video reader does not support something like this out of the box. 

I added this feature to the list where we are tracking video reader improvements.

**Comment by JanuszL** [comment]
Hi @da2so,

https://github.com/NVIDIA/DALI/pull/4914 should address this missing functionality and expose the path using `source_info()` method of the returned tensors.

**Comment by bpleshakov** [comment]
You can pass list of file with empty label list such as 
```
    video, labels = fn.readers.video(filenames=filenames, labels=[])
```

This will result in label returned by dali is an index of a video in filenames list. You must be able to map this index to file path somewhere outside dali.

**Comment by JanuszL** [comment]
@bpleshakov - In DALI 1.28 it should be an output tensor property you can extract - see https://github.com/NVIDIA/DALI/pull/4916.

**Comment by bpleshakov** [comment]
I mean, I got it.
I just suggesting workaround that I am heavily use. For example, video reader do not support label vectors (for multi labeling task, for example) or some other complex data you would like to add to batch that is depends on video. With this simple mapping you can do it.

**Comment by awolant** [comment]
DALI 1.28 is public, I am closing it for now.
