### ISSUE TITLE
Function TensorList<Backend> is a deleted function error for customdummy build

### ISSUE THREAD

**Issue by addisonklinke** [NVIDIA/DALI#491]
In the most recent master branch (commit cfcb87639dd2a5786c423681cab24444fea05922), the custom dummy example for plugin operators does not compile. All that is needed to reproduce is: 

1. `cd docs/examples/extend/customdummy`
2. `mkdir build && cd build`
3. `cmake .. && make -j8` 

This gives me the following error(s) related to a deleted function in tensor_list.h:

```
/home/addison/Documents/git/nvidia_dali/docs/examples/extend/customdummy/dummy.cu(9): error: function "dali::TensorList<Backend>::TensorList(const dali::TensorList<Backend> &) [with Backend=dali::GPUBackend]"
/home/addison/miniconda3/envs/openalpr/lib/python3.6/nvidia/dali/include/dali/pipeline/data/tensor_list.h(317): here cannot be referenced -- it is a deleted function

/home/addison/Documents/git/nvidia_dali/docs/examples/extend/customdummy/dummy.cu(10): error: expression must have pointer type

/home/addison/Documents/git/nvidia_dali/docs/examples/extend/customdummy/dummy.cu(11): error: expression must have pointer type

/home/addison/Documents/git/nvidia_dali/docs/examples/extend/customdummy/dummy.cu(12): error: expression must have pointer type

/home/addison/Documents/git/nvidia_dali/docs/examples/extend/customdummy/dummy.cu(12): error: expression must have pointer type

5 errors detected in the compilation of "/tmp/tmpxft_00001118_00000000-6_dummy.cpp1.ii".
CMake Error at customdummy_generated_dummy.cu.o.cmake:279 (message):
  Error generating file
  /home/addison/Documents/git/nvidia_dali/docs/examples/extend/customdummy/build/CMakeFiles/customdummy.dir//./customdummy_generated_dummy.cu.o
```

**Comment by JanuszL** [comment]
It looks that we forget to update the example in https://github.com/NVIDIA/DALI/pull/449.

**Comment by Kh4L** [comment]
Hi @addisonklinke , indeed we didn't update this example to the new API. #492 should address that, once merged.

**Comment by Kh4L** [comment]
Merged, closing issue

**Comment by addisonklinke** [comment]
I have #492 and the two commits following as well, but am still getting the same error when trying to build the custom dummy example

**Comment by Kh4L** [comment]
@addisonklinke  do you get *exactly* the same error?

Can you paste the content of `docs/examples/extend/customdummy/dummy.cu` here? Or just verify yours against [master's one](https://github.com/NVIDIA/DALI/blob/master/docs/examples/extend/customdummy/dummy.cu)?

**Comment by addisonklinke** [comment]
@Kh4L I figured out the issue and am no longer getting an error compiling `libcustomdummy.so`. My Python interpreter was using Dali from the pip install of v0.6.1 instead of the one I compiled from scratch off the master branch. Once I pointed Python to the latest Dali build, the custom dummy example worked fine. My apologies for the confusion
