### ISSUE TITLE
Dali0.7 error: TypeError: '<' not supported between instances of 'EdgeReference' and 'float'

### ISSUE THREAD

**Issue by owenustc** [NVIDIA/DALI#493]
Hi, I want to implement that every image rotation with a probability ,about 0.3,  but meet the error in dali0.7 as follow:
/opt/conda/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "test_tf2.py", line 63, in <module>
    test_error()
  File "test_tf2.py", line 45, in test_error
    pipe = GPUPipeline(BATCH_SIZE,1, 0, data_dir='./data/',mask_dir='./data_mask/')
  File "test_tf2.py", line 25, in __init__
    self.rotate = ops.Rotate(device="gpu", angle=45, interp_type = types.INTERP_LINEAR,mask=self.rng()<0.3)
TypeError: '<' not supported between instances of 'EdgeReference' and 'float'
 My code can be executed success with a older version of dali, but dali-0.7 no work.  How do i write the code to implement the function that rotation with a fixed probability.  my code as follow:
class GPUPipeline(Pipeline):
    def __init__(self, batch_size, num_threads, device_id=0, data_dir='./data/',mask_dir='./data_mask/'):
        super(GPUPipeline, self).__init__(batch_size, num_threads, device_id, seed = 12)
        self.input1 = ops.FileReader(file_root = data_dir, random_shuffle = False, file_list= data_dir  +  '/file_list.txt')
        self.decode = ops.HostDecoder(output_type = types.RGB)
        self.rng = ops.Uniform(range=(0,1.0))
        self.rotate = ops.Rotate(device="gpu", angle=45, interp_type = types.INTERP_LINEAR,mask=self.rng()<0.3)
        self.cast = ops.Cast(device='gpu', dtype=types.DALIDataType.UINT8)

    def define_graph(self):
        images, label =self.input1()
        images = self.decode(images)
        aug_images = images.gpu()
        aug_images = self.rotate(aug_images)
        return aug_images,label.gpu()

def test_pipe():
   pipe = GPUPipeline(BATCH_SIZE,1, 3, data_dir='./data/',mask_dir='./data_mask/')
   pipe.build()
   pipe_out = pipe.run()
   image, label = pipe_out
   print (image.asCPU().at(0).shape, label.asCPU().at(0).shape)
   cv2.imwrite("./img_pipe.png", image.asCPU().at(0).astype("uint8"))

def test_error():
   daliop = dali_tf.DALIIterator()
   pipe = GPUPipeline(BATCH_SIZE,1, 0, data_dir='./data/',mask_dir='./data_mask/')
   image,mask = daliop(pipe,
            shapes = [(BATCH_SIZE, 322,431, 3),()],
            dtypes =(tf.uint8,tf.int32),device_id=0)

   config = tf.ConfigProto(log_device_placement=True)
   config.gpu_options.allow_growth = True
   config.gpu_options.visible_device_list = "7"
   data=[]
   masks = []
   with tf.Session(config=config) as sess:
        res = sess.run([image, mask])
        data=res
   print (data[0].shape,data[1].shape)
   if data[0].size>0:
       cv2.imwrite("./img_tf.png", data[0][0].astype("uint8"))

#test_pipe()
test_error()

**Comment by JanuszL** [comment]
Hi,
If it worked it mean that it was a bug. DALI doesn't allow you to specify the mask argument as a `mask=self.rng()<0.3`. What you should do it is use the [CoinFlip](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html#nvidia.dali.ops.CoinFlip) random generator:
```
class GPUPipeline(Pipeline):
    def __init__(self, batch_size, num_threads, device_id=0, data_dir='./data/',mask_dir='./data_mask/'):
        super(GPUPipeline, self).__init__(batch_size, num_threads, device_id, seed = 12)
         self.input1 = ops.FileReader(file_root = data_dir, random_shuffle = False, file_list= data_dir  +  '/file_list.txt')
        self.decode = ops.HostDecoder(output_type = types.RGB)
        self.rng = ops.Uniform(range=(0,1.0))
        self.rng2 = ops.CoinFlip(probability=0.3)
        self.rotate = ops.Rotate(device="gpu", angle=45, interp_type = types.INTERP_LINEAR)
        self.cast = ops.Cast(device='gpu', dtype=types.DALIDataType.UINT8)

    def define_graph(self):
        images, label =self.input1()
        images = self.decode(images)
        rng2 = self.rng2()
        aug_images = images.gpu()
        aug_images = self.rotate(aug_images, mask=rng2)
        return aug_images,label.gpu()
```

**Comment by owenustc** [comment]
Hi, @JanuszL , I want  to rotate 15 degrees, not flip operation, include shift and zoom  can be executed with a probability, but no only  flip. How do I to write a shift operation with a fixed probability in dali?

**Comment by owenustc** [comment]
Hi, @JanuszL , Thank you for your example code.  And if I want do shift with random magnitude.  How do I write the code with ops.WarpAffine or other ops of Dali.

**Comment by JanuszL** [comment]
> Hi, @JanuszL , I want to rotate 15 degrees, not flip operation, include shift and zoom can be executed with a probability, but no only flip. How do I to write a shift operation with a fixed probability in dali?

CoinFlip is to return 0 or 1, which does what you want in `self.rng()<0.3` - selects if do given operration with 0.3 probability.


> Hi, @JanuszL , Thank you for your example code. And if I want do shift with random magnitude. How do I write the code with ops.WarpAffine or other ops of Dali.

Currently you can use WarpAffine with the fixed parameters. I can add this to our backlog, but it is hard to tell when it is ready.

**Comment by owenustc** [comment]
Hi, @JanuszL ,
     I want to introduce some zoom operations, which brings  unfixed  size of image. So I can not give a fixed      output shape of pipeline of Dali in tensorflow plugin.  It brings error in function, named model.fit, in keras. How do I do to write a pipeline of dali with unfixed shape of input?

**Comment by JanuszL** [comment]
This should be possible with the ExternalInput and https://github.com/NVIDIA/DALI/pull/1423.

**Comment by mzient** [comment]
Actually, for WarpAffine you don't need #1423 - you can pass the trnasform matrices as regular input and use ExternalSource.
