### ISSUE TITLE
Is there any way to implement Conditional Execution for class/object-based Pipeline?

### ISSUE THREAD

**Issue by linuxsino** [NVIDIA/DALI#4932]
### Describe the question.

In the official documentation, there are three defined methods for Pipeline:

> You can define a DALI Pipeline in the following ways:
> 
> By implementing a function that uses DALI operators inside and decorating it with the [pipeline_def()](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/pipeline.html#nvidia.dali.pipeline_def) decorator.
> 
> By instantiating [Pipeline](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/pipeline.html#nvidia.dali.Pipeline) object directly, building the graph and setting the pipeline outputs with [Pipeline.set_outputs()](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/pipeline.html#nvidia.dali.Pipeline.set_outputs).
> 
> By inheriting from [Pipeline](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/pipeline.html#nvidia.dali.Pipeline) class and overriding [Pipeline.define_graph()](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/pipeline.html#nvidia.dali.Pipeline.define_graph) (this is the legacy way of defining DALI Pipelines).

However, for Conditional Execution, the documentation only provides one implementation method for @pipeline_def().

> To enable the conditionals, we need to pass enable_conditionals flag to the @pipeline_def decorator.

My question is, without rewriting the class/object-based Pipeline to the @pipeline_def() approach, is there a more direct method to help class/object-based Pipeline implement Conditional Execution?

Thanks.

### Check for duplicates

- [x] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by klecki** [comment]
Hi @linuxsino,
it is not possible to use the conditional execution with the class/object-based approach - this is the limitation due to not being able to correctly track operations on state/class members.
If you use the `fn` api and more functional style of programming, the tracing of the pipeline code should be correct.

**Comment by klecki** [comment]
Closing as we do not expect the class/object approach to be supported with conditionals.
