### ISSUE TITLE
dali0.7 error:tensorflow.python.framework.errors_impl.InvalidArgumentError: DALI pipeline output shape at 2 != plugin `shape` argument

### ISSUE THREAD

**Issue by owenustc** [NVIDIA/DALI#494]
Hi, I used dali to rotation with image, mask and label. And I found dali meet a bug when label shape is set in pipeline, the information of error as follow:
/job:localhost/replica:0/task:0/device:GPU:0 -> device: 7, name: Tesla P40, pci bus id: 0000:0f:00.0, compute capability: 6.1
2019-01-30 03:11:29.391419: I tensorflow/core/common_runtime/direct_session.cc:284] Device mapping:
/job:localhost/replica:0/task:0/device:GPU:0 -> device: 7, name: Tesla P40, pci bus id: 0000:0f:00.0, compute capability: 6.1

Dali: (Dali): /job:localhost/replica:0/task:0/device:GPU:0
2019-01-30 03:11:29.392151: I tensorflow/core/common_runtime/placer.cc:886] Dali: (Dali)/job:localhost/replica:0/task:0/device:GPU:0
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: DALI pipeline output shape at 2 != plugin `shape` argument
         [[Node: Dali = Dali[device_id=0, dtypes=[DT_UINT8, DT_UINT8, DT_INT32], num_threads=-1, prefetch_queue_depth=2, serialized_pipeline="\010\001\0...@\000H\014", shapes=[[1,322,431,3], [1,322,431,3], [1]], _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

During handling of the above exception, another exception occurred:
My code as follow:
class GPUPipeline(Pipeline):
    def __init__(self, batch_size, num_threads, device_id=0, data_dir='./data/',mask_dir='./data_mask/'):
        super(GPUPipeline, self).__init__(batch_size, num_threads, device_id, seed = 12)
        self.input1 = ops.FileReader(file_root = data_dir, random_shuffle = False, file_list= data_dir  +  '/file_list.txt')
        self.input2 = ops.FileReader(file_root = mask_dir, random_shuffle = False, file_list= mask_dir  +  '/file_list.txt')
        self.decode = ops.HostDecoder(output_type = types.RGB)
        self.rotate = ops.Rotate(device="gpu", angle=45, interp_type = types.INTERP_LINEAR)
        self.cast = ops.Cast(device='gpu', dtype=types.DALIDataType.UINT8)

    def define_graph(self):
        images, label =self.input1()
        masks, _ = self.input2()
        images = self.decode(images)
        masks = self.decode(masks)
        aug_images = images.gpu()
        aug_masks = masks.gpu()
        aug_images, aug_masks = self.rotate([aug_images,aug_masks])
        return aug_images,aug_masks,label.gpu()

def test_error():
   daliop = dali_tf.DALIIterator()
   pipe = GPUPipeline(BATCH_SIZE,1, 0, data_dir='./data/',mask_dir='./data_mask/')
   image,mask,label = daliop(pipe,
            shapes = [(BATCH_SIZE, 322,431, 3),(BATCH_SIZE, 322,431, 3),(BATCH_SIZE,)],
            dtypes =(tf.uint8,tf.uint8,tf.int32),device_id=0)

   config = tf.ConfigProto(log_device_placement=True)
   config.gpu_options.allow_growth = True
   config.gpu_options.visible_device_list = "7"
   data=[]
   masks = []
   with tf.Session(config=config) as sess:
        res = sess.run([image, mask,label])
        data=res
   print (data[0].shape,data[1].shape)
   if data[0].size>0:
       cv2.imwrite("./img.png", data[0][0].astype("uint8"))
       cv2.imwrite("./mask.png", data[1][0].astype("uint8"))

test_error()

And if I set the shape of label is none, Dali would be work, but this setting can not meet the requirement of model.fit of keras.

**Comment by JanuszL** [comment]
Please use:
```
shapes = [(BATCH_SIZE, 322,431, 3),(BATCH_SIZE, 322,431, 3),(BATCH_SIZE, 1)],
```
You can always also call keras reshape operator at your label tensor output.
I added more verbose debug message in https://github.com/NVIDIA/DALI/pull/495
