### ISSUE TITLE
Positive Value Strided Slice

### ISSUE THREAD

**Issue by 5had3z** [NVIDIA/DALI#4943]
### Is this a new feature, an improvement, or a change to existing functionality?

New Feature

### How would you describe the priority of this feature request

Must have (e.g. DALI adoption is impossible due to lack in functionality).

### Please provide a clear description of problem this feature solves

Striding across data is commonly used. In my instance, I have tensor which describes a state over time, I want to change the sample rate to be lower. This can be achieved by striding along the tensor's time dimension.

data_2hz = data_10hz[:, ::5]

### Feature Description

From an end-user perspective, striding is a common array operation used in data processing. This is a common feature which is missing from the library and could hold back adoption.

### Describe your ideal solution

Implementing stride to the slicing operator.

### Additional context

I have written a simple plugin based off the SliceKernel to stride over a single dimension. This is achieved by manipulating the stride vector argument to the SliceKernelImpl (output dim changes were handled in the Plugin's SetupImpl). This could potentially be extended for n dimensions and intergrated into the general SliceKernel. This obviously doesn't work for negative strides i.e. like reversing a list, but fn.flip() should be able to handle that I think?

```c++

using ConstTensor = dali::ConstSampleView<dali::CPUBackend>;
using Tensor = dali::SampleView<dali::CPUBackend>;

template <typename OutputType, typename InputType, int DimsLeft>
void StrideRecurse(const InputType* input, OutputType* output, const int64_t* inStride, const int64_t* outStride,
    const int64_t* inShape, const int64_t* outShape, std::integral_constant<int, DimsLeft>)
{
    static_assert(DimsLeft > 0, "Dims less than 0");
    if constexpr (DimsLeft > 1)
    {
        for (int64_t inIdx = 0, outIdx = 0; inIdx < *inShape && outIdx < *outShape; inIdx++, outIdx++)
        {
            StrideRecurse(input, output, inStride + 1, outStride + 1, inShape + 1, outShape + 1,
                std::integral_constant<int, DimsLeft - 1>());
            output += *outStride;
            input += *inStride;
        }
    }
    else
    {
        for (int64_t inIdx = 0, outIdx = 0; inIdx < *inShape && outIdx < *outShape;
             inIdx += *inStride, outIdx += *outStride)
        {
            output[outIdx] = static_cast<OutputType>(input[inIdx]);
        }
    }
}

void StrideImpl(ConstTensor in, Tensor out, int64_t dim, int64_t stride) noexcept
{

    const auto& inShape = in.shape();
    const auto nDim = inShape.sample_dim();
    auto inStrides = dali::kernels::GetStrides(inShape);

    const auto& outShape = out.shape();
    auto outStrides = dali::kernels::GetStrides(outShape);

    inStrides[dim] *= stride; // Take larger steps at this level

    // clang-format off
    TYPE_SWITCH(in.type(), dali::type2id, T, SLICE_TYPES, (
        VALUE_SWITCH(nDim, Dims, STRIDE_SUPPORTED_NDIMS, (
            StrideRecurse<T, T, Dims>(in.data<T>(), out.mutable_data<T>(),
                inStrides.data(), outStrides.data(), inShape.data(), outShape.data(),
                std::integral_constant<int, Dims>());
        ), DALI_FAIL(dali::make_string("Unsupported Ndims: ", nDim)));
    ), DALI_FAIL(dali::make_string("Unsupported Type: ", in.type())));
    // clang-format on
}

```

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by 5had3z** [comment]
If you think the above is a reasonable approach, I would be open to implementing.

**Comment by jantonguirao** [comment]
Hi @5had3z. Thank you for your proposal. I think that your approach of multiplying the strides in the kernel will work just fine. We'd be happy to review and assist you on this contribution. Best regards.

**Comment by 5had3z** [comment]
@jantonguirao sounds good, to quickly clarify a few things.

- I presume its all good to keep reverse slice/stride out of scope? I understand it'd be more efficient to fuse stride+flip but that could be done later.
- Should GPU striding be included or a second PR to separate things out?
- Not sure if its on my end, but running clang-format on unchanged files reformats everything, so I'm not sure if I'm applying the defined file correctly or the .clang-format hasn't been used consistently.

Cheers

**Comment by jantonguirao** [comment]
@5had3z 
- I don't quite understand why the reverse strides wouldn't work. If we are reversing, we need to first add the end of the dimension to the start pointer, then the stride can be a negative value. We actually do that in another kernel that does slice/flip/normalize etc in one go. I think we can apply the same principle here. Have you encountered any other issues?
- Ideally both of them, but we can start with CPU to simplify the process.
- About auto-formatting, you are right, we didn't apply clang-format consistently on the code-base and we do not want to touch unrelated files when doing a PR. We accept code as long as it passes the linter `make lint`. So you can use that to know if your formatting is OK.

**Comment by 5had3z** [comment]
@jantonguirao Yes reverse striding like that is fine, I was just being a bit slack as I was thinking about logic required to handle the start and end anchor cases i.e. t[-2::-1], t[-2:1:-2], t[4:1:-2] etc. I frequently have to sanity-check I'm doing the right thing when I write nnegative stride slices, let alone implement them. Either way I'll fuzz test parity between this and numpy to ensure I've done the right thing.

**Comment by jantonguirao** [comment]
The negative anchors are translated to the negative counterpart early, as far as I know. The SliceKernel doesn't deal with negative anchors, if I remember correctly. The operator that takes care of numpy-like indexing is TensorSubscript. As you can see in the snippet below, `lo` and `hi` are corrected so that they are always positive. So the slice kernel itself will not see the negative anchor. What we need to do is make sure that negative strides are handled properly in the SliceKernel, and also remove the check about `step == 1`. 
``` 
        int64_t in_extent = in_shape.tensor_shape_span(i)[d];
        int64_t lo = s.lo.IsDefined() ? s.lo.values[i] : 0;
        int64_t hi = s.hi.IsDefined() ? s.hi.values[i] : in_extent;
        int64_t step = s.step.IsDefined() ? s.step.values[i] : 1;
        // TODO(michalz) Remove when strides are supported
        DALI_ENFORCE(step == 1, "Indexing with non-unit step is not implemented");
        if (lo < 0) lo += in_extent;
        if (hi < 0) hi += in_extent;
        lo = clamp(lo, 0_i64, in_extent);
        hi = clamp(hi, 0_i64, in_extent);
        start_.tensor_shape_span(i)[d] = lo;
        step_.tensor_shape_span(i)[d] = step;
        ```
        
You can write your new testcases in `test_subscript.py`.
