### ISSUE TITLE
Dali Type Hints

### ISSUE THREAD

**Issue by mattangus** [NVIDIA/DALI#4979]
### Is this a new feature, an improvement, or a change to existing functionality?

New Feature

### How would you describe the priority of this feature request

Should have (e.g. Adoption is possible, but the performance shortcomings make the solution inferior).

### Please provide a clear description of problem this feature solves

creating pipelines with dali as a new user is very slow. The documentation is good, but IntelliSense is the most effective way to increase productivity. 

### Feature Description

As a developer, I want to have my IDE (vscode, PyCharm, etc.) to have tab completion when working with dali, so that I do not need to rely on interactive methods (python terminal, IPython, etc.) or the documentation when building dali pipelines. This would greatly increase my productivity.

### Describe your ideal solution

It seems that a lot of code and modules are generated dynamically, so providing generated stubs (`.pyi` files) is probably the only solution.

### Describe any alternatives you have considered

I have tried to generate stubs with mypy's `stubgen` but it does not look at dynamic behaviour.

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by klecki** [comment]
Hi @mattangus,

DALI 1.32, which will soon be released, will introduce baseline support for the Python signatures for operator modules: `nvidia.dali.fn` and `nvidia.dali.ops` and some others (like `nvidia.dali.math` and the Pipeline decorator).

DALI 1.33 (to be released in about a month) will extend the coverage by introducing type hints for the tensor classes, adding the runtime `__signature__` (now the proper signature can be seen in Jupyter Notebook for example) and adding overloads that handle some additional API features (like passing constant tensors as inputs to operators).
There will be annotations for JAX and PyTorch DALI plugins.

Most of those features should be available in the next nightly and weekly releases, there are last few changes waiting to be merged: https://github.com/NVIDIA/DALI/pulls?q=label:signatures++is:pr

I tested those features with VSCode, PyCharm (they have slight differences when it comes how to present overloads and aliases), and Jupyter Notebook. 
I would appreciate any feedback, if you find any issues or have some suggestions, don't hesitate to write here :)

**Comment by klecki** [comment]
[DALI 1.33](https://github.com/NVIDIA/DALI/releases/tag/v1.33.0) was just released bringing further updates to type hints and annotations (coverage for JaX and PyTorch data iterators, data types (Tensor and TensorList), Python function operators and overloads that handle additional API features - like the already mentioned passing of constants as parameters to operators) with some minor fixes as well.

**Comment by mattangus** [comment]
Sorry I forgot to reply. This is exactly what I wanted thanks!
