### ISSUE TITLE
Trying to speed up dino with DALI: error: TypeError: __init__() got an unexpected keyword argument 'device'

### ISSUE THREAD

**Issue by krishnaadithya** [NVIDIA/DALI#4980]
@pipeline_def(enable_conditionals=True)
def create_dali_pipeline(data_dir, crop, size, shard_id, num_shards, dali_cpu=False, is_training=True,global_crops_scale=(0.4, 1.), local_crops_scale=(0.05, 0.4), local_crops_number=8):
    images, labels = fn.readers.file(file_root=data_dir,
                                     shard_id=shard_id,
                                     num_shards=num_shards,
                                     random_shuffle=is_training,
                                     pad_last_batch=True,
                                     name="Reader")
    dali_device = 'cpu' if dali_cpu else 'gpu'
    decoder_device = 'cpu' if dali_cpu else 'mixed'
  
    mirror = ops.random.CoinFlip(probability=0.5)

    cmn = ops.CropMirrorNormalize(
            dtype=types.FLOAT,
            output_layout="CHW",
            mean=[0.485 * 255,0.456 * 255,0.406 * 255],
            std=[0.229 * 255,0.224 * 255,0.225 * 255])
    

    def global_augmentations_1(solaris = False):
        augmentations = [
            ops.RandomResizedCrop(
                size=224,
                random_area=global_crops_scale,
                interp_type=types.INTERP_CUBIC,
                device=dali_device,

            ),
            RandomColorJitter(
                brightness=0.4,
                contrast=0.4,
                saturation=0.2,
                hue=0.1,
                prob=0.8,
                device = dali_device,
            ),
            RandomGrayScaleConversion(prob=0.2, device =dali_device),
            RandomGaussianBlur(prob=1, device = dali_device)
        ]
        if solaris == True:
            augmentations.append(RandomSolarize(prob=0.2, device = dali_device))
            
        return augmentations
    
    def global_augmentations_2():
        augmentations = [
            ops.RandomResizedCrop(
                size=224,
                random_area=global_crops_scale,
                interp_type=types.INTERP_CUBIC,
                device=dali_device,
            ),
            RandomColorJitter(
                brightness=0.4,
                contrast=0.4,
                saturation=0.2,
                hue=0.1,
                prob=0.8,
                device = dali_device,
            ),
            RandomGrayScaleConversion(prob=0.2, device = dali_device),
            RandomGaussianBlur(prob=1, device = dali_device),
            RandomSolarize(prob=0.2, device = dali_device),
        ]
        return augmentations

    def get_local_augmentations():
        augmentations = [
            ops.RandomResizedCrop(
                size=96,
                random_area=local_crops_scale,
                interp_type=types.INTERP_CUBIC,
                device=dali_device,
            ),
            RandomColorJitter(
                brightness=0.4,
                contrast=0.4,
                saturation=0.2,
                hue=0.1,
                prob=0.8,
                device = dali_device,
            ),
            RandomGrayScaleConversion(prob=0.2, device=dali_device),
            RandomGaussianBlur(prob=0.5, device=dali_device)
        ]
        return augmentations
    
   
   
    global_crop_1 = images
    for aug in global_augmentations_1():
        global_crop_1 = aug(global_crop_1)
    global_crop_1 = cmn(global_crop_1)

    global_crop_2 = images
    for aug in global_augmentations_1(solaris=True):
        global_crop_1 = aug(global_crop_2)
    global_crop_2 = cmn(global_crop_2)

    local_crops = []
    for _ in range(local_crops_number):
        local_crop = images
        for aug in get_local_augmentations():
            local_crop = aug(local_crop)

       
        local_crop = cmn(local_crops)
        
        local_crops.append(local_crop)
    
    crops = [global_crop_1,global_crop_2, local_crops]
 

    labels = labels.gpu()
    return crops, labels

if args.disable_dali is False:
        train_pipe = create_dali_pipeline(batch_size=args.batch_size_per_gpu,
                                          num_threads=args.num_workers,
                                          device_id=args.local_rank,
                                          seed=12 + args.local_rank,
                                          data_dir=args.data_path,
                                          crop=224,
                                          size =224,
                                          dali_cpu=args.dali_cpu,
                                          shard_id=args.local_rank,
                                          num_shards=args.world_size,
                                          is_training=True,
                                          global_crops_scale = args.global_crops_scale,
                                          local_crops_scale =args.local_crops_scale, 
                                          local_crops_number =args.local_crops_number)
                                          
                                       
        train_pipe.build()
        data_loader = DALIClassificationIterator(train_pipe, reader_name="Reader",
                                                  last_batch_policy=LastBatchPolicy.PARTIAL,
                                                  auto_reset=True)

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @krishnaadithya,

Thank you for reaching out. Could you provide [a self-contained code](https://github.com/NVIDIA/DALI#reporting-problems-asking-questions) we can run on our end?
I'm afraid that the snipped you provided may miss some key parts that prevent from running it.

**Comment by krishnaadithya** [comment]
My apologies attaching the augmentation part here.

[dali_dino.txt](https://github.com/NVIDIA/DALI/files/12283358/dali_dino.txt)

**Comment by JanuszL** [comment]
Hi @krishnaadithya,

Thank you for providing the code. It is really helpful. A couple of remarks:
- we highly recommend using the functional API, the operator's object one is kept mostly for the backward compatibility purpose. If you need to use it please remember to call the operator after its instantiations (please notice `mirror=mirror()`):
```mirror = ops.random.CoinFlip(probability=0.5)

    cmn = ops.CropMirrorNormalize(
            dtype=types.FLOAT,
            output_layout="CHW",
            mean=[0.485 * 255,0.456 * 255,0.406 * 255],
            std=[0.229 * 255,0.224 * 255,0.225 * 255],mirror=mirror())```
- I'm afraid that `RandomColorJitter` definition is missing
- the provided pipeline misses the decoder operation. After loading raw images you need to decode them first.
