### ISSUE TITLE
How to run `fn.decoders.image` on a sequence of images?

### ISSUE THREAD

**Issue by RazHoshia** [NVIDIA/DALI#4982]
### Describe the question.

I'm trying to create a pipeline that gets a tensor of `[4, 32, -1]` (where the last dim (-1) represents the bytes of an encoded jpeg) and returns a `[4, 32, w, h, 3]` (the decoded images in the same format).
The reason to do that is that I combine this pipeline in a triton pipeline, and the next step is a NN that expects the data in this exact format).

Code:
```
class DecodePipeline(Pipeline):
    def __init__(
        self, images_data, batch_size=64, num_threads=4, device_id=0
    ):
        image_batch_size = 32
        num_views = 4
        super(DecodePipeline, self).__init__(
            batch_size=batch_size, num_threads=num_threads, device_id=device_id
        )
        self.images_data = images_data

    def define_graph(self):
        with self:
            images = fn.external_source(source=self.images_data)
            decoded_images = dali.fn.decoders.image(
                images, device="mixed", output_type=dali.types.RGB
            )
            return decoded_images
```

When running this pipeline, I'm getting only one [w, h, 3] tensor as output (`decoded_images`).
I tried the method described here (https://github.com/NVIDIA/DALI/issues/3691) but with no success.

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by awolant** [comment]
Hello @RazHoshia, thanks for the question.
Could you tell in more detail what exactly do you put into `images_data` ? Maybe you could prepare self contained example using data from [DALI_extra](https://github.com/NVIDIA/DALI_extra)? 
This would make it much easier for us to provide a good and useful answer. Thanks!

**Comment by RazHoshia** [comment]
Hi @awolant, thanks so much for the quick response!
`images_data` is a tensor of [1, 4, 32, -1] (where the fist dim is batch size and the last dim (-1) represents the bytes of an encoded jpeg) .

Here is an example with `DALI_extra`
```
import nvidia.dali as dali
from nvidia.dali.pipeline import Pipeline
import numpy as np

import os

DALI_EXTRA_PATH = "../DALI_extra/db/coco/images"


class DecodePipeline(Pipeline):
    def __init__(self, images_data, batch_size=64, num_threads=4, device_id=0):
        super(DecodePipeline, self).__init__(
            batch_size=batch_size, num_threads=num_threads, device_id=device_id
        )
        self.images_data = images_data

    def define_graph(self):
        with self:
            images = dali.fn.external_source(source=self.images_data)
            decoded_images = dali.fn.decoders.image(
                images, device="mixed", output_type=dali.types.RGB
            )
            return decoded_images


def pad_array_with_zeros(arr, target_size):
    diff = target_size - len(arr)

    if diff <= 0:
        return arr
    pad_width = ((0, diff),)

    # Pad the array with zeros along the first dimension.
    padded_arr = np.pad(arr, pad_width, mode="constant", constant_values=0)

    return padded_arr


# getting images from the COCO folder
images_files = (
    os.listdir(DALI_EXTRA_PATH) * 2 + os.listdir(DALI_EXTRA_PATH)[:6]
)  # my data is 128 images
raw_images = [
    np.fromfile(f"{DALI_EXTRA_PATH}/{file_path}", dtype=np.uint8)
    for file_path in images_files
]
max_image_len = max([len(image) for image in raw_images])
raw_images = np.array(
    [pad_array_with_zeros(image, max_image_len) for image in raw_images]
)
raw_images = raw_images.reshape((1, 4, 32, max_image_len))

images_data = dali.backend.TensorListCPU([dali.backend.TensorCPU(raw_images)])
# in my use case `images_data` is sent as a triton input as a tensor of shape (1, 4, 32, -1) - first dim represents batch size
pipe = DecodePipeline(images_data)
pipe.build()
output = pipe.run()
print(output)
# output is a tensor of shape (image_w, image_h, 3)
# desired output shape is (4, 32, image_w, image_h, 3)
```

**Comment by awolant** [comment]
Thanks, I think I understand a bit better what you are trying to do. 

Note that with the number of images you have per sample (128) if you were to try to do something similar as in #3691 you would end up with significant memory usage due to [multiple decoders creation](https://github.com/NVIDIA/DALI/issues/3691#issuecomment-1044166675). Plus there might be issues with non uniform image size. In the test above you filled them with 0 but I am not sure how this would look like in real life scenario.

What I would suggest instead is to treat your `images_data` as a data source, use external source to read it in multiple batches (somethig like in [this tutorial](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/external_input.html#External-Source-Operator---basic-usage)) and then assemble the output in whatever shape you want outside DALI pipeline. So something like:


```python
import nvidia.dali as dali
from nvidia.dali.pipeline import pipeline_def
import numpy as np

import os

DALI_EXTRA_PATH = "../DALI_extra/db/coco/images"

class ExternalInputIterator(object):
    def __init__(self, batch_size, images_data):
        self.images_data = images_data
        self.batch_size = batch_size

    def __iter__(self):
        self.i = 0
        self.n = len(self.images_data)
        return self

    def __next__(self):
        batch = []
        for _ in range(self.batch_size):
            batch.append(self.images_data[self.i])
            self.i = (self.i + 1) % self.n
        return batch


images_files = (
    os.listdir(DALI_EXTRA_PATH) * 2 + os.listdir(DALI_EXTRA_PATH)[:6]
)

raw_images = [
    np.fromfile(f"{DALI_EXTRA_PATH}/{file_path}", dtype=np.uint8)
    for file_path in images_files
]

batch_size = 32
eii = ExternalInputIterator(batch_size, raw_images)


@pipeline_def(batch_size=batch_size, num_threads=2, device_id=0)
def dali_pipeline():
    images = dali.fn.external_source(source=eii, dtype=dali.types.UINT8)
    decoded_images = dali.fn.decoders.image(images, device="mixed", output_type=dali.types.RGB)
    
    return decoded_images
    
pipe = dali_pipeline()
pipe.build()

all_outputs = []
for i in range(4):
    all_outputs.append(pipe.run()[0])

# Build output from all_outputs with desired shape in whatever data format your NN requires
```

**Comment by awolant** [comment]
@RazHoshia I assumed that you are using Python backend in Triton. is this correct?

**Comment by RazHoshia** [comment]
Thanks!
I'm using the [dali backend](https://github.com/triton-inference-server/dali_backend)
So Im not sure that I can perform this iteration using Triton and this backend (because it loads a dali pipeline)

**Comment by awolant** [comment]
@szalpal Do you have some ideas about how to do something like this in DALI backend in Triton?

**Comment by szalpal** [comment]
@RazHoshia ,

what is your input data? Are those images or video files?

**Comment by RazHoshia** [comment]
Thanks @szalpal ,
no, the NN input is `[B, 4, 32, image_w, image_h, 3]`
the shape of the input is `[B, 4, 32, -1]` (in the example code i wrote above B=1)

**Comment by szalpal** [comment]
@RazHoshia ,

Do these images have constant shape? I mean, is `image_w` and `image_h` equal throughout processing? If it's not then it will be harder from a Triton perspective (Triton would expect every sample in a batch to have the same shape).

To answer your question, the easiest approach you could take is to combine 3 DALI pipelines together using Triton's [Business logic scripting](https://github.com/triton-inference-server/python_backend/tree/main#business-logic-scripting):

```python
BATCH_SIZE = 1
IMAGE_W = 320
IMAGE_H = 240


@pipeline_def(batch_size=BATCH_SIZE)
def pipe1():
    enc = fn.external_source(name='IN')  # input shape: [4, 32, bytes], padding required
    return fn.reshape(enc, shape=[-1])


@pipeline_def(batch_size=BATCH_SIZE * 4 * 32)
def pipe2():
    enc = fn.external_source(name='IN_FLATTENED')  # input shape: [bytes*4*32]
    return fn.decoders.image(enc)


@pipeline_def(batch_size=BATCH_SIZE * 4 * 32)
def pipe3():
    dec = fn.external_source(name='IN_DECODED_FLATTENED')  # input shape: [IMAGE_H, IMAGE_W, 3]
    split = fn.reshape(dec, shape=[4, 32, IMAGE_H, IMAGE_W, 3])
    return fn.transpose(split, perm=[0, 1, 3, 2, 4]
```
`pipe1` takes the data in the shape you require, i.e. `[4, 32, -1]` and flattens it to just `[-1]`. `pipe2` decodes the images (note, that DALI's decoder outputs images with HWC layout). Lastly, `pipe3` takes the images and break it down into the shape your NN needs. 


On the other hand, if the `image_w` and `image_h` are not constant throughout processing, you'd need to employ Triton's [Ragged batching](https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/user_guide/ragged_batching.html), although it might not suffice all your requirements.

**Comment by RazHoshia** [comment]
Hi @szalpal, thanks for the response.
Yes, image_w and image_w are equal throughout processing (640 X 360)
your solution looks exactly like what I need.
Thanks Again!
