### ISSUE TITLE
How to parse TFRecord file with DALI

### ISSUE THREAD

**Issue by MathiesW** [NVIDIA/DALI#4984]
### Describe the question.

I am using TensorFlow TFRecordDatasets for my ML application. The structure of each TFRecord file in TensorFlow is
```
features = {'x': tf.io.FixedLenFeature([], tf.int64), 'y': tf.io.FixedLenFeature([], tf.int64), 'raw_data': tf.io.FixedLenFeature([], tf.string)}
```

The dictionary contains all information about the structure of my serialized data. In TensorFlow, I can easily decode my TFRecord files with this information (basically reshaping `raw_data` to `x` times `y`).

I attempted to read my TFRecord files with DALI. However, I am not able to figure out how to decode my files with the tools DALI provides. The [TFRecord data loading example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/dataloading_tfrecord.html) reads "encoded" images from a TFRecord file. However, I want to decode my serialized data within the pipeline. To my understanding, all information is available.

My first attempt looks like this and should only return the shape of the tfrecord files without any decoding
```
path_tfrecord = Path('data')
path_index = Path('data/index')

pipe = Pipeline(batch_size=2, num_threads=4, device_id=0)
with pipe:
    inputs = fn.readers.tfrecord(
        path=str(path_tfrecord),
        index_path=str(path_index),
        features={
            'x': tfrec.FixedLenFeature((), tfrec.int64, -1),  # -1 taken from dali example how to load tfrecord
            'y': tfrec.FixedLenFeature((), tfrec.in64, -1),  # same -- the actual shapes are 512x512 though
            'raw_data': tfrec.FixedLenFeature([], tfrec.string, ""),
        }
    )

    pipe.set_outputs(inputs['x'], inputs['y'])  # just return shapes to test pipeline

pipe.build()
pipe_out = pipe.run()
```
The script raises
```
RuntimeError: Critical error when building pipeline:
Error when constructing operator: readers___TFRecord encountered:
[/opt/dali/dali/operators/reader/loader/indexed_file_loader.h:207] Assert on "!indices_.empty()" failed: Content of index files should not be empty
```
However, I generated the index files using the script that shipped with DALI. Each `*.idx` file contains 500 lines, which exactly matches the number of samples per TFRecord file. The `*.idx` files have the same name as the `*.tfrecord` files, so assignment shouldn't be a problem, either. Moreover, all TFRecord files share the exact same structure. What am I doing wrong here?

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @MathiesW,

Thank you for reaching out.
`path` and `index_path` receives a file/list of files, not paths to the directory with them.
To reshape the data please use [the `reshape` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.reshape.html#nvidia.dali.fn.reshape) (you may need to join/stack x and y dimensions into one tensor and then provide them to the reshape operator).

**Comment by MathiesW** [comment]
Hi @JanuszL 
thank you, this fixed my problem! Stupid mistake :-)

**Comment by JanuszL** [comment]
I'm glad it works now.
Please let us know in case of any more questions.
