### ISSUE TITLE
Triton Server cannot see the underlying GPU and fallsback to use CPU

### ISSUE THREAD

**Issue by cherrymu** [NVIDIA/DALI#4986]
### Describe the question.

Hello, I am trying to deploy my DALI model using Triton Server v23.07-py3 on kubernetes using the Statefulset and I am seeing below stacktrace eventhough I am running my Triton server on a GPU node

`Assert on "device != "gpu" || device_id_ != CPU_ONLY_DEVICE_ID" failed: Cannot add a GPU operator ExternalSource, device_id should not be equal CPU_ONLY_DEVICE_ID`

Do we need to enable any flag from triton from my k8s deployment to make it see the underlying GPU? 

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by awolant** [comment]
Hello, 
thanks for the question. It looks like you there are some issues with the `device_id`. Have you set it correctly? Can you share the code of your pipeline and setup? That would help us to give a more concrete and useful answer.

**Comment by szalpal** [comment]
@cherrymu ,

To add to what @awolant wrote, the error message you've pasted suggests that you're using an `fn.external_source(device='gpu')` operator inside DALI pipeline, but DALI thinks that your pipeline is CPU-only. This probably happens, because the `device_id` in the `@pipeline_def` is set to `None`.

**Comment by cherrymu** [comment]
Hello @awolant @szalpal, thanks for the reply and the help. I have set the `device_id` to 0 and `device='gpu' `. The confusion for me here is even before I use/load my DALI model the triton server pod doesn't see the underneath GPU as I can see the below log traces from triton pod which suggests that it is using CPU rather than GPU 

~~~~
I0808 15:38:15.198577 1 shared_library.cc:112] OpenLibraryHandle: /opt/tritonserver/backends/pytorch/libtriton_pytorch.so
WARNING: [Torch-TensorRT] - Unable to read CUDA capable devices. Return status: 35  -------------------------------------------> Looks like major error not able to read CUDA 
I0808 15:38:15.757884 1 libtorch.cc:2507] TRITONBACKEND_Initialize: pytorch
I0808 15:38:15.757906 1 libtorch.cc:2517] Triton TRITONBACKEND API version: 1.13
I0808 15:38:15.757910 1 libtorch.cc:2523] 'pytorch' TRITONBACKEND API version: 1.13
I0808 15:38:15.757924 1 cache_manager.cc:480] Create CacheManager with cache_dir: '/opt/tritonserver/caches'
W0808 15:38:15.757951 1 pinned_memory_manager.cc:237] Unable to allocate pinned system memory, pinned memory pool will not be available: CUDA driver version is insufficient for CUDA runtime version
I0808 15:38:15.757977 1 cuda_memory_manager.cc:117] CUDA memory pool disabled
~~~~

This only happens when I use Triton Server Image v23.07-py3 and If I use Triton Server Image v21.07-py3 it is able to see the GPU underneath which I can confirm from below logs for triton image v21.07 

~~~~
I0807 14:37:19.715135 1 metrics.cc:290] Collecting metrics for GPU 0: Tesla T4
I0807 14:37:19.719779 1 shared_library.cc:108] OpenLibraryHandle: /opt/tritonserver/backends/pytorch/libtriton_pytorch.so
I0807 14:37:20.586297 1 libtorch.cc:998] TRITONBACKEND_Initialize: pytorch
I0807 14:37:20.586340 1 libtorch.cc:1008] Triton TRITONBACKEND API version: 1.4
I0807 14:37:20.586345 1 libtorch.cc:1014] 'pytorch' TRITONBACKEND API version: 1.4
I0807 14:37:21.620235 1 pinned_memory_manager.cc:240] Pinned memory pool is created at '0x7fab5c000000' with size 268435456
I0807 14:37:21.622371 1 cuda_memory_manager.cc:105] CUDA memory pool is created on device 0 with size 67108864
~~~~ 

But unfortunately I cannot use Triton v21.07 due to restrictions on my end. So the confusion here is why and how the two image versions differs as lower version can see the GPU and the higer version (23.07) cannot.

**Comment by JanuszL** [comment]
Hi @cherrymu,

The problem you see may be related to the GPU driver version you have and the CUDA the TRITON was built with. 23.07 was created with 12.1 (see full matrix [here](https://docs.nvidia.com/deeplearning/triton-inference-server/release-notes/rel-23-07.html)). So please check if the driver you have supports CUDA 12.1 and update if needed.

**Comment by cherrymu** [comment]
Hello @JanuszL, thanks for the response. I will dig deep into this and will open a new issue if needed. Closing this now, thanks everyone for the quick help with pointers!
