### ISSUE TITLE
Currently, does Dali have a transmission transformation function corresponding to cv2. warpPerspective

### ISSUE THREAD

**Issue by Fightinging1997** [NVIDIA/DALI#5000]
### Describe the question.

Currently, does Dali have a transmission transformation function corresponding to cv2. warpPerspective

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by awolant** [comment]
Hello @Fightinging1997 
thanks for the question. Is there any reason why [DALI warp operation](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/image_processing/warp.html) is not enough for you in your use case?

**Comment by JanuszL** [comment]
Hi @Fightinging1997,

Thank you for reaching out. DALI does support [warp affine operation](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.warp_affine.html), and [generic remap](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.experimental.remap.html) that can be used for the transformation you are asking for.
The warp perspective operation is still on our ToDo list.
