### ISSUE TITLE
fast_resize_crop_mirror Assert on "crop_x >= 0" failed 

### ISSUE THREAD

**Issue by butorine** [NVIDIA/DALI#5001]
### Version

1.29.0dev

### Describe the bug.

`fast_resize_crop_mirror` doesn't seem to be able to crop after resizing with original aspect ratio.

Example below throws
`Error in thread 0: [/dali/dali/operators/image/resize/resize_crop_mirror.h:246] [/dali/dali/image/transform.cc:102]: Assert on "crop_x >= 0" failed`

### Minimum reproducible example

```shell
def pipe():
    images = dali.fn.external_source(name="input")
    images = dali.fn.fast_resize_crop_mirror(
        images,
        resize_longer=224,
        interp_type=types.DALIInterpType.INTERP_LINEAR,
        crop=(224, 224),
        out_of_bounds_policy="pad",
        fill_values=0,
        dtype=types.FLOAT,
    )

    return images
```
```


### Relevant log output

```shell
File "/usr/local/lib/python3.8/dist-packages/nvidia/dali/pipeline.py", line 1113, in run
    return self.outputs()
  File "/usr/local/lib/python3.8/dist-packages/nvidia/dali/pipeline.py", line 956, in outputs
    return self._outputs()
  File "/usr/local/lib/python3.8/dist-packages/nvidia/dali/pipeline.py", line 1040, in _outputs
    return self._pipe.Outputs()
RuntimeError: Critical error in pipeline:
Error when executing CPU operator FastResizeCropMirror encountered:
Error in thread 0: [/dali/dali/operators/image/resize/resize_crop_mirror.h:246] [/dali/dali/image/transform.cc:102]: Assert on "crop_x >= 0" failed
Current pipeline object is no longer valid.
```
```


### Other/Misc.

_No response_

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by butorine** [comment]
Just to add to the above, function works as expected when image is resized without the original aspect ratio:
```
def pipe_three():
    images = dali.fn.external_source(name="input")
    images = dali.fn.fast_resize_crop_mirror(
        images,
        resize_x=224,
        resize_y=224,
        interp_type=types.DALIInterpType.INTERP_LINEAR,
        crop=(224, 224),
        out_of_bounds_policy="pad",
        fill_values=0,
        dtype=types.FLOAT,
    )
```

**Comment by mzient** [comment]
Please do not use `fast_resize_crop_mirror`. It's an obsolete CPU-only operator and, honestly, I'm quite surprised it isn't marked as deprecated. Many of the parameters that you specified are ignored (among these `out_of_bounds_policy` and `fill_values`).

There's no operator in DALI that can resize an out-of-bounds crop with constant padding - that has to be done in 2 stages (first crop, then resize).

`random_resized_crop` can get you random crops with aspect ration constraints, but it will never provide an out-of-bounds crop nor will it flip the image (it's technically doable, we just haven't implemented it yet).
Finally, you can just use `resize` and provide it with a cropping window (`roi_start`, `roi_end`). Resize will flip the image either if size is negative or when roi_start > roi_end.

**Comment by butorine** [comment]
Thank you for clarifying.  I wasn't aware this is obsolete and it's still part of documentation.
