### ISSUE TITLE
if batch_size=16 (fn.warp_affine(images, m, size=(320, 512), fill_value=114))  how will m correspond?

### ISSUE THREAD

**Issue by Fightinging1997** [NVIDIA/DALI#5005]
### Describe the question.

I hope m is also a batch dimension, corresponding to the image

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @Fightinging1997,

Thank you for reaching out.
Yes, you can define the transformation for each image separately either [manually via the external source](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/image_processing/warp.html) or use [transforms family to generate them](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/math/geometric_transforms.html).
You can find more examples at the bottom of [the operator description page](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.warp_affine.html).

**Comment by Fightinging1997** [comment]
fn.warp_affine(images, m, size=(320, 512), fill_value=114)  and cv2.warpPerspective(img,
                                      warp_matrix,
                                      dsize=(width, height),
                                      borderValue=self.border_val)
m and warp_matrix are the same, but the results are completely different.
cv2:
![image](https://github.com/NVIDIA/DALI/assets/66704794/431058fd-0753-4c54-8437-c8dcbae22504)
fn:
![image](https://github.com/NVIDIA/DALI/assets/66704794/7626f2b6-a41b-4087-8217-26e18ca4aef7)

Since the image involves multiple transforms and multiple labels, I can't use the api for keypoint conversion directly, and it's hard for me to know how this affine transform changes the keypoint

**Comment by Fightinging1997** [comment]
![image](https://github.com/NVIDIA/DALI/assets/66704794/97d7e31f-0532-434f-b192-de980e98dd63)
![image](https://github.com/NVIDIA/DALI/assets/66704794/9dac1626-fa1b-4413-a32d-de4132e05c8c)
I read the official website documentation that the two implementation methods are the same, but there are significant differences

**Comment by Fightinging1997** [comment]
I found that the initial question has not been answered yet. Can you help me write an m with a batch of 16, which contains different affine transformation parameters.
At present, I can only achieve affine transformation of single batch corresponding to multiple batch images.

**Comment by mzient** [comment]
@Fightinging1997 
The difference between OpenCV and DALI is that DALI uses destination-to-source mapping - or "inverse_map" in OpenCV terminology. You can switch the behavior by specifying `inverse_map=False`.

**Comment by JanuszL** [comment]
> Can you help me write an m with a batch of 16, which contains different affine transformation parameters.

You should either add one more dimension to the matrix you provide or use an external source operator like in the mentioned [example.](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/image_processing/warp.html).

**Comment by mzient** [comment]
@Fightinging1997 
DALI doesn't have per-sample constants. If you want each sample to get a different transform, you need to provide the matrix as an input or construct it with `fn.transforms`, as shown in the example (which shows how to transform keypoints along with images).
https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/math/geometric_transforms.html

**Comment by Fightinging1997** [comment]
Thank you for answering my question.

Python:
batch_size = 16
import time
start = time.time()

images_dir = "SurroundOD_GH04_20230717/images"

class T:
    @pipeline_def(num_threads=8, device_id=0)
    def get_dali_pipeline(self, ):
        images, _ = fn.readers.file(
            file_root=images_dir, random_shuffle=False, name="Reader")
        # decode data on the GPU
        images = fn.decoders.image(
            images, device="mixed", output_type=types.BGR)
   
        images = fn.resize(images, resize_x=512, resize_y=320, interp_type=types.DALIInterpType.INTERP_LINEAR, antialias=False)

        m = np.array([[ 8.0084014e-01, -3.4328498e-02, -2.1650146e+01],
        [ 1.3179968e-02,  8.0156708e-01,  2.8909576e+01]],dtype=np.float32)
        
        # method1
        m = [m for _ in range(batch_size)]
        # method2
        # m = np.tile(m, (batch_size, 1, 1))

        m = fn.external_source(source=m)
        images = fn.warp_affine(images, m, size=(320, 512), fill_value=114, inverse_map=False)
        
        return images

    def run(self):
        train_data = DALIGenericIterator(
            [self.get_dali_pipeline(batch_size=batch_size)],
            ['data'],
            reader_name='Reader'
        )

        for i, data in enumerate(train_data):
            x = data[0]['data']
        print(time.time()-start)
        print(i*batch_size)
        
t = T()
t.run()

I packaged batch matrices using the external_source method as you mentioned, but an error will be reported. I hope you can help me check the issue:

RuntimeError: Critical error in pipeline:
Error when executing CPU operator readers__File encountered:
[/opt/dali/dali/pipeline/operator/operator.cc:66] Assert on "ref_batch_size == output_batch_size" failed: Batch size has to be uniform across one iteration. Expected: 2; Actual: 16

**Comment by mzient** [comment]
@Fightinging1997 
Almost there :) External source is meant to act as a dataset - therefore, the `source` should be a collection of batches (if operated in batch mode, which is the default).
To fix the problem you can do either:
```Python
m = fn.external_source(source=[m])   # note the extra array around m
```
or
```Python
m = fn.external_source(source=m, batch=False)
```

**Comment by Fightinging1997** [comment]
The problem has been solved, thank you very much

**Comment by Fightinging1997** [comment]
> Thank you for answering my question.
> 
> Python:
> 
> ```
> batch_size = 16
> import time
> start = time.time()
> 
> images_dir = "SurroundOD_GH04_20230717/images"
> 
> class T:
>     @pipeline_def(num_threads=8, device_id=0)
>     def get_dali_pipeline(self, ):
>         images, _ = fn.readers.file(
>             file_root=images_dir, random_shuffle=False, name="Reader")
>         # decode data on the GPU
>         images = fn.decoders.image(
>             images, device="mixed", output_type=types.BGR)
>    
>         images = fn.resize(images, resize_x=512, resize_y=320, interp_type=types.DALIInterpType.INTERP_LINEAR, antialias=False)
> 
>         m = np.array([[ 8.0084014e-01, -3.4328498e-02, -2.1650146e+01],
>         [ 1.3179968e-02,  8.0156708e-01,  2.8909576e+01]],dtype=np.float32)
>         
>         # method1
>         m = [m for _ in range(batch_size)]
>         # method2
>         # m = np.tile(m, (batch_size, 1, 1))
> 
>         m = fn.external_source(source=[m])
>         images = fn.warp_affine(images, m, size=(320, 512), fill_value=114, inverse_map=False)
>         
>         return images
> 
>     def run(self):
>         train_data = DALIGenericIterator(
>             [self.get_dali_pipeline(batch_size=batch_size)],
>             ['data'],
>             reader_name='Reader'
>         )
> 
>         for i, data in enumerate(train_data):
>             x = data[0]['data']
>         print(time.time()-start)
>         print(i*batch_size)
>         
> t = T()
> t.run()
> ```
> 
> I packaged batch matrices using the external_source method as you mentioned, but an error will be reported. I hope you can help me check the issue:
> 
> RuntimeError: Critical error in pipeline: Error when executing CPU operator readers__File encountered: [/opt/dali/dali/pipeline/operator/operator.cc:66] Assert on "ref_batch_size == output_batch_size" failed: Batch size has to be uniform across one iteration. Expected: 2; Actual: 16


I found that if it is changed to [m], it can only be traversed once, but in fact, there are many images

**Comment by Fightinging1997** [comment]
example:
```
flip_mask = [random.choice([1, 0]) for _ in range(batch_size)]
flip_mask = fn.external_source(source=flip_mask, batch=False, cycle=True)
images = fn.flip(images, horizontal=flip_mask)
```

Error:
AttributeError: 'int' object has no attribute 'shape'


The idea is simple, either flip horizontally or not

**Comment by JanuszL** [comment]
Hi @Fightinging1997,

How about:
```
should_flip = fn.random.coin_flip(probability=1.0)  # 100% probability for demo purposes
images = fn.flip(images, horizontal=should_flip)
```?

**Comment by Fightinging1997** [comment]
Thank you very much. I just tried this method and it's feasible

**Comment by mzient** [comment]
@Fightinging1997 You can use `fn.scale` to flip, but you need to know the image size so you can provide the center.
```Python
scales = fn.uniform(values=[-1,1], shape=[2])
m = fn.scale(m, scales=scales, center=image_size_wh / 2)
```
If your image size is constant, that's trivial. If it varies, but you have an encoded image, you can peek its shape, like in the [example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/math/geometric_transforms.html#Adding-Transforms-to-the-Pipeline) (cell [8]):
```Python
def encoded_images_sizes(encoded_images):
    shapes = fn.peek_image_shape(encoded_images)  # the shapes are HWC
    h, w = shapes[0], shapes[1]          # extract H and W ...
    return fn.stack(w, h)                # ...and concatenate


image_size_wh = encoded_image_sizes(encoded images)

scales = fn.uniform(values=[-1,1], shape=[2])
m = fn.scale(m, scales=scales, center=image_size_wh / 2)
```
