### ISSUE TITLE
GCC-13 Toolchain

### ISSUE THREAD

**Issue by 5had3z** [NVIDIA/DALI#5021]
### Describe the question.

Moving to GCC-13 enables the usage of many new C++20 and 23 library features such as more constexpr things, ranges and multithreadding primitives (std::binary_semaphore etc).

I'm able to compile DALI [myself](https://github.com/5had3z/DALI/tree/refactor/cpp23) with gcc-13 and bump C/C++ to 23 and NVCC to 20. The summary of changes include removing more unneccesary template definitions (like #4928), fix some language deprications (std::aligned_storage and std::is_pod), implicit lambda this, #include missing depending on ordering, enum changes and an unnessary ctor() = default; which prevented impicit trivial intializer list.

Of course build + run on my machine works, but I have no idea how "portable" this change is, I don't have experience building wheels and always get caught out by glibc versions between machines myself.

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @5had3z,

Thank you for running experiments with upgrading to the latest available compiler and C++ version.
According to the latest [release notes for CUDA](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#host-compiler-support-polic, the official support for gcc is `6.x - 12.2
`, and C++ `C++11, C++14, C++17, C++20`.
However, the CUDA 11.8 we use to create CUDA 11.x family builds [has even more limitations](https://docs.nvidia.com/cuda/archive/11.8.0/cuda-installation-guide-linux/index.html#system-requirements).
While we encourage hacking DALI and improving it even more, we cannot move that far when it comes to C++ dialect support due to the configuration matrix we support.

**Comment by 5had3z** [comment]
GCC 11 which is supported by CUDA 11.x as host compiler (and is the default compiler for Ubuntu 22.04) supports C++23 as a feature, but doesn't implement most of it. However it does cover most of C++20 which would still be potentially beneficial (the changes I mentioned to could still stand, even if some apply to the C++23 update).

I guess its interesting that I didn't have to add '--allow-unsupported-compiler' anywhere. I thought that if we could take two steps (C++17 -> C++23) without issues coming up that might as well do so.

**Comment by JanuszL** [comment]
Manylinux2014 we use has gcc 10.2.1. So until we move to a more recent version ([manylinux_2_28](https://github.com/pypa/manylinux)) making sure that the majority of the users' systems are ready for it we are limited by it.

**Comment by 5had3z** [comment]
I guess need to wait around for RHEL/Centos 7 to reach EOL next year? Seems to be the main platform holding migration back.

**Comment by JanuszL** [comment]
> I guess need to wait around for RHEL/Centos 7 to reach EOL next year? Seems to be the main platform holding migration back.

Not exactly. The next maylinux variant is 2.28 - which corresponds to the earliest GLIBC version supported by it. Ubuntu 18.04 is shipped with 2.27, 18.10 with 2.28. Also, CUDA still supported the old GLIBX and we plan to be aligned with the CUDA support matrix.

**Comment by JanuszL** [comment]
You can also check [this nice page](https://mayeut.github.io/manylinux-timeline/) to see what the Python ecosystem looks like now.

**Comment by 5had3z** [comment]
Do you plan to support Ubuntu 18.04 outside EOL because CUDA 11 supports it? I guess if you support the latest two major versions then won't be updating toolchain until late 2024/5, which is when I would expect CUDA 13 with Ada/Hopper Next (Blackwell).

GCC 10 has a significant portion of C++20, but I would concur with not bothering to upgrade until manylinux_2_28 is adopted which has GCC 12 unless there are desired features such as ranges, span or jthreads etc.
