### ISSUE TITLE
working in cpu only mode

### ISSUE THREAD

**Issue by yuewu001** [NVIDIA/DALI#504]
is there any plan to make DALI work in CPU only mode? This is quite useful for programming on local devices.

**Comment by JanuszL** [comment]
Hi,
DALI was designed to accelerate processing utilizing GPU, with ability to fallback to the CPU when needed. Still it assumes that GPU is present even if the processing is done purely on the CPU. For all our use cases this assumption is valid.
Technically I don't see any obstacle from striping this GPU dependency, but we cannot commit to do that in the near future and this could be a good case for external contribution.
Added to our ToDo list - DALI-514.

**Comment by JanuszL** [comment]
Hi,
This https://github.com/NVIDIA/DALI/pull/2165 should address your request.

**Comment by JanuszL** [comment]
DALI 0.26 is available and should include the needed functionality.
