### ISSUE TITLE
Step number DALIGenericIterator/fn.readers.video

### ISSUE THREAD

**Issue by zankerx** [NVIDIA/DALI#5040]
### Version

1.24.0

### Describe the bug.

Hello, 

There is something I don't understand with DALIGenericIterator/fn.readers.video. I have a dataset with 256 videos, a batch size of 64. I want to extract 128 consecutive frames randomly from each video.

Normally the DALIGenericIterator should do 4 steps (256/64 = 4), however it does 14. Can a video produce multiple examples?

Thank you in advance for your answer :)

### Minimum reproducible example

```shell
import os
import torch
import numpy as np
import pandas as pd

from nvidia.dali import pipeline_def
import nvidia.dali.fn as fn
from nvidia.dali.plugin.pytorch import DALIGenericIterator

from time import time


n_frames = 128
bs = 64
n_videos = 256

path = '/gpfsdswork/dataset/WebVid/2M'
config_path = 'results_2M_train.csv'

config = pd.read_csv(os.path.join(path, config_path))

videos_paths = [os.path.join(path, v) for v in config['path'].values[:n_videos]]



print('N sample = {}'.format(n_videos))
print('expected steps : {}'.format(n_videos//bs))






@pipeline_def
def video_pipe(filenames, n_frames, size = 224):
        
    videos = fn.readers.video(device="gpu", lazy_init = True, dont_use_mmap = False, filenames=filenames, sequence_length=n_frames, random_shuffle=True, name='Reader')
    #experimental
    videos = fn.random_resized_crop(videos, size = [size, size], device='gpu')
        
        
    return videos
    
s = time()
pipe = video_pipe(videos_paths, n_frames, num_threads = 10, batch_size=bs, device_id=0)
pipe.build()
e = time()

print('Pipe build : {}'.format(e - s))

s = time()
dali_iter = DALIGenericIterator(pipe, ['data'], reader_name='Reader')
e = time()

print('iter build : {}'.format(e - s))


ts = time()

s = time()
for idx,dt in enumerate(dali_iter):
    
    e = time()

    dt = dt[0]['data']

    print('idx : {} loading time : {} | shape : {} | device : {}'.format(idx, e - s, dt.size(), dt.device))

    s = time()


te = time()

print('N steps : {}'.format(idx + 1))
print('Total time : {}'.format(te - ts))
```

### Relevant log output

```shell
N sample = 256
expected steps : 4
Pipe build : 0.16391968727111816
iter build : 15.072671175003052
idx : 0 loading time : 5.245208740234375e-06 | shape : torch.Size([64, 128, 224, 224, 3]) | device : cuda:0
idx : 1 loading time : 2.2564697265625 | shape : torch.Size([64, 128, 224, 224, 3]) | device : cuda:0
idx : 2 loading time : 2.768298864364624 | shape : torch.Size([64, 128, 224, 224, 3]) | device : cuda:0
idx : 3 loading time : 2.624046802520752 | shape : torch.Size([64, 128, 224, 224, 3]) | device : cuda:0
idx : 4 loading time : 2.651775598526001 | shape : torch.Size([64, 128, 224, 224, 3]) | device : cuda:0
idx : 5 loading time : 2.4055840969085693 | shape : torch.Size([64, 128, 224, 224, 3]) | device : cuda:0
idx : 6 loading time : 2.555784225463867 | shape : torch.Size([64, 128, 224, 224, 3]) | device : cuda:0
idx : 7 loading time : 2.5829713344573975 | shape : torch.Size([64, 128, 224, 224, 3]) | device : cuda:0
idx : 8 loading time : 2.6457204818725586 | shape : torch.Size([64, 128, 224, 224, 3]) | device : cuda:0
idx : 9 loading time : 2.8066654205322266 | shape : torch.Size([64, 128, 224, 224, 3]) | device : cuda:0
idx : 10 loading time : 2.631466865539551 | shape : torch.Size([64, 128, 224, 224, 3]) | device : cuda:0
idx : 11 loading time : 2.5567355155944824 | shape : torch.Size([64, 128, 224, 224, 3]) | device : cuda:0
idx : 12 loading time : 2.6740100383758545 | shape : torch.Size([64, 128, 224, 224, 3]) | device : cuda:0
idx : 13 loading time : 2.682931661605835 | shape : torch.Size([64, 128, 224, 224, 3]) | device : cuda:0
N steps : 14
Total time : 33.84318685531616
```

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @zankerx,

Thank you for reaching out.
In your case, the number of samples in the data set is the number of 128 frame sequences that can be extracted from the 256 provided videos. With the default value of the `step` parameter, sequences are adjacent and don't overlap. The number of batches the iterator returns is the `number of sequences in the dataset` / `batch size`.
If you just want to randomly pick one 128-frame sequence from each video, you can craft a `file_list` with randomly selected sequences ahead of time, and the number of entries corresponding to the number of samples you want to obtain through the training. However in this case you will deal with one long epoch and you need to manually split it into real epochs.

**Comment by zankerx** [comment]
Thx @JanuszL :)

Just another question, why is the iterator initialization taking so long? 15s with 256 videos. I tried with 70k video and after 20min the iterator is still not initialized.

 My configuration : 
10 Cascade Lake 6248 2.5GHz cores
 48GB ram
1 NVIDIA V100 SXM2 32GB GPU

**Comment by zankerx** [comment]
Thx @JanuszL :)

Just another question, why is the iterator initialization taking so long? 15s with 256 videos. I tried with 70k video and after 20min the iterator is still not initialized.

My configuration :
10 Cascade Lake 6248 2.5GHz cores
48GB ram
1 NVIDIA V100 SXM2 32GB GPU

**Comment by JanuszL** [comment]
Hi @zankerx,

Is this a publicly available dataset we can use to reproduce your problem? I think that most of the initialization time is up to the parsing of the video stream to discover the number of available frames. However, I don't expect it to take that much, so with a repro we can run we can narrow down the problem.

**Comment by zankerx** [comment]
Hi @JanuszL,

Im using the 2.5M subset from WebVid-10M ([https://github.com/m-bain/webvid]). The code is the same, I just changed the number of video to use (n_videos = 50000).

The problem seems to come from video parsing. When I try `pipe.epoch_size('Reader')` before initializing the iterator, it's this step that takes time. In this case the iterator is initialized very quickly.

Maybe slow reading of data ?

**Comment by JanuszL** [comment]
I think we can remove a redundant call, like https://github.com/NVIDIA/DALI/pull/5047, still there is an overhead to read and parse file headers which is now disc IO bound (for files not in the OS disc cache the speed is tens of times smaller than when there are).
I hope we merge it soon and you can test the nightly build that follows.

**Comment by zankerx** [comment]
Thank you for the time spent.
I will test it as soon as it becomes available.

**Comment by JanuszL** [comment]
Hi @zankerx,

The change has been merged. Please check [the nightly build](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/installation.html#pip-nightly-and-weekly-releases) that should be available tomorrow.

**Comment by JanuszL** [comment]
The 1.31 DALI release is out that should include the fix. Closing.
