### ISSUE TITLE
MixedBackend custom operator does not support using the Workspace ThreadPool?

### ISSUE THREAD

**Issue by bveldhoen** [NVIDIA/DALI#5071]
### Describe the question.

Dear DALI maintainers,

I think DALI is great! I have been using it to evaluate a few things, and I'm still quite new to it, so please bear with me.

I've implemented a MixedBackend Operator (and a CPUBackend operator). When trying to use the Workspace ThreadPool in the implementation for the MixedBackend operator, the following error message is produced:

`[/usr/local/lib/python3.10/dist-packages/nvidia/dali/include/dali/pipeline/workspace/workspace.h:393] Assert on "HasThreadPool()" failed: Workspace does not have a Thread Pool.
`

The purpose of my MixedBackend operator is to copy samples from cpu to gpu, execute inference on a pytorch model, and return the outputs on gpu. In particular, the ability to use native threads while executing the pytorch inference step seems interesting as a way to circumvent Python GIL related issues. (As an aside, I do not want to use TIS at this time).

Due to this restriction, I'm forced to use the custom operator in cpu mode (CPUBackend implementation only), and cheat a bit by intermediately copying the samples to and from gpu to execute the pytorch inference. However, this prevents using the custom operators in pipeline structures, as intended by DALI. More importantly, I can't support a mixed mode scenario which uses native threads.

What is the reason that the MixedBackend does not provide the ThreadPool?
Could you please verify if my findings are correct, or if I've missed something?
Is there perhaps a workaround (i.e. using a different base class, etc.)?
Are there future plans to support a ThreadPool for the MixedBackend operator?

Thank you in advance!

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @bveldhoen,

Thank you for reaching out.
That is true, the mixed and GPU operators are missing shared thread pools. The original rationale was that these ops don't need many CPU threads for processing, in selected cases each operator creates its own, not shared thread pool - like [this](https://github.com/NVIDIA/DALI/blob/main/dali/operators/decoder/nvjpeg/nvjpeg_decoder_decoupled_api.h#L1125).

> The purpose of my MixedBackend operator is to copy samples from cpu to gpu, execute inference on a pytorch model, and return the outputs on gpu. In particular, the ability to use native threads while executing the pytorch inference step seems interesting as a way to circumvent Python GIL related issues. (As an aside, I do not want to use TIS at this time).

The idea seems interesting. Have you considered [TRITON](https://github.com/triton-inference-server)or [pyTriton](https://github.com/triton-inference-server/pytriton)?

**Comment by bveldhoen** [comment]
Hi @JanuszL,

Thank you for your quick response. Using an own ThreadPool seems to be exactly what I need, I'll give it a try and post back here.

(Currently, I don't want to introduce yet another dependency/framework, only to achieve native multithreading, so using TRITON/pyTriton in our solution is a less relevant option (at the moment, this may change due to new findings)).
