### ISSUE TITLE
How to use dali pipeline output as pytorch input without extra copy?

### ISSUE THREAD

**Issue by husterdjx** [NVIDIA/DALI#5077]
### Describe the question.

Hello! I'm currently use NVIDIA DALI to preprocess images.

```python
import nvidia.dali.fn as fn
from nvidia.dali.pipeline.experimental import pipeline_def
import nvidia.dali.types as types
from nvidia.dali.plugin.pytorch import feed_ndarray # I use this API to transform DALI tensor to Pytorch tensor

@pipeline_def
def simple_pipeline(resize_flag=True, resize_x=300, resize_y=300, debug=True):
    jpegs, labels = fn.readers.file(file_root='./images',
                                    random_shuffle=True,
                                    name="Reader")
    images = fn.decoders.image(jpegs, device="mixed", output_type=types.RGB)

    # Resize images
    if resize_flag:
        resized_images = fn.resize(images, resize_x=resize_x, resize_y=resize_y, device="gpu")

    # Normalize images
    mean = [0.485 * 255, 0.456 * 255, 0.406 * 255]  # DALI uses 0-255 scale for images
    std = [0.229 * 255, 0.224 * 255, 0.225 * 255]

    normalized_images = fn.crop_mirror_normalize(resized_images,
                                    mean=mean,
                                    std=std,
                                    output_dtype=types.FLOAT,
                                    device="gpu")

    return normalized_images

pipe = simple_pipeline(batch_size=4, num_threads=3, device_id=0)
pipe.build()

_images,  = pipe.run()
```
print output type and shape:
```python
print("-----_images type: ", type(_images)) # nvidia.dali.backend_impl.TensorListGPU
print("-----_images.dtype: ", _images.dtype) # DALIDataType.FLOAT
print("-----_images.shape: ", _images.shape()) # [(3, 300, 300), (3, 300, 300), (3, 300, 300), (3, 300, 300)]
```
after that, I currently use `as_tensor()` and `feed_ndarray` to transform dali pipeline output to pytorch input(I use Pytorch SSD for detection):
```python
_images_dali_tensor = _images.as_tensor()
print("-----_images_dali_tensor type: ", type(_images_dali_tensor)) # <class 'nvidia.dali.backend_impl.TensorGPU'>
print("-----_images_dali_tensor.dtype: ", _images_dali_tensor.dtype) # DALIDataType.FLOAT
print("-----_images_dali_tensor.shape: ", _images_dali_tensor.shape()) # [4, 3, 300, 300]


_images_torch_tensor = torch.empty(_images_dali_tensor.shape(), dtype=torch.float32, device=torch.device('cuda:0'))
feed_ndarray(_images_dali_tensor, _images_torch_tensor) # COPY !!!

print("PyTorch tensor type:", type(_images_torch_tensor))  # <class 'torch.Tensor'>
print("Device of torch tensor:", _images_torch_tensor.device) # cuda:0
print("Dtype of torch tensor:", _images_torch_tensor.dtype) # torch.float32
print("Shape of torch tensor:", _images_torch_tensor.shape) # torch.Size([4, 3, 300, 300])
```
Now I can use `_images_torch_tensor` as Pytorch input. It works ok, however, there will be two copies of image tensor on the GPU(**torch tensor and dali tensor**), which will occupy extra GPU Memory.

**I just wonder whether there will be another way to use _DALI pipeline output_ as _Pytorch input_, without any extra copy. Or is the existence of such a copy the best practice for machine learning inference tasks when using DALI to preprocess?**

If anyone can help me figure this out, I would greatly appreciate it!

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @husterdjx,

> I just wonder whether there will be another way to use DALI pipeline output as Pytorch input, without any extra copy. Or is the existence of such a copy the best practice for machine learning inference tasks when using DALI to preprocess?

I agree, there is a bit of memory utilization optimization left on the table. DALI does that to simplify the memory ownership resolution - the memory exposed by DALI is still owned by DALI, and as soon as it is copied to Pytorch it can be recycled and reused to compute next batch (see more details [here](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/advanced_topics_pipe_run.html)).
We have a long-term plan to alter that behavior and allow zero copy but we are not there yet.

**Comment by husterdjx** [comment]
Glad to see your clear explanation! @JanuszL 

Data ownership between different framework is actually a trouble. Such a copy can simplify programmer's work.

Thanks to your help! I will close this issue soon!
