### ISSUE TITLE
How to batch TensorGPUs to TensorListGPU?

### ISSUE THREAD

**Issue by husterdjx** [NVIDIA/DALI#5078]
### Describe the question.

Hello! 

I'm doing a multi-crop operation to a batch of images. I first use Pytorch SSD to detect the object from images, and I need to use DALI to crop multi-small images from each image(For example, batchsize=4, each image have 8 detected objects, so I need to crop 32 images from all of these images). 

However, I got that DALI does not provide a specific operator for multi-crop. So I try to do that as follows:
```python
@pipeline_def(batch_size=max_batch_size, num_threads=1, device_id=0, debug=True)
def dali_resnet_pipeline(ssd_boxes):
    input = fn.external_source(name="pipe2_input", device="gpu")

    cropped_resized_images = []
    for img_idx, boxes in enumerate(ssd_boxes):
        for box_idx, box in enumerate(boxes):
            # box: [x, y, w, h]
            print("box:", box)
            x, y, w, h = box
            cropped_image = fn.crop(input.at(img_idx), crop=(w, h), crop_pos_x=x/300, crop_pos_y=y/300, device="gpu")
            cropped_resized_image = fn.resize(cropped_image, resize_x=224, resize_y=224, device="gpu")
            cropped_resized_images.append(cropped_resized_image)

    # Normalize images
    mean = [0.485 * 255, 0.456 * 255, 0.406 * 255]  # DALI uses 0-255 scale for images
    std = [0.229 * 255, 0.224 * 255, 0.225 * 255]

    cropped_resized_normalized_images = []

    for i in range(len(cropped_resized_images)):
        cropped_resized_normalized_images.append(fn.crop_mirror_normalize(cropped_resized_images[i],
                                    mean=mean,
                                    std=std,
                                    output_dtype=types.FLOAT,
                                    device="gpu"))
    
    return cropped_resized_images, cropped_resized_normalized_images
```
I don't know how to batch `TensorGPUs` in a `list` so that I can resize and normalize them in a batch instead of doing them one by one. And return a `TensorListGPU` will be easier for me to transform it into Pytorch tensor.

Additionally, I'm not sure I did multi-crop to a batch of images in a right way, so if anybody has better choice, please let me know!

Appreciate any help!!

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by klecki** [comment]
Hi @husterdjx 
in DALI, the pipeline is defined as-if it is processing one sample at a time, but DALI will introduce the batch processing under the hood - we have "implicit batch dimension".
Your outermost loop `for img_idx, boxes in enumerate(ssd_boxes):` contains `img_idx`, but you should not be accessing individual samples this way. When you stop using the debug mode, it won't work.

I would suggest changing from the `ssd_boxes` parameter to another `external_source` operator. This way, one external source would be producing batch of images, and the other would be producing batch of corresponding boxes.

There will be some limitations, you would need to have the same number of boxes for each sample or pad them with dummy boxes. Assuming you have `K` boxes for each sample, the second external source would have 2D samples, `K` as first dimension, and the 4 coordinates as the second dimension, so for example, batch of size 2, with 3 identical boxes would look like:
```[
[[50, 50, 100, 100], [50, 50, 100, 100],[50, 50, 100, 100],],
[[42, 42, 100, 100], [42, 42, 100, 100],[42, 42, 100, 100],],
]
```

And you can now write the first loop as:
```

    input = fn.external_source(name="pipe2_input", device="gpu")
    boxes = fn.external_source(name="boxes", device="cpu")
    cropped_resized_images = [] 
    for box_idx in range(K):  # K is the constant
        box = boxes[box_idx]   # get the box
        # now, unpack it using slicing: https://docs.nvidia.com/deeplearning/dali/main-user-guide/docs/indexing.html
        x = box[0]
        y = box[1]
        w = box[2]
        h = box[3]
        cropped_image = fn.crop(input.at(img_idx), crop=(w, h), crop_pos_x=x/300, crop_pos_y=y/300, device="gpu")
        cropped_resized_image = fn.resize(cropped_image, resize_x=224, resize_y=224, device="gpu")
        cropped_resized_images.append(cropped_resized_image)
```

After that you have a list of `K` batches that you can process further.

```
cropped_resized_normalized_images = []
for i in range(K):
    cropped_resized_normalized_images.append(fn.crop_mirror_normalize(cropped_resized_images[i],
                                    mean=mean,
                                    std=std,
                                    output_dtype=types.FLOAT,
                                    device="gpu"))
```
You need to return the batches directly, so:
```
return cropped_resized_normalized_images[0], cropped_resized_normalized_images[1], ..., cropped_resized_normalized_images[K-1] 
```

**Comment by husterdjx** [comment]
Thanks a million to @klecki!
