### ISSUE TITLE
How to randomly crop two images

### ISSUE THREAD

**Issue by umie0128** [NVIDIA/DALI#5086]
### Describe the question.

I want to use Dali to process images in semantic segmentation, so how can I ensure that the images and labels are the same area after random cropping

code:
![image](https://github.com/NVIDIA/DALI/assets/49420977/1fe527ea-4d7e-405d-b561-6394372ba5f2)

error:
![image](https://github.com/NVIDIA/DALI/assets/49420977/320144ee-5a3c-427f-b615-e92e01d99cf4)

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @umie0128,

Thank you for reaching out. You can take a look at [the 'random_bbox_crop' operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.random_bbox_crop.html#nvidia.dali.fn.random_bbox_crop). If that doesn't suit you, you can write your own using [Numba](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/custom_operations/numba_function.html] or [Python](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/custom_operations/python_operator.html).

**Comment by umie0128** [comment]
@JanuszL 
but semantic segmentation has not bobox
![image](https://github.com/NVIDIA/DALI/assets/49420977/f72518b4-13fe-46cf-a8bb-a52220b9a4f7)

**Comment by JanuszL** [comment]
Hi @umie0128,

`interp_type` should be `nvidia.dali.types.DALIInterpType` or `TensorList of nvidia.dali.types.DALIInterpType`, not a list like in your case. Can you tell me what you wanted to achieve?

**Comment by umie0128** [comment]
![image](https://github.com/NVIDIA/DALI/assets/49420977/a5605e38-2d72-4587-8cf2-ace0f7f9757f)
hi @JanuszL 

I want to replicate the operations of random resize and random crop, label using INTERP_NN

**Comment by JanuszL** [comment]
Hi @umie0128,

I think I now understand what you want to achieve.
What you can do is:
```
@pipeline_def(device_id=0)
def input_pipe():
    images, _ = fn.readers.file(files=['/home/jlisiecki/Dali/DALI_extra/db/single/jpeg/100/swan-3584559_640.jpg', '/home/jlisiecki/Dali/DALI_extra/db/single/jpeg/134/baukran-3703469_1280.jpg'], labels=[0, 1])
    images = fn.decoders.image(images, device='mixed')
    base_size = 100
    long_size = fn.random.uniform(values=[(x / 10 + 0.5) * base_size + 0.5 for x in range(16)])
    images = fn.resize(images, resize_longer=long_size, interp_type=types.DALIInterpType.INTERP_LINEAR)
    labels= fn.resize(labels, resize_longer=long_size, interp_type=types.DALIInterpType.INTERP_NN)
    return images, labels 
```

Regarding [the 'random_resized_crop` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.random_resized_crop.html) if you set the same seed images and masks should be cropped and resized in the same way:
```
images = fn.random_resized_crop(images, ..., seed=global_seed)
labels = fn.random_resized_crop(labels, ..., seed=global_seed)
```

**Comment by umie0128** [comment]
Hi @JanuszL
I tried the method you provided, but Dali's average accuracy is still significantly lower than numpy's. I would like to ask how to achieve the operation of randomly converting BGR to RBG
![image](https://github.com/NVIDIA/DALI/assets/49420977/6c759d6f-3fd7-42e1-8aaf-504f1ff102c0)

**Comment by JanuszL** [comment]
Hi @umie0128,

I'm sorry to hear that you obtained lower accuracy. What I can suggest is to visually examine the pipeline output to make sure you achieve the expected results.
Regarding random conversion between RGB and BGR, you can use [the color conversion operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.color_space_conversion.html#nvidia-dali-fn-color-space-conversion) together with [the conditional execution](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/pipeline.html#conditional-execution).
