### ISSUE TITLE
Can DALI crop audio?

### ISSUE THREAD

**Issue by QinlongHuang** [NVIDIA/DALI#5093]
### Describe the question.

I'd like to crop a wav in dali pipeline.
```python
@pipeline_def
def mel_spec_pipe(...):
    audio, _ = fn.readers.file(files=fp)
    audio, _ = fn.decoders.audio(audio, dtype=types.FLOAT)
    # crop audio
    spectrogram = fn.spectrogram(audio, ....)
    return spectrogram
```

So can DALI process it?

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @QinlongHuang,

You can use [`indexing` operation](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/indexing.html) to trim the data. if that is something you are asking for. Now DALI doesn't support decoding of only part of the sample using the `fn.decoders.audio` operator, but you can look at [the `nemo_asr` reader operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.readers.nemo_asr.html) where you can create manifest specifying the offset and duration of audio samples for the decoding.

**Comment by JanuszL** [comment]
@QinlongHuang,

In this case you need to use [the `slice` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.slice.html#nvidia.dali.fn.slice) and feed the anchor and window size using [the `external source` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.external_source.html).

**Comment by QinlongHuang** [comment]
@JanuszL Thx for your quick reply. I have read the docs of `fn.slice`. But I'm not sure how to feed start and end index to `fn.slice`. Could you please give me some advice? Here's my code snippet.
```
fps = ['1.wav', '2.wav']
@pipeline_def
def mel_spec_def(..., start_index, end_index):
    audio_buffer, _ = fn.readers.file(files=fps)
    audio, _ = fn.decoders.audio(audio_buffer, dtype=types.FLOAT)  # 2 audios here
    
    start_source = fn.external_source(starts)
    end_source = fn.external_source(ends)
    audio = fn.slice(audio, start=start_source, end=end_source)  # ERROR
```
BTW, according to the docs of [the slice operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.slice.html#nvidia.dali.fn.slice), the input of start and end can be a list, but when I sent a list, it crashed.

**Comment by JanuszL** [comment]
Hi @QinlongHuang,

What you can start with is:
```
fps = ['1.wav', '2.wav']
starts = np.array([[10, ], [7, ]], dtype=np.int32)
ends = np.array([[9, ], [8, ]], dtype=np.int32)
@pipeline_def(device_id=0)
def input_pipe():
    audio_buffer, _ = fn.readers.file(files=fps)
    audio, _ = fn.decoders.audio(audio_buffer, dtype=types.FLOAT)  # 2 audios here
    start_source = fn.external_source(lambda : starts)
    end_source = fn.external_source(lambda : ends)
    images = fn.slice(images, start_source, end_source, axes=[0])
    return images, start_source, end_source
```
Of course, you can extend the `external source` usage as in [this](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/parallel_external_source.html) example and load samples, and the desired ROI that is attached to them. It depends if the slicing windows are specific or defined in any other way.

**Comment by QinlongHuang** [comment]
@JanuszL Thank you sooooo much! It works!!! 
What a great framework ! It speeds up my training by 3x !
