### ISSUE TITLE
problem of loader.h  Assert on "num_shards_ > shard_id_" failed

### ISSUE THREAD

**Issue by chituma110** [NVIDIA/DALI#510]
RuntimeError: Critical error in pipeline: [/opt/dali/dali/pipeline/operators/reader/loader/loader.h:57] Assert on "num_shards_ > shard_id_" failed: num_shards needs to be greater than shard_id
Current pipeline object is no longer valid.

**Comment by JanuszL** [comment]
Hi,
It means that `num_shards` arg of your reader is greater than `device_id` in your pipeline. `device_id` tells DALI which GPU it is working on, while `num_shards` is total number of GPUs used in your training.
