### ISSUE TITLE
How to do item assignment in Pipeline?

### ISSUE THREAD

**Issue by QinlongHuang** [NVIDIA/DALI#5104]
### Describe the question.

Hi DALI Group, 
I'd like to mask the down half of image with 0. On numpy or pytorch, I can do `x[:3, H//2:]=0`, assuming that the shape of `x` is `[6, H, W]`, and it is composed of 2 images, and I only want to mask the first image. When I read the docs, I find the function `fn.erase` might do it. But I don't know how to use it properly. Could you plz give me some advice?

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by QinlongHuang** [comment]
a naive implementation is to split them out, `fn.erase` the first image, and then concat them. Is there anyway to do that directly?

**Comment by mzient** [comment]
Hello @QinlongHuang 
fn.erase can take relative coordinates, so you can easily erase half of the image without knowing its size. Here's an example:
```Python
import nvidia.dali.fn as fn
import nvidia.dali as dali
import numpy as np

@dali.pipeline_def(batch_size=1, device_id=0, num_threads=4)
def my_pipe():
    enc, _ = fn.readers.file(file_root=".", files=["alley.png"])
    img = fn.decoders.image(enc, device="mixed")
    return fn.erase(img, normalized=True, anchor=np.array([[0.5, 0]]), shape=np.array([[0.5, 1.0]]))

pipe=my_pipe()
pipe.build()
out, = pipe.run()

import PIL.Image
PIL.Image.fromarray(np.array(out[0].as_cpu()))
```
Result:
![image](https://github.com/NVIDIA/DALI/assets/17044837/0256f8bc-a224-418b-90f5-9ca7df9d7fd7)

**Comment by QinlongHuang** [comment]
@mzient Thank you so much for your reply. But there are two images in the tensor, and I only want to mask the first one. Here is the snippet of my code now.
```python
frames = fn.decoders.image(self.batch_frames, device='mixed', output_type=types.RGB)  # 2T*[H, W, 3]
frames = [frame.gpu() for frame in frames]
frames = fn.stack(*frames, axis=0)  # [2T, H, W, 3]
x = fn.cat(frames[:self.syncnet_T], frames[self.syncnet_T:], axis=-1)  # [T, H, W, 6]
x = fn.transpose(x, perm=[3, 0, 1, 2])  # [T, H, W, 6] -> [6, T, H, W]
tmp = fn.copy(x[3:])  # [3, T, H, W]
mask = fn.erase(x[:3], 
                            anchor=(self.img_size//2, 0), 
                            shape=(self.img_size//2, self.img_size), 
                            axes=[2,3])  # [3, T, H, W]
x = fn.cat(mask, tmp, axis=0)
```
Can I only mask the first image (i.e., the first 3 channels) via `fn.erase`?

**Comment by mzient** [comment]
Hmm... this code looks strange. Are you using debug mode or the (experimental) eager mode? Normally you wouldn't be able to do `frames = [frame.gpu() for frame in frames]`. If you're in eager mode, I'd suggest to just use `erase` on the interesting images before stacking.
If you're not using eager mode, you could have two readers and decoders. I can't help you much more without seeing the code with larger context. Can you post more complete code? It's hard to work with just a snippet, which refers to an object (`self`) which I know nothing about.

**Comment by QinlongHuang** [comment]
Hi @mzient , `self.batch_frames` is just a list of `DataNode`, and I overwrite the `Pipeline` Class, and the snippet above is in `define_graph` function. As for the sentence `frames = [frame.gpu() for frame in frames]`, I am new to DALI, and I remove this line now, thank u. Here is the complete code of `define_graph` funciton:
```python
def define_graph(self):
        # define DataNode from ExternalSource
        self.batch_frames = [i() for i in self.input_frames_source]
        self.batch_indiv_mels = self.input_indiv_mels_source()
        self.batch_mel = self.input_mel_source()
        
        # read_window
        frames = fn.decoders.image(self.batch_frames, device='mixed', output_type=types.RGB)  # 2T*[H, W, 3]
        frames = fn.stack(*frames, axis=0)  # [2T, H, W, 3]
        x = fn.cat(frames[:self.syncnet_T], frames[self.syncnet_T:], axis=-1)  # [T, H, W, 6]
        # transformation
        x = fn.normalize(x, mean=0., stddev=1., scale=1/255.)
        x = fn.transpose(x, perm=[3, 0, 1, 2])  # [T, H, W, 6] -> [6, T, H, W]
        y = fn.copy(x[:3])  # [3, T, H, W]
        tmp = fn.copy(x[3:])  # [3, T, H, W]
        mask = fn.erase(x[:3], 
                        anchor=(self.img_size//2, 0), 
                        shape=(self.img_size//2, self.img_size), 
                        axes=[2,3])  # [3, T, H, W]
        x = fn.cat(mask, tmp, axis=0)
        
        indiv_mels = fn.reshape(self.batch_indiv_mels, shape=[self.syncnet_T, 1, 80, 16]).gpu()
        mel = fn.reshape(self.batch_mel, shape=[1, 80, 16]).gpu()
        
        return x, indiv_mels, mel, y

```

**Comment by mzient** [comment]
Hello @QinlongHuang ,
DALI readily operates on batches and it has some level of support for videos. This code, even if it works, seems to be quite inefficient on many fronts.
First, passing a list of `DataNode` objects to an operator is just a syntactic sugar for creating multiple instances of that operator.
```Python
frames = fn.decoders.image(self.batch_frames, device='mixed', output_type=types.RGB)
```
is equivalent to
```Python
frames = [fn.decoders.image(x, device='mixed', output_type=types.RGB) for x in self.batch_frames]
```
Unfortunately, there's no easy workaround for that at the time.

Then, there's a lot of shuffling of the data around. One thing that could be done, is to split the stacking.
```Python
# create two sub-stacks - stacking everything and then extracting parts is inefficient
part1 = fn.stack(*frames[:self.syncnet_T], axis=0, axis_name='F')  # the layout now is FHWC
part2 = fn.stack(*frames[self.syncnet_T:], axis=0, axis_name='F')
# now erase the lower half of the images in part2
part2 = fn.erase(part2, normalized=True, anchor=np.array([[0.5, 0]]), shape=np.array([[0.5, 1.0]]), axis_names="HW")
frames = fn.cat(part1, part2, axis=-1)
frames = frames * (1.0/255)  # no need to call normalize for simple scaling
frames = fn.transpose(frames, perm=[3, 0, 1, 2])
```

**Comment by QinlongHuang** [comment]
Hi @mzient, thank u for your patient response. In my data process pipeline, I have to make a copy of `part2` as the label of model training. So I have to add some lines to snippet you wrote, call `code1`, 
```python
part1 = fn.stack(*frames[:self.syncnet_T], axis=0, axis_name='F')  # the layout now is FHWC
part2 = fn.stack(*frames[self.syncnet_T:], axis=0, axis_name='F')
# now erase the lower half of the images in part2
y = fn.copy(part2)
part2 = fn.erase(part2,
                 normalized=True,
                 anchor=np.array([[0.5, 0]]),
                 shape=np.array([[0.5, 1.0]]),
                 axis_names="HW")
frames = fn.cat(part1, part2, axis=-1)
frames = frames * (1.0/255)  # no need to call normalize for simple scaling
frames = fn.transpose(frames, perm=[3, 0, 1, 2])
y = y * (1.0/255)
y = fn.transpose(y, perm=[3, 0, 1, 2])
```
So which one (compared to my snippet before, call `code2`) is more efficient? I prefer `code1`

**Comment by mzient** [comment]
Hello @QinlongHuang ,
DALI DataNodes are immutable, so you don't have to do `fn.copy` - this is a special operator that is not useful in normal code.
It would be sufficient to just do `y = part2`.

**Comment by QinlongHuang** [comment]
I got it. Thank you so much @mzient !!
