### ISSUE TITLE
InputOperator with multiple outputs

### ISSUE THREAD

**Issue by bveldhoen** [NVIDIA/DALI#5135]
### Describe the question.

Hi All,

Thank you in advance for any help you can provide.

I'm running into an issue with a custom implementation of an InputOperator. I need this InputOperator to return multiple outputs, in my case 2. Our current implementation works for only 1 output. When I change our implementation to use 2 outputs, by calling SetDataSource/ForwardCurrentData twice, I seem to run into a deadlock. I can provide stack traces of the relevant threads later, if that would be helpful.

Below the gist of the implementation of Run:

```
explicit MyInputoperator::MyInputOperator(const OpSpec& spec)
{
    ...
    auto outputs = this->GetNextOutputs(); // returns a std::tuple of TensorList<> for the next outputs
    this->SetDataSource(std::get<0>(outputs));
    this->SetDataSource(std::get<1>(outputs));
}

template <>
void MyInputOperator<CPUBackend>::Run(Workspace& ws)
{
    std::cout << "[" << std::this_thread::get_id() << "] "  << "Run (cpu)" << std::endl;
    auto& tp = ws.GetThreadPool();

    std::optional<std::string> data_id;

    auto& output0 = ws.Output<CPUBackend>(0);
    this->ForwardCurrentData(output0, data_id, tp);
    auto& output1 = ws.Output<CPUBackend>(1);
    this->ForwardCurrentData(output1, data_id, tp);

    auto outputs = this->GetNextOutputs(); // returns a std::tuple of TensorList<> for the next outputs
    this->SetDataSource(std::get<0>(outputs));
    this->SetDataSource(std::get<1>(outputs));

    this->SetDepletedOperatorTrace(ws, true);
}
```

GetNextOutputs() returns the next outputs, which are taken from a thread-safe collection member variable (custom deque with max size), which is fed from a separate thread. (but this should be irrelevant, I think)

Is this the appropriate way to make an InputOperator with multiple outputs? If not, what is the preferred solution?

As a sidenote, an example for an InputOperator would be really helpful. The description/comments w.r.t. the order/timing with which SetDataSource/ForwardCurrentData/HandleDataAvailability/SetDepletedOperatorTrace should be called is not really clear, and there are no other good examples in the codebase (besides some unit tests, which do not mimic a real scenario).

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @bveldhoen,

Thank you for reaching out. The initial idea was that the input operator has only one output, or multiple outputs that can be generated using one call to `ForwardCurrentData`. `SetDataSource` puts one element in the internal queue, `ForwardCurrentData` obtains one element from the internal queue. Although your approach is not what we had in mind when implementing the `Inputoperator` infrastructure it should work.
If you can provide a standalone test code that would illustrate the problem it can help with the debugging.

**Comment by bveldhoen** [comment]
Hi @JanuszL,

Thanks for your reply! Since SetDataSource can only take a single TensorList<>, I don't see how I can make this work with a single call to SetDataSource.

One of the problems is that the TensorLists dtype of the two outputs is different (FLOAT vs UINT64). I could work around this issue by representing the UINT64s as FLOATs, and adding a dimension to the single output?

**Comment by bveldhoen** [comment]
Please ignore my previous comment, it's not applicable in hindsight. I've managed to work around this issue by maintaining a map<std::string, TensorList<CPUBackend>>, with the data_id as a key, temporarily storing the 2nd output in the map, and retrieving it in the Run method.

Thanks again!
