### ISSUE TITLE
Is there any speed improvement over Torchvision if the latest pipeline operation is cpu only?

### ISSUE THREAD

**Issue by elmuz** [NVIDIA/DALI#5141]
### Describe the question.

Hi, I am considering to move my actual pipeline to DALI but I am skeptical regarding the speed improvement I could get in my specific case.

My scenario is a very common image segmentation task, where my input is an image and the label is the mask. In particular:

- I am applying some affine transformations that can be replaced by [these functions](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.transforms.html), which I noticed they only have a CPU backend.
- After affine transformations, only random crop and resize is performed before inference.
- I understood that the only supported device transfer is CPU -> GPU and not the other way around.

Given the statements above I suppose that the whole pipeline should live on the CPU and being moved to GPU only afterwards. Can you tell me if in this case I should expect any performance boost by moving to DALI compared to Torch(vision)? If so, where that gain would come from?

Cheers!

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @elmuz,

Thank you for reaching out.
I think [this example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/math/geometric_transforms.html) should describe how to use geometric transformations. The operations you mentioned 
indeed are available only for the CPU but they are responsible only for generating the transformation matrices used later by [the `warp_affine`](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.warp_affine.html) operator. On top of that DALI will also GPU accelerate image decoding (for selected formats like JPEG and JPEG2000).
I would expect to see good performance in the scenario you describe.

**Comment by elmuz** [comment]
Thank you @JanuszL I guess it makes sense. I thought that geometric transformations would block decoding for being on GPU. Instead, if they're only computing matrices and not depending on image tensors, then they can be generated on CPU and fed into the pipeline later after the decoding. Thanks
