### ISSUE TITLE
How to deal with corrupt files?

### ISSUE THREAD

**Issue by Pedrexus** [NVIDIA/DALI#5155]
### Describe the question.

Hello all,

I have been using DALI for a while now, but recently I have been dealing with a problem of having corrupt files:

```python
Error when constructing operator: readers__VideoResize encountered:
[/opt/dali/dali/operators/reader/loader/video_loader.cc:324] Could not find video stream in datasets/db/Kinetics400/train/bungee jumping/oyj6TFAxpiw_000229_000239.mp4
```

I tried finding them with a loop using ffmpeg, but it seems it was not enough, so I would like to ask if there is any way to just ignore them in DALI, identify them with DALI or any other simple work around?

Thank for the hard work on the library.

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @Pedrexus,

Thank you for reaching out.
Is it a regression at your end? Or a convenient functionality you would like to have in DALI?
Maybe you can provide the video so we can reproduce this on our end and see if we can implement skipping unsupported videos in a reliable way?

**Comment by Pedrexus** [comment]
Hello @JanuszL 

This is a problem of the datasets I am using. There are thousands of corrupted video files, and I would like to conveniently skip these by the data loader if possible.

example dataset: https://github.com/cvdfoundation/kinetics-dataset

example working video: https://github.com/NVIDIA/DALI/assets/19956280/c39e048b-f83c-454b-b2d5-35606df4c52f

example corrupted video: https://github.com/NVIDIA/DALI/assets/19956280/5ecb5019-623c-4eae-974a-98150c8d28ac

**Comment by Pedrexus** [comment]
Thank you very much for the help @JanuszL. This is precisely what I needed. I think this thread could be closed then!

**Comment by JanuszL** [comment]
Let us wait till it is merged and you can test it with the nightly build... just in case.

**Comment by JanuszL** [comment]
It has just been merged. It should be available the next nightly we publish.

**Comment by Pedrexus** [comment]
Besides that, I noticed I also get a "variable frame rate" error in the middle of the run when I lower the `stride` to 1 or 2 spite of setting `skip_vfr_check=True`. However, I don't know which video has this problem. Is there any way to identify the defect video or would this PR also help with this?

**Comment by Pedrexus** [comment]
I see in the nightly version I am able to identify the vrf videos now! Thank you for this feature:

`The decoder returned a frame that is 
past the expected one. The most likely cause is variable frame rate video. Filename: datasets/FiftySalads/avi/rgb-18-2.avi`

However, is there a work around to using these videos without having to remove them from the dataset?

**Comment by JanuszL** [comment]
@ptrendx - for now you need to rely on [the experimental video reader](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.experimental.readers.video.html) to handle these.

**Comment by Pedrexus** [comment]
On another dataset, I am now getting the following error:

```139741743781440 Exception in thread: [/opt/dali/dali/operators/reader/loader/video_loader.cc:625] 0: failed to seek frame 0```

I am not sure on which video this is happening. Is there any way to discover?

**Comment by JanuszL** [comment]
Hi @Pedrexus,

I can only guess that the video container doesn't support seeking (it happens for rew video stream you can just decode things from the first frame till the end, but not from the middle).
Is it possible for you to share the video to double check this on our side?

**Comment by Pedrexus** [comment]
Hello @JanuszL,

thank you for the reply. I have been trying to investigate the issue, and for now I only have a few hints. This is a problem specific to the [Something Something V2 dataset](https://developer.qualcomm.com/software/ai-datasets/something-something), which has all videos encoded as WEBM using the VP9 codec.

I checked the [NVDEC docs at this link](https://docs.nvidia.com/video-technologies/video-codec-sdk/12.1/nvdec-video-decoder-api-prog-guide/index.html), and it says VP9 is supported. Moreover, I noticed the pipeline build just stalls on this dataset.

Now, I tried transcoding the .webm files to .mp4 using the following command: `ffmpeg -loglevel error -i "$file" -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" -c:v libx265 -preset faster -threads 0 -crf 28 "${file%.webm}.mp4"`

Now, the pipeline is built, but I am getting a few warnings and errors:

warning example: 
`[mov,mp4,m4a,3gp,3g2,mj2 @ 0x5565f5b09740] moov atom not found. opt/dali/dali/operators/reader/nvdecoder/nvdecoder.cc:205: Unable to decode file datasets/SSv2/mp4/train/Putting something behind something/130752.mp4`

error:
`RuntimeError: Critical error in pipeline:
Error when executing GPU operator readers__VideoResize encountered:
[/opt/dali/dali/operators/reader/nvdecoder/cuvideodecoder.cc:167] Encountered a dynamic video format change.`

I think this could be related to the H.265 I decided to use on the transcoding command, but I am not sure. I'd appreciate If you could suggest which would be the "ideal" format for the video reader.

Here is an example of a video the could not be parsed:

WEBM version (original):
[130752.webm](https://github.com/NVIDIA/DALI/assets/19956280/c0ab86ef-c18c-4540-a6aa-31cda03a6586)

H.265 MP4 version:
https://github.com/NVIDIA/DALI/assets/19956280/0383c416-49bd-4175-ad9f-ac5b7d63a935

**Comment by Pedrexus** [comment]
I also found this related issue https://github.com/NVIDIA/DALI/issues/2737.

**Comment by JanuszL** [comment]
Hi @Pedrexus,

Thank you for reaching out.
It seems that DALI fails to start decoding the provided file and it tries to seek a preceding keyframe. When it fails for the keyframe 0 it falls into an infinite loop - https://github.com/NVIDIA/DALI/pull/5218 should fix this and in the meantime, we will check why the decoder doesn't return any frames for this video.

> RuntimeError: Critical error in pipeline: Error when executing GPU operator readers__VideoResize encountered: [/opt/dali/dali/operators/reader/nvdecoder/cuvideodecoder.cc:167] Encountered a dynamic video format change.

Regarding the above the old reader doesn't support videos encoded with different formats in the same data set, maybe you can try to reencode it to webm instead of H265?

**Comment by Pedrexus** [comment]
I see. Thank you for the reply. 

After reencoding my data to H264, .mp4 with yuv420p, I haven't had other problems. 

I might try other formats later if it could get faster, but it's working fine for now.

**Comment by JanuszL** [comment]
1.33 is out with that fix.
