### ISSUE TITLE
Centering crop on bounding box

### ISSUE THREAD

**Issue by addisonklinke** [NVIDIA/DALI#523]
In the [documentation](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html#nvidia.dali.ops.ResizeCropMirror) for `ops.ResizeCropMirror`, the two parameters `crop_pos_x` and `crop_pos_y` are supposed to give the position of the crop. This sounds like it should be the center point of the cropped image. 

However, when using the operator I find that the point at `(crop_pos_x*crop_x, crop_pos_y*crop_y)` is always in the cropped image, however it is _not_ at the center of the crop. Instead, the "center" point is at the same image coordinates in the crop as it was in the original (or resized) image. Why is this, and how can I get the crop truly centered on a point of interest? 

In this example, I know the coordinates of the license plate (green dot) and want to center the crop on it

**Original Images**
![image](https://user-images.githubusercontent.com/39926682/52508739-d5a45300-2bb2-11e9-8f1d-1d021533fa67.png)

**Cropped at 70%**
![image](https://user-images.githubusercontent.com/39926682/52508757-e654c900-2bb2-11e9-8fbb-8c4c01070195.png)

**Cropped at 40%**
![image](https://user-images.githubusercontent.com/39926682/52508775-f5d41200-2bb2-11e9-82e5-a68f26fd1164.png)

**Cropped at 10%**
![image](https://user-images.githubusercontent.com/39926682/52508795-03899780-2bb3-11e9-90a3-e1d571eab863.png)

You can see that the crop is obviously tracking with the location of the plate (otherwise at 10% it would no longer be in the frame). But clearly, the center of the plate is not the center of the cropped image. The plate stays at the same image coordinates regardless of the cropping level.

**Comment by JanuszL** [comment]
Hi,
Indeed crop description in the documentation is not as verbose as it deserves.
Crop position is calculated as a postion_x * (W - crop_w), where:
* postion_x [0,1]
* W - real image size
* crop_w - desired cropping window
Thanks to this postion_x is always withing the 0-1 range and can be sourced from the random generator.
So in your case you need to take into account the size of the cropping window and calculate its position accordingly (I hope I did the math correctly):
postion_x = (plate_center_x - crop_w / 2 ) / (W - crop_w)

**Comment by addisonklinke** [comment]
@JanuszL The `postion_x = (plate_center_x - crop_w / 2 ) / (W - crop_w)` formula makes sense to me, however it is not constrained to the [0, 1] range needed for `position_x`. The numerator of the equation is a coordinate in the range [0, W] (representing the upper left corner of the crop box), but the denominator is necessarily less than W for `crop_w > 0`, so `position_x > 0` is possible. 

If I understand correctly, I should pass `position_x` as the `crop_pos_x` parameter to the crop operator. However, this will cause an error since `position_x` will not always match the [0, 1] range required by the `crop_pos_x` parameter

**Comment by addisonklinke** [comment]
Thank you @JanuszL, that definitely helps clarify. Perhaps the documentation could indicate that crop position is the upper left corner of the crop? From the current description, I had assumed it would be the center of the crop

For others finding this thread later, using the formula `(plate_center_x - crop_w / 2 ) / (W - crop_w)` can lead to values of `position_x` that are greater than 1 or less than zero. This indicates that in order to center the plate in the image, the upper left corner of the crop would have to be located _outside_ the current image dimensions. This isn't possible, so simply add a check after calculating `position_x` to ensure it is bound between [0, 1] like so
```
position_x = std::max(0.f, std::min(position_x 1.f));
```

**Comment by jantonguirao** [comment]
@addisonklinke We are currently enhancing the documentation about those crop operator arguments. Hopefully it will be much clearer.

**Comment by JanuszL** [comment]
Hi,
@jantonguirao just updated docs - https://github.com/NVIDIA/DALI/pull/529. Regarding the formula it assumes that the whole plate is visible in the image and its size is not bigger than crop_w. In such case left edge would be plate_center_x - crop_w / 2 and right one plate_center_x + crop_w / 2
