### ISSUE TITLE
Can I install DALI on CPU node without GPU/CUDA

### ISSUE THREAD

**Issue by mengwanguc** [NVIDIA/DALI#5253]
### Describe the question.

Hi,

I'm wondering if it's possible to install DALI on a CPU node without GPU/CUDA?
I tried to search the internet but didn't find any solution. Not sure I missed anything.

I understand that DALI is primarily designed to accelerate data loading for GPU nodes.
I'm just wonder it supports installation on CPU nodes. (e.g. I know PyTorch and Tensorflow support running on CPU nodes).

Thanks!
Meng

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @mengwanguc,

Thank you for reaching out.
Yes, you can install DALI on the CPU-only computer, and use it there as long as your pipeline uses only the CPU operator. See [the `device_id` argument description](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/pipeline.html#pipeline-class) of the pipeline class.

**Comment by NaufalRezkyA** [comment]
Hi @JanuszL,

I tried to install DALI on the CPU-only with your suggestions. I changed the device parameter to CPU and device_id in the pipelines so there is no operations related to GPU. I just made a new github issue for this problem. You can check it here for the detail.
[https://github.com/NVIDIA/DALI/issues/5261](url)
Any suggestions will be really useful for me

Thanks,
Naufal

**Comment by NaufalRezkyA** [comment]
@JanuszL I do have a problem with running it on CPU-only. Can you please help? (Sorry if I didn't make it clear in the prior comment). [https://github.com/NVIDIA/DALI/issues/5261](https://github.com/NVIDIA/DALI/issues/url)
