### ISSUE TITLE
How to destory a pipeline?

### ISSUE THREAD

**Issue by yaojunr** [NVIDIA/DALI#5256]
### Describe the question.

```python
@pipeline_def(enable_conditionals=True, batch_size=batch_size, num_threads=num_workers,
        device_id=local_rank_gpu, prefetch_queue_depth=prefetch_queue_depth, seed=config.get('seed', 42))
def custom_pipe():
    jpegs, labels = fn.readers.mxnet(
        path=rec_file, index_path=idx_file, initial_fill=initial_fill, 
        num_shards=world_size, shard_id=rank,
        random_shuffle=random_shuffle, pad_last_batch=last_batch_padded, name=phase)
    images = transform(jpegs)
    return images, labels
pipe = custom_pipe()
pipe.build()

return DALIWarper(DALIClassificationIterator(pipelines=[pipe], reader_name=phase, last_batch_policy=last_batch_policy), 
                    length=length, dataset=dataset, rec_file=rec_file, idx_file=idx_file)

```
I use the code above to create a pipeline. During training, I want to do some sampling the pipeline, so I recreate the pipeline with newly generated mxnet record and replace the old pipeline every epoch. However, I find the memory is not released, and it leads to OOM error. How can I destory the old pipeline?

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @yaojunr,
The pipeline exists as long as the references to it. If you remove the DALIWarper, pipe and do not have any other reference to the pipeline it should be released.
However, recreation of the pipeline adds overhead so you should avoid it if possible.
