### ISSUE TITLE
cv2.resize(interpolation=cv2.INTER_LINEAR) different with  fn.resize(img, antialias=True, subpixel_scale=True, interp_type=types.DALIInterpType.INTERP_LINEAR, resize_y=target_img_height, max_size=max_width)

### ISSUE THREAD

**Issue by sheirving** [NVIDIA/DALI#5260]
### Describe the question.

I use DALI to train my model with input images be resized by " fn.resize(img, antialias=True, subpixel_scale=True, interp_type=types.DALIInterpType.INTERP_LINEAR, resize_y=target_img_height, max_size=max_width)". When inference my model, i use opencv resize image cv2.resize(interpolation=cv2.INTER_LINEAR) , the result acc is lower than DALI inference 2%?

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by cspung** [comment]
The same problem to you, how did you solve it?

**Comment by JanuszL** [comment]
Hi @cspung,

Please check https://github.com/NVIDIA/DALI/issues/4257 or https://github.com/NVIDIA/DALI/issues/3610 threads and see if that is the case. What you can do is compare the processing side by side and check what could be the source of the discrepancy.
