### ISSUE TITLE
Can we add image distortion removal operations

### ISSUE THREAD

**Issue by umie0128** [NVIDIA/DALI#5264]
### Is this a new feature, an improvement, or a change to existing functionality?

New Feature

### How would you describe the priority of this feature request

Must have (e.g. DALI adoption is impossible due to lack in functionality).

### Please provide a clear description of problem this feature solves

hi
I am converting the pixel coordinate system to the world coordinate system, so I want to perform distortion removal on the image. Can Dali currently support distortion removal?

### Feature Description

cv2.undistort -> fn.undistort 

### Describe your ideal solution

cv2.undistort -> fn.undistort 

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @umie0128,

You can use [the `remap` operation](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.experimental.remap.html#nvidia.dali.fn.experimental.remap) and feed it with transformation matrices generated using `initUndistortRectifyMap` from OpenCV using camera calibration data.

**Comment by umie0128** [comment]
Hi @JanuszL 
i try but fn.decoders.image not support 'gpu'
![image](https://github.com/NVIDIA/DALI/assets/49420977/db6e0896-bb81-42cd-be5f-199a9609455c)
how can i fix it

**Comment by JanuszL** [comment]
Hi @umie0128,

The decoder can consume images that are only on the CPU, in your case you want it to consume the input from the GPU operator.  Also, the decoder works on the encoded images, while remapping the raw one. In the provided example I think you should switch the order of these operations to have:
- loading
- decoding
- optional remap

**Comment by umie0128** [comment]
Hi @JanuszL 
Do you mean to do this？
![image](https://github.com/NVIDIA/DALI/assets/49420977/8ad4aef0-9095-455f-92a2-6c25533d4f53)

**Comment by JanuszL** [comment]
@umie0128,

Yes, it should work. You can also set the `mixed` backend in the image decoder operator to get the GPU acceleration for the decoding.

**Comment by umie0128** [comment]
> @umie0128,
> 
> Yes, it should work. You can also set the `mixed` backend in the image decoder operator to get the GPU acceleration for the decoding.

no, it can‘t. There is an error reported below

**Comment by JanuszL** [comment]
Sorry, I missed the error in your screenshot. The error says that the color space conversion operator is on the GPU while its input is on the CPU, so either you should convert it to be a CPU operator, make `imgs.gpu()` to transfer it explicitly to the GPU, or use the `mixed` backend for the decoder so it will produce `imgs` on the GPU.
