### ISSUE TITLE
Can I use DALI only for data augmentation?

### ISSUE THREAD

**Issue by TsingWei** [NVIDIA/DALI#5288]
### Describe the question.

All the examples of DALI seem to use DALI for the  whole pipeline of [ image reading ->  decoding -> augmentation ].  In these cases, the DALI pipeline instance manage the data processing during the entire lifetime of model training.  However, I want to use DALI only as a substitution of the transform from Torch ( which could ease me from the burden of rewriting all the dataset's adpaters I am using).  Is this possible? or where can I get the example of that?

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by banasraf** [comment]
Hi @TsingWei 
If I understand correctly, you want to handle the data loading part outside of the pipeline. I might need more details of what you workflow looks like but my first thought is using the [`external_source`](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.external_source.html) operator. It lets you pass data defined in Python (as lists, iterators, generators, callables) to DALI pipeline.

Here you can see examples of how to use extrenal source.
[External Source Operator - basic usage](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/external_input.html#External-Source-Operator---basic-usage)
[Parallel External Source](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/parallel_external_source.html)

**Comment by TsingWei** [comment]
Thanks! The example looks good to me.
