### ISSUE TITLE
Checkpoint support for readers

### ISSUE THREAD

**Issue by jramapuram** [NVIDIA/DALI#5289]
### Version

1.33.0

### Describe the bug.

The [checkpointing API](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/advanced_topics_checkpointing.html) currently tries to checkpoint an entire pipeline which includes augmentations such as `RandomResizedCrop`. This fails with the following error:

```bash
  File "/miniconda/lib/python3.10/site-packages/nvidia/dali/pipeline.py", line 935, in build
    self._pipe.Build(self._generate_build_args())
RuntimeError: [/opt/dali/dali/pipeline/operator/operator.h:214] Checkpointing is not implemented for this operator: RandomResizedCrop
```

However in most situations what matters is the dataset ordering (especially for very large datasets). 

Is it possible either (a) resolve pipeline checkpoint -- this would entail support for all random ops or (b) just enable checkpointing for the file/image/audio readers (much simpler).

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by szkarpinski** [comment]
Hello @jramapuram , thank you for reaching out. We initially missed `RandomResizedCrop` when adding checkpointing support and already fixed this mistake (https://github.com/NVIDIA/DALI/pull/5246).

The fix will be included in DALI 1.34, you can also install [the nightly build](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/installation.html#nightly-builds) which already has this fixed. All other operators (except for some `experimental` ones listed in [the release notes](https://github.com/NVIDIA/DALI/releases/tag/v1.33.0)) should now support checkpointing as well. If you encounter any other problems with checkpointing, feel free to ask.

**Comment by szkarpinski** [comment]
@jramapuram Unfortunately there's no easy workaround at the moment. I'm currently working on enabling other last batch policies including `DROP` and I'll keep you updated.

**Comment by szkarpinski** [comment]
Hello @jramapuram, I've just merged https://github.com/NVIDIA/DALI/pull/5298 which adds support for `DROP`. It should make it to nightly in a day or two. I'll let you know when it's available.

**Comment by jramapuram** [comment]
Appreciate the quick turnaround @szkarpinski ! 🙏Happy to test and validate when it gets into nightly

**Comment by jramapuram** [comment]
Thanks @stiepan ! Will give this a try this week. Appreciate it.
