### ISSUE TITLE
How to use Dali tool for image sharpening operation

### ISSUE THREAD

**Issue by wangdada-love** [NVIDIA/DALI#5292]
### Describe the question.

I haven't found a suitable API to perform image sharpning.I tried directly using `dali.fn.laplacian`, but this method outputs the edges of the image. I want to combine this edge image with the original image through weighted addition, but I haven't found a usable API for this operation.Can you please guide me on how to code image sharping using DALI?

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by wangdada-love** [comment]
Thanks for your reply.
I have tried this method before, But I received an error message as follows:
```text
RuntimeError: Critical error in pipeline:
Error when executing GPU operator conditional__Merge, instance name: "__Merge_29", encountered:
[/opt/dali/dali/pipeline/operator/builtin/conditional/merge.cc:45] Assert on "base_input.type() == input.type()" failed: Divergent data found in different branches of conditional operation. All paths in conditional operation are merged into one batch which must have consistent type, number of dimensions, layout and other metadata. Found distinct types: float and uint8.

```
I just tried again, but got the same error message. Based on the error message, I speculate that the problem is caused by an incorrect data type. So, I made the following modifications to the code:
```python
def rand_sharp(images, scale=1.0, window_size=3, device="gpu"):
    sharp = fn.laplacian(images, scale=scale, window_size=window_size, device=device)
    sharp = fn.cast(sharp, dtype=dali.types.DALIDataType.FLOAT)
    images = fn.cast(images, dtype=dali.types.DALIDataType.FLOAT)
    out = 0.7 * images + 0.3 * sharp
    out = fn.cast(out, dtype=dali.types.DALIDataType.UINT8)
    return out
```
it works.

**Comment by JanuszL** [comment]
Hi @wangdada-love,

I'm happy you made that work. The issue is that `out = 0.7 * images + 0.3 * sharp` returns float type while the other branch of your `if` condition returns just int8, so in your context just 
```
def rand_sharp(images, scale=1.0, window_size=3, device="gpu"):
    sharp = fn.laplacian(images, scale=scale, window_size=window_size, device=device)
    out = 0.7 * images + 0.3 * sharp
    out = fn.cast(out, dtype=dali.types.DALIDataType.UINT8)
    return out
```
should do as well.

**Comment by wangdada-love** [comment]
outstanding! thank you very much.
