### ISSUE TITLE
Ran of GPU memory when using Imagenet but not COCO-Stuff 2017

### ISSUE THREAD

**Issue by jackdaw213** [NVIDIA/DALI#5293]
### Version

1.32

### Describe the bug.

I have this DALI pipeline below:
```
@pipeline_def(device_id=0)
def dali_pipeline(image_dir, do_transform=True):
    images, _ = fn.readers.file(file_root=image_dir, 
                                     file_list=image_dir+"/labels.txt",
                                     random_shuffle=True, 
                                     name="Reader")
    
    images = fn.decoders.image(images, device="mixed", output_type=types.RGB)
    images = fn.python_function(images, function=rgb2lab)

    if do_transform:
        images = fn.resize(images, size=(320, 240))

    images = fn.transpose(images, perm=[2, 0, 1])
    
    color = images[1:, :, :]
    black = fn.expand_dims(images[0, :, :], axes=0)

    return black, color
```
Here is how I use it:
```
train_loader = DALIGenericIterator(
[dataset.ColorDataset.dali_pipeline(image_dir=args.train_dir,
                                    batch_size=args.batch_size,
                                    num_threads=args.num_workers)],
    ['black', 'color'],
    reader_name='Reader'
)

val_loader = DALIGenericIterator(
    [dataset.ColorDataset.dali_pipeline(image_dir=args.val_dir,
                                        batch_size=args.batch_size,
                                        num_threads=args.num_workers)],
    ['black', 'color'],
    reader_name='Reader'
)
```
In each folder there is a [dummy label file](https://github.com/NVIDIA/DALI/issues/5252#issuecomment-1868218850) for the fn.readers.file and the batch size is 32 for both of them. The code runs fine with [COCO-Stuff](https://github.com/nightrome/cocostuff) dataset (memory usage peaked at 9.5G). But ran out of memory after 1-2 minutes of running using [ImageNet](https://www.kaggle.com/c/imagenet-object-localization-challenge/overview/description) dataset with the output below:
```
Traceback (most recent call last):
  File "/home/jackdaw/GitHub/ImageColorization/main.py", line 140, in <module>
    train.train_model(model,
  File "/home/jackdaw/GitHub/ImageColorization/train.py", line 88, in train_model
    train_loss = train_epoch(cmodel, optimizer, loss, train_loader, device)
  File "/home/jackdaw/GitHub/ImageColorization/train.py", line 15, in train_epoch
    for _, data in enumerate(loader):
  File "/home/jackdaw/GitHub/ImageColorization/.conda/lib/python3.10/site-packages/nvidia/dali/plugin/pytorch.py", line 211, in __next__
    outputs = self._get_outputs()
  File "/home/jackdaw/GitHub/ImageColorization/.conda/lib/python3.10/site-packages/nvidia/dali/plugin/base_iterator.py", line 317, in _get_outputs
    outputs.append(p.share_outputs())
  File "/home/jackdaw/GitHub/ImageColorization/.conda/lib/python3.10/site-packages/nvidia/dali/pipeline.py", line 1065, in share_outputs
    return self._pipe.ShareOutputs()
RuntimeError: Critical error in pipeline:
Error when executing GPU operator Resize encountered:
Can't allocate 67108864 bytes on device 0.
Current pipeline object is no longer valid.
``` 
I also tried to lower the batch size to 1 and the gpu memory usage stayed at 9.2G

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @jackdaw213,

Thank you for reaching out.
Such high memory consumption is not expected. Can you tell what is the number of workers you use?
I'm asking because DALI creates one nvJPEG library instance under the hood of the mixed image decoder for each thread you use, and each of them consumes GPU memory. Can you try reducing the number to 3-5 and see if that helps?
Can you also check if that happened with the toy data set like https://github.com/NVIDIA/DALI_extra? If so can you provide a simple and self-contained script we can run on our end?

**Comment by jackdaw213** [comment]
Hello @JanuszL 
> Can you tell what is the number of workers you use?

I used 4 workers for both of the examples

> Can you also check if that happened with the toy data set like https://github.com/NVIDIA/DALI_extra? If so can you provide a simple and self-contained script we can run on our end?

Unfortunatly I'm not on my main machine right now so I can't test run with DALI_extra but I can provide a [stripped out version of my code](https://pastebin.pl/view/f10e2662) and the [requirements.txt](https://pastebin.pl/view/761be0f1) for conda enviroment

**Comment by jackdaw213** [comment]
Hello @JanuszL, 
Sorry for the delay, I was a bit busy for the past few days. However, I have managed to reproduce the problem with DALI_extra/db/coco/images where the memory usage jumped to 8.8GB for a single image. [Here is the script](https://pastebin.pl/view/254a96d0) I used and the [requirements.txt](https://pastebin.pl/view/761be0f1) for conda

**Comment by jackdaw213** [comment]
Hmm weird, I did some more testing with 3 datasets DALI_extra, COCO, Imagenet. For all of them, using batch size of 1 makes the GPU memory usage shot up to 8-9GB but the script crash with out of memory error ONLY when using DALI_extra and Imagenet (memory usage jumped to 9.5GB and slowly rised until it ran out)

**Comment by jackdaw213** [comment]
Hello @JanuszL,
I just ran the test and the memory usage peaked at `8GB`, plus ~`900MB` of data from your test above, everything seems to behave as expected. But it only crashes with anything else that's not COCO, weird

**Comment by JanuszL** [comment]
@jackdaw213,

> But it only crashes with anything else that's not COCO, weird

Is it also reproducible on the data from DALI_extra? Or only your internal data sets? Can you check what is the memory consumption for the data processing pipeline itself with the crashing data?

**Comment by jackdaw213** [comment]
@JanuszL 

> Is it also reproducible on the data from DALI_extra? Or only your internal data sets?

I can reproduce it with DALI_extra
> Can you check what is the memory consumption for the data processing pipeline itself with the crashing data?

With a batch size of 32, the memory usage of the data pipeline is around 4GB 
Crash log when running the training code using DALI_extra/db/coco/images dataset:
```
Traceback (most recent call last):
  File "/home/jackdaw/GitHub/ImageColorization/toy/test.py", line 226, in <module>
    train_loss = train_epoch(model, optimizer, loss, train_loader, torch.device("cuda:0"))
  File "/home/jackdaw/GitHub/ImageColorization/toy/test.py", line 147, in train_epoch
    output = model(black)
  File "/home/jackdaw/GitHub/ImageColorization/.conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jackdaw/GitHub/ImageColorization/.conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jackdaw/GitHub/ImageColorization/toy/test.py", line 134, in forward
    x = self.d1(x, inp)
  File "/home/jackdaw/GitHub/ImageColorization/.conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jackdaw/GitHub/ImageColorization/.conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jackdaw/GitHub/ImageColorization/toy/test.py", line 56, in forward
    return self.seq(cat)
  File "/home/jackdaw/GitHub/ImageColorization/.conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jackdaw/GitHub/ImageColorization/.conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jackdaw/GitHub/ImageColorization/.conda/lib/python3.10/site-packages/torch/nn/modules/container.py", line 215, in forward
    input = module(input)
  File "/home/jackdaw/GitHub/ImageColorization/.conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/jackdaw/GitHub/ImageColorization/.conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jackdaw/GitHub/ImageColorization/.conda/lib/python3.10/site-packages/torch/nn/modules/activation.py", line 101, in forward
    return F.relu(input, inplace=self.inplace)
  File "/home/jackdaw/GitHub/ImageColorization/.conda/lib/python3.10/site-packages/torch/nn/functional.py", line 1471, in relu
    result = torch.relu(input)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 600.00 MiB. GPU 0 has a total capacty of 9.77 GiB of which 209.56 MiB is free. Including non-PyTorch memory, this process has 9.55 GiB memory in use. Of the allocated memory 5.06 GiB is allocated by PyTorch, and 878.91 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by jackdaw213** [comment]
Hello @JanuszL 

I rerun the complete training code with ImageNet, and the memory usage jumps to 9.5GB then slowly increases (about 20-50MB/5-10s is this behavior expected?) until it runs out of memory. But if I use COCO, everything is suddenly fine, same batch size, same image input size, same everything. I only change the directory path and things start breaking down

Is there any way for me to profile the memory usage myself and then report back since you can't reproduce the problem on your side

**Comment by jackdaw213** [comment]
I upgraded all packages in the virtual env and ran the code again, unfortunately, the same behavior occurred. Here is the new [requirements.txt](https://github.com/NVIDIA/DALI/files/14503888/r.txt)

**Comment by JanuszL** [comment]
@jackdaw213,

When it comes to memory management DALI uses an internal memory pool that grows by allocating new pieces that are 2x bigger than the previous one, each time it runs out of free chunks that can be used. So you shouldn't see a growth of 50MB but rather bigger and bigger chunks allocated less and less frequently. Can you run again your pipeline without the training and check if the memory consumption saturates? In the pipeline you provided there is no randomness, however, the thing that changes is the input image size which affects the amount of memory each batch needs to allocate.
What you can experiment with is [preallocating the DALI memory pool](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/advanced_topics_performance_tuning.html#memory-pool-preallocation) or [releasing the unused memory](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/advanced_topics_performance_tuning.html#freeing-memory-pools).

**Comment by jackdaw213** [comment]
@JanuszL 

> Can you run again your pipeline without the training and check if the memory consumption saturates?

With COCO and DALI_extra the memory saturates at around 2GB while ImageNet stops at around 6-7GB. 

I also tried to run the complete pipeline and there is one strange behavior that I can only replicate with ImageNet. I tried to drop the batch size to 16, 8, and 4 in all 3 times the memory usage will hit 6GB after some time (lower batch size will reach it slower).

**Comment by jackdaw213** [comment]
I created a small dataset out of ImageNet (about 5000 images) and it also has high memory usage. Is it possible for me to compress this small dataset and share it with you via Google Drive ? Maybe you can have better luck reproducing the problem with this dataset?

**Comment by JanuszL** [comment]
Hi @jackdaw213,

With full ImageNet it is somehow expected. Images there can be really big (4k) and it affects the worst-case memory allocation. Also what I see is if either I remove `images = fn.python_function(images, function=rgb2lab)` or move it to after resize so it doesn't have to process full-sized images. It should help with the memory consumption (in my case it it is under 4 GB).

**Comment by jackdaw213** [comment]
@JanuszL 

After many brick walls, I think you cracked the case. I moved the `resize` function to after` fn.decoders` and the data pipeline only eats up 2.2GB of memory now. The training loop now stops at 9GB instead of crashing with OOM error. I will close the issue for now, thank you for your help

**Comment by JanuszL** [comment]
I'm happy that is helps.
