### ISSUE TITLE
Unrecognized image format

### ISSUE THREAD

**Issue by umie0128** [NVIDIA/DALI#5296]
### Version

1.31.0-cuda110

### Describe the bug.

![image](https://github.com/NVIDIA/DALI/assets/49420977/e5a1c57d-f81a-47ac-bd50-510f0ed35da3)
@JanuszL HI~
I am using fn. decoders. image for image processing and encountered this bug when batch processing images. I have used Image. open(). load() for image damage detection. But I still encounter this problem, and if I preprocess a single image, it won't trigger this problem.

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @umie0128,

Is it possible that just one of the images is corrupted? Can you provide a self-contained minimal repro for this problem?
