### ISSUE TITLE
Inference Model without converting TensorGPU to TensorCPU

### ISSUE THREAD

**Issue by vincentvic** [NVIDIA/DALI#5313]
Hello,
I would like to know if i'ts possible to run an inference on a deep learning model without converting the output TensorGPU in TensorCPU with as_cpu(). My model takes as input a tensor of shape (None, IMAGE_SIZE, IMAGE_SIZE, 3). The goal is to avoid to pass data from gpu to cpu.
For example:
```pipe.build()
  for _ in range(total_files): 
      start_pre_time = time.time()
      pipe_out = pipe.run()
      #frames = np.array(pipe_out[0][0].as_cpu()) => Not convert pipe_out in TensorCPU
      model.predict(pipe_out)```

**Comment by JanuszL** [comment]
Hi @vincentvic,

Thank you for reaching out. You can create a GPU array using cupy or use [DL FW plugin](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/framework_plugins.html) to create a native framework tensor out of it.
Please also check [the DALI TRITON backend](https://github.com/triton-inference-server/dali_backend) that will make this automatically for your model inference and even more.

**Comment by vincentvic** [comment]
Thank you for your prompt reply !
