### ISSUE TITLE
Stack a batch in one batch of this shape

### ISSUE THREAD

**Issue by vincentvic** [NVIDIA/DALI#5318]
### Describe the question.

Hello,
I'm running this code 
```
@pipeline_def(batch_size=64, num_threads=4, device_id=0)
def pipe_gds():
    arrayN = fn.readers.numpy(file_root='../video_reader/files/numpy2/', device='gpu')
    arrayN = fn.normalize(arrayN, mean=MEAN / SCALE, stddev=STD, scale=SCALE, dtype=types.FLOAT, device='gpu')
    arrayN = fn.resize(arrayN, device='gpu', resize_x=224, resize_y=224)
    return arrayN
```
And I would like to have as output of shape ([64,224,224,3]) but i have a shape of ([1, 224, 224, 3)] x 64.
How is it possible to 'stack' this list of numpy array to be aligned with the output shape expected by tensorflow
```
pipe = pipe_gds()
daliop = dali_tf.DALIDataset(pipeline=pipe, output_shapes=(64, 224, 224, 3),
                                     output_dtypes=(tf.float32) )
```

Thanks again

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @vincentvic,

Thank you for reaching out.
You don't need to stack tensors, The `DALIDataset` stacks samples into one tensor where the batch is one of the dimensions, what you need to do is remove the unnecessary dimension:
```
arrayN = fn.reshape(arrayN , src_dims=[1,2,3])
```

**Comment by vincentvic** [comment]
Thanks, but i'm not sure it's working.
This is my output for now:
```
 num_samples=64,
     shape=[(224, 224, 3), (224, 224, 3), ..., (224, 224, 3), (224, 224, 3)]),)
```
I'm reading a list of files (.npy) of shape (224,224,3)

**Comment by JanuszL** [comment]
I'm not sure if I understand your concern.
In the mentioned case you receive the batch of 64 samples, (224,224,3) each. When you output this batch from DALIDataset you should get shape=(64, 224, 224, 3). Also, I see that the Dataset can collapse `1` dimensions like in this toy example:
```
from nvidia.dali import pipeline_def
import numpy as np
import nvidia.dali.plugin.tf as dali_tf
import tensorflow as tf

batch_size=5

@pipeline_def
def test_pipe():
    a = np.zeros([1, 4, 5, 3])
    return a

pipe = test_pipe(batch_size=batch_size, num_threads=1, device_id=0)
shapes = ((batch_size, 4, 5, 3))
dtypes = (tf.float32)

with tf.device("/cpu:0"):
    data_set = dali_tf.DALIDataset(
        pipeline=pipe,
        batch_size=batch_size,
        output_shapes=shapes,
        output_dtypes=dtypes,
        device_id=0,
    )
print(next(iter(data_set)))```

**Comment by vincentvic** [comment]
ok thanks a lot; it's work ! Sorry for my confusing !
