### ISSUE TITLE
NumPy decoder

### ISSUE THREAD

**Issue by fversaci** [NVIDIA/DALI#5337]
### Describe the question.

Hi,

for our [Cassandra-DALI plugin](https://github.com/fversaci/cassandra-dali-plugin/tree/dev), we needed a NumPy decoder to decode `npy` files from memory into tensors. Since it's not already available (see #3726 ) we wrote a simple [one](https://github.com/fversaci/cassandra-dali-plugin/blob/dev/crs4/cpp/numpy_decoder.cc) using an extension of the already existing [`ReadTensor` function](https://github.com/NVIDIA/DALI/blob/30d2a0b1bf131787407e98b2e88682d7e0f279d8/dali/util/numpy.cc#L297).

I have a few questions about this.

1. The [`numpy.h`](https://github.com/NVIDIA/DALI/blob/83563a4b35f7498db8cd235db93258713678db4a/dali/util/numpy.h) header file does not seem to be available to the user (it's not being installed [here](https://github.com/NVIDIA/DALI/blob/83563a4b35f7498db8cd235db93258713678db4a/dali/util/CMakeLists.txt#L15)), so we included it in our code as [`dali_numpy.h`](https://github.com/fversaci/cassandra-dali-plugin/blob/6f4744a4c94adff9d73c5b2b38d20e2d7d15ed39/crs4/cpp/dali_numpy.h). Would it be possible to make it available for the users as well?
2. The original `ReadTensor` function always creates tensors in pinned memory. We want to be able to use it also in normal memory, so we extended `ReadTensor` to [`NewReadTensor`](https://github.com/fversaci/cassandra-dali-plugin/blob/6f4744a4c94adff9d73c5b2b38d20e2d7d15ed39/crs4/cpp/numpy.cc#L24), which also accepts a `bool pinned` argument. If that doesn't break anything you're using, it might be useful to have it directly in the original `ReadTensor` function.
3. We use `NewReadTensor` in the [decoder](https://github.com/fversaci/cassandra-dali-plugin/blob/6f4744a4c94adff9d73c5b2b38d20e2d7d15ed39/crs4/cpp/numpy_decoder.cc#L30) in a serial way. Is this function thread-safe, and could we use it in parallel as well?

P.S. If you need to test the NumPy decoder class, you can do so by running [this example](https://github.com/fversaci/cassandra-dali-plugin/tree/dev/examples/corel5k), which utilizes the multilabel [Corel-5k dataset](https://www.kaggle.com/datasets/parhamsalar/corel5k).

Thanks!

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @fversaci,

Thank you for reaching out.
> 1. The [`numpy.h`](https://github.com/NVIDIA/DALI/blob/83563a4b35f7498db8cd235db93258713678db4a/dali/util/numpy.h) header file does not seem to be available to the user (it's not being installed [here](https://github.com/NVIDIA/DALI/blob/83563a4b35f7498db8cd235db93258713678db4a/dali/util/CMakeLists.txt#L15)), so we included it in our code as [`dali_numpy.h`](https://github.com/fversaci/cassandra-dali-plugin/blob/6f4744a4c94adff9d73c5b2b38d20e2d7d15ed39/crs4/cpp/dali_numpy.h). Would it be possible to make it available for the users as well?

@szkarpinski, @klecki do you remember what was the reason for not shipping this file?

> 2. The original `ReadTensor` function always creates tensors in pinned memory. We want to be able to use it also in normal memory, so we extended `ReadTensor` to [`NewReadTensor`](https://github.com/fversaci/cassandra-dali-plugin/blob/6f4744a4c94adff9d73c5b2b38d20e2d7d15ed39/crs4/cpp/numpy.cc#L24), which also accepts a `bool pinned` argument. If that doesn't break anything you're using, it might be useful to have it directly in the original `ReadTensor` function.

It could be just an oversight. As I see this function is used only in tests. Feel free to post a PR that would fix this.

> 3. We use `NewReadTensor` in the [decoder](https://github.com/fversaci/cassandra-dali-plugin/blob/6f4744a4c94adff9d73c5b2b38d20e2d7d15ed39/crs4/cpp/numpy_decoder.cc#L30) in a serial way. Is this function thread-safe, and could we use it in parallel as well?

As far as I see the functions used are stateless and the only side effect I see is the change of the InputStream state. So if you want to share the same InputStream between multiple concurrent threads it won't work.

**Comment by klecki** [comment]
@JanuszL it looks like an oversight for me with regards to the numpy.h, but @azrael417 or @mzient may know more about it.

**Comment by fversaci** [comment]
Thanks @JanuszL and @klecki !

Then, if it's okay to ship 'numpy.h', I will prepare a PR to fix that and also to add 'bool pinned' to 'ReadTensor'.

**Comment by fversaci** [comment]
Hi,

I'm trying to compile DALI (using [docker builder](https://docs.nvidia.com/deeplearning/dali/main-user-guide/docs/compilation.html)) to prepare the PR, but i get an error.

Am doing something wrong?

I'm launching this
```bash
git clone --recursive https://github.com/NVIDIA/DALI
cd DALI/docker
CUDA_VERSION=12.2 CREATE_RUNNER=yes ./build.sh
```

which causes this
```
CMake Error at nvimgcodec_headers-subbuild/nvimgcodec_headers-populate-prefix/src/nvimgcodec_headers-populate-stamp/download-nvimgcodec_headers-populate.cmake:1
59 (message):
  Each download failed!

    error: downloading 'https://developer.download.nvidia.com/compute/nvimgcodec/redist/nvimgcodec/linux-x86_64/nvimgcodec-linux-x86_64-0.2.0.6-archive.tar.xz'
failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1



         --- LOG END ---
         error: downloading 'https://developer.download.nvidia.com/compute/nvimgcodec/redist/nvimgcodec/linux-x86_64/nvimgcodec-linux-x86_64-0.2.0.6-archive.tar
.xz' failed
         status_code: 1
         status_string: "Unsupported protocol"
         log:
         --- LOG BEGIN ---
         Protocol "https" not supported or disabled in libcurl

  Closing connection -1

[...]

gmake[2]: *** [nvimgcodec_headers-populate-prefix/src/nvimgcodec_headers-populate-stamp/nvimgcodec_headers-populate-download] Error 1
gmake[1]: *** [CMakeFiles/nvimgcodec_headers-populate.dir/all] Error 2
gmake: *** [all] Error 2

CMake Error at /usr/local/share/cmake-3.18/Modules/FetchContent.cmake:987 (message):
  Build step for nvimgcodec_headers failed: 2
Call Stack (most recent call first):
  /usr/local/share/cmake-3.18/Modules/FetchContent.cmake:1082:EVAL:2 (__FetchContent_directPopulate)
  /usr/local/share/cmake-3.18/Modules/FetchContent.cmake:1082 (cmake_language)
  cmake/Dependencies.common.cmake:293 (FetchContent_Populate)
  cmake/Dependencies.cmake:108 (include)
  CMakeLists.txt:293 (include)


-- Configuring incomplete, errors occurred!
See also "/opt/dali/build-docker-Release-122_x86_64/CMakeFiles/CMakeOutput.log".
See also "/opt/dali/build-docker-Release-122_x86_64/CMakeFiles/CMakeError.log".
```

**Comment by JanuszL** [comment]
Hi @fversaci,

Please add `REBUILD_BUILDERS=YES` to the `build.sh` invocation to rebuild cmake with https support (https://github.com/NVIDIA/DALI_deps/pull/99) needed to pull nvImageCodec.

**Comment by fversaci** [comment]
Hi, I've created the PR. Please have a look and let me know if it looks okay to you or if any changes are needed.

**Comment by fversaci** [comment]
Perfect, thanks!
