### ISSUE TITLE
Configure max image size

### ISSUE THREAD

**Issue by jpfeil** [NVIDIA/DALI#5424]
### Is this a new feature, an improvement, or a change to existing functionality?

Improvement

### How would you describe the priority of this feature request

Should have (e.g. Adoption is possible, but the performance shortcomings make the solution inferior).

### Please provide a clear description of problem this feature solves

The jpeg decoder sets a threshold for the image size. But I would like to try setting the threshold larger. Is it possible to make this a variable so that people with access to more GPU memory can process larger images?

`/opt/dali/dali/operators/decoder/jpeg/jpeg_mem.cc#line=183): Image too large: 831749472`

### Feature Description

From an end user perspective, you can set the max image size when building the pipeline.

### Describe your ideal solution

A variable that gets passed to the decoder to accept larger images.

### Describe any alternatives you have considered

Just skip large images.

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by jantonguirao** [comment]
@jpfeil Thank you for reporting this.
A few questions:
- Does the image get decoded eventually or your pipeline fails? Note that in DALI there is a hierarchy of decoders and when one fails the next one tries to handle the image. This error message comes from one of them (libjpeg-turbo based), but there's one more (OpenCV based), so I am curious if that one failed as well.
- Could you please share the image that fails so that I can check on my end?

**Comment by jpfeil** [comment]
Thanks, @jantonguirao. I didn't realize DALI could still process the larger images. I just figured it was skipping the larger images. The code block mentions failing fast to prevent an ungraceful exit, but I'm not really familiar with the DALI codebase. Let me check if the images are getting processed eventually.

` // Determine the output image size before attempting decompress to prevent
  // OOM'ing doing the decompress
  jpeg_calc_output_dimensions(&cinfo);

  int64 total_size = static_cast<int64>(cinfo.output_height) *
                     static_cast<int64>(cinfo.output_width) *
                     static_cast<int64>(cinfo.num_components);
  // Some of the internal routines do not gracefully handle ridiculously
  // large images, so fail fast.
  if (cinfo.output_width <= 0 || cinfo.output_height <= 0) {
    ERROR_LOG << "Invalid image size: " << cinfo.output_width << " x "
              << cinfo.output_height << std::endl;
    return nullptr;
  }
  if (total_size >= (1LL << 29)) {
    ERROR_LOG << "Image too large: " << total_size << std::endl;
    return nullptr;
  }`

**Comment by jantonguirao** [comment]
Yes, this decoder fails, but after that there's an opencv based decoder, so I am curious if that one is able to decode the large image
