### ISSUE TITLE
ModuleNotFoundError: No module named 'nvidia.dali.python_function_plugin'

### ISSUE THREAD

**Issue by themattinthehatt** [NVIDIA/DALI#5430]
### Version

1.36

### Describe the bug.

My build starting failing yesterday due to the import error in the issue title. I expected to be able to pip install DALI and then import DALIGenericIterator without an error.

### Minimum reproducible example

```shell
pip install nvidia-dali-cuda110
python -c "from nvidia.dali.plugin.pytorch import DALIGenericIterator"
```

### Relevant log output

```shell
----> 1 from nvidia.dali.plugin.pytorch import DALIGenericIterator

File /home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/nvidia/dali/__init__.py:20
     17 __cuda_version__ = int('11.8.89'.replace('.', ''))
     18 __git_sha__ = 'e2ae685702638e3f8fae8091344f0f7ea045a1f9'
---> 20 from . import ops
     21 from . import pipeline
     22 from . import tensors

File /home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/nvidia/dali/ops/__init__.py:22
     19 import warnings
     20 from itertools import count
---> 22 import nvidia.dali.python_function_plugin
     23 from nvidia.dali import backend as _b
     24 from nvidia.dali import fn as _functional

ModuleNotFoundError: No module named 'nvidia.dali.python_function_plugin'
```

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @themattinthehatt,

Thank you for reporting that. I see the problem affects the package from PyPI. Please try out the one hosted on NVIDIA devzone (by adding `--extra-index-url https://pypi.nvidia.com`) until we rootcause and fix the issue.

**Comment by JanuszL** [comment]
The PyPI issue has been fixed. Please try to reinstall DALI from PyPI again.

**Comment by themattinthehatt** [comment]
yes, can verify that it is working now, thank you for the quick fix!!
