### ISSUE TITLE
Encountered some issues when using mirror flip

### ISSUE THREAD

**Issue by umie0128** [NVIDIA/DALI#5446]
### Describe the question.

@JanuszL Hi~
I want to use mirror flipping in semantic segmentation, but there are left turn arrows and right turn arrows in categories. After flipping the mirror, their category becomes problematic. For example, the left turning arrow in the image becomes a right turning arrow, but remains unchanged on the label. How can I solve this problem.

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @umie0128,

Thank you for reaching out. That is a very interesting question regarding data processing.
I guess you can write [a custom operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/custom_operations/index.html) that would accept the flip value and the labels as the input and based on that change `the left turning arrow` into `the right turning arrow` and be no-op for other labels.

**Comment by umie0128** [comment]
@JanuszL  Thanks！
