### ISSUE TITLE
The correct way of using rand_augment

### ISSUE THREAD

**Issue by CoinCheung** [NVIDIA/DALI#5482]
### Describe the question.

I have a code, part of which is like this:
![image](https://github.com/NVIDIA/DALI/assets/22693362/ccb70784-69f9-450e-a8bc-b56ebb90b33b)
And this:
![image](https://github.com/NVIDIA/DALI/assets/22693362/84251d62-cc9d-4042-9a36-2c8e0f76cf93)

When I launch training, The program just got killed without any error message:
![image](https://github.com/NVIDIA/DALI/assets/22693362/dfd7846b-daff-47e5-ad12-584115508588)

Do you know what is the cause of this, and how could I solve this problem? 

I have tried to shrink the batchsize so that oom is not happening here.

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @CoinCheung,

Thank you for reaching out. Can you provide [a minimal and self-contained reproduction example](https://github.com/NVIDIA/DALI?tab=readme-ov-file#reporting-problems-asking-questions) we can run on our end (even using a toy data from https://github.com/NVIDIA/DALI_extra) so we know that we are talking about the same issue?

**Comment by CoinCheung** [comment]
Sorry for not leave a message for so long. I am closing this since I do not have gpus to use for these days, and I will open a new one when I am ready to solve this problem.
