### ISSUE TITLE
Dealing with corrupt videos using experimental video decoder

### ISSUE THREAD

**Issue by Tomsen1410** [NVIDIA/DALI#5489]
### Version

1.35

### Describe the bug.

I am using `fn.experimental.decoders.video` to decode videos stored in a web dataset. However, there exist files in my dataset that are corrupt and/or can't be openend by DALI. However, instead of throwing an error the entire process halts with a segmentation fault error when the decoder sees a corrupt video:

```
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7f0ccc298d00] moov atom not found
[/opt/dali/dali/operators/reader/loader/video/frames_decoder.cc:237] Failed to open video file memory filedue to Invalid data found when processing input
Segmentation fault (core dumped)
```

Essentially, this issue is similar to #5155, but for the experimental decoder instead of the video reader.

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @Tomsen1410,

Thank you for reporting this.
Can you tell if the videos are indeed corrupted by opening them in FFmpeg or this is just a DALI behavior?
DALI operators work in the push mode, processing the whole batch at the time. So when DALi fails to process a given sample in the batch it cannot ask for more to replace the faulty one, so it throws an error. The only solution that comes to my mind is to provide an empty sample or zeroed one (as some operators may not handle empty tensors gracefully).

**Comment by JanuszL** [comment]
You can check [this thread](https://stackoverflow.com/questions/10957412/fastest-way-to-extract-frames-using-ffmpeg) and see if FFmpeg can decode and save frames to a file.

**Comment by Tomsen1410** [comment]
Ok, I have ran ffmpeg on the corrupted file and it throws the same error:
```
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x559fa2226100] moov atom not found
[in#0 @ 0x559fa2225fc0] Error opening input: Invalid data found when processing input
Error opening input file /path/to/file.mp4.
Error opening input files: Invalid data found when processing input
```

**Comment by JanuszL** [comment]
If FFmpeg cannot handle the video correctly I don't think we can do more than that. As you are using webdataset, you can manually edit the index file generated by `wds2idx.py` script to skip the mentioned sample. I also noticed that DALI doesn't provide a meaningful error message (ad crashes instead of raising an expectation) when it encounters a faulty file. Can you recheck the DALI nightly build once https://github.com/NVIDIA/DALI/pull/5491 is merged, check the offset to the faulty sample in the webdataset, and adjust the index file?

**Comment by Tomsen1410** [comment]
Yes, that is exactly the Problem. I have no way of catching the error and the entire training process stops.

**Comment by JanuszL** [comment]
1.39 and 1.40 are public. Closing.
