### ISSUE TITLE
No matching distribution found for nvidia-dalipip

### ISSUE THREAD

**Issue by hetong007** [NVIDIA/DALI#55]
By following the instruction to install from pip, I met the following error 

```
$ pip install --extra-index-url https://developer.download.nvidia.com/compute/redist nvidia-dalipip install
Looking in indexes: https://pypi.org/simple, https://developer.download.nvidia.com/compute/redist
Collecting nvidia-dalipip
  Could not find a version that satisfies the requirement nvidia-dalipip (from versions: )
No matching distribution found for nvidia-dalipip
```

Also, visiting `https://developer.download.nvidia.com/` gives me a `404 - Not Found` error.

**Comment by cliffwoolley** [comment]
Your pip install command has an extra `pip install` pasted at the end by accident.

It's expected that the developer.download.nvidia.com site is not indexed.
