### ISSUE TITLE
How to extract all elements of sequential numpy file?

### ISSUE THREAD

**Issue by noamsgl** [NVIDIA/DALI#5543]
### Describe the question.

Hi,

I am using `fn.readers.numpy(files=file_names)` to read a list of `.npy` files.
Each file includes a chunk of frames.
Each file has a 3D layout `'FCH' (frame, channel, height)` where `C` and `H` are constant but `F` might differ between files.

I would like to instruct DALI that each `CH` slice should be an individual sample on the output.

I have tried to use `nvidia.dali.fn.element_extract` however this requires me to determine `element_map` in advance and request specific indices. How can I instead extract all the elements of each file, essentially dechunking and then rebatching with the intended training batch size?

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @noamsgl,

Thank you for reaching out.
First of all, I recommend using [`the numpy reader`](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.readers.numpy.html) as it can decode the numpy files and convert them to DALI tensors. If you want to access particular parts of it, please check the [indexing and slicing](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/indexing.html) part of the documentation.

**Comment by noamsgl** [comment]
Hi, thank you for your response and support.

I tried following the example provided. I can't tell if it's working or not because when trying to run or iterate on the pipeline I am getting out of memory errors (cannot allocate X bytes on device) from the Numpy reader data node.

I suspect by changing the chunking and batch size this could be resolved. My whole dataset is 700 GB of raw numpy on disk. Each frame takes about 1MB. My current GPU has 10GB memory capacity.

What is your recommended chunk size for storing the numpy data on disk and DALI batch size in order to avoid memory issues when loading and also expect highest throughput?

**Comment by JanuszL** [comment]
Hi @noamsgl,

Our general recommendation is usually to use the biggest batch that fits your memory. I would start with a batch size of 1 and try to increase it gradually. Also, keep in mind that each operation inside the pipeline consumes the GPU memory so the more you have it the more memory it uses.

**Comment by noamsgl** [comment]
I tested your suggestions for slicing and compared it to saving each numpy segment as a separate file and the latter option was a lot faster. So I will save each file separately for now.
Thanks!
