### ISSUE TITLE
How to use the same fn.random_resized_crop in the same sequence

### ISSUE THREAD

**Issue by ggbondcxl** [NVIDIA/DALI#5547]
### Describe the question.

hi～
I have tried to dali is fast for data preprocessing, but I have a problem, due to implicit batch processing in define gragh, I have a problem with sequence processing, due to shuffle=false, fn.readers.file reads out the images in order, but I'm eight images in a sequence, processing 5 batch is 40 But I need to apply exactly the same random_resized_crop in the same sequence what should I do, the labels are the same in the same sequence, here is how I implemented it：
```python
class VideoPipe(Pipeline):
    def __init__(self, batch_size, num_threads, device_id, file_list, local_crops_number):
        super(VideoPipe, self).__init__(batch_size, num_threads, device_id)
        self.input = fn.readers.file(file_list=file_list, random_shuffle=False)
        self.images = fn.decoders.image(self.input[0], device="mixed", name="Reader")
        self.labels = self.input[1]
        self.local_crops_number = local_crops_number

    def define_graph(self):
        sequences = self.images
        labels = self.labels
        # init_aug
        frames = fn.transpose(sequences, perm=[2, 0, 1])
        # frames = fn.normalize(frames, mean=0.0, stddev=255.0, device="gpu")
        frames = fn.random_resized_crop(frames, size=300, device="gpu", random_area=[0.2, 1.0])

        # output0 = self.process_global(frames)
        # local_outputs = [self.process_local(frames) for _ in range(self.local_crops_number)]
        output0 = frames
        local_outputs = [frames for _ in range(self.local_crops_number)]
        return [output0] + local_outputs

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by jantonguirao** [comment]
In the code above, you are decoding a single image per sample (with `fn.decoders.image`). So in total you'd have `batch_size` images being processed in the batch. Do you mean that you'd like to apply the same cropping window to all of them?

**Comment by JanuszL** [comment]
If you want to read the sequence of 40 frames and apply the same random_resized_crop to them, then
what you can do is read a batch of 40 images, and generate the cropping window using (`nvidia.dali.fn.random_crop_generator`)[https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.random_crop_generator.html], broadcast the first value of the cropping window parameters to all sample using [`permute_batch` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.permute_batch.html), and decode them with ROI and resize, 
```
raw_imgs = fn.readers.file(file_list=file_list, random_shuffle=False)
crop_anchor, crop_shape= fn.random_crop_generator()
crop_anchor = fn.permute_batch(crop_anchor, indices=batch_size * [0])
crop_shape = fn.permute_batch(crop_shape , indices=batch_size * [0])
images = fn.decoders.image_slice(raw_imgs, crop_anchor, crop_shape)
images = = fn.resize(images, resize_x=300, resize_y=300)
```
You can merge them into sequence outside of the pipeline as DALI cannot change the batch size during the processing.

**Comment by ggbondcxl** [comment]
> If you want to read the sequence of 40 frames and apply the same random_resized_crop to them, then如果您想要读取 40 帧的序列并对它们应用相同的 random_resized_crop，则 what you can do is read a batch of 40 images, and generate the cropping window using [`nvidia.dali.fn.random_crop_generator`](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.random_crop_generator.html), broadcast the first value of the cropping window parameters to all sample using [`permute_batch` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.permute_batch.html), and decode them with ROI and resize,你可以做的是读取一批 40 张图片，并使用 `nvidia.dali.fn.random_crop_generator` 生成裁剪窗口，使用 `permute_batch` 运算符将裁剪窗口参数的第一个值广播到所有样本，并使用 ROI 和调整大小对它们进行解码
> 
> ```
> raw_imgs = fn.readers.file(file_list=file_list, random_shuffle=False)
> shapes = fn.peek_image_shape(encoded)
> crop_anchor, crop_shape= fn.random_crop_generator(shapes )
> crop_anchor = fn.permute_batch(crop_anchor, indices=batch_size * [0])
> crop_shape = fn.permute_batch(crop_shape , indices=batch_size * [0])
> images = fn.decoders.image_slice(raw_imgs, crop_anchor, crop_shape)
> images = = fn.resize(images, resize_x=300, resize_y=300)
> ```
> 
> You can merge them into sequence outside of the pipeline as DALI cannot change the batch size during the processing.您可以将它们合并成序列，而不是在管道外部，因为 DALI 在处理过程中无法更改批处理大小。

So if my file list is in the form of /dataset/venice-dataset-15min/frame_44956.jpg 5619, I have a way to 8 images to form a sequence, is the batch made up of sequences, do I perform the same cropping operation on individual sequences, and do I need to apply different this to different sequences? external source, I'm a newbie, can you give me an example, thanks!

**Comment by JanuszL** [comment]
If you want to process multiple sequences in the batch just adjust `permute_batch` `indices` argument` to asure that cropping parameters are broadcasted accordingly.
```
crop_shape = fn.permute_batch(crop_shape , indices=first_seq_lenght * [0] + second_seq_lenght * [first_sequence_lenght])
```

**Comment by ggbondcxl** [comment]
> = =
```python
class VideoPipe(Pipeline):
    def __init__(self, batch_size, num_threads, device_id, file_list, local_crops_number):
        super(VideoPipe, self).__init__(batch_size, num_threads, device_id)
        self.input = fn.readers.file(file_list=file_list, random_shuffle=False)
        shapes = fn.peek_image_shape(self.input[0])
        crop_anchor, crop_shape= fn.random_crop_generator(shapes, random_area=[0.2, 1.0])
        crop_anchor = fn.permute_batch(crop_anchor, indices=batch_size * [0])
        crop_shape = fn.permute_batch(crop_shape , indices=batch_size * [0])
        images = fn.decoders.image_slice(self.input[0], crop_anchor, crop_shape)
        self.image = fn.resize(images, resize_x=300, resize_y=300)
    
        # self.images = fn.decoders.image(self.input[0], device="mixed", name="Reader")
        self.labels = self.input[1]
        self.local_crops_number = local_crops_number

    def define_graph(self):
        sequences = self.images
        labels = self.labels
        # init_aug
        #frames = fn.transpose(sequences, perm=[2, 0, 1])
        # frames = fn.normalize(frames, mean=0.0, stddev=255.0, device="gpu")
        #frames = fn.random_resized_crop(frames, size=300, device="gpu", random_area=[0.2, 1.0])

        # output0 = self.process_global(frames)
        # local_outputs = [self.process_local(frames) for _ in range(self.local_crops_number)]
        output0 = sequences
        local_outputs = [sequences for _ in range(self.local_crops_number)]
        return [output0] + local_outputs
This code has this problem how do I fix it?
![Uploading 截屏2024-07-04 19.34.40.png…]()

**Comment by ggbondcxl** [comment]
> If you want to process multiple sequences in the batch just adjust `permute_batch` `indices` argument` to asure that cropping parameters are broadcasted accordingly.
> 
> ```
> crop_shape = fn.permute_batch(crop_shape , indices=first_seq_lenght * [0] + second_seq_lenght * [first_sequence_lenght])
> ```
This is my current code, some times it works well, some times it gives an error, why is that, also assuming my batchsize is 40, how do I get 0-7 images to be a random crop and 8-15 to be one all the way up to 31-39?
Here's my error：images = fn.decoders.image_slice(self.input[0], crop_anchor, crop_shape)

encountered:

Error in thread 0: The cropping window [314..1375, 27..886] is not valid for image dimensions [1080 x 1920]. File: /dataset/venice-dataset-15min/frame_42986.jpg
Current pipeline object is no longer valid.

Do I need to set the policy for fn.random_crop_generator？thanks！
``` python
class VideoPipe(Pipeline):
    def __init__(self, batch_size, num_threads, device_id, file_list, local_crops_number):
        super(VideoPipe, self).__init__(batch_size, num_threads, device_id)
        self.input = fn.readers.file(file_list=file_list, random_shuffle=False)
        shapes = fn.peek_image_shape(self.input[0])
        crop_anchor, crop_shape= fn.random_crop_generator(shapes, random_area=[0.2, 1.0])
        crop_anchor = fn.permute_batch(crop_anchor, indices=batch_size * [0])
        crop_shape = fn.permute_batch(crop_shape , indices=batch_size * [0])
        images = fn.decoders.image_slice(self.input[0], crop_anchor, crop_shape)
        self.images = fn.resize(images, resize_x=300, resize_y=300)
    
        # self.images = fn.decoders.image(self.input[0], device="mixed", name="Reader")
        self.labels = self.input[1]
        self.local_crops_number = local_crops_number

    def define_graph(self):
        sequences = self.images
        labels = self.labels
        # init_aug
        frames = fn.transpose(sequences, perm=[2, 0, 1])
        # frames = fn.normalize(frames, mean=0.0, stddev=255.0, device="gpu")
        #frames = fn.random_resized_crop(frames, size=300, device="gpu", random_area=[0.2, 1.0])

        # output0 = self.process_global(frames)
        # local_outputs = [self.process_local(frames) for _ in range(self.local_crops_number)]
        output0 = frames
        local_outputs = [frames for _ in range(self.local_crops_number)]
        return [output0] + local_outputs

**Comment by ggbondcxl** [comment]
> > If you want to process multiple sequences in the batch just adjust `permute_batch` `indices` argument` to asure that cropping parameters are broadcasted accordingly.
> > ```
> > crop_shape = fn.permute_batch(crop_shape , indices=first_seq_lenght * [0] + second_seq_lenght * [first_sequence_lenght])
> > ```
> 
> This is my current code, some times it works well, some times it gives an error, why is that, also assuming my batchsize is 40, how do I get 0-7 images to be a random crop and 8-15 to be one all the way up to 31-39? Here's my error：images = fn.decoders.image_slice(self.input[0], crop_anchor, crop_shape)
> 
> encountered:
> 
> Error in thread 0: The cropping window [314..1375, 27..886] is not valid for image dimensions [1080 x 1920]. File: /dataset/venice-dataset-15min/frame_42986.jpg Current pipeline object is no longer valid.
> 
> Do I need to set the policy for fn.random_crop_generator？thanks！
> 
> ```python
> class VideoPipe(Pipeline):
>     def __init__(self, batch_size, num_threads, device_id, file_list, local_crops_number):
>         super(VideoPipe, self).__init__(batch_size, num_threads, device_id)
>         self.input = fn.readers.file(file_list=file_list, random_shuffle=False)
>         shapes = fn.peek_image_shape(self.input[0])
>         crop_anchor, crop_shape= fn.random_crop_generator(shapes, random_area=[0.2, 1.0])
>         crop_anchor = fn.permute_batch(crop_anchor, indices=batch_size * [0])
>         crop_shape = fn.permute_batch(crop_shape , indices=batch_size * [0])
>         images = fn.decoders.image_slice(self.input[0], crop_anchor, crop_shape)
>         self.images = fn.resize(images, resize_x=300, resize_y=300)
>     
>         # self.images = fn.decoders.image(self.input[0], device="mixed", name="Reader")
>         self.labels = self.input[1]
>         self.local_crops_number = local_crops_number
> 
>     def define_graph(self):
>         sequences = self.images
>         labels = self.labels
>         # init_aug
>         frames = fn.transpose(sequences, perm=[2, 0, 1])
>         # frames = fn.normalize(frames, mean=0.0, stddev=255.0, device="gpu")
>         #frames = fn.random_resized_crop(frames, size=300, device="gpu", random_area=[0.2, 1.0])
> 
>         # output0 = self.process_global(frames)
>         # local_outputs = [self.process_local(frames) for _ in range(self.local_crops_number)]
>         output0 = frames
>         local_outputs = [frames for _ in range(self.local_crops_number)]
>         return [output0] + local_outputs
> ```

This seems to be due to the fact that by default, the nvidia.dali.fn.decoders.image_slice() operator uses normalized coordinates and “WH” ordering for the slice argument. But I don't really know how to fix it ？？

**Comment by jantonguirao** [comment]
You can add `axis_names="HW"` to slice:
```
images = fn.decoders.image_slice(self.input[0], crop_anchor, crop_shape, axis_names="HW")
```
That should help

**Comment by ggbondcxl** [comment]
> You can add `axis_names="HW"` to slice:您可以将 `axis_names="HW"` 添加到切片中：
> 
> ```
> images = fn.decoders.image_slice(self.input[0], crop_anchor, crop_shape, axis_names="HW")
> ```
> 
> That should help 那应该会有所帮助
It works！
How to utilize fn.permute_batch to complete the batch with indices 0-7 as crop_anchor, crop_shape and 8-15 as the second crop_anchor, crop_shape? Thanks

**Comment by ggbondcxl** [comment]
> You can add `axis_names="HW"` to slice:
> 
> ```
> images = fn.decoders.image_slice(self.input[0], crop_anchor, crop_shape, axis_names="HW")
> ```
> 
> That should help

It works！
How to utilize fn.permute_batch to complete the batch with indices 0-7 as crop_anchor, crop_shape and 8-15 as the second crop_anchor, crop_shape? Thanks

**Comment by JanuszL** [comment]
```
        crop_anchor = fn.permute_batch(crop_anchor, indices=8 * [0] + 8 * [1])
        crop_shape = fn.permute_batch(crop_shape , indices=8 * [0] + 8 * [1])
```
Should populate cropping parameters with two sets of 8 repeated values.

**Comment by ggbondcxl** [comment]
> ```
>         crop_anchor = fn.permute_batch(crop_anchor, indices=8 * [0] + 8 * [1])
>         crop_shape = fn.permute_batch(crop_shape , indices=8 * [0] + 8 * [1])
> ```
> 
> Should populate cropping parameters with two sets of 8 repeated values.
Here is my complete code, but it throws the error TypeError: “DataNode” was used in conditional context - it might have been used in truth evaluation for `if` statement, logical expression or cast to a boolean. To use conditional execution via `if` statements you need to specify `enable_conditionals=True` in `@nvidia.dali. pipeline_def` decorator. You can read more about conditional execution in specific section of the Pipeline documentation. Bool conversion can be achieved with the `cast` operator. What should I do before I can use if to do coin operations properly?
``` python
class VideoPipe(Pipeline):
    def __init__(self, batch_size, num_threads, device_id, file_list, local_crops_number, frame_per_clip):
        super(VideoPipe, self).__init__(batch_size, num_threads, device_id)
        self.input = fn.readers.file(file_list=file_list, random_shuffle=False)
        shapes = fn.peek_image_shape(self.input[0])
        # crop_anchor, crop_shape= fn.random_crop_generator(shapes, random_area=[0.2, 1.0])
        # crop_anchor = fn.permute_batch(crop_anchor, indices=batch_size * [0])
        # crop_shape = fn.permute_batch(crop_shape , indices=batch_size * [0])
        # print(crop_shape)
        num_clips = batch_size // frame_per_clip
        indices = np.concatenate([i * np.ones(frame_per_clip, dtype=int) for i in range(num_clips)])

        # 将 indices 转换为 Python 列表
        indices = indices.tolist()
        # print(indices)

        crop_anchor, crop_shape= fn.random_crop_generator(shapes, random_area=[0.2, 1.0])
        crop_anchor = fn.permute_batch(crop_anchor, indices=indices)
        crop_shape = fn.permute_batch(crop_shape , indices=indices)


        images = fn.decoders.image_slice(self.input[0], crop_anchor, crop_shape, device="mixed", axis_names="HW")
        self.images = fn.resize(images, resize_x=300, resize_y=300, device="gpu")
    
        # self.images = fn.decoders.image(self.input[0], device="mixed", name="Reader")
        self.labels = self.input[1]
        self.local_crops_number = local_crops_number

    def define_graph(self):
        sequences = self.images
        labels = self.labels
        # init_aug
        frames = fn.transpose(sequences, perm=[2, 0, 1])
        frames = fn.normalize(frames, mean=0.0, stddev=255.0, device="gpu")
        #frames = fn.random_resized_crop(frames, size=300, device="gpu", random_area=[0.2, 1.0])

        output0 = self.process_global(frames)
        # local_outputs = [self.process_local(frames) for _ in range(self.local_crops_number)]
        # output0 = frames
        local_outputs = [frames for _ in range(self.local_crops_number)]
        return [output0] + local_outputs

    def process_local(self, frames):
        local = fn.random_resized_crop(frames, size=112, device="gpu", random_area=[0.05, 0.4])
        apply_color_twist_local = fn.random.coin_flip(probability=0.8)
        local_frame1 = fn.transpose(local, perm=[1, 2, 0])
        local_1 = fn.color_twist(local_frame1, brightness=fn.random.uniform(range=[0.6, 1.4]), 
                                  contrast=fn.random.uniform(range=[0.6, 1.4]), 
                                  saturation=fn.random.uniform(range=[0.8, 1.2]), 
                                  hue=fn.random.uniform(range=[-0.1, 0.1]), device="gpu")
        local_1 = local_1 * apply_color_twist_local + local_frame1 * (1 - apply_color_twist_local)
        grayscale_coin_local = fn.random.coin_flip(probability=0.2)
        local_1 = fn.cast(local_1, dtype=types.UINT8, device="gpu")
        gray_frame_local = fn.color_space_conversion(local_1, image_type=types.RGB, output_type=types.GRAY, device="gpu")
        local_1 = local_1 * (1 - grayscale_coin_local) + gray_frame_local * grayscale_coin_local
        local_1 = fn.gaussian_blur(local_1, window_size=5, sigma=0.5, device="gpu")
        # global_1 = fn.transpose(global_1, perm=[0, 3, 1, 2])
        local_1 = fn.cast(local_1, dtype=types.UINT8, device="gpu")
        local_output = fn.crop_mirror_normalize(local_1, device="gpu",
                                            output_layout="CHW",
                                            mean = [0.485, 0.456, 0.406],
        std = [0.229, 0.224, 0.225])
        return local_output
    
    def process_global(self, frames):
        # vid_crop
        gc_frame1 = fn.random_resized_crop(frames, size=224, device="gpu", random_area=[0.4, 1.0])
        coin = fn.random.coin_flip(probability=0.5)
        if coin:
            gc_frame1 = fn.flip(gc_frame1, horizontal=1, device="gpu")

        # global_transfo1
        coin = fn.random.coin_flip(probability=0.8)
        if coin:
            gc_frame1 = fn.transpose(gc_frame1, perm=[1, 2, 0])
            global_1 = fn.color_twist(gc_frame1, bbrightness=0.4, contrast=0.4, saturation=0.2, hue=0.1, device="gpu")
        
        coin = fn.random.coin_flip(probability=0.2)
        if coin:
            global_1 = fn.color_space_conversion(global_1, image_type=types.RGB, output_type=types.GRAY)

        coin = fn.random.coin_flip(probability=0.1)
        if coin:
            global_1 = fn.gaussian_blur(global_1, sigma=(0.1, 2.0))

        global_output = fn.normalize(global_1)
        return global_output

**Comment by ggbondcxl** [comment]
> Please check [this section of the documentation](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/pipeline.html#conditional-execution) and make sure that `enable_conditionals=True`.

I have followed the documentation, below is my code, I am using fn.color_space_conversion with Assert on “IsType<uint8_t>(input.type())” failed: color space conversion only accepts uint8 tensors error, if I use global_1 = fn.cast(global_1, dtype=types.UINT8, device=“gpu”) then RuntimeError occurs: IsDenseTensor()” Assert Fail: The batch must be representable as a tensor - it must have a uniform shape and be allocated in contiguous memory.

```python
@pipeline_def(batch_size=80, num_threads=2 , device_id=0 ,enable_conditionals=True)
def VideoPipe(total_picture, file_list, local_crops_number, frame_per_clip):
    input = fn.readers.file(file_list=file_list, random_shuffle=False)
    shapes = fn.peek_image_shape(input[0])
    # crop_anchor, crop_shape= fn.random_crop_generator(shapes, random_area=[0.2, 1.0])
    # crop_anchor = fn.permute_batch(crop_anchor, indices=batch_size * [0])
    # crop_shape = fn.permute_batch(crop_shape , indices=batch_size * [0])
    # print(crop_shape)
    num_clips = total_picture // frame_per_clip
    indices = np.concatenate([i * np.ones(frame_per_clip, dtype=int) for i in range(num_clips)])

    # 将 indices 转换为 Python 列表
    indices = indices.tolist()
    # print(indices)

    crop_anchor, crop_shape= fn.random_crop_generator(shapes, random_area=[0.2, 1.0])
    crop_anchor = fn.permute_batch(crop_anchor, indices=indices)
    crop_shape = fn.permute_batch(crop_shape , indices=indices)


    images = fn.decoders.image_slice(input[0], crop_anchor, crop_shape, device="mixed", axis_names="HW") #HWC
    images = fn.resize(images, resize_x=300, resize_y=300, device="gpu") #HWC

    # self.images = fn.decoders.image(self.input[0], device="mixed", name="Reader")
    labels = input[1]
    local_crops_number = local_crops_number

    frames = fn.transpose(images, perm=[2, 0, 1]) #CHW
    frames = fn.normalize(frames, mean=0.0, stddev=255.0, device="gpu") #CHW

    gc_frame1 = fn.random_resized_crop(frames, size=224, device="gpu", random_area=[0.4, 1.0])#CHW
    # gc_frame1 = fn.cast(gc_frame1, dtype=types.UINT8, device="gpu")
    coin = fn.random.coin_flip(probability=0.5)
    if coin:
        gc_frame1 = fn.flip(gc_frame1, horizontal=1, device="gpu")#CHW
    else:
        gc_frame1 = gc_frame1#CHW

    # global_transfo1
    coin = fn.random.coin_flip(probability=0.8)
    if coin:
        gc_frame1 = fn.transpose(gc_frame1, perm=[1, 2, 0])#HWC
        global_1 = fn.color_twist(gc_frame1, brightness=0.4, contrast=0.4, saturation=0.2, hue=0.1, device="gpu")#HWC
    else:
        global_1 = gc_frame1#CHW
        global_1 = fn.transpose(global_1, perm=[1, 2, 0])#HWC
    
    coin = fn.random.coin_flip(probability=0.2)
    # global_1 = fn.cast(global_1, dtype=types.UINT8, device="gpu")
    if coin:
        global_1 = fn.color_space_conversion(global_1, image_type=types.RGB, output_type=types.GRAY, device="gpu")
    else:
        global_1 = global_1

    # coin = fn.random.coin_flip(probability=0.1)
    # if coin:
    #     global_1 = fn.gaussian_blur(global_1, sigma=(0.1, 2.0))
    # else:
    #     global_1 = global_1

    # output = fn.normalize(global_1)
    output = global_1
    return output

**Comment by JanuszL** [comment]
Hi @ggbondcxl,

The:
```global_1 = fn.cast(global_1, dtype=types.UINT8, device=“gpu”)```
is the way to go. The error you see later `RuntimeError occurs: IsDenseTensor()” Assert Fail: The batch must be representable as a tensor - it must have a uniform shape and be allocated in contiguous memory.` is caused by the framework iterator you want to use on top of DALI. When called it attempts to convert/coalesce the DALI tensor list to a single tensor (as most of the deep learning framework data loaders do). However, if the batch is not uniform in shape it fails. What you can do it to either [`pad`](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.pad.html#nvidia.dali.fn.pad) batch or use [ragged iterator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/plugins/pytorch_plugin_api.html#nvidia.dali.plugin.pytorch.DALIRaggedIterator) which returns a set of separate tensors.

**Comment by ggbondcxl** [comment]
> Hi @ggbondcxl,
> 
> The: 冠: `global_1 = fn.cast(global_1, dtype=types.UINT8, device=“gpu”)` is the way to go. The error you see later `RuntimeError occurs: IsDenseTensor()” Assert Fail: The batch must be representable as a tensor - it must have a uniform shape and be allocated in contiguous memory.` is caused by the framework iterator you want to use on top of DALI. When called it attempts to convert/coalesce the DALI tensor list to a single tensor (as most of the deep learning framework data loaders do). However, if the batch is not uniform in shape it fails. What you can do it to either [`pad`](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.pad.html#nvidia.dali.fn.pad) batch or use [ragged iterator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/plugins/pytorch_plugin_api.html#nvidia.dali.plugin.pytorch.DALIRaggedIterator) which returns a set of separate tensors.

I'm commenting out coin = fn.random.coin_flip(probability=0.2)
    global_1 = fn.cast(global_1, dtype=types.UINT8, device=“gpu”)
    if coin.
        global_1 = fn.color_space_conversion(global_1, image_type=types.RGB, output_type=types.GRAY, device=“gpu”)
    else.
        global_1 = global_1 After this paragraph, it works fine, it's the tensor due to fn.color_space_conversion(global_1, image_type=types.RGB, output_type=types.GRAY, device=“gpu”) Irregular?
