### ISSUE TITLE
What is the input data type of DALI, if it have any difference with original data load ?

### ISSUE THREAD

**Issue by binbinmeng** [NVIDIA/DALI#56]
note: /workspace/dataset/pytorch/ ,uder which is train/val images

>>>python main.py -a resnet50 -j 16 --fp16 /workspace/dataset/pytorch/ --batch-size 2048
=> creating model 'resnet50'
Traceback (most recent call last):
  File "main.py", line 423, in <module>
    main()
  File "main.py", line 196, in main
    pipe.build()
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/nvidia/dali/pipeline.py", line 124, in build
    self._prepare_graph()
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/nvidia/dali/pipeline.py", line 115, in _prepare_graph
    self._pipe.AddOperator(op.spec, op.name)
RuntimeError: [/opt/dali/dali/pipeline/operators/reader/loader/lmdb.h:73] Assert on "mdb_env_open(mdb_env_, db_path_.c_str(), mdb_flags, 0664) == 0" failed: LMDB Error: No such file or directory

**Comment by JanuszL** [comment]
Hi,
Please make sure that following path exists:
- /workspace/dataset/pytorch/train
- /workspace/dataset/pytorch/val
And insides are files in appropriate format.

**Comment by JanuszL** [comment]
Please make sure that you are using Cafee 2 LMDB format.
If you set path correctly and using file in appropriate format please reopen this issue.
