### ISSUE TITLE
backend.ReleaseUnusedMemory， I think the pipeline is rebuilt every epoch. Am I doing it right about releasing it?

### ISSUE THREAD

**Issue by rixejzvdl649** [NVIDIA/DALI#5609]
### Describe the question.

I think the pipeline is rebuilt every epoch. Am I doing it right about releasing it?

```python
    def reset(self, flag=True):
        if flag:
            self.tf.close()
            self.pipeline.__del__()
            del self.pipeline, self.dali_iterator
            backend.ReleaseUnusedMemory()
            if self.shard_id == 0:
                print("del dali_iterator, ReleaseUnusedMemory")
            self._build_pipeline()
        else:
            self.tf.close()
            self._build_pipeline()
```

### Check for duplicates

- [X] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by rixejzvdl649** [comment]
Previously I used the following code, which crashed at epoch7


RuntimeError: Critical error in pipeline:
Error in GPU operator `nvidia.dali.ops.CropMirrorNormalize`, which was used in the pipeline definition with the following traceback:
encountered:
Can't allocate 202375168 bytes on device 0.
Current pipeline object is no longer valid.

```
    def reset(self, flag=True):
        if flag:
            self.tf.close()
            del self.dali_iterator
            backend.ReleaseUnusedMemory()
            if self.shard_id == 0:
                print("del dali_iterator, ReleaseUnusedMemory")
            self._build_pipeline()
        else:
            self.tf.close()
            self._build_pipeline()
```

**Comment by rixejzvdl649** [comment]
I feel like there must be something wrong with my previous release. I saw the previous issue discussing weakref, and I released the video memory more thoroughly, but I'm not sure if I wrote the code correctly.

**Comment by rixejzvdl649** [comment]
Or should it be in this form?

```
    def reset(self, flag=True):
        if flag:
            self.tf.close()
            del self.pipeline
            del self.dali_iterator
            backend.ReleaseUnusedMemory()
            if self.shard_id == 0:
                print("del dali_iterator, ReleaseUnusedMemory")
            self._build_pipeline()
        else:
            self.tf.close()
            self._build_pipeline()
```

**Comment by JanuszL** [comment]
Hi @rixejzvdl649,

Thank you for reaching out. Can you post a complete and self-contained code reproducing the mentioned behavior (it could be just a data pipeline using toy samples from https://github.com/NVIDIA/DALI_extra)? Without it we need to speculate.
