### ISSUE TITLE
No attribute `HostDecoderRandomCrop` when running with `dali_cpu`

### ISSUE THREAD

**Issue by deepakn94** [NVIDIA/DALI#562]
I'm trying to integrate DALI into my ImageNet training script, but am running into this error:

```bash
>>> python main_nvidia.py --data_dir ../../../../data/imagenet/ -a resnet50 -b 128
=> creating model 'resnet50'
Traceback (most recent call last):
  File "main_nvidia.py", line 435, in <module>
    main()
  File "main_nvidia.py", line 174, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "main_nvidia.py", line 248, in main_worker
    dali_cpu=not args.dali_gpu)
  File "main_nvidia.py", line 89, in __init__
    self.decode = ops.HostDecoderRandomCrop(device=dali_device,
AttributeError: module 'nvidia.dali.ops' has no attribute 'HostDecoderRandomCrop'
```

I basically copied the code from [the ResNet50 example](https://github.com/NVIDIA/DALI/tree/master/docs/examples/pytorch/resnet50), and am using the `nvcr.io/nvidia/pytorch:19.01-py3` container.

Any help much appreciated!

**Comment by JanuszL** [comment]
Hi,
This operator will be available in the next release, optionally you can to build DALI binary on your own following this [guide](https://github.com/NVIDIA/DALI#compiling-dali-from-source-docker). Please check example aligned with recently available binary https://github.com/NVIDIA/DALI/tree/v0.6.1 or https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/index.html.

**Comment by deepakn94** [comment]
Got it, thanks!
