### ISSUE TITLE
Build dali from sourcecode failed

### ISSUE THREAD

**Issue by south-ocean** [NVIDIA/DALI#5651]
### Describe the question.

when i compile the dali, and cmake command is cmake -D CMAKE_BUILD_TYPE=Release -D BUILD_NVJPEG=OFF -D BUILD_NVJPEG2K=OFF -D BUILD_NVOF=OFF -D BUILD_NVDEC=OFF -D  BUILD_NVML=OFF  -D BUILD_CVCUDA=OFF  -D BUILD_CVCUDA=OFF  -D BUILD_CUFILE=OFF  -D BUILD_NVIMGCODEC=OFF   -D BUILD_PYTHON=ON   .. , but it return an error  fatal error: 'caffe/util/half.cuh' file not found, but i can't find this file in system and dali folser, Can you tell me the file path?

![Image](https://github.com/user-attachments/assets/a429d439-7f08-4117-a37a-4fd226aa93dc)
![Image](https://github.com/user-attachments/assets/8f324c3d-ac76-471a-8e40-6dc73e900845)

### Check for duplicates

- [x] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @south-ocean,

Thank you for reaching out. I see that the offending lines are redundant and can be safely removed (https://github.com/NVIDIA/DALI/pull/5653).
Also, they are wrapped around by  ```#ifdef __CUDA_ARCH__``` that should evaluate to false for the host code.
Can you tell me more about your development environment (host and CUDA compiler versions)?

**Comment by south-ocean** [comment]
yeah, but anyway there are no caffe/util/half.cuh and caffe/util/gpu_math_functions.cuh files and can't find it.

**Comment by JanuszL** [comment]
Hi @south-ocean,

> there are no caffe/util/half.cuh and caffe/util/gpu_math_functions.cuh files

That is expected, and as @mzient mentioned the corresponding code is guarded by a combination of the `#ifdef` so it should not be reachable in the regular conditions. If your compilation process fails on this, your setup is not standard and we would like to learn more about it.
