### ISSUE TITLE
Video decoder hungs on `[DALI][WT]Video' thread

### ISSUE THREAD

**Issue by runitao** [NVIDIA/DALI#5667]
### Version

1.42.0

### Describe the bug.

I use `fn.readers.video` to decode videos, the [minimum reproducible example](https://github.com/runitao/dali_example/blob/main/dali_issue.py) hungs on the `[DALI][WT]Video` thread.

```
python dali_issue.py deadloop.txt
```

however, `ffmpeg -i 425724669.mp4 -r 1 -q 0  '%08d'.jpg` can work well.

The test video file is [425724669.mp4](https://github.com/runitao/dali_example/blob/main/425724669.mp4)

NVIDIA-SMI 535.154.05
Driver Version: 535.154.05
CUDA Version: 12.2

![Image](https://github.com/user-attachments/assets/f8fd2d10-0252-41ed-8f5d-afdc6c7ba103)

### Minimum reproducible example

git clone https://github.com/runitao/dali_example.git

### Check for duplicates

- [x] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Let me check this and get back to you with more info.

**Comment by JanuszL** [comment]
Let me check this and get back to you with more info.

**Comment by JanuszL** [comment]
I think I managed to fix it https://github.com/NVIDIA/DALI/pull/5669.
Please check the nightly build that follows the merge of this change.

**Comment by runitao** [comment]
Hi @JanuszL ,thanks for your effort on this issue.

I found another case which maybe relation with this issue. The video decoder will hungs on if I set `pad_sequences=True`. But with `pad_sequences=False`, the video decoder can work well.

The video sample is [437387963.mp4](https://github.com/user-attachments/assets/6fbdfb7c-61e0-44f2-8df9-324e28cec98f), and the minimum example as follow.
```
#!/usr/bin/env python
#encoding: utf8

import sys

from nvidia.dali import pipeline_def
import nvidia.dali.fn as fn
import nvidia.dali.types as types


@pipeline_def
def video_pipeline(filenames,
                   pad_sequences=True,
                   sequence_length=16,
                   stride=1,
                   shard_id=0,
                   num_shards=1,
                   device='gpu',
                   name='video_reader'):
  video = fn.readers.video(device=device,
                           filenames=filenames,
                           sequence_length=sequence_length,
                           shard_id=shard_id,
                           num_shards=num_shards,
                           random_shuffle=False,
                           initial_fill=1,
                           image_type=types.RGB,
                           dtype=types.FLOAT,
                           prefetch_queue_depth=2,
                           pad_sequences=pad_sequences,
                           file_list_include_preceding_frame=True,
                           stride=stride,
                           name=name)

  return video


def decode(filenames, pad=True):
  pipe = video_pipeline(filenames=filenames,
                        pad_sequences=pad,
                        batch_size=1,
                        sequence_length=16,
                        num_threads=1,
                        device_id=0,
                        device='gpu',
                        shard_id=0,
                        num_shards=1)
  pipe.build()
  for i in range(7):
    (video,) = pipe.run()


if __name__ == '__main__':
  filename = sys.argv[1] if len(sys.argv) > 1 else '437387963.mp4'

  print('decode with pad_sequences=False...')
  decode([filename], pad=False)
  print('decode with pad_sequences=False OK')

  print('\ndecode with pad_sequences=True...')
  decode([filename], pad=True)
  print('decode with pad_sequences=True OK')

```

**Comment by JanuszL** [comment]
Hi @runitao,

Thank you for providing such an edge case. https://github.com/NVIDIA/DALI/pull/5676 should help in this case.

**Comment by runitao** [comment]
> Hi [@runitao](https://github.com/runitao),
> 
> Thank you for providing such an edge case. [#5676](https://github.com/NVIDIA/DALI/pull/5676) should help in this case.

Yes, It works
