### ISSUE TITLE
Video decoder runs slower and slower when decoding a long video

### ISSUE THREAD

**Issue by runitao** [NVIDIA/DALI#5672]
### Describe the question.

#
With the PR [Add an ability to retry rewind to the one before the last keyframe #5669 ](https://github.com/NVIDIA/DALI/pull/5669), which fix the issue [Video decoder hungs on `[DALI][WT]Video' thread #5667](https://github.com/NVIDIA/DALI/issues/5667).

By the minimum example below, I found the video decoder runs slower and slower. Here is the output log.
```
deocde the first 5s of the video
        elapsed=0.40, fps=314.23, num_frames=125
deocde the first 10s of the video
        elapsed=1.24, fps=200.96, num_frames=250
deocde the first 20s of the video
        elapsed=4.73, fps=105.73, num_frames=500
deocde the first 50s of the video
        elapsed=28.46, fps=43.92, num_frames=1250
deocde all the video                                    # video duration is about 510s
        elapsed=2885.07, fps=4.43, num_frames=12770
```

PS. using `ffmpeg -i 439579348.mp4 -r 25 -q 0  -f null -`, fps can reach 2023.
> frame=12770 fps=2023 q=-0.0 Lsize=N/A time=00:08:30.79 bitrate=N/A speed=80.9x 

* video sample
https://drive.google.com/file/d/1V5HkCcDxe-yelVP3YUCrV_bTNlSgdZdv/view?usp=sharing

* minimum example
```
#!/usr/bin/env python
#encoding: utf8

import sys
import numpy as np
import time

from nvidia.dali import pipeline_def
import nvidia.dali.fn as fn
import nvidia.dali.types as types

@pipeline_def
def video_pipeline(filenames,
                   labels=[],
                    sequence_length=16,
                    stride=1,
                    shard_id=0,
                    num_shards=1,
                    device='gpu',
                    name='video_reader'):
  video, label, start_frame_num, timestamps = fn.readers.video(
      device=device,
      filenames=filenames,
      labels=labels,
      sequence_length=sequence_length,
      shard_id=shard_id,
      num_shards=num_shards,
      random_shuffle=False,
      initial_fill=1,
      image_type=types.RGB,
      dtype=types.FLOAT,
      file_list_frame_num=True,
      enable_frame_num=True,
      enable_timestamps=True,
      prefetch_queue_depth=2,
      file_list_include_preceding_frame=True,
      pad_last_batch=True,
      pad_sequences=True,
      stride=stride,
      name=name)

  return timestamps



def decode(filename, iteration):
  batch_size =1
  sequence_length=25 # video avg_frame_rate=25/1
  pipe = video_pipeline(filenames=[filename],batch_size=batch_size,
                        sequence_length=sequence_length, num_threads=1,
                        device_id=0, device='gpu',
                        shard_id=0, num_shards=1)
  pipe.build()

  if iteration == -1:
    epoch_size = pipe.epoch_size('video_reader')
    iteration = (epoch_size + batch_size - 1) // batch_size
  num_frames = 0
  start = time.monotonic()
  for i in range(iteration):
    (timestamps,) = pipe.run()
    ts = timestamps.as_cpu().as_array()[0]
    num_frames += len(ts)
    # print(ts)
    if ts[-1] == -1:
      num_frames -= np.count_nonzero(ts == -1)

  end = time.monotonic()
  elapsed = end - start

  print(f"\telapsed={elapsed:.2f}, fps={num_frames/elapsed:.2f}, num_frames={num_frames}")

if __name__ == '__main__':
  filename = sys.argv[1] if len(sys.argv) > 1 else '439579348.mp4'

  print("deocde the first 5s of the video")
  decode(filename, 5)

  print("deocde the first 10s of the video")
  decode(filename, 10)

  print("deocde the first 20s of the video")
  decode(filename, 20)

  print("deocde the first 50s of the video")
  decode(filename, 50)

  print("deocde all the video")
  decode(filename, -1)

```

### Check for duplicates

- [x] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
https://github.com/NVIDIA/DALI/pull/5669 has been reworked and merged. Please check the next nightly build and reopen if you see a significant performance hit.

**Comment by runitao** [comment]
The video deocder performance is still slow with #5669, same as above.
I think this issue should be reopened.

**Comment by JanuszL** [comment]
Hello again @runitao,

Please accept my apology, I misunderstood the original issue - I was under the impression that the mentioned PR caused a regression.
Looking into this issue more closely it seems that this video decoding (NVDEC) cannot restart from any other keyframe than 0. It usually happens when the keyframe is not [an IDR](https://ireplay.tv/video-streaming-definitions/what-is-an-idr-instantaneous-decoder-refresh/). The software-based decoders like FFmpeg usually are more flexible and can restart the decoding process from any keyframe.
For each sequence, DALI needs to seek to the corresponding, preceding keyframe, and start decoding from there. However, in this case, the decoding process doesn't start and DALI rewinds farther and farther towards the beginning until reaches frame 0 and the decoding starts. So the farther in the video the sequence we want to decode we need to rewind and discard more frames that are decoded from the beginning of the video.
I don't think we can do much from the DALI side in that case.

**Comment by runitao** [comment]
Hi @JanuszL, Thanks for your response. I get your point about the rewinds in DALI.

Recently I am trying to choose a SDK(supporting NVDEC) to decode videos. I have tried PyNvVideoCodec and found it can decode video fast. 

FYI: To decode the same video sample, PyNvVideoCodec can reach 1082fps.
https://drive.google.com/file/d/1V5HkCcDxe-yelVP3YUCrV_bTNlSgdZdv/view?usp=sharing

Here is the minimum example:
```
import os
import sys
import time

import PyNvVideoCodec as nvc
import pycuda.driver as cuda


def decode_with_cuda(filename, cuda_ctx, cuda_stream):
  nv_dmx = nvc.CreateDemuxer(filename=filename)
  nv_dec = nvc.CreateDecoder(gpuid=0,
                             codec=nv_dmx.GetNvCodecId(),
                             cudacontext=cuda_ctx.handle,
                             cudastream=cuda_stream.handle,
                             usedevicememory=False)
  frames = 0
  for packet in nv_dmx:
    for frame in nv_dec.Decode(packet):
      frames += 1
  return frames


def decode(filename):
  cuda.init()
  cuda_device = cuda.Device(0)
  cuda_ctx = cuda_device.retain_primary_context()
  cuda_ctx.push()
  cuda_stream = cuda.Stream()
  frames = decode_with_cuda(filename, cuda_ctx, cuda_stream)
  cuda_ctx.pop()
  return frames


if __name__ == '__main__':
  filename = sys.argv[1] if len(sys.argv) > 1 else '439579348.mp4'

  device_id = 3
  os.environ['CUDA_VISIBLE_DEVICES'] = str(device_id)

  start_time = iter_time = time.monotonic()

  total_frames = decode(filename)

  total_time = time.monotonic() - start_time
  print(f"total time: {total_time:.2f}, handle {total_frames=}, "
        f"decode rate={total_frames/total_time:.2f}")

```

**Comment by JanuszL** [comment]
Hi @runitao,

In the case of PyNvVideoCodec it decodes the whole video in one go without rewinds/seeks. The corresponding video operation in DALI would be [`experimental.inputs.video`](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.experimental.inputs.video.html) with an example usage in [this test](https://github.com/NVIDIA/DALI/blob/main/dali/test/python/input/test_video.py).
```
#!/usr/bin/env python
#encoding: utf8

import sys
import numpy as np
import time

from nvidia.dali import pipeline_def
import nvidia.dali.fn as fn
import nvidia.dali.types as types

@pipeline_def
def video_pipeline(sequence_length=16,
                   device='mixed',
                   name='video_reader'):
  video = fn.experimental.inputs.video(
      device=device,
      sequence_length=sequence_length,
      name=name)

  return video



def decode(filename, iteration):
  batch_size =1
  sequence_length=25 # video avg_frame_rate=25/1
  pipe = video_pipeline(batch_size=batch_size,
                        sequence_length=sequence_length, num_threads=1,
                        device_id=0, device='mixed')
  pipe.build()
  pipe.feed_input('video_reader', np.array([[np.fromfile(filename, dtype=np.uint8)]]))

  num_frames = 0
  start = time.monotonic()
  if iteration == -1:
    iteration = 99999999999999999
  try:
    for _ in range(iteration):
      _ = pipe.run()
      num_frames += batch_size * sequence_length
  except RuntimeError as e:
    if "No data was provided to the InputOperator" in str(e):
      pass
    else:
      raise e

  end = time.monotonic()
  elapsed = end - start

  print(f"\telapsed={elapsed:.2f}, fps={num_frames/elapsed:.2f}, num_frames={num_frames}")

if __name__ == '__main__':
  filename = sys.argv[1] if len(sys.argv) > 1 else '439579348.mp4'

  print("deocde the first 5s of the video")
  decode(filename, 5)

  print("deocde the first 10s of the video")
  decode(filename, 10)

  print("deocde the first 20s of the video")
  decode(filename, 20)

  print("deocde the first 50s of the video")
  decode(filename, 50)

  print("deocde all the video")
  decode(filename, -1)
```
The `fn.readers.video` creates each sample independently and allows shuffling, so each sequence in a batch can come from a different place in the video file.

**Comment by runitao** [comment]
@JanuszL, Thanks for your reminds. I tried with [experimental.inputs.video](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.experimental.inputs.video.html) again(with #5676), YES, it works well now and fits my scene.
