### ISSUE TITLE
easiest way to test ops

### ISSUE THREAD

**Issue by grez72** [NVIDIA/DALI#568]
I'm working on implementing a few custom ops, and I'm trying to figure out the easiest way to test that my operation is behaving correctly. But my question also applies to built-in operations: What is the easiest way to run and access the output of an operation?

For example, I know this doesn't work:
```
from nvidia.dali import ops
flip = ops.CoinFlip()
toss = flip()
print(toss)
# prints <nvidia.dali.tensor.TensorReference object at 0x7f7269673080>
```
How can I get the actual output value of the tensor? Or is this impossible outside the context of a Pipeline? 

Can you provide or point me toward a minimal example of how to run an operation and access its output?

**Comment by klecki** [comment]
Hi,
from Python API it is not possible to call an operator directly, and you have to create whole pipeline to do it. 
What you did here is: 
`flip = ops.CoinFlip()` - this creates an Operator. At this point you can parametrize it with arguments. 
`flip` is a callable object, but it is not calling the underlying implementation of Operator - you use to build a graph of operations/computations describing the flow of your augmentations. 
Values returned by such objects, can be passed to another Operators to indicate data flow.

You can see some examples in here: https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/getting%20started.html#Defining-the-pipeline

Usually you would instantiate operators in constructor of the Pipeline (`__init__`), and build the graph in `define_graph` method. 

Than you have to call `build` on pipeline, to actually allow backend to construct everything, and you can call `run()` to obtain the outputs as tensors.

If you want to access the output of built-in Operator from your operator you will just do something like:

```

class SimplePipeline(Pipeline):
    # Constructor of the Pipeline
    def __init__(self, batch_size, num_threads, device_id):
        super(SimplePipeline, self).__init__(batch_size, num_threads, device_id, seed = 12)
        # Two built-in operators:
        self.input = ops.FileReader(file_root = image_dir)
        self.decode = ops.HostDecoder(output_type = types.RGB)
        # Your operator
        self.op = NewOp(Param1, Param2)

    def define_graph(self):
        jpegs, labels = self.input()
        images = self.decode(jpegs)
        # We indicate, that output of decode should go to your Operator
        output = self.op(images)
        # and we indicate that the pipeline should return the output of your Operator
        return (output,)
```
Than you just create an instance of SimplePipeline, `build()` and `run()`.

There is also option of testing Operators from C++ point of view, and you can see examples in our unit tests: https://github.com/NVIDIA/DALI/blob/master/dali/pipeline/operators/transpose/transpose_test.cc

It still does create a Pipeline object under the hood and builds the graph, similar to the python API. Just be aware, that C++ API is not considered stable.

**Comment by grez72** [comment]
That makes sense...thanks for the clarification. 

In the case of the CoinFlip op, this SimplePipeline throws an error: 
```
Assert on "!tensor_meta.is_support" failed: Outputs of support ops cannot be outputs.
```
I'm trying to create a CustomCoinFlip that returns a float instead of an int (0.0 or 1.0), as described here #567. I haven't managed to get that working yet, but in case I do, I'm guessing I will run into the same error. Is there a workaround for this "Outputs of support ops cannot be outputs" error?  

Thanks!

**Comment by JanuszL** [comment]
Hi,
Currently, there is no workaround for that. We have this in our roadmap to make support ops first-class citizens, but now they are returning different data than other ops - one tensor while other ops return vector or list of tensors.

**Comment by grez72** [comment]
Ok, thanks for following up. I should be able to spot check things for now by looking at output images.
