### ISSUE TITLE
NVIDIA DALI NVML Error (3)

### ISSUE THREAD

**Issue by supportman007** [NVIDIA/DALI#5696]
### Describe the question.

Hi,
Im trying to implement a project from [github.](https://github.com/cfzd/Ultra-Fast-Lane-Detection-v2)
Im using Windows 10 with WSL2. Im using Cuda 11.5 and DALI 1.31.0
This is the error i get:

RuntimeError: Critical error when building pipeline:
Error when constructing operator: decoders__Image, instance name: “__Image_4”, encountered:
Error in thread 0: nvml error (3): The nvml requested operation is not available on target device
Current pipeline object is no longer valid.

what should i do?

### Check for duplicates

- [ ] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @supportman007,

Thank you for reaching out. This error is about missing functionality in NVML for WSL2. Can you try setting `export DALI_DISABLE_NVML=1` and check if that helps?

**Comment by supportman007** [comment]
> Hi [@supportman007](https://github.com/supportman007),
> 
> Thank you for reaching out. This error is about missing functionality in NVML for WSL2. Can you try setting `export DALI_DISABLE_NVML=1` and check if that helps?

it seems like it continues but a second later it came with this error:

RuntimeError: CUDA error: unknown error
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
(lane-det) root@DESKTOP-F744S5D:/home/project_adas/Ultra-Fast-Lane-Detection-V2#
