### ISSUE TITLE
Possible to know with fn.readers.video which video the returned frames come from? Implementing custom label logic

### ISSUE THREAD

**Issue by nkinnaird** [NVIDIA/DALI#5718]
### Describe the question.

Hi there, I'm working on implementing a data loader to load videos and complex labels. I ran across Dali and started implementing it since it seems perfect for my use case. So far I've implemented a basic functional pipeline following the docs using the `dali.fn.readers.video` method which is working well to return batched and sequenced video frames.

Now I need to process and return labels along with the returned video frames. My labels are complex, ie. robot telemetry data that I need to time-align with the returned video frames. I can do the label logic processing myself, but I'm struggling with how to make sure I'm processing the right labels files which correspond to the associated video files. 

I currently have pairs of (video file name, log file name), and I'm passing the first elements in a list to the video reader function with the `filenames` argument. I should be able to use the `enable_timestamps` parameter and the returned timestamps per frame to grab the right log data, I just need to make sure I point to the right log file first. Is there a way with the video reader to know for a returned batch what video filenames those frames came from? 

I thought also maybe I can process the labels first and then pass in the labels with the `labels` argument to the video reader function, but that doesn't seem to be the case. I might also be able to do this with basic python logic, as long as I know the order that the videos are being processed in and what batch number is being returned. Can batches span different videos with the video reader function? If not then perhaps I can do this. Though I'd like to avoid it if possible since I'd like to take full advantage of the parallelization of the video reader function down the line, and keep any sort of such logic to a minimum.

Edit: I forgot to mention I ran across the `fn.external_source` method as well which I thought might work, but from what I can tell this requires me to preprocess all the label data at once before reading the video frames. This probably will not work for me since I can expect there to be a ton of label data, and I'd prefer to acquire the labels at the same time as I acquire the video frames if possible.

Edit edit: Upon reading more about `external_source` perhaps I can use this. Still trying to figure it out so I'll leave this question up in case any helpful thoughts around this come to mind, and whether I can just get the file names from the video reader directly which I think will make things easier if possible.

Any help or thoughts on this would be much appreciated, thanks!

### Check for duplicates

- [x] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @nkinnaird,

Thank you for reaching out.
> I currently have pairs of (video file name, log file name), and I'm passing the first elements in a list to the video reader function with the filenames argument. I should be able to use the enable_timestamps parameter and the returned timestamps per frame to grab the right log data, I just need to make sure I point to the right log file first. Is there a way with the video reader to know for a returned batch what video filenames those frames came from?

You can read the file name directly from each corresponding sample in the batch (tensor) [`source_info`](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/pipeline.html#nvidia.dali.pipeline.DataNode.source_info). Another idea is to have a unique label assigned to each file and do the processing based on that.

> Can batches span different videos with the video reader function?

If you are asking if different video files can be mixed inside one batch, then yes, it is possible, still, each can have a separate and unique label assigned.

> Edit: I forgot to mention I ran across the fn.external_source method as well which I thought might work, but from what I can tell this requires me to preprocess all the label data at once before reading the video frames. This probably will not work for me since I can expect there to be a ton of label data, and I'd prefer to acquire the labels at the same time as I acquire the video frames if possible.
>
> Edit edit: Upon reading more about external_source perhaps I can use this. Still trying to figure it out so I'll leave this question up in case any helpful thoughts around this come to mind, and whether I can just get the file names from the video reader directly which I think will make things easier if possible.

You can use the [`external source` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.external_source.html#) and feed [`experimental.decoders.video`](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.experimental.decoders.video.html), but in this case, you get whole video file decoded in one go while you may prefer to decode only a slice of it in one iteration.

**Comment by nkinnaird** [comment]
Thank you for the help @JanuszL . Yes now that you mention it passing in a unique integer for each video/label file makes a lot of sense and works pretty well. I understand how the labels are returned now a bit better as well, and these unique integers will be appropriate for batches made up of frames from different videos (rare but does happen of course).

I tried the `source_info` approach first without much success, there are still things I don't quite understand there, but for now I'm good to go with the unique label indices. Thanks!
