### ISSUE TITLE
Whether the generated anchors can be moved？

### ISSUE THREAD

**Issue by ggbondcxl** [NVIDIA/DALI#5731]
### Describe the question.

If I have to use nvidia.dali.fn.random_crop_generator, is it possible to do a downward pan for this anchor after generating the anchor. Because I only want to do random cropping in some areas. 
```
crop_anchor, crop_shape= fn.random_crop_generator(np.array([1000,3840,3], dtype=np.int64), random_area=[0.2, 1.0])
images = fn.decoders.image_slice(input, crop_anchor, crop_shape, device="mixed", axis_names="HW")

### Check for duplicates

- [x] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by mdabek-nvidia** [comment]
Hi @ggbondcxl,
Thank you for your question. Do I understand correctly that you are trying to change crop_anchor value after calling fn.randcom_crop_generator? If so this should be possible and you can pass any anchor to image_slice.

**Comment by ggbondcxl** [comment]
> Hi [@ggbondcxl](https://github.com/ggbondcxl), Thank you for your question. Do I understand correctly that you are trying to change crop_anchor value after calling fn.randcom_crop_generator? If so this should be possible and you can pass any anchor to image_slice.

Firstly thank you for your answer, your understanding is correct, can you give me an example if the image is 3180, 2160, 3's and the anchor is crop_anchor, how should I pan down 1000 pixel values?

**Comment by ggbondcxl** [comment]
> Hi [@ggbondcxl](https://github.com/ggbondcxl),
> 
> Sorry for the late answer. Here is the example, that shifts the anchor down by 50 px:
> 
> ```
>    crop_anchor, crop_shape= fn.random_crop_generator(np.array([512, 512, 3], dtype=np.int32), random_area=[0.2, 1.0])
>    crop_anchor1 = fn.cast(crop_anchor, dtype=dali.types.INT32) + types.Constant(np.array([[50,0]]))
>    out = fn.decoders.image_slice(input1, crop_anchor1, crop_shape, device="mixed", axis_names="HW")
> ```

It works, thanks  a lot!
