### ISSUE TITLE
Issues with the installing nvidia-dali cuda 12.0

### ISSUE THREAD

**Issue by arslanmzahid** [NVIDIA/DALI#5749]
### Version

12.0

### Describe the bug.

I am trying to install nvidia dali library through the official pip releases mentioned on the NVIDIA DALI documentation. which is below: 

pip install nvidia-dali-cuda120

I am facing the following issue. 

![Image](https://github.com/user-attachments/assets/354d11b3-f675-4fa5-8f4d-b7db03fcf829)

however, I am facing failures in installing the library, I have checked the pre-requisites need ( I am using CUDA 12.6.2), and I am using the NVIDIA GeForce RTX 4060 Ti . The error is shown below:

Any help regarding this matter ? I think this issue was raised before as well.

### Minimum reproducible example

```shell
The installation of nvidia-dali-cuda120 for version 1.44.0 failed.
This is a special placeholder package which downloads a real wheel package from https://pypi.nvidia.com/. If https://pypi.nvidia.com/ is not reachable, we cannot download the real wheel file to install.
You might try installing this package via
$ pip install --extra-index-url https://pypi.nvidia.com/ nvidia-dali-cuda120
Here is some debug information about your platform to include in any bug report:
Python Version: CPython 3.11.9 Operating System: Windows 10 CPU Architecture: AMD64
Driver Version: 560.94
CUDA Version: 12.6
```

### Relevant log output

```shell

```

### Check for duplicates

- [ ] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @arslanmzahid,

Thank you for reaching out. Unfortunately, Windows OS is not supported by DALI and that is why you see this error.
You can try using DALI through [WSL](https://learn.microsoft.com/en-us/windows/wsl/install).
