### ISSUE TITLE
Continuous label in nvidia.dali.fn.readers.file

### ISSUE THREAD

**Issue by vriffel** [NVIDIA/DALI#5758]
### Describe the question.

Hello, thanks for the amazing library!

I'm loading images from a folder, but my labels are continuous. Because of this, I can't separate them as expected by nvidia.dali.fn.readers.file.

My goal is to read and transform the images using nvidia-dali instead of pytorch. My pipeline is:

```python
import numpy as np
from nvidia.dali import pipeline_def
import nvidia.dali.fn as fn

MEAN = np.asarray([0.485, 0.456, 0.406])[None, None, :]
STD = np.asarray([0.229, 0.224, 0.225])[None, None, :]

@pipeline_def
def dali_transformations():
    jpegs, _ = fn.readers.file(
        files = IMG_PATH, random_shuffle = False
    )
    images = fn.decoders.image(jpegs, device = "mixed")
    angle = fn.random.uniform(range = (-45.0, 45.0))
    flip_prob = np.random.uniform(0, 1, 2)
    if flip_prob[0] > 0.5:
        images = fn.flip(images.gpu(), horizontal = 1, vertical = 0)
    if flip_prob[1] > 0.5:
        images = fn.flip(images.gpu(), horizontal = 0, vertical = 1)
    images = fn.rotate(images.gpu(), angle = angle, fill_value = 0)
    images = fn.resize(images, device = "gpu", resize_x = 224, resize_y = 224)
    images = fn.normalize(images, device = "gpu", mean = MEAN*255, stddev = STD*255)
    images = fn.transpose(images, device = "gpu", perm = [2, 0 , 1])

    return images, _
```

For each batch, I need to rebuild the pipeline inside of a loop training like this:

```python
for i in range(n_batches):
  IMG_PATH = batch_info[i][0] # Here I have the filename of my images
  y = batch_info[i][1] # Here I have my labels, remember they are continuous
  pipe = dali_transformations(
    batch_size = len(IMG_PATH), num_threads = 1, device_id = 0
  )
  pipe.build()
  # Then I convert the images to torch tensor and proceed with the training.
```

If I was able to load the labels together with the images in the pipeline it will speed up a lot the training (I wouldn't have to rebuild the pipeline in each iteration). I tried to pass it as a list using the `labels` argument in nvidia.dali.fn.readers.file, but it is expecting a list of integers, not a list of floats.

Thanks in advance, I can share more information in case it is needed!

### Check for duplicates

- [x] I have searched the [open bugs/issues](https://github.com/NVIDIA/DALI/issues) and have found no duplicates for this bug report

**Comment by JanuszL** [comment]
Hi @vriffel,

Thank you for reaching out. Please try out [the `external source` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/parallel_external_source.html) where you can provide a fully custom data loading pattern defined in python and return floats as labels.

**Comment by vriffel** [comment]
Hi, thanks a lot! It solved my problem.
