### ISSUE TITLE
No module named 'nvidia'

### ISSUE THREAD

**Issue by charliewang789** [NVIDIA/DALI#591]
Hi 

I installed DALI, when I run the first sample code, I got the following error

_from nvidia.dali.pipeline import Pipeline
help(Pipeline)_
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-83f2baa646a8> in <module>
----> 1 import nvidia
      2 from nvidia.dali.pipeline import Pipeline
      3 help(Pipeline)

ModuleNotFoundError: No module named 'nvidia'

Can you please tell me what's wrong?

**Comment by JanuszL** [comment]
Hi,
What version of DALI do you installed?
How it is installed, Conda, virtual env or just bare metal?
Please check if the python version of DALI you have installed matches the Python version you are running, i.e. you installed for python 3.6 while you are running Python 2.7.

**Comment by aalugore** [comment]
Hello. I also am getting the same error. I am building from a conda environment. The python version I built with matches the one i am running with at version 3.6.8. Any insight?

**Comment by JanuszL** [comment]
I just answered in https://github.com/NVIDIA/DALI/issues/696. Hard to tell if it is installation in conda or the build process.

**Comment by JanuszL** [comment]
@aalugore - answering your question from https://github.com/NVIDIA/DALI/issues/696:
> after building DALI, which artifacts/files/binaries do I need to make sure get put into my conda package

We haven't tested build for conda. What we are doing is building whl and we are doing this in two stages:
* build whl https://github.com/NVIDIA/DALI/blob/master/Dockerfile#L58
* patch library names and add necessary libraries into the package using dali/python/bundle-wheel.shhttps://github.com/NVIDIA/DALI/blob/master/Dockerfile#L62

What I would suggest is to use build using dockerized build env by running docker/build.sh (we do that way and it provides portable binary) and then use whl inside your conda env.
Of course, if you want to create conda package I would be more than happy to see such contribution, but whl is our recommended way.

**Comment by aalugore** [comment]
@JanuszL Hi, quick question. Is DALI compatible with CUDA 10.1? in docker/build.sh I see references to 10.0, but not 10.1

**Comment by JanuszL** [comment]
Hi,
You should be able to build with 10.1 (or at least I'm not aware of any problem you could encounter). We are building with 10.0 to cover all 10.0 and 10.1 users.

**Comment by aalugore** [comment]
@JanuszL Hello again. I have been able to put together the beginnings of a working conda package. I've managed to get the python 3 version packaged but am failing with python 2.7. It keeps packaging the python 3.6 version into the python 2.7 package causing the module look up to fail. Looking in the README for dali, a couple ENVs are reference (PYVER, PYV) but these seem to only be used at the Docker file level. Being that I am just running the sequence of cmake, make, pip install --user dali/python, is there another way to force the python2.7 version to be built? Maybe an argument to cmake and/or pip install? Basically just looking for the simplest way to force the python2.7 version without going the docker build route.

**Comment by JanuszL** [comment]
Hi,
That is why we are using Docker and we haven't tested multiple Python builds in bare metal.
Doing quick research I believe it may be the pybind11 thing, checking https://pybind11.readthedocs.io/en/stable/compiling.html#configuration-variables it may be just the matter of passing bellow variables to CMake to make build for proper python version
```
cmake -DPYBIND11_PYTHON_VERSION=3.6 ..
# or
cmake -DPYTHON_EXECUTABLE=path/to/python ..
```
the rest should be the same (as python code or libdali.so itself should be the same).

**Comment by JanuszL** [comment]
Discussion was moved to https://github.com/NVIDIA/DALI/issues/1125.
