### ISSUE TITLE
Padding an image with black pixels to a specified size

### ISSUE THREAD

**Issue by addisonklinke** [NVIDIA/DALI#593]
I have a model that requires all input images to be the same dimensions (540 x 960), so the last step of my pipeline uses Dali's `Resize` operator to ensure this. However, I would like to get different aspect ratio images. Therefore, instead of warping the current image into the 540 x 960 size, I would like to pad it with black pixels until it reaches the desired size. This operation should not center the image every time, but rather place it randomly within the padding. Is this possible on GPU with the built-in Dali operators?

I am also open to writing a custom operator for this. It seems like one approach would be allocating a `buffer` instance of size 3 x 540 x 960 and initializing all pixels with black. Then, select a random starting point within the buffer as the upper left corner of the image. From that point, copy over the image's pixel values into the black buffer. With this approach, I am unsure how to accomplish a couple things

* I know I can use `tensor.Resize()` method to get my desired buffer dimensions. However, how can I efficiently initialize all pixels to black (0) on the GPU without looping through the entire matrix?
* Similarly, is there an efficient way on GPU to copy the image pixel values to a certain location within the buffer? Preferably using a built-in CUDA function like `cudaMemcpy`

**Comment by JanuszL** [comment]
Hi,
Have you looked into https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/detection_pipeline.html and `Paste` operator? If it doesn't meet your requirements it should be easy to rework it to what you need.

**Comment by addisonklinke** [comment]
Excellent, that should work if I modify it to take a separate `x_ratio`  and `y_ratio` for each dimension instead of a singular `ratio` that is applied to both. Is that a feature which could be considered for future versions? Otherwise, the pasted image must have the same aspect ratio as the canvas which defeats the purpose I am trying to use it for

**Comment by JanuszL** [comment]
It seems that it is not that widely used so we don't plan to extend it any further. But if you can share your modification it could be a great contribution to DALI.

**Comment by mbsariyildiz** [comment]
Hello.

I am also looking for a padding function that just pads an image so that it becomes a square image. In this regard, @addisonklinke have you found a solution for your issue?

Regards.

**Comment by ban1080** [comment]
Likewise.

**Comment by JanuszL** [comment]
Hi @ban1080,

Have you tried using [the pad oeprator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.pad)?
You may also consider creating [a custom operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/custom_operations/index.html).
