### ISSUE TITLE
clarify units in the documentation for ops.Hue and ops.ColorTwist?

### ISSUE THREAD

**Issue by grez72** [NVIDIA/DALI#662]
Hi,

The documentation for ops.Hue and for the hue parameter of ops.ColorTwist say 

"hue (float or float tensor, optional, default = 0.0) – Hue change in angles."

But it doesn't specify that hue varies between 0 and 360 degrees, not the 0-1 scale. 

I mistakenly thought hue varied between 0 and 1, in part because pytorch's ColorJitter hue varies on this range (-0.5 <= min <= max <= 0.5), and also because issue #336 shows an example with hue varying uniformly between (-.5,.5), which would make sense if Hue was on the 0 to 1 scale. However, if one wants to "randomly jitter" using ops.ColorTwist I think you would actually want to use (-180,180).

Perhaps this would be more clear?
"hue (float or float tensor, optional, default = 0.0) – Hue change in degrees (min: -180, max: 180)"

Or modeled after pytorch's docs
"hue (float or float tensor, optional, default = 0.0) – Hue change in degrees (-180 <= min <= max <= 180)"

I realize that's not entirely accurate, because -181 is valid (and equivalent to +179), but it would have made it clear to me which units and range to work within.

I'm not sure if this clarification would be helpful to others, but I thought it was worth noting.

Thanks!

**Comment by JanuszL** [comment]
Hi,
Good point. We will update the docs. Thank you for spotting this.

**Comment by JanuszL** [comment]
After some consideration I think that adding note about degrees is enough. It is rather obvious that 0-360 is the same as -180 - 180 and no more clarification is needed as DALI will accept any value and calculate using it properly.
Done in #683

**Comment by Hzzone** [comment]
Thanks for your clarification. I figure it out during mapping the torchvision to dali. we should have the following form:
```python
if isinstance(t, transforms.ColorJitter):
   return partial(fn.color_twist,
                  brightness=fn.random.uniform(range=t.brightness),
                  saturation=fn.random.uniform(range=t.saturation),
                  contrast=fn.random.uniform(range=t.contrast),
                  hue=fn.random.uniform(range=t.hue) * 360.0
                  )
```

**Comment by twmht** [comment]
@Hzzone 

it's helpful.
