### ISSUE TITLE
not all images shown when setting random_shuffle

### ISSUE THREAD

**Issue by grez72** [NVIDIA/DALI#665]
Hi,

I've been working with both the ops.MXNetReader, and I'm unable to get a random_shuffle in which each image is presented exactly once, even when num_shards = 1, and the batch_size (100) is a multiple of the total number of images (50000).

The number of "duplicates" is proportional to the initial_fill. If I set initial_fill to 1, there are no duplicates, but then the order is not randomized. If I set initial_fill to 100, then nearly every image is shown, but several images within the first 100 will be repeated. Likewise, if I set initial_fill to 1000, I get repeats within the first 1000. Is this a bug or the intended behavior?

I imagine that in many cases this wouldn't have much impact, but my model is learning the individual images ("instance discrimination"), so it's essential that each image is shown once per epoch.

Is there a way to guarantee that each image is shown once in a random order, either for ops. MXNetReader, or ops.FileReader?

Thanks!

**Comment by JanuszL** [comment]
Hi,
Our reader design uses buffer we are randomly selects samples to form a batch with moving window that wraps up at then end of epoche. So at the very end of epoche is it likely that samples form the begging of the data set could be repeated. I think it should not possible to implement behavior your are asking for as an option. Tracked DALI-613.

**Comment by grez72** [comment]
Hi,

Thanks for your response. I've found a workaround using python's tempfile to create a temporary file_list, enabling me to use any random order I need when using ops.FileReader, while still presenting each image only once.

In working on this, I did discover a possible issue with ops.MXNetReader (I'm using dali version 0.7.0). Specifically, when I set random_shuffle to True and initial_fill = 100, the images do not appear to be randomly shuffled across the full set. They look "locally shuffled", with the first batch coming from the first ~100 images, the next batch from ~100-200, and so on, until the last batch which comes from the last ~100 images.

To illustrate, here's what I find when random_shuffle=True, and initial_fill=100.

indexes of first batch:
![image](https://user-images.githubusercontent.com/6005275/54494361-a36fca80-48af-11e9-9597-42c6f74ace76.png)

indexes of second batch:
![image](https://user-images.githubusercontent.com/6005275/54494370-aff42300-48af-11e9-9aa6-9596bd1370c3.png)

average index by batch:
![image](https://user-images.githubusercontent.com/6005275/54494206-37409700-48ae-11e9-8eff-349dae81b1d8.png)

When I do the same test with ops.FileReader, each batch appears to be randomly sampled from the full set.

![image](https://user-images.githubusercontent.com/6005275/54494227-5808ec80-48ae-11e9-8c06-0295c35a42de.png)

For reference, here are my readers, in case I've done something obviously incorrect in setting up the pipeline. In order to run the test, I created a version of the cifar10 recordIO dataset in which the "labels" are actually the "image index". Likewise, I have a FileList for the FileReader in which the labels are the image index.

```

cifar_mean = [x*255 for x in [.4914, .4822, .4465]]
cifar_std = [x*255 for x in [.2023, .1994, .2010]]

class MXNetReaderPipeline(Pipeline):
    def __init__(self, rec_file, idx_file, random_shuffle=True, batch_size=100, num_gpus=1, device_id=0, 
                 num_threads=12, seed=12, initial_fill=1024, exec_async=True):
        
        super(MXNetReaderPipeline, self).__init__(batch_size=batch_size,
                                                  num_threads=num_threads,
                                                  device_id=device_id,
                                                  seed=seed)
        
        self.input = ops.MXNetReader(path = rec_file, 
                                     index_path = idx_file, 
                                     num_shards = num_gpus,
                                     shard_id = device_id,
                                     random_shuffle=random_shuffle, 
                                     seed=seed,
                                     initial_fill=initial_fill,
                                     read_ahead=False)
        
        # self.decode = ops.nvJPEGDecoder(device = "mixed", output_type = types.RGB)
        self.decode = ops.HostDecoder(output_type = types.RGB)
        self.norm = ops.NormalizePermute(device="cpu", height=32, width=32, mean=cifar_mean, std=cifar_std)

                                
    def define_graph(self):
        inputs, labels = self.input(name="Reader")        
        images = self.decode(inputs)
        images = self.norm(images)
        
        return (images, labels)

    def iter_setup(self):
        pass

class FileReaderPipeline(Pipeline):
    def __init__(self, file_root, file_list, batch_size=100, num_gpus=1, device_id=0, random_shuffle=False,
                 num_threads=12, seed=12, initial_fill=1024, read_ahead=True, exec_async=True):
        
        super(FileReaderPipeline, self).__init__(batch_size, 
                                                    num_threads, 
                                                    device_id, 
                                                    seed=seed, 
                                                    exec_async=exec_async)        
        
        self.input = ops.FileReader(file_root = file_root, 
                                     file_list = file_list, 
                                     num_shards = num_gpus,
                                     shard_id = device_id,
                                     random_shuffle = random_shuffle,  
                                     seed = seed,
                                     initial_fill=initial_fill,
                                     read_ahead=read_ahead)
        
        # self.decode = ops.nvJPEGDecoder(device = "mixed", output_type = types.RGB)
        self.decode = ops.HostDecoder(output_type = types.RGB)
        self.norm = ops.NormalizePermute(device="cpu", height=32, width=32, mean=cifar_mean, std=cifar_std)

                                
    def define_graph(self):
        inputs, labels = self.input()        
        images = self.decode(inputs)
        images = self.norm(images)
        
        return (images, labels)

    def iter_setup(self):
        pass

```

**Comment by JanuszL** [comment]
Hi,
This is the expected behavior. DALI shuffles only inside the local window (as I described earlier). For the FileReader it does initial shuffling at the very beginning to avoid having a case as you described. For other readers we expect data to be initially shuffled at the global level. If you check [script from the MXNet that can be used to create RecordIO](https://github.com/apache/incubator-mxnet/blob/master/tools/im2rec.py) you can see there is an option `--no-shuffle` which is off by the default. So the default behavior is to produce globally shuffled RecordIO sets. I believe it is done mostly as an optimization - when you have RecordIO you don' probably access it randomly.

**Comment by grez72** [comment]
Hi,

Ah, I had missed that, thanks for the clarification.
