### ISSUE TITLE
Nested directory for ops.FileReader

### ISSUE THREAD

**Issue by rtaori** [NVIDIA/DALI#668]
Hi,

My directory structure looks like this:

![image](https://user-images.githubusercontent.com/6610670/54510712-b617ed00-490b-11e9-9288-c1fe1c77f220.png)

In other words, I have an extra layer of nesting than what the FileReader expects. I would like to load all the images and labels together, but this extra level of nesting is currently not supported in FileReader. I know there is an option to pass in a 'file_list.txt', but this seems like a very cumbersome solution to a simple problem.

Please let me know what is a good workaround for this issue.
Thanks

**Comment by JanuszL** [comment]
Hi,
Currently, the 'file_list.txt' is the only solution that will work for you. Could you tell how this 'category' should be used? Is it just informative or it should be combined with the label name as well to create class id?

**Comment by rtaori** [comment]
Thanks for the quick response!
For my case, `category` is just informative and should be ignored, so all images with the same `label` should be treated as such

**Comment by JanuszL** [comment]
I can imagine many different scenarios - in your case you want to skip category, but others may want to use it to differentiate classes between different categories. Another user may have multiple levels of nesting.
I think it would be very hard to develop a solution that fit all users. So we are inclined to extend file reader into that direction and the best way to use it in your case is just with `file_list`. Simple python script that will traverse your data and generate appropriate `file_list` should be very easy to prepare.
