### ISSUE TITLE
Benchmark results against native framework's augmentations?

### ISSUE THREAD

**Issue by 1duo** [NVIDIA/DALI#67]
Hi,

Is there any published benchmark results available against native frameworks TensorFlow, PyTorch, MxNet?
Given same amount of data augmentations on same hardware. Either full training speed (images/sec) or data augmentations only.

**Comment by JanuszL** [comment]
Hi,
We don't have anything available for publishing regarding performance. We plan to provide such numbers soon. You can check preliminary results for DGX-2 mentioned during talk about DALI [slides](http://on-demand.gputechconf.com/gtc/2018/presentation/s8906-fast-data-pipelines-for-deep-learning-training.pdf), [video](http://on-demand.gputechconf.com/gtc/2018/video/S8906/). It is definitely on our ToDo list.
Also please keep in mind that DALI alleviates workloads that are CPU bound - multiple GPU or limited number of CPU cores for each GPU. When your CPU can catch up with GPU (simple pipeline or low GPU number comparing to CPU cores) there is no performance benefit from DALI.

**Comment by 1duo** [comment]
@JanuszL Thanks!

**Comment by JanuszL** [comment]
Internally tracked DALI-174.

**Comment by JanuszL** [comment]
You can check this results in [our last GTC19 presentation](https://developer.download.nvidia.com/video/gputechconf/gtc/2019/presentation/s9925-fast-ai-data-pre-processing-with-nvidia-dali.pdf).
