### ISSUE TITLE
build error 

### ISSUE THREAD

**Issue by dheerajsreedhar** [NVIDIA/DALI#710]
Compilation error while building DALI from source (bare metal build without docker, master branch)

[ 75%] Building CXX object dali/CMakeFiles/dali.dir/aux/optical_flow/turing_of/optical_flow_turing.cc.o

DALI/dali/image/jpeg_mem.cc: In function dali::uint8* dali::jpeg::{anonymous}::UncompressLow(const void*, dali::jpeg::{anonymous}::FewerArgsForCompiler*) :
DALI/dali/image/jpeg_mem.cc:135:9: error: JCS_EXT_BGR was not declared in this scope
         JCS_EXT_BGR : JCS_RGB;

**Comment by klecki** [comment]
Hi,
it looks like this an issue with not compatible libjpeg.
If you want to build on your native system, you can check how we install libjpeg-turbo that is needed here in https://github.com/NVIDIA/DALI/blob/master/Dockerfile.deps#L84

You can point your CMake manually to your installation of libjpeg-turbo if you installed it in a different place by setting `JPEG_INCLUDE_DIRS` and `JPEG_LIBRARY_RELEASE` as per https://cmake.org/cmake/help/v3.14/module/FindJPEG.html

If you still are having problems I would suggest to try our recommended build using docker:
https://github.com/NVIDIA/DALI#compiling-dali-from-source-using-docker-builder---recommended

Best regards,
Krzysztof.

**Comment by dheerajsreedhar** [comment]
Thank you, I used the suggested version of libjpeg-turbo , made cmake to point to this and the build went fine.
