### ISSUE TITLE
error: no suitable conversion function from "const dali::ImageCache::ImageShape" to "uint8_t *" exists

### ISSUE THREAD

**Issue by kkjh0723** [NVIDIA/DALI#726]
Hi, while I build from source, I encountered error messages below.
Has anyone got this error?

    /home/dali/dali/pipeline/operators/decoder/nvjpeg_decoder.h(317): error: no suitable conversion function from "const dali::ImageCache::ImageShape" to "uint8_t *" exists
    
    /home/dali/dali/pipeline/operators/decoder/nvjpeg_decoder.h(317): error: argument of type "uint8_t *" is incompatible with parameter of type "cudaStream_t"

    /home/dali/dali/pipeline/operators/decoder/nvjpeg_decoder.h(317): error: too many arguments in function call

    3 errors detected in the compilation of "/tmp/tmpxft_00005b52_00000000-11_nvjpeg_decoder.compute_70.cpp1.ii".
    CMake Error at dali_generated_nvjpeg_decoder.cu.o.cmake:266 (message):
      Error generating file
      /home/dali/build/dali/CMakeFiles/dali.dir/pipeline/operators/decoder/./dali_generated_nvjpeg_decoder.cu.o

    
    dali/CMakeFiles/dali.dir/build.make:597: recipe for target 'dali/CMakeFiles/dali.dir/pipeline/operators/decoder/dali_generated_nvjpeg_decoder.cu.o' failed
    make[2]: *** [dali/CMakeFiles/dali.dir/pipeline/operators/decoder/dali_generated_nvjpeg_decoder.cu.o] Error 1
    CMakeFiles/Makefile2:487: recipe for target 'dali/CMakeFiles/dali.dir/all' failed
    make[1]: *** [dali/CMakeFiles/dali.dir/all] Error 2
    Makefile:127: recipe for target 'all' failed    
    make: *** [all] Error 2

**Comment by JanuszL** [comment]
@jantonguirao ?

**Comment by jantonguirao** [comment]
@kkjh0723 
Thank you for your feedback. It is indeed a build error that went unnoticed recently.
We have now fixed it, so please download latest master and the error should be gone.

**Comment by kkjh0723** [comment]
@jantonguirao Thanks very much for the help. It seems the error is gone. However I got another error related to openCV. I will close this issue and open separate issue for it.
