### ISSUE TITLE
How to build the DALI docker image?

### ISSUE THREAD

**Issue by frankie-yanfeng** [NVIDIA/DALI#747]
Hello, 

In the process of build the docker image, I encountered the below issue and have no idea how to solve it, so after check the issues, requests and wiki, there is no relevant clues.

 aiq@aiq-frank:~/Downloads/DALI/docker$ ./build.sh 
+ export PYVER=3.6
+ PYVER=3.6
+ export PYV=36
+ PYV=36
+ export CUDA_VERSION=10
+ CUDA_VERSION=10
+ export NVIDIA_BUILD_ID=12345
+ NVIDIA_BUILD_ID=12345
+ export CREATE_WHL=YES
+ CREATE_WHL=YES
+ export CREATE_RUNNER=NO
+ CREATE_RUNNER=NO
+ export DEPS_IMAGE=dali_cu10.deps
+ DEPS_IMAGE=dali_cu10.deps
+ export BUILDER=dali_36_cu10.build
+ BUILDER=dali_36_cu10.build
+ export RUN_IMG=dali_36_cu10.run
+ RUN_IMG=dali_36_cu10.run
+ set -o errexit
+ pushd ../third_party/manylinux/
~/Downloads/DALI/third_party/manylinux ~/Downloads/DALI/docker
+ git checkout 96b47a25673b33c728e49099a3a6b1bf503a18c2
fatal: reference is not a tree: 96b47a25673b33c728e49099a3a6b1bf503a18c2

**Comment by klecki** [comment]
Hi,
the manylinux is a git submodule, and git does not clone them automatically.

Please try downloading the submodules by running
```
git submodule update --init --recursive
```
in the main directory of your dali source code clone.

Regards,
Krzysztof.
