### ISSUE TITLE
Image distortion with a probability

### ISSUE THREAD

**Issue by dprylipko** [NVIDIA/DALI#756]
I would like to use NVIDIA DALI library to replace my current image pre-processing pipeline written in TensorFlow.

Currently I have the following code that applies random contrast distortion with the probability 0.5:

    def random_contrast(image, lower=0.5, upper=1.5, prob=0.5, seed=None):
        random_value = random_float(seed=seed)
        image = tf.cond(tf.greater(prob, random_value),
                        lambda: tf.image.random_contrast(image, lower=lower, upper=upper, seed=seed),
                        lambda: image)
        return image

The corresponding [Contrast][2] op from DALI allows me to randomly alter the image contrast:

    class MyPipeline(dali.pipeline.Pipeline):
        def __init__(self, ...):
            self.input = dali.ops.TFRecordReader(...)
            ...
    
            self.random_contrast_value = dali.ops.Uniform(range=[0.5, 1.5])
            self.random_contrast = dali.ops.Contrast()
    
    
        def define_graph(self):
            # Read images and labels
            inputs = self.input(name="Reader")
            images = inputs["image/encoded"]
            labels = inputs["image/class/label"].gpu()
    
            # Decode and augmentation
            images = self.decode(images)
            images = self.resize(images)

            images = self.random_contrast(images.gpu(), contrast=self.random_contrast_value())
    
            return (images, labels)

  
But this will apply the distortion to every single image. How can I make the operation being called only with 50% probability?

 

  [1]: https://github.com/NVIDIA/DALI
  [2]: https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html#contrast

**Comment by JanuszL** [comment]
Hi,
You can try using [math expression](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/expressions/expr_conditional_and_masking.html) to conditionally apply the result of the operator. We have the native conditional exaction support in our roadmap but we are not there yet.

**Comment by JanuszL** [comment]
Hi,

You should be able to:
```
  contrast = fn.random.uniform(range=[-0.5, 0.5]) * fn.random.coin_flip()
  imgs = fn.contrast(imgs, contrast=contrast + 1)
```

**Comment by twmht** [comment]
@JanuszL 

Does Dali supports like probability 0.1? not just 0.5.
