### ISSUE TITLE
File mapping failed

### ISSUE THREAD

**Issue by wait1988** [NVIDIA/DALI#763]
When I follow the Coco Reader tutorial,I got the "File mapping failed error".The corresponding image exists and can be opened normally.So how to solve this problem?

Tutorial link:
https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/coco_reader.html

**Comment by JanuszL** [comment]
Hi,
Could you paste the full error message?
Could you double check if the path returned in the error, like in this one
```
Critical error in pipeline: Error in thread 0: [/home/user/Dali/dali/dali/util/local_file.cc:89] File mapping failed: /data/coco/coco-2017/coco2017f/val2017/000000397133.jpg
```
is proper? Maybe you have misspelled it?

**Comment by wait1988** [comment]
@JanuszL RuntimeError: Critical error in pipeline: Error in thread 0: [/opt/dali/dali/util/local_file.cc:89] File mapping failed:~/dataset/coco/val2017/val2017/000000397133.jpg

**Comment by JanuszL** [comment]
Hi,
I would recommend using full paths, without `~` as C++/C open file functions don't understand them.
Please let us know if that works.

**Comment by wait1988** [comment]
@JanuszL Actually I use the full path in my code.Besides,based on your previous error msg,it's just the same image.

**Comment by JanuszL** [comment]
Based on you error message you use `~/dataset/coco/val2017/val2017` which is relative to your home dir. Does this problem appear in other examples as well?

**Comment by wait1988** [comment]
@JanuszL I've hidden my absolute path.I use ExternalInputIterator,it's totally fine.

**Comment by JanuszL** [comment]
I mean other examples with readers - like getting started.ipynb. I want to check if this is a problem of this particular reader, the problem with the COCO data set you have or a general problem with accessing files from DALI in your configuration.

**Comment by wait1988** [comment]
@JanuszL Other readers are totally fine except VideoReader.Because my gpu is 980ti.

**Comment by JanuszL** [comment]
@wait1988 - the error is not because of the GPU. As other examples work well it means that DALI can access and open files on your storage. The error you see in the COCO reader indicates that for some reason DALI cannot access files from this particular data set, and I would rather search for the reason outise DALI, like path permissions or something like that..
I have also noticed that `val2017` repeats twice in your path, can you copy-paste the exact path from the error and cal `ls` on it because I don't really have another idea what is happening on your configuration.

**Comment by wait1988** [comment]
@JanuszL Yep,an extra val2017.

**Comment by wait1988** [comment]
@JanuszL Sorry to bother you again.When I run Coco Reader without augumentation,the result is normal.However,when I run Coco Reader with augumentation,the bbox coordinates of width and height are wrong.My code is as follows:

from __future__ import print_function
from nvidia.dali.pipeline import Pipeline
import nvidia.dali.ops as ops
import nvidia.dali.types as types
import matplotlib.pyplot as plt
import matplotlib.patches as patches
import random
from time import time

subset = "val"
file_root = "/home/sunqin/deep_learning/dataset/coco/" + subset + "2017"
annotations_file = "/home/sunqin/deep_learning/dataset/coco/annotations/instances_" + subset + "2017.json"
num_gpus = 1
batch_size = 16

class COCOPipeline(Pipeline):
    def __init__(self, batch_size, num_threads, device_id):
        super(COCOPipeline, self).__init__(batch_size, num_threads, device_id, seed = 15)
        self.input = ops.COCOReader(file_root = file_root, annotations_file = annotations_file,
                                     shard_id = device_id, num_shards = num_gpus, ratio=True)
        self.decode = ops.nvJPEGDecoder(device = "mixed", output_type = types.RGB)

    def define_graph(self):
        inputs, bboxes, labels = self.input()
        images = self.decode(inputs)
        return (images, bboxes, labels)

class COCOAugPipeline(Pipeline):
    def __init__(self, batch_size, num_threads, device_id):
        super(COCOAugPipeline, self).__init__(batch_size, num_threads, device_id, seed = 15)
        self.input = ops.COCOReader(file_root = file_root, annotations_file = annotations_file,
                                     shard_id = device_id, num_shards = num_gpus, ratio=True, ltrb=True)
        self.decode = ops.nvJPEGDecoder(device = "mixed", output_type = types.RGB)
        self.flip = ops.Flip(device = "gpu")
        self.bbflip = ops.BbFlip(device = "cpu", ltrb=True)
        self.paste_pos = ops.Uniform(range=(0,1))
        self.paste_ratio = ops.Uniform(range=(1,2))
        self.coin = ops.CoinFlip(probability=0.5)
        self.coin2 = ops.CoinFlip(probability=0.5)
        self.paste = ops.Paste(device="gpu", fill_value=(32,64,128))
        self.bbpaste = ops.BBoxPaste(device="cpu", ltrb=True)
        self.prospective_crop = ops.RandomBBoxCrop(device="cpu",
                                                   aspect_ratio=[0.5, 2.0],
                                                   thresholds=[0.1, 0.3, 0.5],
                                                   scaling=[0.8, 1.0],
                                                   ltrb=True)
        self.slice = ops.Slice(device="gpu")

    def define_graph(self):
        rng = self.coin()
        rng2 = self.coin2()

        inputs, bboxes, labels = self.input()
        images = self.decode(inputs)

        # Paste and BBoxPaste need to use same scales and positions
        ratio = self.paste_ratio()
        px = self.paste_pos()
        py = self.paste_pos()
        images = self.paste(images, paste_x = px, paste_y = py, ratio = ratio)
        bboxes = self.bbpaste(bboxes, paste_x = px, paste_y = py, ratio = ratio)

        crop_begin, crop_size, bboxes, labels = self.prospective_crop(bboxes, labels)
        images = self.slice(images, crop_begin, crop_size)

        images = self.flip(images, horizontal = rng, vertical = rng2)
        bboxes = self.bbflip(bboxes, horizontal = rng, vertical = rng2)

        return (images, bboxes, labels)

start = time()
pipes = [COCOPipeline(batch_size=batch_size, num_threads=2, device_id = device_id)  for device_id in range(num_gpus)]
for pipe in pipes:
    pipe.build()
total_time = time() - start
print("Computation graph built and dataset loaded in %f seconds." % total_time)

pipe_out = [pipe.run() for pipe in pipes]

images_cpu = pipe_out[0][0].as_cpu()
bboxes_cpu = pipe_out[0][1]
labels_cpu = pipe_out[0][2]
img_index = 12


img = images_cpu.at(img_index)

H = img.shape[0]
W = img.shape[1]
fig,ax = plt.subplots(1)

ax.imshow(img)
bboxes = bboxes_cpu.at(img_index)
labels = labels_cpu.at(img_index)
categories_set = set()
for label in labels:
    categories_set.add(label[0])

category_id_to_color = dict([ (cat_id , [random.uniform(0, 1) ,random.uniform(0, 1), random.uniform(0, 1)]) for cat_id in categories_set])

for bbox, label in zip(bboxes, labels):
    rect = patches.Rectangle((bbox[0]*W,bbox[1]*H),bbox[2]*W,bbox[3]*H,linewidth=1,edgecolor=category_id_to_color[label[0]],facecolor='none')
    ax.add_patch(rect)
plt.show()



And the results: 
![QQ图片20190416184525](https://user-images.githubusercontent.com/12405314/56203459-e2906780-6077-11e9-85ab-ce1f7847e12b.png)
![QQ图片20190416184538](https://user-images.githubusercontent.com/12405314/56203460-e328fe00-6077-11e9-8de0-f4afc6c0ce5e.png)

**Comment by awolant** [comment]
Hi @wait1988 ,
in the second pipeline you have `ltrb=True` for `COCOReader`. This parameter changes the output format of the boxes to left-top-right-bottom. First pipeline uses left-top-width-height. As we can see, left-top corners are properly aligned, so I think this might be the issue here.

**Comment by wait1988** [comment]
Thanks for your information.It's really helpful.
change
(bbox[0]*W,bbox[1]*H),bbox[2]*W,bbox[3]*H
to
(bbox[0]*W,bbox[1]*H),(bbox[2]-bbox[0])*W,(bbox[3]-bbox[1])*H

**Comment by prajotsl123** [comment]
yes...
this happens when your image path is incorrect
