### ISSUE TITLE
Docker build

### ISSUE THREAD

**Issue by hholst80** [NVIDIA/DALI#793]
Please do not execute `docker system prune -f` in the build script. Feel free to clean up build and run containers that the DALI toolkit has created but do not assume that it is safe to "cleanup" the entire system. 

```
$ docker system prune
WARNING! This will remove:
        - all stopped containers
        - all networks not used by at least one container
        - all dangling images
        - all dangling build cache
Are you sure you want to continue? [y/N]
```

**Comment by JanuszL** [comment]
Hi,
It is manylinux thing - https://github.com/pypa/manylinux/commit/4daf244a7552c3a7c3c9894bf37e9f52181e1dc9#diff-0b83f9dedf40d7356e5ca147a077acb4.
I will update the manylinux base commit to include that fix.

**Comment by JanuszL** [comment]
Fix in https://github.com/NVIDIA/DALI/pull/795
