### ISSUE TITLE
Looking for nvjpegBufferPinnedCreate - not found

### ISSUE THREAD

**Issue by cheneyzhao** [NVIDIA/DALI#794]
Hello, 
I tried to compile DALI from source, and got "Looking for nvjpegBufferPinnedCreate - not found".
I checked nvjpeg.h of both 10.1 and 9.0-v0.2.0, but no nvjpegBufferPinnedCreate definition.
nvjpegCreateEx works fine. Is nvjpegBufferPinnedCreate deprecated? Will it impact performance of DALI without nvjpegBufferPinnedCreate support? Thanks.

**Comment by JanuszL** [comment]
Hi,
This codes uses internal version of nvJPEG which will be released soon. We wanted to make sure that DALI will support it since the day one.
Regarding performance, with this API it will be faster in some use cases.
