### ISSUE TITLE
The correct way of using "ops.FileReader"

### ISSUE THREAD

**Issue by oscarriddle** [NVIDIA/DALI#8]
Python 2.7
Tensorflow 1.7
CentOS 7
CUDA 9.2
cuDNN 7.0.5
Installed DALI from pip

I'm trying the example named Getting Started, that I intended to traverse a directory of plenty of jpgs.
This is my script, and its output, seems like it can't find any jpg images.
```
for root, dir, files in os.walk("img"):
        depth = root.count('/')
        ret = ""
        if depth > 0:
            ret += "  " * (depth - 1) + "|-"
        print ret + root
        for items in fnmatch.filter(files, "*"):
                print (" " * len(ret)) + "|-" + items

image_dir = './img'
batch_size = 8
class SimplePipeline(Pipeline):
    def __init__(self, batch_size, num_threads, device_id):
        super(SimplePipeline, self).__init__(batch_size, num_threads, device_id, seed = 12)
        self.input = ops.FileReader(file_root = image_dir)
        self.decode = ops.HostDecoder(output_type = types.RGB)

    def define_graph(self):
        jpegs, labels = self.input()
        images = self.decode(jpegs)
        return (images, labels)
help(ops)

pipe = SimplePipeline(batch_size, 1, 0)
pipe.build()

pipe_out = pipe.run()
print(pipe_out)
images, labels = pipe_out
print("Images is_dense_tensor: " + str(images.is_dense_tensor()))
print("Labels is_dense_tensor: " + str(labels.is_dense_tensor()))
```
Output:
```
$ python trt_dali.py
/home/karafuto/lib/python2.7/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
WARNING:tensorflow:From /home/karafuto/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
img
|-img.jpg

read 0 files from 1 directories
Segmentation fault (core dumped)

```

The first for loop has printed out that an image that named img.jpg is located under directory img/, however, ops.FileReader found 0 files.

Any idea will be welcome.

**Comment by JanuszL** [comment]
Hi,
File reader requires file tree that is of depth 2. So there are two ways to use it:
- keep files in following dir structure: root/label/image
- providing the list of files
We will update documentation to make describe it more verbosely.

**Comment by oscarriddle** [comment]
@JanuszL Hi, Thanks for your reply.
Could you leave a detail comment please? 

> keep files in following dir structure: root/label/image

I tried to put the image  under a dir named 'dog', which shall be the label name (img/dog/img.jpg). But I still get the fault:
```
Instructions for updating:
Use the retry module or similar alternatives.
img
|-img/dog
  |-img.jpg

read 0 files from 1 directories
Segmentation fault (core dumped)
```

> providing the list of files

Could you leave more detailed comment on how to import filelist to DALI?

**Comment by ptrendx** [comment]
@oscarriddle In the earlier version of the comment you said that putting the expected directory structure still did not work - I assume the fact that you edited your comment means that it is not the case anymore?

About the list of files, here is the excerpt about `file_list` parameter of the FileReader documentation (please let me know if the description of this parameter is not clear):

`file_list` (string) – Path to the file with a list of pairs `file label` (leave empty to traverse the file_root directory to obtain files and labels) (default value: ``)

You can access documentation of any operator from Python using `help()`: `help(nvidia.dali.ops.FileReader)`.

**Comment by oscarriddle** [comment]
Hi @ptrendx 
Thanks for your reply.

Yes, I noticed I set it in a wrong way, and now it can traverse directory and read images.

About the list of files, I need to give a try and I think that makes sense. Generally, in my way, the images are stored separately in different dirs with their label as the name of the dir. So my way is traversing the dirs tree of all images and extract their label from the their path by regular ops.

I will try to use the file_list later.

Thanks

**Comment by cliffwoolley** [comment]
We also now fixed the segfault when no images are found, by the way.

**Comment by zhengge** [comment]
@oscarriddle @pdckxd 
Could you give me a example of file_list?
Thanks!

**Comment by cysmith** [comment]
Can DALI be used for image-to-image translation problems where the "label" is a target image (not a classification string)? For example, input: image from self-driving car, label: semantic segmentation map.
