### ISSUE TITLE
Pipeline is not serializing

### ISSUE THREAD

**Issue by ZinovievVladimir** [NVIDIA/DALI#805]
Why I can't serialize pipeline with DALIIterator, that using input to Slice from output of RandomBBoxCrop? I'm getting the next error:
`DALI daliCreatePipeline(&pipe_handle_, serialized_pipeline.c_str(), serialized_pipeline.length(), batch_size, num_threads, device_id, prefetch_queue_depth_) failed: [/opt/dali/dali/pipeline/pipeline.cc:160] Assert on "it != edge_names_.end()" failed: Input 'contiguous_RandomBBoxCrop_id_3_output_0' to op 'Slice' is not known to the pipeline.
`

**Comment by JanuszL** [comment]
Hi,
Is your code running without serialization? Can you paste your code or some other minimal reproduction example here?

**Comment by ZinovievVladimir** [comment]
Hi, @JanuszL, thank you for fast answer!
Here is my "small" code example:
`from nvidia.dali.pipeline import Pipeline
import nvidia.dali.ops as ops
import tensorflow as tf
import nvidia.dali.plugin.tf as dali_tf

file_root = "/home/vzinoviev/Downloads/test_images/val2017"
annotations_file = "/home/vzinoviev/Downloads/annotations/instances_val2017.json"


class COCOPipeline(Pipeline):
    def __init__(self, batch_size, num_threads, device_id):
        super(COCOPipeline, self).__init__(batch_size, num_threads, device_id)
        self.input = ops.COCOReader(file_root=file_root, annotations_file=annotations_file)
        self.decode = ops.nvJPEGDecoder(device="mixed")
        self.crop = ops.RandomBBoxCrop(device="cpu")
        self.slice = ops.Slice(device="gpu")
        self.resize = ops.Resize(device="gpu", resize_x=256, resize_y=256)

    def define_graph(self):
        inputs, bboxes, labels = self.input()
        images = self.decode(inputs)
        crop_begin, crop_size, bboxes, labels = self.crop(bboxes, labels)
        images = self.slice(images, crop_begin, crop_size)
        images = self.resize(images)
        return images


pipe = COCOPipeline(batch_size=32, num_threads=2, device_id=0)
daliop = dali_tf.DALIIterator()

with tf.device('/gpu'):
    image, bbox, label = daliop(pipeline=pipe,
                                shapes=[(32, 256, 256, 3), (), ()],
                                dtypes=[tf.uint8, tf.float32, tf.int32])
with tf.Session() as sess:
    imgs, bbs, lbls = sess.run([image])`

**Comment by JanuszL** [comment]
Hi,
I don't see any obvious error. We will check that and get back to you.

**Comment by JanuszL** [comment]
Tracked as DALI-756

**Comment by ZinovievVladimir** [comment]
Hi! Is there any news about that bug? I really need that feature...

**Comment by ZinovievVladimir** [comment]
It seems, that was my mistake. I used output from RandomBBoxCrop, that was on the cpu, but Slice was gpu version. But I have another question. If I understand right, this is commit, that must include GPU version of RandomBBoxCrop? https://github.com/NVIDIA/DALI/pull/269 But there is not GPU version of this function in your library now?

**Comment by JanuszL** [comment]
Hi,
It this is a bug because we are doing similar thing in the [COCO with the augmentations example](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/detection_pipeline.html) and it works. And you don't need to have RandomBBoxCrop on the GPU to consume data in GPU Slice.
Following pipeline works:
```
class COCOPipeline(Pipeline):
    def __init__(self, batch_size, num_threads, device_id):
        super(COCOPipeline, self).__init__(batch_size, num_threads, device_id)
        self.input = ops.COCOReader(file_root=file_root, annotations_file=annotations_file, ratio=True, ltrb=True)
        self.decode = ops.nvJPEGDecoder(device="mixed")
        self.crop = ops.RandomBBoxCrop(device="cpu")
        self.slice = ops.Slice(device="gpu")
        self.resize = ops.Resize(device="gpu", resize_x=256, resize_y=256)

    def define_graph(self):
        inputs, bboxes, labels = self.input()
        images = self.decode(inputs)
        crop_begin, crop_size, bboxes, labels = self.crop(bboxes, labels)
        images = self.slice(images, crop_begin, crop_size)
        images = self.resize(images)
        return images


pipe = COCOPipeline(batch_size=32, num_threads=2, device_id=0)
pipe.build()
pipe.run()
```
While this doesn't:
```
from nvidia.dali.pipeline import Pipeline
import nvidia.dali.ops as ops
import tensorflow as tf
import nvidia.dali.plugin.tf as dali_tf

file_root = "/data/coco/coco-2017/coco2017/val2017"
annotations_file = "/data/coco/coco-2017/coco2017/annotations/instances_val2017.json"

class COCOPipeline(Pipeline):
    def __init__(self, batch_size, num_threads, device_id):
        super(COCOPipeline, self).__init__(batch_size, num_threads, device_id)
        self.input = ops.COCOReader(file_root=file_root, annotations_file=annotations_file, ratio=True, ltrb=True)
        self.decode = ops.nvJPEGDecoder(device="mixed")
        self.crop = ops.RandomBBoxCrop(device="cpu")
        self.slice = ops.Slice(device="gpu")
        self.resize = ops.Resize(device="gpu", resize_x=256, resize_y=256)

    def define_graph(self):
        inputs, bboxes, labels = self.input()
        images = self.decode(inputs)
        crop_begin, crop_size, bboxes, labels = self.crop(bboxes, labels)
        images = self.slice(images, crop_begin, crop_size)
        images = self.resize(images)
        return images


pipe = COCOPipeline(batch_size=32, num_threads=2, device_id=0)
serialized_pipeline = pipe.serialize()

new_pipe = Pipeline(batch_size=32, num_threads=2, device_id=0)
new_pipe.deserialize_and_build(serialized_pipeline)
```

**Comment by JanuszL** [comment]
I fixed this in https://github.com/NVIDIA/DALI/pull/848. It should be available in the next DALI release.
