### ISSUE TITLE
DALI can't be linked with protobuf.

### ISSUE THREAD

**Issue by ZinovievVladimir** [NVIDIA/DALI#817]
Hi! I tried to build NVIDIA DALI from source of this repository and get that error. Can you help me with this problem, please?
I used master branch, CUDA 9.0, GCC 5.5.0, Protobuf 3.7.1 from github repository.
```
[ 95%] Linking CXX shared library python/nvidia/dali/libdali.so
/usr/bin/ld: /usr/local/lib/libprotobuf.a(arena.o): relocation R_X86_64_TPOFF32 against hidden symbol `_ZN6google8protobuf8internal9ArenaImpl13thread_cache_E' can not be used when making a shared object
/usr/bin/ld: /usr/local/lib/libprotobuf.a(descriptor.o): relocation R_X86_64_PC32 against symbol `_ZNSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS5_EED1Ev' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
```

**Comment by jantonguirao** [comment]
Hello @ZinovievVladimir,

Could you try to recompile protobuf with "-fPIC" option?
```
    ./autogen.sh 
    ./configure CXXFLAGS="-fPIC" --prefix=/usr/local --disable-shared 
    make 
    sudo make install
```

**Comment by ZinovievVladimir** [comment]
@jantonguirao 
Thank you! But there is another one problem: it seems, that gcc > 5.* version is support avx512 instructions set by default. And somewhere in your code or maybe in dependencies it using intrinsincs. So, my CPU is don't support that instructions and i'm getting failes because of that. 
```
/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512vlintrin.h(11300): error: argument of type "void *" is incompatible with parameter of type "long long *"
```
I write it just because in your README.md you said that you support gcc > 4.9.2, but that is not, how I see... 
And so, I need to build gcc 4.9.2 from source, and it very hard :)

**Comment by JanuszL** [comment]
Hi @ZinovievVladimir,
Could you provide a full error log from your build?
I see that `dali/pipeline/operators/transpose/cutt` has AVX code path, but is up to your compiler to tell if it supports it or not (https://stackoverflow.com/questions/28939652/how-to-detect-sse-sse2-avx-avx2-avx-512-avx-128-fma-kcvi-availability-at-compile).
What I can recommend to you is to disable that instruction in the GCC via compiler options in https://github.com/NVIDIA/DALI/blob/master/CMakeLists.txt#L68.

**Comment by ZinovievVladimir** [comment]
@JanuszL There are only errors like that i have send already. Thank you. I'll try to build gcc 4.9.2 ;)

**Comment by ZinovievVladimir** [comment]
@jantonguirao @JanuszL Against, I've got more new errors...
```
[ 83%] Linking CXX executable python/nvidia/dali/test/dali_benchmark.bin
python/nvidia/dali/libdali.so: undefined reference to `std::__cxx11::basic_st                                                                                ring<char, std::char_traits<char>, std::allocator<char> >::operator[](unsigne                                                                                d long)'
/usr/local/lib/libopencv_imgcodecs.so.4.1.0: undefined reference to `vtable f                                                                                or std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator                                                                                <char> >@GLIBCXX_3.4.21'
python/nvidia/dali/libdali.so: undefined reference to `std::__cxx11::basic_st                                                                                ring<char, std::char_traits<char>, std::allocator<char> >::basic_string(unsig                                                                                ned long, char, std::allocator<char> const&)'
/usr/local/lib/libopencv_imgcodecs.so.4.1.0: undefined reference to `std::__c                                                                                xx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find                                                                                (char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'
python/nvidia/dali/libdali.so: undefined reference to `google::protobuf::Repe                                                                                atedPtrField<std::string>::Add()'
python/nvidia/dali/libdali.so: undefined reference to `std::__cxx11::basic_st                                                                                ring<char, std::char_traits<char>, std::allocator<char> >::find_first_not_of(                                                                                char const*, unsigned long) const'
```

**Comment by ZinovievVladimir** [comment]
@jantonguirao @JanuszL Maybe I just need to rebuild opencv.

**Comment by JanuszL** [comment]
Have you tried [docker based build](https://github.com/NVIDIA/DALI#compiling-dali-from-source-using-docker-builder---recommended)?

**Comment by JanuszL** [comment]
If it still deosn't work please reopen.

**Comment by hx173149** [comment]
> @jantonguirao @JanuszL I've got more new errors...
> 
> ```
> [ 83%] Linking CXX executable python/nvidia/dali/test/dali_benchmark.bin
> python/nvidia/dali/libdali.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator[](unsigned long)'
> /usr/local/lib/libopencv_imgcodecs.so.4.1.0: undefined reference to `vtable for std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
> python/nvidia/dali/libdali.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(unsigned long, char, std::allocator<char> const&)'
> /usr/local/lib/libopencv_imgcodecs.so.4.1.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'
> python/nvidia/dali/libdali.so: undefined reference to `google::protobuf::RepeatedPtrField<std::string>::Add()'
> python/nvidia/dali/libdali.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_first_not_of(char const*, unsigned long) const'
> ```

Hello @JanuszL and I have installed gcc 5.1 and recompile protobuf with -fPIC
I have got the same error:
python/nvidia/dali/libdali.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator[](unsigned long)'
/usr/local/lib/libopencv_imgcodecs.so.4.1.0: undefined reference to `vtable for std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
python/nvidia/dali/libdali.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(unsigned long, char, std::allocator<char> const&)'
/usr/local/lib/libopencv_imgcodecs.so.4.1.0: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'
python/nvidia/dali/libdali.so: undefined reference to `google::protobuf::RepeatedPtrField<std::string>::Add()'
python/nvidia/dali/libdali.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_first_not_of(char const*, unsigned long) const'

**Comment by JanuszL** [comment]
Hi,

Please try with the docker build first. I see:
```
/usr/local/lib/libopencv_imgcodecs.so.4.1.0: undefined reference to `vtable for std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
```
Which is not a DALI file and it also reports missing symbols.
```
google::protobuf::RepeatedPtrField<std::string>::Add()
```
Is not a problem related to `-fPIC` but what functions libprotobuf.so exports. Can you run:
```
make VERBOSE=1
```
to see what include paths are used, which libraries are linked. Maybe your build pick the system protobuf instead of one you custom built?

**Comment by hx173149** [comment]
Hello @JanuszL 
Thanks, I have already slove the problem, this problem is like this:

**Compile the protobuf with gcc 4.8, but compile the dali with gcc 5.1, this will generate the problem!
Recomplie the dali with gcc 5.1 will solve the problem!**

**Comment by JanuszL** [comment]
:+1
