### ISSUE TITLE
Add example with CAFFE2

### ISSUE THREAD

**Issue by yuvval** [NVIDIA/DALI#83]
Would it be possible to add an example with piping to CAFFE2?
Currently I only found such example on some [NVIDIA presentation](http://on-demand.gputechconf.com/gtc/2018/presentation/s8906-fast-data-pipelines-for-deep-learning-training.pdf). The [LMDB example](https://github.com/NVIDIA/DALI/blob/master/docs/examples/dataloading_lmdb.ipynb), only relates for reading CAFFE2 data, without piping it to CAFFE2.

It will be great to have a complete and official example.

Thank you

**Comment by JanuszL** [comment]
Hi,

CAFEE2 and PyTorch will be merged soon https://caffe2.ai/blog/2018/05/02/Caffe2_PyTorch_1_0.html and that is why we decided not to support CAFFE2.
We recommend using PyTorch instead.
