### ISSUE TITLE
VideoReader, getting inconsistent frames

### ISSUE THREAD

**Issue by grez72** [NVIDIA/DALI#834]
Hi,

I'm following the VideoReader example [here](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/video/video_reader_simple_example.html) for dali 0.8.1, but I'm having trouble getting the frames in the correct order.

When I iterate through sequences, the images are not in the correct order, unless add a delay in my loop. Without this delay, the frames are incorrect (they come from earlier in the video).

```
batch_size=1
video_files=['myvid.mp4']
shuffle=False
pipe = VideoPipe(batch_size=batch_size, num_threads=2, device_id=0, data=video_files, shuffle=shuffle)
pipe.build()
for i in range(n_iter):
    pipe_out = pipe.run()    

    # images in the wrong order 
    sequences_out = pipe_out[0].as_cpu().as_array()

    # but if I add a delay, the frames will appear in the correct order
    # time.sleep(.1)
```

Without the sleep delay, the images aren't in a random order, but what I see when I run show_sequence(sequences_out[0]) is a sequence from an earlier point in the video (often from near the beginning).

I discovered this issue when trying to use VideoReader with the pytorch plugin DALIGenericIterator, and found that the video frames were not in the correct order when using DALIGenericIterator. But then I discovered that even with the example above, I couldn't get the frames in the correct order without adding a delay.

Is this a bug, or should I be configuring something differently? Should I be able to use VideoReader with the pytorch DALIGenericIterator?

**Comment by JanuszL** [comment]
Hi,
This is definitely not expected. We will look into this. Thank you for reporting this issue.

**Comment by JanuszL** [comment]
Tracked as DALI-785.

**Comment by Mmdixon** [comment]
I have a very similar setup and problem where using the `VideoReader`, `shuffle=False` I get frames out of order. Moreover, I am missing frames from the whole epoch.

For example, making a test video that is just the frame number on a blue screen at 10 FPS for 10s:
```
ffmpeg -f lavfi -i color=c=blue:s=64x64:d=10:r=10 \
-c:v h264 \
-vf "format=pix_fmts=yuv420p, drawtext=fontsize=16: fontcolor=white: x=(w-text_w)/2: y=(h-text_h)/2: text='%{frame_num}'" \
test_frames.mp4
```
plotting the batches (`batch_size=5`, `sequence_length=10`) looks like:
![batch_missing](https://user-images.githubusercontent.com/1692726/57095850-d516e680-6ce1-11e9-9106-8d8f4af4cb58.png)
The second batch is wrong, missing frames > 60 and starts duplicating previous frames.

However, if I change `prefetch_queue_depth=1` (defaults to `2`) on the `Pipeline`, I get all the frames of the epoch and in the correct order.
![batch_whole](https://user-images.githubusercontent.com/1692726/57096086-65552b80-6ce2-11e9-9374-d04816fd0cce.png)

**Comment by grez72** [comment]
Thanks @Mmdixon for the suggestion, but as you note I still get frames out of order, even with ```prefetch_queue_depth=1```.

I had this issue with both DALI version 0.7.0, and 0.8.0. However, I just upgraded to version 0.9, and it appears that this issue has been resolved, but the frame rate is now much slower.

Testing with a 720x1280 video:

DALI v0.7.0: 32,000 fps! (but frames in the wrong order; I can confirm that frames were actually being iterated at this rate, but they were just the wrong frames).

DALI v0.9.0: 500 fps, frames now in the correct order.

I can get faster speeds with DALI v0.9.0 (e.g., > 1000 fps) by increasing the sequence_length, but nowhere near 32000 fps.

Greater than 1000 fps is more than 5x faster than I have achieved with cv2 or other options.

**Comment by JanuszL** [comment]
Hi,
We have just recently fixed the problem with synchronization during copy-out of data from the DALI pipeline in https://github.com/NVIDIA/DALI/pull/807. Also, some other bugs were fixed since 0.7 and 0.8.
This could explain why you had these extremely high numbers. Speed mostly depends on how much time is spent on decoding and how much does it take to seek the video container and copy data. Numbers around 500 seems to be more aligned with https://developer.nvidia.com/nvidia-video-codec-sdk than 32000.
@Mmdixon - can you test with DALI 0.9.1?

**Comment by Mmdixon** [comment]
@JanuszL Updated to 0.9.1 and tried the various combinations of `batch_size` and other settings as above and it all worked out as expected (all frames and in order). :+1:

**Comment by JanuszL** [comment]
Great!
Closing.

**Comment by Harsha-Musunuri** [comment]
Hi, I see this issue in version Dali 1.32.0..
