### ISSUE TITLE
Dali and uber horovod incompatibility issues

### ISSUE THREAD

**Issue by wangguangyuan** [NVIDIA/DALI#84]
`
import tensorflow as tf
import horovod.tensorflow as hvd
from models import imagenet_resnet_v2
from models import resnet_v2
from dataloader import get_batch_images, FileReadPipeline

#loss function
def _loss(logits, labels, weight_decay=1e-4):
    labels = tf.cast(labels, tf.int32)
    cross_entropy = tf.nn.sparse_softmax_cross_entropy_with_logits(logits=logits, labels=labels,
                                                                   name='cross_entropy_per_example')
    loss = tf.reduce_mean(cross_entropy, name='cross_entropy')

    l2_losses = [weight_decay * tf.nn.l2_loss(v) for v in tf.trainable_variables()
                 if 'beta' not in v.name and 'gamma' not in v.name]

    top_1 = tf.nn.in_top_k(logits, labels, 1)
    top1_acc = tf.reduce_mean(tf.cast(top_1, tf.float32), name='top_1')
    total_loss = loss + tf.add_n(l2_losses)
    return total_loss, top1_acc

def main(_):
    save_path = '/share5/public/classification_data/imagenet1k/meta/absolute_train.txt'

    # Horovod: initialize Horovod.
    hvd.init()
    
   #Get the data format required by tensorflow through dali
    image, label = get_batch_images(pipe_name=FileReadPipeline, batch_size=32, num_threads=4,
                                    device_id=hvd.local_rank(),
                                    random_shuffle=True,
                                    file_list=save_path,
                                    initial_fill=4096)

   label = tf.squeeze(label)

   net = imagenet_resnet_v2(50, num_classes=1000, data_format='channels_last')
   train_output = net(image, is_training=True)
   train_loss, train_top1_acc = _loss(train_output, label)
   
   
   boundaries = [int(epoch) for epoch in [30, 60, 80, 90]]
   values = [0.1 * decay for decay in [1, 0.1, 0.01, 1e-3, 1e-4]]
   global_step = tf.contrib.framework.get_or_create_global_step()
    learning_rate = tf.train.piecewise_constant(tf.cast(global_step, tf.int32), boundaries, values)

    opt = tf.train.RMSPropOptimizer(learning_rate)

    # Horovod: add Horovod Distributed Optimizer.
    opt = hvd.DistributedOptimizer(opt)
    train_op = opt.minimize(train_loss, global_step=global_step)

    gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.5)
    config = tf.ConfigProto(gpu_options=gpu_options)
    with tf.Session(config=config) as sess:
        sess.run(tf.global_variables_initializer())
         
        #don't enable them work, but enable them don't work.
        if hvd.local_rank() == 0:
            print('local_rank: {}'.format(hvd.local_rank()))
            # sync_op = hvd.broadcast_global_variables(0)
            # sess.run(sync_op)

        for _ in range(50):
            ims, labs = sess.run([train_op, label])
            print(labs.shape)
`

When I don't enable sync_op = hvd.broadcast_global_variables(0) and sess.run(sync_op) to work properly，it doesn't work when I enable them. 
Horovod is a distributed training framework for TensorFlow, Keras, and PyTorch. The goal of Horovod is to make distributed Deep Learning fast and easy to use.
(https://github.com/uber/horovod)

[guangyuan@horovod_project]$ python test_speed.py
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
<dataloader.FileReadPipeline object at 0x7facc76c1650>
/gpu:0
(<tf.Tensor 'Dali:0' shape=(32, 224, 224, 3) dtype=float32>, <tf.Tensor 'Squeeze:0' shape=<unknown> dtype=int32>)
WARNING:tensorflow:From test_speed.py:82: get_or_create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.get_or_create_global_step
INFO:tensorflow:Hvd.size: 1
INFO:tensorflow:Hvd.local_rank: 0
INFO:tensorflow:Hvd.rand: 0
2018-07-30 14:54:15.793309: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-07-30 14:54:15.799875: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties:
name: Graphics Device major: 7 minor: 0 memoryClockRate(GHz): 1.912
pciBusID: 0000:02:00.0
totalMemory: 11.78GiB freeMemory: 10.86GiB
2018-07-30 14:54:16.316063: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 1 with properties:
name: Graphics Device major: 7 minor: 0 memoryClockRate(GHz): 1.912
pciBusID: 0000:83:00.0
totalMemory: 11.78GiB freeMemory: 10.87GiB
2018-07-30 14:54:16.316167: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0, 1
2018-07-30 14:54:17.029607: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-07-30 14:54:17.029664: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 1
2018-07-30 14:54:17.029676: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N N
2018-07-30 14:54:17.029683: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 1:   N N
2018-07-30 14:54:17.030162: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6029 MB memory) -> physical GPU (device: 0, name: Graphics Device, pci bus id: 0000:02:00.0, compute capability: 7.0)
2018-07-30 14:54:17.103240: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 6029 MB memory) -> physical GPU (device: 1, name: Graphics Device, pci bus id: 0000:83:00.0, compute capability: 7.0)
local_rank: 0
[root] *** Process received signal ***
[root] Signal: Segmentation fault (11)
[root] Signal code: Address not mapped (1)
[root] Failing at address: 0x10
Segmentation fault (core dumped)

**Comment by JanuszL** [comment]
Tracked as DALI-181

**Comment by JanuszL** [comment]
Hi,
Could you provide us info about `models` you are using and rest of the script (dataloader) so we could reproduce this on our side?

**Comment by wangguangyuan** [comment]
Hi,It is the fault of my side. Our server updated the software a few days ago, which caused some of my horovod libraries to be incompatible. I have reinstalled it.
I am coming back to adjust my program, can I provide a tensorflow overall example?
I do data loading through dali and horovod to do multi-machine communication to accelerate tensorflow and achieve good results.
Can I provide the entire example? Dali does solve the problem that tensorflow originally loaded data slowly, which is really great.

**Comment by JanuszL** [comment]
Hi,
As I understand after reinstalling horovod libraries everything works fine.
Regarding reproduction, next time please provide the full, stand-alone script we could run to reproduce the problem you have. Without it, the issue has a lower priority for us as we need to spend additional time trying to recreate env you have with bigger chance doing something different, which can prevent us from detecting the problem.
If the problem still exists please reopen this task.

**Comment by ptrendx** [comment]
It's great that DALI solves the input pipeline speed for you.
If you want to contribute an example of using Tensorflow with DALI, that's great too. Contributions are very welcome!
