### ISSUE TITLE
Choose the GPU

### ISSUE THREAD

**Issue by ZinovievVladimir** [NVIDIA/DALI#841]
Hi!

I have 3 GPUs and I can use DALI pipeline on multiple GPUs, but only choose count of GPU. I want to choose the numbers of GPU, for example like in Tensorflow : ```/device:GPU:0```, ```/device:GPU:2``` and do not use ```/device:GPU:1``` . Can I do this with your library?

**Comment by JanuszL** [comment]
Hi,
Yes, you can:
- [pipeline constructor](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/api.html#nvidia.dali.pipeline.Pipeline) accepts `device_id` which is the ID of the GPU you want to run a particular instance of the DALI pipeline (on the node you run it)
- any reader, like [FileReader](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html#nvidia.dali.ops.FileReader) accepts `num_shards` which is the total number of the GPUs you use in the whole training (it is about data sharding) and `shard_id` which data shard (global) should be assigned to this DALI instance
