### ISSUE TITLE
unsupported jpg image

### ISSUE THREAD

**Issue by yczhang1017** [NVIDIA/DALI#842]
DALI give me 2x times faster on my training dataset, but when I work on my test dataset, it seems there is a problemic images that cause my DALI dataloader to crash.

I got the following error:
File "/home/joytonight17/.local/lib/python3.7/site-packages/nvidia/dali/pipeline.py", line 289, in _share_outputs
    return self._pipe.ShareOutputs()
RuntimeError: Critical error in pipeline: [/opt/dali/dali/pipeline/operators/decoder/nvjpeg_decoder_decoupled_api.h
:174] [/opt/dali/dali/image/image_factory.cc:78] Assert on "CheckIsPNG(encoded_image, length) + CheckIsBMP(encoded_
image, length) + CheckIsGIF(encoded_image, length) + CheckIsJPEG(encoded_image, length) + CheckIsTiff(encoded_image
, length) == 1" failed: Encoded image has ambiguous format

My test dataset are dowloaded from web sources and has been converted into jpg files using PIL library.

It seems that pytorch dataloader can works well on the test dataset but My transform function here is not consistent with DALI. I am still figuring the right way of pytorch transform to agree with DALI operations.

**Comment by JanuszL** [comment]
Hi,
I think you should have file name included in the error message, so please examine what kind of file is causing this error. If it has a proper extension and you can open it with viewer then it is some error inside DALI. Providing this faulty image would be helpful for us to reproduce and fix the problem.

**Comment by yczhang1017** [comment]
I have a text file in the file list. It causes my problem. 

Thank you.

**Comment by JanuszL** [comment]
One comment from our side - if you just provide root dir then DALI will filter out extensions that are definitely not images and provide a warning about skipped files, if file list is provided then we believe that user knows what he is doing.

**Comment by zhiheng-ldj** [comment]
Hi,

I am facing a similar problem so I hope to discuss here:

My file_name is '/home/admin/0.jpg' and I can open it with viewer:

When I process it with DALI, it raises an error:

```
Assert on "CheckIsPNG(encoded_image, length) + CheckIsBMP(encoded_image, length) + CheckIsGIF(encoded_image, length) + CheckIsJPEG(encoded_image, length) + CheckIsTiff(encoded_image, length) + CheckIsPNM(encoded_image, length) == 1" failed: Encoded image has ambiguous format
```

Thanks for your help!

**Comment by JanuszL** [comment]
Can you share the problematic file so we can see what is wrong with it?

**Comment by zhiheng-ldj** [comment]
Do you mean the jpg file or py script?

**Comment by JanuszL** [comment]
File itself.

**Comment by zhiheng-ldj** [comment]
![0](https://user-images.githubusercontent.com/67734380/98087769-8e4c1300-1ebb-11eb-97a7-3267a6c222ab.jpg)

**Comment by JanuszL** [comment]
Hi,
I just tested with DALI 0.27 and it works fine, you can check the attached [test script](https://github.com/NVIDIA/DALI/files/5487602/Repro.zip) I have used.

**Comment by zhiheng-ldj** [comment]
Hi,

I have read your script and it works fine with mine.

However, I need to read the image path and decode in Dali pipeline as following:

```
for _ in range(self.batch_size):
            batch.append(np.frombuffer(bytes(image_path, encoding = "utf8"), dtype = np.uint8))
....
self.input = ops.ExternalSource()
self.decode = ops.ImageDecoder(device = "mixed", output_type = types.RGB)
....
def define_graph(self):
        self.jpegs_path = self.input()
        img = self.decode(self.jpegs_path)
```

Can I decode a file_path like this? Thanks for your help!

**Comment by JanuszL** [comment]
It should work, please check [this ExternalSource operator example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/external_input.html#Defining-the-data-source).

**Comment by zhiheng-ldj** [comment]
> It should work, please check [this ExternalSource operator example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/general/data_loading/external_input.html#Defining-the-data-source).

Hi, it still doesn't work for me.

I hope to read a file path (for example: '/home/admin/0.jpg') and decode it with ImageDecoder.

```
batch.append(np.frombuffer(b'/home/admin/0.jpg', dtype = np.uint8))
self.decode = ops.ImageDecoder(device = "mixed", output_type = types.RGB)
```

Is it possible that the version I used causes the error? I have tried loading the path from txt file and changing the image from jpg to png, it still raises the same error.

Appreciate your help!

**Comment by JanuszL** [comment]
@zhiheng-ldj - does the mentioned example work for you at all?
Can you provide self-contained repro we can run on our site, you can use https://github.com/NVIDIA/DALI_extra as a data source.
Provide code sniped is the same as in the mentioned ExternalSource example.

**Comment by zhiheng-ldj** [comment]
Hi,

Thanks for your help! I do not know how to provide a self-contained repro. Thus, I write a simple demo and can you help me see whether it could run on your side?

```
import types
import collections
import numpy as np
from random import shuffle
from nvidia.dali.pipeline import Pipeline
import nvidia.dali.ops as ops
import nvidia.dali.types as types

batch_size = 4

class ExternalInputIterator(object):
    def __init__(self, batch_size):
        self.batch_size = batch_size

    def __iter__(self):
        self.i = 0
        self.n = 1
        return self

    def __next__(self):
        batch = []
        labels = []
        for _ in range(self.batch_size):
            batch.append(np.frombuffer(b'/mnt/yunle/byebye/coco28/images/train/0.jpg', dtype = np.uint8))
            labels.append(np.array([1], dtype = np.uint8))
            self.i = (self.i + 1) % self.n
        return (batch, labels)
    
eii = ExternalInputIterator(batch_size)

class ExternalSourcePipeline(Pipeline):
    def __init__(self, batch_size, eii, num_threads, device_id):
        super(ExternalSourcePipeline, self).__init__(batch_size,
                                      num_threads,
                                      device_id,
                                      seed=12)

        self.source = ops.ExternalSource(source = eii, num_outputs = 2)
        self.decode = ops.ImageDecoder(device = "mixed", output_type = types.RGB)
        self.enhance = ops.BrightnessContrast(device = "gpu", contrast = 2)

    def define_graph(self):
        jpegs, labels = self.source()
        images = self.decode(jpegs)
        output = self.enhance(images)
        return (output, labels)
    
pipe = ExternalSourcePipeline(batch_size=batch_size, eii=eii, num_threads=2, device_id = 0)
pipe.build()
pipe_out = pipe.run()

print('Success!')
```

**Comment by zhiheng-ldj** [comment]
The jpg path need to be changed. Thanks! It raises an error on my side:

```
ssert on "CheckIsPNG(encoded_image, length) + CheckIsBMP(encoded_image, length) + CheckIsGIF(encoded_image, length) + CheckIsJPEG(encoded_image, length) + CheckIsTiff(encoded_image, length) + CheckIsPNM(encoded_image, length) == 1" failed: Encoded image has ambiguous format
```

**Comment by JanuszL** [comment]
I think you just misusing the `frombuffer` method - please [check its description](https://numpy.org/doc/stable/reference/generated/numpy.frombuffer.html#numpy-frombuffer).
You need to pass a buffer to it, not the file path. Now you just passing a string converted to binary data and expect our decoder to decode it.
Please add following fix to your code:
```
            f = open("/mnt/yunle/byebye/coco28/images/train/0.jpg", 'rb')
            batch.append(np.frombuffer(f.read(), dtype = np.uint8))
```

**Comment by zhiheng-ldj** [comment]
Oh I see. Thanks!

BTW, do you have any idea about passing the path to pipeline directly instead of reading from file?

**Comment by JanuszL** [comment]
You can try [`fromfile`](https://numpy.org/doc/stable/reference/generated/numpy.fromfile.html).
