### ISSUE TITLE
GPU tensors in graph.

### ISSUE THREAD

**Issue by ZinovievVladimir** [NVIDIA/DALI#844]
Hi! This is only question. When I have tensors on cpu in a graph, I can write something like ```tensor.gpu()``` and I'll have them on gpu, but how can I do the same operation but reverse, from gpu to cpu?

**Comment by JanuszL** [comment]
Hi,
Currently DALI is not supporting moving data back from the GPU to the CPU inside the pipeline. However you can transfer the output of the pipeline back from the GPU to CPU using [`as_cpu`](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/api.html#nvidia.dali.backend.TensorListGPU.as_cpu) method on the tensor list.

**Comment by ZinovievVladimir** [comment]
Yes, I understand, but does it mean, that I can't using an output from gpu operators in input of cpu operators in graph? :(

**Comment by JanuszL** [comment]
Hi,
Unfortunately, you cannot. This round trips CPU->GPU->CPU would kill the perf, also current architecture assumes that data flows from the CPU to GPU where you perform your training (data is consumed).

**Comment by ZinovievVladimir** [comment]
@JanuszL Good morning! Can I to normalize image without crop, but have output in NHWC? (any your operation does not fit, i think)

**Comment by ZinovievVladimir** [comment]
I'm sorry, I think, I can use Transpose :)

**Comment by JanuszL** [comment]
Hi,
You could use [NormalizePermute](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html#normalizepermute) to normalize and optionally change layout.

**Comment by ZinovievVladimir** [comment]
@JanuszL How I see in the doc, NormalizePermute can not change output layout :(

**Comment by JanuszL** [comment]
Sorry, I missed that you doesn't want NCHW format. For now please use transpose op at the end.

**Comment by ZinovievVladimir** [comment]
What if using CropMirrorNormalize and choose the NHWC output with crop on full size of image. Is this faster or not?

**Comment by JanuszL** [comment]
*Normalize is mostly the memcopy, with some multiplication and subtraction per sample. Crop can be treated as a ROI. So if you CropMirrorNormalize with the full size crop then it will be better than two ops.

**Comment by ZinovievVladimir** [comment]
@JanuszL Hi! That's me again. Is it possible to use something like ```if``` construction inside DALI graph? For example, I want to do some operation with 0.5 probability.

**Comment by JanuszL** [comment]
Hi,
It is not possible now to do conditional execution in a generic way. DALI graph definition just describes the connection between operators, while the "if" logic needs to be supported inside the operator itself. However some operators (based on displacement core, like [Water](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html#nvidia.dali.ops.Water) or [Flip](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/supported_ops.html#nvidia.dali.ops.Flip) for example) have mask argument allowing you to do what you are asking for, maybe those are one you want to use.
If you, or someone else, is willing to extend support of this functionality to other operators as well we would be more than happy to accept that kind of contribution.

**Comment by ZinovievVladimir** [comment]
Hi! Can you explain me, please, what a difference between SSDRandomCrop and RandomBBoxCrop? How can I understand - SSDRandomCrop is a special case of RandomBBoxCrop with hardcoded parameters. Am I right?

**Comment by JanuszL** [comment]
Hi,
SSDRandomCrop is basically RandomBBoxCrop+Slice. We needed that until we resolved some problems and were able to provide separated ops. We plan to deprecate SSDRandomCrop in some future.
The recommended way is to use RandomBBoxCrop+Slice (as Slice can be scheduled on CPU or GPU while SSDRandomCrop is only CPU op).
