### ISSUE TITLE
ffmpeg cant be linked

### ISSUE THREAD

**Issue by Msabih** [NVIDIA/DALI#861]
Hi,

I compiled ffpmeg as per the instructions and then tried to build DALI, everything works fine except right at the end during linking step.

```
Linking CXX shared library python/nvidia/dali/libdali.so
gcc7/bin/../lib/gcc/x86_64-linux-gnu/7.1.0/../../../libavformat.a(allformats.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
```

and the errors keep coming.  Any clues to how to solve this issue ?

**Comment by Kh4L** [comment]
Hi @Msabih 

This might be the result of another FFmpeg from your system being picked by the linker. It is common to have at least one other FFmpeg already installed by softwares such as VLC or Blender.

You can choose which install of FFmpeg you want to link against by adding `-DFFMPEG_ROOT_DIR=/your/path` to the cmake command.
If you installed DALI following our instructions the path should be `/usr/local`.

**Comment by Msabih** [comment]
Thanks, it works.
