### ISSUE TITLE
How should I crop or slice while decoding images

### ISSUE THREAD

**Issue by Isaver23** [NVIDIA/DALI#870]
Here is the thing: I have lots of raw pictures, which I need to decode from jpg format files, and bboxs for each of those images. What I really need for training is the cropped or sliced  & resized to fixxed size images with such bboxs information. 
So how should I make it properly?

**Comment by ZinovievVladimir** [comment]
Hi, @Isaver23! I think, you need first to read the images, using reader from DALI, which suits you, use RandomBBoxCrop, and then nvJPEGDecoderCrop and Resize.

**Comment by Isaver23** [comment]
Hi, @ZinovievVladimir! Thanks for your reply, and I'm trying with **nvJPEG Decoder with external window size and anchor method**. 

But I noticed that in this example, it just make some fake bboxs with fixed (begin, size) for crop ops. So if I want to use real bboxs information for different images, what should I do for it? 

Thanks again for you reply, which helps me a lot already! 

 ```
import numpy as np

class ExternalInputIterator(object):
    def __init__(self, batch_size):
        self.batch_size = batch_size

    def __iter__(self):
        self.i = 0
        self.n = self.batch_size
        return self

    def __next__(self):
        pos = []
        size = []
        for _ in range(self.batch_size):
            pos.append(np.asarray([0.4, 0.2], dtype=np.float32))
            size.append(np.asarray([0.3, 0.5], dtype=np.float32))
            self.i = (self.i + 1) % self.n
        return (pos, size)

    next = __next__

eii = ExternalInputIterator(batch_size)
pos_size_iter = iter(eii)

class nvJPEGDecoderSlicePipeline(Pipeline):
    def __init__(self, batch_size, num_threads, device_id):
        super(nvJPEGDecoderSlicePipeline, self).__init__(batch_size, num_threads, device_id, seed = seed)

        self.input = ops.FileReader(file_root = image_dir)
        self.input_crop_pos = ops.ExternalSource()
        self.input_crop_size = ops.ExternalSource()
        self.input_crop = ops.ExternalSource()
        self.decode = ops.nvJPEGDecoderSlice(device = 'mixed', output_type = types.RGB)

    def define_graph(self):
        jpegs, labels = self.input()
        self.crop_pos = self.input_crop_pos()
        self.crop_size = self.input_crop_size()
        images = self.decode(jpegs, self.crop_pos, self.crop_size)
        return (images, labels)

    def iter_setup(self):
        (crop_pos, crop_size) = pos_size_iter.next()
        self.feed_input(self.crop_pos, crop_pos)
        self.feed_input(self.crop_size, crop_size)

pipe = nvJPEGDecoderSlicePipeline(batch_size, 1, 0)
pipe.build()
images, _ = pipe.run()
show_images( images.as_cpu() )
 ```

**Comment by ZinovievVladimir** [comment]
@Isaver23 If you want to read BBoxes as external source, I think you need firstly be sure, that BBoxes are matching to images. For example that they are sorted identically. If you sure about that, than you can just use list of BBoxes as an argument of iterator's constructor.

**Comment by ZinovievVladimir** [comment]
@Isaver23 Are you sure, that you can't read BBoxes using DALI functions? For example, COCOReader?

**Comment by Isaver23** [comment]
@ZinovievVladimir Yes, that's what I'm confused of. Of cource I can sort them for rightly matching, but in that way I can't shuffle my datasets for more usage. Maybe I should use the COCOReader and crop after loading data & bboxs, before fit into models.

**Comment by JanuszL** [comment]
Hi,
If your data set is in COCO format please check [this example](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/detection_pipeline.html). Currently there is no way to synchronize the order between readers - so you cannot use FileReader and easily read corresponding bboxes using ExternalSource. Also, you can try to use ExternalSource instead of FileReader, like in [this example](https://docs.nvidia.com/deeplearning/sdk/dali-developer-guide/docs/examples/external_input.html) - it will be slower but more flexible.

**Comment by Isaver23** [comment]
@JanuszL Thanks, I'll try it later!
