### ISSUE TITLE
dali just iterates ones using external source

### ISSUE THREAD

**Issue by Msabih** [NVIDIA/DALI#881]
Hi,

I am using a custom pytorch dataset which is an iterator that is fed to pytorch dataloader. It works fine using pytorch dataloader. To try Dali to see if there is a performance gain, I dont do imread inside the custom dataset and instead load the image into the buffer so that the jpeg decoding can be done on GPU.

I wanted to see if there is a performance gain as I am loading more than 200,000 jpeg images. 

The dali pipeline works loads the correct image but only for one iteration. Any ideas on what could be going wrong.
```
# ds is the torch custom torch dataset iterator that works

iterator = iter(ds)
class ExternalSourcePipeline(Pipeline):
    def __init__(self, batch_size, num_threads, device_id):
        super(ExternalSourcePipeline, self).__init__(batch_size,
                                      num_threads,
                                      device_id,
                                      seed=12)
        self.input = ops.ExternalSource()
        self.decode = ops.nvJPEGDecoder(device = "mixed", output_type = types.RGB)
        self.cast = ops.Cast(device = "gpu",
                             dtype = types.INT32)
        self.i = 0

    def define_graph(self):
        self.jpegs = self.input()
        images = self.decode(self.jpegs)
        output = self.cast(images)
        return output

    def iter_setup(self):
        batch = ds[self.i]
        self.i += 1
        images = batch['images']
        self.feed_input(self.jpegs, images)

pipe = ExternalSourcePipeline(batch_size=1, num_threads=2, device_id = 0)
pipe.build()
pipe_out = pipe.run()

train_loader = DALIGenericIterator(pipelines = pipe,
                                   size=1,output_map = ['images'])
for idx, batch in enumerate(train_loader):
    print(batch[0]["images"].size())
    print('idx ', idx)

```

**Comment by JanuszL** [comment]
Hi,
Have you checked if `images` inside `iter_setup` are properly loaded from the `ds`?
Could you provide self contained script that is causing problems, the easier it is for us to run and reproduce the better.

**Comment by Msabih** [comment]
> Hi,
> Have you checked if `images` inside `iter_setup` are properly loaded from the `ds`?
> Could you provide self contained script that is causing problems, the easier it is for us to run and reproduce the better.

The problem with providing a self-contained script is that the loader is loading a big dataset. However I could provide the custom dataset code.

>  __getitem__

 of 

> ds

.


```
path = os.path.join(self.dataset_path, img_name)
f = open(path, 'rb')
image = np.frombuffer(f.read(), dtype = np.uint8)
return {'images': [image]}
```

another point is that iterating over 

> ds

gives me the correct amount of iterations. If I print

> images 
inside 
> iter_setup

I get a list numpy arrays as expected. The only problem is that train_loader only iterates once..

**Comment by JanuszL** [comment]
You can disregard exact source of the data set - the python code is important. Without that it is hard to say more.

**Comment by JanuszL** [comment]
I have created some simple example that works for me:
```
from torch.utils import data
import nvidia.dali.ops as ops
import nvidia.dali.types as types
from nvidia.dali.pipeline import Pipeline
import numpy as np
import os
import scipy.misc

class InputDataset(data.Dataset):
    def __init__(self, batch_size, image_dir):
        self.images_dir = image_dir
        self.batch_size = batch_size
        self.files_labels = []
        image_dir = os.path.normpath(image_dir)
        label_i = 0
        classes = []
        for r, d, f in os.walk(image_dir):
            if r == image_dir:
                classes = d
            if os.path.dirname(r) == image_dir:
                f = sorted(f)
                path_f = [os.path.join(r, name) for name in f if "jpg" in name]
                self.files_labels += zip(path_f, len(f) * [label_i])
                label_i += 1

    def __len__(self):
        return len(self.files_labels)

    def __getitem__(self, index):
        jpeg_filename = self.files_labels[index][0]
        label = self.files_labels[index][1]
        f = open(jpeg_filename, 'rb')
        image = np.frombuffer(f.read(), dtype = np.uint8)
        label = np.array([label], dtype = np.uint8)
        return image, label

batch_size = 16
# you can use https://github.com/NVIDIA/DALI_extra
image_dir = '......DALI_extra/db/single/jpeg/'
dataset = InputDataset(batch_size=batch_size, image_dir=image_dir)

def collate_fn(batch):
    images = [item[0] for item in batch]
    labels = [item[1] for item in batch]
    return images, labels

dataset_loader = data.DataLoader(dataset, batch_size=batch_size, shuffle=False, num_workers=4, pin_memory=False, collate_fn=collate_fn, drop_last=True)

class ExternalSourcePipeline(Pipeline):
    def __init__(self, source, batch_size, num_threads, device_id):
        super(ExternalSourcePipeline, self).__init__(batch_size,
                                      num_threads,
                                      device_id,
                                      seed=12)
        self.source = source
        self.source_iter = iter(source)
        self.input = ops.ExternalSource()
        self.input_label = ops.ExternalSource()
        self.decode = ops.nvJPEGDecoder(device = "mixed", output_type = types.RGB)
        self.res = ops.Resize(device="gpu", resize_x=224, resize_y=224, interp_type=types.INTERP_TRIANGULAR)

    def define_graph(self):
        self.jpegs = self.input()
        self.labels = self.input_label()
        images = self.decode(self.jpegs)
        images = self.res(images)
        return (images, self.labels)

    def iter_setup(self):
        print "run"
        try:
          p = self.source_iter.next()
        except:
          print("Exception occured")
          self.source_iter = iter(self.source)
          p = self.source_iter.next()
        images, labels = p
        print len(labels)
        print labels
        self.feed_input(self.jpegs, images)
        self.feed_input(self.labels, labels)

pipe = ExternalSourcePipeline(source=dataset_loader, batch_size=batch_size, num_threads=4, device_id=0)
pipe.build()

for epoch in range(2):
  for i in range(len(dataset) // batch_size):
    images, labels = pipe.run()
    images = images.as_cpu().as_array()
    for j in range(len(images)):
        scipy.misc.imsave('outfile-{}-{}-{}.jpg'.format(epoch, i, j), images[j])
```

**Comment by Msabih** [comment]
@JanuszL Thanks a lot, actually I got it to work by commenting the following part of the code and using manual stopping of iteration.

In this file
https://github.com/NVIDIA/DALI/blob/master/dali/python/nvidia/dali/plugin/pytorch.py
```
        if self._counter >= self._size:
            if self._auto_reset:
                self.reset()
raise StopIteration
```

I am investigating what could I have done wrong for this to work this way.

**Comment by JanuszL** [comment]
Hi,
I'm glad you make it work. 
Now I see where you made a mistake:
```
train_loader = DALIGenericIterator(pipelines = pipe,
                                   size=1,output_map = ['images'])
```
`size` should be actual data size (200 000 in your case, I guess). Lines you commented out are to provide the same behavior as DataLoader - when you are done with your data set then your DALIGenericIterator will tell you about that.

**Comment by Msabih** [comment]
> Hi,
> I'm glad you make it work.
> Now I see where you made a mistake:
> 
> ```
> train_loader = DALIGenericIterator(pipelines = pipe,
>                                    size=1,output_map = ['images'])
> ```
> 
> `size` should be actual data size (200 000 in your case, I guess). Lines you commented out are to provide the same behavior as DataLoader - when you are done with your data set then your DALIGenericIterator will tell you about that.

I was definitely wondering about this size argument but the the documentation states Epoch Size. So I mixed it with number of epochs..... I think this could be elaborated in a line further.

Thank you for the help.

**Comment by JanuszL** [comment]
I think you can easily check `self._counter` and `self._size` values to figure out why it prematurely stops.

**Comment by JanuszL** [comment]
You can also check https://github.com/NVIDIA/DALI/pull/1136.
If DALI still doesn't work please reopen.
