### ISSUE TITLE
build error: 'JCS_EXT_BGR' was not declared in this scope 

### ISSUE THREAD

**Issue by Msabih** [NVIDIA/DALI#884]
Hi,

I built dali on cuda 10.1 and I am getting this error

dali/dali/image/jpeg_mem.cc:135:9: error: 'JCS_EXT_BGR' was not declared in this scope 

and the compiler suggests alternative 

/dali/dali/image/jpeg_mem.cc:135:9: note: suggested alternative: 'JCS_BG_RGB'  

With this alternative, the build succeeds although i have no idea if that will effect the code.

**Comment by JanuszL** [comment]
Hi,
As far as I see `JCS_BG_RGB` is defined by libjpeg while `JCS_EXT_BGR` by libjpeg-turbo.
DALI is mean to use libjpeg-turbo, but it still may work with libjpeg (still we haven't tested it). Please install libjpeg-turbo.
Have you tried [Docker based build](https://github.com/NVIDIA/DALI#compiling-dali-from-source-using-docker-builder---recommended) which sets all dependency as we recommend?

**Comment by Msabih** [comment]
@JanuszL  I figured out that the problem was that dali's cmake was picking up the libffmpeg from /usr/lib whereas I had installed my libffmeg in anaconda. So I had to manually give the flags to CMAKE. Might be useful to mention some of these flags because for a person using anaconda, these are useful.

-DJPEG_INCLUDE_DIR
and 
-DJPEG_LIBRARY
and 
-DFFMPEG_ROOT_DIR

**Comment by JanuszL** [comment]
Hi,
I think it would be not that easy to list all CMake variable. JPEG_INCLUDE_DIR and JPEG_LIBRARY are documented in CMake itself https://cmake.org/cmake/help/v3.0/module/FindJPEG.html. I added some of them in https://github.com/NVIDIA/DALI/pull/889. If you think I have missed something, feel free to issue and PR with the relevant info.
We would be more than happy to see the external contribution that would help other users of our library.
