### ISSUE TITLE
Questions/Potential Improvements for ExternalSource

### ISSUE THREAD

**Issue by Msabih** [NVIDIA/DALI#888]
Hi,

Dali has speed up my training by a factor of 8-10 which is quite nice. My use case is as follows. I have one label image for 10 frames. I came across a number of potential improvements/questions which are as follows.

1) Different label length as compared to image.

 Using dali's ExternalSourcePipeline and feed_input after reading examples, I am able to feed images and labels. However, the code only works if I duplicated the label by a factor of 10 to make the length of labels equal to the total number of frames. Because dali expects both images and labels to have same lengths.

2) Output names of images.

dali expects list of np.ndarray, however it is useful to output the names of the images, currently, I am doing a hacky workaround of converting string to np.ndarray and back.

3) Initial run when building pipeline.

When I build pipeline, two iterations are automatically run while building, is there a way to start the iterator from the beginning.

In case, any of the point is not clear then I will post the code-snippets to explain them.

**Comment by JanuszL** [comment]
Hi,

1) This is the most commonly done assumption - that every sample in the batch has the corresponding label. In your case you are working with sequences - it is not fully supported in all operators yet so your workaround is the only way for the external source.
2) It is a good point. Adding support for a string data type in DALI is not that straight forward, but still, it should be doable.
3) You should not worry about this. These initial runs are to fill DALI prefetch buffer. The fact they are executed during the build means that samples would be ready to obtain as soon as you start iterating. Don't worry, they are not lost.
