### ISSUE TITLE
Data loading speed vs overall training speedup

### ISSUE THREAD

**Issue by Msabih** [NVIDIA/DALI#892]
I have a dataset consisting of around 200,000 images. I am able to get 10 times speedup on loading data as compared to pytorch's data loader but when I do training, the speedup is no longer significant.

Does it mean that most of processing time is spent on training model weights and therefore speeding up loading is not significant ?

Or could there be some parameters that I could still play with.

**Comment by JanuszL** [comment]
Hi,
The first sanity check would be to run `nvidia-smi` during the training and check the GPU utilization. So if it is ~80% then you probably training bound and speed of data processing doesn't matter.
Another thing is that you can try to use synthetic data - just dummy tensor as the input for your training (create zero tensor with required size and reuse it for a couple of epochs). If the speed it almost the same then again you are not data processing bound.

**Comment by Msabih** [comment]
@JanuszL Thanks, thats very helpful.
