### ISSUE TITLE
The way to convert FileReader imported images/labels to normal numpy array

### ISSUE THREAD

**Issue by oscarriddle** [NVIDIA/DALI#9]
Python 2.7
Tensorflow 1.7
CentOS 7
CUDA 9.2
cuDNN 7.0.5
Installed DALI from pip

I'm trying to use DALI to do the image preprocessing and then use tensorflow do the prediction.
In my understand, DALI shall be able to return an numpy array format of images and labels.
After checking the tutorial gettingstarted and TensorFlow-ResNet50, I'm a little confused about the format.

This phrase mentioned that:
```
# As it turns out, `TensorList` containing labels can be represented by a tensor, while the `TensorList` containing images cannot.                             
#                                                                                                                                                              
# Let us see, what is the shape and contents of returned labels.                                                                                               

# In[7]:                                                                                                                                                       


import numpy as np

labels_tensor = labels.as_tensor()

print (labels_tensor.shape())
print (np.array(labels_tensor))
```

I tried this way, here is the code and print out.
```
test_pipe = IncepV3Pipeline(batch_size=BATCH_SIZE, num_threads=2, device_id = 0, num_gpus = DEVICES)
test_pipe.build()
test_pipe_out = test_pipe.run()
print('<>',test_pipe_out)
ims, las = test_pipe_out
print("Images is_dense_tensor: " + str(ims.is_dense_tensor()))
print("Labels is_dense_tensor: " + str(las.is_dense_tensor()))
las_tensor = las.as_tensor()
print('<>',las_tensor.shape())
print('<>',np.array(las_tensor))
```
```
('<>', [<nvidia.dali.backend_impl.TensorListGPU object at 0x7f6d350f8768>, <nvidia.dali.backend_impl.TensorListGPU object at 0x7f6d350f87a0>])
Images is_dense_tensor: True
Labels is_dense_tensor: True
('<>', [16L, 1L])
('<>', array(<nvidia.dali.backend_impl.TensorGPU object at 0x7f6d350f87d8>,
      dtype=object))
```

Since I want to use TF frozen graph for inference, just simply getting numpy array format of images and labels from DALI pipes would be very useful. 

Any idea will be welcome.

**Comment by ptrendx** [comment]
Problem with what you are trying to do is that NumPy arrays reside on the CPU and the result of your DALI pipeline is on the GPU, so, especially if your inference with a frozen graph is being done on the GPU as well, going through NumPy would mean GPU->CPU->GPU round trip of data. I don't think that would make much sense from the performance perspective, but if you want to try you can insert `asCPU()` here:
```
las_tensor = las.asCPU().as_tensor()
```

The other, better, solution would be to make a TensorFlow graph using the TF plugin that would take the pipeline and output TF tensors with you images and the wiring this output as the input of the frozen TF graph that you want to do inference with. I'm not an expert in TF though, so I can not help you with how exactly you could do that wiring.

**Comment by oscarriddle** [comment]
Hi @ptrendx ,
Thanks for your reply.

Looks like TF plugin would be the best method for avoiding memcpy between host and devices. 
But the Tensorflow frozen model may not be able to append tensors anymore, so wiring TF plugin and frozen model may not work.

The main reason why I'm interested in frozen model is that the new NVIDIA TensorRT version appears to be good on INT8 mode accuracy and throughput over GoogLeNet, and TFTRT can only work on frozen model.

So here comes a trade-off, I want to evaluate the performance by utilizing DALI and TensorRT at the same time, maybe I should give a shot of memcpy.

Thanks,

**Comment by cliffwoolley** [comment]
@benbarsdell @jjsjann123 -- let's think about how we can best wire together TFTRT and DALI.

**Comment by oscarriddle** [comment]
Hi,

I tried to copy images from gpu to cpu and change it to numpy array but failed. (Segmentation fault (core dumped))

Code:
```
ims, las = test_pipe_out
print("Images is_dense_tensor: " + str(ims.is_dense_tensor()))
print("Labels is_dense_tensor: " + str(las.is_dense_tensor()))
las_tensor = las.asCPU().as_tensor()
print('<>',las_tensor.shape())
print('<>',np.array(las_tensor))
ims_tensor = ims.asCPU().as_tensor()
print('<>',ims_tensor.shape())
im_np=np.array(ims_tensor)
print(im_np)
```

Output:
```
Images is_dense_tensor: True
Labels is_dense_tensor: True
('<>', [16L, 1L])
('<>', array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]], dtype=int32))
('<>', [16L, 3L, 299L, 299L])
Segmentation fault (core dumped)

```

**Comment by cliffwoolley** [comment]
@oscarriddle - Can you please provide a complete reproducer of the segfault you see here?

**Comment by oscarriddle** [comment]
Hi @cliffwoolley , 
It seems the core info log is not actually been dumped, so I'm not able to find further clue for this issue now.

**Comment by cliffwoolley** [comment]
@oscarriddle -- you can set `ulimit -c unlimited` to get the core file normally.  Unless you are running inside a container?  In which case you need to set some additional options on `nvidia-docker run`... just let me know.

I suggest we keep this issue for isolating the segfault and then https://github.com/NVIDIA/DALI/issues/17 can track providing better examples of using DALI/TF-TRT together.

**Comment by oscarriddle** [comment]
Unfortunately, I don't have the ulimit and the root to install it...
My OS is CentOS 7.0, gcc 5.3, python 2.7. 
Would you test it on your system and see whether it will segfault?

Thanks

**Comment by JanuszL** [comment]
Hi,
Could you provide us minimal standalone test case which causes segfault in your system?

**Comment by JanuszL** [comment]
Tracked internally in DALI-147

**Comment by JanuszL** [comment]
I think I got clue what is wrong, when you call `ims.asCPU().as_tensor()`, `asCPU()` creates `TensorList` which internal buffer is shared with Tensor produced as a result of `as_tensor()` call. Tensor list is not referenced anywhere in python code and is GC as intermediate result what in effects free shared buffer, so when np tries to access that memory you get crash.
For now try:

    ims_tensor_CPU = ims.asCPU()
    ims_tensor = ims_tensor_CPU.as_tensor()
So `ims_tensor_CPU` keep internal buffer valid.

**Comment by ptrendx** [comment]
@JanuszL That is a bug then, it should understand that it needs to keep the thing alive.

**Comment by JanuszL** [comment]
Fix has been merged. If you can/want please check it it works for you with current master. This fix will be included in next release.
