### ISSUE TITLE
error while importing DALI in TF 1.13.1

### ISSUE THREAD

**Issue by dheerajsreedhar** [NVIDIA/DALI#937]
I get this error while importing dali tensorflow plugin

>>> import nvidia.dali.plugin.tf as dali_tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dhsreedh/ds/local/lib/python2.7/site-packages/nvidia/dali/plugin/tf.py", line 35, in <module>
    raise Exception('No matching DALI plugin found for installed TensorFlow version')
Exception: No matching DALI plugin found for installed TensorFlow version

When I try to load the plugin directly I get:
>>> tf.load_op_library("./dali/python/nvidia/dali/plugin/libdali_tf.so")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dhsreedh/ds/local/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: ./dali/python/nvidia/dali/plugin/libdali_tf.so: undefined symbol: _ZN10tensorflow14DataTypeStringENS_8DataTypeE

I am using TF 1.13.1 and CUDA 10.0

There is another closed issue #318 . I tried building DALI with --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" in cmake. It did not help.

**Comment by JanuszL** [comment]
Hi,
A couple of questions from our side:
- which version of DALI do you use?
 - have you build DALI on your own? If so have you checked BUILD_TENSORFLOW as ON in CMake `-DBUILD_TENSORFLOW=ON`?
- if you use prebuild try to force reinstall nvidia-dali-tf-plugin.
- have you using prebuild TF or you have build it on your own?

**Comment by dheerajsreedhar** [comment]
- which version of DALI do you use?
     -> This is the master branch cloned today (May 31)
- have you build DALI on your own? If so have you checked BUILD_TENSORFLOW as ON in CMake -DBUILD_TENSORFLOW=ON?
     -> it is my own build of DALI. BUILD_TENSORFLOW is set to ON and the build was successful.  
 - have you using prebuild TF or you have build it on your own?
     -> It is my own TF build and it works well.

**Comment by JanuszL** [comment]
According to https://www.tensorflow.org/install/source#bazel_build_options this `--cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0"` should be added to tensorflow build options.

**Comment by dheerajsreedhar** [comment]
I did not add that in my tensorflow build options. After adding, it works fine. Closing this.

Thank you very much.

**Comment by JanuszL** [comment]
:+1:
