### ISSUE TITLE
VideoReader specify sequence start frames

### ISSUE THREAD

**Issue by Feri73** [NVIDIA/DALI#940]
Hi,

It would be useful if I could specify a set of valid start frames for the frame sequences extracted using VideoReader. I guess currently it is not supported.

Thanks

**Comment by JanuszL** [comment]
Hi,
How do you want to have this applied? List of first and last valid frame per each file is enough, or you would like to provide better granularity (like any number of [first, last] valid frame for given file)? How it should work with the step and stride parameters?

**Comment by Feri73** [comment]
In my specific application I need the more granular version (basically I need to have multiple "train" and "validation" periods for each video and that's why I need this feature). Therefore this is what I had in mind:
`reader = VideoReader(filenames=['a.mp4','b.mp4'], valid_start_frames=[[(0, 100), (150, 250)], [(10, 200)]], ...)`
I guess this feature does not affect how stride or step work because it is essentially equal to considering each video as multiple clips (created from provided valid_start_frames) and extracting sequences from those "valid clips".

**Comment by JanuszL** [comment]
@Feri73 - sounds like a good functionality. Added to the backlog as DALI-870.

**Comment by cinjon** [comment]
(I would also like this)

**Comment by JanuszL** [comment]
Can you check how https://github.com/NVIDIA/DALI/pull/1500 works for you with the latest nightly build?

**Comment by cinjon** [comment]
This probably is sufficient. I apologize but I ended up using a different approach/reader for the research.

**Comment by JanuszL** [comment]
Sure. No problem.
