### ISSUE TITLE
COCO classes numerating

### ISSUE THREAD

**Issue by ZinovievVladimir** [NVIDIA/DALI#943]
Hi!

When your COCOReader reading classes ids, it's reading them like [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], but in dataset it can be [11, 20, 24, 41, 46, 47, 48, 59, 60, 61]. Is it a bug or something other?

**Comment by JanuszL** [comment]
Hi,
It is intended. We are skipping empty categories in the [COCO data set](https://github.com/NVIDIA/DALI/blob/master/dali/pipeline/operators/reader/loader/coco_loader.cc#L315). Now it is hard-coded but we want to make it an argument that user can provide (automatic trimming or explicit mapping list).
