### ISSUE TITLE
Support Keypoint augmentation

### ISSUE THREAD

**Issue by ghop02** [NVIDIA/DALI#955]
Would be great to be able to use Dali with keypoint annotations in the COCO dataset!

Was disappointed to have to use imageaug to train our pose models.

**Comment by JanuszL** [comment]
Hi,
We have been focused on using COCO for the SSD network. Still it sounds like a sane request.
I think this is a good place where we would love to see some external contribution. Tracked as DALI-887.

**Comment by JanuszL** [comment]
Hi @ghop02,

I think [this example](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/math/geometric_transforms.html) should show how to do that now with the most recent DALI version.
