### ISSUE TITLE
 cmake/modules/FindJpegTurbo.cmake:22 (pkg_check_modules)

### ISSUE THREAD

**Issue by wangguangyuan** [NVIDIA/DALI#96]
1、I have compiled libjpeg-turbo-1.5.9 and installed it at /home/guangyuan/install/libjpeg_turbo_1.5.9, but the import was not successful.
2、If I debug libjpeg-turbo when compiling dali from source code, after compiling successfully, does it affect the running speed? Or can it run normally?

[dali build]$ cmake -DNVJPEG_ROOT_DIR=/home/guangyuan/install/cuda-linux64-nvjpeg -DJPEG_TURBO_ROOT_DIR=/home/guangyuan/install/libjpeg_turbo_1.5.9 ..
-- DALI version: 0.3.0
-- git Version: v0.2.0-24297324-dirty
-- Version: 0.2.0
-- Performing Test HAVE_STD_REGEX
-- Performing Test HAVE_STD_REGEX
-- Performing Test HAVE_STD_REGEX -- compiled but failed to run
-- Performing Test HAVE_GNU_POSIX_REGEX
-- Performing Test HAVE_GNU_POSIX_REGEX
-- Performing Test HAVE_GNU_POSIX_REGEX -- failed to compile
-- Performing Test HAVE_POSIX_REGEX
-- Performing Test HAVE_POSIX_REGEX
-- Performing Test HAVE_POSIX_REGEX -- success
-- Performing Test HAVE_STEADY_CLOCK
-- Performing Test HAVE_STEADY_CLOCK
-- Performing Test HAVE_STEADY_CLOCK -- success
-- jpeg_root_dir:/home/guangyuan/install/libjpeg_turbo_1.5.9
-- pkgcong:
-- JpefTurbo:
CMake Error at /usr/local/cmake-3.8.2/share/cmake-3.8/Modules/FindPkgConfig.cmake:416 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/local/cmake-3.8.2/share/cmake-3.8/Modules/FindPkgConfig.cmake:589 (_pkg_check_modules_internal)
  cmake/modules/FindJpegTurbo.cmake:22 (pkg_check_modules)
  cmake/Dependencies.cmake:86 (find_package)
  CMakeLists.txt:43 (include)

-- Configuring incomplete, errors occurred!
See also "/home/guangyuan/dali/build/CMakeFiles/CMakeOutput.log".
See also "/home/guangyuan/dali/build/CMakeFiles/CMakeError.log".

**Comment by JanuszL** [comment]
Hi,
It is definitely a but. Tracked internally DALI-193.
As a temporal solution please comment out:

    find_package(PkgConfig QUIET)
    if (PkgConfig_FOUND)
        # use pkg-config only if it has been found
        pkg_check_modules(JpegTurbo REQUIRED QUIET libturbojpeg)
    endif()
From FindJpegTurbo.cmake file.

**Comment by wangguangyuan** [comment]
At the same time, I have to remove JpegTurbo. I want to ask if this should have no effect on compiling dali.
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(JpegTurbo
    REQUIRED_VARS JpegTurbo_INCLUDE_DIR JpegTurbo_LIBRARY
    VERSION_VAR JpegTurbo_VERSION)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(
    REQUIRED_VARS JpegTurbo_INCLUDE_DIR JpegTurbo_LIBRARY
    VERSION_VAR JpegTurbo_VERSION)

**Comment by JanuszL** [comment]
If you want to skip JpegTurbo you could set BUILD_JPEG_TURBO to off.

    cmake (...) -DBUILD_JPEG_TURBO=OFF

**Comment by wangguangyuan** [comment]
@JanuszL  
If you want to skip JpegTurbo you could set BUILD_JPEG_TURBO to off.  
Will not affect the speed of dali, such as slowing down the decoding speed?

**Comment by JanuszL** [comment]
Hi,
You are right, it will slow down a bit if you use host decoder. If you are using nvJpeg there should be no difference.
So to solve your problem:
- if you want skip JPEG_TURBO use -DBUILD_JPEG_TURBO=OFF
- you can comment out pkg_config stuff as I wrote
- you can try out my PR https://github.com/NVIDIA/DALI/pull/98
