### ISSUE TITLE
How to perform a relative scaling augmentation?

### ISSUE THREAD

**Issue by Noiredd** [NVIDIA/DALI#969]
I'm building a custom segmentation pipeline, meant to work with different datasets of different sizes, as well as producing images of different sizes. On some stage of the data augmentation, I want to make my objects more variable in size, which I want to do by scaling them by a random *factor*. I tried the obvious choice, `dali.ops.Resize`, and found that it expects me to know absolute pixel values for the resulting image. However, I don't know them (can't compute them), because at the time of building the pipeline I don't know the input size. I tried to `dir` an `EdgeReference` but it doesn't seem to contain any of that information.

So, the question is, can I (1) go around that somehow, and maybe combine other operators to achieve a relative scaling without knowing the exact size, or (2) obtain the image shape information within a pipeline's runtime? Or is it something that has to be more or less hard-coded for each dataset?

**Comment by JanuszL** [comment]
Hi,
Currently, as you noticed, resize supports only absolute coordinates. However, it should not be that difficult to extend it with a switch that allows you to provide relative one, in the range [0,1] (check [this](https://github.com/NVIDIA/DALI/blob/master/dali/pipeline/operators/fused/resize_crop_mirror.h#L43) and [this](https://github.com/NVIDIA/DALI/blob/master/dali/pipeline/operators/fused/resize_crop_mirror.h#L65)).
This sounds like a good place for external contribution.

**Comment by JanuszL** [comment]
Hi,
You can use [the `peek_image_shape` operator](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.peek_image_shape) or just [`shapes`](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#nvidia.dali.fn.shapes) to get the image shape, then divide the shape by [a random](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/supported_ops.html#module-nvidia.dali.fn.random) factor and feed to the resize operator.
