### ISSUE TITLE
fatal error: tensorflow/core/framework/op_kernel.h: No such file or directory

### ISSUE THREAD

**Issue by wangguangyuan** [NVIDIA/DALI#99]
Set BUILD_TENSORFLOW to ON error.

[ 83%] Building CXX object dali/CMakeFiles/dali.dir/util/local_file.cc.o
[ 86%] Building CXX object dali/CMakeFiles/dali.dir/util/npp.cc.o
[ 86%] Building CXX object dali/CMakeFiles/dali.dir/util/nvml_wrap.cc.o
[ 89%] Building CXX object dali/CMakeFiles/dali.dir/util/ocv.cc.o
make[2]: Warning: File `dali/CMakeFiles/dali.dir/pipeline/operators/color/dali_generated_color_twist.cu.o' has modification time 20 s in the future
[ 89%] Building CXX object dali/CMakeFiles/dali.dir/error_handling.cc.o
[ 89%] Building CXX object dali/CMakeFiles/dali.dir/util/user_stream.cc.o
[ 89%] Building CXX object dali/CMakeFiles/dali.dir/common.cc.o
[ 89%] Building CXX object dali/CMakeFiles/dali.dir/c_api/c_api.cc.o
[ 90%] Linking CXX shared library libdali.so
make[2]: warning:  Clock skew detected.  Your build may be incomplete.
[ 90%] Built target dali
Scanning dependencies of target dali_tf
Scanning dependencies of target dali_benchmark.bin
make[2]: Warning: File `dali/libdali.so' has modification time 32 s in the future
[ 91%] Building CXX object dali/CMakeFiles/dali_tf.dir/tensorflow/daliop.cc.o
/home/guangyuan/dali/dali/tensorflow/daliop.cc:17:49: fatal error: tensorflow/core/framework/op_kernel.h: No such file or directory
 #include "tensorflow/core/framework/op_kernel.h"
                                                 ^
compilation terminated.
make[2]: Warning: File `dali/libdali.so' has modification time 32 s in the future
[ 96%] Building CXX object dali/CMakeFiles/dali_benchmark.bin.dir/benchmark/dali_bench.cc.o
[ 96%] Building CXX object dali/CMakeFiles/dali_benchmark.bin.dir/benchmark/resnet50_nvjpeg_bench.cc.o
[ 96%] Building CXX object dali/CMakeFiles/dali_benchmark.bin.dir/benchmark/resnet50_bench.cc.o
make[2]: *** [dali/CMakeFiles/dali_tf.dir/tensorflow/daliop.cc.o] Error 1
make[1]: *** [dali/CMakeFiles/dali_tf.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 96%] Building CXX object dali/CMakeFiles/dali_benchmark.bin.dir/benchmark/decoder_bench.cc.o
[ 96%] Building CXX object dali/CMakeFiles/dali_benchmark.bin.dir/benchmark/file_reader_alexnet_bench.cc.o
[ 97%] Linking CXX executable python/nvidia/dali/test/dali_benchmark.bin
make[2]: warning:  Clock skew detected.  Your build may be incomplete.
[ 97%] Built target dali_benchmark.bin
make: *** [all] Error 2

**Comment by JanuszL** [comment]
Hi,
Please make sure you have appropriate version of tensorflow installed. Also run:

    python -c "from __future__ import print_function; import sys; paths = sys.path; f = [p for p in paths if \"-packages\" in p] ; print(f[0], end=\"\")"
And see if resulting drectory you have tensorflow available.

**Comment by JanuszL** [comment]
If you have right TF version installed and somehow command I provided you returns wrong results please reopen.

**Comment by Zhaojp-Frank** [comment]
I hit same issue, 
Env: TensorFlow1.8 build from source code, Ubuntu16.04, CUDA9.0, cuDNN7, DALI checkout yesterday from master branch.
TF1.8 installed to python3.5

there're some header files in python3.5/dis-packages/tensorflow/core/framework, however, op_kernel.h is missing. 

If I copied the missing file from TF1.8 src code, more files missing; such as third_party/eigen3/unsupported/Eigen/CXX11/Tensor.

Any special setting required when building Tensorflow? or additional set required to specify TF headers? thanks.

**Comment by JanuszL** [comment]
Internally tracked DALI-196

**Comment by JanuszL** [comment]
Hi,
We are using prebuild TensorFlow whl provided by google. In all of them I see that dist-packages/tensorflow/include/tensorflow/core/framework/op_kernel.h is present.
Please make sure you are building TF with the same options as google does.

**Comment by Zhaojp-Frank** [comment]
thanks a lot, when your pointed out the full path of dist_package, I notice there're two similar path in dist-packages, and I use the wrong one. 
/usr/local/lib/python3.5/dist-packages/tensorflow/include/tensorflow/core/framework/ <- should use this one when build DALI
/usr/local/lib/python3.5/dist-packages/tensorflow/core/framework/ <-- not this dir

now it passes the op_kernel.h missing issue. 
thanks. pls close the issue.

**Comment by prashant030591** [comment]
The issue can also come if one is compiling custom tf_ops through bash file and does not include the file path for the tensorflow files : /usr/local/lib/python3.5/dist-packages/tensorflow/include/tensorflow/core/framework

So below are the path that are generally reuquired for tensorflow ops to compile:

-I /usr/local/lib/python3.5/dist-packages/tensorflow/include -I /usr/local/cuda-10.0/include -I /usr/local/lib/python3.5/dist-packages/tensorflow/include/external/nsync/public -lcudart -L /usr/local/cuda-10.0/lib64/ -L/usr/local/lib/python3.5/dist-packages/tensorflow
